FEAT: FEAT::Analytic::Common::ParProfileScalar< DataType_ > Class Template Reference
FEAT::Analytic::Common::ParProfileScalar< DataType_ > Class Template Reference
2D Scalar Parabolic Profile function
#include <common.hpp>
Classes
class Evaluator
Public Types
typedef Analytic::Image::Scalar ImageType
Public Member Functions
bool parse (const String &sbc)
Parses the profile parameters from a string.
Static Public Attributes
static constexpr bool can_grad = true
static constexpr bool can_hess = true
static constexpr bool can_value = true
static constexpr int domain_dim = 2
Protected Attributes
DataType_ _vmax
DataType_ _x0
DataType_ _x1
DataType_ _y0
DataType_ _y1
Detailed Description
template<typename DataType_>
class FEAT::Analytic::Common::ParProfileScalar< DataType_ >
2D Scalar Parabolic Profile function
This class represents a scalar parabolic profile along a 2D line segment, which is given by the coordinates (x_0, y_0) and (x_1, y_1).
Author
Peter Zajac
Definition at line 2137 of file common.hpp.
Member Typedef Documentation
ImageType
template<typename DataType_ > typedef Analytic::Image::Scalar FEAT::Analytic::Common::ParProfileScalar< DataType_ >::ImageType
Definition at line 2142 of file common.hpp.
Member Function Documentation
parse()
template<typename DataType_ > bool FEAT::Analytic::Common::ParProfileBase< DataType_ >::parse (const String & sbc) inline inherited
Parses the profile parameters from a string.
This function can be used to parse the configuration for the parabolic profile from a string, which may e.g. be read from the command line or a text file.
The supported syntax for the string is
\[(x_0 y_0 , x_1 y_1)\]
or
\[(x_0 y_0 , x_1 y_1 , v_{max})\]
Parameters
[in] sbc The string to be parsed.
Returns
true, if the string was parsed successfully, otherwise false.
Definition at line 2100 of file common.hpp.
References FEAT::Analytic::Common::ParProfileBase< DataType_ >::parse(), and FEAT::String::split_by_string().
Referenced by FEAT::Analytic::Common::ParProfileBase< DataType_ >::parse().
Member Data Documentation
_vmax
template<typename DataType_ > DataType_ FEAT::Analytic::Common::ParProfileBase< DataType_ >::_vmax protected inherited
Definition at line 2052 of file common.hpp.
_x0
template<typename DataType_ > DataType_ FEAT::Analytic::Common::ParProfileBase< DataType_ >::_x0 protected inherited
Definition at line 2050 of file common.hpp.
_x1
template<typename DataType_ > DataType_ FEAT::Analytic::Common::ParProfileBase< DataType_ >::_x1 protected inherited
Definition at line 2050 of file common.hpp.
_y0
template<typename DataType_ > DataType_ FEAT::Analytic::Common::ParProfileBase< DataType_ >::_y0 protected inherited
Definition at line 2050 of file common.hpp.
_y1
template<typename DataType_ > DataType_ FEAT::Analytic::Common::ParProfileBase< DataType_ >::_y1 protected inherited
Definition at line 2050 of file common.hpp.
can_grad
template<typename DataType_ > constexpr bool FEAT::Analytic::Common::ParProfileScalar< DataType_ >::can_grad = true static constexpr
Definition at line 2144 of file common.hpp.
can_hess
template<typename DataType_ > constexpr bool FEAT::Analytic::Common::ParProfileScalar< DataType_ >::can_hess = true static constexpr
Definition at line 2145 of file common.hpp.
can_value
template<typename DataType_ > constexpr bool FEAT::Analytic::Common::ParProfileScalar< DataType_ >::can_value = true static constexpr
Definition at line 2143 of file common.hpp.
domain_dim
template<typename DataType_ > constexpr int FEAT::Analytic::Common::ParProfileScalar< DataType_ >::domain_dim = 2 static constexpr
Definition at line 2141 of file common.hpp.
The documentation for this class was generated from the following file:
kernel/analytic/common.hpp