FEAT: FEAT::Adjacency::Graph Class Reference
FEAT::Adjacency::Graph Class Reference
Adjacency Graph implementation.
#include <graph.hpp>
Public Types
typedef IndexVector::const_iterator ImageIterator
ImageIterator for Graph class.
using IndexVector = std::vector< Index >
Public Member Functions
Graph ()
Default constructor.
Graph (const Graph &other, const Permutation &domain_perm, const Permutation &image_perm)
"Permutation" copy CTOR
Graph (const std::vector< char > &buffer)
Deserialization CTOR.
Graph (Graph &&other)
move CTOR
Graph (Index num_nodes_domain, Index num_nodes_image, Index num_indices_image)
Allocation Constructor.
Graph (Index num_nodes_domain, Index num_nodes_image, Index num_indices_image, const Index *domain_ptr, const Index *image_idx)
"Copy-Arrays" Constructor
Graph (Index num_nodes_image, const IndexVector &domain_ptr, const IndexVector &image_idx)
"Copy-Vector" Constructor
template<typename Adjactor1_ , typename Adjactor2_ >
Graph (RenderType render_type, const Adjactor1_ &adjactor1, const Adjactor2_ &adjactor2)
Composite-Render constructor.
template<typename Adjactor_ >
Graph (RenderType render_type, const Adjactor_ &adjactor)
Render constructor.
virtual ~Graph ()
virtual destructor
void clear ()
Clears the graph.
Graph clone () const
Clones this graph.
Index degree () const
Returns the degree of the graph.
Index degree (Index domain_node) const
Returns the degree of a domain node.
Index * get_domain_ptr ()
Returns the domain pointer array.
const Index * get_domain_ptr () const
Returns the domain pointer array.
Index * get_image_idx ()
Returns the image node index array.
const Index * get_image_idx () const
Returns the image node index array.
Index get_num_indices () const
Returns the total number indices.
Index get_num_nodes_domain () const
Index get_num_nodes_image () const
ImageIterator image_begin (Index domain_node) const
Returns an iterator for the first adjacent image node.
ImageIterator image_end (Index domain_node) const
Returns an iterator for the first position past the last adjacent image node.
Graph & operator= (Graph &&other)
move-assign operator
void permute_indices (const Adjacency::Permutation &inv_perm)
Permutes the image indices.
std::vector< char > serialize () const
Serializes the graph into a buffer.
void sort_indices ()
Sorts the image indices to non-descending order.
Static Public Attributes
static constexpr std::uint64_t magic = 0x5052474A44413346ull
Protected Attributes
IndexVector _domain_ptr
Domain pointer Vector.
IndexVector _image_idx
Image node index Vector.
Index _num_nodes_image
total number of image nodes
Detailed Description
Adjacency Graph implementation.
Todo:
detailed description
Author
Peter Zajac
Definition at line 34 of file graph.hpp.
Member Typedef Documentation
ImageIterator
typedef IndexVector::const_iterator FEAT::Adjacency::Graph::ImageIterator
ImageIterator for Graph class.
For the purpose of the Adjactor interface implementation a const Index-pointer is the optimal choice for the image node iterator.
Definition at line 45 of file graph.hpp.
IndexVector
using FEAT::Adjacency::Graph::IndexVector = std::vector < Index>
Definition at line 37 of file graph.hpp.
Constructor & Destructor Documentation
Graph() [1/9]
FEAT::Adjacency::Graph::Graph ()
Default constructor.
This constructor creates a new empty graph, but does not allocate any vectors.
Definition at line 15 of file graph.cpp.
Referenced by clone().
Graph() [2/9]
FEAT::Adjacency::Graph::Graph (Index num_nodes_domain, Index num_nodes_image, Index num_indices_image) explicit
Allocation Constructor.
This constructor creates a new graph and allocates the Graph's vectors to the corresponding lengths.
Note
This constructor does not initialize the allocated vectors – they have to be initialized by the user after construction.
Parameters
[in] num_nodes_domain The total number of domain nodes for the graph.
[in] num_nodes_image The total number of image nodes for the graph.
[in] num_indices_image The total number of image node indices for the graph.
Definition at line 22 of file graph.cpp.
Graph() [3/9]
FEAT::Adjacency::Graph::Graph (Index num_nodes_domain, Index num_nodes_image, Index num_indices_image, const Index * domain_ptr, const Index * image_idx) explicit
"Copy-Arrays" Constructor
This constructor creates a new graph using copies of the arrays passed to this function.
Parameters
[in] num_nodes_domain The total number of domain nodes for the graph.
[in] num_nodes_image The total number of image nodes for the graph.
[in] num_indices_image The total number of image node indices for the graph.
[in] domain_ptr The transient domain pointer array for the graph. Must not be nullptr.
[in] image_idx The transient image node index array for the graph. Must not be nullptr.
Definition at line 33 of file graph.cpp.
References _domain_ptr, and _image_idx.
Graph() [4/9]
FEAT::Adjacency::Graph::Graph (Index num_nodes_image, const IndexVector & domain_ptr, const IndexVector & image_idx) explicit
"Copy-Vector" Constructor
This constructor creates a new graph using copies of the vectors passed to this function.
Parameters
[in] num_nodes_image The total number of image nodes for the graph.
[in] domain_ptr The transient domain pointer vector for the graph. Must not be nullptr.
[in] image_idx The transient image node index vector for the graph. Must not be nullptr.
Definition at line 54 of file graph.cpp.
Graph() [5/9]
template<typename Adjactor_ > FEAT::Adjacency::Graph::Graph (RenderType render_type, const Adjactor_ & adjactor) inline explicit
Render constructor.
This constructor renders an object implementing the Adjactor interface into a graph.
Parameters
[in] render_type The render type. See RenderType for details.
[in] adjactor A reference to the adjactor that is to be rendered.
Definition at line 158 of file graph.hpp.
References FEAT::Adjacency::as_is, FEAT::Adjacency::as_is_sorted, FEAT::Adjacency::injectify, FEAT::Adjacency::injectify_sorted, FEAT::Adjacency::injectify_transpose, FEAT::Adjacency::injectify_transpose_sorted, sort_indices(), FEAT::Adjacency::transpose, FEAT::Adjacency::transpose_sorted, and XABORTM.
Graph() [6/9]
template<typename Adjactor1_ , typename Adjactor2_ > FEAT::Adjacency::Graph::Graph (RenderType render_type, const Adjactor1_ & adjactor1, const Adjactor2_ & adjactor2) inline explicit
Composite-Render constructor.
This constructor renders a composition of two objects implementing the Adjactor interface into a graph.
Parameters
[in] render_type The render type. See RenderType for details.
[in] adjactor1 A transient reference to the first adjactor in the composition that is to be rendered.
[in] adjactor2 A transient reference to the second adjactor in the composition that is to be rendered.
Definition at line 211 of file graph.hpp.
References FEAT::Adjacency::as_is, FEAT::Adjacency::as_is_sorted, FEAT::Adjacency::injectify, FEAT::Adjacency::injectify_sorted, FEAT::Adjacency::injectify_transpose, FEAT::Adjacency::injectify_transpose_sorted, sort_indices(), FEAT::Adjacency::transpose, FEAT::Adjacency::transpose_sorted, and XABORTM.
Graph() [7/9]
FEAT::Adjacency::Graph::Graph (Graph && other)
move CTOR
Definition at line 67 of file graph.cpp.
Graph() [8/9]
FEAT::Adjacency::Graph::Graph (const Graph & other, const Permutation & domain_perm, const Permutation & image_perm) explicit
"Permutation" copy CTOR
This constructor creates a new graph by permuting the domain and image set of the graph that is passed to this function.
Parameters
[in] other The transient graph that has to be permuted.
[in] domain_perm The transient permutation of the domain set.
[in] image_perm The transient permutation of the image set.
Definition at line 96 of file graph.cpp.
References _domain_ptr, _image_idx, and FEAT::Adjacency::Permutation::get_perm_pos().
Graph() [9/9]
FEAT::Adjacency::Graph::Graph (const std::vector< char > & buffer) explicit
Deserialization CTOR.
This constructor creates the graph from a buffer that has been created by using the serialize function.
Parameters
[in] buffer The transient serialization buffer to create the graph from.
Definition at line 130 of file graph.cpp.
References _domain_ptr, _image_idx, _num_nodes_image, and XASSERTM.
~Graph()
FEAT::Adjacency::Graph::~Graph () virtual
virtual destructor
Definition at line 173 of file graph.cpp.
Member Function Documentation
clear()
void FEAT::Adjacency::Graph::clear ()
Clears the graph.
Definition at line 176 of file graph.cpp.
References _domain_ptr, _image_idx, and _num_nodes_image.
Referenced by FEAT::Assembly::DomainAssembler< Trafo_ >::clear().
clone()
Graph FEAT::Adjacency::Graph::clone () const inline
Clones this graph.
Returns
A deep-copy of this graph.
Definition at line 294 of file graph.hpp.
References Graph(), _domain_ptr, _image_idx, and _num_nodes_image.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_extern().
degree() [1/2]
Index FEAT::Adjacency::Graph::degree () const
Returns the degree of the graph.
This function returns the degree of the graph, i.e. the maximum of the degrees of all domain nodes.
Note
The degree of the graph might be greater than the total number of image nodes if the graph is not injective.
Attention
This function performs a loop over all domain nodes and therefore has linear runtime. It is recommended to store the result of this function in a variable if the degree is needed multiple times.
Returns
The degree of the graph.
Definition at line 183 of file graph.cpp.
References _domain_ptr.
degree() [2/2]
Index FEAT::Adjacency::Graph::degree (Index domain_node) const inline
Returns the degree of a domain node.
This function returns the degree of a domain node, i.e. the number of image nodes which are adjacent to the specified domain node.
Note
The degree might be greater than the total number of image nodes if the graph is not injective.
Parameters
[in] domain_node The domain node index whose degree is to be returned.
Returns
The degree of the specified domain node.
Definition at line 316 of file graph.hpp.
References _domain_ptr, and ASSERTM.
Referenced by FEAT::Adjacency::Coloring::Coloring(), FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::PatchMeshPartFactory(), FEAT::Assembly::DomainAssembler< Trafo_ >::_build_colors(), FEAT::Assembly::DomainAssembler< Trafo_ >::_build_layers(), FEAT::Assembly::TraceAssembler< Trafo_ >::compile_all_facets(), FEAT::Adjacency::CuthillMcKee::compute(), and FEAT::Geometry::MeshFileWriter::write_partition().
get_domain_ptr() [1/2]
Index * FEAT::Adjacency::Graph::get_domain_ptr () inline
Returns the domain pointer array.
Returns
The domain pointer array.
Definition at line 342 of file graph.hpp.
References _domain_ptr.
Referenced by FEAT::Adjacency::Coloring::Coloring(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_naive(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_data_mirror(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_reduced_b(), FEAT::Assembly::DomainAssembler< Trafo_ >::_build_colors(), FEAT::Assembly::DomainAssembler< Trafo_ >::_build_graphs(), FEAT::Assembly::DomainAssembler< Trafo_ >::_build_layers(), FEAT::Assembly::SymbolicAssembler::assemble_graph_diag(), FEAT::Geometry::Parti2Lvl< ConformalMesh< Shape_, num_coords_, Coord_ > >::build_elems_at_rank(), FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::build_elems_at_rank(), FEAT::Adjacency::CuthillMcKee::compute(), FEAT::Geometry::MeshPermutation< Shape_ >::create_colored(), FEAT::Adjacency::Coloring::create_partition_graph(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Space::DofMappingRenderer::render().
get_domain_ptr() [2/2]
const Index * FEAT::Adjacency::Graph::get_domain_ptr () const inline
Returns the domain pointer array.
Returns
The domain pointer array.
Definition at line 348 of file graph.hpp.
References _domain_ptr.
get_image_idx() [1/2]
Index * FEAT::Adjacency::Graph::get_image_idx () inline
Returns the image node index array.
Returns
The image node index array.
Definition at line 357 of file graph.hpp.
References _image_idx.
Referenced by FEAT::Adjacency::Coloring::Coloring(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_naive(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_data_mirror(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_reduced_b(), FEAT::Assembly::DomainAssembler< Trafo_ >::_build_colors(), FEAT::Assembly::DomainAssembler< Trafo_ >::_build_graphs(), FEAT::Assembly::DomainAssembler< Trafo_ >::_build_layers(), FEAT::Assembly::SymbolicAssembler::assemble_graph_diag(), FEAT::Geometry::Parti2Lvl< ConformalMesh< Shape_, num_coords_, Coord_ > >::build_elems_at_rank(), FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::build_elems_at_rank(), FEAT::Adjacency::CuthillMcKee::compute(), FEAT::Geometry::MeshPermutation< Shape_ >::create_colored(), FEAT::Adjacency::Coloring::create_partition_graph(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Space::DofMappingRenderer::render().
get_image_idx() [2/2]
const Index * FEAT::Adjacency::Graph::get_image_idx () const inline
Returns the image node index array.
Returns
The image node index array.
Definition at line 363 of file graph.hpp.
References _image_idx.
get_num_indices()
Index FEAT::Adjacency::Graph::get_num_indices () const inline
Returns the total number indices.
Returns
The total number of indices in the graph.
Definition at line 373 of file graph.hpp.
References _image_idx.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_data_mirror(), FEAT::Geometry::MeshPermutation< Shape_ >::create_colored(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_symbolic().
get_num_nodes_domain()
Index FEAT::Adjacency::Graph::get_num_nodes_domain () const inline
Definition at line 892 of file graph.hpp.
get_num_nodes_image()
Index FEAT::Adjacency::Graph::get_num_nodes_image () const inline
Definition at line 899 of file graph.hpp.
image_begin()
ImageIterator FEAT::Adjacency::Graph::image_begin (Index domain_node) const inline
Returns an iterator for the first adjacent image node.
Parameters
[in] domain_node The index of the domain node whose image node iterator is to be returned.
Returns
An iterator representing the first image node adjacent to domain_node, or image_end(domain_node) if no adjacent image nodes exist.
Definition at line 906 of file graph.hpp.
References _domain_ptr, _image_idx, and ASSERTM.
Referenced by FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::PatchMeshPartFactory(), FEAT::Geometry::MeshPermutation< Shape_ >::_pick_gcmk_root(), FEAT::Assembly::TraceAssembler< Trafo_ >::compile(), FEAT::Assembly::TraceAssembler< Trafo_ >::compile_all_facets(), FEAT::Geometry::MeshPermutation< Shape_ >::create_gcmk(), FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_coloring(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_layering(), and FEAT::Geometry::MeshFileWriter::write_partition().
image_end()
ImageIterator FEAT::Adjacency::Graph::image_end (Index domain_node) const inline
Returns an iterator for the first position past the last adjacent image node.
Parameters
[in] domain_node The index of the domain node whose image node iterator is to be returned.
Returns
An iterator representing the first position past the last image node adjacent to domain_node.
Definition at line 914 of file graph.hpp.
References _domain_ptr, _image_idx, and ASSERTM.
Referenced by FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::PatchMeshPartFactory(), FEAT::Geometry::MeshPermutation< Shape_ >::_pick_gcmk_root(), FEAT::Assembly::TraceAssembler< Trafo_ >::compile(), FEAT::Assembly::TraceAssembler< Trafo_ >::compile_all_facets(), FEAT::Geometry::MeshPermutation< Shape_ >::create_gcmk(), FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_coloring(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_layering(), and FEAT::Geometry::MeshFileWriter::write_partition().
operator=()
Graph & FEAT::Adjacency::Graph::operator= (Graph && other)
move-assign operator
move assignment
Definition at line 78 of file graph.cpp.
References _domain_ptr, _image_idx, and _num_nodes_image.
permute_indices()
void FEAT::Adjacency::Graph::permute_indices (const Adjacency::Permutation & inv_perm)
Permutes the image indices.
Parameters
[in] inv_perm The transient inverse image indices permutation.
Definition at line 207 of file graph.cpp.
References _image_idx, FEAT::Adjacency::Permutation::size(), XASSERT, and XASSERTM.
Referenced by FEAT::Assembly::SymbolicAssembler::assemble_graph_2lvl(), and FEAT::Geometry::Partition::permute().
serialize()
std::vector< char > FEAT::Adjacency::Graph::serialize () const
Serializes the graph into a buffer.
Definition at line 217 of file graph.cpp.
References _domain_ptr, _image_idx, _num_nodes_image, and XASSERT.
sort_indices()
void FEAT::Adjacency::Graph::sort_indices ()
Sorts the image indices to non-descending order.
Definition at line 193 of file graph.cpp.
References _domain_ptr, _image_idx, and XASSERTM.
Referenced by Graph(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_reduced_b(), and FEAT::Assembly::DomainAssembler< Trafo_ >::_build_graphs().
Member Data Documentation
_domain_ptr
IndexVector FEAT::Adjacency::Graph::_domain_ptr protected
Domain pointer Vector.
Dimension: #_num_nodes_domain+1
Definition at line 59 of file graph.hpp.
Referenced by Graph(), clear(), clone(), degree(), get_domain_ptr(), image_begin(), image_end(), operator=(), serialize(), and sort_indices().
_image_idx
IndexVector FEAT::Adjacency::Graph::_image_idx protected
Image node index Vector.
Dimension: #_num_indices_image
Definition at line 66 of file graph.hpp.
Referenced by Graph(), clear(), clone(), get_image_idx(), get_num_indices(), image_begin(), image_end(), operator=(), permute_indices(), serialize(), and sort_indices().
_num_nodes_image
Index FEAT::Adjacency::Graph::_num_nodes_image protected
total number of image nodes
Definition at line 52 of file graph.hpp.
Referenced by Graph(), clear(), clone(), operator=(), and serialize().
magic
constexpr std::uint64_t FEAT::Adjacency::Graph::magic = 0x5052474A44413346ull static constexpr
Definition at line 48 of file graph.hpp.
The documentation for this class was generated from the following files:
kernel/adjacency/graph.hpp
kernel/adjacency/graph.cpp