FEAT: FEAT::Geometry::RootMeshNode< RootMesh_ > Class Template Reference
FEAT::Geometry::RootMeshNode< RootMesh_ > Class Template Reference
Root mesh node class template.
#include <mesh_node.hpp>
Public Types
typedef MeshNode< RootMesh_, RootMesh_ > BaseClass
base class typedef
typedef BaseClass::MeshAtlasType MeshAtlasType
mesh atlas type
typedef BaseClass::MeshChartType MeshChartType
mesh chart type
typedef MeshPartNode< RootMeshType > MeshPartNodeType
the mesh part node type
typedef BaseClass::MeshPartType MeshPartType
mesh part type
typedef BaseClass::MeshType MeshType
this mesh type
typedef RootMesh_ RootMeshType
the root mesh type, has to be a Mesh
Public Member Functions
RootMeshNode (std::unique_ptr< MeshType > mesh, MeshAtlasType *atlas=nullptr)
Constructor.
virtual ~RootMeshNode ()
Virtual destructor.
void adapt (bool recursive=true)
Adapts this mesh node.
bool adapt_by_name (const String &part_name, bool recursive=false)
Adapts this mesh node.
void add_halo (int rank, std::unique_ptr< MeshPartType > halo_part)
Adds a halo mesh part to this mesh node.
MeshPartNodeType * add_mesh_part (const String &part_name, std::unique_ptr< MeshPartType > mesh_part, const String &chart_name="", const MeshChartType *chart=nullptr)
Adds a new mesh-part child node.
MeshPartNodeType * add_mesh_part_node (const String &part_name, std::unique_ptr< MeshPartNodeType > mesh_part_node, const String &chart_name="", const MeshChartType *chart=nullptr)
Adds a new mesh-part child node.
MeshPartType * add_patch (int rank, std::unique_ptr< MeshPartType > patch_part)
Adds a patch mesh part to this mesh node.
std::size_t bytes () const
void clear_halos ()
Deletes all halo meshparts from this mesh node.
void clear_patches ()
Deletes all patch meshparts from this mesh node.
std::unique_ptr< RootMeshNode > clone_unique () const
Creates an independent clone of this object and returns a unique pointer to it.
void create_patch_meshpart (const Adjacency::Graph &elems_at_rank, const int rank)
Creates a patch meshpart for a child and adds it to the patch map.
void create_permutation (PermutationStrategy strategy)
Creates a mesh permutation.
std::unique_ptr< RootMeshNode > extract_patch (std::vector< Index > &&elements, bool split_meshparts, bool split_halos, bool split_patches)
Extracts a patch from the root mesh as a new mesh node.
std::unique_ptr< RootMeshNode > extract_patch (std::vector< int > &comm_ranks, const Adjacency::Graph &elems_at_rank, const int rank)
Extracts a patch from the root mesh as a new mesh node.
std::unique_ptr< RootMeshNode > extract_patch (std::vector< int > &comm_ranks, const Partition &partition, const int rank)
Extracts a patch from a manual partition.
MeshPartType * find_mesh_part (const String &part_name)
Searches this container for a MeshPart.
const MeshPartType * find_mesh_part (const String &part_name) const
const MeshChartType * find_mesh_part_chart (const String &part_name) const
Searches for a chart belonging to a MeshPart by name.
String find_mesh_part_chart_name (const String &part_name) const
Searches for a chart name belonging to a MeshPart by name.
MeshPartNodeType * find_mesh_part_node (const String &part_name)
Searches this container for a MeshPartNode.
const MeshPartNodeType * find_mesh_part_node (const String &part_name) const
const MeshAtlasType * get_atlas () const
const MeshPartType * get_halo (int rank) const
Returns a halo meshpart for a given neighbor.
const std::map< int, std::unique_ptr< MeshPartType > > & get_halo_map () const
MeshType * get_mesh ()
Returns the mesh of this node.
const MeshType * get_mesh () const
std::deque< String > get_mesh_part_names (bool no_internals=false) const
Returns the names of all mesh parts of this node.
const MeshPartType * get_patch (int rank) const
Returns a patch meshpart for a given child.
const std::map< int, std::unique_ptr< MeshPartType > > & get_patch_map () const
std::unique_ptr< RootMeshNode > refine_unique (AdaptMode adapt_mode=AdaptMode::chart) const
Refines this node and its sub-tree.
bool remove_mesh_part (const String &part_name)
Removes a mesh-part and its corresponding node.
void rename_halos (const std::map< int, int > &ranks)
Renames the halo meshparts.
void rename_mesh_parts (const std::map< String, String > &renames)
Renames a set of mesh-parts.
void set_mesh (std::unique_ptr< MeshType > mesh)
bool set_mesh_part_chart (const String &part_name, const String &chart_name, const MeshChartType *chart)
Sets the chart for a particular mesh part.
void set_permutation (MeshPermutation< typename MeshType::ShapeType > &&mesh_perm)
Creates a mesh permutation.
Static Public Member Functions
static std::unique_ptr< RootMeshNode > make_unique (std::unique_ptr< MeshType > mesh, MeshAtlasType *atlas=nullptr)
Creates a new RootMeshNode on the heap and returns a unique pointer to it.
static String name ()
Returns the name of the class.
Protected Types
typedef MeshPartNodeContainer::const_iterator MeshPartNodeConstIterator
submesh node const-iterator type
typedef std::map< String, MeshPartNodeBin > MeshPartNodeContainer
submesh node bin container type
typedef MeshPartNodeContainer::iterator MeshPartNodeIterator
submesh node iterator type
typedef MeshPartNodeContainer::reverse_iterator MeshPartNodeReverseIterator
submesh node reverse-iterator type
Protected Member Functions
void _apply_mesh_perm_to_parts ()
helper function: applies the mesh permutation to all mesh parts, halos and patches
void _clone (const RootMeshNode &other)
void refine_children (MeshNode &refined_node) const
Refines all child nodes of this node.
void refine_mesh_parts (MeshNode &refined_node) const
Refines all child MeshPart nodes of this node.
Protected Attributes
MeshAtlasType * _atlas
our atlas pointer
std::map< int, std::unique_ptr< MeshPartType > > _halos
a map of our halo mesh-parts
std::unique_ptr< MeshType > _mesh
a pointer to the mesh of this node
MeshPartNodeContainer _mesh_part_nodes
child submesh nodes
std::map< int, std::unique_ptr< MeshPartType > > _patches
a map of our patch mesh-parts
Detailed Description
template<typename RootMesh_>
class FEAT::Geometry::RootMeshNode< RootMesh_ >
Root mesh node class template.
This class template is used for the root node of a mesh tree.
Author
Peter Zajac
Definition at line 740 of file mesh_node.hpp.
Member Typedef Documentation
BaseClass
template<typename RootMesh_ > typedef MeshNode<RootMesh_, RootMesh_> FEAT::Geometry::RootMeshNode< RootMesh_ >::BaseClass
base class typedef
Definition at line 745 of file mesh_node.hpp.
MeshAtlasType
template<typename RootMesh_ > typedef BaseClass::MeshAtlasType FEAT::Geometry::RootMeshNode< RootMesh_ >::MeshAtlasType
mesh atlas type
Definition at line 752 of file mesh_node.hpp.
MeshChartType
template<typename RootMesh_ > typedef BaseClass::MeshChartType FEAT::Geometry::RootMeshNode< RootMesh_ >::MeshChartType
mesh chart type
Definition at line 754 of file mesh_node.hpp.
MeshPartNodeConstIterator
typedef MeshPartNodeContainer::const_iterator FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::MeshPartNodeConstIterator protected inherited
submesh node const-iterator type
Definition at line 176 of file mesh_node.hpp.
MeshPartNodeContainer
typedef std::map<String, MeshPartNodeBin> FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::MeshPartNodeContainer protected inherited
submesh node bin container type
Definition at line 172 of file mesh_node.hpp.
MeshPartNodeIterator
typedef MeshPartNodeContainer::iterator FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::MeshPartNodeIterator protected inherited
submesh node iterator type
Definition at line 174 of file mesh_node.hpp.
MeshPartNodeReverseIterator
typedef MeshPartNodeContainer::reverse_iterator FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::MeshPartNodeReverseIterator protected inherited
submesh node reverse-iterator type
Definition at line 178 of file mesh_node.hpp.
MeshPartNodeType
typedef MeshPartNode<RootMeshType> FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::MeshPartNodeType inherited
the mesh part node type
Definition at line 127 of file mesh_node.hpp.
MeshPartType
template<typename RootMesh_ > typedef BaseClass::MeshPartType FEAT::Geometry::RootMeshNode< RootMesh_ >::MeshPartType
mesh part type
Definition at line 750 of file mesh_node.hpp.
MeshType
template<typename RootMesh_ > typedef BaseClass::MeshType FEAT::Geometry::RootMeshNode< RootMesh_ >::MeshType
this mesh type
Definition at line 748 of file mesh_node.hpp.
RootMeshType
typedef RootMesh_ FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::RootMeshType inherited
the root mesh type, has to be a Mesh
Definition at line 121 of file mesh_node.hpp.
Constructor & Destructor Documentation
RootMeshNode()
template<typename RootMesh_ > FEAT::Geometry::RootMeshNode< RootMesh_ >::RootMeshNode (std::unique_ptr< MeshType > mesh, MeshAtlasType * atlas = nullptr) inline explicit
Constructor.
Parameters
[in] mesh A resident unique pointer to the mesh for this node.
[in] atlas A resident pointer to the atlas for this node.
Definition at line 798 of file mesh_node.hpp.
~RootMeshNode()
template<typename RootMesh_ > virtual FEAT::Geometry::RootMeshNode< RootMesh_ >::~RootMeshNode () inline virtual
Virtual destructor.
Definition at line 809 of file mesh_node.hpp.
Member Function Documentation
_apply_mesh_perm_to_parts()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::_apply_mesh_perm_to_parts () inline protected
helper function: applies the mesh permutation to all mesh parts, halos and patches
Definition at line 1457 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_halos, FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::_mesh, FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::_mesh_part_nodes, and FEAT::Geometry::RootMeshNode< RootMesh_ >::_patches.
Referenced by FEAT::Geometry::RootMeshNode< RootMesh_ >::create_permutation(), and FEAT::Geometry::RootMeshNode< RootMesh_ >::set_permutation().
_clone()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::_clone (const RootMeshNode< RootMesh_ > & other) inline protected
Definition at line 765 of file mesh_node.hpp.
adapt()
void FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::adapt (bool recursive = true) inline inherited
Adapts this mesh node.
This function loops over all MeshPart nodes and uses their associated charts (if given) to adapt the mesh in this node.
Parameters
[in] recursive If set to true, all mesh_part nodes are adapted prior to adapting this node.
Definition at line 475 of file mesh_node.hpp.
adapt_by_name()
bool FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::adapt_by_name (const String & part_name, bool recursive = false) inline inherited
Adapts this mesh node.
This function adapts this node by a specific chart whose name is given.
Parameters
[in] part_name The name of the mesh_part node that is to be used for adaption.
[in] recursive If set to true, the mesh_part node associated with part_name will be adapted prior to adapting this node.
Returns
true if this node was adapted successfully or false if no node is associated with part_name or if the node did not contain any chart.
Definition at line 517 of file mesh_node.hpp.
add_halo()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::add_halo (int rank, std::unique_ptr< MeshPartType > halo_part) inline
Adds a halo mesh part to this mesh node.
Parameters
[in] rank The rank of the neighbor this halo belongs to.
[in] halo_part A resident unique pointer to the halo mesh part for the neighbor.
Definition at line 868 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_halos, and XASSERTM.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_patch_halos(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_split_basemesh_halos().
add_mesh_part()
MeshPartNodeType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::add_mesh_part (const String & part_name, std::unique_ptr< MeshPartType > mesh_part, const String & chart_name = "", const MeshChartType * chart = nullptr) inline inherited
Adds a new mesh-part child node.
Parameters
[in] part_name The name of the child node.
[in] mesh_part A resident unique pointer to the mesh_part to be added.
[in] chart_name The name of the chart that the mesh-part is to be linked to.
[in] chart A resident pointer to the chart that the subnode is to be associated with. May be nullptr.
Returns
A pointer to the newly created mesh-part node if the insertion was successful, otherwise nullptr.
Definition at line 316 of file mesh_node.hpp.
add_mesh_part_node()
MeshPartNodeType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::add_mesh_part_node (const String & part_name, std::unique_ptr< MeshPartNodeType > mesh_part_node, const String & chart_name = "", const MeshChartType * chart = nullptr) inline inherited
Adds a new mesh-part child node.
Parameters
[in] part_name The name of the child node.
[in] mesh_part_node A resident unique pointer to the mesh_part node to be added.
[in] chart_name The name of the chart that the mesh-part is to be linked to.
[in] chart A resident pointer to the chart that the subnode is to be associated with. May be nullptr.
Returns
mesh_part_node.get() if the insertion was successful, otherwise nullptr.
Definition at line 281 of file mesh_node.hpp.
add_patch()
template<typename RootMesh_ > MeshPartType * FEAT::Geometry::RootMeshNode< RootMesh_ >::add_patch (int rank, std::unique_ptr< MeshPartType > patch_part) inline
Adds a patch mesh part to this mesh node.
Parameters
[in] rank The rank of the child this patch belongs to.
[in] patch_part A resident pointer to the patch mesh part for the child.
Returns
A pointer to the inserted patch mesh part.
Definition at line 941 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_patches, and XASSERT.
Referenced by FEAT::Geometry::RootMeshNode< RootMesh_ >::create_patch_meshpart(), and FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch().
bytes()
template<typename RootMesh_ > std::size_t FEAT::Geometry::RootMeshNode< RootMesh_ >::bytes () const inline
Returns
The size of dynamically allocated memory in bytes.
Definition at line 849 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_halos, FEAT::Geometry::RootMeshNode< RootMesh_ >::_patches, and FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::bytes().
clear_halos()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::clear_halos () inline
Deletes all halo meshparts from this mesh node.
Definition at line 896 of file mesh_node.hpp.
clear_patches()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::clear_patches () inline
Deletes all patch meshparts from this mesh node.
Definition at line 969 of file mesh_node.hpp.
clone_unique()
template<typename RootMesh_ > std::unique_ptr< RootMeshNode > FEAT::Geometry::RootMeshNode< RootMesh_ >::clone_unique () const inline
Creates an independent clone of this object and returns a unique pointer to it.
Returns
A unique pointer to the newly created clone object.
Definition at line 841 of file mesh_node.hpp.
create_patch_meshpart()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::create_patch_meshpart (const Adjacency::Graph & elems_at_rank, const int rank) inline
Creates a patch meshpart for a child and adds it to the patch map.
Parameters
[in] elems_at_rank A transient reference to the adjacency graph that describes which elements belong to each child rank.
[in] rank The child rank for which the patch meshpart is to be created.
Definition at line 1389 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_patch(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::get_mesh(), and FEAT::Geometry::Factory< MeshPart< MeshType_ > >::make_unique().
create_permutation()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::create_permutation (PermutationStrategy strategy) inline
Creates a mesh permutation.
This function creates a permutation based on one of the standards permutation strategies and also permutes the mesh parts, halos and patches stored in this mesh node.
See also
ConformalMesh::create_permutation()
Note
If you want to use a custom permutation other than one of the standard permutation strategies then use set_permutation() instead.
Definition at line 1415 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_apply_mesh_perm_to_parts(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::_mesh, and XASSERTM.
extract_patch() [1/3]
template<typename RootMesh_ > std::unique_ptr< RootMeshNode > FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch (std::vector< Index > && elements, bool split_meshparts, bool split_halos, bool split_patches) inline
Extracts a patch from the root mesh as a new mesh node.
Parameters
[in] elements A vector containing the indices of the patch elements.
[in] split_meshparts Specifies whether the mesh-parts of the mesh node are to be extracted. If false, then the returned mesh node will not contain any mesh parts.
[in] split_halos Specifies whether the halos of the mesh node are to be extracted. If false, then the returned mesh node will not contain any halos.
[in] split_patches Specifies whether the patch mesh-parts of the mesh node are to be extracted. If false, then the returned mesh node will not contain any patch mesh parts.
Returns
A unique pointer to the new mesh node representing the extracted patch.
Definition at line 1055 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_patch(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_chart(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_chart_name(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_node(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::get_mesh(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::get_mesh_part_names(), FEAT::Geometry::Factory< MeshPart< MeshType_ > >::make_unique(), FEAT::Geometry::RootMeshNode< RootMesh_ >::make_unique(), and XASSERTM.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node(), and FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch().
extract_patch() [2/3]
template<typename RootMesh_ > std::unique_ptr< RootMeshNode > FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch (std::vector< int > & comm_ranks, const Adjacency::Graph & elems_at_rank, const int rank) inline
Extracts a patch from the root mesh as a new mesh node.
This function also computes the communication neighbor ranks.
Parameters
[out] comm_ranks A transient reference to the communication neighbor ranks vector for this process.
[in] elems_at_rank A transient reference to the elements-at-rank graph representing the partitioning from which the patch is to be extracted.
[in] rank The rank of the patch to be created.
Returns
A unique pointer to the new mesh node representing the extracted patch.
Definition at line 1200 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_patch(), FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::empty(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_chart(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_chart_name(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_node(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::get_mesh(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::get_mesh_part_names(), FEAT::Adjacency::Graph::image_begin(), FEAT::Adjacency::Graph::image_end(), FEAT::Adjacency::injectify, FEAT::Geometry::Factory< MeshPart< MeshType_ > >::make_unique(), FEAT::Geometry::RootMeshNode< RootMesh_ >::make_unique(), FEAT::stringify(), FEAT::Adjacency::transpose, XABORTM, and XASSERTM.
extract_patch() [3/3]
template<typename RootMesh_ > std::unique_ptr< RootMeshNode > FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch (std::vector< int > & comm_ranks, const Partition & partition, const int rank) inline
Extracts a patch from a manual partition.
This function also computes the communication ranks.
Parameters
[out] comm_ranks A transient reference to the communication ranks vector for this rank.
[in] partition A transient reference to the partition from which the patch is to be extracted.
[in] rank The rank of the patch to be created.
Returns
A unique pointer to the new mesh node representing the extracted patch.
Definition at line 1372 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), and FEAT::Geometry::Partition::get_patches().
find_mesh_part() [1/2]
MeshPartType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part (const String & part_name) inline inherited
Searches this container for a MeshPart.
Parameters
[in] part_name The name of the node associated with the mesh_part to be found.
Returns
A pointer to the mesh_part associated with part_name or nullptr if no such node was found.
Definition at line 392 of file mesh_node.hpp.
find_mesh_part() [2/2]
const MeshPartType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part (const String & part_name) const inline inherited
Searches this container for a MeshPart.
Parameters
[in] part_name The name of the node associated with the mesh_part to be found.
Returns
A pointer to the mesh_part associated with part_name or nullptr if no such node was found.
Definition at line 399 of file mesh_node.hpp.
find_mesh_part_chart()
const MeshChartType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_chart (const String & part_name) const inline inherited
Searches for a chart belonging to a MeshPart by name.
Parameters
[in] part_name The name of the node associated with the chart to be found.
Returns
A pointer to the chart associated with part_name of nullptr if no such node was found or if the corresponding node did not have a chart.
Definition at line 415 of file mesh_node.hpp.
find_mesh_part_chart_name()
String FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_chart_name (const String & part_name) const inline inherited
Searches for a chart name belonging to a MeshPart by name.
Parameters
[in] part_name The name of the node associated with the chart to be found.
Returns
The name of the chart associated with part_name or an empty string is no such node was found.
Definition at line 431 of file mesh_node.hpp.
find_mesh_part_node() [1/2]
MeshPartNodeType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_node (const String & part_name) inline inherited
Searches this container for a MeshPartNode.
Parameters
[in] part_name The name of the node to be found.
Returns
A pointer to the mesh_part node associated with part_name or nullptr if no such node was found.
Definition at line 370 of file mesh_node.hpp.
find_mesh_part_node() [2/2]
const MeshPartNodeType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::find_mesh_part_node (const String & part_name) const inline inherited
Searches this container for a MeshPartNode.
Parameters
[in] part_name The name of the node to be found.
Returns
A pointer to the mesh_part node associated with part_name or nullptr if no such node was found.
Definition at line 377 of file mesh_node.hpp.
get_atlas()
template<typename RootMesh_ > const MeshAtlasType * FEAT::Geometry::RootMeshNode< RootMesh_ >::get_atlas () const inline
Returns
A pointer to the underlying mesh atlas; may return nullptr.
Definition at line 814 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_atlas.
Referenced by FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max(), and FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min().
get_halo()
template<typename RootMesh_ > const MeshPartType * FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo (int rank) const inline
Returns a halo meshpart for a given neighbor.
Parameters
[in] rank The rank of the neighbor for which the halo is to be returned.
Returns
A pointer to the halo mesh part for the neighbor or nullptr, if no halo for this neighbor rank exists.
Definition at line 883 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_halos.
get_halo_map()
template<typename RootMesh_ > const std::map< int, std::unique_ptr< MeshPartType > > & FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map () const inline
Returns
A reference to the internal neighbor-halo map.
Definition at line 890 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_halos.
Referenced by FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_vertex_owners(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_patch_halos(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_split_basemesh_halos(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_synchronize(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::sync().
get_mesh() [1/2]
MeshType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::get_mesh () inline inherited
Returns the mesh of this node.
Returns
A pointer to the mesh contained in this node.
Definition at line 225 of file mesh_node.hpp.
get_mesh() [2/2]
const MeshType * FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::get_mesh () const inline inherited
Returns the mesh of this node.
Returns
A pointer to the mesh contained in this node.
Definition at line 231 of file mesh_node.hpp.
get_mesh_part_names()
std::deque< String > FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::get_mesh_part_names (bool no_internals = false) const inline inherited
Returns the names of all mesh parts of this node.
Parameters
[in] no_internals Specifies whether to skip all internal mesh-parts whose names begin with an underscore.
Returns
A deque of all mesh-part names in this node.
Definition at line 251 of file mesh_node.hpp.
get_patch()
template<typename RootMesh_ > const MeshPartType * FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch (int rank) const inline
Returns a patch meshpart for a given child.
Parameters
[in] rank The rank of the child for which the patch is to be returned.
Returns
A pointer to the patch mesh part for the child or nullptr, if no patch for this child rank exists.
Definition at line 956 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_patches.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_patch_halos(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_layering(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_split_basemesh_halos().
get_patch_map()
template<typename RootMesh_ > const std::map< int, std::unique_ptr< MeshPartType > > & FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch_map () const inline
Returns
A reference to the internal child-patch map.
Definition at line 963 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_patches.
make_unique()
template<typename RootMesh_ > static std::unique_ptr< RootMeshNode > FEAT::Geometry::RootMeshNode< RootMesh_ >::make_unique (std::unique_ptr< MeshType > mesh, MeshAtlasType * atlas = nullptr) inline static
Creates a new RootMeshNode on the heap and returns a unique pointer to it.
Parameters
[in] mesh A resident unique pointer to the mesh for the newly created node.
[in] atlas A resident pointer to the atlas for the newly created node.
Returns
A unique pointer to the new RootMeshNode object.
Definition at line 831 of file mesh_node.hpp.
Referenced by FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), FEAT::Geometry::MeshFileReader::parse(), and FEAT::Geometry::RootMeshNode< RootMesh_ >::refine_unique().
name()
template<typename RootMesh_ > static String FEAT::Geometry::RootMeshNode< RootMesh_ >::name () inline static
Returns the name of the class.
Returns
The name of the class as a String.
Definition at line 1450 of file mesh_node.hpp.
refine_children()
void FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::refine_children (MeshNode< RootMesh_, RootMesh_ > & refined_node) const inline protected inherited
Refines all child nodes of this node.
Parameters
[in,out] refined_node A reference to the node generated by refining this node.
Definition at line 559 of file mesh_node.hpp.
refine_mesh_parts()
void FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::refine_mesh_parts (MeshNode< RootMesh_, RootMesh_ > & refined_node) const inline protected inherited
Refines all child MeshPart nodes of this node.
Parameters
[in,out] refined_node A reference to the node generated by refining this node.
Definition at line 571 of file mesh_node.hpp.
refine_unique()
template<typename RootMesh_ > std::unique_ptr< RootMeshNode > FEAT::Geometry::RootMeshNode< RootMesh_ >::refine_unique (AdaptMode adapt_mode = AdaptMode::chart) const inline
Refines this node and its sub-tree.
Parameters
[in] adapt_mode Mode for adaption, defaults to chart.
Returns
A unique pointer to a newly created RootMeshNode containing the refined mesh tree.
Definition at line 983 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_halos, FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::_mesh, FEAT::Geometry::RootMeshNode< RootMesh_ >::_patches, FEAT::Geometry::RootMeshNode< RootMesh_ >::make_unique(), and FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::refine_children().
remove_mesh_part()
bool FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::remove_mesh_part (const String & part_name) inline inherited
Removes a mesh-part and its corresponding node.
Parameters
[in] part_name The name of the child node to be removed
Returns
true, if a mesh-part with the corresponding name was removed, otherwise false.
Definition at line 333 of file mesh_node.hpp.
rename_halos()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::rename_halos (const std::map< int, int > & ranks) inline
Renames the halo meshparts.
This function can be used to rename the halo meshparts when the rank ordering in the communicator has changed.
Parameters
[in] ranks An map of oldrank-newrank pairs.
Definition at line 910 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_halos.
rename_mesh_parts()
void FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::rename_mesh_parts (const std::map< String, String > & renames) inline inherited
Renames a set of mesh-parts.
Parameters
[in] renames A transient map of oldname-newname pairs.
Definition at line 443 of file mesh_node.hpp.
set_mesh()
void FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::set_mesh (std::unique_ptr< MeshType > mesh) inline inherited
Definition at line 236 of file mesh_node.hpp.
set_mesh_part_chart()
bool FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::set_mesh_part_chart (const String & part_name, const String & chart_name, const MeshChartType * chart) inline inherited
Sets the chart for a particular mesh part.
Parameters
[in] part_name The name of the mesh part that the chart is to be assigned to.
[in] chart A resident pointer to the chart that is to be assigned. May also be nullptr.
Returns
true if the chart was assigned successfully or false if no mesh part with the specified name was found.
Definition at line 351 of file mesh_node.hpp.
set_permutation()
template<typename RootMesh_ > void FEAT::Geometry::RootMeshNode< RootMesh_ >::set_permutation (MeshPermutation< typename MeshType::ShapeType > && mesh_perm) inline
Creates a mesh permutation.
This function creates a permutation based on one of the standards permutation strategies and also permutes the mesh parts, halos and patches stored in this mesh node.
See also
ConformalMesh::set_permutation()
Definition at line 1434 of file mesh_node.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::_apply_mesh_perm_to_parts(), FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::_mesh, and XASSERTM.
Member Data Documentation
_atlas
template<typename RootMesh_ > MeshAtlasType* FEAT::Geometry::RootMeshNode< RootMesh_ >::_atlas protected
our atlas pointer
Definition at line 758 of file mesh_node.hpp.
Referenced by FEAT::Geometry::RootMeshNode< RootMesh_ >::get_atlas().
_halos
template<typename RootMesh_ > std::map<int, std::unique_ptr<MeshPartType> > FEAT::Geometry::RootMeshNode< RootMesh_ >::_halos protected
a map of our halo mesh-parts
Definition at line 760 of file mesh_node.hpp.
Referenced by FEAT::Geometry::RootMeshNode< RootMesh_ >::_apply_mesh_perm_to_parts(), FEAT::Geometry::RootMeshNode< RootMesh_ >::add_halo(), FEAT::Geometry::RootMeshNode< RootMesh_ >::bytes(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::RootMeshNode< RootMesh_ >::refine_unique(), and FEAT::Geometry::RootMeshNode< RootMesh_ >::rename_halos().
_mesh
std::unique_ptr<MeshType> FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::_mesh protected inherited
a pointer to the mesh of this node
Definition at line 182 of file mesh_node.hpp.
_mesh_part_nodes
MeshPartNodeContainer FEAT::Geometry::MeshNode< RootMesh_, RootMesh_ >::_mesh_part_nodes protected inherited
child submesh nodes
Definition at line 184 of file mesh_node.hpp.
_patches
template<typename RootMesh_ > std::map<int, std::unique_ptr<MeshPartType> > FEAT::Geometry::RootMeshNode< RootMesh_ >::_patches protected
a map of our patch mesh-parts
Definition at line 762 of file mesh_node.hpp.
Referenced by FEAT::Geometry::RootMeshNode< RootMesh_ >::_apply_mesh_perm_to_parts(), FEAT::Geometry::RootMeshNode< RootMesh_ >::add_patch(), FEAT::Geometry::RootMeshNode< RootMesh_ >::bytes(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch_map(), and FEAT::Geometry::RootMeshNode< RootMesh_ >::refine_unique().
The documentation for this class was generated from the following file:
kernel/geometry/mesh_node.hpp