FEAT: FEAT::LAFEM::PowerVector< SubType_, count_ > Class Template Reference
FEAT::LAFEM::PowerVector< SubType_, count_ > Class Template Reference
Power-Vector meta class template.
#include <power_vector.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = PowerVector< typename SubType_::template ContainerType< DT2_, IT2_ >, count_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a vector container with different Data and Index types
typedef SubVectorType::DataType DataType
sub-vector data type
typedef SubVectorType::IndexType IndexType
sub-vector index type
typedef SubType_ SubVectorType
sub-vector type
Public Member Functions
PowerVector ()
default CTOR
PowerVector (const PowerVector &)=delete
deleted copy-ctor
PowerVector (Index sub_size)
Constructor.
PowerVector (Index sub_size, DataType value)
Constructor.
PowerVector (PowerVector &&other)
move CTOR
PowerVector (SubVectorType &&the_first, RestClass &&the_rest)
base-class constructor; for internal use only
virtual ~PowerVector ()
virtual destructor
template<int i_>
SubVectorType & at ()
Returns a sub-vector block.
template<int i_>
const SubVectorType & at () const
Returns a sub-vector block.
void axpy (const PowerVector &x, DataType alpha=DataType(1))
Performs \(this \leftarrow \alpha\cdot x + this \).
int blocks () const
Returns the number of blocks in this power-vector.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
void clone (const PowerVector &other)
Turns this vector into a clone of other.
void clone (const PowerVector &other, CloneMode clone_mode)
Turns this vector into a clone of other.
PowerVector clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a copy of this vector.
void component_invert (const PowerVector &x, DataType alpha=DataType(1))
Performs \(this_i \leftarrow \alpha / x_i \).
void component_product (const PowerVector &x, const PowerVector &y)
Performs \(this_i \leftarrow x_i \cdot y_i\).
template<typename SubType2_ >
void convert (const PowerVector< SubType2_, count_ > &other)
Conversion method.
template<typename SubType2_ >
void copy (const PowerVector< SubType2_, count_ > &x, bool full=false)
Performs \(this \leftarrow x\).
DataType dot (const PowerVector &x) const
Returns the dot-product of this vector and another vector.
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DataType min, DataType max)
Reset all elements of the container to random values.
SubVectorType & get (int i)
Returns a sub-vector block.
const SubVectorType & get (int i) const
Returns a sub-vector block.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
DataType max_abs_element () const
Retrieve the absolute maximum value of this vector.
DataType max_element () const
Retrieve the maximum value of this vector.
DataType min_abs_element () const
Retrieve the absolute minimum value of this vector.
DataType min_element () const
Retrieve the minimum value of this vector.
DataType norm2 () const
Returns the euclid norm of this vector.
DataType norm2sqr () const
Returns the squared euclid norm of this vector.
const DataType operator() (Index index) const
Retrieve specific PowerVector element.
void operator() (Index index, DataType value)
Set specific PowerVector element.
PowerVector & operator= (const PowerVector &)=delete
deleted copy-assign operator
PowerVector & operator= (PowerVector &&other)
move-assign operator
void read_from (FileMode mode, const String &filename)
Read in vector from file.
void read_from (FileMode mode, std::istream &file)
Read in vector from stream.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
void scale (const PowerVector &x, DataType alpha)
Performs \(this \leftarrow \alpha\cdot x \).
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
template<Perspective perspective_ = Perspective::native>
Index size () const
Returns the total number of scalar entries of this power-vector.
DataType triple_dot (const PowerVector &x, const PowerVector &y) const
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
void write_out (FileMode mode, const String &filename) const
Write out vector to file.
void write_out (FileMode mode, std::ostream &file) const
Write out vector to file.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr int num_blocks = count_
number of vector blocks
Protected Attributes
SubVectorType _first
the first sub-vector
RestClass _rest
the remaining part
Private Types
typedef PowerVector< SubType_, count_ - 1 > RestClass
base-class typedef
Private Member Functions
void _read_from_binary (std::istream &file)
read binary data of _first and _rest to file.
void _write_out_binary (std::ostream &file) const
write binary data of _first and _rest to file.
Friends
bool operator== (const PowerVector &a, const PowerVector &b)
PowerVector comparison operator.
Detailed Description
template<typename SubType_, int count_>
class FEAT::LAFEM::PowerVector< SubType_, count_ >
Power-Vector meta class template.
This class template implements a composition of n sub-vectors of the same class.
Note
For a composed meta-vector of different sub-vector classes, see the TupleVector class template.
Template Parameters
SubType_ The type of the sub-vector.
count_ The number of sub-vector blocks.
Author
Peter Zajac
Definition at line 38 of file power_vector.hpp.
Member Typedef Documentation
ContainerType
template<typename SubType_ , int count_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::PowerVector< SubType_, count_ >::ContainerType = PowerVector<typename SubType_::template ContainerType<DT2_, IT2_>, count_>
Our 'base' class type.
Definition at line 80 of file power_vector.hpp.
ContainerTypeByDI
template<typename SubType_ , int count_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::PowerVector< SubType_, count_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a vector container with different Data and Index types
Definition at line 84 of file power_vector.hpp.
DataType
template<typename SubType_ , int count_> typedef SubVectorType::DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::DataType
sub-vector data type
Definition at line 75 of file power_vector.hpp.
IndexType
template<typename SubType_ , int count_> typedef SubVectorType::IndexType FEAT::LAFEM::PowerVector< SubType_, count_ >::IndexType
sub-vector index type
Definition at line 77 of file power_vector.hpp.
RestClass
template<typename SubType_ , int count_> typedef PowerVector<SubType_, count_ - 1> FEAT::LAFEM::PowerVector< SubType_, count_ >::RestClass private
base-class typedef
Definition at line 49 of file power_vector.hpp.
SubVectorType
template<typename SubType_ , int count_> typedef SubType_ FEAT::LAFEM::PowerVector< SubType_, count_ >::SubVectorType
sub-vector type
Definition at line 73 of file power_vector.hpp.
Constructor & Destructor Documentation
PowerVector() [1/5]
template<typename SubType_ , int count_> FEAT::LAFEM::PowerVector< SubType_, count_ >::PowerVector () inline
default CTOR
Definition at line 97 of file power_vector.hpp.
PowerVector() [2/5]
template<typename SubType_ , int count_> FEAT::LAFEM::PowerVector< SubType_, count_ >::PowerVector (Index sub_size) inline explicit
Constructor.
Parameters
[in] sub_size The size of any sub-vector of this power-vector.
Definition at line 107 of file power_vector.hpp.
PowerVector() [3/5]
template<typename SubType_ , int count_> FEAT::LAFEM::PowerVector< SubType_, count_ >::PowerVector (Index sub_size, DataType value) inline explicit
Constructor.
Parameters
[in] sub_size The size of any sub-vector of this power-vector.
[in] value The value that the sub-vectors are to be initialized with.
Definition at line 122 of file power_vector.hpp.
PowerVector() [4/5]
template<typename SubType_ , int count_> FEAT::LAFEM::PowerVector< SubType_, count_ >::PowerVector (SubVectorType && the_first, RestClass && the_rest) inline explicit
base-class constructor; for internal use only
Definition at line 129 of file power_vector.hpp.
PowerVector() [5/5]
template<typename SubType_ , int count_> FEAT::LAFEM::PowerVector< SubType_, count_ >::PowerVector (PowerVector< SubType_, count_ > && other) inline
move CTOR
Definition at line 136 of file power_vector.hpp.
~PowerVector()
template<typename SubType_ , int count_> virtual FEAT::LAFEM::PowerVector< SubType_, count_ >::~PowerVector () inline virtual
virtual destructor
Definition at line 159 of file power_vector.hpp.
Member Function Documentation
_read_from_binary()
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::_read_from_binary (std::istream & file) inline private
read binary data of _first and _rest to file.
Definition at line 52 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_read_from_binary(), FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, and FEAT::LAFEM::fm_binary.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::_read_from_binary(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::read_from().
_write_out_binary()
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::_write_out_binary (std::ostream & file) const inline private
write binary data of _first and _rest to file.
Definition at line 62 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, FEAT::LAFEM::PowerVector< SubType_, count_ >::_write_out_binary(), and FEAT::LAFEM::fm_binary.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::_write_out_binary(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::write_out().
at() [1/2]
template<typename SubType_ , int count_> template<int i_> SubVectorType & FEAT::LAFEM::PowerVector< SubType_, count_ >::at () inline
Returns a sub-vector block.
Template Parameters
i_ The index of the sub-vector block that is to be returned.
Returns
A (const) reference to the sub-vector at position i_.
Definition at line 210 of file power_vector.hpp.
at() [2/2]
template<typename SubType_ , int count_> template<int i_> const SubVectorType & FEAT::LAFEM::PowerVector< SubType_, count_ >::at () const inline
Returns a sub-vector block.
Template Parameters
i_ The index of the sub-vector block that is to be returned.
Returns
A (const) reference to the sub-vector at position i_.
Definition at line 218 of file power_vector.hpp.
axpy()
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::axpy (const PowerVector< SubType_, count_ > & x, DataType alpha = DataType(1)) inline
Performs \(this \leftarrow \alpha\cdot x + this \).
Parameters
[in] x The first summand vector.
[in] y The second summand vector.
[in] alpha The scaling factor for x.
Definition at line 378 of file power_vector.hpp.
blocks()
template<typename SubType_ , int count_> int FEAT::LAFEM::PowerVector< SubType_, count_ >::blocks () const inline
Returns the number of blocks in this power-vector.
Definition at line 303 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::num_blocks.
bytes()
template<typename SubType_ , int count_> std::size_t FEAT::LAFEM::PowerVector< SubType_, count_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 574 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, and FEAT::LAFEM::PowerVector< SubType_, count_ >::bytes().
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::bytes().
clear()
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::clear () inline
Free all allocated arrays.
Definition at line 341 of file power_vector.hpp.
clone() [1/3]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::clone (const PowerVector< SubType_, count_ > & other) inline
Turns this vector into a clone of other.
As the default CloneMode of the underlying containers is unknown, this has to be separate.
Definition at line 194 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, and FEAT::LAFEM::PowerVector< SubType_, count_ >::clone().
clone() [2/3]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::clone (const PowerVector< SubType_, count_ > & other, CloneMode clone_mode) inline
Turns this vector into a clone of other.
Parameters
[in] clone_mode Determines the type of clone returned (shallow, weak, layout, deep)
Definition at line 182 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, and FEAT::LAFEM::PowerVector< SubType_, count_ >::clone().
clone() [3/3]
template<typename SubType_ , int count_> PowerVector FEAT::LAFEM::PowerVector< SubType_, count_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a copy of this vector.
Parameters
[in] mode Determines the type of clone returned (shallow, weak, layout, deep)
Definition at line 170 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, and FEAT::LAFEM::PowerVector< SubType_, count_ >::clone().
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::clone().
component_invert()
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::component_invert (const PowerVector< SubType_, count_ > & x, DataType alpha = DataType(1)) inline
Performs \(this_i \leftarrow \alpha / x_i \).
Parameters
[in] x The vector whose components serve as denominators.
[in] alpha The nominator.
Definition at line 405 of file power_vector.hpp.
component_product()
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::component_product (const PowerVector< SubType_, count_ > & x, const PowerVector< SubType_, count_ > & y) inline
Performs \(this_i \leftarrow x_i \cdot y_i\).
Parameters
[in] x The first factor.
[in] y The second factor.
Definition at line 390 of file power_vector.hpp.
convert()
template<typename SubType_ , int count_> template<typename SubType2_ > void FEAT::LAFEM::PowerVector< SubType_, count_ >::convert (const PowerVector< SubType2_, count_ > & other) inline
Conversion method.
Parameters
[in] other The source Vector.
Use source vector content as content of current vector
Definition at line 567 of file power_vector.hpp.
copy()
template<typename SubType_ , int count_> template<typename SubType2_ > void FEAT::LAFEM::PowerVector< SubType_, count_ >::copy (const PowerVector< SubType2_, count_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The vector to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 360 of file power_vector.hpp.
dot()
template<typename SubType_ , int count_> DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::dot (const PowerVector< SubType_, count_ > & x) const inline
Returns the dot-product of this vector and another vector.
Parameters
[in] x The second vector for the dot-product.
Definition at line 432 of file power_vector.hpp.
format() [1/2]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the vector's entries are to be set to.
Definition at line 321 of file power_vector.hpp.
References FEAT::value.
format() [2/2]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::format (Random & rng, DataType min, DataType max) inline
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 334 of file power_vector.hpp.
get() [1/2]
template<typename SubType_ , int count_> SubVectorType & FEAT::LAFEM::PowerVector< SubType_, count_ >::get (int i) inline
Returns a sub-vector block.
Parameters
[in] i The index of the sub-vector block that is to be returned.
Returns
A (const) reference to the sub-vector at position i.
Definition at line 233 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, FEAT::LAFEM::PowerVector< SubType_, count_ >::get(), and XASSERTM.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::get().
get() [2/2]
template<typename SubType_ , int count_> const SubVectorType & FEAT::LAFEM::PowerVector< SubType_, count_ >::get (int i) const inline
Returns a sub-vector block.
Parameters
[in] i The index of the sub-vector block that is to be returned.
Returns
A (const) reference to the sub-vector at position i.
Definition at line 240 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, FEAT::LAFEM::PowerVector< SubType_, count_ >::get(), and XASSERTM.
get_checkpoint_size()
template<typename SubType_ , int count_> std::uint64_t FEAT::LAFEM::PowerVector< SubType_, count_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 247 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, and FEAT::LAFEM::PowerVector< SubType_, count_ >::get_checkpoint_size().
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::get_checkpoint_size().
max_abs_element()
template<typename SubType_ , int count_> DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::max_abs_element () const inline
Retrieve the absolute maximum value of this vector.
Returns
The largest absolute value.
Definition at line 467 of file power_vector.hpp.
References FEAT::Math::max(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::max_abs_element().
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::max_abs_element().
max_element()
template<typename SubType_ , int count_> DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::max_element () const inline
Retrieve the maximum value of this vector.
Returns
The largest value.
Definition at line 487 of file power_vector.hpp.
References FEAT::Math::max(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::max_element().
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::max_element().
min_abs_element()
template<typename SubType_ , int count_> DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::min_abs_element () const inline
Retrieve the absolute minimum value of this vector.
Returns
The smallest absolute value.
Definition at line 477 of file power_vector.hpp.
References FEAT::Math::min(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::min_abs_element().
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::min_abs_element().
min_element()
template<typename SubType_ , int count_> DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::min_element () const inline
Retrieve the minimum value of this vector.
Returns
The smallest value.
Definition at line 497 of file power_vector.hpp.
References FEAT::Math::min(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::min_element().
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::min_element().
name()
template<typename SubType_ , int count_> static String FEAT::LAFEM::PowerVector< SubType_, count_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 348 of file power_vector.hpp.
References FEAT::stringify().
norm2()
template<typename SubType_ , int count_> DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::norm2 () const inline
Returns the euclid norm of this vector.
Definition at line 457 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::norm2sqr(), and FEAT::Math::sqrt().
norm2sqr()
template<typename SubType_ , int count_> DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::norm2sqr () const inline
Returns the squared euclid norm of this vector.
Definition at line 449 of file power_vector.hpp.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::norm2().
operator()() [1/2]
template<typename SubType_ , int count_> const DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::operator() (Index index) const inline
Retrieve specific PowerVector element.
Parameters
[in] index The index of the vector element.
Returns
Specific vector element.
Definition at line 509 of file power_vector.hpp.
References ASSERT, and FEAT::LAFEM::PowerVector< SubType_, count_ >::size().
operator()() [2/2]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::operator() (Index index, DataType value) inline
Set specific PowerVector element.
Parameters
[in] index The index of the vector element.
[in] value The value to be set.
Definition at line 529 of file power_vector.hpp.
References ASSERT, FEAT::LAFEM::PowerVector< SubType_, count_ >::size(), and FEAT::value.
operator=()
template<typename SubType_ , int count_> PowerVector & FEAT::LAFEM::PowerVector< SubType_, count_ >::operator= (PowerVector< SubType_, count_ > && other) inline
move-assign operator
Definition at line 143 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, and FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest.
read_from() [1/2]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::read_from (FileMode mode, const String & filename) inline
Read in vector from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 585 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::read_from().
read_from() [2/2]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::read_from (FileMode mode, std::istream & file) inline
Read in vector from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Definition at line 600 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_read_from_binary(), FEAT::LAFEM::fm_binary, FEAT::stringify(), and XABORTM.
restore_from_checkpoint_data()
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 253 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, and FEAT::LAFEM::PowerVector< SubType_, count_ >::restore_from_checkpoint_data().
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::restore_from_checkpoint_data().
scale()
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::scale (const PowerVector< SubType_, count_ > & x, DataType alpha) inline
Performs \(this \leftarrow \alpha\cdot x \).
Parameters
[in] x The vector to be scaled.
[in] alpha The scaling factor for x.
Definition at line 420 of file power_vector.hpp.
set_checkpoint_data()
template<typename SubType_ , int count_> std::uint64_t FEAT::LAFEM::PowerVector< SubType_, count_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 266 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_first, FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest, and FEAT::LAFEM::PowerVector< SubType_, count_ >::set_checkpoint_data().
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::set_checkpoint_data().
size()
template<typename SubType_ , int count_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerVector< SubType_, count_ >::size () const inline
Returns the total number of scalar entries of this power-vector.
Definition at line 310 of file power_vector.hpp.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::operator()().
triple_dot()
template<typename SubType_ , int count_> DataType FEAT::LAFEM::PowerVector< SubType_, count_ >::triple_dot (const PowerVector< SubType_, count_ > & x, const PowerVector< SubType_, count_ > & y) const inline
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
Parameters
[in] x The first vector.
[in] y The second vector.
Returns
The computed triple dot product.
Definition at line 440 of file power_vector.hpp.
write_out() [1/2]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::write_out (FileMode mode, const String & filename) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] filename The file where the vector shall be stored.
Definition at line 629 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::write_out().
write_out() [2/2]
template<typename SubType_ , int count_> void FEAT::LAFEM::PowerVector< SubType_, count_ >::write_out (FileMode mode, std::ostream & file) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
Todo:
globale liste anlegen
Definition at line 644 of file power_vector.hpp.
References FEAT::LAFEM::PowerVector< SubType_, count_ >::_write_out_binary(), FEAT::LAFEM::fm_binary, and XABORTM.
Friends And Related Function Documentation
PowerVector
template<typename SubType_ , int count_> template<typename , int > friend class PowerVector friend
Definition at line 46 of file power_vector.hpp.
operator==
template<typename SubType_ , int count_> bool operator== (const PowerVector< SubType_, count_ > & a, const PowerVector< SubType_, count_ > & b) friend
PowerVector comparison operator.
Parameters
[in] a A vector to compare with.
[in] b A vector to compare with.
Definition at line 673 of file power_vector.hpp.
Member Data Documentation
_first
template<typename SubType_ , int count_> SubVectorType FEAT::LAFEM::PowerVector< SubType_, count_ >::_first protected
the first sub-vector
Definition at line 91 of file power_vector.hpp.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::_read_from_binary(), FEAT::LAFEM::PowerVector< SubType_, count_ >::_write_out_binary(), FEAT::LAFEM::PowerVector< SubType_, count_ >::bytes(), FEAT::LAFEM::PowerVector< SubType_, count_ >::clone(), FEAT::LAFEM::PowerVector< SubType_, count_ >::get(), FEAT::LAFEM::PowerVector< SubType_, count_ >::get_checkpoint_size(), FEAT::LAFEM::PowerVector< SubType_, count_ >::operator=(), FEAT::LAFEM::PowerVector< SubType_, count_ >::restore_from_checkpoint_data(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::set_checkpoint_data().
_rest
template<typename SubType_ , int count_> RestClass FEAT::LAFEM::PowerVector< SubType_, count_ >::_rest protected
the remaining part
Definition at line 93 of file power_vector.hpp.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::_read_from_binary(), FEAT::LAFEM::PowerVector< SubType_, count_ >::_write_out_binary(), FEAT::LAFEM::PowerVector< SubType_, count_ >::bytes(), FEAT::LAFEM::PowerVector< SubType_, count_ >::clone(), FEAT::LAFEM::PowerVector< SubType_, count_ >::get(), FEAT::LAFEM::PowerVector< SubType_, count_ >::get_checkpoint_size(), FEAT::LAFEM::PowerVector< SubType_, count_ >::operator=(), FEAT::LAFEM::PowerVector< SubType_, count_ >::restore_from_checkpoint_data(), and FEAT::LAFEM::PowerVector< SubType_, count_ >::set_checkpoint_data().
num_blocks
template<typename SubType_ , int count_> constexpr int FEAT::LAFEM::PowerVector< SubType_, count_ >::num_blocks = count_ static constexpr
number of vector blocks
Definition at line 87 of file power_vector.hpp.
Referenced by FEAT::LAFEM::PowerVector< SubType_, count_ >::blocks().
The documentation for this class was generated from the following file:
kernel/lafem/power_vector.hpp