FEAT: FEAT::Statistics Class Reference
FEAT::Statistics Class Reference
Statistics collection class.
#include <statistics.hpp>
Static Public Member Functions
static void add_flops (Index flops)
Add an amount of flops to the global flop counter.
static void add_solver_expression (std::shared_ptr< Solver::ExpressionBase > expression)
static void add_time_axpy (double seconds)
static void add_time_blas2 (double seconds)
static void add_time_blas3 (double seconds)
static void add_time_mpi_execute_blas2 (double seconds)
static void add_time_mpi_execute_blas3 (double seconds)
static void add_time_mpi_execute_collective (double seconds)
static void add_time_mpi_execute_reduction (double seconds)
static void add_time_mpi_wait_blas2 (double seconds)
static void add_time_mpi_wait_blas3 (double seconds)
static void add_time_mpi_wait_collective (double seconds)
static void add_time_mpi_wait_reduction (double seconds)
static void add_time_precon (double seconds)
static void add_time_reduction (double seconds)
static void compress_solver_expressions ()
compress solver statistics (toe / defect norm / mpi timings) from previous calls
static Index get_flops ()
Retrieve current global flop counter.
static String get_formatted_flops (double seconds, int ranks=1)
Retrieve formatted flops per second string.
static String get_formatted_solver_internals (String target="default")
Retrieve formatted timings and iteration counts of internal solver structures for the provided solver target.
static String get_formatted_solver_tree (String target="default")
Returns a descriptive string of the complete solver tree.
static String get_formatted_times (double total_time)
Retrieve formatted time consumption overview in percent relative to some provided total time.
static std::list< Index > & get_iters (String target)
retrieve list of all overall solver iteration entries
static std::list< Index > & get_iters_schwarz (String target)
retrieve list of all outer schwarz solver call iteration count entries
static const std::list< std::shared_ptr< Solver::ExpressionBase > > & get_solver_expressions ()
static double get_time_axpy ()
static double get_time_blas2 ()
static double get_time_blas3 ()
static std::list< std::vector< double > > & get_time_mg (String target)
retrieve list of all overall solver toe entries per mg level
static std::list< std::vector< double > > & get_time_mg_mpi_execute_blas2 (String target)
retrieve list of all overall solver mpi execute blas2 toe entries per level
static std::list< std::vector< double > > & get_time_mg_mpi_execute_blas3 (String target)
retrieve list of all overall solver mpi execute blas3 toe entries per level
static std::list< std::vector< double > > & get_time_mg_mpi_execute_collective (String target)
retrieve list of all overall solver mpi execute collective toe entries per level
static std::list< std::vector< double > > & get_time_mg_mpi_execute_reduction (String target)
retrieve list of all overall solver mpi execute reduction toe entries per level
static std::list< std::vector< double > > & get_time_mg_mpi_wait_blas2 (String target)
retrieve list of all overall solver mpi blas2 wait toe entries per level
static std::list< std::vector< double > > & get_time_mg_mpi_wait_blas3 (String target)
retrieve list of all overall solver mpi blas3 wait toe entries per level
static std::list< std::vector< double > > & get_time_mg_mpi_wait_collective (String target)
retrieve list of all overall solver mpi collective wait toe entries per level
static std::list< std::vector< double > > & get_time_mg_mpi_wait_reduction (String target)
retrieve list of all overall solver mpi reduction wait toe entries per level
static double get_time_mpi_execute_blas2 ()
static std::list< double > & get_time_mpi_execute_blas2 (String target)
retrieve list of all overall solver mpi execute blas2 toe entries
static double get_time_mpi_execute_blas3 ()
static std::list< double > & get_time_mpi_execute_blas3 (String target)
retrieve list of all overall solver mpi execute blas3 toe entries
static double get_time_mpi_execute_collective ()
static std::list< double > & get_time_mpi_execute_collective (String target)
retrieve list of all overall solver mpi execute collective toe entries
static double get_time_mpi_execute_reduction ()
static std::list< double > & get_time_mpi_execute_reduction (String target)
retrieve list of all overall solver mpi execute reduction toe entries
static double get_time_mpi_wait_blas2 ()
static std::list< double > & get_time_mpi_wait_blas2 (String target)
retrieve list of all overall solver mpi blas2 wait toe entries
static double get_time_mpi_wait_blas3 ()
static std::list< double > & get_time_mpi_wait_blas3 (String target)
retrieve list of all overall solver mpi blas3 wait toe entries
static double get_time_mpi_wait_collective ()
static std::list< double > & get_time_mpi_wait_collective (String target)
retrieve list of all overall solver mpi collective wait toe entries
static double get_time_mpi_wait_reduction ()
static std::list< double > & get_time_mpi_wait_reduction (String target)
retrieve list of all overall solver mpi reduction wait toe entries
static double get_time_precon ()
static double get_time_reduction ()
static std::list< double > & get_time_schwarz (String target)
retrieve list of all outer schwarz solver call toe entries
static std::list< double > & get_time_toe (String target)
retrieve list of all overall solver toe entries
static void print_solver_expressions ()
print out the complete solver expression list
static void reset ()
Reset all internal counters (flops/times/solver_statistics)
static void reset_flops ()
Reset global flop counter.
static void reset_times ()
Reset all global timer counters.
Static Public Attributes
static bool enable_solver_expressions = false
specifies whether collection of solver expressions is to be enabled
static String expression_target = "default"
the current solver's descriptive string
static double toe_assembly
time of assembly in seconds, needs initialization
static double toe_partition
time of partitioning in seconds, needs initialization
static double toe_solve
time of solution in seconds, needs initialization
Static Private Member Functions
static String _generate_formatted_solver_tree (String target)
Static Private Attributes
static Index _flops = Index(0)
global flop counter
static std::map< String, String > _formatted_solver_trees
mapping of solver target name to formatted solver tree string
static std::map< String, std::list< std::vector< double > > > _outer_mg_mpi_execute_blas2
static std::map< String, std::list< std::vector< double > > > _outer_mg_mpi_execute_blas3
static std::map< String, std::list< std::vector< double > > > _outer_mg_mpi_execute_collective
static std::map< String, std::list< std::vector< double > > > _outer_mg_mpi_execute_reduction
static std::map< String, std::list< std::vector< double > > > _outer_mg_mpi_wait_blas2
static std::map< String, std::list< std::vector< double > > > _outer_mg_mpi_wait_blas3
static std::map< String, std::list< std::vector< double > > > _outer_mg_mpi_wait_collective
static std::map< String, std::list< std::vector< double > > > _outer_mg_mpi_wait_reduction
static std::map< String, std::list< std::vector< double > > > _outer_mg_toe
mapping of solver name to list of outer multigrid level timings. each std::vector holds a complete level hierarchy of timings.
static std::map< String, std::list< Index > > _outer_schwarz_iters
overall iterations of outer schwarz preconditioners internal solver
static std::map< String, std::list< double > > _outer_schwarz_toe
overall time of outer schwarz preconditioners internal solver
static std::map< String, std::list< Index > > _overall_iters
static std::map< String, std::list< double > > _overall_mpi_execute_blas2
static std::map< String, std::list< double > > _overall_mpi_execute_blas3
static std::map< String, std::list< double > > _overall_mpi_execute_collective
static std::map< String, std::list< double > > _overall_mpi_execute_reduction
static std::map< String, std::list< double > > _overall_mpi_wait_blas2
static std::map< String, std::list< double > > _overall_mpi_wait_blas3
static std::map< String, std::list< double > > _overall_mpi_wait_collective
static std::map< String, std::list< double > > _overall_mpi_wait_reduction
static std::map< String, std::list< double > > _overall_toe
overall time per reset call per solver name string.
static std::map< String, std::list< std::shared_ptr< Solver::ExpressionBase > > > _solver_expressions
a consecutive list of all solver actions
static KahanAccumulation _time_axpy
global time of execution for blas-1 type operations
static KahanAccumulation _time_blas2
global time of execution for blas-2 type operations
static KahanAccumulation _time_blas3
global time of execution for blas-3 type operations
static KahanAccumulation _time_mpi_execute_blas2
global time of execution for mpi related idle/wait tasks of blas-2 operations
static KahanAccumulation _time_mpi_execute_blas3
global time of execution for mpi related idle/wait tasks of blas-3 operations
static KahanAccumulation _time_mpi_execute_collective
global time of execution for mpi related idle/wait tasks of collective operations (without scalar reduction)
static KahanAccumulation _time_mpi_execute_reduction
global time of execution for mpi related idle/wait tasks of (scalar) reduction operations
static KahanAccumulation _time_mpi_wait_blas2
global time of wait execution for mpi related idle/wait tasks of blas2 operations
static KahanAccumulation _time_mpi_wait_blas3
global time of wait execution for mpi related idle/wait tasks of blas3 operations
static KahanAccumulation _time_mpi_wait_collective
global time of wait execution for mpi related idle/wait tasks of collective operations (without scalar reduction)
static KahanAccumulation _time_mpi_wait_reduction
global time of wait execution for mpi related idle/wait tasks of (scalar) reduction operations
static KahanAccumulation _time_precon
global time of execution for special preconditioner kernel type operations
static KahanAccumulation _time_reduction
global time of execution for reduction type operations
Detailed Description
Statistics collection class.
The class Statistics encapsulates various hardware counters, that collects e.g. the accumulated flop count of an linear solver.
Definition at line 31 of file statistics.hpp.
Member Function Documentation
_generate_formatted_solver_tree()
String Statistics::_generate_formatted_solver_tree (String target) static private
Definition at line 59 of file statistics.cpp.
add_flops()
static void FEAT::Statistics::add_flops (Index flops) inline static
Add an amount of flops to the global flop counter.
Definition at line 208 of file statistics.hpp.
References _flops.
Referenced by FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_diag(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_full(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, Filter_ >::apply(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::axpy(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_invert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_product(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::dot(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::invert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::norm2(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::scale(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot(), and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::triple_dot().
add_solver_expression()
static void FEAT::Statistics::add_solver_expression (std::shared_ptr< Solver::ExpressionBase > expression) inline static
Definition at line 342 of file statistics.hpp.
add_time_axpy()
static void FEAT::Statistics::add_time_axpy (double seconds) inline static
Definition at line 248 of file statistics.hpp.
add_time_blas2()
static void FEAT::Statistics::add_time_blas2 (double seconds) inline static
Definition at line 240 of file statistics.hpp.
add_time_blas3()
static void FEAT::Statistics::add_time_blas3 (double seconds) inline static
Definition at line 244 of file statistics.hpp.
add_time_mpi_execute_blas2()
static void FEAT::Statistics::add_time_mpi_execute_blas2 (double seconds) inline static
Definition at line 260 of file statistics.hpp.
add_time_mpi_execute_blas3()
static void FEAT::Statistics::add_time_mpi_execute_blas3 (double seconds) inline static
Definition at line 264 of file statistics.hpp.
add_time_mpi_execute_collective()
static void FEAT::Statistics::add_time_mpi_execute_collective (double seconds) inline static
Definition at line 268 of file statistics.hpp.
add_time_mpi_execute_reduction()
static void FEAT::Statistics::add_time_mpi_execute_reduction (double seconds) inline static
Definition at line 256 of file statistics.hpp.
add_time_mpi_wait_blas2()
static void FEAT::Statistics::add_time_mpi_wait_blas2 (double seconds) inline static
Definition at line 276 of file statistics.hpp.
add_time_mpi_wait_blas3()
static void FEAT::Statistics::add_time_mpi_wait_blas3 (double seconds) inline static
Definition at line 280 of file statistics.hpp.
add_time_mpi_wait_collective()
static void FEAT::Statistics::add_time_mpi_wait_collective (double seconds) inline static
Definition at line 284 of file statistics.hpp.
add_time_mpi_wait_reduction()
static void FEAT::Statistics::add_time_mpi_wait_reduction (double seconds) inline static
Definition at line 272 of file statistics.hpp.
add_time_precon()
static void FEAT::Statistics::add_time_precon (double seconds) inline static
Definition at line 252 of file statistics.hpp.
add_time_reduction()
static void FEAT::Statistics::add_time_reduction (double seconds) inline static
Definition at line 236 of file statistics.hpp.
compress_solver_expressions()
void Statistics::compress_solver_expressions () static
compress solver statistics (toe / defect norm / mpi timings) from previous calls
Definition at line 866 of file statistics.cpp.
References _formatted_solver_trees, _outer_mg_toe, _outer_schwarz_iters, _outer_schwarz_toe, _overall_toe, _solver_expressions, FEAT::Solver::end_solve, FEAT::Solver::level_timings, FEAT::Solver::start_solve, FEAT::Solver::timings, and XABORTM.
Referenced by get_formatted_solver_internals(), and get_formatted_solver_tree().
get_flops()
static Index FEAT::Statistics::get_flops () inline static
Retrieve current global flop counter.
Definition at line 214 of file statistics.hpp.
References _flops.
get_formatted_flops()
static String FEAT::Statistics::get_formatted_flops (double seconds, int ranks = 1) inline static
Retrieve formatted flops per second string.
Definition at line 220 of file statistics.hpp.
References _flops, and FEAT::stringify().
Referenced by FEAT::Control::Statistics::report().
get_formatted_solver_internals()
String Statistics::get_formatted_solver_internals (String target = "default") static
Retrieve formatted timings and iteration counts of internal solver structures for the provided solver target.
Definition at line 558 of file statistics.cpp.
References _formatted_solver_trees, FEAT::Dist::Comm::allreduce(), compress_solver_expressions(), get_iters(), get_iters_schwarz(), get_time_mg(), get_time_mg_mpi_execute_blas2(), get_time_mg_mpi_execute_blas3(), get_time_mg_mpi_execute_collective(), get_time_mg_mpi_execute_reduction(), get_time_mg_mpi_wait_blas2(), get_time_mg_mpi_wait_blas3(), get_time_mg_mpi_wait_collective(), get_time_mg_mpi_wait_reduction(), get_time_schwarz(), get_time_toe(), FEAT::Dist::op_max, FEAT::Dist::op_min, FEAT::String::pad_back(), FEAT::stringify(), FEAT::Dist::Comm::world(), and XASSERT.
get_formatted_solver_tree()
static String FEAT::Statistics::get_formatted_solver_tree (String target = "default") inline static
Returns a descriptive string of the complete solver tree.
Create and format a string describing the complete solver tree.
Note
This method makes some simplifications, e.g. stating only one smoother for the complete FEAT::Solver::BasicVCycle.
The solver must have been executed (successfully) at least one time, to make the solver tree available.
Definition at line 363 of file statistics.hpp.
References _formatted_solver_trees, and compress_solver_expressions().
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), and FEAT::Control::Statistics::report().
get_formatted_times()
String Statistics::get_formatted_times (double total_time) static
Retrieve formatted time consumption overview in percent relative to some provided total time.
Note
This method uses mpi collectives and thus needs to be called by all ranks, even if you don't use the result on every rank on your own.
Definition at line 473 of file statistics.cpp.
References FEAT::Dist::Comm::allreduce(), FEAT::KahanSum(), FEAT::Dist::op_max, FEAT::Dist::op_min, FEAT::String::pad_back(), FEAT::stringify(), and FEAT::Dist::Comm::world().
Referenced by FEAT::Control::Statistics::report().
get_iters()
static std::list< Index > & FEAT::Statistics::get_iters (String target) inline static
retrieve list of all overall solver iteration entries
Definition at line 386 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_iters_schwarz()
static std::list< Index > & FEAT::Statistics::get_iters_schwarz (String target) inline static
retrieve list of all outer schwarz solver call iteration count entries
Definition at line 500 of file statistics.hpp.
References _outer_schwarz_iters.
Referenced by get_formatted_solver_internals().
get_solver_expressions()
static const std::list< std::shared_ptr< Solver::ExpressionBase > > & FEAT::Statistics::get_solver_expressions () inline static
Definition at line 348 of file statistics.hpp.
get_time_axpy()
static double FEAT::Statistics::get_time_axpy () inline static
Definition at line 301 of file statistics.hpp.
get_time_blas2()
static double FEAT::Statistics::get_time_blas2 () inline static
Definition at line 293 of file statistics.hpp.
get_time_blas3()
static double FEAT::Statistics::get_time_blas3 () inline static
Definition at line 297 of file statistics.hpp.
get_time_mg()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg (String target) inline static
retrieve list of all overall solver toe entries per mg level
Definition at line 440 of file statistics.hpp.
References _outer_mg_toe.
Referenced by get_formatted_solver_internals().
get_time_mg_mpi_execute_blas2()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg_mpi_execute_blas2 (String target) inline static
retrieve list of all overall solver mpi execute blas2 toe entries per level
Definition at line 452 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_time_mg_mpi_execute_blas3()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg_mpi_execute_blas3 (String target) inline static
retrieve list of all overall solver mpi execute blas3 toe entries per level
Definition at line 458 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_time_mg_mpi_execute_collective()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg_mpi_execute_collective (String target) inline static
retrieve list of all overall solver mpi execute collective toe entries per level
Definition at line 464 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_time_mg_mpi_execute_reduction()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg_mpi_execute_reduction (String target) inline static
retrieve list of all overall solver mpi execute reduction toe entries per level
Definition at line 446 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_time_mg_mpi_wait_blas2()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg_mpi_wait_blas2 (String target) inline static
retrieve list of all overall solver mpi blas2 wait toe entries per level
Definition at line 476 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_time_mg_mpi_wait_blas3()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg_mpi_wait_blas3 (String target) inline static
retrieve list of all overall solver mpi blas3 wait toe entries per level
Definition at line 482 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_time_mg_mpi_wait_collective()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg_mpi_wait_collective (String target) inline static
retrieve list of all overall solver mpi collective wait toe entries per level
Definition at line 488 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_time_mg_mpi_wait_reduction()
static std::list< std::vector< double > > & FEAT::Statistics::get_time_mg_mpi_wait_reduction (String target) inline static
retrieve list of all overall solver mpi reduction wait toe entries per level
Definition at line 470 of file statistics.hpp.
Referenced by get_formatted_solver_internals().
get_time_mpi_execute_blas2() [1/2]
static double FEAT::Statistics::get_time_mpi_execute_blas2 () inline static
Definition at line 313 of file statistics.hpp.
get_time_mpi_execute_blas2() [2/2]
static std::list< double > & FEAT::Statistics::get_time_mpi_execute_blas2 (String target) inline static
retrieve list of all overall solver mpi execute blas2 toe entries
Definition at line 398 of file statistics.hpp.
get_time_mpi_execute_blas3() [1/2]
static double FEAT::Statistics::get_time_mpi_execute_blas3 () inline static
Definition at line 317 of file statistics.hpp.
get_time_mpi_execute_blas3() [2/2]
static std::list< double > & FEAT::Statistics::get_time_mpi_execute_blas3 (String target) inline static
retrieve list of all overall solver mpi execute blas3 toe entries
Definition at line 404 of file statistics.hpp.
get_time_mpi_execute_collective() [1/2]
static double FEAT::Statistics::get_time_mpi_execute_collective () inline static
Definition at line 321 of file statistics.hpp.
get_time_mpi_execute_collective() [2/2]
static std::list< double > & FEAT::Statistics::get_time_mpi_execute_collective (String target) inline static
retrieve list of all overall solver mpi execute collective toe entries
Definition at line 410 of file statistics.hpp.
get_time_mpi_execute_reduction() [1/2]
static double FEAT::Statistics::get_time_mpi_execute_reduction () inline static
Definition at line 309 of file statistics.hpp.
get_time_mpi_execute_reduction() [2/2]
static std::list< double > & FEAT::Statistics::get_time_mpi_execute_reduction (String target) inline static
retrieve list of all overall solver mpi execute reduction toe entries
Definition at line 392 of file statistics.hpp.
get_time_mpi_wait_blas2() [1/2]
static double FEAT::Statistics::get_time_mpi_wait_blas2 () inline static
Definition at line 329 of file statistics.hpp.
get_time_mpi_wait_blas2() [2/2]
static std::list< double > & FEAT::Statistics::get_time_mpi_wait_blas2 (String target) inline static
retrieve list of all overall solver mpi blas2 wait toe entries
Definition at line 422 of file statistics.hpp.
get_time_mpi_wait_blas3() [1/2]
static double FEAT::Statistics::get_time_mpi_wait_blas3 () inline static
Definition at line 333 of file statistics.hpp.
get_time_mpi_wait_blas3() [2/2]
static std::list< double > & FEAT::Statistics::get_time_mpi_wait_blas3 (String target) inline static
retrieve list of all overall solver mpi blas3 wait toe entries
Definition at line 428 of file statistics.hpp.
get_time_mpi_wait_collective() [1/2]
static double FEAT::Statistics::get_time_mpi_wait_collective () inline static
Definition at line 337 of file statistics.hpp.
get_time_mpi_wait_collective() [2/2]
static std::list< double > & FEAT::Statistics::get_time_mpi_wait_collective (String target) inline static
retrieve list of all overall solver mpi collective wait toe entries
Definition at line 434 of file statistics.hpp.
get_time_mpi_wait_reduction() [1/2]
static double FEAT::Statistics::get_time_mpi_wait_reduction () inline static
Definition at line 325 of file statistics.hpp.
get_time_mpi_wait_reduction() [2/2]
static std::list< double > & FEAT::Statistics::get_time_mpi_wait_reduction (String target) inline static
retrieve list of all overall solver mpi reduction wait toe entries
Definition at line 416 of file statistics.hpp.
get_time_precon()
static double FEAT::Statistics::get_time_precon () inline static
Definition at line 305 of file statistics.hpp.
get_time_reduction()
static double FEAT::Statistics::get_time_reduction () inline static
Definition at line 289 of file statistics.hpp.
get_time_schwarz()
static std::list< double > & FEAT::Statistics::get_time_schwarz (String target) inline static
retrieve list of all outer schwarz solver call toe entries
Definition at line 494 of file statistics.hpp.
References _outer_schwarz_toe.
Referenced by get_formatted_solver_internals().
get_time_toe()
static std::list< double > & FEAT::Statistics::get_time_toe (String target) inline static
retrieve list of all overall solver toe entries
Definition at line 380 of file statistics.hpp.
References _overall_toe.
Referenced by get_formatted_solver_internals().
print_solver_expressions()
void Statistics::print_solver_expressions () static
print out the complete solver expression list
Definition at line 355 of file statistics.cpp.
References _solver_expressions, FEAT::Solver::call_coarse_solver, FEAT::Solver::call_precond, FEAT::Solver::call_precond_l, FEAT::Solver::call_precond_r, FEAT::Solver::call_smoother, FEAT::Solver::call_uzawa_a, FEAT::Solver::call_uzawa_s, FEAT::Solver::defect, FEAT::Solver::end_solve, expression_target, FEAT::Solver::level_timings, FEAT::Solver::prol, FEAT::Solver::rest, FEAT::Solver::start_solve, FEAT::stringify(), and FEAT::Solver::timings.
reset()
static void FEAT::Statistics::reset () inline static
Reset all internal counters (flops/times/solver_statistics)
Definition at line 179 of file statistics.hpp.
References _outer_mg_toe, _outer_schwarz_iters, _outer_schwarz_toe, _overall_toe, _solver_expressions, reset_flops(), and reset_times().
reset_flops()
static void FEAT::Statistics::reset_flops () inline static
Reset global flop counter.
Definition at line 231 of file statistics.hpp.
References _flops.
Referenced by reset().
reset_times()
static void FEAT::Statistics::reset_times () inline static
Reset all global timer counters.
Definition at line 516 of file statistics.hpp.
References _time_axpy, _time_blas2, _time_blas3, _time_mpi_execute_blas2, _time_mpi_execute_blas3, _time_mpi_execute_collective, _time_mpi_execute_reduction, _time_mpi_wait_blas2, _time_mpi_wait_blas3, _time_mpi_wait_collective, _time_mpi_wait_reduction, _time_precon, and _time_reduction.
Referenced by reset().
Member Data Documentation
_flops
Index Statistics::_flops = Index(0) static private
global flop counter
Definition at line 36 of file statistics.hpp.
Referenced by add_flops(), get_flops(), get_formatted_flops(), and reset_flops().
_formatted_solver_trees
std::map< String, String > Statistics::_formatted_solver_trees static private
mapping of solver target name to formatted solver tree string
Definition at line 81 of file statistics.hpp.
Referenced by compress_solver_expressions(), get_formatted_solver_internals(), and get_formatted_solver_tree().
_outer_mg_mpi_execute_blas2
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_mpi_execute_blas2 static private
Definition at line 97 of file statistics.hpp.
_outer_mg_mpi_execute_blas3
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_mpi_execute_blas3 static private
Definition at line 98 of file statistics.hpp.
_outer_mg_mpi_execute_collective
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_mpi_execute_collective static private
Definition at line 99 of file statistics.hpp.
_outer_mg_mpi_execute_reduction
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_mpi_execute_reduction static private
Definition at line 96 of file statistics.hpp.
_outer_mg_mpi_wait_blas2
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_mpi_wait_blas2 static private
Definition at line 101 of file statistics.hpp.
_outer_mg_mpi_wait_blas3
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_mpi_wait_blas3 static private
Definition at line 102 of file statistics.hpp.
_outer_mg_mpi_wait_collective
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_mpi_wait_collective static private
Definition at line 103 of file statistics.hpp.
_outer_mg_mpi_wait_reduction
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_mpi_wait_reduction static private
Definition at line 100 of file statistics.hpp.
_outer_mg_toe
std::map< String, std::list< std::vector< double > > > Statistics::_outer_mg_toe static private
mapping of solver name to list of outer multigrid level timings. each std::vector holds a complete level hierarchy of timings.
Definition at line 95 of file statistics.hpp.
Referenced by compress_solver_expressions(), get_time_mg(), and reset().
_outer_schwarz_iters
std::map< String, std::list< Index > > Statistics::_outer_schwarz_iters static private
overall iterations of outer schwarz preconditioners internal solver
Definition at line 107 of file statistics.hpp.
Referenced by compress_solver_expressions(), get_iters_schwarz(), and reset().
_outer_schwarz_toe
std::map< String, std::list< double > > Statistics::_outer_schwarz_toe static private
overall time of outer schwarz preconditioners internal solver
Definition at line 105 of file statistics.hpp.
Referenced by compress_solver_expressions(), get_time_schwarz(), and reset().
_overall_iters
std::map< String, std::list< Index > > Statistics::_overall_iters static private
Definition at line 85 of file statistics.hpp.
_overall_mpi_execute_blas2
std::map< String, std::list< double > > Statistics::_overall_mpi_execute_blas2 static private
Definition at line 87 of file statistics.hpp.
_overall_mpi_execute_blas3
std::map< String, std::list< double > > Statistics::_overall_mpi_execute_blas3 static private
Definition at line 88 of file statistics.hpp.
_overall_mpi_execute_collective
std::map< String, std::list< double > > Statistics::_overall_mpi_execute_collective static private
Definition at line 89 of file statistics.hpp.
_overall_mpi_execute_reduction
std::map< String, std::list< double > > Statistics::_overall_mpi_execute_reduction static private
Definition at line 86 of file statistics.hpp.
_overall_mpi_wait_blas2
std::map< String, std::list< double > > Statistics::_overall_mpi_wait_blas2 static private
Definition at line 91 of file statistics.hpp.
_overall_mpi_wait_blas3
std::map< String, std::list< double > > Statistics::_overall_mpi_wait_blas3 static private
Definition at line 92 of file statistics.hpp.
_overall_mpi_wait_collective
std::map< String, std::list< double > > Statistics::_overall_mpi_wait_collective static private
Definition at line 93 of file statistics.hpp.
_overall_mpi_wait_reduction
std::map< String, std::list< double > > Statistics::_overall_mpi_wait_reduction static private
Definition at line 90 of file statistics.hpp.
_overall_toe
std::map< String, std::list< double > > Statistics::_overall_toe static private
overall time per reset call per solver name string.
Definition at line 84 of file statistics.hpp.
Referenced by compress_solver_expressions(), get_time_toe(), and reset().
_solver_expressions
std::map< String, std::list< std::shared_ptr< Solver::ExpressionBase > > > Statistics::_solver_expressions static private
a consecutive list of all solver actions
Definition at line 78 of file statistics.hpp.
Referenced by compress_solver_expressions(), print_solver_expressions(), and reset().
_time_axpy
KahanAccumulation Statistics::_time_axpy static private
global time of execution for blas-1 type operations
Definition at line 48 of file statistics.hpp.
Referenced by reset_times().
_time_blas2
KahanAccumulation Statistics::_time_blas2 static private
global time of execution for blas-2 type operations
Definition at line 42 of file statistics.hpp.
Referenced by reset_times().
_time_blas3
KahanAccumulation Statistics::_time_blas3 static private
global time of execution for blas-3 type operations
Definition at line 45 of file statistics.hpp.
Referenced by reset_times().
_time_mpi_execute_blas2
KahanAccumulation Statistics::_time_mpi_execute_blas2 static private
global time of execution for mpi related idle/wait tasks of blas-2 operations
Definition at line 57 of file statistics.hpp.
Referenced by reset_times().
_time_mpi_execute_blas3
KahanAccumulation Statistics::_time_mpi_execute_blas3 static private
global time of execution for mpi related idle/wait tasks of blas-3 operations
Definition at line 60 of file statistics.hpp.
Referenced by reset_times().
_time_mpi_execute_collective
KahanAccumulation Statistics::_time_mpi_execute_collective static private
global time of execution for mpi related idle/wait tasks of collective operations (without scalar reduction)
Definition at line 63 of file statistics.hpp.
Referenced by reset_times().
_time_mpi_execute_reduction
KahanAccumulation Statistics::_time_mpi_execute_reduction static private
global time of execution for mpi related idle/wait tasks of (scalar) reduction operations
Definition at line 54 of file statistics.hpp.
Referenced by reset_times().
_time_mpi_wait_blas2
KahanAccumulation Statistics::_time_mpi_wait_blas2 static private
global time of wait execution for mpi related idle/wait tasks of blas2 operations
Definition at line 69 of file statistics.hpp.
Referenced by reset_times().
_time_mpi_wait_blas3
KahanAccumulation Statistics::_time_mpi_wait_blas3 static private
global time of wait execution for mpi related idle/wait tasks of blas3 operations
Definition at line 72 of file statistics.hpp.
Referenced by reset_times().
_time_mpi_wait_collective
KahanAccumulation Statistics::_time_mpi_wait_collective static private
global time of wait execution for mpi related idle/wait tasks of collective operations (without scalar reduction)
Definition at line 75 of file statistics.hpp.
Referenced by reset_times().
_time_mpi_wait_reduction
KahanAccumulation Statistics::_time_mpi_wait_reduction static private
global time of wait execution for mpi related idle/wait tasks of (scalar) reduction operations
Definition at line 66 of file statistics.hpp.
Referenced by reset_times().
_time_precon
KahanAccumulation Statistics::_time_precon static private
global time of execution for special preconditioner kernel type operations
Definition at line 51 of file statistics.hpp.
Referenced by reset_times().
_time_reduction
KahanAccumulation Statistics::_time_reduction static private
global time of execution for reduction type operations
Definition at line 39 of file statistics.hpp.
Referenced by reset_times().
enable_solver_expressions
bool Statistics::enable_solver_expressions = false static
specifies whether collection of solver expressions is to be enabled
Definition at line 167 of file statistics.hpp.
expression_target
String Statistics::expression_target = "default" static
the current solver's descriptive string
Definition at line 175 of file statistics.hpp.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize(), and print_solver_expressions().
toe_assembly
double Statistics::toe_assembly static
time of assembly in seconds, needs initialization
Definition at line 171 of file statistics.hpp.
Referenced by FEAT::Control::Statistics::report().
toe_partition
double Statistics::toe_partition static
time of partitioning in seconds, needs initialization
Definition at line 169 of file statistics.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_rectilinear(), and FEAT::Control::Statistics::report().
toe_solve
double Statistics::toe_solve static
time of solution in seconds, needs initialization
Definition at line 173 of file statistics.hpp.
Referenced by FEAT::Control::Statistics::report().
The documentation for this class was generated from the following files:
kernel/util/statistics.hpp
kernel/util/statistics.cpp