FEAT: FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ > Class Template Reference
FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ > Class Template Reference
Algebraic DOF partitioning linear system conversion class.
#include <alg_dof_parti_system.hpp>
Public Types
typedef Intern::ADPFilAux< LocalFilterType > ADPFilAuxType
typedef Intern::ADPMatAux< LocalMatrixType > ADPMatAuxType
typedef Global::AlgDofParti< LocalVectorType, MirrorType > AlgDofPartiType
the algebraic DOF partitioning
typedef LAFEM::MatrixMirrorBuffer< DataType, IndexType > BufferMatrixType
the buffer matrix type used for communication
typedef LAFEM::DenseVector< DataType, IndexType > BufferVectorType
the buffer vector type used for communication
typedef LocalMatrix_::DataType DataType
our data type
typedef LAFEM::VectorMirror< DataType, IndexType > DoneeMirrorType
donee neighbor mirror type
typedef Global::Filter< LocalFilterType, MirrorType > GlobalFilterType
the global filter type
typedef Global::Matrix< LocalMatrixType, MirrorType, MirrorType > GlobalMatrixType
the global matrix type
typedef LocalMatrix_::IndexType IndexType
our index type
typedef AlgDofPartiType::IndexVectorType IndexVectorType
auxiliary index vector type
typedef LocalFilter_ LocalFilterType
the local filter type
typedef LocalMatrix_ LocalMatrixType
the local matrix type
typedef LocalMatrixType::VectorTypeR LocalVectorType
the local vector type
typedef Mirror_ MirrorType
the vector mirror type
typedef LAFEM::SparseMatrixCSR< DataType, IndexType > OwnedMatrixType
the matrix type used for the internal storage of our owned matrix rows
typedef Intern::ADPDOMM< LocalMatrixType > OwnerMirrorType
owner neighbor mirror type
Public Member Functions
AlgDofPartiSystem (const AlgDofPartiSystem &)=delete
no copy, no problems
AlgDofPartiSystem (const GlobalMatrixType &matrix, const GlobalFilterType &filter)
Constructor.
AlgDofPartiSystem (const GlobalMatrixType &matrix, const GlobalFilterType &filter, std::shared_ptr< AlgDofPartiType > adp)
Constructor.
template<typename DTX_ , typename RPT_ , typename CIT_ >
void apply (DTX_ *vec_r, const DTX_ *vec_x, const DTX_ *val_a, const RPT_ *row_ptr, const CIT_ *col_idx) const
Performs a global matrix-vector product with this matrix.
std::size_t bytes () const
template<typename DTV_ >
void download_vector (LocalVectorType &vector, const DTV_ *val)
Downloads the ADP vector values from the given array.
template<typename DTA_ , typename RPT_ , typename CIT_ >
void filter_matrix (DTA_ *val, const RPT_ *row_ptr, const CIT_ *col_idx)
Applies the ADP filter onto an ADP matrix.
template<typename DTV_ >
void filter_vec_cor (DTV_ *vec_cor)
Applies the ADP filter onto an ADP correction vector.
template<typename DTV_ >
void filter_vec_def (DTV_ *vec_def)
Applies the ADP filter onto an ADP defect vector.
Index get_adp_matrix_cols () const
Index get_adp_matrix_nzes () const
Index get_adp_matrix_rows () const
Index get_adp_vector_size () const
std::shared_ptr< AlgDofPartiType > get_alg_dof_parti ()
Returns the algebraic dof partitioning that is used internally.
const Dist::Comm * get_comm () const
Index get_global_dof_offset () const
Index get_num_global_dofs () const
Index get_num_global_nonzeros () const
Index get_num_owned_dofs () const
void init_symbolic ()
Performs the symbolic initialization.
AlgDofPartiSystem & operator= (const AlgDofPartiSystem &)=delete
no copy, no problems
void upload_filter ()
Uploads the values of the system filter to the ADP system.
void upload_filter (const LocalFilterType &filter)
Uploads the values of the given filter to the ADP system.
template<typename DTA_ , typename RPT_ , typename CIT_ >
void upload_matrix_numeric (DTA_ *val, const RPT_ *row_ptr, const CIT_ *col_idx)
Uploads the data value array of the ADP CSR system matrix.
template<typename DTA_ , typename RPT_ , typename CIT_ >
void upload_matrix_numeric (DTA_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LocalMatrixType &matrix)
Copies the matrix entry values from the input matrix into this algebraic-dof-partitioned matrix.
template<typename RPT_ , typename CIT_ >
void upload_matrix_symbolic (RPT_ *row_ptr, CIT_ *col_idx, bool keep_graph=false)
Uploads the row-pointer and column-index arrays of the ADP CSR system matrix.
template<typename DTV_ >
void upload_vector (DTV_ *val, const LocalVectorType &vector)
Uploads the ADP vector values to the given array.
Public Attributes
std::shared_ptr< AlgDofPartiType > _alg_dof_parti
the algebraic dof-partitioning
std::vector< BufferMatrixType > _donee_bufs
the matrix buffers for our donee and owner neighbors; both buffers use global DOF indices
std::vector< DoneeMirrorType > _donee_data_mirs
the data array mirrors for our donee and owner neighbors
const GlobalFilterType & _global_filter
the global filter that we want to convert
const GlobalMatrixType & _global_matrix
the global matrix that we want to convert
Index _num_global_non_zeros
number of non-zero entries in total
Index _num_owned_non_zeros
number of non-zero entries owned by this process
OwnerMirrorType _owned_data_mir
the data array mirror for this process
std::shared_ptr< Adjacency::Graph > _owned_graph
adjacency graph containing the owned matrix structure
std::vector< BufferMatrixType > _owner_bufs
std::vector< OwnerMirrorType > _owner_data_mirs
LAFEM::UnitFilter< DataType, IndexType > _unit_filter_rows
indices of all unit-filtered matrix rows; we store this as a mirror
Protected Member Functions
void _assemble_buffers ()
Assembles the owner and donee matrix buffers.
void _assemble_data_mirrors ()
Assembles the data-mirrors for all owner- and donee-neighbors.
void _assemble_structure ()
Assembles the matrix structure of the algebraic-DOF-partitioned matrix.
Static Protected Member Functions
static BufferMatrixType _asm_mat_buf (const LocalMatrixType &local_matrix, const MirrorType &row_mirror, const IndexVectorType &global_dof_idx, const Index num_global_dofs)
Assembles a matrix buffer for a given row mirror.
static void _asm_neighbor_donee_data_mir (DoneeMirrorType &data_mirror, const Adjacency::Graph &owned_graph, const DoneeMirrorType &mirror, const BufferMatrixType &buffer)
Auxiliary function: assembles a data-mirror for a donee-neighbor.
template<typename DTA_ >
static void _scatter_donee_data (DTA_ *adp_val, const BufferVectorType &buffer, const DoneeMirrorType &data_mirror)
Scatters the values of a donee-neighbor buffer-vector into a local matrix.
Detailed Description
template<typename LocalMatrix_, typename LocalFilter_, typename Mirror_>
class FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >
Algebraic DOF partitioning linear system conversion class.
This class implements the functionality that is required to convert a linear system represented by a global system matrix, a global system filter and a global RHS vector from the domain decomposition approach to a row-wise partitioned global CSR (RPG-CSR) system based on the algebraic dof-partitioning, which can then be used as input for various MPI-parallel third-party library solvers.
This class is used by the Solver::ADPSolverBase class to do the dirty work of actually converting the linear system. Unless you intend to work with the ADP system conversion on a lower level yourself, it is recommended to work with the Solver::ADPSolverBase class rather than this class directly.
This class is implemented in a way that the user has to allocate and manage the necessary arrays of the RPG-CSR matrix as well as the vectors manually, whereas this class only offers functions that determine the dimensions of the corresponding arrays as well as functions that fill the arrays with the proper entries.
In the context of this class, the term upload always refers to the conversion of data from the Global::Matrix, Global::Filter and/or Global::Vector objects to their corresponding ADP array counterparts, whereas download refers to the conversion of an ADP vector array to its corresponding Global::Vector object counterpart.
This class is meant to be used as follows:
Create an object of this class for a given system matrix and system filter object. Optionally, you can also specify an already assembled Global::AlgDofParti object to the constructor, which obviously has to match the system matrix structure.
Once the matrix structure is assembled, call the init_symbolic() function. If you did not pass an AlgDofParti object to the constructor of this class, then a new AlgDofParti object will be created internally based on the row-gate of the system matrix during this phase automatically.
Allocate the following arrays for the linear system:
An integer row-pointer array of length get_adp_matrix_rows()+1 entries.
An integer column-index array of length get_adp_matrix_nzes() entries.
A floating point matrix value array of length get_adp_matrix_nzes() entries.
One or two ADP vector value arrays of length get_num_owned_dofs() entries.
Fill the row-pointer and column-index arrays by calling the upload_matrix_symbolic() function.
Once the system matrix values are assembled, fill the matrix values array by calling the upload_matrix_numeric() function.
Once the system filter values are assembled, upload the filter values to the ADP system by calling the upload_filter() function.
Once both the matrix and filter values have been uploaded (note that both of these steps are independent of each other and can be performed in any order), apply the uploaded filter to the matrix value array by calling the filter_matrix() function.
Once the system defect vector is assembled, upload its values to the ADP defect vector value array by calling the upload_vector() function.
Apply the defect filter by calling the filter_vec_def() function.
Now both the matrix and the corresponding defect vector have been converted fully, so you are now free to apply whatever solver algorithm you want onto them.
Once you have obtained a correction vector, you may want to apply the correction filter onto it by calling the filter_vec_cor() function if your solver algorithm has a tendency of not solving the system exactly, and then download the ADP correction vector value array to a system correction vector by calling the download_vector() function.
If the numerical values of the system matrix or the system filter change, e.g. after reassembling them during a non-linear and/or unsteady simulation, you can simply re-upload the matrix and/or filter values by using the above upload functions.
Once you are done, you can simply destroy the AlgDofPartiSystem object without any prior cleanup.
Note
If the matrix structure changes for whatever reason, then you have to destroy both the AlgDofPartiSystem object as well as its underlying AlgDofParti object and re-create them for the new matrix structure from scratch.
Attention
In its current state, only unit-filters (both scalar and blocked) and filter chains and sequences thereof are supported by this class, i.e. neither mean filters nor slip filters are supported yet. However, note that mean filters and slips filters are allowed to exist in a filter chain passed to this class, but they must be empty and therefore inactive, otherwise this class will abort with an assertion failure!
Todo:
add support for LAFEM::PowerXXX containers
add support for LAFEM/Global::MeanFilter
add support for LAFEM::SlipFilter
Author
Peter Zajac
Definition at line 132 of file alg_dof_parti_system.hpp.
Member Typedef Documentation
ADPFilAuxType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Intern::ADPFilAux<LocalFilterType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::ADPFilAuxType
Definition at line 176 of file alg_dof_parti_system.hpp.
ADPMatAuxType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Intern::ADPMatAux<LocalMatrixType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::ADPMatAuxType
Definition at line 175 of file alg_dof_parti_system.hpp.
AlgDofPartiType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Global::AlgDofParti<LocalVectorType, MirrorType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::AlgDofPartiType
the algebraic DOF partitioning
Definition at line 165 of file alg_dof_parti_system.hpp.
BufferMatrixType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LAFEM::MatrixMirrorBuffer<DataType, IndexType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::BufferMatrixType
the buffer matrix type used for communication
Definition at line 159 of file alg_dof_parti_system.hpp.
BufferVectorType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::BufferVectorType
the buffer vector type used for communication
Definition at line 157 of file alg_dof_parti_system.hpp.
DataType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LocalMatrix_::DataType FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::DataType
our data type
Definition at line 136 of file alg_dof_parti_system.hpp.
DoneeMirrorType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LAFEM::VectorMirror<DataType, IndexType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::DoneeMirrorType
donee neighbor mirror type
Definition at line 171 of file alg_dof_parti_system.hpp.
GlobalFilterType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Global::Filter<LocalFilterType, MirrorType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::GlobalFilterType
the global filter type
Definition at line 154 of file alg_dof_parti_system.hpp.
GlobalMatrixType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Global::Matrix<LocalMatrixType, MirrorType, MirrorType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::GlobalMatrixType
the global matrix type
Definition at line 145 of file alg_dof_parti_system.hpp.
IndexType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LocalMatrix_::IndexType FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::IndexType
our index type
Definition at line 138 of file alg_dof_parti_system.hpp.
IndexVectorType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef AlgDofPartiType::IndexVectorType FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::IndexVectorType
auxiliary index vector type
Definition at line 168 of file alg_dof_parti_system.hpp.
LocalFilterType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LocalFilter_ FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::LocalFilterType
the local filter type
Definition at line 151 of file alg_dof_parti_system.hpp.
LocalMatrixType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LocalMatrix_ FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::LocalMatrixType
the local matrix type
Definition at line 141 of file alg_dof_parti_system.hpp.
LocalVectorType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LocalMatrixType::VectorTypeR FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::LocalVectorType
the local vector type
Definition at line 148 of file alg_dof_parti_system.hpp.
MirrorType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Mirror_ FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::MirrorType
the vector mirror type
Definition at line 143 of file alg_dof_parti_system.hpp.
OwnedMatrixType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef LAFEM::SparseMatrixCSR<DataType, IndexType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::OwnedMatrixType
the matrix type used for the internal storage of our owned matrix rows
Definition at line 162 of file alg_dof_parti_system.hpp.
OwnerMirrorType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Intern::ADPDOMM<LocalMatrixType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::OwnerMirrorType
owner neighbor mirror type
Definition at line 173 of file alg_dof_parti_system.hpp.
Constructor & Destructor Documentation
AlgDofPartiSystem() [1/2]
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::AlgDofPartiSystem (const GlobalMatrixType & matrix, const GlobalFilterType & filter) inline explicit
Constructor.
Parameters
[in] matrix A resident reference to the global system matrix
[in] filter A resident reference to the global system filter
Definition at line 220 of file alg_dof_parti_system.hpp.
AlgDofPartiSystem() [2/2]
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::AlgDofPartiSystem (const GlobalMatrixType & matrix, const GlobalFilterType & filter, std::shared_ptr< AlgDofPartiType > adp) inline explicit
Constructor.
Parameters
[in] matrix A resident reference to the global system matrix
[in] filter A resident reference to the global system filter
[in] adp A shared pointer containing the ADP object to be used
Definition at line 242 of file alg_dof_parti_system.hpp.
Member Function Documentation
_asm_mat_buf()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > static BufferMatrixType FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_asm_mat_buf (const LocalMatrixType & local_matrix, const MirrorType & row_mirror, const IndexVectorType & global_dof_idx, const Index num_global_dofs) inline static protected
Assembles a matrix buffer for a given row mirror.
Definition at line 713 of file alg_dof_parti_system.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::feat_omp_ex_scan(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr().
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers().
_asm_neighbor_donee_data_mir()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > static void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_asm_neighbor_donee_data_mir (DoneeMirrorType & data_mirror, const Adjacency::Graph & owned_graph, const DoneeMirrorType & mirror, const BufferMatrixType & buffer) inline static protected
Auxiliary function: assembles a data-mirror for a donee-neighbor.
Definition at line 943 of file alg_dof_parti_system.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Adjacency::Graph::get_num_indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements().
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_data_mirrors().
_assemble_buffers()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers () inline protected
Assembles the owner and donee matrix buffers.
Definition at line 760 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_asm_mat_buf(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_donee_bufs, FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_comm(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_donee_rank(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_global_dof_indices(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_donee_neighbors(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_global_dofs(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_owner_neighbors(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owner_mirror(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owner_rank(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), and FEAT::Dist::RequestVector::wait_all().
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::init_symbolic().
_assemble_data_mirrors()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_data_mirrors () inline protected
Assembles the data-mirrors for all owner- and donee-neighbors.
This functions assembles the data-mirrors, which are used for the communication of the numerical values of a matrix in the #upload_numeric() function. This allows that the matrix values can be uploaded and synchronized without the need to re-communicate the unchanged matrix buffer layouts every time.
Definition at line 994 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_asm_neighbor_donee_data_mir(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_donee_mirror(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_global_dof_indices(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owned_mirror(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owner_mirror(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local().
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::init_symbolic().
_assemble_structure()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure () inline protected
Assembles the matrix structure of the algebraic-DOF-partitioned matrix.
Definition at line 878 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_alg_dof_parti, FEAT::Dist::Comm::allreduce(), FEAT::Adjacency::as_is, FEAT::Adjacency::DynamicGraph::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_comm(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_donee_mirror(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_global_dof_indices(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_donee_neighbors(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_global_dofs(), FEAT::Adjacency::DynamicGraph::get_num_indices(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_owned_dofs(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owned_mirror(), FEAT::Adjacency::DynamicGraph::insert(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), FEAT::Dist::op_sum, FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), and XASSERT.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::init_symbolic().
_scatter_donee_data()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTA_ > static void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_scatter_donee_data (DTA_ * adp_val, const BufferVectorType & buffer, const DoneeMirrorType & data_mirror) inline static protected
Scatters the values of a donee-neighbor buffer-vector into a local matrix.
Definition at line 1021 of file alg_dof_parti_system.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERT.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
apply()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTX_ , typename RPT_ , typename CIT_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::apply (DTX_ * vec_r, const DTX_ * vec_x, const DTX_ * val_a, const RPT_ * row_ptr, const CIT_ * col_idx) const inline
Performs a global matrix-vector product with this matrix.
Attention
As convenient and tempting as this function may look, please be aware that using this function will completely destroy the scalability of our code when running on a large number of processes. In addition to the scalability issues, please be aware that this function may cause a fatal out-of-memory event, as the underlying (naive) implementation gathers the full multiplicand vector on all processes using the AlgDofPartiVector::allgather() function.
Do not use this function except for small-scale debugging purposes. You have been warned.
Parameters
[out] vec_r A reference to the algebraic-dof-partitioned vector that receives the result of the matrix-vector product.
[in] vec_x A const reference to the algebraic-dof-partitioned vector that acts as a multiplicand vector.
Definition at line 402 of file alg_dof_parti_system.hpp.
References FEAT::Dist::Comm::allgatherv(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_adp_matrix_cols(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_adp_matrix_nzes(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_adp_matrix_rows(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_comm(), and XASSERTM.
bytes()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > std::size_t FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::bytes () const inline
Returns
The size of this object in bytes
Definition at line 259 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_owned_data_mir, FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_unit_filter_rows, and FEAT::LAFEM::UnitFilter< DT_, IT_ >::bytes().
download_vector()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTV_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::download_vector (LocalVectorType & vector, const DTV_ * val) inline
Downloads the ADP vector values from the given array.
Parameters
[in,out] vector A transient reference to the local vector that receives the downloaded ADP value array. It is assumed to be allocated to the correct size, but its contents on entry are ignored.
[in] val A transient pointer to an array of length _get_adp_vector_size() that contains the ADP values that are to be downloaded to the output vector given by vector.
Definition at line 375 of file alg_dof_parti_system.hpp.
References XASSERT.
filter_matrix()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTA_ , typename RPT_ , typename CIT_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::filter_matrix (DTA_ * val, const RPT_ * row_ptr, const CIT_ * col_idx) inline
Applies the ADP filter onto an ADP matrix.
Parameters
[in,out] val A transient pointer to the value data array of the matrix that is to be filtered.
[in] row_ptr A transient pointer to the row-pointer array that has been initialized by the upload_matrix_symbolic() function.
[in] col_idx A transient pointer to the column-index array that has been initialized by the upload_matrix_symbolic() function.
Definition at line 679 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_unit_filter_rows, FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_alg_dof_parti(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::used_elements(), and XASSERT.
filter_vec_cor()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTV_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::filter_vec_cor (DTV_ * vec_cor) inline
Applies the ADP filter onto an ADP correction vector.
Parameters
[in,out] vec_def A transient pointer to the defect vector data array that is to be filtered.
Definition at line 653 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_unit_filter_rows, FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::used_elements(), and XASSERT.
filter_vec_def()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTV_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::filter_vec_def (DTV_ * vec_def) inline
Applies the ADP filter onto an ADP defect vector.
Parameters
[in,out] vec_def A transient pointer to the defect vector data array that is to be filtered.
Definition at line 636 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_unit_filter_rows, FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::used_elements(), and XASSERT.
get_adp_matrix_cols()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_adp_matrix_cols () const inline
Returns
The number of columns of the local ADP matrix (corresponds to the total number of global DOFs).
Definition at line 322 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::apply().
get_adp_matrix_nzes()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_adp_matrix_nzes () const inline
Returns
The number of nonzero entries of the local ADP matrix
Definition at line 328 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_num_owned_non_zeros.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::apply().
get_adp_matrix_rows()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_adp_matrix_rows () const inline
Returns
The number of rows of the local ADP matrix (corresponds to the number of owned DOFs).
Definition at line 316 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::apply().
get_adp_vector_size()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_adp_vector_size () const inline
Returns
The size of a local ADP vector (corresponds to the number of owned DOFs).
Definition at line 310 of file alg_dof_parti_system.hpp.
get_alg_dof_parti()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > std::shared_ptr< AlgDofPartiType > FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_alg_dof_parti () inline
Returns the algebraic dof partitioning that is used internally.
Note
The ADP object is (in general) allocated and initialized by the init_symbolic() function, so this function will (in general) return a null pointer if called before init_symbolic().
Definition at line 286 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_alg_dof_parti.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::filter_matrix().
get_comm()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > const Dist::Comm * FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_comm () const inline
Returns
A pointer to the underlying communicator.
Definition at line 340 of file alg_dof_parti_system.hpp.
References XASSERT.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::apply(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
get_global_dof_offset()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_global_dof_offset () const inline
Returns
The index of the first global DOF owned by this process.
Definition at line 304 of file alg_dof_parti_system.hpp.
get_num_global_dofs()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_num_global_dofs () const inline
Returns
The total number of global DOFs.
Definition at line 298 of file alg_dof_parti_system.hpp.
get_num_global_nonzeros()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_num_global_nonzeros () const inline
Returns
The total number of nonzero entries of the global ADP matrix
Definition at line 334 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_num_global_non_zeros.
get_num_owned_dofs()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_num_owned_dofs () const inline
Returns
The number of local DOFs owned by this process.
Definition at line 292 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_filter().
init_symbolic()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::init_symbolic () inline
Performs the symbolic initialization.
This function assembles the algebraic dof partitioning based on the gate of the system matrix (unless an already assembled ADP object was passed to the constructor) and assembles the required buffers and mirrors for the ADP system conversion.
Definition at line 427 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_data_mirrors(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_row_gate().
upload_filter() [1/2]
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_filter () inline
Uploads the values of the system filter to the ADP system.
Definition at line 612 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_filter().
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_filter().
upload_filter() [2/2]
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_filter (const LocalFilterType & filter) inline
Uploads the values of the given filter to the ADP system.
Parameters
[in] filter A transient reference to the filter whose values are to be uploaded
Definition at line 623 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_unit_filter_rows, and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_num_owned_dofs().
upload_matrix_numeric() [1/2]
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTA_ , typename RPT_ , typename CIT_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric (DTA_ * val, const RPT_ * row_ptr, const CIT_ * col_idx) inline
Uploads the data value array of the ADP CSR system matrix.
Parameters
[in,out] val A transient pointer to an array containing at least get_adp_matrix_nzes() entries that receives the CSR data value array of the local slice of the row-wise partitioned global CSR matrix. The array must be allocated to the correct size by the caller, but the contents of the array upon entry are ignored.
[in] row_ptr A transient pointer to the row-pointer array that has been initialized by the upload_matrix_symbolic() function.
[in] col_idx A transient pointer to the column-index array that has been initialized by the upload_matrix_symbolic() function.
Definition at line 521 of file alg_dof_parti_system.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
upload_matrix_numeric() [2/2]
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTA_ , typename RPT_ , typename CIT_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric (DTA_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LocalMatrixType & matrix) inline
Copies the matrix entry values from the input matrix into this algebraic-dof-partitioned matrix.
Parameters
[in,out] val A transient pointer to an array containing at least get_adp_matrix_nzes() entries that receives the CSR data value array of the local slice of the row-wise partitioned global CSR matrix. The array must be allocated to the correct size by the caller, but the contents of the array upon entry are ignored.
[in] row_ptr A transient pointer to the row-pointer array that has been initialized by the upload_matrix_symbolic() function.
[in] col_idx A transient pointer to the column-index array that has been initialized by the upload_matrix_symbolic() function.
[in] matrix The input matrix whose entry values are to be copied.
Attention
The input matrix is assumed to be an unfiltered type-0 matrix.
Definition at line 550 of file alg_dof_parti_system.hpp.
References FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_scatter_donee_data(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_comm(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_donee_rank(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_donee_neighbors(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_owner_neighbors(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owner_rank(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERT.
upload_matrix_symbolic()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename RPT_ , typename CIT_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_symbolic (RPT_ * row_ptr, CIT_ * col_idx, bool keep_graph = false) inline
Uploads the row-pointer and column-index arrays of the ADP CSR system matrix.
Parameters
[in,out] row_ptr A transient pointer to an array containing at least get_adp_matrix_rows()+1 entries that receives the CSR row-pointer array of the local slice of the row-wise partitioned global CSR matrix. The array must be allocated to the correct size by the caller, but the contents of the array upon entry are ignored.
[in] col_idx A transient pointer to an array containing at least get_adp_matrix_nzes() entries that receives the CSR column-index array of the local slice of the row-wise partitioned global CSR matrix. The array must be allocated to the correct size by the caller, but the contents of the array upon entry are ignored.
[in] keep_graph If set to false, the internal adjacency graph of the matrix is discarded at the end of this function call, as it serves no further internal purpose and therefore there is no need to keep the graph in memory unless the user wants to access it after the symbolic upload for some debugging purposes.
Note
The column indices in each row are always sorted in ascending order.
Definition at line 465 of file alg_dof_parti_system.hpp.
References ASSERTM, and XASSERT.
upload_vector()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > template<typename DTV_ > void FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_vector (DTV_ * val, const LocalVectorType & vector) inline
Uploads the ADP vector values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_vector_size() that receives the local ADP values of the input vector given by vector.
[in] vector A transient reference to the local vector that is to be uploaded to the ADP value array.
Definition at line 357 of file alg_dof_parti_system.hpp.
References XASSERT.
Member Data Documentation
_alg_dof_parti
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > std::shared_ptr<AlgDofPartiType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_alg_dof_parti
the algebraic dof-partitioning
Definition at line 185 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_data_mirrors(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_alg_dof_parti(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_filter(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
_donee_bufs
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > std::vector<BufferMatrixType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_donee_bufs
the matrix buffers for our donee and owner neighbors; both buffers use global DOF indices
Definition at line 197 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers().
_donee_data_mirs
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > std::vector<DoneeMirrorType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_donee_data_mirs
the data array mirrors for our donee and owner neighbors
Definition at line 201 of file alg_dof_parti_system.hpp.
_global_filter
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > const GlobalFilterType& FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_global_filter
the global filter that we want to convert
Definition at line 182 of file alg_dof_parti_system.hpp.
_global_matrix
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > const GlobalMatrixType& FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_global_matrix
the global matrix that we want to convert
Definition at line 180 of file alg_dof_parti_system.hpp.
_num_global_non_zeros
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_num_global_non_zeros
number of non-zero entries in total
Definition at line 194 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_num_global_nonzeros().
_num_owned_non_zeros
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > Index FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_num_owned_non_zeros
number of non-zero entries owned by this process
Definition at line 191 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::get_adp_matrix_nzes().
_owned_data_mir
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > OwnerMirrorType FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_owned_data_mir
the data array mirror for this process
Definition at line 205 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::bytes().
_owned_graph
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > std::shared_ptr<Adjacency::Graph> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_owned_graph
adjacency graph containing the owned matrix structure
Definition at line 188 of file alg_dof_parti_system.hpp.
_owner_bufs
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > std::vector<BufferMatrixType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_owner_bufs
Definition at line 198 of file alg_dof_parti_system.hpp.
_owner_data_mirs
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > std::vector<OwnerMirrorType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_owner_data_mirs
Definition at line 202 of file alg_dof_parti_system.hpp.
_unit_filter_rows
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > LAFEM::UnitFilter<DataType, IndexType> FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_unit_filter_rows
indices of all unit-filtered matrix rows; we store this as a mirror
Definition at line 208 of file alg_dof_parti_system.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::bytes(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::filter_matrix(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::filter_vec_cor(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::filter_vec_def(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_filter().
The documentation for this class was generated from the following file:
kernel/global/alg_dof_parti_system.hpp