FEAT: FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ > Class Template Reference
FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ > Class Template Reference
Multigrid preconditioner implementation.
#include <multigrid.hpp>
Public Types
typedef SolverBase< typename SystemMatrix_::VectorTypeR > BaseClass
our base-class
typedef MatrixType::DataType DataType
our data type
typedef LevelType::SystemFilterType FilterType
the system filter type
typedef MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ > HierarchyType
our compatible multigrid hierarchy class
typedef HierarchyType::LevelInfo LevelInfo
the level info type
typedef HierarchyType::LevelType LevelType
the level type
typedef LevelType::SystemMatrixType MatrixType
the system matrix type
typedef LevelType::SolverType SolverType
the sub-solver type
typedef LevelType::TransferOperatorType TransferOperatorType
the transfer operator type
typedef LevelType::SystemVectorType VectorType
the system vector type
Public Member Functions
MultiGrid (std::shared_ptr< HierarchyType > hierarchy, MultiGridCycle cycle, int top_level=0, int crs_level=-1)
Constructor.
virtual ~MultiGrid ()
virtual destructor
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def) override
Applies the multigrid preconditioner.
virtual void done ()
Finalization method.
virtual void done_numeric () override
Numeric finalization function.
virtual void done_symbolic () override
Symbolic finalization function.
Index get_crs_level () const
Returns the currently selected coarse-level index.
MultiGridCycle get_cycle () const
Returns the currently selected cycle.
Index get_top_level () const
Returns the currently selected top-level index.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric initialization function.
virtual void init_symbolic () override
Symbolic initialization function.
virtual String name () const override
Returns a descriptive string.
void set_adapt_cgc (MultiGridAdaptCGC adapt_cgc)
Sets the adaption mode for the coarse grid correction.
void set_cycle (MultiGridCycle cycle)
Sets a new cycle.
void set_levels (int top_level, int crs_level)
Sets the level range for this multigrid.
Protected Member Functions
Status _apply_coarse ()
Applies the coarse grid solver on the coarse level.
Status _apply_cycle_f ()
Applies a single F-cycle.
Status _apply_cycle_v ()
Applies a single V-cycle.
Status _apply_cycle_w ()
Applies a single W-cycle.
virtual Status _apply_prol (const Index cur_lvl, bool cur_smooth)
Prolongates from the coarse level onto the current level.
Status _apply_rest (const Index cur_lvl, bool cur_smooth)
Restricts from the current level onto the coarse level.
bool _apply_smooth_def (Index cur_lvl, SolverType &smoother)
Status _apply_smooth_peak (Index cur_lvl)
Applies the peak-smoother on the current level.
Protected Attributes
MultiGridAdaptCGC _adapt_cgc
the coarse grid correction type
std::vector< int > _counters
W-cycle level counter vector.
Index _crs_level
the coarse-level of this multigrid
MultiGridCycle _cycle
the multigrid cycle
std::shared_ptr< HierarchyType > _hierarchy
the multigrid hierarchy object
std::vector< double > _mpi_execs_blas2
array containing toe of mpi execution blas2 for each processed level
std::vector< double > _mpi_execs_blas3
array containing toe of mpi execution blas3 for each processed level
std::vector< double > _mpi_execs_collective
array containing toe of mpi execution collective for each processed level
std::vector< double > _mpi_execs_reduction
array containing toe of mpi execution reduction for each processed level
std::vector< double > _mpi_waits_blas2
array containing toe of mpi wait blas2 for each processed level
std::vector< double > _mpi_waits_blas3
array containing toe of mpi wait blas3 for each processed level
std::vector< double > _mpi_waits_collective
array containing toe of mpi wait collective for each processed level
std::vector< double > _mpi_waits_reduction
array containing toe of mpi wait reduction for each processed level
std::vector< double > _toes
array containing toe for each processed level
Index _top_level
the top-level of this multigrid
Detailed Description
template<typename SystemMatrix_, typename SystemFilter_, typename TransferOperator_>
class FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >
Multigrid preconditioner implementation.
See also
For details in the design see Description of the geometric MultiGrid solver
Todo:
document this
Template Parameters
SystemMatrix_ The class representing the system matrix.
SystemFilter_ The class representing the system filter.
ProlOperator_ The class representing the prolongation operator (usually a matrix type).
RestOperator_ The class representing the restriction operator (usually a matrix type).
Author
Peter Zajac
Definition at line 984 of file multigrid.hpp.
Member Typedef Documentation
BaseClass
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef SolverBase<typename SystemMatrix_::VectorTypeR> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::BaseClass
our base-class
Definition at line 989 of file multigrid.hpp.
DataType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef MatrixType::DataType FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::DataType
our data type
Definition at line 1011 of file multigrid.hpp.
FilterType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::SystemFilterType FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::FilterType
the system filter type
Definition at line 1002 of file multigrid.hpp.
HierarchyType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef MultiGridHierarchy<SystemMatrix_, SystemFilter_, TransferOperator_> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::HierarchyType
our compatible multigrid hierarchy class
Definition at line 992 of file multigrid.hpp.
LevelInfo
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef HierarchyType::LevelInfo FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo
the level info type
Definition at line 997 of file multigrid.hpp.
LevelType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef HierarchyType::LevelType FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelType
the level type
Definition at line 995 of file multigrid.hpp.
MatrixType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::SystemMatrixType FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::MatrixType
the system matrix type
Definition at line 1000 of file multigrid.hpp.
SolverType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::SolverType FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::SolverType
the sub-solver type
Definition at line 1008 of file multigrid.hpp.
TransferOperatorType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::TransferOperatorType FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::TransferOperatorType
the transfer operator type
Definition at line 1006 of file multigrid.hpp.
VectorType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::SystemVectorType FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::VectorType
the system vector type
Definition at line 1004 of file multigrid.hpp.
Constructor & Destructor Documentation
MultiGrid()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::MultiGrid (std::shared_ptr< HierarchyType > hierarchy, MultiGridCycle cycle, int top_level = 0, int crs_level = -1) inline explicit
Constructor.
Parameters
[in] hierarchy A pointer to the multigrid hierarchy object.
[in] cycle The desired multigrid cycle.
[in] top_level The desired top-level for this multigrid solver.
Set to 0 to use the finest level in the multigrid hierarchy.
[in] crs_level The desired coarse-level for this multigrid solver.
Set to -1 to use the coarsest level in the multigrid hierarchy.
Note
The cycle may be changed anytime by using the set_cycle() function.
Definition at line 1068 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_top_level, and XASSERTM.
~MultiGrid()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::~MultiGrid () inline virtual
virtual destructor
Definition at line 1081 of file multigrid.hpp.
Member Function Documentation
_apply_coarse()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Status FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse () inline protected
Applies the coarse grid solver on the coarse level.
Definition at line 1526 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_toes, FEAT::Solver::aborted, FEAT::TimeStamp::elapsed_now(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::level, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::name(), FEAT::Solver::status_success(), FEAT::Solver::success, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::time_coarse, and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::vec_rhs.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_v(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w().
_apply_cycle_f()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Status FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f () inline protected
Applies a single F-cycle.
Definition at line 1356 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_top_level, FEAT::Math::min(), and FEAT::Solver::success.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply().
_apply_cycle_v()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Status FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_v () inline protected
Applies a single V-cycle.
Definition at line 1335 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), and FEAT::Solver::success.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply().
_apply_cycle_w()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Status FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w () inline protected
Applies a single W-cycle.
Definition at line 1412 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_counters, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_top_level, FEAT::Math::min(), FEAT::Solver::success, and XASSERTM.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply().
_apply_prol()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual Status FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol (const Index cur_lvl, bool cur_smooth) inline protected virtual
Prolongates from the coarse level onto the current level.
Parameters
[in] cur_lvl The level onto which to prolongate.
[in] cur_smooth Specifies whether to apply the post-smoother on the current level.
Definition at line 1845 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_adapt_cgc, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_toes, FEAT::TimeStamp::elapsed_now(), FEAT::Solver::Fixed, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::level, FEAT::Math::min(), FEAT::Solver::MinDefect, FEAT::Solver::MinEnergy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::name(), FEAT::Solver::success, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::time_defect, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::time_smooth, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::time_transfer, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::vec_rhs, and XASSERTM.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_v(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w().
_apply_rest()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Status FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest (const Index cur_lvl, bool cur_smooth) inline protected
Restricts from the current level onto the coarse level.
Parameters
[in] cur_lvl The level from which to restrict.
[in] cur_smooth Specifies whether to apply the pre-smoother on the current level.
Definition at line 1713 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_toes, FEAT::TimeStamp::elapsed_now(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::level, FEAT::Math::min(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::name(), FEAT::Solver::success, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::time_defect, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::time_smooth, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::time_transfer, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::vec_rhs, and XASSERTM.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_v(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w().
_apply_smooth_def()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > bool FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_def (Index cur_lvl, SolverType & smoother) inline protected
Definition at line 1591 of file multigrid.hpp.
_apply_smooth_peak()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Status FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak (Index cur_lvl) inline protected
Applies the peak-smoother on the current level.
Parameters
[in] cur_lvl The current level.
Definition at line 1632 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_toes, FEAT::Solver::aborted, FEAT::TimeStamp::elapsed(), FEAT::TimeStamp::elapsed_now(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::level, FEAT::Solver::success, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::time_defect, and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::vec_rhs.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w().
apply()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual Status FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply (VectorType & vec_cor, const VectorType & vec_def) inline override virtual
Applies the multigrid preconditioner.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Returns
A Status code that represents the status of the solution step.
Implements FEAT::Solver::SolverBase< SystemMatrix_::VectorTypeR >.
Definition at line 1270 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_v(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_cycle, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_toes, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_top_level, FEAT::Solver::aborted, FEAT::Solver::F, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::name(), FEAT::Solver::success, FEAT::Solver::undefined, FEAT::Solver::V, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelInfo::vec_rhs, and FEAT::Solver::W.
done()
virtual void FEAT::Solver::SolverBase< SystemMatrix_::VectorTypeR >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 285 of file base.hpp.
done_numeric()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual void FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric () inline override virtual
Numeric finalization function.
Attention
This function does not perform the actual numeric finalization of the multigrid hierarchy. You have to perform the numeric finalization explicitly by calling the done_numeric function of the corresponding MultiGridHierarchy object after finalising the solver tree!
Reimplemented from FEAT::Solver::SolverBase< SystemMatrix_::VectorTypeR >.
Definition at line 1252 of file multigrid.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric().
done_symbolic()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual void FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic () inline override virtual
Symbolic finalization function.
Attention
This function does not perform the actual symbolic finalization of the multigrid hierarchy. You have to perform the symbolic finalization explicitly by calling the done_symbolic function of the corresponding MultiGridHierarchy object after finalising the solver tree!
Reimplemented from FEAT::Solver::SolverBase< SystemMatrix_::VectorTypeR >.
Definition at line 1210 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_counters, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_toes, and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
get_crs_level()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Index FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_crs_level () const inline
Returns the currently selected coarse-level index.
Returns
The currently selected coarse-level index.
Definition at line 1152 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level.
get_cycle()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > MultiGridCycle FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_cycle () const inline
Returns the currently selected cycle.
Returns
The currently selected cycle.
Definition at line 1112 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_cycle.
get_top_level()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Index FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_top_level () const inline
Returns the currently selected top-level index.
Returns
The currently selected top-level index.
Definition at line 1142 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_top_level.
init()
virtual void FEAT::Solver::SolverBase< SystemMatrix_::VectorTypeR >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 270 of file base.hpp.
init_numeric()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual void FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric () inline override virtual
Numeric initialization function.
Attention
This function does not perform the actual numeric initialization of the multigrid hierarchy. You have to perform the numeric initialization explicitly by calling the init_numeric function of the corresponding MultiGridHierarchy object before initialising the solver tree!
Reimplemented from FEAT::Solver::SolverBase< SystemMatrix_::VectorTypeR >.
Definition at line 1235 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and XASSERTM.
init_symbolic()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual void FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic () inline override virtual
Symbolic initialization function.
Attention
This function does not perform the actual symbolic initialization of the multigrid hierarchy. You have to perform the symbolic initialization explicitly by calling the init_symbolic function of the corresponding MultiGridHierarchy object before initialising the solver tree!
Reimplemented from FEAT::Solver::SolverBase< SystemMatrix_::VectorTypeR >.
Definition at line 1176 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_counters, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas2, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas3, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_collective, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_reduction, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_toes, FEAT::Solver::SolverBase< Vector_ >::init_symbolic(), and XASSERTM.
name()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual String FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::name () const inline override virtual
Returns a descriptive string.
Returns
A string describing the solver.
Implements FEAT::Solver::SolverBase< SystemMatrix_::VectorTypeR >.
Definition at line 1162 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_cycle, and FEAT::stringify().
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply().
set_adapt_cgc()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::set_adapt_cgc (MultiGridAdaptCGC adapt_cgc) inline
Sets the adaption mode for the coarse grid correction.
Parameters
[in] adapt_cgc The adaption mode for the coarse grid correction.
Definition at line 1091 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_adapt_cgc.
set_cycle()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::set_cycle (MultiGridCycle cycle) inline
Sets a new cycle.
Parameters
[in] cycle The new cycle to be used.
Definition at line 1102 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_cycle.
set_levels()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::set_levels (int top_level, int crs_level) inline
Sets the level range for this multigrid.
Parameters
[in] top_level The desired top-level for this multigrid solver.
Set to 0 to use the finest level in the multigrid hierarchy.
[in] crs_level The desired coarse-level for this multigrid solver.
Set to -1 to use the coarsest level in the multigrid hierarchy.
Definition at line 1128 of file multigrid.hpp.
References FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_top_level, and XASSERTM.
Member Data Documentation
_adapt_cgc
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > MultiGridAdaptCGC FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_adapt_cgc protected
the coarse grid correction type
Definition at line 1019 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::set_adapt_cgc().
_counters
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<int> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_counters protected
W-cycle level counter vector.
Definition at line 1026 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_crs_level
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Index FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_crs_level protected
the coarse-level of this multigrid
Definition at line 1023 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::MultiGrid(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_crs_level(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::set_levels().
_cycle
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > MultiGridCycle FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_cycle protected
the multigrid cycle
Definition at line 1017 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_cycle(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::name(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::set_cycle().
_hierarchy
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::shared_ptr<HierarchyType> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_hierarchy protected
the multigrid hierarchy object
Definition at line 1015 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::set_levels().
_mpi_execs_blas2
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas2 protected
array containing toe of mpi execution blas2 for each processed level
Definition at line 1033 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_mpi_execs_blas3
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_blas3 protected
array containing toe of mpi execution blas3 for each processed level
Definition at line 1035 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_mpi_execs_collective
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_collective protected
array containing toe of mpi execution collective for each processed level
Definition at line 1037 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_mpi_execs_reduction
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_execs_reduction protected
array containing toe of mpi execution reduction for each processed level
Definition at line 1031 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_mpi_waits_blas2
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas2 protected
array containing toe of mpi wait blas2 for each processed level
Definition at line 1041 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_mpi_waits_blas3
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_blas3 protected
array containing toe of mpi wait blas3 for each processed level
Definition at line 1043 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_mpi_waits_collective
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_collective protected
array containing toe of mpi wait collective for each processed level
Definition at line 1045 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_mpi_waits_reduction
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_mpi_waits_reduction protected
array containing toe of mpi wait reduction for each processed level
Definition at line 1039 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_toes
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::vector<double> FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_toes protected
array containing toe for each processed level
Definition at line 1029 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_prol(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_rest(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_smooth_peak(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
_top_level
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Index FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_top_level protected
the top-level of this multigrid
Definition at line 1021 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::MultiGrid(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_f(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_cycle_w(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::apply(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_top_level(), and FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::set_levels().
The documentation for this class was generated from the following file:
kernel/solver/multigrid.hpp