FEAT: FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ > Class Template Reference
FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ > Class Template Reference
GlobalMaskedBoundaryFactory implementation.
#include <boundary_factory.hpp>
Public Types
typedef Factory< MeshPart< ParentMesh_ > > BaseClass
Our base class.
typedef MeshPart< ParentMeshType > MeshType
The MeshPart type.
typedef ParentMesh_ ParentMeshType
the parent mesh type
typedef MeshType::ShapeType ShapeType
the shape type
typedef MeshType::TargetSetHolderType TargetSetHolderType
target set holder type
Public Member Functions
GlobalMaskedBoundaryFactory (const ParentMeshType &mesh_in)
Constructor.
void add_halo (int rank, const MeshPart< ParentMeshType > &halo)
Adds a halo to the mask and saves it for synchronization.
void add_mask_facet (Index facet_idx)
void add_mask_meshpart (const MeshPart< ParentMeshType > &part)
Adds all facets in a mesh-part to the boundary facet mask.
void compile (const Dist::Comm &comm)
Compiles the factory.
virtual void fill_attribute_sets (typename BaseClass::AttributeSetContainer &) override
Fills the MeshPart's target set, except that it doesn't.
virtual void fill_index_sets (std::unique_ptr< typename BaseClass::IndexSetHolderType > &) override
Fills the MeshPart's index_set_holder, except that it doesn't as there is no topology.
virtual void fill_target_sets (TargetSetHolderType &target_set_holder) override
Fills the MeshPart's target set.
virtual Index get_num_entities (int dim) override
Returns the number of entities.
Static Public Attributes
static constexpr int facet_dim = shape_dim - 1
the facet dimension
static constexpr int shape_dim = ShapeType::dimension
the shape dimension
Protected Member Functions
void _sync_bnd_masks (const Dist::Comm &comm)
Synchronizes the boundary masks over the communicators.
Private Attributes
std::array< std::vector< int >, std::size_t(shape_dim)> _bnd_masks
the face masks for each face dimensions
Intern::BoundaryFaceComputer< ShapeType > _face_computer
a boundary face computer object for the dirty work
std::array< std::vector< Index >, std::size_t(shape_dim)> _face_idx
the (cell_dim_-1)-dimensional boundary face indices for each face dimension
std::vector< int > _facet_mask
a mask vector for the facets
std::vector< std::pair< int, const MeshType * > > _halos
a map of all halos
const ParentMeshType & _mesh_in
a reference to the input mesh
Detailed Description
template<typename ParentMesh_>
class FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >
GlobalMaskedBoundaryFactory implementation.
This class is an extension of the MaskedBoundaryFactory class, which creates a mesh part containing the set of all unmasked boundary faces for a given partitioned mesh. Facets of the mesh can be masked by added them individually using the add_mask_facet() function or by adding an entire mesh part by using the add_mask_meshpart() function. Furthermore, one must add all halos and their corresponding ranks by calling the add_halo() function. Once all masked facets/meshparts and halos have been added, one has to call the compile() function before creating the mesh part using this factory.
To illustrate why one cannot use the MaskedBoundaryFactory in the case of a partitioned mesh consider the following L-domain example with 3 MPI ranks and 1 element per rank:
+---+
| 2 |
+---X---+
| 0 | 1 |
+---+---+
On ranks 1 and 2, the vertex 'X' is correctly considered to be a boundary vertex, because it is adjacent to a boundary edge, however, on rank 0 this vertex is only adjacent to halo edges, but not to any boundary edge, thus it would be incorrectly treated as an inner vertex. This class solves this problem by explicitly synchronizing the detected boundary entities via the supplied halos.
Author
Peter Zajac
Definition at line 238 of file boundary_factory.hpp.
Member Typedef Documentation
BaseClass
template<typename ParentMesh_ > typedef Factory<MeshPart<ParentMesh_> > FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::BaseClass
Our base class.
Definition at line 243 of file boundary_factory.hpp.
MeshType
template<typename ParentMesh_ > typedef MeshPart<ParentMeshType> FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::MeshType
The MeshPart type.
Definition at line 247 of file boundary_factory.hpp.
ParentMeshType
template<typename ParentMesh_ > typedef ParentMesh_ FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::ParentMeshType
the parent mesh type
Definition at line 245 of file boundary_factory.hpp.
ShapeType
template<typename ParentMesh_ > typedef MeshType::ShapeType FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::ShapeType
the shape type
Definition at line 249 of file boundary_factory.hpp.
TargetSetHolderType
template<typename ParentMesh_ > typedef MeshType::TargetSetHolderType FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::TargetSetHolderType
target set holder type
Definition at line 251 of file boundary_factory.hpp.
Constructor & Destructor Documentation
GlobalMaskedBoundaryFactory()
template<typename ParentMesh_ > FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::GlobalMaskedBoundaryFactory (const ParentMeshType & mesh_in) inline explicit
Constructor.
Parameters
[in] mesh_in A resident reference to mesh for which the boundary meshpart is to be computed.
Definition at line 278 of file boundary_factory.hpp.
Member Function Documentation
_sync_bnd_masks()
template<typename ParentMesh_ > void FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_sync_bnd_masks (const Dist::Comm & comm) inline protected
Synchronizes the boundary masks over the communicators.
Definition at line 366 of file boundary_factory.hpp.
References FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_bnd_masks, FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_face_computer, FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_halos, FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Dist::RequestVector::push_back(), FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::shape_dim, and FEAT::Dist::RequestVector::wait_all().
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::compile().
add_halo()
template<typename ParentMesh_ > void FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::add_halo (int rank, const MeshPart< ParentMeshType > & halo) inline
Adds a halo to the mask and saves it for synchronization.
Parameters
[in] rank The rank of the halo to be added
[in] halo A resident reference to the halo to be added.
Definition at line 312 of file boundary_factory.hpp.
References FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_halos, and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::add_mask_meshpart().
add_mask_facet()
template<typename ParentMesh_ > void FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::add_mask_facet (Index facet_idx) inline
Definition at line 285 of file boundary_factory.hpp.
add_mask_meshpart()
template<typename ParentMesh_ > void FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::add_mask_meshpart (const MeshPart< ParentMeshType > & part) inline
Adds all facets in a mesh-part to the boundary facet mask.
Parameters
[in] part A transient reference to the mesh-part to be added
Definition at line 296 of file boundary_factory.hpp.
References FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_facet_mask, and FEAT::Geometry::TargetSet::get_num_entities().
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::add_halo().
compile()
template<typename ParentMesh_ > void FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::compile (const Dist::Comm & comm) inline
Compiles the factory.
This function performs the necessary synchronization over the communicator to ensure that the boundary is correctly computes for all patches.
Parameters
[in] comm A transient reference to the communicator where the partitioning of the underlying mesh is defined on
Definition at line 330 of file boundary_factory.hpp.
References FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_bnd_masks, FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_face_computer, FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_face_idx, FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_facet_mask, FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_mesh_in, and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_sync_bnd_masks().
fill_attribute_sets()
template<typename ParentMesh_ > virtual void FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::fill_attribute_sets (typename BaseClass::AttributeSetContainer &) inline override virtual
Fills the MeshPart's target set, except that it doesn't.
Definition at line 347 of file boundary_factory.hpp.
fill_index_sets()
template<typename ParentMesh_ > virtual void FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::fill_index_sets (std::unique_ptr< typename BaseClass::IndexSetHolderType > &) inline override virtual
Fills the MeshPart's index_set_holder, except that it doesn't as there is no topology.
Definition at line 352 of file boundary_factory.hpp.
fill_target_sets()
template<typename ParentMesh_ > virtual void FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::fill_target_sets (TargetSetHolderType & target_set_holder) inline override virtual
Fills the MeshPart's target set.
Definition at line 357 of file boundary_factory.hpp.
References FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_face_computer, and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_face_idx.
get_num_entities()
template<typename ParentMesh_ > virtual Index FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::get_num_entities (int dim) inline override virtual
Returns the number of entities.
Definition at line 338 of file boundary_factory.hpp.
References FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_face_idx, and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::shape_dim.
Member Data Documentation
_bnd_masks
template<typename ParentMesh_ > std::array<std::vector<int>, std::size_t(shape_dim)> FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_bnd_masks private
the face masks for each face dimensions
Definition at line 265 of file boundary_factory.hpp.
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_sync_bnd_masks(), and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::compile().
_face_computer
template<typename ParentMesh_ > Intern::BoundaryFaceComputer<ShapeType> FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_face_computer private
a boundary face computer object for the dirty work
Definition at line 261 of file boundary_factory.hpp.
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_sync_bnd_masks(), FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::compile(), and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::fill_target_sets().
_face_idx
template<typename ParentMesh_ > std::array<std::vector<Index>, std::size_t(shape_dim)> FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_face_idx private
the (cell_dim_-1)-dimensional boundary face indices for each face dimension
Definition at line 267 of file boundary_factory.hpp.
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::compile(), FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::fill_target_sets(), and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::get_num_entities().
_facet_mask
template<typename ParentMesh_ > std::vector<int> FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_facet_mask private
a mask vector for the facets
Definition at line 263 of file boundary_factory.hpp.
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::add_mask_meshpart(), and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::compile().
_halos
template<typename ParentMesh_ > std::vector<std::pair<int, const MeshType*> > FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_halos private
a map of all halos
Definition at line 269 of file boundary_factory.hpp.
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_sync_bnd_masks(), and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::add_halo().
_mesh_in
template<typename ParentMesh_ > const ParentMeshType& FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_mesh_in private
a reference to the input mesh
Definition at line 259 of file boundary_factory.hpp.
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::compile().
facet_dim
template<typename ParentMesh_ > constexpr int FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::facet_dim = shape_dim - 1 static constexpr
the facet dimension
Definition at line 255 of file boundary_factory.hpp.
shape_dim
template<typename ParentMesh_ > constexpr int FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::shape_dim = ShapeType::dimension static constexpr
the shape dimension
Definition at line 253 of file boundary_factory.hpp.
Referenced by FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::_sync_bnd_masks(), and FEAT::Geometry::GlobalMaskedBoundaryFactory< ParentMesh_ >::get_num_entities().
The documentation for this class was generated from the following file:
kernel/geometry/boundary_factory.hpp