FEAT: FEAT::Solver::AmaVanka< Matrix_, Filter_ > Class Template Reference
FEAT::Solver::AmaVanka< Matrix_, Filter_ > Class Template Reference
Additive Macro-wise Matrix-based Vanka preconditioner/smoother.
#include <amavanka.hpp>
Public Types
typedef Solver::SolverBase< typename Matrix_::VectorTypeL > BaseClass
our base-class
typedef Matrix_::DataType DataType
our data type
typedef Matrix_::IndexType IndexType
our index type
typedef Matrix_::VectorTypeL VectorType
our vector type
Public Member Functions
AmaVanka (const Matrix_ &matrix, const Filter_ &filter, const DataType omega=DataType(1), const Index num_steps=Index(1))
Constructor.
virtual Status apply (VectorType &vec_x, const VectorType &vec_b) override
applies the preconditioner
std::size_t bytes () const
Returns the total number of bytes currently allocated in this object.
void clear_macro_dofs ()
Clears the macro dofs graphs.
bool compare (const AmaVanka *other) const
std::size_t data_size () const
Returns the total data size used by the AmaVanka smoother.
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic () override
Releases the symbolic factorization data.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Performs numeric factorization.
virtual void init_symbolic () override
Performs symbolic factorization.
virtual String name () const override
Returns the name of the solver.
void push_macro_dofs (Adjacency::Graph &&dofs)
Pushes the dofs-at-macro graph of the next block.
void reset_timings ()
Resets the internal stop watches for time measurement.
void set_num_steps (Index num_steps)
Sets the number of smoothing steps.
void set_omega (DataType omega)
Sets the damping parameter omega.
void set_skip_singular (bool skip_sing)
Sets whether singular macros are to be skipped.
double time_apply () const
Returns the total accumulated time for the solver application.
double time_init_numeric () const
Returns the total accumulated time for numeric initialization.
double time_init_symbolic () const
Returns the total accumulated time for symbolic initialization.
Protected Types
typedef Intern::AmaVankaMatrixHelper< Matrix_ >::VankaMatrix VankaMatrixType
the type of our Vanka matrix
Protected Attributes
bool _auto_macros
deduct macro dofs automatically?
std::vector< Adjacency::Graph > _dof_macros
const Filter_ & _filter
the system filter
std::vector< Adjacency::Graph > _macro_dofs
the DOF-macro graphs
std::vector< int > _macro_mask
the macro mask
const Matrix_ & _matrix
the system matrix
Index _num_steps
number of steps
DataType _omega
damping parameter
bool _skip_singular
skip singular macros?
VankaMatrixType _vanka
the Vanka preconditioner matrix
VectorType _vec_c
temporary vectors
VectorType _vec_d
StopWatch watch_apply
StopWatch watch_init_numeric
StopWatch watch_init_symbolic
Detailed Description
template<typename Matrix_, typename Filter_>
class FEAT::Solver::AmaVanka< Matrix_, Filter_ >
Additive Macro-wise Matrix-based Vanka preconditioner/smoother.
This class implements an additive macro-wise Vanka smoother, which stores its pre-computed operator as a sparse matrix, so that each application of the Vanka smoother consists of only one sparse matrix-vector multiplication.
This class supports a whole batch of different matrix types:
LAFEM::SparseMatrixCSR
LAFEM::SparseMatrixBCSR
LAFEM::SaddlePointMatrix with sub-blocks of type
LAFEM::SparseMatrixBCSR
LAFEM::TupleMatrix with sub-blocks of type
LAFEM::SparseMatrixCSR
LAFEM::SparseMatrixBCSR
Attention
In contrast to the Solver::Vanka class, one must specify the macros for the Vanka smoother for each finite element space which is used to discretize the individual blocks of the solution space by using the push_macro_dofs() function. The only exception is for the LAFEM::SaddlePointMatrix, as for this matrix type, there exists an automatic macro deduction algorithm, which will compute the element-wise macro graphs based on the sparsity patterns of the B and D matrices, resp.
Example: Assume that your solution space is the usual velocity-pressure space pair used in a Stokes system, then you need to add the dof-mapping graphs of both the velocity and the pressure space to the smoother in the following way:
auto vanka = Solver::new_amavanka(system_matrix, system_filter);
vanka->push_macro_dofs(Space::DofMappingRenderer::render(space_velocity));
vanka->push_macro_dofs(Space::DofMappingRenderer::render(space_pressure));
If your solution space has other components (such as e.g. temperature, density or stress), then you have to add the rendered dof-mappings of those spaces in the correct order as well.
Note
In the case of a LAFEM::SaddlePointMatrix, the smoother implemented in this class is mathematically equivalent to a Solver::Vanka smoother of type Solver::VankaType::block_full_add.
Author
Peter Zajac
Definition at line 63 of file amavanka.hpp.
Member Typedef Documentation
BaseClass
template<typename Matrix_ , typename Filter_ > typedef Solver::SolverBase<typename Matrix_::VectorTypeL> FEAT::Solver::AmaVanka< Matrix_, Filter_ >::BaseClass
our base-class
Definition at line 68 of file amavanka.hpp.
DataType
template<typename Matrix_ , typename Filter_ > typedef Matrix_::DataType FEAT::Solver::AmaVanka< Matrix_, Filter_ >::DataType
our data type
Definition at line 71 of file amavanka.hpp.
IndexType
template<typename Matrix_ , typename Filter_ > typedef Matrix_::IndexType FEAT::Solver::AmaVanka< Matrix_, Filter_ >::IndexType
our index type
Definition at line 73 of file amavanka.hpp.
VankaMatrixType
template<typename Matrix_ , typename Filter_ > typedef Intern::AmaVankaMatrixHelper<Matrix_>::VankaMatrix FEAT::Solver::AmaVanka< Matrix_, Filter_ >::VankaMatrixType protected
the type of our Vanka matrix
Definition at line 79 of file amavanka.hpp.
VectorType
template<typename Matrix_ , typename Filter_ > typedef Matrix_::VectorTypeL FEAT::Solver::AmaVanka< Matrix_, Filter_ >::VectorType
our vector type
Definition at line 75 of file amavanka.hpp.
Constructor & Destructor Documentation
AmaVanka()
template<typename Matrix_ , typename Filter_ > FEAT::Solver::AmaVanka< Matrix_, Filter_ >::AmaVanka (const Matrix_ & matrix, const Filter_ & filter, const DataType omega = DataType(1), const Index num_steps = Index(1)) inline explicit
Constructor.
Parameters
[in] matrix The saddle-point system matrix.
[in] filter The system filter.
[in] omega The damping parameter.
[in] num_steps The number of smoothing steps to be performed.
Definition at line 125 of file amavanka.hpp.
Member Function Documentation
apply()
template<typename Matrix_ , typename Filter_ > virtual Status FEAT::Solver::AmaVanka< Matrix_, Filter_ >::apply (VectorType & vec_x, const VectorType & vec_b) inline override virtual
applies the preconditioner
Implements FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Definition at line 435 of file amavanka.hpp.
References FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_num_steps, FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and FEAT::Solver::success.
bytes()
template<typename Matrix_ , typename Filter_ > std::size_t FEAT::Solver::AmaVanka< Matrix_, Filter_ >::bytes () const inline
Returns the total number of bytes currently allocated in this object.
Definition at line 209 of file amavanka.hpp.
References FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_macro_dofs, FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_vanka, and FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_vec_c.
clear_macro_dofs()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::clear_macro_dofs () inline
Clears the macro dofs graphs.
Definition at line 140 of file amavanka.hpp.
References FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_auto_macros.
compare()
template<typename Matrix_ , typename Filter_ > bool FEAT::Solver::AmaVanka< Matrix_, Filter_ >::compare (const AmaVanka< Matrix_, Filter_ > * other) const inline
Definition at line 463 of file amavanka.hpp.
data_size()
template<typename Matrix_ , typename Filter_ > std::size_t FEAT::Solver::AmaVanka< Matrix_, Filter_ >::data_size () const inline
Returns the total data size used by the AmaVanka smoother.
Returns
The total data size, i.e. the total number of floating point values used in the factorization.
Definition at line 227 of file amavanka.hpp.
References FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_vanka.
done()
virtual void FEAT::Solver::SolverBase< Matrix_::VectorTypeL >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
done_numeric()
virtual void FEAT::Solver::SolverBase< Matrix_::VectorTypeL >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented in FEAT::Solver::GenericUmfpack< Matrix_ >.
Definition at line 246 of file base.hpp.
done_symbolic()
template<typename Matrix_ , typename Filter_ > virtual void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::done_symbolic () inline override virtual
Releases the symbolic factorization data.
Reimplemented from FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Reimplemented in FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 319 of file amavanka.hpp.
References FEAT::Solver::SolverBase< typename Matrix_::VectorTypeL >::done_symbolic().
Referenced by FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::done_symbolic().
init()
virtual void FEAT::Solver::SolverBase< Matrix_::VectorTypeL >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
init_numeric()
template<typename Matrix_ , typename Filter_ > virtual void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::init_numeric () inline override virtual
Performs numeric factorization.
Reimplemented from FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Reimplemented in FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 335 of file amavanka.hpp.
References FEAT::Solver::SolverBase< typename Matrix_::VectorTypeL >::init_numeric(), FEAT::Math::invert_matrix(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and XASSERTM.
init_symbolic()
template<typename Matrix_ , typename Filter_ > virtual void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::init_symbolic () inline override virtual
Performs symbolic factorization.
Reimplemented from FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Reimplemented in FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 273 of file amavanka.hpp.
References FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_macro_dofs, FEAT::Solver::SolverBase< typename Matrix_::VectorTypeL >::init_symbolic(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), FEAT::Adjacency::transpose, XABORTM, XASSERT, and XASSERTM.
Referenced by FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::init_symbolic().
name()
template<typename Matrix_ , typename Filter_ > virtual String FEAT::Solver::AmaVanka< Matrix_, Filter_ >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Reimplemented in FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 267 of file amavanka.hpp.
push_macro_dofs()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::push_macro_dofs (Adjacency::Graph && dofs) inline
Pushes the dofs-at-macro graph of the next block.
Parameters
[in] dofs The dofs-at-macro graph of the block.
Definition at line 152 of file amavanka.hpp.
References FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_auto_macros, FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_macro_dofs, and XABORTM.
reset_timings()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::reset_timings () inline
Resets the internal stop watches for time measurement.
Definition at line 235 of file amavanka.hpp.
References FEAT::StopWatch::reset().
set_num_steps()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::set_num_steps (Index num_steps) inline
Sets the number of smoothing steps.
Parameters
[in] num_steps The number of smoothing steps to be performed.
Definition at line 177 of file amavanka.hpp.
References XASSERT.
set_omega()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::set_omega (DataType omega) inline
Sets the damping parameter omega.
Parameters
[in] omega The damping parameter.
Definition at line 189 of file amavanka.hpp.
References XASSERT.
set_skip_singular()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::AmaVanka< Matrix_, Filter_ >::set_skip_singular (bool skip_sing) inline
Sets whether singular macros are to be skipped.
Parameters
[in] skip_sing Specifies whether singular macros are to be skipped.
Definition at line 201 of file amavanka.hpp.
time_apply()
template<typename Matrix_ , typename Filter_ > double FEAT::Solver::AmaVanka< Matrix_, Filter_ >::time_apply () const inline
Returns the total accumulated time for the solver application.
Definition at line 261 of file amavanka.hpp.
References FEAT::StopWatch::elapsed().
time_init_numeric()
template<typename Matrix_ , typename Filter_ > double FEAT::Solver::AmaVanka< Matrix_, Filter_ >::time_init_numeric () const inline
Returns the total accumulated time for numeric initialization.
Definition at line 253 of file amavanka.hpp.
References FEAT::StopWatch::elapsed().
time_init_symbolic()
template<typename Matrix_ , typename Filter_ > double FEAT::Solver::AmaVanka< Matrix_, Filter_ >::time_init_symbolic () const inline
Returns the total accumulated time for symbolic initialization.
Definition at line 245 of file amavanka.hpp.
References FEAT::StopWatch::elapsed().
Member Data Documentation
_auto_macros
template<typename Matrix_ , typename Filter_ > bool FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_auto_macros protected
deduct macro dofs automatically?
Definition at line 88 of file amavanka.hpp.
Referenced by FEAT::Solver::AmaVanka< Matrix_, Filter_ >::clear_macro_dofs(), and FEAT::Solver::AmaVanka< Matrix_, Filter_ >::push_macro_dofs().
_dof_macros
template<typename Matrix_ , typename Filter_ > std::vector<Adjacency::Graph> FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_dof_macros protected
Definition at line 92 of file amavanka.hpp.
_filter
template<typename Matrix_ , typename Filter_ > const Filter_& FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_filter protected
the system filter
Definition at line 84 of file amavanka.hpp.
_macro_dofs
template<typename Matrix_ , typename Filter_ > std::vector<Adjacency::Graph> FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_macro_dofs protected
the DOF-macro graphs
Definition at line 92 of file amavanka.hpp.
Referenced by FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_alloc_device(), FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_alloc_max_degrees(), FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_init_numeric_generic(), FEAT::Solver::AmaVanka< Matrix_, Filter_ >::bytes(), FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::init_numeric(), FEAT::Solver::AmaVanka< Matrix_, Filter_ >::init_symbolic(), and FEAT::Solver::AmaVanka< Matrix_, Filter_ >::push_macro_dofs().
_macro_mask
template<typename Matrix_ , typename Filter_ > std::vector<int> FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_macro_mask protected
the macro mask
Definition at line 94 of file amavanka.hpp.
Referenced by FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_alloc_device(), and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_init_numeric_generic().
_matrix
template<typename Matrix_ , typename Filter_ > const Matrix_& FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_matrix protected
the system matrix
Definition at line 82 of file amavanka.hpp.
Referenced by FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::init_numeric().
_num_steps
template<typename Matrix_ , typename Filter_ > Index FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_num_steps protected
number of steps
Definition at line 96 of file amavanka.hpp.
Referenced by FEAT::Solver::AmaVanka< Matrix_, Filter_ >::apply().
_omega
template<typename Matrix_ , typename Filter_ > DataType FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_omega protected
damping parameter
Definition at line 98 of file amavanka.hpp.
Referenced by FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_init_numeric_cuda(), and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_init_numeric_generic().
_skip_singular
template<typename Matrix_ , typename Filter_ > bool FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_skip_singular protected
skip singular macros?
Definition at line 90 of file amavanka.hpp.
Referenced by FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_alloc_device(), FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_init_numeric_cuda(), and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::_init_numeric_generic().
_vanka
template<typename Matrix_ , typename Filter_ > VankaMatrixType FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_vanka protected
the Vanka preconditioner matrix
Definition at line 86 of file amavanka.hpp.
Referenced by FEAT::Solver::AmaVanka< Matrix_, Filter_ >::bytes(), FEAT::Solver::AmaVanka< Matrix_, Filter_ >::data_size(), and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::init_numeric().
_vec_c
template<typename Matrix_ , typename Filter_ > VectorType FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_vec_c protected
temporary vectors
Definition at line 100 of file amavanka.hpp.
Referenced by FEAT::Solver::AmaVanka< Matrix_, Filter_ >::bytes().
_vec_d
template<typename Matrix_ , typename Filter_ > VectorType FEAT::Solver::AmaVanka< Matrix_, Filter_ >::_vec_d protected
Definition at line 100 of file amavanka.hpp.
watch_apply
template<typename Matrix_ , typename Filter_ > StopWatch FEAT::Solver::AmaVanka< Matrix_, Filter_ >::watch_apply protected
Definition at line 107 of file amavanka.hpp.
watch_init_numeric
template<typename Matrix_ , typename Filter_ > StopWatch FEAT::Solver::AmaVanka< Matrix_, Filter_ >::watch_init_numeric protected
Definition at line 105 of file amavanka.hpp.
watch_init_symbolic
template<typename Matrix_ , typename Filter_ > StopWatch FEAT::Solver::AmaVanka< Matrix_, Filter_ >::watch_init_symbolic protected
Definition at line 103 of file amavanka.hpp.
The documentation for this class was generated from the following file:
kernel/solver/amavanka.hpp