FEAT: FEAT::Adjacency::CuthillMcKee Class Reference
FEAT::Adjacency::CuthillMcKee Class Reference
Cuthill McKee implementation.
#include <cuthill_mckee.hpp>
Public Types
enum RootType { root_default = 0 , root_minimum_degree = 1 , root_maximum_degree = 2 }
Root type enumeration.
enum SortType { sort_default = 0 , sort_asc = 1 , sort_desc = 2 }
Sort type enumeration.
Static Public Member Functions
static Permutation compute (const Graph &graph, bool reverse=false, CuthillMcKee::RootType root_type=root_default, CuthillMcKee::SortType sort_type=sort_default)
Cuthill-McKee permutation computation function.
static Permutation compute (std::vector< Index > &layers, const Graph &graph, bool reverse=false, CuthillMcKee::RootType root_type=root_default, CuthillMcKee::SortType sort_type=sort_default)
Cuthill-McKee permutation computation function.
Detailed Description
Cuthill McKee implementation.
Todo:
detailed description
Author
Constantin Christof
Definition at line 28 of file cuthill_mckee.hpp.
Member Enumeration Documentation
RootType
enum FEAT::Adjacency::CuthillMcKee::RootType
Root type enumeration.
This enumeration specifies how the root node of the Cuthill-McKee algorithm is chosen.
Enumerator
root_default
Default root.
In this mode, the first admissible node is chosen.
root_minimum_degree
Minimum-degree root.
In this mode, a node of minimum degree is chosen as the root node.
root_maximum_degree
Maximum-degree root.
In this mode, a node of maximum degree is chosen as the root node.
Definition at line 37 of file cuthill_mckee.hpp.
SortType
enum FEAT::Adjacency::CuthillMcKee::SortType
Sort type enumeration.
This enumeration specifies the order, that is used to arrange the nodes of each level.
Enumerator
sort_default
Default sorting type.
In this mode, the nodes are not sorted at all.
sort_asc
Ascending order.
In this mode, the nodes are arranged in an ascending order corresponding to their degrees.
sort_desc
Descending order.
In this mode, the nodes are arranged in a descending order corresponding to their degrees.
Definition at line 66 of file cuthill_mckee.hpp.
Member Function Documentation
compute() [1/2]
Permutation FEAT::Adjacency::CuthillMcKee::compute (const Graph & graph, bool reverse = false, CuthillMcKee::RootType root_type = root_default, CuthillMcKee::SortType sort_type = sort_default) static
Cuthill-McKee permutation computation function.
This function creates a Cuthill-McKee permutation of the given graph.
Parameters
[in] graph The transient graph that the permutation is calculated for.
[in] reverse This bool determines, if the reverse Cuthill-McKee permutation should be calculated. If true, then the reversed permutation is used.
[in] root_type This parameter determines the way, the root nodes are chosen.
[in] sort_type This parameter determines, which sorting is used in each level of the Cuthill-McKee algorithm.
Returns
The Cuthill-McKee permutation.
Definition at line 15 of file cuthill_mckee.cpp.
References compute().
compute() [2/2]
Permutation FEAT::Adjacency::CuthillMcKee::compute (std::vector< Index > & layers, const Graph & graph, bool reverse = false, CuthillMcKee::RootType root_type = root_default, CuthillMcKee::SortType sort_type = sort_default) static
Cuthill-McKee permutation computation function.
This function creates a Cuthill-McKee permutation of the given graph.
Parameters
[in] graph The transient graph that the permutation is calculated for.
[in] reverse This bool determines, if the reverse Cuthill-McKee permutation should be calculated. If true, then the reversed permutation is used.
[in] root_type This parameter determines the way, the root nodes are chosen.
[in] sort_type This parameter determines, which sorting is used in each level of the Cuthill-McKee algorithm.
Returns
The Cuthill-McKee permutation.
Definition at line 25 of file cuthill_mckee.cpp.
References FEAT::Adjacency::Permutation::calc_swap_from_perm(), FEAT::Adjacency::Graph::degree(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Adjacency::Permutation::get_perm_pos(), root_default, root_maximum_degree, root_minimum_degree, sort_asc, sort_default, sort_desc, XABORTM, and XASSERTM.
Referenced by compute(), and FEAT::Geometry::MeshPermutation< Shape_ >::create_cmk().
The documentation for this class was generated from the following files:
kernel/adjacency/cuthill_mckee.hpp
kernel/adjacency/cuthill_mckee.cpp