FEAT: FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ > Class Template Reference
FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ > Class Template Reference
Power-Col-Matrix meta class template.
#include <power_col_matrix.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = PowerColMatrix< typename SubType_::template ContainerType< DT2_, IT2_ >, blocks_ >
Our 'base' class type.
typedef SubMatrixType::DataType DataType
sub-matrix data type
typedef SubMatrixType::IndexType IndexType
sub-matrix index type
typedef SubType_ SubMatrixType
sub-matrix type
typedef PowerVector< typename SubMatrixType::VectorTypeL, blocks_ > VectorTypeL
Compatible L-vector type.
typedef SubMatrixType::VectorTypeR VectorTypeR
Compatible R-vector type.
Public Member Functions
PowerColMatrix ()
default ctor
PowerColMatrix (const PowerColMatrix &)=delete
deleted copy-ctor
PowerColMatrix (const SparseLayout< IndexType, layout_id > &layout)
sub-matrix layout ctor
PowerColMatrix (FileMode mode, const String &filename)
Constructor.
PowerColMatrix (FileMode mode, std::istream &file, String directory="")
Constructor.
PowerColMatrix (PowerColMatrix &&other)
move ctor
virtual ~PowerColMatrix ()
virtual destructor
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply (VectorTypeL &r, const VectorTypeR &x) const
Applies this matrix onto a vector.
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply_transposed (VectorTypeR &r, const VectorTypeL &x) const
Applies this matrix onto a vector.
void apply_transposed (VectorTypeR &r, const VectorTypeL &x, const VectorTypeR &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
template<int i_, int j_>
SubMatrixType & at ()
Returns a sub-matrix block.
template<int i_, int j_>
const SubMatrixType & at () const
Returns a sub-matrix block.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
PowerColMatrix clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a deep copy of this matrix.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Returns the total number of columns in this matrix.
template<typename SubType2_ >
void convert (const PowerColMatrix< SubType2_, blocks_ > &other)
Conversion method.
template<typename SubType2_ >
void convert_reverse (PowerColMatrix< SubType2_, blocks_ > &other) const
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
SubMatrixType & get (int i, int j)
Returns a sub-matrix block.
const SubMatrixType & get (int i, int j) const
Returns a sub-matrix block.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
Index get_length_of_line (const Index row) const
Returns the number of NNZ-elements of the selected row.
PowerColMatrix & operator= (const PowerColMatrix &)=delete
deleted copy-assign operator
PowerColMatrix & operator= (PowerColMatrix &&other)
move-assign operator
void read_from (FileMode mode, const String &filename)
Read in matrix from file.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Returns the total number of rows in this matrix.
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
template<Perspective perspective_ = Perspective::native>
Index size () const
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Returns the total number of non-zeros in this matrix.
void write_out (FileMode mode, String filename) const
Write out matrix to file.
void write_out_submatrices (FileMode mode, String directory, String prefix, String suffix, Index length=blocks_) const
Write out submatrices to file.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr SparseLayoutId layout_id = SubMatrixType::layout_id
sub-matrix layout type
static constexpr int num_col_blocks = 1
number of column blocks (horizontal size)
static constexpr int num_row_blocks = blocks_
number of row blocks (vertical size)
Protected Member Functions
PowerColMatrix (SubMatrixType &&the_first, RestClass &&the_rest)
base-class constructor; this one is protected for a reason
Protected Attributes
SubMatrixType _first
the last sub-matrix
RestClass _rest
the remaining part
Private Types
typedef PowerColMatrix< SubType_, blocks_-1 > RestClass
rest-class typedef
Friends
bool operator== (const PowerColMatrix &a, const PowerColMatrix &b)
PowerColMatrix comparison operator.
Detailed Description
template<typename SubType_, int blocks_>
class FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >
Power-Col-Matrix meta class template.
This class template implements a vertical composition of n sub-matrices of the same class. This can be interpreted as a dense m-by-1 matrix of other matrices.
Template Parameters
SubType_ The type of the sub-matrix.
blocks_ The number of sub-matrix blocks.
Author
Peter Zajac
Definition at line 40 of file power_col_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename SubType_ , int blocks_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::ContainerType = PowerColMatrix<typename SubType_::template ContainerType<DT2_, IT2_>, blocks_>
Our 'base' class type.
Definition at line 67 of file power_col_matrix.hpp.
DataType
template<typename SubType_ , int blocks_> typedef SubMatrixType::DataType FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::DataType
sub-matrix data type
Definition at line 56 of file power_col_matrix.hpp.
IndexType
template<typename SubType_ , int blocks_> typedef SubMatrixType::IndexType FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::IndexType
sub-matrix index type
Definition at line 58 of file power_col_matrix.hpp.
RestClass
template<typename SubType_ , int blocks_> typedef PowerColMatrix<SubType_, blocks_-1> FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::RestClass private
rest-class typedef
Definition at line 50 of file power_col_matrix.hpp.
SubMatrixType
template<typename SubType_ , int blocks_> typedef SubType_ FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::SubMatrixType
sub-matrix type
Definition at line 54 of file power_col_matrix.hpp.
VectorTypeL
template<typename SubType_ , int blocks_> typedef PowerVector<typename SubMatrixType::VectorTypeL, blocks_> FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::VectorTypeL
Compatible L-vector type.
Definition at line 62 of file power_col_matrix.hpp.
VectorTypeR
template<typename SubType_ , int blocks_> typedef SubMatrixType::VectorTypeR FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::VectorTypeR
Compatible R-vector type.
Definition at line 64 of file power_col_matrix.hpp.
Constructor & Destructor Documentation
PowerColMatrix() [1/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix (SubMatrixType && the_first, RestClass && the_rest) inline explicit protected
base-class constructor; this one is protected for a reason
Definition at line 81 of file power_col_matrix.hpp.
PowerColMatrix() [2/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix () inline
default ctor
Definition at line 89 of file power_col_matrix.hpp.
PowerColMatrix() [3/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix (const SparseLayout< IndexType, layout_id > & layout) inline explicit
sub-matrix layout ctor
Definition at line 94 of file power_col_matrix.hpp.
PowerColMatrix() [4/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix (PowerColMatrix< SubType_, blocks_ > && other) inline
move ctor
Definition at line 101 of file power_col_matrix.hpp.
PowerColMatrix() [5/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix (FileMode mode, const String & filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a power-col-point-matrix based on the source file.
Definition at line 115 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::read_from().
PowerColMatrix() [6/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix (FileMode mode, std::istream & file, String directory = "") inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Note
This constructor is used internally when reading a file
Creates a power-col-matrix based on the source filestream.
Definition at line 130 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, FEAT::String::trim_me(), and XABORTM.
~PowerColMatrix()
template<typename SubType_ , int blocks_> virtual FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::~PowerColMatrix () inline virtual
virtual destructor
Definition at line 196 of file power_col_matrix.hpp.
Member Function Documentation
apply() [1/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 435 of file power_col_matrix.hpp.
apply() [2/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 499 of file power_col_matrix.hpp.
apply() [3/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 429 of file power_col_matrix.hpp.
apply() [4/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 493 of file power_col_matrix.hpp.
apply_transposed() [1/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 465 of file power_col_matrix.hpp.
apply_transposed() [2/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 538 of file power_col_matrix.hpp.
apply_transposed() [3/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this^\top\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 459 of file power_col_matrix.hpp.
apply_transposed() [4/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x, const VectorTypeR & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this^\top \cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 532 of file power_col_matrix.hpp.
at() [1/2]
template<typename SubType_ , int blocks_> template<int i_, int j_> SubMatrixType & FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::at () inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 278 of file power_col_matrix.hpp.
at() [2/2]
template<typename SubType_ , int blocks_> template<int i_, int j_> const SubMatrixType & FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::at () const inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 287 of file power_col_matrix.hpp.
bytes()
template<typename SubType_ , int blocks_> std::size_t FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 260 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::bytes().
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::bytes(), and FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::bytes().
clear()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::clear () inline
Free all allocated arrays.
Definition at line 411 of file power_col_matrix.hpp.
clone()
template<typename SubType_ , int blocks_> PowerColMatrix FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a deep copy of this matrix.
Definition at line 254 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::clone().
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::clone(), and FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::clone().
columns()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::columns () const inline
Returns the total number of columns in this matrix.
Returns
Matrix column count if perspective_ = false.
Raw matrix column count if perspective_ = true.
Definition at line 367 of file power_col_matrix.hpp.
convert()
template<typename SubType_ , int blocks_> template<typename SubType2_ > void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::convert (const PowerColMatrix< SubType2_, blocks_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 653 of file power_col_matrix.hpp.
convert_reverse()
template<typename SubType_ , int blocks_> template<typename SubType2_ > void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::convert_reverse (PowerColMatrix< SubType2_, blocks_ > & other) const inline
Definition at line 660 of file power_col_matrix.hpp.
create_vector_l()
template<typename SubType_ , int blocks_> VectorTypeL FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 553 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::create_vector_l().
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::create_vector_l().
create_vector_r()
template<typename SubType_ , int blocks_> VectorTypeR FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 559 of file power_col_matrix.hpp.
format()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the matrix' entries are to be set to.
Definition at line 402 of file power_col_matrix.hpp.
References FEAT::value.
get() [1/2]
template<typename SubType_ , int blocks_> SubMatrixType & FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get (int i, int j) inline
Returns a sub-matrix block.
Parameters
[in] i,j The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i,j).
Definition at line 303 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get(), and XASSERTM.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_grad_div_matrices(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get(), and FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::get().
get() [2/2]
template<typename SubType_ , int blocks_> const SubMatrixType & FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get (int i, int j) const inline
Returns a sub-matrix block.
Parameters
[in] i,j The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i,j).
Definition at line 310 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get(), and XASSERTM.
get_checkpoint_size()
template<typename SubType_ , int blocks_> std::uint64_t FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 612 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get_checkpoint_size().
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get_checkpoint_size(), and FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::get_checkpoint_size().
get_length_of_line()
template<typename SubType_ , int blocks_> Index FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get_length_of_line (const Index row) const inline
Returns the number of NNZ-elements of the selected row.
Definition at line 565 of file power_col_matrix.hpp.
name()
template<typename SubType_ , int blocks_> static String FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 385 of file power_col_matrix.hpp.
References FEAT::stringify().
operator=()
template<typename SubType_ , int blocks_> PowerColMatrix & FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::operator= (PowerColMatrix< SubType_, blocks_ > && other) inline
move-assign operator
Definition at line 180 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest.
read_from()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::read_from (FileMode mode, const String & filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 153 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, and XABORTM.
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix().
restore_from_checkpoint_data()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 618 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::restore_from_checkpoint_data().
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::restore_from_checkpoint_data(), and FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::restore_from_checkpoint_data().
rows()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::rows () const inline
Returns the total number of rows in this matrix.
Returns
Matrix row count if perspective_ = false.
Raw matrix row count if perspective_ = true.
Definition at line 355 of file power_col_matrix.hpp.
set_checkpoint_data()
template<typename SubType_ , int blocks_> std::uint64_t FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 631 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::set_checkpoint_data().
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::set_checkpoint_data(), and FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::set_checkpoint_data().
size()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::size () const inline
Definition at line 391 of file power_col_matrix.hpp.
used_elements()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::used_elements () const inline
Returns the total number of non-zeros in this matrix.
Returns
Matrix non zero element count if perspective_ = false.
Raw matrix non zero element count if perspective_ = true.
Definition at line 379 of file power_col_matrix.hpp.
write_out()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out (FileMode mode, String filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 206 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out_submatrices(), and XABORTM.
Referenced by FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::write_out().
write_out_submatrices()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out_submatrices (FileMode mode, String directory, String prefix, String suffix, Index length = blocks_) const inline
Write out submatrices to file.
Parameters
[in] mode The used file format.
[in] directory The directory of the matrix-files.
[in] prefix The prefix of the matrix-files.
[in] suffix The suffix of the matrix-files.
Definition at line 245 of file power_col_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest, FEAT::stringify(), and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out_submatrices().
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out(), and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out_submatrices().
Friends And Related Function Documentation
PowerColMatrix
template<typename SubType_ , int blocks_> template<typename , int > friend class PowerColMatrix friend
Definition at line 47 of file power_col_matrix.hpp.
operator==
template<typename SubType_ , int blocks_> bool operator== (const PowerColMatrix< SubType_, blocks_ > & a, const PowerColMatrix< SubType_, blocks_ > & b) friend
PowerColMatrix comparison operator.
Parameters
[in] a A matrix to compare with.
[in] b A matrix to compare with.
Definition at line 672 of file power_col_matrix.hpp.
Member Data Documentation
_first
template<typename SubType_ , int blocks_> SubMatrixType FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_first protected
the last sub-matrix
Definition at line 76 of file power_col_matrix.hpp.
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::bytes(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::clone(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get_checkpoint_size(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::operator=(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::read_from(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::restore_from_checkpoint_data(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::set_checkpoint_data(), and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out_submatrices().
_rest
template<typename SubType_ , int blocks_> RestClass FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::_rest protected
the remaining part
Definition at line 78 of file power_col_matrix.hpp.
Referenced by FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::PowerColMatrix(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::bytes(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::clone(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get_checkpoint_size(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::operator=(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::read_from(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::restore_from_checkpoint_data(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::set_checkpoint_data(), and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out_submatrices().
layout_id
template<typename SubType_ , int blocks_> constexpr SparseLayoutId FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::layout_id = SubMatrixType::layout_id static constexpr
sub-matrix layout type
Definition at line 60 of file power_col_matrix.hpp.
num_col_blocks
template<typename SubType_ , int blocks_> constexpr int FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::num_col_blocks = 1 static constexpr
number of column blocks (horizontal size)
Definition at line 72 of file power_col_matrix.hpp.
num_row_blocks
template<typename SubType_ , int blocks_> constexpr int FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::num_row_blocks = blocks_ static constexpr
number of row blocks (vertical size)
Definition at line 70 of file power_col_matrix.hpp.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_grad_div_matrices().
The documentation for this class was generated from the following file:
kernel/lafem/power_col_matrix.hpp