FEAT: FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ > Class Template Reference
FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ > Class Template Reference
Power-Diag-Matrix meta class template.
#include <power_diag_matrix.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = PowerDiagMatrix< typename SubType_::template ContainerType< DT2_, IT2_ >, blocks_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a matrix container with different Data and Index types
typedef SubMatrixType::DataType DataType
sub-matrix data type
typedef SubMatrixType::IndexType IndexType
sub-matrix index type
typedef SubType_ SubMatrixType
sub-matrix type
typedef PowerVector< typename SubMatrixType::VectorTypeL, blocks_ > VectorTypeL
Compatible L-vector type.
typedef PowerVector< typename SubMatrixType::VectorTypeR, blocks_ > VectorTypeR
Compatible R-vector type.
Public Member Functions
PowerDiagMatrix ()
default ctor
PowerDiagMatrix (const PowerDiagMatrix &)=delete
deleted copy-ctor
PowerDiagMatrix (const SparseLayout< IndexType, layout_id > &layout)
sub-matrix layout ctor
PowerDiagMatrix (FileMode mode, std::istream &file, String directory="")
Constructor.
PowerDiagMatrix (FileMode mode, String filename)
Constructor.
PowerDiagMatrix (PowerDiagMatrix &&other)
move ctor
virtual ~PowerDiagMatrix ()
virtual destructor
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply (VectorTypeL &r, const VectorTypeR &x) const
Applies this matrix onto a vector.
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply_transposed (VectorTypeR &r, const VectorTypeL &x) const
Applies this matrix onto a vector.
void apply_transposed (VectorTypeR &r, const VectorTypeL &x, const VectorTypeR &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
template<int i_, int j_>
SubMatrixType & at ()
Returns a sub-matrix block.
template<int i_, int j_>
const SubMatrixType & at () const
Returns a sub-matrix block.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
void clone (const PowerDiagMatrix &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
PowerDiagMatrix clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a deep copy of this matrix.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Returns the total number of columns in this matrix.
template<typename SubType2_ >
void convert (const PowerDiagMatrix< SubType2_, blocks_ > &other)
Conversion method.
template<typename SubType2_ >
void convert_reverse (PowerDiagMatrix< SubType2_, blocks_ > &other) const
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
void extract_diag (VectorTypeL &diag) const
extract main diagonal vector from matrix
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
SubMatrixType & get (int i, int j)
Returns a sub-matrix block.
const SubMatrixType & get (int i, int j) const
Returns a sub-matrix block.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
Index get_length_of_line (const Index row) const
Returns the number of NNZ-elements of the selected row.
DataType max_rel_diff (const PowerDiagMatrix &x) const
Retrieve the maximum relative difference of this matrix and another one y.max_rel_diff(x) returns \(\max_{0\leq i < n}\frac{|x_i-y_i|}{\max{|x_i|+|y_i|, eps}} \).
PowerDiagMatrix & operator= (const PowerDiagMatrix &)=delete
deleted copy-assign operator
PowerDiagMatrix & operator= (PowerDiagMatrix &&other)
move-assign operator
void read_from (FileMode mode, String filename)
Read in matrix from file.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Returns the total number of rows in this matrix.
bool same_layout (const PowerDiagMatrix &x) const
Checks if the structural layout of this matrix matches that of another matrix. This excludes comparison of the actual data values.
void scale_cols (const PowerDiagMatrix &a, const VectorTypeR &w)
void scale_rows (const PowerDiagMatrix &a, const VectorTypeL &w)
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
Index size () const
PowerDiagMatrix transpose () const
Creates and returns the transpose of this matrix.
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Returns the total number of non-zeros in this matrix.
void write_out (FileMode mode, String filename) const
Write out matrix to file.
void write_out_submatrices (FileMode mode, String directory, String prefix, String suffix, Index length=blocks_) const
Write out submatrices to file.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr SparseLayoutId layout_id = SubMatrixType::layout_id
sub-matrix layout type
static constexpr int num_col_blocks = blocks_
number of column blocks (horizontal size)
static constexpr int num_row_blocks = blocks_
number of row blocks (vertical size)
Protected Member Functions
PowerDiagMatrix (SubMatrixType &&the_first, RestClass &&the_rest)
base-class constructor; this one is protected for a reason
Protected Attributes
SubMatrixType _first
the first sub-matrix
RestClass _rest
the remaining part
Private Types
typedef PowerDiagMatrix< SubType_, blocks_-1 > RestClass
rest-class typedef
Detailed Description
template<typename SubType_, int blocks_>
class FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >
Power-Diag-Matrix meta class template.
This class template implements a diagonal composition of n sub-matrices of the same class. This can be interpreted as a diagonal m-by-m matrix of other matrices.
Template Parameters
SubType_ The type of the sub-matrix.
blocks_ The number of sub-matrix blocks.
Author
Peter Zajac
Definition at line 36 of file power_diag_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename SubType_ , int blocks_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::ContainerType = PowerDiagMatrix<typename SubType_::template ContainerType<DT2_, IT2_>, blocks_>
Our 'base' class type.
Definition at line 63 of file power_diag_matrix.hpp.
ContainerTypeByDI
template<typename SubType_ , int blocks_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a matrix container with different Data and Index types
Definition at line 67 of file power_diag_matrix.hpp.
DataType
template<typename SubType_ , int blocks_> typedef SubMatrixType::DataType FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::DataType
sub-matrix data type
Definition at line 52 of file power_diag_matrix.hpp.
IndexType
template<typename SubType_ , int blocks_> typedef SubMatrixType::IndexType FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::IndexType
sub-matrix index type
Definition at line 54 of file power_diag_matrix.hpp.
RestClass
template<typename SubType_ , int blocks_> typedef PowerDiagMatrix<SubType_, blocks_-1> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::RestClass private
rest-class typedef
Definition at line 46 of file power_diag_matrix.hpp.
SubMatrixType
template<typename SubType_ , int blocks_> typedef SubType_ FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::SubMatrixType
sub-matrix type
Definition at line 50 of file power_diag_matrix.hpp.
VectorTypeL
template<typename SubType_ , int blocks_> typedef PowerVector<typename SubMatrixType::VectorTypeL, blocks_> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::VectorTypeL
Compatible L-vector type.
Definition at line 58 of file power_diag_matrix.hpp.
VectorTypeR
template<typename SubType_ , int blocks_> typedef PowerVector<typename SubMatrixType::VectorTypeR, blocks_> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::VectorTypeR
Compatible R-vector type.
Definition at line 60 of file power_diag_matrix.hpp.
Constructor & Destructor Documentation
PowerDiagMatrix() [1/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix (SubMatrixType && the_first, RestClass && the_rest) inline explicit protected
base-class constructor; this one is protected for a reason
Definition at line 81 of file power_diag_matrix.hpp.
PowerDiagMatrix() [2/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix () inline
default ctor
Definition at line 89 of file power_diag_matrix.hpp.
PowerDiagMatrix() [3/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix (const SparseLayout< IndexType, layout_id > & layout) inline explicit
sub-matrix layout ctor
Definition at line 94 of file power_diag_matrix.hpp.
PowerDiagMatrix() [4/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix (PowerDiagMatrix< SubType_, blocks_ > && other) inline
move ctor
Definition at line 101 of file power_diag_matrix.hpp.
PowerDiagMatrix() [5/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix (FileMode mode, String filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a power-diag-point-matrix based on the source file.
Definition at line 115 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::read_from().
PowerDiagMatrix() [6/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix (FileMode mode, std::istream & file, String directory = "") inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Note
This constructor is used internally when reading a file
Creates a power-diag-matrix based on the source filestream.
Definition at line 130 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, FEAT::String::trim_me(), and XABORTM.
~PowerDiagMatrix()
template<typename SubType_ , int blocks_> virtual FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::~PowerDiagMatrix () inline virtual
virtual destructor
Definition at line 196 of file power_diag_matrix.hpp.
Member Function Documentation
apply() [1/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 496 of file power_diag_matrix.hpp.
apply() [2/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 566 of file power_diag_matrix.hpp.
apply() [3/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 490 of file power_diag_matrix.hpp.
apply() [4/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 560 of file power_diag_matrix.hpp.
apply_transposed() [1/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 529 of file power_diag_matrix.hpp.
apply_transposed() [2/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 608 of file power_diag_matrix.hpp.
apply_transposed() [3/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this^\top \cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 523 of file power_diag_matrix.hpp.
apply_transposed() [4/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x, const VectorTypeR & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this^\top \cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 602 of file power_diag_matrix.hpp.
at() [1/2]
template<typename SubType_ , int blocks_> template<int i_, int j_> SubMatrixType & FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::at () inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 299 of file power_diag_matrix.hpp.
at() [2/2]
template<typename SubType_ , int blocks_> template<int i_, int j_> const SubMatrixType & FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::at () const inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 308 of file power_diag_matrix.hpp.
bytes()
template<typename SubType_ , int blocks_> std::size_t FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 273 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::bytes().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::bytes().
clear()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::clear () inline
Free all allocated arrays.
Definition at line 465 of file power_diag_matrix.hpp.
clone() [1/2]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::clone (const PowerDiagMatrix< SubType_, blocks_ > & other, CloneMode clone_mode = CloneMode::Weak) inline
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 267 of file power_diag_matrix.hpp.
clone() [2/2]
template<typename SubType_ , int blocks_> PowerDiagMatrix FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a deep copy of this matrix.
Definition at line 254 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::clone().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::clone().
columns()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::columns () const inline
Returns the total number of columns in this matrix.
Returns
Matrix column count if perspective_ = false.
Raw matrix column count if perspective_ = true.
Definition at line 422 of file power_diag_matrix.hpp.
convert()
template<typename SubType_ , int blocks_> template<typename SubType2_ > void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::convert (const PowerDiagMatrix< SubType2_, blocks_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 733 of file power_diag_matrix.hpp.
convert_reverse()
template<typename SubType_ , int blocks_> template<typename SubType2_ > void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::convert_reverse (PowerDiagMatrix< SubType2_, blocks_ > & other) const inline
Definition at line 740 of file power_diag_matrix.hpp.
create_vector_l()
template<typename SubType_ , int blocks_> VectorTypeL FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 654 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::create_vector_l().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::create_vector_l().
create_vector_r()
template<typename SubType_ , int blocks_> VectorTypeR FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 660 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::create_vector_r().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::create_vector_r().
extract_diag()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::extract_diag (VectorTypeL & diag) const inline
extract main diagonal vector from matrix
Definition at line 472 of file power_diag_matrix.hpp.
format()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the matrix' entries are to be set to.
Definition at line 456 of file power_diag_matrix.hpp.
References FEAT::value.
get() [1/2]
template<typename SubType_ , int blocks_> SubMatrixType & FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get (int i, int j) inline
Returns a sub-matrix block.
Parameters
[in] i,j The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i,j).
Definition at line 324 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get(), and XASSERTM.
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get().
get() [2/2]
template<typename SubType_ , int blocks_> const SubMatrixType & FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get (int i, int j) const inline
Returns a sub-matrix block.
Parameters
[in] i,j The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i,j).
Definition at line 331 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get(), and XASSERTM.
get_checkpoint_size()
template<typename SubType_ , int blocks_> std::uint64_t FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 338 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get_checkpoint_size().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get_checkpoint_size().
get_length_of_line()
template<typename SubType_ , int blocks_> Index FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get_length_of_line (const Index row) const inline
Returns the number of NNZ-elements of the selected row.
Definition at line 678 of file power_diag_matrix.hpp.
max_rel_diff()
template<typename SubType_ , int blocks_> DataType FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::max_rel_diff (const PowerDiagMatrix< SubType_, blocks_ > & x) const inline
Retrieve the maximum relative difference of this matrix and another one y.max_rel_diff(x) returns \(\max_{0\leq i < n}\frac{|x_i-y_i|}{\max{|x_i|+|y_i|, eps}} \).
Returns
The largest relative difference.
Definition at line 634 of file power_diag_matrix.hpp.
References FEAT::Math::max(), and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::max_rel_diff().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::max_rel_diff().
name()
template<typename SubType_ , int blocks_> static String FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 440 of file power_diag_matrix.hpp.
References FEAT::stringify().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::same_layout().
operator=()
template<typename SubType_ , int blocks_> PowerDiagMatrix & FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::operator= (PowerDiagMatrix< SubType_, blocks_ > && other) inline
move-assign operator
Definition at line 180 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest.
read_from()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::read_from (FileMode mode, String filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 153 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, and XABORTM.
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix().
restore_from_checkpoint_data()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 344 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::restore_from_checkpoint_data().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::restore_from_checkpoint_data().
rows()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::rows () const inline
Returns the total number of rows in this matrix.
Returns
Matrix row count if perspective_ = false.
Raw matrix row count if perspective_ = true.
Definition at line 410 of file power_diag_matrix.hpp.
same_layout()
template<typename SubType_ , int blocks_> bool FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::same_layout (const PowerDiagMatrix< SubType_, blocks_ > & x) const inline
Checks if the structural layout of this matrix matches that of another matrix. This excludes comparison of the actual data values.
Parameters
[in] x The matrix to compare this matrix to
Returns
true if the layouts match, false otherwise.
Definition at line 648 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::name().
scale_cols()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::scale_cols (const PowerDiagMatrix< SubType_, blocks_ > & a, const VectorTypeR & w) inline
Definition at line 671 of file power_diag_matrix.hpp.
scale_rows()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::scale_rows (const PowerDiagMatrix< SubType_, blocks_ > & a, const VectorTypeL & w) inline
Definition at line 665 of file power_diag_matrix.hpp.
set_checkpoint_data()
template<typename SubType_ , int blocks_> std::uint64_t FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 357 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::set_checkpoint_data().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::set_checkpoint_data().
size()
template<typename SubType_ , int blocks_> Index FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::size () const inline
Definition at line 445 of file power_diag_matrix.hpp.
transpose()
template<typename SubType_ , int blocks_> PowerDiagMatrix FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::transpose () const inline
Creates and returns the transpose of this matrix.
Definition at line 281 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::transpose().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::transpose().
used_elements()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::used_elements () const inline
Returns the total number of non-zeros in this matrix.
Returns
Matrix non zero element count if perspective_ = false.
Raw matrix non zero element count if perspective_ = true.
Definition at line 434 of file power_diag_matrix.hpp.
write_out()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out (FileMode mode, String filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 206 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out_submatrices(), and XABORTM.
write_out_submatrices()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out_submatrices (FileMode mode, String directory, String prefix, String suffix, Index length = blocks_) const inline
Write out submatrices to file.
Parameters
[in] mode The used file format.
[in] directory The directory of the matrix-files.
[in] prefix The prefix of the matrix-files.
[in] suffix The suffix of the matrix-files.
Definition at line 245 of file power_diag_matrix.hpp.
References FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest, FEAT::stringify(), and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out_submatrices().
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out(), and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out_submatrices().
Friends And Related Function Documentation
PowerDiagMatrix
template<typename SubType_ , int blocks_> template<typename , int > friend class PowerDiagMatrix friend
Definition at line 43 of file power_diag_matrix.hpp.
Member Data Documentation
_first
template<typename SubType_ , int blocks_> SubMatrixType FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_first protected
the first sub-matrix
Definition at line 76 of file power_diag_matrix.hpp.
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::bytes(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::clone(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get_checkpoint_size(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::operator=(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::read_from(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::restore_from_checkpoint_data(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::set_checkpoint_data(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::transpose(), and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out_submatrices().
_rest
template<typename SubType_ , int blocks_> RestClass FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::_rest protected
the remaining part
Definition at line 78 of file power_diag_matrix.hpp.
Referenced by FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::PowerDiagMatrix(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::bytes(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::clone(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::get_checkpoint_size(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::operator=(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::read_from(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::restore_from_checkpoint_data(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::set_checkpoint_data(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::transpose(), and FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out_submatrices().
layout_id
template<typename SubType_ , int blocks_> constexpr SparseLayoutId FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::layout_id = SubMatrixType::layout_id static constexpr
sub-matrix layout type
Definition at line 56 of file power_diag_matrix.hpp.
num_col_blocks
template<typename SubType_ , int blocks_> constexpr int FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::num_col_blocks = blocks_ static constexpr
number of column blocks (horizontal size)
Definition at line 72 of file power_diag_matrix.hpp.
num_row_blocks
template<typename SubType_ , int blocks_> constexpr int FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::num_row_blocks = blocks_ static constexpr
number of row blocks (vertical size)
Definition at line 70 of file power_diag_matrix.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/power_diag_matrix.hpp