FEAT: FEAT::Geometry::ExportEPS Class Reference
FEAT::Geometry::ExportEPS Class Reference
EPS exporter class.
#include <export_eps.hpp>
Static Public Member Functions
template<typename Shape_ , typename DataType_ >
static void write (const String &filename, const ConformalMesh< Shape_, 2, DataType_ > &mesh, const double width=100.0, const double height=100.0, const double stroke=0.1, const double extra=0.0)
Exports a mesh to an EPS file.
template<typename Shape_ , typename DataType_ >
static void write (std::ostream &os, const ConformalMesh< Shape_, 2, DataType_ > &mesh, const double width=100.0, const double height=100.0, const double stroke=0.1, const double extra=0.0)
Exports a mesh to an EPS file.
Detailed Description
EPS exporter class.
This class implements an exporter for the Encapsulated Post-Script (EPS) file format, which can be used to generate mesh plots for LaTeX documents.
Note
This class can only export 2D meshes.
Author
Peter Zajac
Definition at line 35 of file export_eps.hpp.
Member Function Documentation
write() [1/2]
template<typename Shape_ , typename DataType_ > static void FEAT::Geometry::ExportEPS::write (const String & filename, const ConformalMesh< Shape_, 2, DataType_ > & mesh, const double width = 100.0, const double height = 100.0, const double stroke = 0.1, const double extra = 0.0) inline static
Exports a mesh to an EPS file.
Parameters
[in] filename The name of the output file.
[in] mesh The 2D conformal mesh that is to be exported.
[in] width,height The maximum dimensions of the bounding box in millimeters.
[in] stroke The stroke width in millimeters.
[in] extra The extra bounding box offset in millimeters.
Definition at line 157 of file export_eps.hpp.
References write().
write() [2/2]
template<typename Shape_ , typename DataType_ > static void FEAT::Geometry::ExportEPS::write (std::ostream & os, const ConformalMesh< Shape_, 2, DataType_ > & mesh, const double width = 100.0, const double height = 100.0, const double stroke = 0.1, const double extra = 0.0) inline static
Exports a mesh to an EPS file.
Parameters
[in,out] os The output stream to which to write to.
[in] mesh The 2D conformal mesh that is to be exported.
[in] width,height The maximum dimensions of the bounding box in millimeters.
[in] stroke The stroke width in millimeters.
[in] extra The extra bounding box offset in millimeters.
Definition at line 57 of file export_eps.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_vertex_set(), FEAT::Math::min(), FEAT::Math::minimax(), and XASSERTM.
Referenced by write().
The documentation for this class was generated from the following file:
kernel/geometry/export_eps.hpp