FEAT: FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > > Class Template Reference
FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > > Class Template Reference abstract
BFBT specialization for Global matrices.
#include <bfbt.hpp>
Public Types
typedef Solver::SolverBase< GlobalVectorType > BaseClass
typedef GlobalVectorType::DataType DataType
typedef Global::Filter< FilterP_, MirrorP_ > GlobalFilterTypeP
typedef Global::Filter< FilterV_, MirrorV_ > GlobalFilterTypeV
typedef Global::Matrix< LocalMatrixType, MirrorType, MirrorType > GlobalMatrixType
typedef Global::Matrix< MatrixA_, MirrorV_, MirrorV_ > GlobalMatrixTypeA
typedef Global::Matrix< MatrixB_, MirrorV_, MirrorP_ > GlobalMatrixTypeB
typedef Global::Matrix< MatrixD_, MirrorP_, MirrorV_ > GlobalMatrixTypeD
typedef Global::Vector< LocalVectorType, MirrorType > GlobalVectorType
typedef Global::Vector< LocalVectorTypeP, MirrorP_ > GlobalVectorTypeP
typedef Global::Vector< LocalVectorTypeV, MirrorV_ > GlobalVectorTypeV
typedef LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > LocalMatrixType
typedef LAFEM::TupleVector< typename MatrixB_::VectorTypeL, typename MatrixD_::VectorTypeL > LocalVectorType
typedef MatrixD_::VectorTypeL LocalVectorTypeP
typedef MatrixB_::VectorTypeL LocalVectorTypeV
typedef LAFEM::TupleMirror< MirrorV_, MirrorP_ > MirrorType
typedef Solver::SolverBase< GlobalVectorTypeV > SolverA
typedef Solver::SolverBase< GlobalVectorTypeP > SolverS
typedef Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > VectorType
The type of vector this solver can be applied to.
Public Member Functions
BFBT (const GlobalMatrixTypeA &matrix_a, const GlobalMatrixTypeB &matrix_b, const GlobalMatrixTypeD &matrix_d, const GlobalFilterTypeV &filter_v, const GlobalFilterTypeP &filter_p, std::shared_ptr< SolverA > solver_left, std::shared_ptr< SolverS > solver_right, const GlobalVectorTypeV &lumped_velo_mass_vec)
virtual Status apply (Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > &vec_cor, const Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > &vec_def)=0
Solver application method.
virtual Status apply (GlobalVectorTypeP &vec_cor, const GlobalVectorTypeP &vec_def) override
virtual void done ()
Finalization method.
virtual void done_numeric () override
Numeric finalization method.
virtual void done_symbolic () override
Symbolic finalization method.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric initialization method.
virtual void init_symbolic () override
Symbolic initialization method.
virtual String name () const override
Returns a descriptive string.
Protected Attributes
const GlobalFilterTypeP & _filter_p
const GlobalFilterTypeV & _filter_v
const GlobalVectorTypeV & _lumped_velo_mass_vec
const GlobalMatrixTypeA & _matrix_a
const GlobalMatrixTypeB & _matrix_b
const GlobalMatrixTypeD & _matrix_d
std::shared_ptr< SolverA > _solver_left
std::shared_ptr< SolverS > _solver_right
GlobalVectorTypeV _vec_tmp_v1
GlobalVectorTypeV _vec_tmp_v2
Detailed Description
template<typename MatrixA_, typename MatrixB_, typename MatrixD_, typename FilterV_, typename FilterP_, typename MirrorV_, typename MirrorP_>
class FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >
BFBT specialization for Global matrices.
Author
Pia Ritter
Definition at line 265 of file bfbt.hpp.
Member Typedef Documentation
BaseClass
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Solver::SolverBase<GlobalVectorType> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::BaseClass
Definition at line 293 of file bfbt.hpp.
DataType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef GlobalVectorType::DataType FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::DataType
Definition at line 291 of file bfbt.hpp.
GlobalFilterTypeP
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Filter<FilterP_, MirrorP_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalFilterTypeP
Definition at line 300 of file bfbt.hpp.
GlobalFilterTypeV
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Filter<FilterV_, MirrorV_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalFilterTypeV
Definition at line 299 of file bfbt.hpp.
GlobalMatrixType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<LocalMatrixType, MirrorType, MirrorType> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalMatrixType
Definition at line 288 of file bfbt.hpp.
GlobalMatrixTypeA
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<MatrixA_, MirrorV_, MirrorV_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalMatrixTypeA
Definition at line 295 of file bfbt.hpp.
GlobalMatrixTypeB
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<MatrixB_, MirrorV_, MirrorP_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalMatrixTypeB
Definition at line 296 of file bfbt.hpp.
GlobalMatrixTypeD
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<MatrixD_, MirrorP_, MirrorV_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalMatrixTypeD
Definition at line 297 of file bfbt.hpp.
GlobalVectorType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Vector<LocalVectorType, MirrorType> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalVectorType
Definition at line 289 of file bfbt.hpp.
GlobalVectorTypeP
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Vector<LocalVectorTypeP, MirrorP_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalVectorTypeP
Definition at line 306 of file bfbt.hpp.
GlobalVectorTypeV
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Vector<LocalVectorTypeV, MirrorV_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalVectorTypeV
Definition at line 305 of file bfbt.hpp.
LocalMatrixType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef LAFEM::SaddlePointMatrix<MatrixA_, MatrixB_, MatrixD_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalMatrixType
Definition at line 284 of file bfbt.hpp.
LocalVectorType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef LAFEM::TupleVector<typename MatrixB_::VectorTypeL, typename MatrixD_::VectorTypeL> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalVectorType
Definition at line 285 of file bfbt.hpp.
LocalVectorTypeP
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef MatrixD_::VectorTypeL FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalVectorTypeP
Definition at line 303 of file bfbt.hpp.
LocalVectorTypeV
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef MatrixB_::VectorTypeL FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalVectorTypeV
Definition at line 302 of file bfbt.hpp.
MirrorType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef LAFEM::TupleMirror<MirrorV_, MirrorP_> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::MirrorType
Definition at line 286 of file bfbt.hpp.
SolverA
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Solver::SolverBase<GlobalVectorTypeV> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::SolverA
Definition at line 308 of file bfbt.hpp.
SolverS
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Solver::SolverBase<GlobalVectorTypeP> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::SolverS
Definition at line 309 of file bfbt.hpp.
VectorType
typedef Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >::VectorType inherited
The type of vector this solver can be applied to.
Definition at line 186 of file base.hpp.
Constructor & Destructor Documentation
BFBT()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::BFBT (const GlobalMatrixTypeA & matrix_a, const GlobalMatrixTypeB & matrix_b, const GlobalMatrixTypeD & matrix_d, const GlobalFilterTypeV & filter_v, const GlobalFilterTypeP & filter_p, std::shared_ptr< SolverA > solver_left, std::shared_ptr< SolverS > solver_right, const GlobalVectorTypeV & lumped_velo_mass_vec) inline explicit
Definition at line 323 of file bfbt.hpp.
Member Function Documentation
apply() [1/2]
virtual Status FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >::apply (Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > & vec_cor, const Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
apply() [2/2]
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual Status FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::apply (GlobalVectorTypeP & vec_cor, const GlobalVectorTypeP & vec_def) inline override virtual
Definition at line 385 of file bfbt.hpp.
done()
virtual void FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
done_numeric()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual void FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric () inline override virtual
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 367 of file bfbt.hpp.
References FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_left, FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_right, FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_vec_tmp_v1, FEAT::Global::Vector< LocalVector_, Mirror_ >::clear(), and FEAT::Solver::SolverBase< Vector_ >::done_numeric().
done_symbolic()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual void FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_symbolic () inline override virtual
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 377 of file bfbt.hpp.
References FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_left, FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_right, and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
init()
virtual void FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
init_numeric()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual void FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_numeric () inline override virtual
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 359 of file bfbt.hpp.
References FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_left, FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_right, and FEAT::Solver::SolverBase< Vector_ >::init_numeric().
init_symbolic()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual void FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 349 of file bfbt.hpp.
References FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_left, FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_right, FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_vec_tmp_v1, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_l(), and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
name()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual String FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::name () const inline override virtual
Returns a descriptive string.
Returns
A string describing the solver.
Implements FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 344 of file bfbt.hpp.
Member Data Documentation
_filter_p
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalFilterTypeP& FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_filter_p protected
Definition at line 316 of file bfbt.hpp.
_filter_v
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalFilterTypeV& FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_filter_v protected
Definition at line 315 of file bfbt.hpp.
_lumped_velo_mass_vec
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalVectorTypeV& FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_lumped_velo_mass_vec protected
Definition at line 320 of file bfbt.hpp.
_matrix_a
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalMatrixTypeA& FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_matrix_a protected
Definition at line 312 of file bfbt.hpp.
_matrix_b
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalMatrixTypeB& FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_matrix_b protected
Definition at line 313 of file bfbt.hpp.
_matrix_d
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalMatrixTypeD& FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_matrix_d protected
Definition at line 314 of file bfbt.hpp.
_solver_left
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > std::shared_ptr<SolverA> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_solver_left protected
Definition at line 317 of file bfbt.hpp.
_solver_right
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > std::shared_ptr<SolverS> FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_solver_right protected
Definition at line 318 of file bfbt.hpp.
_vec_tmp_v1
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeV FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_vec_tmp_v1 protected
Definition at line 319 of file bfbt.hpp.
_vec_tmp_v2
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeV FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_vec_tmp_v2 protected
Definition at line 319 of file bfbt.hpp.
The documentation for this class was generated from the following file:
kernel/solver/bfbt.hpp