FEAT: FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ > Class Template Reference
FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ > Class Template Reference
Storage class for a single layer of the adaptive mesh.
#include <adaptive_mesh_storage.hpp>
Public Member Functions
std::size_t bytes () const
Returns number of bytes used by this layer.
template<int dim_>
void erase (ElementKey< dim_ > key)
Erase an element from this layer.
template<int dim_>
AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType > & get (ElementKey< dim_ > key)
Retrieve the AdaptiveElement belonging to the given key.
template<int dim_>
const AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType > & get (ElementKey< dim_ > key) const
Retrieve the AdaptiveElement belonging to the given key.
template<typename Shape_ >
ElementKey< Shape_::dimension > insert_permanent (const AdaptiveElement< TemplateSet_, Shape_ > &element)
Insert a permanent element into this layer.
template<typename Shape_ >
ElementKey< Shape_::dimension > insert_transient (const AdaptiveElement< TemplateSet_, Shape_ > &element)
Insert a transient element into this layer.
template<int dim_>
Index num_permanent_entities () const
Get number of permanent entities of dimension dim_ in this layer.
template<int dim_>
Index num_transient_entities () const
Get number of transient entities of dimension dim_ in this layer.
template<int dim_>
Util::SlotMap< AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >, ElementKey< dim_ > > & permanent_entities ()
Permanent element SlotMap accessor.
template<int dim_>
const Util::SlotMap< AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >, ElementKey< dim_ > > & permanent_entities () const
Permanent element SlotMap accessor.
template<int dim_>
Util::SlotMap< AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >, ElementKey< dim_ > > & transient_entities ()
Transient element SlotMap accessor.
template<int dim_>
const Util::SlotMap< AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >, ElementKey< dim_ > > & transient_entities () const
Transient element SlotMap accessor.
Protected Types
using AdaptiveElementType = AdaptiveElement< TemplateSet_, ShapeType >
Type of AdaptiveElement managed by this dimension of the MeshLayer.
using BaseClass = MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >
using ElementKeyType = ElementKey< element_dim_ >
Key type for AdaptiveElementType.
using ShapeType = typename Shape::FaceTraits< MeshShape_, element_dim_ >::ShapeType
Shape type of entities stored in this layer of dimension element_dim_.
Protected Attributes
Util::SlotMap< AdaptiveElementType, ElementKeyType > _permanent_entities
Slotmap for permanent mesh elements.
Util::SlotMap< AdaptiveElementType, ElementKeyType > _transient_entities
Slotmap for transient mesh elements.
Detailed Description
template<typename TemplateSet_, typename MeshShape_, typename VertexType_, int element_dim_ = MeshShape_::dimension>
class FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >
Storage class for a single layer of the adaptive mesh.
This class provides storage and utility methods to manage the elements of a single layer of the adaptive mesh.
Uses self-inheritance to construct itself with support for all required dimensions.
Template Parameters
TemplateSet_ Template set for mesh refinement
VertexType_ Type of vertices to be stored
element_dim_ Dimension of this component of the mesh layer
Author
Markus Muegge
Definition at line 446 of file adaptive_mesh_storage.hpp.
Member Typedef Documentation
AdaptiveElementType
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> using FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::AdaptiveElementType = AdaptiveElement<TemplateSet_, ShapeType> protected
Type of AdaptiveElement managed by this dimension of the MeshLayer.
Definition at line 455 of file adaptive_mesh_storage.hpp.
BaseClass
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> using FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::BaseClass = MeshLayer<TemplateSet_, MeshShape_, VertexType_, element_dim_> protected
Definition at line 449 of file adaptive_mesh_storage.hpp.
ElementKeyType
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> using FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::ElementKeyType = ElementKey<element_dim_> protected
Key type for AdaptiveElementType.
Definition at line 457 of file adaptive_mesh_storage.hpp.
ShapeType
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> using FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::ShapeType = typename Shape::FaceTraits<MeshShape_, element_dim_>::ShapeType protected
Shape type of entities stored in this layer of dimension element_dim_.
Definition at line 452 of file adaptive_mesh_storage.hpp.
Member Function Documentation
bytes()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> std::size_t FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::bytes () const inline
Returns number of bytes used by this layer.
Definition at line 597 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::_permanent_entities, FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::_transient_entities, and FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::bytes().
Referenced by FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::bytes().
erase()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> void FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::erase (ElementKey< dim_ > key) inline
Erase an element from this layer.
Parameters
key Key of the element to be erased
Definition at line 505 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::erase(), and FEAT::Geometry::Intern::ElementKey< n >::is_permanent.
Referenced by FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::erase().
get() [1/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::get (ElementKey< dim_ > key) inline
Retrieve the AdaptiveElement belonging to the given key.
Template Parameters
dim_ Dimension of element to retrieve
Parameters
key Key of element to retrieve
Returns
A reference to the AdaptiveElement pointed to by the key
Definition at line 610 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::ElementKey< n >::is_permanent.
get() [2/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> const AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::get (ElementKey< dim_ > key) const inline
Retrieve the AdaptiveElement belonging to the given key.
Template Parameters
dim_ Dimension of element to retrieve
Parameters
key Key of element to retrieve
Returns
A reference to the AdaptiveElement pointed to by the key
Definition at line 631 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::ElementKey< n >::is_permanent.
insert_permanent()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<typename Shape_ > ElementKey< Shape_::dimension > FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::insert_permanent (const AdaptiveElement< TemplateSet_, Shape_ > & element) inline
Insert a permanent element into this layer.
Parameters
element r-value reference to an adaptive element
Returns
Key of the inserted element
Note that the returned key is not yet tagged with the correct layer. You need to do so yourself.
Definition at line 475 of file adaptive_mesh_storage.hpp.
insert_transient()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<typename Shape_ > ElementKey< Shape_::dimension > FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::insert_transient (const AdaptiveElement< TemplateSet_, Shape_ > & element) inline
Insert a transient element into this layer.
Parameters
element r-value reference to an adaptive element
Returns
Key of the inserted element
Note that the returned key is not yet tagged with the correct layer. You need to do so yourself.
Definition at line 492 of file adaptive_mesh_storage.hpp.
num_permanent_entities()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> Index FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::num_permanent_entities () const inline
Get number of permanent entities of dimension dim_ in this layer.
Template Parameters
dim_ Dimension of mesh elements to return number of
Returns
Number of permanent mesh elements of dimension dim_
Definition at line 531 of file adaptive_mesh_storage.hpp.
num_transient_entities()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> Index FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::num_transient_entities () const inline
Get number of transient entities of dimension dim_ in this layer.
Template Parameters
dim_ Dimension of mesh elements to return number of
Returns
Number of transient mesh elements of dimension dim_
Definition at line 550 of file adaptive_mesh_storage.hpp.
permanent_entities() [1/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> Util::SlotMap< AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >, ElementKey< dim_ > > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::permanent_entities () inline
Permanent element SlotMap accessor.
Definition at line 565 of file adaptive_mesh_storage.hpp.
permanent_entities() [2/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> const Util::SlotMap< AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >, ElementKey< dim_ > > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::permanent_entities () const inline
Permanent element SlotMap accessor.
Definition at line 573 of file adaptive_mesh_storage.hpp.
transient_entities() [1/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> Util::SlotMap< AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >, ElementKey< dim_ > > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::transient_entities () inline
Transient element SlotMap accessor.
Definition at line 581 of file adaptive_mesh_storage.hpp.
transient_entities() [2/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> template<int dim_> const Util::SlotMap< AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >, ElementKey< dim_ > > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::transient_entities () const inline
Transient element SlotMap accessor.
Definition at line 589 of file adaptive_mesh_storage.hpp.
Member Data Documentation
_permanent_entities
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> Util::SlotMap<AdaptiveElementType, ElementKeyType> FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::_permanent_entities protected
Slotmap for permanent mesh elements.
Definition at line 460 of file adaptive_mesh_storage.hpp.
Referenced by FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::bytes().
_transient_entities
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ , int element_dim_ = MeshShape_::dimension> Util::SlotMap<AdaptiveElementType, ElementKeyType> FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::_transient_entities protected
Slotmap for transient mesh elements.
Definition at line 462 of file adaptive_mesh_storage.hpp.
Referenced by FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, element_dim_ >::bytes().
The documentation for this class was generated from the following file:
kernel/geometry/intern/adaptive_mesh_storage.hpp