FEAT: FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ > Class Template Reference
FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ > Class Template Reference
Mean Filter Blocked class template.
#include <mean_filter_blocked.hpp>
Public Types
typedef VectorType::DataType DataType
data-type typedef
template<typename DT2_ = DT_, typename IT2_ = IT_, int BlockSize2_ = BlockSize_>
using FilterType = MeanFilterBlocked< DT2_, IT2_, BlockSize2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ , int BS2_>
using FilterTypeByDI = FilterType< DataType2_, IndexType2_, BS2_ >
this typedef lets you create a filter with different Data and Index types
typedef VectorType::IndexType IndexType
index-type typedef
typedef VectorType::ValueType ValueType
value-type typedef
typedef DenseVectorBlocked< DT_, IT_, BlockSize_ > VectorType
vector-type typedef
Public Member Functions
MeanFilterBlocked (MeanFilterBlocked &&other)
move ctor
MeanFilterBlocked (VectorType &&vec_prim, VectorType &&vec_dual, ValueType sol_mean, ValueType volume)
Constructor.
MeanFilterBlocked (VectorType &&vec_prim, VectorType &&vec_dual, ValueType sol_mean=ValueType(0))
Constructor.
virtual ~MeanFilterBlocked ()
virtual destructor
void clear ()
Clears this filter.
MeanFilterBlocked clone (CloneMode clone_mode=CloneMode::Deep) const
Creates a clone of itself.
void clone (const MeanFilterBlocked &other, CloneMode clone_mode=CloneMode::Deep)
Clones data from another MeanFilterBlocked.
template<typename DT2_ , typename IT2_ , int BlockSize2_>
void convert (const MeanFilterBlocked< DT2_, IT2_, BlockSize2_ > &other)
Conversion method.
void filter_cor (VectorType &vector) const
Applies the filter onto a correction vector.
void filter_def (VectorType &vector) const
Applies the filter onto a defect vector.
template<typename MT_ >
void filter_mat (MT_ &matrix) const
Applies the filter onto a system matrix.
void filter_rhs (VectorType &vector) const
Applies the filter onto the right-hand-side vector.
void filter_sol (VectorType &vector) const
Applies the filter onto the solution vector.
MeanFilterBlocked & operator= (MeanFilterBlocked &&other)
move-assign operator
Protected Attributes
ValueType _sol_mean
desired solution vector mean
VectorType _vec_dual
dual weighting vector
VectorType _vec_prim
primal weighting vector
ValueType _volume
weight volume
Detailed Description
template<typename DT_, typename IT_, int BlockSize_>
class FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >
Mean Filter Blocked class template.
Author
Pia Ritter
Definition at line 20 of file mean_filter_blocked.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ , int BlockSize_> typedef VectorType::DataType FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::DataType
data-type typedef
Definition at line 26 of file mean_filter_blocked.hpp.
FilterType
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_, int BlockSize2_ = BlockSize_> using FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::FilterType = MeanFilterBlocked<DT2_, IT2_, BlockSize2_>
Our 'base' class type.
Definition at line 34 of file mean_filter_blocked.hpp.
FilterTypeByDI
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DataType2_ , typename IndexType2_ , int BS2_> using FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::FilterTypeByDI = FilterType<DataType2_, IndexType2_, BS2_>
this typedef lets you create a filter with different Data and Index types
Definition at line 38 of file mean_filter_blocked.hpp.
IndexType
template<typename DT_ , typename IT_ , int BlockSize_> typedef VectorType::IndexType FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::IndexType
index-type typedef
Definition at line 28 of file mean_filter_blocked.hpp.
ValueType
template<typename DT_ , typename IT_ , int BlockSize_> typedef VectorType::ValueType FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::ValueType
value-type typedef
Definition at line 30 of file mean_filter_blocked.hpp.
VectorType
template<typename DT_ , typename IT_ , int BlockSize_> typedef DenseVectorBlocked<DT_, IT_, BlockSize_> FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::VectorType
vector-type typedef
Definition at line 24 of file mean_filter_blocked.hpp.
Constructor & Destructor Documentation
MeanFilterBlocked() [1/4]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::MeanFilterBlocked () inline
Definition at line 52 of file mean_filter_blocked.hpp.
MeanFilterBlocked() [2/4]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::MeanFilterBlocked (VectorType && vec_prim, VectorType && vec_dual, ValueType sol_mean = ValueType(0)) inline explicit
Constructor.
Parameters
[in] vec_prim,vec_dual The primal-dual weighting vector pair for the mean filter.
[in] sol_mean The desired integral mean of the solution vector. Defaults to 0.
Definition at line 69 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid_sqr(), and XASSERTM.
MeanFilterBlocked() [3/4]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::MeanFilterBlocked (VectorType && vec_prim, VectorType && vec_dual, ValueType sol_mean, ValueType volume) inline explicit
Constructor.
Parameters
[in] vec_prim,vec_dual The primal-dual weighting vector pair for the mean filter.
[in] sol_mean The desired integral mean of the solution vector.
[in] volume The domain volume. This is simply the dot-product of the two vectors.
Definition at line 93 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid_sqr(), and XASSERTM.
MeanFilterBlocked() [4/4]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::MeanFilterBlocked (MeanFilterBlocked< DT_, IT_, BlockSize_ > && other) inline
move ctor
Definition at line 106 of file mean_filter_blocked.hpp.
~MeanFilterBlocked()
template<typename DT_ , typename IT_ , int BlockSize_> virtual FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::~MeanFilterBlocked () inline virtual
virtual destructor
Definition at line 128 of file mean_filter_blocked.hpp.
Member Function Documentation
clear()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clear () inline
Clears this filter.
Definition at line 168 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_sol_mean, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, and FEAT::LAFEM::Container< DT_, IT_ >::clear().
clone() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> MeanFilterBlocked FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Creates a clone of itself.
Warning
_volume and _sol_mean will always be a deep copy
Definition at line 136 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_sol_mean, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone().
clone() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clone (const MeanFilterBlocked< DT_, IT_, BlockSize_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clones data from another MeanFilterBlocked.
Warning
_volume and _sol_mean will always be a deep copy
Definition at line 145 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_sol_mean, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone().
convert()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ , int BlockSize2_> void FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::convert (const MeanFilterBlocked< DT2_, IT2_, BlockSize2_ > & other) inline
Conversion method.
Definition at line 155 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_sol_mean, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid_sqr(), and XASSERTM.
filter_cor()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor (VectorType & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 273 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::axpy_blocked(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::dot_blocked(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), and FEAT::Tiny::Vector< T_, n_, s_ >::n.
filter_def()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_def (VectorType & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 261 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs().
filter_mat()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename MT_ > void FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_mat (MT_ & matrix) const inline
Applies the filter onto a system matrix.
Parameters
[in,out] matrix A reference to the matrix to be filtered.
Definition at line 294 of file mean_filter_blocked.hpp.
filter_rhs()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs (VectorType & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 214 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::axpy_blocked(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::dot_blocked(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), and FEAT::Tiny::Vector< T_, n_, s_ >::n.
Referenced by FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_def().
filter_sol()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol (VectorType & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 234 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_sol_mean, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::axpy_blocked(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::dot_blocked(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), and FEAT::Tiny::Vector< T_, n_, s_ >::n.
operator=()
template<typename DT_ , typename IT_ , int BlockSize_> MeanFilterBlocked & FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::operator= (MeanFilterBlocked< DT_, IT_, BlockSize_ > && other) inline
move-assign operator
Definition at line 115 of file mean_filter_blocked.hpp.
References FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_sol_mean, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual, FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim, and FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume.
Member Data Documentation
_sol_mean
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_sol_mean protected
desired solution vector mean
Definition at line 48 of file mean_filter_blocked.hpp.
Referenced by FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol(), and FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::operator=().
_vec_dual
template<typename DT_ , typename IT_ , int BlockSize_> VectorType FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_dual protected
dual weighting vector
Definition at line 44 of file mean_filter_blocked.hpp.
Referenced by FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol(), and FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::operator=().
_vec_prim
template<typename DT_ , typename IT_ , int BlockSize_> VectorType FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_vec_prim protected
primal weighting vector
Definition at line 42 of file mean_filter_blocked.hpp.
Referenced by FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::MeanFilterBlocked(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol(), and FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::operator=().
_volume
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::_volume protected
weight volume
Definition at line 46 of file mean_filter_blocked.hpp.
Referenced by FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::MeanFilterBlocked(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol(), and FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::operator=().
The documentation for this class was generated from the following file:
kernel/lafem/mean_filter_blocked.hpp