FEAT: FEAT::Cubature::Scalar::DriverFactory< Driver_, true > Class Template Reference
FEAT::Cubature::Scalar::DriverFactory< Driver_, true > Class Template Reference
DriverFactory specialization for variadic drivers.
#include <driver_factory.hpp>
Public Types
typedef Driver_ DriverType
Public Member Functions
DriverFactory (int num_points)
template<typename Weight_ , typename Coord_ >
bool create (Rule< Weight_, Coord_ > &rule)
Creates the cubature rule.
Static Public Member Functions
template<typename Functor_ >
static void alias (Functor_ &functor)
Calls the driver's alias function.
template<typename Weight_ , typename Coord_ >
static bool create (Rule< Weight_, Coord_ > &rule, const String &name_in)
Creates the cubature rule from a string.
template<typename Weight_ , typename Coord_ >
static bool create (Rule< Weight_, Coord_ > &rule, int num_points)
Creates the cubature rule.
static String name ()
Returns the name of the cubature rule.
Static Public Attributes
static constexpr int max_points = DriverType::max_points
static constexpr int min_points = DriverType::min_points
static constexpr bool tensorize = DriverType::tensorize
static constexpr bool variadic = true
Protected Attributes
int _num_points
Detailed Description
template<typename Driver_>
class FEAT::Cubature::Scalar::DriverFactory< Driver_, true >
DriverFactory specialization for variadic drivers.
Author
Peter Zajac
Definition at line 143 of file driver_factory.hpp.
Member Typedef Documentation
DriverType
template<typename Driver_ > typedef Driver_ FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::DriverType
Definition at line 146 of file driver_factory.hpp.
Constructor & Destructor Documentation
DriverFactory()
template<typename Driver_ > FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::DriverFactory (int num_points) inline explicit
Definition at line 157 of file driver_factory.hpp.
Member Function Documentation
alias()
template<typename Driver_ > template<typename Functor_ > static void FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::alias (Functor_ & functor) inline static
Calls the driver's alias function.
Definition at line 254 of file driver_factory.hpp.
create() [1/3]
template<typename Driver_ > template<typename Weight_ , typename Coord_ > bool FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::create (Rule< Weight_, Coord_ > & rule) inline
Creates the cubature rule.
Parameters
[out] rule The cubature rule to be created.
Definition at line 171 of file driver_factory.hpp.
create() [2/3]
template<typename Driver_ > template<typename Weight_ , typename Coord_ > static bool FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::create (Rule< Weight_, Coord_ > & rule, const String & name_in) inline static
Creates the cubature rule from a string.
This function creates the cubature rule if the string in name represents a valid representation of the cubature rule's name.
Parameters
[out] rule The rule to be created.
[in] name_in The name of the cubature rule to create.
Returns
true, if the cubature rule was created successfully, or false, if name_in is not a valid name of the cubature rule implemented by this factory.
Definition at line 213 of file driver_factory.hpp.
References FEAT::String::compare_no_case(), FEAT::String::parse(), and FEAT::String::trim().
create() [3/3]
template<typename Driver_ > template<typename Weight_ , typename Coord_ > static bool FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::create (Rule< Weight_, Coord_ > & rule, int num_points) inline static
Creates the cubature rule.
Parameters
[out] rule The cubature rule to be created.
[in] num_points The number of points for the cubature rule.
Definition at line 186 of file driver_factory.hpp.
References FEAT::stringify().
name()
template<typename Driver_ > static String FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::name () inline static
Returns the name of the cubature rule.
Definition at line 245 of file driver_factory.hpp.
Member Data Documentation
_num_points
template<typename Driver_ > int FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::_num_points protected
Definition at line 154 of file driver_factory.hpp.
max_points
template<typename Driver_ > constexpr int FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::max_points = DriverType::max_points static constexpr
Definition at line 151 of file driver_factory.hpp.
min_points
template<typename Driver_ > constexpr int FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::min_points = DriverType::min_points static constexpr
Definition at line 150 of file driver_factory.hpp.
tensorize
template<typename Driver_ > constexpr bool FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::tensorize = DriverType::tensorize static constexpr
Definition at line 149 of file driver_factory.hpp.
variadic
template<typename Driver_ > constexpr bool FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::variadic = true static constexpr
Definition at line 148 of file driver_factory.hpp.
The documentation for this class was generated from the following file:
kernel/cubature/scalar/driver_factory.hpp