FEAT: FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > Class Template Reference
FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > Class Template Reference
Saddle-Point matrix meta class template.
#include <saddle_point_matrix.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = SaddlePointMatrix< typename MatrixA_::template ContainerType< DT2_, IT2_ >, typename MatrixB_::template ContainerType< DT2_, IT2_ >, typename MatrixD_::template ContainerType< DT2_, IT2_ > >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a matrix container with different Data and Index types
typedef MatrixTypeA::DataType DataType
data type
typedef MatrixTypeA::IndexType IndexType
index type
typedef MatrixA_ MatrixTypeA
type of sub-matrix A
typedef MatrixB_ MatrixTypeB
type of sub-matrix B
typedef MatrixD_ MatrixTypeD
type of sub-matrix D
typedef TupleVector< typename MatrixTypeA::VectorTypeL, typename MatrixTypeD::VectorTypeL > VectorTypeL
Compatible L-vector type.
typedef TupleVector< typename MatrixTypeA::VectorTypeR, typename MatrixTypeB::VectorTypeR > VectorTypeR
Compatible R-vector type.
Public Member Functions
SaddlePointMatrix ()
default CTOR
SaddlePointMatrix (FileMode mode, const String &filename)
Constructor.
SaddlePointMatrix (MatrixTypeA &&matrix_a, MatrixTypeB &&matrix_b, MatrixTypeD &&matrix_d)
Sub-Matrix move constructor.
SaddlePointMatrix (SaddlePointMatrix &&other)
move ctor
virtual ~SaddlePointMatrix ()
virtual destructor
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply (VectorTypeL &r, const VectorTypeR &x) const
Applies this matrix onto a vector.
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply_transposed (VectorTypeR &r, const VectorTypeL &x) const
Applies this matrix onto a vector.
void apply_transposed (VectorTypeR &r, const VectorTypeL &x, const VectorTypeR &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
template<int i_, int j_>
SaddlePointMatrixElement< MatrixA_, MatrixB_, MatrixD_, i_, j_ >::Type & at ()
Returns a sub-matrix block.
template<int i_, int j_>
const SaddlePointMatrixElement< MatrixA_, MatrixB_, MatrixD_, i_, j_ >::Type & at () const
Returns a sub-matrix block.
MatrixTypeA & block_a ()
Returns the sub-matrix block A.
const MatrixTypeA & block_a () const
Returns the sub-matrix block A.
MatrixTypeB & block_b ()
Returns the sub-matrix block B.
const MatrixTypeB & block_b () const
Returns the sub-matrix block B.
MatrixTypeD & block_d ()
Returns the sub-matrix block D.
const MatrixTypeD & block_d () const
Returns the sub-matrix block D.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
SaddlePointMatrix clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a deep copy of this matrix.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Returns the total number of columns in this matrix.
template<typename MatrixA2_ , typename MatrixB2_ , typename MatrixD2_ >
void convert (const SaddlePointMatrix< MatrixA2_, MatrixB2_, MatrixD2_ > &other)
Conversion method.
template<typename MatrixA2_ , typename MatrixB2_ , typename MatrixD2_ >
void convert_reverse (SaddlePointMatrix< MatrixA2_, MatrixB2_, MatrixD2_ > &other) const
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
void extract_diag (VectorTypeL &diag) const
extract main diagonal vector from matrix
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
Index get_length_of_line (const Index row) const
Returns the number of NNZ-elements of the selected row.
void lump_rows (VectorTypeL &lump, bool=true) const
SaddlePointMatrix & operator= (SaddlePointMatrix &&other)
move-assign operator
void read_from (FileMode mode, const String &filename)
Read in matrix from file.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Returns the total number of rows in this matrix.
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
template<Perspective perspective_ = Perspective::native>
Index size () const
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Returns the total number of non-zeros in this matrix.
void write_out (FileMode mode, String filename) const
Write out matrix to file.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr int num_col_blocks = 2
number of column blocks (horizontal size)
static constexpr int num_row_blocks = 2
number of row blocks (vertical size)
Protected Attributes
MatrixTypeA _matrix_a
sub-matrix A
MatrixTypeB _matrix_b
sub-matrix B
MatrixTypeD _matrix_d
sub-matrix C
Friends
bool operator== (const SaddlePointMatrix &a, const SaddlePointMatrix &b)
SaddlePointMatrix comparison operator.
Detailed Description
template<typename MatrixA_, typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_>
class FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >
Saddle-Point matrix meta class template.
This class template implements a meta container for saddle-point matrices:
/ A B \
\ D 0 /
where
A is an n-by-n (meta) matrix
B is an n-by-m (meta) matrix
D is an m-by-n (meta) matrix
Template Parameters
MatrixA_ The type of the upper-left (square) matrix block A.
MatrixB_ The type of the upper-right (rectangular) matrix block B.
MatrixD_ The type of the lower-left (rectangular) matrix block D.
Author
Peter Zajac
Definition at line 65 of file saddle_point_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::ContainerType = SaddlePointMatrix<typename MatrixA_::template ContainerType<DT2_, IT2_>, typename MatrixB_::template ContainerType<DT2_, IT2_>, typename MatrixD_::template ContainerType<DT2_, IT2_> >
Our 'base' class type.
Definition at line 98 of file saddle_point_matrix.hpp.
ContainerTypeByDI
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a matrix container with different Data and Index types
Definition at line 104 of file saddle_point_matrix.hpp.
DataType
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> typedef MatrixTypeA::DataType FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::DataType
data type
Definition at line 88 of file saddle_point_matrix.hpp.
IndexType
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> typedef MatrixTypeA::IndexType FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::IndexType
index type
Definition at line 90 of file saddle_point_matrix.hpp.
MatrixTypeA
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> typedef MatrixA_ FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::MatrixTypeA
type of sub-matrix A
Definition at line 69 of file saddle_point_matrix.hpp.
MatrixTypeB
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> typedef MatrixB_ FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::MatrixTypeB
type of sub-matrix B
Definition at line 71 of file saddle_point_matrix.hpp.
MatrixTypeD
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> typedef MatrixD_ FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::MatrixTypeD
type of sub-matrix D
Definition at line 73 of file saddle_point_matrix.hpp.
VectorTypeL
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> typedef TupleVector<typename MatrixTypeA::VectorTypeL, typename MatrixTypeD::VectorTypeL> FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::VectorTypeL
Compatible L-vector type.
Definition at line 93 of file saddle_point_matrix.hpp.
VectorTypeR
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> typedef TupleVector<typename MatrixTypeA::VectorTypeR, typename MatrixTypeB::VectorTypeR> FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::VectorTypeR
Compatible R-vector type.
Definition at line 95 of file saddle_point_matrix.hpp.
Constructor & Destructor Documentation
SaddlePointMatrix() [1/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix () inline
default CTOR
Definition at line 121 of file saddle_point_matrix.hpp.
Referenced by FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clone().
SaddlePointMatrix() [2/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix (MatrixTypeA && matrix_a, MatrixTypeB && matrix_b, MatrixTypeD && matrix_d) inline explicit
Sub-Matrix move constructor.
Parameters
[in] matrix_a,matrix_b,matrix_d The three sub-matrices which are to be inserted.
Definition at line 131 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d, and XASSERT.
SaddlePointMatrix() [3/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix (SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > && other) inline
move ctor
Definition at line 144 of file saddle_point_matrix.hpp.
SaddlePointMatrix() [4/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix (FileMode mode, const String & filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a saddle-point-matrix based on the source file.
Definition at line 159 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::read_from().
~SaddlePointMatrix()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> virtual FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::~SaddlePointMatrix () inline virtual
virtual destructor
Definition at line 223 of file saddle_point_matrix.hpp.
Member Function Documentation
apply() [1/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 451 of file saddle_point_matrix.hpp.
apply() [2/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 526 of file saddle_point_matrix.hpp.
apply() [3/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 444 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
Referenced by FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_diag(), and FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_full().
apply() [4/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 519 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
apply_transposed() [1/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 486 of file saddle_point_matrix.hpp.
apply_transposed() [2/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 571 of file saddle_point_matrix.hpp.
apply_transposed() [3/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this^\top \cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 479 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
apply_transposed() [4/4]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x, const VectorTypeR & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this^\top \cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 564 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
at() [1/2]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<int i_, int j_> SaddlePointMatrixElement< MatrixA_, MatrixB_, MatrixD_, i_, j_ >::Type & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::at () inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 328 of file saddle_point_matrix.hpp.
at() [2/2]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<int i_, int j_> const SaddlePointMatrixElement< MatrixA_, MatrixB_, MatrixD_, i_, j_ >::Type & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::at () const inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 338 of file saddle_point_matrix.hpp.
block_a() [1/2]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> MatrixTypeA & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a () inline
Returns the sub-matrix block A.
Definition at line 280 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a.
Referenced by FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_diag(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_full(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_factor_diag(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_factor_full(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply_transposed(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clear(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::convert(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_l(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_r(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::format(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::get_checkpoint_size(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::get_length_of_line(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::restore_from_checkpoint_data(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::set_checkpoint_data().
block_a() [2/2]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> const MatrixTypeA & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a () const inline
Returns the sub-matrix block A.
Definition at line 286 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a.
block_b() [1/2]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> MatrixTypeB & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b () inline
Returns the sub-matrix block B.
Definition at line 292 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b.
Referenced by FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_diag(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_full(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_build_p_block(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_factor_diag(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_factor_full(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply_transposed(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clear(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::convert(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_r(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::format(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::get_checkpoint_size(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::get_length_of_line(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::restore_from_checkpoint_data(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::set_checkpoint_data().
block_b() [2/2]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> const MatrixTypeB & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b () const inline
Returns the sub-matrix block B.
Definition at line 298 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b.
block_d() [1/2]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> MatrixTypeD & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d () inline
Returns the sub-matrix block D.
Definition at line 304 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d.
Referenced by FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_diag(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_full(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_build_p_block(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_build_p_nodal(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_build_v_block(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_factor_diag(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_factor_full(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply_transposed(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clear(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::convert(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_l(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::format(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::get_checkpoint_size(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::get_length_of_line(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::restore_from_checkpoint_data(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::set_checkpoint_data().
block_d() [2/2]
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> const MatrixTypeD & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d () const inline
Returns the sub-matrix block D.
Definition at line 310 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d.
bytes()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> std::size_t FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 274 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b, and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d.
Referenced by FEAT::Control::StokesBlockedSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_, TransferMatrixS_ >::bytes(), FEAT::Control::StokesBlockedUnitVeloMeanPresSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), FEAT::Control::StokesPowerUnitVeloNonePresSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_ >::bytes(), and FEAT::Control::StokesPowerUnitVeloMeanPresSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_ >::bytes().
clear()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clear () inline
Free all allocated arrays.
Definition at line 412 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
clone()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> SaddlePointMatrix FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a deep copy of this matrix.
Definition at line 268 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b, and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d.
columns()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::columns () const inline
Returns the total number of columns in this matrix.
Returns
Matrix column count if perspective_ = false.
Raw matrix column count if perspective_ = true.
Definition at line 365 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b.
convert()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<typename MatrixA2_ , typename MatrixB2_ , typename MatrixD2_ > void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::convert (const SaddlePointMatrix< MatrixA2_, MatrixB2_, MatrixD2_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 717 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
convert_reverse()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<typename MatrixA2_ , typename MatrixB2_ , typename MatrixD2_ > void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::convert_reverse (SaddlePointMatrix< MatrixA2_, MatrixB2_, MatrixD2_ > & other) const inline
Definition at line 725 of file saddle_point_matrix.hpp.
create_vector_l()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> VectorTypeL FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 593 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_l().
Referenced by FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_l().
create_vector_r()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> VectorTypeR FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 599 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_r().
Referenced by FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_r(), and FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::init_symbolic().
extract_diag()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::extract_diag (VectorTypeL & diag) const inline
extract main diagonal vector from matrix
Definition at line 420 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, and FEAT::LAFEM::TupleVector< First_, Rest_ >::format().
format()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the matrix' entries are to be set to.
Definition at line 402 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d(), and FEAT::value.
get_checkpoint_size()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> std::uint64_t FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 658 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
get_length_of_line()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> Index FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::get_length_of_line (const Index row) const inline
Returns the number of NNZ-elements of the selected row.
Definition at line 605 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
lump_rows()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::lump_rows (VectorTypeL & lump, bool = true) const inline
Definition at line 426 of file saddle_point_matrix.hpp.
name()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> static String FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 383 of file saddle_point_matrix.hpp.
operator=()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> SaddlePointMatrix & FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::operator= (SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > && other) inline
move-assign operator
Definition at line 212 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b, and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d.
read_from()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::read_from (FileMode mode, const String & filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 170 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d, FEAT::String::trim_me(), and XABORTM.
Referenced by FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix().
restore_from_checkpoint_data()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 664 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
rows()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::rows () const inline
Returns the total number of rows in this matrix.
Returns
Matrix row count if perspective_ = false.
Raw matrix row count if perspective_ = true.
Definition at line 353 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d.
set_checkpoint_data()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> std::uint64_t FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 684 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
size()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::size () const inline
Definition at line 391 of file saddle_point_matrix.hpp.
used_elements()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::used_elements () const inline
Returns the total number of non-zeros in this matrix.
Returns
Matrix non zero element count if perspective_ = false.
Raw matrix non zero element count if perspective_ = true.
Definition at line 377 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b, and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d.
write_out()
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> void FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::write_out (FileMode mode, String filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 233 of file saddle_point_matrix.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b, FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d, and XABORTM.
Friends And Related Function Documentation
operator==
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> bool operator== (const SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > & a, const SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > & b) friend
SaddlePointMatrix comparison operator.
Parameters
[in] a A matrix to compare with.
[in] b A matrix to compare with.
Definition at line 738 of file saddle_point_matrix.hpp.
Member Data Documentation
_matrix_a
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> MatrixTypeA FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_a protected
sub-matrix A
Definition at line 113 of file saddle_point_matrix.hpp.
Referenced by FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::bytes(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clone(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::columns(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::extract_diag(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::operator=(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::read_from(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::rows(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::used_elements(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::write_out().
_matrix_b
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> MatrixTypeB FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_b protected
sub-matrix B
Definition at line 115 of file saddle_point_matrix.hpp.
Referenced by FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::bytes(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clone(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::columns(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::operator=(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::read_from(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::used_elements(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::write_out().
_matrix_d
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> MatrixTypeD FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::_matrix_d protected
sub-matrix C
Definition at line 117 of file saddle_point_matrix.hpp.
Referenced by FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::SaddlePointMatrix(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::bytes(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::clone(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::operator=(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::read_from(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::rows(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::used_elements(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::write_out().
num_col_blocks
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> constexpr int FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::num_col_blocks = 2 static constexpr
number of column blocks (horizontal size)
Definition at line 109 of file saddle_point_matrix.hpp.
num_row_blocks
template<typename MatrixA_ , typename MatrixB_ = MatrixA_, typename MatrixD_ = MatrixB_> constexpr int FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::num_row_blocks = 2 static constexpr
number of row blocks (vertical size)
Definition at line 107 of file saddle_point_matrix.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/saddle_point_matrix.hpp