FEAT: FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ > Class Template Reference
FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ > Class Template Reference
Implementation of ADPSolverBase interface for Global::PMDCDSCMatrix instances.
#include <adp_solver_base.hpp>
Public Types
typedef SolverBase_ BaseClass
our base class
typedef LocalMatrixTypeS::DataType DataType
our internal data type
typedef GlobalFilter_ GlobalFilterType
the global filter type
typedef Global::PMDCDSCMatrix< MatrixB_, MatrixD_ > GlobalMatrixType
the global matrix type
typedef GlobalMatrixType::VectorTypeL GlobalVectorType
the global vector type
typedef LocalMatrixTypeS::IndexType IndexType
our internal index type
typedef GlobalMatrixType::LocalMatrixTypeS LocalMatrixTypeS
the local Schur-complement matrix type
typedef LocalMatrixTypeS::VectorTypeL LocalVectorType
our internal local vector type; always a DenseVector<DataType, IndexType>
typedef GlobalVectorType VectorType
the system vector type
Public Member Functions
const Dist::Comm * _get_comm () const
virtual void init_symbolic () override
Symbolic initialization.
Protected Member Functions
ADPSolverBase (const GlobalMatrixType &matrix, const GlobalFilterType &filter)
protected constructor
template<typename DTV_ >
void _download_vector (LAFEM::DenseVector< DataType, IndexType > &vector, const DTV_ *val)
Downloads the ADP vector values from the given array.
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const Global::MeanFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const LAFEM::MeanFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const LAFEM::NoneFilter< DataType, IndexType > &)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterChain< First_ > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ , typename... Rest_>
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterChain< First_, Rest_... > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename SubFilter_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterSequence< SubFilter_ > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::UnitFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
String _get_adp_block_information () const
Index _get_adp_matrix_num_cols () const
Index _get_adp_matrix_num_nzes () const
Index _get_adp_matrix_num_rows () const
Index _get_adp_vector_size () const
Index _get_global_dof_offset () const
Index _get_num_global_dofs () const
Index _get_num_global_nonzeros () const
Index _get_num_owned_dofs () const
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _upload_numeric (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx)
Uploads the (filtered) ADP matrix values to the given array.
template<typename RPT_ , typename CIT_ >
void _upload_symbolic (RPT_ *row_ptr, CIT_ *col_idx)
Uploads the ADP matrix structure to the given arrays.
template<typename DTV_ >
void _upload_vector (DTV_ *val, const LAFEM::DenseVector< DataType, IndexType > &vector)
Uploads the ADP vector values to the given array.
Protected Attributes
const GlobalFilterType & _system_filter
the global system filter
const GlobalMatrixType & _system_matrix
the global system matrix
Private Attributes
Index _global_dof_count
the total global DOF count
Index _global_dof_offset
our global DOF offset
Index _global_num_nzes
the number of global non-zero entries
Index _owned_dof_count
the owned DOF count
Index _owned_num_nzes
the number of owned non-zero entries
Detailed Description
template<typename MatrixB_, typename MatrixD_, typename GlobalFilter_, typename SolverBase_>
class FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >
Implementation of ADPSolverBase interface for Global::PMDCDSCMatrix instances.
This class implements the ADPSolverBase interface for Global::PMDCDSCMatrix instances, which are used to implement the global Schur-complement matrices appearing in Navier-Stokes equations with discontinuous pressure spaces. The most prominent use of this specialization is the Pressure-Poisson-Problem solver of the infamous "PP" application.
Most of the dirty work is outsourced to the Global::PMDCDSCMatrix class, most notably to its three member functions Global::PMDCDSCMatrix::adp_compute_counts(), Global::PMDCDSCMatrix::adp_upload_symbolic() and Global::PMDCDSCMatrix::adp_upload_numeric().
Author
Peter Zajac
Definition at line 450 of file adp_solver_base.hpp.
Member Typedef Documentation
BaseClass
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef SolverBase_ FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::BaseClass
our base class
Definition at line 467 of file adp_solver_base.hpp.
DataType
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef LocalMatrixTypeS::DataType FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::DataType
our internal data type
Definition at line 473 of file adp_solver_base.hpp.
GlobalFilterType
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef GlobalFilter_ FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::GlobalFilterType
the global filter type
Definition at line 459 of file adp_solver_base.hpp.
GlobalMatrixType
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef Global::PMDCDSCMatrix<MatrixB_, MatrixD_> FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::GlobalMatrixType
the global matrix type
Definition at line 455 of file adp_solver_base.hpp.
GlobalVectorType
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef GlobalMatrixType::VectorTypeL FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::GlobalVectorType
the global vector type
Definition at line 457 of file adp_solver_base.hpp.
IndexType
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef LocalMatrixTypeS::IndexType FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::IndexType
our internal index type
Definition at line 475 of file adp_solver_base.hpp.
LocalMatrixTypeS
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef GlobalMatrixType::LocalMatrixTypeS FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::LocalMatrixTypeS
the local Schur-complement matrix type
Definition at line 462 of file adp_solver_base.hpp.
LocalVectorType
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef LocalMatrixTypeS::VectorTypeL FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::LocalVectorType
our internal local vector type; always a DenseVector<DataType, IndexType>
Definition at line 464 of file adp_solver_base.hpp.
VectorType
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > typedef GlobalVectorType FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::VectorType
the system vector type
Definition at line 470 of file adp_solver_base.hpp.
Constructor & Destructor Documentation
ADPSolverBase()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::ADPSolverBase (const GlobalMatrixType & matrix, const GlobalFilterType & filter) inline explicit protected
protected constructor
Parameters
[in] matrix A resident reference to the system matrix
[in] filter A resident reference to the system filter
Definition at line 505 of file adp_solver_base.hpp.
Member Function Documentation
_download_vector()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_download_vector (LAFEM::DenseVector< DataType, IndexType > & vector, const DTV_ * val) inline protected
Downloads the ADP vector values from the given array.
Parameters
[in,out] vector A transient reference to the local vector that receives the downloaded ADP value array. It is assumed to be allocated to the correct size, but its contents on entry are ignored.
[in] val A transient pointer to an array of length _get_adp_vector_size() that contains the ADP values that are to be downloaded to the output vector given by vector.
Definition at line 668 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_vector_size(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERT.
_filter_mat() [1/7]
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const Global::MeanFilter< DataType, IndexType > & filter) inline protected
auxiliary function: filters the local ADP matrix
Definition at line 713 of file adp_solver_base.hpp.
References XASSERTM.
_filter_mat() [2/7]
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const LAFEM::MeanFilter< DataType, IndexType > & filter) inline protected
auxiliary function: filters the local ADP matrix
Definition at line 705 of file adp_solver_base.hpp.
References XASSERTM.
_filter_mat() [3/7]
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const LAFEM::NoneFilter< DataType, IndexType > &) inline protected
auxiliary function: filters the local ADP matrix
Definition at line 682 of file adp_solver_base.hpp.
_filter_mat() [4/7]
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterChain< First_ > & filter) inline protected
auxiliary function: filters the local ADP matrix
Definition at line 739 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [5/7]
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ , typename... Rest_> void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterChain< First_, Rest_... > & filter) inline protected
auxiliary function: filters the local ADP matrix
Definition at line 730 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [6/7]
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ , typename SubFilter_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterSequence< SubFilter_ > & filter) inline protected
auxiliary function: filters the local ADP matrix
Definition at line 721 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [7/7]
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::UnitFilter< DataType, IndexType > & filter) inline protected
auxiliary function: filters the local ADP matrix
Definition at line 690 of file adp_solver_base.hpp.
_get_adp_block_information()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > String FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_block_information () const inline protected
Returns
The block information of the algebraic dof partitioning as an XML string.
Definition at line 588 of file adp_solver_base.hpp.
References XABORTM.
_get_adp_matrix_num_cols()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_matrix_num_cols () const inline protected
Returns
The number of columns of the local ADP matrix; equal to _get_num_global_dofs()
Definition at line 552 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_dofs().
_get_adp_matrix_num_nzes()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_matrix_num_nzes () const inline protected
Returns
The number of nonzero entries of the local ADP matrix
Definition at line 558 of file adp_solver_base.hpp.
_get_adp_matrix_num_rows()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_matrix_num_rows () const inline protected
Returns
The number of rows of the local ADP matrix; equal to _get_num_owned_dofs()
Definition at line 546 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs().
_get_adp_vector_size()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_vector_size () const inline protected
Returns
The size of the local ADP vector; equal to _get_num_owned_dofs()
Definition at line 540 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs().
_get_comm()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > const Dist::Comm * FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_comm () const inline
Returns
A pointer to the underlying communicator
Definition at line 519 of file adp_solver_base.hpp.
_get_global_dof_offset()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_global_dof_offset () const inline protected
Returns
The index of the first global DOF owned by this process
Definition at line 582 of file adp_solver_base.hpp.
_get_num_global_dofs()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_num_global_dofs () const inline protected
Returns
The total number of global DOFs on all processes
Definition at line 570 of file adp_solver_base.hpp.
_get_num_global_nonzeros()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_num_global_nonzeros () const inline protected
Returns
The total number of nonzero entries of the global ADP matrix
Definition at line 564 of file adp_solver_base.hpp.
_get_num_owned_dofs()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_num_owned_dofs () const inline protected
Returns
The number of global DOFs owned by this process
Definition at line 576 of file adp_solver_base.hpp.
_upload_numeric()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_numeric (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx) inline protected
Uploads the (filtered) ADP matrix values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the filtered matrix values of the local ADP matrix.
[in] row_ptr A transient pointer to the row-pointer array of the ADP matrix as returned by the _upload_symbolic() function.
[in] col_idx A transient pointer to the column-index array of the ADP matrix as returned by the _upload_symbolic() function.
Definition at line 627 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat(), and FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_upload_symbolic()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_symbolic (RPT_ * row_ptr, CIT_ * col_idx) inline protected
Uploads the ADP matrix structure to the given arrays.
Parameters
[out] row_ptr A transient pointer to an array of length _get_adp_matrix_num_rows()+1 that receives the the row-pointer array of the ADP matrix.
[out] col_idx A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the column index array of the ADP matrix.
Definition at line 606 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_upload_vector()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_vector (DTV_ * val, const LAFEM::DenseVector< DataType, IndexType > & vector) inline protected
Uploads the ADP vector values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_vector_size() that receives the local ADP values of the input vector given by vector.
[in] vector A transient reference to the local vector that is to be uploaded to the ADP value array.
Definition at line 644 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_vector_size(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERT.
init_symbolic()
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > virtual void FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::init_symbolic () inline override virtual
Symbolic initialization.
This function performs the symbolic initialization of the algebraic DOF partitioning, which boils down to computing the ADP matrix dimensions for this specialization.
Definition at line 530 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
Member Data Documentation
_global_dof_count
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_global_dof_count private
the total global DOF count
Definition at line 485 of file adp_solver_base.hpp.
_global_dof_offset
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_global_dof_offset private
our global DOF offset
Definition at line 487 of file adp_solver_base.hpp.
_global_num_nzes
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_global_num_nzes private
the number of global non-zero entries
Definition at line 493 of file adp_solver_base.hpp.
_owned_dof_count
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_owned_dof_count private
the owned DOF count
Definition at line 489 of file adp_solver_base.hpp.
_owned_num_nzes
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_owned_num_nzes private
the number of owned non-zero entries
Definition at line 491 of file adp_solver_base.hpp.
_system_filter
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > const GlobalFilterType& FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_system_filter protected
the global system filter
Definition at line 481 of file adp_solver_base.hpp.
_system_matrix
template<typename MatrixB_ , typename MatrixD_ , typename GlobalFilter_ , typename SolverBase_ > const GlobalMatrixType& FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_system_matrix protected
the global system matrix
Definition at line 479 of file adp_solver_base.hpp.
The documentation for this class was generated from the following file:
kernel/solver/adp_solver_base.hpp