FEAT: FEAT::LAFEM::Container< DT_, IT_ > Class Template Reference
FEAT::LAFEM::Container< DT_, IT_ > Class Template Reference
Container base class.
#include <container.hpp>
Public Member Functions
Container (Container &&other)
Move Constructor.
Container (Index size_in)
Constructor.
virtual ~Container ()
Destructor.
std::size_t bytes () const
Returns the total amount of bytes allocated.
virtual void clear ()
Free all allocated arrays.
void clone (const Container &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const Container< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
bool empty () const
Checks whether the container is empty.
void format (DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DT_ min, DT_ max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (const LAFEM::SerialConfig &config)
Calculate size.
const std::vector< DT_ * > & get_elements () const
Returns a list of all data arrays.
const std::vector< Index > & get_elements_size () const
Returns a list of all data array sizes.
const std::vector< IT_ * > & get_indices () const
Returns a list of all Index arrays.
const std::vector< Index > & get_indices_size () const
Returns a list of all Index array sizes.
const std::vector< DT_ > & get_scalar_dt () const
Returns a list of all scalar values with datatype dt.
const std::vector< Index > & get_scalar_index () const
Returns a list of all scalar values with datatype index.
void move (Container &&other)
Assignment move operation.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
std::uint64_t set_checkpoint_data (std::vector< char > &data, const LAFEM::SerialConfig &config)
template<Perspective = Perspective::native>
Index size () const
Returns the containers size.
template<Perspective = Perspective::native>
Index used_elements () const
Returns the number of effective stored elements.
Static Public Member Functions
static String name ()
Returns a descriptive string.
Protected Member Functions
void _copy_content (const Container &other, bool full)
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::istream &file)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::vector< char > &input)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > _serialize (FileMode mode, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _serialize (FileMode mode, std::ostream &file, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::uint64_t _serialized_size (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Calculation of the serialized size with optional compression of complete container entity.
template<typename DT2_ , typename IT2_ >
void assign (const Container< DT2_, IT2_ > &other)
Assignment operation.
Protected Attributes
std::vector< DT_ * > _elements
List of pointers to all datatype dependent arrays.
std::vector< Index > _elements_size
List of corresponding datatype array sizes.
bool _foreign_memory
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
std::vector< IT_ * > _indices
List of pointers to all IT_ dependent arrays.
std::vector< Index > _indices_size
List of corresponding IT_ array sizes.
std::vector< DT_ > _scalar_dt
List of scalars with datatype DT_.
std::vector< Index > _scalar_index
List of scalars with datatype index.
Detailed Description
template<typename DT_, typename IT_>
class FEAT::LAFEM::Container< DT_, IT_ >
Container base class.
All LAFEM-Container are derived from this base class.
See also
LAFEM design description
Template Parameters
DT_ The datatype to be used.
IT_ The indextype to be used.
This is the base class of all inheritated containers.
Data survey:
_scalar_index[0]: container size
Author
Dirk Ribbrock
Definition at line 221 of file container.hpp.
Constructor & Destructor Documentation
Container() [1/2]
template<typename DT_ , typename IT_ > FEAT::LAFEM::Container< DT_, IT_ >::Container (Index size_in) inline explicit
Constructor.
Parameters
[in] size_in The size of the created container.
Creates a container with a given size.
Definition at line 796 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
~Container()
template<typename DT_ , typename IT_ > virtual FEAT::LAFEM::Container< DT_, IT_ >::~Container () inline virtual
Destructor.
Destroys a container and releases all of its used arrays.
Definition at line 807 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Container() [2/2]
template<typename DT_ , typename IT_ > FEAT::LAFEM::Container< DT_, IT_ >::Container (Container< DT_, IT_ > && other) inline
Move Constructor.
Parameters
[in] other The source container.
Moves another container to this container.
Definition at line 825 of file container.hpp.
Member Function Documentation
_copy_content()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::_copy_content (const Container< DT_, IT_ > & other, bool full) inline protected
Definition at line 242 of file container.hpp.
_deserialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::istream & file) inline protected
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file std::istream, pointing to the input data.
Recreate a complete container entity by a single binary file.
Definition at line 776 of file container.hpp.
References XABORTM.
_deserialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::vector< char > & input) inline protected
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] input A std::vector containing the byte array.
Recreate a complete container entity by a single binary array.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 622 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Pack::decode(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Type::Helper::extract_floatness(), FEAT::Type::Helper::extract_intness(), FEAT::Type::Helper::extract_signedness(), FEAT::Type::Helper::extract_type_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, XABORTM, XASSERT, and XASSERTM.
_serialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, const SerialConfig & config = SerialConfig()) const inline protected
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
Array data layout:
raw array size in bytes (std::uint64_t)
magic number (std::uint64_t)
DT_ 'hash' value (sizeof(DT_) and floating/integral distinction (packed std::uint64_t)
IT_ 'hash' value (sizeof(IT_) and floating/integral distinction (packed std::uint64_t)
_elements.size() (std::uint64_t)
_indices.size() (std::uint64_t)
_elements_size.size() (std::uint64_t)
_indices_size.size() (std::uint64_t)
_scalar_index.size() (std::uint64_t)
_scalar_dt.size() (std::uint64_t)
_compressed (std::uint64_t)
_elements_size array (std::uint64_t)
_elements arrays byte_size (std::uint64_t) just temporary to read in data
_indices_size array (std::uint64_t)
_indices arrays byte_size (std::uint64_t)
_scalar_index array (std::uint64_t)
_scalar_dt array (DT2_)
_elements arrays (DT2_)
_indices arrays (IT2_)
See FEAT::LAFEM::SerialConfig for details.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 440 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XASSERTM.
_serialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, std::ostream & file, const SerialConfig & config = SerialConfig()) const inline protected
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file The output stream to write data into.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary file with compression enabled. See FEAT::LAFEM::SerialConfig for details.
Definition at line 605 of file container.hpp.
References XABORTM.
_serialized_size()
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline protected
Calculation of the serialized size with optional compression of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Returns
An unsigned int containing the size of serialized container.
Calculate the size of the serialized container entity.
Definition at line 357 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), and FEAT::LAFEM::indices_zlib.
assign()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::assign (const Container< DT2_, IT2_ > & other) inline protected
Assignment operation.
Assigns contents of another container
Parameters
[in] other The source container.
Definition at line 282 of file container.hpp.
References FEAT::MemoryPool::convert(), FEAT::MemoryPool::increase_memory(), and FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::LAFEM::Container< DT_, IT_ >::bytes () const inline
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 1033 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes().
clear()
template<typename DT_ , typename IT_ > virtual void FEAT::LAFEM::Container< DT_, IT_ >::clear () inline virtual
Free all allocated arrays.
Definition at line 874 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from().
clone() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Weak) inline
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 901 of file container.hpp.
References FEAT::LAFEM::Allocate, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Deep, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Layout, FEAT::LAFEM::Shallow, FEAT::LAFEM::Weak, XABORTM, and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVector< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone().
clone() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 974 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), and FEAT::LAFEM::Container< DT_, IT_ >::clone().
empty()
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::empty () const inline
Checks whether the container is empty.
Returns
true if the container is empty, otherwise false.
Definition at line 1156 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic().
format() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (DT_ value = DT_(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 847 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::MemoryPool::set_memory(), and FEAT::value.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
format() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (Random & rng, DT_ min, DT_ max) inline
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 860 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::MemoryPool::set_memory().
get_checkpoint_size()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::get_checkpoint_size (const LAFEM::SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1009 of file container.hpp.
get_elements()
template<typename DT_ , typename IT_ > const std::vector< DT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements () const inline
Returns a list of all data arrays.
Returns
A list of all data arrays.
Definition at line 1059 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
get_elements_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size () const inline
Returns a list of all data array sizes.
Returns
A list of all data array sizes.
Definition at line 1079 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
get_indices()
template<typename DT_ , typename IT_ > const std::vector< IT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices () const inline
Returns a list of all Index arrays.
Returns
A list of all Index arrays.
Definition at line 1069 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
get_indices_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size () const inline
Returns a list of all Index array sizes.
Returns
A list of all Index array sizes.
Definition at line 1089 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices_size.
get_scalar_dt()
template<typename DT_ , typename IT_ > const std::vector< DT_ > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt () const inline
Returns a list of all scalar values with datatype dt.
Returns
A list of all scalars with datatype dt.
Definition at line 1109 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt.
get_scalar_index()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index () const inline
Returns a list of all scalar values with datatype index.
Returns
A list of all scalars with datatype index.
Definition at line 1099 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
move()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::move (Container< DT_, IT_ > && other) inline
Assignment move operation.
Move another container to the current one.
Parameters
[in] other The source container.
Definition at line 988 of file container.hpp.
References FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::operator=().
name()
template<typename DT_ , typename IT_ > static String FEAT::LAFEM::Container< DT_, IT_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 1166 of file container.hpp.
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1015 of file container.hpp.
References FEAT::LAFEM::fm_binary.
set_checkpoint_data()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::set_checkpoint_data (std::vector< char > & data, const LAFEM::SerialConfig & config) inline
Definition at line 1021 of file container.hpp.
References FEAT::LAFEM::fm_binary.
size()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::size () const inline
Returns the containers size.
Returns
The containers size.
The template parameter of type Perspective is used in blocked containers to switch between the raw size and the size, when every block is treated as one entry.
Most containers like SparseMatrixCSR ignore this template parameter.
Definition at line 1127 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseVector< DT_, IT_ >::compare_layout(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_local_dofs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::get_num_nodes_image(), FEAT::LAFEM::DenseVector< DT_, IT_ >::inflate_to_blocks(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::Assembly::FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >::interpolate(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::map_local_to_global_index(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::mask_scatter(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::write_out().
used_elements()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::used_elements () const inline
Returns the number of effective stored elements.
Returns
The number of data values.
The template parameter of type Perspective is used in block containers to switch between the raw number of used elements and the number of used elements, when every block is counted as one entry.
Definition at line 1146 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::invert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), and FEAT::LAFEM::DenseMatrix< DT_, IT_ >::write_out().
Friends And Related Function Documentation
Container
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > friend class Container friend
Definition at line 224 of file container.hpp.
Member Data Documentation
_elements
template<typename DT_ , typename IT_ > std::vector<DT_*> FEAT::LAFEM::Container< DT_, IT_ >::_elements protected
List of pointers to all datatype dependent arrays.
Definition at line 228 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
_elements_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_elements_size protected
List of corresponding datatype array sizes.
Definition at line 232 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_foreign_memory
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory protected
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
Definition at line 240 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), and FEAT::LAFEM::Container< DT_, IT_ >::clear().
_indices
template<typename DT_ , typename IT_ > std::vector<IT_*> FEAT::LAFEM::Container< DT_, IT_ >::_indices protected
List of pointers to all IT_ dependent arrays.
Definition at line 230 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseVector< DT_, IT_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
_indices_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_indices_size protected
List of corresponding IT_ array sizes.
Definition at line 234 of file container.hpp.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_scalar_dt
template<typename DT_ , typename IT_ > std::vector<DT_> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt protected
List of scalars with datatype DT_.
Definition at line 238 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), and FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt().
_scalar_index
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index protected
List of scalars with datatype index.
Definition at line 236 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::Container(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVector< DT_, IT_ >::allocated_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::sorted(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size().
The documentation for this class was generated from the following file:
kernel/lafem/container.hpp