FEAT: FEAT::Adjacency::ColoringDataHandler Class Reference
FEAT::Adjacency::ColoringDataHandler Class Reference
Datahandler for inverse coloring data.
#include <coloring.hpp>
Public Member Functions
ColoringDataHandler (ColoringDataHandler &&other) noexcept
ColoringDataHandler (const ColoringDataHandler &)=delete
template<typename ColoringType_ >
ColoringDataHandler (const ColoringType_ &coloring, int hint=-1)
Constructor receiving coloring data and optional hint.
void fill_color (const Coloring &coloring, int hint=-1)
Fill in the coloring array.
void fill_color (const std::vector< int > &coloring, int hint=-1)
Fill in the coloring array.
int * get_color_map (Index k)
Get the k-th color map.
const int * get_color_map (Index k) const
Get the k-th color map.
Index get_color_size (Index k) const
std::vector< Index > & get_color_sizes ()
const std::vector< Index > & get_color_sizes () const
std::vector< int * > & get_coloring_maps ()
Retrieve the color maps.
const std::vector< int * > & get_coloring_maps () const
Retrieve the color maps.
Index get_max_color_size () const
Get max size of all colors.
Index get_max_size () const
Index get_num_colors () const
Returns the number of colors.
bool initialized () const
ColoringDataHandler & operator= (ColoringDataHandler &&other) noexcept
ColoringDataHandler & operator= (const ColoringDataHandler &)=delete
void release_color ()
Public Attributes
std::vector< Index > _coloring_map_sizes
vector of coloring sizes
std::vector< int * > _coloring_maps
vector of unified memory pointer
Detailed Description
Datahandler for inverse coloring data.
This class is initialized by coloring data and also holds (if supported) coloring data on the gpu.
Warning
This class does not handle allocating and freeing device data by itself, i.e. you have to call the init_device and free_device function yourself.
Definition at line 252 of file coloring.hpp.
Constructor & Destructor Documentation
ColoringDataHandler() [1/2]
template<typename ColoringType_ > FEAT::Adjacency::ColoringDataHandler::ColoringDataHandler (const ColoringType_ & coloring, int hint = -1) inline
Constructor receiving coloring data and optional hint.
Template Parameters
ColoringType_ The type of the input coloring data.
Constructs the coloring data handle from a coloring data array, i.e. a vector of ints or a Coloring graph.
Parameters
[in] coloring Some array of integers, representing colors.
[in] hint Optionally, provide the numbers of colors. If negative, this is deduced automatically.
Warning
If hint is smaller then the maximum color number, this will lead to an allocation error.
Definition at line 277 of file coloring.hpp.
References fill_color().
~ColoringDataHandler()
FEAT::Adjacency::ColoringDataHandler::~ColoringDataHandler () inline
Definition at line 282 of file coloring.hpp.
ColoringDataHandler() [2/2]
FEAT::Adjacency::ColoringDataHandler::ColoringDataHandler (ColoringDataHandler && other) inline noexcept
Definition at line 292 of file coloring.hpp.
Member Function Documentation
fill_color() [1/2]
void FEAT::Adjacency::ColoringDataHandler::fill_color (const Coloring & coloring, int hint = -1) inline
Fill in the coloring array.
Parameters
[in] coloring The coloring graph.
[in] hint Hint on the number of colors. If negative, this is deduced automatically. For this version, the value is not used.
Definition at line 402 of file coloring.hpp.
References _coloring_map_sizes, _coloring_maps, ASSERTM, FEAT::MemoryPool::copy(), FEAT::Adjacency::Coloring::get_num_colors(), and FEAT::Adjacency::Coloring::size().
fill_color() [2/2]
void FEAT::Adjacency::ColoringDataHandler::fill_color (const std::vector< int > & coloring, int hint = -1) inline
Fill in the coloring array.
Parameters
[in] coloring Array mapping a dof to a color.
[in] hint Hint on the number of colors. If negative, this is deduced automatically.
Definition at line 370 of file coloring.hpp.
References _coloring_map_sizes, _coloring_maps, and FEAT::MemoryPool::copy().
Referenced by ColoringDataHandler(), FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::VoxelAmaVanka(), and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::fill_color().
get_color_map() [1/2]
int * FEAT::Adjacency::ColoringDataHandler::get_color_map (Index k) inline
Get the k-th color map.
Definition at line 334 of file coloring.hpp.
References _coloring_maps.
get_color_map() [2/2]
const int * FEAT::Adjacency::ColoringDataHandler::get_color_map (Index k) const inline
Get the k-th color map.
Definition at line 340 of file coloring.hpp.
References _coloring_maps.
get_color_size()
Index FEAT::Adjacency::ColoringDataHandler::get_color_size (Index k) const inline
Definition at line 318 of file coloring.hpp.
get_color_sizes() [1/2]
std::vector< Index > & FEAT::Adjacency::ColoringDataHandler::get_color_sizes () inline
Definition at line 323 of file coloring.hpp.
get_color_sizes() [2/2]
const std::vector< Index > & FEAT::Adjacency::ColoringDataHandler::get_color_sizes () const inline
Definition at line 328 of file coloring.hpp.
get_coloring_maps() [1/2]
std::vector< int * > & FEAT::Adjacency::ColoringDataHandler::get_coloring_maps () inline
Retrieve the color maps.
Definition at line 346 of file coloring.hpp.
References _coloring_maps.
get_coloring_maps() [2/2]
const std::vector< int * > & FEAT::Adjacency::ColoringDataHandler::get_coloring_maps () const inline
Retrieve the color maps.
Definition at line 352 of file coloring.hpp.
References _coloring_maps.
get_max_color_size()
Index FEAT::Adjacency::ColoringDataHandler::get_max_color_size () const inline
Get max size of all colors.
Definition at line 358 of file coloring.hpp.
References _coloring_map_sizes.
get_max_size()
Index FEAT::Adjacency::ColoringDataHandler::get_max_size () const inline
Definition at line 442 of file coloring.hpp.
get_num_colors()
Index FEAT::Adjacency::ColoringDataHandler::get_num_colors () const inline
Returns the number of colors.
Definition at line 313 of file coloring.hpp.
References _coloring_map_sizes.
initialized()
bool FEAT::Adjacency::ColoringDataHandler::initialized () const inline
Definition at line 437 of file coloring.hpp.
operator=()
ColoringDataHandler & FEAT::Adjacency::ColoringDataHandler::operator= (ColoringDataHandler && other) inline noexcept
Definition at line 300 of file coloring.hpp.
release_color()
void FEAT::Adjacency::ColoringDataHandler::release_color () inline
Definition at line 427 of file coloring.hpp.
Member Data Documentation
_coloring_map_sizes
std::vector<Index> FEAT::Adjacency::ColoringDataHandler::_coloring_map_sizes
vector of coloring sizes
Definition at line 258 of file coloring.hpp.
Referenced by fill_color(), get_max_color_size(), and get_num_colors().
_coloring_maps
std::vector<int*> FEAT::Adjacency::ColoringDataHandler::_coloring_maps
vector of unified memory pointer
Definition at line 256 of file coloring.hpp.
Referenced by fill_color(), get_color_map(), and get_coloring_maps().
The documentation for this class was generated from the following file:
kernel/adjacency/coloring.hpp