FEAT: FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > > Class Template Reference
FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > > Class Template Reference
Convert preconditioner specialization for Global::Vector.
#include <convert_precond.hpp>
Public Types
using BaseClass = SolverBase< VectorTypeOuter >
using SolverTypeInner = SolverBase< VectorTypeInner >
typedef Global::Vector< LocalVectorOuter_, MirrorOuter_ > VectorType
The type of vector this solver can be applied to.
using VectorTypeInner = Global::Vector< LocalVectorInner_, MirrorInner_ >
using VectorTypeOuter = Global::Vector< LocalVectorOuter_, MirrorOuter_ >
Public Member Functions
ConvertPrecond (std::shared_ptr< SolverTypeInner > inner_solver)
Constructor.
virtual Status apply (VectorTypeOuter &vec_cor, const VectorTypeOuter &vec_def) override
Solver application method.
virtual void done ()
Finalization method.
virtual void done_numeric () override
Numeric finalization method.
virtual void done_symbolic () override
Symbolic finalization method.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric initialization method.
virtual void init_symbolic () override
Symbolic initialization method.
virtual String name () const override
Returns the name of the solver.
Protected Attributes
std::shared_ptr< SolverTypeInner > _inner_solver
Detailed Description
template<typename LocalVectorOuter_, typename LocalVectorInner_, typename MirrorOuter_, typename MirrorInner_>
class FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >
Convert preconditioner specialization for Global::Vector.
Definition at line 142 of file convert_precond.hpp.
Member Typedef Documentation
BaseClass
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > using FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::BaseClass = SolverBase<VectorTypeOuter>
Definition at line 147 of file convert_precond.hpp.
SolverTypeInner
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > using FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::SolverTypeInner = SolverBase<VectorTypeInner>
Definition at line 150 of file convert_precond.hpp.
VectorType
typedef Global::Vector< LocalVectorOuter_, MirrorOuter_ > FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >::VectorType inherited
The type of vector this solver can be applied to.
Definition at line 188 of file base.hpp.
VectorTypeInner
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > using FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::VectorTypeInner = Global::Vector<LocalVectorInner_, MirrorInner_>
Definition at line 149 of file convert_precond.hpp.
VectorTypeOuter
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > using FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::VectorTypeOuter = Global::Vector<LocalVectorOuter_, MirrorOuter_>
Definition at line 146 of file convert_precond.hpp.
Constructor & Destructor Documentation
ConvertPrecond()
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::ConvertPrecond (std::shared_ptr< SolverTypeInner > inner_solver) inline explicit
Constructor.
Parameters
[in] inner_solver The actual solver, which shall be executed with converted rhs/sol vectors
Definition at line 165 of file convert_precond.hpp.
Member Function Documentation
apply()
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > virtual Status FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::apply (VectorTypeOuter & vec_cor, const VectorTypeOuter & vec_def) inline override virtual
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implements FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >.
Definition at line 204 of file convert_precond.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::clone(), FEAT::Global::Vector< LocalVector_, Mirror_ >::get_gate(), FEAT::LAFEM::Layout, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::name(), FEAT::Solver::status_success(), and FEAT::Solver::success.
done()
virtual void FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 285 of file base.hpp.
done_numeric()
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > virtual void FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_numeric () inline override virtual
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >.
Definition at line 190 of file convert_precond.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric().
done_symbolic()
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > virtual void FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_symbolic () inline override virtual
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >.
Definition at line 197 of file convert_precond.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
init()
virtual void FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 270 of file base.hpp.
init_numeric()
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > virtual void FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::init_numeric () inline override virtual
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >.
Definition at line 183 of file convert_precond.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_numeric().
init_symbolic()
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > virtual void FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::init_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >.
Definition at line 176 of file convert_precond.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
name()
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > virtual String FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SolverBase< Global::Vector< LocalVectorOuter_, MirrorOuter_ > >.
Definition at line 171 of file convert_precond.hpp.
Member Data Documentation
_inner_solver
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > std::shared_ptr<SolverTypeInner> FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::_inner_solver protected
Definition at line 156 of file convert_precond.hpp.
The documentation for this class was generated from the following file:
kernel/solver/convert_precond.hpp