FEAT: FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ > Class Template Reference
FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ > Class Template Reference
Q2Lagrange thread parallel assembly class for the burgers operator.
#include <burgers_assembler.hpp>
Public Types
typedef LagrangeDataHandler< SpaceType, DT_, IT_ > DataHandler
typedef SpaceHelp::DataType DataType
typedef SpaceHelp::DomainPointType DomainPointType
typedef SpaceHelp::ImagePointType ImagePointType
typedef SpaceHelp::IndexType IndexType
typedef SpaceHelp::JacobianMatrixType JacobianMatrixType
typedef SpaceHelp::ShapeType ShapeType
typedef VoxelAssembly::SpaceHelper< SpaceType, DT_, IT_ > SpaceHelp
typedef VoxelAssembly::Q2StandardHyperCube< dim_ > SpaceType
typedefs
typedef SpaceHelp::ValueType ValueType
Public Member Functions
template<typename ColoringType_ >
VoxelBurgersAssembler (const SpaceType &space, const ColoringType_ &coloring, int hint=-1)
Constructor for burgers assembler.
VoxelBurgersAssembler (const VoxelBurgersAssembler &)=delete
VoxelBurgersAssembler (VoxelBurgersAssembler &&)=default
template<typename CubatureFactory_ >
void assemble_matrix1 (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > &matrix, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect, const SpaceType &space, const CubatureFactory_ &cubature_factory, DataType alpha=DataType(1)) const
Assembles the burgers operator for finitie element space with same test and trial space.
void assemble_matrix1_cuda (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > &matrix, const SpaceType &space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType *cub_pt, const DataType *cub_wg, int num_cubs, DataType alpha) const
void assemble_matrix1_generic (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > &matrix, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect, const SpaceType &space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType *cub_pt, const DataType *cub_wg, int num_cubs, DataType alpha) const
template<typename CubatureFactory_ >
void assemble_vector (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &vector, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &primal, const SpaceType &space, const CubatureFactory_ &cubature_factory, DataType alpha=DataType(1)) const
Assembles the application of the burgers operator to a given primal vector.
void assemble_vector_cuda (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &, const SpaceType &, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType *, const DataType *, int, DataType) const
void assemble_vector_generic (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &vector, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &primal, const SpaceType &space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType *cub_pt, const DataType *cub_wg, int num_cubs, DataType alpha) const
VoxelBurgersAssembler & operator= (const VoxelBurgersAssembler &)=delete
VoxelBurgersAssembler & operator= (VoxelBurgersAssembler &&)=default
void set_sd_v_norm (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > &convect)
Sets the internal maximum streamline diffusion velocity norm.
void set_sd_v_norm (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect)
Sets the internal maximum streamline diffusion velocity norm.
void set_sd_v_norm_cuda (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > &)
void set_sd_v_norm_cuda (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &)
void set_sd_v_norm_generic (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > &convect)
void set_sd_v_norm_generic (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect)
VoxelAssembly::AssemblyBurgersData< DataType > wrap_burgers_params () const
Wraps the set burgers parameter into convenient struct.
Public Attributes
DataType beta
Convection scaling.
int blocksize
the block size to be used
bool deformation
Should we use full deformation formulation?
DataType frechet_beta
Scaling parameter for full jacobian convection part.
int gridsize
the grid size to be used
DataHandler mesh_data
The meshdata handler.
DataType nu
The viscosity.
bool print_occupancy
print out occupancy
DataType sd_delta
Streamline diffusion parameter.
DataType sd_nu
Streamline diffosuion viscosity. Generally equal to nu.
DataType sd_v_norm
The current maximum velocity norm.
int shared_mem
how much shared memory should the kernel use
DataType theta
Reaction scaling.
Static Public Attributes
static constexpr int dim = SpaceHelp::dim
constexpr
Detailed Description
template<int dim_, typename DT_, typename IT_>
class FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >
Q2Lagrange thread parallel assembly class for the burgers operator.
This class provides host and device variants for a thread parallel assembly of the burgers operator. For details on the burgers operator, see the burgers assembler in </kernel/assembly/>. The threading strategy is based on a cell based coloring of the mesh, so in principle this version for Q2 space works as long as a valid coloring is provided.
Template Parameters
dim_ Dimension of the hypercubes.
DT_ Datatype to be used.
IT_ Indextype to be used.
Definition at line 1419 of file burgers_assembler.hpp.
Member Typedef Documentation
DataHandler
template<int dim_, typename DT_ , typename IT_ > typedef LagrangeDataHandler<SpaceType, DT_, IT_> FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::DataHandler
Definition at line 1424 of file burgers_assembler.hpp.
DataType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::DataType
Definition at line 1427 of file burgers_assembler.hpp.
DomainPointType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::DomainPointType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::DomainPointType
Definition at line 1433 of file burgers_assembler.hpp.
ImagePointType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::ImagePointType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::ImagePointType
Definition at line 1434 of file burgers_assembler.hpp.
IndexType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::IndexType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::IndexType
Definition at line 1428 of file burgers_assembler.hpp.
JacobianMatrixType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::JacobianMatrixType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::JacobianMatrixType
Definition at line 1436 of file burgers_assembler.hpp.
ShapeType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::ShapeType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::ShapeType
Definition at line 1426 of file burgers_assembler.hpp.
SpaceHelp
template<int dim_, typename DT_ , typename IT_ > typedef VoxelAssembly::SpaceHelper<SpaceType, DT_, IT_> FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::SpaceHelp
Definition at line 1425 of file burgers_assembler.hpp.
SpaceType
template<int dim_, typename DT_ , typename IT_ > typedef VoxelAssembly::Q2StandardHyperCube<dim_> FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::SpaceType
typedefs
Definition at line 1423 of file burgers_assembler.hpp.
ValueType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::ValueType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::ValueType
Definition at line 1435 of file burgers_assembler.hpp.
Constructor & Destructor Documentation
VoxelBurgersAssembler()
template<int dim_, typename DT_ , typename IT_ > template<typename ColoringType_ > FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::VoxelBurgersAssembler (const SpaceType & space, const ColoringType_ & coloring, int hint = -1) inline explicit
Constructor for burgers assembler.
Template Parameters
ColoringType_ The type of the coloring indexset.
Parameters
[in] space The underlying finite element space.
[in] coloring The coloring index set. Has to map each cell to its color. Obviously requires no two adjecent cells to have the same color.
[in] hint Hint for the number of colors. If < 0 the mesh_data will determine this number itself. Undefined behavior if number is not correct.
Definition at line 1494 of file burgers_assembler.hpp.
~VoxelBurgersAssembler()
template<int dim_, typename DT_ , typename IT_ > FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::~VoxelBurgersAssembler () inline
Definition at line 1521 of file burgers_assembler.hpp.
Member Function Documentation
assemble_matrix1()
template<int dim_, typename DT_ , typename IT_ > template<typename CubatureFactory_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1 (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > & matrix, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect, const SpaceType & space, const CubatureFactory_ & cubature_factory, DataType alpha = DataType(1)) const inline
Assembles the burgers operator for finitie element space with same test and trial space.
Template Parameters
CubatureFactory_ Factory type for cubature data.
Parameters
[in/out] matrix The matrix to be assembled. Adds onto residing data.
[in] convect The convection vector. Values are ignored if either beta or sd_delta is zero.
[in] space The underlying space.
[in] cubature_factory The cubature rule to be used.
[in] alpha Scaling parameter for assembly.
Definition at line 1545 of file burgers_assembler.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::Space::Lagrange2::Element< Trafo_ >::get_num_dofs(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
assemble_matrix1_cuda()
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1_cuda (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > & matrix, const SpaceType & space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType * cub_pt, const DataType * cub_wg, int num_cubs, DataType alpha) const inline
Definition at line 1752 of file burgers_assembler.hpp.
assemble_matrix1_generic()
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1_generic (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > & matrix, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect, const SpaceType & space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType * cub_pt, const DataType * cub_wg, int num_cubs, DataType alpha) const inline
Definition at line 1615 of file burgers_assembler.hpp.
assemble_vector()
template<int dim_, typename DT_ , typename IT_ > template<typename CubatureFactory_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_vector (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & vector, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & primal, const SpaceType & space, const CubatureFactory_ & cubature_factory, DataType alpha = DataType(1)) const inline
Assembles the application of the burgers operator to a given primal vector.
Template Parameters
CubatureFactory_ Factory type for cubature data.
Parameters
[in/out] vector The vector to be assembled. Adds onto residing data.
[in] convect The convection vector. Values are ignored if either beta or sd_delta is zero.
[in] primal The primal vector the operator is applied on.
[in] space The underlying space.
[in] cubature_factory The cubature rule to be used.
[in] alpha Scaling parameter for assembly.
Definition at line 1577 of file burgers_assembler.hpp.
References FEAT::Space::Lagrange2::Element< Trafo_ >::get_num_dofs(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
assemble_vector_cuda()
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_vector_cuda (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & , const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & , const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & , const SpaceType & , typename Cubature::Rule< ShapeType, DataType, DataType >::PointType * , const DataType * , int , DataType) const inline
Definition at line 1757 of file burgers_assembler.hpp.
assemble_vector_generic()
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_vector_generic (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & vector, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & primal, const SpaceType & space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType * cub_pt, const DataType * cub_wg, int num_cubs, DataType alpha) const inline
Definition at line 1630 of file burgers_assembler.hpp.
set_sd_v_norm() [1/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > & convect) inline
Sets the internal maximum streamline diffusion velocity norm.
Parameters
[in] convect The global convection vector which is evaluated regarding its maximum euclidean norm.
Definition at line 1610 of file burgers_assembler.hpp.
set_sd_v_norm() [2/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect) inline
Sets the internal maximum streamline diffusion velocity norm.
Parameters
[in] convect The local convection vector which is evaluated regarding its maximum euclidean norm.
Definition at line 1600 of file burgers_assembler.hpp.
set_sd_v_norm_cuda() [1/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm_cuda (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > &) inline
Definition at line 1769 of file burgers_assembler.hpp.
set_sd_v_norm_cuda() [2/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm_cuda (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &) inline
Definition at line 1763 of file burgers_assembler.hpp.
set_sd_v_norm_generic() [1/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm_generic (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > & convect) inline
Definition at line 1653 of file burgers_assembler.hpp.
set_sd_v_norm_generic() [2/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm_generic (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect) inline
Definition at line 1647 of file burgers_assembler.hpp.
wrap_burgers_params()
template<int dim_, typename DT_ , typename IT_ > VoxelAssembly::AssemblyBurgersData< DataType > FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::wrap_burgers_params () const inline
Wraps the set burgers parameter into convenient struct.
Returns
A wrapper for the burgers data.
Definition at line 1528 of file burgers_assembler.hpp.
Member Data Documentation
beta
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::beta
Convection scaling.
Definition at line 1448 of file burgers_assembler.hpp.
blocksize
template<int dim_, typename DT_ , typename IT_ > int FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::blocksize
the block size to be used
Definition at line 1470 of file burgers_assembler.hpp.
deformation
template<int dim_, typename DT_ , typename IT_ > bool FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::deformation
Should we use full deformation formulation?
Definition at line 1476 of file burgers_assembler.hpp.
dim
template<int dim_, typename DT_ , typename IT_ > constexpr int FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::dim = SpaceHelp::dim static constexpr
constexpr
Definition at line 1431 of file burgers_assembler.hpp.
frechet_beta
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::frechet_beta
Scaling parameter for full jacobian convection part.
Definition at line 1451 of file burgers_assembler.hpp.
gridsize
template<int dim_, typename DT_ , typename IT_ > int FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::gridsize
the grid size to be used
Definition at line 1467 of file burgers_assembler.hpp.
mesh_data
template<int dim_, typename DT_ , typename IT_ > DataHandler FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::mesh_data
The meshdata handler.
Definition at line 1439 of file burgers_assembler.hpp.
nu
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::nu
The viscosity.
Definition at line 1442 of file burgers_assembler.hpp.
print_occupancy
template<int dim_, typename DT_ , typename IT_ > bool FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::print_occupancy
print out occupancy
Definition at line 1473 of file burgers_assembler.hpp.
sd_delta
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::sd_delta
Streamline diffusion parameter.
Definition at line 1454 of file burgers_assembler.hpp.
sd_nu
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::sd_nu
Streamline diffosuion viscosity. Generally equal to nu.
Definition at line 1457 of file burgers_assembler.hpp.
sd_v_norm
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::sd_v_norm
The current maximum velocity norm.
Definition at line 1460 of file burgers_assembler.hpp.
shared_mem
template<int dim_, typename DT_ , typename IT_ > int FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::shared_mem
how much shared memory should the kernel use
Definition at line 1464 of file burgers_assembler.hpp.
theta
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::theta
Reaction scaling.
Definition at line 1445 of file burgers_assembler.hpp.
The documentation for this class was generated from the following file:
kernel/voxel_assembly/burgers_assembler.hpp