FEAT: FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ > Class Template Reference
FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ > Class Template Reference
Discrete evaluation data for vector-valued functions.
#include <discrete_evaluator.hpp>
Public Types
typedef DT_ DataType
the data type
typedef Tiny::Vector< DT_, dim_ > ValueType
the value type
Public Member Functions
bool empty () const
Checks whether the evaluation data is empty.
ValueType mean_value () const
Computes the mean function value.
ValueType mean_value_dist (const Dist::Comm &comm) const
Computes the mean function value on a distributed domain.
Public Attributes
std::vector< ValueType > values
the vector of values
Static Public Attributes
static constexpr int dim = dim_
the image dimension
Detailed Description
template<typename DT_, int dim_>
class FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >
Discrete evaluation data for vector-valued functions.
Template Parameters
DT_ The datatype that is to be used.
dim_ The dimension of the underlying mesh.
Author
Peter Zajac
Definition at line 121 of file discrete_evaluator.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , int dim_> typedef DT_ FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::DataType
the data type
Definition at line 127 of file discrete_evaluator.hpp.
ValueType
template<typename DT_ , int dim_> typedef Tiny::Vector<DT_, dim_> FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::ValueType
the value type
Definition at line 129 of file discrete_evaluator.hpp.
Member Function Documentation
empty()
template<typename DT_ , int dim_> bool FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::empty () const inline
Checks whether the evaluation data is empty.
Definition at line 137 of file discrete_evaluator.hpp.
References FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::values.
mean_value()
template<typename DT_ , int dim_> ValueType FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::mean_value () const inline
Computes the mean function value.
Attention
This function does not work on distributed domains!
Use the mean_value_dist() function in this case instead!
Returns
The mean function value.
Definition at line 152 of file discrete_evaluator.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::format(), and FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::values.
mean_value_dist()
template<typename DT_ , int dim_> ValueType FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::mean_value_dist (const Dist::Comm & comm) const inline
Computes the mean function value on a distributed domain.
Parameters
[in] comm The transient communicator that the domain was distributed on.
Returns
The mean function value.
Definition at line 175 of file discrete_evaluator.hpp.
References FEAT::Dist::Comm::allreduce(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Dist::op_sum, and FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::values.
Member Data Documentation
dim
template<typename DT_ , int dim_> constexpr int FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::dim = dim_ static constexpr
the image dimension
Definition at line 125 of file discrete_evaluator.hpp.
values
template<typename DT_ , int dim_> std::vector<ValueType> FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::values
the vector of values
Definition at line 132 of file discrete_evaluator.hpp.
Referenced by FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::empty(), FEAT::Assembly::DiscreteEvaluator::eval_fe_function(), FEAT::Assembly::DiscreteEvaluator::eval_fe_gradient(), FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::mean_value(), and FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::mean_value_dist().
The documentation for this class was generated from the following file:
kernel/assembly/discrete_evaluator.hpp