FEAT: FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ > Class Template Reference
FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ > Class Template Reference
CSCR based sparse matrix.
#include <sparse_matrix_cscr.hpp>
Public Types
template<typename DT2_ = DT_, typename IT2_ = IT_>
using ContainerType = SparseMatrixCSCR< DT2_, IT2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a matrix container with new Datatape and Index types
typedef DT_ DataType
Our datatype.
typedef const IT_ * ImageIterator
ImageIterator typedef for Adjactor interface implementation.
typedef IT_ IndexType
Our indextype.
typedef DenseVector< DT_, IT_ > VectorTypeL
Compatible L-vector type.
typedef DenseVector< DT_, IT_ > VectorTypeR
Compatible R-vector type.
Public Member Functions
SparseMatrixCSCR ()
Constructor.
SparseMatrixCSCR (const Adjacency::Graph &graph)
Constructor.
SparseMatrixCSCR (const Index rows_in, const Index columns_in, DenseVector< IT_, IT_ > &col_ind_in, DenseVector< DT_, IT_ > &val_in, DenseVector< IT_, IT_ > &row_ptr_in, DenseVector< IT_, IT_ > &row_numbers_in)
Constructor.
template<typename MT_ >
SparseMatrixCSCR (const MT_ &other)
Constructor.
SparseMatrixCSCR (const SparseLayout< IT_, layout_id > &layout_in)
Constructor.
SparseMatrixCSCR (const SparseMatrixCSR< DT_, IT_ > &csr, const VectorMirror< DT_, IT_ > &non_zero_rows)
Constructor.
SparseMatrixCSCR (FileMode mode, std::istream &file)
Constructor.
SparseMatrixCSCR (FileMode mode, String filename)
Constructor.
SparseMatrixCSCR (Index rows_in, Index columns_in)
Constructor.
SparseMatrixCSCR (Index rows_in, Index columns_in, Index used_elements_in, Index used_rows_in)
Constructor.
SparseMatrixCSCR (SparseMatrixCSCR &&other)
Move Constructor.
template<typename DT2_ = DT_, typename IT2_ = IT_>
SparseMatrixCSCR (std::vector< char > input)
Constructor.
std::size_t bytes () const
Returns the total amount of bytes allocated.
virtual void clear ()
Free all allocated arrays.
SparseMatrixCSCR clone (CloneMode clone_mode=CloneMode::Weak) const
Clone operation.
void clone (const Container &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const Container< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const SparseMatrixCSCR< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
IT_ * col_ind ()
Retrieve column indices array.
IT_ const * col_ind () const
template<Perspective = Perspective::native>
Index columns () const
Retrieve matrix column count.
template<typename MT_ >
void convert (const MT_ &a)
Conversion method.
template<typename DT2_ , typename IT2_ >
void convert (const SparseMatrixCSCR< DT2_, IT2_ > &other)
Conversion method.
void copy (const SparseMatrixCSCR &x, bool full=false)
Performs \(this \leftarrow x\).
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void deserialize (std::vector< char > input)
Deserialization of complete container entity.
bool empty () const
Checks whether the container is empty.
void format (DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DT_ min, DT_ max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (const LAFEM::SerialConfig &config)
Calculate size.
const std::vector< DT_ * > & get_elements () const
Returns a list of all data arrays.
const std::vector< Index > & get_elements_size () const
Returns a list of all data array sizes.
const std::vector< IT_ * > & get_indices () const
Returns a list of all Index arrays.
const std::vector< Index > & get_indices_size () const
Returns a list of all Index array sizes.
Index get_length_of_line (const Index row) const
Returns the number of NNZ-elements of the selected row.
const std::vector< DT_ > & get_scalar_dt () const
Returns a list of all scalar values with datatype dt.
const std::vector< Index > & get_scalar_index () const
Returns a list of all scalar values with datatype index.
SparseLayout< IT_, layout_id > layout () const
Retrieve convenient sparse matrix layout object.
void move (Container &&other)
Assignment move operation.
DT_ operator() (Index row, Index col) const
Retrieve specific matrix element.
SparseMatrixCSCR & operator= (const SparseLayout< IT_, layout_id > &layout_in)
Assignment operator.
SparseMatrixCSCR & operator= (SparseMatrixCSCR &&other)
Move operator.
void read_from (FileMode mode, std::istream &file)
Read in matrix from stream.
void read_from (FileMode mode, String filename)
Read in matrix from file.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
IT_ * row_numbers ()
Retrieve row numbers of non zero rows.
IT_ const * row_numbers () const
IT_ * row_ptr ()
Retrieve row start index array.
IT_ const * row_ptr () const
template<Perspective = Perspective::native>
Index rows () const
Retrieve matrix row count.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > serialize (const LAFEM::SerialConfig &config=SerialConfig()) const
Serialization of complete container entity.
std::uint64_t set_checkpoint_data (std::vector< char > &data, const LAFEM::SerialConfig &config)
template<Perspective = Perspective::native>
Index size () const
Returns the containers size.
template<Perspective = Perspective::native>
Index used_elements () const
Retrieve non zero element count.
template<Perspective = Perspective::native>
Index used_rows () const
Retrieve used matrix non zero row count.
DT_ * val ()
Retrieve non zero element array.
DT_ const * val () const
void write_out (FileMode mode, std::ostream &file) const
Write out matrix to file.
void write_out (FileMode mode, String filename) const
Write out matrix to file.
Linear algebra operations
void axpy (const SparseMatrixCSCR &x, const SparseMatrixCSCR &y, const DT_ alpha=DT_(1))
Calculate \(this \leftarrow y + \alpha~ x\).
void scale (const SparseMatrixCSCR &x, const DT_ alpha)
Calculate \(this \leftarrow \alpha~ x \).
DT_ norm_frobenius () const
Calculates the Frobenius norm of this matrix.
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x, bool transposed=false) const
Calculate \(r \leftarrow this\cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1), const bool transposed=false) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Static Public Member Functions
static String name ()
Returns a descriptive string.
Static Public Attributes
static constexpr bool is_global = false
static constexpr bool is_local = true
static constexpr SparseLayoutId layout_id = SparseLayoutId::lt_cscr
Our used layout type.
Protected Member Functions
void _copy_content (const Container &other, bool full)
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::istream &file)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::vector< char > &input)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > _serialize (FileMode mode, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _serialize (FileMode mode, std::ostream &file, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::uint64_t _serialized_size (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Calculation of the serialized size with optional compression of complete container entity.
template<typename DT2_ , typename IT2_ >
void assign (const Container< DT2_, IT2_ > &other)
Assignment operation.
Protected Attributes
std::vector< DT_ * > _elements
List of pointers to all datatype dependent arrays.
std::vector< Index > _elements_size
List of corresponding datatype array sizes.
bool _foreign_memory
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
std::vector< IT_ * > _indices
List of pointers to all IT_ dependent arrays.
std::vector< Index > _indices_size
List of corresponding IT_ array sizes.
std::vector< DT_ > _scalar_dt
List of scalars with datatype DT_.
std::vector< Index > _scalar_index
List of scalars with datatype index.
Private Member Functions
Index & _columns ()
Index & _rows ()
Index & _size ()
Index & _used_elements ()
Index & _used_rows ()
Friends
std::ostream & operator<< (std::ostream &lhs, const SparseMatrixCSCR &b)
SparseMatrixCSCR streaming operator.
bool operator== (const SparseMatrixCSCR &a, const SparseMatrixCSCR &b)
SparseMatrixCSCR comparison operator.
Detailed Description
template<typename DT_, typename IT_ = Index>
class FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >
CSCR based sparse matrix.
Template Parameters
DT_ The datatype to be used.
IT_ The indexing type to be used.
This class represents a sparse matrix, that stores its non zero elements in the compressed sparse compressed row format.
This format is very similar to the standard CSR format but stores explicit row numbers for each non empty row.
Data survey:
_elements[0]: raw non zero number values
_indices[0]: column index per non zero element
_indices[1]: row start index (including matrix end index)
_indices[2]: row number of each non empty row
_scalar_index[0]: container size
_scalar_index[1]: row count
_scalar_index[2]: column count
_scalar_index[3]: non zero element count (used elements)
_scalar_index[4]: non zero row count
Refer to LAFEM design description for general usage informations.
Author
Dirk Ribbrock
Definition at line 63 of file sparse_matrix_cscr.hpp.
Member Typedef Documentation
ContainerType
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::ContainerType = SparseMatrixCSCR<DT2_, IT2_>
Our 'base' class type.
Definition at line 106 of file sparse_matrix_cscr.hpp.
ContainerTypeByDI
template<typename DT_ , typename IT_ = Index> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a matrix container with new Datatape and Index types
Definition at line 110 of file sparse_matrix_cscr.hpp.
DataType
template<typename DT_ , typename IT_ = Index> typedef DT_ FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::DataType
Our datatype.
Definition at line 93 of file sparse_matrix_cscr.hpp.
ImageIterator
template<typename DT_ , typename IT_ = Index> typedef const IT_* FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::ImageIterator
ImageIterator typedef for Adjactor interface implementation.
Definition at line 103 of file sparse_matrix_cscr.hpp.
IndexType
template<typename DT_ , typename IT_ = Index> typedef IT_ FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::IndexType
Our indextype.
Definition at line 95 of file sparse_matrix_cscr.hpp.
VectorTypeL
template<typename DT_ , typename IT_ = Index> typedef DenseVector<DT_, IT_> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::VectorTypeL
Compatible L-vector type.
Definition at line 97 of file sparse_matrix_cscr.hpp.
VectorTypeR
template<typename DT_ , typename IT_ = Index> typedef DenseVector<DT_, IT_> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::VectorTypeR
Compatible R-vector type.
Definition at line 99 of file sparse_matrix_cscr.hpp.
Constructor & Destructor Documentation
SparseMatrixCSCR() [1/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR () inline explicit
Constructor.
Creates an empty non dimensional matrix.
Definition at line 120 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR().
SparseMatrixCSCR() [2/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (Index rows_in, Index columns_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
Creates an empty matrix. Because SparseMatrixCSCR is a read-only container, it stays empty.
Note
This matrix does not allocate any memory
Definition at line 140 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
SparseMatrixCSCR() [3/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (Index rows_in, Index columns_in, Index used_elements_in, Index used_rows_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
[in] used_elements_in The amount of non zero elements of the created matrix.
[in] used_rows_in The amount of non zero rows of the created matrix.
Creates an empty (but allocated) matrix.
Note
The allocated memory will not be initialized.
Definition at line 161 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and XASSERT.
SparseMatrixCSCR() [4/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (const SparseLayout< IT_, layout_id > & layout_in) inline explicit
Constructor.
Parameters
[in] layout_in The layout to be used.
Creates an empty matrix with given layout.
Definition at line 191 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and FEAT::MemoryPool::increase_memory().
SparseMatrixCSCR() [5/12]
template<typename DT_ , typename IT_ = Index> template<typename MT_ > FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (const MT_ & other) inline explicit
Constructor.
Parameters
[in] other The source matrix.
Creates a CSCR matrix based on the source matrix.
Definition at line 213 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert().
SparseMatrixCSCR() [6/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (FileMode mode, String filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a CSCR matrix based on the source file.
Definition at line 227 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::read_from().
SparseMatrixCSCR() [7/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (FileMode mode, std::istream & file) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Creates a CSCR matrix based on the source filestream.
Definition at line 241 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::read_from().
SparseMatrixCSCR() [8/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (const Index rows_in, const Index columns_in, DenseVector< IT_, IT_ > & col_ind_in, DenseVector< DT_, IT_ > & val_in, DenseVector< IT_, IT_ > & row_ptr_in, DenseVector< IT_, IT_ > & row_numbers_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
[in] col_ind_in Vector with column indices.
[in] val_in Vector with non zero elements.
[in] row_ptr_in Vector with start indices of all rows into the val/col_ind arrays. Note that this vector must also contain the end index of the last row and thus has a size of row_count + 1.
[in] row_numbers_in Vector with the row number of each used row.
Creates a matrix with given dimensions and content.
Todo:
maybe create empty matrix if col_ind and val and row_ptr inputs are all three empty
Definition at line 260 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERT.
SparseMatrixCSCR() [9/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (const SparseMatrixCSR< DT_, IT_ > & csr, const VectorMirror< DT_, IT_ > & non_zero_rows) inline explicit
Constructor.
Parameters
[in] csr The source csr matrix.
[in] non_zero_rows The mirror describing the rows to be selected
Creates a matrix with selected rows from a given csr matrix.
Definition at line 300 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::MemoryPool::copy(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::MemoryPool::set_memory(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERT.
SparseMatrixCSCR() [10/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (const Adjacency::Graph & graph) inline explicit
Constructor.
Parameters
[in] graph The graph to create the matrix from
Creates a CSCR matrix based on a given adjacency graph, representing the sparsity pattern.
Definition at line 364 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), ASSERT, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Adjacency::Graph::get_num_indices(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr().
SparseMatrixCSCR() [11/12]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (std::vector< char > input) inline explicit
Constructor.
Parameters
[in] input A std::vector, containing the byte array.
Creates a matrix from the given byte array.
Definition at line 423 of file sparse_matrix_cscr.hpp.
SparseMatrixCSCR() [12/12]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR (SparseMatrixCSCR< DT_, IT_ > && other) inline
Move Constructor.
Parameters
[in] other The source matrix.
Moves a given matrix to this matrix.
Definition at line 436 of file sparse_matrix_cscr.hpp.
Member Function Documentation
_columns()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::_columns () inline private
Definition at line 76 of file sparse_matrix_cscr.hpp.
_copy_content()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::_copy_content (const Container< DT_, IT_ > & other, bool full) inline protected inherited
Definition at line 242 of file container.hpp.
_deserialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::istream & file) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file std::istream, pointing to the input data.
Recreate a complete container entity by a single binary file.
Definition at line 776 of file container.hpp.
References XABORTM.
_deserialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::vector< char > & input) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] input A std::vector containing the byte array.
Recreate a complete container entity by a single binary array.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 622 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Pack::decode(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Type::Helper::extract_floatness(), FEAT::Type::Helper::extract_intness(), FEAT::Type::Helper::extract_signedness(), FEAT::Type::Helper::extract_type_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, XABORTM, XASSERT, and XASSERTM.
_rows()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::_rows () inline private
Definition at line 71 of file sparse_matrix_cscr.hpp.
_serialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
Array data layout:
raw array size in bytes (std::uint64_t)
magic number (std::uint64_t)
DT_ 'hash' value (sizeof(DT_) and floating/integral distinction (packed std::uint64_t)
IT_ 'hash' value (sizeof(IT_) and floating/integral distinction (packed std::uint64_t)
_elements.size() (std::uint64_t)
_indices.size() (std::uint64_t)
_elements_size.size() (std::uint64_t)
_indices_size.size() (std::uint64_t)
_scalar_index.size() (std::uint64_t)
_scalar_dt.size() (std::uint64_t)
_compressed (std::uint64_t)
_elements_size array (std::uint64_t)
_elements arrays byte_size (std::uint64_t) just temporary to read in data
_indices_size array (std::uint64_t)
_indices arrays byte_size (std::uint64_t)
_scalar_index array (std::uint64_t)
_scalar_dt array (DT2_)
_elements arrays (DT2_)
_indices arrays (IT2_)
See FEAT::LAFEM::SerialConfig for details.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 440 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XASSERTM.
_serialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, std::ostream & file, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file The output stream to write data into.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary file with compression enabled. See FEAT::LAFEM::SerialConfig for details.
Definition at line 605 of file container.hpp.
References XABORTM.
_serialized_size()
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline protected inherited
Calculation of the serialized size with optional compression of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Returns
An unsigned int containing the size of serialized container.
Calculate the size of the serialized container entity.
Definition at line 357 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), and FEAT::LAFEM::indices_zlib.
_size()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::_size () inline private
Definition at line 66 of file sparse_matrix_cscr.hpp.
_used_elements()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::_used_elements () inline private
Definition at line 81 of file sparse_matrix_cscr.hpp.
_used_rows()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::_used_rows () inline private
Definition at line 86 of file sparse_matrix_cscr.hpp.
apply() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x, bool transposed = false) const inline
Calculate \(r \leftarrow this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] transposed Should the product use the transposed matrix?
Definition at line 968 of file sparse_matrix_cscr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), and XASSERTM.
apply() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1), const bool transposed = false) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
[in] transposed Should the product use the transposed matrix?
Definition at line 1008 of file sparse_matrix_cscr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), and XASSERTM.
assign()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::assign (const Container< DT2_, IT2_ > & other) inline protected inherited
Assignment operation.
Assigns contents of another container
Parameters
[in] other The source container.
Definition at line 282 of file container.hpp.
References FEAT::MemoryPool::convert(), FEAT::MemoryPool::increase_memory(), and FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
axpy()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::axpy (const SparseMatrixCSCR< DT_, IT_ > & x, const SparseMatrixCSCR< DT_, IT_ > & y, const DT_ alpha = DT_(1)) inline
Calculate \(this \leftarrow y + \alpha~ x\).
Parameters
[in] x The first summand matrix to be scaled.
[in] y The second summand matrix
[in] alpha A scalar to multiply x with.
Warning
All three matrices must have the same non zero layout. This operation assumes this silently and does not check this on its own!
Definition at line 894 of file sparse_matrix_cscr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), and XASSERTM.
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::LAFEM::Container< DT_, IT_ >::bytes () const inline inherited
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 1033 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes().
clear()
template<typename DT_ , typename IT_ > virtual void FEAT::LAFEM::Container< DT_, IT_ >::clear () inline virtual inherited
Free all allocated arrays.
Definition at line 874 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from().
clone() [1/4]
template<typename DT_ , typename IT_ = Index> SparseMatrixCSCR FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone (CloneMode clone_mode = CloneMode::Weak) const inline
Clone operation.
Create a clone of this container.
Parameters
[in] clone_mode The actual cloning procedure.
Returns
The created clone.
Definition at line 463 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone().
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone().
clone() [2/4]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 901 of file container.hpp.
References FEAT::LAFEM::Allocate, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Deep, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Layout, FEAT::LAFEM::Shallow, FEAT::LAFEM::Weak, XABORTM, and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVector< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone().
clone() [3/4]
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 974 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), and FEAT::LAFEM::Container< DT_, IT_ >::clone().
clone() [4/4]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone (const SparseMatrixCSCR< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline
Clone operation.
Create a clone of another container.
Parameters
[in] other The source container to create the clone from.
[in] clone_mode The actual cloning procedure.
Definition at line 479 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clone().
col_ind() [1/2]
template<typename DT_ , typename IT_ = Index> IT_ * FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind () inline
Retrieve column indices array.
Returns
Column indices array.
Definition at line 783 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), and FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix().
col_ind() [2/2]
template<typename DT_ , typename IT_ = Index> IT_ const * FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind () const inline
Definition at line 791 of file sparse_matrix_cscr.hpp.
columns()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns () const inline
Retrieve matrix column count.
Returns
Matrix column count.
Definition at line 751 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::create_vector_r(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::scale().
convert() [1/2]
template<typename DT_ , typename IT_ = Index> template<typename MT_ > void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert (const MT_ & a) inline
Conversion method.
Parameters
[in] a The input matrix.
Converts any matrix to SparseMatrixCSCR-format
Definition at line 505 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::elements().
convert() [2/2]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert (const SparseMatrixCSCR< DT2_, IT2_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 492 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign().
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert().
copy()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::copy (const SparseMatrixCSCR< DT_, IT_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The Matrix to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 878 of file sparse_matrix_cscr.hpp.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::axpy().
create_vector_l()
template<typename DT_ , typename IT_ = Index> VectorTypeL FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 1049 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows().
create_vector_r()
template<typename DT_ , typename IT_ = Index> VectorTypeR FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 1055 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns().
deserialize()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::deserialize (std::vector< char > input) inline
Deserialization of complete container entity.
Parameters
[in] input A std::vector, containing the byte array.
Recreate a complete container entity by a single binary array.
Definition at line 596 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::fm_cscr.
empty()
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::empty () const inline inherited
Checks whether the container is empty.
Returns
true if the container is empty, otherwise false.
Definition at line 1156 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic().
format() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (DT_ value = DT_(0)) inline inherited
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 847 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::MemoryPool::set_memory(), and FEAT::value.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
format() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (Random & rng, DT_ min, DT_ max) inline inherited
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 860 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::MemoryPool::set_memory().
get_checkpoint_size()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::get_checkpoint_size (const LAFEM::SerialConfig & config) inline inherited
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1009 of file container.hpp.
get_elements()
template<typename DT_ , typename IT_ > const std::vector< DT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements () const inline inherited
Returns a list of all data arrays.
Returns
A list of all data arrays.
Definition at line 1059 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
get_elements_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size () const inline inherited
Returns a list of all data array sizes.
Returns
A list of all data array sizes.
Definition at line 1079 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
get_indices()
template<typename DT_ , typename IT_ > const std::vector< IT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices () const inline inherited
Returns a list of all Index arrays.
Returns
A list of all Index arrays.
Definition at line 1069 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
get_indices_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size () const inline inherited
Returns a list of all Index array sizes.
Returns
A list of all Index array sizes.
Definition at line 1089 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices_size.
get_length_of_line()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::get_length_of_line (const Index row) const inline
Returns the number of NNZ-elements of the selected row.
Definition at line 1061 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr().
get_scalar_dt()
template<typename DT_ , typename IT_ > const std::vector< DT_ > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt () const inline inherited
Returns a list of all scalar values with datatype dt.
Returns
A list of all scalars with datatype dt.
Definition at line 1109 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt.
get_scalar_index()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index () const inline inherited
Returns a list of all scalar values with datatype index.
Returns
A list of all scalars with datatype index.
Definition at line 1099 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
layout()
template<typename DT_ , typename IT_ = Index> SparseLayout< IT_, layout_id > FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout () const inline
Retrieve convenient sparse matrix layout object.
Returns
An object containing the sparse matrix layout.
Definition at line 729 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
move()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::move (Container< DT_, IT_ > && other) inline inherited
Assignment move operation.
Move another container to the current one.
Parameters
[in] other The source container.
Definition at line 988 of file container.hpp.
References FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::operator=().
name()
template<typename DT_ , typename IT_ = Index> static String FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 867 of file sparse_matrix_cscr.hpp.
norm_frobenius()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::norm_frobenius () const inline
Calculates the Frobenius norm of this matrix.
Returns
The Frobenius norm of this matrix.
Definition at line 948 of file sparse_matrix_cscr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val().
operator()()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator() (Index row, Index col) const inline
Retrieve specific matrix element.
Parameters
[in] row The row of the matrix element.
[in] col The column of the matrix element.
Returns
Specific matrix element.
Definition at line 699 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_indices, ASSERT, FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows().
operator=() [1/2]
template<typename DT_ , typename IT_ = Index> SparseMatrixCSCR & FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator= (const SparseLayout< IT_, layout_id > & layout_in) inline
Assignment operator.
Parameters
[in] layout_in A sparse matrix layout.
Assigns a new matrix layout, discarding all old data
Definition at line 562 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::MemoryPool::increase_memory(), and FEAT::MemoryPool::release_memory().
operator=() [2/2]
template<typename DT_ , typename IT_ = Index> SparseMatrixCSCR & FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator= (SparseMatrixCSCR< DT_, IT_ > && other) inline
Move operator.
Parameters
[in] other The source matrix.
Moves another matrix to the target matrix.
Definition at line 448 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::move().
read_from() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::read_from (FileMode mode, std::istream & file) inline
Read in matrix from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Definition at line 641 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_cscr, and XABORTM.
read_from() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::read_from (FileMode mode, String filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 623 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::read_from().
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::restore_from_checkpoint_data (std::vector< char > & data) inline inherited
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1015 of file container.hpp.
References FEAT::LAFEM::fm_binary.
row_numbers() [1/2]
template<typename DT_ , typename IT_ = Index> IT_ * FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers () inline
Retrieve row numbers of non zero rows.
Returns
Row number array.
Definition at line 846 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()().
row_numbers() [2/2]
template<typename DT_ , typename IT_ = Index> IT_ const * FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers () const inline
Definition at line 854 of file sparse_matrix_cscr.hpp.
row_ptr() [1/2]
template<typename DT_ , typename IT_ = Index> IT_ * FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr () inline
Retrieve row start index array.
Returns
Row start index array.
Definition at line 825 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::get_length_of_line(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()().
row_ptr() [2/2]
template<typename DT_ , typename IT_ = Index> IT_ const * FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr () const inline
Definition at line 833 of file sparse_matrix_cscr.hpp.
rows()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows () const inline
Retrieve matrix row count.
Returns
Matrix row count.
Definition at line 740 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::create_vector_l(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::scale().
scale()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::scale (const SparseMatrixCSCR< DT_, IT_ > & x, const DT_ alpha) inline
Calculate \(this \leftarrow \alpha~ x \).
Parameters
[in] x The matrix to be scaled.
[in] alpha A scalar to scale x with.
Definition at line 928 of file sparse_matrix_cscr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), and XASSERTM.
serialize()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::serialize (const LAFEM::SerialConfig & config = SerialConfig()) const inline
Serialization of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary array.
See FEAT::LAFEM::Container::_serialize for details.
Definition at line 612 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::fm_cscr.
set_checkpoint_data()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::set_checkpoint_data (std::vector< char > & data, const LAFEM::SerialConfig & config) inline inherited
Definition at line 1021 of file container.hpp.
References FEAT::LAFEM::fm_binary.
size()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::size () const inline inherited
Returns the containers size.
Returns
The containers size.
The template parameter of type Perspective is used in blocked containers to switch between the raw size and the size, when every block is treated as one entry.
Most containers like SparseMatrixCSR ignore this template parameter.
Definition at line 1127 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseVector< DT_, IT_ >::compare_layout(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_local_dofs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::get_num_nodes_image(), FEAT::LAFEM::DenseVector< DT_, IT_ >::inflate_to_blocks(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::Assembly::FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >::interpolate(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::map_local_to_global_index(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::mask_scatter(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::write_out().
used_elements()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements () const inline
Retrieve non zero element count.
Returns
Non zero element count.
Definition at line 773 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::norm_frobenius(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::scale().
used_rows()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows () const inline
Retrieve used matrix non zero row count.
Returns
Used matrix non zero row count.
Definition at line 762 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()().
val() [1/2]
template<typename DT_ , typename IT_ = Index> DT_ * FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val () inline
Retrieve non zero element array.
Returns
Non zero element array.
Definition at line 804 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::norm_frobenius(), and FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::scale().
val() [2/2]
template<typename DT_ , typename IT_ = Index> DT_ const * FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val () const inline
Definition at line 812 of file sparse_matrix_cscr.hpp.
write_out() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::write_out (FileMode mode, std::ostream & file) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
Definition at line 678 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_cscr, and XABORTM.
write_out() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::write_out (FileMode mode, String filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 660 of file sparse_matrix_cscr.hpp.
References FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::write_out().
Friends And Related Function Documentation
operator<<
template<typename DT_ , typename IT_ = Index> std::ostream & operator<< (std::ostream & lhs, const SparseMatrixCSCR< DT_, IT_ > & b) friend
SparseMatrixCSCR streaming operator.
Parameters
[in] lhs The target stream.
[in] b The matrix to be streamed.
Definition at line 1179 of file sparse_matrix_cscr.hpp.
operator==
template<typename DT_ , typename IT_ = Index> bool operator== (const SparseMatrixCSCR< DT_, IT_ > & a, const SparseMatrixCSCR< DT_, IT_ > & b) friend
SparseMatrixCSCR comparison operator.
Parameters
[in] a A matrix to compare with.
[in] b A matrix to compare with.
Definition at line 1101 of file sparse_matrix_cscr.hpp.
Member Data Documentation
_elements
template<typename DT_ , typename IT_ > std::vector<DT_*> FEAT::LAFEM::Container< DT_, IT_ >::_elements protected inherited
List of pointers to all datatype dependent arrays.
Definition at line 228 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
_elements_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_elements_size protected inherited
List of corresponding datatype array sizes.
Definition at line 232 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_foreign_memory
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory protected inherited
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
Definition at line 240 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), and FEAT::LAFEM::Container< DT_, IT_ >::clear().
_indices
template<typename DT_ , typename IT_ > std::vector<IT_*> FEAT::LAFEM::Container< DT_, IT_ >::_indices protected inherited
List of pointers to all IT_ dependent arrays.
Definition at line 230 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseVector< DT_, IT_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
_indices_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_indices_size protected inherited
List of corresponding IT_ array sizes.
Definition at line 234 of file container.hpp.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_scalar_dt
template<typename DT_ , typename IT_ > std::vector<DT_> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt protected inherited
List of scalars with datatype DT_.
Definition at line 238 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), and FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt().
_scalar_index
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index protected inherited
List of scalars with datatype index.
Definition at line 236 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::Container(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVector< DT_, IT_ >::allocated_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::sorted(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size().
is_global
template<typename DT_ , typename IT_ = Index> constexpr bool FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::is_global = false static constexpr
Definition at line 112 of file sparse_matrix_cscr.hpp.
is_local
template<typename DT_ , typename IT_ = Index> constexpr bool FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::is_local = true static constexpr
Definition at line 113 of file sparse_matrix_cscr.hpp.
layout_id
template<typename DT_ , typename IT_ = Index> constexpr SparseLayoutId FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout_id = SparseLayoutId::lt_cscr static constexpr
Our used layout type.
Definition at line 101 of file sparse_matrix_cscr.hpp.
The documentation for this class was generated from the following files:
kernel/lafem/forward.hpp
kernel/lafem/sparse_matrix_cscr.hpp