FEAT: FEAT::LAFEM::TestMatrixFactory Class Reference
FEAT::LAFEM::TestMatrixFactory Class Reference
Public Member Functions
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void create (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix, Index nrows, Index ncols, Index nnze, TestMatrixFlags flags)
Creates a sparse matrix in BCSR format with various properties based on the specified flags.
template<typename DT_ , typename IT_ >
void create (SparseMatrixCSR< DT_, IT_ > &matrix, Index nrows, Index ncols, Index nnze, TestMatrixFlags flags)
Creates a sparse matrix in CSR format with various properties based on the specified flags.
void seed_rng_by_timer (int rank=0)
Public Attributes
Random rng
Protected Member Functions
Adjacency::Graph _create_generic_struct (Index nrows, Index ncols, Index nnze)
Creates a generic sparse matrix structure in CSR format based on the specified dimensions and non-zero entries.
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void _create_generic_struct (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix, Index nrows, Index ncols, Index nnze)
Creates a generic sparse matrix structure in BCSR format based on the specified dimensions and non-zero entries.
template<typename DT_ , typename IT_ >
void _create_generic_struct (SparseMatrixCSR< DT_, IT_ > &matrix, Index nrows, Index ncols, Index nnze)
Adjacency::Graph _create_non_empty_diag_struct (Index nrows, Index ncols, Index nnze)
Creates a non empty diagonal sparse matrix structure in CSR format based on the specified dimensions and non-zero entries.
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void _create_non_empty_diag_struct (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix, Index nrows, Index ncols, Index nnze)
Creates a non empty diagonal sparse matrix structure in BCSR format based on the specified dimensions and non-zero entries.
template<typename DT_ , typename IT_ >
void _create_non_empty_diag_struct (SparseMatrixCSR< DT_, IT_ > &matrix, Index nrows, Index ncols, Index nnze)
Adjacency::Graph _create_symmetric_struct (Index nrows, Index ncols, Index nnze)
Creates a symmetric sparse matrix structure in CSR format based on the specified dimensions and non-zero entries.
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void _create_symmetric_struct (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix, Index nrows, Index ncols, Index nnze)
Creates a symmetric sparse matrix structure in BCSR format based on the specified dimensions and non-zero entries.
template<typename DT_ , typename IT_ >
void _create_symmetric_struct (SparseMatrixCSR< DT_, IT_ > &matrix, Index nrows, Index ncols, Index nnze)
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void _fill_generic_values (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix)
Fills the values of a sparse matrix in BCSR format with random values between -1 and 1.
template<typename DT_ , typename IT_ >
void _fill_generic_values (SparseMatrixCSR< DT_, IT_ > &matrix)
Fills the values of a sparse matrix in CSR format with random values between -1 and 1.
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void _fill_non_negative_values (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix)
Fills the values of a sparse matrix in BCSR format with random non negative values between 0 and 1.
template<typename DT_ , typename IT_ >
void _fill_non_negative_values (SparseMatrixCSR< DT_, IT_ > &matrix)
Fills the values of a sparse matrix in CSR format with random non negative values between 0 and 1.
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void _make_diagonal_dominant (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix)
Ensures that a sparse matrix in BCSR format is diagonal dominant.
template<typename DT_ , typename IT_ >
void _make_diagonal_dominant (SparseMatrixCSR< DT_, IT_ > &matrix)
Ensures that a sparse matrix in CSR format is diagonal dominant.
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void _make_non_zero_diag (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix)
Ensures that the diagonal entries of a sparse matrix in BCSR format are non-zero.
template<typename DT_ , typename IT_ >
void _make_non_zero_diag (SparseMatrixCSR< DT_, IT_ > &matrix)
Ensures that the diagonal entries of a sparse matrix in CSR format are non-zero.
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_>
void _make_symmetric_values (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &matrix)
Ensures that the values of a sparse matrix in BCSR format are symmetric.
template<typename DT_ , typename IT_ >
void _make_symmetric_values (SparseMatrixCSR< DT_, IT_ > &matrix)
Ensures that the values of a sparse matrix in CSR format are symmetric.
Detailed Description
Definition at line 64 of file test_matrix_factory.hpp.
Member Function Documentation
_create_generic_struct() [1/3]
Adjacency::Graph FEAT::LAFEM::TestMatrixFactory::_create_generic_struct (Index nrows, Index ncols, Index nnze) inline protected
Creates a generic sparse matrix structure in CSR format based on the specified dimensions and non-zero entries.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) to be created and initialized with a generic structure.
[in] nrows The number of rows in the matrix, must be greater than zero.
[in] ncols The number of columns in the matrix, must be greater than zero.
[in] nnze The desired number of non-zero entries in the matrix.
Definition at line 237 of file test_matrix_factory.hpp.
References FEAT::Adjacency::as_is, FEAT::Adjacency::DynamicGraph::get_num_indices(), FEAT::Adjacency::DynamicGraph::insert(), and XASSERT.
Referenced by _create_generic_struct(), and create().
_create_generic_struct() [2/3]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::_create_generic_struct (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix, Index nrows, Index ncols, Index nnze) inline protected
Creates a generic sparse matrix structure in BCSR format based on the specified dimensions and non-zero entries.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) to be created and initialized with a generic structure.
[in] nrows The number of rows in the matrix, must be greater than zero.
[in] ncols The number of columns in the matrix, must be greater than zero.
[in] nnze The desired number of non-zero entries in the matrix.
Definition at line 275 of file test_matrix_factory.hpp.
References _create_generic_struct().
_create_generic_struct() [3/3]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::_create_generic_struct (SparseMatrixCSR< DT_, IT_ > & matrix, Index nrows, Index ncols, Index nnze) inline protected
Definition at line 254 of file test_matrix_factory.hpp.
_create_non_empty_diag_struct() [1/3]
Adjacency::Graph FEAT::LAFEM::TestMatrixFactory::_create_non_empty_diag_struct (Index nrows, Index ncols, Index nnze) inline protected
Creates a non empty diagonal sparse matrix structure in CSR format based on the specified dimensions and non-zero entries.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) to be created and initialized with a generic structure.
[in] nrows The number of rows in the matrix, must be greater than zero.
[in] ncols The number of columns in the matrix, must be greater than zero.
[in] nnze The desired number of non-zero entries in the matrix.
Note
the matrix has to be square
Definition at line 364 of file test_matrix_factory.hpp.
References FEAT::Adjacency::as_is, FEAT::Adjacency::DynamicGraph::get_num_indices(), FEAT::Adjacency::DynamicGraph::insert(), and XASSERT.
Referenced by _create_non_empty_diag_struct(), and create().
_create_non_empty_diag_struct() [2/3]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::_create_non_empty_diag_struct (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix, Index nrows, Index ncols, Index nnze) inline protected
Creates a non empty diagonal sparse matrix structure in BCSR format based on the specified dimensions and non-zero entries.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) to be created and initialized with a generic structure.
[in] nrows The number of rows in the matrix, must be greater than zero.
[in] ncols The number of columns in the matrix, must be greater than zero.
[in] nnze The desired number of non-zero entries in the matrix.
Note
the matrix as well as the blocks have to be square
Definition at line 410 of file test_matrix_factory.hpp.
References _create_non_empty_diag_struct(), and XASSERT.
_create_non_empty_diag_struct() [3/3]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::_create_non_empty_diag_struct (SparseMatrixCSR< DT_, IT_ > & matrix, Index nrows, Index ncols, Index nnze) inline protected
Definition at line 387 of file test_matrix_factory.hpp.
_create_symmetric_struct() [1/3]
Adjacency::Graph FEAT::LAFEM::TestMatrixFactory::_create_symmetric_struct (Index nrows, Index ncols, Index nnze) inline protected
Creates a symmetric sparse matrix structure in CSR format based on the specified dimensions and non-zero entries.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) to be created and initialized with a generic structure.
[in] nrows The number of rows in the matrix, must be greater than zero.
[in] ncols The number of columns in the matrix, must be greater than zero.
[in] nnze The desired number of non-zero entries in the matrix.
Note
The matrix has to be square There might be nnze +- 1 entries
Definition at line 299 of file test_matrix_factory.hpp.
References FEAT::Adjacency::as_is, FEAT::Adjacency::DynamicGraph::get_num_indices(), FEAT::Adjacency::DynamicGraph::insert(), and XASSERT.
Referenced by _create_symmetric_struct(), and create().
_create_symmetric_struct() [2/3]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::_create_symmetric_struct (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix, Index nrows, Index ncols, Index nnze) inline protected
Creates a symmetric sparse matrix structure in BCSR format based on the specified dimensions and non-zero entries.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) to be created and initialized with a generic structure.
[in] nrows The number of rows in the matrix, must be greater than zero.
[in] ncols The number of columns in the matrix, must be greater than zero.
[in] nnze The desired number of non-zero entries in the matrix.
Note
The matrix as well as the blocks have to be square There might be nnze +-1 entries
Definition at line 341 of file test_matrix_factory.hpp.
References _create_symmetric_struct(), and XASSERT.
_create_symmetric_struct() [3/3]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::_create_symmetric_struct (SparseMatrixCSR< DT_, IT_ > & matrix, Index nrows, Index ncols, Index nnze) inline protected
Definition at line 317 of file test_matrix_factory.hpp.
_fill_generic_values() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::_fill_generic_values (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix) inline protected
Fills the values of a sparse matrix in BCSR format with random values between -1 and 1.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) whose non-zero values will be filled with randomly generated values.
Definition at line 440 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val().
_fill_generic_values() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::_fill_generic_values (SparseMatrixCSR< DT_, IT_ > & matrix) inline protected
Fills the values of a sparse matrix in CSR format with random values between -1 and 1.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) whose non-zero values will be filled with randomly generated values.
Definition at line 424 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
Referenced by create().
_fill_non_negative_values() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::_fill_non_negative_values (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix) inline protected
Fills the values of a sparse matrix in BCSR format with random non negative values between 0 and 1.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) whose non-zero values will be filled with randomly generated values.
Definition at line 474 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val().
_fill_non_negative_values() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::_fill_non_negative_values (SparseMatrixCSR< DT_, IT_ > & matrix) inline protected
Fills the values of a sparse matrix in CSR format with random non negative values between 0 and 1.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) whose non-zero values will be filled with randomly generated values.
Definition at line 458 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
Referenced by create().
_make_diagonal_dominant() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::_make_diagonal_dominant (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix) inline protected
Ensures that a sparse matrix in BCSR format is diagonal dominant.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) whose diagonal entries will be modified to ensure that the matrix is diagonal dominant.
Note
The matrix as well as the blocks have to be square
Definition at line 682 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val().
_make_diagonal_dominant() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::_make_diagonal_dominant (SparseMatrixCSR< DT_, IT_ > & matrix) inline protected
Ensures that a sparse matrix in CSR format is diagonal dominant.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) whose diagonal entries will be modified to ensure that the matrix is diagonal dominant.
Note
The matrix has to be square
Definition at line 642 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
Referenced by create().
_make_non_zero_diag() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::_make_non_zero_diag (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix) inline protected
Ensures that the diagonal entries of a sparse matrix in BCSR format are non-zero.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) whose diagonal entries will be modified to ensure they are non-zero.
Note
The matrix as well as the blocks have to be square
Definition at line 610 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val().
_make_non_zero_diag() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::_make_non_zero_diag (SparseMatrixCSR< DT_, IT_ > & matrix) inline protected
Ensures that the diagonal entries of a sparse matrix in CSR format are non-zero.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) whose diagonal entries will be modified to ensure they are non-zero.
Note
The matrix has to be square
Definition at line 579 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
Referenced by create().
_make_symmetric_values() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::_make_symmetric_values (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix) inline protected
Ensures that the values of a sparse matrix in BCSR format are symmetric.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) whose non-zero values will be modified to ensure symmetry.
Note
The matrix as well as the blocks have to be square
Definition at line 535 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val().
_make_symmetric_values() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::_make_symmetric_values (SparseMatrixCSR< DT_, IT_ > & matrix) inline protected
Ensures that the values of a sparse matrix in CSR format are symmetric.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) whose non-zero values will be modified to ensure symmetry.
Note
The matrix has to be square
Definition at line 495 of file test_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
Referenced by create().
create() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::TestMatrixFactory::create (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & matrix, Index nrows, Index ncols, Index nnze, TestMatrixFlags flags) inline
Creates a sparse matrix in BCSR format with various properties based on the specified flags.
Parameters
[in,out] matrix The sparse matrix object (in BCSR format) to be created and filled.
[in] nrows The number of rows in the matrix.
[in] ncols The number of columns in the matrix.
[in] nnze The number of non-zero entries in the matrix.
[in] flags
Definition at line 167 of file test_matrix_factory.hpp.
References _create_generic_struct(), _create_non_empty_diag_struct(), _create_symmetric_struct(), _fill_generic_values(), _fill_non_negative_values(), _make_diagonal_dominant(), _make_non_zero_diag(), _make_symmetric_values(), FEAT::LAFEM::diagonal_dominant, FEAT::LAFEM::non_empty_diag, FEAT::LAFEM::non_negative, FEAT::LAFEM::non_zero_diag, FEAT::LAFEM::symmetric, and FEAT::LAFEM::symmetric_struct.
create() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::TestMatrixFactory::create (SparseMatrixCSR< DT_, IT_ > & matrix, Index nrows, Index ncols, Index nnze, TestMatrixFlags flags) inline
Creates a sparse matrix in CSR format with various properties based on the specified flags.
Parameters
[in,out] matrix The sparse matrix object (in CSR format) to be created and filled.
[in] nrows The number of rows in the matrix.
[in] ncols The number of columns in the matrix.
[in] nnze The number of non-zero entries in the matrix.
[in] flags
Definition at line 95 of file test_matrix_factory.hpp.
References _create_generic_struct(), _create_non_empty_diag_struct(), _create_symmetric_struct(), _fill_generic_values(), _fill_non_negative_values(), _make_diagonal_dominant(), _make_non_zero_diag(), _make_symmetric_values(), FEAT::LAFEM::diagonal_dominant, FEAT::LAFEM::non_empty_diag, FEAT::LAFEM::non_negative, FEAT::LAFEM::non_zero_diag, FEAT::LAFEM::symmetric, and FEAT::LAFEM::symmetric_struct.
seed_rng_by_timer()
void FEAT::LAFEM::TestMatrixFactory::seed_rng_by_timer (int rank = 0) inline
Definition at line 71 of file test_matrix_factory.hpp.
Member Data Documentation
rng
Random FEAT::LAFEM::TestMatrixFactory::rng
Definition at line 67 of file test_matrix_factory.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/test_matrix_factory.hpp