FEAT: FEAT::LAFEM::FilterChain< First_, Rest_ > Class Template Reference
FEAT::LAFEM::FilterChain< First_, Rest_ > Class Template Reference
Filter Chainclass template.
#include <filter_chain.hpp>
Public Types
typedef First_::DataType DataType
sub-filter data-type
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using FilterType = FilterChain< typename First_::template FilterType< DT2_, IT2_ >, typename Rest_::template FilterType< DT2_, IT2_ >... >
Our 'base' class type.
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using FilterTypeByDI = FilterType< DT2_, IT2_ >
this typedef lets you create a matrix container with different Data and Index types
typedef First_::IndexType IndexType
sub-filter index-type
typedef First_::VectorType VectorType
Public Member Functions
FilterChain ()
default ctor
FilterChain (FilterChain &&other)
move-ctor
FilterChain (First_ &&the_first, Rest_ &&... the_rest)
sub-filter emplacement ctor
template<int i_>
TupleElement< i_, First_, Rest_... >::Type & at ()
template<int i_>
TupleElement< i_, First_, Rest_... >::Type const & at () const
std::size_t bytes () const
Returns the total amount of bytes allocated.
FilterChain clone (CloneMode clone_mode=CloneMode::Deep) const
Creates a clone of itself.
void clone (const FilterChain &other, CloneMode clone_mode=CloneMode::Deep)
Clones data from another FilterChain.
template<typename... SubFilter2_>
void convert (const FilterChain< SubFilter2_... > &other)
template<typename Vector_ >
void filter_cor (Vector_ &vector) const
Applies the filter onto a correction vector.
template<typename Vector_ >
void filter_def (Vector_ &vector) const
Applies the filter onto a defect vector.
template<typename Matrix_ >
void filter_mat (Matrix_ &matrix) const
Applies the filter onto a system matrix.
template<typename Vector_ >
void filter_rhs (Vector_ &vector) const
Applies the filter onto the right-hand-side vector.
template<typename Vector_ >
void filter_sol (Vector_ &vector) const
Applies the filter onto the solution vector.
FilterChain & operator= (FilterChain &&other)
move-assign operator
Static Public Attributes
static constexpr int num_blocks = FilterChain<Rest_...>::num_blocks + 1
number of vector blocks
Protected Member Functions
FilterChain (First_ &&the_first, RestClass &&the_rest)
data-emplacement ctor; this one is protected for a reason
Protected Attributes
First_ _first
the first sub-filter
RestClass _rest
all remaining sub-filters
Private Types
typedef FilterChain< Rest_... > RestClass
Detailed Description
template<typename First_, typename... Rest_>
class FEAT::LAFEM::FilterChain< First_, Rest_ >
Filter Chainclass template.
This class template implements a chain of filters which are successively applied onto a vector.
Template Parameters
First_,Rest_... The filters to be chained.
Author
Peter Zajac
Definition at line 29 of file filter_chain.hpp.
Member Typedef Documentation
DataType
template<typename First_ , typename... Rest_> typedef First_::DataType FEAT::LAFEM::FilterChain< First_, Rest_ >::DataType
sub-filter data-type
Definition at line 41 of file filter_chain.hpp.
FilterType
template<typename First_ , typename... Rest_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::FilterChain< First_, Rest_ >::FilterType = FilterChain< typename First_::template FilterType<DT2_, IT2_>, typename Rest_::template FilterType<DT2_, IT2_>...>
Our 'base' class type.
Definition at line 49 of file filter_chain.hpp.
FilterTypeByDI
template<typename First_ , typename... Rest_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::FilterChain< First_, Rest_ >::FilterTypeByDI = FilterType<DT2_, IT2_>
this typedef lets you create a matrix container with different Data and Index types
Definition at line 55 of file filter_chain.hpp.
IndexType
template<typename First_ , typename... Rest_> typedef First_::IndexType FEAT::LAFEM::FilterChain< First_, Rest_ >::IndexType
sub-filter index-type
Definition at line 43 of file filter_chain.hpp.
RestClass
template<typename First_ , typename... Rest_> typedef FilterChain<Rest_...> FEAT::LAFEM::FilterChain< First_, Rest_ >::RestClass private
Definition at line 34 of file filter_chain.hpp.
VectorType
template<typename First_ , typename... Rest_> typedef First_::VectorType FEAT::LAFEM::FilterChain< First_, Rest_ >::VectorType
Definition at line 45 of file filter_chain.hpp.
Constructor & Destructor Documentation
FilterChain() [1/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::FilterChain< First_, Rest_ >::FilterChain (First_ && the_first, RestClass && the_rest) inline explicit protected
data-emplacement ctor; this one is protected for a reason
Definition at line 70 of file filter_chain.hpp.
FilterChain() [2/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::FilterChain< First_, Rest_ >::FilterChain () inline
default ctor
Definition at line 78 of file filter_chain.hpp.
FilterChain() [3/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::FilterChain< First_, Rest_ >::FilterChain (First_ && the_first, Rest_ &&... the_rest) inline explicit
sub-filter emplacement ctor
Definition at line 83 of file filter_chain.hpp.
FilterChain() [4/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::FilterChain< First_, Rest_ >::FilterChain (FilterChain< First_, Rest_ > && other) inline
move-ctor
Definition at line 90 of file filter_chain.hpp.
Member Function Documentation
at() [1/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type & FEAT::LAFEM::FilterChain< First_, Rest_ >::at () inline
Definition at line 156 of file filter_chain.hpp.
at() [2/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type const & FEAT::LAFEM::FilterChain< First_, Rest_ >::at () const inline
Definition at line 164 of file filter_chain.hpp.
References FEAT::LAFEM::FilterChain< First_, Rest_ >::num_blocks.
bytes()
template<typename First_ , typename... Rest_> std::size_t FEAT::LAFEM::FilterChain< First_, Rest_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 128 of file filter_chain.hpp.
References FEAT::LAFEM::FilterChain< First_, Rest_ >::_first, FEAT::LAFEM::FilterChain< First_, Rest_ >::_rest, and FEAT::LAFEM::FilterChain< First_, Rest_ >::bytes().
Referenced by FEAT::Control::ScalarCombinedSystemLevel< DataType_, IndexType_, ScalarMatrix_ >::bytes(), and FEAT::LAFEM::FilterChain< First_, Rest_ >::bytes().
clone() [1/2]
template<typename First_ , typename... Rest_> FilterChain FEAT::LAFEM::FilterChain< First_, Rest_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Creates a clone of itself.
Definition at line 108 of file filter_chain.hpp.
References FEAT::LAFEM::FilterChain< First_, Rest_ >::_first, FEAT::LAFEM::FilterChain< First_, Rest_ >::_rest, and FEAT::LAFEM::FilterChain< First_, Rest_ >::clone().
Referenced by FEAT::LAFEM::FilterChain< First_, Rest_ >::clone().
clone() [2/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::FilterChain< First_, Rest_ >::clone (const FilterChain< First_, Rest_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clones data from another FilterChain.
Definition at line 114 of file filter_chain.hpp.
References FEAT::LAFEM::FilterChain< First_, Rest_ >::_first, FEAT::LAFEM::FilterChain< First_, Rest_ >::_rest, and FEAT::LAFEM::FilterChain< First_, Rest_ >::clone().
convert()
template<typename First_ , typename... Rest_> template<typename... SubFilter2_> void FEAT::LAFEM::FilterChain< First_, Rest_ >::convert (const FilterChain< SubFilter2_... > & other) inline
Definition at line 121 of file filter_chain.hpp.
filter_cor()
template<typename First_ , typename... Rest_> template<typename Vector_ > void FEAT::LAFEM::FilterChain< First_, Rest_ >::filter_cor (Vector_ & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 196 of file filter_chain.hpp.
filter_def()
template<typename First_ , typename... Rest_> template<typename Vector_ > void FEAT::LAFEM::FilterChain< First_, Rest_ >::filter_def (Vector_ & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 188 of file filter_chain.hpp.
filter_mat()
template<typename First_ , typename... Rest_> template<typename Matrix_ > void FEAT::LAFEM::FilterChain< First_, Rest_ >::filter_mat (Matrix_ & matrix) const inline
Applies the filter onto a system matrix.
Parameters
[in,out] matrix A reference to the matrix to be filtered.
Definition at line 204 of file filter_chain.hpp.
filter_rhs()
template<typename First_ , typename... Rest_> template<typename Vector_ > void FEAT::LAFEM::FilterChain< First_, Rest_ >::filter_rhs (Vector_ & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 172 of file filter_chain.hpp.
filter_sol()
template<typename First_ , typename... Rest_> template<typename Vector_ > void FEAT::LAFEM::FilterChain< First_, Rest_ >::filter_sol (Vector_ & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 180 of file filter_chain.hpp.
operator=()
template<typename First_ , typename... Rest_> FilterChain & FEAT::LAFEM::FilterChain< First_, Rest_ >::operator= (FilterChain< First_, Rest_ > && other) inline
move-assign operator
Definition at line 97 of file filter_chain.hpp.
References FEAT::LAFEM::FilterChain< First_, Rest_ >::_first, and FEAT::LAFEM::FilterChain< First_, Rest_ >::_rest.
Friends And Related Function Documentation
FilterChain
template<typename First_ , typename... Rest_> template<typename , typename... > friend class FilterChain friend
Definition at line 32 of file filter_chain.hpp.
Member Data Documentation
_first
template<typename First_ , typename... Rest_> First_ FEAT::LAFEM::FilterChain< First_, Rest_ >::_first protected
the first sub-filter
Definition at line 65 of file filter_chain.hpp.
Referenced by FEAT::LAFEM::FilterChain< First_, Rest_ >::bytes(), FEAT::LAFEM::FilterChain< First_, Rest_ >::clone(), and FEAT::LAFEM::FilterChain< First_, Rest_ >::operator=().
_rest
template<typename First_ , typename... Rest_> RestClass FEAT::LAFEM::FilterChain< First_, Rest_ >::_rest protected
all remaining sub-filters
Definition at line 67 of file filter_chain.hpp.
Referenced by FEAT::LAFEM::FilterChain< First_, Rest_ >::bytes(), FEAT::LAFEM::FilterChain< First_, Rest_ >::clone(), and FEAT::LAFEM::FilterChain< First_, Rest_ >::operator=().
num_blocks
template<typename First_ , typename... Rest_> constexpr int FEAT::LAFEM::FilterChain< First_, Rest_ >::num_blocks = FilterChain<Rest_...>::num_blocks + 1 static constexpr
number of vector blocks
Definition at line 38 of file filter_chain.hpp.
Referenced by FEAT::LAFEM::FilterChain< First_, Rest_ >::at().
The documentation for this class was generated from the following file:
kernel/lafem/filter_chain.hpp