FEAT: FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ > Class Template Reference
FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ > Class Template Reference
Mesh optimizer based on minimization of harmonic energy.
#include <dudv_functional.hpp>
Public Types
typedef MeshQualityFunctional< MeshType > BaseClass
Our base class.
template<typename DT2_ = DT_, typename IT2_ = IT_>
using ContainerType = DuDvFunctional< DT2_, IT2_, TrafoType_, MatrixType_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a matrix container with new Datatape and Index types
typedef BaseClass::CoordsBufferType CoordsBufferType
Type for exchanging information between state variable and mesh.
typedef MeshType::CoordType CoordType
The precision of the mesh coordinates.
typedef DT_ DataType
Our datatype.
typedef LAFEM::FilterSequence< DirichletFilterType > DirichletFilterSequence
Sequence of Dirichlet filters for several different boundary parts.
typedef LAFEM::UnitFilterBlocked< DT_, IT_, MeshType::world_dim > DirichletFilterType
Filter for Dirichlet boundary conditions.
typedef LAFEM::FilterChain< SlipFilterSequence, DirichletFilterSequence > FilterType
Combined filter.
typedef IT_ IndexType
Our index type.
typedef MatrixType_< DT_, IT_, MeshType::world_dim, MeshType::world_dim > MatrixType
Type for the system matrix.
typedef TrafoType::MeshType MeshType
The mesh the transformation is defined on.
typedef LAFEM::DenseVector< DT_, IT_ > ScalarVectorType
Type for i.e. cell vectors.
typedef MeshType::ShapeType ShapeType
The shape type of the mesh.
typedef LAFEM::FilterSequence< SlipFilterType > SlipFilterSequence
Sequence of Slip filters for several different boundary parts.
typedef LAFEM::SlipFilter< DT_, IT_, MeshType::world_dim > SlipFilterType
Filter for slip boundary conditions.
typedef Intern::TrafoFE< TrafoType >::Space SpaceType
Finite Element space for the transformation.
typedef TrafoType_ TrafoType
Type for the transformation.
typedef MatrixType::VectorTypeL VectorTypeL
Type for vectors from the dual space.
typedef MatrixType::VectorTypeR VectorTypeR
Type for vectors from the primal space.
Public Member Functions
DuDvFunctional (const DuDvFunctional &)=delete
Explicitly delete copy constructor.
DuDvFunctional (Geometry::RootMeshNode< MeshType > *rmn_, TrafoType &trafo, const std::deque< String > &dirichlet_list, const std::deque< String > &slip_list)
Constructor.
virtual ~DuDvFunctional ()
Virtual destructor.
virtual void add_to_vtk_exporter (Geometry::ExportVTK< MeshType > &exporter) const
Adds relevant quantities of this object to a VTK exporter.
virtual void add_to_vtk_exporter (Geometry::ExportVTK< MeshType > &exporter) const override
Adds relevant quantities of this object to a VTK exporter.
virtual void assemble_system_matrix ()
Assembles the system matrix.
virtual void buffer_to_mesh ()
Sets the coordinates in the underlying mesh to _coords_buffer.
virtual CoordType compute_cell_size_defect (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, CoordType &vol) const override
Computes a quality indicator concerning the cell sizes.
virtual CoordType compute_cell_size_defect_post_sync (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, const CoordType &vol) const
Computes a quality indicator concerning the cell sizes, pre synchronization phase.
void compute_cell_size_defect_pre_sync (CoordType &vol_min, CoordType &vol_max, CoordType &vol) const
Computes a quality indicator concerning the cell sizes, pre synchronization phase.
VectorTypeL create_vector_l () const
Creates an L-vector for the functional's gradient.
VectorTypeR create_vector_r () const
Creates an R-vector for the functional and its gradient.
bool empty () const
Checks if the functional is empty (= the null functional.
CoordsBufferType & get_coords ()
Gets the coords buffer.
const CoordsBufferType & get_coords () const
Gets the coords buffer.
MeshType * get_mesh ()
const MeshType * get_mesh () const
Geometry::RootMeshNode< MeshType > * get_mesh_node () const
Index get_num_func_evals () const
Index get_num_grad_evals () const
Index get_num_hess_evals () const
virtual void init () override
Performs one-time initializations.
virtual void mesh_to_buffer ()
Gets the coordinates from the underlying mesh and saves them in _coords_buffer.
virtual void prepare (VectorTypeR &vec_state, FilterType &filter)
Prepares the functional for evaluation.
void reset_num_evals ()
Resets all evaluation counts.
Static Public Member Functions
static String name ()
The class name.
Public Attributes
CoordsBufferType _coords_buffer
Coordinates, used for setting new boundary values etc.
Geometry::RootMeshNode< MeshType > * _mesh_node
The mesh for the underlying transformation.
MatrixType matrix_sys
The system matrix.
SpaceType trafo_space
The FE space for the transformation, needed for filtering.
Static Public Attributes
static constexpr int _local_degree = 4*SpaceType::local_degree + 1
Maximum polynomial degree.
static constexpr int BlockHeight = MatrixType::BlockHeight
Blockheight of the system matrix.
static constexpr int BlockWidth = MatrixType::BlockWidth
Blockwidth of the system matrix.
Protected Attributes
Cubature::DynamicFactory _cubature_factory
Cubature factory, for P1/Q1 transformations in 2d degree 5 is enough.
std::map< String, std::shared_ptr< Assembly::UnitFilterAssembler< MeshType > > > _dirichlet_asm
Assembler for Dirichlet boundary conditions.
ScalarVectorType _lambda
Vector saving the cell sizes on the reference mesh.
Index _num_func_evals
Counter for number of function evaluations.
Index _num_grad_evals
Counter for number of gradient evaluations.
Index _num_hess_evals
Counter for number of hessian evaluations.
std::map< String, std::shared_ptr< Assembly::SlipFilterAssembler< TrafoType > > > _slip_asm
Assembler for slip boundary conditions.
TrafoType & _trafo
The transformation defining the physical mesh.
Detailed Description
template<typename DT_, typename IT_, typename TrafoType_, template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR>
class FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >
Mesh optimizer based on minimization of harmonic energy.
Template Parameters
DT_ Data type for the solver (not the mesh)
IT_ Index type for the solver (not the mesh)
TrafoType_ Type of the underlying transformation.
Author
Jordi Paul
Definition at line 51 of file dudv_functional.hpp.
Member Typedef Documentation
BaseClass
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef MeshQualityFunctional<MeshType> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::BaseClass
Our base class.
Definition at line 82 of file dudv_functional.hpp.
ContainerType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::ContainerType = DuDvFunctional<DT2_, IT2_, TrafoType_, MatrixType_>
Our 'base' class type.
Definition at line 75 of file dudv_functional.hpp.
ContainerTypeByDI
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> template<typename DataType2_ , typename IndexType2_ > using FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a matrix container with new Datatape and Index types
Definition at line 79 of file dudv_functional.hpp.
CoordsBufferType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef BaseClass::CoordsBufferType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::CoordsBufferType
Type for exchanging information between state variable and mesh.
Definition at line 84 of file dudv_functional.hpp.
CoordType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef MeshType::CoordType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::CoordType
The precision of the mesh coordinates.
Definition at line 87 of file dudv_functional.hpp.
DataType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef DT_ FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DataType
Our datatype.
Definition at line 56 of file dudv_functional.hpp.
DirichletFilterSequence
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef LAFEM::FilterSequence<DirichletFilterType> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DirichletFilterSequence
Sequence of Dirichlet filters for several different boundary parts.
Definition at line 102 of file dudv_functional.hpp.
DirichletFilterType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef LAFEM::UnitFilterBlocked<DT_, IT_, MeshType::world_dim> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DirichletFilterType
Filter for Dirichlet boundary conditions.
Definition at line 100 of file dudv_functional.hpp.
FilterType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef LAFEM::FilterChain<SlipFilterSequence, DirichletFilterSequence> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::FilterType
Combined filter.
Definition at line 108 of file dudv_functional.hpp.
IndexType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef IT_ FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::IndexType
Our index type.
Definition at line 58 of file dudv_functional.hpp.
MatrixType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef MatrixType_<DT_, IT_, MeshType::world_dim, MeshType::world_dim> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::MatrixType
Type for the system matrix.
Definition at line 67 of file dudv_functional.hpp.
MeshType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef TrafoType::MeshType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::MeshType
The mesh the transformation is defined on.
Definition at line 62 of file dudv_functional.hpp.
ScalarVectorType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef LAFEM::DenseVector<DT_, IT_> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::ScalarVectorType
Type for i.e. cell vectors.
Definition at line 97 of file dudv_functional.hpp.
ShapeType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef MeshType::ShapeType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::ShapeType
The shape type of the mesh.
Definition at line 64 of file dudv_functional.hpp.
SlipFilterSequence
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef LAFEM::FilterSequence<SlipFilterType> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::SlipFilterSequence
Sequence of Slip filters for several different boundary parts.
Definition at line 106 of file dudv_functional.hpp.
SlipFilterType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef LAFEM::SlipFilter<DT_, IT_, MeshType::world_dim> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::SlipFilterType
Filter for slip boundary conditions.
Definition at line 104 of file dudv_functional.hpp.
SpaceType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef Intern::TrafoFE<TrafoType>::Space FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::SpaceType
Finite Element space for the transformation.
Definition at line 111 of file dudv_functional.hpp.
TrafoType
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef TrafoType_ FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::TrafoType
Type for the transformation.
Definition at line 60 of file dudv_functional.hpp.
VectorTypeL
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef MatrixType::VectorTypeL FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::VectorTypeL
Type for vectors from the dual space.
Definition at line 93 of file dudv_functional.hpp.
VectorTypeR
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> typedef MatrixType::VectorTypeR FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::VectorTypeR
Type for vectors from the primal space.
Definition at line 95 of file dudv_functional.hpp.
Constructor & Destructor Documentation
DuDvFunctional()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DuDvFunctional (Geometry::RootMeshNode< MeshType > * rmn_, TrafoType & trafo, const std::deque< String > & dirichlet_list, const std::deque< String > & slip_list) inline explicit
Constructor.
Parameters
[in] rmn_ The RootMeshNode representing the tree of root mesh, all of its MeshParts and Charts.
[in] trafo The transformation on the root mesh node.
[in] dirichlet_list The list of dirichlet boundaries.
[in] slip_list The list of slip boundaries.
Definition at line 153 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_dirichlet_asm, FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_slip_asm, FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_trafo, FEAT::Assembly::SymbolicAssembler::assemble_matrix_std1(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::find_mesh_part(), FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::matrix_sys, and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::trafo_space.
~DuDvFunctional()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> virtual FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::~DuDvFunctional () inline virtual
Virtual destructor.
Definition at line 216 of file dudv_functional.hpp.
Member Function Documentation
add_to_vtk_exporter() [1/2]
virtual void FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::add_to_vtk_exporter (Geometry::ExportVTK< MeshType > & exporter) const inline virtual inherited
Adds relevant quantities of this object to a VTK exporter.
Parameters
[in,out] exporter The exporter to add our data to.
Definition at line 123 of file mesh_quality_functional.hpp.
add_to_vtk_exporter() [2/2]
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> virtual void FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::add_to_vtk_exporter (Geometry::ExportVTK< MeshType > & exporter) const inline override virtual
Adds relevant quantities of this object to a VTK exporter.
Parameters
[in,out] exporter The exporter to add our data to.
Definition at line 245 of file dudv_functional.hpp.
References FEAT::Geometry::ExportVTK< Mesh_ >::add_cell_scalar(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::elements().
assemble_system_matrix()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> virtual void FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::assemble_system_matrix () inline virtual
Assembles the system matrix.
Definition at line 253 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_cubature_factory, FEAT::Assembly::BilinearOperatorAssembler::assemble_matrix1(), FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::matrix_sys, and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::trafo_space.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::init().
buffer_to_mesh()
virtual void FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::buffer_to_mesh () inline virtual inherited
Sets the coordinates in the underlying mesh to _coords_buffer.
Definition at line 157 of file mesh_quality_functional.hpp.
compute_cell_size_defect()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> virtual CoordType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::compute_cell_size_defect (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, CoordType & vol) const inline override virtual
Computes a quality indicator concerning the cell sizes.
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
In a truly optimal mesh (consisting ONLY of reference cells of the right size), every cell's volume is exactly lambda(cell). This is especially the goal for r-adaptivity. So in an optimal mesh,
\[ \forall K \in \mathcal{T}_h: |K|/|\Omega| = \lambda(K) \]
so we compute the 1-norm of the vector \((v)_i = \left| \frac{|K_i|}{\sum_j |K_j|} - \lambda(K_i) \right| \).
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function has a pre_sync and post_sync part.
See also
Control::DuDvFunctionalControl::compute_cell_size_defect()
Implements FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >.
Definition at line 357 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::compute_cell_size_defect_post_sync(), and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::compute_cell_size_defect_pre_sync().
compute_cell_size_defect_post_sync()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> virtual CoordType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::compute_cell_size_defect_post_sync (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, const CoordType & vol) const inline virtual
Computes a quality indicator concerning the cell sizes, pre synchronization phase.
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function has a pre_sync and post_sync part.
See also
Control::DuDvFunctionalControl::compute_cell_size_defect()
Definition at line 429 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_lambda, FEAT::Math::abs(), FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_mesh(), FEAT::Math::max(), and FEAT::Math::min().
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::compute_cell_size_defect().
compute_cell_size_defect_pre_sync()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> void FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::compute_cell_size_defect_pre_sync (CoordType & vol_min, CoordType & vol_max, CoordType & vol) const inline
Computes a quality indicator concerning the cell sizes, pre synchronization phase.
Parameters
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function has a pre_sync and post_sync part.
See also
Control::DuDvFunctionalControl::compute_cell_size_defect()
Definition at line 386 of file dudv_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_mesh(), FEAT::Math::max(), and FEAT::Math::min().
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::compute_cell_size_defect().
create_vector_l()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> VectorTypeL FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::create_vector_l () const inline
Creates an L-vector for the functional's gradient.
Definition at line 461 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::trafo_space.
create_vector_r()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> VectorTypeR FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::create_vector_r () const inline
Creates an R-vector for the functional and its gradient.
Definition at line 469 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::trafo_space.
empty()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> bool FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::empty () const inline
Checks if the functional is empty (= the null functional.
Returns
True if the number of DoFs is zero.)
Definition at line 453 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::matrix_sys.
get_coords() [1/2]
CoordsBufferType & FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_coords () inline inherited
Gets the coords buffer.
Returns
A reference to the coords buffer for manipulation.
Definition at line 170 of file mesh_quality_functional.hpp.
get_coords() [2/2]
const CoordsBufferType & FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_coords () const inline inherited
Gets the coords buffer.
Returns
A const reference to the coords buffer for manipulation.
Definition at line 180 of file mesh_quality_functional.hpp.
get_mesh() [1/2]
MeshType * FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_mesh () inline inherited
Returns
The root mesh
Definition at line 128 of file mesh_quality_functional.hpp.
get_mesh() [2/2]
const MeshType * FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_mesh () const inline inherited
Returns
The root mesh as const pointer
Definition at line 135 of file mesh_quality_functional.hpp.
get_mesh_node()
Geometry::RootMeshNode< MeshType > * FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_mesh_node () const inline inherited
Returns
The root mesh node
Definition at line 142 of file mesh_quality_functional.hpp.
get_num_func_evals()
Index FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_num_func_evals () const inline inherited
Returns
The number of times the functional value was computed.
Definition at line 188 of file mesh_quality_functional.hpp.
get_num_grad_evals()
Index FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_num_grad_evals () const inline inherited
Returns
The number of times the gradient was computed.
Definition at line 196 of file mesh_quality_functional.hpp.
get_num_hess_evals()
Index FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_num_hess_evals () const inline inherited
Returns
The number of times the hessian was computed.
Definition at line 204 of file mesh_quality_functional.hpp.
init()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> virtual void FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::init () inline override virtual
Performs one-time initializations.
This is not done in the constructor for the case that the system matrix gets overwritten by a derived class, so the unused system matrix of THIS class is not assembled symbolically
Implements FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >.
Definition at line 226 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::assemble_system_matrix().
mesh_to_buffer()
virtual void FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::mesh_to_buffer () inline virtual inherited
Gets the coordinates from the underlying mesh and saves them in _coords_buffer.
Definition at line 148 of file mesh_quality_functional.hpp.
name()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> static String FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::name () inline static
The class name.
Returns
String with the class name
Definition at line 233 of file dudv_functional.hpp.
prepare()
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> virtual void FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::prepare (VectorTypeR & vec_state, FilterType & filter) inline virtual
Prepares the functional for evaluation.
Parameters
[in,out] vec_state The state vector. This is not const because it might be filtered using a slip filter.
[in,out] filter The filter. This is not const because the slip filter might need to be reassembled.
Needs to be called whenever any data like the mesh etc. changed.
Definition at line 280 of file dudv_functional.hpp.
References FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_dirichlet_asm, FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_lambda, FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::_mesh_node, FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_slip_asm, FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_trafo, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::adapt_by_name(), FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::get_mesh(), FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::trafo_space, and XABORTM.
reset_num_evals()
void FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::reset_num_evals () inline inherited
Resets all evaluation counts.
Definition at line 212 of file mesh_quality_functional.hpp.
Member Data Documentation
_coords_buffer
CoordsBufferType FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::_coords_buffer inherited
Coordinates, used for setting new boundary values etc.
Definition at line 52 of file mesh_quality_functional.hpp.
_cubature_factory
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> Cubature::DynamicFactory FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_cubature_factory protected
Cubature factory, for P1/Q1 transformations in 2d degree 5 is enough.
Definition at line 130 of file dudv_functional.hpp.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::assemble_system_matrix().
_dirichlet_asm
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> std::map<String, std::shared_ptr<Assembly::UnitFilterAssembler<MeshType> > > FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_dirichlet_asm protected
Assembler for Dirichlet boundary conditions.
Definition at line 126 of file dudv_functional.hpp.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DuDvFunctional(), and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::prepare().
_lambda
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> ScalarVectorType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_lambda protected
Vector saving the cell sizes on the reference mesh.
Definition at line 124 of file dudv_functional.hpp.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::compute_cell_size_defect_post_sync(), and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::prepare().
_local_degree
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> constexpr int FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_local_degree = 4*SpaceType::local_degree + 1 static constexpr
Maximum polynomial degree.
Definition at line 115 of file dudv_functional.hpp.
_mesh_node
Geometry::RootMeshNode<MeshType>* FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::_mesh_node inherited
The mesh for the underlying transformation.
Definition at line 50 of file mesh_quality_functional.hpp.
_num_func_evals
Index FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::_num_func_evals protected inherited
Counter for number of function evaluations.
Definition at line 56 of file mesh_quality_functional.hpp.
_num_grad_evals
Index FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::_num_grad_evals protected inherited
Counter for number of gradient evaluations.
Definition at line 58 of file mesh_quality_functional.hpp.
_num_hess_evals
Index FEAT::Meshopt::MeshQualityFunctional< TrafoType_::MeshType >::_num_hess_evals protected inherited
Counter for number of hessian evaluations.
Definition at line 60 of file mesh_quality_functional.hpp.
_slip_asm
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> std::map<String, std::shared_ptr<Assembly::SlipFilterAssembler<TrafoType> > > FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_slip_asm protected
Assembler for slip boundary conditions.
Definition at line 128 of file dudv_functional.hpp.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DuDvFunctional(), and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::prepare().
_trafo
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> TrafoType& FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::_trafo protected
The transformation defining the physical mesh.
Definition at line 122 of file dudv_functional.hpp.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DuDvFunctional(), and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::prepare().
BlockHeight
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> constexpr int FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::BlockHeight = MatrixType::BlockHeight static constexpr
Blockheight of the system matrix.
Definition at line 69 of file dudv_functional.hpp.
BlockWidth
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> constexpr int FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::BlockWidth = MatrixType::BlockWidth static constexpr
Blockwidth of the system matrix.
Definition at line 71 of file dudv_functional.hpp.
matrix_sys
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> MatrixType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::matrix_sys
The system matrix.
Definition at line 118 of file dudv_functional.hpp.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DuDvFunctional(), FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::assemble_system_matrix(), and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::empty().
trafo_space
template<typename DT_ , typename IT_ , typename TrafoType_ , template< typename, typename, int, int > class MatrixType_ = LAFEM::SparseMatrixBCSR> SpaceType FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::trafo_space
The FE space for the transformation, needed for filtering.
Definition at line 134 of file dudv_functional.hpp.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::DuDvFunctional(), FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::assemble_system_matrix(), FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::create_vector_l(), FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::create_vector_r(), and FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::prepare().
The documentation for this class was generated from the following file:
kernel/meshopt/dudv_functional.hpp