FEAT: FEAT::MemoryPool Class Reference
FEAT::MemoryPool Class Reference
Memory management.
#include <memory_pool.hpp>
Static Public Member Functions
template<typename DT_ >
static DT_ * allocate_memory (Index count)
allocate new memory
static Index allocated_memory ()
static Index allocated_size (void *address)
template<typename DT1_ , typename DT2_ >
static void convert (DT1_ *dest, const DT2_ *src, const Index count)
Convert datatype DT2_ from src into DT1_ in dest.
template<typename DT_ >
static void convert (DT_ *dest, const DT_ *src, const Index count)
Copy memory area from src to dest.
template<typename DT_ >
static void copy (DT_ *dest, const DT_ *src, const Index count)
Copy memory area from src to dest.
template<typename DT_ >
static void download (DT_ *dest, const DT_ *const src, const Index count)
download memory chunk to host memory
static void finalize ()
Shutdown memory pool and clean up allocated memory pools.
template<typename DT_ >
static const DT_ & get_element (const DT_ *data, const Index index)
receive element
static void increase_memory (void *address)
increase memory counter
static void initialize ()
Setup memory pools.
static void release_memory (void *address)
release memory or decrease reference counter
template<typename DT_ >
static void set_memory (DT_ *address, const DT_ val, const Index count=1)
set memory to specific value
static NOINLINE void synchronize ()
template<typename DT_ >
static void upload (DT_ *dest, const DT_ *const src, const Index count)
upload memory chunk from host memory to device memory
Static Private Attributes
static std::map< void *, Util::Intern::MemoryInfo > _pool
Map of all memory chunks in use.
Detailed Description
Memory management.
This class manages the used memory chunks and releases them, if necessary.
Author
Dirk Ribbrock
Definition at line 53 of file memory_pool.hpp.
Member Function Documentation
allocate_memory()
template<typename DT_ > static DT_ * FEAT::MemoryPool::allocate_memory (Index count) inline static
allocate new memory
Definition at line 82 of file memory_pool.hpp.
References _pool, and XABORTM.
allocated_memory()
static Index FEAT::MemoryPool::allocated_memory () inline static
Definition at line 264 of file memory_pool.hpp.
allocated_size()
static Index FEAT::MemoryPool::allocated_size (void * address) inline static
Definition at line 274 of file memory_pool.hpp.
convert() [1/2]
template<typename DT1_ , typename DT2_ > static void FEAT::MemoryPool::convert (DT1_ * dest, const DT2_ * src, const Index count) inline static
Convert datatype DT2_ from src into DT1_ in dest.
Definition at line 235 of file memory_pool.hpp.
References FEAT::cuda, FEAT::generic, and FEAT::Backend::get_preferred_backend().
convert() [2/2]
template<typename DT_ > static void FEAT::MemoryPool::convert (DT_ * dest, const DT_ * src, const Index count) inline static
Copy memory area from src to dest.
Definition at line 225 of file memory_pool.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::assign().
copy()
template<typename DT_ > static void FEAT::MemoryPool::copy (DT_ * dest, const DT_ * src, const Index count) inline static
Copy memory area from src to dest.
Definition at line 204 of file memory_pool.hpp.
References FEAT::cuda, FEAT::generic, and FEAT::Backend::get_preferred_backend().
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::DenseVector< DT_, IT_ >::max_abs_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::max_abs_element(), FEAT::LAFEM::DenseVector< DT_, IT_ >::max_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::max_element(), FEAT::LAFEM::DenseVector< DT_, IT_ >::min_abs_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::min_abs_element(), FEAT::LAFEM::DenseVector< DT_, IT_ >::min_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::min_element(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
download()
template<typename DT_ > static void FEAT::MemoryPool::download (DT_ * dest, const DT_ *const src, const Index count) inline static
download memory chunk to host memory
Definition at line 154 of file memory_pool.hpp.
finalize()
static void FEAT::MemoryPool::finalize () inline static
Shutdown memory pool and clean up allocated memory pools.
Definition at line 67 of file memory_pool.hpp.
References _pool.
Referenced by FEAT::Runtime::finalize().
get_element()
template<typename DT_ > static const DT_ & FEAT::MemoryPool::get_element (const DT_ * data, const Index index) inline static
receive element
Definition at line 176 of file memory_pool.hpp.
increase_memory()
static void FEAT::MemoryPool::increase_memory (void * address) inline static
increase memory counter
Definition at line 109 of file memory_pool.hpp.
References _pool, XABORTM, and XASSERT.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=().
initialize()
static void FEAT::MemoryPool::initialize () inline static
Setup memory pools.
Definition at line 62 of file memory_pool.hpp.
Referenced by FEAT::Runtime::initialize().
release_memory()
static void FEAT::MemoryPool::release_memory (void * address) inline static
release memory or decrease reference counter
Definition at line 124 of file memory_pool.hpp.
References _pool, and XABORTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::SparseLayout< IT_, Layout_ >::~SparseLayout(), FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::move(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::write_out().
set_memory()
template<typename DT_ > static void FEAT::MemoryPool::set_memory (DT_ * address, const DT_ val, const Index count = 1) inline static
set memory to specific value
Definition at line 183 of file memory_pool.hpp.
References FEAT::cuda, FEAT::generic, and FEAT::Backend::get_preferred_backend().
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), and FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()().
synchronize()
static NOINLINE void FEAT::MemoryPool::synchronize () inline static
Definition at line 255 of file memory_pool.hpp.
upload()
template<typename DT_ > static void FEAT::MemoryPool::upload (DT_ * dest, const DT_ *const src, const Index count) inline static
upload memory chunk from host memory to device memory
Definition at line 165 of file memory_pool.hpp.
Member Data Documentation
_pool
std::map< void *, FEAT::Util::Intern::MemoryInfo > FEAT::MemoryPool::_pool static private
Map of all memory chunks in use.
Definition at line 57 of file memory_pool.hpp.
Referenced by allocate_memory(), finalize(), increase_memory(), and release_memory().
The documentation for this class was generated from the following files:
kernel/util/memory_pool.hpp
kernel/util/memory_pool.cpp