FEAT: FEAT::Global::SynchScalarTicket< DT_ > Class Template Reference
FEAT::Global::SynchScalarTicket< DT_ > Class Template Reference
Ticket class for asynchronous global operations on scalars.
#include <synch_scal.hpp>
Public Member Functions
SynchScalarTicket ()
standard constructor
SynchScalarTicket (const SynchScalarTicket &)=delete
Unwanted copy constructor: Do not implement!
SynchScalarTicket (DT_ x, const Dist::Comm &comm, const Dist::Operation &op, bool sqrt=false)
Constructor.
SynchScalarTicket (SynchScalarTicket &&other)
move constructor
~SynchScalarTicket ()
Destructor.
SynchScalarTicket & operator= (const SynchScalarTicket &)=delete
Unwanted copy assignment operator: Do not implement!
SynchScalarTicket & operator= (SynchScalarTicket &&other)
move-assign operator
DT_ wait ()
wait method
Protected Attributes
bool _finished
signals, whether wait was already called
double _mpi_exec
holds our mpi execution toe
double _mpi_wait
holds our mpi reduction wait toe
DT_ _r
buffer containing the received data
Dist::Request _req
Our request for the corresponding iallreduce mpi call.
bool _sqrt
should we compute the sqrt of the result
DT_ _x
buffer containing the send data
Detailed Description
template<typename DT_>
class FEAT::Global::SynchScalarTicket< DT_ >
Ticket class for asynchronous global operations on scalars.
Internally a cpp thread is used to process the mpi call and ensure proper processing by calling MPI_Wait ahead of the actual tickets wait call.
Author
Dirk Ribbrock, Peter Zajac
Definition at line 32 of file synch_scal.hpp.
Constructor & Destructor Documentation
SynchScalarTicket() [1/3]
template<typename DT_ > FEAT::Global::SynchScalarTicket< DT_ >::SynchScalarTicket () inline
standard constructor
Definition at line 65 of file synch_scal.hpp.
SynchScalarTicket() [2/3]
template<typename DT_ > FEAT::Global::SynchScalarTicket< DT_ >::SynchScalarTicket (DT_ x, const Dist::Comm & comm, const Dist::Operation & op, bool sqrt = false) inline explicit
Constructor.
Parameters
[in] x The value to be synchronized.
[in] comm The communicator to be used for synchronization.
[in] op The reduction operation to be applied.
[in] sqrt Specifies whether to apply the square-root onto the reduction result.
Definition at line 101 of file synch_scal.hpp.
References FEAT::Global::SynchScalarTicket< DT_ >::_r, FEAT::Global::SynchScalarTicket< DT_ >::_req, FEAT::Global::SynchScalarTicket< DT_ >::_x, FEAT::TimeStamp::elapsed_now(), and FEAT::Dist::Comm::iallreduce().
SynchScalarTicket() [3/3]
template<typename DT_ > FEAT::Global::SynchScalarTicket< DT_ >::SynchScalarTicket (SynchScalarTicket< DT_ > && other) inline
move constructor
Definition at line 141 of file synch_scal.hpp.
~SynchScalarTicket()
template<typename DT_ > FEAT::Global::SynchScalarTicket< DT_ >::~SynchScalarTicket () inline
Destructor.
Definition at line 216 of file synch_scal.hpp.
References FEAT::Global::SynchScalarTicket< DT_ >::_finished, and XASSERT.
Member Function Documentation
operator=()
template<typename DT_ > SynchScalarTicket & FEAT::Global::SynchScalarTicket< DT_ >::operator= (SynchScalarTicket< DT_ > && other) inline
move-assign operator
Definition at line 163 of file synch_scal.hpp.
References FEAT::Global::SynchScalarTicket< DT_ >::_finished, FEAT::Global::SynchScalarTicket< DT_ >::_mpi_exec, FEAT::Global::SynchScalarTicket< DT_ >::_mpi_wait, FEAT::Global::SynchScalarTicket< DT_ >::_r, FEAT::Global::SynchScalarTicket< DT_ >::_req, FEAT::Global::SynchScalarTicket< DT_ >::_sqrt, and FEAT::Global::SynchScalarTicket< DT_ >::_x.
wait()
template<typename DT_ > DT_ FEAT::Global::SynchScalarTicket< DT_ >::wait () inline
wait method
wait for completion barrier
Returns
the accumulated data
Definition at line 196 of file synch_scal.hpp.
References FEAT::Global::SynchScalarTicket< DT_ >::_finished, FEAT::Global::SynchScalarTicket< DT_ >::_mpi_exec, FEAT::Global::SynchScalarTicket< DT_ >::_mpi_wait, FEAT::Global::SynchScalarTicket< DT_ >::_r, FEAT::Global::SynchScalarTicket< DT_ >::_req, FEAT::Global::SynchScalarTicket< DT_ >::_sqrt, FEAT::TimeStamp::elapsed_now(), FEAT::Math::sqrt(), FEAT::Dist::Request::wait(), and XASSERTM.
Referenced by FEAT::Global::Gate< LocalVector_, Mirror_ >::max(), FEAT::Global::Gate< LocalVector_, Mirror_ >::min(), FEAT::Global::Gate< LocalVector_, Mirror_ >::norm2(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sum().
Member Data Documentation
_finished
template<typename DT_ > bool FEAT::Global::SynchScalarTicket< DT_ >::_finished protected
signals, whether wait was already called
Definition at line 61 of file synch_scal.hpp.
Referenced by FEAT::Global::SynchScalarTicket< DT_ >::~SynchScalarTicket(), FEAT::Global::SynchScalarTicket< DT_ >::operator=(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
_mpi_exec
template<typename DT_ > double FEAT::Global::SynchScalarTicket< DT_ >::_mpi_exec protected
holds our mpi execution toe
Definition at line 42 of file synch_scal.hpp.
Referenced by FEAT::Global::SynchScalarTicket< DT_ >::operator=(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
_mpi_wait
template<typename DT_ > double FEAT::Global::SynchScalarTicket< DT_ >::_mpi_wait protected
holds our mpi reduction wait toe
Definition at line 44 of file synch_scal.hpp.
Referenced by FEAT::Global::SynchScalarTicket< DT_ >::operator=(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
_r
template<typename DT_ > DT_ FEAT::Global::SynchScalarTicket< DT_ >::_r protected
buffer containing the received data
Definition at line 36 of file synch_scal.hpp.
Referenced by FEAT::Global::SynchScalarTicket< DT_ >::SynchScalarTicket(), FEAT::Global::SynchScalarTicket< DT_ >::operator=(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
_req
template<typename DT_ > Dist::Request FEAT::Global::SynchScalarTicket< DT_ >::_req protected
Our request for the corresponding iallreduce mpi call.
Definition at line 57 of file synch_scal.hpp.
Referenced by FEAT::Global::SynchScalarTicket< DT_ >::SynchScalarTicket(), FEAT::Global::SynchScalarTicket< DT_ >::operator=(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
_sqrt
template<typename DT_ > bool FEAT::Global::SynchScalarTicket< DT_ >::_sqrt protected
should we compute the sqrt of the result
Definition at line 40 of file synch_scal.hpp.
Referenced by FEAT::Global::SynchScalarTicket< DT_ >::operator=(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
_x
template<typename DT_ > DT_ FEAT::Global::SynchScalarTicket< DT_ >::_x protected
buffer containing the send data
Definition at line 38 of file synch_scal.hpp.
Referenced by FEAT::Global::SynchScalarTicket< DT_ >::SynchScalarTicket(), and FEAT::Global::SynchScalarTicket< DT_ >::operator=().
The documentation for this class was generated from the following file:
kernel/global/synch_scal.hpp