FEAT: FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ > Class Template Reference
FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ > Class Template Reference
Default elemental distance concentration function.
#include <mesh_concentration_function.hpp>
Public Types
typedef DT_ DataType
Floating point precision.
Public Member Functions
ConcentrationFunctionPowOfDist (DataType minval_, DataType exponent_, bool use_derivative_=true)
Constructor setting alpha, beta and use_derivative.
virtual ~ConcentrationFunctionPowOfDist ()
Empty destructor.
DataType conc_der (DataType dist) const
Computes the concentration according to a distance.
DataType conc_val (DataType dist) const
Computes the concentration according to a distance.
virtual String info () const
Prints relevant information.
Static Public Member Functions
static String name ()
Returns a descriptive String.
Public Attributes
const bool use_derivative
Does this utilize the derivative of the input wrt. some other DoF?
Private Attributes
const DataType _exponent
beta
const DataType _minval
alpha
Detailed Description
template<typename DT_>
class FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >
Default elemental distance concentration function.
Template Parameters
DT_ Floating point precision
This maps a signed distance to a concentration according to
\[ c(d) = (\alpha + |d|)^\beta, \alpha \geq 0. \]
Definition at line 1728 of file mesh_concentration_function.hpp.
Member Typedef Documentation
DataType
template<typename DT_ > typedef DT_ FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::DataType
Floating point precision.
Definition at line 1732 of file mesh_concentration_function.hpp.
Constructor & Destructor Documentation
ConcentrationFunctionPowOfDist()
template<typename DT_ > FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::ConcentrationFunctionPowOfDist (DataType minval_, DataType exponent_, bool use_derivative_ = true) inline explicit
Constructor setting alpha, beta and use_derivative.
Parameters
[in] minval_ alpha
[in] exponent_ beta
[in] use_derivative_ Whether to the derivative.
Definition at line 1756 of file mesh_concentration_function.hpp.
~ConcentrationFunctionPowOfDist()
template<typename DT_ > virtual FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::~ConcentrationFunctionPowOfDist () inline virtual
Empty destructor.
Definition at line 1774 of file mesh_concentration_function.hpp.
Member Function Documentation
conc_der()
template<typename DT_ > DataType FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::conc_der (DataType dist) const inline
Computes the concentration according to a distance.
Parameters
[in] dist The input parameter
Returns
\(c'(d) = \beta (\alpha |d|)^{(\beta-1)} * sign(d) \)
Definition at line 1826 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::_exponent, FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::_minval, FEAT::Math::abs(), FEAT::Math::pow(), and FEAT::Math::signum().
conc_val()
template<typename DT_ > DataType FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::conc_val (DataType dist) const inline
Computes the concentration according to a distance.
Parameters
[in] dist The input parameter
Returns
\(c(d) = (\alpha |d|)^\beta \)
Definition at line 1813 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::_exponent, FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::_minval, FEAT::Math::abs(), and FEAT::Math::pow().
info()
template<typename DT_ > virtual String FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::info () const inline virtual
Prints relevant information.
Definition at line 1791 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::_exponent, FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::_minval, FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::name(), FEAT::String::pad_back(), FEAT::stringify(), FEAT::stringify_fp_sci(), and FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::use_derivative.
name()
template<typename DT_ > static String FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::name () inline static
Returns a descriptive String.
Returns
The class name as String.
Definition at line 1783 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::info().
Member Data Documentation
_exponent
template<typename DT_ > const DataType FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::_exponent private
beta
Definition at line 1740 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::conc_der(), FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::conc_val(), and FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::info().
_minval
template<typename DT_ > const DataType FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::_minval private
alpha
Definition at line 1738 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::conc_der(), FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::conc_val(), and FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::info().
use_derivative
template<typename DT_ > const bool FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::use_derivative
Does this utilize the derivative of the input wrt. some other DoF?
Definition at line 1734 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::info().
The documentation for this class was generated from the following file:
kernel/meshopt/mesh_concentration_function.hpp