FEAT: FEAT::LAFEM::SerialConfig Class Reference
FEAT::LAFEM::SerialConfig Class Reference
Config class for serialize parameter.
#include <container.hpp>
Public Member Functions
SerialConfig ()
Default Constructor.
SerialConfig (bool zlib_compression, bool zfp_compression, FEAT::Real tol=FEAT::Real(-1.))
Constructor.
CompressionModes get_elements_compression () const
method for getting elements_compression
CompressionModes get_indices_compression () const
method for getting indices_compression
FEAT::Real get_tolerance () const
method for getting tolerance
void set_elements_compression (CompressionModes comp)
method for setting elements_compression
void set_indices_compression (CompressionModes comp)
method for setting indices_compression
void set_tolerance (FEAT::Real tol)
method for setting tolerance
Private Attributes
CompressionModes elements_compression
CompressionModes indices_compression
FEAT::Real tolerance
Detailed Description
Config class for serialize parameter.
Data survey: elements_compression LAFEM::SerializeMode, The compression mode for the elements array. Refer to CompressionModes for details. indices_compression LAFEM::SerializeMode, The compression mode for the indices array tolerance FEAT::Real, The max error that should be occur while compressing with zfp.
Note
tolerance should be unset(meaning -1.) if elements_compression != CompressionModes::elements_zfp and strictly greater 0 if elements_compression == CompressionModes::elements_zfp.
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Definition at line 48 of file container.hpp.
Constructor & Destructor Documentation
SerialConfig() [1/2]
FEAT::LAFEM::SerialConfig::SerialConfig () inline explicit
Default Constructor.
Sets default values for compression, depending whether zlib is loaded or not
Definition at line 65 of file container.hpp.
SerialConfig() [2/2]
FEAT::LAFEM::SerialConfig::SerialConfig (bool zlib_compression, bool zfp_compression, FEAT::Real tol = FEAT::Real(-1.)) inline explicit
Constructor.
Parameters
[in] zlib_compression bool, if true zlib will be used to compress indice arrays and if zfp is not loaded, will also be used to compress element arrays.
[in] zfp_compression bool, if true zfp will be used to compress element arrays.
[in] tolerance FEAT::Real, the maximum error done compressing with zfp. If zfp is enabled, has to be greater 0.
Warning
if zfp_compression is true and tolerance <= 0, an error will be raised.
Set values depending on the configuration of the user
Definition at line 84 of file container.hpp.
References FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, set_elements_compression(), set_indices_compression(), and set_tolerance().
Member Function Documentation
get_elements_compression()
CompressionModes FEAT::LAFEM::SerialConfig::get_elements_compression () const inline
method for getting elements_compression
Returns
CompressionModes, The compression mode for elements.
Definition at line 176 of file container.hpp.
get_indices_compression()
CompressionModes FEAT::LAFEM::SerialConfig::get_indices_compression () const inline
method for getting indices_compression
Returns
CompressionModes, The compression mode for indices.
Definition at line 187 of file container.hpp.
get_tolerance()
FEAT::Real FEAT::LAFEM::SerialConfig::get_tolerance () const inline
method for getting tolerance
Returns
FEAT::Real, the maximum error to be made by zfp compression. If zfp is enabled this has to be greater 0.
Definition at line 198 of file container.hpp.
set_elements_compression()
void FEAT::LAFEM::SerialConfig::set_elements_compression (CompressionModes comp) inline
method for setting elements_compression
Parameters
[in] comp CompressionModes, describing the compression mode for _elements. See CompressionModes for details.
Definition at line 106 of file container.hpp.
References FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, XABORTM, and XASSERTM.
Referenced by SerialConfig().
set_indices_compression()
void FEAT::LAFEM::SerialConfig::set_indices_compression (CompressionModes comp) inline
method for setting indices_compression
Parameters
[in] comp CompressionModes, describing the compression mode for _indices. See CompressionModes for details.
Definition at line 137 of file container.hpp.
References FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XABORTM.
Referenced by SerialConfig().
set_tolerance()
void FEAT::LAFEM::SerialConfig::set_tolerance (FEAT::Real tol) inline
method for setting tolerance
Parameters
[in] tol FEAT::Real, the maximum error to be made by zfp compression. If zfp is enabled this has to be greater 0.
Definition at line 162 of file container.hpp.
References FEAT::LAFEM::elements_zfp, and XASSERTM.
Referenced by SerialConfig().
Member Data Documentation
elements_compression
CompressionModes FEAT::LAFEM::SerialConfig::elements_compression private
Definition at line 51 of file container.hpp.
indices_compression
CompressionModes FEAT::LAFEM::SerialConfig::indices_compression private
Definition at line 51 of file container.hpp.
tolerance
FEAT::Real FEAT::LAFEM::SerialConfig::tolerance private
Definition at line 52 of file container.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/container.hpp