FEAT: FEAT::Control::Statistics Class Reference
FEAT::Control::Statistics Class Reference
Static Public Member Functions
template<typename SystemLevelType_ , typename DomainType_ >
static void report (double solver_toe, int statistics_check, int shape_dimension, std::deque< std::shared_ptr< SystemLevelType_ > > &system_levels, DomainType_ &domain)
Create a detailed report about the application execution.
Detailed Description
Definition at line 17 of file statistics.hpp.
Member Function Documentation
report()
template<typename SystemLevelType_ , typename DomainType_ > static void FEAT::Control::Statistics::report (double solver_toe, int statistics_check, int shape_dimension, std::deque< std::shared_ptr< SystemLevelType_ > > & system_levels, DomainType_ & domain) inline static
Create a detailed report about the application execution.
Parameters
solver_toe The execution time of the complete linear solver in seconds
statistics_check The result of args.check("statistics"), i.e. the detail level(0 = some details, 1 = many details and log file output)
shape_dimension The maximum dimension of the used shapes
system_levels The system level hierarchy
domain The domain
Todo:
reimplement method based on expressions
Definition at line 32 of file statistics.hpp.
References FEAT::Dist::Comm::allreduce(), FEAT::Statistics::get_formatted_flops(), FEAT::MemoryUsage::get_formatted_memory_usage(), FEAT::Statistics::get_formatted_solver_tree(), FEAT::Statistics::get_formatted_times(), FEAT::Dist::op_max, FEAT::Dist::op_min, FEAT::String::pad_back(), FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), FEAT::Statistics::toe_assembly, FEAT::Statistics::toe_partition, FEAT::Statistics::toe_solve, FEAT::String::trim(), and FEAT::Dist::Comm::world().
The documentation for this class was generated from the following file:
control/statistics.hpp