FEAT: FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ > Class Template Reference
FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ > Class Template Reference
Finite-Differences pointstar matrix factory.
#include <pointstar_factory.hpp>
Public Member Functions
PointstarFactoryFD2 (const std::vector< IndexType_ > &num_of_subintervalls, const std::vector< DataType_ > &dimensions)
Creates the pointstar factory.
virtual DenseVector< DataType_, IndexType_ > eigenvector_min () const override
Computes the eigenvector of the smallest eigenvalue.
virtual DataType_ lambda_max () const override
Computes the largest eigenvalue of the FD-style matrix.
virtual DataType_ lambda_min () const override
Computes the smallest eigenvalue of the FD-style matrix.
virtual SparseMatrixBanded< DataType_, IndexType_ > matrix_banded () const override
Generates a FD-style pointstar banded matrix.
virtual DataType_ spectral_cond () const
Computes the spectral condition number of the pointstar matrix.
DenseVector< DataType_, IndexType_ > vector_q2_bubble () const override
Computes a Q2-bubble vector.
Protected Attributes
const Index _d
number of dimensions
const std::vector< DataType_ > & _dimensions
vector with lengths of the n-dimensional hypercube
const std::vector< IndexType_ > & _num_of_subintervalls
vector with number of subintervalls per dimension (plus a leading 2).
Detailed Description
template<typename DataType_, typename IndexType_>
class FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >
Finite-Differences pointstar matrix factory.
This class generates poinstar matrices in Finite-Differences style. Moreover, this class can compute the largest and smallest eigenvalue of the corresponding matrix as well as the eigenvector with respect to the smallest eigenvalue.
Author
Christoph Lohmann
Definition at line 983 of file pointstar_factory.hpp.
Constructor & Destructor Documentation
PointstarFactoryFD2()
template<typename DataType_ , typename IndexType_ > FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::PointstarFactoryFD2 (const std::vector< IndexType_ > & num_of_subintervalls, const std::vector< DataType_ > & dimensions) inline
Creates the pointstar factory.
Parameters
[in] num_of_subintervalls The vector with number of subintervalls per dimension plus a leading 2.
[in] dimensions The vector with lengths of the n-dimensional hypercube
Definition at line 995 of file pointstar_factory.hpp.
~PointstarFactoryFD2()
template<typename DataType_ , typename IndexType_ > virtual FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::~PointstarFactoryFD2 () inline virtual
Definition at line 1001 of file pointstar_factory.hpp.
Member Function Documentation
eigenvector_min()
template<typename DataType_ , typename IndexType_ > virtual DenseVector< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::eigenvector_min () const inline override virtual
Computes the eigenvector of the smallest eigenvalue.
This function generates the eigenvector with respect to the smallest eigenvalue of the corresponding pointstar matrix.
Returns
The m^d x m^d eigenvector
Implements FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >.
Definition at line 1119 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_num_of_subintervalls, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and FEAT::Math::sin().
lambda_max()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::lambda_max () const inline override virtual
Computes the largest eigenvalue of the FD-style matrix.
The largest eigenvalue of the FD-style matrix is given as
\[ \lambda_{\max} = 2 \cdot \sum^d_{k=1} h_k^2 \big(1 + \cos(\pi h_k) \big) \]
Returns
The largest eigenvalue of the matrix.
Implements FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >.
Definition at line 1104 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_dimensions, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_num_of_subintervalls, FEAT::Math::cos(), and FEAT::Math::sqr().
lambda_min()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::lambda_min () const inline override virtual
Computes the smallest eigenvalue of the FD-style matrix.
The smallest eigenvalue of the FD-style matrix wrt the sine-bubble eigenvector is given as
\[ \lambda_{\min} = 2 \cdot \sum^d_{k=1} h_k^2 \big(1 - \cos(\pi h_k) \big) \]
Returns
The smallest eigenvalue of the matrix.
Implements FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >.
Definition at line 1079 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_dimensions, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_num_of_subintervalls, FEAT::Math::cos(), and FEAT::Math::sqr().
matrix_banded()
template<typename DataType_ , typename IndexType_ > virtual SparseMatrixBanded< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::matrix_banded () const inline override virtual
Generates a FD-style pointstar banded matrix.
Returns
The m^d x m^d FD-stye pointstar matrix.
Create matrix-structure
Fill matrix
Implements FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >.
Definition at line 1009 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_dimensions, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_num_of_subintervalls, FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::Math::sqr(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val().
spectral_cond()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::spectral_cond () const inline virtual inherited
Computes the spectral condition number of the pointstar matrix.
Returns
The spectral condition number of the matrix.
Definition at line 944 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::lambda_max(), and FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::lambda_min().
vector_q2_bubble()
template<typename DataType_ , typename IndexType_ > DenseVector< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::vector_q2_bubble () const inline override virtual
Computes a Q2-bubble vector.
This function can be used to generate a useful solution vector for the pointstar matrix. The corresponding right hand side can be computed by multiplying this vector by the matrix.
Returns
The m^d x m^d Q2-bubble vector
Implements FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >.
Definition at line 1158 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_dimensions, FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_num_of_subintervalls, and FEAT::LAFEM::DenseVector< DT_, IT_ >::elements().
Member Data Documentation
_d
template<typename DataType_ , typename IndexType_ > const Index FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_d protected inherited
number of dimensions
Definition at line 894 of file pointstar_factory.hpp.
Referenced by FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::matrix_banded(), and FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::vector_q2_bubble().
_dimensions
template<typename DataType_ , typename IndexType_ > const std::vector<DataType_>& FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_dimensions protected inherited
vector with lengths of the n-dimensional hypercube
Definition at line 892 of file pointstar_factory.hpp.
Referenced by FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::matrix_banded(), and FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::vector_q2_bubble().
_num_of_subintervalls
template<typename DataType_ , typename IndexType_ > const std::vector<IndexType_>& FEAT::LAFEM::PointstarFactoryBase2< DataType_, IndexType_ >::_num_of_subintervalls protected inherited
vector with number of subintervalls per dimension (plus a leading 2).
Definition at line 890 of file pointstar_factory.hpp.
Referenced by FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::matrix_banded(), and FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::vector_q2_bubble().
The documentation for this class was generated from the following file:
kernel/lafem/pointstar_factory.hpp