FEAT: FEAT::Assembly::MeanFilterAssembler Class Reference
FEAT::Assembly::MeanFilterAssembler Class Reference
Mean Filter assembler class.
#include <mean_filter_assembler.hpp>
Static Public Member Functions
template<typename DataType_ , typename IndexType_ , typename Space_ >
static void assemble (LAFEM::DenseVector< DataType_, IndexType_ > &vec_prim, LAFEM::DenseVector< DataType_, IndexType_ > &vec_dual, const Space_ &space, const Cubature::DynamicFactory &cubature_factory)
Assembles an integral mean filter.
template<typename DataType_ , typename IndexType_ , typename Space_ >
static void assemble (LAFEM::DenseVector< DataType_, IndexType_ > &vec_prim, LAFEM::DenseVector< DataType_, IndexType_ > &vec_dual, const Space_ &space, const String &cubature_name)
Assembles an integral mean filter.
template<typename DataType_ , typename IndexType_ , typename Space_ >
static void assemble (LAFEM::MeanFilter< DataType_, IndexType_ > &filter, const Space_ &space, const Cubature::DynamicFactory &cubature_factory, const DataType_ sol_mean=DataType_(0))
Assembles an integral mean filter.
template<typename DataType_ , typename IndexType_ , typename Space_ >
static void assemble (LAFEM::MeanFilter< DataType_, IndexType_ > &filter, const Space_ &space, const String &cubature_name, const DataType_ sol_mean=DataType_(0))
Assembles an integral mean filter.
Detailed Description
Mean Filter assembler class.
This class assembles an integral mean filter for a given finite element space.
Author
Peter Zajac
Definition at line 26 of file mean_filter_assembler.hpp.
Member Function Documentation
assemble() [1/4]
template<typename DataType_ , typename IndexType_ , typename Space_ > static void FEAT::Assembly::MeanFilterAssembler::assemble (LAFEM::DenseVector< DataType_, IndexType_ > & vec_prim, LAFEM::DenseVector< DataType_, IndexType_ > & vec_dual, const Space_ & space, const Cubature::DynamicFactory & cubature_factory) inline static
Assembles an integral mean filter.
Parameters
[out] vec_prim,vec_dual The transient references to the primal and dual vectors for the mean filter.
[in] space The transient finite element space for which the filter is to be assembled.
[in] cubature_factory A cubature factory for integration.
Definition at line 65 of file mean_filter_assembler.hpp.
References FEAT::Assembly::LinearFunctionalAssembler::assemble_vector(), and FEAT::Assembly::Interpolator::project().
assemble() [2/4]
template<typename DataType_ , typename IndexType_ , typename Space_ > static void FEAT::Assembly::MeanFilterAssembler::assemble (LAFEM::DenseVector< DataType_, IndexType_ > & vec_prim, LAFEM::DenseVector< DataType_, IndexType_ > & vec_dual, const Space_ & space, const String & cubature_name) inline static
Assembles an integral mean filter.
Parameters
[out] vec_prim,vec_dual The transient references to the primal and dual vectors for the mean filter.
[in] space The transient finite element space for which the filter is to be assembled.
[in] cubature_name The name of the cubature rule to use for integration
Definition at line 42 of file mean_filter_assembler.hpp.
References assemble().
Referenced by assemble().
assemble() [3/4]
template<typename DataType_ , typename IndexType_ , typename Space_ > static void FEAT::Assembly::MeanFilterAssembler::assemble (LAFEM::MeanFilter< DataType_, IndexType_ > & filter, const Space_ & space, const Cubature::DynamicFactory & cubature_factory, const DataType_ sol_mean = DataType_(0)) inline static
Assembles an integral mean filter.
Parameters
[out] filter A transient reference to the filter to be assembled. The filter is automatically allocated by this function, so it does not need to be allocated beforehand.
[in] space A transient reference to the finite element space for which the filter is to be assembled.
[in] cubature_factory A cubature factory for integration.
[in] sol_mean The desired integral mean of the solution vector. Defaults to 0.
Warning
This function does not work for global mean filters!
Definition at line 132 of file mean_filter_assembler.hpp.
References assemble().
assemble() [4/4]
template<typename DataType_ , typename IndexType_ , typename Space_ > static void FEAT::Assembly::MeanFilterAssembler::assemble (LAFEM::MeanFilter< DataType_, IndexType_ > & filter, const Space_ & space, const String & cubature_name, const DataType_ sol_mean = DataType_(0)) inline static
Assembles an integral mean filter.
Parameters
[out] filter A transient reference to the filter to be assembled. The filter is automatically allocated by this function, so it does not need to be allocated beforehand.
[in] space A transient reference to the finite element space for which the filter is to be assembled.
[in] cubature_name The name of the cubature rule to use for integration
[in] sol_mean The desired integral mean of the solution vector. Defaults to 0.
Warning
This function does not work for global mean filters!
Definition at line 104 of file mean_filter_assembler.hpp.
References assemble().
The documentation for this class was generated from the following file:
kernel/assembly/mean_filter_assembler.hpp