FEAT: FEAT::Geometry::PartiParMETIS Class Reference
FEAT::Geometry::PartiParMETIS Class Reference
ParMETIS mesh/graph partitioner backend.
#include <parti_parmetis.hpp>
Public Member Functions
PartiParMETIS (const Dist::Comm &comm, Index min_elems=1000u, int max_procs=1000)
Constructor.
virtual ~PartiParMETIS ()
virtual destructor
Adjacency::Graph build_elems_at_rank () const
Builds and returns the elements-at-rank graph representing the partitioning.
template<int nf_, int nv_, typename VertexSet_ >
bool execute (const IndexSet< nf_ > &faces_at_elem, const IndexSet< nv_ > &verts_at_elem, const VertexSet_ &vertices, const Index num_parts, const std::vector< Real > &weights)
Executes the ParMETIS graph partitioner.
int get_sub_comm_size () const
Returns the size of the internal sub-communicator.
Protected Member Functions
bool _apply_parmetis ()
auxiliary function: applies the actual ParMETIS call
bool _broadcast_coloring (bool metis_ok)
auxiliary function: broadcasts the coloring from the root process
template<int nv_, typename VertexSet_ >
void _compute_midpoints (const IndexSet< nv_ > &verts_at_elem, const VertexSet_ &vertices)
auxiliary function: compute element midpoints from vertex coordinates
void _create_subgraph (const Adjacency::Graph &faces_at_elem, const Index num_parts)
auxiliary function: builds a hypergraph from the adjacency graph
bool _execute ()
auxiliary function: executes the partitioner
bool _gather_coloring ()
auxiliary function: gathers the partitioned coloring onto the root process
Private Attributes
Adjacency::Coloring _coloring
the element coloring
const Dist::Comm & _comm
our main communicator
Index _first_elem
first element for this process
int _max_procs
maximum number of MPI processes to use
std::vector< Real > _midpoints
element midpoints
Index _min_elems
minimum number of elements per MPI process
Index _num_elems
the total number of elements
Index _num_local_elems
number of elements for this process
Index _num_parts
the desired number of partitions
std::vector< Index > _parts
element partitioning
Dist::Comm _sub_comm
a sub-communicator for the partitioner
Adjacency::Graph _subgraph
the adjacency sub-graph for this process
std::vector< Real > _weights
elements weights; empty if not weighted
Detailed Description
ParMETIS mesh/graph partitioner backend.
Author
Peter Zajac
Definition at line 25 of file parti_parmetis.hpp.
Constructor & Destructor Documentation
PartiParMETIS()
FEAT::Geometry::PartiParMETIS::PartiParMETIS (const Dist::Comm & comm, Index min_elems = 1000u, int max_procs = 1000) explicit
Constructor.
Parameters
[in] comm A resident reference to the communicator to be used by the partitioner. In a recursive partitioning setting, this has to be the progeny communicator.
Note that this class might create a sub-communicator of comm internally if there are too many ranks in the communicator for the given number of mesh elements or desired number of partitions to improve the computation vs communication trade-off.
Member Function Documentation
_compute_midpoints()
template<int nv_, typename VertexSet_ > void FEAT::Geometry::PartiParMETIS::_compute_midpoints (const IndexSet< nv_ > & verts_at_elem, const VertexSet_ & vertices) inline protected
auxiliary function: compute element midpoints from vertex coordinates
Definition at line 140 of file parti_parmetis.hpp.
References _midpoints, _num_local_elems, and FEAT::Geometry::IndexSet< num_indices_ >::num_indices.
Referenced by execute().
build_elems_at_rank()
Adjacency::Graph FEAT::Geometry::PartiParMETIS::build_elems_at_rank () const inline
Builds and returns the elements-at-rank graph representing the partitioning.
Definition at line 112 of file parti_parmetis.hpp.
References _coloring, and FEAT::Adjacency::Coloring::create_partition_graph().
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_metis().
execute()
template<int nf_, int nv_, typename VertexSet_ > bool FEAT::Geometry::PartiParMETIS::execute (const IndexSet< nf_ > & faces_at_elem, const IndexSet< nv_ > & verts_at_elem, const VertexSet_ & vertices, const Index num_parts, const std::vector< Real > & weights) inline
Executes the ParMETIS graph partitioner.
Parameters
[in] faces_at_elem A transient reference to the faces-at-element index set of the mesh that is to be partitioned. The face-dimension of the index set can be chosen freely, but typically in the finite element case this is the vertices-at-element index set of the mesh.
[in] verts_at_elem A transient reference to the vertices-at-element index set of the mesh. This index set is only used to compute the element midpoint coordinates for the partitioner, but it is not used for the computation of the adjacency pattern.
[in] vertices A transient reference to the vertex set of the mesh.
[in] num_parts The desired number of partitions to create. Must be > 0, but it does not necessarily need to be equal to the number of processes in the communicator.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if the partitioning was successful, or false, if some error occurred.
Definition at line 99 of file parti_parmetis.hpp.
References _compute_midpoints(), _create_subgraph(), _execute(), _weights, and FEAT::Adjacency::as_is.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_metis().
get_sub_comm_size()
int FEAT::Geometry::PartiParMETIS::get_sub_comm_size () const inline
Returns the size of the internal sub-communicator.
This only gives useful results after the execute() function has been called.
Definition at line 122 of file parti_parmetis.hpp.
References _sub_comm, and FEAT::Dist::Comm::size().
Member Data Documentation
_coloring
Adjacency::Coloring FEAT::Geometry::PartiParMETIS::_coloring private
the element coloring
Definition at line 53 of file parti_parmetis.hpp.
Referenced by build_elems_at_rank().
_comm
const Dist::Comm& FEAT::Geometry::PartiParMETIS::_comm private
our main communicator
Definition at line 29 of file parti_parmetis.hpp.
_first_elem
Index FEAT::Geometry::PartiParMETIS::_first_elem private
first element for this process
Definition at line 41 of file parti_parmetis.hpp.
_max_procs
int FEAT::Geometry::PartiParMETIS::_max_procs private
maximum number of MPI processes to use
Definition at line 33 of file parti_parmetis.hpp.
_midpoints
std::vector<Real> FEAT::Geometry::PartiParMETIS::_midpoints private
element midpoints
Definition at line 47 of file parti_parmetis.hpp.
Referenced by _compute_midpoints().
_min_elems
Index FEAT::Geometry::PartiParMETIS::_min_elems private
minimum number of elements per MPI process
Definition at line 35 of file parti_parmetis.hpp.
_num_elems
Index FEAT::Geometry::PartiParMETIS::_num_elems private
the total number of elements
Definition at line 37 of file parti_parmetis.hpp.
_num_local_elems
Index FEAT::Geometry::PartiParMETIS::_num_local_elems private
number of elements for this process
Definition at line 43 of file parti_parmetis.hpp.
Referenced by _compute_midpoints().
_num_parts
Index FEAT::Geometry::PartiParMETIS::_num_parts private
the desired number of partitions
Definition at line 39 of file parti_parmetis.hpp.
_parts
std::vector<Index> FEAT::Geometry::PartiParMETIS::_parts private
element partitioning
Definition at line 51 of file parti_parmetis.hpp.
_sub_comm
Dist::Comm FEAT::Geometry::PartiParMETIS::_sub_comm private
a sub-communicator for the partitioner
Definition at line 31 of file parti_parmetis.hpp.
Referenced by get_sub_comm_size().
_subgraph
Adjacency::Graph FEAT::Geometry::PartiParMETIS::_subgraph private
the adjacency sub-graph for this process
Definition at line 45 of file parti_parmetis.hpp.
_weights
std::vector<Real> FEAT::Geometry::PartiParMETIS::_weights private
elements weights; empty if not weighted
Definition at line 49 of file parti_parmetis.hpp.
Referenced by execute().
The documentation for this class was generated from the following file:
kernel/geometry/parti_parmetis.hpp