FEAT: FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ > Class Template Reference
FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ > Class Template Reference
Algebraic DOF Partitioned Vector class template.
#include <alg_dof_parti.hpp>
Public Types
typedef Global::AlgDofParti< LocalVector_, Mirror_ > AlgDofPartiType
the algebraic DOF partitioning type
typedef LAFEM::DenseVector< DataType, IndexType > BufferVectorType
the buffer vector type used for communication
typedef LocalVector_::DataType DataType
our data type
typedef Global::Vector< LocalVector_, Mirror_ > GlobalVectorType
the global vector type
typedef LocalVector_::IndexType IndexType
our index type
typedef LocalVector_ LocalVectorType
the local vector type
typedef Mirror_ MirrorType
the vector mirror type
typedef LAFEM::DenseVector< DataType, IndexType > OwnedVectorType
the vector type used for the internal storage of our owned DOFs
Public Member Functions
AlgDofPartiVector ()
default constructor
AlgDofPartiVector (const AlgDofPartiType *adp_in)
Creates a ADP vector based on an algebraic dof partitioning.
void allgather (BufferVectorType &vec_full) const
Gathers the full global vector on all processes.
void clear ()
Resets the whole object.
void download (GlobalVectorType &global_vector) const
Copies the DOF values from this algebraic-dof-partitioned vector into a global vector.
void download (LocalVectorType &local_vector) const
Copies the DOF values from this algebraic-dof-partitioned vector into a local vector.
const AlgDofPartiType * get_alg_dof_parti () const
const Dist::Comm * get_comm () const
OwnedVectorType & owned ()
const OwnedVectorType & owned () const
void upload (const GlobalVectorType &global_vector)
Copies the DOF values from a global vector to this algebraic-dof-partitioned vector.
void upload (const LocalVectorType &local_vector)
Copies the DOF values from a local vector to this algebraic-dof-partitioned vector.
Protected Attributes
const AlgDofPartiType * _alg_dof_parti
the algebraic dof-partitioning
OwnedVectorType _vector
the internal vector object storing our owned dofs
Detailed Description
template<typename LocalVector_, typename Mirror_>
class FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >
Algebraic DOF Partitioned Vector class template.
This class implements the management of a distributed vector based on an algebraic DOF partitioning. A vector of this class will contain only the owned DOFs of this process. The two basic operations provided by this class are the upload and the download of vectors, where:
upload: copy the DOFs of a Global::Vector into this AlgDofPartiVector
download: copy the DOFs of this AlgDofPartiVector into a Global::Vector
Note that objects of this class do not require any additional initialization as the constructor, which expects and AlgDofPartiObject as its parameters, will automatically allocate the internal vector.
This class also offers a function named allgather(), which creates a vector containing all global DOFs on each process. This function is only meant to be used for small-scale debugging purposes and shall not be used for actual production work, because it a) will totally screw the scalability of your code on a large number of processes and b) may easily lead to fatal out-of-memory events. You have been warned.
Author
Peter Zajac
Definition at line 658 of file alg_dof_parti.hpp.
Member Typedef Documentation
AlgDofPartiType
template<typename LocalVector_ , typename Mirror_ > typedef Global::AlgDofParti<LocalVector_, Mirror_> FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::AlgDofPartiType
the algebraic DOF partitioning type
Definition at line 675 of file alg_dof_parti.hpp.
BufferVectorType
template<typename LocalVector_ , typename Mirror_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::BufferVectorType
the buffer vector type used for communication
Definition at line 678 of file alg_dof_parti.hpp.
DataType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVector_::DataType FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::DataType
our data type
Definition at line 662 of file alg_dof_parti.hpp.
GlobalVectorType
template<typename LocalVector_ , typename Mirror_ > typedef Global::Vector<LocalVector_, Mirror_> FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::GlobalVectorType
the global vector type
Definition at line 672 of file alg_dof_parti.hpp.
IndexType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVector_::IndexType FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::IndexType
our index type
Definition at line 664 of file alg_dof_parti.hpp.
LocalVectorType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVector_ FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::LocalVectorType
the local vector type
Definition at line 667 of file alg_dof_parti.hpp.
MirrorType
template<typename LocalVector_ , typename Mirror_ > typedef Mirror_ FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::MirrorType
the vector mirror type
Definition at line 669 of file alg_dof_parti.hpp.
OwnedVectorType
template<typename LocalVector_ , typename Mirror_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::OwnedVectorType
the vector type used for the internal storage of our owned DOFs
Definition at line 680 of file alg_dof_parti.hpp.
Constructor & Destructor Documentation
AlgDofPartiVector() [1/2]
template<typename LocalVector_ , typename Mirror_ > FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::AlgDofPartiVector () inline
default constructor
Definition at line 690 of file alg_dof_parti.hpp.
AlgDofPartiVector() [2/2]
template<typename LocalVector_ , typename Mirror_ > FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::AlgDofPartiVector (const AlgDofPartiType * adp_in) inline explicit
Creates a ADP vector based on an algebraic dof partitioning.
Once this constructor returns, this vector does not require any further initialization and is therefore ready-to-use.
Parameters
[in] adp_in The algebraic dof partitioning to be used for this vector.
Definition at line 705 of file alg_dof_parti.hpp.
Member Function Documentation
allgather()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather (BufferVectorType & vec_full) const inline
Gathers the full global vector on all processes.
Attention
This function makes use of the infamous allgatherv MPI operation, which is known to completely blow the scalability of an application running on a large number of processes. In addition to the scalability issues, please keep in mind that the global vector may be very large – even potentially larger that the total amount of memory that this available for a single process, which would inevitably result in an application crash due to an out-of-memory event.
Do not use this function except for small-scale debugging purposes. You have been warned.
Parameters
[in,out] vec_full A vector that receives all global dofs. Its length is assumed to be initialized to the global number of degrees of freedom.
Definition at line 759 of file alg_dof_parti.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), XASSERT, and XASSERTM.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::apply().
clear()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear () inline
Resets the whole object.
Definition at line 712 of file alg_dof_parti.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clear().
download() [1/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download (GlobalVectorType & global_vector) const inline
Copies the DOF values from this algebraic-dof-partitioned vector into a global vector.
Parameters
[in,out] global_vector The global vector into which our DOF values are to be copied. The vector is assumed to be allocated to the correct length, but its DOF values upon call are ignored.
Definition at line 807 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::local().
Referenced by FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download().
download() [2/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download (LocalVectorType & local_vector) const inline
Copies the DOF values from this algebraic-dof-partitioned vector into a local vector.
Parameters
[in,out] local_vector The local vector into which our DOF values are to be copied. The vector is assumed to be allocated to the correct length, but its DOF values upon call are ignored.
Definition at line 819 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::get_comm(), FEAT::Dist::Comm::irecv(), FEAT::Dist::RequestVector::is_null(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERT.
get_alg_dof_parti()
template<typename LocalVector_ , typename Mirror_ > const AlgDofPartiType * FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::get_alg_dof_parti () const inline
Returns
A pointer to the underlying algebraic dof partitioning object.
Definition at line 731 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::_alg_dof_parti.
get_comm()
template<typename LocalVector_ , typename Mirror_ > const Dist::Comm * FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::get_comm () const inline
Returns
A pointer to the underlying communicator
Definition at line 737 of file alg_dof_parti.hpp.
References XASSERT.
Referenced by FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download().
owned() [1/2]
template<typename LocalVector_ , typename Mirror_ > OwnedVectorType & FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::owned () inline
Returns
A reference to the internal owned vector object.
Definition at line 719 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::_vector.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::apply(), and FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic().
owned() [2/2]
template<typename LocalVector_ , typename Mirror_ > const OwnedVectorType & FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::owned () const inline
Returns
A reference to the internal owned vector object.
Definition at line 725 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::_vector.
upload() [1/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload (const GlobalVectorType & global_vector) inline
Copies the DOF values from a global vector to this algebraic-dof-partitioned vector.
Parameters
[in] global_vector The global vector whose values are to be copied into this vector.
Definition at line 778 of file alg_dof_parti.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload().
Referenced by FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload().
upload() [2/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload (const LocalVectorType & local_vector) inline
Copies the DOF values from a local vector to this algebraic-dof-partitioned vector.
Parameters
[in] local_vector The local vector whose values are to be copied into this vector.
Definition at line 789 of file alg_dof_parti.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERT.
Member Data Documentation
_alg_dof_parti
template<typename LocalVector_ , typename Mirror_ > const AlgDofPartiType* FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::_alg_dof_parti protected
the algebraic dof-partitioning
Definition at line 684 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download(), and FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::get_alg_dof_parti().
_vector
template<typename LocalVector_ , typename Mirror_ > OwnedVectorType FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::_vector protected
the internal vector object storing our owned dofs
Definition at line 686 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::owned().
The documentation for this class was generated from the following file:
kernel/global/alg_dof_parti.hpp