FEAT: FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ > Class Template Reference
FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ > Class Template Reference
Umbrella smoother class template.
#include <umbrella_smoother.hpp>
Public Types
typedef UmbrellaSmoother< MeshType_ > BaseClass
typedef BaseClass::CoordType CoordType
typedef MeshPart< MeshType > MeshPartType
typedef MeshType_ MeshType
typedef RootMeshNode< MeshType > RootMeshNodeType
typedef MeshType_::VertexSetType VertexSetType
Public Member Functions
DistributedUmbrellaSmoother (const Dist::Comm &comm, RootMeshNodeType &root_mesh_node)
Constructor.
void compile ()
void smooth (Index max_iter, CoordType tol, bool uniform=true)
Smooths the mesh with an umbrella operator.
Static Public Attributes
static constexpr int facet_dim = MeshType::shape_dim - 1
static constexpr int shape_dim = MeshType_::shape_dim
static constexpr int world_dim = MeshType::world_dim
Protected Member Functions
virtual void _calc_boundary_facets () override
determines for each facet whether it is a boundary facet or an inner facet
virtual void _calc_boundary_vertices ()
determines for each vertex whether it is a boundary vertex or an inner vertex
void _calc_max (CoordType &global_max) override
calculates global maximum over all processes; is overridden in DistributedUmbrellaSmoother
void _init_edge_multiplicity ()
Computes per-edge weights for distributed smoothing.
void _synchronize (std::vector< Tiny::Vector< CoordType, world_dim > > &sum_neigh, std::vector< CoordType > &deg) override
synchronizes the smoother over all processes; is overridden in DistributedUmbrellaSmoother
Protected Attributes
std::vector< int > _boundary_facets
vector to store which facet is at the boundary
std::vector< int > _boundary_vertices
vector to store which vertex is at the boundary
const Dist::Comm & _comm
a reference to our communicator
std::vector< CoordType > _edge_weights
MeshType_ & _mesh
the mesh we want to smooth
RootMeshNodeType & _root_mesh_node
a reference to our root mesh node
VertexSetType & _vtx
Detailed Description
template<typename MeshType_>
class FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >
Umbrella smoother class template.
This class extends the functionality of the UmbrellaSmoother class by addition MPI-based synchronization to ensure that one obtains a consistently smoothed mesh in a distributed simulation. Note that this class needs to work with a RootMeshNode rather than a "naked" mesh object, because it requires the halos for synchronization, which are stored in the mesh node and not in the mesh object itself.
See the documentation of the base-class UmbrellaSmoother for more information
Template Parameters
MeshType_ The type of the mesh that is to be smoothed, e.g. ConformalMesh
Author
Pia Ritter
Definition at line 292 of file umbrella_smoother.hpp.
Member Typedef Documentation
BaseClass
template<typename MeshType_ > typedef UmbrellaSmoother<MeshType_> FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::BaseClass
Definition at line 296 of file umbrella_smoother.hpp.
CoordType
template<typename MeshType_ > typedef BaseClass::CoordType FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::CoordType
Definition at line 304 of file umbrella_smoother.hpp.
MeshPartType
template<typename MeshType_ > typedef MeshPart<MeshType> FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::MeshPartType
Definition at line 298 of file umbrella_smoother.hpp.
MeshType
template<typename MeshType_ > typedef MeshType_ FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::MeshType
Definition at line 297 of file umbrella_smoother.hpp.
RootMeshNodeType
template<typename MeshType_ > typedef RootMeshNode<MeshType> FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::RootMeshNodeType
Definition at line 299 of file umbrella_smoother.hpp.
VertexSetType
template<typename MeshType_ > typedef MeshType_::VertexSetType FEAT::Geometry::UmbrellaSmoother< MeshType_ >::VertexSetType inherited
Definition at line 50 of file umbrella_smoother.hpp.
Constructor & Destructor Documentation
DistributedUmbrellaSmoother()
template<typename MeshType_ > FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::DistributedUmbrellaSmoother (const Dist::Comm & comm, RootMeshNodeType & root_mesh_node) inline explicit
Constructor.
Parameters
[in] comm A resident reference to the communicator that was used for partitioning.
[in] root_mesh_node A resident reference to the root mesh node containing the mesh that is to be smoothed.
Definition at line 322 of file umbrella_smoother.hpp.
References FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_init_edge_multiplicity().
~DistributedUmbrellaSmoother()
template<typename MeshType_ > virtual FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::~DistributedUmbrellaSmoother () inline virtual
Definition at line 331 of file umbrella_smoother.hpp.
Member Function Documentation
_calc_boundary_facets()
template<typename MeshType_ > virtual void FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_calc_boundary_facets () inline override protected virtual
determines for each facet whether it is a boundary facet or an inner facet
Reimplemented from FEAT::Geometry::UmbrellaSmoother< MeshType_ >.
Definition at line 337 of file umbrella_smoother.hpp.
References FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_root_mesh_node, FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), and FEAT::Geometry::TargetSet::get_num_entities().
_calc_boundary_vertices()
template<typename MeshType_ > virtual void FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_vertices () inline protected virtual inherited
determines for each vertex whether it is a boundary vertex or an inner vertex
Definition at line 237 of file umbrella_smoother.hpp.
References FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_boundary_facets, FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_boundary_vertices, FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_facets(), and FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_mesh.
Referenced by FEAT::Geometry::UmbrellaSmoother< MeshType_ >::smooth().
_calc_max()
template<typename MeshType_ > void FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_calc_max (CoordType &) inline override protected virtual
calculates global maximum over all processes; is overridden in DistributedUmbrellaSmoother
Reimplemented from FEAT::Geometry::UmbrellaSmoother< MeshType_ >.
Definition at line 533 of file umbrella_smoother.hpp.
References FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_comm, FEAT::Dist::Comm::allreduce(), and FEAT::Dist::op_max.
_init_edge_multiplicity()
template<typename MeshType_ > void FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_init_edge_multiplicity () inline protected
Computes per-edge weights for distributed smoothing.
Counts how many partitions share each edge and sets the edge weight to 1/multiplicity.
Definition at line 361 of file umbrella_smoother.hpp.
References FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_comm, FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_root_mesh_node, FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Dist::Comm::rank(), and FEAT::Dist::Comm::size().
Referenced by FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::DistributedUmbrellaSmoother().
_synchronize()
template<typename MeshType_ > void FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_synchronize (std::vector< Tiny::Vector< CoordType, world_dim > > & , std::vector< CoordType > &) inline override protected virtual
synchronizes the smoother over all processes; is overridden in DistributedUmbrellaSmoother
Reimplemented from FEAT::Geometry::UmbrellaSmoother< MeshType_ >.
Definition at line 412 of file umbrella_smoother.hpp.
References FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_comm, FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_root_mesh_node, FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Dist::RequestVector::push_back(), FEAT::Dist::Comm::rank(), FEAT::Dist::RequestVector::reserve(), FEAT::Dist::Comm::size(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERT.
compile()
template<typename MeshType_ > void FEAT::Geometry::UmbrellaSmoother< MeshType_ >::compile () inline inherited
Definition at line 88 of file umbrella_smoother.hpp.
smooth()
template<typename MeshType_ > void FEAT::Geometry::UmbrellaSmoother< MeshType_ >::smooth (Index max_iter, CoordType tol, bool uniform = true) inline inherited
Smooths the mesh with an umbrella operator.
Iteratively moves each inner vertex towards the (possibly weighted) average of its adjacent vertices (Jacobi update). The weights are either uniform or inversely proportional to the edge lengths (w_ij = 1 / |e_ij|).
Parameters
[in] uniform true for uniform operator and false for scale dependent operator
[in] max_iter Maximum number of smoothing iterations
[in] tol Iteration stops if the largest vertex displacement between two steps falls below this threshold
Note
This function only moves inner vertices and leaves boundary vertices untouched.
Definition at line 115 of file umbrella_smoother.hpp.
References FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_boundary_vertices, FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_max(), FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_mesh, FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_synchronize(), FEAT::Math::maxi(), and FEAT::Math::sqrt().
Member Data Documentation
_boundary_facets
template<typename MeshType_ > std::vector<int> FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_boundary_facets protected inherited
vector to store which facet is at the boundary
Definition at line 60 of file umbrella_smoother.hpp.
Referenced by FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_facets(), and FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_vertices().
_boundary_vertices
template<typename MeshType_ > std::vector<int> FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_boundary_vertices protected inherited
vector to store which vertex is at the boundary
Definition at line 58 of file umbrella_smoother.hpp.
Referenced by FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_vertices(), and FEAT::Geometry::UmbrellaSmoother< MeshType_ >::smooth().
_comm
template<typename MeshType_ > const Dist::Comm& FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_comm protected
a reference to our communicator
Definition at line 308 of file umbrella_smoother.hpp.
Referenced by FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_calc_max(), FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_init_edge_multiplicity(), and FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_synchronize().
_edge_weights
template<typename MeshType_ > std::vector<CoordType> FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_edge_weights protected inherited
Definition at line 62 of file umbrella_smoother.hpp.
_mesh
template<typename MeshType_ > MeshType_& FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_mesh protected inherited
the mesh we want to smooth
Definition at line 56 of file umbrella_smoother.hpp.
Referenced by FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_calc_boundary_vertices(), and FEAT::Geometry::UmbrellaSmoother< MeshType_ >::smooth().
_root_mesh_node
template<typename MeshType_ > RootMeshNodeType& FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_root_mesh_node protected
a reference to our root mesh node
Definition at line 310 of file umbrella_smoother.hpp.
Referenced by FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_init_edge_multiplicity(), and FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::_synchronize().
_vtx
template<typename MeshType_ > VertexSetType& FEAT::Geometry::UmbrellaSmoother< MeshType_ >::_vtx protected inherited
Definition at line 64 of file umbrella_smoother.hpp.
facet_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::facet_dim = MeshType::shape_dim - 1 static constexpr
Definition at line 302 of file umbrella_smoother.hpp.
shape_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::UmbrellaSmoother< MeshType_ >::shape_dim = MeshType_::shape_dim static constexpr inherited
Definition at line 51 of file umbrella_smoother.hpp.
world_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::DistributedUmbrellaSmoother< MeshType_ >::world_dim = MeshType::world_dim static constexpr
Definition at line 301 of file umbrella_smoother.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/umbrella_smoother.hpp