FEAT: FEAT::Control::VoxelTransferAssembler Class Reference
FEAT::Control::VoxelTransferAssembler Class Reference
Transfer Assembler for VoxelDomainControl levels.
#include <voxel_transfer_assembler.hpp>
Static Public Member Functions
template<typename SystemLevel_ , typename DomainLevel_ >
static void assemble_blocked_basic_transfer (SystemLevel_ &sys_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_c, const String &cubature, bool trunc=false, bool shrink=true)
Assembles the transfer operators for a BlockedBasicSystemLevel or a derived class thereof.
template<typename SystemLevel_ , typename DomainLevel_ >
static void assemble_blocked_basic_transfer (SystemLevel_ &sys_lvl_f, const SystemLevel_ &sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_c, const String &cubature, bool trunc=false, bool shrink=true)
Assembles the transfer operators for a BlockedBasicSystemLevel or a derived class thereof.
template<typename SystemLevel_ , typename DomainLevel_ >
static void assemble_scalar_basic_transfer (SystemLevel_ &sys_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_c, const String &cubature, bool trunc=false, bool shrink=true)
Assembles the transfer operators for a ScalarBasicSystemLevel or a derived class thereof.
template<typename SystemLevel_ , typename DomainLevel_ >
static void assemble_scalar_basic_transfer (SystemLevel_ &sys_lvl_f, const SystemLevel_ &sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_c, const String &cubature, bool trunc=false, bool shrink=true)
Assembles the transfer operators for a ScalarBasicSystemLevel or a derived class thereof.
template<typename SystemLevel_ , typename DomainLevel_ >
static void assemble_stokes_blocked_transfers (SystemLevel_ &sys_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_c, const String &cubature, bool trunc_v=false, bool trunc_p=false, bool shrink=true)
Assembles the transfer operators for a StokesBlockedSystemLevel or a derived class thereof.
template<typename SystemLevel_ , typename DomainLevel_ >
static void assemble_stokes_blocked_transfers (SystemLevel_ &sys_lvl_f, const SystemLevel_ &sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_c, const String &cubature, bool trunc_v=false, bool trunc_p=false, bool shrink=true)
Assembles the transfer operators for a StokesBlockedSystemLevel or a derived class thereof.
Static Protected Member Functions
template<typename SystemLevel_ , typename DomainLevel_ , typename SpaceLambda_ , typename TransferLambda_ , typename GateLambda_ , typename MuxerLambda_ >
static void _assemble_blocked_transfer (SystemLevel_ &sys_lvl_f, const SystemLevel_ &sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_c, const String &cubature, bool trunc, bool shrink, SpaceLambda_ &&space_lambda, TransferLambda_ &&transfer_lambda, GateLambda_ &&gate_lambda, MuxerLambda_ &&muxer_lambda)
Assembles the blocked transfer operators for a system level.
template<typename SystemLevel_ , typename DomainLevel_ , typename SpaceLambda_ , typename TransferLambda_ , typename GateLambda_ , typename MuxerLambda_ >
static void _assemble_scalar_transfer (SystemLevel_ &sys_lvl_f, const SystemLevel_ &sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > &virt_lvl_c, const String &cubature, bool trunc, bool shrink, SpaceLambda_ &&space_lambda, TransferLambda_ &&transfer_lambda, GateLambda_ &&gate_lambda, MuxerLambda_ &&muxer_lambda)
Assembles the scalar transfer operators for a system level.
template<typename Matrix_ , typename Mirror_ >
static Matrix_ _deslag_matrix_cols (const Matrix_ &matrix, const Mirror_ &col_mirror)
Deslags a matrix by columns, i.e. removes all columns whose row indices are not present in the given mirror.
template<typename Matrix_ , typename Mirror_ >
static Matrix_ _deslag_matrix_rows (const Matrix_ &matrix, const Mirror_ &row_mirror)
Deslags a matrix by rows, i.e. removes all rows whose row indices are not present in the given mirror.
template<typename Vector_ , typename Mirror_ >
static Vector_ _deslag_vector (const Vector_ &vector, const Mirror_ &mirror)
Deslags a vector, i.e. removes all entries whose indices are not present in the given mirror.
Detailed Description
Transfer Assembler for VoxelDomainControl levels.
This class is used by applications to assemble transfer operators based on a mesh hierarchy that is created and organized by the VoxelDomainControl class.
Author
Peter Zajac
Definition at line 21 of file voxel_transfer_assembler.hpp.
Member Function Documentation
_assemble_blocked_transfer()
template<typename SystemLevel_ , typename DomainLevel_ , typename SpaceLambda_ , typename TransferLambda_ , typename GateLambda_ , typename MuxerLambda_ > static void FEAT::Control::VoxelTransferAssembler::_assemble_blocked_transfer (SystemLevel_ & sys_lvl_f, const SystemLevel_ & sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_c, const String & cubature, bool trunc, bool shrink, SpaceLambda_ && space_lambda, TransferLambda_ && transfer_lambda, GateLambda_ && gate_lambda, MuxerLambda_ && muxer_lambda) inline static protected
Assembles the blocked transfer operators for a system level.
Parameters
[in,out] sys_lvl_f A transient reference to the fine system level whose transfer operators are to be assembled.
[in] sys_lvl_c A transient reference to the coarse system level, if it exists as a physical level in the domain control of this process, otherwise a reference to sys_lvl_f, thus indicating that this process does not participate in the parent layer.
[in] virt_lvl_f A transient reference to the fine virtual domain level.
[in] virt_lvl_c A transient reference to the coarse virtual domain level.
[in] cubature The name of the cubature rule to be used for integration.
[in] trunc Specifies whether the truncation operator is also to be assembled along with the prolongation and restriction operators.
[in] shrink Specifies whether the transfer matrices are to be shrunk, i.e. whether all entries whose absolute value is smaller than 1e-3 times the largest absolute value are to be removed from the matrices.
[in] space_lambda A lambda expression that takes a const reference to a DomainLevel_ and returns a const reference to the finite element space on that level.
[in] transfer_lambda A lambda expression that takes a reference to a SystemLevel and returns a reference to the local LAFEM::Transfer object on that level.
[in] gate_lambda A lambda expression that takes a const reference to a SystemLevel and returns a const reference to the blocked gate on that level.
[in] muxer_lambda A lambda expression that takes a const reference to a SystemLevel and returns a const reference to the blocked coarse muxer on that level.
Definition at line 354 of file voxel_transfer_assembler.hpp.
References _deslag_matrix_cols(), _deslag_matrix_rows(), _deslag_vector(), FEAT::LAFEM::Allocate, FEAT::Assembly::SymbolicAssembler::assemble_matrix_2lvl(), FEAT::Assembly::MirrorAssembler::assemble_mirror(), FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::GridTransfer::assemble_truncation(), FEAT::Global::Gate< LocalVector_, Mirror_ >::convert(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::convert(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join_send(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split_recv(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0(), XASSERT, and XASSERTM.
Referenced by assemble_blocked_basic_transfer(), and assemble_stokes_blocked_transfers().
_assemble_scalar_transfer()
template<typename SystemLevel_ , typename DomainLevel_ , typename SpaceLambda_ , typename TransferLambda_ , typename GateLambda_ , typename MuxerLambda_ > static void FEAT::Control::VoxelTransferAssembler::_assemble_scalar_transfer (SystemLevel_ & sys_lvl_f, const SystemLevel_ & sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_c, const String & cubature, bool trunc, bool shrink, SpaceLambda_ && space_lambda, TransferLambda_ && transfer_lambda, GateLambda_ && gate_lambda, MuxerLambda_ && muxer_lambda) inline static protected
Assembles the scalar transfer operators for a system level.
Parameters
[in,out] sys_lvl_f A transient reference to the fine system level whose transfer operators are to be assembled.
[in] sys_lvl_c A transient reference to the coarse system level, if it exists as a physical level in the domain control of this process, otherwise a reference to sys_lvl_f, thus indicating that this process does not participate in the parent layer.
[in] virt_lvl_f A transient reference to the fine virtual domain level.
[in] virt_lvl_c A transient reference to the coarse virtual domain level.
[in] cubature The name of the cubature rule to be used for integration.
[in] trunc Specifies whether the truncation operator is also to be assembled along with the prolongation and restriction operators.
[in] shrink Specifies whether the transfer matrices are to be shrunk, i.e. whether all entries whose absolute value is smaller than 1e-3 times the largest absolute value are to be removed from the matrices.
[in] space_lambda A lambda expression that takes a const reference to a DomainLevel_ and returns a const reference to the finite element space on that level.
[in] transfer_lambda A lambda expression that takes a reference to a SystemLevel and returns a reference to the local LAFEM::Transfer object on that level.
[in] gate_lambda A lambda expression that takes a const reference to a SystemLevel and returns a const reference to the scalar gate on that level.
[in] muxer_lambda A lambda expression that takes a const reference to a SystemLevel and returns a const reference to the scalar coarse muxer on that level.
Definition at line 159 of file voxel_transfer_assembler.hpp.
References _deslag_matrix_cols(), _deslag_matrix_rows(), _deslag_vector(), FEAT::Assembly::SymbolicAssembler::assemble_matrix_2lvl(), FEAT::Assembly::MirrorAssembler::assemble_mirror(), FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::GridTransfer::assemble_truncation(), XASSERT, and XASSERTM.
Referenced by assemble_scalar_basic_transfer(), and assemble_stokes_blocked_transfers().
_deslag_matrix_cols()
template<typename Matrix_ , typename Mirror_ > static Matrix_ FEAT::Control::VoxelTransferAssembler::_deslag_matrix_cols (const Matrix_ & matrix, const Mirror_ & col_mirror) inline static protected
Deslags a matrix by columns, i.e. removes all columns whose row indices are not present in the given mirror.
Definition at line 73 of file voxel_transfer_assembler.hpp.
Referenced by _assemble_blocked_transfer(), and _assemble_scalar_transfer().
_deslag_matrix_rows()
template<typename Matrix_ , typename Mirror_ > static Matrix_ FEAT::Control::VoxelTransferAssembler::_deslag_matrix_rows (const Matrix_ & matrix, const Mirror_ & row_mirror) inline static protected
Deslags a matrix by rows, i.e. removes all rows whose row indices are not present in the given mirror.
Definition at line 40 of file voxel_transfer_assembler.hpp.
Referenced by _assemble_blocked_transfer(), and _assemble_scalar_transfer().
_deslag_vector()
template<typename Vector_ , typename Mirror_ > static Vector_ FEAT::Control::VoxelTransferAssembler::_deslag_vector (const Vector_ & vector, const Mirror_ & mirror) inline static protected
Deslags a vector, i.e. removes all entries whose indices are not present in the given mirror.
Definition at line 26 of file voxel_transfer_assembler.hpp.
Referenced by _assemble_blocked_transfer(), and _assemble_scalar_transfer().
assemble_blocked_basic_transfer() [1/2]
template<typename SystemLevel_ , typename DomainLevel_ > static void FEAT::Control::VoxelTransferAssembler::assemble_blocked_basic_transfer (SystemLevel_ & sys_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_c, const String & cubature, bool trunc = false, bool shrink = true) inline static
Assembles the transfer operators for a BlockedBasicSystemLevel or a derived class thereof.
Attention
This overload is to be used if the current process does not participate on the coarse level. If the current process participates on both the fine and coarse levels, then use the overload of this function that does also accepts a coarse system level as the second parameter.
Parameters
[in,out] sys_lvl_f A transient reference to the fine system level whose transfer operators are to be assembled.
[in] virt_lvl_f A transient reference to the fine virtual domain level.
[in] virt_lvl_c A transient reference to the coarse virtual domain level.
[in] cubature The name of the cubature rule to be used for integration.
[in] trunc Specifies whether the truncation operator is also to be assembled along with the prolongation and restriction operators.
[in] shrink Specifies whether the transfer matrices are to be shrunk, i.e. whether all entries whose absolute value is smaller than 1e-3 times the largest absolute value are to be removed from the matrices.
Definition at line 652 of file voxel_transfer_assembler.hpp.
References _assemble_blocked_transfer().
assemble_blocked_basic_transfer() [2/2]
template<typename SystemLevel_ , typename DomainLevel_ > static void FEAT::Control::VoxelTransferAssembler::assemble_blocked_basic_transfer (SystemLevel_ & sys_lvl_f, const SystemLevel_ & sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_c, const String & cubature, bool trunc = false, bool shrink = true) inline static
Assembles the transfer operators for a BlockedBasicSystemLevel or a derived class thereof.
Attention
This overload is to be used if the current process participates on both the fine and coarse levels. If the current process only participates on the fine level, then use the overload of this function that does not accept a coarse system level as a parameter.
Parameters
[in,out] sys_lvl_f A transient reference to the fine system level whose transfer operators are to be assembled.
[in] sys_lvl_c A transient reference to the coarse system level.
[in] virt_lvl_f A transient reference to the fine virtual domain level.
[in] virt_lvl_c A transient reference to the coarse virtual domain level.
[in] cubature The name of the cubature rule to be used for integration.
[in] trunc Specifies whether the truncation operator is also to be assembled along with the prolongation and restriction operators.
[in] shrink Specifies whether the transfer matrices are to be shrunk, i.e. whether all entries whose absolute value is smaller than 1e-3 times the largest absolute value are to be removed from the matrices.
Definition at line 697 of file voxel_transfer_assembler.hpp.
References _assemble_blocked_transfer().
assemble_scalar_basic_transfer() [1/2]
template<typename SystemLevel_ , typename DomainLevel_ > static void FEAT::Control::VoxelTransferAssembler::assemble_scalar_basic_transfer (SystemLevel_ & sys_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_c, const String & cubature, bool trunc = false, bool shrink = true) inline static
Assembles the transfer operators for a ScalarBasicSystemLevel or a derived class thereof.
Attention
This overload is to be used if the current process does not participate on the coarse level. If the current process participates on both the fine and coarse levels, then use the overload of this function that does also accepts a coarse system level as the second parameter.
Parameters
[in,out] sys_lvl_f A transient reference to the fine system level whose transfer operators are to be assembled.
[in] virt_lvl_f A transient reference to the fine virtual domain level.
[in] virt_lvl_c A transient reference to the coarse virtual domain level.
[in] cubature The name of the cubature rule to be used for integration.
[in] trunc Specifies whether the truncation operator is also to be assembled along with the prolongation and restriction operators.
[in] shrink Specifies whether the transfer matrices are to be shrunk, i.e. whether all entries whose absolute value is smaller than 1e-3 times the largest absolute value are to be removed from the matrices.
Definition at line 565 of file voxel_transfer_assembler.hpp.
References _assemble_scalar_transfer().
assemble_scalar_basic_transfer() [2/2]
template<typename SystemLevel_ , typename DomainLevel_ > static void FEAT::Control::VoxelTransferAssembler::assemble_scalar_basic_transfer (SystemLevel_ & sys_lvl_f, const SystemLevel_ & sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_c, const String & cubature, bool trunc = false, bool shrink = true) inline static
Assembles the transfer operators for a ScalarBasicSystemLevel or a derived class thereof.
Attention
This overload is to be used if the current process participates on both the fine and coarse levels. If the current process only participates on the fine level, then use the overload of this function that does not accept a coarse system level as a parameter.
Parameters
[in,out] sys_lvl_f A transient reference to the fine system level whose transfer operators are to be assembled.
[in] sys_lvl_c A transient reference to the coarse system level.
[in] virt_lvl_f A transient reference to the fine virtual domain level.
[in] virt_lvl_c A transient reference to the coarse virtual domain level.
[in] cubature The name of the cubature rule to be used for integration.
[in] trunc Specifies whether the truncation operator is also to be assembled along with the prolongation and restriction operators.
[in] shrink Specifies whether the transfer matrices are to be shrunk, i.e. whether all entries whose absolute value is smaller than 1e-3 times the largest absolute value are to be removed from the matrices.
Definition at line 610 of file voxel_transfer_assembler.hpp.
References _assemble_scalar_transfer().
assemble_stokes_blocked_transfers() [1/2]
template<typename SystemLevel_ , typename DomainLevel_ > static void FEAT::Control::VoxelTransferAssembler::assemble_stokes_blocked_transfers (SystemLevel_ & sys_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_c, const String & cubature, bool trunc_v = false, bool trunc_p = false, bool shrink = true) inline static
Assembles the transfer operators for a StokesBlockedSystemLevel or a derived class thereof.
Attention
This overload is to be used if the current process does not participate on the coarse level. If the current process participates on both the fine and coarse levels, then use the overload of this function that does also accepts a coarse system level as the second parameter.
Parameters
[in,out] sys_lvl_f A transient reference to the fine system level whose transfer operators are to be assembled.
[in] virt_lvl_f A transient reference to the fine virtual domain level.
[in] virt_lvl_c A transient reference to the coarse virtual domain level.
[in] cubature The name of the cubature rule to be used for integration.
[in] trunc Specifies whether the truncation operator is also to be assembled along with the prolongation and restriction operators.
[in] shrink Specifies whether the transfer matrices are to be shrunk, i.e. whether all entries whose absolute value is smaller than 1e-3 times the largest absolute value are to be removed from the matrices.
Definition at line 739 of file voxel_transfer_assembler.hpp.
References _assemble_blocked_transfer(), and _assemble_scalar_transfer().
assemble_stokes_blocked_transfers() [2/2]
template<typename SystemLevel_ , typename DomainLevel_ > static void FEAT::Control::VoxelTransferAssembler::assemble_stokes_blocked_transfers (SystemLevel_ & sys_lvl_f, const SystemLevel_ & sys_lvl_c, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_f, const Control::Domain::VirtualLevel< Control::Domain::VoxelDomainLevelWrapper< DomainLevel_ > > & virt_lvl_c, const String & cubature, bool trunc_v = false, bool trunc_p = false, bool shrink = true) inline static
Assembles the transfer operators for a StokesBlockedSystemLevel or a derived class thereof.
Attention
This overload is to be used if the current process participates on both the fine and coarse levels. If the current process only participates on the fine level, then use the overload of this function that does not accept a coarse system level as a parameter.
Parameters
[in,out] sys_lvl_f A transient reference to the fine system level whose transfer operators are to be assembled.
[in] sys_lvl_c A transient reference to the coarse system level.
[in] virt_lvl_f A transient reference to the fine virtual domain level.
[in] virt_lvl_c A transient reference to the coarse virtual domain level.
[in] cubature The name of the cubature rule to be used for integration.
[in] trunc Specifies whether the truncation operator is also to be assembled along with the prolongation and restriction operators.
[in] shrink Specifies whether the transfer matrices are to be shrunk, i.e. whether all entries whose absolute value is smaller than 1e-3 times the largest absolute value are to be removed from the matrices.
Definition at line 791 of file voxel_transfer_assembler.hpp.
References _assemble_blocked_transfer(), and _assemble_scalar_transfer().
The documentation for this class was generated from the following file:
control/voxel_transfer_assembler.hpp