FEAT: FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ > Class Template Reference
FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ > Class Template Reference abstract
Abstract base class for meta-matrix tests.
#include <meta_matrix_test_base.hpp>
Public Types
typedef DataType_ DataType
typedef PowerRowMatrix< ScalarMatrixD, 2 > DiveMatrix
divergence matrix type
typedef PowerColMatrix< ScalarMatrixB, 2 > GradMatrix
gradient matrix type
typedef MetaMatrixTestHelper< DataType, IndexType > Helper
typedef IndexType_ IndexType
typedef ScalarVector PresVector
pressure vector type
typedef Helper::ScalarMatrixA ScalarMatrixA
scalar matrix type A
typedef Helper::ScalarMatrixB ScalarMatrixB
scalar matrix type B
typedef Helper::ScalarMatrixD ScalarMatrixD
scalar matrix type D
typedef Helper::ScalarVector ScalarVector
scalar vector type
typedef SaddlePointMatrix< VeloDiagMatrix, GradMatrix, DiveMatrix > SystemDiagMatrix
system matrix type
typedef SaddlePointMatrix< VeloFullMatrix, GradMatrix, DiveMatrix > SystemFullMatrix
typedef TupleVector< VeloVector, PresVector > SystemVector
system vector type
typedef PowerDiagMatrix< ScalarMatrixA, 2 > VeloDiagMatrix
velocity matrix type (diagonal)
typedef PowerFullMatrix< ScalarMatrixA, 2, 2 > VeloFullMatrix
velocity matrix type (full)
typedef PowerVector< ScalarVector, 2 > VeloVector
velocity vector type
Public Member Functions
MetaMatrixTestBase (const String &id_in, const String datatype_name="none", const String index_name="none", PreferredBackend preferred_backend=PreferredBackend::generic)
virtual void check (const char *const function, const char *const file, const long line, bool was_ok, const String &message) const
utility method used bei TEST_CHECK_THROWS
virtual String get_datatype_name ()
returns our target platform
virtual String get_index_name ()
returns our target platform
virtual PreferredBackend get_preferred_backend () const
virtual String get_preferred_backend_name () const
virtual const String id () const
returns our id string
virtual void run () const =0
runs the test case
Static Public Member Functions
static void gen_system (Index m, SystemDiagMatrix &mat_sys, SystemVector &vec_sol, SystemVector &vec_rhs)
generate test matrix with diagonal velocity blocks
static void gen_system (Index m, SystemFullMatrix &mat_sys, SystemVector &vec_sol, SystemVector &vec_rhs)
generate test matrix with full velocity blocks
Protected Attributes
String _datatype_name
precision description String
const String _id
test description String
String _index_name
index type description String
PreferredBackend _preferred_backend
preferred compute intensive backend
Detailed Description
template<typename DataType_, typename IndexType_>
class FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >
Abstract base class for meta-matrix tests.
This class is used by various meta-matrix tests. It offers the functionality of generating a saddle-point system, i.e. a matrix, an rhs and a corresponding solution vector.
The matrix, which is generated, has the following structure:
  S = / A  B \
      \ D  0 /
  A = / A1  0 \  B = / B1 \
      \ 0  A2 /      \ B2 /
  D = ( D1 D2 )
where:
A1, A2 are of type SparseMatrixCSR
B1, B2 are of type SparseMatrixELL
D1, D2 are of type SparseMatrixCOO
A is of type PowerDiagMatrix
B is of type PowerColMatrix
D is of type PowerRowMatrix
S is of type SaddlePointMatrix
Putting all this together leads to
SaddlePointMatrix<
PowerDiagMatrix< SparseMatrixCSR<...> >,
PowerColMatrix< SparseMatrixELL<...> >,
PowerRowMatrix< SpaceMatrixCOO<...> >
>
*
Author
Peter Zajac
Definition at line 95 of file meta_matrix_test_base.hpp.
Member Typedef Documentation
DataType
template<typename DataType_ , typename IndexType_ > typedef DataType_ FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::DataType
Definition at line 99 of file meta_matrix_test_base.hpp.
DiveMatrix
template<typename DataType_ , typename IndexType_ > typedef PowerRowMatrix<ScalarMatrixD, 2> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::DiveMatrix
divergence matrix type
Definition at line 126 of file meta_matrix_test_base.hpp.
GradMatrix
template<typename DataType_ , typename IndexType_ > typedef PowerColMatrix<ScalarMatrixB, 2> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::GradMatrix
gradient matrix type
Definition at line 124 of file meta_matrix_test_base.hpp.
Helper
template<typename DataType_ , typename IndexType_ > typedef MetaMatrixTestHelper<DataType, IndexType> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::Helper
Definition at line 101 of file meta_matrix_test_base.hpp.
IndexType
template<typename DataType_ , typename IndexType_ > typedef IndexType_ FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::IndexType
Definition at line 100 of file meta_matrix_test_base.hpp.
PresVector
template<typename DataType_ , typename IndexType_ > typedef ScalarVector FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::PresVector
pressure vector type
Definition at line 108 of file meta_matrix_test_base.hpp.
ScalarMatrixA
template<typename DataType_ , typename IndexType_ > typedef Helper::ScalarMatrixA FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::ScalarMatrixA
scalar matrix type A
Definition at line 113 of file meta_matrix_test_base.hpp.
ScalarMatrixB
template<typename DataType_ , typename IndexType_ > typedef Helper::ScalarMatrixB FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::ScalarMatrixB
scalar matrix type B
Definition at line 115 of file meta_matrix_test_base.hpp.
ScalarMatrixD
template<typename DataType_ , typename IndexType_ > typedef Helper::ScalarMatrixD FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::ScalarMatrixD
scalar matrix type D
Definition at line 117 of file meta_matrix_test_base.hpp.
ScalarVector
template<typename DataType_ , typename IndexType_ > typedef Helper::ScalarVector FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::ScalarVector
scalar vector type
Definition at line 104 of file meta_matrix_test_base.hpp.
SystemDiagMatrix
template<typename DataType_ , typename IndexType_ > typedef SaddlePointMatrix<VeloDiagMatrix, GradMatrix, DiveMatrix> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::SystemDiagMatrix
system matrix type
Definition at line 129 of file meta_matrix_test_base.hpp.
SystemFullMatrix
template<typename DataType_ , typename IndexType_ > typedef SaddlePointMatrix<VeloFullMatrix, GradMatrix, DiveMatrix> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::SystemFullMatrix
Definition at line 130 of file meta_matrix_test_base.hpp.
SystemVector
template<typename DataType_ , typename IndexType_ > typedef TupleVector<VeloVector, PresVector> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::SystemVector
system vector type
Definition at line 110 of file meta_matrix_test_base.hpp.
VeloDiagMatrix
template<typename DataType_ , typename IndexType_ > typedef PowerDiagMatrix<ScalarMatrixA, 2> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::VeloDiagMatrix
velocity matrix type (diagonal)
Definition at line 120 of file meta_matrix_test_base.hpp.
VeloFullMatrix
template<typename DataType_ , typename IndexType_ > typedef PowerFullMatrix<ScalarMatrixA, 2, 2> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::VeloFullMatrix
velocity matrix type (full)
Definition at line 122 of file meta_matrix_test_base.hpp.
VeloVector
template<typename DataType_ , typename IndexType_ > typedef PowerVector<ScalarVector, 2> FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::VeloVector
velocity vector type
Definition at line 106 of file meta_matrix_test_base.hpp.
Constructor & Destructor Documentation
MetaMatrixTestBase()
template<typename DataType_ , typename IndexType_ > FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::MetaMatrixTestBase (const String & id_in, const String datatype_name = "none", const String index_name = "none", PreferredBackend preferred_backend = PreferredBackend::generic) inline explicit
Definition at line 132 of file meta_matrix_test_base.hpp.
Member Function Documentation
check()
virtual void FEAT::TestSystem::UnitTest::check (const char *const function, const char *const file, const long line, bool was_ok, const String & message) const inline virtual inherited
utility method used bei TEST_CHECK_THROWS
Definition at line 270 of file test_system.hpp.
gen_system() [1/2]
template<typename DataType_ , typename IndexType_ > static void FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system (Index m, SystemDiagMatrix & mat_sys, SystemVector & vec_sol, SystemVector & vec_rhs) inline static
generate test matrix with diagonal velocity blocks
create two pointstars
generate the corresponding CSR matrices
Definition at line 138 of file meta_matrix_test_base.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::convert(), FEAT::LAFEM::TupleVector< First_, Rest_ >::convert(), FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble().
gen_system() [2/2]
template<typename DataType_ , typename IndexType_ > static void FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system (Index m, SystemFullMatrix & mat_sys, SystemVector & vec_sol, SystemVector & vec_rhs) inline static
generate test matrix with full velocity blocks
create two pointstars
generate the corresponding CSR matrices
Definition at line 185 of file meta_matrix_test_base.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::convert(), FEAT::LAFEM::TupleVector< First_, Rest_ >::convert(), FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble().
get_datatype_name()
virtual String FEAT::TestSystem::UnitTest::get_datatype_name () inline virtual inherited
returns our target platform
Definition at line 285 of file test_system.hpp.
References FEAT::TestSystem::UnitTest::_datatype_name.
get_index_name()
virtual String FEAT::TestSystem::UnitTest::get_index_name () inline virtual inherited
returns our target platform
Definition at line 291 of file test_system.hpp.
References FEAT::TestSystem::UnitTest::_index_name.
get_preferred_backend()
virtual PreferredBackend FEAT::TestSystem::UnitTest::get_preferred_backend () const inline virtual inherited
Definition at line 296 of file test_system.hpp.
get_preferred_backend_name()
virtual String FEAT::TestSystem::UnitTest::get_preferred_backend_name () const inline virtual inherited
Definition at line 301 of file test_system.hpp.
id()
virtual const String FEAT::TestSystem::UnitTest::id () const inline virtual inherited
returns our id string
Definition at line 264 of file test_system.hpp.
References FEAT::TestSystem::UnitTest::_id.
run()
virtual void FEAT::TestSystem::UnitTest::run () const pure virtual inherited
runs the test case
Called by unittest framework only.
Member Data Documentation
_datatype_name
String FEAT::TestSystem::UnitTest::_datatype_name protected inherited
precision description String
Definition at line 236 of file test_system.hpp.
Referenced by FEAT::TestSystem::UnitTest::get_datatype_name().
_id
const String FEAT::TestSystem::UnitTest::_id protected inherited
test description String
Definition at line 234 of file test_system.hpp.
Referenced by FEAT::TestSystem::UnitTest::id().
_index_name
String FEAT::TestSystem::UnitTest::_index_name protected inherited
index type description String
Definition at line 238 of file test_system.hpp.
Referenced by FEAT::TestSystem::UnitTest::get_index_name().
_preferred_backend
PreferredBackend FEAT::TestSystem::UnitTest::_preferred_backend protected inherited
preferred compute intensive backend
Definition at line 240 of file test_system.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/meta_matrix_test_base.hpp