FEAT: FEAT::Geometry::Partition Class Reference
FEAT::Geometry::Partition Class Reference
Partition class.
#include <partition_set.hpp>
Public Member Functions
Partition ()
default construcotr
Partition (Adjacency::Graph &&graph_, const String &name_, int prio_=0, int level_=0)
Constructor.
Partition (const Adjacency::DynamicGraph &graph_, const String &name_, int prio_=0, int level_=0)
Constructor.
Partition (Partition &&other)
move constructor
virtual ~Partition ()
destructor
int get_level () const
String get_name () const
Index get_num_elements () const
Index get_num_patches () const
const Adjacency::Graph & get_patches () const
int get_priority () const
Partition & operator= (Partition &&other)
move-assign operator
void permute (const Adjacency::Permutation &inv_perm)
Permutes the element indices.
Index size () const
Protected Attributes
int _level
the level that this partitioning refers to
String _name
the name of this partitioning
Adjacency::Graph _patches
our actual partitioning
int _prio
the priority for automatic choice
Detailed Description
Partition class.
This class represents a (manual) partitioning of a mesh, which consists of an adjacency graph storing the elements for each rank as well as a few additional entities as the name, the priority and the overlap.
Author
Peter Zajac
Definition at line 29 of file partition_set.hpp.
Constructor & Destructor Documentation
Partition() [1/4]
FEAT::Geometry::Partition::Partition () inline
default construcotr
Definition at line 44 of file partition_set.hpp.
Partition() [2/4]
FEAT::Geometry::Partition::Partition (Adjacency::Graph && graph_, const String & name_, int prio_ = 0, int level_ = 0) inline explicit
Constructor.
Parameters
[in] graph_ The elements-at-rank graph defining the partition.
[in] name_ The name of the partition. May be an empty string
[in] prio_ The priority of the partition.
[in] level_ The refinement level that the partition is defined on.
Definition at line 65 of file partition_set.hpp.
Partition() [3/4]
FEAT::Geometry::Partition::Partition (const Adjacency::DynamicGraph & graph_, const String & name_, int prio_ = 0, int level_ = 0) inline explicit
Constructor.
Parameters
[in] graph_ The elements-at-rank graph defining the partition.
[in] name_ The name of the partition. May be an empty string
[in] prio_ The priority of the partition.
[in] level_ The refinement level that the partition is defined on.
Definition at line 89 of file partition_set.hpp.
Partition() [4/4]
FEAT::Geometry::Partition::Partition (Partition && other) inline
move constructor
Definition at line 98 of file partition_set.hpp.
~Partition()
virtual FEAT::Geometry::Partition::~Partition () inline virtual
destructor
Definition at line 119 of file partition_set.hpp.
Member Function Documentation
get_level()
int FEAT::Geometry::Partition::get_level () const inline
Returns
the refinement level of the partition.
Definition at line 154 of file partition_set.hpp.
References _level.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_extern(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Geometry::MeshFileWriter::write_partition().
get_name()
String FEAT::Geometry::Partition::get_name () const inline
Returns
the name of the partition.
Definition at line 142 of file partition_set.hpp.
References _name.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_extern(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Geometry::MeshFileWriter::write_partition().
get_num_elements()
Index FEAT::Geometry::Partition::get_num_elements () const inline
Returns
the number of elements in the partition.
Definition at line 136 of file partition_set.hpp.
References _patches.
Referenced by FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Geometry::MeshFileWriter::write_partition().
get_num_patches()
Index FEAT::Geometry::Partition::get_num_patches () const inline
Returns
the number of ranks/patches in the partition.
Definition at line 130 of file partition_set.hpp.
References _patches.
Referenced by FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Geometry::MeshFileWriter::write_partition().
get_patches()
const Adjacency::Graph & FEAT::Geometry::Partition::get_patches () const inline
Returns
the elements-at-rank adjacency graph of the partition.
Definition at line 160 of file partition_set.hpp.
References _patches.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_extern(), FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Geometry::MeshFileWriter::write_partition().
get_priority()
int FEAT::Geometry::Partition::get_priority () const inline
Returns
the priority of the partition.
Definition at line 148 of file partition_set.hpp.
References _prio.
Referenced by FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition(), and FEAT::Geometry::MeshFileWriter::write_partition().
operator=()
Partition & FEAT::Geometry::Partition::operator= (Partition && other) inline
move-assign operator
Definition at line 107 of file partition_set.hpp.
References _level, _name, _patches, _prio, and FEAT::Geometry::other.
permute()
void FEAT::Geometry::Partition::permute (const Adjacency::Permutation & inv_perm) inline
Permutes the element indices.
Parameters
[in] inv_perm The inverse element permutation to be applied.
Definition at line 171 of file partition_set.hpp.
References _patches, and FEAT::Adjacency::Graph::permute_indices().
size()
Index FEAT::Geometry::Partition::size () const inline
Returns
the number of ranks/patches in the partition.
Definition at line 124 of file partition_set.hpp.
References _patches.
Member Data Documentation
_level
int FEAT::Geometry::Partition::_level protected
the level that this partitioning refers to
Definition at line 37 of file partition_set.hpp.
Referenced by get_level(), and operator=().
_name
String FEAT::Geometry::Partition::_name protected
the name of this partitioning
Definition at line 33 of file partition_set.hpp.
Referenced by get_name(), and operator=().
_patches
Adjacency::Graph FEAT::Geometry::Partition::_patches protected
our actual partitioning
Definition at line 40 of file partition_set.hpp.
Referenced by get_num_elements(), get_num_patches(), get_patches(), operator=(), permute(), and size().
_prio
int FEAT::Geometry::Partition::_prio protected
the priority for automatic choice
Definition at line 35 of file partition_set.hpp.
Referenced by get_priority(), and operator=().
The documentation for this class was generated from the following file:
kernel/geometry/partition_set.hpp