FEAT: FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > > Class Template Reference
FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > > Class Template Reference
Quadrilateral-to-Hexahedral mesh extruder.
#include <mesh_extruder.hpp>
Public Types
typedef Coord_ CoordType
typedef MeshAtlas< HexaMesh > HexaAtlas
typedef HexaPart::AttributeSetType HexaAttrib
typedef Atlas::ChartBase< HexaMesh > HexaChart
typedef ConformalMesh< Shape::Hypercube< 3 >, 3, Coord_ > HexaMesh
typedef MeshPart< HexaMesh > HexaPart
typedef RootMeshNode< HexaMesh > HexaRootNode
typedef HexaMesh::IndexSetHolderType HexaTopology
typedef HexaPart::TargetSetHolderType HexaTrgSetHolder
typedef HexaMesh::VertexSetType HexaVertexSet
typedef MeshAtlas< QuadMesh > QuadAtlas
typedef QuadPart::AttributeSetType QuadAttrib
typedef Atlas::ChartBase< QuadMesh > QuadChart
typedef ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > QuadMesh
typedef MeshPart< QuadMesh > QuadPart
typedef RootMeshNode< QuadMesh > QuadRootNode
typedef QuadMesh::IndexSetHolderType QuadTopology
typedef QuadPart::TargetSetHolderType QuadTrgSetHolder
typedef QuadMesh::VertexSetType QuadVertexSet
Public Member Functions
MeshExtruder (const std::deque< CoordType > &z_list, String zmin_part_name, String zmax_part_name)
Creates the mesh extruder object.
MeshExtruder (Index slices, CoordType z_min, CoordType z_max, String zmin_part_name, String zmax_part_name)
Creates the mesh extruder object.
void extrude_atlas (HexaAtlas &hexa_atlas, const QuadAtlas &quad_atlas) const
Extrudes an quadrilateral mesh atlas.
void extrude_attribute (std::unique_ptr< HexaAttrib > &hexa_attrib, const QuadAttrib &quad_attrib) const
Extrudes a quadrilateral mesh attribute.
std::unique_ptr< HexaChart > extrude_chart (const QuadChart &quad_chart) const
Extrudes and returns a quadrilateral mesh chart.
void extrude_mapping (HexaTrgSetHolder &hexa_mapp, const QuadTrgSetHolder &quad_mapp, const QuadMesh &quad_parent) const
Extrudes a quadrilateral mapping (aka "target set holder")
void extrude_num_entities (Index hexa_num_entities[], const Index quad_num_entities[]) const
Computes the extruded entity counts.
void extrude_partition (Partition &hexa_parti, const Partition &quad_parti) const
Extrudes a quadrilateral mesh partitioning.
void extrude_partition_set (PartitionSet &hexa_part_set, const PartitionSet &quad_part_set) const
Extrudes a quadrilateral mesh partition set.
void extrude_root_node (HexaRootNode &hexa_root_node, const QuadRootNode &quad_root_node, const HexaAtlas *hexa_atlas) const
Extrudes a quadrilateral root mesh node.
void extrude_slice_mapping (HexaTrgSetHolder &hexa_mapp, const QuadMesh &quad_parent, const Index slice) const
void extrude_topology (HexaTopology &hexa_topo, const QuadTopology &quad_topo) const
Extrudes a quadrilateral topology (aka "index set holder").
void extrude_vertex_set (HexaVertexSet &hexa_vtx, const QuadVertexSet &quad_vtx) const
Extrudes a quadrilateral vertex set.
void set_angles (CoordType yaw, CoordType pitch, CoordType roll)
Sets the transformation angles.
void set_offset (CoordType x, CoordType y, CoordType z)
Sets the transformation offset.
void set_origin (CoordType x, CoordType y)
Sets the transformation origin.
template<typename SubChart_ >
bool try_extrude_chart (std::unique_ptr< HexaChart > &hexa_chart, const QuadChart &quad_chart) const
Tries to extrudes a quadrilateral mesh chart.
Protected Attributes
CoordType _angle_p
CoordType _angle_r
CoordType _angle_y
transformation angles
CoordType _offset_x
transformation offset
CoordType _offset_y
CoordType _offset_z
CoordType _origin_x
transformation origin
CoordType _origin_y
const Index _slices
the number of slices in z-direction
std::deque< CoordType > _z_list
deque of z-coordinates
const CoordType _z_max
const CoordType _z_min
minimal and maximal z-coordinate
String _zmax_part_name
String _zmin_part_name
mesh-part names for z-min/max boundary regions
Detailed Description
template<typename Coord_>
class FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >
Quadrilateral-to-Hexahedral mesh extruder.
Author
Peter Zajac
Definition at line 46 of file mesh_extruder.hpp.
Member Typedef Documentation
CoordType
template<typename Coord_ > typedef Coord_ FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::CoordType
Definition at line 49 of file mesh_extruder.hpp.
HexaAtlas
template<typename Coord_ > typedef MeshAtlas<HexaMesh> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaAtlas
Definition at line 55 of file mesh_extruder.hpp.
HexaAttrib
template<typename Coord_ > typedef HexaPart::AttributeSetType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaAttrib
Definition at line 76 of file mesh_extruder.hpp.
HexaChart
template<typename Coord_ > typedef Atlas::ChartBase<HexaMesh> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaChart
Definition at line 58 of file mesh_extruder.hpp.
HexaMesh
template<typename Coord_ > typedef ConformalMesh<Shape::Hypercube<3>, 3, Coord_> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaMesh
Definition at line 52 of file mesh_extruder.hpp.
HexaPart
template<typename Coord_ > typedef MeshPart<HexaMesh> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaPart
Definition at line 70 of file mesh_extruder.hpp.
HexaRootNode
template<typename Coord_ > typedef RootMeshNode<HexaMesh> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaRootNode
Definition at line 61 of file mesh_extruder.hpp.
HexaTopology
template<typename Coord_ > typedef HexaMesh::IndexSetHolderType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaTopology
Definition at line 67 of file mesh_extruder.hpp.
HexaTrgSetHolder
template<typename Coord_ > typedef HexaPart::TargetSetHolderType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaTrgSetHolder
Definition at line 73 of file mesh_extruder.hpp.
HexaVertexSet
template<typename Coord_ > typedef HexaMesh::VertexSetType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::HexaVertexSet
Definition at line 64 of file mesh_extruder.hpp.
QuadAtlas
template<typename Coord_ > typedef MeshAtlas<QuadMesh> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadAtlas
Definition at line 54 of file mesh_extruder.hpp.
QuadAttrib
template<typename Coord_ > typedef QuadPart::AttributeSetType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadAttrib
Definition at line 75 of file mesh_extruder.hpp.
QuadChart
template<typename Coord_ > typedef Atlas::ChartBase<QuadMesh> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadChart
Definition at line 57 of file mesh_extruder.hpp.
QuadMesh
template<typename Coord_ > typedef ConformalMesh<Shape::Hypercube<2>, 2, Coord_> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadMesh
Definition at line 51 of file mesh_extruder.hpp.
QuadPart
template<typename Coord_ > typedef MeshPart<QuadMesh> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadPart
Definition at line 69 of file mesh_extruder.hpp.
QuadRootNode
template<typename Coord_ > typedef RootMeshNode<QuadMesh> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadRootNode
Definition at line 60 of file mesh_extruder.hpp.
QuadTopology
template<typename Coord_ > typedef QuadMesh::IndexSetHolderType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadTopology
Definition at line 66 of file mesh_extruder.hpp.
QuadTrgSetHolder
template<typename Coord_ > typedef QuadPart::TargetSetHolderType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadTrgSetHolder
Definition at line 72 of file mesh_extruder.hpp.
QuadVertexSet
template<typename Coord_ > typedef QuadMesh::VertexSetType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::QuadVertexSet
Definition at line 63 of file mesh_extruder.hpp.
Constructor & Destructor Documentation
MeshExtruder() [1/2]
template<typename Coord_ > FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::MeshExtruder (Index slices, CoordType z_min, CoordType z_max, String zmin_part_name, String zmax_part_name) inline explicit
Creates the mesh extruder object.
Parameters
[in] slices The number of mesh slices in Z-direction. Must be > 0.
[in] z_min,z_max The minimal and maximal Z-coordinate for the extruded 3D mesh.
[in] zmin_part_name,zmax_part_name The names of the mesh-parts which are to be generated for the boundary regions at z_min and z_max. If set to an empty string, no mesh-part is generated for the corresponding boundary region.
Definition at line 109 of file mesh_extruder.hpp.
References XASSERT.
MeshExtruder() [2/2]
template<typename Coord_ > FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::MeshExtruder (const std::deque< CoordType > & z_list, String zmin_part_name, String zmax_part_name) inline explicit
Creates the mesh extruder object.
Parameters
[in] z_list A transient reference to the list of z-coordinates in ascending order.
[in] zmin_part_name,zmax_part_name The names of the mesh-parts which are to be generated for the boundary regions at z_min and z_max. If set to an empty string, no mesh-part is generated for the corresponding boundary region.
Definition at line 142 of file mesh_extruder.hpp.
References XASSERTM.
Member Function Documentation
extrude_atlas()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_atlas (HexaAtlas & hexa_atlas, const QuadAtlas & quad_atlas) const inline
Extrudes an quadrilateral mesh atlas.
This function extrudes all charts in the input quadrilateral mesh atlas and inserts the extruded charts into the hexahedral mesh atlas.
Parameters
[in,out] hexa_atlas A transient reference to the hexahedral mesh atlas that receives the extruded charts.
[in] quad_atlas A transient reference to the quadrilateral mesh atlas whose charts are to be extruded.
Definition at line 302 of file mesh_extruder.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::add_mesh_chart(), FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart(), FEAT::Geometry::MeshAtlas< Mesh_ >::get_chart_names(), and XASSERT.
extrude_attribute()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_attribute (std::unique_ptr< HexaAttrib > & hexa_attrib, const QuadAttrib & quad_attrib) const inline
Extrudes a quadrilateral mesh attribute.
Parameters
[out] hexa_attrib A transient reference to the hexahedral mesh attribute to be computed.
[in] quad_attrib A transient reference to the quadrilateral mesh attribute to be extruded.
Definition at line 634 of file mesh_extruder.hpp.
References FEAT::Geometry::AttributeSet< DataType_ >::get_dimension(), FEAT::Geometry::AttributeSet< DataType_ >::get_num_values(), and XASSERT.
extrude_chart()
template<typename Coord_ > std::unique_ptr< HexaChart > FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_chart (const QuadChart & quad_chart) const inline
Extrudes and returns a quadrilateral mesh chart.
Parameters
[in] quad_chart A transient reference to the chart that is to be extruded.
Returns
The extruded hexahedral chart.
Attention
The returned object must be deleted by the caller or inserted into an atlas.
Definition at line 270 of file mesh_extruder.hpp.
References XABORTM.
extrude_mapping()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_mapping (HexaTrgSetHolder & hexa_mapp, const QuadTrgSetHolder & quad_mapp, const QuadMesh & quad_parent) const inline
Extrudes a quadrilateral mapping (aka "target set holder")
Parameters
[in,out] hexa_mapp A transient reference to the hexahedral mapping to be computed. Is assumed to be allocated to the correct dimensions.
[in] quad_mapp A transient reference to the quadrilateral mapping to be extruded.
[in] quad_parent A transient reference to the quadrilateral parent mesh.
Definition at line 510 of file mesh_extruder.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities().
extrude_num_entities()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_num_entities (Index hexa_num_entities[], const Index quad_num_entities[]) const inline
Computes the extruded entity counts.
Parameters
[out] hexa_num_entities The array of length 4 that receives the extruded entity counts.
[in] quad_num_entities The array of length 3 to be extruded.
Definition at line 211 of file mesh_extruder.hpp.
References XASSERT.
extrude_partition()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition (Partition & hexa_parti, const Partition & quad_parti) const inline
Extrudes a quadrilateral mesh partitioning.
Parameters
[out] hexa_parti A transient reference to the hexahedral mesh partitioning to be computed.
[in] quad_parti A transient reference to the quadrilateral mesh partitioning to be extruded.
Definition at line 674 of file mesh_extruder.hpp.
References FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Geometry::Partition::get_level(), FEAT::Geometry::Partition::get_name(), FEAT::Geometry::Partition::get_num_elements(), FEAT::Adjacency::Graph::get_num_indices(), FEAT::Geometry::Partition::get_num_patches(), FEAT::Geometry::Partition::get_patches(), and FEAT::Geometry::Partition::get_priority().
extrude_partition_set()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_partition_set (PartitionSet & hexa_part_set, const PartitionSet & quad_part_set) const inline
Extrudes a quadrilateral mesh partition set.
Parameters
[out] hexa_part_set A transient reference to the hexahedral mesh partition set to be computed.
[in] quad_part_set A transient reference to the quadrilateral mesh partition set to be extruded.
Definition at line 720 of file mesh_extruder.hpp.
extrude_root_node()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_root_node (HexaRootNode & hexa_root_node, const QuadRootNode & quad_root_node, const HexaAtlas * hexa_atlas) const inline
Extrudes a quadrilateral root mesh node.
This function extrudes the root mesh as well as all mesh parts of the root node.
Attention
This function does not extrude the atlas of the root node.
Parameters
[in,out] hexa_root_node A transient reference to the hexahedral root mesh node that is to be created.
[in] quad_root_node A transient reference to the quadrilateral root mesh node that is to be extruded.
[in] hexa_atlas A resident hexahedral atlas that has already been extruded from the corresponding quadrilateral atlas. May be nullptr if there are no charts associated with the quadrilateral root mesh node.
Attention
Although the hexa_atlas reference itself is not stored in the hexa_root_node object, the mesh-part nodes inside the hexa_root_node may (and usually will) reference the chart objects stored inside the atlas. In consequence, destroying the hexa_atlas before hexa_root_node may (and usually will) result in orphaned references!
Definition at line 755 of file mesh_extruder.hpp.
References FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::add_mesh_part(), FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::find_mesh_part(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::find_mesh_part_chart_name(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh_part_names(), and XASSERT.
extrude_slice_mapping()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_slice_mapping (HexaTrgSetHolder & hexa_mapp, const QuadMesh & quad_parent, const Index slice) const inline
Definition at line 596 of file mesh_extruder.hpp.
extrude_topology()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_topology (HexaTopology & hexa_topo, const QuadTopology & quad_topo) const inline
Extrudes a quadrilateral topology (aka "index set holder").
Parameters
[in,out] hexa_topo A transient reference to the hexahedral topology to be computed. Must be allocated to the correct dimensions.
[in] quad_topo A transient reference to the quadrilateral topology to be extruded.
Definition at line 377 of file mesh_extruder.hpp.
References FEAT::Geometry::RedundantIndexSetBuilder< Shape_ >::compute(), and XASSERT.
extrude_vertex_set()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_vertex_set (HexaVertexSet & hexa_vtx, const QuadVertexSet & quad_vtx) const inline
Extrudes a quadrilateral vertex set.
Parameters
[in,out] hexa_vtx A transient reference to the hexahedral mesh vertex set that receives the extruded vertex set. Is assumed to be allocated to the correct size.
[in] quad_vtx A transient reference to the quadrilateral mesh vertex set that is to be extruded.
Definition at line 330 of file mesh_extruder.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::get_num_vertices(), FEAT::Tiny::Vector< T_, n_, s_ >::set_mat_vec_mult(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_3d(), and XASSERT.
set_angles()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::set_angles (CoordType yaw, CoordType pitch, CoordType roll) inline
Sets the transformation angles.
Parameters
[in] yaw,pitch,roll The yaw-pitch-roll angles for the transformation.
Definition at line 182 of file mesh_extruder.hpp.
set_offset()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::set_offset (CoordType x, CoordType y, CoordType z) inline
Sets the transformation offset.
Parameters
[in] x,y,z The coordinates of the 3D offset.
Definition at line 195 of file mesh_extruder.hpp.
set_origin()
template<typename Coord_ > void FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::set_origin (CoordType x, CoordType y) inline
Sets the transformation origin.
Parameters
[in] x,y The coordinates of the 2D origin.
Definition at line 170 of file mesh_extruder.hpp.
try_extrude_chart()
template<typename Coord_ > template<typename SubChart_ > bool FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::try_extrude_chart (std::unique_ptr< HexaChart > & hexa_chart, const QuadChart & quad_chart) const inline
Tries to extrudes a quadrilateral mesh chart.
Template Parameters
SubChart_ The type of the quadrilateral sub-chart that is to be tested.
Parameters
[out] hexa_chart A transient reference to the pointer to the hexa chart.
[in] quad_chart A transient reference to the chart that is to be extruded.
Returns
true, if the chart was extruded, otherwise false.
Definition at line 237 of file mesh_extruder.hpp.
Member Data Documentation
_angle_p
template<typename Coord_ > CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_angle_p protected
Definition at line 90 of file mesh_extruder.hpp.
_angle_r
template<typename Coord_ > CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_angle_r protected
Definition at line 90 of file mesh_extruder.hpp.
_angle_y
template<typename Coord_ > CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_angle_y protected
transformation angles
Definition at line 90 of file mesh_extruder.hpp.
_offset_x
template<typename Coord_ > CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_offset_x protected
transformation offset
Definition at line 92 of file mesh_extruder.hpp.
_offset_y
template<typename Coord_ > CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_offset_y protected
Definition at line 92 of file mesh_extruder.hpp.
_offset_z
template<typename Coord_ > CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_offset_z protected
Definition at line 92 of file mesh_extruder.hpp.
_origin_x
template<typename Coord_ > CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_origin_x protected
transformation origin
Definition at line 88 of file mesh_extruder.hpp.
_origin_y
template<typename Coord_ > CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_origin_y protected
Definition at line 88 of file mesh_extruder.hpp.
_slices
template<typename Coord_ > const Index FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_slices protected
the number of slices in z-direction
Definition at line 82 of file mesh_extruder.hpp.
_z_list
template<typename Coord_ > std::deque<CoordType> FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_z_list protected
deque of z-coordinates
Definition at line 80 of file mesh_extruder.hpp.
_z_max
template<typename Coord_ > const CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_z_max protected
Definition at line 84 of file mesh_extruder.hpp.
_z_min
template<typename Coord_ > const CoordType FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_z_min protected
minimal and maximal z-coordinate
Definition at line 84 of file mesh_extruder.hpp.
_zmax_part_name
template<typename Coord_ > String FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_zmax_part_name protected
Definition at line 86 of file mesh_extruder.hpp.
_zmin_part_name
template<typename Coord_ > String FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::_zmin_part_name protected
mesh-part names for z-min/max boundary regions
Definition at line 86 of file mesh_extruder.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/mesh_extruder.hpp