FEAT: FEAT::Solver::PCGNRILU< Matrix_, Filter_ > Class Template Reference
FEAT::Solver::PCGNRILU< Matrix_, Filter_ > Class Template Reference abstract
ILU(p)-preconditioned Conjugate-Gradient on Normal Equations solver implementation.
#include <pcgnrilu.hpp>
Public Types
typedef IterativeSolver< VectorType > BaseClass
typedef MatrixType::DataType DataType
typedef Filter_ FilterType
typedef MatrixType::IndexType IndexType
typedef Matrix_ MatrixType
typedef MatrixType::VectorTypeR VectorType
Public Member Functions
PCGNRILU (const MatrixType &matrix, const FilterType &filter, int ilu_p=-1)
Constructor.
PCGNRILU (const String &section_name, PropertyMap *section, const MatrixType &matrix, const FilterType &filter)
Constructor using a PropertyMap.
virtual ~PCGNRILU ()
Empty virtual destructor.
virtual Status apply (Vector_ &vec_cor, const Vector_ &vec_def)=0
Solver application method.
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def) override
DataType calc_convergence_rate () const
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
DataType calc_defect_reduction () const
Computes the overall defect reduction factor: (defect_final / defect_inital)
virtual Status correct (VectorType &vec_sol, const VectorType &vec_rhs) override
virtual Status correct (VectorType &vec_sol, const VectorType &vec_rhs)=0
Solver correction method.
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic () override
Symbolic finalization method.
DataType get_def_final () const
Returns the final defect.
DataType get_def_initial () const
Returns the initial defect.
DataType get_div_abs () const
Returns the absolute divergence.
DataType get_div_rel () const
Returns the relative divergence.
Index get_max_iter () const
Returns the maximum number of iterations.
Index get_min_iter () const
Returns the minimal number of iterations.
Index get_min_stag_iter () const
Returns the minimum stagnation iteration count.
Index get_num_iter () const
Returns number of performed iterations.
String get_plot_name () const
Returns the plot name of the solver.
DataType get_stag_rate () const
Returns the stagnation rate.
Status get_status () const
Returns the status.
virtual String get_summary () const
Returns a summary string.
DataType get_tol_abs () const
Returns the absolute tolerance.
DataType get_tol_abs_low () const
Returns the lower absolute tolerance.
DataType get_tol_rel () const
Returns the relative tolerance.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric initialization method.
virtual void init_symbolic () override
Symbolic initialization method.
bool is_converged () const
checks for convergence
bool is_converged (const DataType def_cur) const
checks for convergence
bool is_diverged () const
checks for divergence
bool is_diverged (const DataType def_cur) const
checks for divergence
virtual String name () const override
Returns a descriptive string.
virtual void plot_summary () const
Plot a summary of the last solver run.
void set_div_abs (DataType div_abs)
Sets the absolute divergence for the solver.
void set_div_rel (DataType div_rel)
Sets the relative divergence for the solver.
void set_fill_in_param (int p)
Sets the fill-in parameter.
void set_max_iter (Index max_iter)
Sets the maximum iteration count for the solver.
void set_min_iter (Index min_iter)
Sets the minimum iteration count for the solver.
void set_min_stag_iter (Index min_iter)
Sets the minimum stagnate iteration count for the solver.
void set_plot_interval (const Index plot_interval)
Sets the interval between two plot outputs, if any.
void set_plot_mode (const PlotMode plot_mode)
Sets the plot mode of the solver.
void set_plot_name (const String &plot_name)
Sets the plot name of the solver.
void set_stag_rate (DataType rate)
Sets the stagnation rate fot the solver.
void set_tol_abs (DataType tol_abs)
Sets the absolute tolerance for the solver.
void set_tol_abs_low (DataType tol_abs_low)
Sets the lower absolute tolerance for the solver.
void set_tol_rel (DataType tol_rel)
Sets the relative tolerance for the solver.
void skip_defect_calc (bool skip)
Specifies whether defect calculation is allowed to be skipped.
Protected Member Functions
virtual Status _analyse_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag)
Internal function: analyse the current defect.
virtual Status _apply_intern (VectorType &vec_x)
virtual DataType _calc_def_norm (const VectorType &vec_def, const VectorType &vec_sol)
Computes the defect norm.
bool _plot_iter (Status st=Status::progress) const
Plot the current iteration?
virtual void _plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev)
Plots an iteration line.
bool _plot_summary () const
Plot summary?
void _precond_l (VectorType &vec_c, const VectorType &vec_q)
void _precond_r (VectorType &vec_c, const VectorType &vec_q)
void _print_line (const String &line) const
Prints a line.
bool _progress () const
Progress iteration?
void _set_comm (const Dist::Comm *comm)
Sets the communicator for the solver directly.
void _set_comm_by_matrix (const Matrix_ &matrix)
Sets the communicator for the solver from a matrix.
void _set_comm_by_vector (const Matrix_::VectorTypeR &vector)
Sets the communicator for the solver from a vector.
virtual Status _set_initial_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the initial defect vector.
virtual Status _set_new_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the new (next) defect vector.
virtual Status _update_defect (const DataType def_cur_norm)
Internal function: sets the new (next) defect norm.
Protected Attributes
const Dist::Comm * _comm
Communicator of the solver.
DataType _def_cur
current defect
DataType _def_init
initial defect
DataType _def_prev
previous iteration defect
DataType _div_abs
absolute divergence parameter
DataType _div_rel
relative divergence parameter
Intern::ILUCoreScalar< DataType, IndexType > _ilu
ilu factorization data
int _ilu_p
ilu fill-in
Index _iter_digits
iteration count digits for plotting
Index _max_iter
maximum number of iterations
Index _min_iter
minimum number of iterations
Index _min_stag_iter
minimum number of stagnation iterations
Index _num_iter
number of performed iterations
Index _num_stag_iter
number of consecutive stagnated iterations
Index _plot_interval
plot output interval
PlotMode _plot_mode
whether to plot something
String _plot_name
name of the solver in plots
bool _skip_def_calc
whether to skip defect computation if possible
DataType _stag_rate
stagnation rate
Status _status
current status of the solver
const FilterType & _system_filter
the filter for the solver
const MatrixType & _system_matrix
the matrix for the solver
DataType _tol_abs
absolute tolerance parameter
DataType _tol_abs_low
absolute tolerance parameter
DataType _tol_rel
relative tolerance parameter
MatrixType _transp_matrix
the transposed system matrix
VectorType _vec_p
VectorType _vec_q
VectorType _vec_r
temporary vectors
VectorType _vec_s
VectorType _vec_t
Detailed Description
template<typename Matrix_, typename Filter_>
class FEAT::Solver::PCGNRILU< Matrix_, Filter_ >
ILU(p)-preconditioned Conjugate-Gradient on Normal Equations solver implementation.
Let \(M = LU\) denote the ILU(p)-factorization of a (possibly unsymmetric and indefinite) system matrix \(A\), then this class implements a Conjugate-Gradient solver applied onto the preconditioned normal equation system:
\[ \underbrace{(U^{-\top}A^\top L^{-\top} L^{-1}AU^{-1})}_{\widetilde{A}} ~\cdot~\underbrace{(U x)}_{\widetilde{x}}~=~ \underbrace{(U^{-\top}A^\top L^{-\top} L^{-1} b)}_{\widetilde{b}}\]
Attention
This solver implementation is experimental. Do not use it unless you know exactly what you are doing!
Note
This class implements a special case of the more generic PCGNR solver with the preconditioners \(M_L = LL^\top\) and \(M_R = U^\top U\).
Template Parameters
Matrix_ The matrix class to be used by the solver.
Filter_ The filter class to be used by the solver.
Author
Peter Zajac
Definition at line 45 of file pcgnrilu.hpp.
Member Typedef Documentation
BaseClass
template<typename Matrix_ , typename Filter_ > typedef IterativeSolver<VectorType> FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::BaseClass
Definition at line 54 of file pcgnrilu.hpp.
DataType
template<typename Matrix_ , typename Filter_ > typedef MatrixType::DataType FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::DataType
Definition at line 52 of file pcgnrilu.hpp.
FilterType
template<typename Matrix_ , typename Filter_ > typedef Filter_ FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::FilterType
Definition at line 50 of file pcgnrilu.hpp.
IndexType
template<typename Matrix_ , typename Filter_ > typedef MatrixType::IndexType FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::IndexType
Definition at line 53 of file pcgnrilu.hpp.
MatrixType
template<typename Matrix_ , typename Filter_ > typedef Matrix_ FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::MatrixType
Definition at line 49 of file pcgnrilu.hpp.
VectorType
template<typename Matrix_ , typename Filter_ > typedef MatrixType::VectorTypeR FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::VectorType
Definition at line 51 of file pcgnrilu.hpp.
Constructor & Destructor Documentation
PCGNRILU() [1/2]
template<typename Matrix_ , typename Filter_ > FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::PCGNRILU (const MatrixType & matrix, const FilterType & filter, int ilu_p = -1) inline explicit
Constructor.
Parameters
[in] matrix A reference to the system matrix.
[in] filter A reference to the system filter.
[in] ilu_p Maximum allowed fill-in for ILU preconditioner. Set to -1 to disable preconditioning.
Definition at line 83 of file pcgnrilu.hpp.
References FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_comm_by_matrix().
PCGNRILU() [2/2]
template<typename Matrix_ , typename Filter_ > FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::PCGNRILU (const String & section_name, PropertyMap * section, const MatrixType & matrix, const FilterType & filter) inline explicit
Constructor using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Definition at line 109 of file pcgnrilu.hpp.
References FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu_p, FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_comm_by_matrix(), and FEAT::PropertyMap::query().
~PCGNRILU()
template<typename Matrix_ , typename Filter_ > virtual FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::~PCGNRILU () inline virtual
Empty virtual destructor.
Definition at line 127 of file pcgnrilu.hpp.
Member Function Documentation
_analyse_defect()
virtual Status FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_analyse_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag) inline protected virtual inherited
Internal function: analyse the current defect.
Note
This function is called by _set_new_defect() and _update_defect().
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
[in] check_stag Specifies whether to check (and update) the stagnation criterion. This is typically set to false if one wants to check anything else than the 'true' next defect norm.
Returns
The updated status code.
Definition at line 797 of file iterative.hpp.
_apply_intern()
template<typename Matrix_ , typename Filter_ > virtual Status FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_apply_intern (VectorType & vec_x) inline protected virtual
Todo:
use axpby here
Definition at line 248 of file pcgnrilu.hpp.
References FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_new_defect(), FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_num_iter(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::name(), FEAT::Solver::progress, and FEAT::Solver::undefined.
_calc_def_norm()
virtual DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_calc_def_norm (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Computes the defect norm.
Parameters
[in] vec_def The current defect vector.
[in] vec_sol The current solution vector approximation.
Definition at line 650 of file iterative.hpp.
_plot_iter()
bool FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_plot_iter (Status st = Status::progress) const inline protected inherited
Plot the current iteration?
Parameters
[in] st The status of the current iteration.
Returns
true if the plot mode is set to iter or all and the plot interval matches or the solver does not continue to the next iteration
Definition at line 664 of file iterative.hpp.
_plot_iter_line()
virtual void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev) inline protected virtual inherited
Plots an iteration line.
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
Definition at line 717 of file iterative.hpp.
_plot_summary()
bool FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_plot_summary () const inline protected inherited
Plot summary?
Returns
true if the plot mode is set to summary or all.
Definition at line 675 of file iterative.hpp.
_precond_l()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_precond_l (VectorType & vec_c, const VectorType & vec_q) inline protected
Definition at line 226 of file pcgnrilu.hpp.
_precond_r()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_precond_r (VectorType & vec_c, const VectorType & vec_q) inline protected
Definition at line 237 of file pcgnrilu.hpp.
_print_line()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_print_line (const String & line) const inline protected inherited
Prints a line.
Parameters
[in] line The line to be printed.
Definition at line 696 of file iterative.hpp.
_progress()
bool FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_progress () const inline protected inherited
Progress iteration?
Returns
true if the solver should process, otherwise false.
Definition at line 685 of file iterative.hpp.
_set_comm()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_comm (const Dist::Comm * comm) inline protected inherited
Sets the communicator for the solver directly.
Parameters
[in] comm A pointer to the communicator that is to be used by the solver.
Definition at line 611 of file iterative.hpp.
_set_comm_by_matrix()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_comm_by_matrix (const Matrix_ & matrix) inline protected inherited
Sets the communicator for the solver from a matrix.
Parameters
[in] matrix A reference to a matrix. If 'Matrix_' is a 'Global::Matrix', then the communicator of the matrix gate is taken.
Definition at line 624 of file iterative.hpp.
_set_comm_by_vector()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_comm_by_vector (const Matrix_::VectorTypeR & vector) inline protected inherited
Sets the communicator for the solver from a vector.
Parameters
[in] vector A reference to a vector. If 'Vector_' is a 'Global::Vector', then the communicator of the vector gate is taken.
Definition at line 636 of file iterative.hpp.
_set_initial_defect()
virtual Status FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_initial_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Internal function: sets the initial defect vector.
Parameters
[in] vec_def The initial defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Definition at line 746 of file iterative.hpp.
_set_new_defect()
virtual Status FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_set_new_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Internal function: sets the new (next) defect vector.
This function computes the defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] vec_def The new defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Definition at line 855 of file iterative.hpp.
_update_defect()
virtual Status FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_update_defect (const DataType def_cur_norm) inline protected virtual inherited
Internal function: sets the new (next) defect norm.
This function takes a precalculated defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] def_cur_norm The new defect norm.
Returns
The updated Status code.
Note
This function is preferred over _set_new_defect when using asynchronous mpi operations.
Definition at line 901 of file iterative.hpp.
apply() [1/2]
template<typename Vector_ > virtual Status FEAT::Solver::SolverBase< Vector_ >::apply (Vector_ & vec_cor, const Vector_ & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::CuSolverLU, FEAT::Solver::CuSolverQR, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, and FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >.
Referenced by FEAT::Solver::solve().
apply() [2/2]
template<typename Matrix_ , typename Filter_ > virtual Status FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::apply (VectorType & vec_cor, const VectorType & vec_def) inline override virtual
Definition at line 191 of file pcgnrilu.hpp.
calc_convergence_rate()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::calc_convergence_rate () const inline inherited
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
Definition at line 526 of file iterative.hpp.
calc_defect_reduction()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::calc_defect_reduction () const inline inherited
Computes the overall defect reduction factor: (defect_final / defect_inital)
Definition at line 541 of file iterative.hpp.
correct() [1/2]
template<typename Matrix_ , typename Filter_ > virtual Status FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::correct (VectorType & vec_sol, const VectorType & vec_rhs) inline override virtual
Definition at line 209 of file pcgnrilu.hpp.
correct() [2/2]
virtual Status FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::correct (VectorType & vec_sol, const VectorType & vec_rhs) pure virtual inherited
Solver correction method.
This method applies the solver represented by this object onto a given right-hand-side vector and updates the corresponding solution vector.
In contrast to the apply() method of the SolverBase base class, this method uses the vector vec_sol as the initial solution vector for the iterative solution process instead of ignoring its contents upon entry and starting with the null vector.
Parameters
[in,out] vec_sol The vector that contains the initial solution upon entry and receives the solution of the linear system upon exit.
[in] vec_rhs The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_sol and vec_rhs must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
done()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric(), and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
done_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented in FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >.
Definition at line 246 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::done(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::done_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_numeric(), FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::done_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric().
done_symbolic()
template<typename Matrix_ , typename Filter_ > virtual void FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::done_symbolic () inline override virtual
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 166 of file pcgnrilu.hpp.
References FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu, and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
get_def_final()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_def_final () const inline inherited
Returns the final defect.
Definition at line 514 of file iterative.hpp.
get_def_initial()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_def_initial () const inline inherited
Returns the initial defect.
Definition at line 508 of file iterative.hpp.
get_div_abs()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_div_abs () const inline inherited
Returns the absolute divergence.
Definition at line 361 of file iterative.hpp.
get_div_rel()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_div_rel () const inline inherited
Returns the relative divergence.
Definition at line 355 of file iterative.hpp.
get_max_iter()
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_max_iter () const inline inherited
Returns the maximum number of iterations.
Definition at line 416 of file iterative.hpp.
get_min_iter()
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_min_iter () const inline inherited
Returns the minimal number of iterations.
Definition at line 410 of file iterative.hpp.
get_min_stag_iter()
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_min_stag_iter () const inline inherited
Returns the minimum stagnation iteration count.
Definition at line 385 of file iterative.hpp.
get_num_iter()
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_num_iter () const inline inherited
Returns number of performed iterations.
Definition at line 404 of file iterative.hpp.
get_plot_name()
String FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_plot_name () const inline inherited
Returns the plot name of the solver.
Definition at line 465 of file iterative.hpp.
get_stag_rate()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_stag_rate () const inline inherited
Returns the stagnation rate.
Definition at line 373 of file iterative.hpp.
get_status()
Status FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_status () const inline inherited
Returns the status.
Definition at line 520 of file iterative.hpp.
get_summary()
virtual String FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_summary () const inline virtual inherited
Returns a summary string.
Definition at line 554 of file iterative.hpp.
get_tol_abs()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_tol_abs () const inline inherited
Returns the absolute tolerance.
Definition at line 330 of file iterative.hpp.
get_tol_abs_low()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_tol_abs_low () const inline inherited
Returns the lower absolute tolerance.
Definition at line 336 of file iterative.hpp.
get_tol_rel()
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::get_tol_rel () const inline inherited
Returns the relative tolerance.
Definition at line 324 of file iterative.hpp.
init()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
init_numeric()
template<typename Matrix_ , typename Filter_ > virtual void FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_numeric () inline override virtual
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 179 of file pcgnrilu.hpp.
References FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu_p, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_system_matrix, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_transp_matrix, and FEAT::Solver::SolverBase< Vector_ >::init_numeric().
init_symbolic()
template<typename Matrix_ , typename Filter_ > virtual void FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 148 of file pcgnrilu.hpp.
References FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu_p, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_vec_r, and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
is_converged() [1/2]
bool FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::is_converged () const inline inherited
checks for convergence
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Returns
true, if converged, else false
Definition at line 476 of file iterative.hpp.
is_converged() [2/2]
bool FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::is_converged (const DataType def_cur) const inline inherited
checks for convergence
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Parameters
[in] def_cur The defect that is to be analysed
Returns
true, if converged, else false
Definition at line 490 of file iterative.hpp.
is_diverged() [1/2]
bool FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::is_diverged () const inline inherited
checks for divergence
Definition at line 496 of file iterative.hpp.
is_diverged() [2/2]
bool FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::is_diverged (const DataType def_cur) const inline inherited
checks for divergence
Definition at line 502 of file iterative.hpp.
name()
template<typename Matrix_ , typename Filter_ > virtual String FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::name () const inline override virtual
Returns a descriptive string.
Returns
A string describing the solver.
Implements FEAT::Solver::SolverBase< Vector_ >.
Definition at line 143 of file pcgnrilu.hpp.
Referenced by FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_apply_intern().
plot_summary()
virtual void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::plot_summary () const inline virtual inherited
Plot a summary of the last solver run.
Definition at line 571 of file iterative.hpp.
set_div_abs()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_div_abs (DataType div_abs) inline inherited
Sets the absolute divergence for the solver.
Definition at line 349 of file iterative.hpp.
set_div_rel()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_div_rel (DataType div_rel) inline inherited
Sets the relative divergence for the solver.
Definition at line 343 of file iterative.hpp.
set_fill_in_param()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::set_fill_in_param (int p) inline
Sets the fill-in parameter.
Parameters
[in] p The new fill-in parameter
Definition at line 137 of file pcgnrilu.hpp.
References FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu_p, and XASSERT.
set_max_iter()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_max_iter (Index max_iter) inline inherited
Sets the maximum iteration count for the solver.
Definition at line 397 of file iterative.hpp.
set_min_iter()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_min_iter (Index min_iter) inline inherited
Sets the minimum iteration count for the solver.
Definition at line 391 of file iterative.hpp.
set_min_stag_iter()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_min_stag_iter (Index min_iter) inline inherited
Sets the minimum stagnate iteration count for the solver.
Definition at line 379 of file iterative.hpp.
set_plot_interval()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_plot_interval (const Index plot_interval) inline inherited
Sets the interval between two plot outputs, if any.
Parameters
[in] plot_interval The desired interval of iteration plots
Definition at line 453 of file iterative.hpp.
set_plot_mode()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_plot_mode (const PlotMode plot_mode) inline inherited
Sets the plot mode of the solver.
Parameters
[in] plot_mode The desired plot mode
Definition at line 443 of file iterative.hpp.
set_plot_name()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_plot_name (const String & plot_name) inline inherited
Sets the plot name of the solver.
Definition at line 459 of file iterative.hpp.
set_stag_rate()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_stag_rate (DataType rate) inline inherited
Sets the stagnation rate fot the solver.
Definition at line 367 of file iterative.hpp.
set_tol_abs()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_tol_abs (DataType tol_abs) inline inherited
Sets the absolute tolerance for the solver.
Definition at line 312 of file iterative.hpp.
set_tol_abs_low()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_tol_abs_low (DataType tol_abs_low) inline inherited
Sets the lower absolute tolerance for the solver.
Definition at line 318 of file iterative.hpp.
set_tol_rel()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::set_tol_rel (DataType tol_rel) inline inherited
Sets the relative tolerance for the solver.
Definition at line 306 of file iterative.hpp.
skip_defect_calc()
void FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::skip_defect_calc (bool skip) inline inherited
Specifies whether defect calculation is allowed to be skipped.
Warning
Skipping defect calculation can lead to deadlocks in parallel solver implementations if one (but not all) processes need to compute the defect for some reason (like plotting) !
Use this function only when you really know what you are doing!
Parameters
[in] skip Specifies whether defect computation is allowed to be skipped.
Definition at line 432 of file iterative.hpp.
Member Data Documentation
_comm
const Dist::Comm* FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_comm protected inherited
Communicator of the solver.
Definition at line 129 of file iterative.hpp.
_def_cur
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_def_cur protected inherited
current defect
Definition at line 180 of file iterative.hpp.
_def_init
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_def_init protected inherited
initial defect
Definition at line 178 of file iterative.hpp.
_def_prev
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_def_prev protected inherited
previous iteration defect
Definition at line 182 of file iterative.hpp.
_div_abs
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_div_abs protected inherited
absolute divergence parameter
Definition at line 164 of file iterative.hpp.
_div_rel
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_div_rel protected inherited
relative divergence parameter
Definition at line 162 of file iterative.hpp.
_ilu
template<typename Matrix_ , typename Filter_ > Intern::ILUCoreScalar<DataType, IndexType> FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu protected
ilu factorization data
Definition at line 68 of file pcgnrilu.hpp.
Referenced by FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::done_symbolic(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_numeric(), and FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_symbolic().
_ilu_p
template<typename Matrix_ , typename Filter_ > int FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_ilu_p protected
ilu fill-in
Definition at line 66 of file pcgnrilu.hpp.
Referenced by FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::PCGNRILU(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_symbolic(), and FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::set_fill_in_param().
_iter_digits
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_iter_digits protected inherited
iteration count digits for plotting
Definition at line 184 of file iterative.hpp.
_max_iter
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_max_iter protected inherited
maximum number of iterations
Definition at line 170 of file iterative.hpp.
_min_iter
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_min_iter protected inherited
minimum number of iterations
Definition at line 168 of file iterative.hpp.
_min_stag_iter
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_min_stag_iter protected inherited
minimum number of stagnation iterations
Definition at line 174 of file iterative.hpp.
_num_iter
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_num_iter protected inherited
number of performed iterations
Definition at line 172 of file iterative.hpp.
_num_stag_iter
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_num_stag_iter protected inherited
number of consecutive stagnated iterations
Definition at line 176 of file iterative.hpp.
_plot_interval
Index FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_plot_interval protected inherited
plot output interval
Definition at line 188 of file iterative.hpp.
_plot_mode
PlotMode FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_plot_mode protected inherited
whether to plot something
Definition at line 186 of file iterative.hpp.
_plot_name
String FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_plot_name protected inherited
name of the solver in plots
Definition at line 131 of file iterative.hpp.
_skip_def_calc
bool FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_skip_def_calc protected inherited
whether to skip defect computation if possible
Definition at line 190 of file iterative.hpp.
_stag_rate
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_stag_rate protected inherited
stagnation rate
Definition at line 166 of file iterative.hpp.
_status
Status FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_status protected inherited
current status of the solver
Definition at line 133 of file iterative.hpp.
_system_filter
template<typename Matrix_ , typename Filter_ > const FilterType& FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_system_filter protected
the filter for the solver
Definition at line 60 of file pcgnrilu.hpp.
_system_matrix
template<typename Matrix_ , typename Filter_ > const MatrixType& FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_system_matrix protected
the matrix for the solver
Definition at line 58 of file pcgnrilu.hpp.
Referenced by FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_numeric().
_tol_abs
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_tol_abs protected inherited
absolute tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 158 of file iterative.hpp.
_tol_abs_low
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_tol_abs_low protected inherited
absolute tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 160 of file iterative.hpp.
_tol_rel
DataType FEAT::Solver::IterativeSolver< Matrix_::VectorTypeR >::_tol_rel protected inherited
relative tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 156 of file iterative.hpp.
_transp_matrix
template<typename Matrix_ , typename Filter_ > MatrixType FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_transp_matrix protected
the transposed system matrix
Definition at line 62 of file pcgnrilu.hpp.
Referenced by FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_numeric().
_vec_p
template<typename Matrix_ , typename Filter_ > VectorType FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_vec_p protected
Definition at line 64 of file pcgnrilu.hpp.
_vec_q
template<typename Matrix_ , typename Filter_ > VectorType FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_vec_q protected
Definition at line 64 of file pcgnrilu.hpp.
_vec_r
template<typename Matrix_ , typename Filter_ > VectorType FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_vec_r protected
temporary vectors
Definition at line 64 of file pcgnrilu.hpp.
Referenced by FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_symbolic().
_vec_s
template<typename Matrix_ , typename Filter_ > VectorType FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_vec_s protected
Definition at line 64 of file pcgnrilu.hpp.
_vec_t
template<typename Matrix_ , typename Filter_ > VectorType FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::_vec_t protected
Definition at line 64 of file pcgnrilu.hpp.
The documentation for this class was generated from the following file:
kernel/solver/pcgnrilu.hpp