FEAT: FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ > Class Template Reference
FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ > Class Template Reference
Factory for SparseMatrix construction.
#include <sparse_matrix_factory.hpp>
Public Member Functions
SparseMatrixFactory (Index num_rows, Index num_cols)
Constructor.
void add (Index i, Index j, DT_ a_ij)
Adds a new matrix entry to the factory.
Index columns () const
Returns number of columns.
SparseMatrixCSR< DT_, IT_ > make_csr () const
Returns CSR matrix constructed from Map.
Index rows () const
Returns number of rows.
Index size () const
Returns product of number columns and number rows.
Index used_elements () const
Returns number of used elements.
Private Attributes
Index _num_col
Number of columns for the created matrix.
Index _num_row
Number of rows for the created matrix.
std::map< IT_, DT_ > memory
Map collecting the input for the matrix.
Static Private Attributes
static constexpr IT_ max_size = IT_(100000u)
Maximal size of matrix.
Detailed Description
template<typename DT_, typename IT_>
class FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >
Factory for SparseMatrix construction.
The purpose of this class is to make implementing CSR matrices very simple.
The data is stored in a map and can be transfered to a CSR matrix.
Template Parameters
DT_ The data type to be used for the sparse matrix.
IT_ The index type to be used for the sparse matrix.
Author
Gesa Pottbrock
Definition at line 37 of file sparse_matrix_factory.hpp.
Constructor & Destructor Documentation
SparseMatrixFactory()
template<typename DT_ , typename IT_ > FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::SparseMatrixFactory (Index num_rows, Index num_cols) inline explicit
Constructor.
Parameters
[in] num_rows The number of rows for the matrix.
[in] num_cols The number of columns for the matrix.
Definition at line 57 of file sparse_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::max_size, and XASSERTM.
Member Function Documentation
add()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::add (Index i, Index j, DT_ a_ij) inline
Adds a new matrix entry to the factory.
Parameters
[in] i The row-index of the entry to be added.
[in] j The column-index of the entry to be added.
[in] a_ij The value of the entry to be added.
Definition at line 71 of file sparse_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_col, FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_row, ASSERTM, FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::max_size, and FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::memory.
columns()
template<typename DT_ , typename IT_ > Index FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::columns () const inline
Returns number of columns.
Returns
Number of matrix columns.
Definition at line 83 of file sparse_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_col.
make_csr()
template<typename DT_ , typename IT_ > SparseMatrixCSR< DT_, IT_ > FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::make_csr () const inline
Returns CSR matrix constructed from Map.
Returns
CSR Matrix.
Definition at line 121 of file sparse_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_col, FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_row, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::max_size, FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::memory, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
rows()
template<typename DT_ , typename IT_ > Index FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::rows () const inline
Returns number of rows.
Returns
Number of matrix rows.
Definition at line 92 of file sparse_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_row.
size()
template<typename DT_ , typename IT_ > Index FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::size () const inline
Returns product of number columns and number rows.
Returns
Number of possible matrix entries.
Definition at line 101 of file sparse_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_col, and FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_row.
used_elements()
template<typename DT_ , typename IT_ > Index FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::used_elements () const inline
Returns number of used elements.
Returns
Number of used elements.
Definition at line 111 of file sparse_matrix_factory.hpp.
References FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::memory.
Member Data Documentation
_num_col
template<typename DT_ , typename IT_ > Index FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_col private
Number of columns for the created matrix.
Definition at line 43 of file sparse_matrix_factory.hpp.
Referenced by FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::add(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::make_csr(), and FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::size().
_num_row
template<typename DT_ , typename IT_ > Index FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::_num_row private
Number of rows for the created matrix.
Definition at line 41 of file sparse_matrix_factory.hpp.
Referenced by FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::add(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::make_csr(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::size().
max_size
template<typename DT_ , typename IT_ > constexpr IT_ FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::max_size = IT_(100000u) static constexpr private
Maximal size of matrix.
Definition at line 45 of file sparse_matrix_factory.hpp.
Referenced by FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::SparseMatrixFactory(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::add(), and FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::make_csr().
memory
template<typename DT_ , typename IT_ > std::map<IT_, DT_> FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::memory private
Map collecting the input for the matrix.
Definition at line 47 of file sparse_matrix_factory.hpp.
Referenced by FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::add(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::make_csr(), and FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::used_elements().
The documentation for this class was generated from the following file:
kernel/lafem/sparse_matrix_factory.hpp