FEAT: FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ > Class Template Reference
FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ > Class Template Reference
Blocked Dense data vector class template.
#include <dense_vector_blocked.hpp>
Classes
class GatherAxpy
Gather-Axpy operation for DenseVectorBlocked.
class ScatterAxpy
Scatter-Axpy operation for DenseVectorBlocked.
Public Types
template<typename DT2_ = DT_, typename IT2_ = IT_>
using ContainerType = DenseVectorBlocked< DT2_, IT2_, BlockSize_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a vector container with different Data and Index types
typedef DT_ DataType
Our datatype.
typedef IT_ IndexType
Our indextype.
typedef Tiny::Vector< DT_, BlockSize_ > ValueType
Our value type.
Public Member Functions
DenseVectorBlocked ()
Constructor.
DenseVectorBlocked (const DenseVector< DT_, IT_ > &other)
Constructor.
DenseVectorBlocked (const DenseVectorBlocked &dv_in, Index size_in, Index offset_in)
Constructor.
DenseVectorBlocked (DenseVectorBlocked &&other)
Move Constructor.
DenseVectorBlocked (FileMode mode, const String &filename)
Constructor.
DenseVectorBlocked (FileMode mode, std::istream &file)
Constructor.
DenseVectorBlocked (Index size_in)
Constructor.
DenseVectorBlocked (Index size_in, DT_ *data)
Constructor.
DenseVectorBlocked (Index size_in, DT_ value)
Constructor.
DenseVectorBlocked (Random &rng, Index size_in, DataType min, DataType max)
Constructor.
template<typename DT2_ = DT_, typename IT2_ = IT_>
DenseVectorBlocked (std::vector< char > input)
Constructor.
virtual ~DenseVectorBlocked ()
Destructor.
std::size_t bytes () const
Returns the total amount of bytes allocated.
virtual void clear ()
Free all allocated arrays.
DenseVectorBlocked clone (CloneMode clone_mode=CloneMode::Deep) const
Clone operation.
void clone (const Container &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const Container< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const DenseVectorBlocked< DT2_, IT2_, BlockSize_ > &other, CloneMode clone_mode=CloneMode::Deep)
Clone operation.
template<typename DT2_ , typename IT2_ >
void convert (const DenseVector< DT2_, IT2_ > &other)
Conversion method.
template<typename DT2_ , typename IT2_ >
void convert (const DenseVectorBlocked< DT2_, IT2_, BlockSize_ > &other)
Conversion method.
void copy (const DenseVectorBlocked &x, bool full=false)
Performs \(this \leftarrow x\).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void deserialize (std::vector< char > input)
Deserialization of complete container entity.
template<Perspective perspective_ = Perspective::native>
auto elements () -> typename Intern::DenseVectorBlockedPerspectiveHelper< DT_, BlockSize_, perspective_ >::Type *
template<Perspective perspective_ = Perspective::native>
auto elements () const -> const typename Intern::DenseVectorBlockedPerspectiveHelper< DT_, BlockSize_, perspective_ >::Type *
Retrieve a pointer to the data array.
bool empty () const
Checks whether the container is empty.
void format (DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DT_ min, DT_ max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (const LAFEM::SerialConfig &config)
Calculate size.
const std::vector< DT_ * > & get_elements () const
Returns a list of all data arrays.
const std::vector< Index > & get_elements_size () const
Returns a list of all data array sizes.
const std::vector< IT_ * > & get_indices () const
Returns a list of all Index arrays.
const std::vector< Index > & get_indices_size () const
Returns a list of all Index array sizes.
const std::vector< DT_ > & get_scalar_dt () const
Returns a list of all scalar values with datatype dt.
const std::vector< Index > & get_scalar_index () const
Returns a list of all scalar values with datatype index.
void move (Container &&other)
Assignment move operation.
const Tiny::Vector< DT_, BlockSize_ > operator() (Index index) const
Retrieve specific vector element.
void operator() (Index index, const Tiny::Vector< DT_, BlockSize_ > &value)
Set specific vector element.
DenseVectorBlocked & operator= (DenseVectorBlocked &&other)
Assignment move operator.
void permute (Adjacency::Permutation &perm)
Permutate vector according to the given Permutation.
template<typename DT2_ , typename IT2_ >
void project_onto (DenseVectorBlocked< DT_, IT_, BlockSize_ > &projected_vector, const LAFEM::DenseVectorBlocked< DT2_, IT2_, BlockSize_ > &normal_vector) const
Projects this vector onto a another one.
void read_from (FileMode mode, const String &filename)
Read in vector from file.
void read_from (FileMode mode, std::istream &file)
Read in vector from stream.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > serialize (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Serialization of complete container entity.
std::uint64_t set_checkpoint_data (std::vector< char > &data, const LAFEM::SerialConfig &config)
template<Perspective perspective_ = Perspective::native>
Index size () const
The number of elements.
template<Perspective = Perspective::native>
Index used_elements () const
Returns the number of effective stored elements.
void write_out (FileMode mode, const String &filename) const
Write out vector to file.
void write_out (FileMode mode, std::ostream &file) const
Write out vector to file.
Linear algebra operations
void axpy (const DenseVectorBlocked &x, const DT_ alpha=DT_(1))
Calculate \(this \leftarrow \alpha~ x + this\).
void axpy_blocked (const DenseVectorBlocked &x, const ValueType alpha)
Calculate \(this \leftarrow \alpha~ x + this\).
void component_product (const DenseVectorBlocked &x, const DenseVectorBlocked &y)
Calculate \(this_i \leftarrow x_i \cdot y_i\).
void component_copy (const DenseVector< DT_, IT_ > &x, const int block_)
Copies the elements of a dense vector into a specific block of this blocked vector.
void component_copy_to (DenseVector< DT_, IT_ > &x, const int block_) const
Copies the elements of a specific block of this blocked vector into a dense vector.
void component_invert (const DenseVectorBlocked &x, const DT_ alpha=DT_(1))
Performs \(this_i \leftarrow \alpha / x_i \).
void scale (const DenseVectorBlocked &x, const DT_ alpha)
Calculate \(this \leftarrow \alpha~ x \).
void scale_blocked (const DenseVectorBlocked &x, const ValueType alpha)
Calculate \(this \leftarrow \alpha~ x \).
DataType triple_dot (const DenseVectorBlocked &x, const DenseVectorBlocked &y) const
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
ValueType triple_dot_blocked (const DenseVectorBlocked &x, const DenseVectorBlocked &y) const
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
DataType dot (const DenseVectorBlocked &x) const
Calculate \(this \leftarrow this \cdot x\).
ValueType dot_blocked (const DenseVectorBlocked &x) const
Calculate \(this \leftarrow this \cdot x\).
DT_ norm2 () const
Calculates and returns the euclid norm of this vector.
ValueType norm2_blocked () const
Calculates and returns the euclid norm of this vector.
DT_ norm2sqr () const
Calculates and returns the squared euclid norm of this vector.
ValueType norm2sqr_blocked () const
Calculates and returns the squared euclid norm of this vector.
DT_ max_abs_element () const
Retrieve the absolute maximum value of this vector.
ValueType max_abs_element_blocked () const
Retrieve the absolute maximum value of this vector.
DT_ min_abs_element () const
Retrieve the absolute minimum value of this vector.
ValueType min_abs_element_blocked () const
Retrieve the absolute minimum value of this vector.
DT_ max_element () const
Retrieve the maximum value of this vector.
ValueType max_element_blocked () const
Retrieve the maximum value of this vector.
DT_ min_element () const
Retrieve the minimum value of this vector.
ValueType min_element_blocked () const
Retrieve the minimum value of this vector.
Static Public Member Functions
static String name ()
Returns a descriptive string.
Static Public Attributes
static constexpr int BlockSize = BlockSize_
Our size of a single block.
Protected Member Functions
void _copy_content (const Container &other, bool full)
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::istream &file)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::vector< char > &input)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > _serialize (FileMode mode, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _serialize (FileMode mode, std::ostream &file, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::uint64_t _serialized_size (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Calculation of the serialized size with optional compression of complete container entity.
template<typename DT2_ , typename IT2_ >
void assign (const Container< DT2_, IT2_ > &other)
Assignment operation.
Protected Attributes
std::vector< DT_ * > _elements
List of pointers to all datatype dependent arrays.
std::vector< Index > _elements_size
List of corresponding datatype array sizes.
bool _foreign_memory
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
std::vector< IT_ * > _indices
List of pointers to all IT_ dependent arrays.
std::vector< Index > _indices_size
List of corresponding IT_ array sizes.
std::vector< DT_ > _scalar_dt
List of scalars with datatype DT_.
std::vector< Index > _scalar_index
List of scalars with datatype index.
Private Member Functions
Index & _size ()
Friends
std::ostream & operator<< (std::ostream &lhs, const DenseVectorBlocked &b)
DenseVectorBlocked streaming operator.
bool operator== (const DenseVectorBlocked &a, const DenseVectorBlocked &b)
DenseVectorBlocked comparison operator.
Detailed Description
template<typename DT_, typename IT_, int BlockSize_>
class FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >
Blocked Dense data vector class template.
Template Parameters
DT_ The datatype to be used.
IT_ The indextype to be used.
BlockSize_ The size of the represented blocks
This class represents a vector of continuous data in memory.
Logical, the data are organized in small blocks of BlockSize_ length.
Data survey:
_elements[0]: raw number values
_scalar_index[0]: container size - aka block count _scalar_index[1]: boolean flag, signaling DenseVectorRange usage
Refer to LAFEM design description for general usage informations.
Author
Dirk Ribbrock
Definition at line 79 of file dense_vector_blocked.hpp.
Member Typedef Documentation
ContainerType
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::ContainerType = DenseVectorBlocked<DT2_, IT2_, BlockSize_>
Our 'base' class type.
Definition at line 93 of file dense_vector_blocked.hpp.
ContainerTypeByDI
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a vector container with different Data and Index types
Definition at line 97 of file dense_vector_blocked.hpp.
DataType
template<typename DT_ , typename IT_ , int BlockSize_> typedef DT_ FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DataType
Our datatype.
Definition at line 83 of file dense_vector_blocked.hpp.
IndexType
template<typename DT_ , typename IT_ , int BlockSize_> typedef IT_ FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::IndexType
Our indextype.
Definition at line 85 of file dense_vector_blocked.hpp.
ValueType
template<typename DT_ , typename IT_ , int BlockSize_> typedef Tiny::Vector<DT_, BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::ValueType
Our value type.
Definition at line 89 of file dense_vector_blocked.hpp.
Constructor & Destructor Documentation
DenseVectorBlocked() [1/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked () inline explicit
Constructor.
Creates an empty non dimensional vector.
Definition at line 191 of file dense_vector_blocked.hpp.
DenseVectorBlocked() [2/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (Index size_in) inline explicit
Constructor.
Parameters
[in] size_in The size of the created vector. aka block count
Creates a vector with a given block count.
Definition at line 204 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, and FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
DenseVectorBlocked() [3/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (Index size_in, DT_ value) inline explicit
Constructor.
Parameters
[in] size_in The size of the created vector.
[in] value The value, each element will be set to.
Creates a vector with given size and value.
Definition at line 226 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::MemoryPool::set_memory().
DenseVectorBlocked() [4/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (Index size_in, DT_ * data) inline explicit
Constructor.
Parameters
[in] size_in The block count of the created vector.
[in] data An array containing the value data.
Creates a vector with given size and given data.
Definition at line 246 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::increase_memory().
DenseVectorBlocked() [5/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (const DenseVector< DT_, IT_ > & other) inline explicit
Constructor.
Parameters
[in] other The source DenseVector.
Creates a vector from a DenseVector source
Definition at line 268 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert().
DenseVectorBlocked() [6/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & dv_in, Index size_in, Index offset_in) inline explicit
Constructor.
Parameters
[in] dv_in The source DenseVectorBlocked
[in] size_in The (native) size of the created vector range.
[in] offset_in The (native) starting element of the created vector range in relation to the source vector.
Creates a vector range from a given DenseVectorBlocked
Note
The created DenseVectorBlocked has no own memory management nor own allocated memory and should be used carefully!
Definition at line 285 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory.
DenseVectorBlocked() [7/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (FileMode mode, const String & filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a vector from the given source file.
Definition at line 303 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from().
DenseVectorBlocked() [8/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (FileMode mode, std::istream & file) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The stream that is to be read from.
Creates a vector from the given source file.
Definition at line 317 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from().
DenseVectorBlocked() [9/11]
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (std::vector< char > input) inline explicit
Constructor.
Parameters
[in] input A std::vector, containing the byte.
Creates a vector from the given byte array.
Definition at line 331 of file dense_vector_blocked.hpp.
DenseVectorBlocked() [10/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (Random & rng, Index size_in, DataType min, DataType max) inline explicit
Constructor.
Parameters
[in] rng The random number generator.
[in] size_in The vector size.
[in] min Lower rng bound.
[in] max Upper rng bound.
Creates a vector from the given random number generator.
Definition at line 347 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::LAFEM::Container< DT_, IT_ >::format().
DenseVectorBlocked() [11/11]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked (DenseVectorBlocked< DT_, IT_, BlockSize_ > && other) inline
Move Constructor.
Parameters
[in] other The source vector.
Moves another vector to this vector.
Definition at line 366 of file dense_vector_blocked.hpp.
~DenseVectorBlocked()
template<typename DT_ , typename IT_ , int BlockSize_> virtual FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::~DenseVectorBlocked () inline virtual
Destructor.
Definition at line 374 of file dense_vector_blocked.hpp.
Member Function Documentation
_copy_content()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::_copy_content (const Container< DT_, IT_ > & other, bool full) inline protected inherited
Definition at line 240 of file container.hpp.
_deserialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::istream & file) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file std::istream, pointing to the input data.
Recreate a complete container entity by a single binary file.
Definition at line 780 of file container.hpp.
References XABORTM.
_deserialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::vector< char > & input) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] input A std::vector containing the byte array.
Recreate a complete container entity by a single binary array.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 626 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Pack::decode(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Type::Helper::extract_floatness(), FEAT::Type::Helper::extract_intness(), FEAT::Type::Helper::extract_signedness(), FEAT::Type::Helper::extract_type_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, XABORTM, XASSERT, and XASSERTM.
_serialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
Array data layout:
raw array size in bytes (std::uint64_t)
magic number (std::uint64_t)
DT_ 'hash' value (sizeof(DT_) and floating/integral distinction (packed std::uint64_t)
IT_ 'hash' value (sizeof(IT_) and floating/integral distinction (packed std::uint64_t)
_elements.size() (std::uint64_t)
_indices.size() (std::uint64_t)
_elements_size.size() (std::uint64_t)
_indices_size.size() (std::uint64_t)
_scalar_index.size() (std::uint64_t)
_scalar_dt.size() (std::uint64_t)
_compressed (std::uint64_t)
_elements_size array (std::uint64_t)
_elements arrays byte_size (std::uint64_t) just temporary to read in data
_indices_size array (std::uint64_t)
_indices arrays byte_size (std::uint64_t)
_scalar_index array (std::uint64_t)
_scalar_dt array (DT2_)
_elements arrays (DT2_)
_indices arrays (IT2_)
See FEAT::LAFEM::SerialConfig for details.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 444 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XASSERTM.
_serialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, std::ostream & file, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file The output stream to write data into.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary file with compression enabled. See FEAT::LAFEM::SerialConfig for details.
Definition at line 609 of file container.hpp.
References XABORTM.
_serialized_size()
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline protected inherited
Calculation of the serialized size with optional compression of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Returns
An unsigned int containing the size of serialized container.
Calculate the size of the serialized container entity.
Definition at line 361 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), and FEAT::LAFEM::indices_zlib.
_size()
template<typename DT_ , typename IT_ , int BlockSize_> Index & FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::_size () inline private
Definition at line 180 of file dense_vector_blocked.hpp.
assign()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::assign (const Container< DT2_, IT2_ > & other) inline protected inherited
Assignment operation.
Assigns contents of another container
Parameters
[in] other The source container.
Definition at line 280 of file container.hpp.
References FEAT::MemoryPool::convert(), FEAT::MemoryPool::increase_memory(), FEAT::MemoryPool::release_memory(), and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::convert(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute().
axpy()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::axpy (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const DT_ alpha = DT_(1)) inline
Calculate \(this \leftarrow \alpha~ x + this\).
Parameters
[in] x The first summand vector to be scaled.
[in] y The second summand vector
[in] alpha A scalar to multiply x with.
Definition at line 807 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::pod, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
axpy_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::axpy_blocked (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const ValueType alpha) inline
Calculate \(this \leftarrow \alpha~ x + this\).
Parameters
[in] x The first summand vector to be scaled.
[in] y The second summand vector
[in] alpha A Tiny::Vector to multiply x with.
Definition at line 831 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::native, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
Referenced by FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), and FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol().
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::LAFEM::Container< DT_, IT_ >::bytes () const inline inherited
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 1042 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes().
clear()
template<typename DT_ , typename IT_ > virtual void FEAT::LAFEM::Container< DT_, IT_ >::clear () inline virtual inherited
Free all allocated arrays.
Definition at line 875 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from().
clone() [1/4]
template<typename DT_ , typename IT_ , int BlockSize_> DenseVectorBlocked FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Clone operation.
Create a clone of this container.
Parameters
[in] clone_mode The actual cloning procedure.
Definition at line 401 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone().
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clone().
clone() [2/4]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 902 of file container.hpp.
References FEAT::LAFEM::Allocate, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Deep, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Layout, FEAT::LAFEM::Shallow, FEAT::LAFEM::Weak, XABORTM, and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVector< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone().
clone() [3/4]
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 975 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), and FEAT::LAFEM::Container< DT_, IT_ >::clone().
clone() [4/4]
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone (const DenseVectorBlocked< DT2_, IT2_, BlockSize_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clone operation.
Create a clone of this container.
Parameters
[in] other The source container to create the clone from.
[in] clone_mode The actual cloning procedure.
Definition at line 417 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clone().
component_copy()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_copy (const DenseVector< DT_, IT_ > & x, const int block_) inline
Copies the elements of a dense vector into a specific block of this blocked vector.
Parameters
[in] x The vector to be copied.
[in] block_ The index of the block in the target vector where the elements should be copied.
Definition at line 875 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::native, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
component_copy_to()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_copy_to (DenseVector< DT_, IT_ > & x, const int block_) const inline
Copies the elements of a specific block of this blocked vector into a dense vector.
Parameters
[in] x The vector which will contain the copies.
[in] block_ The index of the block of this blocked vector from where the elements should be copied.
Definition at line 895 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::native, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
component_invert()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_invert (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const DT_ alpha = DT_(1)) inline
Performs \(this_i \leftarrow \alpha / x_i \).
Parameters
[in] x The vector whose components serve as denominators.
[in] alpha The nominator.
Definition at line 918 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::pod, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
component_product()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_product (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const DenseVectorBlocked< DT_, IT_, BlockSize_ > & y) inline
Calculate \(this_i \leftarrow x_i \cdot y_i\).
Parameters
[in] x The first factor.
[in] y The second factor.
Definition at line 855 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::pod, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
convert() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert (const DenseVector< DT2_, IT2_ > & other) inline
Conversion method.
Parameters
[in] other The source scalar vector.
Use source scalar vector content as content of current vector
Definition at line 443 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
convert() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert (const DenseVectorBlocked< DT2_, IT2_, BlockSize_ > & other) inline
Conversion method.
Parameters
[in] other The source vector.
Use source vector content as content of current vector
Definition at line 430 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign().
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::write_out().
copy()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The vector to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 580 of file dense_vector_blocked.hpp.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
deserialize()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::deserialize (std::vector< char > input) inline
Deserialization of complete container entity.
Parameters
[in] input A std::vector, containing the byte array.
Recreate a complete container entity by a single binary array.
Definition at line 468 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::fm_dvb.
dot()
template<typename DT_ , typename IT_ , int BlockSize_> DataType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::dot (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x) const inline
Calculate \(this \leftarrow this \cdot x\).
Parameters
[in] x The other vector.
Returns
The calculated dot product.
Definition at line 1026 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::pod, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
dot_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::dot_blocked (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x) const inline
Calculate \(this \leftarrow this \cdot x\).
Parameters
[in] x The other vector.
Returns
The calculated blocked dot product (A Tiny::Vector).
Definition at line 1048 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::native, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
Referenced by FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), and FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol().
elements() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> template<Perspective perspective_ = Perspective::native> auto FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements () -> typename Intern::DenseVectorBlockedPerspectiveHelper<DT_, BlockSize_, perspective_>::Type * inline
non const version.
Definition at line 512 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size().
elements() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> template<Perspective perspective_ = Perspective::native> auto FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements () const -> const typename Intern::DenseVectorBlockedPerspectiveHelper<DT_, BlockSize_, perspective_>::Type * inline
Retrieve a pointer to the data array.
Template Parameters
perspective_ template parameter to choose the return value type
Returns
Non zero element array if perspective_ = Perspective::native, e.g. treat every block as one block.
Raw non zero element array if perspective_ = Perspective::pod, e.g. treat every entry of a block separated.
Definition at line 501 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size().
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorP_, MirrorV_ > >::_asm_local_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorP_, MirrorV_ > >::_premult_da(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::set_sd_v_norm(), and FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::set_sd_v_norm().
empty()
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::empty () const inline inherited
Checks whether the container is empty.
Returns
true if the container is empty, otherwise false.
Definition at line 1165 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::MeanFilterBlocked(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol(), and FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic().
format() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (DT_ value = DT_(0)) inline inherited
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 851 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::MemoryPool::set_memory(), and FEAT::value.
Referenced by FEAT::Assembly::CellErrorFunctionIntegralJob< Function_, Vector_, Space_, max_der_ >::CellErrorFunctionIntegralJob(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply_transposed(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorP_, MirrorV_ > >::init_numeric(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), FEAT::Assembly::CellErrorFunctionIntegralJob< Function_, Vector_, Space_, max_der_ >::result(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
format() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (Random & rng, DT_ min, DT_ max) inline inherited
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 864 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, and FEAT::MemoryPool::set_memory().
get_checkpoint_size()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::get_checkpoint_size (const LAFEM::SerialConfig & config) inline inherited
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1018 of file container.hpp.
get_elements()
template<typename DT_ , typename IT_ > const std::vector< DT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements () const inline inherited
Returns a list of all data arrays.
Returns
A list of all data arrays.
Definition at line 1068 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
get_elements_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size () const inline inherited
Returns a list of all data array sizes.
Returns
A list of all data array sizes.
Definition at line 1088 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
get_indices()
template<typename DT_ , typename IT_ > const std::vector< IT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices () const inline inherited
Returns a list of all Index arrays.
Returns
A list of all Index arrays.
Definition at line 1078 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
get_indices_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size () const inline inherited
Returns a list of all Index array sizes.
Returns
A list of all Index array sizes.
Definition at line 1098 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices_size.
get_scalar_dt()
template<typename DT_ , typename IT_ > const std::vector< DT_ > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt () const inline inherited
Returns a list of all scalar values with datatype dt.
Returns
A list of all scalars with datatype dt.
Definition at line 1118 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt.
get_scalar_index()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index () const inline inherited
Returns a list of all scalar values with datatype index.
Returns
A list of all scalars with datatype index.
Definition at line 1108 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
max_abs_element()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::max_abs_element () const inline
Retrieve the absolute maximum value of this vector.
Returns
The largest absolute value.
Definition at line 1133 of file dense_vector_blocked.hpp.
References FEAT::Math::abs(), ASSERT, and FEAT::TimeStamp::elapsed().
max_abs_element_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::max_abs_element_blocked () const inline
Retrieve the absolute maximum value of this vector.
Returns
The largest blocked absolute value (A Tiny::Vector).
Definition at line 1154 of file dense_vector_blocked.hpp.
References FEAT::TimeStamp::elapsed().
max_element()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::max_element () const inline
Retrieve the maximum value of this vector.
Returns
The largest value.
Definition at line 1209 of file dense_vector_blocked.hpp.
References ASSERT, and FEAT::TimeStamp::elapsed().
max_element_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::max_element_blocked () const inline
Retrieve the maximum value of this vector.
Returns
The largest blocked value (A Tiny::Vector).
Definition at line 1229 of file dense_vector_blocked.hpp.
References FEAT::TimeStamp::elapsed().
min_abs_element()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::min_abs_element () const inline
Retrieve the absolute minimum value of this vector.
Returns
The smallest absolute value.
Definition at line 1171 of file dense_vector_blocked.hpp.
References FEAT::Math::abs(), ASSERT, and FEAT::TimeStamp::elapsed().
min_abs_element_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::min_abs_element_blocked () const inline
Retrieve the absolute minimum value of this vector.
Returns
The smallest blocked absolute value (A Tiny::Vector).
Definition at line 1192 of file dense_vector_blocked.hpp.
References FEAT::TimeStamp::elapsed().
min_element()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::min_element () const inline
Retrieve the minimum value of this vector.
Returns
The smallest value.
Definition at line 1246 of file dense_vector_blocked.hpp.
References ASSERT, and FEAT::TimeStamp::elapsed().
min_element_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::min_element_blocked () const inline
Retrieve the minimum value of this vector.
Returns
The smallest blocked value (A Tiny::Vector).
Definition at line 1266 of file dense_vector_blocked.hpp.
References FEAT::TimeStamp::elapsed().
move()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::move (Container< DT_, IT_ > && other) inline inherited
Assignment move operation.
Move another container to the current one.
Parameters
[in] other The source container.
Definition at line 989 of file container.hpp.
References FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
name()
template<typename DT_ , typename IT_ , int BlockSize_> static String FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 569 of file dense_vector_blocked.hpp.
norm2()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::norm2 () const inline
Calculates and returns the euclid norm of this vector.
Returns
The calculated norm.
Definition at line 1068 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), and FEAT::TimeStamp::elapsed().
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::norm2sqr().
norm2_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::norm2_blocked () const inline
Calculates and returns the euclid norm of this vector.
Returns
The calculated blocked norm (A Tiny::Vector).
Definition at line 1086 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), and FEAT::TimeStamp::elapsed().
norm2sqr()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::norm2sqr () const inline
Calculates and returns the squared euclid norm of this vector.
Returns
The calculated norm.
Definition at line 1104 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::norm2(), and FEAT::Math::sqr().
norm2sqr_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::norm2sqr_blocked () const inline
Calculates and returns the squared euclid norm of this vector.
Returns
The calculated blocked norm (A Tiny::Vector).
Definition at line 1115 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), and FEAT::TimeStamp::elapsed().
operator()() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> const Tiny::Vector< DT_, BlockSize_ > FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator() (Index index) const inline
Retrieve specific vector element.
Parameters
[in] index The index of the vector element.
Returns
Specific Tiny::Vector element.
Definition at line 542 of file dense_vector_blocked.hpp.
References ASSERT, and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size().
operator()() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator() (Index index, const Tiny::Vector< DT_, BlockSize_ > & value) inline
Set specific vector element.
Parameters
[in] index The index of the vector element.
[in] value The value to be set.
Definition at line 557 of file dense_vector_blocked.hpp.
References ASSERT, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and FEAT::value.
operator=()
template<typename DT_ , typename IT_ , int BlockSize_> DenseVectorBlocked & FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator= (DenseVectorBlocked< DT_, IT_, BlockSize_ > && other) inline
Assignment move operator.
Parameters
[in] other The source vector.
Moves another vector to the target vector.
Returns
The vector moved to.
Definition at line 387 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::move().
permute()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::permute (Adjacency::Permutation & perm) inline
Permutate vector according to the given Permutation.
Definition at line 1281 of file dense_vector_blocked.hpp.
References FEAT::Adjacency::Permutation::apply(), FEAT::Adjacency::Permutation::size(), and XASSERTM.
project_onto()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::project_onto (DenseVectorBlocked< DT_, IT_, BlockSize_ > & projected_vector, const LAFEM::DenseVectorBlocked< DT2_, IT2_, BlockSize_ > & normal_vector) const inline
Projects this vector onto a another one.
Parameters
[out] projected_vector A correctly allocated vector which will be overriden with the projected data
[in] normal_vector The vector to be projected on.
Note
The normal vector does not need to be normalized, which in turn leads to the vectors being scaled by the magintude of the entries, besides the projection.
Definition at line 1373 of file dense_vector_blocked.hpp.
References FEAT::Tiny::project_onto(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
read_from() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from (FileMode mode, const String & filename) inline
Read in vector from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 591 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::fm_mtx, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from().
read_from() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from (FileMode mode, std::istream & file) inline
Read in vector from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Definition at line 609 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_dvb, FEAT::LAFEM::fm_exp, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::Container< DT_, IT_ >::move(), and XABORTM.
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::restore_from_checkpoint_data (std::vector< char > & data) inline inherited
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1024 of file container.hpp.
References FEAT::LAFEM::fm_binary.
scale()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::scale (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const DT_ alpha) inline
Calculate \(this \leftarrow \alpha~ x \).
Parameters
[in] x The vector to be scaled.
[in] alpha A scalar to scale x with.
Definition at line 937 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::pod, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
scale_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::scale_blocked (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const ValueType alpha) inline
Calculate \(this \leftarrow \alpha~ x \).
Parameters
[in] x The vector to be scaled.
[in] alpha A Tiny::Vector to scale x with.
Definition at line 956 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::native, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
serialize()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::serialize (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline
Serialization of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
See FEAT::LAFEM::Container::_serialize for details.
Definition at line 487 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::fm_dvb.
set_checkpoint_data()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::set_checkpoint_data (std::vector< char > & data, const LAFEM::SerialConfig & config) inline inherited
Definition at line 1030 of file container.hpp.
References FEAT::LAFEM::fm_binary.
size()
template<typename DT_ , typename IT_ , int BlockSize_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size () const inline
The number of elements.
Returns
number of elements of type Tiny::Vector<DT_, Blocksize_> if perspective_ = false, e.g. count every block as one entry.
Raw number of elements of type DT_ if perspective_ = true, e.g. size * BlockSize_
Definition at line 527 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size().
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorP_, MirrorV_ > >::_asm_local_schur_matrix(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::OldroydAssembler::assemble_matrix(), FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_scalar_matrix(), FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_vector(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_vector(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_vector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::axpy(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::axpy_blocked(), FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_copy(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_copy_to(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_invert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::component_product(), FEAT::Assembly::VelocityAnalyser::compute(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::dot(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::dot_blocked(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_def(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_def(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::Assembly::FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >::interpolate(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::project_onto(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::scale(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::scale_blocked(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::set_sd_v_norm(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::set_sd_v_norm(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::triple_dot_blocked().
triple_dot()
template<typename DT_ , typename IT_ , int BlockSize_> DataType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::triple_dot (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const DenseVectorBlocked< DT_, IT_, BlockSize_ > & y) const inline
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
Parameters
[in] x The first vector.
[in] y The second vector.
Returns
The computed triple dot product.
Definition at line 978 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), and XASSERTM.
triple_dot_blocked()
template<typename DT_ , typename IT_ , int BlockSize_> ValueType FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::triple_dot_blocked (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const DenseVectorBlocked< DT_, IT_, BlockSize_ > & y) const inline
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
Parameters
[in] x The first vector.
[in] y The second vector.
Returns
The computed blocked triple dot product (A Tiny::Vector).
Definition at line 1003 of file dense_vector_blocked.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::native, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
used_elements()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::used_elements () const inline inherited
Returns the number of effective stored elements.
Returns
The number of data values.
The template parameter of type Perspective is used in block containers to switch between the raw number of used elements and the number of used elements, when every block is counted as one entry.
Definition at line 1155 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::invert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows(), and FEAT::LAFEM::DenseMatrix< DT_, IT_ >::write_out().
write_out() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::write_out (FileMode mode, const String & filename) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] filename The file where the vector shall be stored.
Definition at line 730 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::FileOutStreamBufferSize, FEAT::LAFEM::fm_exp, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::write_out().
write_out() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::write_out (FileMode mode, std::ostream & file) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
Definition at line 756 of file dense_vector_blocked.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_dvb, FEAT::LAFEM::fm_exp, FEAT::LAFEM::fm_mtx, FEAT::MemoryPool::release_memory(), FEAT::stringify_fp_sci(), and XABORTM.
Friends And Related Function Documentation
operator<<
template<typename DT_ , typename IT_ , int BlockSize_> std::ostream & operator<< (std::ostream & lhs, const DenseVectorBlocked< DT_, IT_, BlockSize_ > & b) friend
DenseVectorBlocked streaming operator.
Parameters
[in] lhs The target stream.
[in] b The vector to be streamed.
Definition at line 1349 of file dense_vector_blocked.hpp.
operator==
template<typename DT_ , typename IT_ , int BlockSize_> bool operator== (const DenseVectorBlocked< DT_, IT_, BlockSize_ > & a, const DenseVectorBlocked< DT_, IT_, BlockSize_ > & b) friend
DenseVectorBlocked comparison operator.
Parameters
[in] a A vector to compare with.
[in] b A vector to compare with.
Definition at line 1311 of file dense_vector_blocked.hpp.
Member Data Documentation
_elements
template<typename DT_ , typename IT_ > std::vector<DT_*> FEAT::LAFEM::Container< DT_, IT_ >::_elements protected inherited
List of pointers to all datatype dependent arrays.
Definition at line 226 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
_elements_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_elements_size protected inherited
List of corresponding datatype array sizes.
Definition at line 230 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_foreign_memory
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory protected inherited
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
Definition at line 238 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), and FEAT::LAFEM::Container< DT_, IT_ >::clear().
_indices
template<typename DT_ , typename IT_ > std::vector<IT_*> FEAT::LAFEM::Container< DT_, IT_ >::_indices protected inherited
List of pointers to all IT_ dependent arrays.
Definition at line 228 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseVector< DT_, IT_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
_indices_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_indices_size protected inherited
List of corresponding IT_ array sizes.
Definition at line 232 of file container.hpp.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_scalar_dt
template<typename DT_ , typename IT_ > std::vector<DT_> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt protected inherited
List of scalars with datatype DT_.
Definition at line 236 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), and FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt().
_scalar_index
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index protected inherited
List of scalars with datatype index.
Definition at line 234 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::Container(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVector< DT_, IT_ >::allocated_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::sorted(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size().
BlockSize
template<typename DT_ , typename IT_ , int BlockSize_> constexpr int FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::BlockSize = BlockSize_ static constexpr
Our size of a single block.
Definition at line 87 of file dense_vector_blocked.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/dense_vector_blocked.hpp