FEAT: FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ > Class Template Reference
FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ > Class Template Reference abstract
Chart CRTP base-class template.
#include <chart.hpp>
Public Types
typedef PartType::AttributeSetType AttributeSetType
attribute type of our mesh-part
typedef ChartBase< Mesh_ > BaseClass
base-class type
typedef VertexSetType::CoordType CoordType
coordinate type
typedef BaseClass::MeshType MeshType
mesh type
typedef Tiny::Vector< CoordType, param_dim > ParamPoint
out parameter type
typedef BaseClass::PartType PartType
mesh-part type
typedef Traits_ TraitsType
traits type
typedef MeshType::VertexSetType VertexSetType
vertex set type of our mesh
typedef BaseClass::WorldPoint WorldPoint
our world point type
Public Member Functions
virtual void adapt (MeshType &mesh, const PartType &part) const override
Adapts a whole MeshPart.
virtual void adapt (PartType &parent_meshpart, const PartType &meshpart) const override
Adapts a whole MeshPart referring to another MeshPart.
virtual std::size_t bytes () const
virtual bool can_explicit () const override
Specifies whether the chart can perform explicit projection.
virtual bool can_implicit () const override
Specifies whether the chart can perform implicit projection.
virtual CoordType dist (const WorldPoint &point) const override
Computes the distance of a point to this chart.
virtual CoordType dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual String get_type () const =0
Writes the type as String.
virtual WorldPoint map (const WorldPoint &param) const override
Maps a parameter to a world point.
virtual WorldPoint project (const WorldPoint &point) const override
Projects a point onto the chart.
virtual CoordType signed_dist (const WorldPoint &point) const override
Computes the signed distance of a point to this chart.
virtual CoordType signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset)=0
Applies a "proper rigid" transformation onto the chart.
virtual void write (std::ostream &os, const String &sindent) const =0
Writes the Chart into a stream in XML format.
Static Public Attributes
static constexpr bool is_explicit = TraitsType::is_explicit
specifies whether this chart is explicit
static constexpr bool is_implicit = TraitsType::is_implicit
specifies whether this chart is implicit
static constexpr int param_dim = TraitsType::param_dim
the parameter dimension of this chart
static constexpr int world_dim = TraitsType::world_dim
the world dimension of this chart
Protected Member Functions
Derived_ & cast ()
Casts this to its true type.
const Derived_ & cast () const
Casts this to its true type.
Detailed Description
template<typename Derived_, typename Mesh_, typename Traits_>
class FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >
Chart CRTP base-class template.
This class template acts as a CRTP base-class for the actual chart implementations.
Template Parameters
Derived_ The derived class.
Mesh_ The mesh class to be parameterized by this chart class.
Traits_ A traits class that specifies the chart's properties.
Author
Peter Zajac
Definition at line 352 of file chart.hpp.
Member Typedef Documentation
AttributeSetType
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef PartType::AttributeSetType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::AttributeSetType
attribute type of our mesh-part
Definition at line 365 of file chart.hpp.
BaseClass
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef ChartBase<Mesh_> FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::BaseClass
base-class type
Definition at line 357 of file chart.hpp.
CoordType
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef VertexSetType::CoordType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::CoordType
coordinate type
Definition at line 369 of file chart.hpp.
MeshType
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef BaseClass::MeshType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::MeshType
mesh type
Definition at line 361 of file chart.hpp.
ParamPoint
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef Tiny::Vector<CoordType, param_dim> FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::ParamPoint
out parameter type
Definition at line 385 of file chart.hpp.
PartType
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef BaseClass::PartType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::PartType
mesh-part type
Definition at line 363 of file chart.hpp.
TraitsType
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef Traits_ FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::TraitsType
traits type
Definition at line 359 of file chart.hpp.
VertexSetType
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef MeshType::VertexSetType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::VertexSetType
vertex set type of our mesh
Definition at line 367 of file chart.hpp.
WorldPoint
template<typename Derived_ , typename Mesh_ , typename Traits_ > typedef BaseClass::WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::WorldPoint
our world point type
Definition at line 383 of file chart.hpp.
Member Function Documentation
adapt() [1/2]
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual void FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::adapt (MeshType & mesh, const PartType & part) const inline override virtual
Adapts a whole MeshPart.
Parameters
[in] mesh Mesh to be adapted
[in] part MeshPart identifying the region to be adapted
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 420 of file chart.hpp.
References FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast(), FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::world_dim, XABORTM, and XASSERTM.
adapt() [2/2]
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual void FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::adapt (PartType & parent_meshpart, const PartType & meshpart) const inline override virtual
Adapts a whole MeshPart referring to another MeshPart.
Parameters
[in] parent_meshpart MeshPart to be adapted
[in] meshpart MeshPart identifying the region to be adapted
Todo:
: Implement this
There is currently no code that uses MeshParts referring to other MeshParts instead of a RootMesh.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 450 of file chart.hpp.
References XABORTM.
bytes()
template<typename Mesh_ > virtual std::size_t FEAT::Geometry::Atlas::ChartBase< Mesh_ >::bytes () const inline virtual inherited
Returns
The size of dynamically allocated memory in bytes.
Reimplemented in FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >.
Definition at line 52 of file chart.hpp.
can_explicit()
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual bool FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::can_explicit () const inline override virtual
Specifies whether the chart can perform explicit projection.
Returns
true if explicit projection is possible, otherwise false.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Reimplemented in FEAT::Geometry::Atlas::Bezier< Mesh_ >, FEAT::Geometry::Atlas::Circle< Mesh_ >, and FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >.
Definition at line 400 of file chart.hpp.
References FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::is_explicit.
can_implicit()
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual bool FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::can_implicit () const inline override virtual
Specifies whether the chart can perform implicit projection.
Returns
true if implicit projection is possible, otherwise false.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Reimplemented in FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >.
Definition at line 406 of file chart.hpp.
References FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::is_implicit.
cast() [1/2]
template<typename Derived_ , typename Mesh_ , typename Traits_ > Derived_ & FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast () inline protected
Casts this to its true type.
Returns
A Derived_ reference to this
Definition at line 393 of file chart.hpp.
Referenced by FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::adapt(), FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::dist(), FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::map(), FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::project(), and FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::signed_dist().
cast() [2/2]
template<typename Derived_ , typename Mesh_ , typename Traits_ > const Derived_ & FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast () const inline protected
Casts this to its true type.
Returns
A Derived_ reference to this\ifile "/github/workspace/kernel/geometry/atlas/chart.hpp"
Definition at line 396 of file chart.hpp.
dist() [1/2]
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::dist (const WorldPoint & point) const inline override virtual
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 475 of file chart.hpp.
References FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast().
dist() [2/2]
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 481 of file chart.hpp.
References FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast().
get_type()
template<typename Mesh_ > virtual String FEAT::Geometry::Atlas::ChartBase< Mesh_ >::get_type () const pure virtual inherited
Writes the type as String.
Needed for writing this to mesh files.
Returns
The class name as String.
Implemented in FEAT::Geometry::Atlas::Bezier< Mesh_ >, FEAT::Geometry::Atlas::Circle< Mesh_ >, FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >, FEAT::Geometry::Atlas::Sphere< Mesh_ >, and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >.
map()
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::map (const WorldPoint & param) const inline override virtual
Maps a parameter to a world point.
Parameters
[in] param The parameter to be mapped.
Returns
The mapped world point.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 456 of file chart.hpp.
References ASSERTM, FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast(), and FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::is_explicit.
project()
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::project (const WorldPoint & point) const inline override virtual
Projects a point onto the chart.
Parameters
[in] point The point to be projected.
Returns
The projected point.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 466 of file chart.hpp.
References ASSERTM, FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast(), and FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::is_implicit.
signed_dist() [1/2]
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::signed_dist (const WorldPoint & point) const inline override virtual
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 487 of file chart.hpp.
References FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast().
signed_dist() [2/2]
template<typename Derived_ , typename Mesh_ , typename Traits_ > virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 493 of file chart.hpp.
References FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::cast().
transform()
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::ChartBase< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) pure virtual inherited
Applies a "proper rigid" transformation onto the chart.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any point x of the chart:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any point before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): -ignored-
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any point after applying the rotation.
write()
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::ChartBase< Mesh_ >::write (std::ostream & os, const String & sindent) const pure virtual inherited
Writes the Chart into a stream in XML format.
Parameters
[in,out] os The output stream to write into.
[in] sindent The indentation string.
Implemented in FEAT::Geometry::Atlas::Bezier< Mesh_ >, FEAT::Geometry::Atlas::Circle< Mesh_ >, FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >, FEAT::Geometry::Atlas::Sphere< Mesh_ >, and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >.
Member Data Documentation
is_explicit
template<typename Derived_ , typename Mesh_ , typename Traits_ > constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::is_explicit = TraitsType::is_explicit static constexpr
specifies whether this chart is explicit
Definition at line 372 of file chart.hpp.
Referenced by FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::can_explicit(), and FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::map().
is_implicit
template<typename Derived_ , typename Mesh_ , typename Traits_ > constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::is_implicit = TraitsType::is_implicit static constexpr
specifies whether this chart is implicit
Definition at line 374 of file chart.hpp.
Referenced by FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::can_implicit(), and FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::project().
param_dim
template<typename Derived_ , typename Mesh_ , typename Traits_ > constexpr int FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::param_dim = TraitsType::param_dim static constexpr
the parameter dimension of this chart
Definition at line 379 of file chart.hpp.
world_dim
template<typename Derived_ , typename Mesh_ , typename Traits_ > constexpr int FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::world_dim = TraitsType::world_dim static constexpr
the world dimension of this chart
Definition at line 377 of file chart.hpp.
Referenced by FEAT::Geometry::Atlas::ChartCRTP< Derived_, Mesh_, Traits_ >::adapt().
The documentation for this class was generated from the following file:
kernel/geometry/atlas/chart.hpp