FEAT: FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ > Class Template Reference
FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ > Class Template Reference
Sparse vector class template.
#include <sparse_vector_blocked.hpp>
Public Types
typedef DT_ DataType
Our datatype.
typedef IT_ IndexType
Our indextype.
typedef Tiny::Vector< DT_, BlockSize_ > ValueType
Our value type.
Public Member Functions
SparseVectorBlocked ()
Constructor.
SparseVectorBlocked (FileMode mode, const String &filename)
Constructor.
SparseVectorBlocked (FileMode mode, std::istream &file)
Constructor.
SparseVectorBlocked (Index size_in)
Constructor.
SparseVectorBlocked (Index size_in, DenseVectorBlocked< DT_, IT_, BlockSize_ > &elements_in, DenseVector< IT_, IT_ > &indices_in, bool is_sorted=true)
Constructor.
SparseVectorBlocked (SparseVectorBlocked &&other)
Move Constructor.
template<typename DT2_ = DT_, typename IT2_ = IT_>
SparseVectorBlocked (std::vector< char > input)
Constructor.
Index alloc_increment () const
Retrieve allocation incrementation value.
Index allocated_elements () const
Retrieve amount of allocated elements.
std::size_t bytes () const
Returns the total amount of bytes allocated.
virtual void clear ()
Free all allocated arrays.
SparseVectorBlocked clone (CloneMode clone_mode=CloneMode::Deep) const
Clone operation.
void clone (const Container &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const Container< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const SparseVectorBlocked< DT2_, IT2_, BlockSize_ > &other, CloneMode clone_mode=CloneMode::Deep)
Clone operation.
bool compare_layout (const SparseVectorBlocked &other) const
Checks whether the layout of this vector is identical to another sparse vector.
template<typename DT2_ , typename IT2_ >
void convert (const SparseVectorBlocked< DT2_, IT2_, BlockSize_ > &other)
Conversion method.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void deserialize (std::vector< char > input)
Deserialization of complete container entity.
template<Perspective perspective_ = Perspective::native>
auto elements () -> typename Intern::SparseVectorBlockedPerspectiveHelper< DT_, BlockSize_, perspective_ >::Type *
template<Perspective perspective_ = Perspective::native>
auto elements () const -> const typename Intern::SparseVectorBlockedPerspectiveHelper< DT_, BlockSize_, perspective_ >::Type *
Retrieve a pointer to the data array.
bool empty () const
Checks whether the container is empty.
void format (DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DT_ min, DT_ max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (const LAFEM::SerialConfig &config)
Calculate size.
const std::vector< DT_ * > & get_elements () const
Returns a list of all data arrays.
const std::vector< Index > & get_elements_size () const
Returns a list of all data array sizes.
const std::vector< IT_ * > & get_indices () const
Returns a list of all Index arrays.
const std::vector< Index > & get_indices_size () const
Returns a list of all Index array sizes.
const std::vector< DT_ > & get_scalar_dt () const
Returns a list of all scalar values with datatype dt.
const std::vector< Index > & get_scalar_index () const
Returns a list of all scalar values with datatype index.
IT_ * indices ()
Get a pointer to the non zero indices array.
IT_ const * indices () const
Get a pointer to the non zero indices array.
void move (Container &&other)
Assignment move operation.
const ValueType operator() (Index index) const
Retrieve specific vector element.
void operator() (Index index, const ValueType &val)
Set specific vector element.
SparseVectorBlocked & operator= (SparseVectorBlocked &&other)
Assignment move operator.
void permute (Adjacency::Permutation &perm)
Permutate vector according to the given Permutation.
void read_from (FileMode mode, const String &filename)
Read in vector from file.
void read_from (FileMode mode, std::istream &file)
Read in vector from stream.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > serialize (const LAFEM::SerialConfig &config=SerialConfig()) const
Serialization of complete container entity.
std::uint64_t set_checkpoint_data (std::vector< char > &data, const LAFEM::SerialConfig &config)
template<Perspective perspective_ = Perspective::native>
Index size () const
The number of elements.
void sort ()
Sorts the vector.
Index sorted () const
Retrieve status of element sorting.
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Retrieve non zero element count.
void write_out (FileMode mode, const String &filename) const
Write out vector to file.
void write_out (FileMode mode, std::ostream &file) const
Write out vector to file.
Linear algebra operations
DT_ max_abs_element () const
Retrieve the absolute maximum value of this vector.
DT_ min_abs_element () const
Retrieve the absolute minimum value of this vector.
DT_ max_element () const
Retrieve the maximum value of this vector.
DT_ min_element () const
Retrieve the minimum value of this vector.
Static Public Member Functions
static String name ()
Returns a descriptive string.
Static Public Attributes
static constexpr int BlockSize = BlockSize_
Our size of a single block.
Protected Member Functions
void _copy_content (const Container &other, bool full)
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::istream &file)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::vector< char > &input)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > _serialize (FileMode mode, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _serialize (FileMode mode, std::ostream &file, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::uint64_t _serialized_size (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Calculation of the serialized size with optional compression of complete container entity.
template<typename DT2_ , typename IT2_ >
void assign (const Container< DT2_, IT2_ > &other)
Assignment operation.
Protected Attributes
std::vector< DT_ * > _elements
List of pointers to all datatype dependent arrays.
std::vector< Index > _elements_size
List of corresponding datatype array sizes.
bool _foreign_memory
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
std::vector< IT_ * > _indices
List of pointers to all IT_ dependent arrays.
std::vector< Index > _indices_size
List of corresponding IT_ array sizes.
std::vector< DT_ > _scalar_dt
List of scalars with datatype DT_.
std::vector< Index > _scalar_index
List of scalars with datatype index.
Private Member Functions
Index & _allocated_elements ()
Index & _sorted ()
Index & _used_elements ()
Static Private Member Functions
template<typename T1_ , typename T2_ >
static void _insertion_sort (T1_ *key, T2_ *val1, Index size)
Friends
std::ostream & operator<< (std::ostream &lhs, const SparseVectorBlocked &b)
SparseVectorBlocked streaming operator.
bool operator== (const SparseVectorBlocked &a, const SparseVectorBlocked &b)
SparseVectorBlocked comparison operator.
Detailed Description
template<typename DT_, typename IT_, int BlockSize_>
class FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >
Sparse vector class template.
Template Parameters
DT_ The datatype to be used.
IT_ The indexing type to be used.
BlockSize_ The size of the represented blocks
This class represents a vector with non zero element blocks in a sparse layout.
Logical, the data are organized in small blocks of BlockSize_ length.
Data survey:
_elements[0]: raw number values
_indices[0]: non zero indices
_scalar_index[0]: container size - aka block count
_scalar_index[1]: non zero element count (used elements)
_scalar_index[2]: allocated elements
_scalar_index[3]: allocation size increment
_scalar_index[4]: boolean flag, if container is sorted
Refer to LAFEM design description for general usage informations.
Author
Dirk Ribbrock
Definition at line 66 of file sparse_vector_blocked.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ , int BlockSize_> typedef DT_ FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::DataType
Our datatype.
Definition at line 107 of file sparse_vector_blocked.hpp.
IndexType
template<typename DT_ , typename IT_ , int BlockSize_> typedef IT_ FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::IndexType
Our indextype.
Definition at line 109 of file sparse_vector_blocked.hpp.
ValueType
template<typename DT_ , typename IT_ , int BlockSize_> typedef Tiny::Vector<DT_, BlockSize_> FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::ValueType
Our value type.
Definition at line 113 of file sparse_vector_blocked.hpp.
Constructor & Destructor Documentation
SparseVectorBlocked() [1/7]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked () inline explicit
Constructor.
Creates an empty non dimensional vector.
Definition at line 120 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
SparseVectorBlocked() [2/7]
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked (std::vector< char > input) inline explicit
Constructor.
Parameters
[in] input A std::vector, containing the byte array.
Definition at line 136 of file sparse_vector_blocked.hpp.
SparseVectorBlocked() [3/7]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked (FileMode mode, const String & filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a vector based on the source file.
Definition at line 150 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::read_from().
SparseVectorBlocked() [4/7]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked (FileMode mode, std::istream & file) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Creates a vector based on the source filestream.
Definition at line 164 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::read_from().
SparseVectorBlocked() [5/7]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked (Index size_in) inline explicit
Constructor.
Parameters
[in] size_in The size of the created vector.
Creates a vector with a given size.
Definition at line 178 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
SparseVectorBlocked() [6/7]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked (Index size_in, DenseVectorBlocked< DT_, IT_, BlockSize_ > & elements_in, DenseVector< IT_, IT_ > & indices_in, bool is_sorted = true) inline explicit
Constructor.
Parameters
[in] size_in The size of the created vector.
[in] elements_in A list of non zero elements.
[in] indices_in A list of non zero element indices.
[in] is_sorted Indicates, if the elements are sorted by their indices: is_sorted = true (default)
Creates a vector with a given size.
Definition at line 197 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), XASSERT, and XASSERTM.
SparseVectorBlocked() [7/7]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked (SparseVectorBlocked< DT_, IT_, BlockSize_ > && other) inline
Move Constructor.
Parameters
[in] other The source vector.
Moves another vector to this vector.
Definition at line 229 of file sparse_vector_blocked.hpp.
Member Function Documentation
_allocated_elements()
template<typename DT_ , typename IT_ , int BlockSize_> Index & FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::_allocated_elements () inline private
Definition at line 95 of file sparse_vector_blocked.hpp.
_copy_content()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::_copy_content (const Container< DT_, IT_ > & other, bool full) inline protected inherited
Definition at line 240 of file container.hpp.
_deserialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::istream & file) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file std::istream, pointing to the input data.
Recreate a complete container entity by a single binary file.
Definition at line 780 of file container.hpp.
References XABORTM.
_deserialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::vector< char > & input) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] input A std::vector containing the byte array.
Recreate a complete container entity by a single binary array.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 626 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Pack::decode(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Type::Helper::extract_floatness(), FEAT::Type::Helper::extract_intness(), FEAT::Type::Helper::extract_signedness(), FEAT::Type::Helper::extract_type_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, XABORTM, XASSERT, and XASSERTM.
_insertion_sort()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename T1_ , typename T2_ > static void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::_insertion_sort (T1_ * key, T2_ * val1, Index size) inline static private
Definition at line 70 of file sparse_vector_blocked.hpp.
_serialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
Array data layout:
raw array size in bytes (std::uint64_t)
magic number (std::uint64_t)
DT_ 'hash' value (sizeof(DT_) and floating/integral distinction (packed std::uint64_t)
IT_ 'hash' value (sizeof(IT_) and floating/integral distinction (packed std::uint64_t)
_elements.size() (std::uint64_t)
_indices.size() (std::uint64_t)
_elements_size.size() (std::uint64_t)
_indices_size.size() (std::uint64_t)
_scalar_index.size() (std::uint64_t)
_scalar_dt.size() (std::uint64_t)
_compressed (std::uint64_t)
_elements_size array (std::uint64_t)
_elements arrays byte_size (std::uint64_t) just temporary to read in data
_indices_size array (std::uint64_t)
_indices arrays byte_size (std::uint64_t)
_scalar_index array (std::uint64_t)
_scalar_dt array (DT2_)
_elements arrays (DT2_)
_indices arrays (IT2_)
See FEAT::LAFEM::SerialConfig for details.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 444 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XASSERTM.
_serialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, std::ostream & file, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file The output stream to write data into.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary file with compression enabled. See FEAT::LAFEM::SerialConfig for details.
Definition at line 609 of file container.hpp.
References XABORTM.
_serialized_size()
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline protected inherited
Calculation of the serialized size with optional compression of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Returns
An unsigned int containing the size of serialized container.
Calculate the size of the serialized container entity.
Definition at line 361 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), and FEAT::LAFEM::indices_zlib.
_sorted()
template<typename DT_ , typename IT_ , int BlockSize_> Index & FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::_sorted () inline private
Definition at line 100 of file sparse_vector_blocked.hpp.
_used_elements()
template<typename DT_ , typename IT_ , int BlockSize_> Index & FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::_used_elements () inline private
Definition at line 90 of file sparse_vector_blocked.hpp.
alloc_increment()
template<typename DT_ , typename IT_ , int BlockSize_> Index FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment () const inline
Retrieve allocation incrementation value.
Returns
Allocation increment.
Definition at line 747 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()().
allocated_elements()
template<typename DT_ , typename IT_ , int BlockSize_> Index FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements () const inline
Retrieve amount of allocated elements.
Returns
Allocated element count.
Definition at line 735 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()().
assign()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::assign (const Container< DT2_, IT2_ > & other) inline protected inherited
Assignment operation.
Assigns contents of another container
Parameters
[in] other The source container.
Definition at line 280 of file container.hpp.
References FEAT::MemoryPool::convert(), FEAT::MemoryPool::increase_memory(), FEAT::MemoryPool::release_memory(), and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::convert(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute().
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::LAFEM::Container< DT_, IT_ >::bytes () const inline inherited
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 1042 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes().
clear()
template<typename DT_ , typename IT_ > virtual void FEAT::LAFEM::Container< DT_, IT_ >::clear () inline virtual inherited
Free all allocated arrays.
Definition at line 875 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from().
clone() [1/4]
template<typename DT_ , typename IT_ , int BlockSize_> SparseVectorBlocked FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Clone operation.
Create a deep clone of this container.
Parameters
[in] clone_mode The actual cloning procedure.
Returns
The created clone.
Definition at line 256 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone().
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::convert().
clone() [2/4]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 902 of file container.hpp.
References FEAT::LAFEM::Allocate, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Deep, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Layout, FEAT::LAFEM::Shallow, FEAT::LAFEM::Weak, XABORTM, and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVector< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone().
clone() [3/4]
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 975 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), and FEAT::LAFEM::Container< DT_, IT_ >::clone().
clone() [4/4]
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone (const SparseVectorBlocked< DT2_, IT2_, BlockSize_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clone operation.
Create a deep clone of this container.
Parameters
[in] other The source container to create the clone from.
[in] clone_mode The actual cloning procedure.
Definition at line 272 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clone().
compare_layout()
template<typename DT_ , typename IT_ , int BlockSize_> bool FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::compare_layout (const SparseVectorBlocked< DT_, IT_, BlockSize_ > & other) const inline
Checks whether the layout of this vector is identical to another sparse vector.
Parameters
[in] other A transient reference to the other vector to compare to.
Returns
true, if both vectors have the same layout, otherwise false.
Definition at line 816 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements().
convert()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::convert (const SparseVectorBlocked< DT2_, IT2_, BlockSize_ > & other) inline
Conversion method.
Use source vector content as content of current vector
Parameters
[in] other The source container.
Note
This creates a deep copy in any case!
Definition at line 288 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::convert().
deserialize()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::deserialize (std::vector< char > input) inline
Deserialization of complete container entity.
Parameters
[in] input A std::vector, containing the byte array.
Recreate a complete container entity by a single binary array.
Definition at line 517 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::fm_svb.
elements() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> template<Perspective perspective_ = Perspective::native> auto FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements () -> typename Intern::SparseVectorBlockedPerspectiveHelper<DT_, BlockSize_, perspective_>::Type * inline
const version.
Definition at line 316 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted().
elements() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> template<Perspective perspective_ = Perspective::native> auto FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements () const -> const typename Intern::SparseVectorBlockedPerspectiveHelper<DT_, BlockSize_, perspective_>::Type * inline
Retrieve a pointer to the data array.
Template Parameters
perspective_ template parameter to choose the return value type
Returns
Non zero element array if perspective_ = Perspective::native, e.g. treat every block as one block.
Raw non zero element array if perspective_ = Perspective::pod, e.g. treat every entry of a block separated.
Definition at line 303 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted().
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_values(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
empty()
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::empty () const inline inherited
Checks whether the container is empty.
Returns
true if the container is empty, otherwise false.
Definition at line 1165 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::MeanFilterBlocked(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol(), and FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic().
format() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (DT_ value = DT_(0)) inline inherited
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 851 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::MemoryPool::set_memory(), and FEAT::value.
Referenced by FEAT::Assembly::CellErrorFunctionIntegralJob< Function_, Vector_, Space_, max_der_ >::CellErrorFunctionIntegralJob(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply_transposed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply_transposed(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorP_, MirrorV_ > >::init_numeric(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), FEAT::Assembly::CellErrorFunctionIntegralJob< Function_, Vector_, Space_, max_der_ >::result(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
format() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (Random & rng, DT_ min, DT_ max) inline inherited
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 864 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, and FEAT::MemoryPool::set_memory().
get_checkpoint_size()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::get_checkpoint_size (const LAFEM::SerialConfig & config) inline inherited
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1018 of file container.hpp.
get_elements()
template<typename DT_ , typename IT_ > const std::vector< DT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements () const inline inherited
Returns a list of all data arrays.
Returns
A list of all data arrays.
Definition at line 1068 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
get_elements_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size () const inline inherited
Returns a list of all data array sizes.
Returns
A list of all data array sizes.
Definition at line 1088 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
get_indices()
template<typename DT_ , typename IT_ > const std::vector< IT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices () const inline inherited
Returns a list of all Index arrays.
Returns
A list of all Index arrays.
Definition at line 1078 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
get_indices_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size () const inline inherited
Returns a list of all Index array sizes.
Returns
A list of all Index array sizes.
Definition at line 1098 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices_size.
get_scalar_dt()
template<typename DT_ , typename IT_ > const std::vector< DT_ > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt () const inline inherited
Returns a list of all scalar values with datatype dt.
Returns
A list of all scalars with datatype dt.
Definition at line 1118 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt.
get_scalar_index()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index () const inline inherited
Returns a list of all scalar values with datatype index.
Returns
A list of all scalars with datatype index.
Definition at line 1108 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
indices() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> IT_ * FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices () inline
Get a pointer to the non zero indices array.
Returns
Pointer to the indices array.
Definition at line 331 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted().
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::compare_layout(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_def(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy().
indices() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> IT_ const * FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices () const inline
Get a pointer to the non zero indices array.
Returns
Pointer to the indices array. const version.
Definition at line 342 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted().
max_abs_element()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::max_abs_element () const inline
Retrieve the absolute maximum value of this vector.
Returns
The largest absolute value.
Definition at line 617 of file sparse_vector_blocked.hpp.
References FEAT::Math::abs(), ASSERT, and FEAT::TimeStamp::elapsed().
max_element()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::max_element () const inline
Retrieve the maximum value of this vector.
Returns
The largest value.
Definition at line 657 of file sparse_vector_blocked.hpp.
References ASSERT, and FEAT::TimeStamp::elapsed().
min_abs_element()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::min_abs_element () const inline
Retrieve the absolute minimum value of this vector.
Returns
The smallest absolute value.
Definition at line 637 of file sparse_vector_blocked.hpp.
References FEAT::Math::abs(), ASSERT, and FEAT::TimeStamp::elapsed().
min_element()
template<typename DT_ , typename IT_ , int BlockSize_> DT_ FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::min_element () const inline
Retrieve the minimum value of this vector.
Returns
The smallest value.
Definition at line 676 of file sparse_vector_blocked.hpp.
References ASSERT, and FEAT::TimeStamp::elapsed().
move()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::move (Container< DT_, IT_ > && other) inline inherited
Assignment move operation.
Move another container to the current one.
Parameters
[in] other The source container.
Definition at line 989 of file container.hpp.
References FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
name()
template<typename DT_ , typename IT_ , int BlockSize_> static String FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 771 of file sparse_vector_blocked.hpp.
operator()() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> const ValueType FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator() (Index index) const inline
Retrieve specific vector element.
Parameters
[in] index The index of the vector element.
Returns
Specific vector element.
Definition at line 373 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, ASSERTM, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements().
operator()() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator() (Index index, const ValueType & val) inline
Set specific vector element.
Parameters
[in] index The index of the vector element.
[in] val The val to be set.
Definition at line 408 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), ASSERTM, FEAT::MemoryPool::copy(), FEAT::MemoryPool::release_memory(), FEAT::MemoryPool::set_memory(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), and FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator=()
template<typename DT_ , typename IT_ , int BlockSize_> SparseVectorBlocked & FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator= (SparseVectorBlocked< DT_, IT_, BlockSize_ > && other) inline
Assignment move operator.
Parameters
[in] other The source vector.
Moves another vector to the target vector.
Definition at line 241 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::move().
permute()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute (Adjacency::Permutation & perm) inline
Permutate vector according to the given Permutation.
Definition at line 693 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::Adjacency::Permutation::inverse(), FEAT::Adjacency::Permutation::size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), and XASSERTM.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::permute().
read_from() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::read_from (FileMode mode, const String & filename) inline
Read in vector from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 544 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::read_from().
read_from() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::read_from (FileMode mode, std::istream & file) inline
Read in vector from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Definition at line 559 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_svb, and XABORTM.
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::restore_from_checkpoint_data (std::vector< char > & data) inline inherited
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1024 of file container.hpp.
References FEAT::LAFEM::fm_binary.
serialize()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::serialize (const LAFEM::SerialConfig & config = SerialConfig()) const inline
Serialization of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary array.
See FEAT::LAFEM::Container::_serialize for details.
Definition at line 533 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::fm_svb.
set_checkpoint_data()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::set_checkpoint_data (std::vector< char > & data, const LAFEM::SerialConfig & config) inline inherited
Definition at line 1030 of file container.hpp.
References FEAT::LAFEM::fm_binary.
size()
template<typename DT_ , typename IT_ , int BlockSize_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size () const inline
The number of elements.
Returns
number of elements of type ValueType if perspective_ = false.
Raw number of elements of type DataType if perspective_ = true.
Definition at line 358 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::pod, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size().
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::compare_layout(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_def(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::size().
sort()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort () inline
Sorts the vector.
Definition at line 472 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted().
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements().
sorted()
template<typename DT_ , typename IT_ , int BlockSize_> Index FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted () const inline
Retrieve status of element sorting.
Returns
Sorting status.
Definition at line 759 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements().
used_elements()
template<typename DT_ , typename IT_ , int BlockSize_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements () const inline
Retrieve non zero element count.
Returns
Non zero element count.
Definition at line 720 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::pod, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted().
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::compare_layout(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_def(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), and FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::used_elements().
write_out() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::write_out (FileMode mode, const String & filename) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 578 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::FileOutStreamBufferSize, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::write_out().
write_out() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::write_out (FileMode mode, std::ostream & file) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
Definition at line 596 of file sparse_vector_blocked.hpp.
References FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_svb, and XABORTM.
Friends And Related Function Documentation
operator<<
template<typename DT_ , typename IT_ , int BlockSize_> std::ostream & operator<< (std::ostream & lhs, const SparseVectorBlocked< DT_, IT_, BlockSize_ > & b) friend
SparseVectorBlocked streaming operator.
Parameters
[in] lhs The target stream.
[in] b The vector to be streamed.
Definition at line 851 of file sparse_vector_blocked.hpp.
operator==
template<typename DT_ , typename IT_ , int BlockSize_> bool operator== (const SparseVectorBlocked< DT_, IT_, BlockSize_ > & a, const SparseVectorBlocked< DT_, IT_, BlockSize_ > & b) friend
SparseVectorBlocked comparison operator.
Parameters
[in] a A vector to compare with.
[in] b A vector to compare with.
Definition at line 783 of file sparse_vector_blocked.hpp.
Member Data Documentation
_elements
template<typename DT_ , typename IT_ > std::vector<DT_*> FEAT::LAFEM::Container< DT_, IT_ >::_elements protected inherited
List of pointers to all datatype dependent arrays.
Definition at line 226 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
_elements_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_elements_size protected inherited
List of corresponding datatype array sizes.
Definition at line 230 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_foreign_memory
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory protected inherited
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
Definition at line 238 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), and FEAT::LAFEM::Container< DT_, IT_ >::clear().
_indices
template<typename DT_ , typename IT_ > std::vector<IT_*> FEAT::LAFEM::Container< DT_, IT_ >::_indices protected inherited
List of pointers to all IT_ dependent arrays.
Definition at line 228 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseVector< DT_, IT_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
_indices_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_indices_size protected inherited
List of corresponding IT_ array sizes.
Definition at line 232 of file container.hpp.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_scalar_dt
template<typename DT_ , typename IT_ > std::vector<DT_> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt protected inherited
List of scalars with datatype DT_.
Definition at line 236 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), and FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt().
_scalar_index
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index protected inherited
List of scalars with datatype index.
Definition at line 234 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::Container(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVector< DT_, IT_ >::allocated_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::sorted(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size().
BlockSize
template<typename DT_ , typename IT_ , int BlockSize_> constexpr int FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::BlockSize = BlockSize_ static constexpr
Our size of a single block.
Definition at line 111 of file sparse_vector_blocked.hpp.
The documentation for this class was generated from the following files:
kernel/lafem/forward.hpp
kernel/lafem/sparse_vector_blocked.hpp