FEAT: FEAT::Geometry::Atlas::Circle< Mesh_ > Class Template Reference
FEAT::Geometry::Atlas::Circle< Mesh_ > Class Template Reference abstract
Circle chart class template.
#include <circle.hpp>
Public Types
typedef PartType::AttributeSetType AttributeSetType
attribute type of our mesh-part
typedef ChartCRTP< Circle< Mesh_ >, Mesh_, CircleTraits > BaseClass
The CRTP base class.
typedef BaseClass::CoordType CoordType
Floating point type.
typedef BaseClass::MeshType MeshType
mesh type
typedef BaseClass::ParamPoint ParamPoint
Vector type for parametrization points, aka domain points.
typedef BaseClass::PartType PartType
mesh-part type
typedef CircleTraits TraitsType
traits type
typedef MeshType::VertexSetType VertexSetType
vertex set type of our mesh
typedef BaseClass::WorldPoint WorldPoint
Vector type for world points, aka image points.
Public Member Functions
Circle (const Circle &)=default
Circle (CoordType mid_x, CoordType mid_y, CoordType radius)
Creates a Circle chart for implicit adaption.
Circle (CoordType mid_x, CoordType mid_y, CoordType radius, CoordType param_l, CoordType param_r)
Creates a Circle chart for both implicit and explicit adaption.
virtual void adapt (MeshType &mesh, const PartType &part) const override
Adapts a whole MeshPart.
virtual void adapt (PartType &parent_meshpart, const PartType &meshpart) const override
Adapts a whole MeshPart referring to another MeshPart.
virtual std::size_t bytes () const
virtual bool can_explicit () const override
virtual bool can_implicit () const override
CoordType compute_dist (const WorldPoint &point) const
Computes the distance of a point to this chart.
CoordType compute_dist (const WorldPoint &point, WorldPoint &grad_dist) const
CoordType compute_signed_dist (const WorldPoint &point) const
CoordType compute_signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const
virtual CoordType dist (const WorldPoint &point) const override
virtual CoordType dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual String get_type () const override
Writes the type as String.
virtual WorldPoint map (const WorldPoint &param) const override
void map_param (WorldPoint &point, const ParamPoint &param) const
Maps a single parameter point.
virtual WorldPoint project (const WorldPoint &point) const override
void project_meshpart (Mesh_ &mesh, const MeshPart< Mesh_ > &meshpart) const
void project_point (WorldPoint &point) const
Projects a single world point.
virtual CoordType signed_dist (const WorldPoint &point) const override
virtual CoordType signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset) override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset)=0
Applies a "proper rigid" transformation onto the chart.
virtual void write (std::ostream &os, const String &sindent) const override
Writes the Chart into a stream in XML format.
Static Public Attributes
static constexpr bool is_explicit
specifies whether this chart is explicit
static constexpr bool is_implicit
specifies whether this chart is implicit
static constexpr int param_dim
the parameter dimension of this chart
static constexpr int world_dim
the world dimension of this chart
Protected Member Functions
Circle< Mesh_ > & cast ()
Casts this to its true type.
const Circle< Mesh_ > & cast () const
Protected Attributes
bool _have_domain
Specifies whether the circle mapping has a domain.
WorldPoint _midpoint
the circle's midpoint
CoordType _radius
the circle's radius
CoordType _trafo_a
Left parametrization domain boundary.
CoordType _trafo_b
Right parametrization domain boundary.
Detailed Description
template<typename Mesh_>
class FEAT::Geometry::Atlas::Circle< Mesh_ >
Circle chart class template.
This class represents a 2D circle characterized by a midpoint, a radius and a 1D interval for the parameter space.
This chart implements both the implicit and explicit chart interfaces.
The parameter domain [a,b] is mapped onto the circle, where both interval endpoints are mapped onto the east point on the circle, i.e. the point with the X/Y-coordinates [mid_x + radius, mid_y]. If the parameter interval is oriented positive, i.e. if it holds that a < b, then the circle is parameterized in counter-clock-wise orientation. If the parameter interval is oriented negative, i.e. if it holds that b < a, then the circle is parameterized in clock-wise orientation.
Template Parameters
Mesh_ The type of the mesh to be parameterized by this chart.
Author
Peter Zajac
Definition at line 50 of file circle.hpp.
Member Typedef Documentation
AttributeSetType
typedef PartType::AttributeSetType FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::AttributeSetType inherited
attribute type of our mesh-part
Definition at line 365 of file chart.hpp.
BaseClass
template<typename Mesh_ > typedef ChartCRTP<Circle<Mesh_>, Mesh_, CircleTraits> FEAT::Geometry::Atlas::Circle< Mesh_ >::BaseClass
The CRTP base class.
Definition at line 55 of file circle.hpp.
CoordType
template<typename Mesh_ > typedef BaseClass::CoordType FEAT::Geometry::Atlas::Circle< Mesh_ >::CoordType
Floating point type.
Definition at line 57 of file circle.hpp.
MeshType
typedef BaseClass::MeshType FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::MeshType inherited
mesh type
Definition at line 361 of file chart.hpp.
ParamPoint
template<typename Mesh_ > typedef BaseClass::ParamPoint FEAT::Geometry::Atlas::Circle< Mesh_ >::ParamPoint
Vector type for parametrization points, aka domain points.
Definition at line 61 of file circle.hpp.
PartType
typedef BaseClass::PartType FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::PartType inherited
mesh-part type
Definition at line 363 of file chart.hpp.
TraitsType
typedef CircleTraits FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::TraitsType inherited
traits type
Definition at line 359 of file chart.hpp.
VertexSetType
typedef MeshType::VertexSetType FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::VertexSetType inherited
vertex set type of our mesh
Definition at line 367 of file chart.hpp.
WorldPoint
template<typename Mesh_ > typedef BaseClass::WorldPoint FEAT::Geometry::Atlas::Circle< Mesh_ >::WorldPoint
Vector type for world points, aka image points.
Definition at line 59 of file circle.hpp.
Constructor & Destructor Documentation
Circle() [1/2]
template<typename Mesh_ > FEAT::Geometry::Atlas::Circle< Mesh_ >::Circle (CoordType mid_x, CoordType mid_y, CoordType radius) inline explicit
Creates a Circle chart for implicit adaption.
Parameters
[in] mid_x,mid_y The coordinates of the circle midpoint.
[in] radius The radius of the circle. Must be positive.
Definition at line 85 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_midpoint, and XASSERTM.
Circle() [2/2]
template<typename Mesh_ > FEAT::Geometry::Atlas::Circle< Mesh_ >::Circle (CoordType mid_x, CoordType mid_y, CoordType radius, CoordType param_l, CoordType param_r) inline explicit
Creates a Circle chart for both implicit and explicit adaption.
Parameters
[in] mid_x,mid_y The coordinates of the circle midpoint.
[in] radius The radius of the circle. Must be positive.
[in] param_l,param_r Specifies the domain of the parameter interval. See the documentation of this class template for details.
Definition at line 109 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_midpoint, and XASSERTM.
Member Function Documentation
adapt() [1/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::adapt (MeshType & mesh, const PartType & part) const inline override virtual inherited
Adapts a whole MeshPart.
Parameters
[in] mesh Mesh to be adapted
[in] part MeshPart identifying the region to be adapted
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 420 of file chart.hpp.
adapt() [2/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::adapt (PartType & parent_meshpart, const PartType & meshpart) const inline override virtual inherited
Adapts a whole MeshPart referring to another MeshPart.
Parameters
[in] parent_meshpart MeshPart to be adapted
[in] meshpart MeshPart identifying the region to be adapted
Todo:
: Implement this
There is currently no code that uses MeshParts referring to other MeshParts instead of a RootMesh.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 450 of file chart.hpp.
bytes()
template<typename Mesh_ > virtual std::size_t FEAT::Geometry::Atlas::ChartBase< Mesh_ >::bytes () const inline virtual inherited
Returns
The size of dynamically allocated memory in bytes.
Reimplemented in FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >.
Definition at line 52 of file chart.hpp.
can_explicit()
template<typename Mesh_ > virtual bool FEAT::Geometry::Atlas::Circle< Mesh_ >::can_explicit () const inline override virtual
Reimplemented from FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ >, Mesh_, CircleTraits >.
Definition at line 125 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_have_domain.
can_implicit()
virtual bool FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::can_implicit () const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 406 of file chart.hpp.
cast() [1/2]
Circle< Mesh_ > & FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::cast () inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this
Definition at line 393 of file chart.hpp.
cast() [2/2]
const Circle< Mesh_ > & FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::cast () const inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this\ifile "/github/workspace/kernel/geometry/atlas/chart.hpp"
Definition at line 396 of file chart.hpp.
compute_dist() [1/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_dist (const WorldPoint & point) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 171 of file circle.hpp.
References FEAT::Math::abs(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_signed_dist().
compute_dist() [2/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline
Definition at line 177 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::project_point().
compute_signed_dist() [1/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_signed_dist (const WorldPoint & point) const inline
Definition at line 190 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_midpoint, and FEAT::Geometry::Atlas::Circle< Mesh_ >::_radius.
Referenced by FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_dist().
compute_signed_dist() [2/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline
Definition at line 196 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_midpoint, FEAT::Geometry::Atlas::Circle< Mesh_ >::_radius, FEAT::Geometry::Atlas::Circle< Mesh_ >::project_point(), and FEAT::Math::signum().
dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 480 of file chart.hpp.
dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 486 of file chart.hpp.
get_type()
template<typename Mesh_ > virtual String FEAT::Geometry::Atlas::Circle< Mesh_ >::get_type () const inline override virtual
Writes the type as String.
Needed for writing this to mesh files.
Returns
The class name as String.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 248 of file circle.hpp.
map()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::map (const WorldPoint & param) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 456 of file chart.hpp.
map_param()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Circle< Mesh_ >::map_param (WorldPoint & point, const ParamPoint & param) const inline
Maps a single parameter point.
Parameters
[out] point The image of the parameter point under the chart mapping
[in] param The parameter point to be mapped
Definition at line 239 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_trafo_a, FEAT::Geometry::Atlas::Circle< Mesh_ >::_trafo_b, FEAT::Math::cos(), and FEAT::Math::sin().
project()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::project (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 469 of file chart.hpp.
project_meshpart()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Circle< Mesh_ >::project_meshpart (Mesh_ & mesh, const MeshPart< Mesh_ > & meshpart) const inline
Definition at line 218 of file circle.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::project_point().
project_point()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Circle< Mesh_ >::project_point (WorldPoint & point) const inline
Projects a single world point.
Parameters
[in,out] point The world point to be projected
Definition at line 154 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_midpoint, and FEAT::Geometry::Atlas::Circle< Mesh_ >::_radius.
Referenced by FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_dist(), FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_signed_dist(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::project_meshpart().
signed_dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::signed_dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 492 of file chart.hpp.
signed_dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 498 of file chart.hpp.
transform() [1/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::Circle< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) inline override virtual
Definition at line 131 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_have_domain, FEAT::Geometry::Atlas::Circle< Mesh_ >::_midpoint, FEAT::Geometry::Atlas::Circle< Mesh_ >::_trafo_a, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_2d().
transform() [2/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::ChartBase< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) pure virtual inherited
Applies a "proper rigid" transformation onto the chart.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any point x of the chart:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any point before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): -ignored-
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any point after applying the rotation.
Implemented in FEAT::Geometry::Atlas::CGALSurfaceMesh< Mesh_ >.
write()
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::Circle< Mesh_ >::write (std::ostream & os, const String & sindent) const inline override virtual
Writes the Chart into a stream in XML format.
Parameters
[in,out] os The output stream to write into.
[in] sindent The indentation string.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 254 of file circle.hpp.
References FEAT::Geometry::Atlas::Circle< Mesh_ >::_have_domain, FEAT::Geometry::Atlas::Circle< Mesh_ >::_trafo_a, and FEAT::Geometry::Atlas::Circle< Mesh_ >::_trafo_b.
Member Data Documentation
_have_domain
template<typename Mesh_ > bool FEAT::Geometry::Atlas::Circle< Mesh_ >::_have_domain protected
Specifies whether the circle mapping has a domain.
Definition at line 69 of file circle.hpp.
Referenced by FEAT::Geometry::Atlas::Circle< Mesh_ >::can_explicit(), FEAT::Geometry::Atlas::Circle< Mesh_ >::transform(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::write().
_midpoint
template<typename Mesh_ > WorldPoint FEAT::Geometry::Atlas::Circle< Mesh_ >::_midpoint protected
the circle's midpoint
Definition at line 65 of file circle.hpp.
Referenced by FEAT::Geometry::Atlas::Circle< Mesh_ >::Circle(), FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_signed_dist(), FEAT::Geometry::Atlas::Circle< Mesh_ >::project_point(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::transform().
_radius
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Circle< Mesh_ >::_radius protected
the circle's radius
Definition at line 67 of file circle.hpp.
Referenced by FEAT::Geometry::Atlas::Circle< Mesh_ >::compute_signed_dist(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::project_point().
_trafo_a
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Circle< Mesh_ >::_trafo_a protected
Left parametrization domain boundary.
Definition at line 71 of file circle.hpp.
Referenced by FEAT::Geometry::Atlas::Circle< Mesh_ >::map_param(), FEAT::Geometry::Atlas::Circle< Mesh_ >::transform(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::write().
_trafo_b
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Circle< Mesh_ >::_trafo_b protected
Right parametrization domain boundary.
Definition at line 73 of file circle.hpp.
Referenced by FEAT::Geometry::Atlas::Circle< Mesh_ >::map_param(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::write().
is_explicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::is_explicit static constexpr inherited
specifies whether this chart is explicit
Definition at line 372 of file chart.hpp.
is_implicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::is_implicit static constexpr inherited
specifies whether this chart is implicit
Definition at line 374 of file chart.hpp.
param_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::param_dim static constexpr inherited
the parameter dimension of this chart
Definition at line 379 of file chart.hpp.
world_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< Circle< Mesh_ > , Mesh_, CircleTraits >::world_dim static constexpr inherited
the world dimension of this chart
Definition at line 377 of file chart.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/atlas/circle.hpp