FEAT: FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 > Class Template Reference
FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 > Class Template Reference
Storage class for a single layer of the adaptive mesh.
#include <adaptive_mesh_storage.hpp>
Public Member Functions
std::size_t bytes () const
Returns the number of bytes used by this layer.
void erase (ElementKey< 0 > key)
Erase a vertex from this layer.
AdaptiveVertex< VertexType_ > & get_vertex (ElementKey< 0 > key)
Retrieve a reference to the AdaptiveVertex pointed to by key.
const AdaptiveVertex< VertexType_ > & get_vertex (ElementKey< 0 > key) const
Retrieve a reference to the AdaptiveVertex pointed to by key.
ElementKey< 0 > insert_vertex (const AdaptiveVertex< VertexType_ > &vertex)
Insert a vertex into this layer.
Index num_vertices () const
Returns the number of vertices in this layer.
Util::SlotMap< AdaptiveVertex< VertexType_ >, ElementKey< 0 > > & vertices ()
Vertex SlotMap accessor.
const Util::SlotMap< AdaptiveVertex< VertexType_ >, ElementKey< 0 > > & vertices () const
Vertex SlotMap accessor.
Protected Attributes
Util::SlotMap< AdaptiveVertex< VertexType_ >, ElementKey< 0 > > _vertices
SlotMap for this layers vertices.
Detailed Description
template<typename TemplateSet_, typename MeshShape_, typename VertexType_>
class FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >
Storage class for a single layer of the adaptive mesh.
This class provides storage and utility methods to manage the elements of a single layer of the adaptive mesh.
This specialization is the base case of the self-inheritance.
Template Parameters
TemplateSet_ Template set for mesh refinement
VertexType_ Type of vertices to be stored
Author
Markus Muegge
Definition at line 658 of file adaptive_mesh_storage.hpp.
Member Function Documentation
bytes()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > std::size_t FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::bytes () const inline
Returns the number of bytes used by this layer.
Definition at line 708 of file adaptive_mesh_storage.hpp.
erase()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > void FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::erase (ElementKey< 0 > key) inline
Erase a vertex from this layer.
Parameters
key Key pointing to the vertex to be erased
Definition at line 680 of file adaptive_mesh_storage.hpp.
References FEAT::Util::SlotMap< V, Key >::erase().
get_vertex() [1/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > AdaptiveVertex< VertexType_ > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::get_vertex (ElementKey< 0 > key) inline
Retrieve a reference to the AdaptiveVertex pointed to by key.
Definition at line 716 of file adaptive_mesh_storage.hpp.
get_vertex() [2/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > const AdaptiveVertex< VertexType_ > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::get_vertex (ElementKey< 0 > key) const inline
Retrieve a reference to the AdaptiveVertex pointed to by key.
Definition at line 724 of file adaptive_mesh_storage.hpp.
insert_vertex()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > ElementKey< 0 > FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::insert_vertex (const AdaptiveVertex< VertexType_ > & vertex) inline
Insert a vertex into this layer.
Parameters
vertex r-value reference to the AdaptiveVertex to be inserted
Definition at line 670 of file adaptive_mesh_storage.hpp.
References FEAT::Util::SlotMap< V, Key >::insert().
num_vertices()
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > Index FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::num_vertices () const inline
Returns the number of vertices in this layer.
Definition at line 688 of file adaptive_mesh_storage.hpp.
References FEAT::Util::SlotMap< V, Key >::size().
vertices() [1/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > Util::SlotMap< AdaptiveVertex< VertexType_ >, ElementKey< 0 > > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::vertices () inline
Vertex SlotMap accessor.
Definition at line 694 of file adaptive_mesh_storage.hpp.
vertices() [2/2]
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > const Util::SlotMap< AdaptiveVertex< VertexType_ >, ElementKey< 0 > > & FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::vertices () const inline
Vertex SlotMap accessor.
Definition at line 700 of file adaptive_mesh_storage.hpp.
Member Data Documentation
_vertices
template<typename TemplateSet_ , typename MeshShape_ , typename VertexType_ > Util::SlotMap<AdaptiveVertex<VertexType_>, ElementKey<0> > FEAT::Geometry::Intern::MeshLayer< TemplateSet_, MeshShape_, VertexType_, 0 >::_vertices protected
SlotMap for this layers vertices.
Definition at line 662 of file adaptive_mesh_storage.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/intern/adaptive_mesh_storage.hpp