FEAT: FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ > Class Template Reference
FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ > Class Template Reference
Slip Filter class template.
#include <slip_filter.hpp>
Public Types
typedef DT_ DataType
data-type typedef
template<typename DT2_ = DT_, typename IT2_ = IT_>
using FilterType = SlipFilter< DT2_, IT2_, BlockSize_ >
Our 'base' class type.
template<typename DT2_ = DT_, typename IT2_ = IT_>
using FilterTypeByDI = FilterType< DT2_, IT2_ >
For creating filter with different DT, IT.
typedef IT_ IndexType
index-type typedef
typedef Tiny::Vector< DataType, BlockSize > ValueType
Value type.
typedef DenseVectorBlocked< DT_, IT_, BlockSize_ > VectorType
Our supported vector type.
Public Member Functions
SlipFilter ()
default constructor
SlipFilter (Index num_vertices, Index num_dofs)
Constructor.
SlipFilter (SlipFilter &&other)
move-ctor
virtual ~SlipFilter ()
virtual destructor
void add (IndexType idx, ValueType val)
Adds one element to the filter.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Clears the underlying data (namely the SparseVector)
SlipFilter clone (CloneMode clone_mode=CloneMode::Deep) const
Creates a clone of itself.
void clone (const SlipFilter &other, CloneMode clone_mode=CloneMode::Deep)
Clones data from another SlipFilter.
template<typename DT2_ , typename IT2_ , int BS_>
void convert (const SlipFilter< DT2_, IT2_, BS_ > &other)
Converts data from another UnitFilter.
void filter_cor (VectorType &vector) const
Applies the filter onto a correction vector.
void filter_def (VectorType &vector) const
Applies the filter onto a defect vector.
void filter_rhs (VectorType &vector) const
Applies the filter onto the right-hand-side vector.
void filter_sol (VectorType &vector) const
Applies the filter onto the solution vector.
IT_ * get_indices ()
const IT_ * get_indices () const
ValueType * get_values ()
const ValueType * get_values () const
SlipFilter & operator= (SlipFilter &&other)
move-assignment operator
Index size () const
Index used_elements () const
Static Public Attributes
static constexpr int BlockSize = BlockSize_
The block size.
Private Attributes
SparseVectorBlocked< DT_, IT_, BlockSize_ > _nu
This will contain the pointwise outer unit normal in all vertices.
SparseVectorBlocked< DT_, IT_, BlockSize_ > _sv
This will contain the data for filtering.
Detailed Description
template<typename DT_, typename IT_, int BlockSize_>
class FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >
Slip Filter class template.
Template Parameters
DT_ Data type, i.e. double
IT_ Index type, i.e. unsigned int
BlockSize_ Size of the blocks, i.e. 2 for a filter acting on a velocity field in 2d
An application of this filter sets a given vector component, i.e. it sets the normal component of a given velocity vector to zero. This is for enforcing boundary conditions like
\[ u \cdot \nu = g ~\mathrm{on}~ \Gamma \]
in the strong sense. An application of the slip filter \(f_s \) is can be written as
\[ f_s(u,g) = u - (u \cdot \nu) \nu + g \nu. \]
In the Finite Element case, this boundary condition can only be enforced in the strong sense if the FE space \(V_h \) is at least \(\mathcal{C}^0 \). One possible approximation is the condition that
\[ \forall j \in \Gamma_h: \mathcal{N}_j(f_{s,h} \cdot \nu_h) = \mathcal{N}_j(g), \]
where \(\mathcal{N}_j \) is the node functional to the Dof j associated with \(\Gamma_h, f_{s,h} \) is a discrete slip filter mapping and \(\nu_h \) is some discrete approximation of \(\nu \). Assuming \(g = 0 \) for simplicity, if \(v_j\) is a basis function of \(V_h \), possible choice is
\[ f_{s,h}(v_j) = v_j - \frac{\mathcal{N}_j(v_j \cdot \nu_h)}{\mathcal{N}_j (\nu_h \cdot \nu_h)} \nu_h. \]
In the case of conforming Lagrange elements, this reduces to
\[ f_{s,h}(v_h)(x_j) = v_h(x_j) - \frac{v_h \cdot \nu_h}{\nu_h \cdot \nu_h}(x_j) \nu(x_j) \]
for all Lagrange nodes \(x_j \in \Gamma \).
At the moment, the SlipFilterAssembler is only implemented for Lagrange 1 functions and P1/Q1 transformations. For conforming Lagrange p spaces, interpolation of the outer unit normal field to the Lagrange p space needs to be implemented. For other function spaces (especially nonconforming ones) it not clear if the above approximation is sensible in any way.
Even for spaces with enough regularity (at least \(\mathcal{C}^0 \)), the application of Node functionals to FE functions of a different space is missing.
Also missing: Filtering of matrices.
See also
Assembly::SlipFilterAssembler
Author
Jordi Paul
Definition at line 68 of file slip_filter.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ , int BlockSize_> typedef DT_ FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::DataType
data-type typedef
Definition at line 72 of file slip_filter.hpp.
FilterType
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::FilterType = SlipFilter<DT2_, IT2_, BlockSize_>
Our 'base' class type.
Definition at line 84 of file slip_filter.hpp.
FilterTypeByDI
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::FilterTypeByDI = FilterType<DT2_, IT2_>
For creating filter with different DT, IT.
Definition at line 88 of file slip_filter.hpp.
IndexType
template<typename DT_ , typename IT_ , int BlockSize_> typedef IT_ FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::IndexType
index-type typedef
Definition at line 74 of file slip_filter.hpp.
ValueType
template<typename DT_ , typename IT_ , int BlockSize_> typedef Tiny::Vector<DataType, BlockSize> FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::ValueType
Value type.
Definition at line 78 of file slip_filter.hpp.
VectorType
template<typename DT_ , typename IT_ , int BlockSize_> typedef DenseVectorBlocked<DT_, IT_, BlockSize_> FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::VectorType
Our supported vector type.
Definition at line 80 of file slip_filter.hpp.
Constructor & Destructor Documentation
SlipFilter() [1/3]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::SlipFilter () inline
default constructor
Definition at line 100 of file slip_filter.hpp.
SlipFilter() [2/3]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::SlipFilter (Index num_vertices, Index num_dofs) inline explicit
Constructor.
Parameters
[in] num_vertices Number of vertices in the mesh to save the outer unit normal field at.
[in] num_dofs Number of DoFs that will be filtered.
Definition at line 116 of file slip_filter.hpp.
SlipFilter() [3/3]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::SlipFilter (SlipFilter< DT_, IT_, BlockSize_ > && other) inline
move-ctor
Definition at line 123 of file slip_filter.hpp.
~SlipFilter()
template<typename DT_ , typename IT_ , int BlockSize_> virtual FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::~SlipFilter () inline virtual
virtual destructor
Definition at line 141 of file slip_filter.hpp.
Member Function Documentation
add()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::add (IndexType idx, ValueType val) inline
Adds one element to the filter.
Parameters
[in] idx Index where to add
[in] val Value to add
Definition at line 208 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
bytes()
template<typename DT_ , typename IT_ , int BlockSize_> std::size_t FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 176 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_nu, and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
clear()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clear () inline
Clears the underlying data (namely the SparseVector)
Definition at line 169 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_nu, and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
clone() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> SlipFilter FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Creates a clone of itself.
Definition at line 146 of file slip_filter.hpp.
Referenced by FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo(), and FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
clone() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clone (const SlipFilter< DT_, IT_, BlockSize_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clones data from another SlipFilter.
Definition at line 154 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_nu, and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
convert()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ , int BS_> void FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::convert (const SlipFilter< DT2_, IT2_, BS_ > & other) inline
Converts data from another UnitFilter.
Definition at line 162 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_nu, and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
filter_cor()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_cor (VectorType & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 301 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_def().
filter_def()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_def (VectorType & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 285 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
Referenced by FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_cor().
filter_rhs()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_rhs (VectorType & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 255 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
Referenced by FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_sol().
filter_sol()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_sol (VectorType & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 271 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_rhs().
get_indices() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> IT_ * FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::get_indices () inline
Returns
The index array.
Definition at line 226 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
get_indices() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> const IT_ * FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::get_indices () const inline
Returns
The index array.
Definition at line 232 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
get_values() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> ValueType * FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::get_values () inline
Returns
The value array.
Definition at line 238 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
get_values() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> const ValueType * FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::get_values () const inline
Returns
The value array.
Definition at line 244 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
operator=()
template<typename DT_ , typename IT_ , int BlockSize_> SlipFilter & FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::operator= (SlipFilter< DT_, IT_, BlockSize_ > && other) inline
move-assignment operator
Definition at line 130 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_nu, and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
size()
template<typename DT_ , typename IT_ , int BlockSize_> Index FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::size () const inline
Returns
The total size of the filter.
Definition at line 214 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
used_elements()
template<typename DT_ , typename IT_ , int BlockSize_> Index FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::used_elements () const inline
Returns
The number of entries in the filter.
Definition at line 220 of file slip_filter.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
Member Data Documentation
_nu
template<typename DT_ , typename IT_ , int BlockSize_> SparseVectorBlocked<DT_, IT_, BlockSize_> FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_nu private
This will contain the pointwise outer unit normal in all vertices.
Definition at line 94 of file slip_filter.hpp.
Referenced by FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::bytes(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::operator=().
_sv
template<typename DT_ , typename IT_ , int BlockSize_> SparseVectorBlocked<DT_, IT_, BlockSize_> FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::_sv private
This will contain the data for filtering.
Definition at line 96 of file slip_filter.hpp.
Referenced by FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::add(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::bytes(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_def(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::filter_sol(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::get_indices(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::get_values(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::size(), and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::used_elements().
BlockSize
template<typename DT_ , typename IT_ , int BlockSize_> constexpr int FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::BlockSize = BlockSize_ static constexpr
The block size.
Definition at line 76 of file slip_filter.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/slip_filter.hpp