FEAT: FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ > Class Template Reference
FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ > Class Template Reference
sparse banded matrix
#include <sparse_matrix_banded.hpp>
Classes
class GatherAxpy
Gather-Axpy operation for SparseMatrixBanded.
class ImageIterator
ImageIterator class for Adjactor interface implementation.
class ScatterAxpy
Scatter-Axpy operation for SparseMatrixBanded.
Public Types
template<typename DT2_ = DT_, typename IT2_ = IT_>
using ContainerType = SparseMatrixBanded< DT2_, IT2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a matrix container with different Data and Index types
typedef DT_ DataType
Our datatype.
typedef IT_ IndexType
Our indextype.
typedef DT_ ValueType
our value type
typedef DenseVector< DataType, IT_ > VectorTypeL
Compatible L-vector type.
typedef DenseVector< DataType, IT_ > VectorTypeR
Compatible R-vector type.
Public Member Functions
SparseMatrixBanded ()
Constructor.
SparseMatrixBanded (const Adjacency::Graph &graph)
Constructor.
SparseMatrixBanded (const Index rows_in, const Index columns_in, DenseVector< DT_, IT_ > &val_in, DenseVector< IT_, IT_ > &offsets_in)
Constructor.
template<typename MT_ >
SparseMatrixBanded (const MT_ &other)
Constructor.
SparseMatrixBanded (const SparseLayout< IT_, layout_id > &layout_in)
Constructor.
SparseMatrixBanded (FileMode mode, std::istream &file)
Constructor.
SparseMatrixBanded (FileMode mode, String filename)
Constructor.
SparseMatrixBanded (SparseMatrixBanded &&other)
Move Constructor.
template<typename DT2_ = DT_, typename IT2_ = IT_>
SparseMatrixBanded (std::vector< char > input)
Constructor.
Index & _columns ()
template<typename ITX_ >
Index _end_offset (const Index i, const ITX_ *const offsets, const Index rows_in, const Index columns_in, const Index noo) const
Returns last row-index of the diagonal matching to the offset i.
Index & _num_of_offsets ()
Index & _rows ()
Index & _size ()
template<typename ITX_ >
Index _start_offset (const Index i, const ITX_ *const offsets, const Index rows_in, const Index columns_in, const Index noo) const
Returns first row-index of the diagonal matching to the offset i.
Index & _used_elements ()
std::size_t bytes () const
Returns the total amount of bytes allocated.
virtual void clear ()
Free all allocated arrays.
SparseMatrixBanded clone (CloneMode clone_mode=CloneMode::Weak) const
Clone operation.
void clone (const Container &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const Container< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const SparseMatrixBanded< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<Perspective = Perspective::native>
Index columns () const
Retrieve matrix column count.
template<typename DT2_ , typename IT2_ >
void convert (const SparseMatrixBanded< DT2_, IT2_ > &other)
Conversion method.
template<typename DT2_ , typename IT2_ >
void convert (const SparseMatrixCSR< DT2_, IT2_ > &csr)
void copy (const SparseMatrixBanded &x, bool full=false)
Performs \(this \leftarrow x\).
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void deserialize (std::vector< char > input)
Deserialization of complete container entity.
bool empty () const
Checks whether the container is empty.
Index end_offset (const Index i) const
Returns last row-index of the diagonal matching to the offset i.
VectorTypeL extract_diag () const
extract main diagonal vector from matrix
void extract_diag (VectorTypeL &diag) const
void format (DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DT_ min, DT_ max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (const LAFEM::SerialConfig &config)
Calculate size.
const std::vector< DT_ * > & get_elements () const
Returns a list of all data arrays.
const std::vector< Index > & get_elements_size () const
Returns a list of all data array sizes.
const std::vector< IT_ * > & get_indices () const
Returns a list of all Index arrays.
const std::vector< Index > & get_indices_size () const
Returns a list of all Index array sizes.
Index get_num_nodes_domain () const
Index get_num_nodes_image () const
const std::vector< DT_ > & get_scalar_dt () const
Returns a list of all scalar values with datatype dt.
const std::vector< Index > & get_scalar_index () const
Returns a list of all scalar values with datatype index.
ImageIterator image_begin (Index domain_node) const
ImageIterator image_end (Index domain_node) const
SparseLayout< IT_, layout_id > layout () const
Retrieve convenient sparse matrix layout object.
void move (Container &&other)
Assignment move operation.
Index num_of_offsets () const
Retrieve number of offsets.
IT_ * offsets ()
Retrieve offsets array.
IT_ const * offsets () const
DT_ operator() (Index row, Index col) const
Retrieve specific matrix element.
SparseMatrixBanded & operator= (const SparseLayout< IT_, layout_id > &layout_in)
Assignment operator.
SparseMatrixBanded & operator= (SparseMatrixBanded &&other)
Move operator.
void read_from (FileMode mode, const String &filename)
Read in matrix from file.
void read_from (FileMode mode, std::istream &file)
Read in matrix from stream.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<Perspective = Perspective::native>
Index rows () const
Retrieve matrix row count.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > serialize (const LAFEM::SerialConfig &config=SerialConfig()) const
Serialization of complete container entity.
std::uint64_t set_checkpoint_data (std::vector< char > &data, const LAFEM::SerialConfig &config)
template<Perspective = Perspective::native>
Index size () const
Returns the containers size.
Index start_offset (const Index i) const
Returns first row-index of the diagonal matching to the offset i.
template<Perspective = Perspective::native>
Index used_elements () const
Retrieve non zero element count.
DT_ * val ()
Retrieve element array.
DT_ const * val () const
void write_out (FileMode mode, const String &filename) const
Write out matrix to file.
void write_out (FileMode mode, std::ostream &file) const
Write out matrix to file.
Linear algebra operations
void axpy (const SparseMatrixBanded &x, const SparseMatrixBanded &y, const DT_ alpha=DT_(1))
Calculate \(this \leftarrow y + \alpha~ x\).
void scale (const SparseMatrixBanded &x, const DT_ alpha)
Calculate \(this \leftarrow \alpha~ x \).
DT_ norm_frobenius () const
Calculates the Frobenius norm of this matrix.
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Static Public Member Functions
static String name ()
Returns a descriptive string.
Static Public Attributes
static constexpr SparseLayoutId layout_id = SparseLayoutId::lt_banded
Our used layout type.
Protected Member Functions
void _copy_content (const Container &other, bool full)
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::istream &file)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::vector< char > &input)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > _serialize (FileMode mode, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _serialize (FileMode mode, std::ostream &file, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::uint64_t _serialized_size (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Calculation of the serialized size with optional compression of complete container entity.
template<typename DT2_ , typename IT2_ >
void assign (const Container< DT2_, IT2_ > &other)
Assignment operation.
Protected Attributes
std::vector< DT_ * > _elements
List of pointers to all datatype dependent arrays.
std::vector< Index > _elements_size
List of corresponding datatype array sizes.
bool _foreign_memory
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
std::vector< IT_ * > _indices
List of pointers to all IT_ dependent arrays.
std::vector< Index > _indices_size
List of corresponding IT_ array sizes.
std::vector< DT_ > _scalar_dt
List of scalars with datatype DT_.
std::vector< Index > _scalar_index
List of scalars with datatype index.
Friends
std::ostream & operator<< (std::ostream &lhs, const SparseMatrixBanded &b)
SparseMatrixBanded streaming operator.
bool operator== (const SparseMatrixBanded &a, const SparseMatrixBanded &b)
SparseMatrixBanded comparison operator.
Detailed Description
template<typename DT_, typename IT_ = Index>
class FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >
sparse banded matrix
Template Parameters
DT_ The datatype to be used.
IT_ The indexing type to be used.
This class represents a sparse matrix, that stores its diagonal entries Data survey:
_elements[0]: raw non zero number values
_indices[0]: vector of offsets (bottom-left diagonal has offset 0, main diagonal has offset rows - 1 and top-right diagonal has offset row + columns - 2)
_scalar_index[0]: container size
_scalar_index[1]: row count
_scalar_index[2]: column count
_scalar_index[3]: non zero element count (used elements)
_scalar_index[4]: number of offsets
This class saves a sparse-matrix with a banded structure. For each diagonal of the matrix with non-zero elements there must be reserved memory for the whole diagonal. For faster access on the matrix-elements each diagonal get the virtual length of the row-count of the matrix. They are enlarged to the left and right side of the matrix as shown in the following layout.
      +--                  --+
 \    | \           \      \ |
  \   |\ \           \      \|
   \  | \ \           \      |
    \ |  \ \           \     |\
     \|   \ \           \    | \
      |    \ \           \   |  \
      |\    \ \           \  |   \
      +--                  --+
To get the position of the diagonals in the matrix, the matching offsets are saved from left to right in the offsets-array.
The first diagonal is the one at the bottom-left and gets the offset = 0,
the main diaognal has the offset = rows - 1
and the last offset at the top-right has the offset = rows + columns - 2.
Refer to LAFEM design description for general usage informations.
Author
Christoph Lohmann
Definition at line 78 of file sparse_matrix_banded.hpp.
Member Typedef Documentation
ContainerType
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::ContainerType = SparseMatrixBanded<DT2_, IT2_>
Our 'base' class type.
Definition at line 363 of file sparse_matrix_banded.hpp.
ContainerTypeByDI
template<typename DT_ , typename IT_ = Index> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a matrix container with different Data and Index types
Definition at line 367 of file sparse_matrix_banded.hpp.
DataType
template<typename DT_ , typename IT_ = Index> typedef DT_ FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::DataType
Our datatype.
Definition at line 313 of file sparse_matrix_banded.hpp.
IndexType
template<typename DT_ , typename IT_ = Index> typedef IT_ FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::IndexType
Our indextype.
Definition at line 315 of file sparse_matrix_banded.hpp.
ValueType
template<typename DT_ , typename IT_ = Index> typedef DT_ FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::ValueType
our value type
Definition at line 323 of file sparse_matrix_banded.hpp.
VectorTypeL
template<typename DT_ , typename IT_ = Index> typedef DenseVector<DataType, IT_> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::VectorTypeL
Compatible L-vector type.
Definition at line 317 of file sparse_matrix_banded.hpp.
VectorTypeR
template<typename DT_ , typename IT_ = Index> typedef DenseVector<DataType, IT_> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::VectorTypeR
Compatible R-vector type.
Definition at line 319 of file sparse_matrix_banded.hpp.
Constructor & Destructor Documentation
SparseMatrixBanded() [1/9]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded () inline explicit
Constructor.
Creates an empty non dimensional matrix.
Definition at line 374 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded().
SparseMatrixBanded() [2/9]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded (const SparseLayout< IT_, layout_id > & layout_in) inline explicit
Constructor.
Parameters
[in] layout_in The layout to be used.
Creates an empty matrix with given layout.
Definition at line 390 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows().
SparseMatrixBanded() [3/9]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded (const Index rows_in, const Index columns_in, DenseVector< DT_, IT_ > & val_in, DenseVector< IT_, IT_ > & offsets_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
[in] val_in The vector with non zero elements.
[in] offsets_in The vector of offsets.
Creates a matrix with given dimensions and content.
Definition at line 414 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::MemoryPool::increase_memory(), FEAT::Math::max(), FEAT::Math::min(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XABORTM.
SparseMatrixBanded() [4/9]
template<typename DT_ , typename IT_ = Index> template<typename MT_ > FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded (const MT_ & other) inline explicit
Constructor.
Parameters
[in] other The source matrix.
Creates a Banded matrix based on the source matrix.
Definition at line 463 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert().
SparseMatrixBanded() [5/9]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded (const Adjacency::Graph & graph) inline explicit
Constructor.
Parameters
[in] graph The graph to create the matrix from
Creates a matrix based on a given adjacency graph, representing the sparsity pattern.
Definition at line 476 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), and FEAT::LAFEM::Container< DT_, IT_ >::move().
SparseMatrixBanded() [6/9]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded (FileMode mode, String filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a banded matrix based on the source filestream.
Definition at line 520 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::read_from().
SparseMatrixBanded() [7/9]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded (FileMode mode, std::istream & file) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Creates a banded matrix based on the source filestream.
Definition at line 534 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::read_from().
SparseMatrixBanded() [8/9]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded (std::vector< char > input) inline explicit
Constructor.
Parameters
[in] input A std::vector, containing the byte array.
Creates a matrix from the given byte array.
Definition at line 548 of file sparse_matrix_banded.hpp.
SparseMatrixBanded() [9/9]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded (SparseMatrixBanded< DT_, IT_ > && other) inline
Move Constructor.
Parameters
[in] other The source matrix.
Moves a given matrix to this matrix.
Definition at line 561 of file sparse_matrix_banded.hpp.
Member Function Documentation
_columns()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_columns () inline
Definition at line 296 of file sparse_matrix_banded.hpp.
_copy_content()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::_copy_content (const Container< DT_, IT_ > & other, bool full) inline protected inherited
Definition at line 242 of file container.hpp.
_deserialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::istream & file) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file std::istream, pointing to the input data.
Recreate a complete container entity by a single binary file.
Definition at line 782 of file container.hpp.
References XABORTM.
_deserialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::vector< char > & input) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] input A std::vector containing the byte array.
Recreate a complete container entity by a single binary array.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 628 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Pack::decode(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Type::Helper::extract_floatness(), FEAT::Type::Helper::extract_intness(), FEAT::Type::Helper::extract_signedness(), FEAT::Type::Helper::extract_type_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, XABORTM, XASSERT, and XASSERTM.
_end_offset()
template<typename DT_ , typename IT_ = Index> template<typename ITX_ > Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_end_offset (const Index i, const ITX_ *const offsets, const Index rows_in, const Index columns_in, const Index noo) const inline
Returns last row-index of the diagonal matching to the offset i.
Definition at line 1157 of file sparse_matrix_banded.hpp.
References FEAT::Math::min(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets().
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::end_offset().
_num_of_offsets()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_num_of_offsets () inline
Definition at line 306 of file sparse_matrix_banded.hpp.
_rows()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_rows () inline
Definition at line 291 of file sparse_matrix_banded.hpp.
_serialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
Array data layout:
raw array size in bytes (std::uint64_t)
magic number (std::uint64_t)
DT_ 'hash' value (sizeof(DT_) and floating/integral distinction (packed std::uint64_t)
IT_ 'hash' value (sizeof(IT_) and floating/integral distinction (packed std::uint64_t)
_elements.size() (std::uint64_t)
_indices.size() (std::uint64_t)
_elements_size.size() (std::uint64_t)
_indices_size.size() (std::uint64_t)
_scalar_index.size() (std::uint64_t)
_scalar_dt.size() (std::uint64_t)
_compressed (std::uint64_t)
_elements_size array (std::uint64_t)
_elements arrays byte_size (std::uint64_t) just temporary to read in data
_indices_size array (std::uint64_t)
_indices arrays byte_size (std::uint64_t)
_scalar_index array (std::uint64_t)
_scalar_dt array (DT2_)
_elements arrays (DT2_)
_indices arrays (IT2_)
See FEAT::LAFEM::SerialConfig for details.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 446 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XASSERTM.
_serialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, std::ostream & file, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file The output stream to write data into.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary file with compression enabled. See FEAT::LAFEM::SerialConfig for details.
Definition at line 611 of file container.hpp.
References XABORTM.
_serialized_size()
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline protected inherited
Calculation of the serialized size with optional compression of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Returns
An unsigned int containing the size of serialized container.
Calculate the size of the serialized container entity.
Definition at line 363 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), and FEAT::LAFEM::indices_zlib.
_size()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_size () inline
Definition at line 286 of file sparse_matrix_banded.hpp.
_start_offset()
template<typename DT_ , typename IT_ = Index> template<typename ITX_ > Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_start_offset (const Index i, const ITX_ *const offsets, const Index rows_in, const Index columns_in, const Index noo) const inline
Returns first row-index of the diagonal matching to the offset i.
Definition at line 1138 of file sparse_matrix_banded.hpp.
References FEAT::Math::max(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets().
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::start_offset().
_used_elements()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_used_elements () inline
Definition at line 301 of file sparse_matrix_banded.hpp.
apply() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 964 of file sparse_matrix_banded.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), and XASSERTM.
apply() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 997 of file sparse_matrix_banded.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), and XASSERTM.
assign()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::assign (const Container< DT2_, IT2_ > & other) inline protected inherited
Assignment operation.
Assigns contents of another container
Parameters
[in] other The source container.
Definition at line 282 of file container.hpp.
References FEAT::MemoryPool::convert(), FEAT::MemoryPool::increase_memory(), FEAT::MemoryPool::release_memory(), and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::convert(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute().
axpy()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::axpy (const SparseMatrixBanded< DT_, IT_ > & x, const SparseMatrixBanded< DT_, IT_ > & y, const DT_ alpha = DT_(1)) inline
Calculate \(this \leftarrow y + \alpha~ x\).
Parameters
[in] x The first summand matrix to be scaled.
[in] y The second summand matrix
[in] alpha A scalar to multiply x with.
Definition at line 886 of file sparse_matrix_banded.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), and XASSERTM.
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::LAFEM::Container< DT_, IT_ >::bytes () const inline inherited
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 1047 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes().
clear()
template<typename DT_ , typename IT_ > virtual void FEAT::LAFEM::Container< DT_, IT_ >::clear () inline virtual inherited
Free all allocated arrays.
Definition at line 880 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from().
clone() [1/4]
template<typename DT_ , typename IT_ = Index> SparseMatrixBanded FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone (CloneMode clone_mode = CloneMode::Weak) const inline
Clone operation.
Create a clone of this container.
Parameters
[in] clone_mode The actual cloning procedure.
Returns
The created clone.
Definition at line 588 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone().
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone().
clone() [2/4]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 907 of file container.hpp.
References FEAT::LAFEM::Allocate, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Deep, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Layout, FEAT::LAFEM::Shallow, FEAT::LAFEM::Weak, XABORTM, and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVector< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone().
clone() [3/4]
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 980 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), and FEAT::LAFEM::Container< DT_, IT_ >::clone().
clone() [4/4]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone (const SparseMatrixBanded< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline
Clone operation.
Create a clone of another container.
Parameters
[in] other The source container to create the clone from.
[in] clone_mode The actual cloning procedure.
Definition at line 604 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clone().
columns()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns () const inline
Retrieve matrix column count.
Returns
Matrix column count.
Definition at line 800 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::create_vector_r(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::end_offset(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::get_num_nodes_image(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::scale(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::start_offset().
convert() [1/2]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert (const SparseMatrixBanded< DT2_, IT2_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 650 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign().
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded().
convert() [2/2]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert (const SparseMatrixCSR< DT2_, IT2_ > & csr) inline
Definition at line 656 of file sparse_matrix_banded.hpp.
copy()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::copy (const SparseMatrixBanded< DT_, IT_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The Matrix to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 872 of file sparse_matrix_banded.hpp.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::axpy().
create_vector_l()
template<typename DT_ , typename IT_ = Index> VectorTypeL FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 1125 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows().
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag().
create_vector_r()
template<typename DT_ , typename IT_ = Index> VectorTypeR FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 1131 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns().
deserialize()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::deserialize (std::vector< char > input) inline
Deserialization of complete container entity.
Parameters
[in] input A std::vector, containing the byte array.
Recreate a complete container entity by a single binary array.
Definition at line 1066 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::fm_bm.
empty()
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::empty () const inline inherited
Checks whether the container is empty.
Returns
true if the container is empty, otherwise false.
Definition at line 1170 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic().
end_offset()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::end_offset (const Index i) const inline
Returns last row-index of the diagonal matching to the offset i.
Definition at line 1181 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_end_offset(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows().
extract_diag() [1/2]
template<typename DT_ , typename IT_ = Index> VectorTypeL FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag () const inline
extract main diagonal vector from matrix
Definition at line 1051 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::create_vector_l(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag().
extract_diag() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag (VectorTypeL & diag) const inline
Definition at line 1035 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::MemoryPool::copy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), and XASSERTM.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag().
format() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (DT_ value = DT_(0)) inline inherited
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 853 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::MemoryPool::set_memory(), and FEAT::value.
Referenced by FEAT::Assembly::CellErrorFunctionIntegralJob< Function_, Vector_, Space_, max_der_ >::CellErrorFunctionIntegralJob(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), FEAT::Assembly::CellErrorFunctionIntegralJob< Function_, Vector_, Space_, max_der_ >::result(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
format() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (Random & rng, DT_ min, DT_ max) inline inherited
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 866 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::MemoryPool::set_memory().
get_checkpoint_size()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::get_checkpoint_size (const LAFEM::SerialConfig & config) inline inherited
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1023 of file container.hpp.
get_elements()
template<typename DT_ , typename IT_ > const std::vector< DT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements () const inline inherited
Returns a list of all data arrays.
Returns
A list of all data arrays.
Definition at line 1073 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
get_elements_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size () const inline inherited
Returns a list of all data array sizes.
Returns
A list of all data array sizes.
Definition at line 1093 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
get_indices()
template<typename DT_ , typename IT_ > const std::vector< IT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices () const inline inherited
Returns a list of all Index arrays.
Returns
A list of all Index arrays.
Definition at line 1083 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
get_indices_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size () const inline inherited
Returns a list of all Index array sizes.
Returns
A list of all Index array sizes.
Definition at line 1103 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices_size.
get_num_nodes_domain()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::get_num_nodes_domain () const inline
Definition at line 1191 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows().
get_num_nodes_image()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::get_num_nodes_image () const inline
Definition at line 1197 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns().
get_scalar_dt()
template<typename DT_ , typename IT_ > const std::vector< DT_ > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt () const inline inherited
Returns a list of all scalar values with datatype dt.
Returns
A list of all scalars with datatype dt.
Definition at line 1123 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt.
get_scalar_index()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index () const inline inherited
Returns a list of all scalar values with datatype index.
Returns
A list of all scalars with datatype index.
Definition at line 1113 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
image_begin()
template<typename DT_ , typename IT_ = Index> ImageIterator FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::image_begin (Index domain_node) const inline
Definition at line 1203 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), and XASSERT.
image_end()
template<typename DT_ , typename IT_ = Index> ImageIterator FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::image_end (Index domain_node) const inline
Definition at line 1219 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), and XASSERT.
layout()
template<typename DT_ , typename IT_ = Index> SparseLayout< IT_, layout_id > FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout () const inline
Retrieve convenient sparse matrix layout object.
Returns
An object containing the sparse matrix layout.
Definition at line 778 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
move()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::move (Container< DT_, IT_ > && other) inline inherited
Assignment move operation.
Move another container to the current one.
Parameters
[in] other The source container.
Definition at line 994 of file container.hpp.
References FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
name()
template<typename DT_ , typename IT_ = Index> static String FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 861 of file sparse_matrix_banded.hpp.
norm_frobenius()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::norm_frobenius () const inline
Calculates the Frobenius norm of this matrix.
Returns
The Frobenius norm of this matrix.
Definition at line 944 of file sparse_matrix_banded.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val().
num_of_offsets()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets () const inline
Retrieve number of offsets.
Returns
Number of offsets.
Definition at line 821 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::end_offset(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::scale(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::start_offset().
offsets() [1/2]
template<typename DT_ , typename IT_ = Index> IT_ * FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets () inline
Retrieve offsets array.
Returns
offsets array.
Definition at line 846 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_end_offset(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_start_offset(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::end_offset(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::start_offset().
offsets() [2/2]
template<typename DT_ , typename IT_ = Index> IT_ const * FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets () const inline
Definition at line 851 of file sparse_matrix_banded.hpp.
operator()()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator() (Index row, Index col) const inline
Retrieve specific matrix element.
Parameters
[in] row The row of the matrix element.
[in] col The column of the matrix element.
Returns
Specific matrix element.
Definition at line 753 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, ASSERT, FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val().
operator=() [1/2]
template<typename DT_ , typename IT_ = Index> SparseMatrixBanded & FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator= (const SparseLayout< IT_, layout_id > & layout_in) inline
Assignment operator.
Parameters
[in] layout_in A sparse matrix layout.
Assigns a new matrix layout, discarding all old data
Definition at line 616 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::MemoryPool::release_memory(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows().
operator=() [2/2]
template<typename DT_ , typename IT_ = Index> SparseMatrixBanded & FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator= (SparseMatrixBanded< DT_, IT_ > && other) inline
Move operator.
Parameters
[in] other The source matrix.
Moves another matrix to the target matrix.
Definition at line 573 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::move().
read_from() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::read_from (FileMode mode, const String & filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 1094 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::read_from().
read_from() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::read_from (FileMode mode, std::istream & file) inline
Read in matrix from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Definition at line 1111 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_bm, and XABORTM.
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::restore_from_checkpoint_data (std::vector< char > & data) inline inherited
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1029 of file container.hpp.
References FEAT::LAFEM::fm_binary.
rows()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows () const inline
Retrieve matrix row count.
Returns
Matrix row count.
Definition at line 789 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::create_vector_l(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::end_offset(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::get_num_nodes_domain(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::image_end(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::matrix_banded(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::scale(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::start_offset().
scale()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::scale (const SparseMatrixBanded< DT_, IT_ > & x, const DT_ alpha) inline
Calculate \(this \leftarrow \alpha~ x \).
Parameters
[in] x The matrix to be scaled.
[in] alpha A scalar to scale x with.
Definition at line 922 of file sparse_matrix_banded.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), and XASSERTM.
serialize()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::serialize (const LAFEM::SerialConfig & config = SerialConfig()) const inline
Serialization of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary array.
See FEAT::LAFEM::Container::_serialize for details.
Definition at line 1083 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::fm_bm.
set_checkpoint_data()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::set_checkpoint_data (std::vector< char > & data, const LAFEM::SerialConfig & config) inline inherited
Definition at line 1035 of file container.hpp.
References FEAT::LAFEM::fm_binary.
size()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::size () const inline inherited
Returns the containers size.
Returns
The containers size.
The template parameter of type Perspective is used in blocked containers to switch between the raw size and the size, when every block is treated as one entry.
Most containers like SparseMatrixCSR ignore this template parameter.
Definition at line 1141 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseVector< DT_, IT_ >::compare_layout(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_local_dofs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::get_num_nodes_image(), FEAT::LAFEM::DenseVector< DT_, IT_ >::inflate_to_blocks(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::Assembly::FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >::interpolate(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::make_empty(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::map_local_to_global_index(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::mask_scatter(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::write_out().
start_offset()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::start_offset (const Index i) const inline
Returns first row-index of the diagonal matching to the offset i.
Definition at line 1175 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::_start_offset(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows().
used_elements()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements () const inline
Retrieve non zero element count.
Returns
Non zero element count.
Definition at line 811 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::norm_frobenius(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::scale().
val() [1/2]
template<typename DT_ , typename IT_ = Index> DT_ * FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val () inline
Retrieve element array.
Returns
Non zero element array.
Definition at line 831 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::matrix_banded(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::scale().
val() [2/2]
template<typename DT_ , typename IT_ = Index> DT_ const * FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val () const inline
Definition at line 836 of file sparse_matrix_banded.hpp.
write_out() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::write_out (FileMode mode, const String & filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 704 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::FileOutStreamBufferSize, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::write_out().
write_out() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::write_out (FileMode mode, std::ostream & file) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
Definition at line 729 of file sparse_matrix_banded.hpp.
References FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_bm, and XABORTM.
Friends And Related Function Documentation
operator<<
template<typename DT_ , typename IT_ = Index> std::ostream & operator<< (std::ostream & lhs, const SparseMatrixBanded< DT_, IT_ > & b) friend
SparseMatrixBanded streaming operator.
Parameters
[in] lhs The target stream.
[in] b The matrix to be streamed.
Definition at line 1298 of file sparse_matrix_banded.hpp.
operator==
template<typename DT_ , typename IT_ = Index> bool operator== (const SparseMatrixBanded< DT_, IT_ > & a, const SparseMatrixBanded< DT_, IT_ > & b) friend
SparseMatrixBanded comparison operator.
Parameters
[in] a A matrix to compare with.
[in] b A matrix to compare with.
Definition at line 1244 of file sparse_matrix_banded.hpp.
Member Data Documentation
_elements
template<typename DT_ , typename IT_ > std::vector<DT_*> FEAT::LAFEM::Container< DT_, IT_ >::_elements protected inherited
List of pointers to all datatype dependent arrays.
Definition at line 228 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
_elements_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_elements_size protected inherited
List of corresponding datatype array sizes.
Definition at line 232 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_foreign_memory
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory protected inherited
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
Definition at line 240 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), and FEAT::LAFEM::Container< DT_, IT_ >::clear().
_indices
template<typename DT_ , typename IT_ > std::vector<IT_*> FEAT::LAFEM::Container< DT_, IT_ >::_indices protected inherited
List of pointers to all IT_ dependent arrays.
Definition at line 230 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseVector< DT_, IT_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
_indices_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_indices_size protected inherited
List of corresponding IT_ array sizes.
Definition at line 234 of file container.hpp.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_scalar_dt
template<typename DT_ , typename IT_ > std::vector<DT_> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt protected inherited
List of scalars with datatype DT_.
Definition at line 238 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), and FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt().
_scalar_index
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index protected inherited
List of scalars with datatype index.
Definition at line 236 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::Container(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVector< DT_, IT_ >::allocated_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::sorted(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size().
layout_id
template<typename DT_ , typename IT_ = Index> constexpr SparseLayoutId FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout_id = SparseLayoutId::lt_banded static constexpr
Our used layout type.
Definition at line 321 of file sparse_matrix_banded.hpp.
The documentation for this class was generated from the following files:
kernel/lafem/forward.hpp
kernel/lafem/sparse_matrix_banded.hpp