FEAT: FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ > Class Template Reference
FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ > Class Template Reference abstract
Boundary description by a surface mesh in 3d.
#include <surface_mesh.hpp>
Public Types
typedef PartType::AttributeSetType AttributeSetType
attribute type of our mesh-part
typedef ChartCRTP< SurfaceMesh< Mesh_ >, Mesh_, SurfaceMeshTraits > BaseClass
The CRTP base class.
typedef BaseClass::CoordType CoordType
Floating point type for coordinates.
typedef BaseClass::MeshType MeshType
mesh type
typedef Tiny::Vector< CoordType, param_dim > ParamPoint
out parameter type
typedef BaseClass::PartType PartType
mesh-part type
typedef Shape::Simplex< 2 > ShapeType
The shape type is always Simplex<2>
typedef ConformalMesh< ShapeType, 3, CoordType > SurfaceMeshType
The type for the mesh defining the discrete surface.
typedef SurfaceMeshTraits TraitsType
traits type
typedef MeshType::VertexSetType VertexSetType
vertex set type of our mesh
typedef BaseClass::WorldPoint WorldPoint
Vector type for world points.
Public Member Functions
SurfaceMesh ()=delete
Explicitly delete empty default constructor.
SurfaceMesh (std::unique_ptr< SurfaceMeshType > surf_mesh)
Constructor getting an object.
SurfaceMesh (SurfaceMeshType &&)=delete
Explicitly delete move constructor.
virtual ~SurfaceMesh ()
Virtual destructor.
virtual void adapt (MeshType &mesh, const PartType &part) const override
Adapts a whole MeshPart.
virtual void adapt (PartType &parent_meshpart, const PartType &meshpart) const override
Adapts a whole MeshPart referring to another MeshPart.
virtual std::size_t bytes () const override
virtual bool can_explicit () const override
virtual bool can_implicit () const override
CoordType compute_dist (const WorldPoint &point) const
Computes the distance of a point to this chart.
CoordType compute_dist (const WorldPoint &point, WorldPoint &grad_distance) const
Computes the distance of a point to this chart.
CoordType compute_signed_dist (const WorldPoint &point) const
Computes the signed distance of a point to this chart.
CoordType compute_signed_dist (const WorldPoint &point, WorldPoint &grad_distance) const
Computes the signed distance of a point to this chart.
virtual CoordType dist (const WorldPoint &point) const override
virtual CoordType dist (const WorldPoint &point, WorldPoint &grad_dist) const override
WorldPoint get_normal_on_tria (const Index facet, const Tiny::Vector< CoordType, SurfaceMeshType::shape_dim+1 > coeffs) const
Computes the outer normal on a triangle for a single point.
virtual String get_type () const override
Writes the type as String.
virtual WorldPoint map (const WorldPoint &param) const override
virtual WorldPoint project (const WorldPoint &point) const override
void project_meshpart (Mesh_ &mesh, const MeshPart< Mesh_ > &meshpart) const
Orthogonally projects all vertices at facets of a MeshPart.
void project_point (WorldPoint &point) const
Projects a single point to the surface given by the surface mesh.
void project_point (WorldPoint &point, CoordType &signed_distance, WorldPoint &grad_distance) const
Projects a single point to the surface given by the surface mesh.
virtual CoordType signed_dist (const WorldPoint &point) const override
virtual CoordType signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset) override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset)=0
Applies a "proper rigid" transformation onto the chart.
virtual void write (std::ostream &os, const String &sindent) const override
Writes the Chart into a stream in XML format.
Public Attributes
std::unique_ptr< SurfaceMeshType > _surface_mesh
Pointer to the surface mesh object.
Static Public Attributes
static constexpr bool is_explicit
specifies whether this chart is explicit
static constexpr bool is_implicit
specifies whether this chart is implicit
static constexpr int param_dim
the parameter dimension of this chart
static constexpr int world_dim
the world dimension of this chart
Protected Member Functions
SurfaceMesh< Mesh_ > & cast ()
Casts this to its true type.
const SurfaceMesh< Mesh_ > & cast () const
Private Member Functions
template<int world_dim, int sc_, int sx_>
Index find_cell (Tiny::Vector< CoordType, SurfaceMeshType::shape_dim+1, sc_ > &coeffs, const Tiny::Vector< CoordType, world_dim, sx_ > &x, Index guess, CoordType acceptable_distance, const SurfaceMeshType &mesh, bool find_best_approx) const
Finds the cell in the surface mesh that contains a specific point.
Static Private Member Functions
template<typename DT_ , int n_, int sn_, int sb_>
static DT_ compute_bary_and_dist (Tiny::Vector< DT_, n_, sb_ > &bary, const Tiny::Vector< DT_, n_, sn_ > &coeffs)
For given reference cell coordinates, this computes the barycentric coordinates and the distance.
template<typename DT_ , int n_, int sn_, typename IdxType_ >
static bool determine_success (DT_ ortho_dist, DT_ acceptable_distance, Tiny::Vector< DT_, n_, sn_ > &bary, const IdxType_ &facet_idx, bool *traversed)
Determines the success of the point search.
Private Attributes
bool * _cell_marker
Marker for triangles.
bool * _edge_marker
Marker for edges.
Detailed Description
template<typename Mesh_>
class FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >
Boundary description by a surface mesh in 3d.
Template Parameters
Mesh_ Type for the mesh this boundary description refers to
Author
Jordi Paul
Todo:
replace bool arrays by something more modern
Definition at line 52 of file surface_mesh.hpp.
Member Typedef Documentation
AttributeSetType
typedef PartType::AttributeSetType FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::AttributeSetType inherited
attribute type of our mesh-part
Definition at line 365 of file chart.hpp.
BaseClass
template<typename Mesh_ > typedef ChartCRTP<SurfaceMesh<Mesh_>, Mesh_, SurfaceMeshTraits> FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::BaseClass
The CRTP base class.
Definition at line 57 of file surface_mesh.hpp.
CoordType
template<typename Mesh_ > typedef BaseClass::CoordType FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::CoordType
Floating point type for coordinates.
Definition at line 59 of file surface_mesh.hpp.
MeshType
typedef BaseClass::MeshType FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::MeshType inherited
mesh type
Definition at line 361 of file chart.hpp.
ParamPoint
typedef Tiny::Vector<CoordType, param_dim> FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::ParamPoint inherited
out parameter type
Definition at line 385 of file chart.hpp.
PartType
typedef BaseClass::PartType FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::PartType inherited
mesh-part type
Definition at line 363 of file chart.hpp.
ShapeType
template<typename Mesh_ > typedef Shape::Simplex<2> FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::ShapeType
The shape type is always Simplex<2>
Definition at line 63 of file surface_mesh.hpp.
SurfaceMeshType
template<typename Mesh_ > typedef ConformalMesh<ShapeType, 3, CoordType> FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::SurfaceMeshType
The type for the mesh defining the discrete surface.
Definition at line 65 of file surface_mesh.hpp.
TraitsType
typedef SurfaceMeshTraits FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::TraitsType inherited
traits type
Definition at line 359 of file chart.hpp.
VertexSetType
typedef MeshType::VertexSetType FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::VertexSetType inherited
vertex set type of our mesh
Definition at line 367 of file chart.hpp.
WorldPoint
template<typename Mesh_ > typedef BaseClass::WorldPoint FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::WorldPoint
Vector type for world points.
Definition at line 61 of file surface_mesh.hpp.
Constructor & Destructor Documentation
SurfaceMesh()
template<typename Mesh_ > FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::SurfaceMesh (std::unique_ptr< SurfaceMeshType > surf_mesh) inline explicit
Constructor getting an object.
Definition at line 86 of file surface_mesh.hpp.
~SurfaceMesh()
template<typename Mesh_ > virtual FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::~SurfaceMesh () inline virtual
Virtual destructor.
Definition at line 99 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_cell_marker, and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_edge_marker.
Member Function Documentation
adapt() [1/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::adapt (MeshType & mesh, const PartType & part) const inline override virtual inherited
Adapts a whole MeshPart.
Parameters
[in] mesh Mesh to be adapted
[in] part MeshPart identifying the region to be adapted
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 420 of file chart.hpp.
adapt() [2/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::adapt (PartType & parent_meshpart, const PartType & meshpart) const inline override virtual inherited
Adapts a whole MeshPart referring to another MeshPart.
Parameters
[in] parent_meshpart MeshPart to be adapted
[in] meshpart MeshPart identifying the region to be adapted
Todo:
: Implement this
There is currently no code that uses MeshParts referring to other MeshParts instead of a RootMesh.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 450 of file chart.hpp.
bytes()
template<typename Mesh_ > virtual std::size_t FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::bytes () const inline override virtual
Returns
The size of dynamically allocated memory in bytes.
Reimplemented from FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 106 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_surface_mesh.
can_explicit()
virtual bool FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::can_explicit () const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 400 of file chart.hpp.
can_implicit()
virtual bool FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::can_implicit () const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 406 of file chart.hpp.
cast() [1/2]
SurfaceMesh< Mesh_ > & FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::cast () inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this
Definition at line 393 of file chart.hpp.
cast() [2/2]
const SurfaceMesh< Mesh_ > & FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::cast () const inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this\ifile "/github/workspace/kernel/geometry/atlas/chart.hpp"
Definition at line 396 of file chart.hpp.
compute_bary_and_dist()
template<typename Mesh_ > template<typename DT_ , int n_, int sn_, int sb_> static DT_ FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_bary_and_dist (Tiny::Vector< DT_, n_, sb_ > & bary, const Tiny::Vector< DT_, n_, sn_ > & coeffs) inline static private
For given reference cell coordinates, this computes the barycentric coordinates and the distance.
Template Parameters
DT_ The floating point type
n_ World dimension of the points to compute the inverse mapping for
sn_ Stride for the vector of coefficients
sb_ Stride for the vector of barycentric coordinates
Parameters
[out] bary The vector of barycentric coordinates.
[in] coeffs The coefficients for the mapping from the reference cell to the real cell
Returns
The absolute value of the last coefficient, which is the absolute distance.
Assume we have a non-degenerate Simplex called \(S \) in \(\mathbb{R}^d \) defined by vertices \(x^j \in \mathbb{R}^d, j = 0, \dots, s \). Assume for now that \(s = d \).
Then
\[ \forall x \in \mathbb{R}^d: x = x^0 + \sum_{j=1}^s \lambda_j (x^j - x^0) \]
and \(\lambda_j, j=1,\dots,s \) with \(\lambda_0 := 1 - sum_{j=1}^s \) are called the barycentric coordinates of \(x \) wrt. S . Note that the above equation can be rewritten as
\[ \forall x \in \mathbb{R}^d: x = \sum_{j=0}^s \lambda_j x^j. \]
It is easy to see that
\[ x \in S \Leftrightarrow \forall j = 0, \dots, d: \lambda_j \in [0, 1] . \]
If \(\exists j \in \{ 0, \dots, s \}: \lambda_j < 0 \), then \(x \notin S \) and \(x \) lies on the far side of the plane defined by the facet opposite vertex \(j \). This makes the barycentric coordinates very handy for finding out in which direction of a given simplex a point lies.
This routine assumes that \(s = d-1 \), where \(d = 2, 3 \) and that the last coefficient is actually the signed distance of the point \(x \) to which the coefficients belong to the hyperplane defined by \(S \).
Definition at line 733 of file surface_mesh.hpp.
References FEAT::Math::abs().
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell().
compute_dist() [1/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_dist (const WorldPoint & point) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 483 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_dist().
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_dist().
compute_dist() [2/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_dist (const WorldPoint & point, WorldPoint & grad_distance) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 490 of file surface_mesh.hpp.
References FEAT::Math::abs(), and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point().
compute_signed_dist() [1/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_signed_dist (const WorldPoint & point) const inline
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Definition at line 500 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_signed_dist().
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_signed_dist().
compute_signed_dist() [2/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_signed_dist (const WorldPoint & point, WorldPoint & grad_distance) const inline
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Definition at line 507 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point().
determine_success()
template<typename Mesh_ > template<typename DT_ , int n_, int sn_, typename IdxType_ > static bool FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::determine_success (DT_ ortho_dist, DT_ acceptable_distance, Tiny::Vector< DT_, n_, sn_ > & bary, const IdxType_ & facet_idx, bool * traversed) inline static private
Determines the success of the point search.
Template Parameters
DT_ Floating point type for coordinates
n_ Number of barycentric coordinates, meaning shape_dim+1
sn_ Stride for the vector of barycentric coordinates
IdxType_ Type of the IndexSet of appropriate size
Parameters
[in] ortho_dist Orthogonal distance of the point to the appropriate plane
[in] acceptable_distance Tolerance for ortho_dist
[in] bary Barycentric coordinates of the point in the current cell
[in] facet_idx Facet at current cell information
[in] traversed Marker which facets have been traversed so far
Returns
True if bary and traversed indicate that the point can be projected to the current cell.
After the barycentric coordinates of a point wrt. a cell have been computed, we have to determine if the point lies in that cell. This is definitely the case if
\[ \forall j=0, \dots, s: \lambda_j \in [0, 1] \wedge\mathrm{ortho_dist} = 0. \]
If the first condition holds, the second is violated but \(\mathrm{ortho_dist} < \mathrm{acceptable_distance} \), the search was successful as well.
Because we are dealing with floats, we add some tolerance either way. The remaining problem is a concave surface like this:
 x
 (exteriour)
 *--------------
 |            (1)
 | (0)       (interiour)
 |
The barycentric coordinates of edge 0 will point into direction of edge 1 and vice versa. For this, we keep the traversed information: If we first compute the barycentric coordinates wrt. edge (0), it will mark the facet * (which is just a vertex in this case) as traversed. If we later computed the barycentric coordinates of x wrt. edge (1), the coordinate belonging to vertex * will be negative, pointing us back to edge (0). But * has been marked as traversed, so setting that negative barycentric coordinate to zero means (if not other barycentric coordinate was lower than 0) we project to that facet, in this case: * .
Definition at line 810 of file surface_mesh.hpp.
References FEAT::Math::sqrt().
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell().
dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 479 of file chart.hpp.
dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 485 of file chart.hpp.
find_cell()
template<typename Mesh_ > template<int world_dim, int sc_, int sx_> Index FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell (Tiny::Vector< CoordType, SurfaceMeshType::shape_dim+1, sc_ > & coeffs, const Tiny::Vector< CoordType, world_dim, sx_ > & x, Index guess, CoordType acceptable_distance, const SurfaceMeshType & mesh, bool find_best_approx) const inline private
Finds the cell in the surface mesh that contains a specific point.
Template Parameters
world_dim World dimension, meaning the number of coordinates.
sc_ Stride for the coefficients vector.
sx_ Stride for the vector containing the point.
Parameters
[out] coeffs The coefficients that map x to its projection under the standard transformation.
[in] x The point we are looking for.
[in] guess The facet in the surface mesh we start looking for x in.
[in] acceptable_distance The maximum distance we want to move in orthogonal direction, so we do not project to the far side of the domain by accident.
[in] mesh The (surface) mesh we are looking for x in.
For every subfacet, we need to know if it was already traversed by adding the neighbor across said facet to the search stack. If the surface is concave, it might happen that facet A says "go to my neighbor, B", and then B says "go to my neighbor, A". It's then clear that the wanted point lies on the facet between A and B (c.f. determine_success()).
See also
determine_success
Returns
The index of the cell in which x was found
Definition at line 554 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_cell_marker, FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_edge_marker, FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_bary_and_dist(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::determine_success(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_neighbors(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_vertex_set(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim, FEAT::stringify(), and XASSERTM.
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_meshpart(), and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point().
get_normal_on_tria()
template<typename Mesh_ > WorldPoint FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::get_normal_on_tria (const Index facet, const Tiny::Vector< CoordType, SurfaceMeshType::shape_dim+1 > coeffs) const inline
Computes the outer normal on a triangle for a single point.
Parameters
[in] facet Number of the triangle.
[in] coeffs Coefficients of the point where we want to compute the normal.
Returns
The outer (unit) normal vector at the given point.
Definition at line 288 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_surface_mesh, FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::m, FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::n, and FEAT::Tiny::orthogonal().
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point().
get_type()
template<typename Mesh_ > virtual String FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::get_type () const inline override virtual
Writes the type as String.
Needed for writing this to mesh files.
Returns
The class name as String.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 115 of file surface_mesh.hpp.
map()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::map (const WorldPoint & param) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 456 of file chart.hpp.
project()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::project (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 468 of file chart.hpp.
project_meshpart()
template<typename Mesh_ > void FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_meshpart (Mesh_ & mesh, const MeshPart< Mesh_ > & meshpart) const inline
Orthogonally projects all vertices at facets of a MeshPart.
Parameters
[in,out] mesh The mesh the Meshpart refers to and whose vertices are to be projected
[in] meshpart The meshpart identifying the boundary of the mesh that is to be projected
The MeshPart has to contain facets and a topology for them. To keep the search as local as possible, the MeshPart is traversed facet-wise and after finishing the current facet, its neighbors are added to the search stack.
Definition at line 332 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_surface_mesh, FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell(), FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities(), FEAT::Math::pow(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim, and XASSERTM.
project_point() [1/2]
template<typename Mesh_ > void FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point (WorldPoint & point) const inline
Projects a single point to the surface given by the surface mesh.
Parameters
[in,out] point The point that gets projected.
Definition at line 195 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point().
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_dist(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::compute_signed_dist(), and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point().
project_point() [2/2]
template<typename Mesh_ > void FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point (WorldPoint & point, CoordType & signed_distance, WorldPoint & grad_distance) const inline
Projects a single point to the surface given by the surface mesh.
Parameters
[in,out] point The point that gets projected.
[in,out] signed_distance The signed distance of the original to the projected point.
[in,out] grad_distance Gradient of the distance function.
Definition at line 215 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_surface_mesh, FEAT::Tiny::dot(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::get_normal_on_tria(), FEAT::Math::max(), FEAT::Math::min(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim, and FEAT::Math::signum().
signed_dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::signed_dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 491 of file chart.hpp.
signed_dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 497 of file chart.hpp.
transform() [1/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) inline override virtual
Definition at line 121 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_surface_mesh, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_3d().
transform() [2/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::ChartBase< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) pure virtual inherited
Applies a "proper rigid" transformation onto the chart.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any point x of the chart:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any point before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): -ignored-
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any point after applying the rotation.
Implemented in FEAT::Geometry::Atlas::CGALSurfaceMesh< Mesh_ >.
write()
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::write (std::ostream & os, const String & sindent) const inline override virtual
Writes the Chart into a stream in XML format.
Parameters
[in,out] os The output stream to write into.
[in] sindent The indentation string.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 138 of file surface_mesh.hpp.
References FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_surface_mesh, FEAT::Shape::Simplex< dimension_ >::dimension, and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::world_dim.
Member Data Documentation
_cell_marker
template<typename Mesh_ > bool* FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_cell_marker private
Marker for triangles.
Definition at line 77 of file surface_mesh.hpp.
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::~SurfaceMesh(), and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell().
_edge_marker
template<typename Mesh_ > bool* FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_edge_marker private
Marker for edges.
Definition at line 75 of file surface_mesh.hpp.
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::~SurfaceMesh(), and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell().
_surface_mesh
template<typename Mesh_ > std::unique_ptr<SurfaceMeshType> FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::_surface_mesh
Pointer to the surface mesh object.
Definition at line 67 of file surface_mesh.hpp.
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::bytes(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::get_normal_on_tria(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_meshpart(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::transform(), and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::write().
is_explicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::is_explicit static constexpr inherited
specifies whether this chart is explicit
Definition at line 372 of file chart.hpp.
is_implicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::is_implicit static constexpr inherited
specifies whether this chart is implicit
Definition at line 374 of file chart.hpp.
param_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::param_dim static constexpr inherited
the parameter dimension of this chart
Definition at line 379 of file chart.hpp.
world_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< SurfaceMesh< Mesh_ > , Mesh_, SurfaceMeshTraits >::world_dim static constexpr inherited
the world dimension of this chart
Definition at line 377 of file chart.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/atlas/surface_mesh.hpp