FEAT: FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ > Class Template Reference
FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ > Class Template Reference
SystemLevel for a quadratic mesh quality functional leading to a linear system.
#include <meshopt_control.hpp>
Public Types
typedef MeshoptSystemLevel< DT_, IT_, Functional_ > BaseClass
Our base class.
typedef DT_ DataType
Floating point precision for the solver.
typedef Global::Vector< LocalCoordsBuffer, SystemMirror > GlobalCoordsBuffer
Global coordinates buffer.
typedef Global::Vector< LocalScalarVector, ScalarMirror > GlobalScalarVector
Global scalar vector type.
typedef Global::Filter< LocalSystemFilter, SystemMirror > GlobalSystemFilter
Global system filter type.
typedef Global::Matrix< LocalMatrix, SystemMirror, SystemMirror > GlobalSystemMatrix
Global mesh quality functional type.
typedef Global::Muxer< LocalSystemVectorR, SystemMirror > GlobalSystemMuxer
The global muxer for mapping data from one partitioning to the other on this level.
typedef Global::Transfer< LocalSystemTransfer, SystemMirror > GlobalSystemTransfer
Global system transfer operator.
typedef Global::Vector< LocalSystemVectorL, SystemMirror > GlobalSystemVectorL
Global left-vectors.
typedef Global::Vector< LocalSystemVectorR, SystemMirror > GlobalSystemVectorR
Global right-vectors.
typedef IT_ IndexType
Index type for the solver.
typedef BaseClass::LocalCoordsBuffer LocalCoordsBuffer
Local coordinates buffer type for passing information to or from the mesh.
typedef LocalFunctional::DirichletFilterSequence LocalDirichletFilterSequence
... and a sequence of UnitFilters
typedef Functional_< DT_, IT_ > LocalFunctional
(Patch-) Local mesh quality functional type
typedef LocalFunctional::MatrixType LocalMatrix
The local system matrix type (for the gradient)
typedef BaseClass::LocalScalarVector LocalScalarVector
Local vectors of scalar quantities.
typedef LocalFunctional::SlipFilterSequence LocalSlipFilterSequence
This is comprised of a sequence of SlipFilters...
typedef LocalFunctional::FilterType LocalSystemFilter
Filter for the local system.
typedef LAFEM::Transfer< LocalSystemTransferMatrix > LocalSystemTransfer
Local transfer operator.
typedef LAFEM::SparseMatrixBWrappedCSR< DT_, IT_, LocalFunctional::MeshType::world_dim > LocalSystemTransferMatrix
Local inter-level transfer matrix.
typedef BaseClass::LocalSystemVectorL LocalSystemVectorL
Local left-vectors (dual space)
typedef BaseClass::LocalSystemVectorR LocalSystemVectorR
Local right-vectors (primal space)
typedef TrafoType::MeshType MeshType
The type of mesh we use.
typedef Global::Gate< LocalScalarVector, ScalarMirror > ScalarGate
Gates for scalar vectors.
typedef LAFEM::VectorMirror< DT_, IT_ > ScalarMirror
Mirrors for scalar vectors.
typedef LocalFunctional::SpaceType SpaceType
The finite element space.
typedef BaseClass::SystemGate SystemGate
Gates for the system.
typedef BaseClass::SystemMirror SystemMirror
Mirrors for system vectors.
typedef LocalFunctional::TrafoType TrafoType
The underlying transformation.
Public Member Functions
template<typename... Args_>
QuadraticSystemLevel (const int level_index, Geometry::RootMeshNode< MeshType > *rmn, TrafoType &trafo, const std::deque< String > &dirichlet_list, const std::deque< String > &slip_list, Args_ &&... args)
Variadic template constructor.
virtual ~QuadraticSystemLevel ()
Empty virtual destructor.
template<typename DomainLayer_ >
void assemble_gates (const DomainLayer_ &dom_layer)
Assembles the gates on this level on a given DomainLayer.
GlobalSystemVectorL assemble_rhs_vector () const
Assembles a right hand side vector.
GlobalSystemVectorR assemble_sol_vector () const
Assembles an intial guess vector.
void assemble_system_transfer (const MeshoptSystemLevel &level_coarse)
Assembles the transfer operators from this level to a coarser one.
GlobalSystemVectorL create_vector_l () const
Creates a new (left) vector.
GlobalSystemVectorR create_vector_r () const
Creates a new (right) vector.
bool empty () const
Returns if the local functional is empty.
int get_level_index () const
Returns the level index.
void sync_system_filter ()
Synchronizes the system filters.
Public Attributes
GlobalSystemMuxer coarse_muxer_sys
The global partition muxer on this level.
GlobalCoordsBuffer coords_buffer
This contains a shallow copy of the operator's coords_buffer.
GlobalSystemFilter filter_sys
The global filter.
ScalarGate gate_scalar
The scalar gate.
SystemGate gate_sys
The system gate.
LocalFunctional local_functional
The (patch-)local mesh quality functional.
GlobalSystemMatrix matrix_sys
The global system matrix.
GlobalSystemTransfer transfer_sys
The global transfer operator from this level to the next coarser one.
Private Attributes
const int _level_index
This is the number of refines it took from the mesh at the file level to here.
Detailed Description
template<typename DT_, typename IT_, template< typename, typename > class Functional_>
class FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >
SystemLevel for a quadratic mesh quality functional leading to a linear system.
Template Parameters
DT_ Floating point type
IT_ Index type
Functional_ The (patch-) local quadratic mesh quality functional
Since the mesh quality functional is quadratic, it can be minimized by solving the the linear system of equations given by its gradient, represented by the GlobalSystemMatrix.
Definition at line 748 of file meshopt_control.hpp.
Member Typedef Documentation
BaseClass
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef MeshoptSystemLevel<DT_, IT_, Functional_> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::BaseClass
Our base class.
Definition at line 757 of file meshopt_control.hpp.
DataType
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef DT_ FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::DataType
Floating point precision for the solver.
Definition at line 752 of file meshopt_control.hpp.
GlobalCoordsBuffer
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Vector<LocalCoordsBuffer, SystemMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::GlobalCoordsBuffer
Global coordinates buffer.
Definition at line 812 of file meshopt_control.hpp.
GlobalScalarVector
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Vector<LocalScalarVector, ScalarMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::GlobalScalarVector
Global scalar vector type.
Definition at line 806 of file meshopt_control.hpp.
GlobalSystemFilter
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Filter<LocalSystemFilter, SystemMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::GlobalSystemFilter
Global system filter type.
Definition at line 804 of file meshopt_control.hpp.
GlobalSystemMatrix
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Matrix<LocalMatrix, SystemMirror, SystemMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::GlobalSystemMatrix
Global mesh quality functional type.
Definition at line 802 of file meshopt_control.hpp.
GlobalSystemMuxer
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Muxer<LocalSystemVectorR, SystemMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::GlobalSystemMuxer
The global muxer for mapping data from one partitioning to the other on this level.
Definition at line 816 of file meshopt_control.hpp.
GlobalSystemTransfer
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Transfer<LocalSystemTransfer, SystemMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::GlobalSystemTransfer
Global system transfer operator.
Definition at line 814 of file meshopt_control.hpp.
GlobalSystemVectorL
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Vector<LocalSystemVectorL, SystemMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::GlobalSystemVectorL
Global left-vectors.
Definition at line 808 of file meshopt_control.hpp.
GlobalSystemVectorR
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Vector<LocalSystemVectorR, SystemMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::GlobalSystemVectorR
Global right-vectors.
Definition at line 810 of file meshopt_control.hpp.
IndexType
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef IT_ FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::IndexType
Index type for the solver.
Definition at line 754 of file meshopt_control.hpp.
LocalCoordsBuffer
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef BaseClass::LocalCoordsBuffer FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalCoordsBuffer
Local coordinates buffer type for passing information to or from the mesh.
Definition at line 778 of file meshopt_control.hpp.
LocalDirichletFilterSequence
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LocalFunctional::DirichletFilterSequence FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalDirichletFilterSequence
... and a sequence of UnitFilters
Definition at line 790 of file meshopt_control.hpp.
LocalFunctional
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Functional_<DT_, IT_> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalFunctional
(Patch-) Local mesh quality functional type
Definition at line 760 of file meshopt_control.hpp.
LocalMatrix
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LocalFunctional::MatrixType FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalMatrix
The local system matrix type (for the gradient)
Definition at line 770 of file meshopt_control.hpp.
LocalScalarVector
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef BaseClass::LocalScalarVector FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalScalarVector
Local vectors of scalar quantities.
Definition at line 776 of file meshopt_control.hpp.
LocalSlipFilterSequence
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LocalFunctional::SlipFilterSequence FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalSlipFilterSequence
This is comprised of a sequence of SlipFilters...
Definition at line 788 of file meshopt_control.hpp.
LocalSystemFilter
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LocalFunctional::FilterType FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalSystemFilter
Filter for the local system.
Definition at line 786 of file meshopt_control.hpp.
LocalSystemTransfer
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LAFEM::Transfer<LocalSystemTransferMatrix> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalSystemTransfer
Local transfer operator.
Definition at line 783 of file meshopt_control.hpp.
LocalSystemTransferMatrix
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LAFEM::SparseMatrixBWrappedCSR<DT_, IT_, LocalFunctional::MeshType::world_dim> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalSystemTransferMatrix
Local inter-level transfer matrix.
Definition at line 781 of file meshopt_control.hpp.
LocalSystemVectorL
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef BaseClass::LocalSystemVectorL FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalSystemVectorL
Local left-vectors (dual space)
Definition at line 772 of file meshopt_control.hpp.
LocalSystemVectorR
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef BaseClass::LocalSystemVectorR FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::LocalSystemVectorR
Local right-vectors (primal space)
Definition at line 774 of file meshopt_control.hpp.
MeshType
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef TrafoType::MeshType FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::MeshType
The type of mesh we use.
Definition at line 767 of file meshopt_control.hpp.
ScalarGate
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef Global::Gate<LocalScalarVector, ScalarMirror> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::ScalarGate
Gates for scalar vectors.
Definition at line 799 of file meshopt_control.hpp.
ScalarMirror
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LAFEM::VectorMirror<DT_, IT_> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::ScalarMirror
Mirrors for scalar vectors.
Definition at line 797 of file meshopt_control.hpp.
SpaceType
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LocalFunctional::SpaceType FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::SpaceType
The finite element space.
Definition at line 763 of file meshopt_control.hpp.
SystemGate
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef BaseClass::SystemGate FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::SystemGate
Gates for the system.
Definition at line 795 of file meshopt_control.hpp.
SystemMirror
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef BaseClass::SystemMirror FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::SystemMirror
Mirrors for system vectors.
Definition at line 793 of file meshopt_control.hpp.
TrafoType
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> typedef LocalFunctional::TrafoType FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::TrafoType
The underlying transformation.
Definition at line 765 of file meshopt_control.hpp.
Constructor & Destructor Documentation
QuadraticSystemLevel()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> template<typename... Args_> FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::QuadraticSystemLevel (const int level_index, Geometry::RootMeshNode< MeshType > * rmn, TrafoType & trafo, const std::deque< String > & dirichlet_list, const std::deque< String > & slip_list, Args_ &&... args) inline explicit
Variadic template constructor.
Template Parameters
Args_ For passing to the constructor of local_functional
Parameters
[in] level_index The refinement level since the mesh was constructed
[in] rmn The root mesh node on this level
[in] trafo The transformation on this level
[in] dirichlet_list List of the names of all Dirichlet boundaries
[in] slip_list List of the names of all slip boundaries
[in] args Additional arguments that get passed to the constructor of local_functional
Definition at line 849 of file meshopt_control.hpp.
~QuadraticSystemLevel()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> virtual FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::~QuadraticSystemLevel () inline virtual
Empty virtual destructor.
Definition at line 864 of file meshopt_control.hpp.
Member Function Documentation
assemble_gates()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> template<typename DomainLayer_ > void FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_gates (const DomainLayer_ & dom_layer) inline inherited
Assembles the gates on this level on a given DomainLayer.
Template Parameters
DomainLayer_ Type for the layer
Parameters
[in] dom_layer The layer to assemble the gates on
Definition at line 630 of file meshopt_control.hpp.
References FEAT::Assembly::MirrorAssembler::assemble_mirror(), FEAT::Global::Gate< LocalVector_, Mirror_ >::compile(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::gate_scalar, FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::gate_sys, FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::local_functional, FEAT::Global::Gate< LocalVector_, Mirror_ >::push(), FEAT::Global::Gate< LocalVector_, Mirror_ >::set_comm(), and XASSERTM.
assemble_rhs_vector()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalSystemVectorL FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_rhs_vector () const inline inherited
Assembles a right hand side vector.
Note that this is always homogeneous and filtered.
Returns
A right hand side vector for the mesh optimization problem on this level.
Definition at line 590 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::create_vector_l(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::empty(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::filter_sys, FEAT::Global::Vector< LocalVector_, Mirror_ >::format(), and XASSERTM.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
assemble_sol_vector()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalSystemVectorR FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_sol_vector () const inline inherited
Assembles an intial guess vector.
Returns
A vector to be passed to an iterative solver as initial guess.
Definition at line 608 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::coords_buffer, FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::create_vector_r(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::empty(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::filter_sys, FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and XASSERTM.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
assemble_system_transfer()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> void FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer (const MeshoptSystemLevel< DT_, IT_, Functional_ > & level_coarse) inline inherited
Assembles the transfer operators from this level to a coarser one.
Parameters
[in] level_coarse Target coarse level for the transfer operators.
Definition at line 676 of file meshopt_control.hpp.
References FEAT::Assembly::SymbolicAssembler::assemble_matrix_2lvl(), FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_l(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::local(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::local_functional, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::transfer_sys, and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
create_vector_l()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalSystemVectorL FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::create_vector_l () const inline inherited
Creates a new (left) vector.
Definition at line 517 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::gate_sys, and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::local_functional.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_rhs_vector().
create_vector_r()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalSystemVectorR FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::create_vector_r () const inline inherited
Creates a new (right) vector.
Definition at line 525 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::gate_sys, and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::local_functional.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_sol_vector().
empty()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> bool FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::empty () const inline inherited
Returns if the local functional is empty.
Returns
True if the local functional is empty
Definition at line 509 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::local_functional.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_rhs_vector(), and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_sol_vector().
get_level_index()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> int FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::get_level_index () const inline inherited
Returns the level index.
The level index is the number of times the underlying mesh was refined since reading its construction.
Returns
This SystemLevel's level index.
Definition at line 499 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::_level_index.
sync_system_filter()
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> void FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::sync_system_filter () inline inherited
Synchronizes the system filters.
If there is a global functional (like Global::Functional<SomeClass>) that handles the synchronization after each call to prepare(), is is not needed. For quadratic functionals, where there is no global functional but only a Global::Matrix, this routine is provided.
Definition at line 538 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::filter_sys, FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::gate_sys, and FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0().
Member Data Documentation
_level_index
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> const int FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::_level_index private inherited
This is the number of refines it took from the mesh at the file level to here.
Definition at line 425 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::get_level_index().
coarse_muxer_sys
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalSystemMuxer FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::coarse_muxer_sys inherited
The global partition muxer on this level.
Definition at line 419 of file meshopt_control.hpp.
coords_buffer
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalCoordsBuffer FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::coords_buffer inherited
This contains a shallow copy of the operator's coords_buffer.
Definition at line 417 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_sol_vector(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize().
filter_sys
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalSystemFilter FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::filter_sys inherited
The global filter.
Definition at line 415 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::MeshoptSystemLevel(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_rhs_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_sol_vector(), and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::sync_system_filter().
gate_scalar
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> ScalarGate FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::gate_scalar inherited
The scalar gate.
Definition at line 411 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_gates().
gate_sys
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> SystemGate FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::gate_sys inherited
The system gate.
Definition at line 413 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_gates(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::create_vector_l(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::create_vector_r(), and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::sync_system_filter().
local_functional
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> LocalFunctional FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::local_functional inherited
The (patch-)local mesh quality functional.
Definition at line 409 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_gates(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::create_vector_l(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::create_vector_r(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::empty(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize().
matrix_sys
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalSystemMatrix FEAT::Control::Meshopt::QuadraticSystemLevel< DT_, IT_, Functional_ >::matrix_sys
The global system matrix.
Definition at line 820 of file meshopt_control.hpp.
transfer_sys
template<typename DT_ , typename IT_ , template< typename, typename > class Functional_> GlobalSystemTransfer FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::transfer_sys inherited
The global transfer operator from this level to the next coarser one.
Definition at line 421 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer().
The documentation for this class was generated from the following file:
control/meshopt/meshopt_control.hpp