FEAT: FEAT::Global::MeanFilter< DT_, IT_ > Class Template Reference
FEAT::Global::MeanFilter< DT_, IT_ > Class Template Reference
Mean Filter class template.
#include <mean_filter.hpp>
Public Types
typedef VectorType::DataType DataType
data-type typedef
template<typename DT2_ , typename IT2_ >
using FilterType = MeanFilter< DT2_, IT2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using FilterTypeByDI = FilterType< DataType2_, IndexType2_ >
this typedef lets you create a filter with new Datatape and Index types
typedef VectorType::IndexType IndexType
index-type typedef
typedef LAFEM::DenseVector< DT_, IT_ > VectorType
vector-type typedef
Public Member Functions
MeanFilter (MeanFilter &&other)
move ctor
MeanFilter (VectorType &&vec_prim, VectorType &&vec_dual, VectorType &&vec_freq, const Dist::Comm *comm)
Constructor.
virtual ~MeanFilter ()
virtual destructor
std::size_t bytes () const
void clone (const MeanFilter &other, LAFEM::CloneMode clone_mode=LAFEM::CloneMode::Deep)
Clones data from another MeanFilter.
MeanFilter clone (LAFEM::CloneMode clone_mode=LAFEM::CloneMode::Deep) const
Creates a clone of itself.
template<typename DT2_ , typename IT2_ >
void convert (const MeanFilter< DT2_, IT2_ > &other)
Conversion method.
bool empty () const
void filter_cor (VectorType &vector) const
Applies the filter onto a correction vector.
void filter_def (VectorType &vector) const
Applies the filter onto a defect vector.
void filter_rhs (VectorType &vector) const
Applies the filter onto the right-hand-side vector.
void filter_sol (VectorType &vector) const
Applies the filter onto the solution vector.
MeanFilter & operator= (MeanFilter &&other)
move-assign operator
Protected Attributes
const Dist::Comm * _comm
communicator
VectorType _vec_dual
dual weighting vector
VectorType _vec_freq
frequency vector
VectorType _vec_prim
primal weighting vector
DataType _volume
weight volume
Detailed Description
template<typename DT_, typename IT_>
class FEAT::Global::MeanFilter< DT_, IT_ >
Mean Filter class template.
Author
Peter Zajac
Definition at line 24 of file mean_filter.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ > typedef VectorType::DataType FEAT::Global::MeanFilter< DT_, IT_ >::DataType
data-type typedef
Definition at line 30 of file mean_filter.hpp.
FilterType
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > using FEAT::Global::MeanFilter< DT_, IT_ >::FilterType = MeanFilter<DT2_, IT2_>
Our 'base' class type.
Definition at line 36 of file mean_filter.hpp.
FilterTypeByDI
template<typename DT_ , typename IT_ > template<typename DataType2_ , typename IndexType2_ > using FEAT::Global::MeanFilter< DT_, IT_ >::FilterTypeByDI = FilterType<DataType2_, IndexType2_>
this typedef lets you create a filter with new Datatape and Index types
Definition at line 40 of file mean_filter.hpp.
IndexType
template<typename DT_ , typename IT_ > typedef VectorType::IndexType FEAT::Global::MeanFilter< DT_, IT_ >::IndexType
index-type typedef
Definition at line 32 of file mean_filter.hpp.
VectorType
template<typename DT_ , typename IT_ > typedef LAFEM::DenseVector<DT_, IT_> FEAT::Global::MeanFilter< DT_, IT_ >::VectorType
vector-type typedef
Definition at line 28 of file mean_filter.hpp.
Constructor & Destructor Documentation
MeanFilter() [1/3]
template<typename DT_ , typename IT_ > FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter () inline
Definition at line 56 of file mean_filter.hpp.
MeanFilter() [2/3]
template<typename DT_ , typename IT_ > FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter (VectorType && vec_prim, VectorType && vec_dual, VectorType && vec_freq, const Dist::Comm * comm) inline explicit
Constructor.
Parameters
[in] vec_prim,vec_dual The primal-dual weighting vector pair for the mean filter.
[in] vec_freq The frequency vector for the dot-product.
Definition at line 74 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::_comm, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_freq, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::Global::MeanFilter< DT_, IT_ >::_volume, FEAT::Dist::Comm::allreduce(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::Dist::op_sum, and FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot().
MeanFilter() [3/3]
template<typename DT_ , typename IT_ > FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter (MeanFilter< DT_, IT_ > && other) inline
move ctor
Definition at line 93 of file mean_filter.hpp.
~MeanFilter()
template<typename DT_ , typename IT_ > virtual FEAT::Global::MeanFilter< DT_, IT_ >::~MeanFilter () inline virtual
virtual destructor
Definition at line 117 of file mean_filter.hpp.
Member Function Documentation
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::Global::MeanFilter< DT_, IT_ >::bytes () const inline
Definition at line 202 of file mean_filter.hpp.
clone() [1/2]
template<typename DT_ , typename IT_ > void FEAT::Global::MeanFilter< DT_, IT_ >::clone (const MeanFilter< DT_, IT_ > & other, LAFEM::CloneMode clone_mode = LAFEM::CloneMode::Deep) inline
Clones data from another MeanFilter.
Warning
_volume will always be a deep copy
Definition at line 134 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::_comm, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_freq, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::Global::MeanFilter< DT_, IT_ >::_volume, and FEAT::LAFEM::DenseVector< DT_, IT_ >::clone().
clone() [2/2]
template<typename DT_ , typename IT_ > MeanFilter FEAT::Global::MeanFilter< DT_, IT_ >::clone (LAFEM::CloneMode clone_mode = LAFEM::CloneMode::Deep) const inline
Creates a clone of itself.
Warning
_volume will always be a deep copy
Definition at line 125 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::_comm, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_freq, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_prim, and FEAT::LAFEM::DenseVector< DT_, IT_ >::clone().
convert()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::Global::MeanFilter< DT_, IT_ >::convert (const MeanFilter< DT2_, IT2_ > & other) inline
Conversion method.
Definition at line 148 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::_comm, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_freq, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::Global::MeanFilter< DT_, IT_ >::_volume, and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
empty()
template<typename DT_ , typename IT_ > bool FEAT::Global::MeanFilter< DT_, IT_ >::empty () const inline
Definition at line 207 of file mean_filter.hpp.
filter_cor()
template<typename DT_ , typename IT_ > void FEAT::Global::MeanFilter< DT_, IT_ >::filter_cor (VectorType & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 277 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol().
filter_def()
template<typename DT_ , typename IT_ > void FEAT::Global::MeanFilter< DT_, IT_ >::filter_def (VectorType & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 265 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs().
filter_rhs()
template<typename DT_ , typename IT_ > void FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs (VectorType & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 218 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::_comm, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_freq, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::Global::MeanFilter< DT_, IT_ >::_volume, FEAT::Dist::Comm::allreduce(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::Dist::op_sum, and FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot().
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::filter_def().
filter_sol()
template<typename DT_ , typename IT_ > void FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol (VectorType & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 242 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::_comm, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_freq, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::Global::MeanFilter< DT_, IT_ >::_volume, FEAT::Dist::Comm::allreduce(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::Dist::op_sum, and FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot().
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::filter_cor().
operator=()
template<typename DT_ , typename IT_ > MeanFilter & FEAT::Global::MeanFilter< DT_, IT_ >::operator= (MeanFilter< DT_, IT_ > && other) inline
move-assign operator
Definition at line 103 of file mean_filter.hpp.
References FEAT::Global::MeanFilter< DT_, IT_ >::_comm, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_freq, FEAT::Global::MeanFilter< DT_, IT_ >::_vec_prim, and FEAT::Global::MeanFilter< DT_, IT_ >::_volume.
Member Data Documentation
_comm
template<typename DT_ , typename IT_ > const Dist::Comm* FEAT::Global::MeanFilter< DT_, IT_ >::_comm protected
communicator
Definition at line 44 of file mean_filter.hpp.
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::clone(), FEAT::Global::MeanFilter< DT_, IT_ >::convert(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Global::MeanFilter< DT_, IT_ >::operator=().
_vec_dual
template<typename DT_ , typename IT_ > VectorType FEAT::Global::MeanFilter< DT_, IT_ >::_vec_dual protected
dual weighting vector
Definition at line 48 of file mean_filter.hpp.
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::clone(), FEAT::Global::MeanFilter< DT_, IT_ >::convert(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Global::MeanFilter< DT_, IT_ >::operator=().
_vec_freq
template<typename DT_ , typename IT_ > VectorType FEAT::Global::MeanFilter< DT_, IT_ >::_vec_freq protected
frequency vector
Definition at line 50 of file mean_filter.hpp.
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::clone(), FEAT::Global::MeanFilter< DT_, IT_ >::convert(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Global::MeanFilter< DT_, IT_ >::operator=().
_vec_prim
template<typename DT_ , typename IT_ > VectorType FEAT::Global::MeanFilter< DT_, IT_ >::_vec_prim protected
primal weighting vector
Definition at line 46 of file mean_filter.hpp.
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::clone(), FEAT::Global::MeanFilter< DT_, IT_ >::convert(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Global::MeanFilter< DT_, IT_ >::operator=().
_volume
template<typename DT_ , typename IT_ > DataType FEAT::Global::MeanFilter< DT_, IT_ >::_volume protected
weight volume
Definition at line 52 of file mean_filter.hpp.
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::clone(), FEAT::Global::MeanFilter< DT_, IT_ >::convert(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Global::MeanFilter< DT_, IT_ >::operator=().
The documentation for this class was generated from the following file:
kernel/global/mean_filter.hpp