FEAT: FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ > Class Template Reference
FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ > Class Template Reference
Discrete evaluation data for matrix-valued functions.
#include <discrete_evaluator.hpp>
Public Types
typedef DT_ DataType
the data type
typedef Tiny::Matrix< DT_, dim_i_, dim_j_ > ValueType
the value type
Public Member Functions
bool empty () const
Checks whether the evaluation data is empty.
ValueType mean_value () const
Computes the mean function value.
ValueType mean_value_dist (const Dist::Comm &comm) const
Computes the mean function value on a distributed domain.
Public Attributes
std::vector< ValueType > values
the vector of values
Static Public Attributes
static constexpr int dim_i = dim_i_
the image dimension
static constexpr int dim_j = dim_j_
Detailed Description
template<typename DT_, int dim_i_, int dim_j_>
class FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >
Discrete evaluation data for matrix-valued functions.
Template Parameters
DT_ The datatype that is to be used.
dim_ The dimension of the underlying mesh.
Author
Maximilian Esser
Definition at line 220 of file discrete_evaluator.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , int dim_i_, int dim_j_> typedef DT_ FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::DataType
the data type
Definition at line 227 of file discrete_evaluator.hpp.
ValueType
template<typename DT_ , int dim_i_, int dim_j_> typedef Tiny::Matrix<DT_, dim_i_, dim_j_> FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::ValueType
the value type
Definition at line 229 of file discrete_evaluator.hpp.
Member Function Documentation
empty()
template<typename DT_ , int dim_i_, int dim_j_> bool FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::empty () const inline
Checks whether the evaluation data is empty.
Definition at line 237 of file discrete_evaluator.hpp.
References FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::values.
mean_value()
template<typename DT_ , int dim_i_, int dim_j_> ValueType FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::mean_value () const inline
Computes the mean function value.
Attention
This function does not work on distributed domains!
Use the mean_value_dist() function in this case instead!
Returns
The mean function value.
Definition at line 252 of file discrete_evaluator.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), and FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::values.
mean_value_dist()
template<typename DT_ , int dim_i_, int dim_j_> ValueType FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::mean_value_dist (const Dist::Comm & comm) const inline
Computes the mean function value on a distributed domain.
Parameters
[in] comm The communicator that the domain was distributed on.
Returns
The mean function value.
Definition at line 275 of file discrete_evaluator.hpp.
References FEAT::Dist::Comm::allreduce(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::Dist::op_sum, and FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::values.
Member Data Documentation
dim_i
template<typename DT_ , int dim_i_, int dim_j_> constexpr int FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::dim_i = dim_i_ static constexpr
the image dimension
Definition at line 224 of file discrete_evaluator.hpp.
dim_j
template<typename DT_ , int dim_i_, int dim_j_> constexpr int FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::dim_j = dim_j_ static constexpr
Definition at line 225 of file discrete_evaluator.hpp.
values
template<typename DT_ , int dim_i_, int dim_j_> std::vector<ValueType> FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::values
the vector of values
Definition at line 232 of file discrete_evaluator.hpp.
Referenced by FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::empty(), FEAT::Assembly::DiscreteEvaluator::eval_fe_gradient_function(), FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::mean_value(), and FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::mean_value_dist().
The documentation for this class was generated from the following file:
kernel/assembly/discrete_evaluator.hpp