FEAT: FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ > Class Template Reference
FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ > Class Template Reference
Finite-Element Parametric Evaluator CRTP base-class template.
#include <parametric_evaluator.hpp>
Classes
struct ConfigTraits
Space configuration traits class template.
Public Types
typedef EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ > BaseClass
base class typedef
typedef SpaceEvalTraits_ SpaceEvalTraits
space evaluator traits
typedef SpaceEvaluator_ SpaceEvaluator
space evaluator type
typedef TrafoEvaluator::EvalTraits TrafoEvalTraits
trafo evaluator traits
typedef TrafoEvaluator_ TrafoEvaluator
trafo evaluator type
Public Member Functions
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_gradients (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function gradients on the real cell.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_hessians (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function hessians on the real cell.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_values (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function values on the real cell.
void finish ()
Releases the evaluator from the current cell.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void operator() (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Space evaluation operator.
void prepare (const TrafoEvaluator &trafo_eval)
Prepares the evaluator for a given cell.
template<SpaceTags space_cfg_>
void reference_eval (EvalData< SpaceEvalTraits, space_cfg_ > &space_ref_data, const typename SpaceEvalTraits::DomainPointType &dom_point) const
Space reference evaluation function.
Static Public Attributes
static constexpr int domain_dim = SpaceEvalTraits::domain_dim
domain dimension
static constexpr SpaceTags eval_caps
our evaluation capabilities
static constexpr int image_dim = SpaceEvalTraits::image_dim
image dimension
static constexpr int max_local_dofs = SpaceEvalTraits::max_local_dofs
maximum number of local dofs
static constexpr TrafoTags trafo_caps = TrafoEvaluator::eval_caps
the capabilities of the trafo evaluator
Detailed Description
template<typename SpaceEvaluator_, typename TrafoEvaluator_, typename SpaceEvalTraits_, SpaceTags ref_caps_>
class FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >
Finite-Element Parametric Evaluator CRTP base-class template.
This class is a CRTP base-class for parametric Finite-Element space evaluators.
Template Parameters
SpaceEvaluator_ The space evaluator class which derives from this class template.
TrafoEvaluator_ The trafo evaluator class to be used by the space evaluator.
SpaceEvalTraits_ The space evaluator traits of the space evaluator.
ref_caps_ A tag class containing the capabilities of the space evaluator for reference value computation.
Author
Peter Zajac
Definition at line 49 of file parametric_evaluator.hpp.
Member Typedef Documentation
BaseClass
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> typedef EvaluatorBase<SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_> FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::BaseClass
base class typedef
Definition at line 54 of file parametric_evaluator.hpp.
SpaceEvalTraits
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> typedef SpaceEvalTraits_ FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::SpaceEvalTraits
space evaluator traits
Definition at line 63 of file parametric_evaluator.hpp.
SpaceEvaluator
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> typedef SpaceEvaluator_ FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::SpaceEvaluator
space evaluator type
Definition at line 57 of file parametric_evaluator.hpp.
TrafoEvalTraits
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> typedef TrafoEvaluator::EvalTraits FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::TrafoEvalTraits
trafo evaluator traits
Definition at line 66 of file parametric_evaluator.hpp.
TrafoEvaluator
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> typedef TrafoEvaluator_ FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::TrafoEvaluator
trafo evaluator type
Definition at line 60 of file parametric_evaluator.hpp.
Member Function Documentation
eval_gradients()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_gradients (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline inherited
Evaluates the basis function gradients on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function gradients.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 195 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
eval_hessians()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_hessians (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline inherited
Evaluates the basis function hessians on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function hessian matrices.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 215 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
eval_values()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_values (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline inherited
Evaluates the basis function values on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function values.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 175 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
finish()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::finish () inline inherited
Releases the evaluator from the current cell.
Definition at line 115 of file evaluator_base.hpp.
operator()()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::operator() (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline
Space evaluation operator.
This operator evaluates the basis functions in a point on a mesh cell.
Parameters
[out] space_data A transient reference to the space data that is to be computed.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 167 of file parametric_evaluator.hpp.
References FEAT::Trafo::EvalData< EvalTraits_, cfg_tags_ >::dom_point, FEAT::grad, FEAT::hess, and FEAT::value.
prepare()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::prepare (const TrafoEvaluator & trafo_eval) inline inherited
Prepares the evaluator for a given cell.
Parameters
[in] trafo_eval A transient reference to the trafo evaluator containing the cell information.
Definition at line 108 of file evaluator_base.hpp.
reference_eval()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> template<SpaceTags space_cfg_> void FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::reference_eval (EvalData< SpaceEvalTraits, space_cfg_ > & space_ref_data, const typename SpaceEvalTraits::DomainPointType & dom_point) const inline
Space reference evaluation function.
This function evaluates the basis functions in a point on the reference cell.
Parameters
[out] space_ref_data A transient reference to the space reference data that is to be computed.
[in] dom_point A transient reference to the domain point in which the evaluation shall take place.
Definition at line 153 of file parametric_evaluator.hpp.
References FEAT::dom_point, FEAT::ref_grad, FEAT::ref_hess, and FEAT::ref_value.
Member Data Documentation
domain_dim
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> constexpr int FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::domain_dim = SpaceEvalTraits::domain_dim static constexpr
domain dimension
Definition at line 92 of file parametric_evaluator.hpp.
eval_caps
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> constexpr SpaceTags FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::eval_caps static constexpr
Initial value:
=
        (ref_caps_ & (SpaceTags::ref_value | SpaceTags::ref_grad | SpaceTags::ref_hess)) |
        ((*(ref_caps_ & SpaceTags::ref_value) && *(trafo_caps & TrafoTags::dom_point)) ?
          SpaceTags::value : SpaceTags::none) |
        ((*(ref_caps_ & SpaceTags::ref_grad) && *(trafo_caps & (TrafoTags::dom_point | TrafoTags::jac_inv))) ?
          SpaceTags::grad : SpaceTags::none) |
        ((*(ref_caps_ & SpaceTags::ref_hess) && *(trafo_caps & (TrafoTags::dom_point | TrafoTags::jac_inv | TrafoTags::hess_inv))) ?
          SpaceTags::hess : SpaceTags::none)
our evaluation capabilities
Definition at line 72 of file parametric_evaluator.hpp.
image_dim
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> constexpr int FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::image_dim = SpaceEvalTraits::image_dim static constexpr
image dimension
Definition at line 94 of file parametric_evaluator.hpp.
max_local_dofs
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> constexpr int FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::max_local_dofs = SpaceEvalTraits::max_local_dofs static constexpr
maximum number of local dofs
Definition at line 96 of file parametric_evaluator.hpp.
trafo_caps
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ , SpaceTags ref_caps_> constexpr TrafoTags FEAT::Space::ParametricEvaluator< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::trafo_caps = TrafoEvaluator::eval_caps static constexpr
the capabilities of the trafo evaluator
Definition at line 69 of file parametric_evaluator.hpp.
The documentation for this class was generated from the following file:
kernel/space/parametric_evaluator.hpp