FEAT: FEAT::Dist::Status Class Reference
FEAT::Dist::Status Class Reference
Communication Status class.
#include <dist.hpp>
Public Member Functions
Status ()
standard constructor
Status (const Status &)=default
status objects are copyable
int error () const
std::size_t get_count (const Datatype &datatype) const
Returns the size of the message.
std::size_t get_size () const
bool is_null () const
Checks whether the source rank is MPI_PROC_NULL.
MPI_Status * mpi_status ()
Status & operator= (const Status &)=default
status objects are copyable
int source () const
int tag () const
Public Attributes
MPI_Status status
the MPI status structure
Detailed Description
Communication Status class.
This class effectively wraps around the MPI_Status structure.
Attention
This class is assumed to be a POD container for MPI_Status, i.e. you must not add any other member variables or virtual functions to this class!
Author
Peter Zajac
Definition at line 296 of file dist.hpp.
Constructor & Destructor Documentation
Status()
FEAT::Dist::Status::Status () inline
standard constructor
Definition at line 304 of file dist.hpp.
References status.
Member Function Documentation
error()
int FEAT::Dist::Status::error () const inline
Returns
The communication error status, as stored in status.MPI_ERROR
Definition at line 350 of file dist.hpp.
References status.
get_count()
std::size_t FEAT::Dist::Status::get_count (const Datatype & datatype) const inline
Returns the size of the message.
This function effectively wraps around MPI_Get_count().
Parameters
[in] datatype The datatype that the message is encoded in.
Returns
The size of the message in instances of the corresponding datatype.
Definition at line 366 of file dist.hpp.
References FEAT::Dist::Datatype::dt, and status.
get_size()
std::size_t FEAT::Dist::Status::get_size () const inline
Returns
The size of the message in bytes.
Definition at line 374 of file dist.hpp.
References status.
is_null()
bool FEAT::Dist::Status::is_null () const inline
Checks whether the source rank is MPI_PROC_NULL.
Returns
true, if the source rank is MPI_PROC_NULL, otherwise false.
Definition at line 326 of file dist.hpp.
References status.
mpi_status()
MPI_Status * FEAT::Dist::Status::mpi_status () inline
Returns
A pointer to the internal MPI_Status object.
Definition at line 316 of file dist.hpp.
References status.
Referenced by FEAT::Dist::Comm::recv(), FEAT::Dist::Request::test(), FEAT::Dist::RequestVector::test_any(), FEAT::Dist::Request::wait(), and FEAT::Dist::RequestVector::wait_any().
source()
int FEAT::Dist::Status::source () const inline
Returns
The source rank, as stored in status.MPI_SOURCE
Definition at line 334 of file dist.hpp.
References status.
tag()
int FEAT::Dist::Status::tag () const inline
Returns
The communication tag, as stored in status.MPI_TAG
Definition at line 342 of file dist.hpp.
References status.
Member Data Documentation
status
MPI_Status FEAT::Dist::Status::status
the MPI status structure
Definition at line 301 of file dist.hpp.
Referenced by Status(), error(), get_count(), get_size(), is_null(), mpi_status(), source(), and tag().
The documentation for this class was generated from the following file:
kernel/util/dist.hpp