FEAT: FEAT::LAFEM::TupleMatrixRow< First_, Rest_ > Class Template Reference
FEAT::LAFEM::TupleMatrixRow< First_, Rest_ > Class Template Reference
TupleMatrix row helper class template.
#include <tuple_matrix.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = TupleMatrixRow< typename First_::template ContainerType< DT2_, IT2_ >, typename Rest_::template ContainerType< DT2_, IT2_ >... >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a vector container with new Datatype and Index types
typedef First_::DataType DataType
sub-matrix data-type
typedef First_::IndexType IndexType
sub-matrix index-type
typedef First_::VectorTypeL VectorTypeL
Compatible L-vector type.
typedef TupleVector< typename First_::VectorTypeR, typename Rest_::VectorTypeR... > VectorTypeR
Compatible R-vector type.
Public Member Functions
TupleMatrixRow ()
default CTOR
TupleMatrixRow (const TupleMatrixRow &)=delete
deleted copy-ctor
TupleMatrixRow (First_ &&the_first, Rest_ &&... the_rest)
Sub-Matrix emplacement constructor.
TupleMatrixRow (First_ &&the_first, RestClass &&the_rest)
rest-class emplacement ctor; for internal use only
TupleMatrixRow (TupleMatrixRow &&other)
move ctor
void apply (VectorTypeL &r, const VectorTypeR &x) const
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, DataType alpha=DataType(1)) const
template<int i_>
TupleElement< i_, First_, Rest_... >::Type & at ()
Returns a sub-matrix block.
template<int i_>
TupleElement< i_, First_, Rest_... >::Type const & at () const
Returns a sub-matrix block.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
void clone (const TupleMatrixRow &other)
Turns this matrix into a clone of other.
void clone (const TupleMatrixRow &other, CloneMode clone_mode)
Turns this matrix into a clone of other.
TupleMatrixRow clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a copy of this matrix.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Returns the total number of columns in this matrix.
template<typename OtherFirst_ , typename... OtherRest_>
void convert (const TupleMatrixRow< OtherFirst_, OtherRest_... > &other)
template<typename OtherFirst_ , typename... OtherRest_>
void convert_reverse (TupleMatrixRow< OtherFirst_, OtherRest_... > &other) const
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DataType min, DataType max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
Index get_length_of_line (const Index row) const
TupleMatrixRow & operator= (const TupleMatrixRow &)=delete
deleted copy-assign operator
TupleMatrixRow & operator= (TupleMatrixRow &&other)
move-assign operator
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Returns the total number of rows in this matrix.
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
void set_line (const Index row, DataType *const pval_set, IndexType *const pcol_set, const Index col_start, const Index stride=1) const
void set_line_reverse (const Index row, DataType *const pval_set, const Index stride=1)
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Returns the total number of non-zeros in this matrix.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr int num_blocks = TupleMatrixRow<Rest_...>::num_blocks + 1
number of matrix columns
Static Protected Member Functions
static String sub_name_list ()
Returns a list of all sub-matrix type names.
Protected Attributes
First_ _first
the first sub-matrix
RestClass _rest
all remaining sub-matrices
Private Types
typedef TupleMatrixRow< Rest_... > RestClass
Detailed Description
template<typename First_, typename... Rest_>
class FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >
TupleMatrix row helper class template.
This class template is a helper class for the TupleMatrix class template, which is responsible for the management of a single "meta-row" of the outer tuple matrix.
Note
The implementation of this class is quite similar to that of TupleVector.
Template Parameters
First_,...Rest_ A sequence of (meta) matrix classes which are to be composed.
Author
Peter Zajac
Definition at line 33 of file tuple_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename First_ , typename... Rest_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::ContainerType = TupleMatrixRow< typename First_::template ContainerType<DT2_, IT2_>, typename Rest_::template ContainerType<DT2_, IT2_>...>
Our 'base' class type.
Definition at line 58 of file tuple_matrix.hpp.
ContainerTypeByDI
template<typename First_ , typename... Rest_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a vector container with new Datatype and Index types
Definition at line 64 of file tuple_matrix.hpp.
DataType
template<typename First_ , typename... Rest_> typedef First_::DataType FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::DataType
sub-matrix data-type
Definition at line 46 of file tuple_matrix.hpp.
IndexType
template<typename First_ , typename... Rest_> typedef First_::IndexType FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::IndexType
sub-matrix index-type
Definition at line 48 of file tuple_matrix.hpp.
RestClass
template<typename First_ , typename... Rest_> typedef TupleMatrixRow<Rest_...> FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::RestClass private
Definition at line 39 of file tuple_matrix.hpp.
VectorTypeL
template<typename First_ , typename... Rest_> typedef First_::VectorTypeL FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::VectorTypeL
Compatible L-vector type.
Definition at line 67 of file tuple_matrix.hpp.
VectorTypeR
template<typename First_ , typename... Rest_> typedef TupleVector<typename First_::VectorTypeR, typename Rest_::VectorTypeR...> FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::VectorTypeR
Compatible R-vector type.
Definition at line 69 of file tuple_matrix.hpp.
Constructor & Destructor Documentation
TupleMatrixRow() [1/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::TupleMatrixRow () inline
default CTOR
Definition at line 85 of file tuple_matrix.hpp.
TupleMatrixRow() [2/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::TupleMatrixRow (First_ && the_first, RestClass && the_rest) inline explicit
rest-class emplacement ctor; for internal use only
Definition at line 90 of file tuple_matrix.hpp.
TupleMatrixRow() [3/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::TupleMatrixRow (First_ && the_first, Rest_ &&... the_rest) inline explicit
Sub-Matrix emplacement constructor.
Definition at line 97 of file tuple_matrix.hpp.
TupleMatrixRow() [4/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::TupleMatrixRow (TupleMatrixRow< First_, Rest_ > && other) inline
move ctor
Definition at line 104 of file tuple_matrix.hpp.
Member Function Documentation
apply() [1/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Definition at line 305 of file tuple_matrix.hpp.
apply() [2/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, DataType alpha = DataType(1)) const inline
Definition at line 311 of file tuple_matrix.hpp.
at() [1/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type & FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::at () inline
Returns a sub-matrix block.
Template Parameters
i_ The index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position i_.
Definition at line 192 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::num_blocks.
at() [2/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type const & FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::at () const inline
Returns a sub-matrix block.
Template Parameters
i_ The index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position i_.
Definition at line 200 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::num_blocks.
bytes()
template<typename First_ , typename... Rest_> std::size_t FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::bytes () const inline
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 250 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::bytes().
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::bytes().
clear()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clear () inline
Free all allocated arrays.
Definition at line 287 of file tuple_matrix.hpp.
clone() [1/3]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone (const TupleMatrixRow< First_, Rest_ > & other) inline
Turns this matrix into a clone of other.
As the default CloneMode of the underlying containers is unknown, this has to be separate.
Definition at line 154 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone().
clone() [2/3]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone (const TupleMatrixRow< First_, Rest_ > & other, CloneMode clone_mode) inline
Turns this matrix into a clone of other.
Parameters
[in] clone_mode Determines the type of clone returned (shallow, weak, layout, deep)
Definition at line 143 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone().
clone() [3/3]
template<typename First_ , typename... Rest_> TupleMatrixRow FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a copy of this matrix.
Parameters
[in] mode Determines the type of clone returned (shallow, weak, layout, deep)
Definition at line 132 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone().
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone().
columns()
template<typename First_ , typename... Rest_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::columns () const inline
Returns the total number of columns in this matrix.
Returns
Matrix column count if perspective_ = false.
Raw matrix column count if perspective_ = true.
Definition at line 228 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest.
convert()
template<typename First_ , typename... Rest_> template<typename OtherFirst_ , typename... OtherRest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::convert (const TupleMatrixRow< OtherFirst_, OtherRest_... > & other) inline
Definition at line 373 of file tuple_matrix.hpp.
convert_reverse()
template<typename First_ , typename... Rest_> template<typename OtherFirst_ , typename... OtherRest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::convert_reverse (TupleMatrixRow< OtherFirst_, OtherRest_... > & other) const inline
Definition at line 380 of file tuple_matrix.hpp.
create_vector_l()
template<typename First_ , typename... Rest_> VectorTypeL FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 294 of file tuple_matrix.hpp.
create_vector_r()
template<typename First_ , typename... Rest_> VectorTypeR FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 300 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::create_vector_r().
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::create_vector_r().
format() [1/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the matrix's entries are to be set to.
Definition at line 267 of file tuple_matrix.hpp.
References FEAT::value.
format() [2/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::format (Random & rng, DataType min, DataType max) inline
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 280 of file tuple_matrix.hpp.
get_checkpoint_size()
template<typename First_ , typename... Rest_> std::uint64_t FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 339 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::get_checkpoint_size().
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::get_checkpoint_size().
get_length_of_line()
template<typename First_ , typename... Rest_> Index FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::get_length_of_line (const Index row) const inline
Definition at line 317 of file tuple_matrix.hpp.
name()
template<typename First_ , typename... Rest_> static String FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 256 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::sub_name_list().
operator=()
template<typename First_ , typename... Rest_> TupleMatrixRow & FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::operator= (TupleMatrixRow< First_, Rest_ > && other) inline
move-assign operator
Definition at line 111 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest.
restore_from_checkpoint_data()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 345 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::restore_from_checkpoint_data().
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::restore_from_checkpoint_data().
rows()
template<typename First_ , typename... Rest_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::rows () const inline
Returns the total number of rows in this matrix.
Returns
Matrix row count if perspective_ = false.
Raw matrix row count if perspective_ = true.
Definition at line 213 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest, and XASSERTM.
set_checkpoint_data()
template<typename First_ , typename... Rest_> std::uint64_t FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 358 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::set_checkpoint_data().
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::set_checkpoint_data().
set_line()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::set_line (const Index row, DataType *const pval_set, IndexType *const pcol_set, const Index col_start, const Index stride = 1) const inline
Definition at line 322 of file tuple_matrix.hpp.
set_line_reverse()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::set_line_reverse (const Index row, DataType *const pval_set, const Index stride = 1) inline
Definition at line 330 of file tuple_matrix.hpp.
sub_name_list()
template<typename First_ , typename... Rest_> static String FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::sub_name_list () inline static protected
Returns a list of all sub-matrix type names.
Definition at line 78 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::sub_name_list().
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::name(), and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::sub_name_list().
used_elements()
template<typename First_ , typename... Rest_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::used_elements () const inline
Returns the total number of non-zeros in this matrix.
Returns
Matrix non zero element count if perspective_ = false.
Raw matrix non zero element count if perspective_ = true.
Definition at line 240 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first, and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest.
Friends And Related Function Documentation
TupleMatrixRow
template<typename First_ , typename... Rest_> template<typename , typename... > friend class TupleMatrixRow friend
Definition at line 37 of file tuple_matrix.hpp.
Member Data Documentation
_first
template<typename First_ , typename... Rest_> First_ FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_first protected
the first sub-matrix
Definition at line 73 of file tuple_matrix.hpp.
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::columns(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::get_checkpoint_size(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::operator=(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::restore_from_checkpoint_data(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::rows(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::set_checkpoint_data(), and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::used_elements().
_rest
template<typename First_ , typename... Rest_> RestClass FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::_rest protected
all remaining sub-matrices
Definition at line 75 of file tuple_matrix.hpp.
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::clone(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::columns(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::get_checkpoint_size(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::operator=(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::restore_from_checkpoint_data(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::rows(), FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::set_checkpoint_data(), and FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::used_elements().
num_blocks
template<typename First_ , typename... Rest_> constexpr int FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::num_blocks = TupleMatrixRow<Rest_...>::num_blocks + 1 static constexpr
number of matrix columns
Definition at line 43 of file tuple_matrix.hpp.
Referenced by FEAT::LAFEM::TupleMatrixRow< First_, Rest_ >::at().
The documentation for this class was generated from the following file:
kernel/lafem/tuple_matrix.hpp