FEAT: FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ > Class Template Reference
FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ > Class Template Reference abstract
Public Types
typedef MatrixType::DataType DataType
typedef Filter_ FilterType
typedef MatrixType::IndexType IndexType
typedef LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > MatrixType
typedef MatrixType::VectorTypeL VectorType
Public Member Functions
SORPrecondWithBackend (const MatrixType &matrix, const FilterType &filter, const DataType omega=DataType(1))
Constructor.
SORPrecondWithBackend (const String &, PropertyMap *section, const MatrixType &matrix, const FilterType &filter)
Constructor using a PropertyMap.
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def)
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def)=0
virtual void done_symbolic () override
virtual void init_symbolic () override
virtual String name () const override
Returns the name of the solver.
virtual void set_omega (DataType omega) override
Sets the damping parameter.
virtual void set_omega (DataType omega)=0
Protected Member Functions
void _apply_intern (const MatrixType &matrix, VectorType &vec_cor, const VectorType &vec_def)
Protected Attributes
const FilterType & _filter
const MatrixType & _matrix
DataType _omega
Detailed Description
template<typename Filter_, typename DT_, typename IT_, int BlockHeight_, int BlockWidth_>
class FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >
Definition at line 228 of file sor_precond.hpp.
Member Typedef Documentation
DataType
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef MatrixType::DataType FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::DataType
Definition at line 236 of file sor_precond.hpp.
FilterType
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef Filter_ FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::FilterType
Definition at line 234 of file sor_precond.hpp.
IndexType
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef MatrixType::IndexType FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::IndexType
Definition at line 237 of file sor_precond.hpp.
MatrixType
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef LAFEM::SparseMatrixBCSR<DT_, IT_, BlockHeight_, BlockWidth_> FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::MatrixType
Definition at line 233 of file sor_precond.hpp.
VectorType
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef MatrixType::VectorTypeL FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::VectorType
Definition at line 235 of file sor_precond.hpp.
Constructor & Destructor Documentation
SORPrecondWithBackend() [1/2]
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::SORPrecondWithBackend (const MatrixType & matrix, const FilterType & filter, const DataType omega = DataType(1)) inline explicit
Constructor.
Parameters
[in] matrix The matrix to be used.
[in] filter The filter to be used for the correction vector.
[in] omega Damping
Definition at line 287 of file sor_precond.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XABORTM.
SORPrecondWithBackend() [2/2]
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::SORPrecondWithBackend (const String & , PropertyMap * section, const MatrixType & matrix, const FilterType & filter) inline explicit
Constructor using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Definition at line 314 of file sor_precond.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::PropertyMap::query(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XABORTM.
Member Function Documentation
_apply_intern()
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::_apply_intern (const MatrixType & matrix, VectorType & vec_cor, const VectorType & vec_def) inline protected
Definition at line 244 of file sor_precond.hpp.
apply()
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> virtual Status FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::apply (VectorType & vec_cor, const VectorType & vec_def) inline virtual
Definition at line 360 of file sor_precond.hpp.
done_symbolic()
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> virtual void FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::done_symbolic () inline override virtual
Implements FEAT::Solver::SORPrecondBase< LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > >.
Definition at line 356 of file sor_precond.hpp.
init_symbolic()
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> virtual void FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::init_symbolic () inline override virtual
Implements FEAT::Solver::SORPrecondBase< LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > >.
Definition at line 352 of file sor_precond.hpp.
name()
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> virtual String FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SORPrecondBase< LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > >.
Definition at line 334 of file sor_precond.hpp.
set_omega()
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> virtual void FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::set_omega (DataType omega) inline override virtual
Sets the damping parameter.
Parameters
[in] omega The new damping parameter.
Definition at line 346 of file sor_precond.hpp.
References XASSERT.
Member Data Documentation
_filter
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> const FilterType& FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::_filter protected
Definition at line 241 of file sor_precond.hpp.
_matrix
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> const MatrixType& FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::_matrix protected
Definition at line 240 of file sor_precond.hpp.
_omega
template<typename Filter_ , typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> DataType FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::_omega protected
Definition at line 242 of file sor_precond.hpp.
The documentation for this class was generated from the following file:
kernel/solver/sor_precond.hpp