FEAT: FEAT::Space::DofMappingRenderer Class Reference
FEAT::Space::DofMappingRenderer Class Reference
Dof-Mapping renderer class.
#include <dof_mapping_renderer.hpp>
Static Public Member Functions
template<typename Space_ >
static Adjacency::Graph render (const Space_ &space)
Renders the dof-mapping of a space into an adjacency graph.
Detailed Description
Dof-Mapping renderer class.
Author
Peter Zajac
Definition at line 22 of file dof_mapping_renderer.hpp.
Member Function Documentation
render()
template<typename Space_ > static Adjacency::Graph FEAT::Space::DofMappingRenderer::render (const Space_ & space) inline static
Renders the dof-mapping of a space into an adjacency graph.
Parameters
[in] space A reference to a finite element space whose dof-mapping is to be rendered.
Returns
The dof-mapping of the space given as an adjacency graph.
Definition at line 35 of file dof_mapping_renderer.hpp.
References FEAT::Adjacency::Graph::get_domain_ptr(), and FEAT::Adjacency::Graph::get_image_idx().
Referenced by FEAT::Assembly::SymbolicAssembler::assemble_graph_2lvl(), FEAT::Assembly::SymbolicAssembler::assemble_graph_ext_facet1(), FEAT::Assembly::SymbolicAssembler::assemble_graph_ext_facet2(), FEAT::Assembly::SymbolicAssembler::assemble_graph_ext_node1(), FEAT::Assembly::SymbolicAssembler::assemble_graph_ext_node2(), FEAT::Assembly::SymbolicAssembler::assemble_graph_std1(), and FEAT::Assembly::SymbolicAssembler::assemble_graph_std2().
The documentation for this class was generated from the following file:
kernel/space/dof_mapping_renderer.hpp