FEAT: FEAT::Geometry::IndexTree< Shape_ > Class Template Reference
FEAT::Geometry::IndexTree< Shape_ > Class Template Reference
Stores the index representatives of an index set.
#include <index_calculator.hpp>
Classes
class IndexVector
Index vector.
Public Member Functions
IndexTree (Index num_vertices)
Constructor.
virtual ~IndexTree ()
Destructor.
Index enumerate ()
Enumerates the index vector representatives.
template<typename IndexVectorType_ >
std::pair< bool, Index > find (const IndexVectorType_ &index_vector) const
Searches for an index vector within the tree.
Index get_index (Index i, Index j, int k) const
returns the value of the k-th component of the j-th index-representative in the i-th set
int get_num_indices () const
returns number of indices of an index-representative
Index get_set_size (Index i) const
returns size of the i-th representative set
template<typename IndexVectorType_ >
void insert (const IndexVectorType_ &index_vector, Index id)
Inserts an index vector's representative into the index tree.
template<typename IndexSet_ >
void parse (const IndexSet_ &index_set)
Parses an index set into the tree.
Static Public Member Functions
static String name ()
Returns the class name.
Static Public Attributes
static constexpr int num_indices = Shape::FaceTraits<Shape_, 0>::count
number of indices per index vector
Private Types
typedef std::set< IndexVector > RepSet
Set of IndexVector representatives.
typedef std::vector< RepSet > RepSetVector
Vector of IV rep sets.
Private Attributes
RepSetVector _rep_set_vec
representative set vector
Detailed Description
template<typename Shape_>
class FEAT::Geometry::IndexTree< Shape_ >
Stores the index representatives of an index set.
Todo:
detailed description
Author
Constantin Christof
Definition at line 32 of file index_calculator.hpp.
Member Typedef Documentation
RepSet
template<typename Shape_ > typedef std::set<IndexVector> FEAT::Geometry::IndexTree< Shape_ >::RepSet private
Set of IndexVector representatives.
Definition at line 87 of file index_calculator.hpp.
RepSetVector
template<typename Shape_ > typedef std::vector<RepSet> FEAT::Geometry::IndexTree< Shape_ >::RepSetVector private
Vector of IV rep sets.
Definition at line 89 of file index_calculator.hpp.
Constructor & Destructor Documentation
IndexTree()
template<typename Shape_ > FEAT::Geometry::IndexTree< Shape_ >::IndexTree (Index num_vertices) inline explicit
Constructor.
Parameters
[in] num_vertices The total number of vertices in the mesh.
Definition at line 101 of file index_calculator.hpp.
~IndexTree()
template<typename Shape_ > virtual FEAT::Geometry::IndexTree< Shape_ >::~IndexTree () inline virtual
Destructor.
Definition at line 107 of file index_calculator.hpp.
Member Function Documentation
enumerate()
template<typename Shape_ > Index FEAT::Geometry::IndexTree< Shape_ >::enumerate () inline
Enumerates the index vector representatives.
This function loops over all index vector representatives in the index tree and assigns an unique id to each representative. The ids are distributed in consecutive order beginning from zero.
Returns
The total number of representatives; coincides with the first unused id.
Definition at line 222 of file index_calculator.hpp.
References FEAT::Geometry::IndexTree< Shape_ >::_rep_set_vec.
Referenced by FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute_vertex_subshape().
find()
template<typename Shape_ > template<typename IndexVectorType_ > std::pair< bool, Index > FEAT::Geometry::IndexTree< Shape_ >::find (const IndexVectorType_ & index_vector) const inline
Searches for an index vector within the tree.
This function searches the index tree for an index vector's representative and, if found, returns its id within the tree.
Parameters
[in] index_vector The index vector whose representative is to be found.
Returns
A bool-Index-pair indicating the result of the search.
If the first (bool) component is true then the second (Index) component contains the id of the index vector within the tree.
If the first (bool) component is false then the index vector's representative was not found within the index tree.
Definition at line 149 of file index_calculator.hpp.
References FEAT::Geometry::IndexTree< Shape_ >::_rep_set_vec.
Referenced by FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute().
get_index()
template<typename Shape_ > Index FEAT::Geometry::IndexTree< Shape_ >::get_index (Index i, Index j, int k) const inline
returns the value of the k-th component of the j-th index-representative in the i-th set
Definition at line 125 of file index_calculator.hpp.
References FEAT::Geometry::IndexTree< Shape_ >::_rep_set_vec.
Referenced by FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute_vertex_subshape().
get_num_indices()
template<typename Shape_ > int FEAT::Geometry::IndexTree< Shape_ >::get_num_indices () const inline
returns number of indices of an index-representative
Definition at line 112 of file index_calculator.hpp.
get_set_size()
template<typename Shape_ > Index FEAT::Geometry::IndexTree< Shape_ >::get_set_size (Index i) const inline
returns size of the i-th representative set
Definition at line 118 of file index_calculator.hpp.
References FEAT::Geometry::IndexTree< Shape_ >::_rep_set_vec, and XASSERT.
Referenced by FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute_vertex_subshape().
insert()
template<typename Shape_ > template<typename IndexVectorType_ > void FEAT::Geometry::IndexTree< Shape_ >::insert (const IndexVectorType_ & index_vector, Index id) inline
Inserts an index vector's representative into the index tree.
Parameters
[in] index_vector The index vector whose representative is to be stored.
[in] id An id that is to be associated with the index vector.
Definition at line 176 of file index_calculator.hpp.
References FEAT::Geometry::IndexTree< Shape_ >::_rep_set_vec, and ASSERTM.
Referenced by FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute_vertex_subshape(), and FEAT::Geometry::IndexTree< Shape_ >::parse().
name()
template<typename Shape_ > static String FEAT::Geometry::IndexTree< Shape_ >::name () inline static
Returns the class name.
Definition at line 246 of file index_calculator.hpp.
parse()
template<typename Shape_ > template<typename IndexSet_ > void FEAT::Geometry::IndexTree< Shape_ >::parse (const IndexSet_ & index_set) inline
Parses an index set into the tree.
Parameters
[in] index_set A transient reference to the index set that is to be parsed.
Definition at line 197 of file index_calculator.hpp.
References FEAT::Geometry::IndexTree< Shape_ >::insert(), and FEAT::Geometry::IndexTree< Shape_ >::num_indices.
Member Data Documentation
_rep_set_vec
template<typename Shape_ > RepSetVector FEAT::Geometry::IndexTree< Shape_ >::_rep_set_vec private
representative set vector
Definition at line 92 of file index_calculator.hpp.
Referenced by FEAT::Geometry::IndexTree< Shape_ >::enumerate(), FEAT::Geometry::IndexTree< Shape_ >::find(), FEAT::Geometry::IndexTree< Shape_ >::get_index(), FEAT::Geometry::IndexTree< Shape_ >::get_set_size(), and FEAT::Geometry::IndexTree< Shape_ >::insert().
num_indices
template<typename Shape_ > constexpr int FEAT::Geometry::IndexTree< Shape_ >::num_indices = Shape::FaceTraits<Shape_, 0>::count static constexpr
number of indices per index vector
Definition at line 36 of file index_calculator.hpp.
Referenced by FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute(), FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute_vertex_subshape(), and FEAT::Geometry::IndexTree< Shape_ >::parse().
The documentation for this class was generated from the following file:
kernel/geometry/index_calculator.hpp