FEAT: FEAT::Global::Splitter< LocalVector_, Mirror_ > Class Template Reference
FEAT::Global::Splitter< LocalVector_, Mirror_ > Class Template Reference
Global base-mesh vector splitter (and joiner) implementation.
#include <splitter.hpp>
Public Types
typedef Global::Vector< LocalVector_, Mirror_ > GlobalVectorType
our global vector type
typedef LocalVector_ LocalVectorType
our local vector type
typedef Global::Muxer< LocalVector_, Mirror_ > MuxerType
our internal muxer type
Public Member Functions
Splitter ()
standard constructor
Splitter (Splitter &&other)
move-constructor
virtual ~Splitter ()
destructor
std::size_t bytes () const
Returns the internal data size in bytes.
void compile (const LocalVector_ &vec_tmp_)
Compiles the muxer.
template<typename LVT2_ >
void convert (const Splitter< LVT2_, Mirror_ > &other, LocalVector_ &&vector, LAFEM::CloneMode mode=LAFEM::CloneMode::Shallow)
Conversion function for different vector container type.
template<typename LVT2_ , typename MT2_ >
void convert (const Splitter< LVT2_, MT2_ > &other)
Conversion function for same vector container type but with different MDI-Type.
LocalVector_ create_base_vector () const
Creates a new base-mesh vector.
bool is_root () const
Checks whether this is the root process.
bool is_single () const
Checks whether there is only one process in the communicator.
LocalVector_ join (const Global::Vector< LocalVector_, Mirror_ > &vector) const
Joins a global vector into a base-mesh local vector on the root process.
void join (LocalVector_ &vec_base, const Global::Vector< LocalVector_, Mirror_ > &vector) const
Joins a global vector into a base-mesh local vector on the root process.
void join_write_out (const Global::Vector< LocalVector_, Mirror_ > &vector, const String &filename, LAFEM::FileMode mode=LAFEM::FileMode::fm_binary)
Joins a global vector into a base-mesh local vector and writes it to a file.
Splitter & operator= (Splitter &&other)
move-assign operator
void push_patch (Mirror_ &&patch_mirror)
Adds a child rank and mirror for the parent process.
void set_base_vector_template (LocalVector_ &&vector_template)
Sets the base-vector template on the root process.
void set_root (const Dist::Comm *comm, int root_rank, Mirror_ &&root_mirror)
Sets the root communicator.
void split (Global::Vector< LocalVector_, Mirror_ > &vector, const LocalVector_ &vec_base) const
Splits a base-mesh local vector on the root process into a global vector.
void split (LocalVector_ &vector, const LocalVector_ &vec_base) const
Splits a base-mesh local vector on the root process into a patch-local vector.
void split_read_from (Global::Vector< LocalVector_, Mirror_ > &vector, const String &filename, LAFEM::FileMode mode=LAFEM::FileMode::fm_binary)
Reads in a base-mesh local vector and splits it into a global vector.
void split_read_from (LocalVector_ &vector, const String &filename, LAFEM::FileMode mode=LAFEM::FileMode::fm_binary)
Reads in a base-mesh local vector and splits it into a patch-local vector.
Public Attributes
LocalVector_ _base_vector_tmpl
our base-mesh vector template; only required for join() but not for split()
MuxerType _muxer
our internal muxer
Detailed Description
template<typename LocalVector_, typename Mirror_>
class FEAT::Global::Splitter< LocalVector_, Mirror_ >
Global base-mesh vector splitter (and joiner) implementation.
This class provides the functionality for the transfer of primal vectors between a partitioned mesh and its underlying unpartitioned base-mesh on the same refinement level. Technically, this class is merely a special case of the more general Muxer class, however, this class additionally offers some direct file I/O methods. The purpose of this class is to enable the user to write a solution vector, that has been computed on a partitioned mesh in an MPI-parallel simulation, into a single output file on the corresponding unpartitioned mesh by using the join_write_out() function, which can then be read in by another possibly sequential application by the means of the standard LAFEM read_from methods. Furthermore, this class also offers the vice-versa functionality, i.e. it is possible to read in a vector on the unpartitioned mesh that has been written out by the standard LAFEM write_out methods and split it into the local vectors on the corresponding partitioned mesh in an MPI-parallel application by using the split_read_from() function. Of course, as a direct consequence, it is also possible to write a partitioned vector generated on N MPI processes and then read it in by an application running on a different number of MPI processes.
Template Parameters
LocalVector_ The local vector type that the splitter is to be applied onto.
Mirror_ The mirror type that is to be used.
To set up an object of this class, the following steps have to be performed:
On each process, call the set_root() function and provide the communicator as well as the rank of the remaining root process as well as the identity mirror for all DOFs.
On the root process, call the push_patch() function and provide the mirror for each corresponding child patch, which can be assembled from the 'patch:' meshparts that are (hopefully) generated by the partitioner.
On the root process, provide a template vector on the unpartitioned base-mesh space by calling the set_base_vector_template() function. Note that this step is only required if you intend to use the join() or join_write_out() functions and can be skipped if you only want to use the split() or split_read_from() functions.
Compile the splitter by calling the compile() function and supplying it with a temporary local vector.
Author
Peter Zajac
Definition at line 60 of file splitter.hpp.
Member Typedef Documentation
GlobalVectorType
template<typename LocalVector_ , typename Mirror_ > typedef Global::Vector<LocalVector_, Mirror_> FEAT::Global::Splitter< LocalVector_, Mirror_ >::GlobalVectorType
our global vector type
Definition at line 70 of file splitter.hpp.
LocalVectorType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVector_ FEAT::Global::Splitter< LocalVector_, Mirror_ >::LocalVectorType
our local vector type
Definition at line 67 of file splitter.hpp.
MuxerType
template<typename LocalVector_ , typename Mirror_ > typedef Global::Muxer<LocalVector_, Mirror_> FEAT::Global::Splitter< LocalVector_, Mirror_ >::MuxerType
our internal muxer type
Definition at line 64 of file splitter.hpp.
Constructor & Destructor Documentation
Splitter() [1/2]
template<typename LocalVector_ , typename Mirror_ > FEAT::Global::Splitter< LocalVector_, Mirror_ >::Splitter () inline
standard constructor
Definition at line 80 of file splitter.hpp.
Splitter() [2/2]
template<typename LocalVector_ , typename Mirror_ > FEAT::Global::Splitter< LocalVector_, Mirror_ >::Splitter (Splitter< LocalVector_, Mirror_ > && other) inline
move-constructor
Definition at line 87 of file splitter.hpp.
~Splitter()
template<typename LocalVector_ , typename Mirror_ > virtual FEAT::Global::Splitter< LocalVector_, Mirror_ >::~Splitter () inline virtual
destructor
Definition at line 94 of file splitter.hpp.
Member Function Documentation
bytes()
template<typename LocalVector_ , typename Mirror_ > std::size_t FEAT::Global::Splitter< LocalVector_, Mirror_ >::bytes () const inline
Returns the internal data size in bytes.
Definition at line 156 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_base_vector_tmpl, FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer, and FEAT::Global::Muxer< LocalVector_, Mirror_ >::bytes().
Referenced by FEAT::Control::ScalarBasicSystemLevel< DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::bytes().
compile()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::compile (const LocalVector_ & vec_tmp_) inline
Compiles the muxer.
Parameters
[in] vec_tmp_ A transient reference to a temporary vector for internal use.
Definition at line 234 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer, and FEAT::Global::Muxer< LocalVector_, Mirror_ >::compile().
convert() [1/2]
template<typename LocalVector_ , typename Mirror_ > template<typename LVT2_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::convert (const Splitter< LVT2_, Mirror_ > & other, LocalVector_ && vector, LAFEM::CloneMode mode = LAFEM::CloneMode::Shallow) inline
Conversion function for different vector container type.
This function (re)creates this splitter from another gate with a different vector type, but the same mirrors. This can be used to create a splitter using DenseVectorBlocked from a splitter using DenseVector or vice versa.
Parameters
[in] other A (transient) reference to the splitter using the other vector type to create this splitter from.
[in] vector A temporary vector allocated to the correct size that is to be used for internal initialization.
[in] mode The clone-mode to be used for cloning the mirrors. Defaults to shallow clone.
Attention
This function does not (because it can not) convert the base-mesh vector template, so this has to be provided afterwards by calling the set_base_vector_template() function.
Definition at line 146 of file splitter.hpp.
References FEAT::Global::Muxer< LocalVector_, Mirror_ >::convert().
convert() [2/2]
template<typename LocalVector_ , typename Mirror_ > template<typename LVT2_ , typename MT2_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::convert (const Splitter< LVT2_, MT2_ > & other) inline
Conversion function for same vector container type but with different MDI-Type.
Parameters
[in] other A transient reference to the splitter to convert from
Definition at line 117 of file splitter.hpp.
References FEAT::Global::Muxer< LocalVector_, Mirror_ >::convert().
create_base_vector()
template<typename LocalVector_ , typename Mirror_ > LocalVector_ FEAT::Global::Splitter< LocalVector_, Mirror_ >::create_base_vector () const inline
Creates a new base-mesh vector.
Returns
A new vector for the base-mesh space, which is allocated to correct size(s), but its numerical contents are uninitialized.
Definition at line 245 of file splitter.hpp.
References FEAT::LAFEM::Layout, and XASSERT.
is_root()
template<typename LocalVector_ , typename Mirror_ > bool FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_root () const inline
Checks whether this is the root process.
The root process is the process that receives the joined local vector and which is responsible for writing out and reading in the files.
Returns
true, if this is the root process, otherwise false.
Definition at line 169 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer, FEAT::Global::Muxer< LocalVector_, Mirror_ >::get_sibling_comm(), and FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_parent().
Referenced by FEAT::Global::Splitter< LocalVector_, Mirror_ >::join(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::join_write_out(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::split_read_from().
is_single()
template<typename LocalVector_ , typename Mirror_ > bool FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_single () const inline
Checks whether there is only one process in the communicator.
Returns
true, if there is only one process, otherwise false.
Definition at line 179 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer, FEAT::Global::Muxer< LocalVector_, Mirror_ >::get_sibling_comm(), and FEAT::Dist::Comm::size().
Referenced by FEAT::Global::Splitter< LocalVector_, Mirror_ >::join(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::split().
join() [1/2]
template<typename LocalVector_ , typename Mirror_ > LocalVector_ FEAT::Global::Splitter< LocalVector_, Mirror_ >::join (const Global::Vector< LocalVector_, Mirror_ > & vector) const inline
Joins a global vector into a base-mesh local vector on the root process.
Parameters
[in] vector A transient reference to the global vector that is to be joined.
Returns
A base-mesh local vector that represents the joined input global vector.
Attention
A base-mesh vector template must have been given to this object on the root process by calling the set_base_vector_template() before calling this function.
Definition at line 264 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_base_vector_tmpl, FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_root(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_single(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::join(), FEAT::LAFEM::Layout, FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and XASSERTM.
Referenced by FEAT::Global::Splitter< LocalVector_, Mirror_ >::join(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::join_write_out().
join() [2/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::join (LocalVector_ & vec_base, const Global::Vector< LocalVector_, Mirror_ > & vector) const inline
Joins a global vector into a base-mesh local vector on the root process.
Parameters
[in,out] vec_base A transient reference to a base-mesh local vector that receives the joined global vector. Must be allocated to correct size(s), but its numerical contents are ignored.
[in] vector A transient reference to the type-1 global vector that is to be joined.
Note
It is not necessary to have supplied a base-mesh vector template by calling the set_base_vector_template() before calling this function, because the base-mesh vector is supplied here as a function parameter.
Definition at line 301 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer, FEAT::Global::Vector< LocalVector_, Mirror_ >::clone(), FEAT::LAFEM::Deep, FEAT::Global::Vector< LocalVector_, Mirror_ >::from_1_to_0(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_child(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_parent(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_single(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join_send(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and XASSERT.
join_write_out()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::join_write_out (const Global::Vector< LocalVector_, Mirror_ > & vector, const String & filename, LAFEM::FileMode mode = LAFEM::FileMode::fm_binary) inline
Joins a global vector into a base-mesh local vector and writes it to a file.
Parameters
[in] vector A transient reference to the type-1 global vector that is to be joined.
[in] filename The filename of the output file that is to be written.
[in] mode The LAFEM::FileMode of the output file, defaults to binary format.
Attention
A base-mesh vector template must have been given to this object on the root process by calling the set_base_vector_template() before calling this function.
Definition at line 397 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_root(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::join().
operator=()
template<typename LocalVector_ , typename Mirror_ > Splitter & FEAT::Global::Splitter< LocalVector_, Mirror_ >::operator= (Splitter< LocalVector_, Mirror_ > && other) inline
move-assign operator
Definition at line 99 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_base_vector_tmpl, and FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer.
push_patch()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::push_patch (Mirror_ && patch_mirror) inline
Adds a child rank and mirror for the parent process.
Parameters
[in] patch_mirror The mirror of the patch of this process.
Definition at line 207 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer, and FEAT::Global::Muxer< LocalVector_, Mirror_ >::push_child().
set_base_vector_template()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::set_base_vector_template (LocalVector_ && vector_template) inline
Sets the base-vector template on the root process.
Note
Calling this function is only required on the root process if one wants to make use of the join() or join_write_out() functions and can be skipped on all other processes.
Parameters
[in] vector_template A base-mesh vector that is allocated to correct size(s) and which is used as a template for the creation of temporary base-mesh vectors. Its numerical contents are ignored.
Definition at line 223 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_base_vector_tmpl.
set_root()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::set_root (const Dist::Comm * comm, int root_rank, Mirror_ && root_mirror) inline
Sets the root communicator.
Parameters
[in] comm The communicator.
[in] root_rank The rank of the root process in the comm.
[in] root_mirror The root mirror.
Definition at line 196 of file splitter.hpp.
References FEAT::Global::Muxer< LocalVector_, Mirror_ >::set_parent().
split() [1/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::split (Global::Vector< LocalVector_, Mirror_ > & vector, const LocalVector_ & vec_base) const inline
Splits a base-mesh local vector on the root process into a global vector.
Parameters
[in,out] vector A transient reference to the type-1 global vector that receives the split base-mesh vector. Must be allocated to correct size(s), but its numerical contents are ignored.
[in] vec_base A transient reference to a base-mesh local vector that is to be split.
Definition at line 343 of file splitter.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::split().
Referenced by FEAT::Global::Splitter< LocalVector_, Mirror_ >::split(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::split_read_from().
split() [2/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::split (LocalVector_ & vector, const LocalVector_ & vec_base) const inline
Splits a base-mesh local vector on the root process into a patch-local vector.
Parameters
[in,out] vector A transient reference to the type-1 patch-local vector that receives the split base-mesh vector. Must be allocated to correct size(s), but its numerical contents are ignored.
[in] vec_base A transient reference to a base-mesh local vector that is to be split.
Definition at line 359 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer, FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_child(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_parent(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_single(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split_recv(), and XASSERT.
split_read_from() [1/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::split_read_from (Global::Vector< LocalVector_, Mirror_ > & vector, const String & filename, LAFEM::FileMode mode = LAFEM::FileMode::fm_binary) inline
Reads in a base-mesh local vector and splits it into a global vector.
Parameters
[in,out] vector A transient reference to the type-1 global vector that is to be joined. Must be allocated to correct size(s), but its numerical contents are ignored.
[in] filename The filename of the input file that is to be read in.
[in] mode The LAFEM::FileMode of the input file, defaults to binary format.
Definition at line 423 of file splitter.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::split_read_from().
Referenced by FEAT::Global::Splitter< LocalVector_, Mirror_ >::split_read_from().
split_read_from() [2/2]
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Splitter< LocalVector_, Mirror_ >::split_read_from (LocalVector_ & vector, const String & filename, LAFEM::FileMode mode = LAFEM::FileMode::fm_binary) inline
Reads in a base-mesh local vector and splits it into a patch-local vector.
Parameters
[in,out] vector A transient reference to the type-1 patch-local vector that receives the split base-mesh vector. Must be allocated to correct size(s), but its numerical contents are ignored.
[in] filename The filename of the input file that is to be read in.
[in] mode The LAFEM::FileMode of the input file, defaults to binary format.
Definition at line 442 of file splitter.hpp.
References FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_root(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::split().
Member Data Documentation
_base_vector_tmpl
template<typename LocalVector_ , typename Mirror_ > LocalVector_ FEAT::Global::Splitter< LocalVector_, Mirror_ >::_base_vector_tmpl
our base-mesh vector template; only required for join() but not for split()
Definition at line 76 of file splitter.hpp.
Referenced by FEAT::Global::Splitter< LocalVector_, Mirror_ >::bytes(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::join(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::operator=(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::set_base_vector_template().
_muxer
template<typename LocalVector_ , typename Mirror_ > MuxerType FEAT::Global::Splitter< LocalVector_, Mirror_ >::_muxer
our internal muxer
Definition at line 74 of file splitter.hpp.
Referenced by FEAT::Global::Splitter< LocalVector_, Mirror_ >::bytes(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::compile(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_root(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::is_single(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::join(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::operator=(), FEAT::Global::Splitter< LocalVector_, Mirror_ >::push_patch(), and FEAT::Global::Splitter< LocalVector_, Mirror_ >::split().
The documentation for this class was generated from the following file:
kernel/global/splitter.hpp