FEAT: FEAT::Geometry::MeshPermutation< Shape_ > Class Template Reference
FEAT::Geometry::MeshPermutation< Shape_ > Class Template Reference
Mesh permutation class template.
#include <mesh_permutation.hpp>
Public Types
typedef std::array< Adjacency::Permutation, shape_dim+1 > PermArray
permutation array typedef
typedef Shape_ ShapeType
the underlying shape type
Public Member Functions
MeshPermutation ()
standard constructor
MeshPermutation (const MeshPermutation &)=delete
delete copy constructor
MeshPermutation (MeshPermutation &&other)
move constructor
template<int num_coords_, typename Coord_ >
MeshPermutation (PermutationStrategy strategy, const IndexSetHolder< Shape_ > &ish, const VertexSet< num_coords_, Coord_ > &vtx)
Creates a mesh permutation for a conformal mesh.
virtual ~MeshPermutation ()
virtual destructor
std::size_t bytes () const
MeshPermutation clone () const
void clone (const MeshPermutation &other)
Clones another mesh permutation object into this object.
template<int num_coords_, typename Coord_ >
void create (PermutationStrategy strategy, const IndexSetHolder< Shape_ > &ish, const VertexSet< num_coords_, Coord_ > &vtx)
Creates a mesh permutation for a conformal mesh.
void create_cmk (const IndexSetHolder< Shape_ > &ish, bool reverse)
Creates a (reversed) algebraic Cuthill-McKee mesh permutation for a conformal mesh.
void create_colored (const IndexSetHolder< Shape_ > &ish)
Creates a colored mesh permutation for a conformal mesh.
template<int num_coords_, typename Coord_ >
void create_gcmk (const IndexSetHolder< Shape_ > &ish, const VertexSet< num_coords_, Coord_ > &vtx, bool reverse)
Creates a (reversed) geometric Cuthill-McKee mesh permutation for a conformal mesh.
void create_inverse_permutations ()
(Re)Creates the inverse permutations from the forward ones.
template<int num_coords_, typename Coord_ >
void create_lexicographic (const IndexSetHolder< Shape_ > &ish, const VertexSet< num_coords_, Coord_ > &vtx)
Creates a lexicographic mesh permutation for a conformal mesh.
PermArray & create_other ()
Initializes a custom permutation.
void create_random (const IndexSetHolder< Shape_ > &ish)
Creates random mesh permutation for a conformal mesh.
void create_random (const IndexSetHolder< Shape_ > &ish, Random &rng)
Creates random mesh permutation for a conformal mesh.
bool empty () const
Checks whether this permutation is empty.
const std::vector< Index > & get_element_coloring () const
Returns a const reference to the element coloring vector.
const std::vector< Index > & get_element_layering () const
Returns a const reference to the element layering vector.
const Adjacency::Permutation & get_inv_perm (int dim=shape_dim) const
Returns a const reference to an inverse permutation.
const PermArray & get_inv_perms () const
const Adjacency::Permutation & get_perm (int dim=shape_dim) const
Returns a const reference to a (forward) permutation.
const PermArray & get_perms () const
PermutationStrategy get_strategy () const
MeshPermutation & operator= (const MeshPermutation &)=delete
delete copy-assign operator
MeshPermutation & operator= (MeshPermutation &&other)
move-assignment operator
int validate_sizes (const Index *num_entities) const
Validates the permutation sizes.
Static Public Attributes
static constexpr int shape_dim = ShapeType::dimension
the shape dimension
Static Protected Member Functions
static Index _pick_gcmk_root (const Adjacency::Graph &v_at_e, const Adjacency::Graph &e_at_v, const std::vector< int > &mask)
Auxiliary helper function: pick an unmasked root element for GCMK.
Protected Attributes
std::vector< Index > _element_coloring
std::vector< Index > _element_layering
PermArray _inv_perms
the inverse permutations
PermArray _perms
the actual permutations
PermutationStrategy _strategy
the permutation strategy
Detailed Description
template<typename Shape_>
class FEAT::Geometry::MeshPermutation< Shape_ >
Mesh permutation class template.
This class is responsible for computing and managing mesh permutations for conformal meshes. An object of this class is stored as a member variable of the ConformalMesh class.
Parameters
[in] Shape_ The shape type of the mesh that is to be permuted.
This class stores both the forward and inverse permutations for the entities of each dimension. The forward permutation P defines the new positions within the old ordering, i.e. x_new[k] = x_old[P[k]], whereas the corresponding inverse permutation Q defined the old positions within the new array, i.e. x_new[Q[k]] = x_old[k], where x_old is the original unpermuted array and x_new is the permuted array.
Details about Element Coloring strategies:
The fundamental property (definition) of a valid element coloring strategy is as follows:
Let E1 != E2 be two elements which share at least one common vertex, and let C(E1) and C(E2) denote the colors of E1 and E2, respectively, then it must hold that C(E1) != C(E2).
In other words: Two different elements of the same color are not adjacent to each other.
If the mesh was permuted by a coloring strategy and the strategy required NC > 0 colors, then (by definition of the coloring strategy) all elements are sorted by their corresponding color, i.e. first come all elements of color 0, then all elements of color 1, etc.
This class stores the offsets of the first element for each color in an element coloring vector, whose total length is equal to NC+1, i.e. we have:
_element_coloring[0] = index of first element of color 0 = 0
_element_coloring[1] = index of first element of color 1
_element_coloring[2] = index of first element of color 2
...
_element_coloring[NC-1] = index of first element of color NC
_element_coloring[NC] = total number of elements
Details about Element Layering strategies:
The fundamental property (definition) of a valid element layering strategy is as follows:
Let E1 != E2 be two elements which share at least one common vertex, and let L(E1) and L(E2) denote the layers of E1 and E2, respectively, then it must hold that |L(E1)- L(E2)| <= 1.
In other words: An element in layer L can only be adjacent to elements in the (same or adjacent) layers L or (L-1) or (L+1).
If the mesh was permuted by one of the layering strategies (e.g. one of the algebraic or geometric Cuthill-McKee permutations) and the strategy produced NL > 0 layers, then (by definition of the layering strategy) all elements are sorted by their corresponding layer, i.e. first come all elements in layer 0, then all elements in layer 1, etc.
This class stores the offsets of the first element for each layer in an element layering vector, whose total length is equal to NL+1, i.e. we have:
_element_layering[0] = index of first element of layer 0 = 0
_element_layering[1] = index of first element of layer 1
_element_layering[2] = index of first element of layer 2
...
_element_layering[NL-1] = index of first element of layer NL
_element_layering[NL] = total number of elements
Author
Peter Zajac
Definition at line 362 of file mesh_permutation.hpp.
Member Typedef Documentation
PermArray
template<typename Shape_ > typedef std::array<Adjacency::Permutation, shape_dim+1> FEAT::Geometry::MeshPermutation< Shape_ >::PermArray
permutation array typedef
Definition at line 372 of file mesh_permutation.hpp.
ShapeType
template<typename Shape_ > typedef Shape_ FEAT::Geometry::MeshPermutation< Shape_ >::ShapeType
the underlying shape type
Definition at line 366 of file mesh_permutation.hpp.
Constructor & Destructor Documentation
MeshPermutation() [1/3]
template<typename Shape_ > FEAT::Geometry::MeshPermutation< Shape_ >::MeshPermutation () inline
standard constructor
Definition at line 390 of file mesh_permutation.hpp.
MeshPermutation() [2/3]
template<typename Shape_ > template<int num_coords_, typename Coord_ > FEAT::Geometry::MeshPermutation< Shape_ >::MeshPermutation (PermutationStrategy strategy, const IndexSetHolder< Shape_ > & ish, const VertexSet< num_coords_, Coord_ > & vtx) inline explicit
Creates a mesh permutation for a conformal mesh.
Parameters
[in] strategy The mesh permutation strategy to be used.
[in] ish A transient reference to the index set holder of the conformal mesh.
[in] vtx A transient reference to the vertex set of the conformal mesh.
Definition at line 408 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::create().
MeshPermutation() [3/3]
template<typename Shape_ > FEAT::Geometry::MeshPermutation< Shape_ >::MeshPermutation (MeshPermutation< Shape_ > && other) inline
move constructor
Definition at line 418 of file mesh_permutation.hpp.
~MeshPermutation()
template<typename Shape_ > virtual FEAT::Geometry::MeshPermutation< Shape_ >::~MeshPermutation () inline virtual
virtual destructor
Definition at line 446 of file mesh_permutation.hpp.
Member Function Documentation
_pick_gcmk_root()
template<typename Shape_ > static Index FEAT::Geometry::MeshPermutation< Shape_ >::_pick_gcmk_root (const Adjacency::Graph & v_at_e, const Adjacency::Graph & e_at_v, const std::vector< int > & mask) inline static protected
Auxiliary helper function: pick an unmasked root element for GCMK.
Definition at line 1029 of file mesh_permutation.hpp.
References FEAT::Adjacency::Graph::image_begin(), and FEAT::Adjacency::Graph::image_end().
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::create_gcmk().
bytes()
template<typename Shape_ > std::size_t FEAT::Geometry::MeshPermutation< Shape_ >::bytes () const inline
Returns
The total size of this object in bytes.
Definition at line 477 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_element_coloring, FEAT::Geometry::MeshPermutation< Shape_ >::_element_layering, FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_perms, and FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::bytes().
clone() [1/2]
template<typename Shape_ > MeshPermutation FEAT::Geometry::MeshPermutation< Shape_ >::clone () const inline
Returns
An independent clone of this mesh permutation object.
Definition at line 469 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::clone().
clone() [2/2]
template<typename Shape_ > void FEAT::Geometry::MeshPermutation< Shape_ >::clone (const MeshPermutation< Shape_ > & other) inline
Clones another mesh permutation object into this object.
Parameters
[in] other A reference to the source object that is to be cloned into this object.
Definition at line 456 of file mesh_permutation.hpp.
References FEAT::Geometry::other, and FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::clone(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone().
create()
template<typename Shape_ > template<int num_coords_, typename Coord_ > void FEAT::Geometry::MeshPermutation< Shape_ >::create (PermutationStrategy strategy, const IndexSetHolder< Shape_ > & ish, const VertexSet< num_coords_, Coord_ > & vtx) inline
Creates a mesh permutation for a conformal mesh.
This function is effectively just a switch-case wrapper for the other create_XXX() member functions.
Parameters
[in] strategy The mesh permutation strategy to be used. Must not be PermutationStrategy::other.
[in] ish A transient reference to the index set holder of the conformal mesh.
[in] vtx A transient reference to the vertex set of the conformal mesh.
Definition at line 587 of file mesh_permutation.hpp.
References FEAT::Geometry::colored, FEAT::Geometry::MeshPermutation< Shape_ >::create_cmk(), FEAT::Geometry::MeshPermutation< Shape_ >::create_colored(), FEAT::Geometry::MeshPermutation< Shape_ >::create_gcmk(), FEAT::Geometry::MeshPermutation< Shape_ >::create_lexicographic(), FEAT::Geometry::MeshPermutation< Shape_ >::create_random(), FEAT::Geometry::cuthill_mckee, FEAT::Geometry::cuthill_mckee_reversed, FEAT::Geometry::geometric_cuthill_mckee, FEAT::Geometry::geometric_cuthill_mckee_reversed, FEAT::Geometry::lexicographic, FEAT::Geometry::none, FEAT::Geometry::other, FEAT::Geometry::random, and XABORTM.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::MeshPermutation(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::create_permutation().
create_cmk()
template<typename Shape_ > void FEAT::Geometry::MeshPermutation< Shape_ >::create_cmk (const IndexSetHolder< Shape_ > & ish, bool reverse) inline
Creates a (reversed) algebraic Cuthill-McKee mesh permutation for a conformal mesh.
Parameters
[in] ish A transient reference to the index set holder of the conformal mesh.
[in] reverse Specifies whether the ordering is to be reversed.
Note
This function also creates an element layering automatically.
This function only creates a permutation for the mesh elements (entities of highest dimension) but not for the lower-dimensional entities.
Definition at line 780 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_perms, FEAT::Adjacency::CuthillMcKee::compute(), FEAT::Geometry::cuthill_mckee, FEAT::Geometry::cuthill_mckee_reversed, FEAT::Adjacency::injectify, FEAT::Geometry::none, FEAT::Adjacency::CuthillMcKee::root_minimum_degree, FEAT::Adjacency::CuthillMcKee::sort_asc, FEAT::Adjacency::transpose, and XASSERTM.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::create().
create_colored()
template<typename Shape_ > void FEAT::Geometry::MeshPermutation< Shape_ >::create_colored (const IndexSetHolder< Shape_ > & ish) inline
Creates a colored mesh permutation for a conformal mesh.
Parameters
[in] ish A transient reference to the index set holder of the conformal mesh.
Note
This function also creates an element coloring automatically.
This function only creates a permutation for the mesh elements (entities of highest dimension) but not for the lower-dimensional entities.
Definition at line 732 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_perms, FEAT::Geometry::colored, FEAT::Adjacency::Coloring::create_partition_graph(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Adjacency::Graph::get_num_indices(), FEAT::Adjacency::injectify, FEAT::Geometry::none, FEAT::Adjacency::transpose, FEAT::Adjacency::Permutation::type_perm, XASSERT, and XASSERTM.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::create().
create_gcmk()
template<typename Shape_ > template<int num_coords_, typename Coord_ > void FEAT::Geometry::MeshPermutation< Shape_ >::create_gcmk (const IndexSetHolder< Shape_ > & ish, const VertexSet< num_coords_, Coord_ > & vtx, bool reverse) inline
Creates a (reversed) geometric Cuthill-McKee mesh permutation for a conformal mesh.
Parameters
[in] ish A transient reference to the index set holder of the conformal mesh.
[in] vtx A transient reference to the vertex set of the conformal mesh.
[in] reverse Specifies whether the ordering is to be reversed.
Note
This function also creates an element layering automatically.
This function creates permutations for the mesh entities for each dimension.
Remarks
Currently, the vtx parameter is not used by this function, but it is still required for upwards compatibility, because it is possible to improve this algorithm by also using the vertex positioning information.
Definition at line 821 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_pick_gcmk_root(), FEAT::Geometry::geometric_cuthill_mckee, FEAT::Geometry::geometric_cuthill_mckee_reversed, FEAT::Adjacency::Graph::image_begin(), FEAT::Adjacency::Graph::image_end(), FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim, FEAT::Adjacency::transpose, FEAT::Adjacency::Permutation::type_perm, and XASSERT.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::create().
create_inverse_permutations()
template<typename Shape_ > void FEAT::Geometry::MeshPermutation< Shape_ >::create_inverse_permutations () inline
(Re)Creates the inverse permutations from the forward ones.
Definition at line 984 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_perms, and FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim.
create_lexicographic()
template<typename Shape_ > template<int num_coords_, typename Coord_ > void FEAT::Geometry::MeshPermutation< Shape_ >::create_lexicographic (const IndexSetHolder< Shape_ > & ish, const VertexSet< num_coords_, Coord_ > & vtx) inline
Creates a lexicographic mesh permutation for a conformal mesh.
Parameters
[in] ish A transient reference to the index set holder of the conformal mesh.
[in] vtx A transient reference to the vertex set of the conformal mesh.
Note
This function creates permutations for the mesh entities for each dimension.
Definition at line 702 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_perms, FEAT::Geometry::lexicographic, FEAT::Geometry::none, FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim, and XASSERTM.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::create().
create_other()
template<typename Shape_ > PermArray & FEAT::Geometry::MeshPermutation< Shape_ >::create_other () inline
Initializes a custom permutation.
This functions sets the internal strategy enum to PermutationStrategy::other and returns a non-const reference to the internal forwards permutations array, which can then be filled by the caller with the actual permutation data.
Attention
Do not forget to call the create_inverse_permutations() function once you have filled the forward permutations arrays!
Returns
A non-const reference to the internal forward permutations array.
Definition at line 642 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_perms, FEAT::Geometry::none, FEAT::Geometry::other, and XASSERTM.
create_random() [1/2]
template<typename Shape_ > void FEAT::Geometry::MeshPermutation< Shape_ >::create_random (const IndexSetHolder< Shape_ > & ish) inline
Creates random mesh permutation for a conformal mesh.
Parameters
[in] ish A transient reference to the index set holder of the conformal mesh.
Note
This function creates permutations for the mesh entities for each dimension.
Definition at line 658 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::create_random().
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::create(), and FEAT::Geometry::MeshPermutation< Shape_ >::create_random().
create_random() [2/2]
template<typename Shape_ > void FEAT::Geometry::MeshPermutation< Shape_ >::create_random (const IndexSetHolder< Shape_ > & ish, Random & rng) inline
Creates random mesh permutation for a conformal mesh.
Parameters
[in] ish A transient reference to the index set holder of the conformal mesh.
[in] rng A transient reference to the pseudo-random number generator to be used.
Note
This function creates permutations for the mesh entities for each dimension.
Definition at line 676 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_perms, FEAT::Geometry::none, FEAT::Geometry::random, FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim, and XASSERTM.
empty()
template<typename Shape_ > bool FEAT::Geometry::MeshPermutation< Shape_ >::empty () const inline
Checks whether this permutation is empty.
A permutation is empty if the permutation strategy is PermutationStrategy::none.
Returns
true, if this permutation is empty, otherwise false.
Definition at line 492 of file mesh_permutation.hpp.
References FEAT::Geometry::none.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::create_permutation(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::is_permuted(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::set_permutation().
get_element_coloring()
template<typename Shape_ > const std::vector< Index > & FEAT::Geometry::MeshPermutation< Shape_ >::get_element_coloring () const inline
Returns a const reference to the element coloring vector.
The returned vector may be empty, which indicates that the permutation is not a colored permutation and therefore no element coloring exists.
Returns
A const reference to the element coloring vector.
Definition at line 553 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_element_coloring.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_coloring().
get_element_layering()
template<typename Shape_ > const std::vector< Index > & FEAT::Geometry::MeshPermutation< Shape_ >::get_element_layering () const inline
Returns a const reference to the element layering vector.
The returned vector may be empty, which indicates that the permutation is not a layered permutation and therefore no element layering exists.
Returns
A const reference to the element layering vector.
Definition at line 566 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_element_layering.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_layering().
get_inv_perm()
template<typename Shape_ > const Adjacency::Permutation & FEAT::Geometry::MeshPermutation< Shape_ >::get_inv_perm (int dim = shape_dim) const inline
Returns a const reference to an inverse permutation.
Parameters
[in] dim The dimension of the entities whose permutation is to be returned. Must be 0 <= dim <= shape_dim.
Returns
A const reference to the inverse permutation of the entities of dimension dim.
Definition at line 539 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim, and XASSERT.
get_inv_perms()
template<typename Shape_ > const PermArray & FEAT::Geometry::MeshPermutation< Shape_ >::get_inv_perms () const inline
Returns
A const reference to the internal inverse permutations array.
Definition at line 510 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms.
Referenced by FEAT::Geometry::MeshPart< MeshType_ >::permute().
get_perm()
template<typename Shape_ > const Adjacency::Permutation & FEAT::Geometry::MeshPermutation< Shape_ >::get_perm (int dim = shape_dim) const inline
Returns a const reference to a (forward) permutation.
Parameters
[in] dim The dimension of the entities whose permutation is to be returned. Must be 0 <= dim <= shape_dim.
Returns
A const reference to the (forward) permutation of the entities of dimension dim.
Definition at line 524 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim, and XASSERT.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::create_permutation(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::set_permutation().
get_perms()
template<typename Shape_ > const PermArray & FEAT::Geometry::MeshPermutation< Shape_ >::get_perms () const inline
Returns
A const reference to the internal (forward) permutations array.
Definition at line 504 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_perms.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::create_permutation(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::set_permutation().
get_strategy()
template<typename Shape_ > PermutationStrategy FEAT::Geometry::MeshPermutation< Shape_ >::get_strategy () const inline
Returns
The PermutationStrategy that has been used to create this permutation.
Definition at line 498 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_strategy.
operator=()
template<typename Shape_ > MeshPermutation & FEAT::Geometry::MeshPermutation< Shape_ >::operator= (MeshPermutation< Shape_ > && other) inline
move-assignment operator
Definition at line 428 of file mesh_permutation.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::_element_coloring, FEAT::Geometry::MeshPermutation< Shape_ >::_element_layering, FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_perms, FEAT::Geometry::MeshPermutation< Shape_ >::_strategy, and FEAT::Geometry::other.
validate_sizes()
template<typename Shape_ > int FEAT::Geometry::MeshPermutation< Shape_ >::validate_sizes (const Index * num_entities) const inline
Validates the permutation sizes.
Parameters
[in] num_entities An transient array of size shape_dim+1 that contains the number of entities for each dimension.
Returns
0, if all permutation sizes are valid, or
j+1, if the permutations of dimension k have the wrong size
Definition at line 1005 of file mesh_permutation.hpp.
References FEAT::Adjacency::Permutation::empty(), FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim, FEAT::Adjacency::Permutation::size(), and XASSERT.
Member Data Documentation
_element_coloring
template<typename Shape_ > std::vector<Index> FEAT::Geometry::MeshPermutation< Shape_ >::_element_coloring protected
the element color array in case of colored strategy see the documentation of this class for details
Definition at line 383 of file mesh_permutation.hpp.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::bytes(), FEAT::Geometry::MeshPermutation< Shape_ >::get_element_coloring(), and FEAT::Geometry::MeshPermutation< Shape_ >::operator=().
_element_layering
template<typename Shape_ > std::vector<Index> FEAT::Geometry::MeshPermutation< Shape_ >::_element_layering protected
the layer array in case of algebraic/geometric Cuthill-McKee strategy see the documentation of this class for details
Definition at line 386 of file mesh_permutation.hpp.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::bytes(), FEAT::Geometry::MeshPermutation< Shape_ >::get_element_layering(), and FEAT::Geometry::MeshPermutation< Shape_ >::operator=().
_inv_perms
template<typename Shape_ > PermArray FEAT::Geometry::MeshPermutation< Shape_ >::_inv_perms protected
the inverse permutations
Definition at line 380 of file mesh_permutation.hpp.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::bytes(), FEAT::Geometry::MeshPermutation< Shape_ >::create_cmk(), FEAT::Geometry::MeshPermutation< Shape_ >::create_colored(), FEAT::Geometry::MeshPermutation< Shape_ >::create_gcmk(), FEAT::Geometry::MeshPermutation< Shape_ >::create_inverse_permutations(), FEAT::Geometry::MeshPermutation< Shape_ >::create_lexicographic(), FEAT::Geometry::MeshPermutation< Shape_ >::create_random(), FEAT::Geometry::MeshPermutation< Shape_ >::get_inv_perms(), and FEAT::Geometry::MeshPermutation< Shape_ >::operator=().
_perms
template<typename Shape_ > PermArray FEAT::Geometry::MeshPermutation< Shape_ >::_perms protected
the actual permutations
Definition at line 378 of file mesh_permutation.hpp.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::bytes(), FEAT::Geometry::MeshPermutation< Shape_ >::create_cmk(), FEAT::Geometry::MeshPermutation< Shape_ >::create_colored(), FEAT::Geometry::MeshPermutation< Shape_ >::create_gcmk(), FEAT::Geometry::MeshPermutation< Shape_ >::create_inverse_permutations(), FEAT::Geometry::MeshPermutation< Shape_ >::create_lexicographic(), FEAT::Geometry::MeshPermutation< Shape_ >::create_other(), FEAT::Geometry::MeshPermutation< Shape_ >::create_random(), FEAT::Geometry::MeshPermutation< Shape_ >::get_perms(), and FEAT::Geometry::MeshPermutation< Shape_ >::operator=().
_strategy
template<typename Shape_ > PermutationStrategy FEAT::Geometry::MeshPermutation< Shape_ >::_strategy protected
the permutation strategy
Definition at line 376 of file mesh_permutation.hpp.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::get_strategy(), and FEAT::Geometry::MeshPermutation< Shape_ >::operator=().
shape_dim
template<typename Shape_ > constexpr int FEAT::Geometry::MeshPermutation< Shape_ >::shape_dim = ShapeType::dimension static constexpr
the shape dimension
Definition at line 369 of file mesh_permutation.hpp.
Referenced by FEAT::Geometry::MeshPermutation< Shape_ >::bytes(), FEAT::Geometry::MeshPermutation< Shape_ >::clone(), FEAT::Geometry::MeshPermutation< Shape_ >::create_gcmk(), FEAT::Geometry::MeshPermutation< Shape_ >::create_inverse_permutations(), FEAT::Geometry::MeshPermutation< Shape_ >::create_lexicographic(), FEAT::Geometry::MeshPermutation< Shape_ >::create_random(), FEAT::Geometry::MeshPermutation< Shape_ >::get_inv_perm(), FEAT::Geometry::MeshPermutation< Shape_ >::get_perm(), and FEAT::Geometry::MeshPermutation< Shape_ >::validate_sizes().
The documentation for this class was generated from the following file:
kernel/geometry/mesh_permutation.hpp