FEAT: FEAT::Geometry::PatchMeshPartFactory< MeshType_ > Class Template Reference
FEAT::Geometry::PatchMeshPartFactory< MeshType_ > Class Template Reference
Factory for building a PatchBaseMesh from a given partitioning.
#include <patch_meshpart_factory.hpp>
Public Types
typedef MeshType_::VertexSetType::CoordType AttributeDataType
Data type for attributes.
typedef MeshPartType::AttributeSetContainer AttributeSetContainer
Mesh attribute holder type.
typedef MeshPartType::IndexSetHolderType IndexSetHolderType
Index set holder type.
typedef MeshPart< MeshType_ > MeshPartType
Mesh typedef.
typedef MeshType_::ShapeType ShapeType
The shape type of the mesh.
typedef MeshPartType::TargetSetHolderType TargetSetHolderType
Target set holder type.
Public Member Functions
PatchMeshPartFactory (Index my_rank, const Adjacency::Graph &elems_at_rank)
Builds a factory from a given partitioning.
PatchMeshPartFactory (std::vector< Index > &&cells_patch)
virtual ~PatchMeshPartFactory ()
virtual destructor
bool empty () const
Checks whether the patch is empty.
virtual void fill_attribute_sets (AttributeSetContainer &attribute_set_holder) override
Pretends to fill the attribute sets.
virtual void fill_index_sets (std::unique_ptr< IndexSetHolderType > &index_set_holder) override
Pretends to fill the index sets (=topology)
virtual void fill_target_sets (TargetSetHolderType &target_set_holder) override
Fills the target sets.
virtual Index get_num_entities (int dim) override
Returns the number of entities.
MeshPartType make ()
Creates a new mesh part and returns it.
std::unique_ptr< MeshPartType > make_unique ()
Creates a new mesh part on the heap and returns a unique pointer to it.
Static Public Attributes
static constexpr int shape_dim = ShapeType::dimension
The shape dimension.
Private Attributes
std::vector< Index > _cells_patch
This will hold all BaseMesh cell numbers of cells present in the patch.
Detailed Description
template<typename MeshType_>
class FEAT::Geometry::PatchMeshPartFactory< MeshType_ >
Factory for building a PatchBaseMesh from a given partitioning.
Template Parameters
MeshType_ Type of the BaseMesh
Author
Jordi Paul
Peter Zajac
Definition at line 26 of file patch_meshpart_factory.hpp.
Member Typedef Documentation
AttributeDataType
template<typename MeshType_ > typedef MeshType_::VertexSetType::CoordType FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::AttributeDataType
Data type for attributes.
Definition at line 34 of file patch_meshpart_factory.hpp.
AttributeSetContainer
template<typename MeshType_ > typedef MeshPartType::AttributeSetContainer FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::AttributeSetContainer
Mesh attribute holder type.
Definition at line 36 of file patch_meshpart_factory.hpp.
IndexSetHolderType
template<typename MeshType_ > typedef MeshPartType::IndexSetHolderType FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::IndexSetHolderType
Index set holder type.
Definition at line 38 of file patch_meshpart_factory.hpp.
MeshPartType
template<typename MeshType_ > typedef MeshPart<MeshType_> FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::MeshPartType
Mesh typedef.
Definition at line 32 of file patch_meshpart_factory.hpp.
ShapeType
template<typename MeshType_ > typedef MeshType_::ShapeType FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::ShapeType
The shape type of the mesh.
Definition at line 30 of file patch_meshpart_factory.hpp.
TargetSetHolderType
template<typename MeshType_ > typedef MeshPartType::TargetSetHolderType FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::TargetSetHolderType
Target set holder type.
Definition at line 40 of file patch_meshpart_factory.hpp.
Constructor & Destructor Documentation
PatchMeshPartFactory() [1/2]
template<typename MeshType_ > FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::PatchMeshPartFactory (Index my_rank, const Adjacency::Graph & elems_at_rank) inline explicit
Builds a factory from a given partitioning.
Parameters
[in] my_rank Identifier for this patch. Usually this is the MPI rank
[in] elems_at_rank A transient reference to the graph representing the elements-at-rank adjacency.
Definition at line 58 of file patch_meshpart_factory.hpp.
References FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::_cells_patch, FEAT::Adjacency::Graph::degree(), FEAT::Adjacency::Graph::image_begin(), FEAT::Adjacency::Graph::image_end(), and XASSERT.
PatchMeshPartFactory() [2/2]
template<typename MeshType_ > FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::PatchMeshPartFactory (std::vector< Index > && cells_patch) inline explicit
Definition at line 68 of file patch_meshpart_factory.hpp.
~PatchMeshPartFactory()
template<typename MeshType_ > virtual FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::~PatchMeshPartFactory () inline virtual
virtual destructor
Definition at line 74 of file patch_meshpart_factory.hpp.
Member Function Documentation
empty()
template<typename MeshType_ > bool FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::empty () const inline
Checks whether the patch is empty.
Definition at line 81 of file patch_meshpart_factory.hpp.
References FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::_cells_patch.
Referenced by FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch().
fill_attribute_sets()
template<typename MeshType_ > virtual void FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::fill_attribute_sets (AttributeSetContainer & attribute_set_holder) inline override virtual
Pretends to fill the attribute sets.
Parameters
[in,out] attribute_set_holder A transient reference to the attribute set holder whose attribute sets are to be filled.
This MeshPart does not have any attributes.
Implements FEAT::Geometry::Factory< MeshPart< MeshType_ > >.
Definition at line 110 of file patch_meshpart_factory.hpp.
fill_index_sets()
template<typename MeshType_ > virtual void FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::fill_index_sets (std::unique_ptr< IndexSetHolderType > & index_set_holder) inline override virtual
Pretends to fill the index sets (=topology)
Parameters
[in,out] index_set_holder A transient reference to the index set holder whose index sets are to be filled.
This MeshPart does not have a topology.
Implements FEAT::Geometry::Factory< MeshPart< MeshType_ > >.
Definition at line 124 of file patch_meshpart_factory.hpp.
fill_target_sets()
template<typename MeshType_ > virtual void FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::fill_target_sets (TargetSetHolderType & target_set_holder) inline override virtual
Fills the target sets.
Parameters
[in,out] target_set_holder A transient reference to the target set holder whose target sets are to be filled.
This fills just the TargetSet corresponding to the cell dimension.
Implements FEAT::Geometry::Factory< MeshPart< MeshType_ > >.
Definition at line 138 of file patch_meshpart_factory.hpp.
References FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::_cells_patch.
get_num_entities()
template<typename MeshType_ > virtual Index FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::get_num_entities (int dim) inline override virtual
Returns the number of entities.
Parameters
[in] dim The dimension of the entity whose count is to be returned. Must be 0 <= dim <= shape_dim.
Returns
The number of entities of dimension dim.
Implements FEAT::Geometry::Factory< MeshPart< MeshType_ > >.
Definition at line 95 of file patch_meshpart_factory.hpp.
References FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::_cells_patch, FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::shape_dim, and XASSERT.
make()
template<typename MeshType_ > MeshPartType FEAT::Geometry::Factory< MeshPart< MeshType_ > >::make () inline inherited
Creates a new mesh part and returns it.
Returns
A new mesh part object
Definition at line 628 of file mesh_part.hpp.
make_unique()
template<typename MeshType_ > std::unique_ptr< MeshPartType > FEAT::Geometry::Factory< MeshPart< MeshType_ > >::make_unique () inline inherited
Creates a new mesh part on the heap and returns a unique pointer to it.
Returns
A unique pointer to the newly created mesh part object
Definition at line 638 of file mesh_part.hpp.
Referenced by FEAT::Geometry::RootMeshNode< RootMesh_ >::create_patch_meshpart(), and FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch().
Member Data Documentation
_cells_patch
template<typename MeshType_ > std::vector<Index> FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::_cells_patch private
This will hold all BaseMesh cell numbers of cells present in the patch.
Definition at line 46 of file patch_meshpart_factory.hpp.
Referenced by FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::PatchMeshPartFactory(), FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::empty(), FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::fill_target_sets(), and FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::get_num_entities().
shape_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::shape_dim = ShapeType::dimension static constexpr
The shape dimension.
Definition at line 42 of file patch_meshpart_factory.hpp.
Referenced by FEAT::Geometry::PatchMeshPartFactory< MeshType_ >::get_num_entities().
The documentation for this class was generated from the following file:
kernel/geometry/patch_meshpart_factory.hpp