FEAT: FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ > Class Template Reference
FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ > Class Template Reference
Base class for Burgers Careau assembly jobs.
#include <burgers_carreau_assembly_job.hpp>
Public Types
typedef ConvVector_ ConvVectorType
the convection vector type
typedef DataType_ DataType
the datatype we use here
typedef Space_ SpaceType
the space type
Public Member Functions
BurgersCarreauAssemblyJobBase (const ConvVector_ &conv_vector, const Space_ &space_, const String &cubature)
Constructor.
template<typename VectorType_ >
void set_sd_v_norm (const VectorType_ &convect)
Sets the convection field norm \(\|v\|_\Omega\) for the local streamline diffusion parameter delta_T.
Static Public Member Functions
template<typename LocalVector_ , typename Mirror_ >
static DataType calc_sd_v_norm (const Global::Vector< LocalVector_, Mirror_ > &convect)
Calculates the convection field norm \(\|v\|_\Omega\) for the streamline diffusion parameter delta_T.
template<typename IndexType_ , int conv_dim_>
static DataType calc_sd_v_norm (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, conv_dim_ > &convect)
Calculates the convection field norm \(\|v\|_\Omega\) for the local streamline diffusion parameter delta_T.
Public Attributes
DataType_ a
DataType_ beta
scaling parameter for convective operator K
bool carreau
Assemble Carreau coefficient?
const ConvVector_ & convection_vector
the convection vector to be used
Cubature::DynamicFactory cubature_factory
the cubature factory to use
bool deformation
specifies whether to use the deformation tensor
DataType_ frechet_beta
scaling parameter for Frechet derivative of convective operator K'
bool frechet_carreau
Assemble full Jacobian for Carreau?
DataType_ lambda
DataType_ mu_0
DataType_ mu_inf
Carreau Data Parameter.
DataType_ n
DataType_ nu
scaling parameter for diffusive operator L (aka viscosity)
DataType_ reg_eps
DataType_ sd_delta
scaling parameter for streamline diffusion stabilization operator S
DataType_ sd_nu
viscosity parameter nu_S for streamline diffusion (usually equal to nu)
DataType_ sd_v_norm
velocity norm for streamline diffusion
const Space_ & space
the test-/trial-space to be used
DataType_ theta
scaling parameter for reactive operator M
Detailed Description
template<typename DataType_, typename Space_, typename ConvVector_>
class FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >
Base class for Burgers Careau assembly jobs.
Todo:
: Fix description regarding Carreau term This base class is used by various Burgers assemblers to outsource common coefficient member variables as well as code related to precomputing quantities required for the streamline diffusion stabilization.
The operators assembled by the derived classes are the scalar and vector-valued Burgers operators:
\[\mathbf{N}(v,u,\psi) := \nu \mathbf{L}(u,\psi) + \theta \mathbf{M}(u,\psi) + \beta \mathbf{K}(v,u,\psi) + \beta' \mathbf{K'}(v,u,\psi) + \delta \mathbf{S}(v,u,\psi)\]
where
L is the diffusive operator, which is either
the gradient tensor:
\[\mathbf{L}(u,\psi) := \int_\Omega \nabla u \cdot \nabla \psi~dx \]
or the deformation tensor (vector-valued operators only):
\[\mathbf{L}(u,\psi) := \frac{1}{4} \int_\Omega (\nabla+\nabla^\top) u : (\nabla+\nabla^\top) \psi~dx\]
M is the reactive operator:
\[\mathbf{M}(u,\psi) := \int_\Omega u\psi~dx\]
K is the convective operator:
\[\mathbf{K}(v,u,\psi) := \int_\Omega (v\cdot \nabla) u \psi~dx\]
K' is the additional term for the Fréchet derivative of the convective operator K (vector-valued operators only; see note below for details):
\[\mathbf{K'}(v,u,\psi) := \int_\Omega (\nabla v) u \psi~dx\]
S is the Samarskij-style streamline-diffusion stabilization operator (see note below for details):
\[\mathbf{S}(v,u,\psi) := \sum_{T\in\mathcal{T}_h}\delta_{T}\int_T (v\cdot\nabla u)\cdot(v\cdot\nabla\psi)~dx\]
where
\[\delta_T := \frac{h_T}{\|v\|_\Omega}\cdot\frac{2Re_T}{1+Re_T}\qquad\textnormal{and}\qquad Re_T := \frac{\|v\|_T\cdot h_T}{\nu_\mathbf{S}}\]
Notes on the Fréchet derivative of the convective term:
The trilinearform \(\mathbf{K}(v,u,\psi)\) represents the weak formulation of the convective term \(v\cdot\nabla u\), which is the generalization of the non-linear term \(u\cdot\nabla u\). To obtain the Fréchet derivative \(D\mathbf{K}\) of this non-linear operator in the case of \(v=u\), which is required for the Newton method on the Burgers equation, by definition of the Fréchet derivative we have to compute
\[D\mathbf{K}(v,u,\psi) = \bigg[\lim_{\varepsilon\rightarrow 0} \frac{\mathbf{K}(v + \varepsilon \hat{v}, u+\varepsilon \hat{u}, \psi)}{\varepsilon}\bigg]\bigg|_{\hat{u}=u,\hat{v}=v}\]
with \(\hat{u},\hat{v}\in V_h\) with \(\|\hat{u}\| = \|\hat{v}\| = 1\). So, here goes:
\begin{align*} \lim_{\varepsilon\rightarrow 0} \frac{\mathbf{K}(v + \varepsilon \hat{v}, u+\varepsilon \hat{u}, \psi)}{\varepsilon} &=\lim_{\varepsilon\rightarrow 0} \int_\Omega \frac{(v + \varepsilon \hat{v})\cdot\nabla(u+\varepsilon \hat{u}) - v\cdot\nabla u}{\varepsilon}\psi~dx\\ &= \lim_{\varepsilon\rightarrow 0} \int_\Omega\frac{v\cdot\nabla u +\varepsilon v\cdot\nabla \hat{u} + \varepsilon \hat{v}\cdot\nabla u+\varepsilon^2 \hat{v}\cdot\nabla \hat{u} - v\cdot\nabla u}{\varepsilon}\psi~dx\\ &= \lim_{\varepsilon\rightarrow 0} \int_\Omega\frac{\varepsilon v\cdot\nabla \hat{u} + \varepsilon \hat{v}\cdot\nabla u+\varepsilon^2 \hat{v}\cdot\nabla \hat{u}}{\varepsilon}\psi~dx\\ &= \lim_{\varepsilon\rightarrow 0}\frac{\varepsilon}{\varepsilon}\int_\Omega (v\cdot\nabla \hat{u})\psi~dx + \lim_{\varepsilon\rightarrow 0}\frac{\varepsilon}{\varepsilon}\int_\Omega (\hat{v}\cdot\nabla u)\psi~dx + \lim_{\varepsilon\rightarrow 0} \frac{\varepsilon^2}{\varepsilon} \int_\Omega (\hat{v}\cdot\nabla \hat{u})\psi~dx\\ &= \int_\Omega (v\cdot\nabla \hat{u})\psi~dx + \int_\Omega (\hat{v}\cdot\nabla u)\psi~dx + \lim_{\varepsilon\rightarrow 0} \varepsilon \int_\Omega (\hat{v}\cdot\nabla \hat{u})\psi~dx\\ &= \int_\Omega (v\cdot\nabla \hat{u})\psi~dx + \int_\Omega (\hat{v}\cdot\nabla u)\psi~dx \end{align*}
Finally, we obtain our Fréchet derivative by setting \(\hat{u} := u\) and \(\hat{v} = v\):
\[D\mathbf{K}(v,u,\psi) = \underbrace{\int_\Omega (v\cdot\nabla u)\psi~dx}_{=~\mathbf{K}(v,u,\psi)} + \underbrace{\int_\Omega (v\cdot\nabla u)\psi~dx}_{=:~\mathbf{K}'(v,u,\psi)}\]
Note that in the case of this assembly class, the Fréchet derivative \(D\mathbf{K}(v,u,\psi)\) is split into its two additive parts \(\mathbf{K}(v,u,\psi)\) and \(\mathbf{K'}(v,u,\psi)\), which are individually scaled by \(\beta\) and \(\beta'\), respectively, so one has to set both \(\beta = \beta' = 1\) to use the full Fréchet derivative operator \(D\mathbf{K}\).
Notes on Streamline Diffusion Stabilization:
The implementation of the streamline diffusion stabilization is based on Turek's CFD book (see [TurekCFD], pages 119 – 123), however, in the formula above, the local stabilization parameter \(\delta_T\) is not pre- multiplied by the global parameter \(\delta^*\), compare eq. (3.75) in the book, as we use delta as a scaling parameter for the whole operator S in the definition of the full operator N, see above. To enable streamline diffusion stabilization, you have to perform several tasks:
Set the global stabilization parameter sd_delta, which corresponds to the delta* parameter in the CFD book. According to the book (and previous FEAT versions), the value should be in range [0.1, 2], but according to my personal experience, even smaller values may be a good choice (e.g. 0.02).
Set the viscosity parameter sd_nu, which is usually set equal to nu. The only reason for this extra parameter to exist is so that you can use this assembler class to assemble the stabilization without necessarily also assembling the diffusion operator, which is what would happen if you set nu to a non-zero value.
Set the (maximum) velocity norm sd_v_norm of the convection field, which corresponds to \(\|v\|_\Omega\) and is required for the computation of the local delta_T parameters. You can do this by either specifying the value directly or, more conveniently, use one of this class's set_sd_v_norm() functions to compute this norm from a (local or global) convection field vector.
Template Parameters
DataType_ The datatype to be used for the coefficient member variables
Space_ The finite element space to be used for assembly
ConvVector_ The type of the convection (velocity) vector field
Author
Maximilian Esser (based on Jonas Duennebacke's and Peter Zajac's Assemblers)
Definition at line 104 of file burgers_carreau_assembly_job.hpp.
Member Typedef Documentation
ConvVectorType
template<typename DataType_ , typename Space_ , typename ConvVector_ > typedef ConvVector_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::ConvVectorType
the convection vector type
Definition at line 114 of file burgers_carreau_assembly_job.hpp.
DataType
template<typename DataType_ , typename Space_ , typename ConvVector_ > typedef DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::DataType
the datatype we use here
Definition at line 108 of file burgers_carreau_assembly_job.hpp.
SpaceType
template<typename DataType_ , typename Space_ , typename ConvVector_ > typedef Space_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::SpaceType
the space type
Definition at line 111 of file burgers_carreau_assembly_job.hpp.
Constructor & Destructor Documentation
BurgersCarreauAssemblyJobBase()
template<typename DataType_ , typename Space_ , typename ConvVector_ > FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::BurgersCarreauAssemblyJobBase (const ConvVector_ & conv_vector, const Space_ & space_, const String & cubature) inline explicit
Constructor.
Parameters
[in] conv_vector A resident reference to the convection vector for the convective term.
[in] space_ A resident reference to the space to be assembled on.
[in] cubature The name of the cubature rule to be used for assembly.
Definition at line 171 of file burgers_carreau_assembly_job.hpp.
Member Function Documentation
calc_sd_v_norm() [1/2]
template<typename DataType_ , typename Space_ , typename ConvVector_ > template<typename LocalVector_ , typename Mirror_ > static DataType FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm (const Global::Vector< LocalVector_, Mirror_ > & convect) inline static
Calculates the convection field norm \(\|v\|_\Omega\) for the streamline diffusion parameter delta_T.
Note
This function automatically syncs the norm over all processes by using the vector's gate.
Parameters
[in] convect The transient (global) convection field vector.
Returns
The convection vector field norm.
Definition at line 226 of file burgers_carreau_assembly_job.hpp.
References FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm(), FEAT::Global::Vector< LocalVector_, Mirror_ >::get_gate(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::max().
calc_sd_v_norm() [2/2]
template<typename DataType_ , typename Space_ , typename ConvVector_ > template<typename IndexType_ , int conv_dim_> static DataType FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, conv_dim_ > & convect) inline static
Calculates the convection field norm \(\|v\|_\Omega\) for the local streamline diffusion parameter delta_T.
Parameters
[in] convect The transient (local) convection field vector.
Returns
The convection vector field norm.
Definition at line 204 of file burgers_carreau_assembly_job.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::Math::max(), and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size().
Referenced by FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm(), and FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::set_sd_v_norm().
set_sd_v_norm()
template<typename DataType_ , typename Space_ , typename ConvVector_ > template<typename VectorType_ > void FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::set_sd_v_norm (const VectorType_ & convect) inline
Sets the convection field norm \(\|v\|_\Omega\) for the local streamline diffusion parameter delta_T.
Parameters
[in] convect The transient (local) convection field vector.
Definition at line 242 of file burgers_carreau_assembly_job.hpp.
References FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm().
Member Data Documentation
a
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::a
Definition at line 156 of file burgers_carreau_assembly_job.hpp.
beta
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::beta
scaling parameter for convective operator K
Definition at line 126 of file burgers_carreau_assembly_job.hpp.
carreau
template<typename DataType_ , typename Space_ , typename ConvVector_ > bool FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::carreau
Assemble Carreau coefficient?
Definition at line 150 of file burgers_carreau_assembly_job.hpp.
convection_vector
template<typename DataType_ , typename Space_ , typename ConvVector_ > const ConvVector_& FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::convection_vector
the convection vector to be used
Definition at line 141 of file burgers_carreau_assembly_job.hpp.
cubature_factory
template<typename DataType_ , typename Space_ , typename ConvVector_ > Cubature::DynamicFactory FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::cubature_factory
the cubature factory to use
Definition at line 147 of file burgers_carreau_assembly_job.hpp.
deformation
template<typename DataType_ , typename Space_ , typename ConvVector_ > bool FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::deformation
specifies whether to use the deformation tensor
Definition at line 117 of file burgers_carreau_assembly_job.hpp.
frechet_beta
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::frechet_beta
scaling parameter for Frechet derivative of convective operator K'
Definition at line 129 of file burgers_carreau_assembly_job.hpp.
frechet_carreau
template<typename DataType_ , typename Space_ , typename ConvVector_ > bool FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::frechet_carreau
Assemble full Jacobian for Carreau?
Definition at line 153 of file burgers_carreau_assembly_job.hpp.
lambda
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::lambda
Definition at line 156 of file burgers_carreau_assembly_job.hpp.
mu_0
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::mu_0
Definition at line 156 of file burgers_carreau_assembly_job.hpp.
mu_inf
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::mu_inf
Carreau Data Parameter.
Definition at line 156 of file burgers_carreau_assembly_job.hpp.
n
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::n
Definition at line 156 of file burgers_carreau_assembly_job.hpp.
nu
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::nu
scaling parameter for diffusive operator L (aka viscosity)
Definition at line 120 of file burgers_carreau_assembly_job.hpp.
reg_eps
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::reg_eps
Definition at line 156 of file burgers_carreau_assembly_job.hpp.
sd_delta
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::sd_delta
scaling parameter for streamline diffusion stabilization operator S
Definition at line 132 of file burgers_carreau_assembly_job.hpp.
sd_nu
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::sd_nu
viscosity parameter nu_S for streamline diffusion (usually equal to nu)
Definition at line 135 of file burgers_carreau_assembly_job.hpp.
sd_v_norm
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::sd_v_norm
velocity norm for streamline diffusion
Definition at line 138 of file burgers_carreau_assembly_job.hpp.
space
template<typename DataType_ , typename Space_ , typename ConvVector_ > const Space_& FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::space
the test-/trial-space to be used
Definition at line 144 of file burgers_carreau_assembly_job.hpp.
theta
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersCarreauAssemblyJobBase< DataType_, Space_, ConvVector_ >::theta
scaling parameter for reactive operator M
Definition at line 123 of file burgers_carreau_assembly_job.hpp.
The documentation for this class was generated from the following file:
kernel/assembly/burgers_carreau_assembly_job.hpp