FEAT: FEAT::Solver::IterativeSolver< Vector_ > Class Template Reference
FEAT::Solver::IterativeSolver< Vector_ > Class Template Reference abstract
Abstract base-class for iterative solvers.
#include <iterative.hpp>
Public Types
typedef SolverBase< VectorType > BaseClass
The base class.
typedef VectorType::DataType DataType
Floating point type.
typedef Vector_ VectorType
The vector type this solver can be applied to.
Public Member Functions
virtual Status apply (Vector_ &vec_cor, const Vector_ &vec_def)=0
Solver application method.
DataType calc_convergence_rate () const
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
DataType calc_defect_reduction () const
Computes the overall defect reduction factor: (defect_final / defect_inital)
virtual Status correct (VectorType &vec_sol, const VectorType &vec_rhs)=0
Solver correction method.
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic ()
Symbolic finalization method.
DataType get_def_final () const
Returns the final defect.
DataType get_def_initial () const
Returns the initial defect.
DataType get_div_abs () const
Returns the absolute divergence.
DataType get_div_rel () const
Returns the relative divergence.
Index get_max_iter () const
Returns the maximum number of iterations.
Index get_min_iter () const
Returns the minimal number of iterations.
Index get_min_stag_iter () const
Returns the minimum stagnation iteration count.
Index get_num_iter () const
Returns number of performed iterations.
String get_plot_name () const
Returns the plot name of the solver.
DataType get_stag_rate () const
Returns the stagnation rate.
Status get_status () const
Returns the status.
virtual String get_summary () const
Returns a summary string.
DataType get_tol_abs () const
Returns the absolute tolerance.
DataType get_tol_abs_low () const
Returns the lower absolute tolerance.
DataType get_tol_rel () const
Returns the relative tolerance.
virtual void init ()
Initialization method.
virtual void init_numeric ()
Numeric initialization method.
virtual void init_symbolic ()
Symbolic initialization method.
bool is_converged () const
checks for convergence
bool is_converged (const DataType def_cur) const
checks for convergence
bool is_diverged () const
checks for divergence
bool is_diverged (const DataType def_cur) const
checks for divergence
virtual String name () const =0
Returns a descriptive string.
virtual void plot_summary () const
Plot a summary of the last solver run.
void set_div_abs (DataType div_abs)
Sets the absolute divergence for the solver.
void set_div_rel (DataType div_rel)
Sets the relative divergence for the solver.
void set_max_iter (Index max_iter)
Sets the maximum iteration count for the solver.
void set_min_iter (Index min_iter)
Sets the minimum iteration count for the solver.
void set_min_stag_iter (Index min_iter)
Sets the minimum stagnate iteration count for the solver.
void set_plot_interval (const Index plot_interval)
Sets the interval between two plot outputs, if any.
void set_plot_mode (const PlotMode plot_mode)
Sets the plot mode of the solver.
void set_plot_name (const String &plot_name)
Sets the plot name of the solver.
void set_stag_rate (DataType rate)
Sets the stagnation rate fot the solver.
void set_tol_abs (DataType tol_abs)
Sets the absolute tolerance for the solver.
void set_tol_abs_low (DataType tol_abs_low)
Sets the lower absolute tolerance for the solver.
void set_tol_rel (DataType tol_rel)
Sets the relative tolerance for the solver.
void skip_defect_calc (bool skip)
Specifies whether defect calculation is allowed to be skipped.
Protected Member Functions
IterativeSolver (const String &plot_name)
Protected constructor.
IterativeSolver (const String &plot_name, const String &section_name, PropertyMap *section)
Constructor using a PropertyMap.
virtual Status _analyse_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag)
Internal function: analyse the current defect.
virtual DataType _calc_def_norm (const VectorType &vec_def, const VectorType &vec_sol)
Computes the defect norm.
bool _plot_iter (Status st=Status::progress) const
Plot the current iteration?
virtual void _plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev)
Plots an iteration line.
bool _plot_summary () const
Plot summary?
void _print_line (const String &line) const
Prints a line.
bool _progress () const
Progress iteration?
void _set_comm (const Dist::Comm *comm)
Sets the communicator for the solver directly.
template<typename Matrix_ >
void _set_comm_by_matrix (const Matrix_ &matrix)
Sets the communicator for the solver from a matrix.
void _set_comm_by_vector (const Vector_ &vector)
Sets the communicator for the solver from a vector.
virtual Status _set_initial_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the initial defect vector.
virtual Status _set_new_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the new (next) defect vector.
virtual Status _update_defect (const DataType def_cur_norm)
Internal function: sets the new (next) defect norm.
Protected Attributes
const Dist::Comm * _comm
Communicator of the solver.
DataType _def_cur
current defect
DataType _def_init
initial defect
DataType _def_prev
previous iteration defect
DataType _div_abs
absolute divergence parameter
DataType _div_rel
relative divergence parameter
Index _iter_digits
iteration count digits for plotting
Index _max_iter
maximum number of iterations
Index _min_iter
minimum number of iterations
Index _min_stag_iter
minimum number of stagnation iterations
Index _num_iter
number of performed iterations
Index _num_stag_iter
number of consecutive stagnated iterations
Index _plot_interval
plot output interval
PlotMode _plot_mode
whether to plot something
String _plot_name
name of the solver in plots
bool _skip_def_calc
whether to skip defect computation if possible
DataType _stag_rate
stagnation rate
Status _status
current status of the solver
DataType _tol_abs
absolute tolerance parameter
DataType _tol_abs_low
absolute tolerance parameter
DataType _tol_rel
relative tolerance parameter
Detailed Description
template<typename Vector_>
class FEAT::Solver::IterativeSolver< Vector_ >
Abstract base-class for iterative solvers.
This class template acts as an abstract base class for iterative solvers. It also implements various auxiliary features for convergence control.
Template Parameters
Vector_ The class of the vector that is passed to the solver in the solve() method.
Author
Peter Zajac
Definition at line 118 of file iterative.hpp.
Member Typedef Documentation
BaseClass
template<typename Vector_ > typedef SolverBase<VectorType> FEAT::Solver::IterativeSolver< Vector_ >::BaseClass
The base class.
Definition at line 127 of file iterative.hpp.
DataType
template<typename Vector_ > typedef VectorType::DataType FEAT::Solver::IterativeSolver< Vector_ >::DataType
Floating point type.
Definition at line 125 of file iterative.hpp.
VectorType
template<typename Vector_ > typedef Vector_ FEAT::Solver::IterativeSolver< Vector_ >::VectorType
The vector type this solver can be applied to.
Definition at line 123 of file iterative.hpp.
Constructor & Destructor Documentation
IterativeSolver() [1/2]
template<typename Vector_ > FEAT::Solver::IterativeSolver< Vector_ >::IterativeSolver (const String & plot_name) inline explicit protected
Protected constructor.
This constructor initializes the following values:
relative tolerance: sqrt(eps) (~1E-8 for double)
absolute tolerance: 1/eps^2 (~1E+32 for double)
lower absolute tolerance: 0
relative divergence: 1/eps (~1E+16 for double)
absolute divergence: 1/eps^2 (~1E+32 for double)
stagnation rate: 0.95
minimum iterations: 0
maximum iterations: 100
minimum stagnation iterations: 0
convergence plot: false
Parameters
[in] plot_name Specifies the name of the iterative solver. This is used as a prefix for the convergence plot.
Definition at line 213 of file iterative.hpp.
IterativeSolver() [2/2]
template<typename Vector_ > FEAT::Solver::IterativeSolver< Vector_ >::IterativeSolver (const String & plot_name, const String & section_name, PropertyMap * section) inline explicit protected
Constructor using a PropertyMap.
See also
Solver configuration via PropertyMaps
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] plot_name The name of the solver.
Definition at line 254 of file iterative.hpp.
References FEAT::PropertyMap::get_entry().
Member Function Documentation
_analyse_defect()
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag) inline protected virtual
Internal function: analyse the current defect.
Note
This function is called by _set_new_defect() and _update_defect().
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
[in] check_stag Specifies whether to check (and update) the stagnation criterion. This is typically set to false if one wants to check anything else than the 'true' next defect norm.
Returns
The updated status code.
Definition at line 799 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_iter, FEAT::Solver::aborted, FEAT::Solver::diverged, FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), FEAT::Solver::IterativeSolver< Vector_ >::is_diverged(), FEAT::Math::isfinite(), FEAT::Solver::max_iter, FEAT::Solver::progress, FEAT::Solver::stagnated, and FEAT::Solver::success.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::_update_defect().
_calc_def_norm()
template<typename Vector_ > virtual DataType FEAT::Solver::IterativeSolver< Vector_ >::_calc_def_norm (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual
Computes the defect norm.
Parameters
[in] vec_def The current defect vector.
[in] vec_sol The current solution vector approximation.
Definition at line 652 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect().
_plot_iter()
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter (Status st = Status::progress) const inline protected
Plot the current iteration?
Parameters
[in] st The status of the current iteration.
Returns
true if the plot mode is set to iter or all and the plot interval matches or the solver does not continue to the next iteration
Definition at line 666 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, FEAT::Solver::IterativeSolver< Vector_ >::_plot_interval, FEAT::Solver::IterativeSolver< Vector_ >::_plot_mode, FEAT::Solver::all, FEAT::Solver::iter, and FEAT::Solver::progress.
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::_update_defect().
_plot_iter_line()
template<typename Vector_ > virtual void FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev) inline protected virtual
Plots an iteration line.
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
Definition at line 719 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_print_line(), FEAT::String::pad_front(), FEAT::stringify(), FEAT::stringify_fp_fix(), and FEAT::stringify_fp_sci().
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::_update_defect().
_plot_summary()
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::_plot_summary () const inline protected
Plot summary?
Returns
true if the plot mode is set to summary or all.
Definition at line 677 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_mode, FEAT::Solver::all, and FEAT::Solver::summary.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::plot_summary().
_print_line()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::_print_line (const String & line) const inline protected
Prints a line.
Parameters
[in] line The line to be printed.
Definition at line 698 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_comm, and FEAT::Dist::Comm::print().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::plot_summary().
_progress()
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::_progress () const inline protected
Progress iteration?
Returns
true if the solver should process, otherwise false.
Definition at line 687 of file iterative.hpp.
References FEAT::Solver::progress.
_set_comm()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::_set_comm (const Dist::Comm * comm) inline protected
Sets the communicator for the solver directly.
Parameters
[in] comm A pointer to the communicator that is to be used by the solver.
Definition at line 613 of file iterative.hpp.
_set_comm_by_matrix()
template<typename Vector_ > template<typename Matrix_ > void FEAT::Solver::IterativeSolver< Vector_ >::_set_comm_by_matrix (const Matrix_ & matrix) inline protected
Sets the communicator for the solver from a matrix.
Parameters
[in] matrix A reference to a matrix. If 'Matrix_' is a 'Global::Matrix', then the communicator of the matrix gate is taken.
Definition at line 626 of file iterative.hpp.
Referenced by FEAT::Solver::BiCGStab< Matrix_, Filter_ >::BiCGStab(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::BiCGStabL(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::FGMRES(), FEAT::Solver::GroppPCG< Matrix_, Filter_ >::GroppPCG(), FEAT::Solver::IDRS< Matrix_, Filter_ >::IDRS(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::NLOptLS(), FEAT::Solver::PCG< Matrix_, Filter_ >::PCG(), FEAT::Solver::PCR< Matrix_, Filter_ >::PCR(), FEAT::Solver::PipePCG< Matrix_, Filter_ >::PipePCG(), FEAT::Solver::PMR< Matrix_, Filter_ >::PMR(), FEAT::Solver::PSD< Matrix_, Filter_ >::PSD(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::RBiCGStab(), FEAT::Solver::RGCR< Matrix_, Filter_ >::RGCR(), and FEAT::Solver::Richardson< Matrix_, Filter_ >::Richardson().
_set_comm_by_vector()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::_set_comm_by_vector (const Vector_ & vector) inline protected
Sets the communicator for the solver from a vector.
Parameters
[in] vector A reference to a vector. If 'Vector_' is a 'Global::Vector', then the communicator of the vector gate is taken.
Definition at line 638 of file iterative.hpp.
_set_initial_defect()
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual
Internal function: sets the initial defect vector.
Parameters
[in] vec_def The initial defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Reimplemented in FEAT::Solver::QPenalty< Functional_ >.
Definition at line 748 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_calc_def_norm(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low, FEAT::Solver::aborted, FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), FEAT::Math::isfinite(), FEAT::Solver::SolverBase< Vector_ >::name(), FEAT::Solver::progress, FEAT::Math::sqr(), and FEAT::Solver::success.
Referenced by FEAT::Solver::PCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::PCR< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::PipePCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::_apply_intern(), and FEAT::Solver::GroppPCG< Matrix_, Filter_ >::_apply_intern().
_set_new_defect()
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual
Internal function: sets the new (next) defect vector.
This function computes the defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] vec_def The new defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Definition at line 857 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_calc_def_norm(), FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, FEAT::Solver::IterativeSolver< Vector_ >::_max_iter, FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::IterativeSolver< Vector_ >::_skip_def_calc, FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), and FEAT::Solver::SolverBase< Vector_ >::name().
Referenced by FEAT::Solver::PCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::PCR< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), and FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::_apply_intern().
_update_defect()
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_update_defect (const DataType def_cur_norm) inline protected virtual
Internal function: sets the new (next) defect norm.
This function takes a precalculated defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] def_cur_norm The new defect norm.
Returns
The updated Status code.
Note
This function is preferred over _set_new_defect when using asynchronous mpi operations.
Definition at line 903 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), and FEAT::Solver::SolverBase< Vector_ >::name().
Referenced by FEAT::Solver::PipePCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), and FEAT::Solver::GroppPCG< Matrix_, Filter_ >::_apply_intern().
apply()
template<typename Vector_ > virtual Status FEAT::Solver::SolverBase< Vector_ >::apply (Vector_ & vec_cor, const Vector_ & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::CuSolverLU, FEAT::Solver::CuSolverQR, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, and FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >.
Referenced by FEAT::Solver::solve().
calc_convergence_rate()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate () const inline
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
Definition at line 528 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, FEAT::Solver::IterativeSolver< Vector_ >::_def_init, FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, and FEAT::Math::pow().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
calc_defect_reduction()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::calc_defect_reduction () const inline
Computes the overall defect reduction factor: (defect_final / defect_inital)
Definition at line 543 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_init, and FEAT::Math::abs().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
correct()
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::correct (VectorType & vec_sol, const VectorType & vec_rhs) pure virtual
Solver correction method.
This method applies the solver represented by this object onto a given right-hand-side vector and updates the corresponding solution vector.
In contrast to the apply() method of the SolverBase base class, this method uses the vector vec_sol as the initial solution vector for the iterative solution process instead of ignoring its contents upon entry and starting with the null vector.
Parameters
[in,out] vec_sol The vector that contains the initial solution upon entry and receives the solution of the linear system upon exit.
[in] vec_rhs The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_sol and vec_rhs must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >, FEAT::Solver::MQCLinesearch< Functional_, Filter_ >, FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >, FEAT::Solver::SecantLinesearch< Functional_, Filter_ >, and FEAT::Solver::QPenalty< Functional_ >.
Referenced by FEAT::Solver::solve().
done()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 285 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric(), and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
done_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented in FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >.
Definition at line 248 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::done(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::done_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_numeric(), FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::done_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric().
done_symbolic()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done_symbolic () inline virtual inherited
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Reimplemented in FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >, FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::BiCGStab< Matrix_, Filter_ >, FEAT::Solver::BiCGStabL< Matrix_, Filter_ >, FEAT::Solver::Chebyshev< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::FGMRES< Matrix_, Filter_ >, FEAT::Solver::GroppPCG< Matrix_, Filter_ >, FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >, FEAT::Solver::IDRS< Matrix_, Filter_ >, FEAT::Solver::ILUPrecond< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::JacobiPrecond< Matrix_, Filter_ >, FEAT::Solver::Linesearch< Functional_, Filter_ >, FEAT::Solver::MatrixPrecond< Matrix_, Filter_ >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLCG< Functional_, Filter_ >, FEAT::Solver::NLSD< Functional_, Filter_ >, FEAT::Solver::PCG< Matrix_, Filter_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >, FEAT::Solver::PCR< Matrix_, Filter_ >, FEAT::Solver::PipePCG< Matrix_, Filter_ >, FEAT::Solver::PMR< Matrix_, Filter_ >, FEAT::Solver::PolynomialPrecond< Matrix_, Filter_ >, FEAT::Solver::PSD< Matrix_, Filter_ >, FEAT::Solver::QPenalty< Functional_ >, FEAT::Solver::RBiCGStab< Matrix_, Filter_ >, FEAT::Solver::RGCR< Matrix_, Filter_ >, FEAT::Solver::Richardson< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SORPrecond< Matrix_, Filter_ >, FEAT::Solver::SSORPrecond< Matrix_, Filter_ >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >, and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 257 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::done(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::done_symbolic(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::done_symbolic(), FEAT::Solver::Chebyshev< Matrix_, Filter_ >::done_symbolic(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::done_symbolic(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_symbolic(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::done_symbolic(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::done_symbolic(), FEAT::Solver::Linesearch< Functional_, Filter_ >::done_symbolic(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), FEAT::Solver::NLCG< Functional_, Filter_ >::done_symbolic(), FEAT::Solver::NLSD< Functional_, Filter_ >::done_symbolic(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::done_symbolic(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::done_symbolic(), FEAT::Solver::QPenalty< Functional_ >::done_symbolic(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_symbolic(), and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_symbolic().
get_def_final()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_def_final () const inline
Returns the final defect.
Definition at line 516 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
get_def_initial()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_def_initial () const inline
Returns the initial defect.
Definition at line 510 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_init.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
get_div_abs()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_div_abs () const inline
Returns the absolute divergence.
Definition at line 363 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_div_abs.
get_div_rel()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_div_rel () const inline
Returns the relative divergence.
Definition at line 357 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_div_rel.
get_max_iter()
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::get_max_iter () const inline
Returns the maximum number of iterations.
Definition at line 418 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_max_iter.
get_min_iter()
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::get_min_iter () const inline
Returns the minimal number of iterations.
Definition at line 412 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_iter.
get_min_stag_iter()
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::get_min_stag_iter () const inline
Returns the minimum stagnation iteration count.
Definition at line 387 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_stag_iter.
get_num_iter()
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter () const inline
Returns number of performed iterations.
Definition at line 406 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_num_iter.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLSD< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::PCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::PCR< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::PipePCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::GroppPCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_update_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
get_plot_name()
template<typename Vector_ > String FEAT::Solver::IterativeSolver< Vector_ >::get_plot_name () const inline
Returns the plot name of the solver.
Definition at line 467 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_name.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
get_stag_rate()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_stag_rate () const inline
Returns the stagnation rate.
Definition at line 375 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_stag_rate.
get_status()
template<typename Vector_ > Status FEAT::Solver::IterativeSolver< Vector_ >::get_status () const inline
Returns the status.
Definition at line 522 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_status.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
get_summary()
template<typename Vector_ > virtual String FEAT::Solver::IterativeSolver< Vector_ >::get_summary () const inline virtual
Returns a summary string.
Reimplemented in FEAT::Solver::Linesearch< Functional_, Filter_ >, and FEAT::Solver::NLOptLS< Functional_, Filter_ >.
Definition at line 556 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate(), FEAT::Solver::IterativeSolver< Vector_ >::calc_defect_reduction(), FEAT::Solver::IterativeSolver< Vector_ >::get_def_final(), FEAT::Solver::IterativeSolver< Vector_ >::get_def_initial(), FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), FEAT::Solver::IterativeSolver< Vector_ >::get_plot_name(), FEAT::Solver::IterativeSolver< Vector_ >::get_status(), FEAT::stringify(), FEAT::stringify_fp_fix(), and FEAT::stringify_fp_sci().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::plot_summary().
get_tol_abs()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_tol_abs () const inline
Returns the absolute tolerance.
Definition at line 332 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs.
get_tol_abs_low()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_tol_abs_low () const inline
Returns the lower absolute tolerance.
Definition at line 338 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low.
get_tol_rel()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_tol_rel () const inline
Returns the relative tolerance.
Definition at line 326 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel.
init()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 270 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
init_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init_numeric () inline virtual inherited
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented in FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::Chebyshev< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::ILUPrecond< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::JacobiPrecond< Matrix_, Filter_ >, FEAT::Solver::MatrixPrecond< Matrix_, Filter_ >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NonlinearOperatorPrecondWrapper< NonlinearOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >, FEAT::Solver::PolynomialPrecond< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >, and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 239 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::init(), FEAT::Solver::Chebyshev< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::init_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::init_numeric(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::init_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::init_numeric(), FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_numeric(), and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::init_numeric().
init_symbolic()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init_symbolic () inline virtual inherited
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented in FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >, FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::BiCGStab< Matrix_, Filter_ >, FEAT::Solver::BiCGStabL< Matrix_, Filter_ >, FEAT::Solver::Chebyshev< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::FGMRES< Matrix_, Filter_ >, FEAT::Solver::GroppPCG< Matrix_, Filter_ >, FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >, FEAT::Solver::IDRS< Matrix_, Filter_ >, FEAT::Solver::ILUPrecond< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::JacobiPrecond< Matrix_, Filter_ >, FEAT::Solver::Linesearch< Functional_, Filter_ >, FEAT::Solver::MatrixPrecond< Matrix_, Filter_ >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLCG< Functional_, Filter_ >, FEAT::Solver::NLSD< Functional_, Filter_ >, FEAT::Solver::PCG< Matrix_, Filter_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >, FEAT::Solver::PCR< Matrix_, Filter_ >, FEAT::Solver::PipePCG< Matrix_, Filter_ >, FEAT::Solver::PMR< Matrix_, Filter_ >, FEAT::Solver::PolynomialPrecond< Matrix_, Filter_ >, FEAT::Solver::PSD< Matrix_, Filter_ >, FEAT::Solver::QPenalty< Functional_ >, FEAT::Solver::RBiCGStab< Matrix_, Filter_ >, FEAT::Solver::RGCR< Matrix_, Filter_ >, FEAT::Solver::Richardson< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SORPrecond< Matrix_, Filter_ >, FEAT::Solver::SSORPrecond< Matrix_, Filter_ >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >, and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 229 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::init(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::Chebyshev< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::init_symbolic(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::init_symbolic(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::init_symbolic(), FEAT::Solver::Linesearch< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic(), FEAT::Solver::NLCG< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::NLSD< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::QPenalty< Functional_ >::init_symbolic(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::init_symbolic(), and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_symbolic().
is_converged() [1/2]
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::is_converged () const inline
checks for convergence
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Returns
true, if converged, else false
Definition at line 478 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, and FEAT::Solver::IterativeSolver< Vector_ >::is_converged().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::is_converged().
is_converged() [2/2]
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::is_converged (const DataType def_cur) const inline
checks for convergence
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Parameters
[in] def_cur The defect that is to be analysed
Returns
true, if converged, else false
Definition at line 492 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_init, FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs, FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low, and FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel.
is_diverged() [1/2]
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::is_diverged () const inline
checks for divergence
Definition at line 498 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, and FEAT::Solver::IterativeSolver< Vector_ >::is_diverged().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::is_diverged().
is_diverged() [2/2]
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::is_diverged (const DataType def_cur) const inline
checks for divergence
Definition at line 504 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_init, FEAT::Solver::IterativeSolver< Vector_ >::_div_abs, and FEAT::Solver::IterativeSolver< Vector_ >::_div_rel.
name()
template<typename Vector_ > virtual String FEAT::Solver::SolverBase< Vector_ >::name () const pure virtual inherited
Returns a descriptive string.
Returns
A string describing the solver.
Implemented in FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >, FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::BiCGStab< Matrix_, Filter_ >, FEAT::Solver::BiCGStabL< Matrix_, Filter_ >, FEAT::Solver::Chebyshev< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::CuSolverLU, FEAT::Solver::CuSolverQR, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::FGMRES< Matrix_, Filter_ >, FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >, FEAT::Solver::GroppPCG< Matrix_, Filter_ >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::IDRS< Matrix_, Filter_ >, FEAT::Solver::ILUPrecond< Matrix_, Filter_ >, FEAT::Solver::JacobiPrecond< Matrix_, Filter_ >, FEAT::Solver::MatrixPrecond< Matrix_, Filter_ >, FEAT::Solver::MKLDSS, FEAT::Solver::MQCLinesearch< Functional_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >, FEAT::Solver::NLCG< Functional_, Filter_ >, FEAT::Solver::NonlinearOperatorPrecondWrapper< NonlinearOperator_ >, FEAT::Solver::NLSD< Functional_, Filter_ >, FEAT::Solver::PCG< Matrix_, Filter_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >, FEAT::Solver::PCR< Matrix_, Filter_ >, FEAT::Solver::PipePCG< Matrix_, Filter_ >, FEAT::Solver::PMR< Matrix_, Filter_ >, FEAT::Solver::PolynomialPrecond< Matrix_, Filter_ >, FEAT::Solver::PreconWrapper< Matrix_, Filter_, Precon_ >, FEAT::Solver::PSD< Matrix_, Filter_ >, FEAT::Solver::QPenalty< Functional_ >, FEAT::Solver::RBiCGStab< Matrix_, Filter_ >, FEAT::Solver::RGCR< Matrix_, Filter_ >, FEAT::Solver::Richardson< Matrix_, Filter_ >, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SecantLinesearch< Functional_, Filter_ >, FEAT::Solver::SORPrecond< Matrix_, Filter_ >, FEAT::Solver::SSORPrecond< Matrix_, Filter_ >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >, FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::NLOptPrecond< OperatorType_::VectorType, Filter >, FEAT::Solver::NLOptPrecond< Operator_::VectorType, Filter_ >, and FEAT::Solver::NLOptPrecond< NonlinearOperator_::SystemLevelType::GlobalSystemVectorR, NonlinearOperator_::SystemLevelType::GlobalSystemFilter >.
Referenced by FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::_apply_precond(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::_update_defect().
plot_summary()
template<typename Vector_ > virtual void FEAT::Solver::IterativeSolver< Vector_ >::plot_summary () const inline virtual
Plot a summary of the last solver run.
Definition at line 573 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_summary(), FEAT::Solver::IterativeSolver< Vector_ >::_print_line(), and FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::apply(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::apply(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::apply(), FEAT::Solver::NLCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLSD< Functional_, Filter_ >::apply(), FEAT::Solver::PCG< Matrix_, Filter_ >::apply(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::apply(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::apply(), FEAT::Solver::IDRS< Matrix_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::correct(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::correct(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::correct(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::correct(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::correct(), FEAT::Solver::IDRS< Matrix_, Filter_ >::correct(), FEAT::Solver::NLCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLSD< Functional_, Filter_ >::correct(), FEAT::Solver::PCG< Matrix_, Filter_ >::correct(), and FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::correct().
set_div_abs()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_div_abs (DataType div_abs) inline
Sets the absolute divergence for the solver.
Definition at line 351 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_div_abs.
set_div_rel()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_div_rel (DataType div_rel) inline
Sets the relative divergence for the solver.
Definition at line 345 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_div_rel.
set_max_iter()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_max_iter (Index max_iter) inline
Sets the maximum iteration count for the solver.
Definition at line 399 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_iter_digits, FEAT::Solver::IterativeSolver< Vector_ >::_max_iter, FEAT::Math::ilog10(), and FEAT::Solver::max_iter.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_max_iter(), and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_max_iter().
set_min_iter()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_min_iter (Index min_iter) inline
Sets the minimum iteration count for the solver.
Definition at line 393 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_iter.
set_min_stag_iter()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_min_stag_iter (Index min_iter) inline
Sets the minimum stagnate iteration count for the solver.
Definition at line 381 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_stag_iter.
set_plot_interval()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_plot_interval (const Index plot_interval) inline
Sets the interval between two plot outputs, if any.
Parameters
[in] plot_interval The desired interval of iteration plots
Definition at line 455 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_interval.
set_plot_mode()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_plot_mode (const PlotMode plot_mode) inline
Sets the plot mode of the solver.
Parameters
[in] plot_mode The desired plot mode
Definition at line 445 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_mode.
set_plot_name()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_plot_name (const String & plot_name) inline
Sets the plot name of the solver.
Definition at line 461 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_name.
Referenced by FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::BiCGStabL().
set_stag_rate()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_stag_rate (DataType rate) inline
Sets the stagnation rate fot the solver.
Definition at line 369 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_stag_rate.
set_tol_abs()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_tol_abs (DataType tol_abs) inline
Sets the absolute tolerance for the solver.
Definition at line 314 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_abs(), and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_abs().
set_tol_abs_low()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_tol_abs_low (DataType tol_abs_low) inline
Sets the lower absolute tolerance for the solver.
Definition at line 320 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low.
set_tol_rel()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_tol_rel (DataType tol_rel) inline
Sets the relative tolerance for the solver.
Definition at line 308 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel.
skip_defect_calc()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::skip_defect_calc (bool skip) inline
Specifies whether defect calculation is allowed to be skipped.
Warning
Skipping defect calculation can lead to deadlocks in parallel solver implementations if one (but not all) processes need to compute the defect for some reason (like plotting) !
Use this function only when you really know what you are doing!
Parameters
[in] skip Specifies whether defect computation is allowed to be skipped.
Definition at line 434 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_skip_def_calc.
Member Data Documentation
_comm
template<typename Vector_ > const Dist::Comm* FEAT::Solver::IterativeSolver< Vector_ >::_comm protected
Communicator of the solver.
Definition at line 131 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_print_line().
_def_cur
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_def_cur protected
current defect
Definition at line 182 of file iterative.hpp.
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_update_defect(), FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate(), FEAT::Solver::IterativeSolver< Vector_ >::get_def_final(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::is_diverged().
_def_init
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_def_init protected
initial defect
Definition at line 180 of file iterative.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate(), FEAT::Solver::IterativeSolver< Vector_ >::calc_defect_reduction(), FEAT::Solver::IterativeSolver< Vector_ >::get_def_initial(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::is_diverged().
_def_prev
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_def_prev protected
previous iteration defect
Definition at line 184 of file iterative.hpp.
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), and FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern().
_div_abs
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_div_abs protected
absolute divergence parameter
Definition at line 166 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_div_abs(), FEAT::Solver::IterativeSolver< Vector_ >::is_diverged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_div_abs().
_div_rel
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_div_rel protected
relative divergence parameter
Definition at line 164 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_div_rel(), FEAT::Solver::IterativeSolver< Vector_ >::is_diverged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_div_rel().
_iter_digits
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_iter_digits protected
iteration count digits for plotting
Definition at line 186 of file iterative.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::set_max_iter().
_max_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_max_iter protected
maximum number of iterations
Definition at line 172 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_max_iter(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_max_iter(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_max_iter(), FEAT::Solver::IterativeSolver< Vector_ >::set_max_iter(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_abs(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_abs(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_fval(), and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_fval().
_min_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_min_iter protected
minimum number of iterations
Definition at line 170 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_min_iter(), and FEAT::Solver::IterativeSolver< Vector_ >::set_min_iter().
_min_stag_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_min_stag_iter protected
minimum number of stagnation iterations
Definition at line 176 of file iterative.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_min_stag_iter(), and FEAT::Solver::IterativeSolver< Vector_ >::set_min_stag_iter().
_num_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_num_iter protected
number of performed iterations
Definition at line 174 of file iterative.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::PipePCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_update_defect(), FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate(), and FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter().
_num_stag_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_num_stag_iter protected
number of consecutive stagnated iterations
Definition at line 178 of file iterative.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect().
_plot_interval
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_plot_interval protected
plot output interval
Definition at line 190 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), and FEAT::Solver::IterativeSolver< Vector_ >::set_plot_interval().
_plot_mode
template<typename Vector_ > PlotMode FEAT::Solver::IterativeSolver< Vector_ >::_plot_mode protected
whether to plot something
Definition at line 188 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_summary(), and FEAT::Solver::IterativeSolver< Vector_ >::set_plot_mode().
_plot_name
template<typename Vector_ > String FEAT::Solver::IterativeSolver< Vector_ >::_plot_name protected
name of the solver in plots
Definition at line 133 of file iterative.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_plot_name(), and FEAT::Solver::IterativeSolver< Vector_ >::set_plot_name().
_skip_def_calc
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::_skip_def_calc protected
whether to skip defect computation if possible
Definition at line 192 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::skip_defect_calc().
_stag_rate
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_stag_rate protected
stagnation rate
Definition at line 168 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_stag_rate(), and FEAT::Solver::IterativeSolver< Vector_ >::set_stag_rate().
_status
template<typename Vector_ > Status FEAT::Solver::IterativeSolver< Vector_ >::_status protected
current status of the solver
Definition at line 135 of file iterative.hpp.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::apply(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::apply(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::apply(), FEAT::Solver::NLCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLSD< Functional_, Filter_ >::apply(), FEAT::Solver::PCG< Matrix_, Filter_ >::apply(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::apply(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::apply(), FEAT::Solver::IDRS< Matrix_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::correct(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::correct(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::correct(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::correct(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::correct(), FEAT::Solver::IDRS< Matrix_, Filter_ >::correct(), FEAT::Solver::NLCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLSD< Functional_, Filter_ >::correct(), FEAT::Solver::PCG< Matrix_, Filter_ >::correct(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::correct(), and FEAT::Solver::IterativeSolver< Vector_ >::get_status().
_tol_abs
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs protected
absolute tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 160 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_tol_abs(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_tol_abs().
_tol_abs_low
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low protected
absolute tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 162 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_tol_abs_low(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_tol_abs_low().
_tol_rel
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel protected
relative tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 158 of file iterative.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::get_tol_rel(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_tol_rel().
The documentation for this class was generated from the following file:
kernel/solver/iterative.hpp