FEAT: FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > > Class Template Reference
FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > > Class Template Reference
Pre-Multiplied Discontinuous Diagonal Schur-Complement Matrix.
#include <pmdcdsc_matrix.hpp>
Public Types
typedef LAFEM::DenseVector< DataType, IndexType > BufferVectorType
typedef DT_ DataType
typedef GlobalMatrixTypeB::GateColType GateColType
The column-gate type (used by SFINAE)
typedef GlobalMatrixTypeD::GateRowType GateRowType
The row-gate type (used by SFINAE)
typedef Global::Gate< LocalVectorTypeP, MirrorTypeP > GateTypeP
typedef Global::Gate< LocalVectorTypeV, MirrorTypeV > GateTypeV
typedef Global::Matrix< LocalMatrixTypeB, MirrorTypeV, MirrorTypeP > GlobalMatrixTypeB
typedef Global::Matrix< LocalMatrixTypeD, MirrorTypeP, MirrorTypeV > GlobalMatrixTypeD
typedef Global::Vector< LocalVectorTypeP, MirrorTypeP > GlobalVectorTypeP
typedef Global::Vector< LocalVectorTypeV, MirrorTypeV > GlobalVectorTypeV
typedef IT_ IndexType
typedef LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, 1 > LocalMatrixTypeB
typedef LAFEM::SparseMatrixBCSR< DataType, IndexType, 1, dim > LocalMatrixTypeD
typedef LAFEM::SparseMatrixCSR< DataType, IndexType > LocalMatrixTypeS
typedef LAFEM::DenseVector< DataType, IndexType > LocalVectorTypeP
typedef LAFEM::DenseVectorBlocked< DataType, IndexType, dim > LocalVectorTypeV
typedef MirrorP_ MirrorTypeP
typedef MirrorV_ MirrorTypeV
typedef LAFEM::SparseMatrixCSCR< DataType, IndexType > NeighMatrixTypeS
typedef LocalVectorTypeV::ValueType ValueTypeA
typedef LocalMatrixTypeB::ValueType ValueTypeB
typedef LocalMatrixTypeD::ValueType ValueTypeD
typedef GlobalVectorTypeP VectorTypeL
typedef GlobalVectorTypeP VectorTypeR
Public Member Functions
PMDCDSCMatrix (const GlobalVectorTypeV &diagonal_a, const GlobalMatrixTypeB &matrix_b, const GlobalMatrixTypeD &matrix_d)
Constructor.
virtual ~PMDCDSCMatrix ()
virtual destructor
void apply (VectorTypeL &r, const VectorTypeR &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, const DataType alpha=DataType(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void asm_adp_numeric (LocalMatrixTypeS &matrix) const
Copies the numeric values of the matrix into an ADP matrix.
LocalMatrixTypeS asm_adp_symbolic (Index &glob_dof_offset, Index &glob_dof_count) const
Assembles the matrix structure of an algebraic DOF partitioned matrix.
VectorTypeL create_vector_l () const
VectorTypeR create_vector_r () const
GlobalVectorTypeP extract_diag () const
Extracts the main diagonal.
void extract_diag (GlobalVectorTypeP &vec_diag) const
Extracts the main diagonal.
String format_timings () const
Returns a string that contains the formatted timing statistics.
const Dist::Comm * get_comm () const
Returns a pointer to the underlying communicator.
const LocalMatrixTypeS & get_local_schur_matrix () const
void init ()
Performs both symbolic and numeric initialization of the matrix.
void init_numeric ()
Performs the numeric initialization of the matrix.
void init_symbolic ()
Performs the symbolic initialization of the matrix.
void reset_timings ()
Resets the internal stop watches used for collecting timing statistics.
Static Public Attributes
static constexpr int dim = dim_
static constexpr bool is_global = true
static constexpr bool is_local = false
Protected Member Functions
void _apply (LocalVectorTypeP &r, const LocalVectorTypeP &x, const LocalVectorTypeP &y, const DataType alpha, bool only_Ax) const
Applies this matrix onto a vector.
Static Protected Member Functions
static MirrorTypeP _asm_data_mirror (const MirrorTypeP &mirror_p, const MirrorTypeV &mirror_v, const LocalMatrixTypeB &matrix_b, const Adjacency::Graph &graph)
Auxiliary Function: computes a data mirror from B to B'.
static void _asm_local_schur_matrix (LocalMatrixTypeS &s, const LocalMatrixTypeD &d, const LocalVectorTypeV &a, const LocalMatrixTypeB &b)
Assembles the local Schur-Matrix S = (D*A*B)
static void _asm_neighbor_schur_matrix (NeighMatrixTypeS &s, const LocalMatrixTypeB &da, const MirrorTypeV &mirror_v, const Adjacency::Graph &graph_b, const BufferVectorType &buffer_b)
Assembles a neighbor Schur-Matrix S_k = (D*A*M_k^T*B_k)
static void _asm_pres_mirror (MirrorTypeP &mirror_p, const MirrorTypeV &mirror_v, const LocalMatrixTypeB &matrix_b)
Auxiliary function: assembles a pressure mirror from a velocity mirror and the B-matrix.
static Adjacency::Graph _asm_reduced_b (const MirrorTypeP &mirror_p, const MirrorTypeV &mirror_v, const LocalMatrixTypeB &matrix_b)
Auxiliary Function: reduces the matrix B to B'.
static String _fmt_time (double tsum_total, double tmax_total, double tsum, double tmax, String st)
auxiliary function: format a time line
static String _fmt_time (double tsum_total, double tmax_total, String st)
auxiliary function: format a time line
static BufferVectorType _gather_b (const MirrorTypeP &data_mirror, const LocalMatrixTypeB &matrix_b)
Auxiliary Function: Gathers the data array from B to B' using the data mirror.
static ValueTypeD _mat_mult_d_a (const ValueTypeD &val_d, const ValueTypeA &val_a)
auxiliary function for _asm_local_schur_matrix: multiply two values D*A
static void _mat_mult_d_a (ValueTypeB &val_da, const ValueTypeD &val_d, const ValueTypeA &val_a)
auxiliary function for _asm_neighbor_schur_matrix: multiply two values D*A and store in transposed form
static DataType _mat_mult_da_b (const ValueTypeB &val_da, const ValueTypeB &val_b)
auxiliary function for _asm_neighbor_schur_matrix: multiply two values DA*B with DA in transposed form
static DataType _mat_mult_da_b (const ValueTypeD &val_da, const ValueTypeB &val_b)
auxiliary function for _asm_local_schur_matrix: multiply two values DA*B
static void _premult_da (LocalMatrixTypeB &mat_da, const LocalMatrixTypeD &mat_d, const LocalVectorTypeV &mat_a)
Auxiliary Function: Computes the product (D*A) and stores the result in a CSC matrix.
Protected Attributes
std::vector< MirrorTypeP > _data_mirrors
B-matrix data mirrors.
const GlobalVectorTypeV & _diagonal_a
the diagonal matrix a (stored as a vector)
const GlobalMatrixTypeB & _matrix_b
the pressure-gradient matrix B
const GlobalMatrixTypeD & _matrix_d
the velocity-divergence matrix D
LocalMatrixTypeB _matrix_da
Pre-Multiplied transposed matrix-product (D*A)^T.
LocalMatrixTypeS _matrix_s
The local Schur-complement matrix.
std::vector< Adjacency::Graph > _neighbor_graphs
Neighbor B-matrix adjacency graphs.
std::vector< NeighMatrixTypeS > _neighbor_matrices
Pre-multiplied neighbor Schur-complement matrices.
std::vector< MirrorTypeP > _pres_mirrors
Pressure DOF mirrors.
std::vector< int > _ranks
neighbor process ranks
StopWatch watch_apply
total apply time
StopWatch watch_apply_matrix_loc
local Schur-Matrix apply time
StopWatch watch_apply_neighbor_s
neighbor Matrix apply time
StopWatch watch_init_num_gather_b
reduced-B matrix data gather time
StopWatch watch_init_num_matrix_loc
local Schur-Matrix numeric assembly time
StopWatch watch_init_num_neighbor_s
neighbor Schur-matrix numeric assembly time
StopWatch watch_init_num_premult_da
pre-multiply D*A time
StopWatch watch_init_numeric
total numeric init time
StopWatch watch_init_sym_data_mirror
reduced B-matrix data mirror assembly time
StopWatch watch_init_sym_matrix_loc
local Schur-Matrix symbolic assembly time
StopWatch watch_init_sym_neighbor_s
neighbor Schur-Matrix symbolic assembly time
StopWatch watch_init_sym_pres_mirror
pressure mirror assembly time
StopWatch watch_init_sym_reduced_b
reduced B-matrix symbolic assembly time
StopWatch watch_init_symbolic
total symbolic/numeric init time
Detailed Description
template<typename DT_, typename IT_, int dim_, typename MirrorV_, typename MirrorP_>
class FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >
Pre-Multiplied Discontinuous Diagonal Schur-Complement Matrix.
This class implements an efficient pre-multiplied distributed Schur-Complement matrix
\[S := D\cdot A\cdot B\]
where
A is a diagonal matrix (usually an inverted lumped velocity mass matrix)
D is a 1-by-d BCSR matrix (usually the velocity-divergence matrix of a Stokes system)
B is a d-by-1 BCSR matrix (usually the pressure-gradient matrix of a Stokes system)
Note
This class effectively performs the same task as the SymmetricLumpedSchurMatrix, however, the internal implementation is different and relies on explicitly pre-multiplying the Schur-complement matrices rather than performing three consecutive matrix-vector products.
Attention
This class can only be used if the pressure space is discontinuous! Any attempts to use this class for matrices deriving from a continuous pressure space will be aborted by a failed assertion. Please note that this limitation is not just for kicks, but the design of this class and its underlying algorithms simply can not work in this case.
Author
Peter Zajac
Definition at line 60 of file pmdcdsc_matrix.hpp.
Member Typedef Documentation
BufferVectorType
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::BufferVectorType
Definition at line 82 of file pmdcdsc_matrix.hpp.
DataType
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef DT_ FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::DataType
Definition at line 65 of file pmdcdsc_matrix.hpp.
GateColType
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef GlobalMatrixTypeB::GateColType FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::GateColType
The column-gate type (used by SFINAE)
Definition at line 100 of file pmdcdsc_matrix.hpp.
GateRowType
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef GlobalMatrixTypeD::GateRowType FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::GateRowType
The row-gate type (used by SFINAE)
Definition at line 98 of file pmdcdsc_matrix.hpp.
GateTypeP
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef Global::Gate<LocalVectorTypeP, MirrorTypeP> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::GateTypeP
Definition at line 88 of file pmdcdsc_matrix.hpp.
GateTypeV
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef Global::Gate<LocalVectorTypeV, MirrorTypeV> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::GateTypeV
Definition at line 87 of file pmdcdsc_matrix.hpp.
GlobalMatrixTypeB
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<LocalMatrixTypeB, MirrorTypeV, MirrorTypeP> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::GlobalMatrixTypeB
Definition at line 77 of file pmdcdsc_matrix.hpp.
GlobalMatrixTypeD
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<LocalMatrixTypeD, MirrorTypeP, MirrorTypeV> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::GlobalMatrixTypeD
Definition at line 78 of file pmdcdsc_matrix.hpp.
GlobalVectorTypeP
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef Global::Vector<LocalVectorTypeP, MirrorTypeP> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::GlobalVectorTypeP
Definition at line 85 of file pmdcdsc_matrix.hpp.
GlobalVectorTypeV
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef Global::Vector<LocalVectorTypeV, MirrorTypeV> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::GlobalVectorTypeV
Definition at line 84 of file pmdcdsc_matrix.hpp.
IndexType
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef IT_ FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::IndexType
Definition at line 66 of file pmdcdsc_matrix.hpp.
LocalMatrixTypeB
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LAFEM::SparseMatrixBCSR<DataType, IndexType, dim, 1> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::LocalMatrixTypeB
Definition at line 72 of file pmdcdsc_matrix.hpp.
LocalMatrixTypeD
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LAFEM::SparseMatrixBCSR<DataType, IndexType, 1, dim> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::LocalMatrixTypeD
Definition at line 73 of file pmdcdsc_matrix.hpp.
LocalMatrixTypeS
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LAFEM::SparseMatrixCSR<DataType, IndexType> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::LocalMatrixTypeS
Definition at line 74 of file pmdcdsc_matrix.hpp.
LocalVectorTypeP
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::LocalVectorTypeP
Definition at line 81 of file pmdcdsc_matrix.hpp.
LocalVectorTypeV
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LAFEM::DenseVectorBlocked<DataType, IndexType, dim> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::LocalVectorTypeV
Definition at line 80 of file pmdcdsc_matrix.hpp.
MirrorTypeP
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef MirrorP_ FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::MirrorTypeP
Definition at line 70 of file pmdcdsc_matrix.hpp.
MirrorTypeV
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef MirrorV_ FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::MirrorTypeV
Definition at line 69 of file pmdcdsc_matrix.hpp.
NeighMatrixTypeS
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LAFEM::SparseMatrixCSCR<DataType, IndexType> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::NeighMatrixTypeS
Definition at line 75 of file pmdcdsc_matrix.hpp.
ValueTypeA
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LocalVectorTypeV::ValueType FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::ValueTypeA
Definition at line 93 of file pmdcdsc_matrix.hpp.
ValueTypeB
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LocalMatrixTypeB::ValueType FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::ValueTypeB
Definition at line 94 of file pmdcdsc_matrix.hpp.
ValueTypeD
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef LocalMatrixTypeD::ValueType FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::ValueTypeD
Definition at line 95 of file pmdcdsc_matrix.hpp.
VectorTypeL
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef GlobalVectorTypeP FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::VectorTypeL
Definition at line 90 of file pmdcdsc_matrix.hpp.
VectorTypeR
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > typedef GlobalVectorTypeP FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::VectorTypeR
Definition at line 91 of file pmdcdsc_matrix.hpp.
Constructor & Destructor Documentation
PMDCDSCMatrix()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::PMDCDSCMatrix (const GlobalVectorTypeV & diagonal_a, const GlobalMatrixTypeB & matrix_b, const GlobalMatrixTypeD & matrix_d) inline explicit
Constructor.
Note
This constructor just saves the references, but does not perform any further initialization. This has to be done by hand by calling the init_symbolic() and init_numeric() functions.
Parameters
[in] diagonal_a A reference to the vector representing the diagonal matrix A.
[in] matrix_b A reference to the pressure-gradient matrix B.
[in] matrix_d A reference to the velocity-divergence matrix D.
Definition at line 235 of file pmdcdsc_matrix.hpp.
~PMDCDSCMatrix()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > virtual FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::~PMDCDSCMatrix () inline virtual
virtual destructor
Definition at line 246 of file pmdcdsc_matrix.hpp.
Member Function Documentation
_apply()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_apply (LocalVectorTypeP & r, const LocalVectorTypeP & x, const LocalVectorTypeP & y, const DataType alpha, bool only_Ax) const inline protected
Applies this matrix onto a vector.
Parameters
[in,out] r The vector that receives the result.
[in] x The multiplicand vector.
[in] x The summand vector.
[in] alpha The scaling factor for the product.
[in] only_Ax If true, then compute r := A*x, otherwise compute r := y + alpha*A*x.
Definition at line 1450 of file pmdcdsc_matrix.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_comm(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and FEAT::Dist::RequestVector::wait_all().
_asm_data_mirror()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static MirrorTypeP FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_data_mirror (const MirrorTypeP & mirror_p, const MirrorTypeV & mirror_v, const LocalMatrixTypeB & matrix_b, const Adjacency::Graph & graph) inline static protected
Auxiliary Function: computes a data mirror from B to B'.
Parameters
[in] mirror_p The pressure mirror as returned by the _asm_pres_mirror() function.
[in] mirror_v The velocity mirror that contains the indices of the rows of B that are to be extracted to B'.
[in] matrix_b The B-matrix which couples velocity and pressure DOFs.
[in] graph The adjacency graph storing the structure of the reduced matrix B'
Returns
A mirror for the data array of B to B'
Definition at line 1131 of file pmdcdsc_matrix.hpp.
References ASSERT, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Adjacency::Graph::get_num_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements().
_asm_local_schur_matrix()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix (LocalMatrixTypeS & s, const LocalMatrixTypeD & d, const LocalVectorTypeV & a, const LocalMatrixTypeB & b) inline static protected
Assembles the local Schur-Matrix S = (D*A*B)
Parameters
[in,out] s The Schur-Matrix S that is to be assembled.
[in] d,a,b The three multiplicand matrices.
Definition at line 1292 of file pmdcdsc_matrix.hpp.
References ASSERT, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and XASSERT.
_asm_neighbor_schur_matrix()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix (NeighMatrixTypeS & s, const LocalMatrixTypeB & da, const MirrorTypeV & mirror_v, const Adjacency::Graph & graph_b, const BufferVectorType & buffer_b) inline static protected
Assembles a neighbor Schur-Matrix S_k = (D*A*M_k^T*B_k)
Parameters
[in,out] s The neighbor Schur-Matrix S_k that is to be assembled.
[in] da The pre-multiplied matrix (D*A) stored in CSC format (transposed CSR)
[in] mirror_v The velocity mirror representing the mirror matrix M_k.
[in] graph_b The adjacency graph representing the layout of the matrix B_k.
[in] buffer_b A buffer vector containing the data array of the matrix B_k.
Definition at line 1360 of file pmdcdsc_matrix.hpp.
References ASSERT, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and XASSERT.
_asm_pres_mirror()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_pres_mirror (MirrorTypeP & mirror_p, const MirrorTypeV & mirror_v, const LocalMatrixTypeB & matrix_b) inline static protected
Auxiliary function: assembles a pressure mirror from a velocity mirror and the B-matrix.
Parameters
[out] mirror_p The mirror of all pressure DOFs that are coupled by at least one non-zero entry (each) of the given B-matrix to the velocity DOFs stored in the velocity mirror.
[in] mirror_v The velocity mirror that contains the indices of the rows of B that are to be extracted.
[in] matrix_b The B-matrix which couples velocity and pressure DOFs.
Definition at line 1018 of file pmdcdsc_matrix.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr().
_asm_reduced_b()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static Adjacency::Graph FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_reduced_b (const MirrorTypeP & mirror_p, const MirrorTypeV & mirror_v, const LocalMatrixTypeB & matrix_b) inline static protected
Auxiliary Function: reduces the matrix B to B'.
Parameters
[in] mirror_p The pressure mirror as returned by the _asm_pres_mirror() function.
[in] mirror_v The velocity mirror that contains the indices of the rows of B that are to be extracted to B'.
[in] matrix_b The B-matrix which couples velocity and pressure DOFs.
Returns
An adjacency graph storing the structure of the reduced matrix B'
Definition at line 1057 of file pmdcdsc_matrix.hpp.
References ASSERT, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), and FEAT::Adjacency::Graph::sort_indices().
_fmt_time() [1/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static String FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_fmt_time (double tsum_total, double tmax_total, double tsum, double tmax, String st) inline static protected
auxiliary function: format a time line
Definition at line 989 of file pmdcdsc_matrix.hpp.
References FEAT::Math::abs(), FEAT::String::pad_back(), and FEAT::stringify_fp_fix().
_fmt_time() [2/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static String FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_fmt_time (double tsum_total, double tmax_total, String st) inline static protected
auxiliary function: format a time line
Definition at line 981 of file pmdcdsc_matrix.hpp.
References FEAT::String::pad_back(), and FEAT::stringify_fp_fix().
_gather_b()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static BufferVectorType FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_gather_b (const MirrorTypeP & data_mirror, const LocalMatrixTypeB & matrix_b) inline static protected
Auxiliary Function: Gathers the data array from B to B' using the data mirror.
Parameters
[in] data_mirror The data mirror from B to B' as returned by the _asm_data_mirror() function.
[in] matrix_b The input matrix B from which the values for B' are to be gathered.
Returns
A buffer vector containing the gathered data array of B'.
Definition at line 1191 of file pmdcdsc_matrix.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val().
_mat_mult_d_a() [1/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static ValueTypeD FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_mat_mult_d_a (const ValueTypeD & val_d, const ValueTypeA & val_a) inline static protected
auxiliary function for _asm_local_schur_matrix: multiply two values D*A
Definition at line 1209 of file pmdcdsc_matrix.hpp.
_mat_mult_d_a() [2/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_mat_mult_d_a (ValueTypeB & val_da, const ValueTypeD & val_d, const ValueTypeA & val_a) inline static protected
auxiliary function for _asm_neighbor_schur_matrix: multiply two values D*A and store in transposed form
Definition at line 1227 of file pmdcdsc_matrix.hpp.
_mat_mult_da_b() [1/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static DataType FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_mat_mult_da_b (const ValueTypeB & val_da, const ValueTypeB & val_b) inline static protected
auxiliary function for _asm_neighbor_schur_matrix: multiply two values DA*B with DA in transposed form
Definition at line 1234 of file pmdcdsc_matrix.hpp.
_mat_mult_da_b() [2/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static DataType FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_mat_mult_da_b (const ValueTypeD & val_da, const ValueTypeB & val_b) inline static protected
auxiliary function for _asm_local_schur_matrix: multiply two values DA*B
Definition at line 1218 of file pmdcdsc_matrix.hpp.
_premult_da()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > static void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_premult_da (LocalMatrixTypeB & mat_da, const LocalMatrixTypeD & mat_d, const LocalVectorTypeV & mat_a) inline static protected
Auxiliary Function: Computes the product (D*A) and stores the result in a CSC matrix.
Parameters
[in,out] mat_da The matrix that receives the product (D*A).
[in] mat_d The multiplicand matrix D.
[in] mat_a A vector representing the diagonal matrix A.
Definition at line 1254 of file pmdcdsc_matrix.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val().
apply() [1/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 674 of file pmdcdsc_matrix.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::StopWatch::start(), and FEAT::StopWatch::stop().
apply() [2/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, const DataType alpha = DataType(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 689 of file pmdcdsc_matrix.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::StopWatch::start(), and FEAT::StopWatch::stop().
asm_adp_numeric()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_numeric (LocalMatrixTypeS & matrix) const inline
Copies the numeric values of the matrix into an ADP matrix.
Parameters
[in,out] matrix A reference to the ADP matrix which receives the copy of the values, as returned by the #asm_adp_symoblic() function.
Definition at line 889 of file pmdcdsc_matrix.hpp.
References ASSERT, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::copy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERT.
asm_adp_symbolic()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > LocalMatrixTypeS FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_symbolic (Index & glob_dof_offset, Index & glob_dof_count) const inline
Assembles the matrix structure of an algebraic DOF partitioned matrix.
This function computes the layout of the ADP matrix which corresponds to this PMDCDSC matrix, i.e. the matrix, which contains all rows of the virtual global matrix, which correspond to the global DOFs owned by this process. This function is used by the Solver::ADPSolverBase class specialization for this class.
Parameters
[out] glob_dof_offset Receives the global DOF offset of this process.
[out] glob_dof_count Receives the global DOF count over all processes.
Returns
A new local matrix object containing the rows of all DOFs that belong to this process.
Definition at line 714 of file pmdcdsc_matrix.hpp.
References FEAT::Dist::Comm::allreduce(), ASSERT, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::Dist::Comm::exscan(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::Layout, FEAT::Dist::op_sum, FEAT::Dist::Comm::rank(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::Dist::RequestVector::wait_all().
create_vector_l()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > VectorTypeL FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::create_vector_l () const inline
Returns
A new vector compatible L-vector.
Definition at line 257 of file pmdcdsc_matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_l().
create_vector_r()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > VectorTypeR FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::create_vector_r () const inline
Returns
A new vector compatible R-vector.
Definition at line 263 of file pmdcdsc_matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_r().
extract_diag() [1/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeP FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::extract_diag () const inline
Extracts the main diagonal.
Note
The main diagonal vector does not need to be synchronized, because the underlying pressure space is discontinuous by definition/assumption. However, nothing bad will happen if you synchronize the vector anyway.
Returns
A vector that contains the main diagonal of our matrix (D*A*B).
Definition at line 301 of file pmdcdsc_matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_l(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::local().
extract_diag() [2/2]
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::extract_diag (GlobalVectorTypeP & vec_diag) const inline
Extracts the main diagonal.
Note
The main diagonal vector does not need to be synchronized, because the underlying pressure space is discontinuous by definition/assumption. However, nothing bad will happen if you synchronize the vector anyway.
Parameters
[out] vec_diag A vector that receives the main diagonal of our matrix (D*A*B).
Definition at line 285 of file pmdcdsc_matrix.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::local().
format_timings()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > String FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::format_timings () const inline
Returns a string that contains the formatted timing statistics.
Attention
This function must be called by all processes, because it contains a collective call.
Returns
A string containing the timing statistics.
Definition at line 335 of file pmdcdsc_matrix.hpp.
References FEAT::StopWatch::elapsed(), FEAT::Dist::op_max, and FEAT::Dist::op_sum.
get_comm()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > const Dist::Comm * FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::get_comm () const inline
Returns a pointer to the underlying communicator.
Definition at line 251 of file pmdcdsc_matrix.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::get_comm().
get_local_schur_matrix()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > const LocalMatrixTypeS & FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::get_local_schur_matrix () const inline
Returns
A reference to the local Schur-Complement matrix
Definition at line 269 of file pmdcdsc_matrix.hpp.
init()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init () inline
Performs both symbolic and numeric initialization of the matrix.
Definition at line 399 of file pmdcdsc_matrix.hpp.
init_numeric()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric () inline
Performs the numeric initialization of the matrix.
This function performs the following internal tasks:
Compute the numerical values of the local Schur-complement matrix S = (D*A*B).
For each neighbor, extract all matrix entries of our local matrix B, which coincide with entries of the reduced B-matrix for that particular neighbor, and send these matrix entries over to that neighbor process.
For each neighbor, receive the entries of the reduced B-matrix and pre-compute the numerical values of the neighbor Schur-complement matrix S_k := (D*A*B_k).
Definition at line 607 of file pmdcdsc_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_comm(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and FEAT::Dist::RequestVector::wait_all().
init_symbolic()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_symbolic () inline
Performs the symbolic initialization of the matrix.
This function performs the following internal tasks:
Pre-compute the layout of the local Schur-complement matrix (D*A*B)
For each neighbor, compute a mirror of all pressure DOFs, which couple to at least one velocity DOF shared with that neighbor via our B-matrix. These are the pressure DOFs that have to be send to that neighbor during the matrix-vector multiplication in the apply() function.
For each neighbor, compute the layout of the reduced B-matrix, which contains all B-matrix entries, whose column indices correspond to the pressure DOFs in the previously assembled pressure mirror. Translate the column indices from "local pressure DOF indices" to pressure mirror DOF indices during this step.
For each neighbor, compute the data-mirror of the reduced B-matrix.
Send the reduced B-matrix layouts to the corresponding neighbor processes.
For each neighbor, pre-compute the layout of the neighbor Schur-complement matrix S_k := (D*A*B_k), where B_k is the reduced B-matrix received from that particular neighbor process.
Definition at line 425 of file pmdcdsc_matrix.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm(), FEAT::Adjacency::Graph::get_num_indices(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_row_gate(), FEAT::Adjacency::injectify_sorted, FEAT::Adjacency::injectify_transpose, FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::Layout, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), FEAT::Dist::RequestVector::wait_all(), XASSERT, and XASSERTM.
reset_timings()
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > void FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::reset_timings () inline
Resets the internal stop watches used for collecting timing statistics.
Definition at line 309 of file pmdcdsc_matrix.hpp.
References FEAT::StopWatch::reset().
Member Data Documentation
_data_mirrors
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > std::vector<MirrorTypeP> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_data_mirrors protected
B-matrix data mirrors.
For each neighbor process, this vector stores the indices of all B-matrix entries that have to be send to that particular neighbor process, so that it can pre-compute its neighbor Schur-complement matrix during numeric initialization.
Definition at line 169 of file pmdcdsc_matrix.hpp.
_diagonal_a
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > const GlobalVectorTypeV& FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_diagonal_a protected
the diagonal matrix a (stored as a vector)
Definition at line 107 of file pmdcdsc_matrix.hpp.
_matrix_b
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > const GlobalMatrixTypeB& FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_matrix_b protected
the pressure-gradient matrix B
Definition at line 109 of file pmdcdsc_matrix.hpp.
_matrix_d
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > const GlobalMatrixTypeD& FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_matrix_d protected
the velocity-divergence matrix D
Definition at line 111 of file pmdcdsc_matrix.hpp.
_matrix_da
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > LocalMatrixTypeB FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_matrix_da protected
Pre-Multiplied transposed matrix-product (D*A)^T.
This matrix stores the product (D*A) of the two given input matrices D and A in transposed form, which corresponds to the CSC format rather than the CSR format. As D is assumed to have the transposed layout of B, the layout of this transposed matrix therefore coincides with the layout of B, which also explains why the type of the matrix is LocalMatrixTypeB rather than LocalMatrixTypeD.
This pre-multiplied matrix is required for the efficient numerical assembly of the Neighbor Schur-Matrices, which is performed by the _asm_neighbor_schur_matrix() function. Unfortunately, it does not seem to be possible to implement that assembly without the transpose of D in an efficient way. A previous attempt to implement that numerical assembly without this explicit transpose has lead to a slow-down of factor 20000 (in words: twenty thousand).
Remarks
Although D^T is usually equal to B, we do not want to exploit this here, as we cannot say if the user has modified the D/B matrices in any way, which would break this relation and thus this class would not work correctly.
Just in case that you cannot imagine any case where D != B^T, here you go:
The B-matrix may be filtered due to boundary conditions.
The B-matrix may contain additional terms due to a Newton method applied onto non-newtonian Navier-Stokes equations with pressure-dependent viscosity.
The B-matrix may contain additional stuff like stabilization or penalty terms.
Definition at line 146 of file pmdcdsc_matrix.hpp.
_matrix_s
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > LocalMatrixTypeS FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_matrix_s protected
The local Schur-complement matrix.
This matrix stores the product (D*A*B) restricted onto the patch of this process, i.e. it is simply the product of those three local matrices.
Definition at line 119 of file pmdcdsc_matrix.hpp.
_neighbor_graphs
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > std::vector<Adjacency::Graph> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_neighbor_graphs protected
Neighbor B-matrix adjacency graphs.
For each neighbor process, this vector stores the adjacency graph of the neighbor's B-matrix restricted to the pressure DOFs that this particular neighbor send to us.
Definition at line 177 of file pmdcdsc_matrix.hpp.
_neighbor_matrices
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > std::vector<NeighMatrixTypeS> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_neighbor_matrices protected
Pre-multiplied neighbor Schur-complement matrices.
For each neighbor process, this vector stores the pre-multiplied Schur-complement matrix (D*A*B_k), where B_k is the part of the neighbor's B-matrix, whose rows correlate to the velocity DOFs shared by this process and the neighbor process.
Definition at line 186 of file pmdcdsc_matrix.hpp.
_pres_mirrors
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > std::vector<MirrorTypeP> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_pres_mirrors protected
Pressure DOF mirrors.
For each neighbor process, this mirror stores the indices of all pressure DOFs that have to be send to that particular neighbor process, so that it can perform its matrix-vector product with its corresponding neighbor Schur-complement matrix. This mirror contains all pressure DOFs which are defined on elements which are directly adjacent to the communication halo mesh-part of the neighbor.
Definition at line 160 of file pmdcdsc_matrix.hpp.
_ranks
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > std::vector<int> FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_ranks protected
neighbor process ranks
Definition at line 149 of file pmdcdsc_matrix.hpp.
dim
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > constexpr int FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::dim = dim_ static constexpr
Definition at line 67 of file pmdcdsc_matrix.hpp.
is_global
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > constexpr bool FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::is_global = true static constexpr
Definition at line 102 of file pmdcdsc_matrix.hpp.
is_local
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > constexpr bool FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::is_local = false static constexpr
Definition at line 103 of file pmdcdsc_matrix.hpp.
watch_apply
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_apply mutable protected
total apply time
Definition at line 213 of file pmdcdsc_matrix.hpp.
watch_apply_matrix_loc
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_apply_matrix_loc mutable protected
local Schur-Matrix apply time
Definition at line 215 of file pmdcdsc_matrix.hpp.
watch_apply_neighbor_s
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_apply_neighbor_s mutable protected
neighbor Matrix apply time
Definition at line 217 of file pmdcdsc_matrix.hpp.
watch_init_num_gather_b
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_num_gather_b protected
reduced-B matrix data gather time
Definition at line 206 of file pmdcdsc_matrix.hpp.
watch_init_num_matrix_loc
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_num_matrix_loc protected
local Schur-Matrix numeric assembly time
Definition at line 204 of file pmdcdsc_matrix.hpp.
watch_init_num_neighbor_s
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_num_neighbor_s protected
neighbor Schur-matrix numeric assembly time
Definition at line 210 of file pmdcdsc_matrix.hpp.
watch_init_num_premult_da
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_num_premult_da protected
pre-multiply D*A time
Definition at line 208 of file pmdcdsc_matrix.hpp.
watch_init_numeric
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_numeric protected
total numeric init time
Definition at line 202 of file pmdcdsc_matrix.hpp.
watch_init_sym_data_mirror
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_sym_data_mirror protected
reduced B-matrix data mirror assembly time
Definition at line 197 of file pmdcdsc_matrix.hpp.
watch_init_sym_matrix_loc
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_sym_matrix_loc protected
local Schur-Matrix symbolic assembly time
Definition at line 191 of file pmdcdsc_matrix.hpp.
watch_init_sym_neighbor_s
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_sym_neighbor_s protected
neighbor Schur-Matrix symbolic assembly time
Definition at line 199 of file pmdcdsc_matrix.hpp.
watch_init_sym_pres_mirror
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_sym_pres_mirror protected
pressure mirror assembly time
Definition at line 193 of file pmdcdsc_matrix.hpp.
watch_init_sym_reduced_b
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_sym_reduced_b protected
reduced B-matrix symbolic assembly time
Definition at line 195 of file pmdcdsc_matrix.hpp.
watch_init_symbolic
template<typename DT_ , typename IT_ , int dim_, typename MirrorV_ , typename MirrorP_ > StopWatch FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::watch_init_symbolic protected
total symbolic/numeric init time
Definition at line 189 of file pmdcdsc_matrix.hpp.
The documentation for this class was generated from the following file:
kernel/global/pmdcdsc_matrix.hpp