FEAT: FEAT::Geometry::MeshPart< MeshType_ > Class Template Reference
FEAT::Geometry::MeshPart< MeshType_ > Class Template Reference
Class template for partial meshes.
#include <mesh_part.hpp>
Classes
struct IndexSet
Index set type class template.
struct TargetSet
Target set type class template.
Public Types
typedef MeshType::VertexSetType::CoordType AttributeDataType
Data type for attributes.
typedef AttributeSetContainer::const_iterator AttributeSetConstIterator
submesh node const-iterator type
typedef std::map< String, std::unique_ptr< AttributeSetType > > AttributeSetContainer
submesh node bin container type
typedef AttributeSetContainer::iterator AttributeSetIterator
submesh node iterator type
typedef AttributeSetContainer::reverse_iterator AttributeSetReverseIterator
submesh node reverse-iterator type
typedef AttributeSet< AttributeDataType > AttributeSetType
Type for mesh attributes.
typedef IndexSetHolder< ShapeType > IndexSetHolderType
Index set holder type.
typedef MeshType_ MeshType
parent Mesh type
typedef MeshType::IndexSetHolderType ParentIndexSetHolderType
Topology (aka IndexSetHolder) of parent mesh type.
typedef MeshType::ShapeType ShapeType
Shape type.
typedef TargetSetHolder< ShapeType > TargetSetHolderType
Target set holder type.
Public Member Functions
MeshPart (const Index num_entities[], bool create_topology=false)
Constructor.
MeshPart (const MeshPart &other)=delete
deleted copy constructor
MeshPart (Factory< MeshPart > &factory)
Factory constructor.
MeshPart (MeshPart &&other)=default
move constructor
virtual ~MeshPart ()
Virtual destructor.
virtual bool add_attribute (std::unique_ptr< AttributeSetType > attribute, const String &identifier)
Copies one attribute to this MeshPart's AttributeHolder.
std::size_t bytes () const
MeshPart clone () const
void clone (const MeshPart &other)
Clones another mesh part object into this object.
template<int end_dim_, int current_dim_ = ShapeType::dimension>
void deduct_target_sets_from_bottom (const ParentIndexSetHolderType &parent_ish)
Deducts the target sets from bottom to top.
template<int end_dim_, int current_dim_ = 0>
void deduct_target_sets_from_top (const ParentIndexSetHolderType &parent_ish)
Deducts the target sets from top to bottom.
void deduct_topology (const ParentIndexSetHolderType &parent_ish)
Fills the mesh topology from parent information.
AttributeSetType * find_attribute (const String &identifier)
Finds an Attribute by its identifier String and returns a pointer to it.
const AttributeSetType * find_attribute (const String &identifier) const
Finds an Attribute by its identifier String and returns a pointer to it.
template<int cell_dim_, int face_dim_>
IndexSet< cell_dim_, face_dim_ >::Type & get_index_set ()
Returns the reference to an index set.
template<int cell_dim_, int face_dim_>
const IndexSet< cell_dim_, face_dim_ >::Type & get_index_set () const
Returns the reference to an index set.
const AttributeSetContainer & get_mesh_attributes () const
Returns a const reference to the mesh attributes container.
int get_num_attributes () const
Returns the total number of Attributes in this MeshPart.
Index get_num_entities (int dim) const
Returns the number of entities.
template<int cell_dim_>
TargetSet< cell_dim_ >::Type & get_target_set ()
Return the reference to a target set.
template<int cell_dim_>
const TargetSet< cell_dim_ >::Type & get_target_set () const
Return the reference to a target set.
bool has_topology () const
Checks if this MeshPart has a mesh topology.
MeshPart & operator= (const MeshPart &)=delete
deleted copy-assignment operator
MeshPart & operator= (MeshPart &&other)=default
move-assignment operator
void permute (const MeshPermutation< ShapeType > &mesh_perm)
Applies a mesh permutation onto this mesh part's target sets.
Static Public Member Functions
static String name ()
Returns the name of the class.
Static Public Attributes
static constexpr int shape_dim = ShapeType::dimension
Shape dimension.
Protected Attributes
std::unique_ptr< IndexSetHolderType > _index_set_holder
The index sets of the mesh.
AttributeSetContainer _mesh_attributes
The attribute sets of the mesh.
std::array< Index, shape_dim+1 > _num_entities
Number of entities for each shape dimension.
TargetSetHolderType _target_set_holder
The target sets of the mesh.
Detailed Description
template<typename MeshType_>
class FEAT::Geometry::MeshPart< MeshType_ >
Class template for partial meshes.
A MeshPart is a part of another mesh (called parent mesh) and is defined by mapping its own mesh entities (like vertices, edges etc.) to the corresponding mesh entities of the parent mesh. For at least one arbitrary shape dimension a mapping has to exist, but a MeshPart can have one mapping for each shape dimension of the mesh it refers to.
A MeshPart does not need to be connected or to have a topology, although it can implicitly use the parent's topology. It can have sets of AttributeSets for each shape dimension. If the parent mesh is refine, it is possible to use that information to create a refined version of the MeshPart, although particular care has to be taken when refining the AttributeSets.
A MeshPart can supply its own topology, which can be different from the parent's. One important example for this is a MeshPart that defines the boundary of its parent mesh. If the boundary is parametrized using a AttributeSet and the boundary is closed, the parametrization requires the doubling of some mesh entities to correctly represent the parametrization variable.
*
*   Parent:      MeshPart representing the closed boundary:
*   3----2       0--1--2--3--4
*   |    |         map to
*   |    |       0--1--2--3--0
*   0----1
*
*
Vertex 0 of the parent mesh has two different parametrization variables, as it is both the first and the last vertex of the closed boundary. This can be easily represented by having two vertices in the MeshPart point to the same vertex of the parent mesh.
At least one parent mapping has to be given, but it is possible to deduct the other parent mappings from this. There are two possibilities:
Bottom to top: Starting with the lowest dimensional parent mapping, an entity is considered to be in the MeshPart if all its sub shapes are in the MeshPart, i.e. for a given edge parent mapping in 3d, all faces consisting exclusively of edges in the MeshPart are considered to be in the MeshPart as well. This is then repeated for cells as well.
Top to bottom: Starting with the highest dimensional parent mapping, all subshapes of these entities are considered to be in the MeshPart as well, i.e. for a given face parent mapping in 3d, all edges belonging to faces in the MeshPart are considered to be in the MeshPart as well.
Warning
Extra care has to be taken with this when it comes to refinement when adding higher dimensional parent information. Consider the case of a the parent mesh partitioned into several patches and a MeshPart consisting of two vertices where more than two patches meet. If the mesh is refined, there are still exactly two vertices where more than two patches meet. If by chance those two vertices share an edge in the coarse mesh and bottom to top parent deduction is used, an edge is added to the MeshPart. Refinement of said edge then leads to the addition of a new vertex to the MeshPart, which is correct in terms of mesh topology, but the MeshPart then no longer represents the set of patch cross points.
Note
This template works for both ConformalMesh as well as StructuredMesh meshes.
Author
Jordi Paul
Peter Zajac
Definition at line 89 of file mesh_part.hpp.
Member Typedef Documentation
AttributeDataType
template<typename MeshType_ > typedef MeshType::VertexSetType::CoordType FEAT::Geometry::MeshPart< MeshType_ >::AttributeDataType
Data type for attributes.
Definition at line 133 of file mesh_part.hpp.
AttributeSetConstIterator
template<typename MeshType_ > typedef AttributeSetContainer::const_iterator FEAT::Geometry::MeshPart< MeshType_ >::AttributeSetConstIterator
submesh node const-iterator type
Definition at line 142 of file mesh_part.hpp.
AttributeSetContainer
template<typename MeshType_ > typedef std::map<String, std::unique_ptr<AttributeSetType> > FEAT::Geometry::MeshPart< MeshType_ >::AttributeSetContainer
submesh node bin container type
Definition at line 138 of file mesh_part.hpp.
AttributeSetIterator
template<typename MeshType_ > typedef AttributeSetContainer::iterator FEAT::Geometry::MeshPart< MeshType_ >::AttributeSetIterator
submesh node iterator type
Definition at line 140 of file mesh_part.hpp.
AttributeSetReverseIterator
template<typename MeshType_ > typedef AttributeSetContainer::reverse_iterator FEAT::Geometry::MeshPart< MeshType_ >::AttributeSetReverseIterator
submesh node reverse-iterator type
Definition at line 144 of file mesh_part.hpp.
AttributeSetType
template<typename MeshType_ > typedef AttributeSet<AttributeDataType> FEAT::Geometry::MeshPart< MeshType_ >::AttributeSetType
Type for mesh attributes.
Definition at line 135 of file mesh_part.hpp.
IndexSetHolderType
template<typename MeshType_ > typedef IndexSetHolder<ShapeType> FEAT::Geometry::MeshPart< MeshType_ >::IndexSetHolderType
Index set holder type.
Definition at line 99 of file mesh_part.hpp.
MeshType
template<typename MeshType_ > typedef MeshType_ FEAT::Geometry::MeshPart< MeshType_ >::MeshType
parent Mesh type
Definition at line 93 of file mesh_part.hpp.
ParentIndexSetHolderType
template<typename MeshType_ > typedef MeshType::IndexSetHolderType FEAT::Geometry::MeshPart< MeshType_ >::ParentIndexSetHolderType
Topology (aka IndexSetHolder) of parent mesh type.
Definition at line 97 of file mesh_part.hpp.
ShapeType
template<typename MeshType_ > typedef MeshType::ShapeType FEAT::Geometry::MeshPart< MeshType_ >::ShapeType
Shape type.
Definition at line 95 of file mesh_part.hpp.
TargetSetHolderType
template<typename MeshType_ > typedef TargetSetHolder<ShapeType> FEAT::Geometry::MeshPart< MeshType_ >::TargetSetHolderType
Target set holder type.
Definition at line 101 of file mesh_part.hpp.
Constructor & Destructor Documentation
MeshPart() [1/2]
template<typename MeshType_ > FEAT::Geometry::MeshPart< MeshType_ >::MeshPart (const Index num_entities[], bool create_topology = false) inline explicit
Constructor.
Parameters
[in] num_entities An array of length at least shape_dim + 1 holding the number of entities for each shape dimension. Must not be nullptr.
[in] create_topology Determines if the MeshPart is to have a mesh topology.
Definition at line 183 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder, FEAT::Geometry::MeshPart< MeshType_ >::_num_entities, and FEAT::Geometry::MeshPart< MeshType_ >::shape_dim.
MeshPart() [2/2]
template<typename MeshType_ > FEAT::Geometry::MeshPart< MeshType_ >::MeshPart (Factory< MeshPart< MeshType_ > > & factory) inline explicit
Factory constructor.
Parameters
[in] factory A transient reference to the factory that is to be used to create the mesh part.
Definition at line 201 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder, FEAT::Geometry::MeshPart< MeshType_ >::_mesh_attributes, FEAT::Geometry::MeshPart< MeshType_ >::_num_entities, and FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder.
~MeshPart()
template<typename MeshType_ > virtual FEAT::Geometry::MeshPart< MeshType_ >::~MeshPart () inline virtual
Virtual destructor.
Definition at line 232 of file mesh_part.hpp.
Member Function Documentation
add_attribute()
template<typename MeshType_ > virtual bool FEAT::Geometry::MeshPart< MeshType_ >::add_attribute (std::unique_ptr< AttributeSetType > attribute, const String & identifier) inline virtual
Copies one attribute to this MeshPart's AttributeHolder.
Parameters
[in] attribute A resident pointer to the Attribute to be added.
[in] identifier Identifier for the map.
Returns
True if the attribute was successfully added, meaning no attribute with the appropriate identifier was present, or false otherwise.
Definition at line 374 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_mesh_attributes, and XASSERTM.
Referenced by FEAT::Geometry::MeshPart< MeshType_ >::clone(), and FEAT::Geometry::MeshPartOperations< MeshType_ >::copy_attributes().
bytes()
template<typename MeshType_ > std::size_t FEAT::Geometry::MeshPart< MeshType_ >::bytes () const inline
Returns
The size of dynamically allocated memory in bytes.
Definition at line 280 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder, FEAT::Geometry::MeshPart< MeshType_ >::_mesh_attributes, and FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder.
clone() [1/2]
template<typename MeshType_ > MeshPart FEAT::Geometry::MeshPart< MeshType_ >::clone () const inline
Returns
An independent clone of this mesh part object.
Definition at line 268 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder, FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder, and FEAT::Geometry::MeshPart< MeshType_ >::add_attribute().
clone() [2/2]
template<typename MeshType_ > void FEAT::Geometry::MeshPart< MeshType_ >::clone (const MeshPart< MeshType_ > & other) inline
Clones another mesh part object into this object.
Parameters
[in] other A transient reference to the source object that is to be cloned into this object.
Definition at line 243 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::add_attribute(), and FEAT::Geometry::other.
deduct_target_sets_from_bottom()
template<typename MeshType_ > template<int end_dim_, int current_dim_ = ShapeType::dimension> void FEAT::Geometry::MeshPart< MeshType_ >::deduct_target_sets_from_bottom (const ParentIndexSetHolderType & parent_ish) inline
Deducts the target sets from bottom to top.
Template Parameters
end_dim_ Dimension to stop at (meaning the lowest dimension).
current_dim_ Dimension to generate parent information for.
Parameters
[in] parent_ish A transient reference to the topology of the parent this MeshPart refers to.
Warning
This will in general change the implied topology of the MeshPart and is meant to be used in mesh preprocessing only.
Definition at line 504 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_num_entities, and FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder.
deduct_target_sets_from_top()
template<typename MeshType_ > template<int end_dim_, int current_dim_ = 0> void FEAT::Geometry::MeshPart< MeshType_ >::deduct_target_sets_from_top (const ParentIndexSetHolderType & parent_ish) inline
Deducts the target sets from top to bottom.
Template Parameters
end_dim_ Dimension to stop at (meaning the highest dimension).
current_dim_ Dimension to generate parent information for.
Parameters
[in] parent_ish A transient reference to the topology of the parent this MeshPart refers to.
Warning
This will in general change the implied topology of the MeshPart and is meant to be used in mesh preprocessing only.
Definition at line 529 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_num_entities, and FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder.
deduct_topology()
template<typename MeshType_ > void FEAT::Geometry::MeshPart< MeshType_ >::deduct_topology (const ParentIndexSetHolderType & parent_ish) inline
Fills the mesh topology from parent information.
Parameters
[in] parent_ish A transient reference to the IndexSetHolder of the parent this MeshPart refers to.
Warning
This will in general change the implied topology of the MeshPart and is meant to be used in mesh preprocessing only.
Definition at line 547 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder, FEAT::Geometry::MeshPart< MeshType_ >::_num_entities, FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder, and FEAT::Geometry::RedundantIndexSetBuilder< Shape_ >::compute().
Referenced by FEAT::Geometry::MeshNodeLinker< RootMesh_ >::execute().
find_attribute() [1/2]
template<typename MeshType_ > AttributeSetType * FEAT::Geometry::MeshPart< MeshType_ >::find_attribute (const String & identifier) inline
Finds an Attribute by its identifier String and returns a pointer to it.
Parameters
[in] identifier Identifier to match.
Returns
A pointer to the Attribute of shape dimension dim if present.
Warning
Will return nullptr if no Attribute with the given identifier is found
Definition at line 328 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_mesh_attributes.
find_attribute() [2/2]
template<typename MeshType_ > const AttributeSetType * FEAT::Geometry::MeshPart< MeshType_ >::find_attribute (const String & identifier) const inline
Finds an Attribute by its identifier String and returns a pointer to it.
Parameters
[in] identifier Identifier to match.
Returns
A pointer to the Attribute of shape dimension dim if present.
Warning
Will return nullptr if no Attribute with the given identifier is found
Definition at line 335 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_mesh_attributes.
get_index_set() [1/2]
template<typename MeshType_ > template<int cell_dim_, int face_dim_> IndexSet< cell_dim_, face_dim_ >::Type & FEAT::Geometry::MeshPart< MeshType_ >::get_index_set () inline
Returns the reference to an index set.
Template Parameters
cell_dim_ The dimension of the entity whose index set is to be returned.
face_dim_ The dimension of the face that the index set refers to.
Returns
A reference to the index set.
Definition at line 394 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder, FEAT::Geometry::MeshPart< MeshType_ >::has_topology(), and XASSERTM.
get_index_set() [2/2]
template<typename MeshType_ > template<int cell_dim_, int face_dim_> const IndexSet< cell_dim_, face_dim_ >::Type & FEAT::Geometry::MeshPart< MeshType_ >::get_index_set () const inline
Returns the reference to an index set.
Template Parameters
cell_dim_ The dimension of the entity whose index set is to be returned.
face_dim_ The dimension of the face that the index set refers to.
Returns
A reference to the index set.
Definition at line 402 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder, FEAT::Geometry::MeshPart< MeshType_ >::has_topology(), and XASSERTM.
get_mesh_attributes()
template<typename MeshType_ > const AttributeSetContainer & FEAT::Geometry::MeshPart< MeshType_ >::get_mesh_attributes () const inline
Returns a const reference to the mesh attributes container.
Returns
A const reference to the mesh attributes container
Definition at line 346 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_mesh_attributes.
Referenced by FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::build(), FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::fill_attribute_sets(), and FEAT::Geometry::MeshFileWriter::write_meshpart().
get_num_attributes()
template<typename MeshType_ > int FEAT::Geometry::MeshPart< MeshType_ >::get_num_attributes () const inline
Returns the total number of Attributes in this MeshPart.
Returns
The total number of Attributes.
Definition at line 356 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_mesh_attributes.
get_num_entities()
template<typename MeshType_ > Index FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities (int dim) const inline
Returns the number of entities.
Parameters
[in] dim The dimension of the entity whose count is to be returned. Must be 0 <= dim <= shape_dim.
Returns
The number of entities of dimension dim.
Definition at line 311 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_num_entities, FEAT::Geometry::MeshPart< MeshType_ >::shape_dim, and XASSERT.
Referenced by FEAT::Geometry::MeshPartExtruderFactory< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::MeshPartExtruderFactory(), FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::StandardRefinery(), FEAT::Geometry::MeshPartOperations< MeshType_ >::copy_attributes(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_meshpart(), FEAT::Geometry::Atlas::Circle< Mesh_ >::project_meshpart(), FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_meshpart(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_meshpart(), and FEAT::Geometry::MeshFileWriter::write_meshpart().
get_target_set() [1/2]
template<typename MeshType_ > template<int cell_dim_> TargetSet< cell_dim_ >::Type & FEAT::Geometry::MeshPart< MeshType_ >::get_target_set () inline
Return the reference to a target set.
Template Parameters
cell_dim_ The dimension of the entity whose target set is to be returned.
Returns
A reference to the target set.
Definition at line 433 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder, and FEAT::Geometry::MeshPart< MeshType_ >::shape_dim.
get_target_set() [2/2]
template<typename MeshType_ > template<int cell_dim_> const TargetSet< cell_dim_ >::Type & FEAT::Geometry::MeshPart< MeshType_ >::get_target_set () const inline
Return the reference to a target set.
Template Parameters
cell_dim_ The dimension of the entity whose target set is to be returned.
Returns
A reference to the target set.
Definition at line 442 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder, and FEAT::Geometry::MeshPart< MeshType_ >::shape_dim.
has_topology()
template<typename MeshType_ > bool FEAT::Geometry::MeshPart< MeshType_ >::has_topology () const inline
Checks if this MeshPart has a mesh topology.
Definition at line 297 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::ExportVTK(), FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::fill_attribute_sets(), FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::fill_index_sets(), FEAT::Geometry::MeshPart< MeshType_ >::get_index_set(), and FEAT::Geometry::MeshFileWriter::write_meshpart().
name()
template<typename MeshType_ > static String FEAT::Geometry::MeshPart< MeshType_ >::name () inline static
Returns the name of the class.
Returns
The name of the class as a String.
Definition at line 472 of file mesh_part.hpp.
permute()
template<typename MeshType_ > void FEAT::Geometry::MeshPart< MeshType_ >::permute (const MeshPermutation< ShapeType > & mesh_perm) inline
Applies a mesh permutation onto this mesh part's target sets.
Parameters
[in] mesh_perm A transient reference to the mesh permutation that is to be applied.
Definition at line 483 of file mesh_part.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::get_inv_perms().
Member Data Documentation
_index_set_holder
template<typename MeshType_ > std::unique_ptr<IndexSetHolderType> FEAT::Geometry::MeshPart< MeshType_ >::_index_set_holder protected
The index sets of the mesh.
Definition at line 166 of file mesh_part.hpp.
Referenced by FEAT::Geometry::MeshPart< MeshType_ >::MeshPart(), FEAT::Geometry::MeshPart< MeshType_ >::bytes(), FEAT::Geometry::MeshPart< MeshType_ >::clone(), FEAT::Geometry::MeshPart< MeshType_ >::deduct_topology(), FEAT::Geometry::MeshPart< MeshType_ >::get_index_set(), and FEAT::Geometry::MeshPart< MeshType_ >::has_topology().
_mesh_attributes
template<typename MeshType_ > AttributeSetContainer FEAT::Geometry::MeshPart< MeshType_ >::_mesh_attributes protected
The attribute sets of the mesh.
Definition at line 170 of file mesh_part.hpp.
Referenced by FEAT::Geometry::MeshPart< MeshType_ >::MeshPart(), FEAT::Geometry::MeshPart< MeshType_ >::add_attribute(), FEAT::Geometry::MeshPart< MeshType_ >::bytes(), FEAT::Geometry::MeshPart< MeshType_ >::find_attribute(), FEAT::Geometry::MeshPart< MeshType_ >::get_mesh_attributes(), and FEAT::Geometry::MeshPart< MeshType_ >::get_num_attributes().
_num_entities
template<typename MeshType_ > std::array<Index, shape_dim + 1> FEAT::Geometry::MeshPart< MeshType_ >::_num_entities protected
Number of entities for each shape dimension.
Definition at line 164 of file mesh_part.hpp.
Referenced by FEAT::Geometry::MeshPart< MeshType_ >::MeshPart(), FEAT::Geometry::MeshPart< MeshType_ >::deduct_target_sets_from_bottom(), FEAT::Geometry::MeshPart< MeshType_ >::deduct_target_sets_from_top(), FEAT::Geometry::MeshPart< MeshType_ >::deduct_topology(), and FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities().
_target_set_holder
template<typename MeshType_ > TargetSetHolderType FEAT::Geometry::MeshPart< MeshType_ >::_target_set_holder protected
The target sets of the mesh.
Definition at line 168 of file mesh_part.hpp.
Referenced by FEAT::Geometry::MeshPart< MeshType_ >::MeshPart(), FEAT::Geometry::MeshPart< MeshType_ >::bytes(), FEAT::Geometry::MeshPart< MeshType_ >::clone(), FEAT::Geometry::MeshPart< MeshType_ >::deduct_target_sets_from_bottom(), FEAT::Geometry::MeshPart< MeshType_ >::deduct_target_sets_from_top(), FEAT::Geometry::MeshPart< MeshType_ >::deduct_topology(), and FEAT::Geometry::MeshPart< MeshType_ >::get_target_set().
shape_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::MeshPart< MeshType_ >::shape_dim = ShapeType::dimension static constexpr
Shape dimension.
Definition at line 103 of file mesh_part.hpp.
Referenced by FEAT::Geometry::MeshPart< MeshType_ >::MeshPart(), FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities(), and FEAT::Geometry::MeshPart< MeshType_ >::get_target_set().
The documentation for this class was generated from the following file:
kernel/geometry/mesh_part.hpp