FEAT: FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ > Class Template Reference
FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ > Class Template Reference
Public Types
typedef DataType_ DataType
typedef Global::Matrix< LocalSystemMatrix, SystemMirror, SystemMirror > GlobalSystemMatrix
define global system matrix type
typedef Global::Transfer< LocalSystemTransfer, SystemMirror > GlobalSystemTransfer
define global system operator type
typedef Global::Vector< LocalSystemVector, SystemMirror > GlobalSystemVector
define global system vector type
typedef IndexType_ IndexType
typedef BlockedMatrix_ LocalBlockedMatrix
define local blocked matrix type
typedef BlockedMatrix_ LocalSystemMatrix
define local system matrix type
typedef LAFEM::Transfer< LocalSystemTransferMatrix > LocalSystemTransfer
define local system transfer operator type
typedef TransferMatrix_ LocalSystemTransferMatrix
define local transfer matrix type
typedef LocalSystemMatrix::VectorTypeR LocalSystemVector
define local system vector type
typedef Global::Gate< LocalSystemVector, SystemMirror > SystemGate
define system gate
typedef LAFEM::VectorMirror< DataType, IndexType > SystemMirror
define system mirror type
typedef Global::Muxer< LocalSystemVector, SystemMirror > SystemMuxer
Public Member Functions
BlockedBasicSystemLevel ()
CTOR.
template<typename DomainLevel_ >
void assemble_coarse_muxer (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse)
template<typename DomainLevel_ >
void assemble_gate (const Domain::VirtualLevel< DomainLevel_ > &virt_dom_lvl)
template<typename DomainLevel_ , typename Cubature_ >
void assemble_transfer (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse, const Cubature_ &cubature)
template<typename DomainLevel_ , typename Cubature_ >
void assemble_truncation (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse, const Cubature_ &cubature, const BlockedBasicSystemLevel *sys_lvl_coarse=nullptr)
std::size_t bytes () const
Returns the total amount of bytes allocated.
template<typename M_ , typename D_ , typename I_ , typename SM_ >
void convert (const BlockedBasicSystemLevel< dim_, M_, D_, I_, SM_ > &other)
Public Attributes
SystemMuxer coarse_muxer_sys
our coarse-level system muxer
SystemGate gate_sys
our system gate
GlobalSystemMatrix matrix_sys
our global system matrix
GlobalSystemTransfer transfer_sys
our global transfer operator
Static Public Attributes
static constexpr int dim = dim_
Detailed Description
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>>
class FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >
Definition at line 38 of file blocked_basic.hpp.
Member Typedef Documentation
DataType
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef DataType_ FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::DataType
Definition at line 45 of file blocked_basic.hpp.
GlobalSystemMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef Global::Matrix<LocalSystemMatrix, SystemMirror, SystemMirror> FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::GlobalSystemMatrix
define global system matrix type
Definition at line 77 of file blocked_basic.hpp.
GlobalSystemTransfer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef Global::Transfer<LocalSystemTransfer, SystemMirror> FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::GlobalSystemTransfer
define global system operator type
Definition at line 80 of file blocked_basic.hpp.
GlobalSystemVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef Global::Vector<LocalSystemVector, SystemMirror> FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::GlobalSystemVector
define global system vector type
Definition at line 74 of file blocked_basic.hpp.
IndexType
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef IndexType_ FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::IndexType
Definition at line 46 of file blocked_basic.hpp.
LocalBlockedMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef BlockedMatrix_ FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::LocalBlockedMatrix
define local blocked matrix type
Definition at line 50 of file blocked_basic.hpp.
LocalSystemMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef BlockedMatrix_ FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::LocalSystemMatrix
define local system matrix type
Definition at line 53 of file blocked_basic.hpp.
LocalSystemTransfer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef LAFEM::Transfer<LocalSystemTransferMatrix> FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::LocalSystemTransfer
define local system transfer operator type
Definition at line 62 of file blocked_basic.hpp.
LocalSystemTransferMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef TransferMatrix_ FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::LocalSystemTransferMatrix
define local transfer matrix type
Definition at line 56 of file blocked_basic.hpp.
LocalSystemVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef LocalSystemMatrix::VectorTypeR FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::LocalSystemVector
define local system vector type
Definition at line 59 of file blocked_basic.hpp.
SystemGate
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef Global::Gate<LocalSystemVector, SystemMirror> FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::SystemGate
define system gate
Definition at line 68 of file blocked_basic.hpp.
SystemMirror
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef LAFEM::VectorMirror<DataType, IndexType> FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::SystemMirror
define system mirror type
Definition at line 65 of file blocked_basic.hpp.
SystemMuxer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> typedef Global::Muxer<LocalSystemVector, SystemMirror> FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::SystemMuxer
Definition at line 71 of file blocked_basic.hpp.
Constructor & Destructor Documentation
BlockedBasicSystemLevel()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::BlockedBasicSystemLevel () inline
CTOR.
Definition at line 97 of file blocked_basic.hpp.
~BlockedBasicSystemLevel()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> virtual FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::~BlockedBasicSystemLevel () inline virtual
Definition at line 103 of file blocked_basic.hpp.
Member Function Documentation
assemble_coarse_muxer()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> template<typename DomainLevel_ > void FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::assemble_coarse_muxer (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse) inline
Definition at line 158 of file blocked_basic.hpp.
assemble_gate()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> template<typename DomainLevel_ > void FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::assemble_gate (const Domain::VirtualLevel< DomainLevel_ > & virt_dom_lvl) inline
Definition at line 124 of file blocked_basic.hpp.
assemble_transfer()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> template<typename DomainLevel_ , typename Cubature_ > void FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::assemble_transfer (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse, const Cubature_ & cubature) inline
Definition at line 206 of file blocked_basic.hpp.
assemble_truncation()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> template<typename DomainLevel_ , typename Cubature_ > void FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::assemble_truncation (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse, const Cubature_ & cubature, const BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ > * sys_lvl_coarse = nullptr) inline
Definition at line 277 of file blocked_basic.hpp.
bytes()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> std::size_t FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 108 of file blocked_basic.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::bytes(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::bytes(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::bytes(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local().
Referenced by FEAT::Control::BlockedUnitFilterSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::bytes().
convert()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> template<typename M_ , typename D_ , typename I_ , typename SM_ > void FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::convert (const BlockedBasicSystemLevel< dim_, M_, D_, I_, SM_ > & other) inline
Definition at line 115 of file blocked_basic.hpp.
Member Data Documentation
coarse_muxer_sys
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> SystemMuxer FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::coarse_muxer_sys
our coarse-level system muxer
Definition at line 88 of file blocked_basic.hpp.
dim
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> constexpr int FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::dim = dim_ static constexpr
Definition at line 47 of file blocked_basic.hpp.
gate_sys
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> SystemGate FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::gate_sys
our system gate
Definition at line 85 of file blocked_basic.hpp.
matrix_sys
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> GlobalSystemMatrix FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::matrix_sys
our global system matrix
Definition at line 91 of file blocked_basic.hpp.
transfer_sys
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename BlockedMatrix_ = LAFEM::SparseMatrixBCSR<DataType_, IndexType_, dim_, dim_>, typename TransferMatrix_ = LAFEM::SparseMatrixBWrappedCSR<DataType_, IndexType_, dim_>> GlobalSystemTransfer FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::transfer_sys
our global transfer operator
Definition at line 94 of file blocked_basic.hpp.
The documentation for this class was generated from the following file:
control/blocked_basic.hpp