FEAT: FEAT::LAFEM::MatrixMirror< DT_, IT_ > Class Template Reference
FEAT::LAFEM::MatrixMirror< DT_, IT_ > Class Template Reference
Matrix-Mirror class template.
#include <matrix_mirror.hpp>
Public Types
typedef DT_ DataType
data-type typedef
typedef IT_ IndexType
index-type typedef
typedef LAFEM::VectorMirror< DT_, IT_ > VectorMirrorType
vector mirror type
Public Member Functions
MatrixMirror (const VectorMirrorType &row_mirror, const VectorMirrorType &col_mirror)
Constructor.
MatrixMirror (MatrixMirror &&other)
move constructor
virtual ~MatrixMirror ()
virtual destructor
LAFEM::MatrixMirrorBuffer< DT_, IT_ > create_buffer (const LAFEM::SparseMatrixBanded< DT_, IT_ > &matrix) const
Creates a buffer matrix based on a banded template matrix.
template<int bw_, int bh_>
LAFEM::MatrixMirrorBuffer< DT_, IT_ > create_buffer (const LAFEM::SparseMatrixBCSR< DT_, IT_, bw_, bh_ > &matrix) const
Creates a buffer matrix based on a BCSR template matrix.
LAFEM::MatrixMirrorBuffer< DT_, IT_ > create_buffer (const LAFEM::SparseMatrixCSR< DT_, IT_ > &matrix) const
Creates a buffer matrix based on a CSR template matrix.
template<int bw_, int bh_>
void gather (LAFEM::MatrixMirrorBuffer< DT_, IT_ > &buffer, const LAFEM::SparseMatrixBCSR< DT_, IT_, bw_, bh_ > &matrix) const
Performs a gather-operation on an operator matrix.
void gather (LAFEM::MatrixMirrorBuffer< DT_, IT_ > &buffer, const LAFEM::SparseMatrixCSR< DT_, IT_ > &matrix) const
Performs a gather-operation on an operator matrix.
const VectorMirrorType & get_col_mirror () const
const VectorMirrorType & get_row_mirror () const
template<int bw_, int bh_>
void scatter_axpy (LAFEM::SparseMatrixBCSR< DT_, IT_, bw_, bh_ > &matrix, const LAFEM::MatrixMirrorBuffer< DT_, IT_ > &buffer, const DT_ alpha=DT_(1)) const
Performs a scatter-axpy-operation on an operator matrix.
void scatter_axpy (LAFEM::SparseMatrixCSR< DT_, IT_ > &matrix, const LAFEM::MatrixMirrorBuffer< DT_, IT_ > &buffer, const DT_ alpha=DT_(1)) const
Performs a scatter-axpy-operation on an operator matrix.
Protected Member Functions
template<typename MT_ >
Adjacency::Graph _create_buffer_graph (const MT_ &tmpl_mat) const
Protected Attributes
const VectorMirrorType & _col_mirror
col-mirror reference
const VectorMirrorType & _row_mirror
row-mirror reference
Detailed Description
template<typename DT_, typename IT_>
class FEAT::LAFEM::MatrixMirror< DT_, IT_ >
Matrix-Mirror class template.
Todo:
reimplement operations for SparseMatrixBanded
Author
Peter Zajac
Definition at line 32 of file matrix_mirror.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ > typedef DT_ FEAT::LAFEM::MatrixMirror< DT_, IT_ >::DataType
data-type typedef
Definition at line 36 of file matrix_mirror.hpp.
IndexType
template<typename DT_ , typename IT_ > typedef IT_ FEAT::LAFEM::MatrixMirror< DT_, IT_ >::IndexType
index-type typedef
Definition at line 38 of file matrix_mirror.hpp.
VectorMirrorType
template<typename DT_ , typename IT_ > typedef LAFEM::VectorMirror<DT_, IT_> FEAT::LAFEM::MatrixMirror< DT_, IT_ >::VectorMirrorType
vector mirror type
Definition at line 40 of file matrix_mirror.hpp.
Constructor & Destructor Documentation
MatrixMirror() [1/2]
template<typename DT_ , typename IT_ > FEAT::LAFEM::MatrixMirror< DT_, IT_ >::MatrixMirror (const VectorMirrorType & row_mirror, const VectorMirrorType & col_mirror) inline explicit
Constructor.
Parameters
[in] row_mirror A reference to the vector-mirror for the rows, assembled on the test space.
[in] col_mirror A reference to the vector-mirror for the columns, assembled on the trial space.
Definition at line 58 of file matrix_mirror.hpp.
MatrixMirror() [2/2]
template<typename DT_ , typename IT_ > FEAT::LAFEM::MatrixMirror< DT_, IT_ >::MatrixMirror (MatrixMirror< DT_, IT_ > && other) inline
move constructor
Definition at line 65 of file matrix_mirror.hpp.
~MatrixMirror()
template<typename DT_ , typename IT_ > virtual FEAT::LAFEM::MatrixMirror< DT_, IT_ >::~MatrixMirror () inline virtual
virtual destructor
Definition at line 72 of file matrix_mirror.hpp.
Member Function Documentation
_create_buffer_graph()
template<typename DT_ , typename IT_ > template<typename MT_ > Adjacency::Graph FEAT::LAFEM::MatrixMirror< DT_, IT_ >::_create_buffer_graph (const MT_ & tmpl_mat) const inline protected
Definition at line 618 of file matrix_mirror.hpp.
create_buffer() [1/3]
template<typename DT_ , typename IT_ > LAFEM::MatrixMirrorBuffer< DT_, IT_ > FEAT::LAFEM::MatrixMirror< DT_, IT_ >::create_buffer (const LAFEM::SparseMatrixBanded< DT_, IT_ > & matrix) const inline
Creates a buffer matrix based on a banded template matrix.
Parameters
[in] matrix A reference to the template matrix. Its structure must be initialized, but the numerical content is ignored
Returns
A matrix buffer of the same data- and index-type as the template matrix.
Definition at line 131 of file matrix_mirror.hpp.
create_buffer() [2/3]
template<typename DT_ , typename IT_ > template<int bw_, int bh_> LAFEM::MatrixMirrorBuffer< DT_, IT_ > FEAT::LAFEM::MatrixMirror< DT_, IT_ >::create_buffer (const LAFEM::SparseMatrixBCSR< DT_, IT_, bw_, bh_ > & matrix) const inline
Creates a buffer matrix based on a BCSR template matrix.
Parameters
[in] matrix A reference to the template matrix. Its structure must be initialized, but the numerical content is ignored
Returns
A matrix buffer of the same data- and index-type as the template matrix.
Definition at line 99 of file matrix_mirror.hpp.
create_buffer() [3/3]
template<typename DT_ , typename IT_ > LAFEM::MatrixMirrorBuffer< DT_, IT_ > FEAT::LAFEM::MatrixMirror< DT_, IT_ >::create_buffer (const LAFEM::SparseMatrixCSR< DT_, IT_ > & matrix) const inline
Creates a buffer matrix based on a CSR template matrix.
Parameters
[in] matrix A reference to the template matrix. Its structure must be initialized, but the numerical content is ignored
Returns
A matrix buffer of the same data- and index-type as the template matrix.
Definition at line 115 of file matrix_mirror.hpp.
gather() [1/2]
template<typename DT_ , typename IT_ > template<int bw_, int bh_> void FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather (LAFEM::MatrixMirrorBuffer< DT_, IT_ > & buffer, const LAFEM::SparseMatrixBCSR< DT_, IT_, bw_, bh_ > & matrix) const inline
Performs a gather-operation on an operator matrix.
Parameters
[in,out] buffer A reference to the buffer matrix.
[in] matrix A reference to the operator matrix whose entries are to be gathered.
Definition at line 270 of file matrix_mirror.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and XASSERT.
gather() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather (LAFEM::MatrixMirrorBuffer< DT_, IT_ > & buffer, const LAFEM::SparseMatrixCSR< DT_, IT_ > & matrix) const inline
Performs a gather-operation on an operator matrix.
Parameters
[in,out] buffer A reference to the buffer matrix.
[in] matrix A reference to the operator matrix whose entries are to be gathered.
Definition at line 146 of file matrix_mirror.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERT.
get_col_mirror()
template<typename DT_ , typename IT_ > const VectorMirrorType & FEAT::LAFEM::MatrixMirror< DT_, IT_ >::get_col_mirror () const inline
Returns
A reference to the internal column vector-mirror.
Definition at line 83 of file matrix_mirror.hpp.
References FEAT::LAFEM::MatrixMirror< DT_, IT_ >::_col_mirror.
get_row_mirror()
template<typename DT_ , typename IT_ > const VectorMirrorType & FEAT::LAFEM::MatrixMirror< DT_, IT_ >::get_row_mirror () const inline
Returns
A reference to the internal row vector-mirror.
Definition at line 77 of file matrix_mirror.hpp.
References FEAT::LAFEM::MatrixMirror< DT_, IT_ >::_row_mirror.
scatter_axpy() [1/2]
template<typename DT_ , typename IT_ > template<int bw_, int bh_> void FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy (LAFEM::SparseMatrixBCSR< DT_, IT_, bw_, bh_ > & matrix, const LAFEM::MatrixMirrorBuffer< DT_, IT_ > & buffer, const DT_ alpha = DT_(1)) const inline
Performs a scatter-axpy-operation on an operator matrix.
Parameters
[in,out] matrix A reference to the operator matrix.
[in] buffer A reference to the buffer matrix whose entries are to be scattered.
[in] alpha The scaling factor for the operation.
Definition at line 337 of file matrix_mirror.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and XASSERT.
scatter_axpy() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy (LAFEM::SparseMatrixCSR< DT_, IT_ > & matrix, const LAFEM::MatrixMirrorBuffer< DT_, IT_ > & buffer, const DT_ alpha = DT_(1)) const inline
Performs a scatter-axpy-operation on an operator matrix.
Parameters
[in,out] matrix A reference to the operator matrix.
[in] buffer A reference to the buffer matrix whose entries are to be scattered.
[in] alpha The scaling factor for the operation.
Definition at line 210 of file matrix_mirror.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERT.
Member Data Documentation
_col_mirror
template<typename DT_ , typename IT_ > const VectorMirrorType& FEAT::LAFEM::MatrixMirror< DT_, IT_ >::_col_mirror protected
col-mirror reference
Definition at line 46 of file matrix_mirror.hpp.
Referenced by FEAT::LAFEM::MatrixMirror< DT_, IT_ >::get_col_mirror().
_row_mirror
template<typename DT_ , typename IT_ > const VectorMirrorType& FEAT::LAFEM::MatrixMirror< DT_, IT_ >::_row_mirror protected
row-mirror reference
Definition at line 44 of file matrix_mirror.hpp.
Referenced by FEAT::LAFEM::MatrixMirror< DT_, IT_ >::get_row_mirror().
The documentation for this class was generated from the following files:
kernel/lafem/forward.hpp
kernel/lafem/matrix_mirror.hpp