FEAT: FEAT::Assembly::VectorErrorComputer< max_norm_ > Class Template Reference
FEAT::Assembly::VectorErrorComputer< max_norm_ > Class Template Reference
Vector H0/H1/H2-error computer class template.
#include <error_computer.hpp>
Static Public Member Functions
template<typename Vector_ , typename Function_ , typename Space_ , typename CubatureFactory_ >
static VectorErrorInfo< typename Vector_::DataType, Function_::ImageType::scalar_components > compute (const Vector_ &vector, const Function_ &function, const Space_ &space, const CubatureFactory_ &cubature_factory)
Computes the H0/H1/H2-error.
Detailed Description
template<int max_norm_ = 0>
class FEAT::Assembly::VectorErrorComputer< max_norm_ >
Vector H0/H1/H2-error computer class template.
This class template implements the computation of errors between a finite element function and an analytic reference function in the H0-norm as well as the H1- and H2-semi-norms, if desired.
Template Parameters
max_norm_ Specifies the maximal H^k-semi-norm in which the error is to be measured:
max_norm_ = 0: compute only H0-norm of error
max_norm_ = 1: compute H0-norm and H1-semi-norm of error
max_norm_ = 2: compute H0-norm, H1- and H2-semi-norms of error
Attention
To compute the H1- and H2-semi-norms of the error, both the analytic reference function as well as the finite element space need to be able to compute gradients and hessians, respectively.
Author
Peter Zajac
Definition at line 1008 of file error_computer.hpp.
Member Function Documentation
compute()
template<int max_norm_ = 0> template<typename Vector_ , typename Function_ , typename Space_ , typename CubatureFactory_ > static VectorErrorInfo< typename Vector_::DataType, Function_::ImageType::scalar_components > FEAT::Assembly::VectorErrorComputer< max_norm_ >::compute (const Vector_ & vector, const Function_ & function, const Space_ & space, const CubatureFactory_ & cubature_factory) inline static
Computes the H0/H1/H2-error.
This function computes the norm of the difference of a discrete Finite-Element function and an analytic function in the H0, H1 and H2 semi-norms, depending on the template argument of this class.
Parameters
[in] vector The transient coefficient vector of the FE function.
[in] function A transient reference to an object implementing the AnalyticFunction interface representing the analytic function to be tested against.
[in] space The transient Finite-Element space that the coefficient vector belongs to.
[in] cubature_factory A reference to the cubature factory to be used for integration.
Returns
A VectorErrorInfo object which contains the H0-, H1- and H2-error (semi-)norms.
The domain dim
We use the scalar assembly traits and just define our own LocalVectorData below
Definition at line 1057 of file error_computer.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::axpy(), FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::have_h0, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::have_h1, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::have_h2, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::have_l1, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::have_lmax, FEAT::Math::max(), FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_h0, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_h0_comp, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_h1, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_h1_comp, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_h2, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_h2_comp, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_l1, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_l1_comp, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_lmax, FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::norm_lmax_comp, FEAT::Math::sqr(), FEAT::Math::sqrt(), and XASSERTM.
The documentation for this class was generated from the following file:
kernel/assembly/error_computer.hpp