FEAT: FEAT::Assembly::MirrorAssembler Class Reference
FEAT::Assembly::MirrorAssembler Class Reference
Dof-Mirror assembler class template.
#include <mirror_assembler.hpp>
Static Public Member Functions
template<typename DataType_ , typename IndexType_ , Index blocks_, typename Space_ , typename MeshPart_ >
static void assemble_mirror (LAFEM::PowerMirror< LAFEM::VectorMirror< DataType_, IndexType_ >, blocks_ > &vec_mirror, const Space_ &space, const MeshPart_ &mesh_part)
template<typename DataType_ , typename IndexType_ , typename Space_ , typename MeshPart_ >
static void assemble_mirror (LAFEM::VectorMirror< DataType_, IndexType_ > &vec_mirror, const Space_ &space, const MeshPart_ &mesh_part)
Assembles a VectorMirror from a space and a mesh-part.
Detailed Description
Dof-Mirror assembler class template.
Author
Peter Zajac
Definition at line 134 of file mirror_assembler.hpp.
Member Function Documentation
assemble_mirror() [1/2]
template<typename DataType_ , typename IndexType_ , Index blocks_, typename Space_ , typename MeshPart_ > static void FEAT::Assembly::MirrorAssembler::assemble_mirror (LAFEM::PowerMirror< LAFEM::VectorMirror< DataType_, IndexType_ >, blocks_ > & vec_mirror, const Space_ & space, const MeshPart_ & mesh_part) inline static
Definition at line 177 of file mirror_assembler.hpp.
assemble_mirror() [2/2]
template<typename DataType_ , typename IndexType_ , typename Space_ , typename MeshPart_ > static void FEAT::Assembly::MirrorAssembler::assemble_mirror (LAFEM::VectorMirror< DataType_, IndexType_ > & vec_mirror, const Space_ & space, const MeshPart_ & mesh_part) inline static
Assembles a VectorMirror from a space and a mesh-part.
Parameters
[out] vec_mirror A transient reference to the vector mirror that is to be assembled.
[in] space A transient reference to the finite element space to be used.
[in] mesh_part A transient reference to the mesh-part that is to be mirrored.
Definition at line 154 of file mirror_assembler.hpp.
References FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices().
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates(), and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_gates().
The documentation for this class was generated from the following file:
kernel/assembly/mirror_assembler.hpp