FEAT: FEAT::LAFEM::PowerMirror< SubMirror_, count_ > Class Template Reference
FEAT::LAFEM::PowerMirror< SubMirror_, count_ > Class Template Reference
PowerVector meta-mirror class template.
#include <power_mirror.hpp>
Public Types
typedef SubMirrorType::DataType DataType
sub-mirror data-type
typedef SubMirrorType::IndexType IndexType
sub-mirror index-type
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using MirrorType = PowerMirror< typename SubMirrorType::template MirrorType< DT2_, IT2_ >, count_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using MirrorTypeByDI = MirrorType< DataType2_, IndexType2_ >
this typedef lets you create a mirror with new Data and Index types
typedef SubMirror_ SubMirrorType
sub-mirror type
Public Member Functions
PowerMirror ()
default ctor
PowerMirror (PowerMirror &&other)
move-ctor
PowerMirror (SubMirrorType &&sub_mirror)
sub-mirror move-ctor
template<int i_>
SubMirrorType & at ()
Returns a sub-mirror block.
template<int i_>
const SubMirrorType & at () const
Returns a sub-mirror block.
template<typename SubVector_ >
Index buffer_size (const PowerVector< SubVector_, count_ > &vector) const
Computes the required buffer size for a PowerVector.
std::size_t bytes () const
Returns the total amount of bytes allocated.
PowerMirror clone (CloneMode clone_mode=CloneMode::Weak) const
Clone operation.
template<typename SubMirror2_ >
void convert (const PowerMirror< SubMirror2_, count_ > &other)
Conversion method.
template<typename SubVector_ >
DenseVector< DataType, IndexType > create_buffer (const PowerVector< SubVector_, count_ > &vector) const
Creates a new buffer vector for a PowerVector.
bool empty () const
Checks whether the mirror is empty.
template<typename Tv_ >
void gather (LAFEM::DenseVector< DataType, IndexType > &buffer, const LAFEM::PowerVector< Tv_, count_ > &vector, const Index buffer_offset=Index(0)) const
Gathers the buffer entries from a DenseVector.
SubMirrorType & get (int i)
Returns a sub-mirror block.
const SubMirrorType & get (int i) const
Returns a sub-mirror block.
template<Perspective perspective_, typename Tv_ >
Index mask_scatter (const LAFEM::PowerVector< Tv_, count_ > &vector, std::vector< int > &mask, const int value, const Index offset=Index(0)) const
Updates a scatter mask vector for this mirror.
PowerMirror & operator= (PowerMirror &&other)
move-assign operator
template<typename Tv_ >
void scatter_axpy (LAFEM::PowerVector< Tv_, count_ > &vector, const LAFEM::DenseVector< DataType, IndexType > &buffer, const DataType alpha=DataType(1), const Index buffer_offset=Index(0)) const
Scatters the buffer entries onto a DenseVector.
Static Public Member Functions
template<typename SubVector_ >
static PowerMirror make_empty (const PowerVector< SubVector_, count_ > &tmpl_vec)
Creates and returns an empty mirror.
Public Attributes
SubMirrorType _sub_mirror
the one and only sub-mirror object
Static Public Attributes
static constexpr int num_blocks = count_
total number of sub-mirror blocks
Detailed Description
template<typename SubMirror_, int count_>
class FEAT::LAFEM::PowerMirror< SubMirror_, count_ >
PowerVector meta-mirror class template.
This class template implements a vector-mirror which is capable of mirroring PowerVector objects.
Attention
This class template uses the same mirror for all blocks of a PowerVector object!
Template Parameters
SubMirror_ The type of the sub-mirror.
count_ The number of sub-mirror blocks.
Author
Peter Zajac
Definition at line 95 of file power_mirror.hpp.
Member Typedef Documentation
DataType
template<typename SubMirror_ , int count_> typedef SubMirrorType::DataType FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::DataType
sub-mirror data-type
Definition at line 103 of file power_mirror.hpp.
IndexType
template<typename SubMirror_ , int count_> typedef SubMirrorType::IndexType FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::IndexType
sub-mirror index-type
Definition at line 105 of file power_mirror.hpp.
MirrorType
template<typename SubMirror_ , int count_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::MirrorType = PowerMirror<typename SubMirrorType::template MirrorType<DT2_, IT2_>, count_>
Our 'base' class type.
Definition at line 112 of file power_mirror.hpp.
MirrorTypeByDI
template<typename SubMirror_ , int count_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::MirrorTypeByDI = MirrorType<DataType2_, IndexType2_>
this typedef lets you create a mirror with new Data and Index types
Definition at line 116 of file power_mirror.hpp.
SubMirrorType
template<typename SubMirror_ , int count_> typedef SubMirror_ FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::SubMirrorType
sub-mirror type
Definition at line 101 of file power_mirror.hpp.
Constructor & Destructor Documentation
PowerMirror() [1/3]
template<typename SubMirror_ , int count_> FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::PowerMirror () inline
default ctor
Definition at line 122 of file power_mirror.hpp.
Referenced by FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::clone(), and FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::make_empty().
PowerMirror() [2/3]
template<typename SubMirror_ , int count_> FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::PowerMirror (SubMirrorType && sub_mirror) inline explicit
sub-mirror move-ctor
Definition at line 127 of file power_mirror.hpp.
PowerMirror() [3/3]
template<typename SubMirror_ , int count_> FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::PowerMirror (PowerMirror< SubMirror_, count_ > && other) inline
move-ctor
Definition at line 133 of file power_mirror.hpp.
Member Function Documentation
at() [1/2]
template<typename SubMirror_ , int count_> template<int i_> SubMirrorType & FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::at () inline
Returns a sub-mirror block.
Template Parameters
i_ The index of the sub-mirror block that is to be returned.
Returns
A (const) reference to the sub-mirror at position i_.
Definition at line 234 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror.
at() [2/2]
template<typename SubMirror_ , int count_> template<int i_> const SubMirrorType & FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::at () const inline
Returns a sub-mirror block.
Template Parameters
i_ The index of the sub-mirror block that is to be returned.
Returns
A (const) reference to the sub-mirror at position i_.
Definition at line 242 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror.
buffer_size()
template<typename SubMirror_ , int count_> template<typename SubVector_ > Index FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::buffer_size (const PowerVector< SubVector_, count_ > & vector) const inline
Computes the required buffer size for a PowerVector.
Parameters
[in] vector The vector whose buffer size is to be computed.
Definition at line 207 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror.
Referenced by FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::create_buffer().
bytes()
template<typename SubMirror_ , int count_> std::size_t FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 185 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror.
clone()
template<typename SubMirror_ , int count_> PowerMirror FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::clone (CloneMode clone_mode = CloneMode::Weak) const inline
Clone operation.
Returns
A deep copy of this power mirror.
Definition at line 153 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::PowerMirror(), and FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates().
convert()
template<typename SubMirror_ , int count_> template<typename SubMirror2_ > void FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::convert (const PowerMirror< SubMirror2_, count_ > & other) inline
Conversion method.
Parameters
[in] other The source mirror.
Definition at line 165 of file power_mirror.hpp.
create_buffer()
template<typename SubMirror_ , int count_> template<typename SubVector_ > DenseVector< DataType, IndexType > FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::create_buffer (const PowerVector< SubVector_, count_ > & vector) const inline
Creates a new buffer vector for a PowerVector.
Parameters
[in] vector The vector for which the buffer is to be created.
Definition at line 219 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::buffer_size().
empty()
template<typename SubMirror_ , int count_> bool FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::empty () const inline
Checks whether the mirror is empty.
Returns
true, if there are no indices in the mirror, otherwise false.
Definition at line 195 of file power_mirror.hpp.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates().
gather()
template<typename SubMirror_ , int count_> template<typename Tv_ > void FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::gather (LAFEM::DenseVector< DataType, IndexType > & buffer, const LAFEM::PowerVector< Tv_, count_ > & vector, const Index buffer_offset = Index(0)) const inline
Gathers the buffer entries from a DenseVector.
Parameters
[in,out] buffer A reference to the buffer.
[in] vector A vector whose entries are to be gathered.
[in] buffer_offset The offset within the buffer.
Definition at line 272 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror.
get() [1/2]
template<typename SubMirror_ , int count_> SubMirrorType & FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::get (int i) inline
Returns a sub-mirror block.
Parameters
[in] i The index of the sub-mirror block that is to be returned.
Returns
A (const) reference to the sub-mirror at position i.
Definition at line 257 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror, and XASSERTM.
get() [2/2]
template<typename SubMirror_ , int count_> const SubMirrorType & FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::get (int i) const inline
Returns a sub-mirror block.
Parameters
[in] i The index of the sub-mirror block that is to be returned.
Returns
A (const) reference to the sub-mirror at position i.
Definition at line 264 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror, and XASSERTM.
make_empty()
template<typename SubMirror_ , int count_> template<typename SubVector_ > static PowerMirror FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::make_empty (const PowerVector< SubVector_, count_ > & tmpl_vec) inline static
Creates and returns an empty mirror.
Parameters
[in] tmpl_vec A transient reference to a template vector to get the correct size from
Returns
The new empty mirror
Definition at line 179 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::PowerMirror().
mask_scatter()
template<typename SubMirror_ , int count_> template<Perspective perspective_, typename Tv_ > Index FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::mask_scatter (const LAFEM::PowerVector< Tv_, count_ > & vector, std::vector< int > & mask, const int value, const Index offset = Index(0)) const inline
Updates a scatter mask vector for this mirror.
This function is used to create a so-called "scatter mask vector", i.e. a vector, in which each entry, that belongs to a DOF that is shared with other processes, is set to 1, and all other entries are set to 0 (or vice versa). This mask vector can then be used to determine the number of local and/or shared DOFs for this process.
Parameters
[in] vector A template vector to be used to determine the POD size; must be allocated to correct size but its contents are ignored.
[in,out] mask The mask vector to be updated.
[in] value The value that is to be used to set the mask vector entries referenced by this mirror.
[in] offset The offset of the first native/POD DOF in the mask vector.
Returns
The size of the input template vector.
Definition at line 293 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror, and FEAT::value.
operator=()
template<typename SubMirror_ , int count_> PowerMirror & FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::operator= (PowerMirror< SubMirror_, count_ > && other) inline
move-assign operator
Definition at line 139 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror.
scatter_axpy()
template<typename SubMirror_ , int count_> template<typename Tv_ > void FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::scatter_axpy (LAFEM::PowerVector< Tv_, count_ > & vector, const LAFEM::DenseVector< DataType, IndexType > & buffer, const DataType alpha = DataType(1), const Index buffer_offset = Index(0)) const inline
Scatters the buffer entries onto a DenseVector.
Parameters
[in,out] vector A reference to the vector.
[in] buffer A reference to the buffer whose entries are to be scattered.
[in] alpha A scaling factor for the operation.
[in] buffer_offset The offset within the buffer.
Definition at line 282 of file power_mirror.hpp.
References FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror.
Member Data Documentation
_sub_mirror
template<typename SubMirror_ , int count_> SubMirrorType FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::_sub_mirror
the one and only sub-mirror object
Definition at line 119 of file power_mirror.hpp.
Referenced by FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::at(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::buffer_size(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::bytes(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::clone(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::gather(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::get(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::mask_scatter(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::operator=(), and FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::scatter_axpy().
num_blocks
template<typename SubMirror_ , int count_> constexpr int FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::num_blocks = count_ static constexpr
total number of sub-mirror blocks
Definition at line 108 of file power_mirror.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/power_mirror.hpp