FEAT: FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ > Class Template Reference
FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ > Class Template Reference
Parsed vector function implementation.
#include <parsed_function.hpp>
Classes
class Evaluator
Public Types
typedef Analytic::Image::Vector< img_dim_ > ImageType
This function is always a vector field.
Public Member Functions
ParsedVectorFunction ()
Standard constructor.
ParsedVectorFunction (const String &function)
Constructor.
void add_constant (const String &name, double value)
Adds a constant to the parser.
void add_variable (const String &name, double value=0.0)
Adds an extra variable to the parser.
void parse (const String &function)
Parses a function.
void set_variable (const String &name, double value)
Sets the value of an extra variable.
Static Public Attributes
static constexpr bool can_grad = false
we cannot compute gradients
static constexpr bool can_hess = false
we cannot compute hessians
static constexpr bool can_value = true
we can compute function values
static constexpr int domain_dim = dom_dim_
validate our dimensions
Private Attributes
std::map< String, double > _extra_vars
our extra variable names
std::array<::FunctionParser, img_dim_ > _parsers
the actual function parser objects
Detailed Description
template<int dom_dim_, int img_dim_ = dom_dim_>
class FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >
Parsed vector function implementation.
This class provides an implementation of the Analytic::Function interface for vector functions which can parse and evaluate a formula tuple in the up to three variables 'x', 'y' and 'z' as well as user-defined extra variables given as a string at runtime.
Template Parameters
dom_dim_ The domain dimension of the vector function. Must be 1 <= dom_dim_ <= 3.
img_dim_ The image dimension of the vector function. Must be >= 1.
See the documentation of ParsedScalarFunction for more details.
Author
Peter Zajac
Definition at line 357 of file parsed_function.hpp.
Member Typedef Documentation
ImageType
template<int dom_dim_, int img_dim_ = dom_dim_> typedef Analytic::Image::Vector<img_dim_> FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::ImageType
This function is always a vector field.
Definition at line 369 of file parsed_function.hpp.
Constructor & Destructor Documentation
ParsedVectorFunction() [1/2]
template<int dom_dim_, int img_dim_ = dom_dim_> FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::ParsedVectorFunction () inline explicit
Standard constructor.
This constructor adds the following constants to the underlying parser:
pi = 3.14159...
eps = ~1E-16
Definition at line 395 of file parsed_function.hpp.
References FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::add_constant().
ParsedVectorFunction() [2/2]
template<int dom_dim_, int img_dim_ = dom_dim_> FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::ParsedVectorFunction (const String & function) inline explicit
Constructor.
This constructor creates a parsed function from a String.
Parameters
[in] function The expression that defines the function in the variables x, y, and z. The individual parts of the vector function components are separated by a single quotation mark '.
Exceptions
ParsedFunctionParseError An instance of the ParsedFunctionParseError exception is thrown if the fparser library fails to parse the formula. The message of the exception contains more information on the cause of the error and should be presented the user in an appropriate way.
Definition at line 417 of file parsed_function.hpp.
References FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::parse().
Member Function Documentation
add_constant()
template<int dom_dim_, int img_dim_ = dom_dim_> void FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::add_constant (const String & name, double value) inline
Adds a constant to the parser.
Parameters
[in] name The name of the constant.
[in] value The value of the constant.
Definition at line 432 of file parsed_function.hpp.
References FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::_parsers, and FEAT::value.
Referenced by FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::ParsedVectorFunction().
add_variable()
template<int dom_dim_, int img_dim_ = dom_dim_> void FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::add_variable (const String & name, double value = 0.0) inline
Adds an extra variable to the parser.
The value of the extra variable can be changed later on by using the set_variable function.
Parameters
[in] name The name of the variable. Must not be 'x', 'y' or 'z'.
[in] value The value for the extra variable.
Definition at line 449 of file parsed_function.hpp.
References FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::_extra_vars, FEAT::String::compare_no_case(), FEAT::value, and XASSERTM.
parse()
template<int dom_dim_, int img_dim_ = dom_dim_> void FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::parse (const String & function) inline
Parses a function.
Parameters
[in] function The expression that defines the function in the variables x, y, and z. The individual parts of the vector function components are separated by a single quotation mark '.
Exceptions
ParsedFunctionParseError An instance of the ParsedFunctionParseError exception is thrown if the fparser library fails to parse the formula. The message of the exception contains more information on the cause of the error and should be presented the user in an appropriate way.
Definition at line 487 of file parsed_function.hpp.
References FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::_extra_vars, FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::_parsers, FEAT::String::pop_front(), and FEAT::stringify().
Referenced by FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::ParsedVectorFunction().
set_variable()
template<int dom_dim_, int img_dim_ = dom_dim_> void FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::set_variable (const String & name, double value) inline
Sets the value of an extra variable.
Parameters
[in] name The name of the variable. Must have been added by using the add_variable function.
[in] value The value for the extra variable.
Definition at line 467 of file parsed_function.hpp.
References FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::_extra_vars, FEAT::value, and XASSERTM.
Member Data Documentation
_extra_vars
template<int dom_dim_, int img_dim_ = dom_dim_> std::map<String, double> FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::_extra_vars private
our extra variable names
Definition at line 382 of file parsed_function.hpp.
Referenced by FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::add_variable(), FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::parse(), and FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::set_variable().
_parsers
template<int dom_dim_, int img_dim_ = dom_dim_> std::array<::FunctionParser, img_dim_> FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::_parsers private
the actual function parser objects
Definition at line 385 of file parsed_function.hpp.
Referenced by FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::add_constant(), and FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::parse().
can_grad
template<int dom_dim_, int img_dim_ = dom_dim_> constexpr bool FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::can_grad = false static constexpr
we cannot compute gradients
Definition at line 375 of file parsed_function.hpp.
can_hess
template<int dom_dim_, int img_dim_ = dom_dim_> constexpr bool FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::can_hess = false static constexpr
we cannot compute hessians
Definition at line 378 of file parsed_function.hpp.
can_value
template<int dom_dim_, int img_dim_ = dom_dim_> constexpr bool FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::can_value = true static constexpr
we can compute function values
Definition at line 372 of file parsed_function.hpp.
domain_dim
template<int dom_dim_, int img_dim_ = dom_dim_> constexpr int FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::domain_dim = dom_dim_ static constexpr
validate our dimensions
specify our domain dimension
Definition at line 366 of file parsed_function.hpp.
The documentation for this class was generated from the following file:
kernel/analytic/parsed_function.hpp