FEAT: FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ > Class Template Reference
FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ > Class Template Reference
Variadic TupleMatrix class template.
#include <tuple_matrix.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = TupleMatrix< typename FirstRow_::template ContainerType< DT2_, IT2_ >, typename RestRows_::template ContainerType< DT2_, IT2_ >... >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a vector container with new Datatype and Index types
typedef FirstRow_::DataType DataType
sub-matrix data-type
typedef FirstRow_::IndexType IndexType
sub-matrix index-type
typedef TupleVector< typename FirstRow_::VectorTypeL, typename RestRows_::VectorTypeL... > VectorTypeL
Compatible L-vector type.
typedef FirstRow_::VectorTypeR VectorTypeR
Compatible R-vector type.
Public Member Functions
TupleMatrix ()
default CTOR
TupleMatrix (const TupleMatrix &)=delete
deleted copy-ctor
TupleMatrix (FirstRow_ &&the_first, RestClass &&the_rest)
rest-class emplacement ctor; for internal use only
TupleMatrix (FirstRow_ &&the_first, RestRows_ &&... the_rest)
Sub-Matrix emplacement constructor.
TupleMatrix (TupleMatrix &&other)
move ctor
void apply (VectorTypeL &r, const VectorTypeR &x) const
Calculate .
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, DataType alpha=DataType(1)) const
Calculate .
template<int i_, int j_>
TupleMatrixElement< i_, j_, FirstRow_, RestRows_... >::Type & at ()
Returns a sub-matrix block.
template<int i_, int j_>
const TupleMatrixElement< i_, j_, FirstRow_, RestRows_... >::Type & at () const
Returns a sub-matrix block.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
void clone (const TupleMatrix &other)
Turns this matrix into a clone of other.
void clone (const TupleMatrix &other, CloneMode clone_mode)
Turns this matrix into a clone of other.
TupleMatrix clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a copy of this matrix.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Returns the total number of columns in this matrix.
template<typename OtherFirstRow_ , typename... OtherRestRows_>
void convert (const TupleMatrix< OtherFirstRow_, OtherRestRows_... > &other)
template<typename OtherFirstRow_ , typename... OtherRestRows_>
void convert_reverse (TupleMatrix< OtherFirstRow_, OtherRestRows_... > &other) const
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DataType min, DataType max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
Index get_length_of_line (const Index row) const
TupleMatrix & operator= (const TupleMatrix &)=delete
deleted copy-assign operator
TupleMatrix & operator= (TupleMatrix &&other)
move-assign operator
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Returns the total number of rows in this matrix.
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
void set_line (const Index row, DataType *const pval_set, IndexType *const pcol_set, const Index col_start, const Index stride=1) const
void set_line_reverse (const Index row, DataType *const pval_set, const Index stride=1)
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Returns the total number of non-zeros in this matrix.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr int num_col_blocks = FirstRow_::num_blocks
number of column blocks (horizontal size)
static constexpr int num_row_blocks = TupleMatrix<RestRows_...>::num_row_blocks + 1
number of row blocks (vertical size)
Static Protected Member Functions
static String sub_name_list ()
Returns a list of all sub-matrix type names.
Protected Attributes
FirstRow_ _first
sanity check: vector types must match for all rows
RestClass _rest
all remaining sub-matrix rows
Private Types
typedef TupleMatrix< RestRows_... > RestClass
Detailed Description
template<typename FirstRow_, typename... RestRows_>
class FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >
Variadic TupleMatrix class template.
Template Parameters
FirstRow_,...RestRows_ A sequence of TupleMatrixRow template class instances which are to be composed
Attention
All template parameters supplied to this class must be instances of the TupleMatrixRow class template, even if the TupleMatrix only has 1 meta-column!
Author
Peter Zajac
Definition at line 699 of file tuple_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename FirstRow_ , typename... RestRows_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::ContainerType = TupleMatrix< typename FirstRow_::template ContainerType<DT2_, IT2_>, typename RestRows_::template ContainerType<DT2_, IT2_>...>
Our 'base' class type.
Definition at line 734 of file tuple_matrix.hpp.
ContainerTypeByDI
template<typename FirstRow_ , typename... RestRows_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a vector container with new Datatype and Index types
Definition at line 740 of file tuple_matrix.hpp.
DataType
template<typename FirstRow_ , typename... RestRows_> typedef FirstRow_::DataType FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::DataType
sub-matrix data-type
Definition at line 722 of file tuple_matrix.hpp.
IndexType
template<typename FirstRow_ , typename... RestRows_> typedef FirstRow_::IndexType FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::IndexType
sub-matrix index-type
Definition at line 724 of file tuple_matrix.hpp.
RestClass
template<typename FirstRow_ , typename... RestRows_> typedef TupleMatrix<RestRows_...> FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::RestClass private
Definition at line 705 of file tuple_matrix.hpp.
VectorTypeL
template<typename FirstRow_ , typename... RestRows_> typedef TupleVector<typename FirstRow_::VectorTypeL, typename RestRows_::VectorTypeL...> FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::VectorTypeL
Compatible L-vector type.
Definition at line 743 of file tuple_matrix.hpp.
VectorTypeR
template<typename FirstRow_ , typename... RestRows_> typedef FirstRow_::VectorTypeR FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::VectorTypeR
Compatible R-vector type.
Definition at line 745 of file tuple_matrix.hpp.
Constructor & Destructor Documentation
TupleMatrix() [1/4]
template<typename FirstRow_ , typename... RestRows_> FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::TupleMatrix () inline
default CTOR
Definition at line 764 of file tuple_matrix.hpp.
TupleMatrix() [2/4]
template<typename FirstRow_ , typename... RestRows_> FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::TupleMatrix (FirstRow_ && the_first, RestClass && the_rest) inline explicit
rest-class emplacement ctor; for internal use only
Definition at line 769 of file tuple_matrix.hpp.
TupleMatrix() [3/4]
template<typename FirstRow_ , typename... RestRows_> FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::TupleMatrix (FirstRow_ && the_first, RestRows_ &&... the_rest) inline explicit
Sub-Matrix emplacement constructor.
Definition at line 776 of file tuple_matrix.hpp.
TupleMatrix() [4/4]
template<typename FirstRow_ , typename... RestRows_> FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::TupleMatrix (TupleMatrix< FirstRow_, RestRows_ > && other) inline
move ctor
Definition at line 783 of file tuple_matrix.hpp.
Member Function Documentation
apply() [1/2]
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Calculate .
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 992 of file tuple_matrix.hpp.
apply() [2/2]
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, DataType alpha = DataType(1)) const inline
Calculate .
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 1006 of file tuple_matrix.hpp.
at() [1/2]
template<typename FirstRow_ , typename... RestRows_> template<int i_, int j_> TupleMatrixElement< i_, j_, FirstRow_, RestRows_... >::Type & FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::at () inline
Returns a sub-matrix block.
Template Parameters
i_,j_ The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_, j_).
Definition at line 871 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::num_col_blocks, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::num_row_blocks.
at() [2/2]
template<typename FirstRow_ , typename... RestRows_> template<int i_, int j_> const TupleMatrixElement< i_, j_, FirstRow_, RestRows_... >::Type & FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::at () const inline
Returns a sub-matrix block.
Template Parameters
i_,j_ The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_, j_).
Definition at line 880 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::num_col_blocks, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::num_row_blocks.
bytes()
template<typename FirstRow_ , typename... RestRows_> std::size_t FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::bytes () const inline
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 931 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::bytes().
Referenced by FEAT::Control::Stokes3FieldSystemLevel< dim_, nsc_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, MatrixBlockM_, MatrixBlockK_, MatrixBlockL_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_, TransferMatrixS_ >::bytes(), and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::bytes().
clear()
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clear () inline
Free all allocated arrays.
Definition at line 968 of file tuple_matrix.hpp.
clone() [1/3]
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone (const TupleMatrix< FirstRow_, RestRows_ > & other) inline
Turns this matrix into a clone of other.
As the default CloneMode of the underlying containers is unknown, this has to be separate.
Definition at line 833 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone().
clone() [2/3]
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone (const TupleMatrix< FirstRow_, RestRows_ > & other, CloneMode clone_mode) inline
Turns this matrix into a clone of other.
Parameters
[in] clone_mode Determines the type of clone returned (shallow, weak, layout, deep)
Definition at line 822 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone().
clone() [3/3]
template<typename FirstRow_ , typename... RestRows_> TupleMatrix FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a copy of this matrix.
Parameters
[in] mode Determines the type of clone returned (shallow, weak, layout, deep)
Definition at line 811 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone().
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone().
columns()
template<typename FirstRow_ , typename... RestRows_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::columns () const inline
Returns the total number of columns in this matrix.
Returns
Matrix column count if perspective_ = false.
Raw matrix column count if perspective_ = true.
Definition at line 906 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest, and XASSERTM.
convert()
template<typename FirstRow_ , typename... RestRows_> template<typename OtherFirstRow_ , typename... OtherRestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::convert (const TupleMatrix< OtherFirstRow_, OtherRestRows_... > & other) inline
Definition at line 1073 of file tuple_matrix.hpp.
convert_reverse()
template<typename FirstRow_ , typename... RestRows_> template<typename OtherFirstRow_ , typename... OtherRestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::convert_reverse (TupleMatrix< OtherFirstRow_, OtherRestRows_... > & other) const inline
Definition at line 1080 of file tuple_matrix.hpp.
create_vector_l()
template<typename FirstRow_ , typename... RestRows_> VectorTypeL FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 975 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::create_vector_l().
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::create_vector_l().
create_vector_r()
template<typename FirstRow_ , typename... RestRows_> VectorTypeR FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 981 of file tuple_matrix.hpp.
format() [1/2]
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the matrix's entries are to be set to.
Definition at line 948 of file tuple_matrix.hpp.
References FEAT::value.
format() [2/2]
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::format (Random & rng, DataType min, DataType max) inline
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 961 of file tuple_matrix.hpp.
get_checkpoint_size()
template<typename FirstRow_ , typename... RestRows_> std::uint64_t FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1040 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::get_checkpoint_size().
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::get_checkpoint_size().
get_length_of_line()
template<typename FirstRow_ , typename... RestRows_> Index FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::get_length_of_line (const Index row) const inline
Definition at line 1012 of file tuple_matrix.hpp.
name()
template<typename FirstRow_ , typename... RestRows_> static String FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 937 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::sub_name_list().
operator=()
template<typename FirstRow_ , typename... RestRows_> TupleMatrix & FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::operator= (TupleMatrix< FirstRow_, RestRows_ > && other) inline
move-assign operator
Definition at line 790 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest.
restore_from_checkpoint_data()
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1046 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::restore_from_checkpoint_data().
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::restore_from_checkpoint_data().
rows()
template<typename FirstRow_ , typename... RestRows_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::rows () const inline
Returns the total number of rows in this matrix.
Returns
Matrix row count if perspective_ = false.
Raw matrix row count if perspective_ = true.
Definition at line 894 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest.
set_checkpoint_data()
template<typename FirstRow_ , typename... RestRows_> std::uint64_t FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 1059 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::set_checkpoint_data().
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::set_checkpoint_data().
set_line()
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::set_line (const Index row, DataType *const pval_set, IndexType *const pcol_set, const Index col_start, const Index stride = 1) const inline
Definition at line 1021 of file tuple_matrix.hpp.
set_line_reverse()
template<typename FirstRow_ , typename... RestRows_> void FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::set_line_reverse (const Index row, DataType *const pval_set, const Index stride = 1) inline
Definition at line 1030 of file tuple_matrix.hpp.
sub_name_list()
template<typename FirstRow_ , typename... RestRows_> static String FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::sub_name_list () inline static protected
Returns a list of all sub-matrix type names.
Definition at line 757 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::sub_name_list().
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::name(), and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::sub_name_list().
used_elements()
template<typename FirstRow_ , typename... RestRows_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::used_elements () const inline
Returns the total number of non-zeros in this matrix.
Returns
Matrix non zero element count if perspective_ = false.
Raw matrix non zero element count if perspective_ = true.
Definition at line 921 of file tuple_matrix.hpp.
References FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first, and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest.
Friends And Related Function Documentation
TupleMatrix
template<typename FirstRow_ , typename... RestRows_> template<typename , typename... > friend class TupleMatrix friend
Definition at line 703 of file tuple_matrix.hpp.
Member Data Documentation
_first
template<typename FirstRow_ , typename... RestRows_> FirstRow_ FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_first protected
sanity check: vector types must match for all rows
the first sub-matrix row
Definition at line 752 of file tuple_matrix.hpp.
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::bytes(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::columns(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::get_checkpoint_size(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::operator=(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::restore_from_checkpoint_data(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::rows(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::set_checkpoint_data(), and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::used_elements().
_rest
template<typename FirstRow_ , typename... RestRows_> RestClass FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::_rest protected
all remaining sub-matrix rows
Definition at line 754 of file tuple_matrix.hpp.
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::bytes(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::clone(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::columns(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::get_checkpoint_size(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::operator=(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::restore_from_checkpoint_data(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::rows(), FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::set_checkpoint_data(), and FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::used_elements().
num_col_blocks
template<typename FirstRow_ , typename... RestRows_> constexpr int FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::num_col_blocks = FirstRow_::num_blocks static constexpr
number of column blocks (horizontal size)
Definition at line 716 of file tuple_matrix.hpp.
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::at().
num_row_blocks
template<typename FirstRow_ , typename... RestRows_> constexpr int FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::num_row_blocks = TupleMatrix<RestRows_...>::num_row_blocks + 1 static constexpr
number of row blocks (vertical size)
Definition at line 714 of file tuple_matrix.hpp.
Referenced by FEAT::LAFEM::TupleMatrix< FirstRow_, RestRows_ >::at().
The documentation for this class was generated from the following file:
kernel/lafem/tuple_matrix.hpp