FEAT: FEAT::Geometry::Atlas::Sphere< Mesh_ > Class Template Reference
FEAT::Geometry::Atlas::Sphere< Mesh_ > Class Template Reference abstract
Sphere chart class template.
#include <sphere.hpp>
Public Types
typedef PartType::AttributeSetType AttributeSetType
attribute type of our mesh-part
typedef ChartCRTP< Sphere< Mesh_ >, Mesh_, SphereTraits > BaseClass
CRTP base class.
typedef BaseClass::CoordType CoordType
Floating point type.
typedef BaseClass::MeshType MeshType
mesh type
typedef BaseClass::ParamPoint ParamPoint
Vector type for parameter points, aka domain points.
typedef BaseClass::PartType PartType
mesh-part type
typedef SphereTraits TraitsType
traits type
typedef MeshType::VertexSetType VertexSetType
vertex set type of our mesh
typedef BaseClass::WorldPoint WorldPoint
Vector type for world points, aka image points.
Public Member Functions
Sphere (CoordType mid_x, CoordType mid_y, CoordType mid_z, CoordType radius)
Constructor.
virtual void adapt (MeshType &mesh, const PartType &part) const override
Adapts a whole MeshPart.
virtual void adapt (PartType &parent_meshpart, const PartType &meshpart) const override
Adapts a whole MeshPart referring to another MeshPart.
virtual std::size_t bytes () const
virtual bool can_explicit () const override
virtual bool can_implicit () const override
CoordType compute_dist (const WorldPoint &point) const
Computes the distance of a point to this chart.
CoordType compute_dist (const WorldPoint &point, WorldPoint &grad_dist) const
Computes the distance of a point to this chart.
CoordType compute_signed_dist (const WorldPoint &point) const
Computes the signed distance of a point to this chart.
CoordType compute_signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const
Computes the signed distance of a point to this chart.
virtual CoordType dist (const WorldPoint &point) const override
virtual CoordType dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual String get_type () const override
Writes the type as String.
virtual WorldPoint map (const WorldPoint &param) const override
virtual WorldPoint project (const WorldPoint &point) const override
void project_meshpart (Mesh_ &mesh, const MeshPart< Mesh_ > &meshpart) const
Projects all mesh points identified by a meshpart.
void project_point (WorldPoint &point) const
Projects a single world point.
virtual CoordType signed_dist (const WorldPoint &point) const override
virtual CoordType signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset) override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset)=0
Applies a "proper rigid" transformation onto the chart.
virtual void write (std::ostream &os, const String &sindent) const override
Writes the Chart into a stream in XML format.
Static Public Attributes
static constexpr bool is_explicit
specifies whether this chart is explicit
static constexpr bool is_implicit
specifies whether this chart is implicit
static constexpr int param_dim
the parameter dimension of this chart
static constexpr int world_dim
the world dimension of this chart
Protected Member Functions
Sphere< Mesh_ > & cast ()
Casts this to its true type.
const Sphere< Mesh_ > & cast () const
Protected Attributes
WorldPoint _midpoint
the sphere's midpoint
CoordType _radius
the sphere's radius
Detailed Description
template<typename Mesh_>
class FEAT::Geometry::Atlas::Sphere< Mesh_ >
Sphere chart class template.
This class represents a 3D sphere characterized by a midpoint and a radius.
This chart implements only the implicit chart interface.
Template Parameters
Mesh_ The type of the mesh to be parameterized by this chart.
Author
Peter Zajac
Definition at line 42 of file sphere.hpp.
Member Typedef Documentation
AttributeSetType
typedef PartType::AttributeSetType FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::AttributeSetType inherited
attribute type of our mesh-part
Definition at line 365 of file chart.hpp.
BaseClass
template<typename Mesh_ > typedef ChartCRTP<Sphere<Mesh_>, Mesh_, SphereTraits> FEAT::Geometry::Atlas::Sphere< Mesh_ >::BaseClass
CRTP base class.
Definition at line 47 of file sphere.hpp.
CoordType
template<typename Mesh_ > typedef BaseClass::CoordType FEAT::Geometry::Atlas::Sphere< Mesh_ >::CoordType
Floating point type.
Definition at line 49 of file sphere.hpp.
MeshType
typedef BaseClass::MeshType FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::MeshType inherited
mesh type
Definition at line 361 of file chart.hpp.
ParamPoint
template<typename Mesh_ > typedef BaseClass::ParamPoint FEAT::Geometry::Atlas::Sphere< Mesh_ >::ParamPoint
Vector type for parameter points, aka domain points.
Definition at line 53 of file sphere.hpp.
PartType
typedef BaseClass::PartType FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::PartType inherited
mesh-part type
Definition at line 363 of file chart.hpp.
TraitsType
typedef SphereTraits FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::TraitsType inherited
traits type
Definition at line 359 of file chart.hpp.
VertexSetType
typedef MeshType::VertexSetType FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::VertexSetType inherited
vertex set type of our mesh
Definition at line 367 of file chart.hpp.
WorldPoint
template<typename Mesh_ > typedef BaseClass::WorldPoint FEAT::Geometry::Atlas::Sphere< Mesh_ >::WorldPoint
Vector type for world points, aka image points.
Definition at line 51 of file sphere.hpp.
Constructor & Destructor Documentation
Sphere()
template<typename Mesh_ > FEAT::Geometry::Atlas::Sphere< Mesh_ >::Sphere (CoordType mid_x, CoordType mid_y, CoordType mid_z, CoordType radius) inline explicit
Constructor.
Parameters
[in] mid_x,mid_y,mid_z The coordinates of the sphere midpoint.
[in] radius The radius of the sphere. Must be positive.
Definition at line 71 of file sphere.hpp.
References FEAT::Geometry::Atlas::Sphere< Mesh_ >::_midpoint, and XASSERTM.
Member Function Documentation
adapt() [1/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::adapt (MeshType & mesh, const PartType & part) const inline override virtual inherited
Adapts a whole MeshPart.
Parameters
[in] mesh Mesh to be adapted
[in] part MeshPart identifying the region to be adapted
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 420 of file chart.hpp.
adapt() [2/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::adapt (PartType & parent_meshpart, const PartType & meshpart) const inline override virtual inherited
Adapts a whole MeshPart referring to another MeshPart.
Parameters
[in] parent_meshpart MeshPart to be adapted
[in] meshpart MeshPart identifying the region to be adapted
Todo:
: Implement this
There is currently no code that uses MeshParts referring to other MeshParts instead of a RootMesh.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 450 of file chart.hpp.
bytes()
template<typename Mesh_ > virtual std::size_t FEAT::Geometry::Atlas::ChartBase< Mesh_ >::bytes () const inline virtual inherited
Returns
The size of dynamically allocated memory in bytes.
Reimplemented in FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >.
Definition at line 52 of file chart.hpp.
can_explicit()
virtual bool FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::can_explicit () const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 400 of file chart.hpp.
can_implicit()
virtual bool FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::can_implicit () const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 406 of file chart.hpp.
cast() [1/2]
Sphere< Mesh_ > & FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::cast () inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this
Definition at line 393 of file chart.hpp.
cast() [2/2]
const Sphere< Mesh_ > & FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::cast () const inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this\ifile "/github/workspace/kernel/geometry/atlas/chart.hpp"
Definition at line 396 of file chart.hpp.
compute_dist() [1/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_dist (const WorldPoint & point) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 144 of file sphere.hpp.
References FEAT::Math::abs(), and FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_signed_dist().
compute_dist() [2/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 150 of file sphere.hpp.
References FEAT::Geometry::Atlas::Sphere< Mesh_ >::_midpoint, FEAT::Geometry::Atlas::Sphere< Mesh_ >::_radius, FEAT::Math::abs(), and FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_point().
compute_signed_dist() [1/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_signed_dist (const WorldPoint & point) const inline
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Definition at line 164 of file sphere.hpp.
References FEAT::Geometry::Atlas::Sphere< Mesh_ >::_midpoint, and FEAT::Geometry::Atlas::Sphere< Mesh_ >::_radius.
Referenced by FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_dist().
compute_signed_dist() [2/2]
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Definition at line 170 of file sphere.hpp.
References FEAT::Geometry::Atlas::Sphere< Mesh_ >::_midpoint, FEAT::Geometry::Atlas::Sphere< Mesh_ >::_radius, FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_point(), and FEAT::Math::signum().
dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 480 of file chart.hpp.
dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 486 of file chart.hpp.
get_type()
template<typename Mesh_ > virtual String FEAT::Geometry::Atlas::Sphere< Mesh_ >::get_type () const inline override virtual
Writes the type as String.
Needed for writing this to mesh files.
Returns
The class name as String.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 81 of file sphere.hpp.
map()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::map (const WorldPoint & param) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 456 of file chart.hpp.
project()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::project (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 469 of file chart.hpp.
project_meshpart()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_meshpart (Mesh_ & mesh, const MeshPart< Mesh_ > & meshpart) const inline
Projects all mesh points identified by a meshpart.
Parameters
[in,out] mesh The mesh whose points will be projected
[in] meshpart The MeshPart identifying the point to be projected
Definition at line 132 of file sphere.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities(), and FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_point().
project_point()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_point (WorldPoint & point) const inline
Projects a single world point.
Parameters
[in,out] point The world point to be projected
Definition at line 106 of file sphere.hpp.
References FEAT::Geometry::Atlas::Sphere< Mesh_ >::_midpoint, and FEAT::Geometry::Atlas::Sphere< Mesh_ >::_radius.
Referenced by FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_dist(), FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_signed_dist(), and FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_meshpart().
signed_dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::signed_dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 492 of file chart.hpp.
signed_dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 498 of file chart.hpp.
transform() [1/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::Sphere< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) inline override virtual
Definition at line 87 of file sphere.hpp.
References FEAT::Geometry::Atlas::Sphere< Mesh_ >::_midpoint, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_3d().
transform() [2/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::ChartBase< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) pure virtual inherited
Applies a "proper rigid" transformation onto the chart.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any point x of the chart:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any point before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): -ignored-
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any point after applying the rotation.
Implemented in FEAT::Geometry::Atlas::CGALSurfaceMesh< Mesh_ >.
write()
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::Sphere< Mesh_ >::write (std::ostream & os, const String & sindent) const inline override virtual
Writes the Chart into a stream in XML format.
Parameters
[in,out] os The output stream to write into.
[in] sindent The indentation string.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 185 of file sphere.hpp.
Member Data Documentation
_midpoint
template<typename Mesh_ > WorldPoint FEAT::Geometry::Atlas::Sphere< Mesh_ >::_midpoint protected
the sphere's midpoint
Definition at line 57 of file sphere.hpp.
Referenced by FEAT::Geometry::Atlas::Sphere< Mesh_ >::Sphere(), FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_dist(), FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_signed_dist(), FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_point(), and FEAT::Geometry::Atlas::Sphere< Mesh_ >::transform().
_radius
template<typename Mesh_ > CoordType FEAT::Geometry::Atlas::Sphere< Mesh_ >::_radius protected
the sphere's radius
Definition at line 59 of file sphere.hpp.
Referenced by FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_dist(), FEAT::Geometry::Atlas::Sphere< Mesh_ >::compute_signed_dist(), and FEAT::Geometry::Atlas::Sphere< Mesh_ >::project_point().
is_explicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::is_explicit static constexpr inherited
specifies whether this chart is explicit
Definition at line 372 of file chart.hpp.
is_implicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::is_implicit static constexpr inherited
specifies whether this chart is implicit
Definition at line 374 of file chart.hpp.
param_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::param_dim static constexpr inherited
the parameter dimension of this chart
Definition at line 379 of file chart.hpp.
world_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< Sphere< Mesh_ > , Mesh_, SphereTraits >::world_dim static constexpr inherited
the world dimension of this chart
Definition at line 377 of file chart.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/atlas/sphere.hpp