FEAT: FEAT::Cubature::DriverFactory< Driver_, Shape_, true > Class Template Reference
FEAT::Cubature::DriverFactory< Driver_, Shape_, true > Class Template Reference
DriverFactory specialization for variadic drivers.
#include <driver_factory.hpp>
Public Types
typedef Driver_< Shape_ > DriverType
typedef Shape_ ShapeType
Public Member Functions
DriverFactory (int num_points)
template<typename Weight_ , typename Coord_ , typename Point_ >
bool create (Rule< Shape_, Weight_, Coord_, Point_ > &rule)
Creates the cubature rule.
Static Public Member Functions
template<typename Functor_ >
static void alias (Functor_ &functor)
Calls the driver's alias function.
template<typename Weight_ , typename Coord_ , typename Point_ >
static bool create (Rule< Shape_, Weight_, Coord_, Point_ > &rule, const String &name)
Creates the cubature rule from a string.
template<typename Weight_ , typename Coord_ , typename Point_ >
static bool create (Rule< Shape_, Weight_, Coord_, Point_ > &rule, int num_points)
Creates the cubature rule.
static String name ()
Returns the name of the cubature rule.
Static Public Attributes
static constexpr int max_points = DriverType::max_points
static constexpr int min_points = DriverType::min_points
static constexpr bool variadic = true
Protected Attributes
int _num_points
Detailed Description
template<template< typename > class Driver_, typename Shape_>
class FEAT::Cubature::DriverFactory< Driver_, Shape_, true >
DriverFactory specialization for variadic drivers.
Author
Peter Zajac
Definition at line 147 of file driver_factory.hpp.
Member Typedef Documentation
DriverType
template<template< typename > class Driver_, typename Shape_ > typedef Driver_<Shape_> FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::DriverType
Definition at line 150 of file driver_factory.hpp.
ShapeType
template<template< typename > class Driver_, typename Shape_ > typedef Shape_ FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::ShapeType
Definition at line 151 of file driver_factory.hpp.
Constructor & Destructor Documentation
DriverFactory()
template<template< typename > class Driver_, typename Shape_ > FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::DriverFactory (int num_points) inline explicit
Definition at line 160 of file driver_factory.hpp.
Member Function Documentation
alias()
template<template< typename > class Driver_, typename Shape_ > template<typename Functor_ > static void FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::alias (Functor_ & functor) inline static
Calls the driver's alias function.
Definition at line 258 of file driver_factory.hpp.
create() [1/3]
template<template< typename > class Driver_, typename Shape_ > template<typename Weight_ , typename Coord_ , typename Point_ > bool FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::create (Rule< Shape_, Weight_, Coord_, Point_ > & rule) inline
Creates the cubature rule.
Parameters
[out] rule The cubature rule to be created.
Definition at line 174 of file driver_factory.hpp.
create() [2/3]
template<template< typename > class Driver_, typename Shape_ > template<typename Weight_ , typename Coord_ , typename Point_ > static bool FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::create (Rule< Shape_, Weight_, Coord_, Point_ > & rule, const String & name) inline static
Creates the cubature rule from a string.
This function creates the cubature rule if the string in name represents a valid representation of the cubature rule's name.
Parameters
[out] rule The rule to be created.
[in] name The name of the cubature rule to create.
Returns
true, if the cubature rule was created successfully, or false, if name is not a valid name of the cubature rule implemented by this factory.
Definition at line 217 of file driver_factory.hpp.
References FEAT::String::compare_no_case(), FEAT::String::parse(), and FEAT::String::trim().
create() [3/3]
template<template< typename > class Driver_, typename Shape_ > template<typename Weight_ , typename Coord_ , typename Point_ > static bool FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::create (Rule< Shape_, Weight_, Coord_, Point_ > & rule, int num_points) inline static
Creates the cubature rule.
Parameters
[out] rule The cubature rule to be created.
[in] num_points The number of points for the cubature rule.
Definition at line 189 of file driver_factory.hpp.
References FEAT::stringify().
name()
template<template< typename > class Driver_, typename Shape_ > static String FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::name () inline static
Returns the name of the cubature rule.
Definition at line 249 of file driver_factory.hpp.
Member Data Documentation
_num_points
template<template< typename > class Driver_, typename Shape_ > int FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::_num_points protected
Definition at line 157 of file driver_factory.hpp.
max_points
template<template< typename > class Driver_, typename Shape_ > constexpr int FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::max_points = DriverType::max_points static constexpr
Definition at line 154 of file driver_factory.hpp.
min_points
template<template< typename > class Driver_, typename Shape_ > constexpr int FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::min_points = DriverType::min_points static constexpr
Definition at line 153 of file driver_factory.hpp.
variadic
template<template< typename > class Driver_, typename Shape_ > constexpr bool FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::variadic = true static constexpr
Definition at line 152 of file driver_factory.hpp.
The documentation for this class was generated from the following file:
kernel/cubature/driver_factory.hpp