FEAT: FEAT::LAFEM::TupleMirror< First_, Rest_ > Class Template Reference
FEAT::LAFEM::TupleMirror< First_, Rest_ > Class Template Reference
TupleVector meta-mirror class template.
#include <tuple_mirror.hpp>
Public Types
typedef First_::DataType DataType
sub-mirror data-type
typedef First_::IndexType IndexType
sub-mirror index-type
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using MirrorType = TupleMirror< typename First_::template MirrorType< DT2_, IT2_ >, typename Rest_::template MirrorType< DT2_, IT2_ >... >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using MirrorTypeByDI = MirrorType< DataType2_, IndexType2_ >
this typedef lets you create a mirror with new Data and Index types
Public Member Functions
TupleMirror ()
default ctor
TupleMirror (First_ &&the_first, Rest_ &&... the_rest)
sub-mirror emplacement ctor
TupleMirror (TupleMirror &&other)
move-ctor
template<int i_>
TupleElement< i_, First_, Rest_... >::Type & at ()
Returns a sub-mirror block.
template<int i_>
TupleElement< i_, First_, Rest_... >::Type const & at () const
Returns a sub-mirror block.
template<typename Tv_ , typename... Tw_>
Index buffer_size (const TupleVector< Tv_, Tw_... > &vector) const
Computes the required buffer size for a TupleVector.
std::size_t bytes () const
Returns the total amount of bytes allocated.
TupleMirror clone (CloneMode clone_mode=CloneMode::Weak) const
Clone operation.
template<typename... SubMirror2_>
void convert (const TupleMirror< SubMirror2_... > &other)
Conversion method.
template<typename Tv_ , typename... Tw_>
DenseVector< DataType, IndexType > create_buffer (const TupleVector< Tv_, Tw_... > &vector) const
Creates a new buffer vector for a TupleVector.
bool empty () const
Checks whether the mirror is empty.
template<typename Tv_ , typename... Tw_>
void gather (LAFEM::DenseVector< DataType, IndexType > &buffer, const LAFEM::TupleVector< Tv_, Tw_... > &vector, const Index buffer_offset=Index(0)) const
Gathers the buffer entries from a DenseVector.
template<Perspective perspective_, typename Tv_ , typename... Tw_>
Index mask_scatter (const LAFEM::TupleVector< Tv_, Tw_... > &vector, std::vector< int > &mask, const int value, const Index offset=Index(0)) const
Updates a scatter mask vector for this mirror.
TupleMirror & operator= (TupleMirror &&other)
move-assign operator
template<typename Tv_ , typename... Tw_>
void scatter_axpy (LAFEM::TupleVector< Tv_, Tw_... > &vector, const LAFEM::DenseVector< DataType, IndexType > &buffer, const DataType alpha=DataType(1), const Index buffer_offset=Index(0)) const
Scatters the buffer entries onto a DenseVector.
Static Public Attributes
static constexpr int num_blocks = RestClass::num_blocks + 1
number of mirror blocks
Protected Member Functions
TupleMirror (First_ &&the_first, RestClass &&the_rest)
data-move ctor; this one is protected for a reason
Protected Attributes
First_ _first
the first sub-mirror
RestClass _rest
all remaining sub-mirrors
Private Types
typedef TupleMirror< Rest_... > RestClass
Detailed Description
template<typename First_, typename... Rest_>
class FEAT::LAFEM::TupleMirror< First_, Rest_ >
TupleVector meta-mirror class template.
This class template implements a vector-mirror which is capable of mirroring TupleVector objects.
Template Parameters
First_,Rest_... A sequence of (meta) vector mirrors which are to be composed.
Author
Peter Zajac
Definition at line 32 of file tuple_mirror.hpp.
Member Typedef Documentation
DataType
template<typename First_ , typename... Rest_> typedef First_::DataType FEAT::LAFEM::TupleMirror< First_, Rest_ >::DataType
sub-mirror data-type
Definition at line 44 of file tuple_mirror.hpp.
IndexType
template<typename First_ , typename... Rest_> typedef First_::IndexType FEAT::LAFEM::TupleMirror< First_, Rest_ >::IndexType
sub-mirror index-type
Definition at line 46 of file tuple_mirror.hpp.
MirrorType
template<typename First_ , typename... Rest_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::TupleMirror< First_, Rest_ >::MirrorType = TupleMirror< typename First_::template MirrorType<DT2_, IT2_>, typename Rest_::template MirrorType<DT2_, IT2_>...>
Our 'base' class type.
Definition at line 54 of file tuple_mirror.hpp.
MirrorTypeByDI
template<typename First_ , typename... Rest_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::TupleMirror< First_, Rest_ >::MirrorTypeByDI = MirrorType<DataType2_, IndexType2_>
this typedef lets you create a mirror with new Data and Index types
Definition at line 60 of file tuple_mirror.hpp.
RestClass
template<typename First_ , typename... Rest_> typedef TupleMirror<Rest_...> FEAT::LAFEM::TupleMirror< First_, Rest_ >::RestClass private
Definition at line 37 of file tuple_mirror.hpp.
Constructor & Destructor Documentation
TupleMirror() [1/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleMirror< First_, Rest_ >::TupleMirror (First_ && the_first, RestClass && the_rest) inline protected
data-move ctor; this one is protected for a reason
Definition at line 69 of file tuple_mirror.hpp.
TupleMirror() [2/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleMirror< First_, Rest_ >::TupleMirror () inline
default ctor
Definition at line 77 of file tuple_mirror.hpp.
TupleMirror() [3/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleMirror< First_, Rest_ >::TupleMirror (First_ && the_first, Rest_ &&... the_rest) inline explicit
sub-mirror emplacement ctor
Definition at line 82 of file tuple_mirror.hpp.
TupleMirror() [4/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleMirror< First_, Rest_ >::TupleMirror (TupleMirror< First_, Rest_ > && other) inline
move-ctor
Definition at line 89 of file tuple_mirror.hpp.
Member Function Documentation
at() [1/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type & FEAT::LAFEM::TupleMirror< First_, Rest_ >::at () inline
Returns a sub-mirror block.
Template Parameters
i_ The index of the sub-mirror block that is to be returned.
Returns
A (const) reference to the sub-mirror at position i_.
Definition at line 201 of file tuple_mirror.hpp.
at() [2/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type const & FEAT::LAFEM::TupleMirror< First_, Rest_ >::at () const inline
Returns a sub-mirror block.
Template Parameters
i_ The index of the sub-mirror block that is to be returned.
Returns
A (const) reference to the sub-mirror at position i_.
Definition at line 208 of file tuple_mirror.hpp.
buffer_size()
template<typename First_ , typename... Rest_> template<typename Tv_ , typename... Tw_> Index FEAT::LAFEM::TupleMirror< First_, Rest_ >::buffer_size (const TupleVector< Tv_, Tw_... > & vector) const inline
Computes the required buffer size for a TupleVector.
Parameters
[in] vector The vector whose buffer size is to be computed.
Definition at line 174 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first, FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMirror< First_, Rest_ >::buffer_size().
Referenced by FEAT::LAFEM::TupleMirror< First_, Rest_ >::buffer_size(), and FEAT::LAFEM::TupleMirror< First_, Rest_ >::create_buffer().
bytes()
template<typename First_ , typename... Rest_> std::size_t FEAT::LAFEM::TupleMirror< First_, Rest_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 130 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first, FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMirror< First_, Rest_ >::bytes().
Referenced by FEAT::LAFEM::TupleMirror< First_, Rest_ >::bytes().
clone()
template<typename First_ , typename... Rest_> TupleMirror FEAT::LAFEM::TupleMirror< First_, Rest_ >::clone (CloneMode clone_mode = CloneMode::Weak) const inline
Clone operation.
Returns
A deep copy of this tuple mirror.
Definition at line 111 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first, FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMirror< First_, Rest_ >::clone().
Referenced by FEAT::LAFEM::TupleMirror< First_, Rest_ >::clone().
convert()
template<typename First_ , typename... Rest_> template<typename... SubMirror2_> void FEAT::LAFEM::TupleMirror< First_, Rest_ >::convert (const TupleMirror< SubMirror2_... > & other) inline
Conversion method.
Parameters
[in] other The source mirror.
Definition at line 123 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::convert().
Referenced by FEAT::LAFEM::TupleMirror< First_, Rest_ >::convert().
create_buffer()
template<typename First_ , typename... Rest_> template<typename Tv_ , typename... Tw_> DenseVector< DataType, IndexType > FEAT::LAFEM::TupleMirror< First_, Rest_ >::create_buffer (const TupleVector< Tv_, Tw_... > & vector) const inline
Creates a new buffer vector for a TupleVector.
Parameters
[in] vector The vector for which the buffer is to be created.
Definition at line 186 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::buffer_size().
empty()
template<typename First_ , typename... Rest_> bool FEAT::LAFEM::TupleMirror< First_, Rest_ >::empty () const inline
Checks whether the mirror is empty.
Returns
true, if there are no indices in the mirror, otherwise false.
Definition at line 140 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first, FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMirror< First_, Rest_ >::empty().
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates(), and FEAT::LAFEM::TupleMirror< First_, Rest_ >::empty().
gather()
template<typename First_ , typename... Rest_> template<typename Tv_ , typename... Tw_> void FEAT::LAFEM::TupleMirror< First_, Rest_ >::gather (LAFEM::DenseVector< DataType, IndexType > & buffer, const LAFEM::TupleVector< Tv_, Tw_... > & vector, const Index buffer_offset = Index(0)) const inline
Gathers the buffer entries from a DenseVector.
Parameters
[in,out] buffer A reference to the buffer.
[in] vector A vector whose entries are to be gathered.
[in] buffer_offset The offset within the buffer.
Definition at line 215 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first, FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMirror< First_, Rest_ >::gather().
Referenced by FEAT::LAFEM::TupleMirror< First_, Rest_ >::gather().
mask_scatter()
template<typename First_ , typename... Rest_> template<Perspective perspective_, typename Tv_ , typename... Tw_> Index FEAT::LAFEM::TupleMirror< First_, Rest_ >::mask_scatter (const LAFEM::TupleVector< Tv_, Tw_... > & vector, std::vector< int > & mask, const int value, const Index offset = Index(0)) const inline
Updates a scatter mask vector for this mirror.
This function is used to create a so-called "scatter mask vector", i.e. a vector, in which each entry, that belongs to a DOF that is shared with other processes, is set to 1, and all other entries are set to 0 (or vice versa). This mask vector can then be used to determine the number of local and/or shared DOFs for this process.
Parameters
[in] vector A template vector to be used to determine the POD size; must be allocated to correct size but its contents are ignored.
[in,out] mask The mask vector to be updated.
[in] value The value that is to be used to set the mask vector entries referenced by this mirror.
[in] offset The offset of the first native/POD DOF in the mask vector.
Returns
The size of the input template vector.
Definition at line 238 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first, FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest, and FEAT::value.
operator=()
template<typename First_ , typename... Rest_> TupleMirror & FEAT::LAFEM::TupleMirror< First_, Rest_ >::operator= (TupleMirror< First_, Rest_ > && other) inline
move-assign operator
Definition at line 96 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first, and FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest.
scatter_axpy()
template<typename First_ , typename... Rest_> template<typename Tv_ , typename... Tw_> void FEAT::LAFEM::TupleMirror< First_, Rest_ >::scatter_axpy (LAFEM::TupleVector< Tv_, Tw_... > & vector, const LAFEM::DenseVector< DataType, IndexType > & buffer, const DataType alpha = DataType(1), const Index buffer_offset = Index(0)) const inline
Scatters the buffer entries onto a DenseVector.
Parameters
[in,out] vector A reference to the vector.
[in] buffer A reference to the buffer whose entries are to be scattered.
[in] alpha A scaling factor for the operation.
[in] buffer_offset The offset within the buffer.
Definition at line 226 of file tuple_mirror.hpp.
References FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first, FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleMirror< First_, Rest_ >::scatter_axpy().
Referenced by FEAT::LAFEM::TupleMirror< First_, Rest_ >::scatter_axpy().
Friends And Related Function Documentation
TupleMirror
template<typename First_ , typename... Rest_> template<typename , typename... > friend class TupleMirror friend
Definition at line 35 of file tuple_mirror.hpp.
Member Data Documentation
_first
template<typename First_ , typename... Rest_> First_ FEAT::LAFEM::TupleMirror< First_, Rest_ >::_first protected
the first sub-mirror
Definition at line 64 of file tuple_mirror.hpp.
Referenced by FEAT::LAFEM::TupleMirror< First_, Rest_ >::buffer_size(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::clone(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::empty(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::gather(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::mask_scatter(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::operator=(), and FEAT::LAFEM::TupleMirror< First_, Rest_ >::scatter_axpy().
_rest
template<typename First_ , typename... Rest_> RestClass FEAT::LAFEM::TupleMirror< First_, Rest_ >::_rest protected
all remaining sub-mirrors
Definition at line 66 of file tuple_mirror.hpp.
Referenced by FEAT::LAFEM::TupleMirror< First_, Rest_ >::buffer_size(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::clone(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::empty(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::gather(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::mask_scatter(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::operator=(), and FEAT::LAFEM::TupleMirror< First_, Rest_ >::scatter_axpy().
num_blocks
template<typename First_ , typename... Rest_> constexpr int FEAT::LAFEM::TupleMirror< First_, Rest_ >::num_blocks = RestClass::num_blocks + 1 static constexpr
number of mirror blocks
Definition at line 41 of file tuple_mirror.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/tuple_mirror.hpp