FEAT: FEAT::Assembly::GradPresDivVeloAssembler Class Reference
FEAT::Assembly::GradPresDivVeloAssembler Class Reference
Grad(P)/Div(V) assembler class.
#include <gpdv_assembler.hpp>
Static Public Member Functions
template<typename DataType_ , typename IndexType_ , int dim_, typename SpaceVelo_ , typename SpacePres_ >
static void assemble (LAFEM::SparseMatrixBCSR< DataType_, IndexType_, dim_, 1 > &matrix_b, LAFEM::SparseMatrixBCSR< DataType_, IndexType_, 1, dim_ > &matrix_d, const SpaceVelo_ &space_velo, const SpacePres_ &space_pres, const Cubature::DynamicFactory &cubature_factory, const DataType_ scale_b=-DataType_(1), const DataType_ scale_d=-DataType_(1))
Assembles the B and D matrices.
template<typename DataType_ , typename IndexType_ , int dim_, typename SpaceVelo_ , typename SpacePres_ >
static void assemble (LAFEM::SparseMatrixBCSR< DataType_, IndexType_, dim_, 1 > &matrix_b, LAFEM::SparseMatrixBCSR< DataType_, IndexType_, 1, dim_ > &matrix_d, const SpaceVelo_ &space_velo, const SpacePres_ &space_pres, const String &cubature_name, const DataType_ scale_b=-DataType_(1), const DataType_ scale_d=-DataType_(1))
Assembles the B and D matrices.
Detailed Description
Grad(P)/Div(V) assembler class.
This class assembles the two bilinearforms \(\nabla p\) and \(\nabla\cdot v\) of the Stokes equations, from which the weak formulations are obtained by integration by parts, i.e.
\[ b(\psi,\varphi) := - \int_\Omega \psi \nabla \varphi\]
\[ d(\varphi,\psi) := - \int_\Omega (\nabla \cdot \varphi) \psi\]
Note
Both bilinearforms are by default multiplied by -1 to obtain symmetry of the resulting Stokes matrix.
Author
Peter Zajac
Definition at line 33 of file gpdv_assembler.hpp.
Member Function Documentation
assemble() [1/2]
template<typename DataType_ , typename IndexType_ , int dim_, typename SpaceVelo_ , typename SpacePres_ > static void FEAT::Assembly::GradPresDivVeloAssembler::assemble (LAFEM::SparseMatrixBCSR< DataType_, IndexType_, dim_, 1 > & matrix_b, LAFEM::SparseMatrixBCSR< DataType_, IndexType_, 1, dim_ > & matrix_d, const SpaceVelo_ & space_velo, const SpacePres_ & space_pres, const Cubature::DynamicFactory & cubature_factory, const DataType_ scale_b = -DataType_(1), const DataType_ scale_d = -DataType_(1)) inline static
Assembles the B and D matrices.
Parameters
[in,out] matrix_b,matrix_d The transient references to the two matrices to be assembled. If the matrices are empty, their structures are assembled automatically.
[in] space_velo The transient velocity space.
[in] space_pres The transient pressure space.
[in] cubature_factory The cubature factory to be used for integration.
[in] scale_b,scale_d The scaling factors for the matrices. These default to -1 due to integration by parts.
Definition at line 94 of file gpdv_assembler.hpp.
References FEAT::Assembly::SymbolicAssembler::assemble_graph_std2(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::grad, FEAT::jac_det, FEAT::value, and XASSERTM.
assemble() [2/2]
template<typename DataType_ , typename IndexType_ , int dim_, typename SpaceVelo_ , typename SpacePres_ > static void FEAT::Assembly::GradPresDivVeloAssembler::assemble (LAFEM::SparseMatrixBCSR< DataType_, IndexType_, dim_, 1 > & matrix_b, LAFEM::SparseMatrixBCSR< DataType_, IndexType_, 1, dim_ > & matrix_d, const SpaceVelo_ & space_velo, const SpacePres_ & space_pres, const String & cubature_name, const DataType_ scale_b = -DataType_(1), const DataType_ scale_d = -DataType_(1)) inline static
Assembles the B and D matrices.
Parameters
[in,out] matrix_b,matrix_d The transient references to the two matrices to be assembled. If the matrices are empty, their structures are assembled automatically.
[in] space_velo The transient velocity space.
[in] space_pres The transient pressure space.
[in] cubature_name The name of the cubature rule to be used for integration.
[in] scale_b,scale_d The scaling factors for the matrices. These default to -1 due to integration by parts.
Definition at line 58 of file gpdv_assembler.hpp.
References assemble().
Referenced by assemble().
The documentation for this class was generated from the following file:
kernel/assembly/gpdv_assembler.hpp