FEAT: FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ > Class Template Reference
FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ > Class Template Reference
Global Matrix wrapper class template.
#include <matrix.hpp>
Public Types
typedef ColMirror_ ColMirrorType
template<typename LocalMatrix2_ , typename RowMirror2_ = RowMirror_, typename ColMirror2_ = ColMirror_>
using ContainerType = Matrix< LocalMatrix2_, RowMirror2_, ColMirror2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByMDI = Matrix< typename LocalMatrix_::template ContainerType< DataType2_, IndexType2_ >, typename RowMirror_::template MirrorType< DataType2_, IndexType2_ >, typename ColMirror_::template MirrorType< DataType2_, IndexType2_ > >
this typedef lets you create a matrix container with new Datatype and Index types
typedef LocalMatrix_::DataType DataType
typedef Gate< LocalVectorTypeR, ColMirror_ > GateColType
typedef Gate< LocalVectorTypeL, RowMirror_ > GateRowType
typedef LocalMatrix_::IndexType IndexType
typedef LocalMatrix_ LocalMatrixType
typedef LocalMatrix_::VectorTypeL LocalVectorTypeL
typedef LocalMatrix_::VectorTypeR LocalVectorTypeR
typedef RowMirror_ RowMirrorType
typedef Vector< LocalVectorTypeL, RowMirror_ > VectorTypeL
typedef Vector< LocalVectorTypeR, ColMirror_ > VectorTypeR
Public Member Functions
Matrix ()
standard constructor
template<typename... Args_>
Matrix (GateRowType *row_gate, GateColType *col_gate, Args_ &&... args)
Forwarding constructor.
void apply (VectorTypeL &r, const VectorTypeR &x) const
Performs a matrix-vector multiplication: r <- A*x.
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, const DataType alpha=DataType(1)) const
Performs a matrix-vector multiplication: r <- y + alpha*A*x.
auto apply_async (VectorTypeL &r, const VectorTypeR &x) const -> decltype(r.sync_0_async())
Performs a matrix-vector multiplication: r <- A*x.
auto apply_async (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, const DataType alpha=DataType(1)) const -> decltype(r.sync_0_async())
Performs a matrix-vector multiplication: r <- y + alpha*A*x.
std::size_t bytes () const
Returns the total amount of bytes allocated.
Matrix clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a clone of this global matrix.
template<LAFEM::Perspective perspective_ = LAFEM::Perspective::pod>
Index columns () const
Gets the total number of columns in this distributed matrix.
template<typename OtherGlobalMatrix_ >
void convert (GateRowType *row_gate, GateColType *col_gate, const OtherGlobalMatrix_ &other)
LocalMatrix_ convert_to_1 () const
Computes and returns the type-1 conversion of this matrix as a local matrix.
VectorTypeL create_vector_l () const
Creates and returns a new L-compatible global vector object.
VectorTypeR create_vector_r () const
Creates and returns a new R-compatible global vector object.
void extract_diag (VectorTypeL &diag, bool sync=true) const
Extracts the main diagonal of the matrix as a vector.
std::uint64_t get_checkpoint_size (LAFEM::SerialConfig &config)
Calculate size.
const GateColType * get_col_gate () const
Returns a const pointer to the internal column gate of the matrix.
const Dist::Comm * get_comm () const
Returns a const pointer to the internal communicator of the gates of the matrix.
const GateRowType * get_row_gate () const
Returns a const pointer to the internal row gate of the matrix.
LocalMatrix_ & local ()
Returns a reference to the internal local LAFEM matrix object.
const LocalMatrix_ & local () const
Returns a const reference to the internal local LAFEM matrix object.
VectorTypeL lump_rows (bool sync=true) const
Computes and returns the lumped rows of the matrix as a vector.
void lump_rows (VectorTypeL &lump, bool sync=true) const
Computes the lumped rows of the matrix as a vector.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<LAFEM::Perspective perspective_ = LAFEM::Perspective::pod>
Index rows () const
Returns the total number of rows in this distributed matrix.
std::uint64_t set_checkpoint_data (std::vector< char > &data, LAFEM::SerialConfig &config)
template<LAFEM::Perspective perspective_ = LAFEM::Perspective::pod>
Index used_elements () const
Returns the total number of non-zeros in this distributed matrix.
Static Public Attributes
static constexpr bool is_global = true
this is a global matrix class
static constexpr bool is_local = false
this is not a local matrix class
Protected Attributes
GateColType * _col_gate
a pointer to the column gate responsible for synchronization
LocalMatrix_ _matrix
the internal local matrix object
GateRowType * _row_gate
a pointer to the row gate responsible for synchronization
Detailed Description
template<typename LocalMatrix_, typename RowMirror_, typename ColMirror_>
class FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >
Global Matrix wrapper class template.
This class implements a wrapper that contains a LAFEM matrix as its core data object and provides the necessary synchronization functions required in an MPI-parallel simulation based on the overlapping domain decomposition approach. Effectively, this class only couples a local LAFEM matrix with its corresponding pair of row/column Global::Gate objects, which are required to define the compatible L/R vector types, which then take care of the actual synchronization dirty work.
Template Parameters
LocalVector_ The type of the local matrix container; may be any valid combination of LAFEM (meta-)matrix types
RowMirror_ The type of the row mirror; must be compatible to the L-vector type of the local matrix
ColMirror_ The type of the column mirror; must be compatible to the R-vector type of the local matrix
Author
Peter Zajac
Definition at line 41 of file matrix.hpp.
Member Typedef Documentation
ColMirrorType
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef ColMirror_ FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::ColMirrorType
Definition at line 46 of file matrix.hpp.
ContainerType
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > template<typename LocalMatrix2_ , typename RowMirror2_ = RowMirror_, typename ColMirror2_ = ColMirror_> using FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::ContainerType = Matrix<LocalMatrix2_, RowMirror2_, ColMirror2_>
Our 'base' class type.
Definition at line 62 of file matrix.hpp.
ContainerTypeByMDI
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > template<typename DataType2_ , typename IndexType2_ > using FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::ContainerTypeByMDI = Matrix< typename LocalMatrix_::template ContainerType<DataType2_, IndexType2_>, typename RowMirror_::template MirrorType<DataType2_, IndexType2_>, typename ColMirror_::template MirrorType<DataType2_, IndexType2_> >
this typedef lets you create a matrix container with new Datatype and Index types
Definition at line 66 of file matrix.hpp.
DataType
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef LocalMatrix_::DataType FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::DataType
Definition at line 48 of file matrix.hpp.
GateColType
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef Gate<LocalVectorTypeR, ColMirror_> FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::GateColType
Definition at line 58 of file matrix.hpp.
GateRowType
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef Gate<LocalVectorTypeL, RowMirror_> FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::GateRowType
Definition at line 57 of file matrix.hpp.
IndexType
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef LocalMatrix_::IndexType FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::IndexType
Definition at line 49 of file matrix.hpp.
LocalMatrixType
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef LocalMatrix_ FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::LocalMatrixType
Definition at line 44 of file matrix.hpp.
LocalVectorTypeL
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef LocalMatrix_::VectorTypeL FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::LocalVectorTypeL
Definition at line 51 of file matrix.hpp.
LocalVectorTypeR
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef LocalMatrix_::VectorTypeR FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::LocalVectorTypeR
Definition at line 52 of file matrix.hpp.
RowMirrorType
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef RowMirror_ FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::RowMirrorType
Definition at line 45 of file matrix.hpp.
VectorTypeL
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef Vector<LocalVectorTypeL, RowMirror_> FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::VectorTypeL
Definition at line 54 of file matrix.hpp.
VectorTypeR
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > typedef Vector<LocalVectorTypeR, ColMirror_> FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::VectorTypeR
Definition at line 55 of file matrix.hpp.
Constructor & Destructor Documentation
Matrix() [1/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::Matrix () inline
standard constructor
Definition at line 86 of file matrix.hpp.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::clone().
Matrix() [2/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > template<typename... Args_> FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::Matrix (GateRowType * row_gate, GateColType * col_gate, Args_ &&... args) inline explicit
Forwarding constructor.
Parameters
[in] row_gate A resident pointer to the row gate to be used for synchronization
[in] col_gate A resident pointer to the column gate to be used for synchronization
[in] args The arguments that are to be passed to the local matrix object constructor
Attention
The two gates may be different objects, which is e.g. required for matrices which are defined by different test- and trial-spaces in the finite element context, but they always must use the same internal communicator!
Definition at line 111 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate, FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm(), and XASSERT.
Member Function Documentation
apply() [1/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > void FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Performs a matrix-vector multiplication: r <- A*x.
Parameters
[in,out] r A transient reference to the vector that should receive the result of the matrix-vector product. Must be allocated to the correct sizes and must have a valid gate assigned, but its numerical contents upon entry are ignored. Must not be the same object as x.
[in] x A transient reference to the vector that is to be multiplied by this matrix. Must not be the same object as r.
Attention
This function must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 313 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0().
apply() [2/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > void FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, const DataType alpha = DataType(1)) const inline
Performs a matrix-vector multiplication: r <- y + alpha*A*x.
Parameters
[in,out] r A transient reference to the vector that should receive the result of the matrix-vector product. Must be allocated to the correct sizes and must have a valid gate assigned, but its numerical contents upon entry are ignored. Must not be the same object as x, but it may be the same object as y.
[in] x A transient reference to the vector that is to be multiplied by this matrix. Must not be the same object as r.
[in] y A transient reference to the vector that is to be added onto the result of the product. May be the same object as r.
[in] alpha A scaling factor for the matrix-vector product A*x.
Attention
This function must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 365 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, FEAT::Global::Vector< LocalVector_, Mirror_ >::copy(), FEAT::Global::Vector< LocalVector_, Mirror_ >::from_1_to_0(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0().
apply_async() [1/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > auto FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::apply_async (VectorTypeL & r, const VectorTypeR & x) const -> decltype(r.sync_0_async()) inline
Performs a matrix-vector multiplication: r <- A*x.
Parameters
[in,out] r A transient reference to the vector that should receive the result of the matrix-vector product. Must be allocated to the correct sizes and must have a valid gate assigned, but its numerical contents upon entry are ignored. Must not be the same object as x.
[in] x A transient reference to the vector that is to be multiplied by this matrix. Must not be the same object as r.
Returns
A SynchVectorTicket object that waits for the operation to complete.
Attention
This function must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 336 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix.
apply_async() [2/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > auto FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::apply_async (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, const DataType alpha = DataType(1)) const -> decltype(r.sync_0_async()) inline
Performs a matrix-vector multiplication: r <- y + alpha*A*x.
Parameters
[in,out] r A transient reference to the vector that should receive the result of the matrix-vector product. Must be allocated to the correct sizes and must have a valid gate assigned, but its numerical contents upon entry are ignored. Must not be the same object as x, but it may be the same object as y.
[in] x A transient reference to the vector that is to be multiplied by this matrix. Must not be the same object as r.
[in] y A transient reference to the vector that is to be added onto the result of the product. May be the same object as r.
[in] alpha A scaling factor for the matrix-vector product A*x.
Returns
A SynchVectorTicket object that waits for the operation to complete.
Attention
This function must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 405 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, FEAT::Global::Vector< LocalVector_, Mirror_ >::copy(), FEAT::Global::Vector< LocalVector_, Mirror_ >::from_1_to_0(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0_async().
bytes()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > std::size_t FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 267 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate, FEAT::Dist::Comm::allreduce(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm(), FEAT::Dist::op_sum, and FEAT::Dist::Comm::size().
Referenced by FEAT::Control::ScalarMixedSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes().
clone()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > Matrix FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a clone of this global matrix.
Parameters
[in] mode Specifies the clone mode for the internal matrix object.
Returns
The created clone object
Definition at line 189 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::Matrix(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate.
columns()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > template<LAFEM::Perspective perspective_ = LAFEM::Perspective::pod> Index FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::columns () const inline
Gets the total number of columns in this distributed matrix.
Warning
In parallel, this requires communication and is very expensive, so use sparingly!
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Returns
The number of columns of this matrix
Definition at line 225 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate.
convert()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > template<typename OtherGlobalMatrix_ > void FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert (GateRowType * row_gate, GateColType * col_gate, const OtherGlobalMatrix_ & other) inline
Definition at line 144 of file matrix.hpp.
convert_to_1()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > LocalMatrix_ FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1 () const inline
Computes and returns the type-1 conversion of this matrix as a local matrix.
This function performs a type-0 to type-1 conversion of this matrix, which is effectively the matrix counterpart of the type-0 synchronization of a vector, i.e. all matrix entries, which are shared by multiple processes, are replaced by the sum of all contributions from all processes which share the corresponding row/column DOFs. This converted matrix is required for Schwarz-like solver approaches.
Attention
The resulting matrix may (and usually will) have a larger stencil than the original underlying patch-local LAFEM matrix, which is stored in this object's _matrix variable. The reason is that a neighbor process may have additional couplings between DOFs that this process does not have, and these additional coupling are also included in this process's type-1 matrix. However, the stencil of the returned matrix is never smaller than the original local matrix stencil, i.e. the stencil of the patch-local type-0 matrix is always a sub-stencil of the returned type-1 matrix.
Returns
A new local matrix object containing the type-1 matrix for this process patch.
Attention
This function must be called by all processes participating in the gate's communicator, otherwise the application might deadlock.
Definition at line 497 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate, FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate, FEAT::Global::SynchMatrix< MT_, VMT_ >::exec(), FEAT::Global::SynchMatrix< MT_, VMT_ >::init(), and FEAT::LAFEM::Weak.
create_vector_l()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > VectorTypeL FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_l () const inline
Creates and returns a new L-compatible global vector object.
Returns
A new L-compatible global vector that is linked to the row gate of this matrix
Definition at line 199 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::create_vector_l(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::extract_diag(), FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_symbolic(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::lump_rows().
create_vector_r()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > VectorTypeR FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_r () const inline
Creates and returns a new R-compatible global vector object.
Returns
A new R-compatible global vector that is linked to the column gate of this matrix
Definition at line 209 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate, and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::create_vector_r().
extract_diag()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > void FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::extract_diag (VectorTypeL & diag, bool sync = true) const inline
Extracts the main diagonal of the matrix as a vector.
Parameters
[in] diag A transient reference to the vector that shall receive the main diagonal elements
[in] sync Specifies whether the main diagonal vector is to be synchronized to obtain a type-1 vector. If set to false, the resulting vector will be a type-0 vector.
Attention
This function must be called by all processes participating in the gate's communicator, otherwise the application might deadlock.
Definition at line 289 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0().
get_checkpoint_size()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > std::uint64_t FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_checkpoint_size (LAFEM::SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 510 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix.
get_col_gate()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > const GateColType * FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_col_gate () const inline
Returns a const pointer to the internal column gate of the matrix.
Returns
A const pointer to the internal column gate of the matrix.
Definition at line 166 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate.
get_comm()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > const Dist::Comm * FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_comm () const inline
Returns a const pointer to the internal communicator of the gates of the matrix.
Returns
a const pointer to the internal communicator of the gates of the matrix.
Definition at line 176 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate, and FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm().
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_apply(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_comm(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric(), and FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::init_symbolic().
get_row_gate()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > const GateRowType * FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_row_gate () const inline
Returns a const pointer to the internal row gate of the matrix.
Returns
A const pointer to the internal row gate of the matrix.
Definition at line 156 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_symbolic(), and FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic().
local() [1/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > LocalMatrix_ & FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local () inline
Returns a reference to the internal local LAFEM matrix object.
Returns
A reference to the internal local LAFEM matrix object.
Definition at line 128 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_grad_div_matrices(), FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::bytes(), FEAT::Control::ScalarBasicSystemLevel< DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::bytes(), FEAT::Control::Stokes3FieldSystemLevel< dim_, nsc_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, MatrixBlockM_, MatrixBlockK_, MatrixBlockL_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_, TransferMatrixS_ >::bytes(), FEAT::Control::StokesBlockedSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), FEAT::Control::StokesBlockedUnitVeloMeanPresSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), FEAT::Control::StokesPowerUnitVeloNonePresSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_ >::bytes(), FEAT::Control::StokesPowerUnitVeloMeanPresSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_ >::bytes(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_symbolic(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic().
local() [2/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > const LocalMatrix_ & FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local () const inline
Returns a const reference to the internal local LAFEM matrix object.
Returns
A const reference to the internal local LAFEM matrix object.
Definition at line 138 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix.
lump_rows() [1/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > VectorTypeL FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::lump_rows (bool sync = true) const inline
Computes and returns the lumped rows of the matrix as a vector.
Each entry of the lumped rows vector contains the sum of all matrix elements in the corresponding row of this matrix.
Parameters
[in] sync Specifies whether the lumped rows vector is to be synchronized to obtain a type-1 vector. If set to false, the resulting vector will be a type-0 vector.
Returns
A new vector containing the lumped row elements of this matrix.
Attention
This function must be called by all processes participating in the gate's communicator, otherwise the application might deadlock.
Definition at line 464 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_l(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::lump_rows().
lump_rows() [2/2]
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > void FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::lump_rows (VectorTypeL & lump, bool sync = true) const inline
Computes the lumped rows of the matrix as a vector.
Each entry of the lumped rows vector contains the sum of all matrix elements in the corresponding row of this matrix.
Parameters
[in] lump A transient reference to the vector that shall receive the lumped row elements
[in] sync Specifies whether the lumped rows vector is to be synchronized to obtain a type-1 vector. If set to false, the resulting vector will be a type-0 vector.
Attention
This function must be called by all processes participating in the gate's communicator, otherwise the application might deadlock.
Definition at line 436 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0(), and XASSERTM.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::lump_rows().
restore_from_checkpoint_data()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > void FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 516 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix.
rows()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > template<LAFEM::Perspective perspective_ = LAFEM::Perspective::pod> Index FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::rows () const inline
Returns the total number of rows in this distributed matrix.
Warning
In parallel, this requires communication and is very expensive, so use sparingly!
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Returns
The number of rows of this matrix
Definition at line 241 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate.
set_checkpoint_data()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > std::uint64_t FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::set_checkpoint_data (std::vector< char > & data, LAFEM::SerialConfig & config) inline
Definition at line 522 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix.
used_elements()
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > template<LAFEM::Perspective perspective_ = LAFEM::Perspective::pod> Index FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::used_elements () const inline
Returns the total number of non-zeros in this distributed matrix.
Warning
In parallel, this requires communication and is very expensive, so use sparingly!
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Returns
The total number of non-zeros in this matrix
Definition at line 257 of file matrix.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate, FEAT::Dist::Comm::allreduce(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm(), FEAT::Dist::op_sum, and FEAT::Dist::Comm::size().
Member Data Documentation
_col_gate
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > GateColType* FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_col_gate protected
a pointer to the column gate responsible for synchronization
Definition at line 80 of file matrix.hpp.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::Matrix(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::bytes(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::clone(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::columns(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_r(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_col_gate(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::used_elements().
_matrix
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > LocalMatrix_ FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_matrix protected
the internal local matrix object
Definition at line 82 of file matrix.hpp.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::apply(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::apply_async(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::bytes(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::clone(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_l(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_r(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::extract_diag(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_checkpoint_size(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::lump_rows(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::restore_from_checkpoint_data(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::set_checkpoint_data(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::used_elements().
_row_gate
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > GateRowType* FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::_row_gate protected
a pointer to the row gate responsible for synchronization
Definition at line 78 of file matrix.hpp.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::Matrix(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::bytes(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::clone(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_l(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_comm(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_row_gate(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::rows(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::used_elements().
is_global
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > constexpr bool FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::is_global = true static constexpr
this is a global matrix class
Definition at line 72 of file matrix.hpp.
is_local
template<typename LocalMatrix_ , typename RowMirror_ , typename ColMirror_ > constexpr bool FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::is_local = false static constexpr
this is not a local matrix class
Definition at line 74 of file matrix.hpp.
The documentation for this class was generated from the following file:
kernel/global/matrix.hpp