FEAT: FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ > Class Template Reference
FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ > Class Template Reference
Tuple-Diag-Matrix meta class template.
#include <tuple_diag_matrix.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = TupleDiagMatrix< typename First_::template ContainerType< DT2_, IT2_ >, typename Rest_::template ContainerType< DT2_, IT2_ >... >
Our 'base' class type.
template<typename DT2_ , typename IT2_ >
using ContainerTypeByDI = TupleDiagMatrix< typename First_::template ContainerType< DT2_, IT2_ >, typename Rest_::template ContainerType< DT2_, IT2_ >... >
this typedef lets you create a matrix container with new Datatape and Index types
typedef First_::DataType DataType
sub-matrix data type
typedef First_::IndexType IndexType
sub-matrix index type
typedef TupleVector< typename First_::VectorTypeL, typename Rest_::VectorTypeL... > VectorTypeL
Compatible L-vector type.
typedef TupleVector< typename First_::VectorTypeR, typename Rest_::VectorTypeR... > VectorTypeR
Compatible R-vector type.
Public Member Functions
TupleDiagMatrix ()
default ctor
TupleDiagMatrix (const TupleDiagMatrix &)=delete
deleted copy-ctor
TupleDiagMatrix (FileMode mode, const String &filename)
Constructor.
TupleDiagMatrix (FileMode mode, std::istream &file, const String &directory="")
Constructor.
TupleDiagMatrix (First_ &&the_first, Rest_ &&... the_rest)
Sub-Matrix emplacement constructor.
TupleDiagMatrix (TupleDiagMatrix &&other)
move ctor
virtual ~TupleDiagMatrix ()
virtual destructor
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply (VectorTypeL &r, const VectorTypeR &x) const
Applies this matrix onto a vector.
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
template<int i_, int j_>
TupleElement< i_, First_, Rest_... >::Type & at ()
Returns a sub-matrix block.
template<int i_, int j_>
const TupleElement< i_, First_, Rest_... >::Type & at () const
Returns a sub-matrix block.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
TupleDiagMatrix clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a deep copy of this matrix.
Index columns () const
Returns the total number of columns in this matrix.
template<typename First2_ , typename... Rest2_>
void convert (const TupleDiagMatrix< First2_, Rest2_... > &other)
Conversion method.
template<typename First2_ , typename... Rest2_>
void convert_reverse (TupleDiagMatrix< First2_, Rest2_... > &other) const
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
void extract_diag (VectorTypeL &diag) const
extract main diagonal vector from matrix
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
Index get_length_of_line (const Index row) const
Returns the number of NNZ-elements of the selected row.
TupleDiagMatrix & operator= (const TupleDiagMatrix &)=delete
deleted copy-assign operator
TupleDiagMatrix & operator= (TupleDiagMatrix &&other)
move-assign operator
void read_from (FileMode mode, const String &filename)
Read in matrix from file.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
Index rows () const
Returns the total number of rows in this matrix.
void scale_cols (const TupleDiagMatrix &a, const VectorTypeR &w)
void scale_rows (const TupleDiagMatrix &a, const VectorTypeL &w)
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
Index size () const
TupleDiagMatrix transpose () const
Creates and returns the transpose of this matrix.
Index used_elements () const
Returns the total number of non-zeros in this matrix.
void write_out (FileMode mode, String filename) const
Write out matrix to file.
void write_out_submatrices (FileMode mode, const String &directory, const String &prefix, const String &suffix, Index length=num_row_blocks) const
Write out submatrices to file.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr int num_col_blocks = RestClass::num_col_blocks + 1
number of column blocks (horizontal size)
static constexpr int num_row_blocks = RestClass::num_row_blocks + 1
number of row blocks (vertical size)
Protected Member Functions
TupleDiagMatrix (First_ &&the_first, RestClass &&the_rest)
base-class constructor; this one is protected for a reason
Static Protected Member Functions
static String sub_name_list ()
Returns a list of all sub-matrix type names.
Protected Attributes
First_ _first
the first sub-matrix
RestClass _rest
the remaining part
Private Types
typedef TupleDiagMatrix< Rest_... > RestClass
rest-class typedef
Friends
bool operator== (const TupleDiagMatrix &a, const TupleDiagMatrix &b)
TupleDiagMatrix comparison operator.
Detailed Description
template<typename First_, typename... Rest_>
class FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >
Tuple-Diag-Matrix meta class template.
This class template implements a diagonal composition of n sub-matrices of arbitrary classes. This can be interpreted as a diagonal m-by-m matrix of other matrices.
Template Parameters
First_,...Rest_ A sequence of (meta) matrix classes which are to be composed.
Author
Peter Zajac
Definition at line 36 of file tuple_diag_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename First_ , typename... Rest_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::ContainerType = TupleDiagMatrix< typename First_::template ContainerType<DT2_, IT2_>, typename Rest_::template ContainerType<DT2_, IT2_>...>
Our 'base' class type.
Definition at line 58 of file tuple_diag_matrix.hpp.
ContainerTypeByDI
template<typename First_ , typename... Rest_> template<typename DT2_ , typename IT2_ > using FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::ContainerTypeByDI = TupleDiagMatrix< typename First_::template ContainerType<DT2_, IT2_>, typename Rest_::template ContainerType<DT2_, IT2_>...>
this typedef lets you create a matrix container with new Datatape and Index types
Definition at line 64 of file tuple_diag_matrix.hpp.
DataType
template<typename First_ , typename... Rest_> typedef First_::DataType FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::DataType
sub-matrix data type
Definition at line 47 of file tuple_diag_matrix.hpp.
IndexType
template<typename First_ , typename... Rest_> typedef First_::IndexType FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::IndexType
sub-matrix index type
Definition at line 49 of file tuple_diag_matrix.hpp.
RestClass
template<typename First_ , typename... Rest_> typedef TupleDiagMatrix<Rest_...> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::RestClass private
rest-class typedef
Definition at line 43 of file tuple_diag_matrix.hpp.
VectorTypeL
template<typename First_ , typename... Rest_> typedef TupleVector<typename First_::VectorTypeL, typename Rest_::VectorTypeL...> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::VectorTypeL
Compatible L-vector type.
Definition at line 52 of file tuple_diag_matrix.hpp.
VectorTypeR
template<typename First_ , typename... Rest_> typedef TupleVector<typename First_::VectorTypeR, typename Rest_::VectorTypeR...> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::VectorTypeR
Compatible R-vector type.
Definition at line 54 of file tuple_diag_matrix.hpp.
Constructor & Destructor Documentation
TupleDiagMatrix() [1/6]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix (First_ && the_first, RestClass && the_rest) inline explicit protected
base-class constructor; this one is protected for a reason
Definition at line 80 of file tuple_diag_matrix.hpp.
TupleDiagMatrix() [2/6]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix () inline
default ctor
Definition at line 94 of file tuple_diag_matrix.hpp.
TupleDiagMatrix() [3/6]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix (First_ && the_first, Rest_ &&... the_rest) inline explicit
Sub-Matrix emplacement constructor.
Definition at line 99 of file tuple_diag_matrix.hpp.
TupleDiagMatrix() [4/6]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix (TupleDiagMatrix< First_, Rest_ > && other) inline
move ctor
Definition at line 106 of file tuple_diag_matrix.hpp.
TupleDiagMatrix() [5/6]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix (FileMode mode, const String & filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a tuple-diag-point-matrix based on the source file.
Definition at line 120 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::read_from().
TupleDiagMatrix() [6/6]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix (FileMode mode, std::istream & file, const String & directory = "") inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Note
This constructor is used internally when reading a file
Creates a tuple-diag-matrix based on the source filestream.
Definition at line 135 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, FEAT::String::trim_me(), and XABORTM.
~TupleDiagMatrix()
template<typename First_ , typename... Rest_> virtual FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::~TupleDiagMatrix () inline virtual
virtual destructor
Definition at line 198 of file tuple_diag_matrix.hpp.
Member Function Documentation
apply() [1/4]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 409 of file tuple_diag_matrix.hpp.
apply() [2/4]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 446 of file tuple_diag_matrix.hpp.
apply() [3/4]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 403 of file tuple_diag_matrix.hpp.
apply() [4/4]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 440 of file tuple_diag_matrix.hpp.
at() [1/2]
template<typename First_ , typename... Rest_> template<int i_, int j_> TupleElement< i_, First_, Rest_... >::Type & FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::at () inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 288 of file tuple_diag_matrix.hpp.
at() [2/2]
template<typename First_ , typename... Rest_> template<int i_, int j_> const TupleElement< i_, First_, Rest_... >::Type & FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::at () const inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 296 of file tuple_diag_matrix.hpp.
bytes()
template<typename First_ , typename... Rest_> std::size_t FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 262 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::bytes().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::bytes().
clear()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::clear () inline
Free all allocated arrays.
Definition at line 378 of file tuple_diag_matrix.hpp.
clone()
template<typename First_ , typename... Rest_> TupleDiagMatrix FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a deep copy of this matrix.
Definition at line 256 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::clone().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::clone().
columns()
template<typename First_ , typename... Rest_> Index FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::columns () const inline
Returns the total number of columns in this matrix.
Definition at line 341 of file tuple_diag_matrix.hpp.
convert()
template<typename First_ , typename... Rest_> template<typename First2_ , typename... Rest2_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::convert (const TupleDiagMatrix< First2_, Rest2_... > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 580 of file tuple_diag_matrix.hpp.
convert_reverse()
template<typename First_ , typename... Rest_> template<typename First2_ , typename... Rest2_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::convert_reverse (TupleDiagMatrix< First2_, Rest2_... > & other) const inline
Definition at line 587 of file tuple_diag_matrix.hpp.
create_vector_l()
template<typename First_ , typename... Rest_> VectorTypeL FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 467 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::create_vector_l().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::create_vector_l().
create_vector_r()
template<typename First_ , typename... Rest_> VectorTypeR FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 473 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::create_vector_r().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::create_vector_r().
extract_diag()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::extract_diag (VectorTypeL & diag) const inline
extract main diagonal vector from matrix
Definition at line 385 of file tuple_diag_matrix.hpp.
format()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the matrix' entries are to be set to.
Definition at line 369 of file tuple_diag_matrix.hpp.
References FEAT::value.
get_checkpoint_size()
template<typename First_ , typename... Rest_> std::uint64_t FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 539 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::get_checkpoint_size().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::get_checkpoint_size().
get_length_of_line()
template<typename First_ , typename... Rest_> Index FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::get_length_of_line (const Index row) const inline
Returns the number of NNZ-elements of the selected row.
Definition at line 491 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::rows().
name()
template<typename First_ , typename... Rest_> static String FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 353 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::sub_name_list().
operator=()
template<typename First_ , typename... Rest_> TupleDiagMatrix & FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::operator= (TupleDiagMatrix< First_, Rest_ > && other) inline
move-assign operator
Definition at line 182 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest.
read_from()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::read_from (FileMode mode, const String & filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 155 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, and XABORTM.
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix().
restore_from_checkpoint_data()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 545 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::restore_from_checkpoint_data().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::restore_from_checkpoint_data().
rows()
template<typename First_ , typename... Rest_> Index FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::rows () const inline
Returns the total number of rows in this matrix.
Definition at line 335 of file tuple_diag_matrix.hpp.
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::get_length_of_line().
scale_cols()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::scale_cols (const TupleDiagMatrix< First_, Rest_ > & a, const VectorTypeR & w) inline
Definition at line 484 of file tuple_diag_matrix.hpp.
scale_rows()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::scale_rows (const TupleDiagMatrix< First_, Rest_ > & a, const VectorTypeL & w) inline
Definition at line 478 of file tuple_diag_matrix.hpp.
set_checkpoint_data()
template<typename First_ , typename... Rest_> std::uint64_t FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 558 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::set_checkpoint_data().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::set_checkpoint_data().
size()
template<typename First_ , typename... Rest_> Index FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::size () const inline
Definition at line 358 of file tuple_diag_matrix.hpp.
sub_name_list()
template<typename First_ , typename... Rest_> static String FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::sub_name_list () inline static protected
Returns a list of all sub-matrix type names.
Definition at line 87 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::sub_name_list().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::name(), and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::sub_name_list().
transpose()
template<typename First_ , typename... Rest_> TupleDiagMatrix FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::transpose () const inline
Creates and returns the transpose of this matrix.
Definition at line 270 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::transpose().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::transpose().
used_elements()
template<typename First_ , typename... Rest_> Index FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::used_elements () const inline
Returns the total number of non-zeros in this matrix.
Definition at line 347 of file tuple_diag_matrix.hpp.
write_out()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out (FileMode mode, String filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 208 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::num_row_blocks, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out_submatrices(), and XABORTM.
write_out_submatrices()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out_submatrices (FileMode mode, const String & directory, const String & prefix, const String & suffix, Index length = num_row_blocks) const inline
Write out submatrices to file.
Parameters
[in] mode The used file format.
[in] directory The directory of the matrix-files.
[in] prefix The prefix of the matrix-files.
[in] suffix The suffix of the matrix-files.
Definition at line 247 of file tuple_diag_matrix.hpp.
References FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest, FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::num_row_blocks, FEAT::stringify(), and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out_submatrices().
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out(), and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out_submatrices().
Friends And Related Function Documentation
TupleDiagMatrix
template<typename First_ , typename... Rest_> template<typename , typename... > friend class TupleDiagMatrix friend
Definition at line 40 of file tuple_diag_matrix.hpp.
operator==
template<typename First_ , typename... Rest_> bool operator== (const TupleDiagMatrix< First_, Rest_ > & a, const TupleDiagMatrix< First_, Rest_ > & b) friend
TupleDiagMatrix comparison operator.
Parameters
[in] a A matrix to compare with.
[in] b A matrix to compare with.
Definition at line 600 of file tuple_diag_matrix.hpp.
Member Data Documentation
_first
template<typename First_ , typename... Rest_> First_ FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_first protected
the first sub-matrix
Definition at line 75 of file tuple_diag_matrix.hpp.
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::clone(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::get_checkpoint_size(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::operator=(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::read_from(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::restore_from_checkpoint_data(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::set_checkpoint_data(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::transpose(), and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out_submatrices().
_rest
template<typename First_ , typename... Rest_> RestClass FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::_rest protected
the remaining part
Definition at line 77 of file tuple_diag_matrix.hpp.
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::TupleDiagMatrix(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::clone(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::get_checkpoint_size(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::operator=(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::read_from(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::restore_from_checkpoint_data(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::set_checkpoint_data(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::transpose(), and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out_submatrices().
num_col_blocks
template<typename First_ , typename... Rest_> constexpr int FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::num_col_blocks = RestClass::num_col_blocks + 1 static constexpr
number of column blocks (horizontal size)
Definition at line 71 of file tuple_diag_matrix.hpp.
num_row_blocks
template<typename First_ , typename... Rest_> constexpr int FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::num_row_blocks = RestClass::num_row_blocks + 1 static constexpr
number of row blocks (vertical size)
Definition at line 69 of file tuple_diag_matrix.hpp.
Referenced by FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out(), and FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out_submatrices().
The documentation for this class was generated from the following file:
kernel/lafem/tuple_diag_matrix.hpp