FEAT: FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ > Class Template Reference
FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ > Class Template Reference
Implementation of ADPSolverBase interface for Global::Matrix instances.
#include <adp_solver_base.hpp>
Public Types
typedef Global::AlgDofPartiMatrix< LocalMatrixType, MirrorType > ADPMatrixType
typedef Global::AlgDofPartiVector< LocalVectorType, MirrorType > ADPVectorType
typedef Global::AlgDofParti< LocalVectorType, MirrorType > AlgDofPartiType
typedef SolverBase_ BaseClass
typedef AlgDofPartiType::DataType DataType
typedef GlobalFilter_ GlobalFilterType
typedef Global::Matrix< LocalMatrixType, MirrorType, MirrorType > GlobalMatrixType
typedef Global::Vector< LocalVectorType, MirrorType > GlobalVectorType
typedef AlgDofPartiType::IndexType IndexType
typedef LocalMatrix_ LocalMatrixType
typedef LocalMatrixType::VectorTypeL LocalVectorType
typedef Mirror_ MirrorType
typedef GlobalVectorType VectorType
Public Member Functions
const Dist::Comm * _get_comm () const
virtual void done_symbolic () override
virtual void init_numeric () override
Numeric Initialization.
virtual void init_symbolic () override
Symbolic Initialization.
Protected Member Functions
ADPSolverBase (const GlobalMatrixType &matrix, const GlobalFilterType &filter)
void _download_vec_cor (VectorType &vec_cor)
void _download_vec_def (VectorType &vec_def)
Index _get_global_dof_offset () const
const IndexType * _get_mat_col_idx () const
Index _get_mat_num_nze () const
const IndexType * _get_mat_row_ptr () const
const DataType * _get_mat_vals () const
Index _get_num_global_dofs () const
Index _get_num_owned_dofs () const
DataType * _get_vec_cor_vals (VectorType &)
const DataType * _get_vec_def_vals (const VectorType &)
DataType * _get_vec_def_vals (VectorType &)
void _upload_vec_cor (const VectorType &vec_cor)
void _upload_vec_def (const VectorType &vec_def)
Protected Attributes
const GlobalFilterType & _system_filter
the global system filter
const GlobalMatrixType & _system_matrix
the global system matrix
Private Attributes
ADPMatrixType _adp_matrix
the ADP matrix
ADPVectorType _adp_vec_cor
ADPVectorType _adp_vec_def
two ADP vectors for correction and defect vectors
AlgDofPartiType _alg_dof_parti
the algebraic DOF partitioning
Detailed Description
template<typename LocalMatrix_, typename Mirror_, typename GlobalFilter_, typename SolverBase_>
class FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >
Implementation of ADPSolverBase interface for Global::Matrix instances.
This class implements the ADPSolverBase interface for Global::Matrix instances, which derive from standard (scalar) finite element discretizations. Most of the dirty work is outsourced to the Global::AlgDofParti, Global::AlgDofPartiVector and Global::AlgDoPartiMatrix classes.
Note
Although this class does not explicitly expect the local matrix to be a LAFEM::SparseMatrixCSR, this is (currently) the only matrix type that is supported by the underlying Global::AlgDofParti class template.
Author
Peter Zajac
Definition at line 119 of file adp_solver_base.hpp.
Member Typedef Documentation
ADPMatrixType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef Global::AlgDofPartiMatrix<LocalMatrixType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::ADPMatrixType
Definition at line 138 of file adp_solver_base.hpp.
ADPVectorType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef Global::AlgDofPartiVector<LocalVectorType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::ADPVectorType
Definition at line 139 of file adp_solver_base.hpp.
AlgDofPartiType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef Global::AlgDofParti<LocalVectorType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::AlgDofPartiType
Definition at line 137 of file adp_solver_base.hpp.
BaseClass
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef SolverBase_ FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::BaseClass
Definition at line 133 of file adp_solver_base.hpp.
DataType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef AlgDofPartiType::DataType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::DataType
Definition at line 141 of file adp_solver_base.hpp.
GlobalFilterType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef GlobalFilter_ FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::GlobalFilterType
Definition at line 130 of file adp_solver_base.hpp.
GlobalMatrixType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef Global::Matrix<LocalMatrixType, MirrorType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::GlobalMatrixType
Definition at line 128 of file adp_solver_base.hpp.
GlobalVectorType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef Global::Vector<LocalVectorType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::GlobalVectorType
Definition at line 129 of file adp_solver_base.hpp.
IndexType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef AlgDofPartiType::IndexType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::IndexType
Definition at line 142 of file adp_solver_base.hpp.
LocalMatrixType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef LocalMatrix_ FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::LocalMatrixType
Definition at line 124 of file adp_solver_base.hpp.
LocalVectorType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef LocalMatrixType::VectorTypeL FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::LocalVectorType
Definition at line 125 of file adp_solver_base.hpp.
MirrorType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef Mirror_ FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::MirrorType
Definition at line 126 of file adp_solver_base.hpp.
VectorType
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > typedef GlobalVectorType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::VectorType
Definition at line 135 of file adp_solver_base.hpp.
Constructor & Destructor Documentation
ADPSolverBase()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::ADPSolverBase (const GlobalMatrixType & matrix, const GlobalFilterType & filter) inline explicit protected
Definition at line 158 of file adp_solver_base.hpp.
Member Function Documentation
_download_vec_cor()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_download_vec_cor (VectorType & vec_cor) inline protected
Definition at line 296 of file adp_solver_base.hpp.
_download_vec_def()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_download_vec_def (VectorType & vec_def) inline protected
Definition at line 291 of file adp_solver_base.hpp.
_get_comm()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > const Dist::Comm * FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_comm () const inline
Returns
A pointer to the underlying communicator
Definition at line 171 of file adp_solver_base.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_comm().
_get_global_dof_offset()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_global_dof_offset () const inline protected
Definition at line 241 of file adp_solver_base.hpp.
_get_mat_col_idx()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > const IndexType * FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_mat_col_idx () const inline protected
Definition at line 261 of file adp_solver_base.hpp.
_get_mat_num_nze()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_mat_num_nze () const inline protected
Definition at line 246 of file adp_solver_base.hpp.
_get_mat_row_ptr()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > const IndexType * FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_mat_row_ptr () const inline protected
Definition at line 256 of file adp_solver_base.hpp.
_get_mat_vals()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > const DataType * FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_mat_vals () const inline protected
Definition at line 251 of file adp_solver_base.hpp.
_get_num_global_dofs()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_num_global_dofs () const inline protected
Definition at line 236 of file adp_solver_base.hpp.
_get_num_owned_dofs()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_num_owned_dofs () const inline protected
Definition at line 231 of file adp_solver_base.hpp.
_get_vec_cor_vals()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > DataType * FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_vec_cor_vals (VectorType &) inline protected
Definition at line 276 of file adp_solver_base.hpp.
_get_vec_def_vals() [1/2]
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > const DataType * FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_vec_def_vals (const VectorType &) inline protected
Definition at line 266 of file adp_solver_base.hpp.
_get_vec_def_vals() [2/2]
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > DataType * FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_get_vec_def_vals (VectorType &) inline protected
Definition at line 271 of file adp_solver_base.hpp.
_upload_vec_cor()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_upload_vec_cor (const VectorType & vec_cor) inline protected
Definition at line 286 of file adp_solver_base.hpp.
_upload_vec_def()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_upload_vec_def (const VectorType & vec_def) inline protected
Definition at line 281 of file adp_solver_base.hpp.
done_symbolic()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > virtual void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::done_symbolic () inline override virtual
Definition at line 220 of file adp_solver_base.hpp.
init_numeric()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > virtual void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_numeric () inline override virtual
Numeric Initialization.
This function uploads the numeric matrix values and applies the filter onto the ADP matrix.
Definition at line 209 of file adp_solver_base.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
init_symbolic()
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > virtual void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic () inline override virtual
Symbolic Initialization.
This function assembles the algebraic DOF partitioning, creates the ADP matrix, uploads the matrix structure and creates the two ADP vectors.
Definition at line 182 of file adp_solver_base.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_row_gate(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::owned(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::owned(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic().
Member Data Documentation
_adp_matrix
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > ADPMatrixType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_adp_matrix private
the ADP matrix
Definition at line 148 of file adp_solver_base.hpp.
_adp_vec_cor
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > ADPVectorType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_adp_vec_cor private
Definition at line 150 of file adp_solver_base.hpp.
_adp_vec_def
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > ADPVectorType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_adp_vec_def private
two ADP vectors for correction and defect vectors
Definition at line 150 of file adp_solver_base.hpp.
_alg_dof_parti
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > AlgDofPartiType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_alg_dof_parti private
the algebraic DOF partitioning
Definition at line 146 of file adp_solver_base.hpp.
_system_filter
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > const GlobalFilterType& FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_system_filter protected
the global system filter
Definition at line 156 of file adp_solver_base.hpp.
_system_matrix
template<typename LocalMatrix_ , typename Mirror_ , typename GlobalFilter_ , typename SolverBase_ > const GlobalMatrixType& FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::_system_matrix protected
the global system matrix
Definition at line 154 of file adp_solver_base.hpp.
The documentation for this class was generated from the following file:
kernel/solver/adp_solver_base.hpp