FEAT: FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > > Class Template Reference
FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > > Class Template Reference
Schwarz preconditioner specialization for Global::Vector.
#include <schwarz_precond.hpp>
Public Types
typedef SolverBase< Global::Vector< LocalVector_, Mirror_ > > BaseClass
base-class typedef
typedef Global::Filter< LocalFilter_, Mirror_ > GlobalFilterType
our global filter type
typedef Global::Vector< LocalVector_, Mirror_ > GlobalVectorType
our global vector type
typedef SolverBase< LocalVector_ > LocalSolverType
the local solver interface
typedef LocalVector_ LocalVectorType
our local vector type
typedef Global::Vector< LocalVector_, Mirror_ > VectorType
The type of vector this solver can be applied to.
Public Member Functions
SchwarzPrecond (const String &section_name, PropertyMap *section, std::shared_ptr< LocalSolverType > local_solver, const GlobalFilterType &filter)
Constructor using a PropertyMap.
SchwarzPrecond (std::shared_ptr< LocalSolverType > local_solver, const GlobalFilterType &filter)
Constructor.
virtual Status apply (GlobalVectorType &vec_cor, const GlobalVectorType &vec_def) override
Solver application method.
virtual void done ()
Finalization method.
virtual void done_numeric () override
Numeric finalization method.
virtual void done_symbolic () override
Symbolic finalization method.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric initialization method.
virtual void init_symbolic () override
Symbolic initialization method.
virtual String name () const override
Returns the name of the solver.
Protected Attributes
const GlobalFilterType & _filter
our global filter
std::shared_ptr< LocalSolverType > _local_solver
our local solver object
Detailed Description
template<typename LocalVector_, typename LocalFilter_, typename Mirror_>
class FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >
Schwarz preconditioner specialization for Global::Vector.
This class template implements an additive Schwarz preconditioner, i.e. this class implements a global preconditioner by synchronously adding (and averaging) a set of local solutions.
Template Parameters
LocalVector_ The type of the local vector nested in a global vector.
Definition at line 44 of file schwarz_precond.hpp.
Member Typedef Documentation
BaseClass
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > typedef SolverBase<Global::Vector<LocalVector_, Mirror_> > FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::BaseClass
base-class typedef
Definition at line 55 of file schwarz_precond.hpp.
GlobalFilterType
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > typedef Global::Filter<LocalFilter_, Mirror_> FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::GlobalFilterType
our global filter type
Definition at line 53 of file schwarz_precond.hpp.
GlobalVectorType
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > typedef Global::Vector<LocalVector_, Mirror_> FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::GlobalVectorType
our global vector type
Definition at line 51 of file schwarz_precond.hpp.
LocalSolverType
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > typedef SolverBase<LocalVector_> FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::LocalSolverType
the local solver interface
Definition at line 58 of file schwarz_precond.hpp.
LocalVectorType
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > typedef LocalVector_ FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::LocalVectorType
our local vector type
Definition at line 49 of file schwarz_precond.hpp.
VectorType
typedef Global::Vector< LocalVector_, Mirror_ > FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >::VectorType inherited
The type of vector this solver can be applied to.
Definition at line 188 of file base.hpp.
Constructor & Destructor Documentation
SchwarzPrecond() [1/2]
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::SchwarzPrecond (std::shared_ptr< LocalSolverType > local_solver, const GlobalFilterType & filter) inline explicit
Constructor.
Parameters
[in] local_solver The local solver that is to be used by the Schwarz preconditioner.
Definition at line 73 of file schwarz_precond.hpp.
SchwarzPrecond() [2/2]
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::SchwarzPrecond (const String & section_name, PropertyMap * section, std::shared_ptr< LocalSolverType > local_solver, const GlobalFilterType & filter) inline explicit
Constructor using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] local_solver The local solver that is to be used by the Schwarz preconditioner.
Definition at line 91 of file schwarz_precond.hpp.
Member Function Documentation
apply()
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > virtual Status FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::apply (GlobalVectorType & vec_cor, const GlobalVectorType & vec_def) inline override virtual
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implements FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >.
Definition at line 125 of file schwarz_precond.hpp.
References FEAT::Solver::aborted, FEAT::Dist::Comm::allreduce(), FEAT::Global::Vector< LocalVector_, Mirror_ >::get_comm(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Dist::op_sum, FEAT::Solver::status_success(), FEAT::Solver::success, FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_1(), and XASSERT.
done()
virtual void FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 285 of file base.hpp.
done_numeric()
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > virtual void FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::done_numeric () inline override virtual
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >.
Definition at line 115 of file schwarz_precond.hpp.
done_symbolic()
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > virtual void FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::done_symbolic () inline override virtual
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >.
Definition at line 120 of file schwarz_precond.hpp.
init()
virtual void FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 270 of file base.hpp.
init_numeric()
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > virtual void FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::init_numeric () inline override virtual
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >.
Definition at line 110 of file schwarz_precond.hpp.
init_symbolic()
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > virtual void FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::init_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >.
Definition at line 105 of file schwarz_precond.hpp.
name()
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > virtual String FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SolverBase< Global::Vector< LocalVector_, Mirror_ > >.
Definition at line 100 of file schwarz_precond.hpp.
Member Data Documentation
_filter
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > const GlobalFilterType& FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::_filter protected
our global filter
Definition at line 64 of file schwarz_precond.hpp.
_local_solver
template<typename LocalVector_ , typename LocalFilter_ , typename Mirror_ > std::shared_ptr<LocalSolverType> FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::_local_solver protected
our local solver object
Definition at line 62 of file schwarz_precond.hpp.
The documentation for this class was generated from the following file:
kernel/solver/schwarz_precond.hpp