FEAT: FEAT::Global::AlgDofParti< LocalVector_, Mirror_ > Class Template Reference
FEAT::Global::AlgDofParti< LocalVector_, Mirror_ > Class Template Reference
Algebraic DOF Partitioning implementation.
#include <alg_dof_parti.hpp>
Public Types
typedef Intern::ADPAux< IndexVectorType > ADPAuxType
auxiliary helper class type
typedef LAFEM::DenseVector< DataType, IndexType > BufferVectorType
the type for buffers used by our mirrors
typedef LocalVectorType::DataType DataType
our data type
typedef LAFEM::VectorMirror< DataType, IndexType > DoneeMirrorType
type of mirror for neighbor donee owned dof indices
typedef Global::Gate< LocalVectorType, MirrorType > GateType
the global gate type
typedef Global::Vector< LocalVectorType, MirrorType > GlobalVectorType
the global vector type
typedef LocalVectorType::IndexType IndexType
our index type
typedef LocalVectorType::template ContainerTypeByDI< IndexType, IndexType > IndexVectorType
the index vector type, this one is required for internal computations
typedef LocalVector_ LocalVectorType
the local vector type
typedef Mirror_ MirrorType
the vector mirror type
typedef MirrorType OwnedMirrorType
type of mirror for owned local dof indices
typedef MirrorType OwnerMirrorType
type of mirror for neighbor owner local dof indices
Public Member Functions
AlgDofParti ()
default constructor
AlgDofParti (const AlgDofParti &)=delete
no copy, no problems
virtual ~AlgDofParti ()=default
virtual destructor
void assemble_allgather (bool yes_i_really_want_to_do_this=false)
Assembles the required data for the AlgDofPartiSystem::apply() function.
void assemble_by_gate (const GateType &gate, Index extra_local=0u, Index extra_shared=0u)
Assembles the AlgDofParti object from a given Global::Gate.
std::size_t bytes () const
void clear ()
Resets the whole object.
template<typename DT2_ >
void download_vector (const DT2_ *owned_dofs, LocalVectorType &local_vector, DataType *extra_local=nullptr, DataType *extra_shared=nullptr) const
const std::vector< int > & get_all_global_dof_counts () const
Returns the all-global-dof-counts vector.
const std::vector< int > & get_all_global_dof_offsets () const
Returns the all-global-dof-offsets vector.
String get_block_information () const
Returns the block information of the algebraic dof partitioning as an XML string.
const Dist::Comm * get_comm () const
const DoneeMirrorType & get_donee_mirror (Index i) const
Returns a donee neighbor mirror.
int get_donee_rank (Index i) const
Returns an donee neighbor rank.
const IndexVectorType & get_global_dof_indices () const
Returns the global-dof-indices array.
Index get_global_dof_offset () const
Index get_num_donee_neighbors () const
Index get_num_global_dofs () const
Index get_num_local_dofs () const
Index get_num_owned_dofs () const
Index get_num_owner_neighbors () const
const OwnedMirrorType & get_owned_mirror () const
Returns the Mirror of the owned DOFs.
const OwnerMirrorType & get_owner_mirror (Index i) const
Returns an owner neighbor mirror.
int get_owner_rank (Index i) const
Returns an owner neighbor rank.
AlgDofParti & operator= (const AlgDofParti &)=delete
no copy, no problems
template<typename DT2_ >
void upload_vector (DT2_ *owned_dofs, const LocalVectorType &local_vector, const DataType *extra_local=nullptr, const DataType *extra_shared=nullptr) const
Public Attributes
std::vector< int > _all_global_dof_counts
global DOF counts of all processes,
std::vector< int > _all_global_dof_offset
global DOF offsets of all processes,
String _block_information
a string containing the block information in XML format
const Dist::Comm * _comm
our communicator
std::vector< DoneeMirrorType > _donee_mirrors
rank/mirror-pair of DOF-donee processes
std::vector< int > _donee_ranks
ranks of DOF-donee neighbor processes
Index _extra_dof_offset
offset of first extra DOF
Index _extra_local_dof_count
number of extra local dofs; may be different for each process
Index _extra_shared_dof_count
number of extra shared dofs; must be equal on all processes
Index _global_dof_count
global dof count over all processes
IndexVectorType _global_dof_idx
global dof indices for each local dof
Index _global_dof_offset
global dof offset of this process
Index _local_dof_count
number of local dofs of this process
Index _owned_dof_count
number of owned dofs of this process
MirrorType _owned_mirror
mirror for this process's owned DOFs
std::vector< OwnerMirrorType > _owner_mirrors
rank/mirror-pair of DOF-owner processes
std::vector< int > _owner_ranks
ranks of DOF-owner neighbor processes
Static Protected Member Functions
template<typename DT2_ >
static Index _gather (LAFEM::DenseVector< DataType, IndexType > &buffer, const DT2_ *vector, const LAFEM::VectorMirror< DataType, IndexType > &mirror)
static Index _get_donee_dofs (std::vector< IndexType > &send_buf, const LAFEM::VectorMirror< DataType, IndexType > &donee_mir, Index offset)
Detailed Description
template<typename LocalVector_, typename Mirror_>
class FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >
Algebraic DOF Partitioning implementation.
This class implements the functionality to generate and manage a distributed partitioning of the degrees of freedom of a (linear) system in an algebraic sense instead of the usual domain-decomposition approach. With this algebraic dof partitioning approach (ADP), each process in a given communicator becomes the unique owner of a set of consecutively enumerated global dofs, whereas in the domain-decomposition approach a single global dof may be shared by several processes, thus having no unique owner. The primary purpose of this class and the closely related AlgDofPartiSystem class is to offer the capability of embedding various third-party linear solver libraries as solvers, preconditioners or smoothers within the solver framework used in FEAT.
To use this class, one needs to have a fully assembled Global::Gate object, which contains all the partitioning information in the usual domain-decomposition sense, which is used as a "starting point" for an algebraic DOF partitioning in the assemble_by_gate() function.
Throughout this class and the closely related AlgDofPartiSystem class, you will frequently find the terms "local DOF", "shared DOF" and "owned DOF" and "donee DOF", which are defined as follows:
"local" DOFs always means the DOFs as they are used in the domain decomposition world.
"shared" DOFs are all local DOFs are "shared" by at least two processes in the domain decomposition world. In other words: Each local DOF, which is part of at least one neighbor mirror in the Global::Gate, is a shared DOF.
"owned" DOFs are all local DOFs, which:
are not shared with any other process
are only shared with processes of higher comm rank
"donee" DOFs are all shared DOFs, which are not owned DOFs
Furthermore, the neighbor ranks and mirrors, which are used in the Global::Gate of the domain-decomposition based approach, are converted into "owner" and "donee" neighbor ranks and mirrors in this algebraic approach. The basic idea is the following: Assume that three processes A, B and C share a common set of DOFs, i.e. they are neighbors in the domain-decomposition sense, and assume that process A has a lower rank than process B and process C. Due to the "ownership" rule (lowest rank is owner), process A becomes the "owner" of the shared DOFs and thus is responsible for enumerating and managing all DOFs shared by A, B and C, which in turn makes processes B and C "donees". Now, because process A owns at least one DOF that is also a local DOF of process B and a local DOF of process C in the domain decomposition sense, we have that:
process A is an "owner neighbor" of process B
process A is an "owner neighbor" of process C
process B is a "donee neighbor" of process A
process C is a "donee neighbor" of process A
Algebraic DOF partitioning of combined discretizations:
This class supports the algebraic dof partitioning of simple scalar FE spaces, which are represented by the LAFEM::DenseVector class, as well as more complex space combinations, which are represented by a hierarchy of meta containers, such as the LAFEM::TupleVector, and basic containers like LAFEM::DenseVector and/or LAFEM::DenseVectorBlocked; one prominent example is the velocity-pressure space pair used in Stokes systems which is typically represented by a LAFEM::DenseVectorBlocked for the velocity components and a (scalar) LAFEM::DenseVector for the pressure component, which are then joined together by a LAFEM::TupleVector meta container to form a single class that contains the entire velocity-pressure pair.
In the case of a combined discretization (such as the velocity-pressure pair), the algebraic dof partitioning distributes the DOFs of the individual components in an interleaved fashion among the processes, i.e. each process owns a set of DOFs of the first component followed by a set of DOFs of the second component, etc., so in the example of the velocity-pressure pair each process owns a set of consecutively numbered velocity DOFs followed by a set of consecutively numbered pressure DOFs, and so from a global perspective, the global DOFs alternate between sets of velocity and pressure DOFs across all processes.
Example:
Let's assume that we have 25x2=50 velocity DOFs (V0.0, V0.1, V1.0, ..., V24.0, V24.1) and 12 pressure DOFs (P0, ..., P11) in total partitioned among 4 processes and let's assume that each process owns 3 pressure DOFs and that the four processes own 18, 12, 12 and 8 velocity dofs, respectively, then the algebraic DOF partitioning of the 62 total global DOFs would look like in the table below:
+------------------------------+-------------------------------+--------------------------------+----------------------------------+
|          Process 0           |           Process 1           |            Process 2           |            Process 3             |
+------------------------------+-------------------------------+--------------------------------+----------------------------------+
|    0, ...,    17, 18, 19, 20 |    21, ...,    32, 33, 34, 35 |     36, ...,    47, 48, 49, 50 |    51, ...,     58, 59,  60,  61 | <- global algebraic DOF
+------------------------------+-------------------------------+--------------------------------+----------------------------------+
|    0, ...,    17, 18, 19, 20 |     0, ...,    11, 12, 13, 14 |      0, ...,    11, 12, 13, 14 |     0, ...,      8,  9,  10,  11 | <- owned (local) algebraic DOF
+------------------------------+-------------------------------+--------------------------------+----------------------------------+
| V0.0, ...,  V8.1             |  V9.0, ..., V14.1             |  V15.0, ..., V20.1             |  V21.0, ..., V24.1               | <- global velocity DOF (interpreted as blocked DOFs)
|  V'0, ...,  V'17             |  V'18, ...,  V'29             |   V'30, ...,  V'41             |   V'42, ...,  V'49               | <- global velocity DOF (interpreted as scalar DOFs)
|                   P0, P1, P2 |                    P3, P4, P5 |                     P6, P7, P8 |                     P9, P10, P11 | <- global pressure DOF (scalar)
+------------------------------+-------------------------------+--------------------------------+----------------------------------+
| v0.0, ...,  v8.1             |  v0.0, ...,  v5.1             |   v0.0, ...,  v5.1             |   v0.0, ...,  v4.1               | <- owned (local) velocity DOF (interpreted as blocked DOFs)
|  v'0, ...,  v'17             |   v'0, ...,  v'11             |    v'0, ...,  v'11             |    v'0, ...,   v'7               | <- owned (local) velocity DOF (interpreted as scalar DOFs)
|                   p0, p1, p2 |                    p0, p1, p2 |                     p0, p1, p2 |                     p0,  p1,  p2 | <- owned (local) pressure DOF
+------------------------------+-------------------------------+--------------------------------+----------------------------------+
So in the above example, global algebraic DOF 33 corresponds to global pressure DOF 3 (P3), which is owned by process 1 and which corresponds to the owned pressure DOF 1 (p1) on that process, whereas global DOF 47 corresponds to the second block-component (index 1) of the global velocity DOF 20 (V20.1), which is owned by process 2 and which corresponds to the owned velocity DOF 5 (v5.1), etc.
Retrieving ADP block information for combined discretizations:
Some third-party libraries, which are used as solver backends for ADP based solvers, do not treat the system as a black box, but require information about the composition of the system components within the algebraic DOF partitioning – or in simpler terms: the library needs to know which DOF is a velocity DOF and which DOF is a pressure DOF in the example above. This information can be queried by calling the get_block_information() member function, which returns a String object containing the relevant offsets and counts encoded in XML format.
The returned XML string consists of one or more lines and each line contains a single XML marker, which currently is either
a closed <Scalar .../> marker that represents a scalar component that corresponds to a LAFEM::DenseVector container
a closed <Blocked .../> marker that represents a blocked/vector-valued component that corresponds to a LAFEM::DenseVectorBlocked container
an open <Tuple ...> marker that represents a meta component that combines one or more other components and which corresponds to the LAFEM::TupleVector container
a </Tuple> marker that closes a previously opened <Tuple ...> marker
Each of the above XML markers contains the following five attributes in alphabetical order:
gc ("global count"): contains the total number of global DOFs on all processes of the corresponding component; this quantity is identical on all processes
gf ("global first"): represents the index of the first DOF of this component that is is owned by the current process
go ("global offset"): represents the index of the first global DOF owned by this process, which corresponds to the first global DOF of the corresponding component
lc ("local count"): contains the number of local DOFs within this component that are owned by the current process.
lo ("local offset"): represents the index of the first local DOF owned by this process, which corresponds to the first local DOF of the corresponding component
Additionally, the <Blocked .../> marker also contains the following attribute:
bs ("block size"): contains the total number values per DOF block
In the example above, the four processes would contain the following block information strings:
Process 0:
<Tuple gc="62" gf="0" go="0" lc="21" lo="0">
<Blocked bs="2" gc="50" gf="0" go="0" lc="18" lo="0"/>
<Scalar gc="12" gf="0" go="18" lc="3" lo="18"/>
</Tuple>
Process 1:
<Tuple gc="62" gf="21" go="21" lc="15" lo="0">
<Blocked bs="2" gc="50" gf="18" go="21" lc="12" lo="0"/>
<Scalar gc="12" gf="3" go="33" lc="3" lo="12"/>
</Tuple>
Process 2:
<Tuple gc="62" gf="36" go="36" lc="15" lo="0">
<Blocked bs="2" gc="50" gf="30" go="36" lc="12" lo="0"/>
<Scalar gc="12" gf="6" go="48" lc="3" lo="12"/>
</Tuple>
Process 3:
<Tuple gc="62" gf="51" go="51" lc="11" lo="0">
<Blocked bs="2" gc="50" gf="42" go="51" lc="8" lo="0"/>
<Scalar gc="12" gf="9" go="59" lc="3" lo="8"/>
</Tuple>
Todo:
decide what happens if this process owns no dofs at all
make sure that this works for discontinuous elements, too
ensure that extra local and extra shared dofs are handled appropriately
Author
Peter Zajac
Definition at line 191 of file alg_dof_parti.hpp.
Member Typedef Documentation
ADPAuxType
template<typename LocalVector_ , typename Mirror_ > typedef Intern::ADPAux<IndexVectorType> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::ADPAuxType
auxiliary helper class type
Definition at line 213 of file alg_dof_parti.hpp.
BufferVectorType
template<typename LocalVector_ , typename Mirror_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::BufferVectorType
the type for buffers used by our mirrors
Definition at line 216 of file alg_dof_parti.hpp.
DataType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVectorType::DataType FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::DataType
our data type
Definition at line 200 of file alg_dof_parti.hpp.
DoneeMirrorType
template<typename LocalVector_ , typename Mirror_ > typedef LAFEM::VectorMirror<DataType, IndexType> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::DoneeMirrorType
type of mirror for neighbor donee owned dof indices
Definition at line 223 of file alg_dof_parti.hpp.
GateType
template<typename LocalVector_ , typename Mirror_ > typedef Global::Gate<LocalVectorType, MirrorType> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::GateType
the global gate type
Definition at line 207 of file alg_dof_parti.hpp.
GlobalVectorType
template<typename LocalVector_ , typename Mirror_ > typedef Global::Vector<LocalVectorType, MirrorType> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::GlobalVectorType
the global vector type
Definition at line 205 of file alg_dof_parti.hpp.
IndexType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVectorType::IndexType FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::IndexType
our index type
Definition at line 202 of file alg_dof_parti.hpp.
IndexVectorType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVectorType::template ContainerTypeByDI<IndexType, IndexType> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::IndexVectorType
the index vector type, this one is required for internal computations
Definition at line 210 of file alg_dof_parti.hpp.
LocalVectorType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVector_ FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::LocalVectorType
the local vector type
Definition at line 195 of file alg_dof_parti.hpp.
MirrorType
template<typename LocalVector_ , typename Mirror_ > typedef Mirror_ FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::MirrorType
the vector mirror type
Definition at line 197 of file alg_dof_parti.hpp.
OwnedMirrorType
template<typename LocalVector_ , typename Mirror_ > typedef MirrorType FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::OwnedMirrorType
type of mirror for owned local dof indices
Definition at line 219 of file alg_dof_parti.hpp.
OwnerMirrorType
template<typename LocalVector_ , typename Mirror_ > typedef MirrorType FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::OwnerMirrorType
type of mirror for neighbor owner local dof indices
Definition at line 221 of file alg_dof_parti.hpp.
Constructor & Destructor Documentation
AlgDofParti()
template<typename LocalVector_ , typename Mirror_ > FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::AlgDofParti () inline
default constructor
Definition at line 268 of file alg_dof_parti.hpp.
Member Function Documentation
_gather()
template<typename LocalVector_ , typename Mirror_ > template<typename DT2_ > static Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_gather (LAFEM::DenseVector< DataType, IndexType > & buffer, const DT2_ * vector, const LAFEM::VectorMirror< DataType, IndexType > & mirror) inline static protected
Definition at line 874 of file alg_dof_parti.hpp.
_get_donee_dofs()
template<typename LocalVector_ , typename Mirror_ > static Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_get_donee_dofs (std::vector< IndexType > & send_buf, const LAFEM::VectorMirror< DataType, IndexType > & donee_mir, Index offset) inline static protected
Definition at line 862 of file alg_dof_parti.hpp.
assemble_allgather()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_allgather (bool yes_i_really_want_to_do_this = false) inline
Assembles the required data for the AlgDofPartiSystem::apply() function.
Warning
Calling this function and (more importantly) the AlgDofPartiSystem::apply() functions will totally screw up the scalability of your application, so the code will blow up in your face on bigger clusters.
Do not use this function except for small-scale debugging purposes. You have been warned.
Parameters
[in] yes_i_really_want_to_do_this An assertion will fire if this is false. The only purpose of this parameter is to force you to read the warning in this documentation first.
Definition at line 493 of file alg_dof_parti.hpp.
References FEAT::Dist::Comm::allgather(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_global_dof_offset(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_global_dofs(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_owned_dofs(), FEAT::Dist::Comm::size(), and XASSERTM.
assemble_by_gate()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate (const GateType & gate, Index extra_local = 0u, Index extra_shared = 0u) inline
Assembles the AlgDofParti object from a given Global::Gate.
This function performs the assembly of all required internal data structures.
Parameters
[in] extra_local The number of extra local dofs for this process.
[in] extra_shared The number of extra shared dofs for all processes.
Todo:
what do we do if owned_dofs==0 ?
Definition at line 526 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_comm, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_donee_mirrors, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_donee_ranks, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_extra_local_dof_count, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_extra_shared_dof_count, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owned_dof_count, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owner_mirrors, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owner_ranks, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, FEAT::Dist::Comm::allreduce(), FEAT::Dist::Comm::exscan(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_freqs(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_mirrors(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Dist::op_sum, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERTM.
bytes()
template<typename LocalVector_ , typename Mirror_ > std::size_t FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::bytes () const inline
Returns
The size of this object in bytes
Definition at line 314 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_all_global_dof_counts, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_all_global_dof_offset, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_donee_mirrors, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_idx, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owned_mirror, and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owner_mirrors.
clear()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear () inline
Resets the whole object.
Definition at line 289 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_all_global_dof_counts, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_all_global_dof_offset, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_comm, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_donee_mirrors, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_extra_dof_offset, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_extra_local_dof_count, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_extra_shared_dof_count, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_count, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_idx, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_offset, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_local_dof_count, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owned_dof_count, FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owned_mirror, and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owner_mirrors.
download_vector()
template<typename LocalVector_ , typename Mirror_ > template<typename DT2_ > void FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::download_vector (const DT2_ * owned_dofs, LocalVectorType & local_vector, DataType * extra_local = nullptr, DataType * extra_shared = nullptr) const inline
Definition at line 772 of file alg_dof_parti.hpp.
get_all_global_dof_counts()
template<typename LocalVector_ , typename Mirror_ > const std::vector< int > & FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_all_global_dof_counts () const inline
Returns the all-global-dof-counts vector.
Attention
This vector is only allocated after assemble_allgather() has been called.
Don't use this unless you really know what you are doing!
Returns
The all-global-dof-counts vector.
Definition at line 475 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_all_global_dof_counts, and XASSERTM.
get_all_global_dof_offsets()
template<typename LocalVector_ , typename Mirror_ > const std::vector< int > & FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_all_global_dof_offsets () const inline
Returns the all-global-dof-offsets vector.
Attention
This vector is only allocated after assemble_allgather() has been called.
Don't use this unless you really know what you are doing!
Returns
The all-global-dof-offsets vector.
Definition at line 460 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_all_global_dof_offset, and XASSERTM.
get_block_information()
template<typename LocalVector_ , typename Mirror_ > String FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_block_information () const inline
Returns the block information of the algebraic dof partitioning as an XML string.
Definition at line 332 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_block_information.
get_comm()
template<typename LocalVector_ , typename Mirror_ > const Dist::Comm * FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_comm () const inline
Returns
The communicator
Definition at line 308 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_comm.
get_donee_mirror()
template<typename LocalVector_ , typename Mirror_ > const DoneeMirrorType & FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_donee_mirror (Index i) const inline
Returns a donee neighbor mirror.
Note
The indices of a donee neighbor mirror are owned DOF indices.
Parameters
[in] i The index of the donee neighbor.
Returns
The mirror of the i-th donee neighbor.
Definition at line 446 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_data_mirrors(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure().
get_donee_rank()
template<typename LocalVector_ , typename Mirror_ > int FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_donee_rank (Index i) const inline
Returns an donee neighbor rank.
Parameters
[in] i The index of the donee neighbor.
Returns
The rank of the i-th donee neighbor.
Definition at line 412 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
get_global_dof_indices()
template<typename LocalVector_ , typename Mirror_ > const IndexVectorType & FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_global_dof_indices () const inline
Returns the global-dof-indices array.
Definition at line 364 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_idx.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_data_mirrors(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure().
get_global_dof_offset()
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_global_dof_offset () const inline
Returns
The index of the first global DOF owned by this process.
Definition at line 356 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_offset.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_allgather().
get_num_donee_neighbors()
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_donee_neighbors () const inline
Returns
The number of donee neighbors.
Definition at line 384 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
get_num_global_dofs()
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_global_dofs () const inline
Returns
The total number of global DOFs.
Definition at line 350 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_count.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_allgather().
get_num_local_dofs()
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_local_dofs () const inline
Returns
The number of local DOFs shared by this process.
Definition at line 344 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_local_dof_count.
get_num_owned_dofs()
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_owned_dofs () const inline
Returns
The number of local DOFs owned by this process.
Definition at line 338 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owned_dof_count.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_allgather().
get_num_owner_neighbors()
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_owner_neighbors () const inline
Returns
The number of owner neighbors.
Definition at line 378 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
get_owned_mirror()
template<typename LocalVector_ , typename Mirror_ > const OwnedMirrorType & FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owned_mirror () const inline
Returns the Mirror of the owned DOFs.
Definition at line 372 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owned_mirror.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_data_mirrors(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_structure().
get_owner_mirror()
template<typename LocalVector_ , typename Mirror_ > const OwnerMirrorType & FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owner_mirror (Index i) const inline
Returns an owner neighbor mirror.
Note
The indices of an owner neighbor mirror are local DOF indices.
Parameters
[in] i The index of the owner neighbor.
Returns
The mirror of the i-th owner neighbor.
Definition at line 429 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_data_mirrors().
get_owner_rank()
template<typename LocalVector_ , typename Mirror_ > int FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owner_rank (Index i) const inline
Returns an owner neighbor rank.
Parameters
[in] i The index of the owner neighbor.
Returns
The rank of the i-th owner neighbor.
Definition at line 398 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::_assemble_buffers(), and FEAT::Global::AlgDofPartiSystem< LocalMatrix_, LocalFilter_, Mirror_ >::upload_matrix_numeric().
upload_vector()
template<typename LocalVector_ , typename Mirror_ > template<typename DT2_ > void FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::upload_vector (DT2_ * owned_dofs, const LocalVectorType & local_vector, const DataType * extra_local = nullptr, const DataType * extra_shared = nullptr) const inline
Definition at line 743 of file alg_dof_parti.hpp.
Member Data Documentation
_all_global_dof_counts
template<typename LocalVector_ , typename Mirror_ > std::vector<int> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_all_global_dof_counts
global DOF counts of all processes,
See also
#allgather()
Definition at line 264 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::bytes(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_all_global_dof_counts().
_all_global_dof_offset
template<typename LocalVector_ , typename Mirror_ > std::vector<int> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_all_global_dof_offset
global DOF offsets of all processes,
See also
#allgather()
Definition at line 262 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::bytes(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_all_global_dof_offsets().
_block_information
template<typename LocalVector_ , typename Mirror_ > String FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_block_information
a string containing the block information in XML format
Definition at line 255 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_block_information().
_comm
template<typename LocalVector_ , typename Mirror_ > const Dist::Comm* FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_comm
our communicator
Definition at line 227 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_comm().
_donee_mirrors
template<typename LocalVector_ , typename Mirror_ > std::vector<DoneeMirrorType> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_donee_mirrors
rank/mirror-pair of DOF-donee processes
Definition at line 253 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::bytes(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear().
_donee_ranks
template<typename LocalVector_ , typename Mirror_ > std::vector<int> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_donee_ranks
ranks of DOF-donee neighbor processes
Definition at line 249 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate().
_extra_dof_offset
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_extra_dof_offset
offset of first extra DOF
Definition at line 241 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear().
_extra_local_dof_count
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_extra_local_dof_count
number of extra local dofs; may be different for each process
Definition at line 237 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear().
_extra_shared_dof_count
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_extra_shared_dof_count
number of extra shared dofs; must be equal on all processes
Definition at line 239 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear().
_global_dof_count
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_count
global dof count over all processes
Definition at line 231 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_global_dofs().
_global_dof_idx
template<typename LocalVector_ , typename Mirror_ > IndexVectorType FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_idx
global dof indices for each local dof
Definition at line 243 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::bytes(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_global_dof_indices().
_global_dof_offset
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_global_dof_offset
global dof offset of this process
Definition at line 229 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_global_dof_offset().
_local_dof_count
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_local_dof_count
number of local dofs of this process
Definition at line 233 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_local_dofs().
_owned_dof_count
template<typename LocalVector_ , typename Mirror_ > Index FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owned_dof_count
number of owned dofs of this process
Definition at line 235 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_num_owned_dofs().
_owned_mirror
template<typename LocalVector_ , typename Mirror_ > MirrorType FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owned_mirror
mirror for this process's owned DOFs
Definition at line 245 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::bytes(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::get_owned_mirror().
_owner_mirrors
template<typename LocalVector_ , typename Mirror_ > std::vector<OwnerMirrorType> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owner_mirrors
rank/mirror-pair of DOF-owner processes
Definition at line 251 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate(), FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::bytes(), and FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::clear().
_owner_ranks
template<typename LocalVector_ , typename Mirror_ > std::vector<int> FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::_owner_ranks
ranks of DOF-owner neighbor processes
Definition at line 247 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofParti< LocalVector_, Mirror_ >::assemble_by_gate().
The documentation for this class was generated from the following file:
kernel/global/alg_dof_parti.hpp