FEAT: FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ > Class Template Reference
FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ > Class Template Reference abstract
Trilinos StokesFROSchPreconditioner class template.
#include <frosch.hpp>
Public Types
typedef TpetraSolverBase< Matrix_, Filter_ > BaseClass
our base-class
typedef MatrixType::DataType DataType
our internal data type
typedef Filter_ FilterType
the (local) filter type
typedef MatrixType::IndexType IndexType
our internal index type
typedef Matrix_ MatrixType
this specialization expects a local matrix
typedef BaseClass::VectorType VectorType
the vector type
Public Member Functions
StokesFROSchPreconditioner (const Matrix_ &matrix, const Filter_ &filter, const Trilinos::FROSchParameterList &params)
StokesFROSchPreconditioner (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter)
virtual Status apply (Vector_ &vec_cor, const Vector_ &vec_def)=0
Solver application method.
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def) override
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic () override
Symbolic Finalization.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric Initialization.
virtual void init_symbolic () override
Symbolic Initialization.
virtual String name () const override
Returns a descriptive string.
Protected Member Functions
void _download_cor (VectorType &vec_cor)
Downloads the Tpetra correction vector.
template<typename DTV_ >
void _download_vector (LocalVectorType &vector, const DTV_ *val)
Downloads the ADP vector values from the given array.
template<typename DTV_ >
void _download_vector (VectorType &vector, const DTV_ *val)
Downloads the ADP vector values from the given array.
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const Global::MeanFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const LAFEM::MeanFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const LAFEM::NoneFilter< DataType, IndexType > &)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterChain< First_ > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ , typename... Rest_>
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterChain< First_, Rest_... > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename SubFilter_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterSequence< SubFilter_ > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::UnitFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
void _format_cor ()
Format the Tpetra correction vector.
String _get_adp_block_information () const
String _get_adp_block_information () const
Index _get_adp_matrix_num_cols () const
Index _get_adp_matrix_num_cols () const
Index _get_adp_matrix_num_nzes () const
Index _get_adp_matrix_num_nzes () const
Index _get_adp_matrix_num_rows () const
Index _get_adp_matrix_num_rows () const
Index _get_adp_vector_size () const
Index _get_adp_vector_size () const
const Dist::Comm * _get_comm () const
const Dist::Comm * _get_comm () const
Index _get_global_dof_offset () const
Index _get_global_dof_offset () const
Index _get_num_global_dofs () const
Index _get_num_global_dofs () const
Index _get_num_global_nonzeros () const
Index _get_num_global_nonzeros () const
Index _get_num_owned_dofs () const
Index _get_num_owned_dofs () const
void _upload_def (const VectorType &vec_def)
Uploads the Tpetra defect vector.
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _upload_numeric (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx)
Uploads the (filtered) ADP matrix values to the given array.
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _upload_numeric (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx)
Uploads the (filtered) ADP matrix values to the given array.
template<typename RPT_ , typename CIT_ >
void _upload_symbolic (RPT_ *row_ptr, CIT_ *col_idx)
Uploads the ADP matrix structure to the given arrays.
template<typename RPT_ , typename CIT_ >
void _upload_symbolic (RPT_ *row_ptr, CIT_ *col_idx)
Uploads the ADP matrix structure to the given arrays.
template<typename DTV_ >
void _upload_vector (DTV_ *val, const LocalVectorType &vector)
Uploads the ADP vector values to the given array.
template<typename DTV_ >
void _upload_vector (DTV_ *val, const VectorType &vector)
Uploads the ADP vector values to the given array.
Protected Attributes
Dist::Comm _comm_self
self-communicator object
void * _core
a pointer to our opaque core wrapper object
Index _first_owned_pres_dof
Index _first_owned_velo_dof
Index _num_global_pres_dofs
Index _num_global_velo_dofs
Index _num_owned_pres_dofs
Index _num_owned_velo_dofs
const Trilinos::FROSchParameterList & _params
void * _solver
the FROSchPreconditioner solver object
const FilterType & _system_filter
the system filter
const MatrixType & _system_matrix
the system matrix
Private Member Functions
void _deduct_sizes ()
Detailed Description
template<typename Matrix_, typename Filter_>
class FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >
Trilinos StokesFROSchPreconditioner class template.
This class acts as a wrapper around the FROSch Preconditioner (block variant) from the Trilinos library.
Todo:
support setting of solver parameters
Author
Stephan Köhler
Definition at line 1011 of file frosch.hpp.
Member Typedef Documentation
BaseClass
template<typename Matrix_ , typename Filter_ > typedef TpetraSolverBase<Matrix_, Filter_> FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::BaseClass
our base-class
Definition at line 1016 of file frosch.hpp.
DataType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef MatrixType::DataType FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::DataType inherited
our internal data type
Definition at line 783 of file adp_solver_base.hpp.
FilterType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef Filter_ FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::FilterType inherited
the (local) filter type
Definition at line 777 of file adp_solver_base.hpp.
IndexType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef MatrixType::IndexType FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::IndexType inherited
our internal index type
Definition at line 785 of file adp_solver_base.hpp.
MatrixType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef Matrix_ FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::MatrixType inherited
this specialization expects a local matrix
the (local) matrix type
Definition at line 773 of file adp_solver_base.hpp.
VectorType
template<typename Matrix_ , typename Filter_ > typedef BaseClass::VectorType FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::VectorType
the vector type
Definition at line 1018 of file frosch.hpp.
Constructor & Destructor Documentation
StokesFROSchPreconditioner() [1/2]
template<typename Matrix_ , typename Filter_ > FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::StokesFROSchPreconditioner (const Matrix_ & matrix, const Filter_ & filter, const Trilinos::FROSchParameterList & params) inline explicit
Definition at line 1034 of file frosch.hpp.
StokesFROSchPreconditioner() [2/2]
template<typename Matrix_ , typename Filter_ > FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::StokesFROSchPreconditioner (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter) inline explicit
Todo:
parse parameters
Definition at line 1046 of file frosch.hpp.
~StokesFROSchPreconditioner()
template<typename Matrix_ , typename Filter_ > virtual FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::~StokesFROSchPreconditioner () inline override virtual
Definition at line 1053 of file frosch.hpp.
Member Function Documentation
_deduct_sizes()
template<typename Matrix_ , typename Filter_ > void FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::_deduct_sizes () inline private
Definition at line 1157 of file frosch.hpp.
_download_cor()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> void FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_download_cor (VectorType & vec_cor) inline protected inherited
Downloads the Tpetra correction vector.
This function first downloads the Tpetra vector into its ADP correction vector counterpart and afterwards downloads that into the given correction vector.
Parameters
[out] vec_cor The correction vector to download to.
Definition at line 767 of file frosch.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_download_vector(), and FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_filter.
_download_vector() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_download_vector (LocalVectorType & vector, const DTV_ * val) protected inherited
Downloads the ADP vector values from the given array.
Parameters
[in,out] vector A transient reference to the local vector that receives the downloaded ADP value array. It is assumed to be allocated to the correct size, but its contents on entry are ignored.
[in] val A transient pointer to an array of length _get_adp_vector_size() that contains the ADP values that are to be downloaded to the output vector given by vector.
Referenced by FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_download_cor(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_download_cor(), and FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::apply().
_download_vector() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_download_vector (VectorType & vector, const DTV_ * val) inline protected inherited
Downloads the ADP vector values from the given array.
Parameters
[in,out] vector A transient reference to the local vector that receives the downloaded ADP value array. It is assumed to be allocated to the correct size, but its contents on entry are ignored.
[in] val A transient pointer to an array of length _get_adp_vector_size() that contains the ADP values that are to be downloaded to the output vector given by vector.
Definition at line 956 of file adp_solver_base.hpp.
_filter_mat() [1/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const Global::MeanFilter< DataType, IndexType > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 994 of file adp_solver_base.hpp.
References XASSERTM.
_filter_mat() [2/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const LAFEM::MeanFilter< DataType, IndexType > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 986 of file adp_solver_base.hpp.
References XASSERTM.
_filter_mat() [3/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const LAFEM::NoneFilter< DataType, IndexType > &) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 963 of file adp_solver_base.hpp.
Referenced by FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_numeric(), and FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric().
_filter_mat() [4/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterChain< First_ > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 1020 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [5/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ , typename... Rest_> void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterChain< First_, Rest_... > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 1011 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [6/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ , typename SubFilter_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterSequence< SubFilter_ > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 1002 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [7/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::UnitFilter< DataType, IndexType > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 971 of file adp_solver_base.hpp.
_format_cor()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> void FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_format_cor () inline protected inherited
Format the Tpetra correction vector.
Definition at line 752 of file frosch.hpp.
_get_adp_block_information() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> String FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_block_information () const protected inherited
Returns
The block information of the algebraic dof partitioning as an XML string.
_get_adp_block_information() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> String FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_block_information () const inline protected inherited
Returns
The block information of the algebraic dof partitioning as an XML string.
Definition at line 873 of file adp_solver_base.hpp.
References XABORTM.
_get_adp_matrix_num_cols() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_cols () const protected inherited
Returns
The number of columns of the local ADP matrix; equal to _get_num_global_dofs()
_get_adp_matrix_num_cols() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_cols () const inline protected inherited
Returns
The number of columns of the local ADP matrix; equal to _get_num_global_dofs()
Definition at line 837 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_adp_matrix_num_nzes() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_nzes () const protected inherited
Returns
The number of nonzero entries of the local ADP matrix
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_adp_matrix_num_nzes() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_nzes () const inline protected inherited
Returns
The number of nonzero entries of the local ADP matrix
Definition at line 843 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_adp_matrix_num_rows() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_rows () const protected inherited
Returns
The number of rows of the local ADP matrix; equal to _get_num_owned_dofs()
_get_adp_matrix_num_rows() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_rows () const inline protected inherited
Returns
The number of rows of the local ADP matrix; equal to _get_num_owned_dofs()
Definition at line 831 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_adp_vector_size() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_vector_size () const protected inherited
Returns
The size of the local ADP vector; equal to _get_num_owned_dofs()
Referenced by FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_download_vector(), and FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_vector().
_get_adp_vector_size() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_vector_size () const inline protected inherited
Returns
The size of the local ADP vector; equal to _get_num_owned_dofs()
Definition at line 825 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_comm() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const Dist::Comm * FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_comm () const protected inherited
Returns
A pointer to the underlying communicator
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_comm() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const Dist::Comm * FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_comm () const inline protected inherited
Returns
A pointer to the underlying (self) communicator
Definition at line 819 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_comm_self.
_get_global_dof_offset() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_global_dof_offset () const protected inherited
Returns
The index of the first global DOF owned by this process
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_global_dof_offset() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_global_dof_offset () const inline protected inherited
Returns
The index of the first global DOF owned by this process
Definition at line 867 of file adp_solver_base.hpp.
_get_num_global_dofs() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_dofs () const protected inherited
Returns
The total number of global DOFs on all processes
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_matrix_num_cols(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_num_global_dofs() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_dofs () const inline protected inherited
Returns
The total number of global DOFs on all processes
Definition at line 855 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_num_global_nonzeros() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_nonzeros () const protected inherited
Returns
The total number of nonzero entries of the global ADP matrix
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), and FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack().
_get_num_global_nonzeros() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_nonzeros () const inline protected inherited
Returns
The total number of nonzero entries of the global ADP matrix
Definition at line 849 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_num_owned_dofs() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs () const protected inherited
Returns
The number of global DOFs owned by this process
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_matrix_num_rows(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_vector_size(), FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_num_owned_dofs() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs () const inline protected inherited
Returns
The number of global DOFs owned by this process
Definition at line 861 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_upload_def()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> void FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_def (const VectorType & vec_def) inline protected inherited
Uploads the Tpetra defect vector.
This function first uploads the given defect vector into its ADP defect vector counterpart and afterwards uploads that into the Tpetra vector counterpart.
Parameters
[in] vec_def The defect vector to be uploaded from.
Definition at line 744 of file frosch.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_vector().
_upload_numeric() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx) protected inherited
Uploads the (filtered) ADP matrix values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the filtered matrix values of the local ADP matrix.
[in] row_ptr A transient pointer to the row-pointer array of the ADP matrix as returned by the _upload_symbolic() function.
[in] col_idx A transient pointer to the column-index array of the ADP matrix as returned by the _upload_symbolic() function.
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::init_numeric(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_numeric(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_numeric().
_upload_numeric() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx) inline protected inherited
Uploads the (filtered) ADP matrix values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the filtered matrix values of the local ADP matrix.
[in] row_ptr A transient pointer to the row-pointer array of the ADP matrix as returned by the _upload_symbolic() function.
[in] col_idx A transient pointer to the column-index array of the ADP matrix as returned by the _upload_symbolic() function.
Definition at line 917 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat(), and FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_upload_symbolic() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_symbolic (RPT_ * row_ptr, CIT_ * col_idx) protected inherited
Uploads the ADP matrix structure to the given arrays.
Parameters
[out] row_ptr A transient pointer to an array of length _get_adp_matrix_num_rows()+1 that receives the the row-pointer array of the local ADP matrix.
[out] col_idx A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the column index array of the local ADP matrix.
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_upload_symbolic() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_symbolic (RPT_ * row_ptr, CIT_ * col_idx) inline protected inherited
Uploads the ADP matrix structure to the given arrays.
Parameters
[out] row_ptr A transient pointer to an array of length _get_adp_matrix_num_rows()+1 that receives the the row-pointer array of the ADP matrix.
[out] col_idx A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the column index array of the ADP matrix.
Definition at line 891 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_upload_vector() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_vector (DTV_ * val, const LocalVectorType & vector) protected inherited
Uploads the ADP vector values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_vector_size() that receives the local ADP values of the input vector given by vector.
[in] vector A transient reference to the local vector that is to be uploaded to the ADP value array.
Referenced by FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_def(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_def(), and FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::apply().
_upload_vector() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_vector (DTV_ * val, const VectorType & vector) inline protected inherited
Uploads the ADP vector values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_vector_size() that receives the local ADP values of the input vector given by vector.
[in] vector A transient reference to the local vector that is to be uploaded to the ADP value array.
Definition at line 939 of file adp_solver_base.hpp.
apply() [1/2]
template<typename Vector_ > virtual Status FEAT::Solver::SolverBase< Vector_ >::apply (Vector_ & vec_cor, const Vector_ & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, and FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >.
Referenced by FEAT::Solver::solve().
apply() [2/2]
template<typename Matrix_ , typename Filter_ > virtual Status FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::apply (VectorType & vec_cor, const VectorType & vec_def) inline override virtual
Definition at line 1140 of file frosch.hpp.
done()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric(), and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
done_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented in FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >.
Definition at line 246 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::done(), FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::done_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_numeric(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::done_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric().
done_symbolic()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> virtual void FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::done_symbolic () inline override virtual inherited
Symbolic Finalization.
This function destroys all Tpetra objects managed by this class and resets all auxiliary vectors and pointers.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 801 of file frosch.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_symbolic(), and XASSERT.
init()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
init_numeric()
template<typename Matrix_ , typename Filter_ > virtual void FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_numeric () inline override virtual
Numeric Initialization.
This function uploads the numerical values of the ADP matrix, which is managed by the base-class, to the Tpetra matrix.
Reimplemented from FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >.
Definition at line 1125 of file frosch.hpp.
References FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_core, and FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::init_numeric().
init_symbolic()
template<typename Matrix_ , typename Filter_ > virtual void FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_symbolic () inline override virtual
Symbolic Initialization.
This function creates the Tpetra matrix and vector objects and initializes their structure/layout by using the algebraic DOF partitioning (ADP) that is managed by the base-class. This function also performs an initial upload of the matrix and vector values from the ADP structures (because Tpetra requires this), although these values may be undefined (but existent) at this point.
Furthermore, the maps for FROSch (block variant) are built and written into the parameterlist.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 1079 of file frosch.hpp.
References FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_core, FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_nzes(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_comm(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_global_dof_offset(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_dofs(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_symbolic(), FEAT::Solver::SolverBase< Vector_ >::init_symbolic(), and XASSERT.
name()
template<typename Matrix_ , typename Filter_ > virtual String FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::name () const inline override virtual
Returns a descriptive string.
Returns
A string describing the solver.
Implements FEAT::Solver::SolverBase< Vector_ >.
Definition at line 1062 of file frosch.hpp.
Member Data Documentation
_comm_self
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Dist::Comm FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_comm_self protected inherited
self-communicator object
Many third-party libraries always expect a MPI_Comm object even if we operate only on a single MPI process, therefore this class creates a custom self-communicator that can be passed on to the third-party libraries.
Definition at line 795 of file adp_solver_base.hpp.
Referenced by FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_comm().
_core
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> void* FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_core protected inherited
a pointer to our opaque core wrapper object
Definition at line 725 of file frosch.hpp.
Referenced by FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::FROSchPreconditioner< Matrix_, Filter_ >::init_symbolic(), and FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::init_symbolic().
_first_owned_pres_dof
template<typename Matrix_ , typename Filter_ > Index FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::_first_owned_pres_dof protected
Definition at line 1028 of file frosch.hpp.
_first_owned_velo_dof
template<typename Matrix_ , typename Filter_ > Index FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::_first_owned_velo_dof protected
Definition at line 1027 of file frosch.hpp.
_num_global_pres_dofs
template<typename Matrix_ , typename Filter_ > Index FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::_num_global_pres_dofs protected
Definition at line 1031 of file frosch.hpp.
_num_global_velo_dofs
template<typename Matrix_ , typename Filter_ > Index FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::_num_global_velo_dofs protected
Definition at line 1030 of file frosch.hpp.
_num_owned_pres_dofs
template<typename Matrix_ , typename Filter_ > Index FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::_num_owned_pres_dofs protected
Definition at line 1025 of file frosch.hpp.
_num_owned_velo_dofs
template<typename Matrix_ , typename Filter_ > Index FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::_num_owned_velo_dofs protected
Definition at line 1024 of file frosch.hpp.
_params
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const Trilinos::FROSchParameterList& FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_params protected inherited
Definition at line 726 of file frosch.hpp.
_solver
template<typename Matrix_ , typename Filter_ > void* FEAT::Solver::StokesFROSchPreconditioner< Matrix_, Filter_ >::_solver protected
the FROSchPreconditioner solver object
Definition at line 1022 of file frosch.hpp.
_system_filter
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const FilterType& FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_filter protected inherited
the system filter
Definition at line 799 of file adp_solver_base.hpp.
Referenced by FEAT::Solver::TpetraSolverBase< Matrix_, Filter_, SolverBase_ >::_download_cor(), and FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_download_cor().
_system_matrix
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const MatrixType& FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix protected inherited
the system matrix
Definition at line 797 of file adp_solver_base.hpp.
Referenced by FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_cols(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_nzes(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_rows(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_vector_size(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_dofs(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_nonzeros(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_numeric(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_symbolic(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_symbolic(), and FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::init_symbolic().
The documentation for this class was generated from the following file:
kernel/solver/frosch.hpp