FEAT: FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ > Class Template Reference
FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ > Class Template Reference abstract
ILU(p) specialization for SparseMatrixCSR.
#include <ilu_precond.hpp>
Public Types
typedef DT_ DataType
typedef Filter_ FilterType
typedef IT_ IndexType
typedef LAFEM::SparseMatrixCSR< DT_, IT_ > MatrixType
typedef MatrixType::VectorTypeL VectorType
Public Member Functions
ILUPrecondWithBackend (const MatrixType &matrix, const FilterType &filter, const int p=0)
Constructor.
ILUPrecondWithBackend (const String &section_name, PropertyMap *section, const MatrixType &matrix, const FilterType &filter)
virtual ~ILUPrecondWithBackend ()
Empty virtual destructor.
virtual Status apply (VectorType &out, const VectorType &in) override
apply the preconditioner
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def)=0
virtual void done_symbolic () override
virtual void init_numeric () override
virtual void init_symbolic () override
virtual String name () const override
Returns the name of the solver.
virtual void set_fill_in_param (int p) override
Sets the fill-in parameter.
Protected Attributes
const FilterType & _filter
Intern::ILUCoreScalar< DataType, IndexType > _ilu
const MatrixType & _matrix
int _p
Detailed Description
template<typename DT_, typename IT_, typename Filter_>
class FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >
ILU(p) specialization for SparseMatrixCSR.
This specialization works for the LAFEM::SparseMatrixCSR matrix type
Author
Peter Zajac
Definition at line 978 of file ilu_precond.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ , typename Filter_ > typedef DT_ FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::DataType
Definition at line 983 of file ilu_precond.hpp.
FilterType
template<typename DT_ , typename IT_ , typename Filter_ > typedef Filter_ FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::FilterType
Definition at line 985 of file ilu_precond.hpp.
IndexType
template<typename DT_ , typename IT_ , typename Filter_ > typedef IT_ FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::IndexType
Definition at line 984 of file ilu_precond.hpp.
MatrixType
template<typename DT_ , typename IT_ , typename Filter_ > typedef LAFEM::SparseMatrixCSR<DT_, IT_> FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::MatrixType
Definition at line 982 of file ilu_precond.hpp.
VectorType
template<typename DT_ , typename IT_ , typename Filter_ > typedef MatrixType::VectorTypeL FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::VectorType
Definition at line 986 of file ilu_precond.hpp.
Constructor & Destructor Documentation
ILUPrecondWithBackend() [1/2]
template<typename DT_ , typename IT_ , typename Filter_ > FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::ILUPrecondWithBackend (const MatrixType & matrix, const FilterType & filter, const int p = 0) inline explicit
Constructor.
Parameters
[in] matrix The matrix to be used.
[in] p Maximum level of fillin.
Definition at line 1004 of file ilu_precond.hpp.
ILUPrecondWithBackend() [2/2]
template<typename DT_ , typename IT_ , typename Filter_ > FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::ILUPrecondWithBackend (const String & section_name, PropertyMap * section, const MatrixType & matrix, const FilterType & filter) inline explicit
Definition at line 1011 of file ilu_precond.hpp.
~ILUPrecondWithBackend()
template<typename DT_ , typename IT_ , typename Filter_ > virtual FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::~ILUPrecondWithBackend () inline virtual
Empty virtual destructor.
Definition at line 1025 of file ilu_precond.hpp.
Member Function Documentation
apply()
template<typename DT_ , typename IT_ , typename Filter_ > virtual Status FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply (VectorType & out, const VectorType & in) inline override virtual
apply the preconditioner
Parameters
[out] out The preconditioner result.
[in] in The vector to be preconditioned.
Definition at line 1081 of file ilu_precond.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::Solver::success.
done_symbolic()
template<typename DT_ , typename IT_ , typename Filter_ > virtual void FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::done_symbolic () inline override virtual
Implements FEAT::Solver::ILUPrecondBase< LAFEM::SparseMatrixCSR< DT_, IT_ > >.
Definition at line 1064 of file ilu_precond.hpp.
init_numeric()
template<typename DT_ , typename IT_ , typename Filter_ > virtual void FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::init_numeric () inline override virtual
Implements FEAT::Solver::ILUPrecondBase< LAFEM::SparseMatrixCSR< DT_, IT_ > >.
Definition at line 1069 of file ilu_precond.hpp.
init_symbolic()
template<typename DT_ , typename IT_ , typename Filter_ > virtual void FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::init_symbolic () inline override virtual
Implements FEAT::Solver::ILUPrecondBase< LAFEM::SparseMatrixCSR< DT_, IT_ > >.
Definition at line 1047 of file ilu_precond.hpp.
name()
template<typename DT_ , typename IT_ , typename Filter_ > virtual String FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::ILUPrecondBase< LAFEM::SparseMatrixCSR< DT_, IT_ > >.
Definition at line 1042 of file ilu_precond.hpp.
set_fill_in_param()
template<typename DT_ , typename IT_ , typename Filter_ > virtual void FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::set_fill_in_param (int p) inline override virtual
Sets the fill-in parameter.
Parameters
[in] p The new fill-in parameter
Implements FEAT::Solver::ILUPrecondBase< LAFEM::SparseMatrixCSR< DT_, IT_ > >.
Definition at line 1035 of file ilu_precond.hpp.
References XASSERT.
Member Data Documentation
_filter
template<typename DT_ , typename IT_ , typename Filter_ > const FilterType& FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::_filter protected
Definition at line 990 of file ilu_precond.hpp.
_ilu
template<typename DT_ , typename IT_ , typename Filter_ > Intern::ILUCoreScalar<DataType, IndexType> FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::_ilu protected
Definition at line 991 of file ilu_precond.hpp.
_matrix
template<typename DT_ , typename IT_ , typename Filter_ > const MatrixType& FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::_matrix protected
Definition at line 989 of file ilu_precond.hpp.
_p
template<typename DT_ , typename IT_ , typename Filter_ > int FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::_p protected
Definition at line 992 of file ilu_precond.hpp.
The documentation for this class was generated from the following file:
kernel/solver/ilu_precond.hpp