FEAT: FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ > Class Template Reference
FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ > Class Template Reference
Null Matrix implementation.
#include <null_matrix.hpp>
Public Types
template<typename DT2_ = DT_, typename IT2_ = IT_>
using ContainerType = NullMatrix< DT2_, IT2_, BlockHeight_, BlockWidth_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a matrix container with new Datatype and Index types
typedef DT_ DataType
Our datatype.
typedef const IT_ * ImageIterator
ImageIterator typedef for Adjactor interface implementation.
typedef IT_ IndexType
Our indextype.
typedef Tiny::Matrix< DataType, BlockHeight, BlockWidth > ValueType
Value type, meaning the type of each block.
typedef Intern::BlockedVectorHelper< DT_, IT_, BlockHeight_ >::VectorType VectorTypeL
Compatible L-vector type.
typedef Intern::BlockedVectorHelper< DT_, IT_, BlockWidth_ >::VectorType VectorTypeR
Compatible R-vector type.
Public Member Functions
NullMatrix ()
Constructor.
NullMatrix (Index rows_in, Index columns_in)
Constructor.
NullMatrix (NullMatrix &&other)
Move Constructor.
std::size_t bytes () const
Returns the total amount of bytes allocated.
NullMatrix clone (CloneMode clone_mode=CloneMode::Weak) const
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const NullMatrix< DT2_, IT2_, BlockHeight_, BlockWidth_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Retrieve matrix column count.
template<typename DT2_ , typename IT2_ >
void convert (const NullMatrix< DT2_, IT2_, BlockHeight_, BlockWidth_ > &other)
Conversion method.
void copy (const NullMatrix &x, bool full=false)
Performs \(this \leftarrow x\).
VectorTypeL extract_diag () const
extract main diagonal vector from matrix
void extract_diag (VectorTypeL &diag) const
void format (const DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
uint64_t get_checkpoint_size ()
Calculate size.
Index get_num_nodes_domain () const
Index get_num_nodes_image () const
ImageIterator image_begin (Index domain_node) const
ImageIterator image_end (Index domain_node) const
VectorTypeL lump_rows () const
Returns the lumped rows vector.
void lump_rows (VectorTypeL &lump) const
NullMatrix & operator= (NullMatrix &&other)
Move operator.
void resize (Index rows_in, Index columns_in)
Resizes the matrix to different dimensions.
void restore_from_checkpoint_data (std::vector< char > &)
Extract object from checkpoint.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Retrieve matrix row count.
void set_checkpoint_data (std::vector< char > &)
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Retrieve non zero element count.
Linear algebra operations
void axpy (const NullMatrix &x, const NullMatrix &y, const DT_ alpha=DT_(1))
Calculate \(this \leftarrow y + \alpha~ x\).
void scale (const NullMatrix &x, const DT_ alpha)
Calculate \(this \leftarrow \alpha~ x \).
DT_ norm_frobenius () const
Calculates the Frobenius norm of this matrix.
void row_norm2 (VectorTypeL &row_norms) const
Computes the 2-norm for every row.
void row_norm2sqr (VectorTypeL &row_norms) const
Computes the square of the 2-norm for every row.
void row_norm2sqr (VectorTypeL &row_norms, const VectorTypeR &scal) const
Computes the square of the 2-norm for every row, where every row is scaled by a vector.
NullMatrix< DT_, IT_, BlockWidth_, BlockHeight_ > transpose () const
Calculate \(this^\top \).
void transpose (const NullMatrix< DT_, IT_, BlockWidth_, BlockHeight_ > &x)
Calculate \(this \leftarrow x^\top \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply_transposed (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x) const
Calculate \(r \leftarrow this^\top \cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVector< DT_, IT_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > &r, const DenseVector< DT_, IT_ > &x) const
Calculate \(r \leftarrow this^\top \cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply_transposed (DenseVector< DT_, IT_ > &r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &x) const
Calculate \(r \leftarrow this^\top \cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > &r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &x) const
Calculate \(r \leftarrow this^\top \cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply_transposed (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply_transposed (DenseVector< DT_, IT_ > &r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > &r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &x, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > &r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
Static Public Member Functions
static String name ()
Returns a descriptive string.
Static Public Attributes
static constexpr int BlockHeight = BlockHeight_
Our block height.
static constexpr int BlockWidth = BlockWidth_
Our block width.
static constexpr bool is_global = false
static constexpr bool is_local = true
Private Attributes
Index _num_cols
Index _num_rows
matrix dimensions
Detailed Description
template<typename DT_, typename IT_, int BlockHeight_ = 1, int BlockWidth_ = 1>
class FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >
Null Matrix implementation.
This class implements a null matrix in the common LAFEM matrix interface. The main purpose of this class is to act as a "null block" inside a bigger meta-matrix, which is typically a LAFEM::TupleMatrix.
This matrix is a "hybrid-blocked-scalar" implementation, i.e. it can act as both a "blocked" null-matrix class as well as a "scalar" null-matrix class by setting BlockHeight_ = BlockWidth_ = 1. The compatible L/R vector types are chosen to be DenseVector or DenseVectorBlocked depending on whether the corresponding block dimension is 1 or greater than 1 (in analogy to the SparseMatrixBCSR class).
Also note that the DT_ and IT_ template arguments are only required for the conformance with the LAFEM matrix interface.
Author
Peter Zajac
Definition at line 57 of file null_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::ContainerType = NullMatrix<DT2_, IT2_, BlockHeight_, BlockWidth_>
Our 'base' class type.
Definition at line 79 of file null_matrix.hpp.
ContainerTypeByDI
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a matrix container with new Datatype and Index types
Definition at line 83 of file null_matrix.hpp.
DataType
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> typedef DT_ FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::DataType
Our datatype.
Definition at line 64 of file null_matrix.hpp.
ImageIterator
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> typedef const IT_* FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::ImageIterator
ImageIterator typedef for Adjactor interface implementation.
Definition at line 75 of file null_matrix.hpp.
IndexType
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> typedef IT_ FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::IndexType
Our indextype.
Definition at line 66 of file null_matrix.hpp.
ValueType
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> typedef Tiny::Matrix<DataType, BlockHeight, BlockWidth> FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::ValueType
Value type, meaning the type of each block.
Definition at line 72 of file null_matrix.hpp.
VectorTypeL
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> typedef Intern::BlockedVectorHelper<DT_,IT_,BlockHeight_>::VectorType FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::VectorTypeL
Compatible L-vector type.
Definition at line 86 of file null_matrix.hpp.
VectorTypeR
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> typedef Intern::BlockedVectorHelper<DT_,IT_,BlockWidth_>::VectorType FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::VectorTypeR
Compatible R-vector type.
Definition at line 88 of file null_matrix.hpp.
Constructor & Destructor Documentation
NullMatrix() [1/3]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::NullMatrix () inline explicit
Constructor.
Creates an empty matrix.
Definition at line 104 of file null_matrix.hpp.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::clone().
NullMatrix() [2/3]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::NullMatrix (Index rows_in, Index columns_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
Note
This matrix does not allocate any memory
Definition at line 117 of file null_matrix.hpp.
NullMatrix() [3/3]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::NullMatrix (NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ > && other) inline
Move Constructor.
Parameters
[in] other The source matrix.
Moves a given matrix to this matrix.
Definition at line 129 of file null_matrix.hpp.
Member Function Documentation
apply() [1/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 424 of file null_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
apply() [2/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 538 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
apply() [3/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 480 of file null_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply() [4/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 622 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply() [5/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVector< DT_, IT_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 452 of file null_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply() [6/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 580 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply() [7/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 508 of file null_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply() [8/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 706 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply() [9/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 664 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply_transposed() [1/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x) const inline
Calculate \(r \leftarrow this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 438 of file null_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
apply_transposed() [2/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 559 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
apply_transposed() [3/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVector< DT_, IT_ > & r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & x) const inline
Calculate \(r \leftarrow this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 494 of file null_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply_transposed() [4/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVector< DT_, IT_ > & r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 643 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply_transposed() [5/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > & r, const DenseVector< DT_, IT_ > & x) const inline
Calculate \(r \leftarrow this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 466 of file null_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply_transposed() [6/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 600 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply_transposed() [7/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > & r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & x) const inline
Calculate \(r \leftarrow this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 522 of file null_matrix.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply_transposed() [8/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > & r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 727 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
apply_transposed() [9/9]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply_transposed (DenseVectorBlocked< DT_, IT_, BlockWidth_ > & r, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & x, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this^\top \cdot x \).
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 685 of file null_matrix.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
axpy()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy (const NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ > & x, const NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ > & y, const DT_ alpha = DT_(1)) inline
Calculate \(this \leftarrow y + \alpha~ x\).
Parameters
[in] x The first summand matrix to be scaled.
[in] y The second summand matrix
[in] alpha A scalar to multiply x with.
Warning
All three matrices must have the same non zero layout. This operation assumes this silently and does not check this on its own!
Definition at line 303 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
bytes()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> std::size_t FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::bytes () const inline
Returns the total amount of bytes allocated.
Returns
0
Definition at line 266 of file null_matrix.hpp.
clone() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> NullMatrix FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::clone (CloneMode clone_mode = CloneMode::Weak) const inline
Clone operation.
Create a clone of this container.
Parameters
[in] clone_mode The actual cloning procedure.
Returns
The created clone.
Definition at line 157 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::NullMatrix(), and FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::_num_rows.
clone() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::clone (const NullMatrix< DT2_, IT2_, BlockHeight_, BlockWidth_ > & other, CloneMode clone_mode = CloneMode::Weak) inline
Clone operation.
Create a clone of another container.
Parameters
[in] other The source container to create the clone from.
[in] clone_mode The actual cloning procedure.
Definition at line 171 of file null_matrix.hpp.
columns()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::columns () const inline
Retrieve matrix column count.
Returns
Matrix column count if perspective_ = false, e.g. count every block as one column.
Raw matrix column count if perspective_ = true, e.g. column_count * BlockWidth_.
Definition at line 217 of file null_matrix.hpp.
References FEAT::LAFEM::pod.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::get_num_nodes_image(), and FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::scale().
convert()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::convert (const NullMatrix< DT2_, IT2_, BlockHeight_, BlockWidth_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 187 of file null_matrix.hpp.
copy()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::copy (const NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The Matrix to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 277 of file null_matrix.hpp.
extract_diag() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> VectorTypeL FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag () const inline
extract main diagonal vector from matrix
Definition at line 775 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag().
extract_diag() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag (VectorTypeL & diag) const inline
Definition at line 767 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag().
format()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::format (const DT_ value = DT_(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 287 of file null_matrix.hpp.
get_checkpoint_size()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> uint64_t FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::get_checkpoint_size () inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 814 of file null_matrix.hpp.
get_num_nodes_domain()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> Index FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::get_num_nodes_domain () const inline
Definition at line 836 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::rows().
get_num_nodes_image()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> Index FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::get_num_nodes_image () const inline
Definition at line 842 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::columns().
image_begin()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> ImageIterator FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin (Index domain_node) const inline
Definition at line 848 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
image_end()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> ImageIterator FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end (Index domain_node) const inline
Definition at line 855 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
lump_rows() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> VectorTypeL FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows () const inline
Returns the lumped rows vector.
Each entry in the returned lumped rows vector contains the the sum of all matrix elements in the corresponding row.
Returns
The lumped vector.
Definition at line 758 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows().
lump_rows() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows (VectorTypeL & lump) const inline
Definition at line 743 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows().
name()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> static String FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 244 of file null_matrix.hpp.
norm_frobenius()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> DT_ FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::norm_frobenius () const inline
Calculates the Frobenius norm of this matrix.
Returns
The Frobenius norm of this matrix.
Definition at line 338 of file null_matrix.hpp.
operator=()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> NullMatrix & FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::operator= (NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ > && other) inline
Move operator.
Parameters
[in] other The source matrix.
Moves another matrix to the target matrix.
Definition at line 141 of file null_matrix.hpp.
resize()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::resize (Index rows_in, Index columns_in) inline
Resizes the matrix to different dimensions.
Parameters
[in] rows_in,columns_in The new dimensions of the matrix.
Definition at line 255 of file null_matrix.hpp.
Referenced by FEAT::Assembly::SymbolicAssembler::assemble_matrix_std1(), and FEAT::Assembly::SymbolicAssembler::assemble_matrix_std2().
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::restore_from_checkpoint_data (std::vector< char > &) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 820 of file null_matrix.hpp.
row_norm2()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2 (VectorTypeL & row_norms) const inline
Computes the 2-norm for every row.
Parameters
[in] row_norms For every row, this left-vector will contain its 2-norm
Definition at line 349 of file null_matrix.hpp.
References XASSERTM.
row_norm2sqr() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr (VectorTypeL & row_norms) const inline
Computes the square of the 2-norm for every row.
Parameters
[out] row_norms For every row, this left-vector will contain the square of its 2-norm
Definition at line 362 of file null_matrix.hpp.
References XASSERTM.
row_norm2sqr() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr (VectorTypeL & row_norms, const VectorTypeR & scal) const inline
Computes the square of the 2-norm for every row, where every row is scaled by a vector.
Parameters
[out] row_norms For every (scaled) row, this left-vector will contain the square of its 2-norm
[in] scal The scaling vector
This computes
\[ row\_norms_i = \sum_{j=0}^{n-1} scal_j (this_{ij})^2 \]
and is used to compute
\[ \mathrm{tr}(B^T \mathrm{diag}(A) B) \]
Definition at line 388 of file null_matrix.hpp.
References XASSERTM.
rows()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::rows () const inline
Retrieve matrix row count.
Returns
Matrix row count if perspective_ = false, e.g. count every block as one row.
Raw matrix row count if perspective_ = true, e.g. row_count * BlockHeight_.
Definition at line 200 of file null_matrix.hpp.
References FEAT::LAFEM::pod.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::get_num_nodes_domain(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows(), and FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::scale().
scale()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::scale (const NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ > & x, const DT_ alpha) inline
Calculate \(this \leftarrow \alpha~ x \).
Parameters
[in] x The matrix to be scaled.
[in] alpha A scalar to scale x with.
Definition at line 324 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
set_checkpoint_data()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::set_checkpoint_data (std::vector< char > &) inline
Definition at line 826 of file null_matrix.hpp.
transpose() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> NullMatrix< DT_, IT_, BlockWidth_, BlockHeight_ > FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose () const inline
Calculate \(this^\top \).
Returns
The transposed matrix
Note
The resulting matrix has transposed block dimensions, too.
Definition at line 403 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::_num_rows.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
transpose() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> void FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose (const NullMatrix< DT_, IT_, BlockWidth_, BlockHeight_ > & x) inline
Calculate \(this \leftarrow x^\top \).
Parameters
[in] x The matrix to be transposed.
Definition at line 413 of file null_matrix.hpp.
References FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
used_elements()
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements () const inline
Retrieve non zero element count.
Returns
Non zero element count if perspective_ = false, e.g. count every block as one entry.
Raw non zero element count if perspective_ = true, e.g. used_elements * BlockHeight_ * BlockWidth_.
Definition at line 234 of file null_matrix.hpp.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy(), and FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::scale().
Member Data Documentation
_num_cols
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> Index FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::_num_cols private
Definition at line 95 of file null_matrix.hpp.
_num_rows
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> Index FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::_num_rows private
matrix dimensions
Definition at line 95 of file null_matrix.hpp.
Referenced by FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), and FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
BlockHeight
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> constexpr int FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockHeight = BlockHeight_ static constexpr
Our block height.
Definition at line 68 of file null_matrix.hpp.
BlockWidth
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> constexpr int FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockWidth = BlockWidth_ static constexpr
Our block width.
Definition at line 70 of file null_matrix.hpp.
is_global
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> constexpr bool FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::is_global = false static constexpr
Definition at line 90 of file null_matrix.hpp.
is_local
template<typename DT_ , typename IT_ , int BlockHeight_ = 1, int BlockWidth_ = 1> constexpr bool FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::is_local = true static constexpr
Definition at line 91 of file null_matrix.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/null_matrix.hpp