FEAT: FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > > Class Template Reference
FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > > Class Template Reference abstract
UzawaPrecond specialization for Global matrices.
#include <uzawa_precond.hpp>
Public Types
typedef Solver::SolverBase< GlobalVectorType > BaseClass
typedef GlobalVectorType::DataType DataType
typedef Global::Gate< LocalVectorTypeP, MirrorP_ > GateTypeP
typedef Global::Gate< LocalVectorTypeV, MirrorV_ > GateTypeV
typedef Global::Filter< LocalFilterType, MirrorType > GlobalFilterType
typedef Global::Filter< FilterP_, MirrorP_ > GlobalFilterTypeP
typedef Global::Filter< FilterV_, MirrorV_ > GlobalFilterTypeV
typedef Global::Matrix< LocalMatrixType, MirrorType, MirrorType > GlobalMatrixType
typedef Global::Matrix< MatrixA_, MirrorV_, MirrorV_ > GlobalMatrixTypeA
typedef Global::Matrix< MatrixB_, MirrorV_, MirrorP_ > GlobalMatrixTypeB
typedef Global::Matrix< MatrixD_, MirrorP_, MirrorV_ > GlobalMatrixTypeD
typedef Global::Vector< LocalVectorType, MirrorType > GlobalVectorType
typedef Global::Vector< LocalVectorTypeP, MirrorP_ > GlobalVectorTypeP
typedef Global::Vector< LocalVectorTypeV, MirrorV_ > GlobalVectorTypeV
typedef LAFEM::TupleFilter< FilterV_, FilterP_ > LocalFilterType
typedef LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > LocalMatrixType
typedef LAFEM::TupleVector< typename MatrixB_::VectorTypeL, typename MatrixD_::VectorTypeL > LocalVectorType
typedef MatrixD_::VectorTypeL LocalVectorTypeP
typedef MatrixB_::VectorTypeL LocalVectorTypeV
typedef LAFEM::TupleMirror< MirrorV_, MirrorP_ > MirrorType
typedef Solver::SolverBase< GlobalVectorTypeV > SolverA
typedef Solver::SolverBase< GlobalVectorTypeP > SolverS
typedef Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > VectorType
The type of vector this solver can be applied to.
Public Member Functions
UzawaPrecond (const GlobalMatrixTypeA &matrix_a, const GlobalMatrixTypeB &matrix_b, const GlobalMatrixTypeD &matrix_d, const GlobalFilterTypeV &filter_v, const GlobalFilterTypeP &filter_p, std::shared_ptr< SolverA > solver_a, std::shared_ptr< SolverS > solver_s, UzawaType type=UzawaType::diagonal, bool auto_init_s=true)
virtual Status apply (Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > &vec_cor, const Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > &vec_def)=0
Solver application method.
virtual Status apply (GlobalVectorType &vec_cor, const GlobalVectorType &vec_def) override
virtual void done ()
Finalization method.
virtual void done_numeric () override
Numeric finalization method.
virtual void done_symbolic () override
Symbolic finalization method.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric initialization method.
virtual void init_symbolic () override
Symbolic initialization method.
virtual String name () const override
Returns a descriptive string.
Protected Attributes
const bool _auto_init_s
const GlobalFilterTypeP & _filter_p
const GlobalFilterTypeV & _filter_v
const GlobalMatrixTypeA & _matrix_a
const GlobalMatrixTypeB & _matrix_b
const GlobalMatrixTypeD & _matrix_d
std::shared_ptr< SolverA > _solver_a
std::shared_ptr< SolverS > _solver_s
UzawaType _uzawa_type
GlobalVectorTypeP _vec_def_p
GlobalVectorTypeV _vec_def_v
GlobalVectorTypeP _vec_rhs_p
GlobalVectorTypeV _vec_rhs_v
GlobalVectorTypeP _vec_sol_p
GlobalVectorTypeV _vec_sol_v
Detailed Description
template<typename MatrixA_, typename MatrixB_, typename MatrixD_, typename FilterV_, typename FilterP_, typename MirrorV_, typename MirrorP_>
class FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >
UzawaPrecond specialization for Global matrices.
Author
Peter Zajac
Definition at line 372 of file uzawa_precond.hpp.
Member Typedef Documentation
BaseClass
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Solver::SolverBase<GlobalVectorType> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::BaseClass
Definition at line 403 of file uzawa_precond.hpp.
DataType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef GlobalVectorType::DataType FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::DataType
Definition at line 401 of file uzawa_precond.hpp.
GateTypeP
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Gate<LocalVectorTypeP, MirrorP_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GateTypeP
Definition at line 419 of file uzawa_precond.hpp.
GateTypeV
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Gate<LocalVectorTypeV, MirrorV_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GateTypeV
Definition at line 418 of file uzawa_precond.hpp.
GlobalFilterType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Filter<LocalFilterType, MirrorType> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalFilterType
Definition at line 398 of file uzawa_precond.hpp.
GlobalFilterTypeP
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Filter<FilterP_, MirrorP_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalFilterTypeP
Definition at line 410 of file uzawa_precond.hpp.
GlobalFilterTypeV
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Filter<FilterV_, MirrorV_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalFilterTypeV
Definition at line 409 of file uzawa_precond.hpp.
GlobalMatrixType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<LocalMatrixType, MirrorType, MirrorType> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalMatrixType
Definition at line 397 of file uzawa_precond.hpp.
GlobalMatrixTypeA
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<MatrixA_, MirrorV_, MirrorV_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalMatrixTypeA
Definition at line 405 of file uzawa_precond.hpp.
GlobalMatrixTypeB
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<MatrixB_, MirrorV_, MirrorP_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalMatrixTypeB
Definition at line 406 of file uzawa_precond.hpp.
GlobalMatrixTypeD
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Matrix<MatrixD_, MirrorP_, MirrorV_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalMatrixTypeD
Definition at line 407 of file uzawa_precond.hpp.
GlobalVectorType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Vector<LocalVectorType, MirrorType> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalVectorType
Definition at line 399 of file uzawa_precond.hpp.
GlobalVectorTypeP
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Vector<LocalVectorTypeP, MirrorP_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalVectorTypeP
Definition at line 416 of file uzawa_precond.hpp.
GlobalVectorTypeV
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Global::Vector<LocalVectorTypeV, MirrorV_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::GlobalVectorTypeV
Definition at line 415 of file uzawa_precond.hpp.
LocalFilterType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef LAFEM::TupleFilter<FilterV_, FilterP_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalFilterType
Definition at line 393 of file uzawa_precond.hpp.
LocalMatrixType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef LAFEM::SaddlePointMatrix<MatrixA_, MatrixB_, MatrixD_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalMatrixType
Definition at line 392 of file uzawa_precond.hpp.
LocalVectorType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef LAFEM::TupleVector<typename MatrixB_::VectorTypeL, typename MatrixD_::VectorTypeL> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalVectorType
Definition at line 394 of file uzawa_precond.hpp.
LocalVectorTypeP
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef MatrixD_::VectorTypeL FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalVectorTypeP
Definition at line 413 of file uzawa_precond.hpp.
LocalVectorTypeV
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef MatrixB_::VectorTypeL FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::LocalVectorTypeV
Definition at line 412 of file uzawa_precond.hpp.
MirrorType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef LAFEM::TupleMirror<MirrorV_, MirrorP_> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::MirrorType
Definition at line 395 of file uzawa_precond.hpp.
SolverA
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Solver::SolverBase<GlobalVectorTypeV> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::SolverA
Definition at line 421 of file uzawa_precond.hpp.
SolverS
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > typedef Solver::SolverBase<GlobalVectorTypeP> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::SolverS
Definition at line 422 of file uzawa_precond.hpp.
VectorType
typedef Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >::VectorType inherited
The type of vector this solver can be applied to.
Definition at line 186 of file base.hpp.
Constructor & Destructor Documentation
UzawaPrecond()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::UzawaPrecond (const GlobalMatrixTypeA & matrix_a, const GlobalMatrixTypeB & matrix_b, const GlobalMatrixTypeD & matrix_d, const GlobalFilterTypeV & filter_v, const GlobalFilterTypeP & filter_p, std::shared_ptr< SolverA > solver_a, std::shared_ptr< SolverS > solver_s, UzawaType type = UzawaType::diagonal, bool auto_init_s = true) inline explicit
Definition at line 438 of file uzawa_precond.hpp.
Member Function Documentation
apply() [1/2]
virtual Status FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >::apply (Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > & vec_cor, const Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
apply() [2/2]
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual Status FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::apply (GlobalVectorType & vec_cor, const GlobalVectorType & vec_def) inline override virtual
Definition at line 526 of file uzawa_precond.hpp.
done()
virtual void FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
done_numeric()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual void FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric () inline override virtual
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 497 of file uzawa_precond.hpp.
References FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_auto_init_s, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_a, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_s, and FEAT::Solver::SolverBase< Vector_ >::done_numeric().
done_symbolic()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual void FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_symbolic () inline override virtual
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 507 of file uzawa_precond.hpp.
References FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_auto_init_s, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_a, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_s, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_uzawa_type, FEAT::Global::Vector< LocalVector_, Mirror_ >::clear(), FEAT::Solver::diagonal, and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
init()
virtual void FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
init_numeric()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual void FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_numeric () inline override virtual
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 487 of file uzawa_precond.hpp.
References FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_auto_init_s, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_a, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_s, and FEAT::Solver::SolverBase< Vector_ >::init_numeric().
init_symbolic()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual void FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 466 of file uzawa_precond.hpp.
References FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_auto_init_s, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_a, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_solver_s, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::_uzawa_type, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::create_vector_l(), FEAT::Solver::diagonal, and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
name()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > virtual String FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::name () const inline override virtual
Returns a descriptive string.
Returns
A string describing the solver.
Implements FEAT::Solver::SolverBase< Global::Vector< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL >, LAFEM::TupleMirror< MirrorV_, MirrorP_ > > >.
Definition at line 461 of file uzawa_precond.hpp.
Member Data Documentation
_auto_init_s
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const bool FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_auto_init_s protected
Definition at line 435 of file uzawa_precond.hpp.
_filter_p
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalFilterTypeP& FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_filter_p protected
Definition at line 429 of file uzawa_precond.hpp.
_filter_v
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalFilterTypeV& FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_filter_v protected
Definition at line 428 of file uzawa_precond.hpp.
_matrix_a
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalMatrixTypeA& FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_matrix_a protected
Definition at line 425 of file uzawa_precond.hpp.
_matrix_b
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalMatrixTypeB& FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_matrix_b protected
Definition at line 426 of file uzawa_precond.hpp.
_matrix_d
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > const GlobalMatrixTypeD& FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_matrix_d protected
Definition at line 427 of file uzawa_precond.hpp.
_solver_a
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > std::shared_ptr<SolverA> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_solver_a protected
Definition at line 432 of file uzawa_precond.hpp.
_solver_s
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > std::shared_ptr<SolverS> FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_solver_s protected
Definition at line 433 of file uzawa_precond.hpp.
_uzawa_type
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > UzawaType FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_uzawa_type protected
Definition at line 434 of file uzawa_precond.hpp.
_vec_def_p
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeP FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_vec_def_p protected
Definition at line 431 of file uzawa_precond.hpp.
_vec_def_v
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeV FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_vec_def_v protected
Definition at line 430 of file uzawa_precond.hpp.
_vec_rhs_p
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeP FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_vec_rhs_p protected
Definition at line 431 of file uzawa_precond.hpp.
_vec_rhs_v
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeV FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_vec_rhs_v protected
Definition at line 430 of file uzawa_precond.hpp.
_vec_sol_p
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeP FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_vec_sol_p protected
Definition at line 431 of file uzawa_precond.hpp.
_vec_sol_v
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ , typename MirrorV_ , typename MirrorP_ > GlobalVectorTypeV FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::_vec_sol_v protected
Definition at line 430 of file uzawa_precond.hpp.
The documentation for this class was generated from the following file:
kernel/solver/uzawa_precond.hpp