FEAT: FEAT::Assembly::SlipFilterAssembler< Trafo_ > Class Template Reference
FEAT::Assembly::SlipFilterAssembler< Trafo_ > Class Template Reference
Contains routines to assemble slip filters.
#include <slip_filter_assembler.hpp>
Public Types
typedef MeshType::CoordType CoordType
Floating point type.
typedef TrafoType::MeshType MeshType
The mesh type.
typedef Geometry::TargetSetHolder< typename MeshType::ShapeType > TargetSetHolderType
Type for the mapping of slip boundary entities to mesh entities.
typedef Trafo_ TrafoType
the trafo type
Public Member Functions
SlipFilterAssembler (const SlipFilterAssembler &)=delete
Explicitly delete the copy constructor.
SlipFilterAssembler (const TrafoType &trafo)
Constructor from mesh.
SlipFilterAssembler (SlipFilterAssembler &&)=delete
Explicitly delete the move constructor.
virtual ~SlipFilterAssembler ()
Virtual destructor.
void add_mesh_part (const Geometry::MeshPart< MeshType > &meshpart)
Adds a MeshPart to the assembler.
template<typename DataType_ , typename IndexType_ >
void assemble (LAFEM::SlipFilter< DataType_, IndexType_, world_dim > &filter, const Space::Lagrange1::Element< Trafo_ > &space)
Assembles a homogeneous SlipFilter for a Lagrange 1 FE space.
template<typename DataType_ , typename IndexType_ >
void assemble (LAFEM::SlipFilter< DataType_, IndexType_, world_dim > &filter, const Space::Lagrange2::Element< Trafo_ > &space)
Assembles a homogeneous SlipFilter for a Lagrange 2 FE space.
SlipFilterAssembler & operator= (SlipFilterAssembler &&)=delete
Explicitly delete the move assignment operator.
void recompute_target_set_holder (const MeshType &mesh)
Recomputes the target mapping for geometric entities.
Static Public Attributes
static constexpr int facet_dim = MeshType::shape_dim-1
shape dimension
static constexpr int world_dim = MeshType::world_dim
The number of coordinates for each vertex.
Private Attributes
std::vector< Index > _facets
Facets for the slip condition get marked by this.
Index _num_entities [MeshType::shape_dim+1]
Number of entities of various shape dimensions in the slip boundary represented by this filter.
std::vector< CoordType > _orientation
For every facet in the mesh, this is its orientation in the mesh.
bool _recompute
Flag when to recompute _facets and _orientation (i.e. if MeshParts get added)
TargetSetHolderType _target_set_holder
Mapping of boundary entities to mesh entities (i.e. vertices, edges, facets)
const TrafoType & _trafo
a reference to the trafo that we want to assemble on
Detailed Description
template<typename Trafo_>
class FEAT::Assembly::SlipFilterAssembler< Trafo_ >
Contains routines to assemble slip filters.
Template Parameters
Trafo_ The trafo type.
The assemble() routine is implemented for the homogeneous slip condition for Lagrange 1/2 elements only. For the many other limitations, see the SlipFilter class documentation.
See also
SlipFilter
Author
Jordi Paul, Peter Zajac
Definition at line 310 of file slip_filter_assembler.hpp.
Member Typedef Documentation
CoordType
template<typename Trafo_ > typedef MeshType::CoordType FEAT::Assembly::SlipFilterAssembler< Trafo_ >::CoordType
Floating point type.
Definition at line 318 of file slip_filter_assembler.hpp.
MeshType
template<typename Trafo_ > typedef TrafoType::MeshType FEAT::Assembly::SlipFilterAssembler< Trafo_ >::MeshType
The mesh type.
Definition at line 316 of file slip_filter_assembler.hpp.
TargetSetHolderType
template<typename Trafo_ > typedef Geometry::TargetSetHolder<typename MeshType::ShapeType> FEAT::Assembly::SlipFilterAssembler< Trafo_ >::TargetSetHolderType
Type for the mapping of slip boundary entities to mesh entities.
Definition at line 320 of file slip_filter_assembler.hpp.
TrafoType
template<typename Trafo_ > typedef Trafo_ FEAT::Assembly::SlipFilterAssembler< Trafo_ >::TrafoType
the trafo type
Definition at line 314 of file slip_filter_assembler.hpp.
Constructor & Destructor Documentation
SlipFilterAssembler()
template<typename Trafo_ > FEAT::Assembly::SlipFilterAssembler< Trafo_ >::SlipFilterAssembler (const TrafoType & trafo) inline explicit
Constructor from mesh.
Parameters
[in] trafo A resident reference to the trafo to assemble the slip filter on
We need to know the number of vertices in the mesh for the final sizes of _facets and _orientation, or some sort of size management has to be implemented
Definition at line 350 of file slip_filter_assembler.hpp.
References FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_num_entities.
~SlipFilterAssembler()
template<typename Trafo_ > virtual FEAT::Assembly::SlipFilterAssembler< Trafo_ >::~SlipFilterAssembler () inline virtual
Virtual destructor.
Definition at line 371 of file slip_filter_assembler.hpp.
Member Function Documentation
add_mesh_part()
template<typename Trafo_ > void FEAT::Assembly::SlipFilterAssembler< Trafo_ >::add_mesh_part (const Geometry::MeshPart< MeshType > & meshpart) inline
Adds a MeshPart to the assembler.
This means that the boundary where the slip condition is enforced gets enlarged by the MeshPart.
Parameters
[in] meshpart MeshPart identifying a part of the boundary where to enforce the slip condition
Definition at line 384 of file slip_filter_assembler.hpp.
References FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_facets, FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_num_entities, and FEAT::Assembly::SlipFilterAssembler< Trafo_ >::facet_dim.
assemble() [1/2]
template<typename Trafo_ > template<typename DataType_ , typename IndexType_ > void FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble (LAFEM::SlipFilter< DataType_, IndexType_, world_dim > & filter, const Space::Lagrange1::Element< Trafo_ > & space) inline
Assembles a homogeneous SlipFilter for a Lagrange 1 FE space.
Template Parameters
Trafo_ The transformation
DataType_ Data type for the filter
IndexType_ Index type for the filter
Parameters
[in,out] filter The filter to be assembled
[in,out] space The filter gets applied of functions of this FE space
Definition at line 450 of file slip_filter_assembler.hpp.
References FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_facets, FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_orientation, FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_recompute, FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clone(), FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_orientations(), FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_outer_unit_normal(), FEAT::Space::Lagrange1::Element< Trafo_ >::get_num_dofs(), FEAT::Space::ElementBase< Trafo_ >::get_trafo(), and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::size().
assemble() [2/2]
template<typename Trafo_ > template<typename DataType_ , typename IndexType_ > void FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble (LAFEM::SlipFilter< DataType_, IndexType_, world_dim > & filter, const Space::Lagrange2::Element< Trafo_ > & space) inline
Assembles a homogeneous SlipFilter for a Lagrange 2 FE space.
Template Parameters
Trafo_ The transformation
DataType_ Data type for the filter
IndexType_ Index type for the filter
Parameters
[in,out] filter The filter to be assembled
[in,out] space The filter gets applied of functions of this FE space
This implements a primitive P1/Q1 to P2/Q2 interpolation of the outer unit normal vector field. It would be nicer to have a real inter FE space mapping, but that would require the application of node functionals to FE functions. This is not implemented yet due to regularity issues (i.e. application of a Q1 node functional requires point evaluation at mesh vertices, but Q1~ functions are not continuous so this is not possible).
Definition at line 499 of file slip_filter_assembler.hpp.
References FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_facets, FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_orientation, FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_recompute, FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_target_set_holder, FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_orientations(), FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_outer_unit_normal(), FEAT::Space::Lagrange2::Element< Trafo_ >::get_num_dofs(), FEAT::Space::ElementBase< Trafo_ >::get_trafo(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::get_values(), FEAT::Assembly::SlipFilterAssembler< Trafo_ >::recompute_target_set_holder(), FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::size(), and FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::used_elements().
recompute_target_set_holder()
template<typename Trafo_ > void FEAT::Assembly::SlipFilterAssembler< Trafo_ >::recompute_target_set_holder (const MeshType & mesh) inline
Recomputes the target mapping for geometric entities.
Parameters
[in] mesh The slip boundary this filter represents is part of this mesh.
Definition at line 408 of file slip_filter_assembler.hpp.
References FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_facets, FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_num_entities, FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_target_set_holder, and FEAT::Assembly::SlipFilterAssembler< Trafo_ >::facet_dim.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
Member Data Documentation
_facets
template<typename Trafo_ > std::vector<Index> FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_facets private
Facets for the slip condition get marked by this.
Definition at line 330 of file slip_filter_assembler.hpp.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::add_mesh_part(), FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble(), and FEAT::Assembly::SlipFilterAssembler< Trafo_ >::recompute_target_set_holder().
_num_entities
template<typename Trafo_ > Index FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_num_entities[MeshType::shape_dim+1] private
Number of entities of various shape dimensions in the slip boundary represented by this filter.
Definition at line 336 of file slip_filter_assembler.hpp.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::SlipFilterAssembler(), FEAT::Assembly::SlipFilterAssembler< Trafo_ >::add_mesh_part(), and FEAT::Assembly::SlipFilterAssembler< Trafo_ >::recompute_target_set_holder().
_orientation
template<typename Trafo_ > std::vector<CoordType> FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_orientation private
For every facet in the mesh, this is its orientation in the mesh.
Definition at line 332 of file slip_filter_assembler.hpp.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
_recompute
template<typename Trafo_ > bool FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_recompute private
Flag when to recompute _facets and _orientation (i.e. if MeshParts get added)
Definition at line 334 of file slip_filter_assembler.hpp.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
_target_set_holder
template<typename Trafo_ > TargetSetHolderType FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_target_set_holder private
Mapping of boundary entities to mesh entities (i.e. vertices, edges, facets)
Definition at line 338 of file slip_filter_assembler.hpp.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble(), and FEAT::Assembly::SlipFilterAssembler< Trafo_ >::recompute_target_set_holder().
_trafo
template<typename Trafo_ > const TrafoType& FEAT::Assembly::SlipFilterAssembler< Trafo_ >::_trafo private
a reference to the trafo that we want to assemble on
Definition at line 328 of file slip_filter_assembler.hpp.
facet_dim
template<typename Trafo_ > constexpr int FEAT::Assembly::SlipFilterAssembler< Trafo_ >::facet_dim = MeshType::shape_dim-1 static constexpr
shape dimension
Definition at line 322 of file slip_filter_assembler.hpp.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::add_mesh_part(), and FEAT::Assembly::SlipFilterAssembler< Trafo_ >::recompute_target_set_holder().
world_dim
template<typename Trafo_ > constexpr int FEAT::Assembly::SlipFilterAssembler< Trafo_ >::world_dim = MeshType::world_dim static constexpr
The number of coordinates for each vertex.
Definition at line 324 of file slip_filter_assembler.hpp.
The documentation for this class was generated from the following file:
kernel/assembly/slip_filter_assembler.hpp