FEAT: FEAT::Geometry::IndexCalculator< Shape_, face_dim_ > Class Template Reference
FEAT::Geometry::IndexCalculator< Shape_, face_dim_ > Class Template Reference
Calculates the missing index sets if the vertex-at-shape index sets are given.
#include <index_calculator.hpp>
Public Types
typedef Shape::FaceTraits< Shape_, face_dim_ >::ShapeType FaceType
Type of the subshape to calculate the missing information at.
typedef IndexTree< FaceType > IndexTreeType
Type for the IndexTree containing vertex@subshape information.
Static Public Member Functions
template<typename IndexSetIn_ , typename IndexSetOut_ >
static bool compute (const IndexTreeType &index_tree, const IndexSetIn_ &index_set_in, IndexSetOut_ &index_set_out)
Calculates an index set from vertex@shape information.
template<typename IndexSetIn_ , typename IndexSetOut_ >
static void compute_vertex_subshape (const IndexSetIn_ &index_set_in, IndexSetOut_ &index_set_out)
For given vertex@shape information, numbers subshapes and calculates vertex@subshape.
static String name ()
Returns the class name.
Detailed Description
template<typename Shape_, int face_dim_>
class FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >
Calculates the missing index sets if the vertex-at-shape index sets are given.
Author
Constantin Christof
Definition at line 260 of file index_calculator.hpp.
Member Typedef Documentation
FaceType
template<typename Shape_ , int face_dim_> typedef Shape::FaceTraits<Shape_,face_dim_>::ShapeType FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::FaceType
Type of the subshape to calculate the missing information at.
Definition at line 264 of file index_calculator.hpp.
IndexTreeType
template<typename Shape_ , int face_dim_> typedef IndexTree<FaceType> FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::IndexTreeType
Type for the IndexTree containing vertex@subshape information.
Definition at line 266 of file index_calculator.hpp.
Member Function Documentation
compute()
template<typename Shape_ , int face_dim_> template<typename IndexSetIn_ , typename IndexSetOut_ > static bool FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute (const IndexTreeType & index_tree, const IndexSetIn_ & index_set_in, IndexSetOut_ & index_set_out) inline static
Calculates an index set from vertex@shape information.
Assume that for a Hypercube<3>, we have the vertex@cell information. This routine can generate the edge@cell or face@cell information from this.
More generic: From vertex@shape, generate subshape@shape, where the type/dimension of subshape is determined by face_dim_
Template Parameters
IndexSetIn_ Type for the vertex@shape information IndexSet.
IndexSetOut_ Type for the subshape@shape information IndexSet.
Parameters
[in] index_tree For every entity of subshape, this IndexTree holds the information which vertices this entity contains.
[in] index_set_in Provided vertex@shape information.
[out] index_set_out subshape@shape information.
Definition at line 297 of file index_calculator.hpp.
References FEAT::Geometry::IndexTree< Shape_ >::find(), and FEAT::Geometry::IndexTree< Shape_ >::num_indices.
compute_vertex_subshape()
template<typename Shape_ , int face_dim_> template<typename IndexSetIn_ , typename IndexSetOut_ > static void FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::compute_vertex_subshape (const IndexSetIn_ & index_set_in, IndexSetOut_ & index_set_out) inline static
For given vertex@shape information, numbers subshapes and calculates vertex@subshape.
Definition at line 343 of file index_calculator.hpp.
References FEAT::Geometry::IndexTree< Shape_ >::enumerate(), FEAT::Geometry::IndexTree< Shape_ >::get_index(), FEAT::Geometry::IndexTree< Shape_ >::get_set_size(), FEAT::Geometry::IndexTree< Shape_ >::insert(), and FEAT::Geometry::IndexTree< Shape_ >::num_indices.
name()
template<typename Shape_ , int face_dim_> static String FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::name () inline static
Returns the class name.
Definition at line 408 of file index_calculator.hpp.
References FEAT::stringify().
The documentation for this class was generated from the following file:
kernel/geometry/index_calculator.hpp