FEAT: FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ > Class Template Reference
FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ > Class Template Reference
Storage class for AdaptiveMeshes.
#include <adaptive_mesh_storage.hpp>
Public Types
template<int dim_>
using AdaptiveElementByDim = AdaptiveElement< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >
Accessor for adaptive elements by dimension.
using AdaptiveVertexType = AdaptiveVertex< VertexType >
Adaptive vertex type.
using CoordType = typename VertexType_::ValueType
template<int dim_>
using ElementChildrenByDim = ElementChildren< TemplateSet_, typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >
Accessor for element children by dimension.
template<int dim_>
using ElementRefByDim = ElementKey< dim_ >
Accessor for element reference types by dimension.
template<int dim_>
using ElementTopologyByDim = ElementTopology< typename Shape::FaceTraits< MeshShape_, dim_ >::ShapeType >
Accessor for element topologies by dimension.
enum class IterationOrder { PreOrder , PostOrder }
template<int dim_>
using OrientedElementRefByDim = OrientedElement< dim_ >
Accessor for oriented element types by dimension.
using TemplateSet = TemplateSet_
Template set to be used for refinement.
using VertexType = VertexType_
Type of vertices in this mesh.
Public Member Functions
std::size_t bytes () const
Returns the number of bytes used by this class.
template<int dim_>
std::array< Index, 4 > erase (ElementKey< dim_ > key)
Erases an element and all its children from the storage.
void fill_neighbors ()
Determines neighboring elements for all mesh elements.
template<int dim_>
AdaptiveElementByDim< dim_ > & get_by_index (Layer layer, Index idx)
Retrieves an element of the mesh by its layer and index.
template<int dim_>
const AdaptiveElementByDim< dim_ > & get_by_index (Layer layer, Index idx) const
Retrieves an element of the mesh by its layer and index.
template<int dim_>
Index get_index (ElementKey< dim_ > key) const
Get the numeric mesh index of the element pointed to by key.
template<int dim_>
Index get_index (OrientedElement< dim_ > oriented_key) const
Get the numeric mesh index of the element pointed to by key.
Index get_neighbor (Layer layer, Index element_idx, Index neighbor_idx) const
Returns the index of the n-th neighbor of the given element.
AdaptiveVertexType & get_vertex_by_index (Layer layer, Index idx)
Retrieves a vertex of the mesh by its layer and index.
const AdaptiveVertexType & get_vertex_by_index (Layer layer, Index idx) const
Retrieves a vertex of the mesh by its layer and index.
template<typename Shape_ >
ElementKey< Shape_::dimension > insert (const AdaptiveElement< TemplateSet, Shape_ > &element)
Insert an adaptive element into the storage.
VertexKey insert (const AdaptiveVertexType &vertex)
Insert a vertex into the storage.
VertexKey insert (VertexType vertex, Layer layer)
Insert a vertex into the storage.
Index num_entities (Layer layer, int dim) const
Returns the number of mesh elements of the given dimension on the given layer.
Index num_layers () const
Return the number of layers in this mesh.
template<int dim_>
Index num_total_entities () const
Returns the total number of all mesh elements in the storage.
template<int dim_>
AdaptiveElementByDim< dim_ > & operator[] (ElementKey< dim_ > key)
Retrieve element by key.
template<int dim_>
const AdaptiveElementByDim< dim_ > & operator[] (ElementKey< dim_ > key) const
Retrieve element by key.
AdaptiveVertexType & operator[] (OrientedElement< 0 > ref)
const AdaptiveVertexType & operator[] (OrientedElement< 0 > ref) const
template<int dim_>
AdaptiveElementByDim< dim_ > & operator[] (OrientedElement< dim_ > ref)
Retrieve element by oriented reference.
template<int dim_>
const AdaptiveElementByDim< dim_ > & operator[] (OrientedElement< dim_ > ref) const
AdaptiveVertexType & operator[] (VertexKey key)
Retrieve vertex by key.
const AdaptiveVertexType & operator[] (VertexKey key) const
Retrieve vertex by key.
void reindex ()
Re-indexes the storage.
void transform (const VertexType &origin, const VertexType &angles, const VertexType &offset)
Applies a "proper rigid" transformation onto the mesh vertices.
template<int dim>
TemplateSet::template RefinementTypeByDim< dim > type (ElementKey< dim > key)
Get refinement type of element.
template<typename VisitorType_ , int dim_>
void walk_subtree (ElementKey< dim_ > root_key, VisitorType_ &visitor, Layer max_depth, IterationOrder order=IterationOrder::PreOrder) const
template<typename VisitorType_ >
void walk_tree (VisitorType_ &visitor, Layer max_depth, IterationOrder order=IterationOrder::PreOrder) const
Private Types
using MeshLayerType = MeshLayer< TemplateSet, MeshShape_, VertexType >
Type of a mesh layer for this mesh.
Private Member Functions
void _add_mesh_layers (Index new_top_layer)
Adds additional mesh layers, such that.
template<typename Shape_ , int dim_ = Shape_::dimension>
std::array< Index, 4 > _erase_children (typename TemplateSet::template RefinementTypeByDim< Shape_::dimension > type, ElementChildren< TemplateSet, Shape_ > &children)
template<int dim_>
void _index_layer (MeshLayerType &layer, Index &next_permanent_index)
Assigns indexes to all elemens of a layer.
template<int dim_>
Index _num_entities (Layer layer) const
Returns the number of mesh elements of the given dimension on the given layer.
template<typename Shape_ , int dim_ = Shape_::dimension, typename VisitorType >
void _walk_subtree_children (const AdaptiveElement< TemplateSet, Shape_ > &root, VisitorType &visitor, Layer max_depth) const
Static Private Member Functions
template<int sm_, int sn_, int sv_>
static void _aux_rot_mat (Tiny::Matrix< CoordType, 1, 1, sm_, sn_ > &r, const Tiny::Vector< CoordType, 1, sv_ > &)
Helper for transform method.
template<int sm_, int sn_, int sv_>
static void _aux_rot_mat (Tiny::Matrix< CoordType, 2, 2, sm_, sn_ > &r, const Tiny::Vector< CoordType, 2, sv_ > &a)
Helper for transform method.
template<int sm_, int sn_, int sv_>
static void _aux_rot_mat (Tiny::Matrix< CoordType, 3, 3, sm_, sn_ > &r, const Tiny::Vector< CoordType, 3, sv_ > &a)
Helper for transform method.
Private Attributes
bool _has_neighbors = false
Indicates whether neighbors have been calculated for this mesh.
bool _is_indexed = false
Indicates whether this mesh has been indexed since the last modification.
std::vector< MeshLayerType > _layers
List of MeshLayers for this mesh.
Static Private Attributes
static const constexpr ElementKey< MeshShape_::dimension > neighbor_sentinel = ElementKey<MeshShape_::dimension>()
Sentinel key for non-existing neighbors, e.g. for boundary elements.
static constexpr int num_coords = VertexType::n
Detailed Description
template<typename MeshShape_, typename TemplateSet_, typename VertexType_>
class FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >
Storage class for AdaptiveMeshes.
Handles storing refinement trees for the AdaptiveMesh. Mesh elements are stored separated by layer.
Allows accessing elements via SlotMap keys and by index. To allow access via indices, the storage must first be indexed via AdaptiveMeshStorage::reindex(). After creation and after any modification of the tree structure the storage is unindexed. If the storage is unindexed, retrieving an element via its index will abort the program. Ensure you call AdaptiveMeshStorage::reindex after any modification before retrieving elements
Template Parameters
MeshShape_ Shape type of the mesh to be stored
TemplateSet_ Template set for mesh refinement
VertexType_ Type of mesh vertices to be stored
Author
Markus Muegge
Definition at line 750 of file adaptive_mesh_storage.hpp.
Member Typedef Documentation
AdaptiveElementByDim
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::AdaptiveElementByDim = AdaptiveElement<TemplateSet_, typename Shape::FaceTraits<MeshShape_, dim_>::ShapeType>
Accessor for adaptive elements by dimension.
Definition at line 779 of file adaptive_mesh_storage.hpp.
AdaptiveVertexType
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::AdaptiveVertexType = AdaptiveVertex<VertexType>
Adaptive vertex type.
Definition at line 782 of file adaptive_mesh_storage.hpp.
CoordType
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::CoordType = typename VertexType_::ValueType
Definition at line 756 of file adaptive_mesh_storage.hpp.
ElementChildrenByDim
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::ElementChildrenByDim = ElementChildren<TemplateSet_, typename Shape::FaceTraits<MeshShape_, dim_>::ShapeType>
Accessor for element children by dimension.
Definition at line 775 of file adaptive_mesh_storage.hpp.
ElementRefByDim
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::ElementRefByDim = ElementKey<dim_>
Accessor for element reference types by dimension.
Definition at line 763 of file adaptive_mesh_storage.hpp.
ElementTopologyByDim
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::ElementTopologyByDim = ElementTopology<typename Shape::FaceTraits<MeshShape_, dim_>::ShapeType>
Accessor for element topologies by dimension.
Definition at line 771 of file adaptive_mesh_storage.hpp.
MeshLayerType
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::MeshLayerType = MeshLayer<TemplateSet, MeshShape_, VertexType> private
Type of a mesh layer for this mesh.
Definition at line 795 of file adaptive_mesh_storage.hpp.
OrientedElementRefByDim
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::OrientedElementRefByDim = OrientedElement<dim_>
Accessor for oriented element types by dimension.
Definition at line 767 of file adaptive_mesh_storage.hpp.
TemplateSet
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::TemplateSet = TemplateSet_
Template set to be used for refinement.
Definition at line 759 of file adaptive_mesh_storage.hpp.
VertexType
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > using FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::VertexType = VertexType_
Type of vertices in this mesh.
Definition at line 754 of file adaptive_mesh_storage.hpp.
Member Enumeration Documentation
IterationOrder
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > enum class FEAT::Geometry::Intern::AdaptiveMeshStorage::IterationOrder strong
Traversal orders for iterating over refinement trees
Definition at line 787 of file adaptive_mesh_storage.hpp.
Member Function Documentation
_add_mesh_layers()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_add_mesh_layers (Index new_top_layer) inline private
Adds additional mesh layers, such that.
\code_layers[new_top_layer]
eexists.
Definition at line 1699 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers.
Referenced by FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert().
_aux_rot_mat() [1/3]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int sm_, int sn_, int sv_> static void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_aux_rot_mat (Tiny::Matrix< CoordType, 1, 1, sm_, sn_ > & r, const Tiny::Vector< CoordType, 1, sv_ > &) inline static private
Helper for transform method.
Definition at line 1741 of file adaptive_mesh_storage.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_identity().
Referenced by FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::transform().
_aux_rot_mat() [2/3]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int sm_, int sn_, int sv_> static void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_aux_rot_mat (Tiny::Matrix< CoordType, 2, 2, sm_, sn_ > & r, const Tiny::Vector< CoordType, 2, sv_ > & a) inline static private
Helper for transform method.
Definition at line 1752 of file adaptive_mesh_storage.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_2d().
_aux_rot_mat() [3/3]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int sm_, int sn_, int sv_> static void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_aux_rot_mat (Tiny::Matrix< CoordType, 3, 3, sm_, sn_ > & r, const Tiny::Vector< CoordType, 3, sv_ > & a) inline static private
Helper for transform method.
Definition at line 1763 of file adaptive_mesh_storage.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_3d().
_erase_children()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<typename Shape_ , int dim_ = Shape_::dimension> std::array< Index, 4 > FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_erase_children (typename TemplateSet::template RefinementTypeByDim< Shape_::dimension > type, ElementChildren< TemplateSet, Shape_ > & children) inline private
Definition at line 1650 of file adaptive_mesh_storage.hpp.
_index_layer()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_index_layer (MeshLayerType & layer, Index & next_permanent_index) inline private
Assigns indexes to all elemens of a layer.
Template Parameters
dim_ Dimension of elements to assign indices to
Parameters
[in] layer Layer whose elements will be assigned indices
[in,out] Initial next permanent index, will contain first permanent index for next layer after call finishes
Definition at line 1716 of file adaptive_mesh_storage.hpp.
_num_entities()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> Index FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_num_entities (Layer layer) const inline private
Returns the number of mesh elements of the given dimension on the given layer.
Template Parameters
dim_ Dimension to query
Parameters
[in] layer Layer to count elements of
Note
O(num_layers) complexity
Definition at line 1628 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, ASSERT, and FEAT::Geometry::Intern::Layer::idx.
_walk_subtree_children()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<typename Shape_ , int dim_ = Shape_::dimension, typename VisitorType > void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_walk_subtree_children (const AdaptiveElement< TemplateSet, Shape_ > & root, VisitorType & visitor, Layer max_depth) const inline private
Definition at line 1678 of file adaptive_mesh_storage.hpp.
bytes()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > std::size_t FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::bytes () const inline
Returns the number of bytes used by this class.
Definition at line 1608 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers.
erase()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> std::array< Index, 4 > FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::erase (ElementKey< dim_ > key) inline
Erases an element and all its children from the storage.
Parameters
[in] key Key of the root element to be erased
Returns
An array indicating how many elemets of each dimension were erased
Attention
Unindexes the storage!
Definition at line 836 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_has_neighbors, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, ASSERTM, FEAT::Geometry::Intern::Layer::idx, and FEAT::Geometry::Intern::ElementKey< n >::layer.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_erase().
fill_neighbors()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::fill_neighbors () inline
Determines neighboring elements for all mesh elements.
Definition at line 1126 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_has_neighbors, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, FEAT::Geometry::Intern::ElementKey< n >::is_permanent, FEAT::Geometry::Intern::ElementKey< n >::layer, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::neighbor_sentinel, and XABORTM.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::fill_neighbors().
get_by_index() [1/2]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> AdaptiveElementByDim< dim_ > & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_by_index (Layer layer, Index idx) inline
Retrieves an element of the mesh by its layer and index.
Template Parameters
dim_ Dimension of the element to retrieve
Parameters
[in] layer The layer to retrieve the element from
[in] idx The numeric index of the element
Returns
A reference to the element
Attention
Requires the storage to be indexed!
Definition at line 1491 of file adaptive_mesh_storage.hpp.
get_by_index() [2/2]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> const AdaptiveElementByDim< dim_ > & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_by_index (Layer layer, Index idx) const inline
Retrieves an element of the mesh by its layer and index.
Template Parameters
dim_ Dimension of the element to retrieve
Parameters
[in] layer The layer to retrieve the element from
[in] idx The numeric index of the element
Returns
A reference to the element
Attention
Requires the storage to be indexed!
Definition at line 1448 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, ASSERT, ASSERTM, FEAT::Geometry::Intern::Layer::idx, and XABORTM.
get_index() [1/2]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> Index FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_index (ElementKey< dim_ > key) const inline
Get the numeric mesh index of the element pointed to by key.
Template Parameters
dim_ Dimension to query
Parameters
[in] key Key pointing to mesh element whose index should be retrieved
Attention
Requires the storage to be indexed!
Definition at line 1531 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, and ASSERT.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::bridge_pairs(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::get_child(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::get_face_index(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_neighbor(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::get_overlap_cell(), and FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::overlap_mapping().
get_index() [2/2]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> Index FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_index (OrientedElement< dim_ > oriented_key) const inline
Get the numeric mesh index of the element pointed to by key.
Template Parameters
dim_ Dimension to query
Parameters
[in] key Key pointing to mesh element whose index should be retrieved
Attention
Requires the storage to be indexed!
Definition at line 1546 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, and ASSERT.
get_neighbor()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > Index FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_neighbor (Layer layer, Index element_idx, Index neighbor_idx) const inline
Returns the index of the n-th neighbor of the given element.
Returns
The index of the neighbor, if one exists, ~Index(0) otherwise.
Definition at line 1504 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_has_neighbors, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, ASSERT, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_index(), and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::neighbor_sentinel.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::get_neighbor().
get_vertex_by_index() [1/2]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > AdaptiveVertexType & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_vertex_by_index (Layer layer, Index idx) inline
Retrieves a vertex of the mesh by its layer and index.
Parameters
[in] layer The layer to retrieve a vertex of
[in] idx The numeric index of the vertex
Returns
A reference to the vertex
Attention
Requires the storage to be indexed!
Definition at line 1428 of file adaptive_mesh_storage.hpp.
get_vertex_by_index() [2/2]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > const AdaptiveVertexType & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_vertex_by_index (Layer layer, Index idx) const inline
Retrieves a vertex of the mesh by its layer and index.
Parameters
[in] layer The layer to retrieve a vertex of
[in] idx The numeric index of the vertex
Returns
A reference to the vertex
Attention
Requires the storage to be indexed!
Definition at line 1385 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, ASSERT, ASSERTM, FEAT::Geometry::Intern::Layer::idx, and XABORTM.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::has_vertex_changed(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::transfer_sdls(), and FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::vertex().
insert() [1/3]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<typename Shape_ > ElementKey< Shape_::dimension > FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert (const AdaptiveElement< TemplateSet, Shape_ > & element) inline
Insert an adaptive element into the storage.
Parameters
[in] element r-value reference to the element to be inserted
Attention
Unindexes the storage!
Definition at line 909 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_add_mesh_layers(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_has_neighbors, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, FEAT::Geometry::Intern::Layer::idx, FEAT::Geometry::Intern::ElementKey< n >::is_permanent, FEAT::Geometry::Intern::ElementKey< n >::layer, FEAT::Geometry::Intern::AdaptiveElement< TemplateSet_, Shape_ >::layer, and FEAT::Geometry::Intern::AdaptiveElement< TemplateSet_, Shape_ >::type.
insert() [2/3]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > VertexKey FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert (const AdaptiveVertexType & vertex) inline
Insert a vertex into the storage.
Parameters
[in] vertex r-value reference to the vertex to be inserted
Attention
Unindexes the storage!
Definition at line 871 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_add_mesh_layers(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, FEAT::Geometry::Intern::Layer::idx, FEAT::Geometry::Intern::ElementKey< n >::layer, and FEAT::Geometry::Intern::AdaptiveVertex< VertexType >::layer.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_adapt_roots(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_build(), and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert().
insert() [3/3]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > VertexKey FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert (VertexType vertex, Layer layer) inline
Insert a vertex into the storage.
Parameters
[in] vertex Vertex coordinate vector
[in] layer Layer to insert the vertex into
Attention
Unindexes the storage!
Definition at line 896 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert().
num_entities()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > Index FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::num_entities (Layer layer, int dim) const inline
Returns the number of mesh elements of the given dimension on the given layer.
Parameters
[in] layer Layer to count elements of
[in] dim_ Dimension to query
Note
O(num_layers) complexity
Definition at line 1082 of file adaptive_mesh_storage.hpp.
References XABORTM.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::overlap_mapping(), and FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::transfer_sdls().
num_layers()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > Index FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::num_layers () const inline
Return the number of layers in this mesh.
Note
Layer 0 contains a duplicate of those parts of the underlying mesh, that will be refined further. It is counted as a mesh layer by this method, but you might not consider it a mesh layer for your use case. In that case layer 1 is the first refined layer.
Definition at line 949 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::num_layers(), and FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::transfer_sdls().
num_total_entities()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> Index FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::num_total_entities () const inline
Returns the total number of all mesh elements in the storage.
Template Parameters
dim_ Dimension to query
Note
O(num_layers) complexity
Definition at line 1111 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers.
operator[]() [1/8]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> AdaptiveElementByDim< dim_ > & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[] (ElementKey< dim_ > key) inline
Retrieve element by key.
Definition at line 1568 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, ASSERT, FEAT::Geometry::Intern::Layer::idx, and FEAT::Geometry::Intern::ElementKey< n >::layer.
operator[]() [2/8]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> const AdaptiveElementByDim< dim_ > & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[] (ElementKey< dim_ > key) const inline
Retrieve element by key.
Definition at line 1576 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, ASSERT, FEAT::Geometry::Intern::Layer::idx, and FEAT::Geometry::Intern::ElementKey< n >::layer.
operator[]() [3/8]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > AdaptiveVertexType & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[] (OrientedElement< 0 > ref) inline
Definition at line 1582 of file adaptive_mesh_storage.hpp.
operator[]() [4/8]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > const AdaptiveVertexType & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[] (OrientedElement< 0 > ref) const inline
Definition at line 1587 of file adaptive_mesh_storage.hpp.
operator[]() [5/8]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> AdaptiveElementByDim< dim_ > & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[] (OrientedElement< dim_ > ref) inline
Retrieve element by oriented reference.
Definition at line 1594 of file adaptive_mesh_storage.hpp.
operator[]() [6/8]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim_> const AdaptiveElementByDim< dim_ > & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[] (OrientedElement< dim_ > ref) const inline
Definition at line 1600 of file adaptive_mesh_storage.hpp.
operator[]() [7/8]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > AdaptiveVertexType & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[] (VertexKey key) inline
Retrieve vertex by key.
Definition at line 1553 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, ASSERT, FEAT::Geometry::Intern::Layer::idx, and FEAT::Geometry::Intern::ElementKey< n >::layer.
operator[]() [8/8]
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > const AdaptiveVertexType & FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[] (VertexKey key) const inline
Retrieve vertex by key.
Definition at line 1560 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, ASSERT, FEAT::Geometry::Intern::Layer::idx, and FEAT::Geometry::Intern::ElementKey< n >::layer.
reindex()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::reindex () inline
Re-indexes the storage.
Assigns indices to all mesh elements, such that each mesh layer can be accessed via a continous range of numeric indices starting at 0.
Definition at line 1317 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed, and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::adapt().
transform()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::transform (const VertexType & origin, const VertexType & angles, const VertexType & offset) inline
Applies a "proper rigid" transformation onto the mesh vertices.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any vertex x of the vertex set:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any vertex before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): ignored
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any vertex after applying the rotation.
Warning
Affects all layers of the mesh
Definition at line 1295 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_aux_rot_mat(), and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::transform().
type()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<int dim> TemplateSet::template RefinementTypeByDim< dim > FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::type (ElementKey< dim > key) inline
Get refinement type of element.
Parameters
[in] key The key of the element whose type should be retrieved
Returns
The refinement type of the element
Definition at line 821 of file adaptive_mesh_storage.hpp.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_adapt_children(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_adapt_roots_of_dim(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_adapt_sub_entities(), FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_resolve_boundary_entity_reference(), and FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::get_num_children().
walk_subtree()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<typename VisitorType_ , int dim_> void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::walk_subtree (ElementKey< dim_ > root_key, VisitorType_ & visitor, Layer max_depth, IterationOrder order = IterationOrder::PreOrder) const inline
Traverses the sub-tree anchored at the element pointed to by root_key in the given order.
Template Parameters
VisitorType_ Object with
VisitorType_::operator()(VertexKey)
VisitorType_::operator()(EdgeKey)
VisitorType_::operator()(FaceKey)
VisitorType_::operator()(CellKey) methods.
Parameters
[in] root_key Key pointing to root of subtree
[in] visitor Visitor object
[in] max_depth Maximum depth (inclusive)
[in] order Traversal order
Definition at line 971 of file adaptive_mesh_storage.hpp.
Referenced by FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::walk_tree().
walk_tree()
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > template<typename VisitorType_ > void FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::walk_tree (VisitorType_ & visitor, Layer max_depth, IterationOrder order = IterationOrder::PreOrder) const inline
Traverses all refinement trees in the given order
Template Parameters
VisitorType_ Object with
VisitorType_::operator()(VertexKey)
VisitorType_::operator()(EdgeKey)
VisitorType_::operator()(FaceKey)
VisitorType_::operator()(CellKey) methods.
Parameters
[in] root_key Key pointing to root of subtree
[in] visitor Visitor object
[in] max_depth Maximum depth (inclusive)
[in] order Traversal order
Definition at line 1019 of file adaptive_mesh_storage.hpp.
References FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers, and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::walk_subtree().
Member Data Documentation
_has_neighbors
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > bool FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_has_neighbors = false private
Indicates whether neighbors have been calculated for this mesh.
Definition at line 809 of file adaptive_mesh_storage.hpp.
Referenced by FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::erase(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::fill_neighbors(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_neighbor(), and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert().
_is_indexed
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > bool FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_is_indexed = false private
Indicates whether this mesh has been indexed since the last modification.
Definition at line 806 of file adaptive_mesh_storage.hpp.
Referenced by FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::erase(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_by_index(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_index(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_neighbor(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_vertex_by_index(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert(), and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::reindex().
_layers
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > std::vector<MeshLayerType> FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_layers private
List of MeshLayers for this mesh.
Definition at line 803 of file adaptive_mesh_storage.hpp.
Referenced by FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_add_mesh_layers(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::_num_entities(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::bytes(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::erase(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::fill_neighbors(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_by_index(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_vertex_by_index(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::insert(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::num_layers(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::num_total_entities(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::operator[](), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::reindex(), FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::transform(), and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::walk_tree().
neighbor_sentinel
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > const constexpr ElementKey<MeshShape_::dimension> FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::neighbor_sentinel = ElementKey<MeshShape_::dimension>() static constexpr private
Sentinel key for non-existing neighbors, e.g. for boundary elements.
Definition at line 800 of file adaptive_mesh_storage.hpp.
Referenced by FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::fill_neighbors(), and FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::get_neighbor().
num_coords
template<typename MeshShape_ , typename TemplateSet_ , typename VertexType_ > constexpr int FEAT::Geometry::Intern::AdaptiveMeshStorage< MeshShape_, TemplateSet_, VertexType_ >::num_coords = VertexType::n static constexpr private
Definition at line 797 of file adaptive_mesh_storage.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/intern/adaptive_mesh_storage.hpp