FEAT: FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > Class Template Reference
FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > Class Template Reference
CSR based blocked sparse matrix.
#include <sparse_matrix_bcsr.hpp>
Classes
class ScatterAxpy
Scatter-Axpy operation for SparseMatrixBCSR.
Public Types
template<typename DT2_ = DT_, typename IT2_ = IT_>
using ContainerType = SparseMatrixBCSR< DT2_, IT2_, BlockHeight_, BlockWidth_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a matrix container with new Datatape and Index types
typedef DT_ DataType
Our datatype.
typedef const IT_ * ImageIterator
ImageIterator typedef for Adjactor interface implementation.
typedef IT_ IndexType
Our indextype.
typedef Tiny::Matrix< DataType, BlockHeight, BlockWidth > ValueType
Value type, meaning the type of each block.
typedef Intern::BCSRVectorHelper< DT_, IT_, BlockHeight_ >::VectorType VectorTypeL
Compatible L-vector type.
typedef Intern::BCSRVectorHelper< DT_, IT_, BlockWidth_ >::VectorType VectorTypeR
Compatible R-vector type.
Public Member Functions
SparseMatrixBCSR ()
Constructor.
SparseMatrixBCSR (const Adjacency::Graph &graph)
Constructor.
SparseMatrixBCSR (const Index rows_in, const Index columns_in, DenseVector< IT_, IT_ > &col_ind_in, DenseVector< DT_, IT_ > &val_in, DenseVector< IT_, IT_ > &row_ptr_in)
Constructor.
SparseMatrixBCSR (const SparseLayout< IT_, layout_id > &layout_in)
Constructor.
SparseMatrixBCSR (FileMode mode, const String &filename)
Constructor.
SparseMatrixBCSR (FileMode mode, std::istream &file)
Constructor.
SparseMatrixBCSR (Index rows_in, Index columns_in)
Constructor.
SparseMatrixBCSR (Index rows_in, Index columns_in, Index used_elements_in)
Constructor.
SparseMatrixBCSR (SparseMatrixBCSR &&other)
Move Constructor.
template<typename DT2_ = DT_, typename IT2_ = IT_>
SparseMatrixBCSR (std::vector< char > input)
Constructor.
template<int BHD_>
void add_trace_double_mat_mult (typename LAFEM::SparseMatrixBCSR< DT_, IT_, BHD_, BlockHeight >::VectorTypeL &v, const LAFEM::SparseMatrixBCSR< DT_, IT_, BHD_, BlockHeight > &d, const LAFEM::DenseVectorBlocked< DT_, IT_, BlockHeight > &a, const DT_ alpha=DT_(1)) const
Adds the trace of a double matrix multiplikation to a vector.
std::size_t bytes () const
Returns the total amount of bytes allocated.
virtual void clear ()
Free all allocated arrays.
SparseMatrixBCSR clone (CloneMode clone_mode=CloneMode::Weak) const
Clone operation.
void clone (const Container &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const Container< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const SparseMatrixBCSR< DT2_, IT2_, BlockHeight_, BlockWidth_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
IT_ * col_ind ()
Retrieve column indices array.
IT_ const * col_ind () const
Retrieve column indices array.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Retrieve matrix column count.
void convert (const Adjacency::Graph &graph)
Conversion method.
template<typename DT2_ , typename IT2_ >
void convert (const SparseMatrixBCSR< DT2_, IT2_, BlockHeight_, BlockWidth_ > &other)
Conversion method.
void copy (const SparseMatrixBCSR &x, bool full=false)
Performs \(this \leftarrow x\).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void deserialize (std::vector< char > input)
Deserialization of complete container entity.
bool empty () const
Checks whether the container is empty.
VectorTypeL extract_diag () const
extract main diagonal vector from matrix
void extract_diag (VectorTypeL &diag) const
extract main diagonal vector from matrix
void extract_diag (VectorTypeL &diag, DenseVector< IT_, IT_ > &diag_indices) const
extract main diagonal vector from matrix
DenseVector< IT_, IT_ > extract_diag_indices () const
extract main diagonal vector from matrix
void extract_diag_indices (DenseVector< IT_, IT_ > &diag_indices) const
extract main diagonal vector from matrix
void format (DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DT_ min, DT_ max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (const LAFEM::SerialConfig &config)
Calculate size.
const std::vector< DT_ * > & get_elements () const
Returns a list of all data arrays.
const std::vector< Index > & get_elements_size () const
Returns a list of all data array sizes.
const std::vector< IT_ * > & get_indices () const
Returns a list of all Index arrays.
const std::vector< Index > & get_indices_size () const
Returns a list of all Index array sizes.
Index get_num_nodes_domain () const
Index get_num_nodes_image () const
const std::vector< DT_ > & get_scalar_dt () const
Returns a list of all scalar values with datatype dt.
const std::vector< Index > & get_scalar_index () const
Returns a list of all scalar values with datatype index.
ImageIterator image_begin (Index domain_node) const
ImageIterator image_end (Index domain_node) const
SparseLayout< IT_, layout_id > layout () const
Retrieve convenient sparse matrix layout object.
VectorTypeL lump_rows () const
Returns the lumped rows vector.
void lump_rows (VectorTypeL &lump) const
void move (Container &&other)
Assignment move operation.
ValueType operator() (Index row, Index col) const
Retrieve specific matrix element.
SparseMatrixBCSR & operator= (const SparseLayout< IT_, layout_id > &layout_in)
Assignment operator.
SparseMatrixBCSR & operator= (SparseMatrixBCSR &&other)
Move operator.
void permute (Adjacency::Permutation &perm_row, Adjacency::Permutation &perm_col)
Permutate matrix rows and columns according to the given Permutations.
void read_from (FileMode mode, const String &filename)
Read in matrix from file.
void read_from (FileMode mode, std::istream &file)
Read in matrix from stream.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
IT_ * row_ptr ()
Retrieve row start index array.
IT_ const * row_ptr () const
Retrieve row start index array.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Retrieve matrix row count.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > serialize (const LAFEM::SerialConfig &config=SerialConfig()) const
Serialization of complete container entity.
std::uint64_t set_checkpoint_data (std::vector< char > &data, const LAFEM::SerialConfig &config)
template<Perspective = Perspective::native>
Index size () const
Returns the containers size.
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Retrieve non zero element count.
template<Perspective perspective_ = Perspective::native>
auto val () -> typename Intern::BCSRPerspectiveHelper< DT_, BlockHeight_, BlockWidth_, perspective_ >::Type *
template<Perspective perspective_ = Perspective::native>
auto val () const -> const typename Intern::BCSRPerspectiveHelper< DT_, BlockHeight_, BlockWidth_, perspective_ >::Type *
Retrieve non zero element array.
void write_out (FileMode mode, const String &filename) const
Write out matrix to file.
void write_out (FileMode mode, std::ostream &file) const
Write out matrix to file.
Linear algebra operations
void axpy (const SparseMatrixBCSR &x, const SparseMatrixBCSR &y, const DT_ alpha=DT_(1))
Calculate \(this \leftarrow y + \alpha~ x\).
void scale (const SparseMatrixBCSR &x, const DT_ alpha)
Calculate \(this \leftarrow \alpha~ x \).
DT_ norm_frobenius () const
Calculates the Frobenius norm of this matrix.
void row_norm2 (VectorTypeL &row_norms) const
Computes the 2-norm for every row.
void row_norm2sqr (VectorTypeL &row_norms) const
Computes the square of the 2-norm for every row.
void row_norm2sqr (VectorTypeL &row_norms, const VectorTypeR &scal) const
Computes the square of the 2-norm for every row, where every row is scaled by a vector.
SparseMatrixBCSR< DT_, IT_, BlockWidth_, BlockHeight_ > transpose () const
Calculate \(this^\top \).
void transpose (const SparseMatrixBCSR< DT_, IT_, BlockWidth_, BlockHeight_ > &x)
Calculate \(this \leftarrow x^\top \).
void scale_rows (const SparseMatrixBCSR &x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &s)
Calculate \(this_{ij} \leftarrow x_{ij}\cdot s_i\).
void scale_cols (const SparseMatrixBCSR &x, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &s)
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVector< DT_, IT_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > &r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void add_double_mat_product (const LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &d, const LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &a, const LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &b, const DT_ alpha=DT_(1), const bool allow_incomplete=false)
Adds a double-matrix product onto this matrix.
void add_double_mat_product (const LAFEM::SparseMatrixCSR< DT_, IT_ > &d, const LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > &a, const LAFEM::SparseMatrixCSR< DT_, IT_ > &b, const DT_ alpha=DT_(1), const bool allow_incomplete=false)
Adds a double-matrix product onto this matrix.
Static Public Member Functions
static String name ()
Returns a descriptive string.
Static Public Attributes
static constexpr int BlockHeight = BlockHeight_
Our block height.
static constexpr int BlockWidth = BlockWidth_
Our block width.
static constexpr bool is_global = false
static constexpr bool is_local = true
static constexpr SparseLayoutId layout_id = SparseLayoutId::lt_csr
Our used layout type.
Protected Member Functions
void _copy_content (const Container &other, bool full)
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::istream &file)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::vector< char > &input)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > _serialize (FileMode mode, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _serialize (FileMode mode, std::ostream &file, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::uint64_t _serialized_size (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Calculation of the serialized size with optional compression of complete container entity.
template<typename DT2_ , typename IT2_ >
void assign (const Container< DT2_, IT2_ > &other)
Assignment operation.
Protected Attributes
std::vector< DT_ * > _elements
List of pointers to all datatype dependent arrays.
std::vector< Index > _elements_size
List of corresponding datatype array sizes.
bool _foreign_memory
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
std::vector< IT_ * > _indices
List of pointers to all IT_ dependent arrays.
std::vector< Index > _indices_size
List of corresponding IT_ array sizes.
std::vector< DT_ > _scalar_dt
List of scalars with datatype DT_.
std::vector< Index > _scalar_index
List of scalars with datatype index.
Private Member Functions
Index & _columns ()
Index & _rows ()
Index & _size ()
Index & _used_elements ()
Friends
std::ostream & operator<< (std::ostream &lhs, const SparseMatrixBCSR &b)
SparseMatrixBCSR streaming operator.
bool operator== (const SparseMatrixBCSR &a, const SparseMatrixBCSR &b)
SparseMatrixBCSR comparison operator.
Detailed Description
template<typename DT_, typename IT_, int BlockHeight_, int BlockWidth_>
class FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >
CSR based blocked sparse matrix.
Template Parameters
DT_ The datatype to be used.
IT_ The indexing type to be used.
This class represents a sparse matrix, that stores its non zero elements in the compressed sparse row format. Every non zero element is a small dense matrix block on itself, represented as Tiny::Matrix objects. To be consistent with the external interface, the layout information are stored in block-scoped coordinates.
Data survey:
_elements[0]: raw non zero number values
_indices[0]: column index per non zero element
_indices[1]: row start index (including matrix end index)
_scalar_index[0]: container size
_scalar_index[1]: row count
_scalar_index[2]: column count
_scalar_index[3]: non zero element count (used ValueType elements)
Refer to LAFEM design description for general usage informations.
Author
Dirk Ribbrock
Definition at line 91 of file sparse_matrix_bcsr.hpp.
Member Typedef Documentation
ContainerType
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::ContainerType = SparseMatrixBCSR<DT2_, IT2_, BlockHeight_, BlockWidth_>
Our 'base' class type.
Definition at line 116 of file sparse_matrix_bcsr.hpp.
ContainerTypeByDI
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a matrix container with new Datatape and Index types
Definition at line 120 of file sparse_matrix_bcsr.hpp.
DataType
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef DT_ FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::DataType
Our datatype.
Definition at line 98 of file sparse_matrix_bcsr.hpp.
ImageIterator
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef const IT_* FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::ImageIterator
ImageIterator typedef for Adjactor interface implementation.
Definition at line 112 of file sparse_matrix_bcsr.hpp.
IndexType
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef IT_ FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::IndexType
Our indextype.
Definition at line 100 of file sparse_matrix_bcsr.hpp.
ValueType
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef Tiny::Matrix<DataType, BlockHeight, BlockWidth> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::ValueType
Value type, meaning the type of each block.
Definition at line 106 of file sparse_matrix_bcsr.hpp.
VectorTypeL
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef Intern::BCSRVectorHelper<DT_,IT_,BlockHeight_>::VectorType FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::VectorTypeL
Compatible L-vector type.
Definition at line 123 of file sparse_matrix_bcsr.hpp.
VectorTypeR
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> typedef Intern::BCSRVectorHelper<DT_,IT_,BlockWidth_>::VectorType FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::VectorTypeR
Compatible R-vector type.
Definition at line 125 of file sparse_matrix_bcsr.hpp.
Constructor & Destructor Documentation
SparseMatrixBCSR() [1/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR () inline explicit
Constructor.
Creates an empty non dimensional matrix.
Definition at line 257 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
SparseMatrixBCSR() [2/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (Index rows_in, Index columns_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
Creates an empty matrix. Because SparseMatrixCSR is a read-only container, it stays empty.
Note
This matrix does not allocate any memory
Definition at line 276 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
SparseMatrixBCSR() [3/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (Index rows_in, Index columns_in, Index used_elements_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
[in] used_elements_in The amount of non zero elements of the created matrix.
Creates an empty (but allocated) matrix.
Note
The allocated memory will not be initialized.
Definition at line 295 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and XASSERT.
SparseMatrixBCSR() [4/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (const SparseLayout< IT_, layout_id > & layout_in) inline explicit
Constructor.
Parameters
[in] layout_in The layout to be used.
Creates an empty matrix with given layout.
Definition at line 322 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and FEAT::MemoryPool::increase_memory().
SparseMatrixBCSR() [5/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (const Adjacency::Graph & graph) inline explicit
Constructor.
Parameters
[in] graph The graph to create the matrix from
Creates a BCSR blocked matrix based on a given adjacency graph representing the sparsity pattern.
Definition at line 343 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Adjacency::Graph::get_num_indices(), and FEAT::LAFEM::Container< DT_, IT_ >::move().
SparseMatrixBCSR() [6/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (FileMode mode, const String & filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a BCSR matrix based on the source file.
Definition at line 388 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::read_from().
SparseMatrixBCSR() [7/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (FileMode mode, std::istream & file) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Creates a BCSR matrix based on the source filestream.
Definition at line 402 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::read_from().
SparseMatrixBCSR() [8/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (const Index rows_in, const Index columns_in, DenseVector< IT_, IT_ > & col_ind_in, DenseVector< DT_, IT_ > & val_in, DenseVector< IT_, IT_ > & row_ptr_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
[in] col_ind_in Vector with column indices.
[in] val_in Vector with non zero elements.
[in] row_ptr_in Vector with start indices of all rows into the val/col_ind arrays. Note that this vector must also contain the end index of the last row and thus has a size of row_count + 1.
Creates a matrix with given dimensions and content.
Todo:
maybe create empty matrix if col_ind and val and row_ptr inputs are all three empty
Definition at line 420 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Container< DT_, IT_ >::size(), XASSERT, and XASSERTM.
SparseMatrixBCSR() [9/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<typename DT2_ = DT_, typename IT2_ = IT_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (std::vector< char > input) inline explicit
Constructor.
Parameters
[in] input A std::vector, containing the byte array.
Creates a matrix from the given byte array.
Definition at line 457 of file sparse_matrix_bcsr.hpp.
SparseMatrixBCSR() [10/10]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > && other) inline
Move Constructor.
Parameters
[in] other The source matrix.
Moves a given matrix to this matrix.
Definition at line 470 of file sparse_matrix_bcsr.hpp.
Member Function Documentation
_columns()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> Index & FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::_columns () inline private
Definition at line 240 of file sparse_matrix_bcsr.hpp.
_copy_content()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::_copy_content (const Container< DT_, IT_ > & other, bool full) inline protected inherited
Definition at line 242 of file container.hpp.
_deserialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::istream & file) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file std::istream, pointing to the input data.
Recreate a complete container entity by a single binary file.
Definition at line 782 of file container.hpp.
References XABORTM.
_deserialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::vector< char > & input) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] input A std::vector containing the byte array.
Recreate a complete container entity by a single binary array.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 628 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Pack::decode(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Type::Helper::extract_floatness(), FEAT::Type::Helper::extract_intness(), FEAT::Type::Helper::extract_signedness(), FEAT::Type::Helper::extract_type_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, XABORTM, XASSERT, and XASSERTM.
_rows()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> Index & FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::_rows () inline private
Definition at line 235 of file sparse_matrix_bcsr.hpp.
_serialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
Array data layout:
raw array size in bytes (std::uint64_t)
magic number (std::uint64_t)
DT_ 'hash' value (sizeof(DT_) and floating/integral distinction (packed std::uint64_t)
IT_ 'hash' value (sizeof(IT_) and floating/integral distinction (packed std::uint64_t)
_elements.size() (std::uint64_t)
_indices.size() (std::uint64_t)
_elements_size.size() (std::uint64_t)
_indices_size.size() (std::uint64_t)
_scalar_index.size() (std::uint64_t)
_scalar_dt.size() (std::uint64_t)
_compressed (std::uint64_t)
_elements_size array (std::uint64_t)
_elements arrays byte_size (std::uint64_t) just temporary to read in data
_indices_size array (std::uint64_t)
_indices arrays byte_size (std::uint64_t)
_scalar_index array (std::uint64_t)
_scalar_dt array (DT2_)
_elements arrays (DT2_)
_indices arrays (IT2_)
See FEAT::LAFEM::SerialConfig for details.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 446 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XASSERTM.
_serialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, std::ostream & file, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file The output stream to write data into.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary file with compression enabled. See FEAT::LAFEM::SerialConfig for details.
Definition at line 611 of file container.hpp.
References XABORTM.
_serialized_size()
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline protected inherited
Calculation of the serialized size with optional compression of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Returns
An unsigned int containing the size of serialized container.
Calculate the size of the serialized container entity.
Definition at line 363 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), and FEAT::LAFEM::indices_zlib.
_size()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> Index & FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::_size () inline private
Definition at line 230 of file sparse_matrix_bcsr.hpp.
_used_elements()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> Index & FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::_used_elements () inline private
Definition at line 245 of file sparse_matrix_bcsr.hpp.
add_double_mat_product() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product (const LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & d, const LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & a, const LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & b, const DT_ alpha = DT_(1), const bool allow_incomplete = false) inline
Adds a double-matrix product onto this matrix.
This function performs the following computation:
\[ X \leftarrow X + \alpha D\cdot A\cdot B\]
where
X denotes this m-by-n matrix
D denotes a m-by-k matrix
A denotes a k-by-l matrix
B denotes a l-by-n matrix
Attention
This function assumes that the output matrix already contains the required sparsity pattern. This function will throw an exception if the sparsity pattern of the output matrix is incomplete unless allow_incomplete is set to true.
Note
This function currently only supports data in main memory.
Parameters
[in] d,a,b The three matrices to be multiplied
[in] alpha The scaling factor for the product
[in] allow_incomplete Specifies whether the output matrix structure is allowed to be incomplete. If set to false, this function will throw an exception on incompleteness, otherwise the missing entries are ignored (dropped).
Definition at line 1693 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_mat_mat_mult(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), XABORTM, and XASSERT.
add_double_mat_product() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product (const LAFEM::SparseMatrixCSR< DT_, IT_ > & d, const LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & a, const LAFEM::SparseMatrixCSR< DT_, IT_ > & b, const DT_ alpha = DT_(1), const bool allow_incomplete = false) inline
Adds a double-matrix product onto this matrix.
This function performs the following computation:
\[ X \leftarrow X + \alpha D\cdot A\cdot B\]
where
X denotes this m-by-n matrix
D denotes a m-by-k matrix
A denotes a k-by-l matrix
B denotes a l-by-n matrix
Attention
This function assumes that the output matrix already contains the required sparsity pattern. This function will throw an exception if the sparsity pattern of the output matrix is incomplete unless allow_incomplete is set to true.
Note
This function currently only supports data in main memory.
This version of the add_double_mat_product operation works on d and b as scalar csr matrices. Their values are treaded as beeing a fully filled block.
Parameters
[in] d,a,b The three matrices to be multiplied
[in] alpha The scaling factor for the product
[in] allow_incomplete Specifies whether the output matrix structure is allowed to be incomplete. If set to false, this function will throw an exception on incompleteness, otherwise the missing entries are ignored (dropped).
Definition at line 1826 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_mat_mat_mult(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), XABORTM, and XASSERT.
add_trace_double_mat_mult()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<int BHD_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult (typename LAFEM::SparseMatrixBCSR< DT_, IT_, BHD_, BlockHeight >::VectorTypeL & v, const LAFEM::SparseMatrixBCSR< DT_, IT_, BHD_, BlockHeight > & d, const LAFEM::DenseVectorBlocked< DT_, IT_, BlockHeight > & a, const DT_ alpha = DT_(1)) const inline
Adds the trace of a double matrix multiplikation to a vector.
This function performs the following computation:
\[ v \leftarrow v + \alpha \mathrm{tr}(D \textnormal{diag}(A) \cdot B\]
where \(B = \mathrm{this} \)
where
v denotes a m vector
D denotes a m-by-l matrix
A denotes a vector representing a l-by-l diagonal matrix
B denotes a l-by-n matrix
and the block sizes have to match accordingly:
v has a bm blocks
D has bm-by-bl blocks
A has bl blocks
B has bl-by-bn blocks
Note
This function currently only supports data in main memory.
Template Parameters
BHD_] The block height of D, which is also the block size for v
Parameters
[in] a The vector representing the diagonal matrix A.
[in] d,b The left and right multiplicant matrices
[in] alpha The scaling factor for the product.
Author
Jordi Paul
Definition at line 2147 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockHeight, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockWidth, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERT.
apply() [1/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Attention
r and x must not refer to the same vector object!
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 1314 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
apply() [2/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Attention
r and x must not refer to the same vector object!
Note
r and y are allowed to refer to the same vector object.
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 1456 of file sparse_matrix_bcsr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
apply() [3/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Attention
r and x must not refer to the same vector object!
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 1383 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
apply() [4/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Attention
r and x must not refer to the same vector object!
Note
r and y are allowed to refer to the same vector object.
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 1543 of file sparse_matrix_bcsr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
apply() [5/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVector< DT_, IT_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Attention
r and x must not refer to the same vector object!
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 1348 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
apply() [6/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Attention
r and x must not refer to the same vector object!
Note
r and y are allowed to refer to the same vector object.
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 1500 of file sparse_matrix_bcsr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
apply() [7/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Attention
r and x must not refer to the same vector object!
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
Definition at line 1418 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
apply() [8/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Attention
r and x must not refer to the same vector object!
Note
r and y are allowed to refer to the same vector object.
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 1629 of file sparse_matrix_bcsr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::pod, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
apply() [9/9]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply (DenseVectorBlocked< DT_, IT_, BlockHeight_ > & r, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Attention
r and x must not refer to the same vector object!
Note
r and y are allowed to refer to the same vector object.
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
Definition at line 1586 of file sparse_matrix_bcsr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
assign()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::assign (const Container< DT2_, IT2_ > & other) inline protected inherited
Assignment operation.
Assigns contents of another container
Parameters
[in] other The source container.
Definition at line 282 of file container.hpp.
References FEAT::MemoryPool::convert(), FEAT::MemoryPool::increase_memory(), FEAT::MemoryPool::release_memory(), and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::convert(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute().
axpy()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy (const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & x, const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & y, const DT_ alpha = DT_(1)) inline
Calculate \(this \leftarrow y + \alpha~ x\).
Parameters
[in] x The first summand matrix to be scaled.
[in] y The second summand matrix
[in] alpha A scalar to multiply x with.
Warning
All three matrices must have the same non zero layout. This operation assumes this silently and does not check this on its own!
Definition at line 1045 of file sparse_matrix_bcsr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::pod, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::LAFEM::Container< DT_, IT_ >::bytes () const inline inherited
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 1047 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes().
clear()
template<typename DT_ , typename IT_ > virtual void FEAT::LAFEM::Container< DT_, IT_ >::clear () inline virtual inherited
Free all allocated arrays.
Definition at line 880 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from().
clone() [1/4]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> SparseMatrixBCSR FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone (CloneMode clone_mode = CloneMode::Weak) const inline
Clone operation.
Create a clone of this container.
Parameters
[in] clone_mode The actual cloning procedure.
Returns
The created clone.
Definition at line 497 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone().
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone().
clone() [2/4]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 907 of file container.hpp.
References FEAT::LAFEM::Allocate, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Deep, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Layout, FEAT::LAFEM::Shallow, FEAT::LAFEM::Weak, XABORTM, and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVector< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone().
clone() [3/4]
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 980 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), and FEAT::LAFEM::Container< DT_, IT_ >::clone().
clone() [4/4]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone (const SparseMatrixBCSR< DT2_, IT2_, BlockHeight_, BlockWidth_ > & other, CloneMode clone_mode = CloneMode::Weak) inline
Clone operation.
Create a clone of another container.
Parameters
[in] other The source container to create the clone from.
[in] clone_mode The actual cloning procedure.
Definition at line 513 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clone().
col_ind() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> IT_ * FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind () inline
Retrieve column indices array.
Returns
Column indices array.
Definition at line 944 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_data_mirror(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_pres_mirror(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_reduced_b(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_premult_da(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator()(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out().
col_ind() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> IT_ const * FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind () const inline
Retrieve column indices array.
Returns
Column indices array. const version.
Definition at line 954 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::LAFEM::Container< DT_, IT_ >::size().
columns()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns () const inline
Retrieve matrix column count.
Returns
Matrix column count if perspective_ = false, e.g. count every block as one column.
Raw matrix column count if perspective_ = true, e.g. column_count * BlockWidth_.
Definition at line 916 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and FEAT::LAFEM::pod.
Referenced by FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::SORPrecondWithBackend(), FEAT::Solver::SSORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::SSORPrecondWithBackend(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_pres_mirror(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_premult_da(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::OldroydAssembler::assemble_matrix(), FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::get_num_nodes_image(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator()(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
convert() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert (const Adjacency::Graph & graph) inline
Conversion method.
Parameters
[in] graph The graph to create the matrix from
Creates a BCSR blocked matrix based on a given adjacency graph representing the sparsity pattern.
Definition at line 538 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), and FEAT::LAFEM::Container< DT_, IT_ >::move().
convert() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert (const SparseMatrixBCSR< DT2_, IT2_, BlockHeight_, BlockWidth_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 526 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign().
copy()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::copy (const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The Matrix to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 1029 of file sparse_matrix_bcsr.hpp.
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy().
deserialize()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::deserialize (std::vector< char > input) inline
Deserialization of complete container entity.
Parameters
[in] input A std::vector, containing the byte array.
Recreate a complete container entity by a single binary array.
Definition at line 584 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::fm_bcsr.
empty()
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::empty () const inline inherited
Checks whether the container is empty.
Returns
true if the container is empty, otherwise false.
Definition at line 1170 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic().
extract_diag() [1/3]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> VectorTypeL FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag () const inline
extract main diagonal vector from matrix
Returns
The vector containing the diagonal entry values
Definition at line 2000 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag().
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag().
extract_diag() [2/3]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag (VectorTypeL & diag) const inline
extract main diagonal vector from matrix
Parameters
[out] diag The vector containing the diagonal entry values
Definition at line 1988 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices().
extract_diag() [3/3]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag (VectorTypeL & diag, DenseVector< IT_, IT_ > & diag_indices) const inline
extract main diagonal vector from matrix
Parameters
[in] diag_indices A vector containing the indices of the diagonal entries
[out] diag The vector containing the diagonal entry values
Definition at line 1961 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_interface_filter().
extract_diag_indices() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> DenseVector< IT_, IT_ > FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices () const inline
extract main diagonal vector from matrix
Returns
A vector containing the indices of the diagonal entries
Definition at line 2026 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices().
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices().
extract_diag_indices() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices (DenseVector< IT_, IT_ > & diag_indices) const inline
extract main diagonal vector from matrix
Parameters
[out] diag_indices A vector containing the indices of the diagonal entries
Definition at line 2013 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
format() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (DT_ value = DT_(0)) inline inherited
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 853 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::MemoryPool::set_memory(), and FEAT::value.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
format() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (Random & rng, DT_ min, DT_ max) inline inherited
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 866 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::MemoryPool::set_memory().
get_checkpoint_size()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::get_checkpoint_size (const LAFEM::SerialConfig & config) inline inherited
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1023 of file container.hpp.
get_elements()
template<typename DT_ , typename IT_ > const std::vector< DT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements () const inline inherited
Returns a list of all data arrays.
Returns
A list of all data arrays.
Definition at line 1073 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
get_elements_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size () const inline inherited
Returns a list of all data array sizes.
Returns
A list of all data array sizes.
Definition at line 1093 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
get_indices()
template<typename DT_ , typename IT_ > const std::vector< IT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices () const inline inherited
Returns a list of all Index arrays.
Returns
A list of all Index arrays.
Definition at line 1083 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
get_indices_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size () const inline inherited
Returns a list of all Index array sizes.
Returns
A list of all Index array sizes.
Definition at line 1103 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices_size.
get_num_nodes_domain()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> Index FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::get_num_nodes_domain () const inline
Definition at line 2389 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows().
get_num_nodes_image()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> Index FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::get_num_nodes_image () const inline
Definition at line 2395 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns().
get_scalar_dt()
template<typename DT_ , typename IT_ > const std::vector< DT_ > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt () const inline inherited
Returns a list of all scalar values with datatype dt.
Returns
A list of all scalars with datatype dt.
Definition at line 1123 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt.
get_scalar_index()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index () const inline inherited
Returns a list of all scalar values with datatype index.
Returns
A list of all scalars with datatype index.
Definition at line 1113 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
image_begin()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> ImageIterator FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin (Index domain_node) const inline
Definition at line 2401 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
image_end()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> ImageIterator FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end (Index domain_node) const inline
Definition at line 2408 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
layout()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> SparseLayout< IT_, layout_id > FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout () const inline
Retrieve convenient sparse matrix layout object.
Returns
An object containing the sparse matrix layout.
Definition at line 889 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
lump_rows() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> VectorTypeL FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows () const inline
Returns the lumped rows vector.
Each entry in the returned lumped rows vector contains the the sum of all matrix elements in the corresponding row.
Returns
The lumped vector.
Definition at line 1944 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows().
lump_rows() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows (VectorTypeL & lump) const inline
Definition at line 1925 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockHeight, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockWidth, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows().
move()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::move (Container< DT_, IT_ > && other) inline inherited
Assignment move operation.
Move another container to the current one.
Parameters
[in] other The source container.
Definition at line 994 of file container.hpp.
References FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
name()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> static String FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 1018 of file sparse_matrix_bcsr.hpp.
norm_frobenius()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> DT_ FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::norm_frobenius () const inline
Calculates the Frobenius norm of this matrix.
Returns
The Frobenius norm of this matrix.
Definition at line 1101 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), and FEAT::TimeStamp::elapsed().
operator()()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> ValueType FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator() (Index row, Index col) const inline
Retrieve specific matrix element.
Parameters
[in] row The row of the matrix element.
[in] col The column of the matrix element.
Returns
Specific matrix element.
Definition at line 864 of file sparse_matrix_bcsr.hpp.
References ASSERT, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows().
operator=() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> SparseMatrixBCSR & FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator= (const SparseLayout< IT_, layout_id > & layout_in) inline
Assignment operator.
Parameters
[in] layout_in A sparse matrix layout.
Assigns a new matrix layout, discarding all old data
Definition at line 550 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::MemoryPool::increase_memory(), and FEAT::MemoryPool::release_memory().
operator=() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> SparseMatrixBCSR & FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator= (SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > && other) inline
Move operator.
Parameters
[in] other The source matrix.
Moves another matrix to the target matrix.
Definition at line 482 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::move().
permute()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute (Adjacency::Permutation & perm_row, Adjacency::Permutation & perm_col) inline
Permutate matrix rows and columns according to the given Permutations.
Definition at line 2034 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::Adjacency::Permutation::get_perm_pos(), FEAT::Adjacency::Permutation::inverse(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::Adjacency::Permutation::size(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and XASSERTM.
read_from() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::read_from (FileMode mode, const String & filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 611 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::read_from().
read_from() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::read_from (FileMode mode, std::istream & file) inline
Read in matrix from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Todo:
read_from_mtx
Definition at line 628 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::fm_bcsr, FEAT::LAFEM::fm_binary, and XABORTM.
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::restore_from_checkpoint_data (std::vector< char > & data) inline inherited
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1029 of file container.hpp.
References FEAT::LAFEM::fm_binary.
row_norm2()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2 (VectorTypeL & row_norms) const inline
Computes the 2-norm for every row.
Parameters
[in] row_norms For every row, this left-vector will contain its 2-norm
Definition at line 1118 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockHeight, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockWidth, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
row_norm2sqr() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr (VectorTypeL & row_norms) const inline
Computes the square of the 2-norm for every row.
Parameters
[out] row_norms For every row, this left-vector will contain the square of its 2-norm
Definition at line 1139 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockHeight, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockWidth, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
row_norm2sqr() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr (VectorTypeL & row_norms, const VectorTypeR & scal) const inline
Computes the square of the 2-norm for every row, where every row is scaled by a vector.
Parameters
[out] row_norms For every (scaled) row, this left-vector will contain the square of its 2-norm
[in] scal The scaling vector
This computes
\[ row\_norms_i = \sum_{j=0}^{n-1} scal_j (this_{ij})^2 \]
and is used to compute
\[ \mathrm{tr}(B^T \mathrm{diag}(A) B) \]
Definition at line 1173 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockHeight, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockWidth, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERTM.
row_ptr() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> IT_ * FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr () inline
Retrieve row start index array.
Returns
Row start index array.
Definition at line 995 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_data_mirror(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_pres_mirror(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_reduced_b(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_premult_da(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator()(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out().
row_ptr() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> IT_ const * FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr () const inline
Retrieve row start index array.
Returns
Row start index array. const version.
Definition at line 1005 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
rows()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows () const inline
Retrieve matrix row count.
Returns
Matrix row count if perspective_ = false, e.g. count every block as one row.
Raw matrix row count if perspective_ = true, e.g. row_count * BlockHeight_.
Definition at line 901 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and FEAT::LAFEM::pod.
Referenced by FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::SORPrecondWithBackend(), FEAT::Solver::SSORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >::SSORPrecondWithBackend(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_compute_slip_matrix_layout(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_compute_unit_mask_p(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_compute_unit_mask_v(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_premult_da(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::OldroydAssembler::assemble_matrix(), FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::get_num_nodes_domain(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator()(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out().
scale()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale (const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & x, const DT_ alpha) inline
Calculate \(this \leftarrow \alpha~ x \).
Parameters
[in] x The matrix to be scaled.
[in] alpha A scalar to scale x with.
Definition at line 1083 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::pod, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
scale_cols()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_cols (const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & x, const DenseVectorBlocked< DT_, IT_, BlockWidth_ > & s) inline
Definition at line 1289 of file sparse_matrix_bcsr.hpp.
scale_rows()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows (const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & x, const DenseVectorBlocked< DT_, IT_, BlockHeight_ > & s) inline
Calculate \(this_{ij} \leftarrow x_{ij}\cdot s_i\).
Parameters
[in] x The matrix whose rows are to be scaled.
[in] s The vector to the scale the rows by.
Definition at line 1272 of file sparse_matrix_bcsr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and XASSERTM.
serialize()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::serialize (const LAFEM::SerialConfig & config = SerialConfig()) const inline
Serialization of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary array.
See FEAT::LAFEM::Container::_serialize for details.
Definition at line 600 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::fm_bcsr.
set_checkpoint_data()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::set_checkpoint_data (std::vector< char > & data, const LAFEM::SerialConfig & config) inline inherited
Definition at line 1035 of file container.hpp.
References FEAT::LAFEM::fm_binary.
size()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::size () const inline inherited
Returns the containers size.
Returns
The containers size.
The template parameter of type Perspective is used in blocked containers to switch between the raw size and the size, when every block is treated as one entry.
Most containers like SparseMatrixCSR ignore this template parameter.
Definition at line 1141 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseVector< DT_, IT_ >::compare_layout(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_local_dofs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::get_num_nodes_image(), FEAT::LAFEM::DenseVector< DT_, IT_ >::inflate_to_blocks(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::Assembly::FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >::interpolate(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::map_local_to_global_index(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::mask_scatter(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::write_out().
transpose() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> SparseMatrixBCSR< DT_, IT_, BlockWidth_, BlockHeight_ > FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose () const inline
Calculate \(this^\top \).
Returns
The transposed matrix
Note
The resulting matrix has transposed block dimensions, too.
Definition at line 1196 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
transpose() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose (const SparseMatrixBCSR< DT_, IT_, BlockWidth_, BlockHeight_ > & x) inline
Calculate \(this \leftarrow x^\top \).
Parameters
[in] x The matrix to be transposed.
Definition at line 1208 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::move(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val().
used_elements()
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements () const inline
Retrieve non zero element count.
Returns
Non zero element count if perspective_ = false, e.g. count every block as one entry.
Raw non zero element count if perspective_ = true, e.g. used_elements * BlockHeight_ * BlockWidth_.
Definition at line 931 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and FEAT::LAFEM::pod.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_data_mirror(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
val() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<Perspective perspective_ = Perspective::native> auto FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val () -> typename Intern::BCSRPerspectiveHelper<DT_, BlockHeight_, BlockWidth_, perspective_>::Type * inline
const version. const version.
Definition at line 982 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, and FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out().
val() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> template<Perspective perspective_ = Perspective::native> auto FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val () const -> const typename Intern::BCSRPerspectiveHelper<DT_, BlockHeight_, BlockWidth_, perspective_>::Type * inline
Retrieve non zero element array.
Template Parameters
perspective_ template parameter to choose the return value type
Returns
Non zero element array if perspective_ = Perspective::native, e.g. treat every block as one block.
Raw non zero element array if perspective_ = Perspective::pod, e.g. treat every entry of a block separated.
Definition at line 971 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, and FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_gather_b(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_premult_da(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
write_out() [1/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out (FileMode mode, const String & filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 795 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::FileOutStreamBufferSize, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out().
write_out() [2/2]
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out (FileMode mode, std::ostream & file) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
Definition at line 821 of file sparse_matrix_bcsr.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::fm_bcsr, FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::stringify_fp_sci(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and XABORTM.
Friends And Related Function Documentation
operator<<
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> std::ostream & operator<< (std::ostream & lhs, const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & b) friend
SparseMatrixBCSR streaming operator.
Parameters
[in] lhs The target stream.
[in] b The matrix to be streamed.
Definition at line 2299 of file sparse_matrix_bcsr.hpp.
operator==
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> bool operator== (const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & a, const SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ > & b) friend
SparseMatrixBCSR comparison operator.
Parameters
[in] a A matrix to compare with.
[in] b A matrix to compare with.
Definition at line 2228 of file sparse_matrix_bcsr.hpp.
Member Data Documentation
_elements
template<typename DT_ , typename IT_ > std::vector<DT_*> FEAT::LAFEM::Container< DT_, IT_ >::_elements protected inherited
List of pointers to all datatype dependent arrays.
Definition at line 228 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
_elements_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_elements_size protected inherited
List of corresponding datatype array sizes.
Definition at line 232 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_foreign_memory
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory protected inherited
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
Definition at line 240 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), and FEAT::LAFEM::Container< DT_, IT_ >::clear().
_indices
template<typename DT_ , typename IT_ > std::vector<IT_*> FEAT::LAFEM::Container< DT_, IT_ >::_indices protected inherited
List of pointers to all IT_ dependent arrays.
Definition at line 230 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseVector< DT_, IT_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
_indices_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_indices_size protected inherited
List of corresponding IT_ array sizes.
Definition at line 234 of file container.hpp.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_scalar_dt
template<typename DT_ , typename IT_ > std::vector<DT_> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt protected inherited
List of scalars with datatype DT_.
Definition at line 238 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), and FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt().
_scalar_index
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index protected inherited
List of scalars with datatype index.
Definition at line 236 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::Container(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVector< DT_, IT_ >::allocated_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::sorted(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size().
BlockHeight
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> constexpr int FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockHeight = BlockHeight_ static constexpr
Our block height.
Definition at line 102 of file sparse_matrix_bcsr.hpp.
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr().
BlockWidth
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> constexpr int FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::BlockWidth = BlockWidth_ static constexpr
Our block width.
Definition at line 104 of file sparse_matrix_bcsr.hpp.
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::lump_rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_norm2sqr().
is_global
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> constexpr bool FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::is_global = false static constexpr
Definition at line 127 of file sparse_matrix_bcsr.hpp.
is_local
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> constexpr bool FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::is_local = true static constexpr
Definition at line 128 of file sparse_matrix_bcsr.hpp.
layout_id
template<typename DT_ , typename IT_ , int BlockHeight_, int BlockWidth_> constexpr SparseLayoutId FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout_id = SparseLayoutId::lt_csr static constexpr
Our used layout type.
Definition at line 109 of file sparse_matrix_bcsr.hpp.
The documentation for this class was generated from the following files:
kernel/lafem/forward.hpp
kernel/lafem/sparse_matrix_bcsr.hpp