FEAT: FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ > Class Template Reference
FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ > Class Template Reference abstract
Control class for DuDvFunctionals.
#include <dudv_functional_control.hpp>
Public Types
typedef MeshoptControlBase< DomainControl_ > BaseClass
Our base class.
typedef LAFEM::VectorMirror< CoordType, Index > CoordsMirror
corresponding vector mirror
typedef MeshType::CoordType CoordType
The floating point type the mesh's coordinates use.
typedef DT_ DataType
The floating point type.
typedef DomainControl_ DomainControl
The type of the underlying domain control.
typedef DomainControl_ DomainControlType
The type of the domain control.
typedef DomainControl_::LayerType DomainLayerType
Domain layers.
typedef DomainControl_::LevelType DomainLevel
The type of levels of DomainControl.
typedef DomainControl_::LevelType DomainLevelType
Domain levels.
typedef Global::Vector< LocalCoordsBuffer, CoordsMirror > GlobalCoordsBuffer
The global version of LocalCoordsBuffer, needed for prepare setting the internal state variable.
typedef SystemLevelType::GlobalSystemFilter GlobalSystemFilter
Global system filter.
typedef SystemLevelType::GlobalSystemMatrix GlobalSystemMatrix
Global system matrix.
typedef SystemLevelType::GlobalSystemVectorL GlobalSystemVectorL
Global left vector type.
typedef SystemLevelType::GlobalSystemVectorR GlobalSystemVectorR
Global right vector type.
typedef IT_ IndexType
The index type.
typedef LAFEM::DenseVectorBlocked< CoordType, Index, world_dim > LocalCoordsBuffer
template<typename DT2_ , typename IT2_ >
using LocalFunctionalType = FEAT::Meshopt::DuDvFunctional< DT2_, IT2_, TrafoType >
Template-alias away the Trafo so the SystemLevel can take it as a template template parameter.
typedef DomainControl_::MeshType MeshType
The underlying mesh type.
typedef QuadraticSystemLevel< DT_, IT_, LocalFunctionalType > SystemLevelType
Linear system of equations on one refinement level.
typedef LocalFunctionalType< DT_, IT_ >::SpaceType TrafoSpace
The FE space the transformation lives in.
typedef DomainLevelType::TrafoType TrafoType
The transformation we solve for.
typedef LAFEM::SparseMatrixBWrappedCSR< DT_, IT_, MeshType::world_dim > TransferMatrixType
Inter-level transfer matrix.
typedef Geometry::ExportVTK< MeshType > VTKExporterType
Type of the vtk exporter this (and derived classes) can write to.
Public Member Functions
DuDvFunctionalControl ()=delete
Explicitly delete empty default constructor.
DuDvFunctionalControl (DomainControl_ &dom_ctrl, const int meshopt_lvl_, const std::deque< String > &dirichlet_list, const std::deque< String > &slip_list, const String &solver_name_, PropertyMap &solver_config_, bool fixed_reference_domain_)
Constructor.
DuDvFunctionalControl (DuDvFunctionalControl &&)=delete
Explicitly delete move constructor.
virtual ~DuDvFunctionalControl ()
Virtual destructor.
virtual void add_to_vtk_exporter (Geometry::ExportVTK< MeshType > &exporter, const int lvl_index) const override
Adds quantities of the underlying mesh quality functional to a given exporter object.
virtual Solver::Status apply (GlobalSystemVectorR &vec_sol, const GlobalSystemVectorL &vec_rhs)
Applies the inverse of this functional's gradient to a right hand side.
virtual void buffer_to_mesh () override
Copies the contents of the buffer vector to the mesh's vertex coordinates.
virtual CoordType compute_cell_size_defect (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, CoordType &vol) const =0
‍**
virtual CoordType compute_cell_size_defect (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, CoordType &vol) const override
‍**
void compute_mesh_quality (CoordType &edge_angle, CoordType &qi_min, CoordType &qi_mean, CoordType *edge_angle_cellwise=nullptr, CoordType *qi_cellwise=nullptr, int lvl_index=-1) const
Computes mesh quality heuristics.
virtual SystemLevelType::GlobalCoordsBuffer & get_coords () override
Gets the coordinates buffer vector.
const std::deque< String > & get_dirichlet_boundaries () const
Gets the names of all Dirichlet boundaries.
virtual size_t get_num_levels () const override
Get the number of levels in this object.
const std::deque< String > & get_slip_boundaries () const
Gets the names of all slip boundaries.
virtual String info () const override
virtual void init_numeric ()
Numerically assembles the functional for evaluation.
virtual void mesh_to_buffer () override
Copies the mesh's vertex coordinates to the buffer vector.
virtual String name () const override
Returns a descriptive String.
virtual void optimize () override
virtual void prepare (const GlobalCoordsBuffer &vec_state)=0
Sets the internal state variable.
virtual void prepare (const GlobalSystemVectorR &vec_state) override
Sets the internal state variable.
Public Attributes
std::shared_ptr< Solver::MultiGridHierarchy< GlobalSystemMatrix, GlobalSystemFilter, typename SystemLevelType::GlobalSystemTransfer > > _multigrid_hierarchy
The multigrid hierarchy for our solver.
std::deque< SystemLevelType * > _system_levels
For every level of refinement, we have one system level.
const bool fixed_reference_domain
Whether to reassemble the system matrix in every call of optimize.
int meshopt_lvl
The level index (= number of refinements since the mesh file) to optimize the mesh on.
size_t meshopt_lvl_pos
The position of this level in the deque of system levels.
std::shared_ptr< Solver::SolverBase< GlobalSystemVectorR > > solver
The solver.
PropertyMap & solver_config
Solver configuration.
String solver_name
The name of the section from solver_config we want to use.
Static Public Attributes
static constexpr int world_dim = DomainControl_::MeshType::world_dim
The world dimension, i.e. number of coordinates.
Protected Member Functions
void _create_solver ()
Protected Attributes
std::deque< String > _dirichlet_boundaries
List of all meshparts with dirichlet boundary conditions.
DomainControl & _dom_ctrl
The domain control whose mesh objects can be modified.
std::deque< String > _slip_boundaries
List of all meshparts with slipboundary conditions.
Detailed Description
template<typename DT_, typename IT_, typename DomainControl_>
class FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >
Control class for DuDvFunctionals.
Template Parameters
DT_ The floating point precision for the solver
IT_ Index type
DomainControl_ The domain control type this is based on
Author
Jordi Paul
Definition at line 57 of file dudv_functional_control.hpp.
Member Typedef Documentation
BaseClass
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef MeshoptControlBase<DomainControl_> FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::BaseClass
Our base class.
Definition at line 67 of file dudv_functional_control.hpp.
CoordsMirror
template<typename DomainControl_ > typedef LAFEM::VectorMirror<CoordType, Index> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::CoordsMirror inherited
corresponding vector mirror
Definition at line 81 of file meshopt_control.hpp.
CoordType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef MeshType::CoordType FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::CoordType
The floating point type the mesh's coordinates use.
Definition at line 89 of file dudv_functional_control.hpp.
DataType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef DT_ FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DataType
The floating point type.
Definition at line 62 of file dudv_functional_control.hpp.
DomainControl
template<typename DomainControl_ > typedef DomainControl_ FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::DomainControl inherited
The type of the underlying domain control.
Definition at line 66 of file meshopt_control.hpp.
DomainControlType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef DomainControl_ FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DomainControlType
The type of the domain control.
Definition at line 70 of file dudv_functional_control.hpp.
DomainLayerType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef DomainControl_::LayerType FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DomainLayerType
Domain layers.
Definition at line 72 of file dudv_functional_control.hpp.
DomainLevel
template<typename DomainControl_ > typedef DomainControl_::LevelType FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::DomainLevel inherited
The type of levels of DomainControl.
Definition at line 68 of file meshopt_control.hpp.
DomainLevelType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef DomainControl_::LevelType FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DomainLevelType
Domain levels.
Definition at line 74 of file dudv_functional_control.hpp.
GlobalCoordsBuffer
template<typename DomainControl_ > typedef Global::Vector<LocalCoordsBuffer, CoordsMirror> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::GlobalCoordsBuffer inherited
The global version of LocalCoordsBuffer, needed for prepare setting the internal state variable.
Definition at line 83 of file meshopt_control.hpp.
GlobalSystemFilter
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef SystemLevelType::GlobalSystemFilter FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::GlobalSystemFilter
Global system filter.
Definition at line 103 of file dudv_functional_control.hpp.
GlobalSystemMatrix
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef SystemLevelType::GlobalSystemMatrix FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::GlobalSystemMatrix
Global system matrix.
Definition at line 101 of file dudv_functional_control.hpp.
GlobalSystemVectorL
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef SystemLevelType::GlobalSystemVectorL FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::GlobalSystemVectorL
Global left vector type.
Definition at line 97 of file dudv_functional_control.hpp.
GlobalSystemVectorR
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef SystemLevelType::GlobalSystemVectorR FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::GlobalSystemVectorR
Global right vector type.
Definition at line 99 of file dudv_functional_control.hpp.
IndexType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef IT_ FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::IndexType
The index type.
Definition at line 64 of file dudv_functional_control.hpp.
LocalCoordsBuffer
template<typename DomainControl_ > typedef LAFEM::DenseVectorBlocked<CoordType, Index, world_dim> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::LocalCoordsBuffer inherited
Type for buffer vectors exchanging information between mesh and some vector type on which the solvers operate
Definition at line 79 of file meshopt_control.hpp.
LocalFunctionalType
template<typename DT_ , typename IT_ , typename DomainControl_ > template<typename DT2_ , typename IT2_ > using FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::LocalFunctionalType = FEAT::Meshopt::DuDvFunctional<DT2_, IT2_, TrafoType>
Template-alias away the Trafo so the SystemLevel can take it as a template template parameter.
Definition at line 81 of file dudv_functional_control.hpp.
MeshType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef DomainControl_::MeshType FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::MeshType
The underlying mesh type.
Definition at line 87 of file dudv_functional_control.hpp.
SystemLevelType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef QuadraticSystemLevel<DT_, IT_, LocalFunctionalType> FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::SystemLevelType
Linear system of equations on one refinement level.
Definition at line 92 of file dudv_functional_control.hpp.
TrafoSpace
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef LocalFunctionalType<DT_,IT_>::SpaceType FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::TrafoSpace
The FE space the transformation lives in.
Definition at line 84 of file dudv_functional_control.hpp.
TrafoType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef DomainLevelType::TrafoType FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::TrafoType
The transformation we solve for.
Definition at line 77 of file dudv_functional_control.hpp.
TransferMatrixType
template<typename DT_ , typename IT_ , typename DomainControl_ > typedef LAFEM::SparseMatrixBWrappedCSR<DT_, IT_, MeshType::world_dim> FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::TransferMatrixType
Inter-level transfer matrix.
Definition at line 95 of file dudv_functional_control.hpp.
VTKExporterType
template<typename DomainControl_ > typedef Geometry::ExportVTK<MeshType> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::VTKExporterType inherited
Type of the vtk exporter this (and derived classes) can write to.
Definition at line 86 of file meshopt_control.hpp.
Constructor & Destructor Documentation
DuDvFunctionalControl()
template<typename DT_ , typename IT_ , typename DomainControl_ > FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DuDvFunctionalControl (DomainControl_ & dom_ctrl, const int meshopt_lvl_, const std::deque< String > & dirichlet_list, const std::deque< String > & slip_list, const String & solver_name_, PropertyMap & solver_config_, bool fixed_reference_domain_) inline explicit
Constructor.
Parameters
[in] dom_ctrl The domaincontrol holding all geometry information for all levels
[in] meshopt_lvl_ Index of the level to perform the mesh optimization on
[in] dirichlet_list List of meshpart identifiers for Dirichlet boundary conditions
[in] slip_list List of meshpart identifiers for slip boundary conditions
[in] solver_name_ Name of the solver to select from the solver_config_
[in] solver_config_ PropertyMap holding the solver configuration
[in] fixed_reference_domain_ If this is set to true, the system matrix is only assembled once, corresponding to a fixed reference domain.
Definition at line 155 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::meshopt_lvl, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::meshopt_lvl_pos, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::prepare(), and XASSERT.
~DuDvFunctionalControl()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::~DuDvFunctionalControl () inline virtual
Virtual destructor.
Definition at line 234 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_multigrid_hierarchy, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::solver.
Member Function Documentation
_create_solver()
template<typename DT_ , typename IT_ , typename DomainControl_ > void FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_create_solver () inline protected
Definition at line 567 of file dudv_functional_control.hpp.
add_to_vtk_exporter()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual void FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::add_to_vtk_exporter (Geometry::ExportVTK< MeshType > & exporter, const int lvl_index) const inline override virtual
Adds quantities of the underlying mesh quality functional to a given exporter object.
Parameters
[in,out] exporter The vtk exporter to add our data to
[in] lvl_index This level's data gets added.
Reimplemented from FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 386 of file dudv_functional_control.hpp.
References FEAT::Geometry::ExportVTK< Mesh_ >::add_vertex_vector(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels().
apply()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual Solver::Status FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::apply (GlobalSystemVectorR & vec_sol, const GlobalSystemVectorL & vec_rhs) inline virtual
Applies the inverse of this functional's gradient to a right hand side.
Parameters
[in,out] vec_sol Initial guess, gets overwritten with the solution.
[in] vec_rhs Right hand side.
This is for using this functional as a preconditioner i.e. for the HyperelasticityFunctional
Returns
The status the solver finished with
Definition at line 467 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_multigrid_hierarchy, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::meshopt_lvl_pos, FEAT::Solver::solve(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::solver.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize().
buffer_to_mesh()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual void FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::buffer_to_mesh () inline override virtual
Copies the contents of the buffer vector to the mesh's vertex coordinates.
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 330 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels().
compute_cell_size_defect() [1/2]
template<typename DomainControl_ > virtual CoordType FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_cell_size_defect (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, CoordType & vol) const pure virtual inherited
‍**
Computes a quality indicator concerning the cell sizes
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
In a truly optimal mesh (consisting ONLY of reference cells of the right size), every cell's volume is exactly lambda(cell). This is especially the goal for r-adaptivity. So in an optimal mesh,
so we compute the 1-norm of the vector .
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function uses a pre_sync and post_sync part.
See also
Meshopt::HyperelasticityFunctional::compute_cell_size_defect()
compute_cell_size_defect() [2/2]
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual CoordType FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::compute_cell_size_defect (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, CoordType & vol) const inline override virtual
‍**
Computes a quality indicator concerning the cell sizes
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
In a truly optimal mesh (consisting ONLY of reference cells of the right size), every cell's volume is exactly lambda(cell). This is especially the goal for r-adaptivity. So in an optimal mesh,
so we compute the 1-norm of the vector .
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function uses a pre_sync and post_sync part.
See also
Meshopt::HyperelasticityFunctional::compute_cell_size_defect()
Definition at line 297 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels.
compute_mesh_quality()
template<typename DomainControl_ > void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_mesh_quality (CoordType & edge_angle, CoordType & qi_min, CoordType & qi_mean, CoordType * edge_angle_cellwise = nullptr, CoordType * qi_cellwise = nullptr, int lvl_index = -1) const inline inherited
Computes mesh quality heuristics.
Parameters
[out] edge_angle The worst angle between two edges. Keep in mind that in 3d, this can be >0 even for deteriorated cells.
[out] qi_min The minimum quality indicator over all cells.
[out] qi_mean The mean quality indicator overa all cells.
[out] edge_angle_cellwise For debugging or visualization purposes, this can receive the worst edge angle for every cell.
[out] qi_cellwise For debugging or visualization purposes, this can receive the quality indicator for every cell.
[in] lvl_index Index of the level to compute everything for. Defaults to the maximum level.
Definition at line 276 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl, FEAT::Dist::Comm::allreduce(), FEAT::Geometry::MeshQualityHeuristic< Shape_ >::compute(), FEAT::Dist::op_min, FEAT::Dist::op_sum, FEAT::stringify(), XABORTM, and XASSERT.
get_coords()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual SystemLevelType::GlobalCoordsBuffer & FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_coords () inline override virtual
Gets the coordinates buffer vector.
Returns
A reference to the coordinates buffer
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 318 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels.
get_dirichlet_boundaries()
template<typename DomainControl_ > const std::deque< String > & FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_dirichlet_boundaries () const inline inherited
Gets the names of all Dirichlet boundaries.
Note that each name refers to a boundary, but that boundary does not necessarily have to be present due to partitioning etc.
Returns
A deque of Strings with all Dirichlet boundary names
Definition at line 202 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dirichlet_boundaries.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info().
get_num_levels()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual size_t FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels () const inline override virtual
Get the number of levels in this object.
Returns
The number of levels.
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 324 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DuDvFunctionalControl(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::add_to_vtk_exporter(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::buffer_to_mesh(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::init_numeric(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::mesh_to_buffer(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::prepare().
get_slip_boundaries()
template<typename DomainControl_ > const std::deque< String > & FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries () const inline inherited
Gets the names of all slip boundaries.
Note that each name refers to a boundary, but that boundary does not necessarily have to be present due to partitioning etc.
Returns
A deque of Strings with all slip boundary names
Definition at line 215 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_slip_boundaries.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
info()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual String FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info () const inline override virtual
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 253 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::fixed_reference_domain, FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_dirichlet_boundaries(), FEAT::Statistics::get_formatted_solver_tree(), FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::meshopt_lvl, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::name(), FEAT::String::pad_back(), FEAT::stringify(), and FEAT::String::trim().
init_numeric()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual void FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::init_numeric () inline virtual
Numerically assembles the functional for evaluation.
This is mainly for using this functional as a preconditioner for the HyperelasticityFunctional so it can be called separately.
Definition at line 414 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::fixed_reference_domain, and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels().
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize().
mesh_to_buffer()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual void FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::mesh_to_buffer () inline override virtual
Copies the mesh's vertex coordinates to the buffer vector.
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 358 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels().
name()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual String FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::name () const inline override virtual
Returns a descriptive String.
Returns
The class name as String
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 247 of file dudv_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize().
optimize()
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual void FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize () inline override virtual
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 481 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::apply(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_rhs_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_sol_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::coords_buffer, FEAT::Statistics::expression_target, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels(), FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::init_numeric(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::local_functional, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::meshopt_lvl_pos, and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::name().
prepare() [1/2]
template<typename DomainControl_ > virtual void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::prepare (const GlobalCoordsBuffer & vec_state) pure virtual inherited
Sets the internal state variable.
Parameters
[in] vec_state Global buffer vector containing (possibly new) mesh vertex coordinates
prepare() [2/2]
template<typename DT_ , typename IT_ , typename DomainControl_ > virtual void FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::prepare (const GlobalSystemVectorR & vec_state) inline override virtual
Sets the internal state variable.
Parameters
[in] vec_state Global buffer vector containing (possibly new) mesh vertex coordinates
Definition at line 426 of file dudv_functional_control.hpp.
References FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels, FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::local().
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DuDvFunctionalControl().
Member Data Documentation
_dirichlet_boundaries
template<typename DomainControl_ > std::deque<String> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dirichlet_boundaries protected inherited
List of all meshparts with dirichlet boundary conditions.
Definition at line 92 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_dirichlet_boundaries().
_dom_ctrl
template<typename DomainControl_ > DomainControl& FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl protected inherited
The domain control whose mesh objects can be modified.
Definition at line 90 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_mesh_quality(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
_multigrid_hierarchy
template<typename DT_ , typename IT_ , typename DomainControl_ > std::shared_ptr<Solver::MultiGridHierarchy< GlobalSystemMatrix, GlobalSystemFilter, typename SystemLevelType::GlobalSystemTransfer > > FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_multigrid_hierarchy
The multigrid hierarchy for our solver.
Definition at line 113 of file dudv_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::~DuDvFunctionalControl(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::apply().
_slip_boundaries
template<typename DomainControl_ > std::deque<String> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_slip_boundaries protected inherited
List of all meshparts with slipboundary conditions.
Definition at line 94 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries().
_system_levels
template<typename DT_ , typename IT_ , typename DomainControl_ > std::deque<SystemLevelType*> FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::_system_levels
For every level of refinement, we have one system level.
Definition at line 106 of file dudv_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DuDvFunctionalControl(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::~DuDvFunctionalControl(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::apply(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::buffer_to_mesh(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::compute_cell_size_defect(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_coords(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::get_num_levels(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::init_numeric(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::mesh_to_buffer(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::prepare().
fixed_reference_domain
template<typename DT_ , typename IT_ , typename DomainControl_ > const bool FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::fixed_reference_domain
Whether to reassemble the system matrix in every call of optimize.
Definition at line 123 of file dudv_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::init_numeric().
meshopt_lvl
template<typename DT_ , typename IT_ , typename DomainControl_ > int FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::meshopt_lvl
The level index (= number of refinements since the mesh file) to optimize the mesh on.
Definition at line 125 of file dudv_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DuDvFunctionalControl(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info().
meshopt_lvl_pos
template<typename DT_ , typename IT_ , typename DomainControl_ > size_t FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::meshopt_lvl_pos
The position of this level in the deque of system levels.
Definition at line 127 of file dudv_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::DuDvFunctionalControl(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::apply(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize().
solver
template<typename DT_ , typename IT_ , typename DomainControl_ > std::shared_ptr<Solver::SolverBase<GlobalSystemVectorR> > FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::solver
The solver.
Definition at line 121 of file dudv_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::~DuDvFunctionalControl(), and FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::apply().
solver_config
template<typename DT_ , typename IT_ , typename DomainControl_ > PropertyMap& FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::solver_config
Solver configuration.
Definition at line 117 of file dudv_functional_control.hpp.
solver_name
template<typename DT_ , typename IT_ , typename DomainControl_ > String FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::solver_name
The name of the section from solver_config we want to use.
Definition at line 119 of file dudv_functional_control.hpp.
world_dim
template<typename DomainControl_ > constexpr int FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::world_dim = DomainControl_::MeshType::world_dim static constexpr inherited
The world dimension, i.e. number of coordinates.
Definition at line 73 of file meshopt_control.hpp.
The documentation for this class was generated from the following file:
control/meshopt/dudv_functional_control.hpp