FEAT: FEAT::LAFEM::TupleFilter< First_, Rest_ > Class Template Reference
FEAT::LAFEM::TupleFilter< First_, Rest_ > Class Template Reference
TupleVector meta-filter class template.
#include <tuple_filter.hpp>
Public Types
typedef First_::DataType DataType
sub-filter data-type
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using FilterType = TupleFilter< typename First_::template FilterType< DT2_, IT2_ >, typename Rest_::template FilterType< DT2_, IT2_ >... >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using FilterTypeByDI = FilterType< DataType2_, IndexType2_ >
this typedef lets you create a filter with different Data and Index types
typedef First_::IndexType IndexType
sub-filter index-type
typedef TupleVector< typename First_::VectorType, typename Rest_::VectorType... > VectorType
corresponding vector
Public Member Functions
TupleFilter ()
default ctor
TupleFilter (First_ &&the_first, Rest_ &&... the_rest)
sub-filter emplacement ctor
TupleFilter (TupleFilter &&other)
move-ctor
template<int i_>
TupleElement< i_, First_, Rest_... >::Type & at ()
template<int i_>
TupleElement< i_, First_, Rest_... >::Type const & at () const
std::size_t bytes () const
Returns the total amount of bytes allocated.
TupleFilter clone (CloneMode clone_mode=CloneMode::Deep) const
Creates a clone of itself.
void clone (const TupleFilter &other, CloneMode clone_mode=CloneMode::Deep)
Clones data from another TupleFilter.
template<typename... SubFilter2_>
void convert (const TupleFilter< SubFilter2_... > &other)
void filter_cor (VectorType &vector) const
Applies the filter onto a correction vector.
void filter_def (VectorType &vector) const
Applies the filter onto a defect vector.
void filter_rhs (VectorType &vector) const
Applies the filter onto the right-hand-side vector.
void filter_sol (VectorType &vector) const
Applies the filter onto the solution vector.
TupleFilter & operator= (TupleFilter &&other)
move-assign operator
Static Public Attributes
static constexpr int num_blocks = TupleFilter<Rest_...>::num_blocks + 1
number of vector blocks
Protected Member Functions
TupleFilter (First_ &&the_first, RestClass &&the_rest)
data-emplacement ctor; this one is protected for a reason
Protected Attributes
First_ _first
the first sub-filter
RestClass _rest
all remaining sub-filters
Private Types
typedef TupleFilter< Rest_... > RestClass
Detailed Description
template<typename First_, typename... Rest_>
class FEAT::LAFEM::TupleFilter< First_, Rest_ >
TupleVector meta-filter class template.
This class template implements a composition of sub-filters of arbitrary classes, which can be applied onto TupleVector meta-container objects.
Note
If you are looking for a way to define a filter which is a composition of filters successively applied onto the same vector, see the FilterChain class template.
Template Parameters
First_,Rest_... The filters to be composed.
Author
Peter Zajac
Definition at line 33 of file tuple_filter.hpp.
Member Typedef Documentation
DataType
template<typename First_ , typename... Rest_> typedef First_::DataType FEAT::LAFEM::TupleFilter< First_, Rest_ >::DataType
sub-filter data-type
Definition at line 45 of file tuple_filter.hpp.
FilterType
template<typename First_ , typename... Rest_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::TupleFilter< First_, Rest_ >::FilterType = TupleFilter< typename First_::template FilterType<DT2_, IT2_>, typename Rest_::template FilterType<DT2_, IT2_>...>
Our 'base' class type.
Definition at line 60 of file tuple_filter.hpp.
FilterTypeByDI
template<typename First_ , typename... Rest_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::TupleFilter< First_, Rest_ >::FilterTypeByDI = FilterType<DataType2_, IndexType2_>
this typedef lets you create a filter with different Data and Index types
Definition at line 66 of file tuple_filter.hpp.
IndexType
template<typename First_ , typename... Rest_> typedef First_::IndexType FEAT::LAFEM::TupleFilter< First_, Rest_ >::IndexType
sub-filter index-type
Definition at line 47 of file tuple_filter.hpp.
RestClass
template<typename First_ , typename... Rest_> typedef TupleFilter<Rest_...> FEAT::LAFEM::TupleFilter< First_, Rest_ >::RestClass private
Definition at line 38 of file tuple_filter.hpp.
VectorType
template<typename First_ , typename... Rest_> typedef TupleVector<typename First_::VectorType, typename Rest_::VectorType...> FEAT::LAFEM::TupleFilter< First_, Rest_ >::VectorType
corresponding vector
Definition at line 56 of file tuple_filter.hpp.
Constructor & Destructor Documentation
TupleFilter() [1/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleFilter< First_, Rest_ >::TupleFilter (First_ && the_first, RestClass && the_rest) inline explicit protected
data-emplacement ctor; this one is protected for a reason
Definition at line 75 of file tuple_filter.hpp.
TupleFilter() [2/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleFilter< First_, Rest_ >::TupleFilter () inline
default ctor
Definition at line 83 of file tuple_filter.hpp.
TupleFilter() [3/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleFilter< First_, Rest_ >::TupleFilter (First_ && the_first, Rest_ &&... the_rest) inline explicit
sub-filter emplacement ctor
Definition at line 88 of file tuple_filter.hpp.
TupleFilter() [4/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleFilter< First_, Rest_ >::TupleFilter (TupleFilter< First_, Rest_ > && other) inline
move-ctor
Definition at line 95 of file tuple_filter.hpp.
Member Function Documentation
at() [1/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type & FEAT::LAFEM::TupleFilter< First_, Rest_ >::at () inline
Definition at line 161 of file tuple_filter.hpp.
at() [2/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type const & FEAT::LAFEM::TupleFilter< First_, Rest_ >::at () const inline
Definition at line 169 of file tuple_filter.hpp.
References FEAT::LAFEM::TupleFilter< First_, Rest_ >::num_blocks.
bytes()
template<typename First_ , typename... Rest_> std::size_t FEAT::LAFEM::TupleFilter< First_, Rest_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 133 of file tuple_filter.hpp.
References FEAT::LAFEM::TupleFilter< First_, Rest_ >::_first, FEAT::LAFEM::TupleFilter< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleFilter< First_, Rest_ >::bytes().
Referenced by FEAT::Control::StokesBlockedUnitVeloMeanPresSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), FEAT::Control::StokesPowerUnitVeloNonePresSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_ >::bytes(), FEAT::Control::StokesPowerUnitVeloMeanPresSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_ >::bytes(), and FEAT::LAFEM::TupleFilter< First_, Rest_ >::bytes().
clone() [1/2]
template<typename First_ , typename... Rest_> TupleFilter FEAT::LAFEM::TupleFilter< First_, Rest_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Creates a clone of itself.
Definition at line 113 of file tuple_filter.hpp.
References FEAT::LAFEM::TupleFilter< First_, Rest_ >::_first, FEAT::LAFEM::TupleFilter< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleFilter< First_, Rest_ >::clone().
Referenced by FEAT::LAFEM::TupleFilter< First_, Rest_ >::clone().
clone() [2/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleFilter< First_, Rest_ >::clone (const TupleFilter< First_, Rest_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clones data from another TupleFilter.
Definition at line 119 of file tuple_filter.hpp.
References FEAT::LAFEM::TupleFilter< First_, Rest_ >::_first, FEAT::LAFEM::TupleFilter< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleFilter< First_, Rest_ >::clone().
convert()
template<typename First_ , typename... Rest_> template<typename... SubFilter2_> void FEAT::LAFEM::TupleFilter< First_, Rest_ >::convert (const TupleFilter< SubFilter2_... > & other) inline
Definition at line 126 of file tuple_filter.hpp.
filter_cor()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleFilter< First_, Rest_ >::filter_cor (VectorType & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 197 of file tuple_filter.hpp.
filter_def()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleFilter< First_, Rest_ >::filter_def (VectorType & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 190 of file tuple_filter.hpp.
filter_rhs()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleFilter< First_, Rest_ >::filter_rhs (VectorType & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 176 of file tuple_filter.hpp.
filter_sol()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleFilter< First_, Rest_ >::filter_sol (VectorType & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 183 of file tuple_filter.hpp.
operator=()
template<typename First_ , typename... Rest_> TupleFilter & FEAT::LAFEM::TupleFilter< First_, Rest_ >::operator= (TupleFilter< First_, Rest_ > && other) inline
move-assign operator
Definition at line 102 of file tuple_filter.hpp.
References FEAT::LAFEM::TupleFilter< First_, Rest_ >::_first, and FEAT::LAFEM::TupleFilter< First_, Rest_ >::_rest.
Friends And Related Function Documentation
TupleFilter
template<typename First_ , typename... Rest_> template<typename , typename... > friend class TupleFilter friend
Definition at line 36 of file tuple_filter.hpp.
Member Data Documentation
_first
template<typename First_ , typename... Rest_> First_ FEAT::LAFEM::TupleFilter< First_, Rest_ >::_first protected
the first sub-filter
Definition at line 70 of file tuple_filter.hpp.
Referenced by FEAT::LAFEM::TupleFilter< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleFilter< First_, Rest_ >::clone(), and FEAT::LAFEM::TupleFilter< First_, Rest_ >::operator=().
_rest
template<typename First_ , typename... Rest_> RestClass FEAT::LAFEM::TupleFilter< First_, Rest_ >::_rest protected
all remaining sub-filters
Definition at line 72 of file tuple_filter.hpp.
Referenced by FEAT::LAFEM::TupleFilter< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleFilter< First_, Rest_ >::clone(), and FEAT::LAFEM::TupleFilter< First_, Rest_ >::operator=().
num_blocks
template<typename First_ , typename... Rest_> constexpr int FEAT::LAFEM::TupleFilter< First_, Rest_ >::num_blocks = TupleFilter<Rest_...>::num_blocks + 1 static constexpr
number of vector blocks
Definition at line 42 of file tuple_filter.hpp.
Referenced by FEAT::LAFEM::TupleFilter< First_, Rest_ >::at().
The documentation for this class was generated from the following file:
kernel/lafem/tuple_filter.hpp