FEAT: FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ > Class Template Reference
FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ > Class Template Reference
Unit Filter Blocked class template.
#include <unit_filter_blocked.hpp>
Public Types
typedef DT_ DataType
data-type typedef
template<typename DT2_ = DT_, typename IT2_ = IT_>
using FilterType = UnitFilterBlocked< DT2_, IT2_, BlockSize_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using FilterTypeByDI = FilterType< DataType2_, IndexType2_ >
this typedef lets you create a filter with new Datatype and Index types
typedef IT_ IndexType
index-type typedef
typedef Tiny::Vector< DataType, BlockSize > ValueType
Value type.
typedef DenseVectorBlocked< DataType, IndexType, BlockSize > VectorType
Our supported vector type.
Public Member Functions
UnitFilterBlocked ()
default constructor
UnitFilterBlocked (Index num_entries, bool ignore_nans=false)
Constructor.
UnitFilterBlocked (Index size_in, DenseVectorBlocked< DT_, IT_, BlockSize_ > &values, DenseVector< IT_, IT_ > &indices)
Constructor.
UnitFilterBlocked (UnitFilterBlocked &&other)
move-ctor
virtual ~UnitFilterBlocked ()
virtual destructor
void add (IndexType idx, ValueType val)
Adds one element to the filter.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Clears the underlying data (namely the SparseVector)
UnitFilterBlocked clone (CloneMode clone_mode=CloneMode::Deep) const
Creates a clone of itself.
void clone (const UnitFilterBlocked &other, CloneMode clone_mode=CloneMode::Deep)
Clones data from another UnitFilterBlocked.
template<typename DT2_ , typename IT2_ , int BS_>
void convert (const UnitFilterBlocked< DT2_, IT2_, BS_ > &other)
Converts data from another UnitFilter.
void filter_cor (VectorType &vector) const
Applies the filter onto a correction vector.
void filter_def (VectorType &vector) const
Applies the filter onto a defect vector.
void filter_mat (MatrixType &matrix) const
Applies the filter onto a system matrix.
void filter_offdiag_col_mat (MatrixType &matrix) const
Filter the non-diagonal column entries.
void filter_offdiag_row_mat (MatrixType &matrix) const
Filter the non-diagonal row entries.
void filter_rhs (VectorType &vector) const
Applies the filter onto the right-hand-side vector.
void filter_sol (VectorType &vector) const
Applies the filter onto the solution vector.
template<int BlockWidth_>
void filter_weak_matrix_rows (SparseMatrixBCSR< DT_, IT_, BlockSize_, BlockWidth_ > &matrix_a, const SparseMatrixBCSR< DT_, IT_, BlockSize_, BlockWidth_ > &matrix_m) const
Replaces the rows of the system matrix by scaled rows of another matrix.
IT_ * get_indices ()
const IT_ * get_indices () const
ValueType * get_values ()
const ValueType * get_values () const
UnitFilterBlocked & operator= (UnitFilterBlocked &&other)
move-assignment operator
void permute (Adjacency::Permutation &perm)
Permutate internal vector according to the given Permutation.
void set_ignore_nans (bool ignore_nans)
Specifies whether the filter should ignore NaN filter values.
Index size () const
Index used_elements () const
Static Public Attributes
static constexpr int BlockSize = BlockSize_
The block size.
static constexpr bool is_global = false
static constexpr bool is_local = true
Private Attributes
bool _ignore_nans
ignore NaNs in filter values
SparseVectorBlocked< DataType, IndexType, BlockSize > _sv
SparseVector, containing all entries of the unit filter.
Detailed Description
template<typename DT_, typename IT_, int BlockSize_>
class FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >
Unit Filter Blocked class template.
Template Parameters
DT_ Data type, i.e. double
IT_ Index type, i.e. unsigned int
BlockSize_ Size of the blocks, i.e. 2 for a filter acting on a velocity field in 2d
Mostly c&p from UnitFilter
Note
This class allows to emulate a "slip-filter-like" behavior by disabling individual filter components on a per-DOF basis by turning on the "ignore NaNs" functionality and setting all component values, which should be ignored by the filter, to NaN. Example: if you want to emulate a 3D slip-filter for the Y-component, then set the filter value (NaN, 0, NaN) for all DOFs that should be affected by the filter.
Author
Jordi Paul, Peter Zajac
Definition at line 49 of file unit_filter_blocked.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ , int BlockSize_> typedef DT_ FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::DataType
data-type typedef
Definition at line 53 of file unit_filter_blocked.hpp.
FilterType
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::FilterType = UnitFilterBlocked<DT2_, IT2_, BlockSize_>
Our 'base' class type.
Definition at line 65 of file unit_filter_blocked.hpp.
FilterTypeByDI
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::FilterTypeByDI = FilterType<DataType2_, IndexType2_>
this typedef lets you create a filter with new Datatype and Index types
Definition at line 69 of file unit_filter_blocked.hpp.
IndexType
template<typename DT_ , typename IT_ , int BlockSize_> typedef IT_ FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::IndexType
index-type typedef
Definition at line 55 of file unit_filter_blocked.hpp.
ValueType
template<typename DT_ , typename IT_ , int BlockSize_> typedef Tiny::Vector<DataType, BlockSize> FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::ValueType
Value type.
Definition at line 59 of file unit_filter_blocked.hpp.
VectorType
template<typename DT_ , typename IT_ , int BlockSize_> typedef DenseVectorBlocked<DataType, IndexType, BlockSize> FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::VectorType
Our supported vector type.
Definition at line 61 of file unit_filter_blocked.hpp.
Constructor & Destructor Documentation
UnitFilterBlocked() [1/4]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked () inline
default constructor
Definition at line 85 of file unit_filter_blocked.hpp.
UnitFilterBlocked() [2/4]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked (Index num_entries, bool ignore_nans = false) inline explicit
Constructor.
Parameters
[in] num_entries The total number of entries for the unit filter.
[in] ingore_nans Specifies whether the filter should ignore NaNs filter values
Definition at line 100 of file unit_filter_blocked.hpp.
UnitFilterBlocked() [3/4]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked (Index size_in, DenseVectorBlocked< DT_, IT_, BlockSize_ > & values, DenseVector< IT_, IT_ > & indices) inline explicit
Constructor.
Parameters
[in] size_in The size of the created filter.
[in] values DenseVector containing element values
[in] indices DenseVector containing element indices
Definition at line 113 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
UnitFilterBlocked() [4/4]
template<typename DT_ , typename IT_ , int BlockSize_> FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked (UnitFilterBlocked< DT_, IT_, BlockSize_ > && other) inline
move-ctor
Definition at line 122 of file unit_filter_blocked.hpp.
~UnitFilterBlocked()
template<typename DT_ , typename IT_ , int BlockSize_> virtual FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::~UnitFilterBlocked () inline virtual
virtual destructor
Definition at line 140 of file unit_filter_blocked.hpp.
Member Function Documentation
add()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::add (IndexType idx, ValueType val) inline
Adds one element to the filter.
Parameters
[in] idx Index where to add
[in] val Value to add
Definition at line 208 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv.
Referenced by FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble().
bytes()
template<typename DT_ , typename IT_ , int BlockSize_> std::size_t FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 174 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::Container< DT_, IT_ >::bytes().
clear()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear () inline
Clears the underlying data (namely the SparseVector)
Definition at line 168 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::Container< DT_, IT_ >::clear().
clone() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> UnitFilterBlocked FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Creates a clone of itself.
Definition at line 145 of file unit_filter_blocked.hpp.
Referenced by FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo().
clone() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clone (const UnitFilterBlocked< DT_, IT_, BlockSize_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clones data from another UnitFilterBlocked.
Definition at line 153 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_ignore_nans, FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone().
convert()
template<typename DT_ , typename IT_ , int BlockSize_> template<typename DT2_ , typename IT2_ , int BS_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::convert (const UnitFilterBlocked< DT2_, IT2_, BS_ > & other) inline
Converts data from another UnitFilter.
Definition at line 161 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_ignore_nans, FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::convert().
filter_cor()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor (VectorType & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 495 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_def().
filter_def()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_def (VectorType & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 478 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_ignore_nans, FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), and XASSERTM.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_cor().
filter_mat()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_mat (MatrixType & matrix) const inline
Applies the filter onto a system matrix.
Template Parameters
BlockWidth_ The input matrix' block width
Parameters
[in,out] matrix A reference to the matrix to be filtered.
The input matrix has to have a block(ed) structure and its BlockHeight has to agree with the filter's blocksize.
Definition at line 272 of file unit_filter_blocked.hpp.
filter_offdiag_col_mat()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_offdiag_col_mat (MatrixType & matrix) const inline
Filter the non-diagonal column entries.
Template Parameters
BlockWidth_ The input matrix' block width
Parameters
[in,out] matrix A reference to the matrix to be filtered.
The input matrix has to have a block(ed) structure and its BlockHeight has to agree with the filter's blocksize.
Definition at line 306 of file unit_filter_blocked.hpp.
filter_offdiag_row_mat()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_offdiag_row_mat (MatrixType & matrix) const inline
Filter the non-diagonal row entries.
Template Parameters
BlockWidth_ The input matrix' block width
Parameters
[in,out] matrix A reference to the matrix to be filtered.
The input matrix has to have a block(ed) structure and its BlockHeight has to agree with the filter's blocksize.
Definition at line 289 of file unit_filter_blocked.hpp.
filter_rhs()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs (VectorType & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 449 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_ignore_nans, FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), and XASSERTM.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol().
filter_sol()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_sol (VectorType & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 466 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs().
filter_weak_matrix_rows()
template<typename DT_ , typename IT_ , int BlockSize_> template<int BlockWidth_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows (SparseMatrixBCSR< DT_, IT_, BlockSize_, BlockWidth_ > & matrix_a, const SparseMatrixBCSR< DT_, IT_, BlockSize_, BlockWidth_ > & matrix_m) const inline
Replaces the rows of the system matrix by scaled rows of another matrix.
This function replaces all rows of the system matrix A, whose row index is included in this filter's indices, by the corresponding rows of a given donor matrix M, which is typically a mass matrix, scaled by the values which are stored in this filter. This functionality can be used to implement a weak form of Dirichlet boundary conditions, which is also used to employ mass-conserving fictitious boundary conditions in a Stokes system.
Parameters
[in,out] matrix_a The system matrix whose rows are to be replaced
[in] matrix_m The donor matrix whose rows are to be copied into the system matrix
Definition at line 403 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_indices(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_values(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and XASSERTM.
get_indices() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> IT_ * FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_indices () inline
Returns
The index array.
Definition at line 226 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices().
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows().
get_indices() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> const IT_ * FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_indices () const inline
Returns
The index array.
Definition at line 232 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices().
get_values() [1/2]
template<typename DT_ , typename IT_ , int BlockSize_> ValueType * FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_values () inline
Returns
The value array.
Definition at line 238 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements().
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows().
get_values() [2/2]
template<typename DT_ , typename IT_ , int BlockSize_> const ValueType * FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_values () const inline
Returns
The value array.
Definition at line 244 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements().
operator=()
template<typename DT_ , typename IT_ , int BlockSize_> UnitFilterBlocked & FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::operator= (UnitFilterBlocked< DT_, IT_, BlockSize_ > && other) inline
move-assignment operator
Definition at line 129 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_ignore_nans, and FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv.
permute()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::permute (Adjacency::Permutation & perm) inline
Permutate internal vector according to the given Permutation.
Definition at line 250 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute().
set_ignore_nans()
template<typename DT_ , typename IT_ , int BlockSize_> void FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::set_ignore_nans (bool ignore_nans) inline
Specifies whether the filter should ignore NaN filter values.
Parameters
[in] ingore_nans Specifies whether the filter should ignore NaNs filter values
Definition at line 196 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_ignore_nans.
size()
template<typename DT_ , typename IT_ , int BlockSize_> Index FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::size () const inline
Returns
The total size of the filter.
Definition at line 214 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::size().
Referenced by FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble().
used_elements()
template<typename DT_ , typename IT_ , int BlockSize_> Index FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::used_elements () const inline
Returns
The number of entries in the filter.
Definition at line 220 of file unit_filter_blocked.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv, and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements().
Member Data Documentation
_ignore_nans
template<typename DT_ , typename IT_ , int BlockSize_> bool FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_ignore_nans private
ignore NaNs in filter values
Definition at line 81 of file unit_filter_blocked.hpp.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_def(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::operator=(), and FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::set_ignore_nans().
_sv
template<typename DT_ , typename IT_ , int BlockSize_> SparseVectorBlocked<DataType, IndexType, BlockSize> FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::_sv private
SparseVector, containing all entries of the unit filter.
Definition at line 78 of file unit_filter_blocked.hpp.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::add(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_def(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_rhs(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::filter_weak_matrix_rows(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_indices(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::get_values(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::size(), and FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::used_elements().
BlockSize
template<typename DT_ , typename IT_ , int BlockSize_> constexpr int FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::BlockSize = BlockSize_ static constexpr
The block size.
Definition at line 57 of file unit_filter_blocked.hpp.
is_global
template<typename DT_ , typename IT_ , int BlockSize_> constexpr bool FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::is_global = false static constexpr
Definition at line 71 of file unit_filter_blocked.hpp.
is_local
template<typename DT_ , typename IT_ , int BlockSize_> constexpr bool FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::is_local = true static constexpr
Definition at line 72 of file unit_filter_blocked.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/unit_filter_blocked.hpp