FEAT: FEAT::Solver::NLCG< Functional_, Filter_ > Class Template Reference
FEAT::Solver::NLCG< Functional_, Filter_ > Class Template Reference abstract
Nonlinear Conjugate Gradient method for finding a minimum of an functional's gradient.
#include <nlcg.hpp>
Public Types
typedef NLOptLS< FunctionalType, FilterType > BaseClass
Our baseclass.
typedef Functional_::DataType DataType
Underlying floating point type.
typedef Filter_ FilterType
The filter type.
typedef Functional_ FunctionalType
The nonlinear functional type.
typedef Functional_::GradientType GradientType
Type of the functional's gradient has.
typedef Solver::Linesearch< Functional_, Filter_ > LinesearchType
Our type of linesearch.
typedef NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > PrecondType
Generic preconditioner.
typedef Functional_::VectorTypeR VectorType
Input type for the gradient.
Public Member Functions
NLCG (const String &section_name, PropertyMap *section, Functional_ &functional, Filter_ &filter, std::shared_ptr< LinesearchType > linesearch, std::shared_ptr< PrecondType > precond=nullptr)
Constructor using a PropertyMap.
NLCG (Functional_ &functional, Filter_ &filter, std::shared_ptr< LinesearchType > linesearch, const NLCGDirectionUpdate du=direction_update_default, bool keep_iterates=false, std::shared_ptr< PrecondType > precond=nullptr)
Standard constructor.
virtual ~NLCG ()
Virtual destructor.
virtual Status apply (Vector_ &vec_cor, const Vector_ &vec_def)=0
Solver application method.
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def) override
Solver application method.
DataType calc_convergence_rate () const
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
DataType calc_defect_reduction () const
Computes the overall defect reduction factor: (defect_final / defect_inital)
virtual Status correct (VectorType &vec_sol, const VectorType &vec_rhs) override
Solver correction method.
virtual Status correct (VectorType &vec_sol, const VectorType &vec_rhs)=0
Solver correction method.
virtual void done ()
Finalization method.
virtual void done_numeric () override
virtual void done_symbolic () override
Symbolic finalization method.
DataType get_def_final () const
Returns the final defect.
DataType get_def_initial () const
Returns the initial defect.
DataType get_div_abs () const
Returns the absolute divergence.
DataType get_div_rel () const
Returns the relative divergence.
Index get_max_iter () const
Returns the maximum number of iterations.
Index get_min_iter () const
Returns the minimal number of iterations.
Index get_min_stag_iter () const
Returns the minimum stagnation iteration count.
Index get_num_iter () const
Returns number of performed iterations.
String get_plot_name () const
Returns the plot name of the solver.
DataType get_stag_rate () const
Returns the stagnation rate.
Status get_status () const
Returns the status.
virtual String get_summary () const override
Returns a summary string.
DataType get_tol_abs () const
Returns the absolute tolerance.
DataType get_tol_abs_low () const
Returns the lower absolute tolerance.
virtual DataType get_tol_fval ()
Gets the tolerance for function value improvement.
DataType get_tol_rel () const
Returns the relative tolerance.
virtual DataType get_tol_step ()
Gets the tolerance for the linesearch step size.
virtual void init ()
Initialization method.
virtual void init_numeric () override
virtual void init_symbolic () override
Symbolic initialization method.
bool is_converged () const
checks for convergence
bool is_converged (const DataType def_cur) const
checks for convergence
bool is_diverged () const
checks for divergence
bool is_diverged (const DataType def_cur) const
checks for divergence
virtual String name () const override
Returns a descriptive string.
virtual void plot_summary () const
Plot a summary of the last solver run.
void set_direction_update (NLCGDirectionUpdate update_)
Sets the direction update method.
void set_div_abs (DataType div_abs)
Sets the absolute divergence for the solver.
void set_div_rel (DataType div_rel)
Sets the relative divergence for the solver.
void set_keep_iterates (bool keep_iterates)
Sets the iterates deque according to a bool.
virtual void set_ls_iter_digits (Index digits)
Sets the number of digits used to plot line search iteration numbers.
void set_max_iter (Index max_iter)
Sets the maximum iteration count for the solver.
void set_max_num_restarts (Index max_num_restarts)
Sets the restart frquency.
void set_min_iter (Index min_iter)
Sets the minimum iteration count for the solver.
void set_min_stag_iter (Index min_iter)
Sets the minimum stagnate iteration count for the solver.
void set_plot_interval (const Index plot_interval)
Sets the interval between two plot outputs, if any.
void set_plot_mode (const PlotMode plot_mode)
Sets the plot mode of the solver.
void set_plot_name (const String &plot_name)
Sets the plot name of the solver.
void set_restart_freq (Index restart_freq)
Sets the restart frquency.
void set_stag_rate (DataType rate)
Sets the stagnation rate fot the solver.
void set_tol_abs (DataType tol_abs)
Sets the absolute tolerance for the solver.
void set_tol_abs_low (DataType tol_abs_low)
Sets the lower absolute tolerance for the solver.
virtual void set_tol_fval (DataType tol_fval)
Sets the tolerance for function value improvement.
void set_tol_rel (DataType tol_rel)
Sets the relative tolerance for the solver.
virtual void set_tol_step (DataType tol_step)
Sets the tolerance for the linesearch step size.
void skip_defect_calc (bool skip)
Specifies whether defect calculation is allowed to be skipped.
Public Attributes
std::deque< VectorType > * iterates
For debugging purposes, all iterates can be logged to here.
Static Public Attributes
static constexpr NLCGDirectionUpdate direction_update_default = NLCGDirectionUpdate::DYHSHybrid
Default search direction update.
Protected Member Functions
virtual Status _analyse_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag)
Internal function: analyse the current defect.
virtual Status _apply_intern (VectorType &vec_sol)
Internal function, applies the solver.
bool _apply_precond (VectorType &vec_cor, const VectorType &vec_def, const Filter_ &filter)
Applies the preconditioner onto a defect vector.
virtual DataType _calc_def_norm (const VectorType &vec_def, const VectorType &vec_sol)
Computes the defect norm.
bool _plot_iter (Status st=Status::progress) const
Plot the current iteration?
virtual void _plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev)
Plots an iteration line.
bool _plot_summary () const
Plot summary?
void _print_line (const String &line) const
Prints a line.
bool _progress () const
Progress iteration?
void _set_comm (const Dist::Comm *comm)
Sets the communicator for the solver directly.
template<typename Matrix_ >
void _set_comm_by_matrix (const Matrix_ &matrix)
Sets the communicator for the solver from a matrix.
void _set_comm_by_vector (const Vector_ &vector)
Sets the communicator for the solver from a vector.
virtual Status _set_initial_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the initial defect vector.
virtual Status _set_initial_defect (const VectorType &vec_def, const VectorType &vec_sol) override
Internal function: sets the initial defect vector.
virtual Status _set_new_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the new (next) defect vector.
virtual Status _set_new_defect (const VectorType &vec_r, const VectorType &vec_sol) override
Internal function: sets the new defect norm.
virtual Status _update_defect (const DataType def_cur_norm)
Internal function: sets the new (next) defect norm.
DataType compute_beta (const DataType &gamma, const DataType &gamma_prev) const
Computes the parameter beta for the search direction update.
DataType dai_yuan (const DataType gamma) const
Dai-Yuan update.
DataType dy_hs_hybrid (const DataType gamma) const
Dai-Yuan-Hestenes-Stiefel update.
DataType fletcher_reeves (const DataType gamma, const DataType gamma_prev) const
Fletcher-Reeves update.
DataType hager_zhang (const DataType gamma) const
Hager-Zhang update.
DataType hestenes_stiefel () const
Hestenes-Stiefel update.
DataType polak_ribiere (const DataType gamma_prev) const
Modified Polak-Ribiere-Polyak.
Protected Attributes
const Dist::Comm * _comm
Communicator of the solver.
DataType _def_cur
current defect
DataType _def_init
initial defect
DataType _def_prev
previous iteration defect
NLCGDirectionUpdate _direction_update
Method to update the search direction.
DataType _div_abs
absolute divergence parameter
DataType _div_rel
relative divergence parameter
Filter_ & _filter
The filter we apply to the gradient.
Functional_ & _functional
Our nonlinear functional.
DataType _fval
Current functional value.
DataType _fval_init
Initial function value.
DataType _fval_prev
Functional value from the previous iteration.
Index _iter_digits
iteration count digits for plotting
std::shared_ptr< LinesearchType > _linesearch
The linesearch used along the descent direction.
Index _ls_iter_digits
The number of digits used to plot line search iteration numbers.
Index _ls_its
The number of iterations the linesearch performed in the last iteration of this solver.
Index _max_iter
maximum number of iterations
Index _max_num_restarts
Maximum number of restarts triggered by the strong Wolfe conditions not holding.
Index _min_iter
minimum number of iterations
Index _min_stag_iter
minimum number of stagnation iterations
Index _num_iter
number of performed iterations
Index _num_restarts
Number of these restarts performed consecutively.
Index _num_stag_iter
number of consecutive stagnated iterations
Index _plot_interval
plot output interval
PlotMode _plot_mode
whether to plot something
String _plot_name
name of the solver in plots
std::shared_ptr< PrecondType > _precond
Index _restart_freq
Restart frequency, defaults to problemsize+3.
bool _skip_def_calc
whether to skip defect computation if possible
DataType _stag_rate
stagnation rate
Status _status
current status of the solver
DataType _steplength
The last step length of the line search.
DataType _tol_abs
absolute tolerance parameter
DataType _tol_abs_low
absolute tolerance parameter
DataType _tol_fval
Tolerance for function improvement.
DataType _tol_rel
relative tolerance parameter
DataType _tol_step
Tolerance for the length of the update step.
VectorType _vec_p
descend direction vector
VectorType _vec_r
defect vector
VectorType _vec_y
temporary vector: y[k+1] = r[k+1] - r[k]
VectorType _vec_z
temporary vector: Preconditioned defect
Detailed Description
template<typename Functional_, typename Filter_>
class FEAT::Solver::NLCG< Functional_, Filter_ >
Nonlinear Conjugate Gradient method for finding a minimum of an functional's gradient.
Template Parameters
Functional_ Nonlinear Functional to minimize the gradient of
Filter_ Filter to apply to the functional's gradient
See [NW06] for an overview of optimization techniques.
Possible update strategies for the search direction are Dai-Yuan [DY99], Fletcher-Reeves [FR64], Hager-Zhang [HZ05], Hestenes-Stiefel [HS52] and Polak-Ribiere [PR64].
Definition at line 99 of file nlcg.hpp.
Member Typedef Documentation
BaseClass
template<typename Functional_ , typename Filter_ > typedef NLOptLS<FunctionalType, FilterType> FEAT::Solver::NLCG< Functional_, Filter_ >::BaseClass
Our baseclass.
Definition at line 117 of file nlcg.hpp.
DataType
template<typename Functional_ , typename Filter_ > typedef Functional_::DataType FEAT::Solver::NLCG< Functional_, Filter_ >::DataType
Underlying floating point type.
Definition at line 114 of file nlcg.hpp.
FilterType
template<typename Functional_ , typename Filter_ > typedef Filter_ FEAT::Solver::NLCG< Functional_, Filter_ >::FilterType
The filter type.
Definition at line 105 of file nlcg.hpp.
FunctionalType
template<typename Functional_ , typename Filter_ > typedef Functional_ FEAT::Solver::NLCG< Functional_, Filter_ >::FunctionalType
The nonlinear functional type.
Definition at line 103 of file nlcg.hpp.
GradientType
template<typename Functional_ , typename Filter_ > typedef Functional_::GradientType FEAT::Solver::NLCG< Functional_, Filter_ >::GradientType
Type of the functional's gradient has.
Definition at line 110 of file nlcg.hpp.
LinesearchType
template<typename Functional_ , typename Filter_ > typedef Solver::Linesearch<Functional_, Filter_> FEAT::Solver::NLCG< Functional_, Filter_ >::LinesearchType
Our type of linesearch.
Definition at line 107 of file nlcg.hpp.
PrecondType
template<typename Functional_ , typename Filter_ > typedef NLOptPrecond<typename Functional_::VectorTypeL, Filter_> FEAT::Solver::NLCG< Functional_, Filter_ >::PrecondType
Generic preconditioner.
Definition at line 119 of file nlcg.hpp.
VectorType
template<typename Functional_ , typename Filter_ > typedef Functional_::VectorTypeR FEAT::Solver::NLCG< Functional_, Filter_ >::VectorType
Input type for the gradient.
Definition at line 112 of file nlcg.hpp.
Constructor & Destructor Documentation
NLCG() [1/2]
template<typename Functional_ , typename Filter_ > FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG (Functional_ & functional, Filter_ & filter, std::shared_ptr< LinesearchType > linesearch, const NLCGDirectionUpdate du = direction_update_default, bool keep_iterates = false, std::shared_ptr< PrecondType > precond = nullptr) inline explicit
Standard constructor.
Parameters
[in,out] functional The (nonlinear) functional. Cannot be const because it saves its own state
[in] filter Filter to apply to the functional's gradient
[in,out] linesearch The linesearch to be used, cannot be const as internal data changes
[in] du Which direction update to use
[in] keep_iterates Keep all iterates in a std::deque. Defaults to false.
[in,out] precond Preconditioner, defaults to nullptr. Cannot be const as internal data changes
Definition at line 176 of file nlcg.hpp.
References FEAT::Solver::NLOptLS< Functional_, Filter_ >::_functional, FEAT::Solver::NLCG< Functional_, Filter_ >::_linesearch, FEAT::Solver::IterativeSolver< Vector_ >::_min_stag_iter, FEAT::Math::ilog10(), FEAT::Solver::NLCG< Functional_, Filter_ >::iterates, FEAT::Solver::NLOptLS< Functional_, Filter_ >::set_ls_iter_digits(), and XASSERT.
NLCG() [2/2]
template<typename Functional_ , typename Filter_ > FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG (const String & section_name, PropertyMap * section, Functional_ & functional, Filter_ & filter, std::shared_ptr< LinesearchType > linesearch, std::shared_ptr< PrecondType > precond = nullptr) inline explicit
Constructor using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] functional The functional.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
[in] linesearch The linesearch to use.
Definition at line 223 of file nlcg.hpp.
References FEAT::Solver::NLOptLS< Functional_, Filter_ >::_functional, FEAT::Solver::NLCG< Functional_, Filter_ >::_linesearch, FEAT::Solver::IterativeSolver< Vector_ >::_min_stag_iter, FEAT::Math::ilog10(), FEAT::Solver::NLCG< Functional_, Filter_ >::iterates, FEAT::PropertyMap::query(), FEAT::Solver::NLCG< Functional_, Filter_ >::set_direction_update(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::set_ls_iter_digits(), FEAT::Solver::NLCG< Functional_, Filter_ >::set_max_num_restarts(), and XASSERT.
~NLCG()
template<typename Functional_ , typename Filter_ > virtual FEAT::Solver::NLCG< Functional_, Filter_ >::~NLCG () inline virtual
Virtual destructor.
Definition at line 268 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::iterates.
Member Function Documentation
_analyse_defect()
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag) inline protected virtual inherited
Internal function: analyse the current defect.
Note
This function is called by _set_new_defect() and _update_defect().
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
[in] check_stag Specifies whether to check (and update) the stagnation criterion. This is typically set to false if one wants to check anything else than the 'true' next defect norm.
Returns
The updated status code.
Definition at line 799 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_iter, FEAT::Solver::aborted, FEAT::Solver::diverged, FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), FEAT::Solver::IterativeSolver< Vector_ >::is_diverged(), FEAT::Math::isfinite(), FEAT::Solver::max_iter, FEAT::Solver::progress, FEAT::Solver::stagnated, and FEAT::Solver::success.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::_update_defect().
_apply_intern()
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern (VectorType & vec_sol) inline protected virtual
Internal function, applies the solver.
Parameters
[in,out] vec_sol The initial guess, gets overwritten by the solution
Returns
A solver status code.
This does not have a right hand side because that is contained in the gradient of the functional and we always seek grad functional(vec_sol) = 0
Definition at line 423 of file nlcg.hpp.
References FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >::_apply_precond(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_filter, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval_prev, FEAT::Solver::NLCG< Functional_, Filter_ >::_linesearch, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_ls_its, FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, FEAT::Solver::NLCG< Functional_, Filter_ >::_num_restarts, FEAT::Solver::NLCG< Functional_, Filter_ >::_restart_freq, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLCG< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_steplength, FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel, FEAT::Solver::NLCG< Functional_, Filter_ >::_vec_r, FEAT::Solver::aborted, FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta(), FEAT::Solver::IterationStats::destroy(), FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), FEAT::Solver::NLCG< Functional_, Filter_ >::iterates, FEAT::Solver::NLCG< Functional_, Filter_ >::name(), FEAT::Solver::progress, FEAT::Solver::success, and FEAT::Solver::undefined.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::apply(), and FEAT::Solver::NLCG< Functional_, Filter_ >::correct().
_apply_precond()
bool FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >::_apply_precond (VectorType & vec_cor, const VectorType & vec_def, const Filter_ & filter) inline protected inherited
Applies the preconditioner onto a defect vector.
Note
If no preconditioner is present, this function will simply copy the input vector's contents into the output vector, therefore emulating an "identity preconditioner".
Parameters
[in,out] vec_cor A reference to the vector that shall receive the preconditioned defect.
[in] vec_def A reference to the vector that is to be preconditioned.
[in] filter A reference to the system filter. This filter is only used if no preconditioner is present.
Returns
true, if the preconditioner application was successful, otherwise false.
Definition at line 1071 of file iterative.hpp.
_calc_def_norm()
template<typename Vector_ > virtual DataType FEAT::Solver::IterativeSolver< Vector_ >::_calc_def_norm (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Computes the defect norm.
Parameters
[in] vec_def The current defect vector.
[in] vec_sol The current solution vector approximation.
Definition at line 652 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect().
_plot_iter()
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter (Status st = Status::progress) const inline protected inherited
Plot the current iteration?
Parameters
[in] st The status of the current iteration.
Returns
true if the plot mode is set to iter or all and the plot interval matches or the solver does not continue to the next iteration
Definition at line 666 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, FEAT::Solver::IterativeSolver< Vector_ >::_plot_interval, FEAT::Solver::IterativeSolver< Vector_ >::_plot_mode, FEAT::Solver::all, FEAT::Solver::iter, and FEAT::Solver::progress.
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::_update_defect().
_plot_iter_line()
template<typename Vector_ > virtual void FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev) inline protected virtual inherited
Plots an iteration line.
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
Definition at line 719 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_print_line(), FEAT::String::pad_front(), FEAT::stringify(), FEAT::stringify_fp_fix(), and FEAT::stringify_fp_sci().
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::_update_defect().
_plot_summary()
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::_plot_summary () const inline protected inherited
Plot summary?
Returns
true if the plot mode is set to summary or all.
Definition at line 677 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_mode, FEAT::Solver::all, and FEAT::Solver::summary.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::plot_summary().
_print_line()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::_print_line (const String & line) const inline protected inherited
Prints a line.
Parameters
[in] line The line to be printed.
Definition at line 698 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_comm, and FEAT::Dist::Comm::print().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::plot_summary().
_progress()
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::_progress () const inline protected inherited
Progress iteration?
Returns
true if the solver should process, otherwise false.
Definition at line 687 of file iterative.hpp.
References FEAT::Solver::progress.
_set_comm()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::_set_comm (const Dist::Comm * comm) inline protected inherited
Sets the communicator for the solver directly.
Parameters
[in] comm A pointer to the communicator that is to be used by the solver.
Definition at line 613 of file iterative.hpp.
_set_comm_by_matrix()
template<typename Vector_ > template<typename Matrix_ > void FEAT::Solver::IterativeSolver< Vector_ >::_set_comm_by_matrix (const Matrix_ & matrix) inline protected inherited
Sets the communicator for the solver from a matrix.
Parameters
[in] matrix A reference to a matrix. If 'Matrix_' is a 'Global::Matrix', then the communicator of the matrix gate is taken.
Definition at line 626 of file iterative.hpp.
Referenced by FEAT::Solver::BiCGStab< Matrix_, Filter_ >::BiCGStab(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::BiCGStabL(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::FGMRES(), FEAT::Solver::GroppPCG< Matrix_, Filter_ >::GroppPCG(), FEAT::Solver::IDRS< Matrix_, Filter_ >::IDRS(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::NLOptLS(), FEAT::Solver::PCG< Matrix_, Filter_ >::PCG(), FEAT::Solver::PCR< Matrix_, Filter_ >::PCR(), FEAT::Solver::PipePCG< Matrix_, Filter_ >::PipePCG(), FEAT::Solver::PMR< Matrix_, Filter_ >::PMR(), FEAT::Solver::PSD< Matrix_, Filter_ >::PSD(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::RBiCGStab(), FEAT::Solver::RGCR< Matrix_, Filter_ >::RGCR(), and FEAT::Solver::Richardson< Matrix_, Filter_ >::Richardson().
_set_comm_by_vector()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::_set_comm_by_vector (const Vector_ & vector) inline protected inherited
Sets the communicator for the solver from a vector.
Parameters
[in] vector A reference to a vector. If 'Vector_' is a 'Global::Vector', then the communicator of the vector gate is taken.
Definition at line 638 of file iterative.hpp.
_set_initial_defect() [1/2]
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Internal function: sets the initial defect vector.
Parameters
[in] vec_def The initial defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Reimplemented in FEAT::Solver::QPenalty< Functional_ >.
Definition at line 748 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_calc_def_norm(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low, FEAT::Solver::aborted, FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), FEAT::Math::isfinite(), FEAT::Solver::SolverBase< Vector_ >::name(), FEAT::Solver::progress, FEAT::Math::sqr(), and FEAT::Solver::success.
Referenced by FEAT::Solver::PCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), and FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::_apply_intern().
_set_initial_defect() [2/2]
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect (const VectorType & vec_def, const VectorType & vec_sol) inline override protected virtual inherited
Internal function: sets the initial defect vector.
Parameters
[in] vec_def The initial defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Definition at line 269 of file nloptls.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_calc_def_norm(), FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, FEAT::Solver::IterativeSolver< Vector_ >::_def_init, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval_prev, FEAT::Solver::IterativeSolver< Vector_ >::_iter_digits, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_ls_iter_digits, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_ls_its, FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, FEAT::Solver::IterativeSolver< Vector_ >::_num_stag_iter, FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_name, FEAT::Solver::IterativeSolver< Vector_ >::_print_line(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_steplength, FEAT::Solver::aborted, FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), FEAT::Math::isfinite(), FEAT::Solver::SolverBase< Vector_ >::name(), FEAT::String::pad_front(), FEAT::Solver::progress, FEAT::Math::sqr(), FEAT::stringify(), FEAT::stringify_fp_sci(), and FEAT::Solver::success.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), and FEAT::Solver::NLSD< Functional_, Filter_ >::_apply_intern().
_set_new_defect() [1/2]
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Internal function: sets the new (next) defect vector.
This function computes the defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] vec_def The new defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Definition at line 857 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_calc_def_norm(), FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, FEAT::Solver::IterativeSolver< Vector_ >::_max_iter, FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::IterativeSolver< Vector_ >::_skip_def_calc, FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), and FEAT::Solver::SolverBase< Vector_ >::name().
Referenced by FEAT::Solver::PCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), and FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::_apply_intern().
_set_new_defect() [2/2]
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::NLCG< Functional_, Filter_ >::_set_new_defect (const VectorType & vec_r, const VectorType & vec_sol) inline override protected virtual
Internal function: sets the new defect norm.
This function computes the defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] vec_r The new defect vector.
[in] vec_sol The current solution vector approximation.
Returns
A solver status code.
Reimplemented from FEAT::Solver::NLOptLS< Functional_, Filter_ >.
Definition at line 673 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::_max_num_restarts, FEAT::Solver::NLCG< Functional_, Filter_ >::_num_restarts, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::progress, and FEAT::Solver::stagnated.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern().
_update_defect()
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_update_defect (const DataType def_cur_norm) inline protected virtual inherited
Internal function: sets the new (next) defect norm.
This function takes a precalculated defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] def_cur_norm The new defect norm.
Returns
The updated Status code.
Note
This function is preferred over _set_new_defect when using asynchronous mpi operations.
Definition at line 903 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), and FEAT::Solver::SolverBase< Vector_ >::name().
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern().
apply() [1/2]
template<typename Vector_ > virtual Status FEAT::Solver::SolverBase< Vector_ >::apply (Vector_ & vec_cor, const Vector_ & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::CuSolverLU, FEAT::Solver::CuSolverQR, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, and FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >.
Referenced by FEAT::Solver::solve().
apply() [2/2]
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::NLCG< Functional_, Filter_ >::apply (VectorType & vec_cor, const VectorType & vec_def) inline override virtual
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Definition at line 310 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_filter, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_functional, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval, FEAT::Solver::IterativeSolver< Vector_ >::_status, and FEAT::Solver::IterativeSolver< Vector_ >::plot_summary().
calc_convergence_rate()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate () const inline inherited
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
Definition at line 528 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, FEAT::Solver::IterativeSolver< Vector_ >::_def_init, FEAT::Solver::IterativeSolver< Vector_ >::_num_iter, and FEAT::Math::pow().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
calc_defect_reduction()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::calc_defect_reduction () const inline inherited
Computes the overall defect reduction factor: (defect_final / defect_inital)
Definition at line 543 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_init, and FEAT::Math::abs().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
compute_beta()
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta (const DataType & gamma, const DataType & gamma_prev) const inline protected
Computes the parameter beta for the search direction update.
Parameters
[in] gamma <r[k+1], z[k+1]>
[in] gamma_prev <r[k], z[k]>
If the returned \(\beta = 0,\) the next search direction is the steepest descent direction.
Returns
The new parameter beta.
Definition at line 636 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::_direction_update, FEAT::Solver::NLCG< Functional_, Filter_ >::dai_yuan(), FEAT::Solver::NLCG< Functional_, Filter_ >::dy_hs_hybrid(), FEAT::Solver::NLCG< Functional_, Filter_ >::fletcher_reeves(), FEAT::Solver::NLCG< Functional_, Filter_ >::hager_zhang(), FEAT::Solver::NLCG< Functional_, Filter_ >::hestenes_stiefel(), FEAT::Solver::NLCG< Functional_, Filter_ >::polak_ribiere(), FEAT::stringify(), and XABORTM.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern().
correct() [1/2]
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::NLCG< Functional_, Filter_ >::correct (VectorType & vec_sol, const VectorType & vec_rhs) inline override virtual
Solver correction method.
This method applies the solver represented by this object onto a given right-hand-side vector and updates the corresponding solution vector.
In contrast to the apply() method of the SolverBase base class, this method uses the vector vec_sol as the initial solution vector for the iterative solution process instead of ignoring its contents upon entry and starting with the null vector.
Parameters
[in,out] vec_sol The vector that contains the initial solution upon entry and receives the solution of the linear system upon exit.
[in] vec_rhs The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_sol and vec_rhs must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Definition at line 336 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_filter, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_functional, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval, FEAT::Solver::IterativeSolver< Vector_ >::_status, and FEAT::Solver::IterativeSolver< Vector_ >::plot_summary().
correct() [2/2]
template<typename Vector_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::correct (VectorType & vec_sol, const VectorType & vec_rhs) pure virtual inherited
Solver correction method.
This method applies the solver represented by this object onto a given right-hand-side vector and updates the corresponding solution vector.
In contrast to the apply() method of the SolverBase base class, this method uses the vector vec_sol as the initial solution vector for the iterative solution process instead of ignoring its contents upon entry and starting with the null vector.
Parameters
[in,out] vec_sol The vector that contains the initial solution upon entry and receives the solution of the linear system upon exit.
[in] vec_rhs The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_sol and vec_rhs must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >, FEAT::Solver::MQCLinesearch< Functional_, Filter_ >, FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >, FEAT::Solver::SecantLinesearch< Functional_, Filter_ >, and FEAT::Solver::QPenalty< Functional_ >.
Referenced by FEAT::Solver::solve().
dai_yuan()
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLCG< Functional_, Filter_ >::dai_yuan (const DataType gamma) const inline protected
Dai-Yuan update.
Parameters
[in] gamma <r[k+1], z[k+1]>
The Dai-Yuan update sets
\[ r_k := -\nabla f(x_k), \quad z_k := M^{-1} r_k, \quad \gamma_{k+1} := \left< r_{k+1}, z_{k+1} \right>, \quad \eta_{k+\frac{1}{2}} := \left<r_{k+1}, p_k \right>, \quad \eta_k := \left<r_k, d_k\right> \]
\[ \beta_{k+1} := \frac{\gamma_{k+1}}{ - \eta_{k+\frac{1}{2}} - \eta_k} \]
Note the sign changes due to this being formulated in terms of the defect rather than the function's gradient.
Returns
The new \(\beta_{DY}\)
Definition at line 713 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta().
done()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 285 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric(), and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
done_numeric()
virtual void FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >::done_numeric () inline override virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 1035 of file iterative.hpp.
done_symbolic()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::NLCG< Functional_, Filter_ >::done_symbolic () inline override virtual
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Reimplemented from FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >.
Definition at line 289 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::_linesearch, FEAT::Solver::NLCG< Functional_, Filter_ >::_restart_freq, FEAT::Solver::SolverBase< Vector_ >::done_symbolic(), and FEAT::Solver::NLCG< Functional_, Filter_ >::iterates.
dy_hs_hybrid()
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLCG< Functional_, Filter_ >::dy_hs_hybrid (const DataType gamma) const inline protected
Dai-Yuan-Hestenes-Stiefel update.
Parameters
[in] gamma <r[k+1], z[k+1]>
The hybrid Dai-Yuan/Hestenes-Stiefel update sets
\[ r_k := -\nabla f(x_k), \quad z_k := M^{-1} r_k, \quad \gamma_k := \left< r_k, z_k \right>, \quad \gamma_{k+\frac{1}{2}} := \left< r_k, z_{k+1} \right>, \quad \eta_{k+\frac{1}{2}} := \left<r_{k+1}, p_k \right>, \quad \eta_k := \left<r_k, d_k\right> \]
\[ \beta_{k+1} := \max \left\{0, \min \left\{ \frac{\gamma_{k+1} - \gamma_{k+\frac{1}{2}}}{ - \eta_{k+\frac{1}{2}}+ \eta_k}, \frac{\gamma_{k+1}}{ - \eta_{k+\frac{1}{2}}+ \eta_k} \right\} \right\} \]
Note the sign changes due to this being formulated in terms of the defect rather than the function's gradient.
Returns
The new \(\beta_{DYHS}\)
Definition at line 742 of file nlcg.hpp.
References FEAT::Math::max(), and FEAT::Math::min().
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta().
fletcher_reeves()
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLCG< Functional_, Filter_ >::fletcher_reeves (const DataType gamma, const DataType gamma_prev) const inline protected
Fletcher-Reeves update.
Parameters
[in] gamma <r[k+1], z[k+1]>
[in] gamma_prev <r[k], z[k]>
The Fletcher-Reeves update sets
\[ r_k := -\nabla f(x_k), \quad z_k := M^{-1} r_k, \quad \gamma_k := \left< r_k, z_k \right>, \quad \gamma_{k+\frac{1}{2}} = \left<r_{k+1}, p_k \right> \]
\[ \beta_{k+1} := \frac{\gamma_{k+1}}{\gamma_k} \]
Returns
The new \(\beta_{FR}\)
Definition at line 777 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta().
get_def_final()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_def_final () const inline inherited
Returns the final defect.
Definition at line 516 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
get_def_initial()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_def_initial () const inline inherited
Returns the initial defect.
Definition at line 510 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_init.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
get_div_abs()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_div_abs () const inline inherited
Returns the absolute divergence.
Definition at line 363 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_div_abs.
get_div_rel()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_div_rel () const inline inherited
Returns the relative divergence.
Definition at line 357 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_div_rel.
get_max_iter()
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::get_max_iter () const inline inherited
Returns the maximum number of iterations.
Definition at line 418 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_max_iter.
get_min_iter()
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::get_min_iter () const inline inherited
Returns the minimal number of iterations.
Definition at line 412 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_iter.
get_min_stag_iter()
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::get_min_stag_iter () const inline inherited
Returns the minimum stagnation iteration count.
Definition at line 387 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_stag_iter.
get_num_iter()
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter () const inline inherited
Returns number of performed iterations.
Definition at line 406 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_num_iter.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLSD< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::PCG< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_update_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
get_plot_name()
template<typename Vector_ > String FEAT::Solver::IterativeSolver< Vector_ >::get_plot_name () const inline inherited
Returns the plot name of the solver.
Definition at line 467 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_name.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
get_stag_rate()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_stag_rate () const inline inherited
Returns the stagnation rate.
Definition at line 375 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_stag_rate.
get_status()
template<typename Vector_ > Status FEAT::Solver::IterativeSolver< Vector_ >::get_status () const inline inherited
Returns the status.
Definition at line 522 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_status.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
get_summary()
template<typename Functional_ , typename Filter_ > virtual String FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary () const inline override virtual inherited
Returns a summary string.
Reimplemented from FEAT::Solver::IterativeSolver< Vector_ >.
Definition at line 184 of file nloptls.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, FEAT::Solver::IterativeSolver< Vector_ >::_def_init, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_functional, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval_init, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval_prev, FEAT::Solver::NLOptLS< Functional_, Filter_ >::_steplength, FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter(), FEAT::Solver::IterativeSolver< Vector_ >::get_plot_name(), FEAT::Solver::IterativeSolver< Vector_ >::get_status(), FEAT::stringify(), and FEAT::stringify_fp_sci().
get_tol_abs()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_tol_abs () const inline inherited
Returns the absolute tolerance.
Definition at line 332 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs.
get_tol_abs_low()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_tol_abs_low () const inline inherited
Returns the lower absolute tolerance.
Definition at line 338 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low.
get_tol_fval()
template<typename Functional_ , typename Filter_ > virtual DataType FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_tol_fval () inline virtual inherited
Gets the tolerance for function value improvement.
The convergence check is against the maximum of the absolute and relative function value.
Returns
The function value improvement tolerance
Definition at line 210 of file nloptls.hpp.
References FEAT::Solver::NLOptLS< Functional_, Filter_ >::_tol_fval.
get_tol_rel()
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::get_tol_rel () const inline inherited
Returns the relative tolerance.
Definition at line 326 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel.
get_tol_step()
template<typename Functional_ , typename Filter_ > virtual DataType FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_tol_step () inline virtual inherited
Gets the tolerance for the linesearch step size.
If the linesearch fails to find a new iterate because its relative update is too small, the direction update will fail to produce a new search direction so the NLSD has to be terminated.
Returns
The function value improvement tolerance
Definition at line 223 of file nloptls.hpp.
References FEAT::Solver::NLOptLS< Functional_, Filter_ >::_tol_step.
hager_zhang()
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLCG< Functional_, Filter_ >::hager_zhang (const DataType gamma) const inline protected
Hager-Zhang update.
Parameters
[in] gamma <r[k+1], z[k+1]>
The Hager-Zhang update sets
\[ r_k := -\nabla f(x_k), \quad z_k := M^{-1} r_k, \quad \gamma_k := \left< r_k, z_k \right>, \quad \gamma_{k+\frac{1}{2}} := \left< r_k, z_{k+1} \right>, \quad \eta_{k+\frac{1}{2}} := \left<r_{k+1}, p_k \right>, \quad \eta_k := \left<r_k, d_k\right> \]
\[ \bar{\beta}_{k+1} := \left< r_{k+1} -r_k - \frac{2 \|r_{k+1}\|^2}{\left< r_{k+1} - r_k, p_k \right>} p_k, 1/(<r_{k+1} - r_k, p_k>) r_k \right>, \]
\[ \beta_{k+1} := max\{ \beta, -1/ \left(\| p_k \| min\{ \mathrm{thresh}, \| r_{k+1} \| \} \right) \}, \]
where thresh is a predefined threshold parameter (i.e. 0.01).
Note the sign changes due to this being formulated in terms of the defect rather than the function's gradient.
Warning
This update strategy needs more precision in the linesearch than all others and is not very efficient in the current implementation. This serves more as a starting point for further improvement.
Returns
The new \(\beta_{HZ}\)
Definition at line 812 of file nlcg.hpp.
References FEAT::Math::max(), FEAT::Math::min(), FEAT::Math::sqr(), and FEAT::Math::sqrt().
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta().
hestenes_stiefel()
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLCG< Functional_, Filter_ >::hestenes_stiefel () const inline protected
Hestenes-Stiefel update.
The Hestenes-Stiefel update sets
\[ r_k := -\nabla f(x_k), \quad z_k := M^{-1} r_k, \quad \gamma_k := \left< r_k, z_k \right>, \quad \gamma_{k+\frac{1}{2}} := \left< r_k, z_{k+1} \right>, \quad \eta_{k+\frac{1}{2}} := \left<r_{k+1}, p_k \right>, \quad \eta_k := \left<r_k, d_k\right> \]
\[ \beta_{k+1} := \max \left\{0, \frac{\gamma_{k+1} - \gamma_{k+\frac{1}{2}}}{ - \eta_{k+\frac{1}{2}} + \eta_k} \right\} \]
Note the sign changes due to this being formulated in terms of the defect rather than the function's gradient.
Returns
The new \(\beta_{HS}\)
Definition at line 851 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta().
init()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 270 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
init_numeric()
virtual void FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >::init_numeric () inline override virtual inherited
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 1027 of file iterative.hpp.
init_symbolic()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::NLCG< Functional_, Filter_ >::init_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >.
Definition at line 275 of file nlcg.hpp.
References FEAT::Solver::NLOptLS< Functional_, Filter_ >::_functional, FEAT::Solver::NLCG< Functional_, Filter_ >::_linesearch, FEAT::Solver::NLCG< Functional_, Filter_ >::_vec_r, and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
is_converged() [1/2]
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::is_converged () const inline inherited
checks for convergence
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Returns
true, if converged, else false
Definition at line 478 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, and FEAT::Solver::IterativeSolver< Vector_ >::is_converged().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::is_converged().
is_converged() [2/2]
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::is_converged (const DataType def_cur) const inline inherited
checks for convergence
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Parameters
[in] def_cur The defect that is to be analysed
Returns
true, if converged, else false
Definition at line 492 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_init, FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs, FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low, and FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel.
is_diverged() [1/2]
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::is_diverged () const inline inherited
checks for divergence
Definition at line 498 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_cur, and FEAT::Solver::IterativeSolver< Vector_ >::is_diverged().
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::is_diverged().
is_diverged() [2/2]
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::is_diverged (const DataType def_cur) const inline inherited
checks for divergence
Definition at line 504 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_def_init, FEAT::Solver::IterativeSolver< Vector_ >::_div_abs, and FEAT::Solver::IterativeSolver< Vector_ >::_div_rel.
name()
template<typename Functional_ , typename Filter_ > virtual String FEAT::Solver::NLCG< Functional_, Filter_ >::name () const inline override virtual
Returns a descriptive string.
Returns
A string describing the solver.
Implements FEAT::Solver::SolverBase< Vector_ >.
Definition at line 304 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern().
plot_summary()
template<typename Vector_ > virtual void FEAT::Solver::IterativeSolver< Vector_ >::plot_summary () const inline virtual inherited
Plot a summary of the last solver run.
Definition at line 573 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_summary(), FEAT::Solver::IterativeSolver< Vector_ >::_print_line(), and FEAT::Solver::IterativeSolver< Vector_ >::get_summary().
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::apply(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::apply(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::apply(), FEAT::Solver::NLCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLSD< Functional_, Filter_ >::apply(), FEAT::Solver::PCG< Matrix_, Filter_ >::apply(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::apply(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::apply(), FEAT::Solver::IDRS< Matrix_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::correct(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::correct(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::correct(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::correct(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::correct(), FEAT::Solver::IDRS< Matrix_, Filter_ >::correct(), FEAT::Solver::NLCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLSD< Functional_, Filter_ >::correct(), FEAT::Solver::PCG< Matrix_, Filter_ >::correct(), and FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::correct().
polak_ribiere()
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLCG< Functional_, Filter_ >::polak_ribiere (const DataType gamma_prev) const inline protected
Modified Polak-Ribiere-Polyak.
Parameters
[in] gamma_prev <r[k], z[k]>
The Polak-Ribire-Polyak update sets
\begin{align*} r_k & := -\nabla f(x_k), \quad z_k := M^{-1} r_k, \quad \gamma_k := \left< r_k, z_k \right>, \quad \gamma_{k+\frac{1}{2}} := \left<r_{k+1}, z_k \right> \\ \beta_{k+1} & := \max\left\{ 0, \frac{\gamma_{k+1} - \gamma_{k+\frac{1}{2}}}{\gamma_k} \right\} \end{align*}
Returns
The new \(\beta_{PRP+}\)
Definition at line 876 of file nlcg.hpp.
References FEAT::Math::max().
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta().
set_direction_update()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::NLCG< Functional_, Filter_ >::set_direction_update (NLCGDirectionUpdate update_) inline
Sets the direction update method.
Parameters
[in] update_ NLCGDirectionUpdate to use.
Definition at line 404 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::_direction_update.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG().
set_div_abs()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_div_abs (DataType div_abs) inline inherited
Sets the absolute divergence for the solver.
Definition at line 351 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_div_abs.
set_div_rel()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_div_rel (DataType div_rel) inline inherited
Sets the relative divergence for the solver.
Definition at line 345 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_div_rel.
set_keep_iterates()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::NLCG< Functional_, Filter_ >::set_keep_iterates (bool keep_iterates) inline
Sets the iterates deque according to a bool.
Definition at line 362 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::iterates.
set_ls_iter_digits()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::NLOptLS< Functional_, Filter_ >::set_ls_iter_digits (Index digits) inline virtual inherited
Sets the number of digits used to plot line search iteration numbers.
Definition at line 260 of file nloptls.hpp.
References FEAT::Solver::NLOptLS< Functional_, Filter_ >::_ls_iter_digits.
Referenced by FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::ALGLIBMinCG(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::ALGLIBMinLBFGS(), FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG(), and FEAT::Solver::NLSD< Functional_, Filter_ >::NLSD().
set_max_iter()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_max_iter (Index max_iter) inline inherited
Sets the maximum iteration count for the solver.
Definition at line 399 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_iter_digits, FEAT::Solver::IterativeSolver< Vector_ >::_max_iter, FEAT::Math::ilog10(), and FEAT::Solver::max_iter.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_max_iter(), and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_max_iter().
set_max_num_restarts()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::NLCG< Functional_, Filter_ >::set_max_num_restarts (Index max_num_restarts) inline
Sets the restart frquency.
Definition at line 380 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::_max_num_restarts, and XASSERT.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG().
set_min_iter()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_min_iter (Index min_iter) inline inherited
Sets the minimum iteration count for the solver.
Definition at line 393 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_iter.
set_min_stag_iter()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_min_stag_iter (Index min_iter) inline inherited
Sets the minimum stagnate iteration count for the solver.
Definition at line 381 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_min_stag_iter.
set_plot_interval()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_plot_interval (const Index plot_interval) inline inherited
Sets the interval between two plot outputs, if any.
Parameters
[in] plot_interval The desired interval of iteration plots
Definition at line 455 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_interval.
set_plot_mode()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_plot_mode (const PlotMode plot_mode) inline inherited
Sets the plot mode of the solver.
Parameters
[in] plot_mode The desired plot mode
Definition at line 445 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_mode.
set_plot_name()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_plot_name (const String & plot_name) inline inherited
Sets the plot name of the solver.
Definition at line 461 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_plot_name.
Referenced by FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::BiCGStabL().
set_restart_freq()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::NLCG< Functional_, Filter_ >::set_restart_freq (Index restart_freq) inline
Sets the restart frquency.
Definition at line 391 of file nlcg.hpp.
References FEAT::Solver::NLCG< Functional_, Filter_ >::_restart_freq, and XASSERT.
set_stag_rate()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_stag_rate (DataType rate) inline inherited
Sets the stagnation rate fot the solver.
Definition at line 369 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_stag_rate.
set_tol_abs()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_tol_abs (DataType tol_abs) inline inherited
Sets the absolute tolerance for the solver.
Definition at line 314 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_abs(), and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_abs().
set_tol_abs_low()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_tol_abs_low (DataType tol_abs_low) inline inherited
Sets the lower absolute tolerance for the solver.
Definition at line 320 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low.
set_tol_fval()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::NLOptLS< Functional_, Filter_ >::set_tol_fval (DataType tol_fval) inline virtual inherited
Sets the tolerance for function value improvement.
Parameters
[in] tol_fval New tolerance for function value improvement.
The convergence check is against the maximum of the absolute and relative function value.
Reimplemented in FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >, and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >.
Definition at line 237 of file nloptls.hpp.
References FEAT::Solver::NLOptLS< Functional_, Filter_ >::_tol_fval.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::NLOptLS(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_fval(), and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_fval().
set_tol_rel()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::set_tol_rel (DataType tol_rel) inline inherited
Sets the relative tolerance for the solver.
Definition at line 308 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel.
set_tol_step()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::NLOptLS< Functional_, Filter_ >::set_tol_step (DataType tol_step) inline virtual inherited
Sets the tolerance for the linesearch step size.
Parameters
[in] tol_step New tolerance for the linesearch step size.
If the linesearch fails to find a new iterate because its relative update is too small, the direction update will fail to produce a new search direction so the NLCG has to be terminated.
Definition at line 252 of file nloptls.hpp.
References FEAT::Solver::NLOptLS< Functional_, Filter_ >::_tol_step.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::NLOptLS().
skip_defect_calc()
template<typename Vector_ > void FEAT::Solver::IterativeSolver< Vector_ >::skip_defect_calc (bool skip) inline inherited
Specifies whether defect calculation is allowed to be skipped.
Warning
Skipping defect calculation can lead to deadlocks in parallel solver implementations if one (but not all) processes need to compute the defect for some reason (like plotting) !
Use this function only when you really know what you are doing!
Parameters
[in] skip Specifies whether defect computation is allowed to be skipped.
Definition at line 434 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::_skip_def_calc.
Member Data Documentation
_comm
template<typename Vector_ > const Dist::Comm* FEAT::Solver::IterativeSolver< Vector_ >::_comm protected inherited
Communicator of the solver.
Definition at line 131 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_print_line().
_def_cur
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_def_cur protected inherited
current defect
Definition at line 182 of file iterative.hpp.
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_update_defect(), FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate(), FEAT::Solver::IterativeSolver< Vector_ >::get_def_final(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::is_diverged().
_def_init
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_def_init protected inherited
initial defect
Definition at line 180 of file iterative.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate(), FEAT::Solver::IterativeSolver< Vector_ >::calc_defect_reduction(), FEAT::Solver::IterativeSolver< Vector_ >::get_def_initial(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::is_diverged().
_def_prev
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_def_prev protected inherited
previous iteration defect
Definition at line 184 of file iterative.hpp.
Referenced by FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), and FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern().
_direction_update
template<typename Functional_ , typename Filter_ > NLCGDirectionUpdate FEAT::Solver::NLCG< Functional_, Filter_ >::_direction_update protected
Method to update the search direction.
Definition at line 131 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta(), and FEAT::Solver::NLCG< Functional_, Filter_ >::set_direction_update().
_div_abs
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_div_abs protected inherited
absolute divergence parameter
Definition at line 166 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_div_abs(), FEAT::Solver::IterativeSolver< Vector_ >::is_diverged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_div_abs().
_div_rel
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_div_rel protected inherited
relative divergence parameter
Definition at line 164 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_div_rel(), FEAT::Solver::IterativeSolver< Vector_ >::is_diverged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_div_rel().
_filter
template<typename Functional_ , typename Filter_ > Filter_& FEAT::Solver::NLOptLS< Functional_, Filter_ >::_filter protected inherited
The filter we apply to the gradient.
Definition at line 70 of file nloptls.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLSD< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_func_grad(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_func_grad(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLSD< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::correct(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLCG< Functional_, Filter_ >::correct(), and FEAT::Solver::NLSD< Functional_, Filter_ >::correct().
_functional
template<typename Functional_ , typename Filter_ > Functional_& FEAT::Solver::NLOptLS< Functional_, Filter_ >::_functional protected inherited
Our nonlinear functional.
Definition at line 68 of file nloptls.hpp.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::ALGLIBMinLBFGS(), FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_func_grad(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_func_grad(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLSD< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::correct(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLSD< Functional_, Filter_ >::correct(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::NLCG< Functional_, Filter_ >::init_symbolic(), and FEAT::Solver::NLSD< Functional_, Filter_ >::init_symbolic().
_fval
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval protected inherited
Current functional value.
Definition at line 80 of file nloptls.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLSD< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_func_grad(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_func_grad(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLSD< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::correct(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLSD< Functional_, Filter_ >::correct(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
_fval_init
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval_init protected inherited
Initial function value.
Definition at line 78 of file nloptls.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
_fval_prev
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLOptLS< Functional_, Filter_ >::_fval_prev protected inherited
Functional value from the previous iteration.
Definition at line 82 of file nloptls.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLSD< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_func_grad(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_func_grad(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
_iter_digits
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_iter_digits protected inherited
iteration count digits for plotting
Definition at line 186 of file iterative.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::set_max_iter().
_linesearch
template<typename Functional_ , typename Filter_ > std::shared_ptr<LinesearchType> FEAT::Solver::NLCG< Functional_, Filter_ >::_linesearch protected
The linesearch used along the descent direction.
Definition at line 125 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG(), FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLCG< Functional_, Filter_ >::done_symbolic(), and FEAT::Solver::NLCG< Functional_, Filter_ >::init_symbolic().
_ls_iter_digits
template<typename Functional_ , typename Filter_ > Index FEAT::Solver::NLOptLS< Functional_, Filter_ >::_ls_iter_digits protected inherited
The number of digits used to plot line search iteration numbers.
Definition at line 86 of file nloptls.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::set_ls_iter_digits().
_ls_its
template<typename Functional_ , typename Filter_ > Index FEAT::Solver::NLOptLS< Functional_, Filter_ >::_ls_its protected inherited
The number of iterations the linesearch performed in the last iteration of this solver.
Definition at line 88 of file nloptls.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLSD< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_log(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_log(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect().
_max_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_max_iter protected inherited
maximum number of iterations
Definition at line 172 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_max_iter(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_max_iter(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_max_iter(), FEAT::Solver::IterativeSolver< Vector_ >::set_max_iter(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_abs(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_abs(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_fval(), and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_fval().
_max_num_restarts
template<typename Functional_ , typename Filter_ > Index FEAT::Solver::NLCG< Functional_, Filter_ >::_max_num_restarts protected
Maximum number of restarts triggered by the strong Wolfe conditions not holding.
Definition at line 143 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::NLCG< Functional_, Filter_ >::set_max_num_restarts().
_min_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_min_iter protected inherited
minimum number of iterations
Definition at line 170 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_analyse_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_min_iter(), and FEAT::Solver::IterativeSolver< Vector_ >::set_min_iter().
_min_stag_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_min_stag_iter protected inherited
minimum number of stagnation iterations
Definition at line 176 of file iterative.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_min_stag_iter(), and FEAT::Solver::IterativeSolver< Vector_ >::set_min_stag_iter().
_num_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_num_iter protected inherited
number of performed iterations
Definition at line 174 of file iterative.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_update_defect(), FEAT::Solver::IterativeSolver< Vector_ >::calc_convergence_rate(), and FEAT::Solver::IterativeSolver< Vector_ >::get_num_iter().
_num_restarts
template<typename Functional_ , typename Filter_ > Index FEAT::Solver::NLCG< Functional_, Filter_ >::_num_restarts protected
Number of these restarts performed consecutively.
Definition at line 145 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), and FEAT::Solver::NLCG< Functional_, Filter_ >::_set_new_defect().
_num_stag_iter
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_num_stag_iter protected inherited
number of consecutive stagnated iterations
Definition at line 178 of file iterative.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect().
_plot_interval
template<typename Vector_ > Index FEAT::Solver::IterativeSolver< Vector_ >::_plot_interval protected inherited
plot output interval
Definition at line 190 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), and FEAT::Solver::IterativeSolver< Vector_ >::set_plot_interval().
_plot_mode
template<typename Vector_ > PlotMode FEAT::Solver::IterativeSolver< Vector_ >::_plot_mode protected inherited
whether to plot something
Definition at line 188 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_summary(), and FEAT::Solver::IterativeSolver< Vector_ >::set_plot_mode().
_plot_name
template<typename Vector_ > String FEAT::Solver::IterativeSolver< Vector_ >::_plot_name protected inherited
name of the solver in plots
Definition at line 133 of file iterative.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_plot_name(), and FEAT::Solver::IterativeSolver< Vector_ >::set_plot_name().
_precond
template<typename Functional_ , typename Filter_ > std::shared_ptr<PrecondType> FEAT::Solver::NLCG< Functional_, Filter_ >::_precond protected
This will be the preconditioner, or a nullptr. We need to save it ourselves because we cannot access the prepare() routine through the SolverBase pointer in our BaseClass
Definition at line 128 of file nlcg.hpp.
_restart_freq
template<typename Functional_ , typename Filter_ > Index FEAT::Solver::NLCG< Functional_, Filter_ >::_restart_freq protected
Restart frequency, defaults to problemsize+3.
Definition at line 147 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLCG< Functional_, Filter_ >::done_symbolic(), and FEAT::Solver::NLCG< Functional_, Filter_ >::set_restart_freq().
_skip_def_calc
template<typename Vector_ > bool FEAT::Solver::IterativeSolver< Vector_ >::_skip_def_calc protected inherited
whether to skip defect computation if possible
Definition at line 192 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::skip_defect_calc().
_stag_rate
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_stag_rate protected inherited
stagnation rate
Definition at line 168 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_stag_rate(), and FEAT::Solver::IterativeSolver< Vector_ >::set_stag_rate().
_status
template<typename Vector_ > Status FEAT::Solver::IterativeSolver< Vector_ >::_status protected inherited
current status of the solver
Definition at line 135 of file iterative.hpp.
Referenced by FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::apply(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::apply(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::apply(), FEAT::Solver::NLCG< Functional_, Filter_ >::apply(), FEAT::Solver::NLSD< Functional_, Filter_ >::apply(), FEAT::Solver::PCG< Matrix_, Filter_ >::apply(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::apply(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::apply(), FEAT::Solver::IDRS< Matrix_, Filter_ >::apply(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::correct(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::correct(), FEAT::Solver::BiCGStab< Matrix_, Filter_ >::correct(), FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::correct(), FEAT::Solver::FGMRES< Matrix_, Filter_ >::correct(), FEAT::Solver::IDRS< Matrix_, Filter_ >::correct(), FEAT::Solver::NLCG< Functional_, Filter_ >::correct(), FEAT::Solver::NLSD< Functional_, Filter_ >::correct(), FEAT::Solver::PCG< Matrix_, Filter_ >::correct(), FEAT::Solver::RBiCGStab< Matrix_, Filter_ >::correct(), and FEAT::Solver::IterativeSolver< Vector_ >::get_status().
_steplength
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLOptLS< Functional_, Filter_ >::_steplength protected inherited
The last step length of the line search.
Definition at line 84 of file nloptls.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLSD< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::_log(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::_log(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary().
_tol_abs
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs protected inherited
absolute tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 160 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::get_tol_abs(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_tol_abs().
_tol_abs_low
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_tol_abs_low protected inherited
absolute tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 162 of file iterative.hpp.
Referenced by FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::get_tol_abs_low(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_tol_abs_low().
_tol_fval
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLOptLS< Functional_, Filter_ >::_tol_fval protected inherited
Tolerance for function improvement.
Definition at line 73 of file nloptls.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_tol_fval(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_max_iter(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_max_iter(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_abs(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_abs(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::set_tol_fval(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_fval(), and FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_fval().
_tol_rel
template<typename Vector_ > DataType FEAT::Solver::IterativeSolver< Vector_ >::_tol_rel protected inherited
relative tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 158 of file iterative.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::IterativeSolver< Vector_ >::get_tol_rel(), FEAT::Solver::IterativeSolver< Vector_ >::is_converged(), and FEAT::Solver::IterativeSolver< Vector_ >::set_tol_rel().
_tol_step
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::NLOptLS< Functional_, Filter_ >::_tol_step protected inherited
Tolerance for the length of the update step.
Definition at line 75 of file nloptls.hpp.
Referenced by FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_tol_step(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::init_symbolic(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_max_iter(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_max_iter(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_abs(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_abs(), FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >::set_tol_fval(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_tol_fval(), and FEAT::Solver::NLOptLS< Functional_, Filter_ >::set_tol_step().
_vec_p
template<typename Functional_ , typename Filter_ > VectorType FEAT::Solver::NLCG< Functional_, Filter_ >::_vec_p protected
descend direction vector
Definition at line 136 of file nlcg.hpp.
_vec_r
template<typename Functional_ , typename Filter_ > VectorType FEAT::Solver::NLCG< Functional_, Filter_ >::_vec_r protected
defect vector
Definition at line 134 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), and FEAT::Solver::NLCG< Functional_, Filter_ >::init_symbolic().
_vec_y
template<typename Functional_ , typename Filter_ > VectorType FEAT::Solver::NLCG< Functional_, Filter_ >::_vec_y protected
temporary vector: y[k+1] = r[k+1] - r[k]
Definition at line 140 of file nlcg.hpp.
_vec_z
template<typename Functional_ , typename Filter_ > VectorType FEAT::Solver::NLCG< Functional_, Filter_ >::_vec_z protected
temporary vector: Preconditioned defect
Definition at line 138 of file nlcg.hpp.
direction_update_default
template<typename Functional_ , typename Filter_ > constexpr NLCGDirectionUpdate FEAT::Solver::NLCG< Functional_, Filter_ >::direction_update_default = NLCGDirectionUpdate::DYHSHybrid static constexpr
Default search direction update.
Definition at line 121 of file nlcg.hpp.
iterates
template<typename Functional_ , typename Filter_ > std::deque<VectorType>* FEAT::Solver::NLCG< Functional_, Filter_ >::iterates
For debugging purposes, all iterates can be logged to here.
Definition at line 151 of file nlcg.hpp.
Referenced by FEAT::Solver::NLCG< Functional_, Filter_ >::NLCG(), FEAT::Solver::NLCG< Functional_, Filter_ >::~NLCG(), FEAT::Solver::NLCG< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NLCG< Functional_, Filter_ >::done_symbolic(), and FEAT::Solver::NLCG< Functional_, Filter_ >::set_keep_iterates().
The documentation for this class was generated from the following file:
kernel/solver/nlcg.hpp