FEAT: FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ > Class Template Reference
FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ > Class Template Reference abstract
Vanka preconditioner/smoother class template implementation.
#include <vanka.hpp>
Public Types
typedef MatrixType::DataType DataType
our data type
typedef Filter_ FilterType
our filter type
typedef MatrixType::IndexType IndexType
our index type
typedef LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > MatrixType
our matrix type
typedef MatrixB_::VectorTypeR VectorP
pressure vector type
typedef MatrixType::VectorTypeR VectorType
our vector type
typedef MatrixD_::VectorTypeR VectorV
velocity vector type
Public Member Functions
Vanka (const MatrixType &matrix, const FilterType &filter, VankaType type, DataType omega=DataType(1), Index num_iter=Index(1))
Constructor.
virtual Status apply (LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > &vec_cor, const LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > &vec_def)=0
Solver application method.
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def) override
std::size_t bytes () const
std::size_t data_size () const
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic () override
Releases the symbolic factorization data.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Performs numeric factorization.
virtual void init_symbolic () override
Performs symbolic factorization.
virtual String name () const override
Returns the name of the solver.
void reset_timings ()
Resets the internal stop watches for time measurement.
double time_apply () const
Returns the total accumulated time for the solver application.
double time_init_numeric () const
Returns the total accumulated time for numeric initialization.
double time_init_symbolic () const
Returns the total accumulated time for symbolic initialization.
Protected Types
typedef Intern::VankaMatrix< MatrixA_ > VankaMatrixA
typedef Intern::VankaMatrix< MatrixB_ > VankaMatrixB
typedef Intern::VankaMatrix< MatrixD_ > VankaMatrixD
Protected Member Functions
void _alloc_data ()
Allocates the data arrays for numerical factorization.
void _apply_diag (VectorType &vec_cor, const VectorType &vec_def)
Applies the 'diagonal' Vanka iteration.
void _apply_full (VectorType &vec_cor, const VectorType &vec_def)
Applies the 'full' Vanka iteration.
void _build_p_block ()
Builds the 'blocked' pressure graph.
void _build_p_nodal ()
Builds the 'nodal' pressure graph.
void _build_v_block ()
Builds the velocity graph.
void _calc_scale ()
Calculate the scaling vector for additive Vanka.
void _factor_diag ()
Performs the 'diagonal' numerical factorization.
void _factor_full ()
Performs the 'full' numerical factorization.
Protected Attributes
std::vector< IndexType > _block_p_idx
std::vector< IndexType > _block_p_ptr
pressure block structure
std::vector< IndexType > _block_v_idx
std::vector< IndexType > _block_v_ptr
velocity block structure
std::vector< DataType > _data
factorization data
IndexType _degree_p
maximum pressure block degree
IndexType _degree_v
maximum velocity block degree
const FilterType & _filter
the system filter
const MatrixType & _matrix
the system matrix
Index _num_iter
desired number of iterations
DataType _omega
relaxation parameter
VankaType _type
the Vanka type
std::vector< DataType > _vcor
std::vector< DataType > _vdef
local defect/correction vectors
VectorType _vec_scale
temporary vectors (additive types only)
VectorType _vec_tmp1
VectorType _vec_tmp2
StopWatch watch_apply
StopWatch watch_init_numeric
StopWatch watch_init_symbolic
Detailed Description
template<typename MatrixA_, typename MatrixB_, typename MatrixD_, typename Filter_>
class FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >
Vanka preconditioner/smoother class template implementation.
This class template implements the Vanka preconditioner/smoother, which is a special Block-SOR/Gauss-Seidel variant suitable for working with saddle-point systems of the form
\[\begin{bmatrix} A & B\\D & 0\end{bmatrix} \cdot \begin{bmatrix} v\\p\end{bmatrix} = \begin{bmatrix} f\\g\end{bmatrix}\]
In total, this class template implements eight different variants of the Vanka, which can be chosen at run-time by specifying the corresponding VankaType in the constructor of this object. The eight variants are the cross-product of three binary variants:
1.a: Block Variants (VankaType::block_*_*)
The block variants collect all pressure DOFs, which are adjacent to each other via the connectivity graph of D*B with the same degree. If the B and D matrices are build by using a discontiunuous pressure element, then these block variants collect all DOFs associated with a single element of the underlying mesh, thus leading to the 'true' element-based Vanka.
Block variants are recommended for discontinuous pressure spaces.
1.b: Nodal Variants (VankaType::nodal_*_*)
The nodal variants process exactly one pressure DOF per block.
Nodal variants are recommended for continuous pressure spaces.
2.a: Diagonal Variants (VankaType::*_diag_*)
These variants apply the Schur-complement approach onto each local system and approximate the inverse of A by the inverse of its main diagonal. If there is more than one local pressure DOF, the local Schur-Complement matrix itself is inverted by using Gaussian elimination.
2.b: Full Variants (VankaType::*_full_*)
These variants invert the full dense local systems by using Gaussian elimination.
3.a: Multiplicative Variants (VankaType::*_*_mult)
These variants work successively within one Vanka iteration, just as the (scalar) Gauss-Seidel- or SOR-iterations do.
3.b: Additive Variants (VankaType::*_*_add)
These variants work in an additive way, i.e. they ignore the 'progess' made in the current iteration, just as the (scalar) Jacobi-iterations do.
Moreover, each of the above variants is parameterized in a relaxation/damping parameter omega, which can be specified in the constructor. For multiplicative variants, omega is a relaxation parameter (as in SOR), whereas for additive variants omega is a damping parameter (as in damped Jacobi).
Guidelines, Remarks, Warnings & Tips
In many cases, setting the relaxation/damping parameter omega to a value less than 1 can 'cure' a diverging Vanka variant. So before trying out a more expensive variant to achieve convergence, you may want to play around with omega first, e.g. by setting it to 0.8.
In many cases and for any variant, choosing omega > 1 leads to divergence, so don't do that.
If the pressure space is discontinuous, one should always choose block variants instead of nodal variants, as these require less memory, are less computationally expensive and lead to faster convergence in most cases.
If the pressure space is continuous, one should stick to the nodal variants.
Moreover, never use full variants for continuous pressure spaces, as these may require astronomical amounts of memory for the factorization!
Diagonal variants usually require (significantly) less memory than full variants. Therefore, when trying to configure a Vanka for a new type of problem and/or discretization, one should first try whether a diagonal variant works before trying a full variant.
For more complex problems (like convection-dominant Navier-Stokes), the full variants are often more stable than the diagonal variants.
Multiplicative variants are roughly twice as computationally expensive as additive variants.
Surprisingly, additive variants seem to converge faster than their multiplicative counterparts in many cases (at least for linear Stokes equations).
See also
[Vanka86]
Todo:
Find out how to use Vanka for Global::Matrix systems...
Author
Peter Zajac
Definition at line 1009 of file vanka.hpp.
Member Typedef Documentation
DataType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef MatrixType::DataType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::DataType
our data type
Definition at line 1021 of file vanka.hpp.
FilterType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef Filter_ FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::FilterType
our filter type
Definition at line 1016 of file vanka.hpp.
IndexType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef MatrixType::IndexType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::IndexType
our index type
Definition at line 1023 of file vanka.hpp.
MatrixType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef LAFEM::SaddlePointMatrix<MatrixA_, MatrixB_, MatrixD_> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::MatrixType
our matrix type
Definition at line 1014 of file vanka.hpp.
VankaMatrixA
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef Intern::VankaMatrix<MatrixA_> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::VankaMatrixA protected
Definition at line 1032 of file vanka.hpp.
VankaMatrixB
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef Intern::VankaMatrix<MatrixB_> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::VankaMatrixB protected
Definition at line 1033 of file vanka.hpp.
VankaMatrixD
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef Intern::VankaMatrix<MatrixD_> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::VankaMatrixD protected
Definition at line 1034 of file vanka.hpp.
VectorP
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef MatrixB_::VectorTypeR FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::VectorP
pressure vector type
Definition at line 1028 of file vanka.hpp.
VectorType
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef MatrixType::VectorTypeR FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::VectorType
our vector type
Definition at line 1019 of file vanka.hpp.
VectorV
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > typedef MatrixD_::VectorTypeR FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::VectorV
velocity vector type
Definition at line 1026 of file vanka.hpp.
Constructor & Destructor Documentation
Vanka()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::Vanka (const MatrixType & matrix, const FilterType & filter, VankaType type, DataType omega = DataType(1), Index num_iter = Index(1)) inline explicit
Constructor.
Parameters
[in] matrix The saddle-point system matrix.
[in] filter The system filter.
[in] type The desired type of Vanka.
[in] omega The relaxation parameter.
[in] num_iter The number of iterations to be performed.
Definition at line 1096 of file vanka.hpp.
Member Function Documentation
_alloc_data()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_alloc_data () inline protected
Allocates the data arrays for numerical factorization.
Definition at line 1407 of file vanka.hpp.
References FEAT::Math::max(), and FEAT::Math::sqr().
_apply_diag()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_diag (VectorType & vec_cor, const VectorType & vec_def) inline protected
Applies the 'diagonal' Vanka iteration.
Definition at line 1799 of file vanka.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d(), FEAT::LAFEM::TupleVector< First_, Rest_ >::copy(), FEAT::TimeStamp::elapsed_now(), FEAT::LAFEM::TupleVector< First_, Rest_ >::format(), and FEAT::Solver::iter.
_apply_full()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_full (VectorType & vec_cor, const VectorType & vec_def) inline protected
Applies the 'full' Vanka iteration.
Definition at line 1556 of file vanka.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::apply(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d(), FEAT::LAFEM::TupleVector< First_, Rest_ >::copy(), FEAT::TimeStamp::elapsed_now(), FEAT::LAFEM::TupleVector< First_, Rest_ >::format(), and FEAT::Solver::iter.
_build_p_block()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_build_p_block () inline protected
Builds the 'blocked' pressure graph.
This function build the pressure graph by trying to re-create patched 'blocks' by conjugating the D and B matrices of the system matrix.
Definition at line 1259 of file vanka.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d(), and FEAT::Math::max().
_build_p_nodal()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_build_p_nodal () inline protected
Builds the 'nodal' pressure graph.
Definition at line 1339 of file vanka.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
_build_v_block()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_build_v_block () inline protected
Builds the velocity graph.
Definition at line 1357 of file vanka.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d().
_calc_scale()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_calc_scale () inline protected
Calculate the scaling vector for additive Vanka.
Definition at line 1457 of file vanka.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::format().
_factor_diag()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_factor_diag () inline protected
Performs the 'diagonal' numerical factorization.
Todo:
does this produce false alerts?
Definition at line 1694 of file vanka.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d(), FEAT::Math::invert_matrix(), and FEAT::Math::isnormal().
_factor_full()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_factor_full () inline protected
Performs the 'full' numerical factorization.
Definition at line 1492 of file vanka.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_a(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_b(), FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::block_d(), and FEAT::Math::invert_matrix().
apply() [1/2]
virtual Status FEAT::Solver::SolverBase< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > >::apply (LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > & vec_cor, const LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
apply() [2/2]
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > virtual Status FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::apply (VectorType & vec_cor, const VectorType & vec_def) inline override virtual
Definition at line 1187 of file vanka.hpp.
bytes()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::size_t FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::bytes () const inline
Definition at line 1211 of file vanka.hpp.
data_size()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::size_t FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::data_size () const inline
Definition at line 1206 of file vanka.hpp.
done()
virtual void FEAT::Solver::SolverBase< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
done_numeric()
virtual void FEAT::Solver::SolverBase< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented in FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, and FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >.
Definition at line 246 of file base.hpp.
done_symbolic()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > virtual void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::done_symbolic () inline override virtual
Releases the symbolic factorization data.
Reimplemented from FEAT::Solver::SolverBase< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > >.
Definition at line 1148 of file vanka.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::clear().
init()
virtual void FEAT::Solver::SolverBase< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
init_numeric()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > virtual void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::init_numeric () inline override virtual
Performs numeric factorization.
Reimplemented from FEAT::Solver::SolverBase< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > >.
Definition at line 1163 of file vanka.hpp.
References FEAT::Solver::full, FEAT::StopWatch::start(), and FEAT::StopWatch::stop().
init_symbolic()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > virtual void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::init_symbolic () inline override virtual
Performs symbolic factorization.
Reimplemented from FEAT::Solver::SolverBase< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > >.
Definition at line 1113 of file vanka.hpp.
References FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::create_vector_r(), FEAT::StopWatch::start(), and FEAT::StopWatch::stop().
name()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > virtual String FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SolverBase< LAFEM::TupleVector< MatrixB_::VectorTypeL, MatrixD_::VectorTypeL > >.
Definition at line 1107 of file vanka.hpp.
reset_timings()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > void FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::reset_timings () inline
Resets the internal stop watches for time measurement.
Definition at line 1221 of file vanka.hpp.
References FEAT::StopWatch::reset().
time_apply()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > double FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::time_apply () const inline
Returns the total accumulated time for the solver application.
Definition at line 1247 of file vanka.hpp.
References FEAT::StopWatch::elapsed().
time_init_numeric()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > double FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::time_init_numeric () const inline
Returns the total accumulated time for numeric initialization.
Definition at line 1239 of file vanka.hpp.
References FEAT::StopWatch::elapsed().
time_init_symbolic()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > double FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::time_init_symbolic () const inline
Returns the total accumulated time for symbolic initialization.
Definition at line 1231 of file vanka.hpp.
References FEAT::StopWatch::elapsed().
Member Data Documentation
_block_p_idx
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::vector<IndexType> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_block_p_idx protected
Definition at line 1062 of file vanka.hpp.
_block_p_ptr
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::vector<IndexType> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_block_p_ptr protected
pressure block structure
Definition at line 1062 of file vanka.hpp.
_block_v_idx
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::vector<IndexType> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_block_v_idx protected
Definition at line 1060 of file vanka.hpp.
_block_v_ptr
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::vector<IndexType> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_block_v_ptr protected
velocity block structure
Definition at line 1060 of file vanka.hpp.
_data
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::vector<DataType> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_data protected
factorization data
Definition at line 1064 of file vanka.hpp.
_degree_p
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > IndexType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_degree_p protected
maximum pressure block degree
Definition at line 1058 of file vanka.hpp.
_degree_v
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > IndexType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_degree_v protected
maximum velocity block degree
Definition at line 1056 of file vanka.hpp.
_filter
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > const FilterType& FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_filter protected
the system filter
Definition at line 1048 of file vanka.hpp.
_matrix
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > const MatrixType& FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_matrix protected
the system matrix
Definition at line 1046 of file vanka.hpp.
_num_iter
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > Index FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_num_iter protected
desired number of iterations
Definition at line 1054 of file vanka.hpp.
_omega
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > DataType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_omega protected
relaxation parameter
Definition at line 1052 of file vanka.hpp.
_type
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > VankaType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_type protected
the Vanka type
Definition at line 1050 of file vanka.hpp.
_vcor
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::vector<DataType> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_vcor protected
Definition at line 1066 of file vanka.hpp.
_vdef
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::vector<DataType> FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_vdef protected
local defect/correction vectors
Definition at line 1066 of file vanka.hpp.
_vec_scale
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > VectorType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_vec_scale protected
temporary vectors (additive types only)
Definition at line 1068 of file vanka.hpp.
_vec_tmp1
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > VectorType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_vec_tmp1 protected
Definition at line 1068 of file vanka.hpp.
_vec_tmp2
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > VectorType FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_vec_tmp2 protected
Definition at line 1068 of file vanka.hpp.
watch_apply
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > StopWatch FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::watch_apply protected
Definition at line 1075 of file vanka.hpp.
watch_init_numeric
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > StopWatch FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::watch_init_numeric protected
Definition at line 1073 of file vanka.hpp.
watch_init_symbolic
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > StopWatch FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::watch_init_symbolic protected
Definition at line 1071 of file vanka.hpp.
The documentation for this class was generated from the following file:
kernel/solver/vanka.hpp