FEAT: FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ > Class Template Reference
FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ > Class Template Reference
Algebraic DOF Partitioned CSR matrix class template.
#include <alg_dof_parti.hpp>
Public Types
typedef Global::AlgDofParti< LocalVectorType, MirrorType > AlgDofPartiType
the algebraic DOF partitioning
typedef Global::AlgDofPartiVector< LocalVectorType, MirrorType > AlgDofPartiVectorType
the compatible alg-dof-parti vector type
typedef LAFEM::MatrixMirrorBuffer< DataType, IndexType > BufferMatrixType
the buffer matrix type used for communication
typedef LAFEM::DenseVector< DataType, IndexType > BufferVectorType
the buffer vector type used for communication
typedef LocalMatrix_::DataType DataType
our data type
typedef Global::Matrix< LocalMatrixType, MirrorType, MirrorType > GlobalMatrixType
the global matrix type
typedef LocalMatrix_::IndexType IndexType
our index type
typedef LocalMatrix_ LocalMatrixType
the local matrix type
typedef LocalMatrixType::VectorTypeR LocalVectorType
the local vector type
typedef Mirror_ MirrorType
the vector mirror type
typedef LAFEM::SparseMatrixCSR< DataType, IndexType > OwnedMatrixType
the matrix type used for the internal storage of our owned matrix rows
Public Member Functions
AlgDofPartiMatrix ()
default constructor
AlgDofPartiMatrix (const AlgDofPartiType *adp_in)
Creates a ADP matrix based on an algebraic dof partitioning.
void apply (AlgDofPartiVectorType &vec_r, const AlgDofPartiVectorType &vec_x) const
Performs a global matrix-vector product with this matrix.
void clear ()
Resets the whole object.
template<typename LocalFilter_ >
void filter_matrix (const Global::Filter< LocalFilter_, MirrorType > &filter)
Applies a global unit-filter into this matrix.
void filter_matrix (const LAFEM::UnitFilter< DataType, IndexType > &filter)
Applies a unit-filter into this matrix.
const AlgDofPartiType * get_alg_dof_parti () const
const Dist::Comm * get_comm () const
OwnedMatrixType & owned ()
const OwnedMatrixType & owned () const
void upload (const GlobalMatrixType &mat_a)
Initializes this algebraic dof-partitioned matrix from a global matrix.
void upload (const LocalMatrixType &mat_a)
Initializes this algebraic dof-partitioned matrix from a global matrix.
void upload_numeric (const GlobalMatrixType &mat_a)
Copies the matrix entry values from the input matrix into this algebraic-dof-partitioned matrix.
void upload_numeric (const LocalMatrixType &mat_a)
Copies the matrix entry values from the input matrix into this algebraic-dof-partitioned matrix.
void upload_symbolic (const GlobalMatrixType &mat_a)
Initializes this algebraic dof-partitioned matrix from a global matrix.
void upload_symbolic (const LocalMatrixType &mat_a)
Initializes this algebraic-dof-partitioned matrix from a local matrix.
Protected Member Functions
void _assemble_buffers (const LocalMatrixType &local_matrix)
Assembles the owner and donee matrix buffers.
void _assemble_data_mirrors (const LocalMatrixType &local_matrix)
Assembles the data-mirrors for all owner- and donee-neighbors.
void _assemble_structure (const LocalMatrixType &local_matrix)
Assembles the matrix structure of the algebraic-DOF-partitioned matrix.
void _upload_own (const LocalMatrixType &local_matrix)
Uploads the values of the local matrix into our matrix partition.
Static Protected Member Functions
static MirrorType _asm_donee_data_mir (const LocalMatrixType &local_matrix, const MirrorType &mirror, const BufferMatrixType &buffer)
Auxiliary function: assembles a data-mirror for a donee-neighbor.
static BufferMatrixType _asm_mat_buf (const LocalMatrixType &local_matrix, const MirrorType &mirror, const std::vector< IndexType > &gdi, const IndexType num_glob_dofs)
Auxiliary function: creates a matrix buffer for a given owner mirror.
static MirrorType _asm_owner_data_mir (const LocalMatrixType &local_matrix, const MirrorType &mirror, const BufferMatrixType &buffer, const std::vector< IndexType > &glob_dof_idx)
Auxiliary function: assembles a data-mirror for an owner-neighbor.
static void _gather_data (BufferVectorType &buffer, const LocalMatrixType &local_matrix, const MirrorType &data_mirror)
Gathers the values of a local matrix into an owner-neighbor buffer-vector.
static void _scatter_data (LocalMatrixType &local_matrix, const BufferVectorType &buffer, const MirrorType &data_mirror)
Scatters the values of a donee-neighbor buffer-vector into a local matrix.
Protected Attributes
const AlgDofPartiType * _alg_dof_parti
the algebraic dof-partitioning
std::vector< MirrorType > _data_donee_mirs
the data array mirrors for our donee and owner neighbors
std::vector< MirrorType > _data_owner_mirs
std::vector< BufferMatrixType > _donee_bufs
the matrix buffers for our donee and owner neighbors
OwnedMatrixType _matrix
the internal matrix storing our owned matrix rows
std::vector< std::pair< IndexType, IndexType > > _my_data_mir
the data array "mirror" for this process
std::vector< BufferMatrixType > _owner_bufs
Detailed Description
template<typename LocalMatrix_, typename Mirror_>
class FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >
Algebraic DOF Partitioned CSR matrix class template.
This class implements the management of a distributed CSR matrix based on an algebraic DOF partitioning. A matrix of this class will contain only the (full) rows corresponding to the owned DOFs of this process, where the column indices are global DOF indices.
In contrast to the AlgDofPartiVector, objects of this class need further initialization after the call of the constructor. This additional initialization is performed by uploading at least the layout of a given Global::Matrix. In analogy to the concept of our (linear) solvers, the "upload" process is split into two functions:
upload_symbolic(): creates all internal data structures and computes the internal matrix structure based on the given input matrix structure.
upload_numeric(): copies the numerical values of the input matrix into the owned matrix and performs the required communication.
Also in analogy to the solver concept, one may repeatedly call upload_numeric() with changing matrix values without the need to call upload_symbolic() every time, as long as the input matrix structure does not change. This can seriously reduce communication overhead in non-linear scenarios, where the matrix values change frequently.
Note that, in contrast to the AlgDofPartiVector class, this matrix class does not offer a "download" functionality.
Author
Peter Zajac
Definition at line 913 of file alg_dof_parti.hpp.
Member Typedef Documentation
AlgDofPartiType
template<typename LocalMatrix_ , typename Mirror_ > typedef Global::AlgDofParti<LocalVectorType, MirrorType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::AlgDofPartiType
the algebraic DOF partitioning
Definition at line 940 of file alg_dof_parti.hpp.
AlgDofPartiVectorType
template<typename LocalMatrix_ , typename Mirror_ > typedef Global::AlgDofPartiVector<LocalVectorType, MirrorType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::AlgDofPartiVectorType
the compatible alg-dof-parti vector type
Definition at line 942 of file alg_dof_parti.hpp.
BufferMatrixType
template<typename LocalMatrix_ , typename Mirror_ > typedef LAFEM::MatrixMirrorBuffer<DataType, IndexType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::BufferMatrixType
the buffer matrix type used for communication
Definition at line 934 of file alg_dof_parti.hpp.
BufferVectorType
template<typename LocalMatrix_ , typename Mirror_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::BufferVectorType
the buffer vector type used for communication
Definition at line 932 of file alg_dof_parti.hpp.
DataType
template<typename LocalMatrix_ , typename Mirror_ > typedef LocalMatrix_::DataType FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::DataType
our data type
Definition at line 917 of file alg_dof_parti.hpp.
GlobalMatrixType
template<typename LocalMatrix_ , typename Mirror_ > typedef Global::Matrix<LocalMatrixType, MirrorType, MirrorType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::GlobalMatrixType
the global matrix type
Definition at line 926 of file alg_dof_parti.hpp.
IndexType
template<typename LocalMatrix_ , typename Mirror_ > typedef LocalMatrix_::IndexType FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::IndexType
our index type
Definition at line 919 of file alg_dof_parti.hpp.
LocalMatrixType
template<typename LocalMatrix_ , typename Mirror_ > typedef LocalMatrix_ FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::LocalMatrixType
the local matrix type
Definition at line 922 of file alg_dof_parti.hpp.
LocalVectorType
template<typename LocalMatrix_ , typename Mirror_ > typedef LocalMatrixType::VectorTypeR FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::LocalVectorType
the local vector type
Definition at line 929 of file alg_dof_parti.hpp.
MirrorType
template<typename LocalMatrix_ , typename Mirror_ > typedef Mirror_ FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::MirrorType
the vector mirror type
Definition at line 924 of file alg_dof_parti.hpp.
OwnedMatrixType
template<typename LocalMatrix_ , typename Mirror_ > typedef LAFEM::SparseMatrixCSR<DataType, IndexType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::OwnedMatrixType
the matrix type used for the internal storage of our owned matrix rows
Definition at line 937 of file alg_dof_parti.hpp.
Constructor & Destructor Documentation
AlgDofPartiMatrix() [1/2]
template<typename LocalMatrix_ , typename Mirror_ > FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::AlgDofPartiMatrix () inline
default constructor
Definition at line 959 of file alg_dof_parti.hpp.
AlgDofPartiMatrix() [2/2]
template<typename LocalMatrix_ , typename Mirror_ > FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::AlgDofPartiMatrix (const AlgDofPartiType * adp_in) inline explicit
Creates a ADP matrix based on an algebraic dof partitioning.
Attention
In contrast to the AlgDofPartiVector class, this matrix class is not fully initialized after this constructor returns. It is at least required to set up the internal data structures by calling the upload_symbolic() or upload() function and passing an initialized matrix to it.
Parameters
[in] adp_in The algebraic dof partitioning to be used for this matrix.
Definition at line 977 of file alg_dof_parti.hpp.
Member Function Documentation
_asm_donee_data_mir()
template<typename LocalMatrix_ , typename Mirror_ > static MirrorType FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_asm_donee_data_mir (const LocalMatrixType & local_matrix, const MirrorType & mirror, const BufferMatrixType & buffer) inline static protected
Auxiliary function: assembles a data-mirror for a donee-neighbor.
Parameters
[in] local_matrix The local matrix that acts as a layout template.
Its layout must be initialized, but its numerical values are ignored.
[in] mirror The mirror of the donee-neighbor.
[in] buffer The matrix buffer for the donee-mirror.
Definition at line 1546 of file alg_dof_parti.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements().
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors().
_asm_mat_buf()
template<typename LocalMatrix_ , typename Mirror_ > static BufferMatrixType FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_asm_mat_buf (const LocalMatrixType & local_matrix, const MirrorType & mirror, const std::vector< IndexType > & gdi, const IndexType num_glob_dofs) inline static protected
Auxiliary function: creates a matrix buffer for a given owner mirror.
This function creates a matrix buffer for a given owner mirror, which contains all matrix rows that correspond to the owned DOF indices stored in the mirror. The column indices of the buffer correspond to global DOF indices.
Parameters
[in] local_matrix The local matrix that acts as a layout template.
Its layout must be initialized, but its numerical values are ignored.
[in] mirror The mirror that contains the local DOF indices, which correspond to the row indices of the local matrix which are to be extracted into the buffer.
[in] gdi An array containing the global DOF indices for all local DOFs.
[in] num_glob_dofs The total number of global DOFs over all processes.
Definition at line 1293 of file alg_dof_parti.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr().
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_buffers().
_asm_owner_data_mir()
template<typename LocalMatrix_ , typename Mirror_ > static MirrorType FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_asm_owner_data_mir (const LocalMatrixType & local_matrix, const MirrorType & mirror, const BufferMatrixType & buffer, const std::vector< IndexType > & glob_dof_idx) inline static protected
Auxiliary function: assembles a data-mirror for an owner-neighbor.
Parameters
[in] local_matrix The local matrix that acts as a layout template.
Its layout must be initialized, but its numerical values are ignored.
[in] mirror The mirror of the owner-neighbor.
[in] buffer The matrix buffer for the owner-mirror.
[in] glob_dof_idx A vector containing the global DOF indices for all local DOFs.
Definition at line 1604 of file alg_dof_parti.hpp.
References FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements().
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors().
_assemble_buffers()
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_buffers (const LocalMatrixType & local_matrix) inline protected
Assembles the owner and donee matrix buffers.
Parameters
[in] local_matrix The local matrix that acts as a layout template.
Its layout must be initialized, but its numerical values are ignored.
Definition at line 1340 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_asm_mat_buf(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_donee_bufs, FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::get_comm(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), and FEAT::Dist::RequestVector::wait_all().
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic().
_assemble_data_mirrors()
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors (const LocalMatrixType & local_matrix) inline protected
Assembles the data-mirrors for all owner- and donee-neighbors.
This functions assembles the data-mirrors, which are used for the communication of the numerical values of a matrix in the upload_numeric() function. This allows that the matrix values can be uploaded and synchronized without the need to re-communicate the unchanged matrix buffer layouts every time.
Parameters
[in] local_matrix The local matrix that acts as a layout template.
Its layout must be initialized, but its numerical values are ignored.
Definition at line 1659 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_asm_donee_data_mir(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_asm_owner_data_mir(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_my_data_mir, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and XASSERT.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic().
_assemble_structure()
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_structure (const LocalMatrixType & local_matrix) inline protected
Assembles the matrix structure of the algebraic-DOF-partitioned matrix.
Parameters
[in] local_matrix The local matrix that acts as a layout template.
Its layout must be initialized, but its numerical values are ignored.
Definition at line 1461 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_alg_dof_parti, FEAT::Adjacency::as_is, FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::Adjacency::DynamicGraph::insert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), and XASSERT.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic().
_gather_data()
template<typename LocalMatrix_ , typename Mirror_ > static void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data (BufferVectorType & buffer, const LocalMatrixType & local_matrix, const MirrorType & data_mirror) inline static protected
Gathers the values of a local matrix into an owner-neighbor buffer-vector.
Parameters
[out] buffer A buffer vector that receives the gathered values.
[in] local_matrix The local matrix whose values are to be gathered.
[in] data_mirror The owner-data mirror to be used.
Definition at line 1752 of file alg_dof_parti.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERT.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
_scatter_data()
template<typename LocalMatrix_ , typename Mirror_ > static void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data (LocalMatrixType & local_matrix, const BufferVectorType & buffer, const MirrorType & data_mirror) inline static protected
Scatters the values of a donee-neighbor buffer-vector into a local matrix.
Parameters
[in,out] local_matrix The local matrix that receives the scattered values.
[in] buffer The buffer vector whose values are to be scattered.
[in] data_mirror The donee-data mirror to be used.
Definition at line 1778 of file alg_dof_parti.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERT.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
_upload_own()
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_upload_own (const LocalMatrixType & local_matrix) inline protected
Uploads the values of the local matrix into our matrix partition.
Parameters
[in] local_matrix The local matrix whose values are to be uploaded.
Definition at line 1729 of file alg_dof_parti.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
apply()
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::apply (AlgDofPartiVectorType & vec_r, const AlgDofPartiVectorType & vec_x) const inline
Performs a global matrix-vector product with this matrix.
Attention
As convenient and tempting as this function may look, please be aware that using this function will completely destroy the scalability of our code when running on a large number of processes. In addition to the scalability issues, please be aware that this function may cause a fatal out-of-memory event, as the underlying (naive) implementation gathers the full multiplicand vector on all processes using the AlgDofPartiVector::allgather() function.
Do not use this function except for small-scale debugging purposes. You have been warned.
Parameters
[out] vec_r A reference to the algebraic-dof-partitioned vector that receives the result of the matrix-vector product.
[in] vec_x A const reference to the algebraic-dof-partitioned vector that acts as a multiplicand vector.
Definition at line 1040 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::owned(), and XASSERTM.
clear()
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear () inline
Resets the whole object.
Definition at line 984 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_data_donee_mirs, FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_donee_bufs, FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_matrix, FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_my_data_mir, and FEAT::LAFEM::Container< DT_, IT_ >::clear().
filter_matrix() [1/2]
template<typename LocalMatrix_ , typename Mirror_ > template<typename LocalFilter_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix (const Global::Filter< LocalFilter_, MirrorType > & filter) inline
Applies a global unit-filter into this matrix.
Attention
You must use this function to filter the internal partitioned matrix. You cannot use the filter_mat() function of the unit-filter here, because the indices of the unit-filter relate to local DOF indices, whereas our internal matrix object works in owned DOF indices.
Parameters
[in] filter The unit-filter that is to be applied onto the matrix. May be empty.
Definition at line 1213 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix().
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix(), and FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_numeric().
filter_matrix() [2/2]
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix (const LAFEM::UnitFilter< DataType, IndexType > & filter) inline
Applies a unit-filter into this matrix.
Attention
You must use this function to filter the internal partitioned matrix. You cannot use the filter_mat() function of the unit-filter here, because the indices of the unit-filter relate to local DOF indices, whereas our internal matrix object works in owned DOF indices.
Parameters
[in] filter The unit-filter that is to be applied onto the matrix. May be empty.
Definition at line 1230 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_alg_dof_parti, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
get_alg_dof_parti()
template<typename LocalMatrix_ , typename Mirror_ > const AlgDofPartiType * FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::get_alg_dof_parti () const inline
Returns
A pointer to the underlying algebraic dof partitioning object.
Definition at line 1008 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_alg_dof_parti.
get_comm()
template<typename LocalMatrix_ , typename Mirror_ > const Dist::Comm * FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::get_comm () const inline
Returns
A pointer to the underlying communicator.
Definition at line 1014 of file alg_dof_parti.hpp.
References XASSERT.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_buffers(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
owned() [1/2]
template<typename LocalMatrix_ , typename Mirror_ > OwnedMatrixType & FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::owned () inline
Returns
A reference to the internal owned matrix object.
Definition at line 996 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_matrix.
Referenced by FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic().
owned() [2/2]
template<typename LocalMatrix_ , typename Mirror_ > const OwnedMatrixType & FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::owned () const inline
Returns
A reference to the internal owned matrix object.
Definition at line 1002 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_matrix.
upload() [1/2]
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload (const GlobalMatrixType & mat_a) inline
Initializes this algebraic dof-partitioned matrix from a global matrix.
Parameters
[in] mat_a The global matrix whose layout and values are to be used to initialize this matrix.
Definition at line 1061 of file alg_dof_parti.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload().
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload().
upload() [2/2]
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload (const LocalMatrixType & mat_a) inline
Initializes this algebraic dof-partitioned matrix from a global matrix.
Parameters
[in] mat_a The global matrix whose layout and values are to be used to initialize this matrix.
Definition at line 1072 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic().
upload_numeric() [1/2]
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric (const GlobalMatrixType & mat_a) inline
Copies the matrix entry values from the input matrix into this algebraic-dof-partitioned matrix.
Parameters
[in] mat_a The input matrix whose entry values are to be copied.
Attention
The input matrix is assumed to be an unfiltered type-0 matrix.
Definition at line 1125 of file alg_dof_parti.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
Referenced by FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_numeric(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
upload_numeric() [2/2]
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric (const LocalMatrixType & mat_a) inline
Copies the matrix entry values from the input matrix into this algebraic-dof-partitioned matrix.
Parameters
[in] mat_a The input matrix whose entry values are to be copied.
Attention
The input matrix is assumed to be an unfiltered type-0 matrix.
Definition at line 1139 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_alg_dof_parti, FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_upload_own(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::get_comm(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERT.
upload_symbolic() [1/2]
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic (const GlobalMatrixType & mat_a) inline
Initializes this algebraic dof-partitioned matrix from a global matrix.
This function performs the "symbolic" initialization of this algebraic-dof-partitioned matrix based on the layout of the given input matrix. After the call of ths function, this matrix object is fully initialized, although the actual numerical values of the matrix entries are still undefined and have to be copied from the global input matrix lateron by using the upload_numeric() function.
Parameters
[in] mat_a The global matrix whose layout is to be used to initialize this matrix.
Definition at line 1090 of file alg_dof_parti.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic().
Referenced by FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic().
upload_symbolic() [2/2]
template<typename LocalMatrix_ , typename Mirror_ > void FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_symbolic (const LocalMatrixType & mat_a) inline
Initializes this algebraic-dof-partitioned matrix from a local matrix.
This function performs the "symbolic" initialization of this algebraic-dof-partitioned matrix based on the layout of the given input matrix. After the call of this function, this matrix object is fully initialized, although the actual numerical values of the matrix entries are still undefined and have to be copied from the local input matrix later on by using the upload_numeric() function.
Parameters
[in] mat_a The local matrix whose layout is to be used to initialize this matrix.
Definition at line 1107 of file alg_dof_parti.hpp.
References FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_buffers(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_structure(), and XASSERT.
Member Data Documentation
_alg_dof_parti
template<typename LocalMatrix_ , typename Mirror_ > const AlgDofPartiType* FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_alg_dof_parti protected
the algebraic dof-partitioning
Definition at line 946 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_buffers(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_structure(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::get_alg_dof_parti(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
_data_donee_mirs
template<typename LocalMatrix_ , typename Mirror_ > std::vector<MirrorType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_data_donee_mirs protected
the data array mirrors for our donee and owner neighbors
Definition at line 953 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear().
_data_owner_mirs
template<typename LocalMatrix_ , typename Mirror_ > std::vector<MirrorType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_data_owner_mirs protected
Definition at line 953 of file alg_dof_parti.hpp.
_donee_bufs
template<typename LocalMatrix_ , typename Mirror_ > std::vector<BufferMatrixType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_donee_bufs protected
the matrix buffers for our donee and owner neighbors
Definition at line 951 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_buffers(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear().
_matrix
template<typename LocalMatrix_ , typename Mirror_ > OwnedMatrixType FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_matrix protected
the internal matrix storing our owned matrix rows
Definition at line 948 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::owned().
_my_data_mir
template<typename LocalMatrix_ , typename Mirror_ > std::vector<std::pair<IndexType,IndexType> > FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_my_data_mir protected
the data array "mirror" for this process
Definition at line 955 of file alg_dof_parti.hpp.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear().
_owner_bufs
template<typename LocalMatrix_ , typename Mirror_ > std::vector<BufferMatrixType> FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_owner_bufs protected
Definition at line 951 of file alg_dof_parti.hpp.
The documentation for this class was generated from the following file:
kernel/global/alg_dof_parti.hpp