FEAT: FEAT::Solver::CuSolverQR Class Reference
FEAT::Solver::CuSolverQR Class Reference
CuSolverQR solver class.
#include <cusolver.hpp>
Public Types
typedef LAFEM::DenseVector< double, unsigned int > VectorType
The type of vector this solver can be applied to.
Public Member Functions
CuSolverQR (const LAFEM::SparseMatrixCSR< double, unsigned int > &system_matrix)
Constructor.
virtual Status apply (LAFEM::DenseVector< double, unsigned int > &x, const LAFEM::DenseVector< double, unsigned int > &b) override
Solver application method.
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic ()
Symbolic finalization method.
virtual void init ()
Initialization method.
virtual void init_numeric ()
Numeric initialization method.
virtual void init_symbolic ()
Symbolic initialization method.
virtual String name () const override
Returns the name of the solver.
Private Attributes
const LAFEM::SparseMatrixCSR< double, unsigned int > & _system_matrix
system matrix
Detailed Description
CuSolverQR solver class.
This class provides an implementation of the SolverBase interface using the direct cuda solver cusolverSpDcsrlsvqr for doing the actual dirty work.
Attention
This class is only declared if FEAT was configured to build and link against cuda and the cuda sdk ships with the cusolver library (cuda version >= 7).
Definition at line 91 of file cusolver.hpp.
Member Typedef Documentation
VectorType
typedef LAFEM::DenseVector< double, unsigned int > FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >::VectorType inherited
The type of vector this solver can be applied to.
Definition at line 188 of file base.hpp.
Constructor & Destructor Documentation
CuSolverQR()
FEAT::Solver::CuSolverQR::CuSolverQR (const LAFEM::SparseMatrixCSR< double, unsigned int > & system_matrix) inline explicit
Constructor.
Parameters
[in] system_matrix A reference to the system matrix to be factorized.
Definition at line 104 of file cusolver.hpp.
Member Function Documentation
apply()
virtual Status FEAT::Solver::CuSolverQR::apply (LAFEM::DenseVector< double, unsigned int > & vec_cor, const LAFEM::DenseVector< double, unsigned int > & vec_def) inline override virtual
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implements FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >.
Definition at line 115 of file cusolver.hpp.
References _system_matrix, FEAT::Solver::aborted, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::Solver::success, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
done()
virtual void FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 285 of file base.hpp.
done_numeric()
virtual void FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Definition at line 248 of file base.hpp.
done_symbolic()
virtual void FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >::done_symbolic () inline virtual inherited
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Definition at line 257 of file base.hpp.
init()
virtual void FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 270 of file base.hpp.
init_numeric()
virtual void FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >::init_numeric () inline virtual inherited
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Definition at line 239 of file base.hpp.
init_symbolic()
virtual void FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >::init_symbolic () inline virtual inherited
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Definition at line 229 of file base.hpp.
name()
virtual String FEAT::Solver::CuSolverQR::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SolverBase< LAFEM::DenseVector< double, unsigned int > >.
Definition at line 110 of file cusolver.hpp.
Member Data Documentation
_system_matrix
const LAFEM::SparseMatrixCSR<double, unsigned int>& FEAT::Solver::CuSolverQR::_system_matrix private
system matrix
Definition at line 96 of file cusolver.hpp.
Referenced by apply().
The documentation for this class was generated from the following file:
kernel/solver/cusolver.hpp