FEAT: FEAT::Geometry::IndexSet< num_indices_ > Class Template Reference
FEAT::Geometry::IndexSet< num_indices_ > Class Template Reference
Conformal Index-Set class template.
#include <index_set.hpp>
Public Types
typedef const Index * ImageIterator
ImageIterator type for Adjactor interface implementation.
typedef IndexTuple< num_indices > IndexTupleType
index tuple type
Public Member Functions
IndexSet (Index num_entities=0, Index index_bound=0)
Constructor.
IndexSet (IndexSet &&other)
move constructor
virtual ~IndexSet ()
virtual destructor
std::size_t bytes () const
IndexSet clone () const
Index get_index_bound () const
Returns the index bound.
IndexTupleType * get_indices ()
Returns the index vector array.
const IndexTupleType * get_indices () const
Returns the index vector array.
Index get_num_entities () const
Returns the number of entities.
int get_num_indices () const
Returns the number of indices per entity.
Index get_num_nodes_domain () const
Returns the number of domain nodes.
Index get_num_nodes_image () const
Returns the number of image nodes.
ImageIterator image_begin (Index domain_node) const
Returns an iterator for the first adjacent image node.
ImageIterator image_end (Index domain_node) const
Returns an iterator for the first position past the last adjacent image node.
Index & operator() (Index i, int j)
Maps a face index.
const Index & operator() (Index i, int j) const
Maps a face index.
IndexSet & operator= (IndexSet &&other)
move-assignment operator
IndexTupleType & operator[] (Index i)
Returns a reference to an index tuple.
const IndexTupleType & operator[] (Index i) const
Returns a reference to an index tuple.
void permute (const Adjacency::Permutation &perm, const Adjacency::Permutation &inv_perm_face)
Permutes this index set in-situ.
void set_index_bound (Index bound)
Sets the index bound.
Static Public Member Functions
static String name ()
Returns the name of the class.
Static Public Attributes
static constexpr int num_indices = num_indices_
number of indices per entry
Protected Member Functions
IndexSet (Index idx_bnd, const std::vector< IndexTupleType > &idx)
internal clone constructor
Protected Attributes
Index _index_bound
std::vector< IndexTupleType > _indices
index vector array
Detailed Description
template<int num_indices_>
class FEAT::Geometry::IndexSet< num_indices_ >
Conformal Index-Set class template.
This is used for storing information about i.e. which vertices are present in each
edge
face
cell
and similar types of information, like edges@faces, edges@cells, faces@cells, depending on the dimension.
Author
Peter Zajac
Definition at line 83 of file index_set.hpp.
Member Typedef Documentation
ImageIterator
template<int num_indices_> typedef const Index* FEAT::Geometry::IndexSet< num_indices_ >::ImageIterator
ImageIterator type for Adjactor interface implementation.
Definition at line 95 of file index_set.hpp.
IndexTupleType
template<int num_indices_> typedef IndexTuple<num_indices> FEAT::Geometry::IndexSet< num_indices_ >::IndexTupleType
index tuple type
Definition at line 92 of file index_set.hpp.
Constructor & Destructor Documentation
IndexSet() [1/3]
template<int num_indices_> FEAT::Geometry::IndexSet< num_indices_ >::IndexSet (Index idx_bnd, const std::vector< IndexTupleType > & idx) inline explicit protected
internal clone constructor
Definition at line 106 of file index_set.hpp.
IndexSet() [2/3]
template<int num_indices_> FEAT::Geometry::IndexSet< num_indices_ >::IndexSet (Index num_entities = 0, Index index_bound = 0) inline explicit
Constructor.
Parameters
[in] num_entities The number of entities for the index set.
[in] index_bound The index bound.
Definition at line 121 of file index_set.hpp.
IndexSet() [3/3]
template<int num_indices_> FEAT::Geometry::IndexSet< num_indices_ >::IndexSet (IndexSet< num_indices_ > && other) inline
move constructor
Definition at line 131 of file index_set.hpp.
~IndexSet()
template<int num_indices_> virtual FEAT::Geometry::IndexSet< num_indices_ >::~IndexSet () inline virtual
virtual destructor
Definition at line 151 of file index_set.hpp.
Member Function Documentation
bytes()
template<int num_indices_> std::size_t FEAT::Geometry::IndexSet< num_indices_ >::bytes () const inline
Returns
The size of dynamically allocated memory in bytes.
Definition at line 162 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices.
clone()
template<int num_indices_> IndexSet FEAT::Geometry::IndexSet< num_indices_ >::clone () const inline
Returns
An independent clone of this target set object.
Definition at line 156 of file index_set.hpp.
get_index_bound()
template<int num_indices_> Index FEAT::Geometry::IndexSet< num_indices_ >::get_index_bound () const inline
Returns the index bound.
Returns
The index bound.
Definition at line 192 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_index_bound.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_mask(), FEAT::Geometry::StructIndexSet< shape_dim_, cell_dim_, face_dim_ >::copy_to(), and FEAT::Geometry::IndexSet< num_indices_ >::permute().
get_indices() [1/2]
template<int num_indices_> IndexTupleType * FEAT::Geometry::IndexSet< num_indices_ >::get_indices () inline
Returns the index vector array.
Returns
The index vector array.
Definition at line 202 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices.
get_indices() [2/2]
template<int num_indices_> const IndexTupleType * FEAT::Geometry::IndexSet< num_indices_ >::get_indices () const inline
Returns the index vector array.
Returns
The index vector array.
Definition at line 208 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices.
get_num_entities()
template<int num_indices_> Index FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities () const inline
Returns the number of entities.
Returns
The number of entities;
Definition at line 182 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_mask(), FEAT::Geometry::StructIndexSet< shape_dim_, cell_dim_, face_dim_ >::copy_to(), FEAT::Geometry::IndexSet< num_indices_ >::get_num_nodes_domain(), FEAT::Geometry::IndexSet< num_indices_ >::image_begin(), FEAT::Geometry::IndexSet< num_indices_ >::image_end(), FEAT::Geometry::IndexSet< num_indices_ >::operator()(), FEAT::Geometry::IndexSet< num_indices_ >::operator[](), and FEAT::Geometry::IndexSet< num_indices_ >::permute().
get_num_indices()
template<int num_indices_> int FEAT::Geometry::IndexSet< num_indices_ >::get_num_indices () const inline
Returns the number of indices per entity.
Returns
The number of indices per entity.
Definition at line 172 of file index_set.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_mask().
get_num_nodes_domain()
template<int num_indices_> Index FEAT::Geometry::IndexSet< num_indices_ >::get_num_nodes_domain () const inline
Returns the number of domain nodes.
Returns
The total number of domain nodes in the adjactor.
Definition at line 330 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities().
get_num_nodes_image()
template<int num_indices_> Index FEAT::Geometry::IndexSet< num_indices_ >::get_num_nodes_image () const inline
Returns the number of image nodes.
Returns
The total number of image nodes in the adjactor.
Definition at line 336 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_index_bound.
image_begin()
template<int num_indices_> ImageIterator FEAT::Geometry::IndexSet< num_indices_ >::image_begin (Index domain_node) const inline
Returns an iterator for the first adjacent image node.
Parameters
[in] domain_node The index of the domain node whose image node iterator is to be returned.
Returns
An iterator representing the first image node adjacent to domain_node, or image_end(domain_node) if no adjacent image nodes exist.
Definition at line 342 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices, ASSERT, and FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities().
image_end()
template<int num_indices_> ImageIterator FEAT::Geometry::IndexSet< num_indices_ >::image_end (Index domain_node) const inline
Returns an iterator for the first position past the last adjacent image node.
Parameters
[in] domain_node The index of the domain node whose image node iterator is to be returned.
Returns
An iterator representing the first position past the last image node adjacent to domain_node.
Definition at line 349 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices, ASSERT, and FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities().
name()
template<int num_indices_> static String FEAT::Geometry::IndexSet< num_indices_ >::name () inline static
Returns the name of the class.
Returns
The name of the class as a String.
Definition at line 321 of file index_set.hpp.
References FEAT::stringify().
operator()() [1/2]
template<int num_indices_> Index & FEAT::Geometry::IndexSet< num_indices_ >::operator() (Index i, int j) inline
Maps a face index.
Parameters
[in] i The index of the entity whose face index is to be returned.
[in] j The index of the local face that is to be mapped.
Returns
A (const) reference to the index of the local face j on entity i.
Definition at line 247 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices, ASSERT, FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities(), and FEAT::Geometry::IndexSet< num_indices_ >::num_indices.
operator()() [2/2]
template<int num_indices_> const Index & FEAT::Geometry::IndexSet< num_indices_ >::operator() (Index i, int j) const inline
Maps a face index.
Parameters
[in] i The index of the entity whose face index is to be returned.
[in] j The index of the local face that is to be mapped.
Returns
A (const) reference to the index of the local face j on entity i.
Definition at line 267 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices, ASSERT, FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities(), and FEAT::Geometry::IndexSet< num_indices_ >::num_indices.
operator=()
template<int num_indices_> IndexSet & FEAT::Geometry::IndexSet< num_indices_ >::operator= (IndexSet< num_indices_ > && other) inline
move-assignment operator
Definition at line 138 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_index_bound, FEAT::Geometry::IndexSet< num_indices_ >::_indices, and FEAT::Geometry::other.
operator[]() [1/2]
template<int num_indices_> IndexTupleType & FEAT::Geometry::IndexSet< num_indices_ >::operator[] (Index i) inline
Returns a reference to an index tuple.
Parameters
[in] i The index of the entity whose index tuple is to be returned.
Returns
A (const) reference to the index tuple of the entity.
Definition at line 222 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices, ASSERT, and FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities().
operator[]() [2/2]
template<int num_indices_> const IndexTupleType & FEAT::Geometry::IndexSet< num_indices_ >::operator[] (Index i) const inline
Returns a reference to an index tuple.
Parameters
[in] i The index of the entity whose index tuple is to be returned.
Returns
A (const) reference to the index tuple of the entity.
Definition at line 229 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices, ASSERT, and FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities().
permute()
template<int num_indices_> void FEAT::Geometry::IndexSet< num_indices_ >::permute (const Adjacency::Permutation & perm, const Adjacency::Permutation & inv_perm_face) inline
Permutes this index set in-situ.
\perm[in] perm A transient reference to the permutation of the shape indices.
Parameters
[in] inv_perm_face A transient reference to the inverse permutation of the face indices.
Definition at line 294 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_indices, FEAT::Adjacency::Permutation::apply(), FEAT::Adjacency::Permutation::empty(), FEAT::Geometry::IndexSet< num_indices_ >::get_index_bound(), FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities(), FEAT::Adjacency::Permutation::size(), and XASSERT.
set_index_bound()
template<int num_indices_> void FEAT::Geometry::IndexSet< num_indices_ >::set_index_bound (Index bound) inline
Sets the index bound.
Parameters
[in] bound The new index bound.
Definition at line 280 of file index_set.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::_index_bound.
Member Data Documentation
_index_bound
template<int num_indices_> Index FEAT::Geometry::IndexSet< num_indices_ >::_index_bound protected
index bound;, i.e. number of edges if the IndexSet is to hold the information edges@cells. Necessary for Adjactor implementation
Definition at line 100 of file index_set.hpp.
Referenced by FEAT::Geometry::IndexSet< num_indices_ >::get_index_bound(), FEAT::Geometry::IndexSet< num_indices_ >::get_num_nodes_image(), FEAT::Geometry::IndexSet< num_indices_ >::operator=(), and FEAT::Geometry::IndexSet< num_indices_ >::set_index_bound().
_indices
template<int num_indices_> std::vector<IndexTupleType> FEAT::Geometry::IndexSet< num_indices_ >::_indices protected
index vector array
Definition at line 103 of file index_set.hpp.
Referenced by FEAT::Geometry::IndexSet< num_indices_ >::bytes(), FEAT::Geometry::IndexSet< num_indices_ >::get_indices(), FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities(), FEAT::Geometry::IndexSet< num_indices_ >::image_begin(), FEAT::Geometry::IndexSet< num_indices_ >::image_end(), FEAT::Geometry::IndexSet< num_indices_ >::operator()(), FEAT::Geometry::IndexSet< num_indices_ >::operator=(), FEAT::Geometry::IndexSet< num_indices_ >::operator[](), and FEAT::Geometry::IndexSet< num_indices_ >::permute().
num_indices
template<int num_indices_> constexpr int FEAT::Geometry::IndexSet< num_indices_ >::num_indices = num_indices_ static constexpr
number of indices per entry
Definition at line 89 of file index_set.hpp.
Referenced by FEAT::Geometry::PartiParMETIS::_compute_midpoints(), and FEAT::Geometry::IndexSet< num_indices_ >::operator()().
The documentation for this class was generated from the following file:
kernel/geometry/index_set.hpp