FEAT: FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ > Class Template Reference
FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ > Class Template Reference abstract
SOR preconditioner internal implementation.
#include <sor_precond.hpp>
Public Types
typedef DT_ DataType
typedef Filter_ FilterType
typedef IT_ IndexType
typedef LAFEM::SparseMatrixCSR< DT_, IT_ > MatrixType
typedef MatrixType::VectorTypeL VectorType
Public Member Functions
SORPrecondWithBackend (const MatrixType &matrix, const FilterType &filter, const DataType omega=DataType(1))
Constructor.
SORPrecondWithBackend (const String &section_name, PropertyMap *section, const MatrixType &matrix, const FilterType &filter)
Constructor using a PropertyMap.
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def) override
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def)=0
virtual void done_symbolic () override
virtual void init_symbolic () override
virtual String name () const override
Returns the name of the solver.
virtual void set_omega (DataType omega) override
Sets the damping parameter.
virtual void set_omega (DataType omega)=0
Protected Member Functions
void _apply_intern (const LAFEM::SparseMatrixCSR< DataType, IndexType > &matrix, VectorType &vec_cor, const VectorType &vec_def)
Protected Attributes
const FilterType & _filter
const MatrixType & _matrix
DataType _omega
Detailed Description
template<typename Filter_, typename DT_, typename IT_>
class FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >
SOR preconditioner internal implementation.
This class implements a simple SOR preconditioner, e.g. zero fill-in and no pivoting.
This implementation works for the following matrix types and combinations thereof:
LAFEM::SparseMatrixCSR
LAFEM::SparseMatrixBCSR
Author
Dirk Ribbrock
Definition at line 80 of file sor_precond.hpp.
Member Typedef Documentation
DataType
template<typename Filter_ , typename DT_ , typename IT_ > typedef DT_ FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::DataType
Definition at line 85 of file sor_precond.hpp.
FilterType
template<typename Filter_ , typename DT_ , typename IT_ > typedef Filter_ FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::FilterType
Definition at line 87 of file sor_precond.hpp.
IndexType
template<typename Filter_ , typename DT_ , typename IT_ > typedef IT_ FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::IndexType
Definition at line 86 of file sor_precond.hpp.
MatrixType
template<typename Filter_ , typename DT_ , typename IT_ > typedef LAFEM::SparseMatrixCSR<DT_, IT_> FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::MatrixType
Definition at line 84 of file sor_precond.hpp.
VectorType
template<typename Filter_ , typename DT_ , typename IT_ > typedef MatrixType::VectorTypeL FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::VectorType
Definition at line 88 of file sor_precond.hpp.
Constructor & Destructor Documentation
SORPrecondWithBackend() [1/2]
template<typename Filter_ , typename DT_ , typename IT_ > FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::SORPrecondWithBackend (const MatrixType & matrix, const FilterType & filter, const DataType omega = DataType(1)) inline explicit
Constructor.
Parameters
[in] matrix The matrix to be used.
[in] filter The filter to be used for the correction vector.
[in] omega Damping
Definition at line 109 of file sor_precond.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and XABORTM.
SORPrecondWithBackend() [2/2]
template<typename Filter_ , typename DT_ , typename IT_ > FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::SORPrecondWithBackend (const String & section_name, PropertyMap * section, const MatrixType & matrix, const FilterType & filter) inline explicit
Constructor using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Definition at line 136 of file sor_precond.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::PropertyMap::query(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and XABORTM.
Member Function Documentation
_apply_intern()
template<typename Filter_ , typename DT_ , typename IT_ > void FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::_apply_intern (const LAFEM::SparseMatrixCSR< DataType, IndexType > & matrix, VectorType & vec_cor, const VectorType & vec_def) inline protected
Definition at line 201 of file sor_precond.hpp.
apply()
template<typename Filter_ , typename DT_ , typename IT_ > virtual Status FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply (VectorType & vec_cor, const VectorType & vec_def) inline override virtual
Definition at line 179 of file sor_precond.hpp.
done_symbolic()
template<typename Filter_ , typename DT_ , typename IT_ > virtual void FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::done_symbolic () inline override virtual
Implements FEAT::Solver::SORPrecondBase< LAFEM::SparseMatrixCSR< DT_, IT_ > >.
Definition at line 175 of file sor_precond.hpp.
init_symbolic()
template<typename Filter_ , typename DT_ , typename IT_ > virtual void FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::init_symbolic () inline override virtual
Implements FEAT::Solver::SORPrecondBase< LAFEM::SparseMatrixCSR< DT_, IT_ > >.
Definition at line 171 of file sor_precond.hpp.
name()
template<typename Filter_ , typename DT_ , typename IT_ > virtual String FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SORPrecondBase< LAFEM::SparseMatrixCSR< DT_, IT_ > >.
Definition at line 153 of file sor_precond.hpp.
set_omega()
template<typename Filter_ , typename DT_ , typename IT_ > virtual void FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::set_omega (DataType omega) inline override virtual
Sets the damping parameter.
Parameters
[in] omega The new damping parameter.
Definition at line 165 of file sor_precond.hpp.
References XASSERT.
Member Data Documentation
_filter
template<typename Filter_ , typename DT_ , typename IT_ > const FilterType& FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::_filter protected
Definition at line 92 of file sor_precond.hpp.
_matrix
template<typename Filter_ , typename DT_ , typename IT_ > const MatrixType& FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::_matrix protected
Definition at line 91 of file sor_precond.hpp.
_omega
template<typename Filter_ , typename DT_ , typename IT_ > DataType FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::_omega protected
Definition at line 93 of file sor_precond.hpp.
The documentation for this class was generated from the following file:
kernel/solver/sor_precond.hpp