FEAT: FEAT::Assembly::StokesFBMAssembler< MeshType_ > Class Template Reference
FEAT::Assembly::StokesFBMAssembler< MeshType_ > Class Template Reference
Stokes Fictitious Boundary Method assembler class.
#include <stokes_fbm_assembler.hpp>
Public Types
typedef MeshType_ MeshType
our mesh type
Public Member Functions
StokesFBMAssembler (const MeshType &mesh_)
Constructor.
StokesFBMAssembler (const StokesFBMAssembler &)=delete
StokesFBMAssembler (StokesFBMAssembler &&)=delete
virtual ~StokesFBMAssembler ()
virtual destructor
void add_fbm_meshpart (const Geometry::MeshPart< MeshType > &fbm_part)
Adds a FBM mesh-part to the assembler.
template<typename DT_ , typename IT_ , typename Space_ >
void assemble_characteristic_vector (LAFEM::DenseVector< DT_, IT_ > &vector, const Space_ &space, const DT_ val_outside=DT_(0), const DT_ val_inside=DT_(1), const DT_ val_intface=DT_(1)) const
Assembles a characteristic vector on the FBM region.
template<typename DT_ , typename IT_ , typename Space_ >
void assemble_inside_filter (LAFEM::UnitFilter< DT_, IT_ > &filter, const Space_ &space) const
Assembles a UnitFilter inside the FBM region.
template<typename DT_ , typename IT_ , typename Space_ , int dim_>
void assemble_inside_filter (LAFEM::UnitFilterBlocked< DT_, IT_, dim_ > &filter, const Space_ &space) const
Assembles a UnitFilterBlocked inside the FBM region.
template<typename DT_ , typename IT_ , typename Space_ , typename Mirror_ >
void assemble_interface_filter (LAFEM::UnitFilter< DT_, IT_ > &filter, const Space_ &space, const Global::Matrix< LAFEM::SparseMatrixCSR< DT_, IT_ >, Mirror_, Mirror_ > &matrix_a, const Global::Matrix< LAFEM::SparseMatrixCSR< DT_, IT_ >, Mirror_, Mirror_ > &matrix_m) const
Assembles a UnitFilter on the FBM interface (parallel version)
template<typename DT_ , typename IT_ , typename Space_ >
void assemble_interface_filter (LAFEM::UnitFilter< DT_, IT_ > &filter, const Space_ &space, const LAFEM::SparseMatrixCSR< DT_, IT_ > &matrix_a, const LAFEM::SparseMatrixCSR< DT_, IT_ > &matrix_m) const
Assembles a UnitFilter on the FBM interface (non-parallel version)
template<typename DT_ , typename IT_ , typename Space_ , typename Mirror_ , int bh_, int bw_>
void assemble_interface_filter (LAFEM::UnitFilterBlocked< DT_, IT_, bh_ > &filter, const Space_ &space, const Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, bh_, bw_ >, Mirror_, Mirror_ > &matrix_a, const Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, bh_, bw_ >, Mirror_, Mirror_ > &matrix_m) const
Assembles a UnitFilterBlocked on the FBM interface (parallel version)
template<typename DT_ , typename IT_ , typename Space_ , int bh_, int bw_>
void assemble_interface_filter (LAFEM::UnitFilterBlocked< DT_, IT_, bh_ > &filter, const Space_ &space, const LAFEM::SparseMatrixBCSR< DT_, IT_, bh_, bw_ > &matrix_a, const LAFEM::SparseMatrixBCSR< DT_, IT_, bh_, bw_ > &matrix_m) const
Assembles a UnitFilterBlocked on the FBM interface (non-parallel version)
void clear ()
Clears the assembler.
void compile ()
Compiles the assembler.
const std::vector< int > & get_fbm_mask_vector (int dim) const
Returns a reference to an internal FBM mask vector.
const Geometry::MeshPart< MeshType > & get_meshpart_inside () const
Returns a reference to the mesh-part representing the FBM inside region.
const Geometry::MeshPart< MeshType > & get_meshpart_interface () const
Returns a reference to the mesh-part representing the FBM interface.
const Assembly::UnitFilterAssembler< MeshType > & get_unit_asm_inside () const
Returns a reference to the internal unit-filter assembler inside the FBM region.
const Assembly::UnitFilterAssembler< MeshType > & get_unit_asm_interface () const
Returns a reference to the internal unit-filter assembler on the FBM interface.
StokesFBMAssembler & operator= (const StokesFBMAssembler &)=delete
StokesFBMAssembler & operator= (StokesFBMAssembler &&)=delete
void sync (const Geometry::RootMeshNode< MeshType > &mesh_node, const Dist::Comm &comm)
Synchronizes the assembler over all processes in a parallel simulation.
Static Public Attributes
static constexpr int shape_dim = MeshType::shape_dim
our shape dimension
Protected Member Functions
void _add_fbm_target_set (const Geometry::TargetSet &target_set, int dim)
auxiliary function: add a target set to the FBM mask vector
void _build_tbm_target_set (Geometry::TargetSet &target_set, int dim, int mask_value)
auxiliary function: build target set from mask vector
Static Protected Member Functions
static const Geometry::TargetSet & _get_target_set (const Geometry::TargetSetHolder< Shape::Vertex > &tsh, int dim)
auxiliary function: get a target set from a target set holder (recursion end overload)
template<typename Shape_ >
static const Geometry::TargetSet & _get_target_set (const Geometry::TargetSetHolder< Shape_ > &tsh, int dim)
auxiliary function: get a target set from a target set holder
static Geometry::TargetSet & _get_target_set (Geometry::TargetSetHolder< Shape::Vertex > &tsh, int dim)
auxiliary function: get a target set from a target set holder (recursion end overload)
template<typename Shape_ >
static Geometry::TargetSet & _get_target_set (Geometry::TargetSetHolder< Shape_ > &tsh, int dim)
auxiliary function: get a target set from a target set holder
template<int m_>
static void _process_mask (std::vector< int > &shape_mask, const std::vector< int > &face_mask, const Geometry::IndexSet< m_ > &faces_at_shape)
Auxiliary function: update bit 1 of the mask vector for a shape based on a bit 0 of its face mask vector.
template<typename Shape_ , std::size_t n_>
static void _process_masks (std::array< std::vector< int >, n_ > &masks, const Geometry::IndexSetWrapper< Shape_, 0 > &idx_wrapper)
auxiliary function: process masks for all face dimensions for a given shape (recursion end)
template<typename Shape_ , int face_dim_, std::size_t n_>
static void _process_masks (std::array< std::vector< int >, n_ > &masks, const Geometry::IndexSetWrapper< Shape_, face_dim_ > &idx_wrapper)
auxiliary function: process masks for all face dimensions for a given shape
template<std::size_t n_>
static void _process_shapes (std::array< std::vector< int >, n_ > &, const Geometry::IndexSetHolder< Shape::Vertex > &)
auxiliary function: process masks shape dimensions (recursion end)
template<typename Shape_ , std::size_t n_>
static void _process_shapes (std::array< std::vector< int >, n_ > &masks, const Geometry::IndexSetHolder< Shape_ > &idx_holder)
auxiliary function: process masks shape dimensions
Protected Attributes
bool _compiled
already compiled?
std::array< std::vector< int >, shape_dim+1 > _fbm_masks
Array of FBM mask vectors.
std::unique_ptr< Geometry::MeshPart< MeshType > > _fbm_meshpart_inside
the meshpart representing the FBM inside region
std::unique_ptr< Geometry::MeshPart< MeshType > > _fbm_meshpart_interface
the meshpart representing the FBM interface region
const MeshType & _mesh
a reference to our mesh object
std::unique_ptr< Assembly::UnitFilterAssembler< MeshType_ > > _unit_asm_inside
unit-filter assembler on inside mesh-part
std::unique_ptr< Assembly::UnitFilterAssembler< MeshType_ > > _unit_asm_interface
unit-filter assembler on interface mesh-part
Detailed Description
template<typename MeshType_>
class FEAT::Assembly::StokesFBMAssembler< MeshType_ >
Stokes Fictitious Boundary Method assembler class.
This class can be used to assemble a triplet of unit filters for the velocity and pressure spaces of a Stokes system. The three unit filters that result from this assembly are:
An UnitFilterBlocked thats filter out all velocity DOFs which are wholly inside the FBM region by setting them to 0
An UnitFilter that filters out all pressure DOFs which are wholly inside the FBM region by setting them to 0
An UnitFilterBlocked for the velocity that represents the FBM interface DOFs which are handled by the div-free L2-projection, which is incorporated into the system matrix by replacing the corresponding A matrix rows by (properly scaled) mass matrix rows.
To use this assembler for the proper handling of FBM boundary conditions, proceed as follows:
Assemble the matrix block A of the Stokes system (typically a Laplace matrix) as well as the velocity mass matrix
Create a StokesFBMAssembler object
Add all meshparts that represent the FBM region(s) to the assembler by calling add_fbm_meshpart()
In a parallel simulation, call the sync() function to synchronize the FBM data across all processes
Call the compile() function to finish the setup of the assembler
Use the assemble_inside_filter() function to assemble the unit-filters for the velocity and pressure spaces
Use the assemble_interface_filter() function to assemble a special unit filter that will represent the interface DOFs in the velocity space. Then, every time you (re)assemble the matrix block A of the system matrix, call the LAFEM::UnitFilterBlocked::filter_weak_matrix_rows() to replace the matrix A interface rows by the corresponding rows of the velocity mass matrix.
If you require a pressure mean filter, assemble the primal and dual vectors of the filter by using the Assembly::MeanFilterAssembler and filter them by applying the pressure unit filter's filter_cor function before pushing them into the mean filter.
If you require the characteristic function of the FBM region interface, e.g. for the volumetric computation of the drag and lift forces, then you can use the assemble_characteristic_vector() function for that.
Author
Peter Zajac
Definition at line 62 of file stokes_fbm_assembler.hpp.
Member Typedef Documentation
MeshType
template<typename MeshType_ > typedef MeshType_ FEAT::Assembly::StokesFBMAssembler< MeshType_ >::MeshType
our mesh type
Definition at line 66 of file stokes_fbm_assembler.hpp.
Constructor & Destructor Documentation
StokesFBMAssembler()
template<typename MeshType_ > FEAT::Assembly::StokesFBMAssembler< MeshType_ >::StokesFBMAssembler (const MeshType & mesh_) inline explicit
Constructor.
Parameters
[in] mesh_ A resident reference to the underlying mesh that the FBM is to be assembled on
Definition at line 109 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_masks, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_mesh, and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::shape_dim.
~StokesFBMAssembler()
template<typename MeshType_ > virtual FEAT::Assembly::StokesFBMAssembler< MeshType_ >::~StokesFBMAssembler () inline virtual
virtual destructor
Definition at line 130 of file stokes_fbm_assembler.hpp.
Member Function Documentation
_add_fbm_target_set()
template<typename MeshType_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_add_fbm_target_set (const Geometry::TargetSet & target_set, int dim) inline protected
auxiliary function: add a target set to the FBM mask vector
Definition at line 554 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_masks, and FEAT::Geometry::TargetSet::get_num_entities().
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::add_fbm_meshpart().
_build_tbm_target_set()
template<typename MeshType_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_build_tbm_target_set (Geometry::TargetSet & target_set, int dim, int mask_value) inline protected
auxiliary function: build target set from mask vector
Definition at line 563 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_masks.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile().
_get_target_set() [1/4]
template<typename MeshType_ > static const Geometry::TargetSet & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set (const Geometry::TargetSetHolder< Shape::Vertex > & tsh, int dim) inline static protected
auxiliary function: get a target set from a target set holder (recursion end overload)
Definition at line 590 of file stokes_fbm_assembler.hpp.
References XASSERT.
_get_target_set() [2/4]
template<typename MeshType_ > template<typename Shape_ > static const Geometry::TargetSet & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set (const Geometry::TargetSetHolder< Shape_ > & tsh, int dim) inline static protected
auxiliary function: get a target set from a target set holder
Definition at line 579 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set(), and XASSERT.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::add_fbm_meshpart(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::sync().
_get_target_set() [3/4]
template<typename MeshType_ > static Geometry::TargetSet & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set (Geometry::TargetSetHolder< Shape::Vertex > & tsh, int dim) inline static protected
auxiliary function: get a target set from a target set holder (recursion end overload)
Definition at line 609 of file stokes_fbm_assembler.hpp.
References XASSERT.
_get_target_set() [4/4]
template<typename MeshType_ > template<typename Shape_ > static Geometry::TargetSet & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set (Geometry::TargetSetHolder< Shape_ > & tsh, int dim) inline static protected
auxiliary function: get a target set from a target set holder
Definition at line 598 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set(), and XASSERT.
_process_mask()
template<typename MeshType_ > template<int m_> static void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_mask (std::vector< int > & shape_mask, const std::vector< int > & face_mask, const Geometry::IndexSet< m_ > & faces_at_shape) inline static protected
Auxiliary function: update bit 1 of the mask vector for a shape based on a bit 0 of its face mask vector.
This function sets bit 1 of any shape entity to 0 if there is at least one face adjacent to that shape entity whose bit 0 is equal to 0.
Parameters
[in,out] shape_mask The mask vector for the shape that whose bit 1 mask is to be updated
[in] face_masj The mask vector for the face that whose bit 0 mask is to be used for the update of the shape mask
[in] faces_at_shape The faces-at-shape index set of the underlying mesh which describes the faces that are adjacent to a shape
Definition at line 631 of file stokes_fbm_assembler.hpp.
References FEAT::Geometry::IndexSet< num_indices_ >::get_index_bound(), FEAT::Geometry::IndexSet< num_indices_ >::get_num_entities(), FEAT::Geometry::IndexSet< num_indices_ >::get_num_indices(), and XASSERT.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_masks().
_process_masks() [1/2]
template<typename MeshType_ > template<typename Shape_ , std::size_t n_> static void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_masks (std::array< std::vector< int >, n_ > & masks, const Geometry::IndexSetWrapper< Shape_, 0 > & idx_wrapper) inline static protected
auxiliary function: process masks for all face dimensions for a given shape (recursion end)
Definition at line 658 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_mask().
_process_masks() [2/2]
template<typename MeshType_ > template<typename Shape_ , int face_dim_, std::size_t n_> static void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_masks (std::array< std::vector< int >, n_ > & masks, const Geometry::IndexSetWrapper< Shape_, face_dim_ > & idx_wrapper) inline static protected
auxiliary function: process masks for all face dimensions for a given shape
Definition at line 650 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_mask(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_masks().
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_masks(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_shapes().
_process_shapes() [1/2]
template<typename MeshType_ > template<std::size_t n_> static void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_shapes (std::array< std::vector< int >, n_ > & , const Geometry::IndexSetHolder< Shape::Vertex > &) inline static protected
auxiliary function: process masks shape dimensions (recursion end)
Definition at line 674 of file stokes_fbm_assembler.hpp.
_process_shapes() [2/2]
template<typename MeshType_ > template<typename Shape_ , std::size_t n_> static void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_shapes (std::array< std::vector< int >, n_ > & masks, const Geometry::IndexSetHolder< Shape_ > & idx_holder) inline static protected
auxiliary function: process masks shape dimensions
Definition at line 665 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_masks(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_shapes().
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_shapes(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile().
add_fbm_meshpart()
template<typename MeshType_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::add_fbm_meshpart (const Geometry::MeshPart< MeshType > & fbm_part) inline
Adds a FBM mesh-part to the assembler.
Parameters
[in] fbm_part A transient reference to the FBM mesh-part to be added.
Definition at line 172 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_add_fbm_target_set(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::shape_dim, and XASSERTM.
assemble_characteristic_vector()
template<typename MeshType_ > template<typename DT_ , typename IT_ , typename Space_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector (LAFEM::DenseVector< DT_, IT_ > & vector, const Space_ & space, const DT_ val_outside = DT_(0), const DT_ val_inside = DT_(1), const DT_ val_intface = DT_(1)) const inline
Assembles a characteristic vector on the FBM region.
Parameters
[out] vector A transient reference to the characteristic vector that is to be assembled
[in] space A transient reference to the space that the characteristic vector is to be assembled for
[in] val_outside The vector value that is to be used outside the FBM interface/inside regions; defaults to 0
[in] val_inside The vector value that is to be used inside the FBM region; defaults to 1
[in] val_intface The vector value that is to be on the FBM interface; defaults to 1
Definition at line 366 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_inside, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_interface, FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::Container< DT_, IT_ >::format(), and XASSERTM.
assemble_inside_filter() [1/2]
template<typename MeshType_ > template<typename DT_ , typename IT_ , typename Space_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_inside_filter (LAFEM::UnitFilter< DT_, IT_ > & filter, const Space_ & space) const inline
Assembles a UnitFilter inside the FBM region.
Parameters
[in,out] filter A transient reference to the filter to be assembled
[in] space A transient reference to the space to assemble the filter for
Definition at line 396 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, and XASSERTM.
assemble_inside_filter() [2/2]
template<typename MeshType_ > template<typename DT_ , typename IT_ , typename Space_ , int dim_> void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_inside_filter (LAFEM::UnitFilterBlocked< DT_, IT_, dim_ > & filter, const Space_ & space) const inline
Assembles a UnitFilterBlocked inside the FBM region.
Parameters
[in,out] filter A transient reference to the filter to be assembled
[in] space A transient reference to the space to assemble the filter for
Definition at line 412 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, and XASSERTM.
assemble_interface_filter() [1/4]
template<typename MeshType_ > template<typename DT_ , typename IT_ , typename Space_ , typename Mirror_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_interface_filter (LAFEM::UnitFilter< DT_, IT_ > & filter, const Space_ & space, const Global::Matrix< LAFEM::SparseMatrixCSR< DT_, IT_ >, Mirror_, Mirror_ > & matrix_a, const Global::Matrix< LAFEM::SparseMatrixCSR< DT_, IT_ >, Mirror_, Mirror_ > & matrix_m) const inline
Assembles a UnitFilter on the FBM interface (parallel version)
Attention
This is a collective function that must be called by all processes simultaneously!
Parameters
[in,out] filter A transient reference to the filter to be assembled
[in] space A transient reference to the space to assemble the filter for
[in] matrix_a A transient reference to the global system matrix block A that the FBM filter will be applied to later on
[in] matrix_m A transient reference to the global mass matrix that will be used to apply the FBM filter later on
Definition at line 506 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, and XASSERTM.
assemble_interface_filter() [2/4]
template<typename MeshType_ > template<typename DT_ , typename IT_ , typename Space_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_interface_filter (LAFEM::UnitFilter< DT_, IT_ > & filter, const Space_ & space, const LAFEM::SparseMatrixCSR< DT_, IT_ > & matrix_a, const LAFEM::SparseMatrixCSR< DT_, IT_ > & matrix_m) const inline
Assembles a UnitFilter on the FBM interface (non-parallel version)
Attention
This function can only be used in serial (non-parallel) simulations! If you intent to use FBM in a simulation that uses Global::Matrix containers, then you need to call the overload that takes Global::Matrix parameters for the A and M matrices, respectively, because of the synchronization that is necessary to compute the correct filter entries, which itself requires access to the global matrix functionality!
Parameters
[in,out] filter A transient reference to the filter to be assembled
[in] space A transient reference to the space to assemble the filter for
[in] matrix_a A transient reference to the system matrix block A that the FBM filter will be applied to later on
[in] matrix_m A transient reference to the mass matrix that will be used to apply the FBM filter later on
Definition at line 440 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_l(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), and XASSERTM.
assemble_interface_filter() [3/4]
template<typename MeshType_ > template<typename DT_ , typename IT_ , typename Space_ , typename Mirror_ , int bh_, int bw_> void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_interface_filter (LAFEM::UnitFilterBlocked< DT_, IT_, bh_ > & filter, const Space_ & space, const Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, bh_, bw_ >, Mirror_, Mirror_ > & matrix_a, const Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, bh_, bw_ >, Mirror_, Mirror_ > & matrix_m) const inline
Assembles a UnitFilterBlocked on the FBM interface (parallel version)
Attention
This is a collective function that must be called by all processes simultaneously!
Parameters
[in,out] filter A transient reference to the filter to be assembled
[in] space A transient reference to the space to assemble the filter for
[in] matrix_a A transient reference to the global system matrix block A that the FBM filter will be applied to later on
[in] matrix_m A transient reference to the global mass matrix that will be used to apply the FBM filter later on
Definition at line 538 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, and XASSERTM.
assemble_interface_filter() [4/4]
template<typename MeshType_ > template<typename DT_ , typename IT_ , typename Space_ , int bh_, int bw_> void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_interface_filter (LAFEM::UnitFilterBlocked< DT_, IT_, bh_ > & filter, const Space_ & space, const LAFEM::SparseMatrixBCSR< DT_, IT_, bh_, bw_ > & matrix_a, const LAFEM::SparseMatrixBCSR< DT_, IT_, bh_, bw_ > & matrix_m) const inline
Assembles a UnitFilterBlocked on the FBM interface (non-parallel version)
Attention
This function can only be used in serial (non-parallel) simulations! If you intent to use FBM in a simulation that uses Global::Matrix containers, then you need to call the overload that takes Global::Matrix parameters for the A and M matrices, respectively, because of the synchronization that is necessary to compute the correct filter entries, which itself requires access to the global matrix functionality!
Parameters
[in,out] filter A transient reference to the filter to be assembled
[in] space A transient reference to the space to assemble the filter for
[in] matrix_a A transient reference to the system matrix block A that the FBM filter will be applied to later on
[in] matrix_m A transient reference to the mass matrix that will be used to apply the FBM filter later on
Definition at line 475 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), and XASSERTM.
clear()
template<typename MeshType_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear () inline
Clears the assembler.
Definition at line 137 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_masks, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_meshpart_inside, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_meshpart_interface, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_mesh, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_inside, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_interface, and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::shape_dim.
compile()
template<typename MeshType_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile () inline
Compiles the assembler.
Definition at line 275 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_build_tbm_target_set(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_masks, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_meshpart_inside, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_meshpart_interface, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_mesh, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_process_shapes(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_inside, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_interface, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::shape_dim, and XASSERTM.
get_fbm_mask_vector()
template<typename MeshType_ > const std::vector< int > & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_fbm_mask_vector (int dim) const inline
Returns a reference to an internal FBM mask vector.
Parameters
[in] dim The dimension of the mask vector that is to be returned.
Returns
A const reference to the internal FBM mask vector
Definition at line 160 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_masks, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::shape_dim, and XASSERT.
get_meshpart_inside()
template<typename MeshType_ > const Geometry::MeshPart< MeshType > & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_meshpart_inside () const inline
Returns a reference to the mesh-part representing the FBM inside region.
Definition at line 327 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_meshpart_inside, and XASSERTM.
get_meshpart_interface()
template<typename MeshType_ > const Geometry::MeshPart< MeshType > & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_meshpart_interface () const inline
Returns a reference to the mesh-part representing the FBM interface.
Definition at line 320 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_meshpart_interface, and XASSERTM.
get_unit_asm_inside()
template<typename MeshType_ > const Assembly::UnitFilterAssembler< MeshType > & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_unit_asm_inside () const inline
Returns a reference to the internal unit-filter assembler inside the FBM region.
Definition at line 341 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_inside, and XASSERTM.
get_unit_asm_interface()
template<typename MeshType_ > const Assembly::UnitFilterAssembler< MeshType > & FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_unit_asm_interface () const inline
Returns a reference to the internal unit-filter assembler on the FBM interface.
Definition at line 334 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_interface, and XASSERTM.
sync()
template<typename MeshType_ > void FEAT::Assembly::StokesFBMAssembler< MeshType_ >::sync (const Geometry::RootMeshNode< MeshType > & mesh_node, const Dist::Comm & comm) inline
Synchronizes the assembler over all processes in a parallel simulation.
Attention
This is a collective function that must be called by all processes simultaneously!
Parameters
[in] mesh_node A transient reference to the mesh node containing the communication halos of this process's neighbors
[in] comm The distributed communicator that corresponds to the mesh node
Definition at line 190 of file stokes_fbm_assembler.hpp.
References FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_masks, FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_get_target_set(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Dist::RequestVector::push_back(), FEAT::Dist::RequestVector::reserve(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::shape_dim, FEAT::Dist::RequestVector::wait_all(), and XASSERTM.
Member Data Documentation
_compiled
template<typename MeshType_ > bool FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_compiled protected
already compiled?
Definition at line 100 of file stokes_fbm_assembler.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::add_fbm_meshpart(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_inside_filter(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_interface_filter(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_meshpart_inside(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_meshpart_interface(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_unit_asm_inside(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_unit_asm_interface(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::sync().
_fbm_masks
template<typename MeshType_ > std::array<std::vector<int>, shape_dim+1> FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_masks protected
Array of FBM mask vectors.
For each dimension, the mask vector contains an int value for each entity of that dimension, which can be equal to one of the following four values:
0: Indicates that the entity itself as well as all of its sub-dimensional entities are not contained in the FBM region, thus these are the entities that are wholly outside the FBM region.
1: Indicates that the entity itself is inside the FBM region, but at least one of its sub-dimensional faces is outside the FBM region. These are the entities that are partially inside the FBM region.
2: Indicates that the entity itself is outside the FBM region, but all of its sub-dimensional faces are inside in the FBM region. This is a borderline case which only happens if the mesh is too coarse to properly resolve a non-convex FBM region. These DOFs are treated as if they had the value 0.
3: Indicates that the entity itself as well as all of its sub-dimensional entities are inside the FBM region, thus these are the entities that are wholly inside the FBM region.
Definition at line 90 of file stokes_fbm_assembler.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::StokesFBMAssembler(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_add_fbm_target_set(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_build_tbm_target_set(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_fbm_mask_vector(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::sync().
_fbm_meshpart_inside
template<typename MeshType_ > std::unique_ptr<Geometry::MeshPart<MeshType> > FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_meshpart_inside protected
the meshpart representing the FBM inside region
Definition at line 92 of file stokes_fbm_assembler.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_meshpart_inside().
_fbm_meshpart_interface
template<typename MeshType_ > std::unique_ptr<Geometry::MeshPart<MeshType> > FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_fbm_meshpart_interface protected
the meshpart representing the FBM interface region
Definition at line 94 of file stokes_fbm_assembler.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_meshpart_interface().
_mesh
template<typename MeshType_ > const MeshType& FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_mesh protected
a reference to our mesh object
Definition at line 72 of file stokes_fbm_assembler.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::StokesFBMAssembler(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile().
_unit_asm_inside
template<typename MeshType_ > std::unique_ptr<Assembly::UnitFilterAssembler<MeshType_> > FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_inside protected
unit-filter assembler on inside mesh-part
Definition at line 96 of file stokes_fbm_assembler.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_unit_asm_inside().
_unit_asm_interface
template<typename MeshType_ > std::unique_ptr<Assembly::UnitFilterAssembler<MeshType_> > FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_unit_asm_interface protected
unit-filter assembler on interface mesh-part
Definition at line 98 of file stokes_fbm_assembler.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_unit_asm_interface().
shape_dim
template<typename MeshType_ > constexpr int FEAT::Assembly::StokesFBMAssembler< MeshType_ >::shape_dim = MeshType::shape_dim static constexpr
our shape dimension
Definition at line 68 of file stokes_fbm_assembler.hpp.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::StokesFBMAssembler(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::add_fbm_meshpart(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::clear(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::compile(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::get_fbm_mask_vector(), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::sync().
The documentation for this class was generated from the following file:
kernel/assembly/stokes_fbm_assembler.hpp