FEAT: FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > > Class Template Reference
FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > > Class Template Reference
Iterative-Partitioner class template specialization for ConformalMesh.
#include <parti_iterative.hpp>
Public Types
typedef ConformalMesh< Shape_, num_coords_, Coord_ > MeshType
our mesh type
Public Member Functions
PartiIterative (MeshType &mesh, const Dist::Comm &comm, Index num_patches, double time_init, double time_mutate)
Constructor.
Adjacency::Graph build_elems_at_rank () const
Returns the Elements-at-Rank graph of the partitioning.
Private Attributes
const Dist::Comm & _comm
Our communicator.
const Index _num_elems
number of elements in input mesh
const Index _num_patches
number of desired patches
const Index _num_ranks
number of usable ranks
std::list< Geometry::Intern::PartiIterativeIndividual< Shape_, num_coords_, Coord_ > > _population
Our population.
Detailed Description
template<typename Shape_, int num_coords_, typename Coord_>
class FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >
Iterative-Partitioner class template specialization for ConformalMesh.
The basic usage of this class is as follows:
Refine the mesh until it contains at least num_patches cells.
Create an object of this class and pass the to-be-partitioned mesh as well as the desired number of patches and the available number of ranks in a communicator to the constructor.
Create the Elements-At-Rank graph using the build_elems_at_rank() function.
Author
Dirk Ribbrock
Definition at line 464 of file parti_iterative.hpp.
Member Typedef Documentation
MeshType
template<typename Shape_ , int num_coords_, typename Coord_ > typedef ConformalMesh<Shape_, num_coords_, Coord_> FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::MeshType
our mesh type
Definition at line 480 of file parti_iterative.hpp.
Constructor & Destructor Documentation
PartiIterative()
template<typename Shape_ , int num_coords_, typename Coord_ > FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::PartiIterative (MeshType & mesh, const Dist::Comm & comm, Index num_patches, double time_init, double time_mutate) inline explicit
Constructor.
Parameters
[in] mesh The mesh that is to be partitioned (on some refined level).
[in] comm The global communicator to be used.
[in] time_init The amount of seconds to be used for initial patch center search.
[in] time_mutate The amount of seconds to be used for partitioning optimization via patch mutation.
Definition at line 497 of file parti_iterative.hpp.
References FEAT::TimeStamp::elapsed_now(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors(), and FEAT::TimeStamp::stamp().
Member Function Documentation
build_elems_at_rank()
template<typename Shape_ , int num_coords_, typename Coord_ > Adjacency::Graph FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::build_elems_at_rank () const inline
Returns the Elements-at-Rank graph of the partitioning.
Returns
The Elements-at-Rank graph of the partitioning.
Todo:
use mpi_reduce_all with op_minloc
Definition at line 557 of file parti_iterative.hpp.
References FEAT::Dist::Comm::allgather(), FEAT::Dist::Comm::bcast(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), and FEAT::Dist::Comm::rank().
Member Data Documentation
_comm
template<typename Shape_ , int num_coords_, typename Coord_ > const Dist::Comm& FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::_comm private
Our communicator.
Definition at line 472 of file parti_iterative.hpp.
_num_elems
template<typename Shape_ , int num_coords_, typename Coord_ > const Index FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::_num_elems private
number of elements in input mesh
Definition at line 468 of file parti_iterative.hpp.
_num_patches
template<typename Shape_ , int num_coords_, typename Coord_ > const Index FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::_num_patches private
number of desired patches
Definition at line 476 of file parti_iterative.hpp.
_num_ranks
template<typename Shape_ , int num_coords_, typename Coord_ > const Index FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::_num_ranks private
number of usable ranks
Definition at line 470 of file parti_iterative.hpp.
_population
template<typename Shape_ , int num_coords_, typename Coord_ > std::list<Geometry::Intern::PartiIterativeIndividual<Shape_, num_coords_, Coord_> > FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::_population private
Our population.
Definition at line 474 of file parti_iterative.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/parti_iterative.hpp