FEAT: FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ > Class Template Reference
FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ > Class Template Reference
Base-Class for Hierarchical Domain Control implementations.
#include <parti_domain_control_base.hpp>
Classes
class Ancestor
Ancestor info class.
Public Types
typedef Geometry::MeshAtlas< MeshType > AtlasType
typedef Control::Domain::DomainControl< DomainLevel_ > BaseClass
Our base class.
typedef DomainLayer LayerType
typedef DomainLevel_ LevelType
typedef Geometry::RootMeshNode< MeshType > MeshNodeType
our root mesh node type
typedef LevelType::PartType MeshPartType
our mesh-part type
typedef LevelType::MeshType MeshType
typedef LevelType::ShapeType ShapeType
typedef VirtualLevel< LevelType > VirtLevelType
typedef Real WeightType
weight type for partitioner element weights; always Real
Public Member Functions
PartiDomainControlBase (const Dist::Comm &comm_, bool support_multi_layered)
Constructor.
virtual ~PartiDomainControlBase ()
virtual destructor
VirtLevelType & at (std::size_t i)
const VirtLevelType & at (std::size_t i) const
VirtLevelType & back ()
const VirtLevelType & back () const
LayerType & back_layer ()
const LayerType & back_layer () const
std::size_t bytes () const
const Dist::Comm & comm () const
void compile_virtual_levels ()
String dump_ancestry () const
Debugging function: Returns a string containing encoded ancestry information.
String dump_layer_levels () const
String dump_layers () const
String dump_virt_levels () const
virtual String format_chosen_levels () const
Returns the chosen levels formatted as a parsable string.
virtual String format_desired_levels () const
Returns the desired levels formatted as a parsable string.
VirtLevelType & front ()
const VirtLevelType & front () const
LayerType & front_layer ()
const LayerType & front_layer () const
Geometry::AdaptMode get_adapt_mode () const
Gets the adapt-mode for refinement.
const std::deque< Ancestor > & get_ancestry () const
Returns a const reference to the ancestry.
AtlasType & get_atlas ()
const AtlasType & get_atlas () const
const std::deque< std::pair< int, int > > get_chosen_levels () const
Returns the deque of chosen refinement levels.
virtual String get_chosen_parti_info () const
Returns an informative string about the chosen partitioning.
int get_desired_level_max () const
Returns the desired maximum refinement level.
int get_desired_level_min () const
Returns the desired minimum refinement level.
const std::deque< std::pair< int, int > > get_desired_levels () const
Returns the deque of desired refinement levels.
bool has_ghost () const
void keep_base_levels ()
Instructs the domain controller to keep the base-mesh levels after partitioning.
int max_level_index () const
int med_level_index () const
int min_level_index () const
std::size_t num_global_layers () const
std::size_t num_local_layers () const
virtual bool parse_args (SimpleArgParser &args)
Parses the partitioner options from an argument parser.
virtual bool parse_property_map (PropertyMap &pmap)
Parses the partitioner options from a PropertyMap.
virtual void print () const
void push_layer (std::shared_ptr< LayerType > layer)
void push_level_back (int layer_index, std::shared_ptr< LevelType > level)
void push_level_front (int layer_index, std::shared_ptr< LevelType > level)
std::vector< char > serialize_partitioning () const
Serializes the partitioning information into a binary buffer.
void set_adapt_mode (Geometry::AdaptMode adapt_mode)
Sets the adapt-mode for refinement.
virtual void set_desired_levels (const std::deque< String > &slvls)
Sets the desired levels for the partitioned hierarchy.
void set_desired_levels (const String &slvls)
Sets the desired levels for the partitioned hierarchy.
virtual void set_desired_levels (int lvl_max, int lvl_med, int lvl_min)
Sets the desired refinement levels for a double-layered hierarchy.
virtual void set_desired_levels (int lvl_max, int lvl_min=-1)
Sets the desired refinement levels for a single-layered hierarchy.
std::size_t size_physical () const
std::size_t size_virtual () const
Static Public Member Functions
static String name ()
Protected Member Functions
virtual bool _apply_parti (Ancestor &ancestor, MeshNodeType &base_mesh_node)
Applies an a-posteriori partitioner.
bool _apply_parti_genetic (Ancestor &ancestor, MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the genetic partitioner onto the base-mesh.
bool _apply_parti_metis (Ancestor &ancestor, const MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the METIS partitioner onto the base-mesh.
bool _apply_parti_naive (Ancestor &ancestor, const MeshNodeType &mesh_node, const std::vector< WeightType > &weights)
Applies the naive partitioner onto the base-mesh.
bool _apply_parti_zoltan (Ancestor &ancestor, const MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the Zoltan partitioner onto the base-mesh.
virtual bool _check_parti (Ancestor &ancestor, const MeshNodeType &mesh_node, bool is_base_layer)
Checks for an appropriate partitioning strategy.
virtual std::vector< WeightType > _compute_weights (Ancestor &ancestor, const MeshNodeType &base_mesh_node)
Computes the element partitioning weights.
virtual void _create_ancestry_scattered ()
Creates the layers for a multi-layered domain control in a scattered fashion.
virtual void _create_ancestry_single ()
Creates the ancestry for a single layer (or a single process)
virtual void _create_multi_layers_scattered ()
Creates the layers for a multi-layered domain control in a scattered fashion.
virtual bool _parse_parti_type (const String &type)
Parses a partitioner type.
virtual void _reset_parti_types ()
Resets/disables all partitioner types.
virtual void _split_basemesh_halos (const Ancestor &ancestor, const MeshNodeType &base_mesh_node, MeshNodeType &patch_mesh_node, std::vector< int > &neighbor_ranks)
Splits the base-mesh halos and computes the inter-patch-mesh halos.
Protected Attributes
Geometry::AdaptMode _adapt_mode
the adapt mode for refinement
bool _allow_parti_genetic
allow genetic partitioner?
bool _allow_parti_metis
allow metis partitioner?
bool _allow_parti_naive
allow naive partitioner?
bool _allow_parti_zoltan
allow Zoltan partitioner?
std::deque< Ancestor > _ancestry
the partition ancestry deque
AtlasType _atlas
std::deque< std::shared_ptr< LevelType > > _base_levels
std::deque< std::pair< int, int > > _chosen_levels
chosen level deque
const Dist::Comm & _comm
std::deque< std::pair< int, int > > _desired_levels
desired level deque
double _genetic_time_init
time for genetic partitioner initialization
double _genetic_time_mutate
time for genetic partitioner mutation
bool _keep_base_levels
keep base-mesh levels on root process?
std::deque< std::deque< std::shared_ptr< LevelType > > > _layer_levels
std::deque< std::shared_ptr< LayerType > > _layers
std::size_t _num_global_layers
int _required_elems_per_rank
required number of elements per rank for a-posteriori partitioning
bool _support_multi_layered
support multi-layered hierarchy?
std::deque< VirtLevelType > _virt_levels
std::size_t _virt_size
bool _was_created
specifies whether the domain control was already created
Detailed Description
template<typename DomainLevel_>
class FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >
Base-Class for Hierarchical Domain Control implementations.
Todo:
document this
For more details on meshes, see the related doxygen page FEAT Mesh File Format.
Author
Peter Zajac
Definition at line 41 of file parti_domain_control_base.hpp.
Member Typedef Documentation
AtlasType
typedef Geometry::MeshAtlas<MeshType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::AtlasType inherited
Definition at line 420 of file domain_control.hpp.
BaseClass
template<typename DomainLevel_ > typedef Control::Domain::DomainControl<DomainLevel_> FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::BaseClass
Our base class.
Definition at line 46 of file parti_domain_control_base.hpp.
LayerType
typedef DomainLayer FEAT::Control::Domain::DomainControl< DomainLevel_ >::LayerType inherited
Definition at line 414 of file domain_control.hpp.
LevelType
typedef DomainLevel_ FEAT::Control::Domain::DomainControl< DomainLevel_ >::LevelType inherited
Definition at line 413 of file domain_control.hpp.
MeshNodeType
template<typename DomainLevel_ > typedef Geometry::RootMeshNode<MeshType> FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::MeshNodeType
our root mesh node type
Definition at line 56 of file parti_domain_control_base.hpp.
MeshPartType
template<typename DomainLevel_ > typedef LevelType::PartType FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::MeshPartType
our mesh-part type
Definition at line 58 of file parti_domain_control_base.hpp.
MeshType
typedef LevelType::MeshType FEAT::Control::Domain::DomainControl< DomainLevel_ >::MeshType inherited
Definition at line 418 of file domain_control.hpp.
ShapeType
typedef LevelType::ShapeType FEAT::Control::Domain::DomainControl< DomainLevel_ >::ShapeType inherited
Definition at line 417 of file domain_control.hpp.
VirtLevelType
typedef VirtualLevel<LevelType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::VirtLevelType inherited
Definition at line 415 of file domain_control.hpp.
WeightType
template<typename DomainLevel_ > typedef Real FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::WeightType
weight type for partitioner element weights; always Real
Definition at line 61 of file parti_domain_control_base.hpp.
Constructor & Destructor Documentation
PartiDomainControlBase()
template<typename DomainLevel_ > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::PartiDomainControlBase (const Dist::Comm & comm_, bool support_multi_layered) inline explicit
Constructor.
Parameters
[in] comm_ A resident reference to the main communicator to be used.
[in] support_multi_layered Specifies whether the controller is allowed to create multi-layered hierarchies.
Definition at line 154 of file parti_domain_control_base.hpp.
~PartiDomainControlBase()
template<typename DomainLevel_ > virtual FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::~PartiDomainControlBase () inline virtual
virtual destructor
Definition at line 172 of file parti_domain_control_base.hpp.
Member Function Documentation
_apply_parti()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti (Ancestor & ancestor, MeshNodeType & base_mesh_node) inline protected virtual
Applies an a-posteriori partitioner.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
Returns
true, if the base-mesh was partitioned, otherwise false.
Definition at line 1295 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_genetic(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_metis(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_naive(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_zoltan(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_compute_weights(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_apriori.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered().
_apply_parti_genetic()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_genetic (Ancestor & ancestor, MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected
Applies the genetic partitioner onto the base-mesh.
Parameters
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true.
Definition at line 1444 of file parti_domain_control_base.hpp.
References FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_metis()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_metis (Ancestor & ancestor, const MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected
Applies the METIS partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if METIS was applied successfully, otherwise false.
Definition at line 1391 of file parti_domain_control_base.hpp.
References FEAT::Geometry::PartiParMETIS::build_elems_at_rank(), FEAT::Geometry::PartiParMETIS::execute(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_naive()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_naive (Ancestor & ancestor, const MeshNodeType & mesh_node, const std::vector< WeightType > & weights) inline protected
Applies the naive partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if a naive partition was created successfully, otherwise false.
Definition at line 1486 of file parti_domain_control_base.hpp.
References FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info, and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_zoltan()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_zoltan (Ancestor & ancestor, const MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected
Applies the Zoltan partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if Zoltan was applied successfully, otherwise false.
Definition at line 1339 of file parti_domain_control_base.hpp.
References FEAT::Geometry::PartiZoltan::build_elems_at_rank(), FEAT::Geometry::PartiZoltan::execute(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_check_parti()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_check_parti (Ancestor & ancestor, const MeshNodeType & mesh_node, bool is_base_layer) inline protected virtual
Checks for an appropriate partitioning strategy.
This function examines the given base mesh and checks whether one of the a-priori partitioning strategies (extern or 2-level) yields a valid partitioning for the given number of partitions. If so, the corresponding partitioning level and graph are stored in ancestor.parti_level and ancestor.parti_graph. If not, this function determines how often the base-mesh has to be refined until its has enough cells so that one of the a-posteriori partitioners can be applied.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] mesh_node The base-mesh node that is to be partitioned.
[in] is_base_layer Set to true, if #base_mesh_node is the mesh node that corresponds to the input file's mesh and therefore extern partitioning is a valid option, or set to false in any other case.
Returns
true, if an a-priori partitioning was found, otherwise false.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 1254 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Math::max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_level.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_compute_weights()
template<typename DomainLevel_ > virtual std::vector< WeightType > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_compute_weights (Ancestor & ancestor, const MeshNodeType & base_mesh_node) inline protected virtual
Computes the element partitioning weights.
Note
This base-class implementation always returns an empty vector, but a derived class may override this method and an actual non-trivial weight vector.
Returns
A vector containing the weights for the base mesh elements or an empty vector, if all elements are to be weighted equally.
Definition at line 751 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_create_ancestry_scattered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_scattered () inline protected virtual
Creates the layers for a multi-layered domain control in a scattered fashion.
Definition at line 865 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Dist::Comm::comm_create_range_incl(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_procs, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_create_ancestry_single()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_single () inline protected virtual
Creates the ancestry for a single layer (or a single process)
Definition at line 759 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_procs, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process().
_create_multi_layers_scattered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_multi_layers_scattered () inline protected virtual
Creates the layers for a multi-layered domain control in a scattered fashion.
Definition at line 804 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::comm, FEAT::Dist::Comm::comm_create_range_incl(), FEAT::Dist::Comm::comm_dup(), FEAT::Dist::Comm::is_null(), FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_parse_parti_type()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type (const String & type) inline protected virtual
Parses a partitioner type.
Parameters
[in] type The name of the partitioner type that is to be enabled.
Returns
true, if type represents a supported partitioner type, otherwise false.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 727 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan, and FEAT::String::compare_no_case().
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_reset_parti_types()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types () inline protected virtual
Resets/disables all partitioner types.
This function is called by the parse_args and parse_property_map function when the user has supplied a list of allowed partitioner types.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 713 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_split_basemesh_halos()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_split_basemesh_halos (const Ancestor & ancestor, const MeshNodeType & base_mesh_node, MeshNodeType & patch_mesh_node, std::vector< int > & neighbor_ranks) inline protected virtual
Splits the base-mesh halos and computes the inter-patch-mesh halos.
This is where the magic happens in the case of the multi-layered hierarchy.
Parameters
[in] ancestor The ancestor object for the current layer.
[in] base_mesh_node The base-mesh node that has been partitioned and whose halos are to be split.
[in,out] patch_mesh_node The patch-mesh node that represents the partition whose halos are to be computed.
[in,out] neighbor_ranks The vector that receives the ranks of the new neighbors that derive from halo splitting.
Definition at line 941 of file parti_domain_control_base.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_halo(), FEAT::Dist::Comm::bcast(), FEAT::Dist::Comm::gather(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::is_null(), FEAT::Dist::Comm::isend(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), FEAT::Dist::RequestVector::wait_all(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
at() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::at (std::size_t i) inline inherited
Definition at line 579 of file domain_control.hpp.
at() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::at (std::size_t i) const inline inherited
Definition at line 584 of file domain_control.hpp.
back() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back () inline inherited
Definition at line 599 of file domain_control.hpp.
back() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back () const inline inherited
Definition at line 604 of file domain_control.hpp.
back_layer() [1/2]
LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back_layer () inline inherited
Definition at line 519 of file domain_control.hpp.
back_layer() [2/2]
const LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back_layer () const inline inherited
Definition at line 524 of file domain_control.hpp.
bytes()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::bytes () const inline inherited
Definition at line 477 of file domain_control.hpp.
comm()
const Dist::Comm & FEAT::Control::Domain::DomainControl< DomainLevel_ >::comm () const inline inherited
Definition at line 472 of file domain_control.hpp.
compile_virtual_levels()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::compile_virtual_levels () inline inherited
Definition at line 637 of file domain_control.hpp.
dump_ancestry()
template<typename DomainLevel_ > String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::dump_ancestry () const inline
Debugging function: Returns a string containing encoded ancestry information.
Definition at line 571 of file parti_domain_control_base.hpp.
References FEAT::String::pad_front(), and FEAT::stringify().
dump_layer_levels()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_layer_levels () const inline inherited
Definition at line 735 of file domain_control.hpp.
dump_layers()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_layers () const inline inherited
Definition at line 713 of file domain_control.hpp.
dump_virt_levels()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_virt_levels () const inline inherited
Definition at line 748 of file domain_control.hpp.
format_chosen_levels()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_chosen_levels () const inline virtual
Returns the chosen levels formatted as a parsable string.
The string returned by this function can be parsed by the set_desired_levels() function.
Returns
The chosen levels formatted as a parsable string.
Definition at line 501 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, and FEAT::stringify().
format_desired_levels()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_desired_levels () const inline virtual
Returns the desired levels formatted as a parsable string.
The string returned by this function can be parsed by the set_desired_levels() function.
Returns
The desired levels formatted as a parsable string.
Definition at line 480 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, and FEAT::stringify().
front() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front () inline inherited
Definition at line 589 of file domain_control.hpp.
front() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front () const inline inherited
Definition at line 594 of file domain_control.hpp.
front_layer() [1/2]
LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front_layer () inline inherited
Definition at line 509 of file domain_control.hpp.
front_layer() [2/2]
const LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front_layer () const inline inherited
Definition at line 514 of file domain_control.hpp.
get_adapt_mode()
template<typename DomainLevel_ > Geometry::AdaptMode FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_adapt_mode () const inline
Gets the adapt-mode for refinement.
Returns
The adapt-mode that is used.
Definition at line 304 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode.
get_ancestry()
template<typename DomainLevel_ > const std::deque< Ancestor > & FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_ancestry () const inline
Returns a const reference to the ancestry.
Definition at line 606 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry.
get_atlas() [1/2]
AtlasType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::get_atlas () inline inherited
Definition at line 609 of file domain_control.hpp.
get_atlas() [2/2]
const AtlasType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::get_atlas () const inline inherited
Definition at line 614 of file domain_control.hpp.
get_chosen_levels()
template<typename DomainLevel_ > const std::deque< std::pair< int, int > > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_levels () const inline
Returns the deque of chosen refinement levels.
Returns
The deque of chosen refinement levels.
Definition at line 563 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels.
get_chosen_parti_info()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_parti_info () const inline virtual
Returns an informative string about the chosen partitioning.
Note
This function only returns something useful after the #create() function has been called.
In the case of a multi-layered recursive partitioning, the returned string is a multi-line string containing the partitioning info for each recursive layer in a separate line.
Definition at line 527 of file parti_domain_control_base.hpp.
References FEAT::stringify().
get_desired_level_max()
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_max () const inline
Returns the desired maximum refinement level.
Returns
The desired maximum refinement level
Definition at line 458 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
get_desired_level_min()
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_min () const inline
Returns the desired minimum refinement level.
Returns
The desired minimum refinement level
Definition at line 468 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
get_desired_levels()
template<typename DomainLevel_ > const std::deque< std::pair< int, int > > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_levels () const inline
Returns the deque of desired refinement levels.
Returns
The deque of desired refinement levels.
Definition at line 553 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
has_ghost()
bool FEAT::Control::Domain::DomainControl< DomainLevel_ >::has_ghost () const inline inherited
Todo:
does this really work?
Definition at line 554 of file domain_control.hpp.
keep_base_levels()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::keep_base_levels () inline inherited
Instructs the domain controller to keep the base-mesh levels after partitioning.
Calling this function requests the domain controller to keep the base-mesh levels and refine them even after the partitioning process. This functionality is required to assemble a Global::Splitter object, which allows to serialize and deserialize vectors independent of the partitioning used to create the vector.
Attention
The functionality requested by this function is NOT scalable for large process counts, i.e. the root process WILL run out of memory in large-scale simulations. This functionality should only be used for moderate process counts.
Definition at line 632 of file domain_control.hpp.
max_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::max_level_index () const inline inherited
Definition at line 534 of file domain_control.hpp.
med_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::med_level_index () const inline inherited
Definition at line 539 of file domain_control.hpp.
min_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::min_level_index () const inline inherited
Definition at line 529 of file domain_control.hpp.
name()
static String FEAT::Control::Domain::DomainControl< DomainLevel_ >::name () inline static inherited
Definition at line 448 of file domain_control.hpp.
num_global_layers()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::num_global_layers () const inline inherited
Definition at line 493 of file domain_control.hpp.
num_local_layers()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::num_local_layers () const inline inherited
Definition at line 488 of file domain_control.hpp.
parse_args()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args (SimpleArgParser & args) inline virtual
Parses the partitioner options from an argument parser.
See also
Control::Domain::add_supported_pdc_args()
Parameters
[in] args The parser that is to be used.
Returns
true, if the parsing was successful, or false, if at least one option was invalid.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 188 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::SimpleArgParser::parse(), FEAT::Dist::Comm::print(), FEAT::SimpleArgParser::query(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args().
parse_property_map()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map (PropertyMap & pmap) inline virtual
Parses the partitioner options from a PropertyMap.
Parameters
[in] pmap A transient reference to the property map that contains the configuration
Returns
true, if the parsing was successful, or false, if at least one option was invalid.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 232 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::print(), FEAT::PropertyMap::query(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
print()
virtual void FEAT::Control::Domain::DomainControl< DomainLevel_ >::print () const inline virtual inherited
Definition at line 453 of file domain_control.hpp.
push_layer()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_layer (std::shared_ptr< LayerType > layer) inline inherited
Definition at line 498 of file domain_control.hpp.
push_level_back()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_level_back (int layer_index, std::shared_ptr< LevelType > level) inline inherited
Definition at line 549 of file domain_control.hpp.
push_level_front()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_level_front (int layer_index, std::shared_ptr< LevelType > level) inline inherited
Definition at line 544 of file domain_control.hpp.
serialize_partitioning()
template<typename DomainLevel_ > std::vector< char > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::serialize_partitioning () const inline
Serializes the partitioning information into a binary buffer.
Definition at line 614 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::allreduce(), FEAT::BinaryStream::container(), FEAT::Dist::Comm::gather(), FEAT::Dist::op_max, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
set_adapt_mode()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode (Geometry::AdaptMode adapt_mode) inline
Sets the adapt-mode for refinement.
Parameters
[in] adapt_mode The adapt-mode that is to be used.
Definition at line 292 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, and XASSERTM.
set_desired_levels() [1/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (const std::deque< String > & slvls) inline virtual
Sets the desired levels for the partitioned hierarchy.
Parameters
[in] slvls A transient reference to the deque of strings containing the desired levels.
Each entry of the deque is supposed to be in the format level:nprocs.
Definition at line 329 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), FEAT::stringify(), and XASSERTM.
set_desired_levels() [2/4]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (const String & slvls) inline
Sets the desired levels for the partitioned hierarchy.
Parameters
[in] slvls A string containing the list of desired levels.
Definition at line 315 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels(), and FEAT::String::split_by_whitespaces().
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels().
set_desired_levels() [3/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (int lvl_max, int lvl_med, int lvl_min) inline virtual
Sets the desired refinement levels for a double-layered hierarchy.
Parameters
[in] lvl_max The desired maximum refinement level. Must be >= 0.
[in] lvl_med The desired median refinement level. Must be < lvl_max If < 0, then (lvl_max+lvl_med+1) is used as the median level.
[in] lvl_min The desired minimum refinement level. Must be <= lvl_med. If < 0, then (lvl_med+lvl_min+1) is used as the minimum level.
Definition at line 429 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), and XASSERTM.
set_desired_levels() [4/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (int lvl_max, int lvl_min = -1) inline virtual
Sets the desired refinement levels for a single-layered hierarchy.
Parameters
[in] lvl_max The desired maximum refinement level. Must be >= 0.
[in] lvl_min The desired minimum refinement level. Must be <= lvl_max. If < 0, then (lvl_max+lvl_min+1) is used as the minimum level.
Definition at line 399 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), and XASSERTM.
size_physical()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::size_physical () const inline inherited
Definition at line 569 of file domain_control.hpp.
size_virtual()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::size_virtual () const inline inherited
Definition at line 564 of file domain_control.hpp.
Member Data Documentation
_adapt_mode
template<typename DomainLevel_ > Geometry::AdaptMode FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode protected
the adapt mode for refinement
Definition at line 114 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_adapt_mode(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode().
_allow_parti_genetic
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic protected
allow genetic partitioner?
Definition at line 119 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_metis
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis protected
allow metis partitioner?
Definition at line 117 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_naive
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive protected
allow naive partitioner?
Definition at line 121 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_zoltan
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan protected
allow Zoltan partitioner?
Definition at line 123 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_ancestry
template<typename DomainLevel_ > std::deque<Ancestor> FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry protected
the partition ancestry deque
Definition at line 142 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_ancestry().
_atlas
AtlasType FEAT::Control::Domain::DomainControl< DomainLevel_ >::_atlas protected inherited
Definition at line 424 of file domain_control.hpp.
_base_levels
std::deque<std::shared_ptr<LevelType> > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_base_levels protected inherited
Definition at line 426 of file domain_control.hpp.
_chosen_levels
template<typename DomainLevel_ > std::deque<std::pair<int,int> > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels protected
chosen level deque
Definition at line 132 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_chosen_levels(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_levels().
_comm
const Dist::Comm& FEAT::Control::Domain::DomainControl< DomainLevel_ >::_comm protected inherited
Definition at line 423 of file domain_control.hpp.
_desired_levels
template<typename DomainLevel_ > std::deque<std::pair<int,int> > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels protected
desired level deque
Definition at line 129 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_slag_mask(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_scattered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_desired_levels(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_min(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_levels(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels().
_genetic_time_init
template<typename DomainLevel_ > double FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init protected
time for genetic partitioner initialization
Definition at line 137 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_genetic_time_mutate
template<typename DomainLevel_ > double FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate protected
time for genetic partitioner mutation
Definition at line 139 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_keep_base_levels
bool FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels protected inherited
keep base-mesh levels on root process?
Definition at line 433 of file domain_control.hpp.
_layer_levels
std::deque<std::deque<std::shared_ptr<LevelType> > > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_layer_levels protected inherited
Definition at line 427 of file domain_control.hpp.
_layers
std::deque<std::shared_ptr<LayerType> > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_layers protected inherited
Definition at line 425 of file domain_control.hpp.
_num_global_layers
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::_num_global_layers protected inherited
Definition at line 429 of file domain_control.hpp.
_required_elems_per_rank
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank protected
required number of elements per rank for a-posteriori partitioning
Definition at line 135 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_support_multi_layered
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_support_multi_layered protected
support multi-layered hierarchy?
Definition at line 126 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy().
_virt_levels
std::deque<VirtLevelType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::_virt_levels protected inherited
Definition at line 428 of file domain_control.hpp.
_virt_size
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::_virt_size protected inherited
Definition at line 430 of file domain_control.hpp.
_was_created
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created protected
specifies whether the domain control was already created
Definition at line 112 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_rectilinear(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_permutation_strategy().
The documentation for this class was generated from the following file:
control/domain/parti_domain_control_base.hpp