FEAT: FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ > Class Template Reference
FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ > Class Template Reference abstract
Base-Class for solvers/preconditioners borrowed from HYPRE library.
#include <hypre.hpp>
Public Types
typedef ADPSolverBase< Matrix_, Filter_, SolverBase_ > BaseClass
our base-class
typedef MatrixType::DataType DataType
our internal data type
typedef Filter_ FilterType
the (local) filter type
typedef MatrixType::IndexType IndexType
our internal index type
typedef Matrix_ MatrixType
this specialization expects a local matrix
typedef BaseClass::VectorType VectorType
Public Member Functions
virtual Status apply (Vector_ &vec_cor, const Vector_ &vec_def)=0
Solver application method.
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic () override
Symbolic Finalization.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric Initialization.
virtual void init_symbolic () override
Symbolic Initialization.
virtual String name () const =0
Returns a descriptive string.
Protected Member Functions
HypreSolverBase (const Matrix_ &matrix, const Filter_ &filter)
void _download_cor (VectorType &vec_cor)
Downloads the HYPRE correction vector.
template<typename DTV_ >
void _download_vector (LocalVectorType &vector, const DTV_ *val)
Downloads the ADP vector values from the given array.
template<typename DTV_ >
void _download_vector (VectorType &vector, const DTV_ *val)
Downloads the ADP vector values from the given array.
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const Global::MeanFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const LAFEM::MeanFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *, const RPT_ *, const CIT_ *, const LAFEM::NoneFilter< DataType, IndexType > &)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterChain< First_ > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ , typename... Rest_>
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterChain< First_, Rest_... > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ , typename SubFilter_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::FilterSequence< SubFilter_ > &filter)
auxiliary function: filters the local ADP matrix
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _filter_mat (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx, const LAFEM::UnitFilter< DataType, IndexType > &filter)
auxiliary function: filters the local ADP matrix
void _format_cor ()
Formats the HYPRE correction vector to zero.
Index _get_adp_matrix_num_cols () const
Index _get_adp_matrix_num_cols () const
Index _get_adp_matrix_num_nzes () const
Index _get_adp_matrix_num_nzes () const
Index _get_adp_matrix_num_rows () const
Index _get_adp_matrix_num_rows () const
Index _get_adp_vector_size () const
Index _get_adp_vector_size () const
const Dist::Comm * _get_comm () const
const Dist::Comm * _get_comm () const
Index _get_global_dof_offset () const
Index _get_global_dof_offset () const
Index _get_num_global_dofs () const
Index _get_num_global_dofs () const
Index _get_num_global_nonzeros () const
Index _get_num_global_nonzeros () const
Index _get_num_owned_dofs () const
Index _get_num_owned_dofs () const
void _upload_def (const VectorType &vec_def)
Uploads the HYPRE defect vector.
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _upload_numeric (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx)
Uploads the (filtered) ADP matrix values to the given array.
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _upload_numeric (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx)
Uploads the (filtered) ADP matrix values to the given array.
template<typename RPT_ , typename CIT_ >
void _upload_symbolic (RPT_ *row_ptr, CIT_ *col_idx)
Uploads the ADP matrix structure to the given arrays.
template<typename RPT_ , typename CIT_ >
void _upload_symbolic (RPT_ *row_ptr, CIT_ *col_idx)
Uploads the ADP matrix structure to the given arrays.
template<typename DTV_ >
void _upload_vector (DTV_ *val, const LocalVectorType &vector)
Uploads the ADP vector values to the given array.
template<typename DTV_ >
void _upload_vector (DTV_ *val, const VectorType &vector)
Uploads the ADP vector values to the given array.
Protected Attributes
Dist::Comm _comm_self
self-communicator object
void * _core
a pointer to our opaque core wrapper object
const FilterType & _system_filter
the system filter
const MatrixType & _system_matrix
the system matrix
Detailed Description
template<typename Matrix_, typename Filter_, typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>>
class FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >
Base-Class for solvers/preconditioners borrowed from HYPRE library.
This class acts as a base-class for all solvers that we borrow from the HYPRE library. As all our HYPRE solvers use the "IJ"-based ParCSR format, which corresponds to our "algebraic DOF partitioning", this class derives from the ADPSolverBase class, which takes care of the translation between the system matrix and the ADP data structures.
This base-class takes care of allocating, initializing and updating the required HYPRE matrix and vector objects, which are outsourced into an opaque core wrapper object.
Author
Peter Zajac
Definition at line 105 of file hypre.hpp.
Member Typedef Documentation
BaseClass
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef ADPSolverBase<Matrix_, Filter_, SolverBase_> FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::BaseClass
our base-class
Definition at line 110 of file hypre.hpp.
DataType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef MatrixType::DataType FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::DataType inherited
our internal data type
Definition at line 767 of file adp_solver_base.hpp.
FilterType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef Filter_ FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::FilterType inherited
the (local) filter type
Definition at line 761 of file adp_solver_base.hpp.
IndexType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef MatrixType::IndexType FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::IndexType inherited
our internal index type
Definition at line 769 of file adp_solver_base.hpp.
MatrixType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef Matrix_ FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::MatrixType inherited
this specialization expects a local matrix
the (local) matrix type
Definition at line 757 of file adp_solver_base.hpp.
VectorType
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> typedef BaseClass::VectorType FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::VectorType
Definition at line 112 of file hypre.hpp.
Constructor & Destructor Documentation
HypreSolverBase()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::HypreSolverBase (const Matrix_ & matrix, const Filter_ & filter) inline explicit protected
Definition at line 118 of file hypre.hpp.
Member Function Documentation
_download_cor()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> void FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_download_cor (VectorType & vec_cor) inline protected
Downloads the HYPRE correction vector.
This function first queries the vector values from HYPRE into the internal buffer and then downloads the contents to the given correction vector.
Parameters
[out] vec_cor The correction vector to download to.
Definition at line 148 of file hypre.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_download_vector(), and FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_filter.
_download_vector() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_download_vector (LocalVectorType & vector, const DTV_ * val) protected inherited
Downloads the ADP vector values from the given array.
Parameters
[in,out] vector A transient reference to the local vector that receives the downloaded ADP value array. It is assumed to be allocated to the correct size, but its contents on entry are ignored.
[in] val A transient pointer to an array of length _get_adp_vector_size() that contains the ADP values that are to be downloaded to the output vector given by vector.
Referenced by FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_download_cor(), and FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::apply().
_download_vector() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_download_vector (VectorType & vector, const DTV_ * val) inline protected inherited
Downloads the ADP vector values from the given array.
Parameters
[in,out] vector A transient reference to the local vector that receives the downloaded ADP value array. It is assumed to be allocated to the correct size, but its contents on entry are ignored.
[in] val A transient pointer to an array of length _get_adp_vector_size() that contains the ADP values that are to be downloaded to the output vector given by vector.
Definition at line 933 of file adp_solver_base.hpp.
_filter_mat() [1/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const Global::MeanFilter< DataType, IndexType > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 971 of file adp_solver_base.hpp.
References XASSERTM.
_filter_mat() [2/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const LAFEM::MeanFilter< DataType, IndexType > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 963 of file adp_solver_base.hpp.
References XASSERTM.
_filter_mat() [3/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * , const RPT_ * , const CIT_ * , const LAFEM::NoneFilter< DataType, IndexType > &) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 940 of file adp_solver_base.hpp.
Referenced by FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_filter_mat(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_numeric(), and FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric().
_filter_mat() [4/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterChain< First_ > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 997 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [5/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ , typename First_ , typename... Rest_> void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterChain< First_, Rest_... > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 988 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [6/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ , typename SubFilter_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::FilterSequence< SubFilter_ > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 979 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat().
_filter_mat() [7/7]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx, const LAFEM::UnitFilter< DataType, IndexType > & filter) inline protected inherited
auxiliary function: filters the local ADP matrix
Definition at line 948 of file adp_solver_base.hpp.
_format_cor()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> void FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_format_cor () inline protected
Formats the HYPRE correction vector to zero.
Definition at line 158 of file hypre.hpp.
_get_adp_matrix_num_cols() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_cols () const protected inherited
Returns
The number of columns of the local ADP matrix; equal to _get_num_global_dofs()
_get_adp_matrix_num_cols() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_cols () const inline protected inherited
Returns
The number of columns of the local ADP matrix; equal to _get_num_global_dofs()
Definition at line 821 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_adp_matrix_num_nzes() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_nzes () const protected inherited
Returns
The number of nonzero entries of the local ADP matrix
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_adp_matrix_num_nzes() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_nzes () const inline protected inherited
Returns
The number of nonzero entries of the local ADP matrix
Definition at line 827 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_adp_matrix_num_rows() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_rows () const protected inherited
Returns
The number of rows of the local ADP matrix; equal to _get_num_owned_dofs()
_get_adp_matrix_num_rows() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_rows () const inline protected inherited
Returns
The number of rows of the local ADP matrix; equal to _get_num_owned_dofs()
Definition at line 815 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_adp_vector_size() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_vector_size () const protected inherited
Returns
The size of the local ADP vector; equal to _get_num_owned_dofs()
Referenced by FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_download_vector(), and FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_vector().
_get_adp_vector_size() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_vector_size () const inline protected inherited
Returns
The size of the local ADP vector; equal to _get_num_owned_dofs()
Definition at line 809 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_comm() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const Dist::Comm * FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_comm () const protected inherited
Returns
A pointer to the underlying communicator
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::init_symbolic(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_comm() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const Dist::Comm * FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_comm () const inline protected inherited
Returns
A pointer to the underlying (self) communicator
Definition at line 803 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_comm_self.
_get_global_dof_offset() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_global_dof_offset () const protected inherited
Returns
The index of the first global DOF owned by this process
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_global_dof_offset() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_global_dof_offset () const inline protected inherited
Returns
The index of the first global DOF owned by this process
Definition at line 851 of file adp_solver_base.hpp.
_get_num_global_dofs() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_dofs () const protected inherited
Returns
The total number of global DOFs on all processes
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_matrix_num_cols(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_numeric(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_num_global_dofs() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_dofs () const inline protected inherited
Returns
The total number of global DOFs on all processes
Definition at line 839 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_num_global_nonzeros() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_nonzeros () const protected inherited
Returns
The total number of nonzero entries of the global ADP matrix
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), and FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack().
_get_num_global_nonzeros() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_nonzeros () const inline protected inherited
Returns
The total number of nonzero entries of the global ADP matrix
Definition at line 833 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_get_num_owned_dofs() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs () const protected inherited
Returns
The number of global DOFs owned by this process
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_matrix_num_rows(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_get_adp_vector_size(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_get_num_owned_dofs() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Index FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs () const inline protected inherited
Returns
The number of global DOFs owned by this process
Definition at line 845 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_upload_def()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> void FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_def (const VectorType & vec_def) inline protected
Uploads the HYPRE defect vector.
This function first uploads the given defect vector the internal buffer and notifies HYPRE that the vector values have changed.
Parameters
[in] vec_def The defect vector to be uploaded from.
Definition at line 133 of file hypre.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_vector().
_upload_numeric() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx) protected inherited
Uploads the (filtered) ADP matrix values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the filtered matrix values of the local ADP matrix.
[in] row_ptr A transient pointer to the row-pointer array of the ADP matrix as returned by the _upload_symbolic() function.
[in] col_idx A transient pointer to the column-index array of the ADP matrix as returned by the _upload_symbolic() function.
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_numeric(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_numeric().
_upload_numeric() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx) inline protected inherited
Uploads the (filtered) ADP matrix values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the filtered matrix values of the local ADP matrix.
[in] row_ptr A transient pointer to the row-pointer array of the ADP matrix as returned by the _upload_symbolic() function.
[in] col_idx A transient pointer to the column-index array of the ADP matrix as returned by the _upload_symbolic() function.
Definition at line 894 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_filter_mat(), and FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_upload_symbolic() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_symbolic (RPT_ * row_ptr, CIT_ * col_idx) protected inherited
Uploads the ADP matrix structure to the given arrays.
Parameters
[out] row_ptr A transient pointer to an array of length _get_adp_matrix_num_rows()+1 that receives the the row-pointer array of the local ADP matrix.
[out] col_idx A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the column index array of the local ADP matrix.
Referenced by FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_cudss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mkldss(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_mumps(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_superlu(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::_create_core_umfpack(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic(), and FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_symbolic().
_upload_symbolic() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_symbolic (RPT_ * row_ptr, CIT_ * col_idx) inline protected inherited
Uploads the ADP matrix structure to the given arrays.
Parameters
[out] row_ptr A transient pointer to an array of length _get_adp_matrix_num_rows()+1 that receives the the row-pointer array of the ADP matrix.
[out] col_idx A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the column index array of the ADP matrix.
Definition at line 868 of file adp_solver_base.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix.
_upload_vector() [1/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_vector (DTV_ * val, const LocalVectorType & vector) protected inherited
Uploads the ADP vector values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_vector_size() that receives the local ADP values of the input vector given by vector.
[in] vector A transient reference to the local vector that is to be uploaded to the ADP value array.
Referenced by FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_def(), and FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::apply().
_upload_vector() [2/2]
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_vector (DTV_ * val, const VectorType & vector) inline protected inherited
Uploads the ADP vector values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_vector_size() that receives the local ADP values of the input vector given by vector.
[in] vector A transient reference to the local vector that is to be uploaded to the ADP value array.
Definition at line 916 of file adp_solver_base.hpp.
apply()
template<typename Vector_ > virtual Status FEAT::Solver::SolverBase< Vector_ >::apply (Vector_ & vec_cor, const Vector_ & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, and FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >.
Referenced by FEAT::Solver::solve().
done()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric(), and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
done_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented in FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >.
Definition at line 246 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::done(), FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::done_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_numeric(), FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::done_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric().
done_symbolic()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> virtual void FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::done_symbolic () inline override virtual
Symbolic Finalization.
This function destroys all HYPRE objects managed by this class and resets all auxiliary vectors and pointers.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 221 of file hypre.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_symbolic(), and XASSERT.
init()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
init_numeric()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> virtual void FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_numeric () inline override virtual
Numeric Initialization.
This function uploads the numerical values of the ADP matrix, which is managed by the base-class, to the HYPRE matrix.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Reimplemented in FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, and FEAT::Solver::BoomerAMG< Matrix_, Filter_ >.
Definition at line 202 of file hypre.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric(), FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and XASSERT.
Referenced by FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >::init_numeric(), and FEAT::Solver::BoomerAMG< Matrix_, Filter_ >::init_numeric().
init_symbolic()
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> virtual void FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_symbolic () inline override virtual
Symbolic Initialization.
This function creates the HYPRE matrix and vector objects and initializes their structure/layout by using the algebraic DOF partitioning (ADP) that is managed by the base-class. This function also performs an initial upload of the matrix and vector values from the ADP structures (because HYPRE requires this), although these values may be undefined (but existent) at this point.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 173 of file hypre.hpp.
References FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_nzes(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_comm(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_global_dof_offset(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_symbolic(), FEAT::Solver::SolverBase< Vector_ >::init_symbolic(), and XASSERT.
name()
template<typename Vector_ > virtual String FEAT::Solver::SolverBase< Vector_ >::name () const pure virtual inherited
Returns a descriptive string.
Returns
A string describing the solver.
Implemented in FEAT::Solver::ALGLIBMinLBFGS< Functional_, Filter_ >, FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::BiCGStab< Matrix_, Filter_ >, FEAT::Solver::BiCGStabL< Matrix_, Filter_ >, FEAT::Solver::Chebyshev< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::Descent< Matrix_, Filter_ >, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::DirectSparseSolver< Matrix_, Filter_ >, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::FGMRES< Matrix_, Filter_ >, FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >, FEAT::Solver::GMRES< Matrix_, Filter_ >, FEAT::Solver::GroppPCG< Matrix_, Filter_ >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::IDRS< Matrix_, Filter_ >, FEAT::Solver::ILUPrecond< Matrix_, Filter_ >, FEAT::Solver::JacobiPrecond< Matrix_, Filter_ >, FEAT::Solver::MatrixPrecond< Matrix_, Filter_ >, FEAT::Solver::MKLDSS, FEAT::Solver::MQCLinesearch< Functional_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >, FEAT::Solver::NLCG< Functional_, Filter_ >, FEAT::Solver::NonlinearOperatorPrecondWrapper< NonlinearOperator_ >, FEAT::Solver::NLSD< Functional_, Filter_ >, FEAT::Solver::PCG< Matrix_, Filter_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >, FEAT::Solver::PCR< Matrix_, Filter_ >, FEAT::Solver::PipePCG< Matrix_, Filter_ >, FEAT::Solver::PMR< Matrix_, Filter_ >, FEAT::Solver::PolynomialPrecond< Matrix_, Filter_ >, FEAT::Solver::PreconWrapper< Matrix_, Filter_, Precon_ >, FEAT::Solver::PSD< Matrix_, Filter_ >, FEAT::Solver::QPenalty< Functional_ >, FEAT::Solver::RBiCGStab< Matrix_, Filter_ >, FEAT::Solver::RGCR< Matrix_, Filter_ >, FEAT::Solver::Richardson< Matrix_, Filter_ >, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SecantLinesearch< Functional_, Filter_ >, FEAT::Solver::SORPrecond< Matrix_, Filter_ >, FEAT::Solver::SSORPrecond< Matrix_, Filter_ >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >, FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::NLOptPrecond< OperatorType_::VectorType, Filter >, FEAT::Solver::NLOptPrecond< Operator_::VectorType, Filter_ >, and FEAT::Solver::NLOptPrecond< NonlinearOperator_::SystemLevelType::GlobalSystemVectorR, NonlinearOperator_::SystemLevelType::GlobalSystemFilter >.
Referenced by FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::_apply_precond(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::IterativeSolver< Vector_ >::_set_new_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), and FEAT::Solver::IterativeSolver< Vector_ >::_update_defect().
Member Data Documentation
_comm_self
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> Dist::Comm FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_comm_self protected inherited
self-communicator object
Many third-party libraries always expect a MPI_Comm object even if we operate only on a single MPI process, therefore this class creates a custom self-communicator that can be passed on to the third-party libraries.
Definition at line 779 of file adp_solver_base.hpp.
Referenced by FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_comm().
_core
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> void* FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_core protected
a pointer to our opaque core wrapper object
Definition at line 116 of file hypre.hpp.
Referenced by FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >::init_numeric(), and FEAT::Solver::BoomerAMG< Matrix_, Filter_ >::init_numeric().
_system_filter
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const FilterType& FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_filter protected inherited
the system filter
Definition at line 783 of file adp_solver_base.hpp.
Referenced by FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::_download_cor().
_system_matrix
template<typename Matrix_ , typename Filter_ , typename SolverBase_ = Solver::SolverBase<typename Matrix_::VectorTypeL>> const MatrixType& FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_system_matrix protected inherited
the system matrix
Definition at line 781 of file adp_solver_base.hpp.
Referenced by FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_cols(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_nzes(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_matrix_num_rows(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_adp_vector_size(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_dofs(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_global_nonzeros(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_get_num_owned_dofs(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_numeric(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_numeric(), FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::_upload_symbolic(), FEAT::Solver::ADPSolverBase< Matrix_, Filter_, SolverBase_ >::_upload_symbolic(), and FEAT::Solver::ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >::init_symbolic().
The documentation for this class was generated from the following file:
kernel/solver/hypre.hpp