FEAT: FEAT::Geometry::TargetSet Class Reference
FEAT::Geometry::TargetSet Class Reference
Target set class.
#include <target_set.hpp>
Public Member Functions
TargetSet ()
standard constructor
TargetSet (Index num_entities)
Constructor.
TargetSet (TargetSet &&other)
move constructor
virtual ~TargetSet ()
virtual destructor
std::size_t bytes () const
TargetSet clone () const
Index * get_indices ()
const Index * get_indices () const
Index get_num_entities () const
Returns the number of entities.
TargetSet & operator= (TargetSet &&other)
move-assignment operator
Index & operator[] (Index i)
Returns a target index.
const Index & operator[] (Index i) const
Returns a target index.
void permute_map (const Adjacency::Permutation &inv_perm)
Protected Member Functions
TargetSet (const std::vector< Index > &idx)
internal clone constructor
Protected Attributes
std::vector< Index > _indices
Index vector. _indices[i] = j means that entity i represents entity j in the parent.
Detailed Description
Target set class.
A MeshPart refers to its parent mesh through several TargetSets.
Author
Peter Zajac
Definition at line 28 of file target_set.hpp.
Constructor & Destructor Documentation
TargetSet() [1/4]
FEAT::Geometry::TargetSet::TargetSet (const std::vector< Index > & idx) inline explicit protected
internal clone constructor
Definition at line 35 of file target_set.hpp.
TargetSet() [2/4]
FEAT::Geometry::TargetSet::TargetSet () inline
standard constructor
Definition at line 42 of file target_set.hpp.
Referenced by clone().
TargetSet() [3/4]
FEAT::Geometry::TargetSet::TargetSet (Index num_entities) inline explicit
Constructor.
Parameters
[in] num_entities The number of entities that are to be indexed.
Definition at line 53 of file target_set.hpp.
TargetSet() [4/4]
FEAT::Geometry::TargetSet::TargetSet (TargetSet && other) inline
move constructor
Definition at line 59 of file target_set.hpp.
~TargetSet()
virtual FEAT::Geometry::TargetSet::~TargetSet () inline virtual
virtual destructor
Definition at line 77 of file target_set.hpp.
Member Function Documentation
bytes()
std::size_t FEAT::Geometry::TargetSet::bytes () const inline
Returns
The size of dynamically allocated memory in bytes.
Definition at line 88 of file target_set.hpp.
References _indices.
clone()
TargetSet FEAT::Geometry::TargetSet::clone () const inline
Returns
An independent clone of this target set object.
Definition at line 82 of file target_set.hpp.
References TargetSet().
get_indices() [1/2]
Index * FEAT::Geometry::TargetSet::get_indices () inline
Returns
A pointer to the target index array.
Definition at line 102 of file target_set.hpp.
References _indices.
get_indices() [2/2]
const Index * FEAT::Geometry::TargetSet::get_indices () const inline
Returns
A pointer to the target index array.
Definition at line 108 of file target_set.hpp.
References _indices.
get_num_entities()
Index FEAT::Geometry::TargetSet::get_num_entities () const inline
Returns the number of entities.
Definition at line 94 of file target_set.hpp.
References _indices.
Referenced by FEAT::Geometry::PatchPartMap::PatchPartMap(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::_add_fbm_target_set(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_vertex_owners(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_synchronize(), FEAT::Geometry::PatchPartMap::build(), FEAT::Geometry::PatchPartMap::fill_target_set(), operator[](), and FEAT::Assembly::StokesFBMAssembler< MeshType_ >::sync().
operator=()
TargetSet & FEAT::Geometry::TargetSet::operator= (TargetSet && other) inline
move-assignment operator
Definition at line 65 of file target_set.hpp.
References _indices, and FEAT::Geometry::other.
operator[]() [1/2]
Index & FEAT::Geometry::TargetSet::operator[] (Index i) inline
Returns a target index.
Parameters
[in] i The index of the entity whose target index is to be returned.
Returns
A reference to the target index of entity i.
Definition at line 122 of file target_set.hpp.
References _indices, ASSERT, and get_num_entities().
operator[]() [2/2]
const Index & FEAT::Geometry::TargetSet::operator[] (Index i) const inline
Returns a target index.
Parameters
[in] i The index of the entity whose target index is to be returned.
Returns
A reference to the target index of entity i.
Definition at line 129 of file target_set.hpp.
References _indices, ASSERT, and get_num_entities().
permute_map()
void FEAT::Geometry::TargetSet::permute_map (const Adjacency::Permutation & inv_perm) inline
Definition at line 135 of file target_set.hpp.
Member Data Documentation
_indices
std::vector<Index> FEAT::Geometry::TargetSet::_indices protected
Index vector. _indices[i] = j means that entity i represents entity j in the parent.
Definition at line 32 of file target_set.hpp.
Referenced by bytes(), get_indices(), get_num_entities(), operator=(), and operator[]().
The documentation for this class was generated from the following file:
kernel/geometry/target_set.hpp