FEAT: FEAT::Solver::GenericUmfpack< Matrix_ > Class Template Reference
FEAT::Solver::GenericUmfpack< Matrix_ > Class Template Reference abstract
Generic UMFPACK solver class.
#include <umfpack.hpp>
Public Types
typedef SolverBase< typename Matrix_::VectorTypeL > BaseClass
our base class
typedef Matrix_ MatrixType
our matrix type
typedef MatrixType::VectorTypeL VectorType
our vector type
Public Member Functions
GenericUmfpack (const MatrixType &matrix)
virtual ~GenericUmfpack ()
virtual destructor
virtual Status apply (Matrix_::VectorTypeL &vec_cor, const Matrix_::VectorTypeL &vec_def)=0
Solver application method.
virtual Status apply (VectorType &vec_sol, const VectorType &vec_rhs) override
virtual void done ()
Finalization method.
virtual void done_numeric () override
Numeric finalization method.
virtual void done_symbolic () override
Symbolic finalization method.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Numeric initialization method.
virtual void init_symbolic () override
Symbolic initialization method.
virtual String name () const override
Returns the name of the solver.
Protected Attributes
const MatrixType & _matrix
our matrix
LAFEM::DenseVector< typename VectorType::DataType, typename VectorType::IndexType > _tmp_vrhs
LAFEM::DenseVector< typename VectorType::DataType, typename VectorType::IndexType > _tmp_vsol
temporary vectors for datatype conversion
Umfpack::MatrixType _umf_matrix
the matrix for our Umfpack solver (SparseMatrixCSR<double, Index>)
Umfpack::VectorType _umf_vrhs
Umfpack::VectorType _umf_vsol
the vectors for our Umfpack solver (DenseVector<double, Index>)
Umfpack _umfpack
the actual Umfpack solver object
Detailed Description
template<typename Matrix_>
class FEAT::Solver::GenericUmfpack< Matrix_ >
Generic UMFPACK solver class.
This class effectively wraps around an Umfpack solver object
Attention
This class is only declared if FEAT was configured to build and link against the UMFPACK third-party library.
Author
Peter Zajac
Definition at line 647 of file umfpack.hpp.
Member Typedef Documentation
BaseClass
template<typename Matrix_ > typedef SolverBase<typename Matrix_::VectorTypeL> FEAT::Solver::GenericUmfpack< Matrix_ >::BaseClass
our base class
Definition at line 652 of file umfpack.hpp.
MatrixType
template<typename Matrix_ > typedef Matrix_ FEAT::Solver::GenericUmfpack< Matrix_ >::MatrixType
our matrix type
Definition at line 654 of file umfpack.hpp.
VectorType
template<typename Matrix_ > typedef MatrixType::VectorTypeL FEAT::Solver::GenericUmfpack< Matrix_ >::VectorType
our vector type
Definition at line 656 of file umfpack.hpp.
Constructor & Destructor Documentation
GenericUmfpack()
template<typename Matrix_ > FEAT::Solver::GenericUmfpack< Matrix_ >::GenericUmfpack (const MatrixType & matrix) inline explicit
Definition at line 671 of file umfpack.hpp.
~GenericUmfpack()
template<typename Matrix_ > virtual FEAT::Solver::GenericUmfpack< Matrix_ >::~GenericUmfpack () inline virtual
virtual destructor
Definition at line 678 of file umfpack.hpp.
Member Function Documentation
apply() [1/2]
virtual Status FEAT::Solver::SolverBase< Matrix_::VectorTypeL >::apply (Matrix_::VectorTypeL & vec_cor, const Matrix_::VectorTypeL & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::AmaVanka< Matrix_, Filter_ >.
apply() [2/2]
template<typename Matrix_ > virtual Status FEAT::Solver::GenericUmfpack< Matrix_ >::apply (VectorType & vec_sol, const VectorType & vec_rhs) inline override virtual
Definition at line 752 of file umfpack.hpp.
done()
virtual void FEAT::Solver::SolverBase< Matrix_::VectorTypeL >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
done_numeric()
template<typename Matrix_ > virtual void FEAT::Solver::GenericUmfpack< Matrix_ >::done_numeric () inline override virtual
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented from FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Definition at line 746 of file umfpack.hpp.
References FEAT::Solver::GenericUmfpack< Matrix_ >::_umfpack, FEAT::Solver::SolverBase< typename Matrix_::VectorTypeL >::done_numeric(), and FEAT::Solver::Umfpack::done_numeric().
done_symbolic()
template<typename Matrix_ > virtual void FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic () inline override virtual
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step.
Reimplemented from FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Definition at line 712 of file umfpack.hpp.
References FEAT::Solver::GenericUmfpack< Matrix_ >::_tmp_vsol, FEAT::Solver::GenericUmfpack< Matrix_ >::_umf_matrix, FEAT::Solver::GenericUmfpack< Matrix_ >::_umf_vsol, FEAT::Solver::GenericUmfpack< Matrix_ >::_umfpack, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Solver::SolverBase< typename Matrix_::VectorTypeL >::done_symbolic(), and FEAT::Solver::Umfpack::done_symbolic().
init()
virtual void FEAT::Solver::SolverBase< Matrix_::VectorTypeL >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
init_numeric()
template<typename Matrix_ > virtual void FEAT::Solver::GenericUmfpack< Matrix_ >::init_numeric () inline override virtual
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented from FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Definition at line 725 of file umfpack.hpp.
References FEAT::Solver::GenericUmfpack< Matrix_ >::_matrix, FEAT::Solver::GenericUmfpack< Matrix_ >::_umf_matrix, FEAT::Solver::GenericUmfpack< Matrix_ >::_umfpack, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::Solver::SolverBase< typename Matrix_::VectorTypeL >::init_numeric(), FEAT::Solver::Umfpack::init_numeric(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
init_symbolic()
template<typename Matrix_ > virtual void FEAT::Solver::GenericUmfpack< Matrix_ >::init_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Definition at line 688 of file umfpack.hpp.
References FEAT::Solver::GenericUmfpack< Matrix_ >::_matrix, FEAT::Solver::GenericUmfpack< Matrix_ >::_tmp_vsol, FEAT::Solver::GenericUmfpack< Matrix_ >::_umf_matrix, FEAT::Solver::GenericUmfpack< Matrix_ >::_umf_vsol, FEAT::Solver::GenericUmfpack< Matrix_ >::_umfpack, FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_l(), FEAT::Solver::SolverBase< typename Matrix_::VectorTypeL >::init_symbolic(), and FEAT::Solver::Umfpack::init_symbolic().
name()
template<typename Matrix_ > virtual String FEAT::Solver::GenericUmfpack< Matrix_ >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SolverBase< Matrix_::VectorTypeL >.
Definition at line 683 of file umfpack.hpp.
Member Data Documentation
_matrix
template<typename Matrix_ > const MatrixType& FEAT::Solver::GenericUmfpack< Matrix_ >::_matrix protected
our matrix
Definition at line 660 of file umfpack.hpp.
Referenced by FEAT::Solver::GenericUmfpack< Matrix_ >::init_numeric(), and FEAT::Solver::GenericUmfpack< Matrix_ >::init_symbolic().
_tmp_vrhs
template<typename Matrix_ > LAFEM::DenseVector<typename VectorType::DataType, typename VectorType::IndexType> FEAT::Solver::GenericUmfpack< Matrix_ >::_tmp_vrhs protected
Definition at line 666 of file umfpack.hpp.
_tmp_vsol
template<typename Matrix_ > LAFEM::DenseVector<typename VectorType::DataType, typename VectorType::IndexType> FEAT::Solver::GenericUmfpack< Matrix_ >::_tmp_vsol protected
temporary vectors for datatype conversion
Definition at line 666 of file umfpack.hpp.
Referenced by FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), and FEAT::Solver::GenericUmfpack< Matrix_ >::init_symbolic().
_umf_matrix
template<typename Matrix_ > Umfpack::MatrixType FEAT::Solver::GenericUmfpack< Matrix_ >::_umf_matrix protected
the matrix for our Umfpack solver (SparseMatrixCSR<double, Index>)
Definition at line 662 of file umfpack.hpp.
Referenced by FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::init_numeric(), and FEAT::Solver::GenericUmfpack< Matrix_ >::init_symbolic().
_umf_vrhs
template<typename Matrix_ > Umfpack::VectorType FEAT::Solver::GenericUmfpack< Matrix_ >::_umf_vrhs protected
Definition at line 664 of file umfpack.hpp.
_umf_vsol
template<typename Matrix_ > Umfpack::VectorType FEAT::Solver::GenericUmfpack< Matrix_ >::_umf_vsol protected
the vectors for our Umfpack solver (DenseVector<double, Index>)
Definition at line 664 of file umfpack.hpp.
Referenced by FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), and FEAT::Solver::GenericUmfpack< Matrix_ >::init_symbolic().
_umfpack
template<typename Matrix_ > Umfpack FEAT::Solver::GenericUmfpack< Matrix_ >::_umfpack protected
the actual Umfpack solver object
Definition at line 668 of file umfpack.hpp.
Referenced by FEAT::Solver::GenericUmfpack< Matrix_ >::done_numeric(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::init_numeric(), and FEAT::Solver::GenericUmfpack< Matrix_ >::init_symbolic().
The documentation for this class was generated from the following file:
kernel/solver/umfpack.hpp