FEAT: FEAT::Adjacency::Permutation Class Reference
FEAT::Adjacency::Permutation Class Reference
Permutation class.
#include <permutation.hpp>
Public Types
enum ConstrType {
type_none , type_identity , type_perm , type_swap ,
type_inv_perm , type_inv_swap
}
Construction type enumeration.
using IndexVector = std::vector< Index >
Public Member Functions
Permutation ()
default CTOR
Permutation (Index num_entries, ConstrType constr_type=type_none, const Index *v=nullptr)
Constructor.
Permutation (Index num_entries, Random &random)
Random constructor.
Permutation (Permutation &&other)
move ctor
virtual ~Permutation ()
virtual destructor
template<typename Tx_ >
void apply (Tx_ *x, bool invert=false) const
Applies In-Situ permutation.
template<typename Ty_ , typename Tx_ >
void apply (Ty_ *y, const Tx_ *x, bool invert=false) const
Applies permutation.
void calc_perm_from_swap ()
Computes the permutation-position vector from the swap-position vector.
void calc_swap_from_perm ()
Computes the swap-position vector from the permutation-position vector.
Permutation clone () const
Clones this permutation.
bool empty () const
Checks whether the permutation is empty.
Index * get_perm_pos ()
returns the permute-position array
const Index * get_perm_pos () const
returns the permute-position array
Index * get_swap_pos ()
returns the swap-position array
const Index * get_swap_pos () const
returns the swap-position array
Permutation inverse () const
Computes the inverse permutation.
template<typename IT_ >
IT_ map (IT_ i) const
Permutation & operator= (Permutation &&)
move-assign operator
Index size () const
returns the size of the permutation
Private Attributes
IndexVector _perm_pos
the permute-position vector
IndexVector _swap_pos
the swap-position vector
Detailed Description
Permutation class.
Author
Peter Zajac
Definition at line 26 of file permutation.hpp.
Member Typedef Documentation
IndexVector
using FEAT::Adjacency::Permutation::IndexVector = std::vector < Index>
Definition at line 29 of file permutation.hpp.
Member Enumeration Documentation
ConstrType
enum FEAT::Adjacency::Permutation::ConstrType
Construction type enumeration.
Enumerator
type_none
create uninitialized permutation
type_identity
create identity permutation
type_perm
create from permutation array
type_swap
create from swap array
type_inv_perm
create from inverse permutation array
type_inv_swap
create from inverse swap array
Definition at line 32 of file permutation.hpp.
Constructor & Destructor Documentation
Permutation() [1/4]
FEAT::Adjacency::Permutation::Permutation () inline
default CTOR
Definition at line 56 of file permutation.hpp.
Referenced by clone(), and inverse().
Permutation() [2/4]
FEAT::Adjacency::Permutation::Permutation (Index num_entries, ConstrType constr_type = type_none, const Index * v = nullptr) explicit
Constructor.
Parameters
[in] num_entries The size of the permutation to be created.
[in] constr_type Specifies the construction type:
type_none
Create an uninitialized permutation.
The permutation array has to be set up after the object is created.
The input array v is ignored.
type_identity
Create an identity permutation.
The input array v is ignored.
type_perm
Interpret the input vector as a permute-position vector.
type_swap
Interpret the input vector as a swap-position vector.
type_inv_perm
Interpret the input array as an inverse permute-position array.
type_inv_swap
Interpret the input array as an inverse swap-position array.
[in] v The transient input array for the initialization. The interpretation of the array's content depends on the constr_type parameter.
Definition at line 14 of file permutation.cpp.
References _perm_pos, _swap_pos, calc_perm_from_swap(), calc_swap_from_perm(), type_identity, type_inv_perm, type_inv_swap, type_none, type_perm, type_swap, and XASSERTM.
Permutation() [3/4]
FEAT::Adjacency::Permutation::Permutation (Index num_entries, Random & random) explicit
Random constructor.
This constructor creates a random permutation using a random number generator.
Parameters
[in] num_entries The size of the permutation to be created.
[in] random The transient random number generator to be used.
Definition at line 93 of file permutation.cpp.
References _swap_pos, calc_perm_from_swap(), and XASSERTM.
Permutation() [4/4]
FEAT::Adjacency::Permutation::Permutation (Permutation && other)
move ctor
Definition at line 106 of file permutation.cpp.
~Permutation()
FEAT::Adjacency::Permutation::~Permutation () virtual
virtual destructor
Definition at line 123 of file permutation.cpp.
Member Function Documentation
apply() [1/2]
template<typename Tx_ > void FEAT::Adjacency::Permutation::apply (Tx_ * x, bool invert = false) const inline
Applies In-Situ permutation.
This member function applies the permutation in-situ.
Parameters
[in,out] x The transient array that is to be permuted.
[in] invert Specifies whether to apply the forward (false) or inverse (true) permutation.
Warning
The function does not check, whether the referenced array x is large enough!
Definition at line 200 of file permutation.hpp.
References _swap_pos, ASSERTM, size(), and XASSERT.
Referenced by calc_perm_from_swap(), FEAT::LAFEM::DenseVector< DT_, IT_ >::permute(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::permute(), and FEAT::Geometry::IndexSet< num_indices_ >::permute().
apply() [2/2]
template<typename Ty_ , typename Tx_ > void FEAT::Adjacency::Permutation::apply (Ty_ * y, const Tx_ * x, bool invert = false) const inline
Applies permutation.
This function applies the permutation on an array.
Parameters
[out] y The transient array that shall receive the permuted array.
[in] x The transient array that is to be permuted.
[in] invert Specifies whether to apply the forward (false) or inverse (true) permutation.
Warning
The function does not check, whether the referenced arrays x and y are large enough!
Definition at line 254 of file permutation.hpp.
References _perm_pos, size(), and XASSERT.
calc_perm_from_swap()
void FEAT::Adjacency::Permutation::calc_perm_from_swap ()
Computes the permutation-position vector from the swap-position vector.
Definition at line 140 of file permutation.cpp.
References _perm_pos, apply(), and size().
Referenced by Permutation().
calc_swap_from_perm()
void FEAT::Adjacency::Permutation::calc_swap_from_perm ()
Computes the swap-position vector from the permutation-position vector.
Definition at line 126 of file permutation.cpp.
References _perm_pos, _swap_pos, and size().
Referenced by Permutation(), and FEAT::Adjacency::CuthillMcKee::compute().
clone()
Permutation FEAT::Adjacency::Permutation::clone () const inline
Clones this permutation.
Returns
A deep-copy of this permutation
Definition at line 116 of file permutation.hpp.
References Permutation(), _perm_pos, size(), and type_perm.
empty()
bool FEAT::Adjacency::Permutation::empty () const inline
Checks whether the permutation is empty.
Definition at line 145 of file permutation.hpp.
References _perm_pos.
Referenced by FEAT::Assembly::SymbolicAssembler::assemble_graph_intermesh(), FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::GridTransfer::assemble_truncation(), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::permute(), FEAT::Geometry::IndexSet< num_indices_ >::permute(), FEAT::Assembly::GridTransfer::prolongate_vector(), and FEAT::Geometry::MeshPermutation< Shape_ >::validate_sizes().
get_perm_pos() [1/2]
Index * FEAT::Adjacency::Permutation::get_perm_pos () inline
returns the permute-position array
Definition at line 151 of file permutation.hpp.
References _perm_pos.
Referenced by FEAT::Adjacency::Graph::Graph(), FEAT::Adjacency::CuthillMcKee::compute(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute().
get_perm_pos() [2/2]
const Index * FEAT::Adjacency::Permutation::get_perm_pos () const inline
returns the permute-position array
Definition at line 157 of file permutation.hpp.
References _perm_pos.
get_swap_pos() [1/2]
Index * FEAT::Adjacency::Permutation::get_swap_pos () inline
returns the swap-position array
Definition at line 163 of file permutation.hpp.
References _swap_pos.
get_swap_pos() [2/2]
const Index * FEAT::Adjacency::Permutation::get_swap_pos () const inline
returns the swap-position array
Definition at line 169 of file permutation.hpp.
References _swap_pos.
inverse()
Permutation FEAT::Adjacency::Permutation::inverse () const inline
Computes the inverse permutation.
Returns
The inverse permutation.
Definition at line 129 of file permutation.hpp.
References Permutation(), _perm_pos, size(), and type_inv_perm.
Referenced by FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute().
map()
template<typename IT_ > IT_ FEAT::Adjacency::Permutation::map (IT_ i) const inline
Definition at line 175 of file permutation.hpp.
operator=()
Permutation & FEAT::Adjacency::Permutation::operator= (Permutation && other)
move-assign operator
Definition at line 111 of file permutation.cpp.
References _perm_pos, and _swap_pos.
size()
Index FEAT::Adjacency::Permutation::size () const inline
returns the size of the permutation
Definition at line 138 of file permutation.hpp.
References _perm_pos, _swap_pos, and XASSERTM.
Referenced by apply(), calc_perm_from_swap(), calc_swap_from_perm(), clone(), inverse(), FEAT::LAFEM::DenseVector< DT_, IT_ >::permute(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute(), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::permute(), FEAT::Geometry::IndexSet< num_indices_ >::permute(), FEAT::Adjacency::Graph::permute_indices(), and FEAT::Geometry::MeshPermutation< Shape_ >::validate_sizes().
Member Data Documentation
_perm_pos
IndexVector FEAT::Adjacency::Permutation::_perm_pos private
the permute-position vector
Definition at line 50 of file permutation.hpp.
Referenced by Permutation(), apply(), calc_perm_from_swap(), calc_swap_from_perm(), clone(), empty(), get_perm_pos(), inverse(), operator=(), and size().
_swap_pos
IndexVector FEAT::Adjacency::Permutation::_swap_pos private
the swap-position vector
Definition at line 52 of file permutation.hpp.
Referenced by Permutation(), apply(), calc_swap_from_perm(), get_swap_pos(), operator=(), and size().
The documentation for this class was generated from the following files:
kernel/adjacency/permutation.hpp
kernel/adjacency/permutation.cpp