FEAT: FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > Class Template Reference
FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > Class Template Reference
Conformal mesh class template.
#include <conformal_mesh.hpp>
Classes
struct IndexSet
Index set type class template.
Public Types
typedef Coord_ CoordType
Coordinate type.
typedef IndexSetHolder< ShapeType > IndexSetHolderType
index set holder type
typedef MeshPermutation< ShapeType > MeshPermutationType
mesh permutation type
typedef IndexSet< shape_dim, shape_dim-1 >::Type NeighborSetType
index set type for storing neighbor adjacency information
typedef Shape_ ShapeType
Shape type.
typedef VertexSet< num_coords_, Coord_ > VertexSetType
Vertex set type.
typedef VertexSetType::VertexType VertexType
Vertex type.
Public Member Functions
ConformalMesh (ConformalMesh &&other)
move constructor
ConformalMesh (const ConformalMesh &)=delete
delete copy constructor
ConformalMesh (const Index num_entities[])
Constructor.
ConformalMesh (Factory< ConformalMesh > &factory)
Factory constructor.
virtual ~ConformalMesh ()
virtual destructor
std::size_t bytes () const
ConformalMesh clone () const
void clone (const ConformalMesh &other)
Clones another conformal mesh object into this object.
void create_permutation (PermutationStrategy strategy)
Creates a mesh permutation based on one of the standard permutation strategies.
void deduct_topology_from_top ()
Deducts the topology from the Vertex-At-Shape index set.
void fill_neighbors ()
Fills the neighbor index set.
template<int cell_dim_, int face_dim_>
IndexSet< cell_dim_, face_dim_ >::Type & get_index_set ()
Returns the reference to an index set.
template<int cell_dim_, int face_dim_>
const IndexSet< cell_dim_, face_dim_ >::Type & get_index_set () const
Returns the reference to an index set.
const MeshPermutationType & get_mesh_permutation () const
Returns a reference to the underlying mesh permutation object.
IndexSet< shape_dim, shape_dim-1 >::Type & get_neighbors ()
const IndexSet< shape_dim, shape_dim-1 >::Type & get_neighbors () const
Index get_num_elements () const
Returns the number of elements.
Index get_num_entities (int dim) const
Returns the number of entities.
Index get_num_vertices () const
Returns the number of vertices.
VertexSetType & get_vertex_set ()
Returns a reference to the vertex set of the mesh.
const VertexSetType & get_vertex_set () const
Returns a reference to the vertex set of the mesh.
bool is_permuted () const
Checks whether the mesh is permuted.
ConformalMesh & operator= (ConformalMesh &&other)
move-assignment operator
ConformalMesh & operator= (const ConformalMesh &)=delete
delete copy-assign operator
void reorient_boundary_facets ()
Ensures that all boundary facets are positively oriented.
void set_permutation (MeshPermutationType &&mesh_perm)
Sets a custom mesh permutation for this mesh.
void transform (const VertexType &origin, const VertexType &angles, const VertexType &offset)
Applies a "proper rigid" transformation onto the mesh.
bool validate_element_coloring () const
Validates the element coloring.
bool validate_element_layering () const
Validates the element layering.
Static Public Member Functions
static String name ()
Returns the name of the class.
Static Public Attributes
static constexpr bool is_structured = false
this mesh is not structured
static constexpr int shape_dim = ShapeType::dimension
shape dimension
static constexpr int world_dim = VertexSetType::num_coords
world dimension
Protected Attributes
IndexSetHolderType _index_set_holder
the index sets of the mesh
NeighborSetType _neighbors
Information about cells sharing a facet.
Index _num_entities [shape_dim+1]
number of entities for each shape dimension
MeshPermutationType _permutation
mesh permutation (if permuted)
VertexSetType _vertex_set
the vertex set of the mesh
Detailed Description
template<typename Shape_, int num_coords_ = Shape_::dimension, typename Coord_ = Real>
class FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >
Conformal mesh class template.
Todo:
detailed documentation
Template Parameters
Shape_ The shape that is to be used for the mesh. Must be either Shape::Simplex<n> or Shape::Hypercube<n> for some n > 0.
For more details on meshes, see the related doxygen page FEAT Mesh File Format.
Author
Peter Zajac
Definition at line 42 of file conformal_mesh.hpp.
Member Typedef Documentation
CoordType
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> typedef Coord_ FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::CoordType
Coordinate type.
Definition at line 51 of file conformal_mesh.hpp.
IndexSetHolderType
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> typedef IndexSetHolder<ShapeType> FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::IndexSetHolderType
index set holder type
Definition at line 60 of file conformal_mesh.hpp.
MeshPermutationType
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> typedef MeshPermutation<ShapeType> FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::MeshPermutationType
mesh permutation type
Definition at line 71 of file conformal_mesh.hpp.
NeighborSetType
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> typedef IndexSet<shape_dim,shape_dim-1>::Type FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::NeighborSetType
index set type for storing neighbor adjacency information
Definition at line 104 of file conformal_mesh.hpp.
ShapeType
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> typedef Shape_ FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ShapeType
Shape type.
Definition at line 48 of file conformal_mesh.hpp.
VertexSetType
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> typedef VertexSet<num_coords_, Coord_> FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::VertexSetType
Vertex set type.
Definition at line 54 of file conformal_mesh.hpp.
VertexType
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> typedef VertexSetType::VertexType FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::VertexType
Vertex type.
Definition at line 57 of file conformal_mesh.hpp.
Constructor & Destructor Documentation
ConformalMesh() [1/3]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ConformalMesh (const Index num_entities[]) inline explicit
Constructor.
Parameters
[in] num_entities An array of length at least shape_dim + 1 holding the number of entities for each shape dimension. Must not be nullptr.
Definition at line 130 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities, and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim.
ConformalMesh() [2/3]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ConformalMesh (Factory< ConformalMesh< Shape_, num_coords_, Coord_ > > & factory) inline explicit
Factory constructor.
Parameters
[in] factory A transient reference to the factory that is to be used to create the mesh.
Definition at line 149 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_index_set_holder, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_vertex_set, and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors().
ConformalMesh() [3/3]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ConformalMesh (ConformalMesh< Shape_, num_coords_, Coord_ > && other) inline
move constructor
Definition at line 174 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities, FEAT::Geometry::other, and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim.
~ConformalMesh()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> virtual FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::~ConformalMesh () inline virtual
virtual destructor
Definition at line 213 of file conformal_mesh.hpp.
Member Function Documentation
bytes()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> std::size_t FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::bytes () const inline
Returns
The size of dynamically allocated memory in bytes.
Definition at line 245 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_index_set_holder, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_neighbors, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_permutation, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_vertex_set, FEAT::Geometry::MeshPermutation< Shape_ >::bytes(), and FEAT::Geometry::VertexSet< num_coords_, Coord_ >::bytes().
clone() [1/2]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> ConformalMesh FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone () const inline
Returns
An independent clone of this mesh object.
Definition at line 234 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_index_set_holder, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_neighbors, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_permutation, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_vertex_set, FEAT::Geometry::VertexSet< num_coords_, Coord_ >::clone(), and FEAT::Geometry::MeshPermutation< Shape_ >::clone().
clone() [2/2]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> void FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone (const ConformalMesh< Shape_, num_coords_, Coord_ > & other) inline
Clones another conformal mesh object into this object.
Parameters
[in] other A transient reference to the source object that is to be cloned into this object.
Definition at line 223 of file conformal_mesh.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::clone(), FEAT::Geometry::other, and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim.
create_permutation()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> void FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::create_permutation (PermutationStrategy strategy) inline
Creates a mesh permutation based on one of the standard permutation strategies.
This function creates a new mesh permutation and also applies that permutation to the vertex set and all the index sets stored in this mesh object.
Parameters
[in] strategy The permutation strategy to use, see #MeshPermutation for more details.
Note
If you want to use a custom permutation other than one of the standard permutation strategies then use set_permutation() instead.
Attention
A mesh can only be permuted once and therefore this function will fire an assertion if the mesh is already permuted.
Definition at line 319 of file conformal_mesh.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::create(), FEAT::Geometry::MeshPermutation< Shape_ >::empty(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors(), FEAT::Geometry::MeshPermutation< Shape_ >::get_perm(), FEAT::Geometry::MeshPermutation< Shape_ >::get_perms(), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::permute(), and XASSERTM.
deduct_topology_from_top()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> void FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::deduct_topology_from_top () inline
Deducts the topology from the Vertex-At-Shape index set.
This function ensures that the deducted topology will have positively oriented facets. This function also computes the neighbor structures.
Definition at line 575 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_index_set_holder, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities, FEAT::Geometry::RedundantIndexSetBuilder< Shape_ >::compute(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::reorient_boundary_facets().
fill_neighbors()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> void FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors () inline
Fills the neighbor index set.
Definition at line 481 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_neighbors, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_index_set(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim, and XASSERTM.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ConformalMesh(), FEAT::Geometry::PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >::PartiIterative(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::create_permutation(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::deduct_topology_from_top(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::set_permutation().
get_index_set() [1/2]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> template<int cell_dim_, int face_dim_> IndexSet< cell_dim_, face_dim_ >::Type & FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_index_set () inline
Returns the reference to an index set.
Template Parameters
cell_dim_ The dimension of the entity whose index set is to be returned.
face_dim_ The dimension of the face that the index set refers to.
Returns
A reference to the index set.
Definition at line 533 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_index_set_holder.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors().
get_index_set() [2/2]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> template<int cell_dim_, int face_dim_> const IndexSet< cell_dim_, face_dim_ >::Type & FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_index_set () const inline
Returns the reference to an index set.
Template Parameters
cell_dim_ The dimension of the entity whose index set is to be returned.
face_dim_ The dimension of the face that the index set refers to.
Returns
A reference to the index set.
Definition at line 542 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_index_set_holder.
get_mesh_permutation()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> const MeshPermutationType & FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_mesh_permutation () const inline
Returns a reference to the underlying mesh permutation object.
Definition at line 297 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_permutation.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_coloring(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_layering().
get_neighbors() [1/2]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> IndexSet< shape_dim, shape_dim-1 >::Type & FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_neighbors () inline
Returns
A reference to the facet neighbor relations
Definition at line 495 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_neighbors.
Referenced by FEAT::Geometry::Intern::PartiIterativeIndividual< Shape_, num_coords_, Coord_ >::PartiIterativeIndividual(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell(), FEAT::Geometry::Intern::PartiIterativeIndividual< Shape_, num_coords_, Coord_ >::mutate(), and FEAT::Geometry::Intern::PartiIterativeIndividual< Shape_, num_coords_, Coord_ >::update_boundary_size().
get_neighbors() [2/2]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> const IndexSet< shape_dim, shape_dim-1 >::Type & FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_neighbors () const inline
Returns
A reference to the facet neighbor relations
Definition at line 501 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_neighbors.
get_num_elements()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> Index FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_elements () const inline
Returns the number of elements.
Returns
The number of elements.
Definition at line 279 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities, and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim.
get_num_entities()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> Index FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities (int dim) const inline
Returns the number of entities.
Parameters
[in] dim The dimension of the entity whose count is to be returned. Must be 0 <= dim <= shape_dim.
Returns
The number of entities of dimension dim.
Definition at line 259 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim, and XASSERT.
Referenced by FEAT::Geometry::MeshExtruderFactory< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::MeshExtruderFactory(), FEAT::Geometry::PatchHaloSplitter< ConformalMesh< Shape_, num_coords_, Coord_ > >::PatchHaloSplitter(), FEAT::Geometry::StandardRefinery< ConformalMesh< Shape_, num_coords_, CoordType_ > >::StandardRefinery(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_mapping(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell(), FEAT::Space::ExtVtkWriter< Trafo_ >::open(), FEAT::Space::ExtVtkWriter< Trafo_ >::write_gradients(), FEAT::Space::ExtVtkWriter< Trafo_ >::write_hessians(), FEAT::Geometry::MeshFileWriter::write_mesh(), FEAT::Space::ExtVtkWriter< Trafo_ >::write_values(), and FEAT::Space::ExtVtkWriter< Trafo_ >::write_values_blocked().
get_num_vertices()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> Index FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_vertices () const inline
Returns the number of vertices.
Returns
The number of vertices.
Definition at line 270 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities.
get_vertex_set() [1/2]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> VertexSetType & FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_vertex_set () inline
Returns a reference to the vertex set of the mesh.
Definition at line 507 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_vertex_set.
Referenced by FEAT::Geometry::StandardRefinery< ConformalMesh< Shape_, num_coords_, CoordType_ > >::fill_vertex_set(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell(), FEAT::Geometry::ExportEPS::write(), FEAT::Geometry::ExportSVG::write(), and FEAT::Geometry::MeshFileWriter::write_mesh().
get_vertex_set() [2/2]
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> const VertexSetType & FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_vertex_set () const inline
Returns a reference to the vertex set of the mesh.
Definition at line 513 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_vertex_set.
is_permuted()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> bool FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::is_permuted () const inline
Checks whether the mesh is permuted.
Returns
true if the mesh is permuted, otherwise false.
Definition at line 289 of file conformal_mesh.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::empty().
name()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> static String FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::name () inline static
Returns the name of the class.
Returns
The name of the class as a String.
Definition at line 630 of file conformal_mesh.hpp.
References FEAT::stringify().
operator=()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> ConformalMesh & FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::operator= (ConformalMesh< Shape_, num_coords_, Coord_ > && other) inline
move-assignment operator
Definition at line 187 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_index_set_holder, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_neighbors, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_permutation, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_vertex_set, FEAT::Geometry::other, and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim.
reorient_boundary_facets()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> void FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::reorient_boundary_facets () inline
Ensures that all boundary facets are positively oriented.
This function checks the orientation of each boundary facet and flips it if it is negatively oriented to obtain positive orientation on all boundary facets.
Definition at line 589 of file conformal_mesh.hpp.
References FEAT::Geometry::FacetFlipper< Shape_ >::reorient().
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::deduct_topology_from_top().
set_permutation()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> void FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::set_permutation (MeshPermutationType && mesh_perm) inline
Sets a custom mesh permutation for this mesh.
This function can be used to apply a mesh permutation that is created using some other approach than the predefined standard permutation strategies.
This function also applies that permutation to the vertex set and all the index sets stored in this mesh object.
Parameters
[in] mesh_perm The mesh permutation to use.
Attention
A mesh can only be permuted once and therefore this function will fire an assertion if the mesh is already permuted.
Definition at line 353 of file conformal_mesh.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::empty(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors(), FEAT::Geometry::MeshPermutation< Shape_ >::get_perm(), FEAT::Geometry::MeshPermutation< Shape_ >::get_perms(), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::permute(), and XASSERTM.
transform()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> void FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::transform (const VertexType & origin, const VertexType & angles, const VertexType & offset) inline
Applies a "proper rigid" transformation onto the mesh.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any vertex x of the vertex set:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any vertex before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): ignored
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any vertex after applying the rotation.
Definition at line 620 of file conformal_mesh.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_vertex_set, and FEAT::Geometry::VertexSet< num_coords_, Coord_ >::transform().
validate_element_coloring()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> bool FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_coloring () const inline
Validates the element coloring.
An element coloring is valid, if any pair of two different elements, which share at least one common vertex, have different colors.
Returns
true, if the element coloring is either valid or empty, otherwise false.
Definition at line 382 of file conformal_mesh.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::get_element_coloring(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_mesh_permutation(), FEAT::Adjacency::Graph::image_begin(), FEAT::Adjacency::Graph::image_end(), and FEAT::Adjacency::transpose.
validate_element_layering()
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> bool FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::validate_element_layering () const inline
Validates the element layering.
An element layering is valid, if any pair of two different elements, which share at least one common vertex, have different colors.
Returns
true, if the element layering is either valid or empty, otherwise false.
Definition at line 432 of file conformal_mesh.hpp.
References FEAT::Geometry::MeshPermutation< Shape_ >::get_element_layering(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_mesh_permutation(), FEAT::Adjacency::Graph::image_begin(), FEAT::Adjacency::Graph::image_end(), FEAT::Math::max(), FEAT::Math::min(), and FEAT::Adjacency::transpose.
Member Data Documentation
_index_set_holder
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> IndexSetHolderType FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_index_set_holder protected
the index sets of the mesh
Definition at line 114 of file conformal_mesh.hpp.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ConformalMesh(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::bytes(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::deduct_topology_from_top(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_index_set(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::operator=().
_neighbors
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> NeighborSetType FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_neighbors protected
Information about cells sharing a facet.
Definition at line 117 of file conformal_mesh.hpp.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::bytes(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_neighbors(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::operator=().
_num_entities
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> Index FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_num_entities[shape_dim+1] protected
number of entities for each shape dimension
Definition at line 108 of file conformal_mesh.hpp.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ConformalMesh(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::deduct_topology_from_top(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_elements(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_vertices(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::operator=().
_permutation
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> MeshPermutationType FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_permutation protected
mesh permutation (if permuted)
Definition at line 120 of file conformal_mesh.hpp.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::bytes(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_mesh_permutation(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::operator=().
_vertex_set
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> VertexSetType FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::_vertex_set protected
the vertex set of the mesh
Definition at line 111 of file conformal_mesh.hpp.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ConformalMesh(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::bytes(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_vertex_set(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::operator=(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::transform().
is_structured
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> constexpr bool FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::is_structured = false static constexpr
this mesh is not structured
Definition at line 68 of file conformal_mesh.hpp.
shape_dim
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> constexpr int FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::shape_dim = ShapeType::dimension static constexpr
shape dimension
Definition at line 63 of file conformal_mesh.hpp.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::ConformalMesh(), FEAT::Geometry::Intern::PartiIterativeIndividual< Shape_, num_coords_, Coord_ >::PartiIterativeIndividual(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::fill_neighbors(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_elements(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::Geometry::Intern::PartiIterativeIndividual< Shape_, num_coords_, Coord_ >::mutate(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::operator=(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_meshpart(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point(), and FEAT::Geometry::Intern::PartiIterativeIndividual< Shape_, num_coords_, Coord_ >::update_boundary_size().
world_dim
template<typename Shape_ , int num_coords_ = Shape_::dimension, typename Coord_ = Real> constexpr int FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::world_dim = VertexSetType::num_coords static constexpr
world dimension
Definition at line 65 of file conformal_mesh.hpp.
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::write().
The documentation for this class was generated from the following file:
kernel/geometry/conformal_mesh.hpp