FEAT: FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > > Class Template Reference
FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > > Class Template Reference
StandardRefinery implementation for StructuredMesh.
#include <structured_mesh.hpp>
Public Types
typedef StructuredMesh< shape_dim_, num_coords_, Coord_ > MeshType
mesh type
typedef MeshType::ShapeType ShapeType
shape type
typedef MeshType::VertexSetType VertexSetType
vertex set type
Public Member Functions
StandardRefinery (const MeshType &coarse_mesh)
Constructor.
virtual void fill_vertex_set (VertexSetType &vertex_set) override
Fills the vertex set.
virtual Index get_num_slices (int dir) override
Returns the number of slices.
Static Public Attributes
static constexpr int shape_dim = ShapeType::dimension
shape dimension
Protected Attributes
const MeshType & _coarse_mesh
coarse mesh reference
Index _num_slices_coarse [shape_dim]
number of slices in coarse mesh
Detailed Description
template<int shape_dim_, int num_coords_, typename Coord_>
class FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >
StandardRefinery implementation for StructuredMesh.
Author
Peter Zajac
Definition at line 350 of file structured_mesh.hpp.
Member Typedef Documentation
MeshType
template<int shape_dim_, int num_coords_, typename Coord_ > typedef StructuredMesh<shape_dim_, num_coords_, Coord_> FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::MeshType
mesh type
Definition at line 355 of file structured_mesh.hpp.
ShapeType
template<int shape_dim_, int num_coords_, typename Coord_ > typedef MeshType::ShapeType FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::ShapeType
shape type
Definition at line 357 of file structured_mesh.hpp.
VertexSetType
template<int shape_dim_, int num_coords_, typename Coord_ > typedef MeshType::VertexSetType FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::VertexSetType
vertex set type
Definition at line 359 of file structured_mesh.hpp.
Constructor & Destructor Documentation
StandardRefinery()
template<int shape_dim_, int num_coords_, typename Coord_ > FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::StandardRefinery (const MeshType & coarse_mesh) inline explicit
Constructor.
Parameters
[in] coarse_mesh A reference to the coarse mesh that is to be refined.
Definition at line 377 of file structured_mesh.hpp.
References FEAT::Geometry::StructuredMesh< shape_dim_, num_coords_, Coord_ >::get_num_slices().
Member Function Documentation
fill_vertex_set()
template<int shape_dim_, int num_coords_, typename Coord_ > virtual void FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::fill_vertex_set (VertexSetType & vertex_set) inline override virtual
Fills the vertex set.
Parameters
[in,out] vertex_set The vertex set whose coordinates are to be filled.
Implements FEAT::Geometry::Factory< StructuredMesh< shape_dim_, num_coords_, Coord_ > >.
Definition at line 406 of file structured_mesh.hpp.
References FEAT::Geometry::StructuredMesh< shape_dim_, num_coords_, Coord_ >::get_vertex_set().
get_num_slices()
template<int shape_dim_, int num_coords_, typename Coord_ > virtual Index FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::get_num_slices (int dir) inline override virtual
Returns the number of slices.
Parameters
[in] dir The direction of the slice whose count is to be returned.
Returns
The number of slices in direction dir.
Implements FEAT::Geometry::Factory< StructuredMesh< shape_dim_, num_coords_, Coord_ > >.
Definition at line 395 of file structured_mesh.hpp.
References FEAT::Geometry::StructuredMesh< shape_dim_, num_coords_, Coord_ >::get_num_slices().
Member Data Documentation
_coarse_mesh
template<int shape_dim_, int num_coords_, typename Coord_ > const MeshType& FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::_coarse_mesh protected
coarse mesh reference
Definition at line 366 of file structured_mesh.hpp.
_num_slices_coarse
template<int shape_dim_, int num_coords_, typename Coord_ > Index FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::_num_slices_coarse[shape_dim] protected
number of slices in coarse mesh
Definition at line 368 of file structured_mesh.hpp.
shape_dim
template<int shape_dim_, int num_coords_, typename Coord_ > constexpr int FEAT::Geometry::StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >::shape_dim = ShapeType::dimension static constexpr
shape dimension
Definition at line 362 of file structured_mesh.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/structured_mesh.hpp