FEAT: FEAT::Solver::QPenalty< Functional_ > Class Template Reference
FEAT::Solver::QPenalty< Functional_ > Class Template Reference abstract
Quadratic penalty iteration.
#include <qpenalty.hpp>
Public Types
typedef IterativeSolver< VectorType > BaseClass
Our base class.
typedef VectorType::DataType DataType
Underlying floating point type.
typedef Functional_ FunctionalType
The functional type.
typedef Functional_::VectorTypeR VectorType
The input vector type.
Public Member Functions
QPenalty (const QPenalty &)=delete
Explicitly delete the copy constructor.
QPenalty (const String &section_name, PropertyMap *section, FunctionalType &functional, std::shared_ptr< IterativeSolver< VectorType > > inner_solver)
Constructor using a PropertyMap.
QPenalty (FunctionalType &functional, std::shared_ptr< IterativeSolver< VectorType > > inner_solver, DataType initial_penalty_param=DataType(1))
Constructor.
virtual ~QPenalty ()
Virtual destructor.
virtual Status apply (Vector_ &vec_cor, const Vector_ &vec_def)=0
Solver application method.
virtual Status apply (VectorType &vec_cor, const VectorType &vec_def) override
Solver application method.
DataType calc_convergence_rate () const
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
DataType calc_defect_reduction () const
Computes the overall defect reduction factor: (defect_final / defect_inital)
virtual Status correct (VectorType &vec_sol, const VectorType &vec_rhs) override
Solver correction method.
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic () override
Symbolic initialization method.
DataType get_def_final () const
Returns the final defect.
DataType get_def_initial () const
Returns the initial defect.
DataType get_div_abs () const
Returns the absolute divergence.
DataType get_div_rel () const
Returns the relative divergence.
Index get_max_iter () const
Returns the maximum number of iterations.
Index get_min_iter () const
Returns the minimal number of iterations.
Index get_min_stag_iter () const
Returns the minimum stagnation iteration count.
Index get_num_iter () const
Returns number of performed iterations.
String get_plot_name () const
Returns the plot name of the solver.
DataType get_stag_rate () const
Returns the stagnation rate.
Status get_status () const
Returns the status.
virtual String get_summary () const
Returns a summary string.
DataType get_tol_abs () const
Returns the absolute tolerance.
DataType get_tol_abs_low () const
Returns the lower absolute tolerance.
DataType get_tol_rel () const
Returns the relative tolerance.
virtual void init ()
Initialization method.
virtual void init_numeric ()
Numeric initialization method.
virtual void init_symbolic () override
Symbolic initialization method.
bool is_converged () const
checks for convergence
bool is_converged (const DataType def_cur) const
checks for convergence
bool is_diverged () const
checks for divergence
bool is_diverged (const DataType def_cur) const
checks for divergence
virtual String name () const override
Returns a descriptive string.
virtual void plot_summary () const
Plot a summary of the last solver run.
void set_div_abs (DataType div_abs)
Sets the absolute divergence for the solver.
void set_div_rel (DataType div_rel)
Sets the relative divergence for the solver.
void set_initial_penalty_param (DataType initial_penalty_param)
Sets the initial penalty parameter.
void set_max_iter (Index max_iter)
Sets the maximum iteration count for the solver.
void set_min_iter (Index min_iter)
Sets the minimum iteration count for the solver.
void set_min_stag_iter (Index min_iter)
Sets the minimum stagnate iteration count for the solver.
void set_plot_interval (const Index plot_interval)
Sets the interval between two plot outputs, if any.
void set_plot_mode (const PlotMode plot_mode)
Sets the plot mode of the solver.
void set_plot_name (const String &plot_name)
Sets the plot name of the solver.
void set_stag_rate (DataType rate)
Sets the stagnation rate fot the solver.
void set_tol_abs (DataType tol_abs)
Sets the absolute tolerance for the solver.
void set_tol_abs_low (DataType tol_abs_low)
Sets the lower absolute tolerance for the solver.
void set_tol_penalty (DataType tol_penalty)
Sets the initial penalty parameter.
void set_tol_rel (DataType tol_rel)
Sets the relative tolerance for the solver.
void skip_defect_calc (bool skip)
Specifies whether defect calculation is allowed to be skipped.
Protected Member Functions
virtual Status _analyse_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag)
Internal function: analyse the current defect.
virtual Status _apply_intern (VectorType &vec_sol, const VectorType &vec_rhs)
Internal function, applies the solver.
virtual DataType _calc_def_norm (const VectorType &vec_def, const VectorType &vec_sol)
Computes the defect norm.
bool _plot_iter (Status st=Status::progress) const
Plot the current iteration?
virtual void _plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev)
Plots an iteration line.
bool _plot_summary () const
Plot summary?
void _print_line (const String &line) const
Prints a line.
bool _progress () const
Progress iteration?
void _set_comm (const Dist::Comm *comm)
Sets the communicator for the solver directly.
void _set_comm_by_matrix (const Matrix_ &matrix)
Sets the communicator for the solver from a matrix.
void _set_comm_by_vector (const Functional_::VectorTypeR &vector)
Sets the communicator for the solver from a vector.
Status _set_initial_defect (const DataType def_init_)
Internal function: sets the initial defect.
virtual Status _set_initial_defect (const VectorType &vec_def, const VectorType &vec_sol)
Makes the BaseClass' routine available, which cannot be used but shuts up the overloaded virtual warning.
virtual Status _set_new_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the new (next) defect vector.
virtual Status _update_defect (const DataType def_cur_norm)
Internal function: sets the new (next) defect norm.
Protected Attributes
const Dist::Comm * _comm
Communicator of the solver.
DataType _def_cur
current defect
DataType _def_init
initial defect
DataType _def_prev
previous iteration defect
DataType _div_abs
absolute divergence parameter
DataType _div_rel
relative divergence parameter
Index _iter_digits
iteration count digits for plotting
Index _max_iter
maximum number of iterations
Index _min_iter
minimum number of iterations
Index _min_stag_iter
minimum number of stagnation iterations
Index _num_iter
number of performed iterations
Index _num_stag_iter
number of consecutive stagnated iterations
Index _plot_interval
plot output interval
PlotMode _plot_mode
whether to plot something
String _plot_name
name of the solver in plots
bool _skip_def_calc
whether to skip defect computation if possible
DataType _stag_rate
stagnation rate
Status _status
current status of the solver
DataType _tol_abs
absolute tolerance parameter
DataType _tol_abs_low
absolute tolerance parameter
DataType _tol_rel
relative tolerance parameter
Private Attributes
FunctionalType & _functional
The functional that takes the penalty parameters and is assembled in the inner solver.
DataType _initial_penalty_param
We start with this initial penalty parameter.
std::shared_ptr< IterativeSolver< VectorType > > _inner_solver
The inner solver for the penalized, unconstrained optimization problem.
DataType _tol_penalty
Maximum value the penalty parameter is allowed to take.
Detailed Description
template<typename Functional_>
class FEAT::Solver::QPenalty< Functional_ >
Quadratic penalty iteration.
Template Parameters
Functional_ The functional (or functional) for the constrained optimization problem.
This class implements an outer solver for a quadratic penalty iteration. Assume we have an optimization problem of the form
\[ x^* = \mathrm{argmin}_{x \in D} f(x) ~ \mathrm{subject~to~} \forall i \in E: c_i(x) = 0 \]
\(c_i \) are equality constraints turning the minimization of \(f \) into a constrained optimization problem. To solve this constrained problem, one can solve a series of unconstrained problems with the quadratic penalty iteration by defining the quadratic penalty function
\[ Q(x,\mu) := f(x) + \frac{\mu}{2} \sum_{i \in E} c_i^2(x) \]
and solving it for a series \((\mu_k)_k \in \mathbb{N}, \mu_k \stackrel{k \to \infty}{\longrightarrow} \infty \). Because the penalty terms are smooth, tools from unconstrained optimization can be applied (see [NW06] Chapter 17.1). The greatest advantage of this is that this needs no constraint qualifications and is still applicable if \(\mathrm{dim}(\mathrm{ker} (\nabla c_{i_1}, \dots, \nabla c_{i_M})) > 0 \), which is required by all more sophisticated methods like augmented Lagragian etc.
All of this means that the Functional_ \(Q \) must be assembled anew in every iteration and the inner solver needs to take care of this.
One critical part is the choice of \(\mu_k\). It needs to start small (i.e. \(\mu_1 = 1\)) because the initial state might violate the constraints quite strongly. The rate of increase has to be fast enough that the number of penalty iterations remains small (i.e. \(\leq 10 \)), but the systematic ill-conditioning of the penalty function means that we cannot be too quick about this. If the increase is too quick, the previous iterate will be too far away of a minimizer of the new problem and the inner solver will fail to converge. So take care.
Author
Jordi Paul
Definition at line 49 of file qpenalty.hpp.
Member Typedef Documentation
BaseClass
template<typename Functional_ > typedef IterativeSolver<VectorType> FEAT::Solver::QPenalty< Functional_ >::BaseClass
Our base class.
Definition at line 59 of file qpenalty.hpp.
DataType
template<typename Functional_ > typedef VectorType::DataType FEAT::Solver::QPenalty< Functional_ >::DataType
Underlying floating point type.
Definition at line 57 of file qpenalty.hpp.
FunctionalType
template<typename Functional_ > typedef Functional_ FEAT::Solver::QPenalty< Functional_ >::FunctionalType
The functional type.
Definition at line 53 of file qpenalty.hpp.
VectorType
template<typename Functional_ > typedef Functional_::VectorTypeR FEAT::Solver::QPenalty< Functional_ >::VectorType
The input vector type.
Definition at line 55 of file qpenalty.hpp.
Constructor & Destructor Documentation
QPenalty() [1/2]
template<typename Functional_ > FEAT::Solver::QPenalty< Functional_ >::QPenalty (FunctionalType & functional, std::shared_ptr< IterativeSolver< VectorType > > inner_solver, DataType initial_penalty_param = DataType(1)) inline explicit
Constructor.
Parameters
[in] functional The functional for the inner constrained optimization problem.
[in] inner_solver The solver for the inner penalized unconstrained optimization problem.
[in] initial_penalty_param The starting penalty parameter, defaults to 1.
Definition at line 84 of file qpenalty.hpp.
References FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_comm_by_matrix().
QPenalty() [2/2]
template<typename Functional_ > FEAT::Solver::QPenalty< Functional_ >::QPenalty (const String & section_name, PropertyMap * section, FunctionalType & functional, std::shared_ptr< IterativeSolver< VectorType > > inner_solver) inline explicit
Constructor using a PropertyMap.
Template Parameters
Functional_ The type of the quadratic penalty function \(Q \).
Parameters
[in] section_name The name of the config section, which it does not know by itself.
[in] section A pointer to the PropertyMap section configuring this solver.
[in] functional The quadratic penalty function \(Q \).
[in] inner_solver The inner solver for solving the penalized unconstrained optimization problem.
Definition at line 114 of file qpenalty.hpp.
References FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_comm_by_matrix(), FEAT::PropertyMap::query(), FEAT::Solver::QPenalty< Functional_ >::set_initial_penalty_param(), and FEAT::Solver::QPenalty< Functional_ >::set_tol_penalty().
~QPenalty()
template<typename Functional_ > virtual FEAT::Solver::QPenalty< Functional_ >::~QPenalty () inline virtual
Virtual destructor.
Definition at line 144 of file qpenalty.hpp.
References FEAT::Solver::QPenalty< Functional_ >::_inner_solver.
Member Function Documentation
_analyse_defect()
virtual Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_analyse_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag) inline protected virtual inherited
Internal function: analyse the current defect.
Note
This function is called by _set_new_defect() and _update_defect().
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
[in] check_stag Specifies whether to check (and update) the stagnation criterion. This is typically set to false if one wants to check anything else than the 'true' next defect norm.
Returns
The updated status code.
Definition at line 799 of file iterative.hpp.
_apply_intern()
template<typename Functional_ > virtual Status FEAT::Solver::QPenalty< Functional_ >::_apply_intern (VectorType & vec_sol, const VectorType & vec_rhs) inline protected virtual
Internal function, applies the solver.
Parameters
[in,out] vec_sol The initial guess, gets overwritten by the solution
[in] vec_rhs The right-hand side.
Returns
A solver status code.
Definition at line 228 of file qpenalty.hpp.
References FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_cur, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_init, FEAT::Solver::QPenalty< Functional_ >::_functional, FEAT::Solver::QPenalty< Functional_ >::_inner_solver, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_iter_digits, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_max_iter, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_min_iter, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_iter, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_iter(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_name, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_print_line(), FEAT::Solver::QPenalty< Functional_ >::_set_initial_defect(), FEAT::Solver::QPenalty< Functional_ >::_tol_penalty, FEAT::Solver::aborted, FEAT::Solver::diverged, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_num_iter(), FEAT::Math::ilog10(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_converged(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_diverged(), FEAT::Math::isfinite(), FEAT::Math::max(), FEAT::Solver::max_iter, FEAT::Solver::QPenalty< Functional_ >::name(), FEAT::String::pad_front(), FEAT::Solver::progress, FEAT::Math::sqr(), FEAT::Solver::stagnated, FEAT::stringify(), FEAT::stringify_fp_sci(), FEAT::Solver::success, and FEAT::Solver::undefined.
Referenced by FEAT::Solver::QPenalty< Functional_ >::apply(), and FEAT::Solver::QPenalty< Functional_ >::correct().
_calc_def_norm()
virtual DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_calc_def_norm (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Computes the defect norm.
Parameters
[in] vec_def The current defect vector.
[in] vec_sol The current solution vector approximation.
Definition at line 652 of file iterative.hpp.
_plot_iter()
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_iter (Status st = Status::progress) const inline protected inherited
Plot the current iteration?
Parameters
[in] st The status of the current iteration.
Returns
true if the plot mode is set to iter or all and the plot interval matches or the solver does not continue to the next iteration
Definition at line 666 of file iterative.hpp.
_plot_iter_line()
virtual void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev) inline protected virtual inherited
Plots an iteration line.
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
Definition at line 719 of file iterative.hpp.
_plot_summary()
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_summary () const inline protected inherited
Plot summary?
Returns
true if the plot mode is set to summary or all.
Definition at line 677 of file iterative.hpp.
_print_line()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_print_line (const String & line) const inline protected inherited
Prints a line.
Parameters
[in] line The line to be printed.
Definition at line 698 of file iterative.hpp.
_progress()
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_progress () const inline protected inherited
Progress iteration?
Returns
true if the solver should process, otherwise false.
Definition at line 687 of file iterative.hpp.
_set_comm()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_comm (const Dist::Comm * comm) inline protected inherited
Sets the communicator for the solver directly.
Parameters
[in] comm A pointer to the communicator that is to be used by the solver.
Definition at line 613 of file iterative.hpp.
_set_comm_by_matrix()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_comm_by_matrix (const Matrix_ & matrix) inline protected inherited
Sets the communicator for the solver from a matrix.
Parameters
[in] matrix A reference to a matrix. If 'Matrix_' is a 'Global::Matrix', then the communicator of the matrix gate is taken.
Definition at line 626 of file iterative.hpp.
_set_comm_by_vector()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_comm_by_vector (const Functional_::VectorTypeR & vector) inline protected inherited
Sets the communicator for the solver from a vector.
Parameters
[in] vector A reference to a vector. If 'Vector_' is a 'Global::Vector', then the communicator of the vector gate is taken.
Definition at line 638 of file iterative.hpp.
_set_initial_defect() [1/2]
template<typename Functional_ > Status FEAT::Solver::QPenalty< Functional_ >::_set_initial_defect (const DataType def_init_) inline protected
Internal function: sets the initial defect.
Parameters
[in] def_init_ The initial constraint violation.
Returns
A Status code.
Definition at line 333 of file qpenalty.hpp.
References FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_cur, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_init, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_iter_digits, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_iter, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_stag_iter, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_iter(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_name, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_print_line(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_tol_abs, FEAT::Solver::aborted, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_num_iter(), FEAT::Math::isfinite(), FEAT::Solver::QPenalty< Functional_ >::name(), FEAT::String::pad_front(), FEAT::Solver::progress, FEAT::stringify(), FEAT::stringify_fp_sci(), and FEAT::Solver::success.
Referenced by FEAT::Solver::QPenalty< Functional_ >::_apply_intern().
_set_initial_defect() [2/2]
template<typename Functional_ > virtual Status FEAT::Solver::IterativeSolver< Vector_ >::_set_initial_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual
Makes the BaseClass' routine available, which cannot be used but shuts up the overloaded virtual warning.
Reimplemented from FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >.
Definition at line 748 of file iterative.hpp.
_set_new_defect()
virtual Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_new_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Internal function: sets the new (next) defect vector.
This function computes the defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] vec_def The new defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Definition at line 857 of file iterative.hpp.
_update_defect()
virtual Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_update_defect (const DataType def_cur_norm) inline protected virtual inherited
Internal function: sets the new (next) defect norm.
This function takes a precalculated defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] def_cur_norm The new defect norm.
Returns
The updated Status code.
Note
This function is preferred over _set_new_defect when using asynchronous mpi operations.
Definition at line 903 of file iterative.hpp.
apply() [1/2]
template<typename Vector_ > virtual Status FEAT::Solver::SolverBase< Vector_ >::apply (Vector_ & vec_cor, const Vector_ & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::CuSolverLU, FEAT::Solver::CuSolverQR, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, and FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >.
Referenced by FEAT::Solver::solve().
apply() [2/2]
template<typename Functional_ > virtual Status FEAT::Solver::QPenalty< Functional_ >::apply (VectorType & vec_cor, const VectorType & vec_def) inline override virtual
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Definition at line 190 of file qpenalty.hpp.
References FEAT::Solver::QPenalty< Functional_ >::_apply_intern(), FEAT::Solver::QPenalty< Functional_ >::_functional, FEAT::Solver::QPenalty< Functional_ >::_initial_penalty_param, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_status, and FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::plot_summary().
calc_convergence_rate()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::calc_convergence_rate () const inline inherited
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
Definition at line 528 of file iterative.hpp.
calc_defect_reduction()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::calc_defect_reduction () const inline inherited
Computes the overall defect reduction factor: (defect_final / defect_inital)
Definition at line 543 of file iterative.hpp.
correct()
template<typename Functional_ > virtual Status FEAT::Solver::QPenalty< Functional_ >::correct (VectorType & vec_sol, const VectorType & vec_rhs) inline override virtual
Solver correction method.
This method applies the solver represented by this object onto a given right-hand-side vector and updates the corresponding solution vector.
In contrast to the apply() method of the SolverBase base class, this method uses the vector vec_sol as the initial solution vector for the iterative solution process instead of ignoring its contents upon entry and starting with the null vector.
Parameters
[in,out] vec_sol The vector that contains the initial solution upon entry and receives the solution of the linear system upon exit.
[in] vec_rhs The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_sol and vec_rhs must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implements FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >.
Definition at line 204 of file qpenalty.hpp.
References FEAT::Solver::QPenalty< Functional_ >::_apply_intern(), FEAT::Solver::QPenalty< Functional_ >::_functional, FEAT::Solver::QPenalty< Functional_ >::_initial_penalty_param, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_status, and FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::plot_summary().
done()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 285 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric(), and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
done_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented in FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >.
Definition at line 248 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::done(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::done_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_numeric(), FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::done_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric().
done_symbolic()
template<typename Functional_ > virtual void FEAT::Solver::QPenalty< Functional_ >::done_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 163 of file qpenalty.hpp.
References FEAT::Solver::QPenalty< Functional_ >::_inner_solver, and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
get_def_final()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_def_final () const inline inherited
Returns the final defect.
Definition at line 516 of file iterative.hpp.
get_def_initial()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_def_initial () const inline inherited
Returns the initial defect.
Definition at line 510 of file iterative.hpp.
get_div_abs()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_div_abs () const inline inherited
Returns the absolute divergence.
Definition at line 363 of file iterative.hpp.
get_div_rel()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_div_rel () const inline inherited
Returns the relative divergence.
Definition at line 357 of file iterative.hpp.
get_max_iter()
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_max_iter () const inline inherited
Returns the maximum number of iterations.
Definition at line 418 of file iterative.hpp.
get_min_iter()
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_min_iter () const inline inherited
Returns the minimal number of iterations.
Definition at line 412 of file iterative.hpp.
get_min_stag_iter()
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_min_stag_iter () const inline inherited
Returns the minimum stagnation iteration count.
Definition at line 387 of file iterative.hpp.
get_num_iter()
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_num_iter () const inline inherited
Returns number of performed iterations.
Definition at line 406 of file iterative.hpp.
get_plot_name()
String FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_plot_name () const inline inherited
Returns the plot name of the solver.
Definition at line 467 of file iterative.hpp.
get_stag_rate()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_stag_rate () const inline inherited
Returns the stagnation rate.
Definition at line 375 of file iterative.hpp.
get_status()
Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_status () const inline inherited
Returns the status.
Definition at line 522 of file iterative.hpp.
get_summary()
virtual String FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_summary () const inline virtual inherited
Returns a summary string.
Reimplemented in FEAT::Solver::Linesearch< Functional_, Filter_ >.
Definition at line 556 of file iterative.hpp.
get_tol_abs()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_tol_abs () const inline inherited
Returns the absolute tolerance.
Definition at line 332 of file iterative.hpp.
get_tol_abs_low()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_tol_abs_low () const inline inherited
Returns the lower absolute tolerance.
Definition at line 338 of file iterative.hpp.
get_tol_rel()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_tol_rel () const inline inherited
Returns the relative tolerance.
Definition at line 326 of file iterative.hpp.
init()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 270 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
init_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init_numeric () inline virtual inherited
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented in FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::Chebyshev< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::ILUPrecond< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::JacobiPrecond< Matrix_, Filter_ >, FEAT::Solver::MatrixPrecond< Matrix_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NonlinearOperatorPrecondWrapper< NonlinearOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >, FEAT::Solver::PolynomialPrecond< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >, and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 239 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::init(), FEAT::Solver::Chebyshev< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::init_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::init_numeric(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::init_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::init_numeric(), FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_numeric(), and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::init_numeric().
init_symbolic()
template<typename Functional_ > virtual void FEAT::Solver::QPenalty< Functional_ >::init_symbolic () inline override virtual
Symbolic initialization method.
This method is called to perform symbolic initialization of the solver.
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 156 of file qpenalty.hpp.
References FEAT::Solver::QPenalty< Functional_ >::_inner_solver, and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
is_converged() [1/2]
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_converged () const inline inherited
checks for convergence
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Returns
true, if converged, else false
Definition at line 478 of file iterative.hpp.
is_converged() [2/2]
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_converged (const DataType def_cur) const inline inherited
checks for convergence
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Parameters
[in] def_cur The defect that is to be analysed
Returns
true, if converged, else false
Definition at line 492 of file iterative.hpp.
is_diverged() [1/2]
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_diverged () const inline inherited
checks for divergence
Definition at line 498 of file iterative.hpp.
is_diverged() [2/2]
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_diverged (const DataType def_cur) const inline inherited
checks for divergence
Definition at line 504 of file iterative.hpp.
name()
template<typename Functional_ > virtual String FEAT::Solver::QPenalty< Functional_ >::name () const inline override virtual
Returns a descriptive string.
Returns
A string describing the solver.
Implements FEAT::Solver::SolverBase< Vector_ >.
Definition at line 150 of file qpenalty.hpp.
Referenced by FEAT::Solver::QPenalty< Functional_ >::_apply_intern(), and FEAT::Solver::QPenalty< Functional_ >::_set_initial_defect().
plot_summary()
virtual void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::plot_summary () const inline virtual inherited
Plot a summary of the last solver run.
Definition at line 573 of file iterative.hpp.
set_div_abs()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_div_abs (DataType div_abs) inline inherited
Sets the absolute divergence for the solver.
Definition at line 351 of file iterative.hpp.
set_div_rel()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_div_rel (DataType div_rel) inline inherited
Sets the relative divergence for the solver.
Definition at line 345 of file iterative.hpp.
set_initial_penalty_param()
template<typename Functional_ > void FEAT::Solver::QPenalty< Functional_ >::set_initial_penalty_param (DataType initial_penalty_param) inline
Sets the initial penalty parameter.
Definition at line 172 of file qpenalty.hpp.
References FEAT::Solver::QPenalty< Functional_ >::_initial_penalty_param, and XASSERT.
Referenced by FEAT::Solver::QPenalty< Functional_ >::QPenalty().
set_max_iter()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_max_iter (Index max_iter) inline inherited
Sets the maximum iteration count for the solver.
Definition at line 399 of file iterative.hpp.
set_min_iter()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_min_iter (Index min_iter) inline inherited
Sets the minimum iteration count for the solver.
Definition at line 393 of file iterative.hpp.
set_min_stag_iter()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_min_stag_iter (Index min_iter) inline inherited
Sets the minimum stagnate iteration count for the solver.
Definition at line 381 of file iterative.hpp.
set_plot_interval()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_plot_interval (const Index plot_interval) inline inherited
Sets the interval between two plot outputs, if any.
Parameters
[in] plot_interval The desired interval of iteration plots
Definition at line 455 of file iterative.hpp.
set_plot_mode()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_plot_mode (const PlotMode plot_mode) inline inherited
Sets the plot mode of the solver.
Parameters
[in] plot_mode The desired plot mode
Definition at line 445 of file iterative.hpp.
set_plot_name()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_plot_name (const String & plot_name) inline inherited
Sets the plot name of the solver.
Definition at line 461 of file iterative.hpp.
set_stag_rate()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_stag_rate (DataType rate) inline inherited
Sets the stagnation rate fot the solver.
Definition at line 369 of file iterative.hpp.
set_tol_abs()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_tol_abs (DataType tol_abs) inline inherited
Sets the absolute tolerance for the solver.
Definition at line 314 of file iterative.hpp.
set_tol_abs_low()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_tol_abs_low (DataType tol_abs_low) inline inherited
Sets the lower absolute tolerance for the solver.
Definition at line 320 of file iterative.hpp.
set_tol_penalty()
template<typename Functional_ > void FEAT::Solver::QPenalty< Functional_ >::set_tol_penalty (DataType tol_penalty) inline
Sets the initial penalty parameter.
Definition at line 182 of file qpenalty.hpp.
References FEAT::Solver::QPenalty< Functional_ >::_tol_penalty, and XASSERT.
Referenced by FEAT::Solver::QPenalty< Functional_ >::QPenalty().
set_tol_rel()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_tol_rel (DataType tol_rel) inline inherited
Sets the relative tolerance for the solver.
Definition at line 308 of file iterative.hpp.
skip_defect_calc()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::skip_defect_calc (bool skip) inline inherited
Specifies whether defect calculation is allowed to be skipped.
Warning
Skipping defect calculation can lead to deadlocks in parallel solver implementations if one (but not all) processes need to compute the defect for some reason (like plotting) !
Use this function only when you really know what you are doing!
Parameters
[in] skip Specifies whether defect computation is allowed to be skipped.
Definition at line 434 of file iterative.hpp.
Member Data Documentation
_comm
const Dist::Comm* FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_comm protected inherited
Communicator of the solver.
Definition at line 131 of file iterative.hpp.
_def_cur
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_cur protected inherited
current defect
Definition at line 182 of file iterative.hpp.
_def_init
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_init protected inherited
initial defect
Definition at line 180 of file iterative.hpp.
_def_prev
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_prev protected inherited
previous iteration defect
Definition at line 184 of file iterative.hpp.
_div_abs
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_div_abs protected inherited
absolute divergence parameter
Definition at line 166 of file iterative.hpp.
_div_rel
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_div_rel protected inherited
relative divergence parameter
Definition at line 164 of file iterative.hpp.
_functional
template<typename Functional_ > FunctionalType& FEAT::Solver::QPenalty< Functional_ >::_functional private
The functional that takes the penalty parameters and is assembled in the inner solver.
Definition at line 63 of file qpenalty.hpp.
Referenced by FEAT::Solver::QPenalty< Functional_ >::_apply_intern(), FEAT::Solver::QPenalty< Functional_ >::apply(), and FEAT::Solver::QPenalty< Functional_ >::correct().
_initial_penalty_param
template<typename Functional_ > DataType FEAT::Solver::QPenalty< Functional_ >::_initial_penalty_param private
We start with this initial penalty parameter.
Definition at line 67 of file qpenalty.hpp.
Referenced by FEAT::Solver::QPenalty< Functional_ >::apply(), FEAT::Solver::QPenalty< Functional_ >::correct(), and FEAT::Solver::QPenalty< Functional_ >::set_initial_penalty_param().
_inner_solver
template<typename Functional_ > std::shared_ptr<IterativeSolver<VectorType> > FEAT::Solver::QPenalty< Functional_ >::_inner_solver private
The inner solver for the penalized, unconstrained optimization problem.
Definition at line 65 of file qpenalty.hpp.
Referenced by FEAT::Solver::QPenalty< Functional_ >::~QPenalty(), FEAT::Solver::QPenalty< Functional_ >::_apply_intern(), FEAT::Solver::QPenalty< Functional_ >::done_symbolic(), and FEAT::Solver::QPenalty< Functional_ >::init_symbolic().
_iter_digits
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_iter_digits protected inherited
iteration count digits for plotting
Definition at line 186 of file iterative.hpp.
_max_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_max_iter protected inherited
maximum number of iterations
Definition at line 172 of file iterative.hpp.
_min_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_min_iter protected inherited
minimum number of iterations
Definition at line 170 of file iterative.hpp.
_min_stag_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_min_stag_iter protected inherited
minimum number of stagnation iterations
Definition at line 176 of file iterative.hpp.
_num_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_iter protected inherited
number of performed iterations
Definition at line 174 of file iterative.hpp.
_num_stag_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_stag_iter protected inherited
number of consecutive stagnated iterations
Definition at line 178 of file iterative.hpp.
_plot_interval
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_interval protected inherited
plot output interval
Definition at line 190 of file iterative.hpp.
_plot_mode
PlotMode FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_mode protected inherited
whether to plot something
Definition at line 188 of file iterative.hpp.
_plot_name
String FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_name protected inherited
name of the solver in plots
Definition at line 133 of file iterative.hpp.
_skip_def_calc
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_skip_def_calc protected inherited
whether to skip defect computation if possible
Definition at line 192 of file iterative.hpp.
_stag_rate
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_stag_rate protected inherited
stagnation rate
Definition at line 168 of file iterative.hpp.
_status
Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_status protected inherited
current status of the solver
Definition at line 135 of file iterative.hpp.
_tol_abs
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_tol_abs protected inherited
absolute tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 160 of file iterative.hpp.
_tol_abs_low
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_tol_abs_low protected inherited
absolute tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 162 of file iterative.hpp.
_tol_penalty
template<typename Functional_ > DataType FEAT::Solver::QPenalty< Functional_ >::_tol_penalty private
Maximum value the penalty parameter is allowed to take.
Definition at line 69 of file qpenalty.hpp.
Referenced by FEAT::Solver::QPenalty< Functional_ >::_apply_intern(), and FEAT::Solver::QPenalty< Functional_ >::set_tol_penalty().
_tol_rel
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_tol_rel protected inherited
relative tolerance parameter
The solver is converged if
the defect is smaller than _tol_abs and smaller than _tol_rel*_def_init
or
the defect is smaller than _tol_abs and also smaller than _tol_abs_low
As this might not be a sufficent description, the criterion that is checked is
\[ (\vert \vert r_k\vert\vert \leq \text{tol\_abs}) \land ((\vert \vert r_k\vert\vert \leq \text{tol\_rel}\cdot\vert \vert r_0\vert\vert) \lor (\vert \vert r_k\vert\vert \leq \text{tol\_abs\_low})) \]
where \(r_k \) is the defect vector in the current iteration and \(r_0 \) the initial defect vector. Both _tol_rel and _tol_abs alone were not sufficent because of one practical case: If you have already a good initial solution so that the defect is 10^{-3}, it might be very hard to gain 8 digits and you might be happy with a defect of the order 10^{-8} anyways. On the other hand, if you have a bad initial solution and your defect is on the order of 10^{4}, you might be unhappy if you only gain 8 digits - but a priori you do not know the quality of the intial guess. The way it is now allows to say "I want the defect to be smaller than 10^{-3}, and I want to gain 8 digits - but if I manage to put the defect down to 10^{-7} and did not gain 8 digits so far then I'm also happy"
Definition at line 158 of file iterative.hpp.
The documentation for this class was generated from the following file:
kernel/solver/qpenalty.hpp