FEAT: FEAT::Assembly::UnitFilterAssembler< Mesh_ > Class Template Reference
FEAT::Assembly::UnitFilterAssembler< Mesh_ > Class Template Reference
Unit-Filter assembly class template.
#include <unit_filter_assembler.hpp>
Public Types
typedef Mesh_ MeshType
space type
Public Member Functions
UnitFilterAssembler ()
Constructor.
virtual ~UnitFilterAssembler ()
virtual destructor
void add_mesh_part (const Geometry::MeshPart< MeshType > &mesh_part)
Adds the dofs on a mesh-part to the dof-set.
template<typename DataType_ , typename IndexType_ , typename Space_ >
void assemble (LAFEM::UnitFilter< DataType_, IndexType_ > &filter, const Space_ &space) const
Builds a homogeneous unit-filter.
template<typename DataType_ , typename IndexType_ , typename Space_ , typename Function_ >
void assemble (LAFEM::UnitFilter< DataType_, IndexType_ > &filter, const Space_ &space, const Function_ &function) const
Builds an (inhomogeneous) unit-filter.
template<typename DataType_ , typename IndexType_ , typename Space_ >
void assemble (LAFEM::UnitFilter< DataType_, IndexType_ > &filter, const Space_ &space, const LAFEM::DenseVector< DataType_, IndexType_ > &vector_) const
Builds an inhomogeneous unit-filter.
template<typename DataType_ , typename IndexType_ , int BlockSize_, typename Space_ >
void assemble (LAFEM::UnitFilterBlocked< DataType_, IndexType_, BlockSize_ > &filter, const Space_ &space) const
Builds a homogeneous blocked unit filter.
template<typename DataType_ , typename IndexType_ , int BlockSize_, typename Space_ , typename Function_ >
void assemble (LAFEM::UnitFilterBlocked< DataType_, IndexType_, BlockSize_ > &filter, const Space_ &space, const Function_ &function) const
Builds an inhomogeneous blocked unit filter.
template<typename DTF_ , typename ITF_ , typename DTV_ , typename ITV_ , int BlockSize_, typename Space_ >
void assemble (LAFEM::UnitFilterBlocked< DTF_, ITF_, BlockSize_ > &filter, const Space_ &space, const LAFEM::DenseVectorBlocked< DTV_, ITV_, BlockSize_ > &vector_) const
Builds an inhomogeneous blocked unit filter.
Private Types
typedef std::set< Index > IdxSet
dof-index set typedef
Private Attributes
IdxSet _cells [shape_dim+1]
dof-index set
Static Private Attributes
static constexpr int shape_dim = MeshType::shape_dim
shape dimension
Detailed Description
template<typename Mesh_>
class FEAT::Assembly::UnitFilterAssembler< Mesh_ >
Unit-Filter assembly class template.
Template Parameters
Mesh_ The type of the mesh on which the unit filter is to be assembled.
Author
Peter Zajac
Definition at line 45 of file unit_filter_assembler.hpp.
Member Typedef Documentation
IdxSet
template<typename Mesh_ > typedef std::set<Index> FEAT::Assembly::UnitFilterAssembler< Mesh_ >::IdxSet private
dof-index set typedef
Definition at line 56 of file unit_filter_assembler.hpp.
MeshType
template<typename Mesh_ > typedef Mesh_ FEAT::Assembly::UnitFilterAssembler< Mesh_ >::MeshType
space type
Definition at line 49 of file unit_filter_assembler.hpp.
Constructor & Destructor Documentation
UnitFilterAssembler()
template<typename Mesh_ > FEAT::Assembly::UnitFilterAssembler< Mesh_ >::UnitFilterAssembler () inline explicit
Constructor.
Definition at line 65 of file unit_filter_assembler.hpp.
~UnitFilterAssembler()
template<typename Mesh_ > virtual FEAT::Assembly::UnitFilterAssembler< Mesh_ >::~UnitFilterAssembler () inline virtual
virtual destructor
Definition at line 70 of file unit_filter_assembler.hpp.
Member Function Documentation
add_mesh_part()
template<typename Mesh_ > void FEAT::Assembly::UnitFilterAssembler< Mesh_ >::add_mesh_part (const Geometry::MeshPart< MeshType > & mesh_part) inline
Adds the dofs on a mesh-part to the dof-set.
Parameters
[in] mesh_part A transient reference to a mesh part object.
Definition at line 80 of file unit_filter_assembler.hpp.
References FEAT::Assembly::UnitFilterAssembler< Mesh_ >::_cells.
assemble() [1/6]
template<typename Mesh_ > template<typename DataType_ , typename IndexType_ , typename Space_ > void FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble (LAFEM::UnitFilter< DataType_, IndexType_ > & filter, const Space_ & space) const inline
Builds a homogeneous unit-filter.
This function assembles a unit-filter implementing the homogeneous Dirichlet boundary conditions.
Parameters
[in,out] filter A transient reference to the unit-filter where the entries are to be added. The filter will be allocated with the correct size if it is empty.
[in] space The transient finite-element space for which the filter is to be assembled.
Definition at line 98 of file unit_filter_assembler.hpp.
References FEAT::Assembly::UnitFilterAssembler< Mesh_ >::_cells, FEAT::LAFEM::UnitFilter< DT_, IT_ >::add(), and FEAT::LAFEM::UnitFilter< DT_, IT_ >::size().
assemble() [2/6]
template<typename Mesh_ > template<typename DataType_ , typename IndexType_ , typename Space_ , typename Function_ > void FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble (LAFEM::UnitFilter< DataType_, IndexType_ > & filter, const Space_ & space, const Function_ & function) const inline
Builds an (inhomogeneous) unit-filter.
This function assembles a unit-filter implementing Dirichlet boundary conditions based on a function.
Parameters
[in,out] filter A transient reference to the unit-filter where the entries are to be added.
[in] space The transient finite-element space for which the filter is to be assembled.
[in] function An transient object implementing the Analytic::Function interface representing the scalar boundary value function.
Definition at line 182 of file unit_filter_assembler.hpp.
References FEAT::Assembly::UnitFilterAssembler< Mesh_ >::_cells, FEAT::LAFEM::UnitFilter< DT_, IT_ >::add(), and FEAT::LAFEM::UnitFilter< DT_, IT_ >::size().
assemble() [3/6]
template<typename Mesh_ > template<typename DataType_ , typename IndexType_ , typename Space_ > void FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble (LAFEM::UnitFilter< DataType_, IndexType_ > & filter, const Space_ & space, const LAFEM::DenseVector< DataType_, IndexType_ > & vector_) const inline
Builds an inhomogeneous unit-filter.
This function assembles a unit-filter implementing the inhomogeneous Dirichlet boundary conditions given by the vector vector_. In general, this vector will be a representation of an FE function.
Parameters
[in,out] filter A transient reference to the unit-filter where the entries are to be added.
[in] space The transient finite-element space for which the filter is to be assembled.
[in] vector_ A transient LAFEM::DenseVector containing (among other stuff) the entries to be added.
Definition at line 136 of file unit_filter_assembler.hpp.
References FEAT::Assembly::UnitFilterAssembler< Mesh_ >::_cells, FEAT::LAFEM::UnitFilter< DT_, IT_ >::add(), and FEAT::LAFEM::UnitFilter< DT_, IT_ >::size().
assemble() [4/6]
template<typename Mesh_ > template<typename DataType_ , typename IndexType_ , int BlockSize_, typename Space_ > void FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble (LAFEM::UnitFilterBlocked< DataType_, IndexType_, BlockSize_ > & filter, const Space_ & space) const inline
Builds a homogeneous blocked unit filter.
This function assembles a blocked unit filter implementing the homogeneous Dirichlet boundary conditions.
Parameters
[in,out] filter A transient reference to the blocked unit filter where the entries are to be added.
[in] space The transient finite-element space for which the filter is to be assembled.
Definition at line 223 of file unit_filter_assembler.hpp.
References FEAT::Assembly::UnitFilterAssembler< Mesh_ >::_cells, FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::add(), and FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::size().
assemble() [5/6]
template<typename Mesh_ > template<typename DataType_ , typename IndexType_ , int BlockSize_, typename Space_ , typename Function_ > void FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble (LAFEM::UnitFilterBlocked< DataType_, IndexType_, BlockSize_ > & filter, const Space_ & space, const Function_ & function) const inline
Builds an inhomogeneous blocked unit filter.
This function assembles a blocked unit filter implementing the inhomogeneous Dirichlet boundary conditions.
Parameters
[in,out] filter A transient reference to the blocked unit filter where the entries are to be added.
[in] space The transient finite-element space for which the filter is to be assembled.
[in] function An transient object implementing the Analytic::Function interface representing the vector-valued boundary value function.
Definition at line 264 of file unit_filter_assembler.hpp.
References FEAT::Assembly::UnitFilterAssembler< Mesh_ >::_cells, FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::add(), and FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::size().
assemble() [6/6]
template<typename Mesh_ > template<typename DTF_ , typename ITF_ , typename DTV_ , typename ITV_ , int BlockSize_, typename Space_ > void FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble (LAFEM::UnitFilterBlocked< DTF_, ITF_, BlockSize_ > & filter, const Space_ & space, const LAFEM::DenseVectorBlocked< DTV_, ITV_, BlockSize_ > & vector_) const inline
Builds an inhomogeneous blocked unit filter.
This function assembles a blocked unit filter implementing the inhomogeneous Dirichlet boundary conditions given by the vector vector_. In general, this vector will be a representation of an FE function.
Parameters
[in,out] filter A transient reference to the unit-filter where the entries are to be added.
[in] vector_ A transient LAFEM::DenseVector containing (among other stuff) the entries to be added.
[in] space The transient finite-element space for which the filter is to be assembled.
Definition at line 313 of file unit_filter_assembler.hpp.
References FEAT::Assembly::UnitFilterAssembler< Mesh_ >::_cells, FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::add(), and FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::size().
Member Data Documentation
_cells
template<typename Mesh_ > IdxSet FEAT::Assembly::UnitFilterAssembler< Mesh_ >::_cells[shape_dim+1] private
dof-index set
Definition at line 59 of file unit_filter_assembler.hpp.
Referenced by FEAT::Assembly::UnitFilterAssembler< Mesh_ >::add_mesh_part(), and FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble().
shape_dim
template<typename Mesh_ > constexpr int FEAT::Assembly::UnitFilterAssembler< Mesh_ >::shape_dim = MeshType::shape_dim static constexpr private
shape dimension
Definition at line 53 of file unit_filter_assembler.hpp.
The documentation for this class was generated from the following file:
kernel/assembly/unit_filter_assembler.hpp