FEAT: FEAT::Assembly::BilinearOperatorAssembler Class Reference
FEAT::Assembly::BilinearOperatorAssembler Class Reference
Bilinear Operator Assembler class template.
#include <bilinear_operator_assembler.hpp>
Static Public Member Functions
template<typename Vector_ , typename Operator_ , typename Space_ , typename CubatureFactory_ >
static void apply1 (Vector_ &ret, const Vector_ &coeff_vector, const Operator_ &operat, const Space_ &space, const CubatureFactory_ &cubature_factory, typename Vector_::DataType alpha=typename Vector_::DataType(1))
Applies the bilinear operator to an FE function.
template<typename Vector_ , typename Operator_ , typename TestSpace_ , typename TrialSpace_ , typename CubatureFactory_ >
static void apply2 (Vector_ &ret, const Vector_ &coeff_vector, const Operator_ &operat, const TestSpace_ &test_space, const TrialSpace_ &trial_space, const CubatureFactory_ &cubature_factory, typename Vector_::DataType alpha=typename Vector_::DataType(1))
Applies the bilinear operator to an FE function.
template<typename Matrix_ , typename Operator_ , typename Space_ , typename CubatureFactory_ >
static void assemble_matrix1 (Matrix_ &matrix, Operator_ &operat, const Space_ &space, const CubatureFactory_ &cubature_factory, typename Matrix_::DataType alpha=typename Matrix_::DataType(1))
Assembles a bilinear operator into a matrix.
template<typename Matrix_ , typename Operator_ , typename TestSpace_ , typename TrialSpace_ , typename CubatureFactory_ >
static void assemble_matrix2 (Matrix_ &matrix, Operator_ &operat, const TestSpace_ &test_space, const TrialSpace_ &trial_space, const CubatureFactory_ &cubature_factory, typename Matrix_::DataType alpha=typename Matrix_::DataType(1))
Assembles a bilinear operator into a matrix.
Detailed Description
Bilinear Operator Assembler class template.
This class template implements the assembly of a standard bilinear operator into a matrix.
Author
Peter Zajac
Definition at line 24 of file bilinear_operator_assembler.hpp.
Member Function Documentation
apply1()
template<typename Vector_ , typename Operator_ , typename Space_ , typename CubatureFactory_ > static void FEAT::Assembly::BilinearOperatorAssembler::apply1 (Vector_ & ret, const Vector_ & coeff_vector, const Operator_ & operat, const Space_ & space, const CubatureFactory_ & cubature_factory, typename Vector_::DataType alpha = typename Vector_::DataType(1)) inline static
Applies the bilinear operator to an FE function.
This function is the version for identical test- and trial-spaces and does the same as assembling the operator into a matrix and multiplying it with a vector representing the FE function. Useful if this is needed only a few times and one does not want to save the matrix.
Parameters
[out] ret The transient return vector.
[in] coeff_vector The transient coefficient vector for the FE function.
[in] operat A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] space A transient reference to the finite-element to be used as the test- and trial-space.
[in] cubature_factory A transient reference to the cubature factory to be used for integration.
[in] alpha The scaling factor for the bilinear operator.
Author
Jordi Paul
Definition at line 389 of file bilinear_operator_assembler.hpp.
References FEAT::Tiny::axpy(), and XASSERTM.
apply2()
template<typename Vector_ , typename Operator_ , typename TestSpace_ , typename TrialSpace_ , typename CubatureFactory_ > static void FEAT::Assembly::BilinearOperatorAssembler::apply2 (Vector_ & ret, const Vector_ & coeff_vector, const Operator_ & operat, const TestSpace_ & test_space, const TrialSpace_ & trial_space, const CubatureFactory_ & cubature_factory, typename Vector_::DataType alpha = typename Vector_::DataType(1)) inline static
Applies the bilinear operator to an FE function.
This function is the version for different test- and trial-spaces and does the same as assembling the operator into a matrix and multiplying it with a vector representing the FE function. Useful if this is needed only a few times and one does not want to save the matrix.
Parameters
[out] ret The transient return vector.
[in] coeff_vector The transient coefficient vector for the FE function.
[in] operat A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] test_space A transient reference to the finite-element test-space to be used.
[in] trial_space A transient reference to the finite-element trial-space to be used.
[in] cubature_factory A transient reference to the cubature factory to be used for integration.
[in] alpha The scaling factor for the bilinear operator.
Author
Jordi Paul
Definition at line 563 of file bilinear_operator_assembler.hpp.
References FEAT::Tiny::axpy(), and XASSERTM.
assemble_matrix1()
template<typename Matrix_ , typename Operator_ , typename Space_ , typename CubatureFactory_ > static void FEAT::Assembly::BilinearOperatorAssembler::assemble_matrix1 (Matrix_ & matrix, Operator_ & operat, const Space_ & space, const CubatureFactory_ & cubature_factory, typename Matrix_::DataType alpha = typename Matrix_::DataType(1)) inline static
Assembles a bilinear operator into a matrix.
This function is the version for identical test- and trial-spaces.
Parameters
[in,out] matrix The transient matrix that is to be assembled.
[in] operat A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] space A transient reference to the finite-element to be used as the test- and trial-space.
[in] cubature_factory A transient reference to the cubature factory to be used for integration.
[in] alpha The scaling factor for the bilinear operator.
Definition at line 225 of file bilinear_operator_assembler.hpp.
References FEAT::Tiny::axpy(), and XASSERTM.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::assemble_system_matrix().
assemble_matrix2()
template<typename Matrix_ , typename Operator_ , typename TestSpace_ , typename TrialSpace_ , typename CubatureFactory_ > static void FEAT::Assembly::BilinearOperatorAssembler::assemble_matrix2 (Matrix_ & matrix, Operator_ & operat, const TestSpace_ & test_space, const TrialSpace_ & trial_space, const CubatureFactory_ & cubature_factory, typename Matrix_::DataType alpha = typename Matrix_::DataType(1)) inline static
Assembles a bilinear operator into a matrix.
This function is the version for different test- and trial-spaces.
Parameters
[in,out] matrix The transient matrix that is to be assembled.
[in] operat A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] test_space A transient reference to the finite-element test-space to be used.
[in] trial_space A transient reference to the finite-element trial-space to be used.
[in] cubature_factory A transient reference to the cubature factory to be used for integration.
[in] alpha The scaling factor for the bilinear operator.
Definition at line 56 of file bilinear_operator_assembler.hpp.
References FEAT::Tiny::axpy(), and XASSERTM.
The documentation for this class was generated from the following file:
kernel/assembly/bilinear_operator_assembler.hpp