FEAT: FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ > Class Template Reference
FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ > Class Template Reference
Global NonlinearFunctional wrapper class template.
#include <nonlinear_functional.hpp>
Public Types
typedef LocalNonlinearFunctional_::DataType DataType
Floating point data type of the local functional.
typedef Filter< LocalFilterType, RowMirrorType_ > FilterType
The associated global filter type.
typedef Gate< LocalVectorTypeR, ColMirrorType_ > GateColType
Global Gate for right-vectors.
typedef Gate< LocalVectorTypeL, RowMirrorType_ > GateRowType
Global Gate for left-vectors.
typedef VectorTypeL GradientType
The a gradient vector is the output of the operators compute_grad() function and thus a left-vector.
typedef LocalNonlinearFunctional_::IndexType IndexType
Index type of the local functional.
typedef LocalNonlinearFunctional_::FilterType LocalFilterType
The local functionals filter type.
typedef LocalNonlinearFunctional_::VectorTypeL LocalVectorTypeL
The local functionals left-vector type.
typedef LocalNonlinearFunctional_::VectorTypeR LocalVectorTypeR
The local functionals right-vector type.
typedef Vector< LocalVectorTypeL, RowMirrorType_ > VectorTypeL
The associated global left-vector type.
typedef Vector< LocalVectorTypeR, ColMirrorType_ > VectorTypeR
The associated global right-vector type.
Public Member Functions
NonlinearFunctional ()=delete
Explicitly delete default constructor.
NonlinearFunctional (const NonlinearFunctional &)=delete
Explicitly delete copy constructor.
NonlinearFunctional (GateRowType *row_gate, GateColType *col_gate, LocalNonlinearFunctional_ &nonlinear_functional)
Constructor.
virtual ~NonlinearFunctional ()
Empty virtual destructor.
Index columns ()
Gets the number of columns.
DataType compute_constraint ()
Computes the constraint and returns it.
VectorTypeL create_vector_l () const
Creates an empty left-vector of the correct size.
VectorTypeR create_vector_r () const
Creates an empty right-vector of the correct size.
void eval_fval_grad (DataType &fval, VectorTypeL &grad)
Computes the functional's value and gradient at the current state.
const Dist::Comm * get_comm () const
Returns the functional's communicator.
DataType get_constraint ()
Get the constraint from the local nonlinear functional.
Index get_num_func_evals () const
Get the number of times compute_func() was called.
Index get_num_grad_evals () const
Get the number of times compute_grad() was called.
Index get_num_hess_evals () const
Get the number of times compute_hess() was called.
DataType get_penalty_param () const
Get the penalty parameter from the local nonlinear functional.
void init ()
Functionality that cannot be done in the constructor.
LocalNonlinearFunctional_ & local ()
Gets the local nonlinear functional.
const LocalNonlinearFunctional_ & local () const
Gets the local nonlinear functional, const version.
void prepare (const VectorTypeR &vec_state, FilterType &filter)
Prepares the operator for evaluation by setting the current state.
void reset_num_evals ()
Resets the evaluation counters.
Index rows ()
Gets the number of rows.
void set_penalty_param (const DataType fac)
Sets the local functional's penalty parameter.
Static Public Attributes
static constexpr int BlockHeight = LocalNonlinearFunctional_::BlockHeight
The global nonlinear functional's Blockheight ist the same as the local nonlinear functional's.
static constexpr int BlockWidth = LocalNonlinearFunctional_::BlockWidth
The global nonlinear functional's Blockwidth ist the same as the local nonlinear functional's.
Protected Attributes
GateColType * _col_gate
Gate for syncing column vectors.
LocalNonlinearFunctional_ & _nonlinear_functional
The underlying local nonlinear functional.
GateRowType * _row_gate
Gate for syncing row vectors.
Detailed Description
template<typename LocalNonlinearFunctional_, typename RowMirrorType_, typename ColMirrorType_>
class FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >
Global NonlinearFunctional wrapper class template.
Template Parameters
LocalNonlinearFunctional_ The class of the (patch-) local nonlinear functional
Author
Jordi Paul
Definition at line 26 of file nonlinear_functional.hpp.
Member Typedef Documentation
DataType
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef LocalNonlinearFunctional_::DataType FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::DataType
Floating point data type of the local functional.
Definition at line 30 of file nonlinear_functional.hpp.
FilterType
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef Filter<LocalFilterType, RowMirrorType_> FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::FilterType
The associated global filter type.
Definition at line 46 of file nonlinear_functional.hpp.
GateColType
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef Gate<LocalVectorTypeR, ColMirrorType_> FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::GateColType
Global Gate for right-vectors.
Definition at line 51 of file nonlinear_functional.hpp.
GateRowType
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef Gate<LocalVectorTypeL, RowMirrorType_> FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::GateRowType
Global Gate for left-vectors.
Definition at line 49 of file nonlinear_functional.hpp.
GradientType
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef VectorTypeL FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::GradientType
The a gradient vector is the output of the operators compute_grad() function and thus a left-vector.
Definition at line 54 of file nonlinear_functional.hpp.
IndexType
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef LocalNonlinearFunctional_::IndexType FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::IndexType
Index type of the local functional.
Definition at line 32 of file nonlinear_functional.hpp.
LocalFilterType
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef LocalNonlinearFunctional_::FilterType FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::LocalFilterType
The local functionals filter type.
Definition at line 39 of file nonlinear_functional.hpp.
LocalVectorTypeL
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef LocalNonlinearFunctional_::VectorTypeL FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::LocalVectorTypeL
The local functionals left-vector type.
Definition at line 35 of file nonlinear_functional.hpp.
LocalVectorTypeR
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef LocalNonlinearFunctional_::VectorTypeR FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::LocalVectorTypeR
The local functionals right-vector type.
Definition at line 37 of file nonlinear_functional.hpp.
VectorTypeL
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef Vector<LocalVectorTypeL, RowMirrorType_> FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::VectorTypeL
The associated global left-vector type.
Definition at line 42 of file nonlinear_functional.hpp.
VectorTypeR
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > typedef Vector<LocalVectorTypeR, ColMirrorType_> FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::VectorTypeR
The associated global right-vector type.
Definition at line 44 of file nonlinear_functional.hpp.
Constructor & Destructor Documentation
NonlinearFunctional()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::NonlinearFunctional (GateRowType * row_gate, GateColType * col_gate, LocalNonlinearFunctional_ & nonlinear_functional) inline explicit
Constructor.
Parameters
[in] row_gate Gate for rows
[in] col_gate Gate for columns
[in] nonlinear_functional The (patch-)local nonlinear functional
Definition at line 83 of file nonlinear_functional.hpp.
~NonlinearFunctional()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > virtual FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::~NonlinearFunctional () inline virtual
Empty virtual destructor.
Definition at line 97 of file nonlinear_functional.hpp.
Member Function Documentation
columns()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > Index FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::columns () inline
Gets the number of columns.
Warning
In parallel, this requires communication and is very expensive, so use sparingly!
Returns
The number of colums
Definition at line 305 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::create_vector_r().
compute_constraint()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > DataType FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::compute_constraint () inline
Computes the constraint and returns it.
Returns
The global nonlinear functional's constraint
Definition at line 395 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
create_vector_l()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > VectorTypeL FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::create_vector_l () const inline
Creates an empty left-vector of the correct size.
Returns
A new left-vector
Definition at line 173 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional, and FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_row_gate.
Referenced by FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::rows().
create_vector_r()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > VectorTypeR FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::create_vector_r () const inline
Creates an empty right-vector of the correct size.
Returns
A new right-vector
Definition at line 183 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_col_gate, and FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
Referenced by FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::columns().
eval_fval_grad()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > void FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::eval_fval_grad (DataType & fval, VectorTypeL & grad) inline
Computes the functional's value and gradient at the current state.
Parameters
[out] fval The functional value
[out] grad The vector receiving the synced gradient vector
Definition at line 340 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional, FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_row_gate, FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_constraint(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_penalty_param(), FEAT::grad, FEAT::Math::sqr(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sum().
get_comm()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > const Dist::Comm * FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_comm () const inline
Returns the functional's communicator.
Definition at line 124 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_row_gate, and FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm().
get_constraint()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > DataType FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_constraint () inline
Get the constraint from the local nonlinear functional.
Returns
A copy of the global nonlinear functional's constraint
Definition at line 385 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
Referenced by FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::eval_fval_grad().
get_num_func_evals()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > Index FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_num_func_evals () const inline
Get the number of times compute_func() was called.
Returns
The number of functional evaluations
Definition at line 134 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
get_num_grad_evals()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > Index FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_num_grad_evals () const inline
Get the number of times compute_grad() was called.
Returns
The number of gradient evaluations
Definition at line 144 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
get_num_hess_evals()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > Index FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_num_hess_evals () const inline
Get the number of times compute_hess() was called.
Returns
The number of Hessian evaluations
Definition at line 154 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
get_penalty_param()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > DataType FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_penalty_param () const inline
Get the penalty parameter from the local nonlinear functional.
Returns
A copy of the local nonlinear functional's penalty parameter
Definition at line 367 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
Referenced by FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::eval_fval_grad().
init()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > void FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::init () inline
Functionality that cannot be done in the constructor.
Definition at line 191 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_col_gate, FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional, FEAT::Global::Gate< LocalVector_, Mirror_ >::sum(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0().
local() [1/2]
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > LocalNonlinearFunctional_ & FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::local () inline
Gets the local nonlinear functional.
Returns
A reference to the underlying local nonlinear functional
Definition at line 106 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
local() [2/2]
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > const LocalNonlinearFunctional_ & FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::local () const inline
Gets the local nonlinear functional, const version.
Returns
A const reference to the underlying local nonlinear functional
Definition at line 116 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
prepare()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > void FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::prepare (const VectorTypeR & vec_state, FilterType & filter) inline
Prepares the operator for evaluation by setting the current state.
Parameters
[in] vec_state The current state
[in,out] filter The filter that might be modified by the local functional's prepare
Definition at line 225 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_col_gate, FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional, FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sum(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0().
reset_num_evals()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > void FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::reset_num_evals () inline
Resets the evaluation counters.
Definition at line 163 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
rows()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > Index FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::rows () inline
Gets the number of rows.
Warning
In parallel, this requires communication and is very expensive, so use sparingly!
Returns
The number of colums
Definition at line 321 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::create_vector_l().
set_penalty_param()
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > void FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::set_penalty_param (const DataType fac) inline
Sets the local functional's penalty parameter.
Definition at line 375 of file nonlinear_functional.hpp.
References FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional.
Member Data Documentation
_col_gate
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > GateColType* FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_col_gate protected
Gate for syncing column vectors.
Definition at line 65 of file nonlinear_functional.hpp.
Referenced by FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::create_vector_r(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::init(), and FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::prepare().
_nonlinear_functional
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > LocalNonlinearFunctional_& FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_nonlinear_functional protected
The underlying local nonlinear functional.
Definition at line 67 of file nonlinear_functional.hpp.
Referenced by FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::compute_constraint(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::create_vector_l(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::create_vector_r(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::eval_fval_grad(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_constraint(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_num_func_evals(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_num_grad_evals(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_num_hess_evals(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_penalty_param(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::init(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::local(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::prepare(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::reset_num_evals(), and FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::set_penalty_param().
_row_gate
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > GateRowType* FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::_row_gate protected
Gate for syncing row vectors.
Definition at line 63 of file nonlinear_functional.hpp.
Referenced by FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::create_vector_l(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::eval_fval_grad(), and FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_comm().
BlockHeight
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > constexpr int FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::BlockHeight = LocalNonlinearFunctional_::BlockHeight static constexpr
The global nonlinear functional's Blockheight ist the same as the local nonlinear functional's.
Definition at line 57 of file nonlinear_functional.hpp.
BlockWidth
template<typename LocalNonlinearFunctional_ , typename RowMirrorType_ , typename ColMirrorType_ > constexpr int FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::BlockWidth = LocalNonlinearFunctional_::BlockWidth static constexpr
The global nonlinear functional's Blockwidth ist the same as the local nonlinear functional's.
Definition at line 59 of file nonlinear_functional.hpp.
The documentation for this class was generated from the following file:
kernel/global/nonlinear_functional.hpp