FEAT: FEAT::Geometry::Atlas::Bezier< Mesh_ > Class Template Reference
FEAT::Geometry::Atlas::Bezier< Mesh_ > Class Template Reference abstract
Bezier chart class template.
#include <bezier.hpp>
Public Types
typedef PartType::AttributeSetType AttributeSetType
attribute type of our mesh-part
typedef ChartCRTP< Bezier< Mesh_ >, Mesh_, BezierTraits > BaseClass
The CRTP base class.
typedef VertexSetType::CoordType CoordType
coordinate type
typedef BaseClass::CoordType DataType
Floating point type for coordinates.
typedef BaseClass::MeshType MeshType
mesh type
typedef BaseClass::ParamPoint ParamPoint
Vector type for parameter points aka. domain points.
typedef BaseClass::PartType PartType
mesh-part type
typedef BezierTraits TraitsType
traits type
typedef MeshType::VertexSetType VertexSetType
vertex set type of our mesh
typedef BaseClass::WorldPoint WorldPoint
Vector type for world points aka. image points.
Public Member Functions
Bezier (bool closed=false, DataType orientation=DataType(1))
default CTOR
Bezier (const Bezier &)=default
Bezier (const std::deque< std::size_t > &vtx_ptr, const std::deque< WorldPoint > &world, const std::deque< ParamPoint > &param, bool closed, DataType orientation=DataType(1))
Constructor.
virtual void adapt (MeshType &mesh, const PartType &part) const override
Adapts a whole MeshPart.
virtual void adapt (PartType &parent_meshpart, const PartType &meshpart) const override
Adapts a whole MeshPart referring to another MeshPart.
virtual std::size_t bytes () const
virtual bool can_explicit () const override
Specifies whether the chart can perform explicit projection.
virtual bool can_implicit () const override
DataType compute_dist (const WorldPoint &point) const
Computes the distance of a point to this chart.
DataType compute_dist (const WorldPoint &point, WorldPoint &grad_dist) const
Computes the distance of a point to this chart.
DataType compute_signed_dist (const WorldPoint &point) const
Computes the signed distance of a point to this chart.
DataType compute_signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const
Computes the signed distance of a point to this chart.
virtual CoordType dist (const WorldPoint &point) const override
virtual CoordType dist (const WorldPoint &point, WorldPoint &grad_dist) const override
WorldPoint get_normal_on_segment (const Index i, const DataType t) const
Computes the outer unit normal in a single point.
int get_orientation () const
Returns the orientation code for the curve.
virtual String get_type () const override
Writes the type as String.
std::deque< std::size_t > & get_vertex_pointers ()
Returns a (const) reference to the internal vertex pointers deque.
const std::deque< std::size_t > & get_vertex_pointers () const
Returns a (const) reference to the internal vertex pointers deque.
std::deque< WorldPoint > & get_world_points ()
Returns a (const) reference to the internal world points deque.
const std::deque< WorldPoint > & get_world_points () const
Returns a (const) reference to the internal world points deque.
bool is_closed () const
Checks whether the curve is open or closed.
virtual WorldPoint map (const WorldPoint &param) const override
WorldPoint map_on_segment (const Index i, const DataType t) const
Maps a local segment parameter point.
void map_param (WorldPoint &point, const ParamPoint &param) const
Maps a single parameter point.
virtual WorldPoint project (const WorldPoint &point) const override
void project_meshpart (Mesh_ &mesh, const MeshPart< Mesh_ > &meshpart) const
Projects all mesh points identified by a meshpart.
DataType project_on_segment (const Index i, const WorldPoint &point) const
Projects a point onto one segment of the spline.
void project_point (WorldPoint &point) const
Projects a single world point.
void push_close ()
Marks the Bezier chart as closed.
void push_control (const WorldPoint &point)
Pushes a new control point to the spline.
void push_param (const ParamPoint &param)
Pushes a new parameter to the spline.
void push_vertex (const WorldPoint &point)
Pushes a new vertex point to the spline.
void set_orientation (int ori)
Sets the orientation code for the curve.
virtual CoordType signed_dist (const WorldPoint &point) const override
virtual CoordType signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset) override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset)=0
Applies a "proper rigid" transformation onto the chart.
virtual void write (std::ostream &os, const String &sindent) const override
Writes the Chart into a stream in XML format.
Static Public Attributes
static constexpr bool is_explicit
specifies whether this chart is explicit
static constexpr bool is_implicit
specifies whether this chart is implicit
static constexpr int max_degree = 5
maximum allowed spline degree
static constexpr int param_dim
the parameter dimension of this chart
static constexpr int world_dim
the world dimension of this chart
Protected Member Functions
Bezier< Mesh_ > & cast ()
Casts this to its true type.
const Bezier< Mesh_ > & cast () const
std::size_t find_param (const DataType x) const
Protected Attributes
bool _closed
Specifies whether the spline is closed.
DataType _orientation
Specifies if the chart is to be oriented negatively or not.
std::deque< ParamPoint > _param
The parameter values for these world points.
std::deque< std::size_t > _vtx_ptr
The vertex point pointer array.
std::deque< WorldPoint > _world
The vertex and control points for the spline.
Detailed Description
template<typename Mesh_>
class FEAT::Geometry::Atlas::Bezier< Mesh_ >
Bezier chart class template.
This chart represents a 2D composite Bezier curve of varying degree, which is represented by a vector of vertex points, Bezier control points and parameters.
This chart implements both the implicit and explicit chart interfaces.
Template Parameters
Mesh_ The type of the mesh to be parameterized by this chart.
Author
Peter Zajac
Definition at line 43 of file bezier.hpp.
Member Typedef Documentation
AttributeSetType
typedef PartType::AttributeSetType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::AttributeSetType inherited
attribute type of our mesh-part
Definition at line 365 of file chart.hpp.
BaseClass
template<typename Mesh_ > typedef ChartCRTP<Bezier<Mesh_>, Mesh_, BezierTraits> FEAT::Geometry::Atlas::Bezier< Mesh_ >::BaseClass
The CRTP base class.
Definition at line 48 of file bezier.hpp.
CoordType
typedef VertexSetType::CoordType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::CoordType inherited
coordinate type
Definition at line 369 of file chart.hpp.
DataType
template<typename Mesh_ > typedef BaseClass::CoordType FEAT::Geometry::Atlas::Bezier< Mesh_ >::DataType
Floating point type for coordinates.
Definition at line 50 of file bezier.hpp.
MeshType
typedef BaseClass::MeshType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::MeshType inherited
mesh type
Definition at line 361 of file chart.hpp.
ParamPoint
template<typename Mesh_ > typedef BaseClass::ParamPoint FEAT::Geometry::Atlas::Bezier< Mesh_ >::ParamPoint
Vector type for parameter points aka. domain points.
Definition at line 54 of file bezier.hpp.
PartType
typedef BaseClass::PartType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::PartType inherited
mesh-part type
Definition at line 363 of file chart.hpp.
TraitsType
typedef BezierTraits FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::TraitsType inherited
traits type
Definition at line 359 of file chart.hpp.
VertexSetType
typedef MeshType::VertexSetType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::VertexSetType inherited
vertex set type of our mesh
Definition at line 367 of file chart.hpp.
WorldPoint
template<typename Mesh_ > typedef BaseClass::WorldPoint FEAT::Geometry::Atlas::Bezier< Mesh_ >::WorldPoint
Vector type for world points aka. image points.
Definition at line 52 of file bezier.hpp.
Constructor & Destructor Documentation
Bezier() [1/2]
template<typename Mesh_ > FEAT::Geometry::Atlas::Bezier< Mesh_ >::Bezier (bool closed = false, DataType orientation = DataType(1)) inline explicit
default CTOR
Definition at line 73 of file bezier.hpp.
Bezier() [2/2]
template<typename Mesh_ > FEAT::Geometry::Atlas::Bezier< Mesh_ >::Bezier (const std::deque< std::size_t > & vtx_ptr, const std::deque< WorldPoint > & world, const std::deque< ParamPoint > & param, bool closed, DataType orientation = DataType(1)) inline explicit
Constructor.
Parameters
[in] vtx_ptr A transient deque containing the indices of the vertex points in the world point array.
[in] world A transient deque of vertex and control points representing the spline.
[in] param A transient deque of parameter points representing the parameter space.
[in] closed Specifies whether the spline is closed.
[in] orientation The orientation code for the curve. Must be either +1 or -1.
Definition at line 98 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_orientation, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_param, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world, FEAT::Geometry::Atlas::Bezier< Mesh_ >::max_degree, XASSERT, and XASSERTM.
Member Function Documentation
adapt() [1/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::adapt (MeshType & mesh, const PartType & part) const inline override virtual inherited
Adapts a whole MeshPart.
Parameters
[in] mesh Mesh to be adapted
[in] part MeshPart identifying the region to be adapted
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 420 of file chart.hpp.
adapt() [2/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::adapt (PartType & parent_meshpart, const PartType & meshpart) const inline override virtual inherited
Adapts a whole MeshPart referring to another MeshPart.
Parameters
[in] parent_meshpart MeshPart to be adapted
[in] meshpart MeshPart identifying the region to be adapted
Todo:
: Implement this
There is currently no code that uses MeshParts referring to other MeshParts instead of a RootMesh.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 450 of file chart.hpp.
bytes()
template<typename Mesh_ > virtual std::size_t FEAT::Geometry::Atlas::ChartBase< Mesh_ >::bytes () const inline virtual inherited
Returns
The size of dynamically allocated memory in bytes.
Reimplemented in FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >.
Definition at line 52 of file chart.hpp.
can_explicit()
template<typename Mesh_ > virtual bool FEAT::Geometry::Atlas::Bezier< Mesh_ >::can_explicit () const inline override virtual
Specifies whether the chart can perform explicit projection.
Returns
true if explicit projection is possible, otherwise false.
Reimplemented from FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ >, Mesh_, BezierTraits >.
Definition at line 219 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_param.
can_implicit()
virtual bool FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::can_implicit () const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 406 of file chart.hpp.
cast() [1/2]
Bezier< Mesh_ > & FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::cast () inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this
Definition at line 393 of file chart.hpp.
cast() [2/2]
const Bezier< Mesh_ > & FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::cast () const inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this\ifile "/github/workspace/kernel/geometry/atlas/chart.hpp"
Definition at line 396 of file chart.hpp.
compute_dist() [1/2]
template<typename Mesh_ > DataType FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_dist (const WorldPoint & point) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 729 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_point().
compute_dist() [2/2]
template<typename Mesh_ > DataType FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 737 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_point().
compute_signed_dist() [1/2]
template<typename Mesh_ > DataType FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist (const WorldPoint & point) const inline
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Definition at line 748 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist().
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist().
compute_signed_dist() [2/2]
template<typename Mesh_ > DataType FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Definition at line 756 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_closed, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_orientation, FEAT::Math::abs(), FEAT::Tiny::dot(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_normal_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_on_segment(), FEAT::Math::signum(), FEAT::Math::sqr(), FEAT::Math::sqrt(), and XASSERT.
dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 480 of file chart.hpp.
dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 486 of file chart.hpp.
find_param()
template<typename Mesh_ > std::size_t FEAT::Geometry::Atlas::Bezier< Mesh_ >::find_param (const DataType x) const inline protected
Definition at line 961 of file bezier.hpp.
get_normal_on_segment()
template<typename Mesh_ > WorldPoint FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_normal_on_segment (const Index i, const DataType t) const inline
Computes the outer unit normal in a single point.
Parameters
[in] i The segment index onto which to compute the normal.
[in] t The local segment parameter.
Returns
The outer unit normal in the point given by t.
Definition at line 340 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_orientation, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world, ASSERTM, and FEAT::Geometry::Atlas::Bezier< Mesh_ >::max_degree.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist().
get_orientation()
template<typename Mesh_ > int FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_orientation () const inline
Returns the orientation code for the curve.
Returns
+1 if the curve is positively oriented or -1 if it's negatively oriented.
Definition at line 196 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_orientation.
get_type()
template<typename Mesh_ > virtual String FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_type () const inline override virtual
Writes the type as String.
Needed for writing this to mesh files.
Returns
The class name as String.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 133 of file bezier.hpp.
get_vertex_pointers() [1/2]
template<typename Mesh_ > std::deque< std::size_t > & FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_vertex_pointers () inline
Returns a (const) reference to the internal vertex pointers deque.
Returns
A (const) reference to the internal vertex pointers deque.
Definition at line 249 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr.
get_vertex_pointers() [2/2]
template<typename Mesh_ > const std::deque< std::size_t > & FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_vertex_pointers () const inline
Returns a (const) reference to the internal vertex pointers deque.
Returns
A (const) reference to the internal vertex pointers deque.
Definition at line 259 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr.
get_world_points() [1/2]
template<typename Mesh_ > std::deque< WorldPoint > & FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_world_points () inline
Returns a (const) reference to the internal world points deque.
Returns
A (const) reference to the internal world points deque.
Definition at line 229 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world.
get_world_points() [2/2]
template<typename Mesh_ > const std::deque< WorldPoint > & FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_world_points () const inline
Returns a (const) reference to the internal world points deque.
Returns
A (const) reference to the internal world points deque.
Definition at line 239 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world.
is_closed()
template<typename Mesh_ > bool FEAT::Geometry::Atlas::Bezier< Mesh_ >::is_closed () const inline
Checks whether the curve is open or closed.
Returns
true, if the curve is closed, otherwise false.
Definition at line 186 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_closed.
map()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::map (const WorldPoint & param) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 456 of file chart.hpp.
map_on_segment()
template<typename Mesh_ > WorldPoint FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_on_segment (const Index i, const DataType t) const inline
Maps a local segment parameter point.
Parameters
[in] i The segment index onto which to map
[in] t The local segment parameter
Definition at line 289 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world, ASSERTM, and FEAT::Geometry::Atlas::Bezier< Mesh_ >::max_degree.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_param(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_on_segment(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_point().
map_param()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_param (WorldPoint & point, const ParamPoint & param) const inline
Maps a single parameter point.
Parameters
[out] point The image of the parameter point under the chart mapping
[in] param The parameter point to be mapped
Definition at line 618 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_on_segment(), and XASSERTM.
project()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::project (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 469 of file chart.hpp.
project_meshpart()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_meshpart (Mesh_ & mesh, const MeshPart< Mesh_ > & meshpart) const inline
Projects all mesh points identified by a meshpart.
Parameters
[in,out] mesh A transient reference to the mesh whose points will be projected
[in] meshpart The MeshPart identifying the point to be projected
Todo:
implement fancy variant here
Definition at line 717 of file bezier.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_point().
project_on_segment()
template<typename Mesh_ > DataType FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_on_segment (const Index i, const WorldPoint & point) const inline
Projects a point onto one segment of the spline.
Note
For the description of the Selimovic elimination test used in this function, see [Selimovic2006]
Parameters
[in] i The index of the spline segment onto which to project
[in] point The world point that is to be projected.
Returns
The projected world point parameter.
Definition at line 410 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world, FEAT::Math::abs(), ASSERTM, FEAT::Math::clamp(), FEAT::Tiny::dot(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::max_degree, and FEAT::Math::min().
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_point().
project_point()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_point (WorldPoint & point) const inline
Projects a single world point.
Parameters
[in,out] point The world point to be projected
Definition at line 638 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_on_segment(), and FEAT::Math::sqrt().
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_dist(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_meshpart().
push_close()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_close () inline
Marks the Bezier chart as closed.
Definition at line 176 of file bezier.hpp.
push_control()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_control (const WorldPoint & point) inline
Pushes a new control point to the spline.
Parameters
[in] point The control point to be pushed
Definition at line 157 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world.
Referenced by FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::content().
push_param()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_param (const ParamPoint & param) inline
Pushes a new parameter to the spline.
Parameters
[in] param The parameter to be pushed
Definition at line 168 of file bezier.hpp.
Referenced by FEAT::Geometry::Atlas::BezierParamsParser< Mesh_ >::content().
push_vertex()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_vertex (const WorldPoint & point) inline
Pushes a new vertex point to the spline.
Parameters
[in] point The vertex point to be pushed
Definition at line 144 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr, and FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world.
Referenced by FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::content().
set_orientation()
template<typename Mesh_ > void FEAT::Geometry::Atlas::Bezier< Mesh_ >::set_orientation (int ori) inline
Sets the orientation code for the curve.
Parameters
[in] ori The new orientation code. Must be either +1 or -1.
Definition at line 207 of file bezier.hpp.
References FEAT::Math::abs(), and XASSERTM.
signed_dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::signed_dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 492 of file chart.hpp.
signed_dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 498 of file chart.hpp.
transform() [1/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::Bezier< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) inline override virtual
Definition at line 265 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_2d().
transform() [2/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::ChartBase< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) pure virtual inherited
Applies a "proper rigid" transformation onto the chart.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any point x of the chart:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any point before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): -ignored-
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any point after applying the rotation.
Implemented in FEAT::Geometry::Atlas::CGALSurfaceMesh< Mesh_ >.
write()
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::Bezier< Mesh_ >::write (std::ostream & os, const String & sindent) const inline override virtual
Writes the Chart into a stream in XML format.
Parameters
[in,out] os The output stream to write into.
[in] sindent The indentation string.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 913 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::_orientation, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_param, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr, FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world, and FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ >, Mesh_, BezierTraits >::world_dim.
Member Data Documentation
_closed
template<typename Mesh_ > bool FEAT::Geometry::Atlas::Bezier< Mesh_ >::_closed protected
Specifies whether the spline is closed.
Definition at line 67 of file bezier.hpp.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::is_closed().
_orientation
template<typename Mesh_ > DataType FEAT::Geometry::Atlas::Bezier< Mesh_ >::_orientation protected
Specifies if the chart is to be oriented negatively or not.
Definition at line 69 of file bezier.hpp.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::Bezier(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::compute_signed_dist(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_normal_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_orientation(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::write().
_param
template<typename Mesh_ > std::deque<ParamPoint> FEAT::Geometry::Atlas::Bezier< Mesh_ >::_param protected
The parameter values for these world points.
Definition at line 65 of file bezier.hpp.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::Bezier(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::can_explicit(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::write().
_vtx_ptr
template<typename Mesh_ > std::deque<std::size_t> FEAT::Geometry::Atlas::Bezier< Mesh_ >::_vtx_ptr protected
The vertex point pointer array.
Definition at line 61 of file bezier.hpp.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::Bezier(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_normal_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_vertex_pointers(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_vertex(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::write().
_world
template<typename Mesh_ > std::deque<WorldPoint> FEAT::Geometry::Atlas::Bezier< Mesh_ >::_world protected
The vertex and control points for the spline.
Definition at line 63 of file bezier.hpp.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::Bezier(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_normal_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_world_points(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_control(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_vertex(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::transform(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::write().
is_explicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::is_explicit static constexpr inherited
specifies whether this chart is explicit
Definition at line 372 of file chart.hpp.
is_implicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::is_implicit static constexpr inherited
specifies whether this chart is implicit
Definition at line 374 of file chart.hpp.
max_degree
template<typename Mesh_ > constexpr int FEAT::Geometry::Atlas::Bezier< Mesh_ >::max_degree = 5 static constexpr
maximum allowed spline degree
Definition at line 57 of file bezier.hpp.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::Bezier(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::get_normal_on_segment(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::map_on_segment(), and FEAT::Geometry::Atlas::Bezier< Mesh_ >::project_on_segment().
param_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::param_dim static constexpr inherited
the parameter dimension of this chart
Definition at line 379 of file chart.hpp.
world_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ > , Mesh_, BezierTraits >::world_dim static constexpr inherited
the world dimension of this chart
Definition at line 377 of file chart.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/atlas/bezier.hpp