FEAT: FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ > Class Template Reference
FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ > Class Template Reference
This is a container class for holding PatchPartMaps for all dimensions.
#include <patch_meshpart_splitter.hpp>
Public Types
typedef PatchPartMapHolder< Shape_, dim_ - 1 > BaseClass
Our base class.
Public Member Functions
PatchPartMapHolder (const TargetSetHolder< Shape_ > &tsh)
Standard constructor.
bool build (const TargetSetHolder< Shape_ > &tsh, const IndexSetHolder< Shape_ > *ish)
Assembles information from a BaseMesh MeshPart.
template<typename AttributeSetContainer_ >
void fill_attribute_sets (AttributeSetContainer_ &attribute_container_out, const AttributeSetContainer_ &attribute_container_in) const
MeshPart Factory interface: Fills the AttributeSetContainer.
template<typename IndexSetHolder_ >
void fill_index_sets (IndexSetHolder_ &ish, const IndexSetHolder_ &ish_in) const
Factory interface: Fills the IndexSetHolder.
void fill_target_sets (TargetSetHolder< Shape_ > &tsh) const
Factory interface: Fills the TargetSetHolder.
Index get_num_entities (int dim) const
Gets the number of entities.
const std::map< Index, Index > & get_vertex_map () const
Gets the vertex map.
bool has_topology () const
Does the current BaseMesh MeshPart have a topology?
Private Attributes
bool _has_topology
We need to know if the last BaseMesh MeshPart from build() had a topology.
PatchPartMap _patch_map
The PatchPartMap for our dimension.
Detailed Description
template<typename Shape_, int dim_ = Shape_::dimension>
class FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >
This is a container class for holding PatchPartMaps for all dimensions.
Template Parameters
Shape_ The ShapeType this container refers to. This also defines the dimension etc.
dim_ Shape dimension this container refers to
Author
Jordi Paul
Definition at line 423 of file patch_meshpart_splitter.hpp.
Member Typedef Documentation
BaseClass
template<typename Shape_ , int dim_ = Shape_::dimension> typedef PatchPartMapHolder<Shape_, dim_ - 1> FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::BaseClass
Our base class.
Definition at line 428 of file patch_meshpart_splitter.hpp.
Constructor & Destructor Documentation
PatchPartMapHolder()
template<typename Shape_ , int dim_ = Shape_::dimension> FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::PatchPartMapHolder (const TargetSetHolder< Shape_ > & tsh) inline explicit
Standard constructor.
Parameters
[in] tsh A transient reference to the TargetSetHolder of the PatchMeshPart
Definition at line 443 of file patch_meshpart_splitter.hpp.
Member Function Documentation
build()
template<typename Shape_ , int dim_ = Shape_::dimension> bool FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::build (const TargetSetHolder< Shape_ > & tsh, const IndexSetHolder< Shape_ > * ish) inline
Assembles information from a BaseMesh MeshPart.
Parameters
[in] tsh A transient reference to the TargetSetHolder of the MeshPart referring to the BaseMesh.
[in] ish A transient pointer to the IndexSetHolder of the MeshPart referring to the BaseMesh. This is nullptr if it does not have a topology.
Returns
true if this class or its BaseClass added any information
Definition at line 462 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::_has_topology, FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::_patch_map, FEAT::Geometry::PatchPartMap::build(), and FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::build().
Referenced by FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::build(), and FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::build().
fill_attribute_sets()
template<typename Shape_ , int dim_ = Shape_::dimension> template<typename AttributeSetContainer_ > void FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_attribute_sets (AttributeSetContainer_ & attribute_container_out, const AttributeSetContainer_ & attribute_container_in) const inline
MeshPart Factory interface: Fills the AttributeSetContainer.
Template Parameters
AttributeSetContainer_ Type of the AttributeSetContainer_.
Parameters
[out] attribute_container_out A transient reference to the AttributeSetContainer of the PatchMeshPart's MeshPart to be filled
[in] attribute_container_in A transient reference to the AttributeSetContainer of the BaseMesh's MeshPart to restrict to the PatchMeshPart's MeshPart.
Definition at line 514 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_attribute_sets().
Referenced by FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::fill_attribute_sets(), and FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_attribute_sets().
fill_index_sets()
template<typename Shape_ , int dim_ = Shape_::dimension> template<typename IndexSetHolder_ > void FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_index_sets (IndexSetHolder_ & ish, const IndexSetHolder_ & ish_in) const inline
Factory interface: Fills the IndexSetHolder.
Template Parameters
IndexSetHolder_ The type of the IndexSetHolder
Parameters
[in] ish A transient reference to the PatchMeshPart MeshPart's IndexSetHolder
[in] ish_in A transient reference to the PatchMeshPart's IndexSetHolder
Note that it has to be checked beforehand if the IndexSetHolder(s) are nullptr.
Definition at line 549 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::_patch_map, FEAT::Geometry::PatchPartMap::fill_index_set(), FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_index_sets(), and FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_vertex_map().
Referenced by FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_index_sets(), and FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::fill_index_sets().
fill_target_sets()
template<typename Shape_ , int dim_ = Shape_::dimension> void FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_target_sets (TargetSetHolder< Shape_ > & tsh) const inline
Factory interface: Fills the TargetSetHolder.
Parameters
[in] tsh A transient reference to the PatchMeshPart MeshPart's TargetSetHolder
Definition at line 528 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::_patch_map, FEAT::Geometry::PatchPartMap::fill_target_set(), and FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_target_sets().
Referenced by FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_target_sets(), and FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::fill_target_sets().
get_num_entities()
template<typename Shape_ , int dim_ = Shape_::dimension> Index FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_num_entities (int dim) const inline
Gets the number of entities.
Parameters
[in] dim The dimension. Note that \(0 \leq \mathrm{dim} \leq \mathrm{shape\_dim}.\)
Returns
The number of entities of a certain dimension
Definition at line 481 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::_patch_map, FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_num_entities(), FEAT::Geometry::PatchPartMap::size(), and XASSERT.
Referenced by FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_num_entities(), and FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::get_num_entities().
get_vertex_map()
template<typename Shape_ , int dim_ = Shape_::dimension> const std::map< Index, Index > & FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_vertex_map () const inline
Gets the vertex map.
This is needed for the get_index_set function of the PatchPartMap.
Returns
The mapping of BaseMesh MeshPart vertices to PatchMeshPart MeshPart vertices
Definition at line 563 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_vertex_map().
Referenced by FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_index_sets(), and FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_vertex_map().
has_topology()
template<typename Shape_ , int dim_ = Shape_::dimension> bool FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::has_topology () const inline
Does the current BaseMesh MeshPart have a topology?
Returns
true if the MeshPart does have a topology, false otherwise.
Definition at line 496 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::_has_topology.
Referenced by FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::fill_index_sets().
Member Data Documentation
_has_topology
template<typename Shape_ , int dim_ = Shape_::dimension> bool FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::_has_topology private
We need to know if the last BaseMesh MeshPart from build() had a topology.
Definition at line 434 of file patch_meshpart_splitter.hpp.
Referenced by FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::build(), and FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::has_topology().
_patch_map
template<typename Shape_ , int dim_ = Shape_::dimension> PatchPartMap FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::_patch_map private
The PatchPartMap for our dimension.
Definition at line 432 of file patch_meshpart_splitter.hpp.
Referenced by FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::build(), FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_index_sets(), FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_target_sets(), and FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_num_entities().
The documentation for this class was generated from the following file:
kernel/geometry/patch_meshpart_splitter.hpp