FEAT: FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ > Class Template Reference
FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ > Class Template Reference abstract
Control class for HyperelasticityFunctionals.
#include <hyperelasticity_functional_control.hpp>
Public Types
typedef MeshoptControlBase< DomainControl_ > BaseClass
Our base class.
typedef LAFEM::VectorMirror< CoordType, Index > CoordsMirror
corresponding vector mirror
typedef MeshType::CoordType CoordType
The floating point type the mesh's coordinates use.
typedef DT_ DataType
The floating point type.
typedef DomainControl_ DomainControl
The type of the underlying domain control.
typedef DomainControl_ DomainControlType
The type of the domain control.
typedef DomainControl_::LayerType DomainLayerType
Domain layers.
typedef DomainControl_::LevelType DomainLevel
The type of levels of DomainControl.
typedef DomainControl_::LevelType DomainLevelType
Domain levels.
typedef Global::Vector< LocalCoordsBuffer, CoordsMirror > GlobalCoordsBuffer
The global version of LocalCoordsBuffer, needed for prepare setting the internal state variable.
typedef IT_ IndexType
The index type.
typedef LAFEM::DenseVectorBlocked< CoordType, Index, world_dim > LocalCoordsBuffer
template<typename DT2_ , typename IT2_ >
using LocalQualityFunctionalType = Hyperelasticity_< DT2_, IT2_, TrafoType >
Type of the "system matrix" for the solver.
typedef DomainControl_::MeshType MeshType
The underlying mesh type.
typedef Solver::NLOptPrecond< typename SystemLevelType::GlobalSystemVectorR, typename SystemLevelType::GlobalSystemFilter > PrecondType
Type for assembling FE space based quantities like filters, gates etc.
typedef NonlinearSystemLevel< DT_, IT_, LocalQualityFunctionalType > SystemLevelType
The system level type, holding all information about the nonlinear system of equations.
typedef LocalQualityFunctionalType< DT_, IT_ >::SpaceType TrafoSpace
The FE space the transformation lives in.
typedef DomainLevelType::TrafoType TrafoType
The transformation we solve for.
typedef LAFEM::SparseMatrixBWrappedCSR< DT_, IT_, MeshType::world_dim > TransferMatrixType
Inter level transfer matrix.
typedef Geometry::ExportVTK< MeshType > VTKExporterType
Type of the vtk exporter this (and derived classes) can write to.
Public Member Functions
HyperelasticityFunctionalControl (const HyperelasticityFunctionalControl &)=delete
Explicitly delete the default constructor.
template<typename... Args_>
HyperelasticityFunctionalControl (DomainControl_ &dom_ctrl, const int meshopt_lvl_, const std::deque< String > &dirichlet_list, const std::deque< String > &slip_list, const String &solver_name_, PropertyMap &solver_config_, Args_ &&... args)
Variadic template constructor.
virtual ~HyperelasticityFunctionalControl ()
Virtual destructor.
virtual void add_to_vtk_exporter (Geometry::ExportVTK< MeshType > &exporter, const int lvl_index) const override
Adds quantities of the underlying mesh quality functional to a given exporter object.
virtual void buffer_to_mesh () override
Copies the contents of the buffer vector to the mesh's vertex coordinates.
virtual CoordType compute_cell_size_defect (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, CoordType &vol) const =0
‍**
virtual CoordType compute_cell_size_defect (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, CoordType &vol) const override
‍**
void compute_mesh_quality (CoordType &edge_angle, CoordType &qi_min, CoordType &qi_mean, CoordType *edge_angle_cellwise=nullptr, CoordType *qi_cellwise=nullptr, int lvl_index=-1) const
Computes mesh quality heuristics.
virtual SystemLevelType::GlobalCoordsBuffer & get_coords () override
Gets the coordinates buffer vector.
const std::deque< String > & get_dirichlet_boundaries () const
Gets the names of all Dirichlet boundaries.
virtual size_t get_num_levels () const override
Get the number of levels in this object.
const std::deque< String > & get_slip_boundaries () const
Gets the names of all slip boundaries.
virtual String info () const override
virtual void mesh_to_buffer () override
Copies the mesh's vertex coordinates to the buffer vector.
virtual String name () const override
Returns a descriptive String.
virtual void optimize () override
Optimizes the current mesh.
virtual void prepare (const GlobalCoordsBuffer &vec_state)=0
Sets the internal state variable.
virtual void prepare (const typename SystemLevelType::GlobalSystemVectorR &vec_state) override
Sets the internal state variable.
Public Attributes
std::deque< SystemLevelType * > _system_levels
These hold the system information for each level.
std::shared_ptr< Solver::Linesearch< typename SystemLevelType::GlobalFunctional, typename SystemLevelType::GlobalSystemFilter > > linesearch
The linesearch method for NLCG.
int meshopt_lvl
The level index (= number of refinements since the mesh file) to optimize the mesh on.
size_t meshopt_lvl_pos
The position of this level in the deque of system levels.
std::shared_ptr< PrecondType > precond
The preconditioner. As this might involve a matrix to be assembled, we keep it between solves.
std::shared_ptr< Solver::IterativeSolver< typename SystemLevelType::GlobalSystemVectorR > > solver
The solver.
PropertyMap & solver_config
Solver configuration.
const String solver_name
Name of the solver configuration from solver_config we want.
Static Public Attributes
static constexpr int world_dim = DomainControl_::MeshType::world_dim
The world dimension, i.e. number of coordinates.
Protected Member Functions
void _create_linesearch (const String &section_name)
void _create_nonlinear_optimizer ()
Protected Attributes
std::deque< String > _dirichlet_boundaries
List of all meshparts with dirichlet boundary conditions.
DomainControl & _dom_ctrl
The domain control whose mesh objects can be modified.
std::deque< String > _slip_boundaries
List of all meshparts with slipboundary conditions.
Detailed Description
template<typename DT_, typename IT_, typename DomainControl_, template< typename, typename, typename > class Hyperelasticity_>
class FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >
Control class for HyperelasticityFunctionals.
Template Parameters
DT_ The floating point precision for the solver
IT_ Index type
DomainControl_ The domain control type this is based on
Trafo_ The mesh's underlying transformation. At the time of writing, there is only Trafo::Standard, which means P1/Q1 transformation.
Hyperelasticity_ The (patch-) local HyperelasticityFunctional to use.
See also
FEAT::Meshopt::HyperElasticityFunctionalBase
Author
Jordi Paul
Definition at line 59 of file hyperelasticity_functional_control.hpp.
Member Typedef Documentation
BaseClass
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef MeshoptControlBase<DomainControl_> FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::BaseClass
Our base class.
Definition at line 69 of file hyperelasticity_functional_control.hpp.
CoordsMirror
template<typename DomainControl_ > typedef LAFEM::VectorMirror<CoordType, Index> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::CoordsMirror inherited
corresponding vector mirror
Definition at line 80 of file meshopt_control.hpp.
CoordType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef MeshType::CoordType FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::CoordType
The floating point type the mesh's coordinates use.
Definition at line 91 of file hyperelasticity_functional_control.hpp.
DataType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef DT_ FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::DataType
The floating point type.
Definition at line 64 of file hyperelasticity_functional_control.hpp.
DomainControl
template<typename DomainControl_ > typedef DomainControl_ FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::DomainControl inherited
The type of the underlying domain control.
Definition at line 65 of file meshopt_control.hpp.
DomainControlType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef DomainControl_ FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::DomainControlType
The type of the domain control.
Definition at line 72 of file hyperelasticity_functional_control.hpp.
DomainLayerType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef DomainControl_::LayerType FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::DomainLayerType
Domain layers.
Definition at line 74 of file hyperelasticity_functional_control.hpp.
DomainLevel
template<typename DomainControl_ > typedef DomainControl_::LevelType FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::DomainLevel inherited
The type of levels of DomainControl.
Definition at line 67 of file meshopt_control.hpp.
DomainLevelType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef DomainControl_::LevelType FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::DomainLevelType
Domain levels.
Definition at line 76 of file hyperelasticity_functional_control.hpp.
GlobalCoordsBuffer
template<typename DomainControl_ > typedef Global::Vector<LocalCoordsBuffer, CoordsMirror> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::GlobalCoordsBuffer inherited
The global version of LocalCoordsBuffer, needed for prepare setting the internal state variable.
Definition at line 82 of file meshopt_control.hpp.
IndexType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef IT_ FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::IndexType
The index type.
Definition at line 66 of file hyperelasticity_functional_control.hpp.
LocalCoordsBuffer
template<typename DomainControl_ > typedef LAFEM::DenseVectorBlocked<CoordType, Index, world_dim> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::LocalCoordsBuffer inherited
Type for buffer vectors exchanging information between mesh and some vector type on which the solvers operate
Definition at line 78 of file meshopt_control.hpp.
LocalQualityFunctionalType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> template<typename DT2_ , typename IT2_ > using FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::LocalQualityFunctionalType = Hyperelasticity_<DT2_, IT2_, TrafoType>
Type of the "system matrix" for the solver.
Definition at line 83 of file hyperelasticity_functional_control.hpp.
MeshType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef DomainControl_::MeshType FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::MeshType
The underlying mesh type.
Definition at line 89 of file hyperelasticity_functional_control.hpp.
PrecondType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef Solver::NLOptPrecond< typename SystemLevelType::GlobalSystemVectorR, typename SystemLevelType::GlobalSystemFilter > FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::PrecondType
Type for assembling FE space based quantities like filters, gates etc.
Preconditioner type. Becaus the preconditioner is expensive to assemble symbolically and numerically, it is kept and recycled between nonlinear solver calls, so we have to keep it.
Definition at line 112 of file hyperelasticity_functional_control.hpp.
SystemLevelType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef NonlinearSystemLevel< DT_, IT_, LocalQualityFunctionalType > FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::SystemLevelType
The system level type, holding all information about the nonlinear system of equations.
Definition at line 101 of file hyperelasticity_functional_control.hpp.
TrafoSpace
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef LocalQualityFunctionalType<DT_,IT_>::SpaceType FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::TrafoSpace
The FE space the transformation lives in.
Definition at line 86 of file hyperelasticity_functional_control.hpp.
TrafoType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef DomainLevelType::TrafoType FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::TrafoType
The transformation we solve for.
Definition at line 79 of file hyperelasticity_functional_control.hpp.
TransferMatrixType
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> typedef LAFEM::SparseMatrixBWrappedCSR<DT_, IT_, MeshType::world_dim> FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::TransferMatrixType
Inter level transfer matrix.
Definition at line 94 of file hyperelasticity_functional_control.hpp.
VTKExporterType
template<typename DomainControl_ > typedef Geometry::ExportVTK<MeshType> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::VTKExporterType inherited
Type of the vtk exporter this (and derived classes) can write to.
Definition at line 85 of file meshopt_control.hpp.
Constructor & Destructor Documentation
HyperelasticityFunctionalControl()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> template<typename... Args_> FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl (DomainControl_ & dom_ctrl, const int meshopt_lvl_, const std::deque< String > & dirichlet_list, const std::deque< String > & slip_list, const String & solver_name_, PropertyMap & solver_config_, Args_ &&... args) inline explicit
Variadic template constructor.
Parameters
[in] dom_ctrl The domaincontrol holding all geometry information for all levels
[in] meshopt_lvl_ Index of the level to perform the mesh optimization on
[in] dirichlet_list List of meshpart identifiers for Dirichlet boundary conditions
[in] slip_list List of meshpart identifiers for slip boundary conditions
[in] solver_name_ Name of the solver to select from the solver_config_
[in] solver_config_ PropertyMap holding the solver configuration
[in] args Additional arguments passed to the constructor of the local functional
Definition at line 164 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels, FEAT::Control::Meshopt::MeshoptPrecondFactory::create_nlopt_precond(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_num_levels(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::meshopt_lvl, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::meshopt_lvl_pos, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::precond, FEAT::PropertyMap::query_section(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::solver_config, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::solver_name, XABORTM, and XASSERT.
~HyperelasticityFunctionalControl()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::~HyperelasticityFunctionalControl () inline virtual
Virtual destructor.
Definition at line 241 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::precond, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::solver.
Member Function Documentation
_create_linesearch()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> void FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_create_linesearch (const String & section_name) inline protected
Definition at line 542 of file hyperelasticity_functional_control.hpp.
_create_nonlinear_optimizer()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> void FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_create_nonlinear_optimizer () inline protected
Definition at line 586 of file hyperelasticity_functional_control.hpp.
add_to_vtk_exporter()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual void FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::add_to_vtk_exporter (Geometry::ExportVTK< MeshType > & exporter, const int lvl_index) const inline override virtual
Adds quantities of the underlying mesh quality functional to a given exporter object.
Parameters
[in,out] exporter The vtk exporter to add our data to
[in] lvl_index This level's data gets added.
Reimplemented from FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 402 of file hyperelasticity_functional_control.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_vector(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_num_levels(), and FEAT::grad.
buffer_to_mesh()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual void FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::buffer_to_mesh () inline override virtual
Copies the contents of the buffer vector to the mesh's vertex coordinates.
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 348 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_num_levels().
compute_cell_size_defect() [1/2]
template<typename DomainControl_ > virtual CoordType FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_cell_size_defect (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, CoordType & vol) const pure virtual inherited
‍**
Computes a quality indicator concerning the cell sizes
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
In a truly optimal mesh (consisting ONLY of reference cells of the right size), every cell's volume is exactly lambda(cell). This is especially the goal for r-adaptivity. So in an optimal mesh,
\[ \forall K \in \mathcal{T}_h: |K|/|\Omega| = \lambda(K) \]
so we compute the 1-norm of the vector \((v)_i = \left| \frac{|K_i|}{\sum_j |K_j|} - \lambda(K_i) \right| \).
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function uses a pre_sync and post_sync part.
See also
Meshopt::HyperelasticityFunctional::compute_cell_size_defect()
compute_cell_size_defect() [2/2]
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual CoordType FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::compute_cell_size_defect (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, CoordType & vol) const inline override virtual
‍**
Computes a quality indicator concerning the cell sizes
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
In a truly optimal mesh (consisting ONLY of reference cells of the right size), every cell's volume is exactly lambda(cell). This is especially the goal for r-adaptivity. So in an optimal mesh,
\[ \forall K \in \mathcal{T}_h: |K|/|\Omega| = \lambda(K) \]
so we compute the 1-norm of the vector \((v)_i = \left| \frac{|K_i|}{\sum_j |K_j|} - \lambda(K_i) \right| \).
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function uses a pre_sync and post_sync part.
See also
Meshopt::HyperelasticityFunctional::compute_cell_size_defect()
Definition at line 260 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels.
compute_mesh_quality()
template<typename DomainControl_ > void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_mesh_quality (CoordType & edge_angle, CoordType & qi_min, CoordType & qi_mean, CoordType * edge_angle_cellwise = nullptr, CoordType * qi_cellwise = nullptr, int lvl_index = -1) const inline inherited
Computes mesh quality heuristics.
Parameters
[out] edge_angle The worst angle between two edges. Keep in mind that in 3d, this can be >0 even for deteriorated cells.
[out] qi_min The minimum quality indicator over all cells.
[out] qi_mean The mean quality indicator overa all cells.
[out] edge_angle_cellwise For debugging or visualization purposes, this can receive the worst edge angle for every cell.
[out] qi_cellwise For debugging or visualization purposes, this can receive the quality indicator for every cell.
[in] lvl_index Index of the level to compute everything for. Defaults to the maximum level.
Definition at line 275 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl, FEAT::Dist::Comm::allreduce(), FEAT::Geometry::MeshQualityHeuristic< Shape_ >::compute(), FEAT::Dist::op_min, FEAT::Dist::op_sum, FEAT::stringify(), XABORTM, and XASSERT.
get_coords()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual SystemLevelType::GlobalCoordsBuffer & FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_coords () inline override virtual
Gets the coordinates buffer vector.
Returns
A reference to the coordinates buffer
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 342 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels.
get_dirichlet_boundaries()
template<typename DomainControl_ > const std::deque< String > & FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_dirichlet_boundaries () const inline inherited
Gets the names of all Dirichlet boundaries.
Note that each name refers to a boundary, but that boundary does not necessarily have to be present due to partitioning etc.
Returns
A deque of Strings with all Dirichlet boundary names
Definition at line 201 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dirichlet_boundaries.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info().
get_num_levels()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual size_t FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_num_levels () const inline override virtual
Get the number of levels in this object.
Returns
The number of levels.
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 287 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::add_to_vtk_exporter(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::buffer_to_mesh(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::mesh_to_buffer(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::prepare().
get_slip_boundaries()
template<typename DomainControl_ > const std::deque< String > & FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries () const inline inherited
Gets the names of all slip boundaries.
Note that each name refers to a boundary, but that boundary does not necessarily have to be present due to partitioning etc.
Returns
A deque of Strings with all slip boundary names
Definition at line 214 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_slip_boundaries.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
info()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual String FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info () const inline override virtual
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 293 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels, FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_dirichlet_boundaries(), FEAT::Statistics::get_formatted_solver_tree(), FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::meshopt_lvl, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::name(), FEAT::String::pad_back(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::precond, FEAT::stringify(), and FEAT::String::trim().
mesh_to_buffer()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual void FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::mesh_to_buffer () inline override virtual
Copies the mesh's vertex coordinates to the buffer vector.
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 376 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_num_levels().
name()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual String FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::name () const inline override virtual
Returns a descriptive String.
Returns
The class name as String
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 281 of file hyperelasticity_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
optimize()
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual void FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize () inline override virtual
Optimizes the current mesh.
Implements FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >.
Definition at line 466 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels, FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_rhs_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_sol_vector(), FEAT::Statistics::expression_target, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_num_levels(), FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries(), FEAT::Control::Meshopt::NonlinearSystemLevel< DT_, IT_, Functional_ >::global_functional, FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::meshopt_lvl_pos, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::name(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::reset_num_evals(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::solver.
prepare() [1/2]
template<typename DomainControl_ > virtual void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::prepare (const GlobalCoordsBuffer & vec_state) pure virtual inherited
Sets the internal state variable.
Parameters
[in] vec_state Global buffer vector containing (possibly new) mesh vertex coordinates
prepare() [2/2]
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> virtual void FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::prepare (const typename SystemLevelType::GlobalSystemVectorR & vec_state) inline override virtual
Sets the internal state variable.
Parameters
[in] vec_state Global buffer vector containing (possibly new) mesh vertex coordinates
Definition at line 433 of file hyperelasticity_functional_control.hpp.
References FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels, FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_num_levels(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::precond.
Member Data Documentation
_dirichlet_boundaries
template<typename DomainControl_ > std::deque<String> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dirichlet_boundaries protected inherited
List of all meshparts with dirichlet boundary conditions.
Definition at line 91 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_dirichlet_boundaries().
_dom_ctrl
template<typename DomainControl_ > DomainControl& FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl protected inherited
The domain control whose mesh objects can be modified.
Definition at line 89 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_mesh_quality(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
_slip_boundaries
template<typename DomainControl_ > std::deque<String> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_slip_boundaries protected inherited
List of all meshparts with slipboundary conditions.
Definition at line 93 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries().
_system_levels
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> std::deque<SystemLevelType*> FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::_system_levels
These hold the system information for each level.
Definition at line 115 of file hyperelasticity_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::~HyperelasticityFunctionalControl(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::buffer_to_mesh(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::compute_cell_size_defect(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_coords(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::get_num_levels(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::mesh_to_buffer(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::prepare().
linesearch
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> std::shared_ptr<Solver::Linesearch<typename SystemLevelType::GlobalFunctional, typename SystemLevelType::GlobalSystemFilter> > FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::linesearch
The linesearch method for NLCG.
Definition at line 123 of file hyperelasticity_functional_control.hpp.
meshopt_lvl
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> int FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::meshopt_lvl
The level index (= number of refinements since the mesh file) to optimize the mesh on.
Definition at line 134 of file hyperelasticity_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info().
meshopt_lvl_pos
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> size_t FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::meshopt_lvl_pos
The position of this level in the deque of system levels.
Definition at line 136 of file hyperelasticity_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
precond
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> std::shared_ptr<PrecondType> FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::precond
The preconditioner. As this might involve a matrix to be assembled, we keep it between solves.
Definition at line 132 of file hyperelasticity_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::~HyperelasticityFunctionalControl(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::prepare().
solver
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> std::shared_ptr<Solver::IterativeSolver<typename SystemLevelType::GlobalSystemVectorR> > FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::solver
The solver.
Definition at line 130 of file hyperelasticity_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::~HyperelasticityFunctionalControl(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
solver_config
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> PropertyMap& FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::solver_config
Solver configuration.
Definition at line 119 of file hyperelasticity_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl().
solver_name
template<typename DT_ , typename IT_ , typename DomainControl_ , template< typename, typename, typename > class Hyperelasticity_> const String FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::solver_name
Name of the solver configuration from solver_config we want.
Definition at line 121 of file hyperelasticity_functional_control.hpp.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl().
world_dim
template<typename DomainControl_ > constexpr int FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::world_dim = DomainControl_::MeshType::world_dim static constexpr inherited
The world dimension, i.e. number of coordinates.
Definition at line 72 of file meshopt_control.hpp.
The documentation for this class was generated from the following file:
control/meshopt/hyperelasticity_functional_control.hpp