FEAT: FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ > Class Template Reference
FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ > Class Template Reference abstract
Pointstar factory base class.
#include <pointstar_factory.hpp>
Public Member Functions
virtual DenseVector< DataType_, IndexType_ > eigenvector_min () const
Computes the eigenvector of the smallest eigenvalue.
virtual DataType_ lambda_max () const =0
Computes the largest eigenvalue of the pointstar matrix.
virtual DataType_ lambda_min () const =0
Computes the smallest eigenvalue of the pointstar matrix.
virtual SparseMatrixCSR< DataType_, IndexType_ > matrix_csr () const =0
Computes the pointstar matrix in CSR format.
virtual DataType_ spectral_cond () const
Computes the spectral condition number of the pointstar matrix.
DenseVector< DataType_, IndexType_ > vector_q2_bubble () const
Computes a Q2-bubble vector.
Protected Member Functions
PointstarFactoryBase (Index m, Index d)
Protected Attributes
Index _d
number of dimensions
Index _m
number of inner nodes per dimension
Detailed Description
template<typename DataType_, typename IndexType_>
class FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >
Pointstar factory base class.
Author
Peter Zajac
Definition at line 28 of file pointstar_factory.hpp.
Constructor & Destructor Documentation
PointstarFactoryBase()
template<typename DataType_ , typename IndexType_ > FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::PointstarFactoryBase (Index m, Index d) inline protected
Definition at line 36 of file pointstar_factory.hpp.
~PointstarFactoryBase()
template<typename DataType_ , typename IndexType_ > virtual FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::~PointstarFactoryBase () inline protected virtual
Definition at line 43 of file pointstar_factory.hpp.
Member Function Documentation
eigenvector_min()
template<typename DataType_ , typename IndexType_ > virtual DenseVector< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min () const inline virtual
Computes the eigenvector of the smallest eigenvalue.
This function generates the eigenvector with respect to the smallest eigenvalue of the corresponding pointstar matrix.
Returns
The m^d x m^d eigenvector
Definition at line 90 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and FEAT::Math::sin().
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
lambda_max()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::lambda_max () const pure virtual
Computes the largest eigenvalue of the pointstar matrix.
Returns
The largest eigenvalue of the matrix.
Implemented in FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >, and FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >.
Referenced by FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::spectral_cond().
lambda_min()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::lambda_min () const pure virtual
Computes the smallest eigenvalue of the pointstar matrix.
Returns
The smallest eigenvalue of the matrix.
Implemented in FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >, and FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >.
Referenced by FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::spectral_cond().
matrix_csr()
template<typename DataType_ , typename IndexType_ > virtual SparseMatrixCSR< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::matrix_csr () const pure virtual
Computes the pointstar matrix in CSR format.
Returns
The m^d x m^d pointstar matrix
Implemented in FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >, and FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >.
spectral_cond()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::spectral_cond () const inline virtual
Computes the spectral condition number of the pointstar matrix.
Returns
The spectral condition number of the matrix.
Definition at line 76 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::lambda_max(), and FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::lambda_min().
vector_q2_bubble()
template<typename DataType_ , typename IndexType_ > DenseVector< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble () const inline
Computes a Q2-bubble vector.
This function can be used to generate a useful solution vector for the pointstar matrix. The corresponding right hand side can be computed by multiplying this vector by the matrix.
Returns
The m^d x m^d Q2-bubble vector
Definition at line 125 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m, and FEAT::LAFEM::DenseVector< DT_, IT_ >::elements().
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
Member Data Documentation
_d
template<typename DataType_ , typename IndexType_ > Index FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_d protected
number of dimensions
Definition at line 34 of file pointstar_factory.hpp.
Referenced by FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr(), and FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble().
_m
template<typename DataType_ , typename IndexType_ > Index FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m protected
number of inner nodes per dimension
Definition at line 32 of file pointstar_factory.hpp.
Referenced by FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr_neumann(), and FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble().
The documentation for this class was generated from the following file:
kernel/lafem/pointstar_factory.hpp