FEAT: FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ > Class Template Reference
FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ > Class Template Reference
Tiny Matrix class template.
#include <tiny_algebra.hpp>
Public Types
typedef Intern::DataTypeExtractor< ValueType >::MyDataType DataType
The basic data type buried in the lowest level of the vector.
typedef Vector< T_, n_, sn_ > RowType
the type of a single matrix row
typedef T_ ValueType
the data type of the matrix
Public Member Functions
Matrix ()
default constructor
template<typename T2_ , int sma_, int sna_>
Matrix (const Matrix< T2_, m_, n_, sma_, sna_ > &a)
copy constructor
template<typename Tx_ >
Matrix (const std::initializer_list< std::initializer_list< Tx_ > > &x)
Initializer list constructor.
template<typename Tx_ >
Matrix (const std::initializer_list< Tx_ > &x)
Initializer list of Tiny::Vector constructor.
Matrix (DataType value)
value-assignment constructor
template<int k_, int l_, int sma_, int sna_, int smb_, int snb_, int smd_, int snd_>
Matrix & add_double_mat_mult (const Matrix< T_, k_, l_, sma_, sna_ > &a, const Matrix< T_, k_, m_, smb_, snb_ > &b, const Matrix< T_, l_, n_, smd_, snd_ > &d, DataType alpha=DataType(1))
Adds the algebraic matrix double-product of three other matrices onto this matrix.
template<int la_, int lb_, int sma_, int sna_, int smb_, int snb_>
Matrix & add_mat_mat_mult (const Matrix< T_, m_, la_, sma_, sna_ > &a, const Matrix< T_, lb_, n_, smb_, snb_ > &b, DataType alpha=DataType(1))
Adds the algebraic matrix-product of two other matrices onto this matrix.
template<int snx_, int sny_>
Matrix & add_outer_product (const Vector< T_, m_, snx_ > &x, const Vector< T_, n_, sny_ > &y, const DataType alpha=DataType(1))
Adds the outer product of two vectors onto the matrix.
Matrix & add_scalar_main_diag (DataType alpha)
Adds a value onto the matrix's main diagonal.
template<int l_, int snv_, int slt_, int smt_, int snt_>
Matrix & add_vec_tensor_mult (const Vector< T_, l_, snv_ > &x, const Tensor3< T_, l_, m_, n_, slt_, smt_, snt_ > &t, DataType alpha=DataType(1))
Adds the result of a vector-tensor left-product onto this matrix.
template<int sma_, int sna_>
Matrix & axpy (DataType alpha, const Matrix< T_, m_, n_, sma_, sna_ > &a)
Adds another scaled matrix onto this matrix.
DataType det () const
Returns the determinant of the matrix.
void format (DataType alpha=DataType(0))
Formats the matrix.
DataType norm_frobenius () const
Returns the Frobenius norm of the matrix.
DataType norm_frobenius_sqr () const
Returns the Frobenius norm squared of the matrix.
DataType norm_hessian_sqr () const
Returns the Hessian norm square.
DataType norm_sub_id_frobenius () const
Returns the Frobenius norm of the difference of this matrix and the identity matrix.
T_ & operator() (int i, int j)
Access operator.
const T_ & operator() (int i, int j) const
Access operator.
Matrix & operator*= (DataType alpha)
scalar-right-multiply-by operator
template<int sma_, int sna_>
Matrix & operator+= (const Matrix< T_, m_, n_, sma_, sna_ > &a)
matrix component-wise addition operator
template<int sma_, int sna_>
Matrix & operator-= (const Matrix< T_, m_, n_, sma_, sna_ > &a)
matrix component-wise subtraction operator
template<int sma_, int sna_>
Matrix & operator= (const Matrix< T_, m_, n_, sma_, sna_ > &a)
assignment operator
template<typename Tx_ >
Matrix & operator= (const std::initializer_list< std::initializer_list< Tx_ > > &x)
Initializer list assignment operator.
template<typename Tx_ >
Matrix & operator= (const std::initializer_list< Tx_ > &x)
Initializer list assignment operator.
Matrix & operator= (DataType value)
value-assignment operator
RowType & operator[] (int i)
Row-Access operator.
const RowType & operator[] (int i) const
Row-Access operator.
template<int snx_, int sny_>
DataType scalar_product (const Vector< T_, m_, snx_ > &x, const Vector< T_, n_, sny_ > &y) const
Computes the scalar product of two vectors with this matrix.
template<int sma_, int sna_>
Matrix & set_cofactor (const Matrix< T_, m_, n_, sma_, sna_ > &a)
Sets this matrix to the cofactor matrix of another matrix.
template<int k_, int l_, int sma_, int sna_, int smb_, int snb_, int smd_, int snd_>
Matrix & set_double_mat_mult (const Matrix< T_, k_, l_, sma_, sna_ > &a, const Matrix< T_, k_, m_, smb_, snb_ > &b, const Matrix< T_, l_, n_, smd_, snd_ > &d, T_ alpha=T_(1))
Sets this matrix to the algebraic matrix double-product of three other matrices.
template<int l_, int sla_, int sna_>
Matrix & set_gram (const Matrix< T_, l_, n_, sla_, sna_ > &a)
Sets this matrix to the Gram matrix of another matrix.
Matrix & set_identity ()
Sets this matrix to the identity matrix.
template<int sma_, int sna_>
Matrix & set_inverse (const Matrix< T_, m_, n_, sma_, sna_ > &a)
Sets this matrix to the inverse of another matrix.
template<int la_, int lb_, int sma_, int sna_, int smb_, int snb_>
Matrix & set_mat_mat_mult (const Matrix< T_, m_, la_, sma_, sna_ > &a, const Matrix< T_, lb_, n_, smb_, snb_ > &b)
Sets this matrix to the algebraic matrix-product of two other matrices.
template<int snx_, int sny_>
Matrix & set_outer_product (const Vector< T_, m_, snx_ > &x, const Vector< T_, n_, sny_ > &y)
Sets this matrix to the outer product of two vectors.
Matrix & set_rotation_2d (T_ angle)
Sets this matrix to a 2D rotation matrix.
Matrix & set_rotation_3d (T_ yaw, T_ pitch, T_ roll)
Sets this matrix to a 3D yaw-pitch-roll rotation matrix.
template<int sma_, int sna_>
Matrix & set_transpose (const Matrix< T_, n_, m_, sma_, sna_ > &a)
Sets this matrix to the transpose of another matrix.
template<int l_, int snv_, int slt_, int smt_, int snt_>
Matrix & set_vec_tensor_mult (const Vector< T_, l_, snv_ > &x, const Tensor3< T_, l_, m_, n_, slt_, smt_, snt_ > &t, DataType alpha=DataType(1))
Sets this matrix to the result of a vector-tensor left-product.
template<int mm_, int nn_>
Matrix< T_, mm_, nn_, sm_, sn_ > & size_cast ()
Size-cast function.
template<int mm_, int nn_>
const Matrix< T_, mm_, nn_, sm_, sn_ > & size_cast () const
Size-cast function.
DataType trace () const
Returns the trace of the matrix.
DataType vol () const
Returns the volume of the matrix.
Static Public Member Functions
static Matrix null ()
Returns a null-matrix.
Public Attributes
RowType v [sm_]
actual matrix data; that's an array of vectors
Static Public Attributes
static constexpr int m = m_
the row count of the matrix
static constexpr int n = n_
the column count of the matrix
static constexpr int sm = sm_
the row stride of the matrix
static constexpr int sn = sn_
the column stride of the matrix
Friends
std::ostream & operator<< (std::ostream &lhs, const Matrix &A)
Tiny::Matrix streaming operator.
Detailed Description
template<typename T_, int m_, int n_, int sm_ = m_, int sn_ = n_>
class FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >
Tiny Matrix class template.
This class template implements a matrix whose value type and size is given at compile-time. The value type can be a primitive type, or some other object like a Vector.
Template Parameters
T_ The datatype that the vector shall contain.
m_,n_ The number rows and columns of the matrix. Must be > 0.
sm_ The row stride of the matrix. Must be >= m_.
sn_ The column stride of the matrix. Must be >= n_.
Author
Peter Zajac
Definition at line 77 of file tiny_algebra.hpp.
Member Typedef Documentation
DataType
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> typedef Intern::DataTypeExtractor<ValueType>::MyDataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::DataType
The basic data type buried in the lowest level of the vector.
Definition at line 785 of file tiny_algebra.hpp.
RowType
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> typedef Vector<T_, n_, sn_> FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::RowType
the type of a single matrix row
Definition at line 788 of file tiny_algebra.hpp.
ValueType
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> typedef T_ FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::ValueType
the data type of the matrix
Definition at line 783 of file tiny_algebra.hpp.
Constructor & Destructor Documentation
Matrix() [1/5]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::Matrix () inline
default constructor
Definition at line 793 of file tiny_algebra.hpp.
Referenced by FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::null().
Matrix() [2/5]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::Matrix (DataType value) inline explicit
value-assignment constructor
Definition at line 798 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v, and FEAT::value.
Matrix() [3/5]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<typename T2_ , int sma_, int sna_> FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::Matrix (const Matrix< T2_, m_, n_, sma_, sna_ > & a) inline
copy constructor
Definition at line 808 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Matrix() [4/5]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<typename Tx_ > FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::Matrix (const std::initializer_list< Tx_ > & x) inline explicit
Initializer list of Tiny::Vector constructor.
Tiny::Vector<double, 2> v{...}, w{...};
Tiny::Matrix<double, 2, 2> m{v, w};
Parameters
[in] x The initializer list whose elements are to be assigned.
Definition at line 831 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v, and XASSERTM.
Matrix() [5/5]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<typename Tx_ > FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::Matrix (const std::initializer_list< std::initializer_list< Tx_ > > & x) inline explicit
Initializer list constructor.
Note
This overload seems to be necessary, because the example code below does not compile otherwise for some reason that I do not understand...
Tiny::Matrix<double, 2, 2> v{{0.0, 1.0}, {2.0, 3.0}};
Parameters
[in] x The initializer list whose elements are to be assigned.
Definition at line 853 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v, and XASSERTM.
Member Function Documentation
add_double_mat_mult()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int k_, int l_, int sma_, int sna_, int smb_, int snb_, int smd_, int snd_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_double_mat_mult (const Matrix< T_, k_, l_, sma_, sna_ > & a, const Matrix< T_, k_, m_, smb_, snb_ > & b, const Matrix< T_, l_, n_, smd_, snd_ > & d, DataType alpha = DataType(1)) inline
Adds the algebraic matrix double-product of three other matrices onto this matrix.
Let C denote this m-by-n matrix, B the left k-by-m input matrix, D the right l-by-n input matrix and A the inner k-by-l input matrix, then this operation computes:
\[ C \leftarrow C + \alpha B^\top\cdot A\cdot D\]
Parameters
[in] a The inner k-by-l multiplicand matrix.
[in] b The left k-by-m multiplicand matrix.
[in] d The right l-by-n multiplicand matrix.
[in] alpha A scaling factor for the product.
Returns
*this
Definition at line 1508 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_double_mat_mult().
add_mat_mat_mult()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int la_, int lb_, int sma_, int sna_, int smb_, int snb_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_mat_mat_mult (const Matrix< T_, m_, la_, sma_, sna_ > & a, const Matrix< T_, lb_, n_, smb_, snb_ > & b, DataType alpha = DataType(1)) inline
Adds the algebraic matrix-product of two other matrices onto this matrix.
Let C denote this matrix, and let A denote the left m-by-l matrix and B the right l-by-n matrix, then this function computes:
\[ C\leftarrow C + \alpha A\cdot B \]
Parameters
[in] a The left m-by-l multiplicand matrix.
[in] b The right l-by-n multiplicand matrix.
[in] alpha A scaling factor for the product.
Returns
*this
Definition at line 1434 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_mat_mat_mult().
add_outer_product()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int snx_, int sny_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_outer_product (const Vector< T_, m_, snx_ > & x, const Vector< T_, n_, sny_ > & y, const DataType alpha = DataType(1)) inline
Adds the outer product of two vectors onto the matrix.
This function performs:
\[ a_{ij} \leftarrow a_{ij} + \alpha x_i y_j \]
Parameters
[in] x The left multiplicand vector of size m_.
[in] y The right multiplicand vector of size n_.
[in] alpha The scaling factor for the outer product.
Returns
*this
Definition at line 1334 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::BurgersBlockedAssemblyTaskBase< Job_, DataType_, block_size_ >::assemble_burgers_point(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::OldroydAssembler::assemble_matrix(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_vector(), FEAT::Assembly::VelocityAnalyser::compute(), FEAT::Assembly::DiscreteEvaluator::eval_fe_gradient_function(), and FEAT::Assembly::BurgersAssemblyTaskBase< Job_, DataType_ >::prepare_point().
add_scalar_main_diag()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_scalar_main_diag (DataType alpha) inline
Adds a value onto the matrix's main diagonal.
Parameters
[in] alpha The value that is to be added onto the main diagonal.
Definition at line 1408 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::BurgersBlockedAssemblyTaskBase< Job_, DataType_, block_size_ >::assemble_burgers_point(), FEAT::Assembly::OldroydAssembler::assemble_matrix(), FEAT::Assembly::BurgersBlockedAssemblyTaskBase< Job_, DataType_, block_size_ >::assemble_streamline_diffusion(), FEAT::Assembly::Common::LaplaceOperatorBlocked< dimension_ >::Evaluator< AsmTraits_ >::eval(), FEAT::Assembly::Common::IdentityOperatorBlocked< dimension_ >::Evaluator< AsmTraits_ >::eval(), and FEAT::Assembly::Common::DuDvOperatorBlocked< dimension_ >::Evaluator< AsmTraits_ >::eval().
add_vec_tensor_mult()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int l_, int snv_, int slt_, int smt_, int snt_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_vec_tensor_mult (const Vector< T_, l_, snv_ > & x, const Tensor3< T_, l_, m_, n_, slt_, smt_, snt_ > & t, DataType alpha = DataType(1)) inline
Adds the result of a vector-tensor left-product onto this matrix.
Let A denote this m-by-n matrix, v the l-size input vector and T the l-by-m-by-b input tensor, then this operation computes:
\[ \forall i\in\{0,...,m-1\},j\in\{0,...,n-1\}:~ A_{ij} \leftarrow A_{ij} + \alpha \sum_{k=0}^{l-1} v_k\cdot T_{kij}\]
Note
This function is used for the computation of second-order derivatives by the chain rule.
Parameters
[in] x The l-size vector that serves as a left multiplicand.
[in] t The l-by-m-by-n tensor that serves as a right multiplicand.
[in] alpha A scaling factor for the product.
Returns
*this
Definition at line 1597 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_vec_tensor_mult().
axpy()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int sma_, int sna_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::axpy (DataType alpha, const Matrix< T_, m_, n_, sma_, sna_ > & a) inline
Adds another scaled matrix onto this matrix.
Parameters
[in] alpha The scaling parameter for the axpy.
[in] a The matrix to be added onto this matrix.
Returns
*this
Definition at line 1390 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::BurgersBlockedAssemblyTaskBase< Job_, DataType_, block_size_ >::assemble_burgers_point(), and FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_vector().
det()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> DataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::det () const inline
Returns the determinant of the matrix.
Warning
This function only works for m_ = n_ and will intentionally fail to compile in any other case.
Returns
The determinant of the matrix.
Definition at line 1149 of file tiny_algebra.hpp.
format()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> void FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format (DataType alpha = DataType(0)) inline
Formats the matrix.
Parameters
[in] alpha The value that the matrix is to be set to.
Definition at line 1037 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::format(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::BurgersBlockedAssemblyTaskBase< Job_, DataType_, block_size_ >::assemble(), FEAT::Assembly::BurgersScalarAssemblyTaskBase< Job_, DataType_ >::assemble(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_functional_vector(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_operator_matrix(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_stabil_operator_matrix(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::OldroydAssembler::assemble_matrix(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2(), FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::GridTransfer::assemble_truncation(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_vector(), FEAT::Assembly::VelocityAnalyser::compute(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Assembly::DiscreteEvaluator::eval_fe_gradient_function(), FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::mean_value(), FEAT::Assembly::MatrixDiscreteEvalData< DT_, dim_i_, dim_j_ >::mean_value_dist(), FEAT::Space::Argyris::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Simplex< 2 > >::prepare(), FEAT::Assembly::BurgersAssemblyTaskBase< Job_, DataType_ >::prepare_point(), FEAT::Assembly::GridTransfer::prolongate_vector(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_double_mat_mult(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_gram(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_mat_mat_mult(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_vec_tensor_mult().
norm_frobenius()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> DataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_frobenius () const inline
Returns the Frobenius norm of the matrix.
This function computes and returns
\[ \Big(\sum_{i=0}^{m-1}\sum_{j=0}^{n-1} (A_{ij})^2\Big)^{\frac{1}{2}} \]
Returns
The Frobenius norm of the matrix.
Definition at line 1078 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_frobenius_sqr(), and FEAT::Math::sqrt().
Referenced by FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::GridTransfer::assemble_truncation(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_vector(), and FEAT::Assembly::GridTransfer::prolongate_vector().
norm_frobenius_sqr()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> DataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_frobenius_sqr () const inline
Returns the Frobenius norm squared of the matrix.
This function computes and returns
\[ \sum_{i=0}^{m-1}\sum_{j=0}^{n-1} (A_{ij})^2\]
Returns
The Frobenius norm of the matrix.
Definition at line 1091 of file tiny_algebra.hpp.
References FEAT::Math::sqr(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_frobenius().
norm_hessian_sqr()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> DataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_hessian_sqr () const inline
Returns the Hessian norm square.
This function computes and returns
\[ \sum_{i=0}^{m-1}\sum_{j=0}^{n-1} K_{ij}\cdot (A_{ij})^2 \]
where K_ij is 1 for i=j and 1/2 otherwise.
Note
This function is used for the computation of the H^2 semi-norm of a function.
Returns
The Hessian norm square of the matrix.
Definition at line 1056 of file tiny_algebra.hpp.
References FEAT::Math::sqr(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::FunctionIntegralInfo< DataType_, ValueType_, GradientType_, HessianType_ >::add_hess().
norm_sub_id_frobenius()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> DataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_sub_id_frobenius () const inline
Returns the Frobenius norm of the difference of this matrix and the identity matrix.
Returns
The Frobenius norm of the difference of this matrix and the identity matrix.
Definition at line 1109 of file tiny_algebra.hpp.
References FEAT::Math::sqr(), FEAT::Math::sqrt(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::write().
null()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> static Matrix FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::null () inline static
Returns a null-matrix.
Definition at line 1714 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::Matrix().
operator()() [1/2]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> T_ & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator() (int i, int j) inline
Access operator.
Parameters
[in] i,j The indices of the matrix entry that is to be returned.
Returns
A (const) reference to the matrix entry at position (i,j).
Definition at line 934 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
operator()() [2/2]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> const T_ & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator() (int i, int j) const inline
Access operator.
Parameters
[in] i,j The indices of the matrix entry that is to be returned.
Returns
A (const) reference to the matrix entry at position (i,j).
Definition at line 942 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
operator*=()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator*= (DataType alpha) inline
scalar-right-multiply-by operator
Definition at line 1000 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
operator+=()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int sma_, int sna_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator+= (const Matrix< T_, m_, n_, sma_, sna_ > & a) inline
matrix component-wise addition operator
Definition at line 1011 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
operator-=()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int sma_, int sna_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator-= (const Matrix< T_, m_, n_, sma_, sna_ > & a) inline
matrix component-wise subtraction operator
Definition at line 1022 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
operator=() [1/4]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int sma_, int sna_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator= (const Matrix< T_, m_, n_, sma_, sna_ > & a) inline
assignment operator
Definition at line 873 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
operator=() [2/4]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<typename Tx_ > Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator= (const std::initializer_list< std::initializer_list< Tx_ > > & x) inline
Initializer list assignment operator.
Tiny::Matrix<double, 2, 2> m;
m = {{0.0, 1.0}, {2.0, 3.0}};
Parameters
[in] x The initializer list whose elements are to be assigned.
Definition at line 916 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v, and XASSERTM.
operator=() [3/4]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<typename Tx_ > Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator= (const std::initializer_list< Tx_ > & x) inline
Initializer list assignment operator.
Tiny::Vector<double, 2> v{1.0, 2.0}, w{3.0, 4.0};
Tiny::Matrix<double, 2, 2> m;
m = {v, w};
Parameters
[in] x The initializer list whose elements are to be assigned.
Definition at line 895 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v, and XASSERTM.
operator=() [4/4]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator= (DataType value) inline
value-assignment operator
Definition at line 862 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v, and FEAT::value.
operator[]() [1/2]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> RowType & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator[] (int i) inline
Row-Access operator.
Parameters
[in] i The index of the row that is to be returned.
Returns
A (const) reference to the i-th row of the matrix.S
Definition at line 958 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
operator[]() [2/2]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> const RowType & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator[] (int i) const inline
Row-Access operator.
Parameters
[in] i The index of the row that is to be returned.
Returns
A (const) reference to the i-th row of the matrix.S
Definition at line 965 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
scalar_product()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int snx_, int sny_> DataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::scalar_product (const Vector< T_, m_, snx_ > & x, const Vector< T_, n_, sny_ > & y) const inline
Computes the scalar product of two vectors with this matrix.
This function returns
\[ x^\top\cdot A\cdot y = \sum_{i=0}^{m-1}\sum_{j=0}^{n-1} x_i\cdot A_{ij}\cdot y_j\]
Parameters
[in] x The left muliplicant vector of size m_.
[in] y The right multiplicand vector of size n_.
Returns
The scalar product of x and y with this matrix.
Definition at line 1306 of file tiny_algebra.hpp.
References FEAT::Tiny::dot(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::Common::LaplaceBeltramiOperator::Evaluator< AsmTraits_ >::eval().
set_cofactor()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int sma_, int sna_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_cofactor (const Matrix< T_, m_, n_, sma_, sna_ > & a) inline
Sets this matrix to the cofactor matrix of another matrix.
\(\mathrm{Cof}(A) \) is the cofactor matrix of \(A \). If \(A \in \mathbb{R}^{n \times n}\), define \(A^{(i,j)} \in \mathbb{R}^{n-1 \times n-1}\) as the matrix obtained by deleting the \(i \)th column and \(j \)th row of \(A \). Then
\[ \mathrm{Cof}(A)_{i,j} = (-1)^{i+j} \det(A^{(i,j)}) \]
and if \(A \in \mathrm{GL}_n\), \(\mathrm{Cof}(A) = \det(A) A^{-T} \).
Warning
This function only works for m_ = n_ and will intentionally fail to compile in any other case.
Parameters
[in] a The matrix whose cofactor matrix is to be stored in this matrix.
Returns
*this
Definition at line 1219 of file tiny_algebra.hpp.
References ASSERTM.
set_double_mat_mult()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int k_, int l_, int sma_, int sna_, int smb_, int snb_, int smd_, int snd_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_double_mat_mult (const Matrix< T_, k_, l_, sma_, sna_ > & a, const Matrix< T_, k_, m_, smb_, snb_ > & b, const Matrix< T_, l_, n_, smd_, snd_ > & d, T_ alpha = T_(1)) inline
Sets this matrix to the algebraic matrix double-product of three other matrices.
Let C denote this m-by-n matrix, B the left k-by-m input matrix, D the right l-by-n input matrix and A the inner k-by-l input matrix, then this operation computes:
\[ C \leftarrow B^\top\cdot A\cdot D\]
Parameters
[in] a The inner k-by-l multiplicand matrix.
[in] b The left k-by-m multiplicand matrix.
[in] d The right l-by-n multiplicand matrix.
[in] alpha A scaling factor for the product.
Returns
*this
Definition at line 1561 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_double_mat_mult(), ASSERTM, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format().
set_gram()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int l_, int sla_, int sna_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_gram (const Matrix< T_, l_, n_, sla_, sna_ > & a) inline
Sets this matrix to the Gram matrix of another matrix.
Let C denote this n-by-n matrix, and let A denote the l-by-n input matrix, then this function computes:
\[ C\leftarrow A^\top\cdot A \]
Parameters
[in] a The matrix whose Gram matrix is to be stored in this matrix.
Returns
*this
Definition at line 1270 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
set_identity()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_identity () inline
Sets this matrix to the identity matrix.
Returns
*this
Definition at line 1652 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
set_inverse()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int sma_, int sna_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_inverse (const Matrix< T_, m_, n_, sma_, sna_ > & a) inline
Sets this matrix to the inverse of another matrix.
Warning
This function only works for m_ = n_ and will intentionally fail to compile in any other case.
Parameters
[in] a The matrix whose inverse is to be stored in this matrix.
Returns
*this
Definition at line 1187 of file tiny_algebra.hpp.
References ASSERTM.
Referenced by FEAT::Space::CroRavRanTur::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Quadrilateral >::_build_coeff_matrix(), FEAT::Space::CroRavRanTur::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hexahedron >::_build_coeff_matrix(), FEAT::Trafo::Standard::inverse_mapping(), and FEAT::Space::Argyris::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Simplex< 2 > >::prepare().
set_mat_mat_mult()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int la_, int lb_, int sma_, int sna_, int smb_, int snb_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_mat_mat_mult (const Matrix< T_, m_, la_, sma_, sna_ > & a, const Matrix< T_, lb_, n_, smb_, snb_ > & b) inline
Sets this matrix to the algebraic matrix-product of two other matrices.
Let C denote this matrix, and let A denote the left m-by-l matrix and B the right l-by-n matrix, then this function computes:
\[ C\leftarrow A\cdot B \]
Parameters
[in] a The left m-by-l multiplicand matrix.
[in] b The right l-by-n multiplicand matrix.
Returns
*this
Definition at line 1475 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_mat_mat_mult(), ASSERTM, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format().
Referenced by FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::GridTransfer::assemble_truncation(), FEAT::Tiny::operator*(), and FEAT::Assembly::GridTransfer::prolongate_vector().
set_outer_product()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int snx_, int sny_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_outer_product (const Vector< T_, m_, snx_ > & x, const Vector< T_, n_, sny_ > & y) inline
Sets this matrix to the outer product of two vectors.
This function performs:
\[ a_{ij} \leftarrow x_i y_j \]
Parameters
[in] x The left multiplicand vector of size m_.
[in] y The right multiplicand vector of size n_.
Returns
*this
Definition at line 1364 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::Common::DuDvOperatorBlocked< dimension_ >::Evaluator< AsmTraits_ >::eval().
set_rotation_2d()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_2d (T_ angle) inline
Sets this matrix to a 2D rotation matrix.
Parameters
[in] angle Specifies the rotation angle in radians
Returns
*this
Definition at line 1668 of file tiny_algebra.hpp.
References FEAT::Math::cos(), FEAT::Math::sin(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Geometry::Atlas::Bezier< Mesh_ >::transform(), and FEAT::Geometry::Atlas::Circle< Mesh_ >::transform().
set_rotation_3d()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_3d (T_ yaw, T_ pitch, T_ roll) inline
Sets this matrix to a 3D yaw-pitch-roll rotation matrix.
This function sets a 3D rotation matrix by specifying the yaw, pitch and roll angles.
The convention for the rotation is Z-Y'-X'', also known as nautical angles.
See also
https://en.wikipedia.org/wiki/Euler_angles
https://en.wikipedia.org/wiki/Aircraft_principal_axes
http://planning.cs.uiuc.edu/node102.html
Returns
*this
Definition at line 1690 of file tiny_algebra.hpp.
References FEAT::Math::cos(), FEAT::Math::sin(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_vertex_set(), FEAT::Geometry::Atlas::Sphere< Mesh_ >::transform(), and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::transform().
set_transpose()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int sma_, int sna_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_transpose (const Matrix< T_, n_, m_, sma_, sna_ > & a) inline
Sets this matrix to the transpose of another matrix.
Parameters
[in] a The matrix whose transpose is to be stored in this matrix.
Returns
*this
Definition at line 1242 of file tiny_algebra.hpp.
References ASSERTM, FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_vector(), and FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose().
set_vec_tensor_mult()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int l_, int snv_, int slt_, int smt_, int snt_> Matrix & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_vec_tensor_mult (const Vector< T_, l_, snv_ > & x, const Tensor3< T_, l_, m_, n_, slt_, smt_, snt_ > & t, DataType alpha = DataType(1)) inline
Sets this matrix to the result of a vector-tensor left-product.
Let A denote this m-by-n matrix, v the l-size input vector and T the l-by-m-by-b input tensor, then this operation computes:
\[ \forall i\in\{0,...,m-1\},j\in\{0,...,n-1\}:~ A_{ij} \leftarrow \alpha \sum_{k=0}^{l-1} v_k\cdot T_{kij}\]
Note
This function is used for the computation of second-order derivatives by the chain rule.
Parameters
[in] x The l-size vector that serves as a left multiplicand.
[in] t The l-by-m-by-n tensor that serves as a right multiplicand.
[in] alpha A scaling factor for the product.
Returns
*this
Definition at line 1638 of file tiny_algebra.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_vec_tensor_mult(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format().
size_cast() [1/2]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int mm_, int nn_> Matrix< T_, mm_, nn_, sm_, sn_ > & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::size_cast () inline
Size-cast function.
This function casts this matrix's reference to another size.
Template Parameters
mm_,nn_ The dimensions of the casted matrix. Must be 0 < mm_ <= sm_ and 0 < nn_ <= sn_.
Returns
A casted (const) reference of *this.
Definition at line 983 of file tiny_algebra.hpp.
size_cast() [2/2]
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> template<int mm_, int nn_> const Matrix< T_, mm_, nn_, sm_, sn_ > & FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::size_cast () const inline
Size-cast function.
This function casts this matrix's reference to another size.
Template Parameters
mm_,nn_ The dimensions of the casted matrix. Must be 0 < mm_ <= sm_ and 0 < nn_ <= sn_.
Returns
A casted (const) reference of *this.
Definition at line 992 of file tiny_algebra.hpp.
trace()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> DataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::trace () const inline
Returns the trace of the matrix.
This function computes and returns
\[ \sum_{i=0}^{\min(m,n)} A_{ii}\]
i.e. the sum of all main diagonal elements.
Returns
The trace of the matrix.
Definition at line 1131 of file tiny_algebra.hpp.
References FEAT::Math::min(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Assembly::FunctionIntegralInfo< DataType_, ValueType_, GradientType_, HessianType_ >::add_grad(), and FEAT::Assembly::VelocityAnalyser::compute().
vol()
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> DataType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::vol () const inline
Returns the volume of the matrix.
The volume of a matrix A is defined as:
\[ \textnormal{vol}(A) := \sqrt{\textnormal{det}(A^\top\cdot A)} \]
Note
For m_ = n_, the volume of the matrix equals the absolute of its determinant.
For m_ < n_, the volume of the matrix is always zero.
Returns
The volume of the matrix.
Definition at line 1168 of file tiny_algebra.hpp.
Friends And Related Function Documentation
operator<<
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> std::ostream & operator<< (std::ostream & lhs, const Matrix< T_, m_, n_, sm_, sn_ > & A) friend
Tiny::Matrix streaming operator.
Parameters
[in] lhs The target stream.
[in] A The matrix to be streamed.
Definition at line 1725 of file tiny_algebra.hpp.
Member Data Documentation
m
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> constexpr int FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::m = m_ static constexpr
the row count of the matrix
Definition at line 774 of file tiny_algebra.hpp.
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::get_normal_on_tria().
n
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> constexpr int FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::n = n_ static constexpr
the column count of the matrix
Definition at line 776 of file tiny_algebra.hpp.
Referenced by FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::get_normal_on_tria().
sm
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> constexpr int FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::sm = sm_ static constexpr
the row stride of the matrix
Definition at line 778 of file tiny_algebra.hpp.
sn
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> constexpr int FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::sn = sn_ static constexpr
the column stride of the matrix
Definition at line 780 of file tiny_algebra.hpp.
Referenced by FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::GridTransfer::assemble_truncation(), and FEAT::Assembly::GridTransfer::prolongate_vector().
v
template<typename T_ , int m_, int n_, int sm_ = m_, int sn_ = n_> RowType FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v[sm_]
actual matrix data; that's an array of vectors
Definition at line 790 of file tiny_algebra.hpp.
Referenced by FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::Matrix(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_double_mat_mult(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_mat_mat_mult(), FEAT::Tiny::Vector< T_, n_, s_ >::add_mat_vec_mult(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_outer_product(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_scalar_main_diag(), FEAT::Tiny::Vector< T_, n_, s_ >::add_vec_mat_mult(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_vec_tensor_mult(), FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::GridTransfer::assemble_truncation(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::axpy(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_frobenius_sqr(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_hessian_sqr(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_sub_id_frobenius(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator()(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator*=(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator+=(), FEAT::Tiny::Tensor3< T_, l_, m_, n_, sl_, sm_, sn_ >::operator+=(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator-=(), FEAT::Tiny::Tensor3< T_, l_, m_, n_, sl_, sm_, sn_ >::operator-=(), FEAT::Tiny::Tensor3< T_, l_, m_, n_, sl_, sm_, sn_ >::operator=(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator=(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator[](), FEAT::Assembly::GridTransfer::prolongate_vector(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::scalar_product(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_gram(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_identity(), FEAT::Tiny::Vector< T_, n_, s_ >::set_mat_vec_mult(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_outer_product(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_2d(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_rotation_3d(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_transpose(), FEAT::Tiny::Vector< T_, n_, s_ >::set_vec_mat_mult(), and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::trace().
The documentation for this class was generated from the following file:
kernel/util/tiny_algebra.hpp