FEAT: FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ > Class Template Reference
FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ > Class Template Reference
Basic Space Evaluator CRTP base-class template.
#include <evaluator_base.hpp>
Classes
struct ConfigTraits
Public Types
typedef SpaceEvalTraits_ SpaceEvalTraits
space evaluator traits
typedef SpaceEvaluator_ SpaceEvaluator
space evaluator type
typedef TrafoEvaluator::EvalTraits TrafoEvalTraits
trafo evaluator traits
typedef TrafoEvaluator_ TrafoEvaluator
trafo evaluator type
Public Member Functions
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_gradients (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function gradients on the real cell.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_hessians (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function hessians on the real cell.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_values (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function values on the real cell.
void finish ()
Releases the evaluator from the current cell.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void operator() (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Space evaluation operator.
void prepare (const TrafoEvaluator &trafo_eval)
Prepares the evaluator for a given cell.
Static Public Attributes
static constexpr int domain_dim = SpaceEvalTraits::domain_dim
trafo domain dimension
static constexpr SpaceTags eval_caps = ...
static constexpr int image_dim = SpaceEvalTraits::image_dim
trafo image dimension
static constexpr int max_local_dofs = SpaceEvalTraits::max_local_dofs
maximum number of local DOFs
Detailed Description
template<typename SpaceEvaluator_, typename TrafoEvaluator_, typename SpaceEvalTraits_>
class FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >
Basic Space Evaluator CRTP base-class template.
This class is a CRTP base-class used by various finite-element space evaluators to outsource common wrapper code which is independent of the actual finite-element in use.
Template Parameters
SpaceEvaluator_ The space evaluator class that derives from this class template.
TrafoEvaluator_ The trafo evaluator class to be used by this space evaluator.
SpaceEvalTraits_ The evaluator traits of the space evaluator.
Author
Peter Zajac
Definition at line 47 of file evaluator_base.hpp.
Member Typedef Documentation
SpaceEvalTraits
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef SpaceEvalTraits_ FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::SpaceEvalTraits
space evaluator traits
Definition at line 57 of file evaluator_base.hpp.
SpaceEvaluator
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef SpaceEvaluator_ FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::SpaceEvaluator
space evaluator type
Definition at line 51 of file evaluator_base.hpp.
TrafoEvalTraits
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef TrafoEvaluator::EvalTraits FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::TrafoEvalTraits
trafo evaluator traits
Definition at line 60 of file evaluator_base.hpp.
TrafoEvaluator
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef TrafoEvaluator_ FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::TrafoEvaluator
trafo evaluator type
Definition at line 54 of file evaluator_base.hpp.
Member Function Documentation
eval_gradients()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_gradients (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline
Evaluates the basis function gradients on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function gradients.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 195 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
eval_hessians()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_hessians (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline
Evaluates the basis function hessians on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function hessian matrices.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 215 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
eval_values()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_values (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline
Evaluates the basis function values on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function values.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 175 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
finish()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::finish () inline
Releases the evaluator from the current cell.
Definition at line 115 of file evaluator_base.hpp.
operator()()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator() (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline
Space evaluation operator.
This operator evaluates the basis functions in a point on a mesh cell.
Parameters
[out] space_data A transient reference to the space data that is to be computed.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 131 of file evaluator_base.hpp.
References FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_gradients(), FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_hessians(), FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_values(), FEAT::grad, FEAT::hess, and FEAT::value.
prepare()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::prepare (const TrafoEvaluator & trafo_eval) inline
Prepares the evaluator for a given cell.
Parameters
[in] trafo_eval A transient reference to the trafo evaluator containing the cell information.
Definition at line 108 of file evaluator_base.hpp.
Member Data Documentation
domain_dim
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > constexpr int FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::domain_dim = SpaceEvalTraits::domain_dim static constexpr
trafo domain dimension
Definition at line 63 of file evaluator_base.hpp.
eval_caps
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > constexpr SpaceTags FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_caps = ... static constexpr
Definition at line 83 of file evaluator_base.hpp.
image_dim
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > constexpr int FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::image_dim = SpaceEvalTraits::image_dim static constexpr
trafo image dimension
Definition at line 65 of file evaluator_base.hpp.
max_local_dofs
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > constexpr int FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::max_local_dofs = SpaceEvalTraits::max_local_dofs static constexpr
maximum number of local DOFs
Definition at line 67 of file evaluator_base.hpp.
The documentation for this class was generated from the following file:
kernel/space/evaluator_base.hpp