FEAT: FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ > Class Template Reference
FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ > Class Template Reference
Power-Full-Matrix meta class template.
#include <power_full_matrix.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = PowerFullMatrix< typename SubType_::template ContainerType< DT2_, IT2_ >, width_, height_ >
Our 'base' class type.
typedef PowerColMatrix< PowerRowMatrix< SubType_, width_ >, height_ > ContClass
container-class typedef
typedef SubMatrixType::DataType DataType
sub-matrix data type
typedef SubMatrixType::IndexType IndexType
sub-matrix index type
typedef SubType_ SubMatrixType
sub-matrix type
typedef PowerVector< typename SubMatrixType::VectorTypeL, height_ > VectorTypeL
Compatible L-vector type.
typedef PowerVector< typename SubMatrixType::VectorTypeR, width_ > VectorTypeR
Compatible R-vector type.
Public Member Functions
PowerFullMatrix ()
default ctor
PowerFullMatrix (const PowerFullMatrix &)=delete
deleted copy-ctor
PowerFullMatrix (const SparseLayout< IndexType, layout_id > &layout)
sub-matrix layout ctor
PowerFullMatrix (FileMode mode, const String &filename)
Constructor.
PowerFullMatrix (FileMode mode, std::istream &file, const String &directory="")
Constructor.
PowerFullMatrix (PowerFullMatrix &&other)
move ctor
virtual ~PowerFullMatrix ()
virtual destructor
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply (VectorTypeL &r, const VectorTypeR &x) const
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, DataType alpha=DataType(1)) const
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply_transposed (VectorTypeR &r, const VectorTypeL &x) const
void apply_transposed (VectorTypeR &r, const VectorTypeL &x, const VectorTypeR &y, DataType alpha=DataType(1)) const
template<int i_, int j_>
SubMatrixType & at ()
Returns a sub-matrix block.
template<int i_, int j_>
const SubMatrixType & at () const
Returns a sub-matrix block.
std::size_t bytes () const
Returns the total amount of bytes allocated.
PowerFullMatrix clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a deep copy of this matrix.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Returns the total number of columns in this matrix.
template<typename SubType2_ >
void convert (const PowerFullMatrix< SubType2_, width_, height_ > &other)
template<typename SubType2_ >
void convert_reverse (PowerFullMatrix< SubType2_, width_, height_ > &other) const
VectorTypeL create_vector_l () const
VectorTypeR create_vector_r () const
void extract_diag (VectorTypeL &diag) const
extract main diagonal vector from matrix
void format (DataType value=DataType(0))
SubMatrixType & get (int i, int j)
Returns a sub-matrix block.
const SubMatrixType & get (int i, int j) const
Returns a sub-matrix block.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
DataType max_rel_diff (const PowerFullMatrix &x) const
Retrieve the maximum relative difference of this matrix and another one y.max_rel_diff(x) returns \(\max_{0\leq i < n}\frac{|x_i-y_i|}{\max{|x_i|+|y_i|, eps}} \).
PowerFullMatrix & operator= (const PowerFullMatrix &)=delete
deleted copy-assign operator
PowerFullMatrix & operator= (PowerFullMatrix &&other)
move-assign operator
void read_from (FileMode mode, const String &filename)
Read in matrix from file.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Returns the total number of rows in this matrix.
bool same_layout (const PowerFullMatrix &x) const
Checks if the structural layout of this matrix matches that of another matrix. This excludes comparison of the actual data values.
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
template<Perspective perspective_ = Perspective::native>
Index size () const
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Returns the total number of non-zeros in this matrix.
void write_out (FileMode mode, const String &filename) const
Write out matrix to file.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr SparseLayoutId layout_id = SubMatrixType::layout_id
sub-matrix layout type
static constexpr int num_col_blocks = width_
number of column blocks (horizontal size)
static constexpr int num_row_blocks = height_
number of row blocks (vertical size)
Protected Member Functions
PowerFullMatrix (ContClass &&cont)
base-class emplacement constructor
Protected Attributes
ContClass _container
Detailed Description
template<typename SubType_, int width_, int height_>
class FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >
Power-Full-Matrix meta class template.
This class template implements a composition of m xn sub-matrices of the same class. This can be interpreted as an m-by-n matrix of other matrices.
Template Parameters
SubType_ The type of the sub-matrix.
width_ The number of sub-matrix blocks per row.
height_ The number of sub-matrix blocks per column.
Author
Peter Zajac
Definition at line 52 of file power_full_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename SubType_ , int width_, int height_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::ContainerType = PowerFullMatrix< typename SubType_::template ContainerType<DT2_, IT2_>, width_, height_>
Our 'base' class type.
Definition at line 73 of file power_full_matrix.hpp.
ContClass
template<typename SubType_ , int width_, int height_> typedef PowerColMatrix<PowerRowMatrix<SubType_, width_>, height_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::ContClass
container-class typedef
Definition at line 58 of file power_full_matrix.hpp.
DataType
template<typename SubType_ , int width_, int height_> typedef SubMatrixType::DataType FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::DataType
sub-matrix data type
Definition at line 62 of file power_full_matrix.hpp.
IndexType
template<typename SubType_ , int width_, int height_> typedef SubMatrixType::IndexType FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::IndexType
sub-matrix index type
Definition at line 64 of file power_full_matrix.hpp.
SubMatrixType
template<typename SubType_ , int width_, int height_> typedef SubType_ FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::SubMatrixType
sub-matrix type
Definition at line 60 of file power_full_matrix.hpp.
VectorTypeL
template<typename SubType_ , int width_, int height_> typedef PowerVector<typename SubMatrixType::VectorTypeL, height_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::VectorTypeL
Compatible L-vector type.
Definition at line 68 of file power_full_matrix.hpp.
VectorTypeR
template<typename SubType_ , int width_, int height_> typedef PowerVector<typename SubMatrixType::VectorTypeR, width_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::VectorTypeR
Compatible R-vector type.
Definition at line 70 of file power_full_matrix.hpp.
Constructor & Destructor Documentation
PowerFullMatrix() [1/6]
template<typename SubType_ , int width_, int height_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::PowerFullMatrix (ContClass && cont) inline explicit protected
base-class emplacement constructor
Definition at line 87 of file power_full_matrix.hpp.
PowerFullMatrix() [2/6]
template<typename SubType_ , int width_, int height_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::PowerFullMatrix () inline
default ctor
Definition at line 94 of file power_full_matrix.hpp.
Referenced by FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::clone().
PowerFullMatrix() [3/6]
template<typename SubType_ , int width_, int height_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::PowerFullMatrix (const SparseLayout< IndexType, layout_id > & layout) inline explicit
sub-matrix layout ctor
Definition at line 99 of file power_full_matrix.hpp.
PowerFullMatrix() [4/6]
template<typename SubType_ , int width_, int height_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::PowerFullMatrix (PowerFullMatrix< SubType_, width_, height_ > && other) inline
move ctor
Definition at line 105 of file power_full_matrix.hpp.
PowerFullMatrix() [5/6]
template<typename SubType_ , int width_, int height_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::PowerFullMatrix (FileMode mode, const String & filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a power-full-point-matrix based on the source file.
Definition at line 118 of file power_full_matrix.hpp.
PowerFullMatrix() [6/6]
template<typename SubType_ , int width_, int height_> FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::PowerFullMatrix (FileMode mode, std::istream & file, const String & directory = "") inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Creates a power-full-matrix based on the source filestream.
Definition at line 132 of file power_full_matrix.hpp.
~PowerFullMatrix()
template<typename SubType_ , int width_, int height_> virtual FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::~PowerFullMatrix () inline virtual
virtual destructor
Definition at line 166 of file power_full_matrix.hpp.
Member Function Documentation
apply() [1/4]
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 361 of file power_full_matrix.hpp.
apply() [2/4]
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 371 of file power_full_matrix.hpp.
apply() [3/4]
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Definition at line 356 of file power_full_matrix.hpp.
apply() [4/4]
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, DataType alpha = DataType(1)) const inline
Definition at line 366 of file power_full_matrix.hpp.
apply_transposed() [1/4]
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 382 of file power_full_matrix.hpp.
apply_transposed() [2/4]
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 392 of file power_full_matrix.hpp.
apply_transposed() [3/4]
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x) const inline
Definition at line 377 of file power_full_matrix.hpp.
apply_transposed() [4/4]
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x, const VectorTypeR & y, DataType alpha = DataType(1)) const inline
Definition at line 387 of file power_full_matrix.hpp.
at() [1/2]
template<typename SubType_ , int width_, int height_> template<int i_, int j_> SubMatrixType & FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::at () inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 208 of file power_full_matrix.hpp.
at() [2/2]
template<typename SubType_ , int width_, int height_> template<int i_, int j_> const SubMatrixType & FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::at () const inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 217 of file power_full_matrix.hpp.
bytes()
template<typename SubType_ , int width_, int height_> std::size_t FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 190 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::bytes().
clone()
template<typename SubType_ , int width_, int height_> PowerFullMatrix FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a deep copy of this matrix.
Definition at line 184 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::PowerFullMatrix(), and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::clone().
columns()
template<typename SubType_ , int width_, int height_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::columns () const inline
Returns the total number of columns in this matrix.
Returns
Matrix column count if raw = false.
Raw matrix column count if raw = true.
Definition at line 315 of file power_full_matrix.hpp.
convert()
template<typename SubType_ , int width_, int height_> template<typename SubType2_ > void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::convert (const PowerFullMatrix< SubType2_, width_, height_ > & other) inline
Definition at line 423 of file power_full_matrix.hpp.
convert_reverse()
template<typename SubType_ , int width_, int height_> template<typename SubType2_ > void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::convert_reverse (PowerFullMatrix< SubType2_, width_, height_ > & other) const inline
Definition at line 429 of file power_full_matrix.hpp.
create_vector_l()
template<typename SubType_ , int width_, int height_> VectorTypeL FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::create_vector_l () const inline
Definition at line 286 of file power_full_matrix.hpp.
create_vector_r()
template<typename SubType_ , int width_, int height_> VectorTypeR FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::create_vector_r () const inline
Definition at line 291 of file power_full_matrix.hpp.
extract_diag()
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::extract_diag (VectorTypeL & diag) const inline
extract main diagonal vector from matrix
Definition at line 350 of file power_full_matrix.hpp.
format()
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::format (DataType value = DataType(0)) inline
Definition at line 344 of file power_full_matrix.hpp.
get() [1/2]
template<typename SubType_ , int width_, int height_> SubMatrixType & FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::get (int i, int j) inline
Returns a sub-matrix block.
Parameters
[in] i,j The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i,j).
Definition at line 233 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get(), and XASSERTM.
get() [2/2]
template<typename SubType_ , int width_, int height_> const SubMatrixType & FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::get (int i, int j) const inline
Returns a sub-matrix block.
Parameters
[in] i,j The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i,j).
Definition at line 241 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get(), and XASSERTM.
get_checkpoint_size()
template<typename SubType_ , int width_, int height_> std::uint64_t FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 435 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get_checkpoint_size().
max_rel_diff()
template<typename SubType_ , int width_, int height_> DataType FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::max_rel_diff (const PowerFullMatrix< SubType_, width_, height_ > & x) const inline
Retrieve the maximum relative difference of this matrix and another one y.max_rel_diff(x) returns \(\max_{0\leq i < n}\frac{|x_i-y_i|}{\max{|x_i|+|y_i|, eps}} \).
Returns
The largest relative difference.
Definition at line 404 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::max_rel_diff().
name()
template<typename SubType_ , int width_, int height_> static String FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 333 of file power_full_matrix.hpp.
References FEAT::stringify().
operator=()
template<typename SubType_ , int width_, int height_> PowerFullMatrix & FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::operator= (PowerFullMatrix< SubType_, width_, height_ > && other) inline
move-assign operator
Definition at line 151 of file power_full_matrix.hpp.
read_from()
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::read_from (FileMode mode, const String & filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 144 of file power_full_matrix.hpp.
restore_from_checkpoint_data()
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 441 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::restore_from_checkpoint_data().
rows()
template<typename SubType_ , int width_, int height_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::rows () const inline
Returns the total number of rows in this matrix.
Returns
Matrix row count if perspective_ = false.
Raw matrix row count if perspective_ = true.
Definition at line 303 of file power_full_matrix.hpp.
same_layout()
template<typename SubType_ , int width_, int height_> bool FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::same_layout (const PowerFullMatrix< SubType_, width_, height_ > & x) const inline
Checks if the structural layout of this matrix matches that of another matrix. This excludes comparison of the actual data values.
Parameters
[in] x The matrix to compare this matrix to
Returns
true if the layouts match, false otherwise.
Definition at line 417 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::same_layout().
set_checkpoint_data()
template<typename SubType_ , int width_, int height_> std::uint64_t FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 447 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::set_checkpoint_data().
size()
template<typename SubType_ , int width_, int height_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::size () const inline
Definition at line 339 of file power_full_matrix.hpp.
used_elements()
template<typename SubType_ , int width_, int height_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::used_elements () const inline
Returns the total number of non-zeros in this matrix.
Returns
Matrix non zero element count if raw = false.
Raw matrix non zero element count if raw = true.
Definition at line 327 of file power_full_matrix.hpp.
write_out()
template<typename SubType_ , int width_, int height_> void FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::write_out (FileMode mode, const String & filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 176 of file power_full_matrix.hpp.
References FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out().
Member Data Documentation
_container
template<typename SubType_ , int width_, int height_> ContClass FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::_container protected
Definition at line 83 of file power_full_matrix.hpp.
layout_id
template<typename SubType_ , int width_, int height_> constexpr SparseLayoutId FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::layout_id = SubMatrixType::layout_id static constexpr
sub-matrix layout type
Definition at line 66 of file power_full_matrix.hpp.
num_col_blocks
template<typename SubType_ , int width_, int height_> constexpr int FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::num_col_blocks = width_ static constexpr
number of column blocks (horizontal size)
Definition at line 79 of file power_full_matrix.hpp.
num_row_blocks
template<typename SubType_ , int width_, int height_> constexpr int FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::num_row_blocks = height_ static constexpr
number of row blocks (vertical size)
Definition at line 77 of file power_full_matrix.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/power_full_matrix.hpp