FEAT: FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ > Class Template Reference
FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ > Class Template Reference abstract
Base class for Meshopt control objects.
#include <meshopt_control.hpp>
Public Types
typedef LAFEM::VectorMirror< CoordType, Index > CoordsMirror
corresponding vector mirror
typedef DomainControl_::MeshType::CoordType CoordType
Floating point type for coordinates.
typedef DomainControl_ DomainControl
The type of the underlying domain control.
typedef DomainControl_::LevelType DomainLevel
The type of levels of DomainControl.
typedef Global::Vector< LocalCoordsBuffer, CoordsMirror > GlobalCoordsBuffer
The global version of LocalCoordsBuffer, needed for prepare setting the internal state variable.
typedef LAFEM::DenseVectorBlocked< CoordType, Index, world_dim > LocalCoordsBuffer
typedef DomainControl_::MeshType MeshType
The type of mesh the DomainControl uses.
typedef Geometry::ExportVTK< MeshType > VTKExporterType
Type of the vtk exporter this (and derived classes) can write to.
Public Member Functions
MeshoptControlBase (DomainControl &dom_ctrl_, const std::deque< String > &dirichlet_boundaries, const std::deque< String > &slip_boundaries)
The simplest constructor possible.
virtual ~MeshoptControlBase ()
Empty virtual destructor.
virtual void add_to_vtk_exporter (Geometry::ExportVTK< MeshType > &exporter, const int lvl_index) const
Adds quantities of the underlying mesh quality functional to a given exporter object.
virtual void buffer_to_mesh ()=0
Copies the contents of the buffer vector to the mesh's vertex coordinates.
virtual CoordType compute_cell_size_defect (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, CoordType &vol) const =0
‍**
void compute_mesh_quality (CoordType &edge_angle, CoordType &qi_min, CoordType &qi_mean, CoordType *edge_angle_cellwise=nullptr, CoordType *qi_cellwise=nullptr, int lvl_index=-1) const
Computes mesh quality heuristics.
virtual GlobalCoordsBuffer & get_coords ()=0
Gets the coordinates buffer vector.
const std::deque< String > & get_dirichlet_boundaries () const
Gets the names of all Dirichlet boundaries.
virtual size_t get_num_levels () const =0
Get the number of levels in this object.
const std::deque< String > & get_slip_boundaries () const
Gets the names of all slip boundaries.
virtual String info () const =0
Prints settings of the control object.
virtual void mesh_to_buffer ()=0
Copies the mesh's vertex coordinates to the buffer vector.
virtual String name () const =0
Returns a descriptive String.
virtual void optimize ()=0
Optimizes the current mesh.
virtual void prepare (const GlobalCoordsBuffer &vec_state)=0
Sets the internal state variable.
Static Public Attributes
static constexpr int world_dim = DomainControl_::MeshType::world_dim
The world dimension, i.e. number of coordinates.
Protected Attributes
std::deque< String > _dirichlet_boundaries
List of all meshparts with dirichlet boundary conditions.
DomainControl & _dom_ctrl
The domain control whose mesh objects can be modified.
std::deque< String > _slip_boundaries
List of all meshparts with slipboundary conditions.
Detailed Description
template<typename DomainControl_>
class FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >
Base class for Meshopt control objects.
Template Parameters
DomainControl_ Type of the underlying domain control
For every mesh quality functional, there is a control class which inherits from this. This class only knows the bare minimum.
Definition at line 62 of file meshopt_control.hpp.
Member Typedef Documentation
CoordsMirror
template<typename DomainControl_ > typedef LAFEM::VectorMirror<CoordType, Index> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::CoordsMirror
corresponding vector mirror
Definition at line 81 of file meshopt_control.hpp.
CoordType
template<typename DomainControl_ > typedef DomainControl_::MeshType::CoordType FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::CoordType
Floating point type for coordinates.
Definition at line 75 of file meshopt_control.hpp.
DomainControl
template<typename DomainControl_ > typedef DomainControl_ FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::DomainControl
The type of the underlying domain control.
Definition at line 66 of file meshopt_control.hpp.
DomainLevel
template<typename DomainControl_ > typedef DomainControl_::LevelType FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::DomainLevel
The type of levels of DomainControl.
Definition at line 68 of file meshopt_control.hpp.
GlobalCoordsBuffer
template<typename DomainControl_ > typedef Global::Vector<LocalCoordsBuffer, CoordsMirror> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::GlobalCoordsBuffer
The global version of LocalCoordsBuffer, needed for prepare setting the internal state variable.
Definition at line 83 of file meshopt_control.hpp.
LocalCoordsBuffer
template<typename DomainControl_ > typedef LAFEM::DenseVectorBlocked<CoordType, Index, world_dim> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::LocalCoordsBuffer
Type for buffer vectors exchanging information between mesh and some vector type on which the solvers operate
Definition at line 79 of file meshopt_control.hpp.
MeshType
template<typename DomainControl_ > typedef DomainControl_::MeshType FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::MeshType
The type of mesh the DomainControl uses.
Definition at line 70 of file meshopt_control.hpp.
VTKExporterType
template<typename DomainControl_ > typedef Geometry::ExportVTK<MeshType> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::VTKExporterType
Type of the vtk exporter this (and derived classes) can write to.
Definition at line 86 of file meshopt_control.hpp.
Constructor & Destructor Documentation
MeshoptControlBase()
template<typename DomainControl_ > FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::MeshoptControlBase (DomainControl & dom_ctrl_, const std::deque< String > & dirichlet_boundaries, const std::deque< String > & slip_boundaries) inline explicit
The simplest constructor possible.
Definition at line 101 of file meshopt_control.hpp.
~MeshoptControlBase()
template<typename DomainControl_ > virtual FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::~MeshoptControlBase () inline virtual
Empty virtual destructor.
Definition at line 112 of file meshopt_control.hpp.
Member Function Documentation
add_to_vtk_exporter()
template<typename DomainControl_ > virtual void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::add_to_vtk_exporter (Geometry::ExportVTK< MeshType > & exporter, const int lvl_index) const inline virtual
Adds quantities of the underlying mesh quality functional to a given exporter object.
Parameters
[in,out] exporter The vtk exporter to add our data to
[in] lvl_index This level's data gets added.
Reimplemented in FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >.
Definition at line 243 of file meshopt_control.hpp.
buffer_to_mesh()
template<typename DomainControl_ > virtual void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::buffer_to_mesh () pure virtual
Copies the contents of the buffer vector to the mesh's vertex coordinates.
Implemented in FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >.
compute_cell_size_defect()
template<typename DomainControl_ > virtual CoordType FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_cell_size_defect (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, CoordType & vol) const pure virtual
‍**
Computes a quality indicator concerning the cell sizes
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
In a truly optimal mesh (consisting ONLY of reference cells of the right size), every cell's volume is exactly lambda(cell). This is especially the goal for r-adaptivity. So in an optimal mesh,
\[ \forall K \in \mathcal{T}_h: |K|/|\Omega| = \lambda(K) \]
so we compute the 1-norm of the vector \((v)_i = \left| \frac{|K_i|}{\sum_j |K_j|} - \lambda(K_i) \right| \).
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function uses a pre_sync and post_sync part.
See also
Meshopt::HyperelasticityFunctional::compute_cell_size_defect()
compute_mesh_quality()
template<typename DomainControl_ > void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_mesh_quality (CoordType & edge_angle, CoordType & qi_min, CoordType & qi_mean, CoordType * edge_angle_cellwise = nullptr, CoordType * qi_cellwise = nullptr, int lvl_index = -1) const inline
Computes mesh quality heuristics.
Parameters
[out] edge_angle The worst angle between two edges. Keep in mind that in 3d, this can be >0 even for deteriorated cells.
[out] qi_min The minimum quality indicator over all cells.
[out] qi_mean The mean quality indicator overa all cells.
[out] edge_angle_cellwise For debugging or visualization purposes, this can receive the worst edge angle for every cell.
[out] qi_cellwise For debugging or visualization purposes, this can receive the quality indicator for every cell.
[in] lvl_index Index of the level to compute everything for. Defaults to the maximum level.
Definition at line 276 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl, FEAT::Dist::Comm::allreduce(), FEAT::Geometry::MeshQualityHeuristic< Shape_ >::compute(), FEAT::Dist::op_min, FEAT::Dist::op_sum, FEAT::stringify(), XABORTM, and XASSERT.
get_coords()
template<typename DomainControl_ > virtual GlobalCoordsBuffer & FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_coords () pure virtual
Gets the coordinates buffer vector.
Returns
A reference to the coordinates buffer
Implemented in FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >.
get_dirichlet_boundaries()
template<typename DomainControl_ > const std::deque< String > & FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_dirichlet_boundaries () const inline
Gets the names of all Dirichlet boundaries.
Note that each name refers to a boundary, but that boundary does not necessarily have to be present due to partitioning etc.
Returns
A deque of Strings with all Dirichlet boundary names
Definition at line 202 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dirichlet_boundaries.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info().
get_num_levels()
template<typename DomainControl_ > virtual size_t FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_num_levels () const pure virtual
Get the number of levels in this object.
Returns
The number of levels.
Implemented in FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >.
get_slip_boundaries()
template<typename DomainControl_ > const std::deque< String > & FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries () const inline
Gets the names of all slip boundaries.
Note that each name refers to a boundary, but that boundary does not necessarily have to be present due to partitioning etc.
Returns
A deque of Strings with all slip boundary names
Definition at line 215 of file meshopt_control.hpp.
References FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_slip_boundaries.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
info()
template<typename DomainControl_ > virtual String FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::info () const pure virtual
Prints settings of the control object.
Implemented in FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >.
mesh_to_buffer()
template<typename DomainControl_ > virtual void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::mesh_to_buffer () pure virtual
Copies the mesh's vertex coordinates to the buffer vector.
Implemented in FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >.
name()
template<typename DomainControl_ > virtual String FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::name () const pure virtual
Returns a descriptive String.
Returns
The class name as String
Implemented in FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >.
optimize()
template<typename DomainControl_ > virtual void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::optimize () pure virtual
Optimizes the current mesh.
Implemented in FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >, and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >.
prepare()
template<typename DomainControl_ > virtual void FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::prepare (const GlobalCoordsBuffer & vec_state) pure virtual
Sets the internal state variable.
Parameters
[in] vec_state Global buffer vector containing (possibly new) mesh vertex coordinates
Member Data Documentation
_dirichlet_boundaries
template<typename DomainControl_ > std::deque<String> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dirichlet_boundaries protected
List of all meshparts with dirichlet boundary conditions.
Definition at line 92 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_dirichlet_boundaries().
_dom_ctrl
template<typename DomainControl_ > DomainControl& FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_dom_ctrl protected
The domain control whose mesh objects can be modified.
Definition at line 90 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_mesh_quality(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::optimize(), and FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::optimize().
_slip_boundaries
template<typename DomainControl_ > std::deque<String> FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::_slip_boundaries protected
List of all meshparts with slipboundary conditions.
Definition at line 94 of file meshopt_control.hpp.
Referenced by FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::get_slip_boundaries().
world_dim
template<typename DomainControl_ > constexpr int FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::world_dim = DomainControl_::MeshType::world_dim static constexpr
The world dimension, i.e. number of coordinates.
Definition at line 73 of file meshopt_control.hpp.
The documentation for this class was generated from the following file:
control/meshopt/meshopt_control.hpp