FEAT: FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > > Class Template Reference
FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > > Class Template Reference
Algebraic DOF Partitioning implementation.
#include <alg_dof_parti.hpp>
Public Types
typedef DT_ DataType
our data type
typedef Global::Gate< LocalVectorType, MirrorType > GateType
the global gate type
typedef Global::Vector< LocalVectorType, MirrorType > GlobalVectorType
the global vector type
typedef IT_ IndexType
our index type
typedef LAFEM::DenseVector< DataType, IndexType > LocalVectorType
the local vector type
typedef LAFEM::VectorMirror< DataType, IndexType > MirrorType
the vector mirror type
Public Member Functions
void assemble_allgather (bool yes_i_really_want_this=false)
Assembles the required data for the AlgDofPartiVector::allgather() and AlgDofPartiMatrix::apply() functions.
void assemble_by_gate (const GateType &gate)
Assembles the AlgDofParti object from a given Global::Gate.
void clear ()
Resets the whole object.
const std::vector< int > & get_all_global_dof_counts () const
Returns the all-global-dof-counts vector.
const std::vector< int > & get_all_global_dof_offsets () const
Returns the all-global-dof-offsets vector.
const Dist::Comm * get_comm () const
const MirrorType & get_donee_mirror (IndexType i) const
Returns a donee neighbor mirror.
int get_donee_rank (IndexType i) const
Returns an donee neighbor rank.
const std::vector< IndexType > get_global_dof_indices () const
Returns the global-dof-indices array.
IndexType get_global_dof_offset () const
IndexType get_num_donee_neighbors () const
IndexType get_num_global_dofs () const
IndexType get_num_local_dofs () const
IndexType get_num_owned_dofs () const
IndexType get_num_owner_neighbors () const
const MirrorType & get_owned_mirror () const
Returns the Mirror of the owned DOFs.
const MirrorType & get_owner_mirror (IndexType i) const
Returns an owner neighbor mirror.
int get_owner_rank (IndexType i) const
Returns an owner neighbor rank.
IndexType map_local_to_global_index (const IndexType local_dof_idx) const
Maps a local DOF index to the corresponding global DOF index.
IndexType map_owned_to_local_index (const IndexType owned_dof_idx) const
Maps an owned DOF index to the corresponding local DOF index.
Protected Attributes
std::vector< int > _all_glob_dof_counts
global DOF counts of all processes,
std::vector< int > _all_glob_dof_offset
global DOF offsets of all processes,
const Dist::Comm * _comm
our communicator
IndexType _glob_dof_count
global dof count over all processes
std::vector< IndexType > _glob_dof_idx
global dof indices, size = number of local DOFs
IndexType _glob_dof_offset
global dof offset of this process
std::vector< std::pair< int, MirrorType > > _neighbors_donee
rank/mirror-pair of DOF-donee processes
std::vector< std::pair< int, MirrorType > > _neighbors_owner
rank/mirror-pair of DOF-owner processes
MirrorType _owned_mirror
mirror for this process's owned DOFs
Static Private Member Functions
static std::vector< IndexType > _donee_vidx (const MirrorType &old_mir, const std::vector< IndexType > &own_dof_idx)
static std::vector< IndexType > _owner_vidx (const MirrorType &old_mir, const std::vector< int > &dof_owners, const int neighbor_rank)
static MirrorType _vidx2mirror (const IndexType size, const std::vector< IndexType > &vidx)
Detailed Description
template<typename DT_, typename IT_>
class FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >
Algebraic DOF Partitioning implementation.
This class implements the functionality to generate and manage a distributed partitioning of the degrees of freedom of a (linear) system in an algebraic sense instead of the usual domain-decomposition approach. With this algebraic dof partitioning approach, each process in a given communicator becomes the unqiue owner of a set of consecutively enumerated global dofs, whereas in the domain-decomposition approach a single global dof may be shared by several processes, thus having no unique owner. The primary purpose of this class and the AlgDofPartiVector and AlgDofPartiMatrix classes is to offer the capability of embedding various third-party linear solver libraries as solvers, preconditioners or smoothers within the solver framework used in FEAT.
To use this class, one needs to have a fully assembled Global::Gate object, which contains all the partitioning information in the usual domain-decomposition sense, which is used as a "starting point" for an algebraic DOF partitioning in the assemble_by_gate() function.
Throughout this class and the AlgDofPartiVector and AlgDofPartiMatrix classes, you will often find the terms "local DOF", "shared DOF" and "owned DOF" and "donee DOF". The definitions are as followed:
"local" DOFs always means the DOFs as they are used in the domain decomposition world.
"shared" DOFs are all local DOFs are "shared" by at least two processes in the domain decomposition world. In other words: Each local DOF, which is part of at least one neighbor mirror in the Global::Gate, is a shared DOF.
"owned" DOFs are all local DOFs, which:
are not shared with any other process
are only shared with processes of higher rank
"donee" DOFs are all shared DOFs, which are not owned DOFs
Furthermore, the neighbor ranks and mirrors, which are used in the Global::Gate of the domain-decomposition based approach, are converted into "owner" and "donee" neighbor ranks and mirrors in this algebraic approach. The basic idea is the following: Assume that three processes A, B and C share a common set of DOFs, i.e. they are neighbors in the domain-decomposition sense, and assume that process A has a lower rank than process B and process C. Due to the "ownership" rule (lowest rank is owner), process A becomes the "owner" of the shared DOFs and thus is responsible for enumerating and managing all DOFs shared by A, B and C, which in turn makes processes B and C "donees". Now, because process A owns at least one DOF that is also a local DOF of process B and a local DOF of process C in the domain decomposition sense, we have that:
process A is an "owner neighbor" of process B
process A is an "owner neighbor" of process C
process B is a "donee neighbor" of process A
process C is a "donee neighbor" of process A
Todo:
decide what happens if this process has no dofs at all
make sure that this works for discontinuous elements, too
Author
Peter Zajac
Definition at line 84 of file alg_dof_parti.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ > typedef DT_ FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::DataType
our data type
Definition at line 88 of file alg_dof_parti.hpp.
GateType
template<typename DT_ , typename IT_ > typedef Global::Gate<LocalVectorType, MirrorType> FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::GateType
the global gate type
Definition at line 99 of file alg_dof_parti.hpp.
GlobalVectorType
template<typename DT_ , typename IT_ > typedef Global::Vector<LocalVectorType, MirrorType> FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::GlobalVectorType
the global vector type
Definition at line 97 of file alg_dof_parti.hpp.
IndexType
template<typename DT_ , typename IT_ > typedef IT_ FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::IndexType
our index type
Definition at line 90 of file alg_dof_parti.hpp.
LocalVectorType
template<typename DT_ , typename IT_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::LocalVectorType
the local vector type
Definition at line 93 of file alg_dof_parti.hpp.
MirrorType
template<typename DT_ , typename IT_ > typedef LAFEM::VectorMirror<DataType, IndexType> FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::MirrorType
the vector mirror type
Definition at line 95 of file alg_dof_parti.hpp.
Constructor & Destructor Documentation
AlgDofParti()
template<typename DT_ , typename IT_ > FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::AlgDofParti () inline
Definition at line 123 of file alg_dof_parti.hpp.
Member Function Documentation
_donee_vidx()
template<typename DT_ , typename IT_ > static std::vector< IndexType > FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_donee_vidx (const MirrorType & old_mir, const std::vector< IndexType > & own_dof_idx) inline static private
Definition at line 615 of file alg_dof_parti.hpp.
_owner_vidx()
template<typename DT_ , typename IT_ > static std::vector< IndexType > FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_owner_vidx (const MirrorType & old_mir, const std::vector< int > & dof_owners, const int neighbor_rank) inline static private
Definition at line 597 of file alg_dof_parti.hpp.
_vidx2mirror()
template<typename DT_ , typename IT_ > static MirrorType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_vidx2mirror (const IndexType size, const std::vector< IndexType > & vidx) inline static private
Definition at line 585 of file alg_dof_parti.hpp.
assemble_allgather()
template<typename DT_ , typename IT_ > void FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::assemble_allgather (bool yes_i_really_want_this = false) inline
Assembles the required data for the AlgDofPartiVector::allgather() and AlgDofPartiMatrix::apply() functions.
Warning
Calling this function and (more importantly) the AlgDofPartiVector::allgather() function or the AlgDofPartiMatrix::apply() functions will totally screw up the scalability of your application, so the code will blow up in your face on bigger clusters.
Do not use this function except for small-scale debugging purposes. You have been warned.
Parameters
[in] yes_i_really_want_this An assertion will fire if this is false. The only purpose of this parameter is to force you to read the warning in this documentation first.
Definition at line 338 of file alg_dof_parti.hpp.
References FEAT::Dist::Comm::allgather(), FEAT::Dist::Comm::size(), and XASSERTM.
assemble_by_gate()
template<typename DT_ , typename IT_ > void FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::assemble_by_gate (const GateType & gate) inline
Assembles the AlgDofParti object from a given Global::Gate.
This function performs the assembly of all required internal data structures.
Todo:
what do we do if owned_dofs==0 ?
Definition at line 361 of file alg_dof_parti.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, FEAT::Dist::Comm::allreduce(), FEAT::Dist::Comm::exscan(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::Dist::op_sum, FEAT::Dist::Comm::rank(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERTM.
clear()
template<typename DT_ , typename IT_ > void FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear () inline
Resets the whole object.
Definition at line 131 of file alg_dof_parti.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clear().
get_all_global_dof_counts()
template<typename DT_ , typename IT_ > const std::vector< int > & FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_all_global_dof_counts () const inline
Returns the all-global-dof-counts vector.
Attention
This vector is only allocated after assemble_allgather() has been called.
Don't use this unless you really know what you are doing!
Returns
The all-global-dof-counts vector.
Definition at line 318 of file alg_dof_parti.hpp.
References XASSERTM.
get_all_global_dof_offsets()
template<typename DT_ , typename IT_ > const std::vector< int > & FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_all_global_dof_offsets () const inline
Returns the all-global-dof-offsets vector.
Attention
This vector is only allocated after assemble_allgather() has been called.
Don't use this unless you really know what you are doing!
Returns
The all-global-dof-offsets vector.
Definition at line 303 of file alg_dof_parti.hpp.
References XASSERTM.
get_comm()
template<typename DT_ , typename IT_ > const Dist::Comm * FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_comm () const inline
Returns
The communicator
Definition at line 145 of file alg_dof_parti.hpp.
get_donee_mirror()
template<typename DT_ , typename IT_ > const MirrorType & FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_donee_mirror (IndexType i) const inline
Returns a donee neighbor mirror.
Note
The indices of a donee neighbor mirror are local DOF indices.
Parameters
[in] i The index of the donee neighbor.
Returns
The mirror of the i-th donee neighbor.
Definition at line 289 of file alg_dof_parti.hpp.
get_donee_rank()
template<typename DT_ , typename IT_ > int FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_donee_rank (IndexType i) const inline
Returns an donee neighbor rank.
Parameters
[in] i The index of the donee neighbor.
Returns
The rank of the i-th donee neighbor.
Definition at line 255 of file alg_dof_parti.hpp.
get_global_dof_indices()
template<typename DT_ , typename IT_ > const std::vector< IndexType > FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_global_dof_indices () const inline
Returns the global-dof-indices array.
Definition at line 177 of file alg_dof_parti.hpp.
get_global_dof_offset()
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_global_dof_offset () const inline
Returns
The index of the first global DOF owned by this process.
Definition at line 169 of file alg_dof_parti.hpp.
get_num_donee_neighbors()
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_donee_neighbors () const inline
Returns
The number of donee neighbors.
Definition at line 227 of file alg_dof_parti.hpp.
get_num_global_dofs()
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_global_dofs () const inline
Returns
The total number of global DOFs.
Definition at line 163 of file alg_dof_parti.hpp.
get_num_local_dofs()
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_local_dofs () const inline
Returns
The number of local DOFs shared by this process.
Definition at line 157 of file alg_dof_parti.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
get_num_owned_dofs()
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_owned_dofs () const inline
Returns
The number of global DOFs owned by this process.
Definition at line 151 of file alg_dof_parti.hpp.
References FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices().
get_num_owner_neighbors()
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_owner_neighbors () const inline
Returns
The number of owner neighbors.
Definition at line 221 of file alg_dof_parti.hpp.
get_owned_mirror()
template<typename DT_ , typename IT_ > const MirrorType & FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_owned_mirror () const inline
Returns the Mirror of the owned DOFs.
Definition at line 215 of file alg_dof_parti.hpp.
get_owner_mirror()
template<typename DT_ , typename IT_ > const MirrorType & FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_owner_mirror (IndexType i) const inline
Returns an owner neighbor mirror.
Note
The indices of an owner neighbor mirror are owned DOF indices.
Parameters
[in] i The index of the owner neighbor.
Returns
The mirror of the i-th owner neighbor.
Definition at line 272 of file alg_dof_parti.hpp.
get_owner_rank()
template<typename DT_ , typename IT_ > int FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_owner_rank (IndexType i) const inline
Returns an owner neighbor rank.
Parameters
[in] i The index of the owner neighbor.
Returns
The rank of the i-th owner neighbor.
Definition at line 241 of file alg_dof_parti.hpp.
map_local_to_global_index()
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::map_local_to_global_index (const IndexType local_dof_idx) const inline
Maps a local DOF index to the corresponding global DOF index.
Parameters
[in] local_dof_idx The local index of the DOF whose global index is to be returned.
Returns
The global index of the local DOF.
Definition at line 191 of file alg_dof_parti.hpp.
References ASSERT, and FEAT::LAFEM::Container< DT_, IT_ >::size().
map_owned_to_local_index()
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::map_owned_to_local_index (const IndexType owned_dof_idx) const inline
Maps an owned DOF index to the corresponding local DOF index.
Parameters
[in] owned_dof_idx The owned index of the DOF whose local index is to be returned.
Returns
The local index of the owned DOF.
Definition at line 206 of file alg_dof_parti.hpp.
References ASSERT, FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices().
Member Data Documentation
_all_glob_dof_counts
template<typename DT_ , typename IT_ > std::vector<int> FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_all_glob_dof_counts protected
global DOF counts of all processes,
See also
#allgather()
Definition at line 120 of file alg_dof_parti.hpp.
_all_glob_dof_offset
template<typename DT_ , typename IT_ > std::vector<int> FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_all_glob_dof_offset protected
global DOF offsets of all processes,
See also
#allgather()
Definition at line 118 of file alg_dof_parti.hpp.
_comm
template<typename DT_ , typename IT_ > const Dist::Comm* FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_comm protected
our communicator
Definition at line 103 of file alg_dof_parti.hpp.
_glob_dof_count
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_glob_dof_count protected
global dof count over all processes
Definition at line 107 of file alg_dof_parti.hpp.
_glob_dof_idx
template<typename DT_ , typename IT_ > std::vector<IndexType> FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_glob_dof_idx protected
global dof indices, size = number of local DOFs
Definition at line 109 of file alg_dof_parti.hpp.
_glob_dof_offset
template<typename DT_ , typename IT_ > IndexType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_glob_dof_offset protected
global dof offset of this process
Definition at line 105 of file alg_dof_parti.hpp.
_neighbors_donee
template<typename DT_ , typename IT_ > std::vector<std::pair<int, MirrorType> > FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_neighbors_donee protected
rank/mirror-pair of DOF-donee processes
Definition at line 115 of file alg_dof_parti.hpp.
_neighbors_owner
template<typename DT_ , typename IT_ > std::vector<std::pair<int, MirrorType> > FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_neighbors_owner protected
rank/mirror-pair of DOF-owner processes
Definition at line 113 of file alg_dof_parti.hpp.
_owned_mirror
template<typename DT_ , typename IT_ > MirrorType FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::_owned_mirror protected
mirror for this process's owned DOFs
Definition at line 111 of file alg_dof_parti.hpp.
The documentation for this class was generated from the following file:
kernel/global/alg_dof_parti.hpp