FEAT: FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ > Class Template Reference
FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ > Class Template Reference
Baseclass for a family of variational mesh optimization algorithms.
#include <hyperelasticity_functional.hpp>
Public Types
typedef MeshQualityFunctional< MeshType > BaseClass
Our base class.
typedef CellFunctionalType_ CellFunctionalType
Type for the cell functional.
typedef BaseClass::CoordsBufferType CoordsBufferType
Type for exchanging information between state variable and mesh.
typedef MeshType::CoordType CoordType
The precision of the mesh coordinates.
typedef CoordType DataType
We always use the precision of the mesh.
typedef LAFEM::FilterSequence< DirichletFilterType > DirichletFilterSequence
Sequence of Dirichlet filters for several different boundary parts.
typedef LAFEM::UnitFilterBlocked< DT_, IT_, MeshType::world_dim > DirichletFilterType
Filter for Dirichlet boundary conditions.
typedef LAFEM::FilterChain< SlipFilterSequence, DirichletFilterSequence > FilterType
Combined filter.
typedef VectorTypeR GradientType
Type of the gradient vector.
typedef Index IndexType
We always use Index for now.
typedef TrafoType::MeshType MeshType
The mesh the transformation is defined on.
typedef RefCellTrafo_ RefCellTrafo
Type of the reference cell trafo for the mesh quality.
typedef LAFEM::DenseVector< CoordType, IndexType > ScalarVectorType
Vector type for element sizes etc.
typedef MeshType::ShapeType ShapeType
ShapeType of said mesh.
typedef LAFEM::FilterSequence< SlipFilterType > SlipFilterSequence
Sequence of Slip filters for several different boundary parts.
typedef LAFEM::SlipFilter< DT_, IT_, MeshType::world_dim > SlipFilterType
Filter for slip boundary conditions.
typedef Intern::TrafoFE< TrafoType >::Space SpaceType
Finite Element space for the transformation.
typedef Trafo_ TrafoType
Type for the transformation.
typedef LAFEM::DenseVectorBlocked< CoordType, IndexType, MeshType::world_dim > VectorType
Vector type for coordinate vectors etc.
typedef LAFEM::DenseVectorBlocked< DT_, IT_, MeshType::world_dim > VectorTypeL
Output vector type of the operator.
typedef LAFEM::DenseVectorBlocked< DT_, IT_, MeshType::world_dim > VectorTypeR
Input vector type of the operator.
Public Member Functions
HyperelasticityFunctional ()=delete
Explicitly delete default constructor.
HyperelasticityFunctional (const HyperelasticityFunctional &)=delete
Explicitly delete copy constructor.
HyperelasticityFunctional (Geometry::RootMeshNode< MeshType > *rmn_, TrafoType &trafo, const std::deque< String > &dirichlet_list, const std::deque< String > &slip_list, std::shared_ptr< CellFunctionalType_ > cell_functional_)
Constructor.
HyperelasticityFunctional (Geometry::RootMeshNode< MeshType > *rmn_, TrafoType &trafo, const std::deque< String > &dirichlet_list, const std::deque< String > &slip_list, std::shared_ptr< CellFunctionalType_ > cell_functional_, ScaleComputation scale_computation_, std::shared_ptr< MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ > > mesh_conc_=nullptr, DataType penalty_param_=DataType(0))
Constructor.
virtual ~HyperelasticityFunctional ()
Destructor.
virtual void add_to_vtk_exporter (Geometry::ExportVTK< typename Trafo_::MeshType > &exporter) const override
Adds relevant quantities of this object to a VTK exporter.
virtual void buffer_to_mesh ()
Sets the coordinates in the underlying mesh to _coords_buffer.
Index columns () const
Returns the number of columns.
virtual CoordType compute_cell_size_defect (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, CoordType &vol) const override
Computes a quality indicator concerning the cell sizes.
virtual CoordType compute_cell_size_defect_post_sync (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, const CoordType &vol) const
Computes a quality indicator concerning the cell sizes, pre synchronization phase.
void compute_cell_size_defect_pre_sync (CoordType &vol_min, CoordType &vol_max, CoordType &vol) const
Computes a quality indicator concerning the cell sizes, pre synchronization phase.
VectorTypeL create_vector_l () const
Creates an L-vector for the functional's gradient.
VectorTypeR create_vector_r () const
Creates an R-vector for the functional and its gradient.
bool empty () const
Checks if the functional is empty (= the null functional)
virtual void eval_fval_cellwise (CoordType &fval, CoordType *fval_norm, CoordType *fval_cof, CoordType *fval_det) const
Computes the functional value parts on every cell.
virtual void eval_fval_grad (CoordType &fval, VectorTypeL &grad, const bool &add_penalty_fval=true)
Evaluates the functional's value and gradient at the current state.
DataType get_constraint ()
Gets the last computed (alignment) constraint.
CoordsBufferType & get_coords ()
Gets the coords buffer.
const CoordsBufferType & get_coords () const
Gets the coords buffer.
MeshType * get_mesh ()
const MeshType * get_mesh () const
Geometry::RootMeshNode< MeshType > * get_mesh_node () const
Index get_num_func_evals () const
Index get_num_grad_evals () const
Index get_num_hess_evals () const
DataType get_penalty_param () const
Gets the penalty parameter.
virtual String info () const
Prints some characteristics of the HyperelasticityFunctional object.
virtual void init () override
Performs intializations that cannot be done in the constructor.
virtual void init_post_sync ()
Performs initializations that cannot be done in the constructor, post synchronization phase.
virtual void init_pre_sync ()
Performs initializations that cannot be done in the constructor, pre synchronization phase.
virtual void mesh_to_buffer ()
Gets the coordinates from the underlying mesh and saves them in _coords_buffer.
virtual void prepare (const VectorTypeR &vec_state, FilterType &filter)
Prepares the functional for evaluation.
virtual void prepare_post_sync (const VectorTypeR &vec_state, FilterType &filter)
Prepares the functional for evaluation, post synchronization phase.
virtual void prepare_pre_sync (const VectorTypeR &vec_state, FilterType &filter)
Prepares the functional for evaluation, pre synchronization phase.
void reset_num_evals ()
Resets all evaluation counts.
Index rows () const
Returns the number of rows.
void set_penalty_param (const DataType penalty_param_)
Sets the penalty parameter.
Static Public Member Functions
static String name ()
The class name.
Public Attributes
CoordsBufferType _coords_buffer
Coordinates, used for setting new boundary values etc.
Geometry::RootMeshNode< MeshType > * _mesh_node
The mesh for the underlying transformation.
std::map< String, DataType * > sync_scalars
These are the scalars that need to be synchronized in init() or prepare()
std::set< VectorTypeR * > sync_vecs
These are the vectors that need to be synchronized (type-0 to type-1)
SpaceType trafo_space
The FE space for the transformation, needed for filtering.
Static Public Attributes
static constexpr int BlockHeight = MeshType::world_dim
Block height of the operator's gradient.
static constexpr int BlockWidth = MeshType::world_dim
Block Weight of the operator's gradient.
Protected Member Functions
virtual void _compute_lambda_cellsize ()
Computes the weights _lambda according to the current mesh.
virtual void _compute_lambda_conc ()
Computes _lambda according to the concentration function given by _mesh_conc.
virtual void _compute_lambda_uniform ()
Computes the uniformly distributed weights _lambda.
virtual void _compute_scales_init ()
Recomputes the optimal scales, every call to the solver.
virtual void _compute_scales_iter ()
Recomputes the optimal scales, every iteration.
virtual void _compute_scales_once ()
Computes the scales, just once.
Protected Attributes
std::shared_ptr< CellFunctionalType > _cell_functional
Since the cell functional contains a ShapeType, these have to be the same.
std::map< String, std::shared_ptr< Assembly::UnitFilterAssembler< MeshType > > > _dirichlet_asm
Assembler for Dirichlet boundary conditions.
ScalarVectorType _h
Size parameters for the local reference element.
ScalarVectorType _lambda
Weights for local mesh size.
std::shared_ptr< MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ > > _mesh_conc
The mesh concentration function (if any)
ScalarVectorType _mu
Weights for the local contributions to the global functional value.
Index _num_func_evals
Counter for number of function evaluations.
Index _num_grad_evals
Counter for number of gradient evaluations.
Index _num_hess_evals
Counter for number of hessian evaluations.
std::map< String, std::shared_ptr< Assembly::SlipFilterAssembler< TrafoType > > > _slip_asm
Assembler for slip boundary conditions.
TrafoType & _trafo
The transformation defining the physical mesh.
Private Attributes
DataType _alignment_constraint
Last computed contraint (violation)
const Index _columns
This is the number of DoFs in the trial space (= number of mesh vertices)
DataType _penalty_param
Factor for the alignment penalty term.
const Index _rows
This is the number of DoFs in the test space (= number of mesh vertices)
ScaleComputation _scale_computation
How to compute the optimal scales.
DataType _sum_det
DataType _sum_lambda
The sum of all lambda (= optimal cell size) over all cells before normalization.
DataType _sum_mu
The sum of all mu (= cell weights) over all cells before normalization.
Detailed Description
template<typename DT_, typename IT_, typename Trafo_, typename CellFunctionalType_, typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>>
class FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >
Baseclass for a family of variational mesh optimization algorithms.
Template Parameters
DT_ Floating point type for solving.
IT_ Index type for solver vectors etc.
Trafo_ Type of the underlying transformation.
CellFunctionalType_ (Cell-)local functional used for defining mesh quality.
See also
RumpfFunctional
Template Parameters
RefCellTrafo_ Basically choses the reference cell according to which to optimize the mesh quality for.
Mesh optimization algorithms derived from Martin Rumpf's paper [Rum96].
Note
The evaluation of the nonlinear functional requires operations that are essentially similar to an assembly of an operator into a matrix.
Assume we have a regular, conforming mesh \(\mathcal{T} \) and each cell \(K \in \mathcal{T} \) can be expressed as the image of an (optimal) reference cell \(\hat{K} \) such that
\[ \forall K \in \mathcal{T}: \exists R_K : \hat{K} \to K: \forall \hat{x} \in \hat{K}: \det \nabla R_K(\hat{x}) \neq 0, \]
which ensures that the mapping is nonsingular and that the orientation of the reference cell is preserved. We are now looking for a deformation \(\Phi: \mathcal{T} \to \Phi(\mathcal{T})\) such that \(\Phi(\mathcal{T} \) is optimal in the sense that it minimizes a functional of the form
\[ \mathcal{F}(\Phi) = \int_\Omega \mathcal{L}(\Phi,x) dx = \sum_{K \in \mathcal{T}} \mu_K \int_K \mathcal{L}_K(\Phi,x) dx. \]
Under the assumptions of frame indifference and translation invariance it can be shown that
\[ \forall K \in \mathcal{T}: \exists L_K \in SO_d \times K: \mathcal{L}_K: \mathcal{L}(\Phi,\cdot) = L_K(\nabla \Phi, \cdot) = L_K(\nabla R_K, \cdot) \]
and that the local cell functional is of the form
\[ F(\nabla R_K(\Phi)) := \int_K L(\nabla R_K (\Phi)(x)) dx = \mu_K L(\| \nabla R_T(\Phi) \|_F^2, \| \mathrm{cof} \nabla R_T(\Phi) \|_F^2, \det \nabla R_T(\Phi)) \]
In the code, \(F \) is called the RumpfFunctional.
Author
Jordi Paul
Definition at line 175 of file hyperelasticity_functional.hpp.
Member Typedef Documentation
BaseClass
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef MeshQualityFunctional<MeshType> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::BaseClass
Our base class.
Definition at line 197 of file hyperelasticity_functional.hpp.
CellFunctionalType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef CellFunctionalType_ FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::CellFunctionalType
Type for the cell functional.
Definition at line 186 of file hyperelasticity_functional.hpp.
CoordsBufferType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef BaseClass::CoordsBufferType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::CoordsBufferType
Type for exchanging information between state variable and mesh.
Definition at line 232 of file hyperelasticity_functional.hpp.
CoordType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef MeshType::CoordType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::CoordType
The precision of the mesh coordinates.
Definition at line 184 of file hyperelasticity_functional.hpp.
DataType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef CoordType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::DataType
We always use the precision of the mesh.
Definition at line 192 of file hyperelasticity_functional.hpp.
DirichletFilterSequence
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::FilterSequence<DirichletFilterType> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::DirichletFilterSequence
Sequence of Dirichlet filters for several different boundary parts.
Definition at line 214 of file hyperelasticity_functional.hpp.
DirichletFilterType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::UnitFilterBlocked<DT_, IT_, MeshType::world_dim> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::DirichletFilterType
Filter for Dirichlet boundary conditions.
Definition at line 212 of file hyperelasticity_functional.hpp.
FilterType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::FilterChain<SlipFilterSequence, DirichletFilterSequence> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::FilterType
Combined filter.
Definition at line 220 of file hyperelasticity_functional.hpp.
GradientType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef VectorTypeR FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::GradientType
Type of the gradient vector.
Definition at line 230 of file hyperelasticity_functional.hpp.
IndexType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef Index FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::IndexType
We always use Index for now.
Definition at line 194 of file hyperelasticity_functional.hpp.
MeshType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef TrafoType::MeshType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::MeshType
The mesh the transformation is defined on.
Definition at line 182 of file hyperelasticity_functional.hpp.
RefCellTrafo
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef RefCellTrafo_ FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::RefCellTrafo
Type of the reference cell trafo for the mesh quality.
Definition at line 189 of file hyperelasticity_functional.hpp.
ScalarVectorType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::DenseVector<CoordType, IndexType> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::ScalarVectorType
Vector type for element sizes etc.
Definition at line 208 of file hyperelasticity_functional.hpp.
ShapeType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef MeshType::ShapeType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::ShapeType
ShapeType of said mesh.
Definition at line 205 of file hyperelasticity_functional.hpp.
SlipFilterSequence
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::FilterSequence<SlipFilterType> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::SlipFilterSequence
Sequence of Slip filters for several different boundary parts.
Definition at line 218 of file hyperelasticity_functional.hpp.
SlipFilterType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::SlipFilter<DT_, IT_, MeshType::world_dim> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::SlipFilterType
Filter for slip boundary conditions.
Definition at line 216 of file hyperelasticity_functional.hpp.
SpaceType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef Intern::TrafoFE<TrafoType>::Space FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::SpaceType
Finite Element space for the transformation.
Definition at line 223 of file hyperelasticity_functional.hpp.
TrafoType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef Trafo_ FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::TrafoType
Type for the transformation.
Definition at line 180 of file hyperelasticity_functional.hpp.
VectorType
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::DenseVectorBlocked<CoordType, IndexType, MeshType::world_dim> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::VectorType
Vector type for coordinate vectors etc.
Definition at line 210 of file hyperelasticity_functional.hpp.
VectorTypeL
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::DenseVectorBlocked<DT_, IT_, MeshType::world_dim> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::VectorTypeL
Output vector type of the operator.
Definition at line 226 of file hyperelasticity_functional.hpp.
VectorTypeR
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> typedef LAFEM::DenseVectorBlocked<DT_, IT_, MeshType::world_dim> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::VectorTypeR
Input vector type of the operator.
Definition at line 228 of file hyperelasticity_functional.hpp.
Constructor & Destructor Documentation
HyperelasticityFunctional() [1/2]
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional (Geometry::RootMeshNode< MeshType > * rmn_, TrafoType & trafo, const std::deque< String > & dirichlet_list, const std::deque< String > & slip_list, std::shared_ptr< CellFunctionalType_ > cell_functional_) inline explicit
Constructor.
Parameters
[in] rmn_ The RootMeshNode representing the tree of root mesh, all of its MeshParts and Charts.
[in] trafo The transformation on the root mesh node.
[in] dirichlet_list The list of dirichlet boundaries.
[in] slip_list The list of slip boundaries.
[in] cell_functional_ The (cell-)local functional used
This is the simple constructor that always sets the scale computation to once_uniform and the mesh concentration function to nullptr.
Definition at line 309 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_once(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_dirichlet_asm, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mu, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_slip_asm, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_mu, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_trafo, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::find_mesh_part(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::sync_scalars, and XASSERTM.
HyperelasticityFunctional() [2/2]
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional (Geometry::RootMeshNode< MeshType > * rmn_, TrafoType & trafo, const std::deque< String > & dirichlet_list, const std::deque< String > & slip_list, std::shared_ptr< CellFunctionalType_ > cell_functional_, ScaleComputation scale_computation_, std::shared_ptr< MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ > > mesh_conc_ = nullptr, DataType penalty_param_ = DataType(0)) inline explicit
Constructor.
Parameters
[in] rmn_ The RootMeshNode representing the tree of root mesh, all of its MeshParts and Charts.
[in] trafo The transformation on the root mesh node.
[in] dirichlet_list The list of dirichlet boundaries.
[in] slip_list The list of slip boundaries.
[in] cell_functional_ The (cell-)local functional used
[in] scale_computation_ The type of scale computation to use
[in] mesh_conc_ The mesh concentration function to use. If no scale computation that uses this is set, this may be nullptr.
[in] penalty_param_ The penalty parameter, e.g. for surface alignment. Defaults to 0, which turns off this functionality.
Definition at line 419 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_once(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_dirichlet_asm, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mesh_conc, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mu, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_penalty_param, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_slip_asm, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_mu, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_trafo, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::find_mesh_part(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::sync_scalars, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::sync_vecs, and XASSERTM.
~HyperelasticityFunctional()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::~HyperelasticityFunctional () inline virtual
Destructor.
Definition at line 516 of file hyperelasticity_functional.hpp.
Member Function Documentation
_compute_lambda_cellsize()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_cellsize () inline protected virtual
Computes the weights _lambda according to the current mesh.
Definition at line 1178 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_lambda, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_lambda, and FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_init(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_once().
_compute_lambda_conc()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_conc () inline protected virtual
Computes _lambda according to the concentration function given by _mesh_conc.
Definition at line 1203 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_coords_buffer, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_lambda, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mesh_conc, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_lambda, FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), and FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_init(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_iter(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_once().
_compute_lambda_uniform()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform () inline protected virtual
Computes the uniformly distributed weights _lambda.
Definition at line 1194 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_lambda, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_lambda, FEAT::LAFEM::Container< DT_, IT_ >::format(), and FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_init(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_once().
_compute_scales_init()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_init () inline protected virtual
Recomputes the optimal scales, every call to the solver.
Definition at line 1226 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_cellsize(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_conc(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_coords_buffer, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_scale_computation, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_det, and FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_pre_sync().
_compute_scales_iter()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_iter () inline protected virtual
Recomputes the optimal scales, every iteration.
To be called from prepare(). This consists of first computing _lambda and then _h.
Definition at line 1259 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_conc(), FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_coords_buffer, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_scale_computation, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_det, and FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
_compute_scales_once()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_once () inline protected virtual
Computes the scales, just once.
To be called from a constructor. This consists of first computing _lambda and then _h.
Definition at line 1279 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_cellsize(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_conc(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_coords_buffer, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_scale_computation, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_det, and FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional().
add_to_vtk_exporter()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::add_to_vtk_exporter (Geometry::ExportVTK< typename Trafo_::MeshType > & exporter) const inline override virtual
Adds relevant quantities of this object to a VTK exporter.
Parameters
[in,out] exporter The exporter to add our data to.
Note
This does not compute and/or add the functional's gradient to the exporter because this requires filtering and synchronization if there is more than one patch. Compute the gradient at a point where you know these things (e.g. in the application itself, or in Control::Meshopt::HyperelasticityControl).
Reimplemented from FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >.
Definition at line 606 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mesh_conc, FEAT::Geometry::ExportVTK< Mesh_ >::add_cell_scalar(), FEAT::Geometry::ExportVTK< Mesh_ >::add_cell_vector(), FEAT::Geometry::ExportVTK< Mesh_ >::add_vertex_scalar(), FEAT::Geometry::ExportVTK< Mesh_ >::add_vertex_vector(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::eval_fval_cellwise(), and FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh().
buffer_to_mesh()
virtual void FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::buffer_to_mesh () inline virtual inherited
Sets the coordinates in the underlying mesh to _coords_buffer.
Definition at line 157 of file mesh_quality_functional.hpp.
columns()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> Index FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::columns () const inline
Returns the number of columns.
Returns
The number of columns.
Definition at line 551 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_columns.
compute_cell_size_defect()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual CoordType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::compute_cell_size_defect (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, CoordType & vol) const inline override virtual
Computes a quality indicator concerning the cell sizes.
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
In a truly optimal mesh (consisting ONLY of reference cells of the right size), every cell's volume is exactly lambda(cell). This is especially the goal for r-adaptivity. So in an optimal mesh,
\[ \forall K \in \mathcal{T}_h: |K|/|\Omega| = \lambda(K) \]
so we compute the 1-norm of the vector \((v)_i = \left| \frac{|K_i|}{\sum_j |K_j|} - \lambda(K_i) \right| \).
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function has a pre_sync and post_sync part.
See also
Control::HyperelasticityFunctionalControl::compute_cell_size_defect()
Implements FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >.
Definition at line 918 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::compute_cell_size_defect_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::compute_cell_size_defect_pre_sync().
compute_cell_size_defect_post_sync()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual CoordType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::compute_cell_size_defect_post_sync (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, const CoordType & vol) const inline virtual
Computes a quality indicator concerning the cell sizes, pre synchronization phase.
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function has a pre_sync and post_sync part.
See also
Control::HyperelasticityFunctionalControl::compute_cell_size_defect()
Definition at line 991 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_lambda, FEAT::Math::abs(), FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh(), FEAT::Math::max(), and FEAT::Math::min().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::compute_cell_size_defect().
compute_cell_size_defect_pre_sync()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::compute_cell_size_defect_pre_sync (CoordType & vol_min, CoordType & vol_max, CoordType & vol) const inline
Computes a quality indicator concerning the cell sizes, pre synchronization phase.
Parameters
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
As these quantities are global, this function has a pre_sync and post_sync part.
See also
Control::HyperelasticityFunctionalControl::compute_cell_size_defect()
Definition at line 948 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh(), FEAT::Math::max(), and FEAT::Math::min().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::compute_cell_size_defect().
create_vector_l()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> VectorTypeL FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::create_vector_l () const inline
Creates an L-vector for the functional's gradient.
Definition at line 533 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::trafo_space.
create_vector_r()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> VectorTypeR FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::create_vector_r () const inline
Creates an R-vector for the functional and its gradient.
Definition at line 541 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::trafo_space.
empty()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> bool FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::empty () const inline
Checks if the functional is empty (= the null functional)
Returns
True if the number of DoFs is zero.)
Definition at line 525 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::trafo_space.
eval_fval_cellwise()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::eval_fval_cellwise (CoordType & fval, CoordType * fval_norm, CoordType * fval_cof, CoordType * fval_det) const inline virtual
Computes the functional value parts on every cell.
Parameters
[in] fval The functional value summed up over all cells.
[in] fval_norm Array to receive the Frobenius norm part of the functional value on every cell.
[in] fval_cof Array to receive the cofactor matrix part of the functional value on every cell.
[in] fval_det Array to receive the det part of the functional value on every cell.
Definition at line 1128 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_coords_buffer, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_h, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mu, and FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::add_to_vtk_exporter().
eval_fval_grad()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::eval_fval_grad (CoordType & fval, VectorTypeL & grad, const bool & add_penalty_fval = true) inline virtual
Evaluates the functional's value and gradient at the current state.
Parameters
[out] fval The functional value computed
[out] grad The functional's gradient computed
[in] add_penalty_fval Whether to add the penalty term
Note
The awkward handling of the penalty term is because this needs to be handled in THIS class and not in another class that uses it because the the quadratic penalty method (
See also
Solver::QPenalty) needs to call an inner solver that is unaware of the existence (or special treatment) of the penalty term.
Definition at line 1030 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_coords_buffer, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_h, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mu, FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_num_func_evals, FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_num_grad_evals, FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh(), FEAT::grad, FEAT::Math::sqr(), and XASSERTM.
get_constraint()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> DataType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::get_constraint () inline
Gets the last computed (alignment) constraint.
This is useful if you KNOW the constraint was already computed (i.e. by prepare())
Returns
The (alignment) constraint.
Definition at line 675 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_alignment_constraint.
get_coords() [1/2]
CoordsBufferType & FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_coords () inline inherited
Gets the coords buffer.
Returns
A reference to the coords buffer for manipulation.
Definition at line 170 of file mesh_quality_functional.hpp.
get_coords() [2/2]
const CoordsBufferType & FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_coords () const inline inherited
Gets the coords buffer.
Returns
A const reference to the coords buffer for manipulation.
Definition at line 180 of file mesh_quality_functional.hpp.
get_mesh() [1/2]
MeshType * FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh () inline inherited
Returns
The root mesh
Definition at line 128 of file mesh_quality_functional.hpp.
get_mesh() [2/2]
const MeshType * FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh () const inline inherited
Returns
The root mesh as const pointer
Definition at line 135 of file mesh_quality_functional.hpp.
get_mesh_node()
Geometry::RootMeshNode< MeshType > * FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_mesh_node () const inline inherited
Returns
The root mesh node
Definition at line 142 of file mesh_quality_functional.hpp.
get_num_func_evals()
Index FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_num_func_evals () const inline inherited
Returns
The number of times the functional value was computed.
Definition at line 188 of file mesh_quality_functional.hpp.
get_num_grad_evals()
Index FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_num_grad_evals () const inline inherited
Returns
The number of times the gradient was computed.
Definition at line 196 of file mesh_quality_functional.hpp.
get_num_hess_evals()
Index FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::get_num_hess_evals () const inline inherited
Returns
The number of times the hessian was computed.
Definition at line 204 of file mesh_quality_functional.hpp.
get_penalty_param()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> DataType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::get_penalty_param () const inline
Gets the penalty parameter.
Returns
The penalty parameter
Definition at line 647 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_penalty_param.
info()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual String FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::info () const inline virtual
Prints some characteristics of the HyperelasticityFunctional object.
Definition at line 579 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_cell_functional, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mesh_conc, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_scale_computation, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::name(), FEAT::String::pad_back(), and FEAT::stringify().
init()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init () inline override virtual
Performs intializations that cannot be done in the constructor.
Note
This needs some synchronization, so if this object lives on just one of many patches, use init_pre_sync() and init_post_sync() like the Global::NonlinearFunctional class does.
Implements FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >.
Definition at line 700 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_pre_sync().
init_post_sync()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync () inline virtual
Performs initializations that cannot be done in the constructor, post synchronization phase.
See also
init()
Definition at line 737 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_h, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_lambda, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mu, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_det, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_lambda, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_mu, and FEAT::LAFEM::DenseVector< DT_, IT_ >::scale().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init().
init_pre_sync()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_pre_sync () inline virtual
Performs initializations that cannot be done in the constructor, pre synchronization phase.
See also
init()
Definition at line 711 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_init(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mesh_conc, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_penalty_param, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_scale_computation, FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::buffer_to_mesh(), FEAT::stringify(), FEAT::stringify_fp_sci(), and XABORTM.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init().
mesh_to_buffer()
virtual void FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::mesh_to_buffer () inline virtual inherited
Gets the coordinates from the underlying mesh and saves them in _coords_buffer.
Definition at line 148 of file mesh_quality_functional.hpp.
name()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> static String FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::name () inline static
The class name.
Returns
String with the class name
Definition at line 571 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::info().
prepare()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare (const VectorTypeR & vec_state, FilterType & filter) inline virtual
Prepares the functional for evaluation.
Parameters
[in] vec_state The state to evaluate the functional at.
[in] filter The filter. We might need to reassemble it.
Needs to be called whenever any data like the mesh, the levelset function etc. changed.
Definition at line 772 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
prepare_post_sync()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_post_sync (const VectorTypeR & vec_state, FilterType & filter) inline virtual
Prepares the functional for evaluation, post synchronization phase.
Parameters
[in] vec_state The state to evaluate the functional at.
[in] filter The filter. We might need to reassemble it.
See also
prepare()
Definition at line 866 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_h, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_lambda, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mesh_conc, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_det, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_lambda, and FEAT::LAFEM::DenseVector< DT_, IT_ >::scale().
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare().
prepare_pre_sync()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> virtual void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync (const VectorTypeR & vec_state, FilterType & filter) inline virtual
Prepares the functional for evaluation, pre synchronization phase.
Parameters
[in] vec_state The state to evaluate the functional at.
[in] filter The filter. We might need to reassemble it.
See also
prepare()
Definition at line 790 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_alignment_constraint, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_iter(), FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_coords_buffer, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_dirichlet_asm, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mesh_conc, FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_mesh_node, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_penalty_param, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_scale_computation, FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_slip_asm, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::adapt_by_name(), FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::buffer_to_mesh(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::mesh_to_buffer(), FEAT::stringify(), FEAT::stringify_fp_sci(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::trafo_space, and XABORTM.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare().
reset_num_evals()
void FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::reset_num_evals () inline inherited
Resets all evaluation counts.
Definition at line 212 of file mesh_quality_functional.hpp.
rows()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> Index FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::rows () const inline
Returns the number of rows.
Returns
The number of rows.
Definition at line 561 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_rows.
set_penalty_param()
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> void FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::set_penalty_param (const DataType penalty_param_) inline
Sets the penalty parameter.
Parameters
[in] penalty_param_ The new penalty parameter.
Definition at line 659 of file hyperelasticity_functional.hpp.
References FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_penalty_param, FEAT::Math::pow(), and XASSERTM.
Member Data Documentation
_alignment_constraint
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> DataType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_alignment_constraint private
Last computed contraint (violation)
Definition at line 276 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::get_constraint(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
_cell_functional
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> std::shared_ptr<CellFunctionalType> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_cell_functional protected
Since the cell functional contains a ShapeType, these have to be the same.
The cell functional for determining mesh quality
Definition at line 240 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::info().
_columns
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> const Index FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_columns private
This is the number of DoFs in the trial space (= number of mesh vertices)
Definition at line 267 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::columns().
_coords_buffer
CoordsBufferType FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_coords_buffer inherited
Coordinates, used for setting new boundary values etc.
Definition at line 52 of file mesh_quality_functional.hpp.
_dirichlet_asm
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> std::map<String, std::shared_ptr<Assembly::UnitFilterAssembler<MeshType> > > FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_dirichlet_asm protected
Assembler for Dirichlet boundary conditions.
Definition at line 251 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
_h
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> ScalarVectorType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_h protected
Size parameters for the local reference element.
Definition at line 249 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::eval_fval_cellwise(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::eval_fval_grad(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_post_sync().
_lambda
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> ScalarVectorType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_lambda protected
Weights for local mesh size.
Definition at line 247 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_cellsize(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_conc(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::compute_cell_size_defect_post_sync(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_post_sync().
_mesh_conc
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> std::shared_ptr<MeshConcentrationFunctionBase<Trafo_, RefCellTrafo_> > FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mesh_conc protected
The mesh concentration function (if any)
Definition at line 255 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_conc(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::add_to_vtk_exporter(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::info(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_pre_sync(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
_mesh_node
Geometry::RootMeshNode<MeshType>* FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_mesh_node inherited
The mesh for the underlying transformation.
Definition at line 50 of file mesh_quality_functional.hpp.
_mu
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> ScalarVectorType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_mu protected
Weights for the local contributions to the global functional value.
Definition at line 244 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::eval_fval_cellwise(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::eval_fval_grad(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync().
_num_func_evals
Index FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_num_func_evals protected inherited
Counter for number of function evaluations.
Definition at line 56 of file mesh_quality_functional.hpp.
_num_grad_evals
Index FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_num_grad_evals protected inherited
Counter for number of gradient evaluations.
Definition at line 58 of file mesh_quality_functional.hpp.
_num_hess_evals
Index FEAT::Meshopt::MeshQualityFunctional< Trafo_::MeshType >::_num_hess_evals protected inherited
Counter for number of hessian evaluations.
Definition at line 60 of file mesh_quality_functional.hpp.
_penalty_param
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> DataType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_penalty_param private
Factor for the alignment penalty term.
Definition at line 274 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::get_penalty_param(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_pre_sync(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::set_penalty_param().
_rows
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> const Index FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_rows private
This is the number of DoFs in the test space (= number of mesh vertices)
Definition at line 269 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::rows().
_scale_computation
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> ScaleComputation FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_scale_computation private
How to compute the optimal scales.
Definition at line 271 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_init(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_iter(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_once(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::info(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_pre_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
_slip_asm
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> std::map<String, std::shared_ptr<Assembly::SlipFilterAssembler<TrafoType> > > FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_slip_asm protected
Assembler for slip boundary conditions.
Definition at line 253 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
_sum_det
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> DataType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_det private
This is the sum of the determinant of the transformation of the reference cell to the mesh cell over all cells
Definition at line 280 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_init(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_iter(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_scales_once(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_post_sync().
_sum_lambda
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> DataType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_lambda private
The sum of all lambda (= optimal cell size) over all cells before normalization.
Definition at line 282 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_cellsize(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_conc(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_post_sync().
_sum_mu
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> DataType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_sum_mu private
The sum of all mu (= cell weights) over all cells before normalization.
Definition at line 284 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync().
_trafo
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> TrafoType& FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_trafo protected
The transformation defining the physical mesh.
Definition at line 242 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional().
BlockHeight
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> constexpr int FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::BlockHeight = MeshType::world_dim static constexpr
Block height of the operator's gradient.
Definition at line 200 of file hyperelasticity_functional.hpp.
BlockWidth
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> constexpr int FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::BlockWidth = MeshType::world_dim static constexpr
Block Weight of the operator's gradient.
Definition at line 202 of file hyperelasticity_functional.hpp.
sync_scalars
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> std::map<String, DataType*> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::sync_scalars
These are the scalars that need to be synchronized in init() or prepare()
Definition at line 261 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional().
sync_vecs
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> std::set<VectorTypeR*> FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::sync_vecs
These are the vectors that need to be synchronized (type-0 to type-1)
Definition at line 263 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional().
trafo_space
template<typename DT_ , typename IT_ , typename Trafo_ , typename CellFunctionalType_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::MeshType::CoordType>> SpaceType FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::trafo_space
The FE space for the transformation, needed for filtering.
Definition at line 259 of file hyperelasticity_functional.hpp.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::create_vector_l(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::create_vector_r(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::empty(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync().
The documentation for this class was generated from the following file:
kernel/meshopt/hyperelasticity_functional.hpp