FEAT: FEAT::Meshopt::MeshQualityFunctional< MeshType_ > Class Template Reference
FEAT::Meshopt::MeshQualityFunctional< MeshType_ > Class Template Reference abstract
Baseclass for mesh optimization algorithms.
#include <mesh_quality_functional.hpp>
Public Types
typedef LAFEM::DenseVectorBlocked< CoordType, Index, MeshType::world_dim > CoordsBufferType
Type for the vectors to hold coordinates etc.
typedef MeshType::CoordType CoordType
Our datatype.
typedef MeshType_ MeshType
Type of the mesh to optimize.
typedef MeshType::ShapeType ShapeType
The shape type.
Public Member Functions
MeshQualityFunctional ()
Empty standard constructor.
MeshQualityFunctional (Geometry::RootMeshNode< MeshType > *mesh_node_)
Constructor.
virtual ~MeshQualityFunctional ()
Virtual destructor.
virtual void add_to_vtk_exporter (Geometry::ExportVTK< MeshType > &exporter) const
Adds relevant quantities of this object to a VTK exporter.
virtual void buffer_to_mesh ()
Sets the coordinates in the underlying mesh to _coords_buffer.
virtual CoordType compute_cell_size_defect (CoordType &lambda_min, CoordType &lambda_max, CoordType &vol_min, CoordType &vol_max, CoordType &vol) const =0
Computes a quality indicator concerning the cell sizes.
CoordsBufferType & get_coords ()
Gets the coords buffer.
const CoordsBufferType & get_coords () const
Gets the coords buffer.
MeshType * get_mesh ()
const MeshType * get_mesh () const
Geometry::RootMeshNode< MeshType > * get_mesh_node () const
Index get_num_func_evals () const
Index get_num_grad_evals () const
Index get_num_hess_evals () const
virtual void init ()=0
Performs one-time initializations.
virtual void mesh_to_buffer ()
Gets the coordinates from the underlying mesh and saves them in _coords_buffer.
void reset_num_evals ()
Resets all evaluation counts.
Static Public Member Functions
static String name ()
The class name.
Public Attributes
CoordsBufferType _coords_buffer
Coordinates, used for setting new boundary values etc.
Geometry::RootMeshNode< MeshType > * _mesh_node
The mesh for the underlying transformation.
Protected Attributes
Index _num_func_evals
Counter for number of function evaluations.
Index _num_grad_evals
Counter for number of gradient evaluations.
Index _num_hess_evals
Counter for number of hessian evaluations.
Detailed Description
template<typename MeshType_>
class FEAT::Meshopt::MeshQualityFunctional< MeshType_ >
Baseclass for mesh optimization algorithms.
This abstract class is the baseclass for all mesh optimization algorithms, which can be direct, variational or something entirely different.
Template Parameters
TrafoType_ Type of the underlying transformation.
Author
Jordi Paul
Definition at line 34 of file mesh_quality_functional.hpp.
Member Typedef Documentation
CoordsBufferType
template<typename MeshType_ > typedef LAFEM::DenseVectorBlocked<CoordType, Index, MeshType::world_dim> FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::CoordsBufferType
Type for the vectors to hold coordinates etc.
Definition at line 44 of file mesh_quality_functional.hpp.
CoordType
template<typename MeshType_ > typedef MeshType::CoordType FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::CoordType
Our datatype.
Definition at line 40 of file mesh_quality_functional.hpp.
MeshType
template<typename MeshType_ > typedef MeshType_ FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::MeshType
Type of the mesh to optimize.
Definition at line 38 of file mesh_quality_functional.hpp.
ShapeType
template<typename MeshType_ > typedef MeshType::ShapeType FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::ShapeType
The shape type.
Definition at line 42 of file mesh_quality_functional.hpp.
Constructor & Destructor Documentation
MeshQualityFunctional() [1/2]
template<typename MeshType_ > FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::MeshQualityFunctional (Geometry::RootMeshNode< MeshType > * mesh_node_) inline explicit
Constructor.
Parameters
[in] mesh_node_ The RootMeshNode this mesh optimizer will refer to.
Definition at line 68 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::mesh_to_buffer(), and XASSERTM.
MeshQualityFunctional() [2/2]
template<typename MeshType_ > FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::MeshQualityFunctional () inline explicit
Empty standard constructor.
This is needed because derived classes like DuDvFunctional are used in Global::Matrix, which needs an empty standard constructor.
Definition at line 87 of file mesh_quality_functional.hpp.
~MeshQualityFunctional()
template<typename MeshType_ > virtual FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional () inline virtual
Virtual destructor.
Definition at line 97 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_coords_buffer, FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_mesh_node, and FEAT::LAFEM::Container< DT_, IT_ >::clear().
Member Function Documentation
add_to_vtk_exporter()
template<typename MeshType_ > virtual void FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::add_to_vtk_exporter (Geometry::ExportVTK< MeshType > & exporter) const inline virtual
Adds relevant quantities of this object to a VTK exporter.
Parameters
[in,out] exporter The exporter to add our data to.
Reimplemented in FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >.
Definition at line 121 of file mesh_quality_functional.hpp.
buffer_to_mesh()
template<typename MeshType_ > virtual void FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::buffer_to_mesh () inline virtual
Sets the coordinates in the underlying mesh to _coords_buffer.
Definition at line 155 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_coords_buffer, and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_mesh().
compute_cell_size_defect()
template<typename MeshType_ > virtual CoordType FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::compute_cell_size_defect (CoordType & lambda_min, CoordType & lambda_max, CoordType & vol_min, CoordType & vol_max, CoordType & vol) const pure virtual
Computes a quality indicator concerning the cell sizes.
Parameters
[out] lambda_min Minimum of the optimal cell size lambda over all cells
[out] lambda_max Maximum of the optimal cell size lambda over all cells
[out] vol_min Minimum cell volume
[out] vol_max Maximum cell volume
[out] vol Total volume of the domain given by the mesh
In a truly optimal mesh (consisting ONLY of reference cells of the right size), every cell's volume is exactly lambda(cell). This is especially the goal for r-adaptivity. So in an optimal mesh,
\[ \forall K \in \mathcal{T}_h: |K|/|\Omega| = \lambda(K) \]
so we compute the 1-norm of the vector \((v)_i = \left| \frac{|K_i|}{\sum_j |K_j|} - \lambda(K_i) \right| \).
Returns
The relative cell size quality indicator.
Note
lambda_min, lambda_max, vol_min, and vol_max are all volume fractions.
Implemented in FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >, and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >.
get_coords() [1/2]
template<typename MeshType_ > CoordsBufferType & FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_coords () inline
Gets the coords buffer.
Returns
A reference to the coords buffer for manipulation.
Definition at line 168 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_coords_buffer.
get_coords() [2/2]
template<typename MeshType_ > const CoordsBufferType & FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_coords () const inline
Gets the coords buffer.
Returns
A const reference to the coords buffer for manipulation.
Definition at line 178 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_coords_buffer.
get_mesh() [1/2]
template<typename MeshType_ > MeshType * FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_mesh () inline
Returns
The root mesh
Definition at line 126 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_mesh_node, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), and XASSERT.
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::buffer_to_mesh(), and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::mesh_to_buffer().
get_mesh() [2/2]
template<typename MeshType_ > const MeshType * FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_mesh () const inline
Returns
The root mesh as const pointer
Definition at line 133 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_mesh_node, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), and XASSERT.
get_mesh_node()
template<typename MeshType_ > Geometry::RootMeshNode< MeshType > * FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_mesh_node () const inline
Returns
The root mesh node
Definition at line 140 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_mesh_node.
get_num_func_evals()
template<typename MeshType_ > Index FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_num_func_evals () const inline
Returns
The number of times the functional value was computed.
Definition at line 186 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_func_evals.
get_num_grad_evals()
template<typename MeshType_ > Index FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_num_grad_evals () const inline
Returns
The number of times the gradient was computed.
Definition at line 194 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_grad_evals.
get_num_hess_evals()
template<typename MeshType_ > Index FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_num_hess_evals () const inline
Returns
The number of times the hessian was computed.
Definition at line 202 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_hess_evals.
init()
template<typename MeshType_ > virtual void FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::init () pure virtual
Performs one-time initializations.
Because of the whole class inheritance hierarchy, some one time initializations cannot be performed in the constructors.
Implemented in FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >, and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >.
mesh_to_buffer()
template<typename MeshType_ > virtual void FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::mesh_to_buffer () inline virtual
Gets the coordinates from the underlying mesh and saves them in _coords_buffer.
Definition at line 146 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_coords_buffer, and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_mesh().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::MeshQualityFunctional().
name()
template<typename MeshType_ > static String FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::name () inline static
The class name.
Returns
String with the class name
Definition at line 109 of file mesh_quality_functional.hpp.
reset_num_evals()
template<typename MeshType_ > void FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::reset_num_evals () inline
Resets all evaluation counts.
Definition at line 210 of file mesh_quality_functional.hpp.
References FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_func_evals, FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_grad_evals, and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_hess_evals.
Member Data Documentation
_coords_buffer
template<typename MeshType_ > CoordsBufferType FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_coords_buffer
Coordinates, used for setting new boundary values etc.
Definition at line 50 of file mesh_quality_functional.hpp.
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::buffer_to_mesh(), FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_coords(), and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::mesh_to_buffer().
_mesh_node
template<typename MeshType_ > Geometry::RootMeshNode<MeshType>* FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_mesh_node
The mesh for the underlying transformation.
Definition at line 48 of file mesh_quality_functional.hpp.
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_mesh(), and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_mesh_node().
_num_func_evals
template<typename MeshType_ > Index FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_func_evals protected
Counter for number of function evaluations.
Definition at line 54 of file mesh_quality_functional.hpp.
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_num_func_evals(), and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::reset_num_evals().
_num_grad_evals
template<typename MeshType_ > Index FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_grad_evals protected
Counter for number of gradient evaluations.
Definition at line 56 of file mesh_quality_functional.hpp.
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_num_grad_evals(), and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::reset_num_evals().
_num_hess_evals
template<typename MeshType_ > Index FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::_num_hess_evals protected
Counter for number of hessian evaluations.
Definition at line 58 of file mesh_quality_functional.hpp.
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::get_num_hess_evals(), and FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::reset_num_evals().
The documentation for this class was generated from the following file:
kernel/meshopt/mesh_quality_functional.hpp