FEAT: FEAT::Geometry::MeshNodeLinker< RootMesh_ > Class Template Reference
FEAT::Geometry::MeshNodeLinker< RootMesh_ > Class Template Reference
MeshNode liner class template.
#include <mesh_file_reader.hpp>
Public Member Functions
MeshNodeLinker (RootMeshNode< RootMesh_ > &mesh_node, MeshAtlas< RootMesh_ > &atlas)
Constructor.
void execute ()
Executes the linker.
void meshpart_deduct_topology (const String &meshpart)
Adds a task to deduct a meshpart topology from the root mesh.
void meshpart_link_to_chart (const String &meshpart, const String &chart)
Adds a task to link a meshpart to a chart.
Protected Attributes
MeshAtlas< RootMesh_ > & _atlas
our atlas
RootMeshNode< RootMesh_ > & _mesh_node
our mesh node
std::deque< String > _meshpart_deduct_topo
std::deque< std::pair< String, String > > _meshpart_to_chart
Detailed Description
template<typename RootMesh_>
class FEAT::Geometry::MeshNodeLinker< RootMesh_ >
MeshNode liner class template.
This linker class is used by the MeshFileReader for various post-parse operations, such as deducting meshpart topologies or linking meshparts to their corresponding charts.
Author
Peter Zajac
Definition at line 56 of file mesh_file_reader.hpp.
Constructor & Destructor Documentation
MeshNodeLinker()
template<typename RootMesh_ > FEAT::Geometry::MeshNodeLinker< RootMesh_ >::MeshNodeLinker (RootMeshNode< RootMesh_ > & mesh_node, MeshAtlas< RootMesh_ > & atlas) inline explicit
Constructor.
Parameters
[in,out] mesh_node A resident reference to the mesh node that the linker should operate on.
[in,out] atlas A resident reference to the atlas that contains the charts.
Definition at line 79 of file mesh_file_reader.hpp.
Member Function Documentation
execute()
template<typename RootMesh_ > void FEAT::Geometry::MeshNodeLinker< RootMesh_ >::execute () inline
Executes the linker.
This function executes all the tasks that have been added to the linker.
Definition at line 115 of file mesh_file_reader.hpp.
References FEAT::Geometry::MeshNodeLinker< RootMesh_ >::_atlas, FEAT::Geometry::MeshNodeLinker< RootMesh_ >::_mesh_node, FEAT::Geometry::MeshPart< MeshType_ >::deduct_topology(), and FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart().
Referenced by FEAT::Geometry::MeshFileReader::parse().
meshpart_deduct_topology()
template<typename RootMesh_ > void FEAT::Geometry::MeshNodeLinker< RootMesh_ >::meshpart_deduct_topology (const String & meshpart) inline
Adds a task to deduct a meshpart topology from the root mesh.
Parameters
[in] meshpart The name of the meshpart whose topology is to be deducted from the root mesh.
Definition at line 105 of file mesh_file_reader.hpp.
meshpart_link_to_chart()
template<typename RootMesh_ > void FEAT::Geometry::MeshNodeLinker< RootMesh_ >::meshpart_link_to_chart (const String & meshpart, const String & chart) inline
Adds a task to link a meshpart to a chart.
Parameters
[in] meshpart The name of the meshpart that is to be linked to a chart.
[in] chart A resident reference to the name of the chart that the meshpart is to be linked to.
Definition at line 94 of file mesh_file_reader.hpp.
Member Data Documentation
_atlas
template<typename RootMesh_ > MeshAtlas<RootMesh_>& FEAT::Geometry::MeshNodeLinker< RootMesh_ >::_atlas protected
our atlas
Definition at line 62 of file mesh_file_reader.hpp.
Referenced by FEAT::Geometry::MeshNodeLinker< RootMesh_ >::execute().
_mesh_node
template<typename RootMesh_ > RootMeshNode<RootMesh_>& FEAT::Geometry::MeshNodeLinker< RootMesh_ >::_mesh_node protected
our mesh node
Definition at line 60 of file mesh_file_reader.hpp.
Referenced by FEAT::Geometry::MeshNodeLinker< RootMesh_ >::execute().
_meshpart_deduct_topo
template<typename RootMesh_ > std::deque<String> FEAT::Geometry::MeshNodeLinker< RootMesh_ >::_meshpart_deduct_topo protected
Definition at line 67 of file mesh_file_reader.hpp.
_meshpart_to_chart
template<typename RootMesh_ > std::deque<std::pair<String,String> > FEAT::Geometry::MeshNodeLinker< RootMesh_ >::_meshpart_to_chart protected
Definition at line 65 of file mesh_file_reader.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/mesh_file_reader.hpp