FEAT: FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ > Class Template Reference
FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ > Class Template Reference
Public Types
typedef Traits_::DataType DataType
coefficient data type
typedef Traits_::GradientType GradientType
gradient type
typedef Traits_::HessianType HessianType
hessian type
typedef Traits_::PointType PointType
evaluation point type
typedef Traits_::ValueType ValueType
value type
Public Member Functions
Evaluator (const AutoDerive &function)
mandatory CTOR
GradientType extrapol_grad (const PointType &point)
Computes the gradient by a Richardson extrapolation scheme.
HessianType extrapol_hess (const PointType &point)
Computes the hessian by a Richardson extrapolation scheme.
GradientType gradient (const PointType &point)
HessianType hessian (const PointType &point)
ValueType value (const PointType &point)
Static Public Attributes
static constexpr int domain_dim = Traits_::domain_dim
get our dimension
Protected Member Functions
void _eval_grad_quot (GradientType &x, PointType &v, const DataType h)
evaluates the first-order difference quotients
void _eval_hess_quot (HessianType &x, PointType &v, const DataType h)
evaluates the second-order difference quotients
Static Protected Member Functions
template<int img_dim_, int sm_, int sn_>
static void _set_grad_quot (Tiny::Matrix< DataType, img_dim_, domain_dim, sm_, sn_ > &x, int i, const ValueType &vr, const ValueType &vl, const DataType denom)
template<int sn_>
static void _set_grad_quot (Tiny::Vector< DataType, domain_dim, sn_ > &x, int i, const DataType &vr, const DataType &vl, const DataType denom)
template<int sm_, int sn_>
static void _set_hess_quot (Tiny::Matrix< DataType, domain_dim, domain_dim, sm_, sn_ > &x, int i, const ValueType &vr, const ValueType &vl, const ValueType &vc, const DataType denom)
template<int sm_, int sn_>
static void _set_hess_quot (Tiny::Matrix< DataType, domain_dim, domain_dim, sm_, sn_ > &x, int i, int j, const ValueType &vne, const ValueType &vsw, const ValueType &vnw, const ValueType &vse, const DataType denom)
template<int image_dim_, int sl_, int sm_, int sn_>
static void _set_hess_quot (Tiny::Tensor3< DataType, image_dim_, domain_dim, domain_dim, sl_, sm_, sn_ > &x, int i, const ValueType &vr, const ValueType &vl, const ValueType &vc, const DataType denom)
template<int image_dim_, int sl_, int sm_, int sn_>
static void _set_hess_quot (Tiny::Tensor3< DataType, image_dim_, domain_dim, domain_dim, sl_, sm_, sn_ > &x, int i, int j, const ValueType &vne, const ValueType &vsw, const ValueType &vnw, const ValueType &vse, const DataType denom)
template<int m_, int n_, int sm_, int sn_>
static DataType def_norm_sqr (const Tiny::Matrix< DataType, m_, n_, sm_, sn_ > &x, const Tiny::Matrix< DataType, m_, n_, sm_, sn_ > &y)
template<int l_, int m_, int n_, int sl_, int sm_, int sn_>
static DataType def_norm_sqr (const Tiny::Tensor3< DataType, l_, m_, n_, sl_, sm_, sn_ > &x, const Tiny::Tensor3< DataType, l_, m_, n_, sl_, sm_, sn_ > &y)
template<int n_, int s_>
static DataType def_norm_sqr (const Tiny::Vector< DataType, n_, s_ > &x, const Tiny::Vector< DataType, n_, s_ > &y)
Private Attributes
Function_::template Evaluator< Traits_ > _func_eval
the original function's evaluator
std::vector< GradientType > _grad
our gradient extrapolation table
std::vector< HessianType > _hess
our hessian extrapolation table
const DataType _init_grad_h
initial h for gradient extrapolation
const DataType _init_hess_h
initial h for hessian extrapolation
Detailed Description
template<typename Function_, typename DataType_ = Real>
template<typename Traits_>
class FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >
Definition at line 111 of file auto_derive.hpp.
Member Typedef Documentation
DataType
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > typedef Traits_::DataType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::DataType
coefficient data type
Definition at line 116 of file auto_derive.hpp.
GradientType
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > typedef Traits_::GradientType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::GradientType
gradient type
Definition at line 122 of file auto_derive.hpp.
HessianType
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > typedef Traits_::HessianType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::HessianType
hessian type
Definition at line 124 of file auto_derive.hpp.
PointType
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > typedef Traits_::PointType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::PointType
evaluation point type
Definition at line 118 of file auto_derive.hpp.
ValueType
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > typedef Traits_::ValueType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::ValueType
value type
Definition at line 120 of file auto_derive.hpp.
Constructor & Destructor Documentation
Evaluator()
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::Evaluator (const AutoDerive & function) inline explicit
mandatory CTOR
Definition at line 142 of file auto_derive.hpp.
Member Function Documentation
_eval_grad_quot()
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > void FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_eval_grad_quot (GradientType & x, PointType & v, const DataType h) inline protected
evaluates the first-order difference quotients
Definition at line 333 of file auto_derive.hpp.
References FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_func_eval, and FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::domain_dim.
Referenced by FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::extrapol_grad().
_eval_hess_quot()
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > void FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_eval_hess_quot (HessianType & x, PointType & v, const DataType h) inline protected
evaluates the second-order difference quotients
Definition at line 392 of file auto_derive.hpp.
References FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_func_eval, and FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::domain_dim.
Referenced by FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::extrapol_hess().
_set_grad_quot() [1/2]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int img_dim_, int sm_, int sn_> static void FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_set_grad_quot (Tiny::Matrix< DataType, img_dim_, domain_dim, sm_, sn_ > & x, int i, const ValueType & vr, const ValueType & vl, const DataType denom) inline static protected
Definition at line 326 of file auto_derive.hpp.
_set_grad_quot() [2/2]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int sn_> static void FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_set_grad_quot (Tiny::Vector< DataType, domain_dim, sn_ > & x, int i, const DataType & vr, const DataType & vl, const DataType denom) inline static protected
Definition at line 319 of file auto_derive.hpp.
_set_hess_quot() [1/4]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int sm_, int sn_> static void FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_set_hess_quot (Tiny::Matrix< DataType, domain_dim, domain_dim, sm_, sn_ > & x, int i, const ValueType & vr, const ValueType & vl, const ValueType & vc, const DataType denom) inline static protected
Definition at line 363 of file auto_derive.hpp.
_set_hess_quot() [2/4]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int sm_, int sn_> static void FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_set_hess_quot (Tiny::Matrix< DataType, domain_dim, domain_dim, sm_, sn_ > & x, int i, int j, const ValueType & vne, const ValueType & vsw, const ValueType & vnw, const ValueType & vse, const DataType denom) inline static protected
Definition at line 370 of file auto_derive.hpp.
_set_hess_quot() [3/4]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int image_dim_, int sl_, int sm_, int sn_> static void FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_set_hess_quot (Tiny::Tensor3< DataType, image_dim_, domain_dim, domain_dim, sl_, sm_, sn_ > & x, int i, const ValueType & vr, const ValueType & vl, const ValueType & vc, const DataType denom) inline static protected
Definition at line 377 of file auto_derive.hpp.
_set_hess_quot() [4/4]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int image_dim_, int sl_, int sm_, int sn_> static void FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_set_hess_quot (Tiny::Tensor3< DataType, image_dim_, domain_dim, domain_dim, sl_, sm_, sn_ > & x, int i, int j, const ValueType & vne, const ValueType & vsw, const ValueType & vnw, const ValueType & vse, const DataType denom) inline static protected
Definition at line 385 of file auto_derive.hpp.
def_norm_sqr() [1/3]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int m_, int n_, int sm_, int sn_> static DataType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::def_norm_sqr (const Tiny::Matrix< DataType, m_, n_, sm_, sn_ > & x, const Tiny::Matrix< DataType, m_, n_, sm_, sn_ > & y) inline static protected
Definition at line 291 of file auto_derive.hpp.
def_norm_sqr() [2/3]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int l_, int m_, int n_, int sl_, int sm_, int sn_> static DataType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::def_norm_sqr (const Tiny::Tensor3< DataType, l_, m_, n_, sl_, sm_, sn_ > & x, const Tiny::Tensor3< DataType, l_, m_, n_, sl_, sm_, sn_ > & y) inline static protected
Definition at line 299 of file auto_derive.hpp.
def_norm_sqr() [3/3]
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > template<int n_, int s_> static DataType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::def_norm_sqr (const Tiny::Vector< DataType, n_, s_ > & x, const Tiny::Vector< DataType, n_, s_ > & y) inline static protected
Definition at line 284 of file auto_derive.hpp.
extrapol_grad()
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > GradientType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::extrapol_grad (const PointType & point) inline
Computes the gradient by a Richardson extrapolation scheme.
Definition at line 175 of file auto_derive.hpp.
References FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_eval_grad_quot(), FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_grad, and FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_init_grad_h.
extrapol_hess()
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > HessianType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::extrapol_hess (const PointType & point) inline
Computes the hessian by a Richardson extrapolation scheme.
Definition at line 230 of file auto_derive.hpp.
References FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_eval_hess_quot(), FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_hess, and FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_init_hess_h.
gradient()
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > GradientType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::gradient (const PointType & point) inline
Definition at line 156 of file auto_derive.hpp.
hessian()
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > HessianType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::hessian (const PointType & point) inline
Definition at line 164 of file auto_derive.hpp.
value()
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > ValueType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::value (const PointType & point) inline
Definition at line 151 of file auto_derive.hpp.
Member Data Documentation
_func_eval
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > Function_::template Evaluator<Traits_> FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_func_eval private
the original function's evaluator
Definition at line 130 of file auto_derive.hpp.
Referenced by FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_eval_grad_quot(), and FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_eval_hess_quot().
_grad
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > std::vector<GradientType> FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_grad private
our gradient extrapolation table
Definition at line 132 of file auto_derive.hpp.
Referenced by FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::extrapol_grad().
_hess
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > std::vector<HessianType> FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_hess private
our hessian extrapolation table
Definition at line 134 of file auto_derive.hpp.
Referenced by FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::extrapol_hess().
_init_grad_h
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > const DataType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_init_grad_h private
initial h for gradient extrapolation
Definition at line 136 of file auto_derive.hpp.
Referenced by FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::extrapol_grad().
_init_hess_h
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > const DataType FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_init_hess_h private
initial h for hessian extrapolation
Definition at line 138 of file auto_derive.hpp.
Referenced by FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::extrapol_hess().
domain_dim
template<typename Function_ , typename DataType_ = Real> template<typename Traits_ > constexpr int FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::domain_dim = Traits_::domain_dim static constexpr
get our dimension
Definition at line 126 of file auto_derive.hpp.
Referenced by FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_eval_grad_quot(), and FEAT::Analytic::AutoDerive< Function_, DataType_ >::Evaluator< Traits_ >::_eval_hess_quot().
The documentation for this class was generated from the following file:
kernel/analytic/auto_derive.hpp