FEAT: FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ > Class Template Reference
FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ > Class Template Reference
Multigrid hierarchy management class template.
#include <multigrid.hpp>
Classes
class LevelInfo
Multigrid level info class.
Public Types
typedef MultiGridLevelBase< SystemMatrix_, SystemFilter_, TransferOperator_ > LevelType
the level base class type
typedef LevelType::SolverType SolverType
the coarse-grid solver/smoother type
typedef MultiGridLevelStd< SystemMatrix_, SystemFilter_, TransferOperator_ > StdLevelType
the standard level class type
typedef LevelType::SystemFilterType SystemFilterType
the system filter type
typedef LevelType::SystemMatrixType SystemMatrixType
the system matrix type
typedef LevelType::SystemVectorType SystemVectorType
the system vector type
typedef LevelType::TransferOperatorType TransferOperatorType
the transfer operator type
Public Member Functions
MultiGridHierarchy (std::size_t size_virt)
Constructor.
virtual ~MultiGridHierarchy ()
Destructor.
void done ()
Finalization method.
void done_numeric ()
Numeric finalization method.
void done_symbolic ()
Symbolic finalization method.
LevelType & get_level (Index lvl)
Returns a level in the hierarchy.
const LevelType & get_level (Index lvl) const
Returns a level in the hierarchy.
double get_time_coarse (int lvl=-1) const
Returns the time for coarse grid solver application.
double get_time_defect (int lvl=-1) const
Returns the time for defect computation.
double get_time_smooth (int lvl=-1) const
Returns the time for smoother application.
double get_time_transfer (int lvl=-1) const
Returns the time for grid transfer application.
bool have_numeric () const
Specifies whether the symbolic initialization was performed.
bool have_symbolic () const
Specifies whether the symbolic initialization was performed.
void init ()
Initialization method.
void init_numeric ()
Numeric initialization method.
void init_symbolic ()
Symbolic initialization method.
void push_level (const SystemMatrixType &system_matrix, const SystemFilterType &system_filter, const TransferOperatorType &transfer_operator, std::shared_ptr< SolverType > smoother_pre, std::shared_ptr< SolverType > smoother_post, std::shared_ptr< SolverType > smoother_peak, std::shared_ptr< SolverType > coarse_solver=nullptr)
Pushes a standard refined level into the hierarchy.
void push_level (const SystemMatrixType &system_matrix, const SystemFilterType &system_filter, std::shared_ptr< SolverType > coarse_solver)
Pushes a standard coarse-grid level into the hierarchy.
void push_level (std::shared_ptr< LevelType > level)
Pushes a new (custom) level into the hierarchy.
void reset_timings ()
Resets the internal timing statistics.
Index size_physical () const
Returns the physical hierarchy size.
Index size_virtual () const
Returns the virtual hierarchy size.
Protected Member Functions
LevelInfo & _get_level_info (Index lvl)
Returns a level info in the hierarchy.
Protected Attributes
bool _have_init_numeric
specifies whether init_numeric() has been called
bool _have_init_symbolic
specifies whether init_symbolic() has been called
std::deque< LevelInfo > _levels
the deque of all level info objects
std::size_t _virt_size
the virtual multigrid hierarchy sizes
Friends
class MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >
MultiGrid is our friend.
Detailed Description
template<typename SystemMatrix_, typename SystemFilter_, typename TransferOperator_>
class FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >
Multigrid hierarchy management class template.
Todo:
document this
Template Parameters
SystemMatrix_ The class representing the system matrix.
SystemFilter_ The class representing the system filter.
TransferOperator_ The class representing the transfer operator.
Author
Peter Zajac
Definition at line 419 of file multigrid.hpp.
Member Typedef Documentation
LevelType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef MultiGridLevelBase<SystemMatrix_, SystemFilter_, TransferOperator_> FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::LevelType
the level base class type
Definition at line 426 of file multigrid.hpp.
SolverType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::SolverType FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::SolverType
the coarse-grid solver/smoother type
Definition at line 439 of file multigrid.hpp.
StdLevelType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef MultiGridLevelStd<SystemMatrix_, SystemFilter_, TransferOperator_> FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::StdLevelType
the standard level class type
Definition at line 428 of file multigrid.hpp.
SystemFilterType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::SystemFilterType FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::SystemFilterType
the system filter type
Definition at line 433 of file multigrid.hpp.
SystemMatrixType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::SystemMatrixType FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::SystemMatrixType
the system matrix type
Definition at line 431 of file multigrid.hpp.
SystemVectorType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::SystemVectorType FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::SystemVectorType
the system vector type
Definition at line 435 of file multigrid.hpp.
TransferOperatorType
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > typedef LevelType::TransferOperatorType FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::TransferOperatorType
the transfer operator type
Definition at line 437 of file multigrid.hpp.
Constructor & Destructor Documentation
MultiGridHierarchy()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::MultiGridHierarchy (std::size_t size_virt) inline explicit
Constructor.
Parameters
[in] size_virt The virtual multigrid hierarchy size on all processes.
Definition at line 588 of file multigrid.hpp.
~MultiGridHierarchy()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > virtual FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::~MultiGridHierarchy () inline virtual
Destructor.
Definition at line 599 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels.
Member Function Documentation
_get_level_info()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > LevelInfo & FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_get_level_info (Index lvl) inline protected
Returns a level info in the hierarchy.
Note
This function is used by the MultiGrid solver class.
Parameters
[in] lvl The index of the level info to be returned.
Returns
A reference to the corresponding level info object.
Definition at line 565 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::size_physical(), and XASSERTM.
done()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done () inline
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 829 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic().
done_numeric()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric () inline
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step of the sub-solvers in the multigrid hierarchy.
Definition at line 794 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_numeric, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, and XASSERTM.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done().
done_symbolic()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic () inline
Symbolic finalization method.
This method is called to release any data allocated in the symbolic initialization step of the sub-solvers in the multigrid hierarchy.
Definition at line 757 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_numeric, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_symbolic, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, and XASSERTM.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done().
get_level() [1/2]
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > LevelType & FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_level (Index lvl) inline
Returns a level in the hierarchy.
Parameters
[in] lvl The index of the level to be returned.
Returns
A (const) reference to the corresponding level object.
Definition at line 720 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::size_physical(), and XASSERTM.
get_level() [2/2]
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > const LevelType & FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_level (Index lvl) const inline
Returns a level in the hierarchy.
Parameters
[in] lvl The index of the level to be returned.
Returns
A (const) reference to the corresponding level object.
Definition at line 727 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::size_physical(), and XASSERTM.
get_time_coarse()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > double FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_time_coarse (int lvl = -1) const inline
Returns the time for coarse grid solver application.
Parameters
[in] lvl The level for which the timing is to be retrieved. If set to -1, the sum of all level timings is returned.
Returns
The time for coarse grid solver application.
Definition at line 898 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, and XASSERT.
get_time_defect()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > double FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_time_defect (int lvl = -1) const inline
Returns the time for defect computation.
Parameters
[in] lvl The level for which the timing is to be retrieved. If set to -1, the sum of all level timings is returned.
Returns
The time for defect computation.
Definition at line 921 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, and XASSERT.
get_time_smooth()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > double FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_time_smooth (int lvl = -1) const inline
Returns the time for smoother application.
Parameters
[in] lvl The level for which the timing is to be retrieved. If set to -1, the sum of all level timings is returned.
Returns
The time for smoother application.
Definition at line 875 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, and XASSERT.
get_time_transfer()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > double FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_time_transfer (int lvl = -1) const inline
Returns the time for grid transfer application.
Parameters
[in] lvl The level for which the timing is to be retrieved. If set to -1, the sum of all level timings is returned.
Returns
The time for grid transfer application.
Definition at line 944 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, and XASSERT.
have_numeric()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > bool FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::have_numeric () const inline
Specifies whether the symbolic initialization was performed.
Returns
true between a call of init_symbolic() and done_symbolic(), otherwise false.
Definition at line 852 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_numeric.
have_symbolic()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > bool FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::have_symbolic () const inline
Specifies whether the symbolic initialization was performed.
Returns
true between a call of init_symbolic() and done_symbolic(), otherwise false.
Definition at line 841 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_symbolic.
init()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init () inline
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 814 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric(), and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic().
init_numeric()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric () inline
Numeric initialization method.
This method is called to perform numeric initialization of the sub-solvers in the multigrid hierarchy.
Before this function can be called, the symbolic initialization must be performed.
Definition at line 776 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_numeric, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_symbolic, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, and XASSERTM.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init().
init_symbolic()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic () inline
Symbolic initialization method.
This method is called to perform symbolic initialization of the sub-solvers in the multigrid hierarchy.
Definition at line 739 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_numeric, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_symbolic, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, and XASSERTM.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init().
push_level() [1/3]
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level (const SystemMatrixType & system_matrix, const SystemFilterType & system_filter, const TransferOperatorType & transfer_operator, std::shared_ptr< SolverType > smoother_pre, std::shared_ptr< SolverType > smoother_post, std::shared_ptr< SolverType > smoother_peak, std::shared_ptr< SolverType > coarse_solver = nullptr) inline
Pushes a standard refined level into the hierarchy.
Parameters
[in] system_matrix A reference to the system matrix.
[in] system_filter A reference to the system filter.
[in] transfer_operator A reference to the transfer operator onto this level.
[in] smoother_pre A shared pointer to the pre-smoother. May be nullptr if no pre-smoother is to be used.
[in] smoother_post A shared pointer to the post-smoother. May be nullptr if no post-smoother is to be used.
[in] smoother_peak A shared pointer to the peak-smoother. Is set to nullptr, the multigrid will use both the pre- and post-smoothers as the peak-smoother.
[in] coarse_solver A shared pointer to the coarse grid solver. This one is usually nullptr, unless one wants to use this refined level also as a coarse-grid level.
Note
The smoother_pre, smoother_post, smoother_peak and coarse_solver pointers need not point to different objects. This class will ensure the correct handling of unique solver objects independent of whether more that one pointer references the same unique object on one level.
Definition at line 677 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level().
push_level() [2/3]
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level (const SystemMatrixType & system_matrix, const SystemFilterType & system_filter, std::shared_ptr< SolverType > coarse_solver) inline
Pushes a standard coarse-grid level into the hierarchy.
Parameters
[in] system_matrix A reference to the system matrix.
[in] system_filter A reference to the system filter.
[in] coarse_solver A shared pointer to the coarse grid solver. May be nullptr if no coarse-grid solver is to be used.
Definition at line 633 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level().
push_level() [3/3]
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level (std::shared_ptr< LevelType > level) inline
Pushes a new (custom) level into the hierarchy.
Parameters
[in] level A shared pointer to the new level.
Definition at line 612 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_numeric, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_symbolic, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels, FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_virt_size, and XASSERTM.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level().
reset_timings()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > void FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::reset_timings () inline
Resets the internal timing statistics.
Definition at line 860 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels.
size_physical()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Index FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::size_physical () const inline
Returns the physical hierarchy size.
Returns
The physical hierarchy size.
Definition at line 696 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_get_level_info(), and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_level().
size_virtual()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > Index FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::size_virtual () const inline
Returns the virtual hierarchy size.
Returns
The virtual hierarchy size.
Definition at line 706 of file multigrid.hpp.
References FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_virt_size.
Friends And Related Function Documentation
MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > friend class MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ > friend
MultiGrid is our friend.
Definition at line 386 of file multigrid.hpp.
Member Data Documentation
_have_init_numeric
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > bool FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_numeric protected
specifies whether init_numeric() has been called
Definition at line 579 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::have_numeric(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic(), and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level().
_have_init_symbolic
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > bool FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_have_init_symbolic protected
specifies whether init_symbolic() has been called
Definition at line 577 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::have_symbolic(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic(), and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level().
_levels
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::deque<LevelInfo> FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_levels protected
the deque of all level info objects
Definition at line 573 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::~MultiGridHierarchy(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_get_level_info(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_symbolic(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_level(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_time_coarse(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_time_defect(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_time_smooth(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::get_time_transfer(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_symbolic(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level(), FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::reset_timings(), and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::size_physical().
_virt_size
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::size_t FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::_virt_size protected
the virtual multigrid hierarchy sizes
Definition at line 575 of file multigrid.hpp.
Referenced by FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::push_level(), and FEAT::Solver::MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ >::size_virtual().
The documentation for this class was generated from the following file:
kernel/solver/multigrid.hpp