FEAT: FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > Class Template Reference
FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > Class Template Reference
Bogner-Fox-Schmit Element Evaluator implementation for Hypercube<2> shape.
#include <evaluator.hpp>
Public Types
typedef ParametricEvaluator< Evaluator, TrafoEvaluator_, SpaceEvalTraits_, ref_caps > BaseClass
base-class typedef
typedef SpaceEvalTraits::DataType DataType
data type
typedef EvalPolicy::DomainPointType DomainPointType
domain point type
typedef SpaceEvalTraits::EvalPolicy EvalPolicy
evaluation policy
typedef SpaceEvalTraits_ SpaceEvalTraits
space evaluation traits
typedef Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > SpaceEvaluator
space evaluator type
typedef Space_ SpaceType
space type
typedef TrafoEvaluator::EvalTraits TrafoEvalTraits
trafo evaluator traits
typedef TrafoEvaluator_ TrafoEvaluator
trafo evaluator type
Public Member Functions
Evaluator (const SpaceType &space)
Constructor.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_gradients (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function gradients on the real cell.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_hessians (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function hessians on the real cell.
template<typename EvalData_ >
void eval_ref_gradients (EvalData_ &data, const DomainPointType &point) const
Evaluates the basis function gradients on the reference cell.
template<typename EvalData_ >
void eval_ref_hessians (EvalData_ &data, const DomainPointType &point) const
Evaluates the basis function hessians on the reference cell.
template<typename EvalData_ >
void eval_ref_values (EvalData_ &data, const DomainPointType &point) const
Evaluates the basis function values on the reference cell.
template<SpaceTags space_cfg_, TrafoTags trafo_cfg_>
void eval_values (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
Evaluates the basis function values on the real cell.
void finish ()
Releases the evaluator from the current cell.
int get_num_local_dofs () const
Returns the number of local DOFs.
void operator() (EvalData< SpaceEvalTraits, space_cfg_ > &space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > &trafo_data) const
void prepare (const TrafoEvaluator &trafo_eval)
Prepares the evaluator for a given cell.
void reference_eval (EvalData< SpaceEvalTraits, space_cfg_ > &space_ref_data, const typename SpaceEvalTraits::DomainPointType &dom_point) const
Space reference evaluation function.
Static Public Attributes
static constexpr int domain_dim
domain dimension
static constexpr SpaceTags eval_caps
our evaluation capabilities
static constexpr int image_dim
image dimension
static constexpr int max_local_dofs
maximum number of local dofs
static constexpr TrafoTags trafo_caps
the capabilities of the trafo evaluator
Protected Member Functions
DataType _trans_dx (Index i, DataType rx, DataType ry) const
Transforms the X-derivative basis function.
DataType _trans_dy (Index i, DataType rx, DataType ry) const
Transforms the Y-derivative basis function.
Protected Attributes
Tiny::Matrix< DataType, 2, 2 > _coeff_fod [4]
first-order derivative transform coefficients
Detailed Description
template<typename Space_, typename TrafoEvaluator_, typename SpaceEvalTraits_>
class FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >
Bogner-Fox-Schmit Element Evaluator implementation for Hypercube<2> shape.
Author
Peter Zajac
Definition at line 290 of file evaluator.hpp.
Member Typedef Documentation
BaseClass
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef ParametricEvaluator<Evaluator, TrafoEvaluator_, SpaceEvalTraits_, ref_caps> FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::BaseClass
base-class typedef
Definition at line 303 of file evaluator.hpp.
DataType
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef SpaceEvalTraits::DataType FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::DataType
data type
Definition at line 321 of file evaluator.hpp.
DomainPointType
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef EvalPolicy::DomainPointType FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::DomainPointType
domain point type
Definition at line 318 of file evaluator.hpp.
EvalPolicy
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef SpaceEvalTraits::EvalPolicy FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::EvalPolicy
evaluation policy
Definition at line 315 of file evaluator.hpp.
SpaceEvalTraits
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef SpaceEvalTraits_ FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::SpaceEvalTraits
space evaluation traits
Definition at line 309 of file evaluator.hpp.
SpaceEvaluator
typedef Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::SpaceEvaluator inherited
space evaluator type
Definition at line 57 of file parametric_evaluator.hpp.
SpaceType
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef Space_ FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::SpaceType
space type
Definition at line 306 of file evaluator.hpp.
TrafoEvalTraits
typedef TrafoEvaluator::EvalTraits FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::TrafoEvalTraits inherited
trafo evaluator traits
Definition at line 66 of file parametric_evaluator.hpp.
TrafoEvaluator
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > typedef TrafoEvaluator_ FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::TrafoEvaluator
trafo evaluator type
Definition at line 312 of file evaluator.hpp.
Constructor & Destructor Documentation
Evaluator()
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::Evaluator (const SpaceType & space) inline explicit
Constructor.
Parameters
[in] space A reference to the Element using this evaluator.
Definition at line 368 of file evaluator.hpp.
Member Function Documentation
_trans_dx()
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > DataType FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::_trans_dx (Index i, DataType rx, DataType ry) const inline protected
Transforms the X-derivative basis function.
Parameters
[in] i The index of the vertex of the basis function.
[in] rx,ry The values of the X- and Y-derivative basis functions on the reference element.
Returns
The value of the X-derivative basis function on the real element.
Definition at line 339 of file evaluator.hpp.
_trans_dy()
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > DataType FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::_trans_dy (Index i, DataType rx, DataType ry) const inline protected
Transforms the Y-derivative basis function.
Parameters
[in] i The index of the vertex of the basis function.
[in] rx,ry The values of the X- and Y-derivative basis functions on the reference element.
Returns
The value of the Y-derivative basis function on the real element.
Definition at line 356 of file evaluator.hpp.
eval_gradients()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_gradients (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline inherited
Evaluates the basis function gradients on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function gradients.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 195 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
eval_hessians()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_hessians (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline inherited
Evaluates the basis function hessians on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function hessian matrices.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 215 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
eval_ref_gradients()
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<typename EvalData_ > void FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::eval_ref_gradients (EvalData_ & data, const DomainPointType & point) const inline
Evaluates the basis function gradients on the reference cell.
Parameters
[out] data A reference to a basis gradient vector receiving the result.
[in] point A reference to the point on the reference cell where to evaluate.
Definition at line 473 of file evaluator.hpp.
eval_ref_hessians()
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<typename EvalData_ > void FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::eval_ref_hessians (EvalData_ & data, const DomainPointType & point) const inline
Evaluates the basis function hessians on the reference cell.
Parameters
[out] data A reference to a basis hessian vector receiving the result.
[in] point A reference to the point on the reference cell where to evaluate.
Definition at line 547 of file evaluator.hpp.
eval_ref_values()
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<typename EvalData_ > void FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::eval_ref_values (EvalData_ & data, const DomainPointType & point) const inline
Evaluates the basis function values on the reference cell.
Parameters
[out] data A reference to a basis value vector receiving the result.
[in] point A reference to the point on the reference cell where to evaluate.
Definition at line 423 of file evaluator.hpp.
eval_values()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > template<SpaceTags space_cfg_, TrafoTags trafo_cfg_> void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::eval_values (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline inherited
Evaluates the basis function values on the real cell.
Template Parameters
space_cfg_,trafo_cfg_ The space and trafo configuration tags. These are determined automatically by the compiler.
Parameters
[out] space_data A transient reference to an evaluation data structure that shall receive the basis function values.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 175 of file evaluator_base.hpp.
References XABORTM.
Referenced by FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::operator()().
finish()
template<typename SpaceEvaluator_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > void FEAT::Space::EvaluatorBase< SpaceEvaluator_, TrafoEvaluator_, SpaceEvalTraits_ >::finish () inline inherited
Releases the evaluator from the current cell.
Definition at line 115 of file evaluator_base.hpp.
get_num_local_dofs()
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > int FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::get_num_local_dofs () const inline
Returns the number of local DOFs.
Returns
The number of local dofs.
Definition at line 378 of file evaluator.hpp.
operator()()
void FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::operator() (EvalData< SpaceEvalTraits, space_cfg_ > & space_data, const Trafo::EvalData< TrafoEvalTraits, trafo_cfg_ > & trafo_data) const inline inherited
Space evaluation operator.
This operator evaluates the basis functions in a point on a mesh cell.
Parameters
[out] space_data A transient reference to the space data that is to be computed.
[in] trafo_data The transient trafo evaluation data containing information about the evaluation point.
Definition at line 167 of file parametric_evaluator.hpp.
prepare()
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > void FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::prepare (const TrafoEvaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > & trafo_eval) inline
Prepares the evaluator for a given cell.
Parameters
[in] trafo_eval A reference to the trafo evaluator containing the cell information.
Definition at line 389 of file evaluator.hpp.
References FEAT::dom_point.
reference_eval()
void FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::reference_eval (EvalData< SpaceEvalTraits, space_cfg_ > & space_ref_data, const typename SpaceEvalTraits::DomainPointType & dom_point) const inline inherited
Space reference evaluation function.
This function evaluates the basis functions in a point on the reference cell.
Parameters
[out] space_ref_data A transient reference to the space reference data that is to be computed.
[in] dom_point A transient reference to the domain point in which the evaluation shall take place.
Definition at line 153 of file parametric_evaluator.hpp.
Member Data Documentation
_coeff_fod
template<typename Space_ , typename TrafoEvaluator_ , typename SpaceEvalTraits_ > Tiny::Matrix<DataType, 2, 2> FEAT::Space::BognerFoxSchmit::Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > >::_coeff_fod[4] protected
first-order derivative transform coefficients
Definition at line 325 of file evaluator.hpp.
domain_dim
constexpr int FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::domain_dim static constexpr inherited
domain dimension
Definition at line 92 of file parametric_evaluator.hpp.
eval_caps
constexpr SpaceTags FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::eval_caps static constexpr inherited
our evaluation capabilities
Definition at line 72 of file parametric_evaluator.hpp.
image_dim
constexpr int FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::image_dim static constexpr inherited
image dimension
Definition at line 94 of file parametric_evaluator.hpp.
max_local_dofs
constexpr int FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::max_local_dofs static constexpr inherited
maximum number of local dofs
Definition at line 96 of file parametric_evaluator.hpp.
trafo_caps
constexpr TrafoTags FEAT::Space::ParametricEvaluator< Evaluator< Space_, TrafoEvaluator_, SpaceEvalTraits_, Shape::Hypercube< 2 > > , TrafoEvaluator_, SpaceEvalTraits_, ref_caps_ >::trafo_caps static constexpr inherited
the capabilities of the trafo evaluator
Definition at line 69 of file parametric_evaluator.hpp.
The documentation for this class was generated from the following file:
kernel/space/bogner_fox_schmit/evaluator.hpp