FEAT: FEAT::Geometry::DistributedMeshDistortion< MeshType_ > Class Template Reference
FEAT::Geometry::DistributedMeshDistortion< MeshType_ > Class Template Reference
Distributed mesh distortion class template.
#include <mesh_distortion.hpp>
Public Types
typedef MeshDistortion< MeshType_ > BaseClass
typedef BaseClass::CoordType CoordType
typedef MeshPart< MeshType > MeshPartType
typedef MeshType_ MeshType
typedef RootMeshNode< MeshType > RootMeshNodeType
Public Member Functions
DistributedMeshDistortion (const Dist::Comm &comm, RootMeshNodeType &root_mesh_node)
Constructor.
DistributedMeshDistortion (const Dist::Comm &comm, RootMeshNodeType &root_mesh_node, Random::SeedType seed)
Constructor.
virtual ~DistributedMeshDistortion ()
virtual destructor
void distort_shortest_edge_local (CoordType scale=CoordType(0.1))
Distorts the mesh according to the shortest local edge.
void distort_shortest_edge_uniform (CoordType scale=CoordType(0.1))
Distorts the mesh according to the shortest edge.
void distort_uniform (CoordType rad)
Distorts the mesh uniformly.
Static Public Attributes
static constexpr int facet_dim = MeshType::shape_dim - 1
static constexpr int shape_dim = MeshType_::shape_dim
static constexpr int world_dim = MeshType::world_dim
Protected Member Functions
virtual void _calc_boundary_facets () override
determines for each facet whether it is a boundary facet or an inner facet
virtual void _calc_boundary_vertices ()
determines for each vertex whether it is a boundary vertex or an inner vertex
virtual void _calc_shortest_edge () override
determines for each vertex whether it is a boundary vertex or an inner vertex
virtual void _calc_vertex_owners ()
determines for each vertex the length of the shortest adjacent edge
virtual void _synchronize () override
synchronizes the distortion over all processes; is overridden in DistributedMeshDistortion
Protected Attributes
std::vector< int > _boundary_facets
vector to story which facet is at the boundary
std::vector< int > _boundary_vertices
vector to store which vertex is at the boundary
const Dist::Comm & _comm
a reference to our communicator
MeshType_ & _mesh
the mesh we want to distort
const CoordType _pi_val = Math::pi<CoordType>()
have a guess...
Random _rand
random number generator for random distortion
RootMeshNodeType & _root_mesh_node
a reference to our root mesh node
std::vector< CoordType > _shortest_edge
vector to store the length of the shortest edge belonging to each vertex
std::vector< int > _vertex_owners
a vector of vertex owner ranks
Detailed Description
template<typename MeshType_>
class FEAT::Geometry::DistributedMeshDistortion< MeshType_ >
Distributed mesh distortion class template.
This class extends the functionality of the MeshDistortion class by addition MPI-based synchronization to ensure that one obtains a consistently distorted mesh in a distributed simulation. Note that this class needs to work with a RootMeshNode rather than a "naked" mesh object, because it requires the halos for synchronization, which are stored in the mesh node and not in the mesh object itself.
See the documentation of the base-class MeshDistortion for more information a list of available distortion algorithms.
Template Parameters
MeshType_ The type of the mesh that is to be distorted, e.g. ConformalMesh
Author
Peter Zajac
Definition at line 331 of file mesh_distortion.hpp.
Member Typedef Documentation
BaseClass
template<typename MeshType_ > typedef MeshDistortion<MeshType_> FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::BaseClass
Definition at line 335 of file mesh_distortion.hpp.
CoordType
template<typename MeshType_ > typedef BaseClass::CoordType FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::CoordType
Definition at line 343 of file mesh_distortion.hpp.
MeshPartType
template<typename MeshType_ > typedef MeshPart<MeshType> FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::MeshPartType
Definition at line 337 of file mesh_distortion.hpp.
MeshType
template<typename MeshType_ > typedef MeshType_ FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::MeshType
Definition at line 336 of file mesh_distortion.hpp.
RootMeshNodeType
template<typename MeshType_ > typedef RootMeshNode<MeshType> FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::RootMeshNodeType
Definition at line 338 of file mesh_distortion.hpp.
Constructor & Destructor Documentation
DistributedMeshDistortion() [1/2]
template<typename MeshType_ > FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::DistributedMeshDistortion (const Dist::Comm & comm, RootMeshNodeType & root_mesh_node) inline explicit
Constructor.
Parameters
[in] comm A resident reference to the communicator that was used for partitioning.
[in] root_mesh_node A resident reference to the root mesh node containing the mesh that is to be distorted.
Definition at line 363 of file mesh_distortion.hpp.
DistributedMeshDistortion() [2/2]
template<typename MeshType_ > FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::DistributedMeshDistortion (const Dist::Comm & comm, RootMeshNodeType & root_mesh_node, Random::SeedType seed) inline explicit
Constructor.
Parameters
[in] comm A resident reference to the communicator that was used for partitioning.
[in] root_mesh_node A resident reference to the root mesh node containing the mesh that is to be distorted.
[in] seed The seed for the internal random number generator.
Definition at line 382 of file mesh_distortion.hpp.
~DistributedMeshDistortion()
template<typename MeshType_ > virtual FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::~DistributedMeshDistortion () inline virtual
virtual destructor
Definition at line 391 of file mesh_distortion.hpp.
Member Function Documentation
_calc_boundary_facets()
template<typename MeshType_ > virtual void FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_boundary_facets () inline override protected virtual
determines for each facet whether it is a boundary facet or an inner facet
Reimplemented from FEAT::Geometry::MeshDistortion< MeshType_ >.
Definition at line 397 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_root_mesh_node, FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), and FEAT::Geometry::TargetSet::get_num_entities().
_calc_boundary_vertices()
template<typename MeshType_ > virtual void FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices () inline protected virtual inherited
determines for each vertex whether it is a boundary vertex or an inner vertex
Definition at line 264 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_facets, FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_vertices, FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_facets(), and FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_calc_shortest_edge()
template<typename MeshType_ > virtual void FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_shortest_edge () inline override protected virtual
determines for each vertex whether it is a boundary vertex or an inner vertex
Reimplemented from FEAT::Geometry::MeshDistortion< MeshType_ >.
Definition at line 418 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_comm, FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_root_mesh_node, FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Math::min(), FEAT::Dist::RequestVector::push_back(), FEAT::Dist::RequestVector::reserve(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERT.
_calc_vertex_owners()
template<typename MeshType_ > virtual void FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_vertex_owners () inline protected virtual
determines for each vertex the length of the shortest adjacent edge
Definition at line 497 of file mesh_distortion.hpp.
References FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_comm, FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_root_mesh_node, FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_vertex_owners, FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Math::min(), and FEAT::Dist::Comm::rank().
Referenced by FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_synchronize().
_synchronize()
template<typename MeshType_ > virtual void FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_synchronize () inline override protected virtual
synchronizes the distortion over all processes; is overridden in DistributedMeshDistortion
Reimplemented from FEAT::Geometry::MeshDistortion< MeshType_ >.
Definition at line 522 of file mesh_distortion.hpp.
References FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_vertex_owners(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_comm, FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_root_mesh_node, FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_vertex_owners, FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Dist::RequestVector::push_back(), FEAT::Dist::Comm::rank(), FEAT::Dist::RequestVector::reserve(), FEAT::Dist::RequestVector::wait_any(), and XASSERT.
distort_shortest_edge_local()
template<typename MeshType_ > void FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local (CoordType scale = CoordType(0.1)) inline inherited
Distorts the mesh according to the shortest local edge.
Moves each inner vertex on an arbitrary point on a circle (2D) or sphere (3D) around the original vertex The radius of the circle/sphere is determined by the shortest edge adjacent to the vertex: radius = scale * length_shortest_edge
Parameters
[in] scale factor to scale the length of the shortest edge to determine the radius
Note
This function only moves inner vertices and leaves boundary vertices untouched.
Definition at line 188 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_vertices, FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh, FEAT::Geometry::MeshDistortion< MeshType_ >::_pi_val, FEAT::Geometry::MeshDistortion< MeshType_ >::_rand, FEAT::Geometry::MeshDistortion< MeshType_ >::_shortest_edge, FEAT::Geometry::MeshDistortion< MeshType_ >::_synchronize(), FEAT::Math::cos(), and FEAT::Math::sin().
distort_shortest_edge_uniform()
template<typename MeshType_ > void FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform (CoordType scale = CoordType(0.1)) inline inherited
Distorts the mesh according to the shortest edge.
Moves each inner vertex on an arbitrary point on a circle (2D) or sphere (3D) around the original vertex The radius of the circle/sphere is determined by the shortest edge in the mesh:
radius = scale * shortest_edge
Parameters
[in] scale factor to scale the length of the shortest edge to determine the radius
Note
This function only moves inner vertices and leaves boundary vertices untouched.
Definition at line 167 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::_shortest_edge, and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
distort_uniform()
template<typename MeshType_ > void FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform (CoordType rad) inline inherited
Distorts the mesh uniformly.
Moves each inner vertex on an arbitrary point on a circle (2D) or sphere (3D) around the original vertex
Parameters
[in] rad Radius of the circle or sphere
Note
This function only moves inner vertices and leaves boundary vertices untouched.
Definition at line 111 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_vertices, FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh, FEAT::Geometry::MeshDistortion< MeshType_ >::_pi_val, FEAT::Geometry::MeshDistortion< MeshType_ >::_rand, FEAT::Geometry::MeshDistortion< MeshType_ >::_synchronize(), FEAT::Math::cos(), and FEAT::Math::sin().
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform().
Member Data Documentation
_boundary_facets
template<typename MeshType_ > std::vector<int> FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_facets protected inherited
vector to story which facet is at the boundary
Definition at line 56 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_facets(), and FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices().
_boundary_vertices
template<typename MeshType_ > std::vector<int> FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_vertices protected inherited
vector to store which vertex is at the boundary
Definition at line 54 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_comm
template<typename MeshType_ > const Dist::Comm& FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_comm protected
a reference to our communicator
Definition at line 347 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_vertex_owners(), and FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_synchronize().
_mesh
template<typename MeshType_ > MeshType_& FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh protected inherited
the mesh we want to distort
Definition at line 50 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_pi_val
template<typename MeshType_ > const CoordType FEAT::Geometry::MeshDistortion< MeshType_ >::_pi_val = Math::pi<CoordType>() protected inherited
have a guess...
Definition at line 60 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_rand
template<typename MeshType_ > Random FEAT::Geometry::MeshDistortion< MeshType_ >::_rand protected inherited
random number generator for random distortion
Definition at line 52 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_root_mesh_node
template<typename MeshType_ > RootMeshNodeType& FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_root_mesh_node protected
a reference to our root mesh node
Definition at line 349 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_vertex_owners(), and FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_synchronize().
_shortest_edge
template<typename MeshType_ > std::vector<CoordType> FEAT::Geometry::MeshDistortion< MeshType_ >::_shortest_edge protected inherited
vector to store the length of the shortest edge belonging to each vertex
Definition at line 58 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform().
_vertex_owners
template<typename MeshType_ > std::vector<int> FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_vertex_owners protected
a vector of vertex owner ranks
Definition at line 351 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_vertex_owners(), and FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_synchronize().
facet_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::facet_dim = MeshType::shape_dim - 1 static constexpr
Definition at line 341 of file mesh_distortion.hpp.
shape_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::MeshDistortion< MeshType_ >::shape_dim = MeshType_::shape_dim static constexpr inherited
Definition at line 45 of file mesh_distortion.hpp.
world_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::world_dim = MeshType::world_dim static constexpr
Definition at line 340 of file mesh_distortion.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/mesh_distortion.hpp