FEAT: FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > > Class Template Reference
FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > > Class Template Reference
Core class for conversion of BCSR Stokes systems to CSR format for direct solvers.
#include <direct_stokes_solver.hpp>
Public Types
typedef LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ > MatrixTypeA
the type of the matrix block A
typedef LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 > MatrixTypeB
the type of the matrix block B
typedef LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ > MatrixTypeD
the type of the matrix block D
typedef LAFEM::SparseMatrixCSR< DT_, IT_ > MatrixTypeS
the type of the matrix block S
typedef LAFEM::NoneFilter< DT_, IT_ > NoneFilterTypeP
the none filter type for the pressure
typedef LAFEM::NoneFilterBlocked< DT_, IT_, dim_ > NoneFilterTypeV
the none filter type for the velocity
typedef LAFEM::SlipFilter< DT_, IT_, dim_ > SlipFilterTypeV
the slip filter type for the velocity
typedef SolverDT_ SolverDataType
the data type to be used by the solver
typedef LAFEM::NoneFilter< SolverDataType, SolverIndexType > SolverFilterType
the solver filter type
typedef SolverIT_ SolverIndexType
the index type to be used by the solver
typedef LAFEM::SparseMatrixCSR< SolverDataType, SolverIndexType > SolverMatrixType
the solver matrix type
typedef LAFEM::DenseVector< SolverDataType, SolverIndexType > SolverVectorType
the solver vector type
typedef LAFEM::UnitFilter< DT_, IT_ > UnitFilterTypeP
the unit filter type for the pressure
typedef LAFEM::UnitFilterBlocked< DT_, IT_, dim_ > UnitFilterTypeV
the unit filter type for the velocity
typedef LAFEM::DenseVector< DT_, IT_ > VectorTypeP
the type of the pressure vector
typedef LAFEM::DenseVectorBlocked< DT_, IT_, dim_ > VectorTypeV
the type of the velocity vector
Public Member Functions
DirectStokesCore (const DirectStokesCore &)=delete
no copy allowed
DirectStokesCore (const MatrixTypeA &matrix_a, const MatrixTypeB &matrix_b, const MatrixTypeD &matrix_d, const MatrixTypeS *matrix_s=nullptr)
Constructor.
virtual ~DirectStokesCore ()
virtual destructor
SolverVectorType create_solver_vector () const
Creates a new solver vector, whose contents are left uninitialized.
virtual void done_numeric ()
Releases all data allocated during numerical initialization.
virtual void done_symbolic ()
Releases all data allocated during symbolic initialization.
virtual void download_vector (const SolverVectorType &vector, VectorTypeV &vector_v, VectorTypeP &vector_p) const
Downloads a velocity/pressure vector pair from a solver vector.
const SolverFilterType & get_solver_filter () const
Returns a const reference to the solver filter, which is always an empty NoneFilter.
const SolverMatrixType & get_solver_matrix () const
Returns a const reference to the solver matrix.
virtual void init_numeric ()
Performs the numeric initialization.
virtual void init_symbolic ()
Performs the symbolic initialization.
DirectStokesCore & operator= (const DirectStokesCore &)=delete
no copy allowed
template<typename FilterV_ , typename FilterP_ >
void set_filters (const LAFEM::TupleFilter< FilterV_, FilterP_ > &filter)
Sets the velocity and pressure filters.
void set_need_main_diagonal (bool need_it)
Specifies whether the solver matrix needs to contain all main diagonal entries.
template<typename FilterV_ , typename FilterP_ >
void update_filters (const LAFEM::TupleFilter< FilterV_, FilterP_ > &filter)
Updates the velocity and pressure filters.
virtual void upload_vector (SolverVectorType &vector, const VectorTypeV &vector_v, const VectorTypeP &vector_p) const
Uploads a velocity/pressure vector pair to a solver vector.
Protected Types
typedef std::array< std::size_t, 3u > FilterUpdateCounter
type for filter counting
Protected Member Functions
template<typename LocFilter_ , typename Mirror_ >
void _add_filter_pres (const Global::Filter< LocFilter_, Mirror_ > &filter, FilterUpdateCounter *fuc)
adds or updates a global pressure filter
void _add_filter_pres (const Global::MeanFilter< DT_, IT_ > &filter, FilterUpdateCounter *fuc)
adds or updates a pressure mean filter
template<typename First_ >
void _add_filter_pres (const LAFEM::FilterChain< First_ > &filter, FilterUpdateCounter *fuc)
adds or updates a pressure filter chain
template<typename First_ , typename Second_ , typename... Rest_>
void _add_filter_pres (const LAFEM::FilterChain< First_, Second_, Rest_... > &filter, FilterUpdateCounter *fuc)
adds or updates a pressure filter chain
template<typename SubFilter_ >
void _add_filter_pres (const LAFEM::FilterSequence< SubFilter_ > &filter, FilterUpdateCounter *fuc)
adds or updates a pressure filter sequence
void _add_filter_pres (const LAFEM::MeanFilter< DT_, IT_ > &filter, FilterUpdateCounter *fuc)
adds or updates a pressure mean filter
void _add_filter_pres (const NoneFilterTypeP &, FilterUpdateCounter *)
adds or updates a pressure none filter (dummy function)
void _add_filter_pres (const UnitFilterTypeP &filter, FilterUpdateCounter *fuc)
adds or updates a pressure unit filter
template<typename LocFilter_ , typename Mirror_ >
void _add_filter_velo (const Global::Filter< LocFilter_, Mirror_ > &filter, FilterUpdateCounter *fuc)
adds or updates a global velocity filter
template<typename First_ >
void _add_filter_velo (const LAFEM::FilterChain< First_ > &filter, FilterUpdateCounter *fuc)
adds or updates a velocity filter chain
template<typename First_ , typename Second_ , typename... Rest_>
void _add_filter_velo (const LAFEM::FilterChain< First_, Second_, Rest_... > &filter, FilterUpdateCounter *fuc)
adds or updates a velocity filter chain
template<typename SubFilter_ >
void _add_filter_velo (const LAFEM::FilterSequence< SubFilter_ > &filter, FilterUpdateCounter *fuc)
adds or updates a velocity filter sequence
void _add_filter_velo (const NoneFilterTypeV &, FilterUpdateCounter *)
adds or updates a velocity none filter (dummy function)
void _add_filter_velo (const SlipFilterTypeV &filter, FilterUpdateCounter *fuc)
adds or updates a velocity slip filter
void _add_filter_velo (const UnitFilterTypeV &filter, FilterUpdateCounter *fuc)
adds or updates a velocity unit filter
IT_ _compute_slip_matrix_layout ()
computes the slip matrix layout Q^T and returns the total number of slip DOFs
void _compute_unit_mask_p ()
computes the pressure unit filter mask
void _compute_unit_mask_v ()
computes the velocity unit filter mask
Protected Attributes
bool _filters_already_set = false
have the filters been set yet?
bool _have_mean_filter_p = false
do we have to use the pressure mean filter?
const MatrixTypeA & _matrix_a
reference to matrix block A
const MatrixTypeB & _matrix_b
reference to matrix block B
const MatrixTypeD & _matrix_d
reference to matrix block D
const MatrixTypeS * _matrix_s
pointer to matrix block S (may be nullptr or an empty matrix)
VectorTypeP _mean_filter_p_dual
pressure mean filter (may be nullptr or an empty vector if no pressure mean filter is to be applied)
bool _need_main_diagonal = false
do we need a main diagonal in S?
std::vector< IT_ > _slip_col_idx
std::vector< IT_ > _slip_fil_dqu
std::vector< IT_ > _slip_fil_idx
std::deque< SlipFilterTypeV > _slip_filters_v
deque of velocity slip filters
std::vector< IT_ > _slip_row_ptr
slip filter matrix Q entries
SolverFilterType _solver_filter
the solver filter (a NoneFilter)
SolverMatrixType _solver_matrix
the solver matrix
std::deque< UnitFilterTypeP > _unit_filters_p
deque of pressure unit filters
std::deque< UnitFilterTypeV > _unit_filters_v
deque of velocity unit filters
std::vector< int > _unit_mask_p
std::vector< int > _unit_mask_v
unit filter masks for velocity and pressure
Detailed Description
template<typename SolverDT_, typename SolverIT_, typename DT_, typename IT_, int dim_>
class FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >
Core class for conversion of BCSR Stokes systems to CSR format for direct solvers.
This class can be used to convert a Stokes saddle-point system of the form
\[ \begin{bmatrix} A & B\\D & S \end{bmatrix} \cdot \begin{bmatrix}v\\p\end{bmatrix} = \begin{bmatrix}f\\g\end{bmatrix}\]
consisting of BCSR-matrices A, B and D as well as a scalar matrix S, which is usually an empty matrix, into a scalar CSR system of the form
\[ \begin{bmatrix} \tilde{A} & \tilde{B} & Q & 0\\\tilde{D} & \tilde{S} & 0 & P\\Q^\top & 0 & 0 & 0\\0 & P^\top & 0 & 0 \end{bmatrix} \cdot \begin{bmatrix}v\\p\\q\\\lambda\end{bmatrix} = \begin{bmatrix}f\\g\\0\\0\end{bmatrix}\]
where
\(\tilde{A}\) corresponds to the matrix block A, which has been filtered by all velocity unit filters, i.e. each row that corresponds to a velocity unit filter DOF has been replaced by a unit row.
\(\tilde{B}\) corresponds to the matrix block B, which has been off-diagonally filtered by all velocity unit filters, i.e. each row that corresponds to a velocity unit filter DOF has been replaced by an empty row.
\(\tilde{D}\) corresponds to the matrix block D, which has been off-diagonally filtered by all pressure unit filters, i.e. each row that corresponds to a pressure unit filter DOF has been replaced by an empty row.
\(\tilde{S}\) corresponds to the matrix block S, which has been filtered by all pressure unit filters, i.e. each row that corresponds to a pressure unit filter DOF has been replaced by a unit row.
Q corresponds to the nv-by-nq Lagrange multiplier matrices arising from the velocity slip filters, where nv denotes the total number of (scalar) velocity DOFs and nq denotes the total number of (blocked) velocity slip filter DOFs.
P corresponds to the np-by-1 Lagrange multiplier vector arising from the pressure mean filter, where np denoted the total number of pressure DOFs
q is the (vector-valued) Lagrange multiplier for the velocity slip boundary conditions. Note that the equation for this unknown only exists if there exists at least one non-empty velocity slip filter.
\(\lambda\) is the scalar Lagrange multiplier for the pressure mean filter. Note that the equation for this unknown only exists if there exists a non-empty pressure mean filter.
This class is capable of handling and incorporating the following filters into the system:
velocity unit filters for the incorporation of inflow and no-flow (aka no-slip) boundary conditions
velocity slip filters for the incorporation of slip boundary conditions
pressure unit filters for the incorporation of pressure Dirichlet conditions (rarely used)
pressure mean filters for the incorporation of vanishing pressure integral mean condition
Note
The existence of pressure unit filters and a pressure mean filter are mutually exclusive, because they both aim at resolving the issue of singular pressure in the case of a "no-outflow" system. However, this class does not explicitly check for this mutual exclusivity.
The primary use case of this class is as an internal class for the DirectStokesSolver implementations, however, this class may also be used stand-alone, if one desires to do so. If you intend to use this class directly, then the following points are important to remember:
Before you call the init_symbolic() function, you have to ensure that (at least) the layouts of all matrices are initialized and that the velocity/pressure filters have also been initialized and set by calling the set_filters() function.
If the values of the velocity and/or pressure unit/slip filters change after the symbolic initialization has been performed, you have to update the filter contents by calling the update_filters() function before performing the numerical initialization by calling the init_numeric() function. Note that there is no harm in always updating the filters prior to a init_numeric() call, even if it is redundant.
Attention
As explained above, this class incorporates all boundary conditions and constraints, which are given by filters, directly into the solver system, and as a direct consequence of this fact, the filter layouts are not allowed to change between symbolic and numeric initialization! This means: if the indices of the velocity/pressure DOFs, which are affected by unit or slip filters, change after symbolic initialization, then you must re-perform the the symbolic initialization – it is not sufficient to only re-perform the numeric initialization in this case!
Template Parameters
SolverDT_ The desired data type of the direct solver; this is usually double.
SolverIT_ The desired index type of the direct solver
Author
Peter Zajac
Definition at line 119 of file direct_stokes_solver.hpp.
Member Typedef Documentation
FilterUpdateCounter
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef std::array<std::size_t, 3u> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::FilterUpdateCounter protected
type for filter counting
Definition at line 207 of file direct_stokes_solver.hpp.
MatrixTypeA
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::SparseMatrixBCSR<DT_, IT_, dim_, dim_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::MatrixTypeA
the type of the matrix block A
Definition at line 128 of file direct_stokes_solver.hpp.
MatrixTypeB
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::SparseMatrixBCSR<DT_, IT_, dim_, 1> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::MatrixTypeB
the type of the matrix block B
Definition at line 130 of file direct_stokes_solver.hpp.
MatrixTypeD
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::SparseMatrixBCSR<DT_, IT_, 1, dim_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::MatrixTypeD
the type of the matrix block D
Definition at line 132 of file direct_stokes_solver.hpp.
MatrixTypeS
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::SparseMatrixCSR<DT_, IT_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::MatrixTypeS
the type of the matrix block S
Definition at line 134 of file direct_stokes_solver.hpp.
NoneFilterTypeP
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::NoneFilter<DT_, IT_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::NoneFilterTypeP
the none filter type for the pressure
Definition at line 153 of file direct_stokes_solver.hpp.
NoneFilterTypeV
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::NoneFilterBlocked<DT_, IT_, dim_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::NoneFilterTypeV
the none filter type for the velocity
Definition at line 146 of file direct_stokes_solver.hpp.
SlipFilterTypeV
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::SlipFilter<DT_, IT_, dim_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::SlipFilterTypeV
the slip filter type for the velocity
Definition at line 144 of file direct_stokes_solver.hpp.
SolverDataType
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef SolverDT_ FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::SolverDataType
the data type to be used by the solver
Definition at line 156 of file direct_stokes_solver.hpp.
SolverFilterType
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::NoneFilter<SolverDataType, SolverIndexType> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::SolverFilterType
the solver filter type
Definition at line 165 of file direct_stokes_solver.hpp.
SolverIndexType
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef SolverIT_ FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::SolverIndexType
the index type to be used by the solver
Definition at line 158 of file direct_stokes_solver.hpp.
SolverMatrixType
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::SparseMatrixCSR<SolverDataType, SolverIndexType> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::SolverMatrixType
the solver matrix type
Definition at line 161 of file direct_stokes_solver.hpp.
SolverVectorType
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::DenseVector<SolverDataType, SolverIndexType> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::SolverVectorType
the solver vector type
Definition at line 163 of file direct_stokes_solver.hpp.
UnitFilterTypeP
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::UnitFilter<DT_, IT_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::UnitFilterTypeP
the unit filter type for the pressure
Definition at line 149 of file direct_stokes_solver.hpp.
UnitFilterTypeV
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::UnitFilterBlocked<DT_, IT_, dim_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::UnitFilterTypeV
the unit filter type for the velocity
Definition at line 142 of file direct_stokes_solver.hpp.
VectorTypeP
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::DenseVector<DT_, IT_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::VectorTypeP
the type of the pressure vector
Definition at line 139 of file direct_stokes_solver.hpp.
VectorTypeV
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> typedef LAFEM::DenseVectorBlocked<DT_, IT_, dim_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::VectorTypeV
the type of the velocity vector
Definition at line 137 of file direct_stokes_solver.hpp.
Constructor & Destructor Documentation
DirectStokesCore()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::DirectStokesCore (const MatrixTypeA & matrix_a, const MatrixTypeB & matrix_b, const MatrixTypeD & matrix_d, const MatrixTypeS * matrix_s = nullptr) inline explicit
Constructor.
This constructor sets the references to the sub-matrices. Note that the matrices do not need to be initialized when this constructor is called.
Parameters
[in] matrix_a,matrix_b,matrix_d The resident references to the matrix blocks A, B and D.
[in] matrix_s A resident pointer to the matrix block S. This may be set to nullptr if the S block is empty, which is the usual case.
Definition at line 223 of file direct_stokes_solver.hpp.
~DirectStokesCore()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> virtual FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::~DirectStokesCore () inline virtual
virtual destructor
Definition at line 233 of file direct_stokes_solver.hpp.
Member Function Documentation
_add_filter_pres() [1/8]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename LocFilter_ , typename Mirror_ > void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres (const Global::Filter< LocFilter_, Mirror_ > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a global pressure filter
Definition at line 931 of file direct_stokes_solver.hpp.
_add_filter_pres() [2/8]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres (const Global::MeanFilter< DT_, IT_ > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a pressure mean filter
Definition at line 889 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::Shallow, and XASSERTM.
_add_filter_pres() [3/8]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename First_ > void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres (const LAFEM::FilterChain< First_ > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a pressure filter chain
Definition at line 906 of file direct_stokes_solver.hpp.
_add_filter_pres() [4/8]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename First_ , typename Second_ , typename... Rest_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres (const LAFEM::FilterChain< First_, Second_, Rest_... > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a pressure filter chain
Definition at line 913 of file direct_stokes_solver.hpp.
_add_filter_pres() [5/8]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename SubFilter_ > void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres (const LAFEM::FilterSequence< SubFilter_ > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a pressure filter sequence
Definition at line 921 of file direct_stokes_solver.hpp.
_add_filter_pres() [6/8]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres (const LAFEM::MeanFilter< DT_, IT_ > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a pressure mean filter
Definition at line 879 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::Shallow, and XASSERTM.
_add_filter_pres() [7/8]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres (const NoneFilterTypeP & , FilterUpdateCounter *) inline protected
adds or updates a pressure none filter (dummy function)
Definition at line 899 of file direct_stokes_solver.hpp.
_add_filter_pres() [8/8]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres (const UnitFilterTypeP & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a pressure unit filter
Definition at line 858 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::clone(), FEAT::LAFEM::Shallow, and XABORTM.
_add_filter_velo() [1/7]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename LocFilter_ , typename Mirror_ > void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo (const Global::Filter< LocFilter_, Mirror_ > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a global velocity filter
Definition at line 852 of file direct_stokes_solver.hpp.
_add_filter_velo() [2/7]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename First_ > void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo (const LAFEM::FilterChain< First_ > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a velocity filter chain
Definition at line 827 of file direct_stokes_solver.hpp.
_add_filter_velo() [3/7]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename First_ , typename Second_ , typename... Rest_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo (const LAFEM::FilterChain< First_, Second_, Rest_... > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a velocity filter chain
Definition at line 834 of file direct_stokes_solver.hpp.
_add_filter_velo() [4/7]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename SubFilter_ > void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo (const LAFEM::FilterSequence< SubFilter_ > & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a velocity filter sequence
Definition at line 842 of file direct_stokes_solver.hpp.
_add_filter_velo() [5/7]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo (const NoneFilterTypeV & , FilterUpdateCounter *) inline protected
adds or updates a velocity none filter (dummy function)
Definition at line 820 of file direct_stokes_solver.hpp.
_add_filter_velo() [6/7]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo (const SlipFilterTypeV & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a velocity slip filter
Definition at line 798 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::SlipFilter< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::Shallow, and XABORTM.
_add_filter_velo() [7/7]
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_velo (const UnitFilterTypeV & filter, FilterUpdateCounter * fuc) inline protected
adds or updates a velocity unit filter
Definition at line 776 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::Shallow, and XABORTM.
_compute_slip_matrix_layout()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> IT_ FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_compute_slip_matrix_layout () inline protected
computes the slip matrix layout Q^T and returns the total number of slip DOFs
Definition at line 937 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), and XASSERT.
_compute_unit_mask_p()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_compute_unit_mask_p () inline protected
computes the pressure unit filter mask
Definition at line 1019 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows().
_compute_unit_mask_v()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_compute_unit_mask_v () inline protected
computes the velocity unit filter mask
Definition at line 1003 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows().
create_solver_vector()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> SolverVectorType FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::create_solver_vector () const inline
Creates a new solver vector, whose contents are left uninitialized.
Definition at line 273 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_r().
done_numeric()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> virtual void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_numeric () inline virtual
Releases all data allocated during numerical initialization.
Definition at line 746 of file direct_stokes_solver.hpp.
done_symbolic()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> virtual void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic () inline virtual
Releases all data allocated during symbolic initialization.
This function also clears all internal filter structures, i.e. the filters have to be set again manually by calling the set_filters() function before another call to init_symoblic() can be performed.
Definition at line 758 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clear().
download_vector()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> virtual void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector (const SolverVectorType & vector, VectorTypeV & vector_v, VectorTypeP & vector_p) const inline virtual
Downloads a velocity/pressure vector pair from a solver vector.
Parameters
[in] vector A transient reference to the solver vector that provides the download.
[in,out] vector_v,vector_p The transient references to the velocity/pressure vectors that receive the downloaded data.
Definition at line 320 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
get_solver_filter()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> const SolverFilterType & FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::get_solver_filter () const inline
Returns a const reference to the solver filter, which is always an empty NoneFilter.
Definition at line 265 of file direct_stokes_solver.hpp.
get_solver_matrix()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> const SolverMatrixType & FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::get_solver_matrix () const inline
Returns a const reference to the solver matrix.
Definition at line 257 of file direct_stokes_solver.hpp.
init_numeric()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> virtual void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_numeric () inline virtual
Performs the numeric initialization.
This function computes the numerical entries of the solver matrix.
Definition at line 601 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and XASSERT.
init_symbolic()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> virtual void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic () inline virtual
Performs the symbolic initialization.
This function computes the sparsity pattern of the solver matrix.
Definition at line 382 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and XASSERT.
set_filters()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename FilterV_ , typename FilterP_ > void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::set_filters (const LAFEM::TupleFilter< FilterV_, FilterP_ > & filter) inline
Sets the velocity and pressure filters.
This function must be called before init_symbolic() and all filter layouts must already have been assembled.
Parameters
[in] filter A resident reference to the filter pair.
Definition at line 351 of file direct_stokes_solver.hpp.
References XASSERTM.
set_need_main_diagonal()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::set_need_main_diagonal (bool need_it) inline
Specifies whether the solver matrix needs to contain all main diagonal entries.
Parameters
[in] need_main_diagonal Specifies whether the solver matrix structure should always contain all main diagonal entries. This is required by some solvers, e.g. by the MKL DSS solver.
Definition at line 249 of file direct_stokes_solver.hpp.
update_filters()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> template<typename FilterV_ , typename FilterP_ > void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::update_filters (const LAFEM::TupleFilter< FilterV_, FilterP_ > & filter) inline
Updates the velocity and pressure filters.
This function can be called between init_symoblic() and init_numeric() if the filters have been reassembled. Note that only the values of the filters are allowed to change, but their layouts must remain unchanged!
Parameters
[in] filter A resident reference to the filter pair.
Definition at line 369 of file direct_stokes_solver.hpp.
References XASSERTM.
upload_vector()
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> virtual void FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector (SolverVectorType & vector, const VectorTypeV & vector_v, const VectorTypeP & vector_p) const inline virtual
Uploads a velocity/pressure vector pair to a solver vector.
Parameters
[in,out] vector A transient reference to the solver vector that receives the uploaded data.
[in] vector_v,vector_p The transient references to the velocity/pressure vectors that are to be uploaded.
Definition at line 287 of file direct_stokes_solver.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
Member Data Documentation
_filters_already_set
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> bool FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_filters_already_set = false protected
have the filters been set yet?
Definition at line 192 of file direct_stokes_solver.hpp.
_have_mean_filter_p
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> bool FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_have_mean_filter_p = false protected
do we have to use the pressure mean filter?
Definition at line 195 of file direct_stokes_solver.hpp.
_matrix_a
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> const MatrixTypeA& FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_matrix_a protected
reference to matrix block A
Definition at line 169 of file direct_stokes_solver.hpp.
_matrix_b
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> const MatrixTypeB& FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_matrix_b protected
reference to matrix block B
Definition at line 171 of file direct_stokes_solver.hpp.
_matrix_d
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> const MatrixTypeD& FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_matrix_d protected
reference to matrix block D
Definition at line 173 of file direct_stokes_solver.hpp.
_matrix_s
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> const MatrixTypeS* FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_matrix_s protected
pointer to matrix block S (may be nullptr or an empty matrix)
Definition at line 175 of file direct_stokes_solver.hpp.
_mean_filter_p_dual
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> VectorTypeP FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_mean_filter_p_dual protected
pressure mean filter (may be nullptr or an empty vector if no pressure mean filter is to be applied)
Definition at line 189 of file direct_stokes_solver.hpp.
_need_main_diagonal
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> bool FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_need_main_diagonal = false protected
do we need a main diagonal in S?
Definition at line 198 of file direct_stokes_solver.hpp.
_slip_col_idx
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::vector<IT_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_slip_col_idx protected
Definition at line 204 of file direct_stokes_solver.hpp.
_slip_fil_dqu
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::vector<IT_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_slip_fil_dqu protected
Definition at line 204 of file direct_stokes_solver.hpp.
_slip_fil_idx
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::vector<IT_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_slip_fil_idx protected
Definition at line 204 of file direct_stokes_solver.hpp.
_slip_filters_v
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::deque<SlipFilterTypeV> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_slip_filters_v protected
deque of velocity slip filters
Definition at line 183 of file direct_stokes_solver.hpp.
_slip_row_ptr
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::vector<IT_> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_slip_row_ptr protected
slip filter matrix Q entries
Definition at line 204 of file direct_stokes_solver.hpp.
_solver_filter
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> SolverFilterType FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_solver_filter protected
the solver filter (a NoneFilter)
Definition at line 180 of file direct_stokes_solver.hpp.
_solver_matrix
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> SolverMatrixType FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_solver_matrix protected
the solver matrix
Definition at line 178 of file direct_stokes_solver.hpp.
_unit_filters_p
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::deque<UnitFilterTypeP> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_unit_filters_p protected
deque of pressure unit filters
Definition at line 187 of file direct_stokes_solver.hpp.
_unit_filters_v
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::deque<UnitFilterTypeV> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_unit_filters_v protected
deque of velocity unit filters
Definition at line 185 of file direct_stokes_solver.hpp.
_unit_mask_p
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::vector<int> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_unit_mask_p protected
Definition at line 201 of file direct_stokes_solver.hpp.
_unit_mask_v
template<typename SolverDT_ , typename SolverIT_ , typename DT_ , typename IT_ , int dim_> std::vector<int> FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_unit_mask_v protected
unit filter masks for velocity and pressure
Definition at line 201 of file direct_stokes_solver.hpp.
The documentation for this class was generated from the following file:
kernel/solver/direct_stokes_solver.hpp