FEAT: FEAT::Space::Discontinuous::Element< Trafo_, Variant_ > Class Template Reference
FEAT::Space::Discontinuous::Element< Trafo_, Variant_ > Class Template Reference
Discontinuous Finite-Element space class template.
#include <element.hpp>
Classes
class DofAssignment
Dof-Assignment class wrapper template.
class Evaluator
Space evaluator class wrapper template.
class NodeFunctional
Node-Functional class wrapper template.
Public Types
typedef ElementBase< Trafo_ > BaseClass
base-class typedef
typedef DofMappingSingleEntity< Element, 0, num_local_dofs > DofMappingType
Dof-Mapping class.
typedef TrafoType::MeshType MeshType
mesh type
typedef TrafoType::ShapeType ShapeType
shape type
typedef Trafo_ TrafoType
transformation type
typedef Variant_ VariantTag
variant of the element
Public Member Functions
Element (TrafoType &trafo)
Constructor.
virtual ~Element ()
virtual destructor
MeshType & get_mesh ()
Returns a reference to the underlying mesh.
const MeshType & get_mesh () const
Returns a reference to the underlying mesh.
Index get_num_dofs () const
Returns the number of dofs.
TrafoType & get_trafo ()
Returns a reference to the trafo.
const TrafoType & get_trafo () const
Returns a reference to the trafo.
String name () const
Returns the name of the element.
bool operator== (const ElementBase &other) const
Comparison operator.
Static Public Member Functions
static String name ()
Returns the name of the element.
Static Public Attributes
static constexpr bool have_node_func = true
node functionals available
static constexpr int local_degree = VariantTag::local_degree
Local Polynomial degree count.
static constexpr int num_local_dofs = DofTraits<DofTag<ShapeType, VariantTag>, ShapeType::dimension>::count
number of local dofs
static constexpr int shape_dim = ShapeType::dimension
shape dimension
static constexpr int world_dim = MeshType::world_dim
our image/world dimension
Protected Attributes
TrafoType & _trafo
transformation reference
Detailed Description
template<typename Trafo_, typename Variant_ = Variant::StdPolyP<0>>
class FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >
Discontinuous Finite-Element space class template.
Template Parameters
Trafo_ The transformation that is to be used by this space.
Author
Peter Zajac
Definition at line 38 of file element.hpp.
Member Typedef Documentation
BaseClass
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> typedef ElementBase<Trafo_> FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::BaseClass
base-class typedef
Definition at line 43 of file element.hpp.
DofMappingType
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> typedef DofMappingSingleEntity<Element, 0, num_local_dofs> FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::DofMappingType
Dof-Mapping class.
Definition at line 81 of file element.hpp.
MeshType
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> typedef TrafoType::MeshType FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::MeshType
mesh type
Definition at line 47 of file element.hpp.
ShapeType
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> typedef TrafoType::ShapeType FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::ShapeType
shape type
Definition at line 49 of file element.hpp.
TrafoType
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> typedef Trafo_ FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::TrafoType
transformation type
Definition at line 45 of file element.hpp.
VariantTag
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> typedef Variant_ FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::VariantTag
variant of the element
Definition at line 51 of file element.hpp.
Constructor & Destructor Documentation
Element()
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::Element (TrafoType & trafo) inline explicit
Constructor.
Parameters
[in] trafo A resident reference to the transformation which is to be used by this space.
Definition at line 117 of file element.hpp.
~Element()
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> virtual FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::~Element () inline virtual
virtual destructor
Definition at line 123 of file element.hpp.
Member Function Documentation
get_mesh() [1/2]
template<typename Trafo_ > MeshType & FEAT::Space::ElementBase< Trafo_ >::get_mesh () inline inherited
Returns a reference to the underlying mesh.
Returns
A (const) reference to the mesh used by this space.
Definition at line 192 of file element_base.hpp.
References FEAT::Space::ElementBase< Trafo_ >::get_trafo().
Referenced by FEAT::Space::Argyris::Element< Trafo_ >::get_num_dofs(), FEAT::Space::BognerFoxSchmit::Element< Trafo_ >::get_num_dofs(), FEAT::Space::CaiDouSanSheYe::Element< Trafo_ >::get_num_dofs(), FEAT::Space::CroRavRanTur::Element< Trafo_ >::get_num_dofs(), FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::get_num_dofs(), FEAT::Space::Hermite3::Element< Trafo_ >::get_num_dofs(), FEAT::Space::Lagrange1::Element< Trafo_ >::get_num_dofs(), and FEAT::Space::Q1TBNP::Element< Trafo_ >::get_num_dofs().
get_mesh() [2/2]
template<typename Trafo_ > const MeshType & FEAT::Space::ElementBase< Trafo_ >::get_mesh () const inline inherited
Returns a reference to the underlying mesh.
Returns
A (const) reference to the mesh used by this space.
Definition at line 198 of file element_base.hpp.
References FEAT::Space::ElementBase< Trafo_ >::get_trafo().
get_num_dofs()
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> Index FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::get_num_dofs () const inline
Returns the number of dofs.
Returns
The total number of global degrees of freedom for the patch.
Definition at line 128 of file element.hpp.
References FEAT::Space::ElementBase< Trafo_ >::get_mesh(), and FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::num_local_dofs.
get_trafo() [1/2]
template<typename Trafo_ > TrafoType & FEAT::Space::ElementBase< Trafo_ >::get_trafo () inline inherited
Returns a reference to the trafo.
Returns
A (const) reference to the transformation used by this space.
Definition at line 175 of file element_base.hpp.
References FEAT::Space::ElementBase< Trafo_ >::_trafo.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble(), FEAT::Space::ElementBase< Trafo_ >::get_mesh(), FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ >::recurse(), and FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, 0 >::recurse().
get_trafo() [2/2]
template<typename Trafo_ > const TrafoType & FEAT::Space::ElementBase< Trafo_ >::get_trafo () const inline inherited
Returns a reference to the trafo.
Returns
A (const) reference to the transformation used by this space.
Definition at line 181 of file element_base.hpp.
References FEAT::Space::ElementBase< Trafo_ >::_trafo.
name()
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> static String FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::name () inline static
Returns the name of the element.
Definition at line 135 of file element.hpp.
operator==()
template<typename Trafo_ > bool FEAT::Space::ElementBase< Trafo_ >::operator== (const ElementBase< Trafo_ > & other) const inline inherited
Comparison operator.
This operator checks whether two element objects are equal.
Returns
true, if this this and other name the same object, otherwise false.
Definition at line 211 of file element_base.hpp.
Member Data Documentation
_trafo
template<typename Trafo_ > TrafoType& FEAT::Space::ElementBase< Trafo_ >::_trafo protected inherited
transformation reference
Definition at line 153 of file element_base.hpp.
Referenced by FEAT::Space::ElementBase< Trafo_ >::get_trafo().
have_node_func
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> constexpr bool FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::have_node_func = true static constexpr
node functionals available
Definition at line 54 of file element.hpp.
local_degree
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> constexpr int FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::local_degree = VariantTag::local_degree static constexpr
Local Polynomial degree count.
This constant describes the maximum local polynomial degree of the element. This may be used, e.g. for automated determination of appropriate cubature rules.
Please note that for Simplex elements, 'degree' refers to the P_k spaces, whereas for Hypercube elements, 'degree' refers to the Q_k spaces.
Definition at line 57 of file element.hpp.
num_local_dofs
template<typename Trafo_ , typename Variant_ = Variant::StdPolyP<0>> constexpr int FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::num_local_dofs = DofTraits<DofTag<ShapeType, VariantTag>, ShapeType::dimension>::count static constexpr
number of local dofs
Definition at line 60 of file element.hpp.
Referenced by FEAT::Space::Discontinuous::Element< Trafo_, Variant_ >::get_num_dofs().
shape_dim
template<typename Trafo_ > constexpr int FEAT::Space::ElementBase< Trafo_ >::shape_dim = ShapeType::dimension static constexpr inherited
shape dimension
Definition at line 37 of file element_base.hpp.
world_dim
template<typename Trafo_ > constexpr int FEAT::Space::ElementBase< Trafo_ >::world_dim = MeshType::world_dim static constexpr inherited
our image/world dimension
Definition at line 39 of file element_base.hpp.
The documentation for this class was generated from the following file:
kernel/space/discontinuous/element.hpp