FEAT: FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ > Class Template Reference
FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ > Class Template Reference abstract
Public Types
typedef PartType::AttributeSetType AttributeSetType
attribute type of our mesh-part
typedef ChartCRTP< Extrude< Mesh_, SubChart_ >, Mesh_, ExtrudeTraits< SubChart_ > > BaseClass
The CRTP base class.
typedef BaseClass::CoordType CoordType
Floating point type.
typedef BaseClass::MeshType MeshType
mesh type
typedef BaseClass::ParamPoint ParamPoint
Vector type for parametrization points, aka domain points.
typedef BaseClass::PartType PartType
mesh-part type
typedef SubChart_::ParamPoint SubParamPoint
typedef SubChart_::WorldPoint SubWorldPoint
typedef ExtrudeTraits< SubChart_ > TraitsType
traits type
typedef MeshType::VertexSetType VertexSetType
vertex set type of our mesh
typedef BaseClass::WorldPoint WorldPoint
Vector type for world points, aka image points.
Public Member Functions
Extrude (std::unique_ptr< SubChart_ > sub_chart)
virtual void adapt (MeshType &mesh, const PartType &part) const override
Adapts a whole MeshPart.
virtual void adapt (PartType &parent_meshpart, const PartType &meshpart) const override
Adapts a whole MeshPart referring to another MeshPart.
virtual std::size_t bytes () const
virtual bool can_explicit () const override
virtual bool can_implicit () const override
CoordType compute_dist (const WorldPoint &point) const
Computes the distance of a point to this chart.
CoordType compute_dist (const WorldPoint &point, WorldPoint &grad_dist) const
Computes the distance of a point to this chart.
CoordType compute_signed_dist (const WorldPoint &point) const
Computes the signed distance of a point to this chart.
CoordType compute_signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const
Computes the signed distance of a point to this chart.
virtual CoordType dist (const WorldPoint &point) const override
virtual CoordType dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual String get_type () const override
Writes the type as String.
virtual WorldPoint map (const WorldPoint &param) const override
void map_param (WorldPoint &point, const ParamPoint &param) const
virtual WorldPoint project (const WorldPoint &point) const override
void project_meshpart (Mesh_ &mesh, const MeshPart< Mesh_ > &meshpart) const
void project_point (WorldPoint &point) const
void set_angles (CoordType yaw, CoordType pitch, CoordType roll)
void set_offset (CoordType x, CoordType y, CoordType z)
void set_origin (CoordType x, CoordType y)
void set_sub_chart (std::unique_ptr< SubChart_ > sub_chart)
virtual CoordType signed_dist (const WorldPoint &point) const override
virtual CoordType signed_dist (const WorldPoint &point, WorldPoint &grad_dist) const override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset) override
virtual void transform (const WorldPoint &origin, const WorldPoint &angles, const WorldPoint &offset)=0
Applies a "proper rigid" transformation onto the chart.
void transform_2d_to_3d (WorldPoint &p, const SubWorldPoint &q, const CoordType z=CoordType(0)) const
void transform_3d_to_2d (const WorldPoint &p, SubWorldPoint &q) const
void transform_3d_to_2d (const WorldPoint &p, SubWorldPoint &q, CoordType &z) const
virtual void write (std::ostream &os, const String &sindent) const override
Writes the Chart into a stream in XML format.
Public Attributes
std::unique_ptr< SubChart_ > _sub_chart
our sub-chart object
Static Public Attributes
static constexpr bool is_explicit
specifies whether this chart is explicit
static constexpr bool is_implicit
specifies whether this chart is implicit
static constexpr int param_dim
the parameter dimension of this chart
static constexpr int world_dim
the world dimension of this chart
Protected Member Functions
Extrude< Mesh_, SubChart_ > & cast ()
Casts this to its true type.
const Extrude< Mesh_, SubChart_ > & cast () const
Protected Attributes
Tiny::Vector< CoordType, 3 > _offset
the offset point
Tiny::Vector< CoordType, 2 > _origin
the origin point
Tiny::Matrix< CoordType, 3, 3 > _rotation
the rotation matrix
Detailed Description
template<typename Mesh_, typename SubChart_>
class FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >
Definition at line 33 of file extrude.hpp.
Member Typedef Documentation
AttributeSetType
typedef PartType::AttributeSetType FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::AttributeSetType inherited
attribute type of our mesh-part
Definition at line 365 of file chart.hpp.
BaseClass
template<typename Mesh_ , typename SubChart_ > typedef ChartCRTP<Extrude<Mesh_, SubChart_>, Mesh_, ExtrudeTraits<SubChart_> > FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::BaseClass
The CRTP base class.
Definition at line 38 of file extrude.hpp.
CoordType
template<typename Mesh_ , typename SubChart_ > typedef BaseClass::CoordType FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::CoordType
Floating point type.
Definition at line 40 of file extrude.hpp.
MeshType
typedef BaseClass::MeshType FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::MeshType inherited
mesh type
Definition at line 361 of file chart.hpp.
ParamPoint
template<typename Mesh_ , typename SubChart_ > typedef BaseClass::ParamPoint FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::ParamPoint
Vector type for parametrization points, aka domain points.
Definition at line 44 of file extrude.hpp.
PartType
typedef BaseClass::PartType FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::PartType inherited
mesh-part type
Definition at line 363 of file chart.hpp.
SubParamPoint
template<typename Mesh_ , typename SubChart_ > typedef SubChart_::ParamPoint FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::SubParamPoint
Definition at line 47 of file extrude.hpp.
SubWorldPoint
template<typename Mesh_ , typename SubChart_ > typedef SubChart_::WorldPoint FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::SubWorldPoint
Definition at line 46 of file extrude.hpp.
TraitsType
typedef ExtrudeTraits< SubChart_ > FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::TraitsType inherited
traits type
Definition at line 359 of file chart.hpp.
VertexSetType
typedef MeshType::VertexSetType FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::VertexSetType inherited
vertex set type of our mesh
Definition at line 367 of file chart.hpp.
WorldPoint
template<typename Mesh_ , typename SubChart_ > typedef BaseClass::WorldPoint FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::WorldPoint
Vector type for world points, aka image points.
Definition at line 42 of file extrude.hpp.
Constructor & Destructor Documentation
Extrude() [1/2]
template<typename Mesh_ , typename SubChart_ > FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::Extrude () inline explicit
Definition at line 62 of file extrude.hpp.
Extrude() [2/2]
template<typename Mesh_ , typename SubChart_ > FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::Extrude (std::unique_ptr< SubChart_ > sub_chart) inline explicit
Definition at line 70 of file extrude.hpp.
~Extrude()
template<typename Mesh_ , typename SubChart_ > virtual FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::~Extrude () inline virtual
Definition at line 78 of file extrude.hpp.
Member Function Documentation
adapt() [1/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::adapt (MeshType & mesh, const PartType & part) const inline override virtual inherited
Adapts a whole MeshPart.
Parameters
[in] mesh Mesh to be adapted
[in] part MeshPart identifying the region to be adapted
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 420 of file chart.hpp.
adapt() [2/2]
virtual void FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::adapt (PartType & parent_meshpart, const PartType & meshpart) const inline override virtual inherited
Adapts a whole MeshPart referring to another MeshPart.
Parameters
[in] parent_meshpart MeshPart to be adapted
[in] meshpart MeshPart identifying the region to be adapted
Todo:
: Implement this
There is currently no code that uses MeshParts referring to other MeshParts instead of a RootMesh.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 450 of file chart.hpp.
bytes()
template<typename Mesh_ > virtual std::size_t FEAT::Geometry::Atlas::ChartBase< Mesh_ >::bytes () const inline virtual inherited
Returns
The size of dynamically allocated memory in bytes.
Reimplemented in FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >.
Definition at line 52 of file chart.hpp.
can_explicit()
template<typename Mesh_ , typename SubChart_ > virtual bool FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::can_explicit () const inline override virtual
Reimplemented from FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ >, Mesh_, ExtrudeTraits< SubChart_ > >.
Definition at line 111 of file extrude.hpp.
References FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_sub_chart.
can_implicit()
template<typename Mesh_ , typename SubChart_ > virtual bool FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::can_implicit () const inline override virtual
Reimplemented from FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ >, Mesh_, ExtrudeTraits< SubChart_ > >.
Definition at line 106 of file extrude.hpp.
References FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_sub_chart.
cast() [1/2]
Extrude< Mesh_, SubChart_ > & FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::cast () inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this
Definition at line 393 of file chart.hpp.
cast() [2/2]
const Extrude< Mesh_, SubChart_ > & FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::cast () const inline protected inherited
Casts this to its true type.
Returns
A Derived_ reference to this\ifile "/github/workspace/kernel/geometry/atlas/chart.hpp"
Definition at line 396 of file chart.hpp.
compute_dist() [1/2]
template<typename Mesh_ , typename SubChart_ > CoordType FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::compute_dist (const WorldPoint & point) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 219 of file extrude.hpp.
References FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_sub_chart.
compute_dist() [2/2]
template<typename Mesh_ , typename SubChart_ > CoordType FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::compute_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline
Computes the distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The distance to this chart
Definition at line 228 of file extrude.hpp.
References FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_sub_chart, and ASSERT.
compute_signed_dist() [1/2]
template<typename Mesh_ , typename SubChart_ > CoordType FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::compute_signed_dist (const WorldPoint & point) const inline
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Definition at line 248 of file extrude.hpp.
References FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_sub_chart.
compute_signed_dist() [2/2]
template<typename Mesh_ , typename SubChart_ > CoordType FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::compute_signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline
Computes the signed distance of a point to this chart.
Parameters
[in] point The world point to compute the distance for
Returns
The signed distance to this chart
Definition at line 257 of file extrude.hpp.
References FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_sub_chart.
dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 480 of file chart.hpp.
dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 486 of file chart.hpp.
get_type()
template<typename Mesh_ , typename SubChart_ > virtual String FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::get_type () const inline override virtual
Writes the type as String.
Needed for writing this to mesh files.
Returns
The class name as String.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 274 of file extrude.hpp.
map()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::map (const WorldPoint & param) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 456 of file chart.hpp.
map_param()
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::map_param (WorldPoint & point, const ParamPoint & param) const inline
Definition at line 207 of file extrude.hpp.
project()
virtual WorldPoint FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::project (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 469 of file chart.hpp.
project_meshpart()
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::project_meshpart (Mesh_ & mesh, const MeshPart< Mesh_ > & meshpart) const inline
Definition at line 197 of file extrude.hpp.
project_point()
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::project_point (WorldPoint & point) const inline
Definition at line 185 of file extrude.hpp.
set_angles()
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::set_angles (CoordType yaw, CoordType pitch, CoordType roll) inline
Definition at line 95 of file extrude.hpp.
set_offset()
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::set_offset (CoordType x, CoordType y, CoordType z) inline
Definition at line 88 of file extrude.hpp.
set_origin()
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::set_origin (CoordType x, CoordType y) inline
Definition at line 82 of file extrude.hpp.
set_sub_chart()
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::set_sub_chart (std::unique_ptr< SubChart_ > sub_chart) inline
Definition at line 100 of file extrude.hpp.
signed_dist() [1/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::signed_dist (const WorldPoint & point) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 492 of file chart.hpp.
signed_dist() [2/2]
virtual CoordType FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::signed_dist (const WorldPoint & point, WorldPoint & grad_dist) const inline override virtual inherited
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 498 of file chart.hpp.
transform() [1/2]
template<typename Mesh_ , typename SubChart_ > virtual void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) inline override virtual
Definition at line 147 of file extrude.hpp.
transform() [2/2]
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::ChartBase< Mesh_ >::transform (const WorldPoint & origin, const WorldPoint & angles, const WorldPoint & offset) pure virtual inherited
Applies a "proper rigid" transformation onto the chart.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any point x of the chart:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any point before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): -ignored-
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any point after applying the rotation.
Implemented in FEAT::Geometry::Atlas::CGALSurfaceMesh< Mesh_ >.
transform_2d_to_3d()
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::transform_2d_to_3d (WorldPoint & p, const SubWorldPoint & q, const CoordType z = CoordType(0)) const inline
Definition at line 116 of file extrude.hpp.
transform_3d_to_2d() [1/2]
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::transform_3d_to_2d (const WorldPoint & p, SubWorldPoint & q) const inline
Definition at line 141 of file extrude.hpp.
transform_3d_to_2d() [2/2]
template<typename Mesh_ , typename SubChart_ > void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::transform_3d_to_2d (const WorldPoint & p, SubWorldPoint & q, CoordType & z) const inline
Definition at line 128 of file extrude.hpp.
write()
template<typename Mesh_ , typename SubChart_ > virtual void FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::write (std::ostream & os, const String & sindent) const inline override virtual
Writes the Chart into a stream in XML format.
Parameters
[in,out] os The output stream to write into.
[in] sindent The indentation string.
Implements FEAT::Geometry::Atlas::ChartBase< Mesh_ >.
Definition at line 279 of file extrude.hpp.
References FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_offset, FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_origin, FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_rotation, FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_sub_chart, FEAT::Math::atan2(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid_sqr(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::norm_sub_id_frobenius(), FEAT::Math::pow(), FEAT::Math::sqr(), and FEAT::Math::sqrt().
Member Data Documentation
_offset
template<typename Mesh_ , typename SubChart_ > Tiny::Vector<CoordType, 3> FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_offset protected
the offset point
Definition at line 57 of file extrude.hpp.
Referenced by FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::write().
_origin
template<typename Mesh_ , typename SubChart_ > Tiny::Vector<CoordType, 2> FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_origin protected
the origin point
Definition at line 55 of file extrude.hpp.
Referenced by FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::write().
_rotation
template<typename Mesh_ , typename SubChart_ > Tiny::Matrix<CoordType, 3, 3> FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_rotation protected
the rotation matrix
Definition at line 59 of file extrude.hpp.
Referenced by FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::write().
_sub_chart
template<typename Mesh_ , typename SubChart_ > std::unique_ptr<SubChart_> FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::_sub_chart
our sub-chart object
Definition at line 51 of file extrude.hpp.
Referenced by FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::can_explicit(), FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::can_implicit(), FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::compute_dist(), FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::compute_signed_dist(), and FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::write().
is_explicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::is_explicit static constexpr inherited
specifies whether this chart is explicit
Definition at line 372 of file chart.hpp.
is_implicit
constexpr bool FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::is_implicit static constexpr inherited
specifies whether this chart is implicit
Definition at line 374 of file chart.hpp.
param_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::param_dim static constexpr inherited
the parameter dimension of this chart
Definition at line 379 of file chart.hpp.
world_dim
constexpr int FEAT::Geometry::Atlas::ChartCRTP< Extrude< Mesh_, SubChart_ > , Mesh_, ExtrudeTraits< SubChart_ > >::world_dim static constexpr inherited
the world dimension of this chart
Definition at line 377 of file chart.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/atlas/extrude.hpp