FEAT: FEAT::Assembly::DiscreteCellProjector Class Reference
FEAT::Assembly::DiscreteCellProjector Class Reference
Discrete cell projector class.
#include <discrete_projector.hpp>
Static Public Member Functions
template<typename VectorOut_ , typename VectorIn_ , typename Space_ >
static void project (VectorOut_ &vector, const VectorIn_ &coeff, const Space_ &space)
Projects a discrete function into the cells using the barycentre cubature rule.
template<typename VectorOut_ , typename VectorIn_ , typename Space_ >
static void project (VectorOut_ &vector, const VectorIn_ &coeff, const Space_ &space, const Cubature::DynamicFactory &cubature_factory)
Projects a discrete function into the cells.
template<typename VectorOut_ , typename VectorIn_ , typename Space_ >
static void project (VectorOut_ &vector, const VectorIn_ &coeff, const Space_ &space, const String &cubature_name)
Projects a discrete function into the cells.
template<typename VectorOut_ , typename VectorIn_ , typename Space_ >
static void project_gradient (VectorOut_ &vector, const VectorIn_ &coeff, const Space_ &space, const Cubature::DynamicFactory &cubature_factory)
Projects the gradient of a scalar discrete function into the cells.
template<typename VectorOut_ , typename VectorIn_ , typename Space_ >
static void project_gradient (VectorOut_ &vector, const VectorIn_ &coeff, const Space_ &space, const String &cubature_name)
Projects the gradient of a scalar discrete function into the cells.
template<typename VectorOut_ , typename VectorIn_ , typename Space_ >
static void project_refined (VectorOut_ &vector, const VectorIn_ &coeff, const Space_ &space)
Projects a discrete function into the cells of a once refined mesh.
Detailed Description
Discrete cell projector class.
This class interpolates a discrete finite-element function in the cells of the space's underlying mesh by computing the integral mean over the cell using a cubature rule.
Author
Peter Zajac
Definition at line 354 of file discrete_projector.hpp.
Member Function Documentation
project() [1/3]
template<typename VectorOut_ , typename VectorIn_ , typename Space_ > static void FEAT::Assembly::DiscreteCellProjector::project (VectorOut_ & vector, const VectorIn_ & coeff, const Space_ & space) inline static
Projects a discrete function into the cells using the barycentre cubature rule.
Parameters
[out] vector A transient reference to a vector object that shall receive the cell interpolation of the discrete function.
[in] coeff A transient reference to the coefficient vector of the finite-element function.
[in] space A transient reference to the finite-element space.
Definition at line 373 of file discrete_projector.hpp.
References project().
Referenced by project().
project() [2/3]
template<typename VectorOut_ , typename VectorIn_ , typename Space_ > static void FEAT::Assembly::DiscreteCellProjector::project (VectorOut_ & vector, const VectorIn_ & coeff, const Space_ & space, const Cubature::DynamicFactory & cubature_factory) inline static
Projects a discrete function into the cells.
Parameters
[out] vector A transient reference to a vector object that shall receive the cell interpolation of the discrete function.
[in] coeff A transient reference to the coefficient vector of the finite-element function.
[in] space A transient reference to the finite-element space.
[in] cubature_factory The transient cubature factory that is to be used for integration.
Definition at line 427 of file discrete_projector.hpp.
References FEAT::Tiny::axpy(), and FEAT::value.
project() [3/3]
template<typename VectorOut_ , typename VectorIn_ , typename Space_ > static void FEAT::Assembly::DiscreteCellProjector::project (VectorOut_ & vector, const VectorIn_ & coeff, const Space_ & space, const String & cubature_name) inline static
Projects a discrete function into the cells.
Parameters
[out] vector A transient reference to a vector object that shall receive the cell interpolation of the discrete function.
[in] coeff A transient reference to the coefficient vector of the finite-element function.
[in] space A transient reference to the finite-element space.
[in] cubature_factory The transient cubature factory that is to be used for integration.
Definition at line 401 of file discrete_projector.hpp.
References project().
project_gradient() [1/2]
template<typename VectorOut_ , typename VectorIn_ , typename Space_ > static void FEAT::Assembly::DiscreteCellProjector::project_gradient (VectorOut_ & vector, const VectorIn_ & coeff, const Space_ & space, const Cubature::DynamicFactory & cubature_factory) inline static
Projects the gradient of a scalar discrete function into the cells.
Parameters
[out] vector A transient reference to a vector object that shall receive the cell interpolation of the discrete function.
[in] coeff A transient reference to the coefficient vector of the finite-element function.
[in] space A transient reference to the finite-element space.
[in] cubature_factory The transient cubature factory that is to be used for integration.
Definition at line 595 of file discrete_projector.hpp.
References FEAT::Tiny::axpy(), and FEAT::value.
project_gradient() [2/2]
template<typename VectorOut_ , typename VectorIn_ , typename Space_ > static void FEAT::Assembly::DiscreteCellProjector::project_gradient (VectorOut_ & vector, const VectorIn_ & coeff, const Space_ & space, const String & cubature_name) inline static
Projects the gradient of a scalar discrete function into the cells.
Parameters
[out] vector A transient reference to a vector object that shall receive the cell interpolation of the discrete function's gradient.
[in] coeff A transient reference to the coefficient vector of the finite-element function.
[in] space A transient reference to the finite-element space.
[in] cubature_factory The transient cubature factory that is to be used for integration.
Definition at line 569 of file discrete_projector.hpp.
References project_gradient().
Referenced by project_gradient().
project_refined()
template<typename VectorOut_ , typename VectorIn_ , typename Space_ > static void FEAT::Assembly::DiscreteCellProjector::project_refined (VectorOut_ & vector, const VectorIn_ & coeff, const Space_ & space) inline static
Projects a discrete function into the cells of a once refined mesh.
Parameters
[out] vector A transient reference to a vector object that shall receive the refined cell interpolation of the discrete function.
[in] coeff A transient reference to the coefficient vector of the finite-element function.
[in] space A transient reference to the finite-element space.
Definition at line 731 of file discrete_projector.hpp.
References FEAT::Tiny::axpy(), and FEAT::value.
The documentation for this class was generated from the following file:
kernel/assembly/discrete_projector.hpp