FEAT: FEAT::Control::Domain::CGALDomainControl< DomainLevel_ > Class Template Reference
FEAT::Control::Domain::CGALDomainControl< DomainLevel_ > Class Template Reference
Hierarchical partitioned Voxel Domain Control.
#include <cgal_domain_control.hpp>
Public Types
typedef Geometry::MeshAtlas< MeshType > AtlasType
typedef Control::Domain::PartiDomainControlBase< DomainLevel_ > BaseClass
our base class
typedef MeshType::CoordType CoordType
coordinate type
typedef DomainLayer LayerType
typedef DomainLevel_ LevelType
typedef Geometry::RootMeshNode< MeshType > MeshNodeType
our root mesh node type
typedef LevelType::PartType MeshPartType
our mesh-part type
typedef LevelType::MeshType MeshType
typedef LevelType::ShapeType ShapeType
typedef VirtualLevel< LevelType > VirtLevelType
typedef Real WeightType
weight type for partitioner element weights; always Real
Public Member Functions
CGALDomainControl (const Dist::Comm &comm_, bool support_multi_layered)
Constructor.
virtual ~CGALDomainControl ()
virtual destructor
void add_trafo_mesh_part_charts ()
VirtLevelType & at (std::size_t i)
const VirtLevelType & at (std::size_t i) const
VirtLevelType & back ()
const VirtLevelType & back () const
LayerType & back_layer ()
const LayerType & back_layer () const
std::size_t bytes () const
bool cgal_wrapper_empty () const
void cheap_weight_calculation (bool option)
set whether we use an expensive or cheap method to calculate the element weights
const Dist::Comm & comm () const
void compile_virtual_levels ()
virtual void create (const std::deque< String > &filenames, String dirpath="")
Creates a domain control from a list of filenames.
virtual void create (Geometry::MeshFileReader &)
Creates a domain control from a MeshFileReader.
virtual void create (std::unique_ptr< MeshNodeType > &)
Creates a domain control from a base-mesh node.
MeshNodeType & create_base_mesh_3d (Index num_x, Index num_y, Index num_z, CoordType x_min, CoordType x_max, CoordType y_min, CoordType y_max, CoordType z_min, CoordType z_max)
Creates a 3D structured cuboid base mesh and returns its base-mesh node.
void create_cgal_wrapper (const FEAT::String &file, Geometry::CGALFileMode file_mode)
has to be called from each process part of the domain hirarchy
void create_cgal_wrapper (std::istream &file, Geometry::CGALFileMode file_mode)
Creates a voxel map based on a VoxelMasker object.
void create_hierarchy ()
Creates the domain level hierarchy.
String dump_ancestry () const
Debugging function: Returns a string containing encoded ancestry information.
String dump_layer_levels () const
String dump_layers () const
String dump_slag_layer_levels () const
Debugging function: Returns a string containing encoded slag layer level information.
String dump_virt_levels () const
virtual String format_chosen_levels () const
Returns the chosen levels formatted as a parsable string.
virtual String format_desired_levels () const
Returns the desired levels formatted as a parsable string.
VirtLevelType & front ()
const VirtLevelType & front () const
LayerType & front_layer ()
const LayerType & front_layer () const
std::vector< WeightType > gather_element_weights (Index level) const
Gathers the element map weights on a given domain level.
Geometry::AdaptMode get_adapt_mode () const
Gets the adapt-mode for refinement.
const std::deque< Ancestor > & get_ancestry () const
Returns a const reference to the ancestry.
AtlasType & get_atlas ()
const AtlasType & get_atlas () const
Tiny::Vector< CoordType, shape_dim > get_bounding_box_max () const
Tiny::Vector< CoordType, shape_dim > get_bounding_box_min () const
Geometry::CGALWrapper< CoordType > * get_cgal_wrapper ()
const Geometry::CGALWrapper< CoordType > * get_cgal_wrapper () const
const std::deque< std::pair< int, int > > get_chosen_levels () const
Returns the deque of chosen refinement levels.
virtual String get_chosen_parti_info () const
Returns an informative string about the chosen partitioning.
int get_desired_level_max () const
Returns the desired maximum refinement level.
int get_desired_level_min () const
Returns the desired minimum refinement level.
const std::deque< std::pair< int, int > > get_desired_levels () const
Returns the deque of desired refinement levels.
const StopWatch & get_watch_base_mesh () const
Returns a const reference to the StopWatch that measures the base-mesh creation phase.
const StopWatch & get_watch_cgal_wrapper () const
Returns a const reference to the StopWatch that measures the voxel-map creation phase.
const StopWatch & get_watch_hierarchy () const
Returns a const reference to the StopWatch that measures the base-mesh creation phase.
const StopWatch & get_watch_weights () const
bool has_ghost () const
void keep_base_levels ()
Instructs the domain controller to keep the base-mesh levels after partitioning.
void keep_cgal_wrapper ()
Instructs the domain controller to keep the voxel map after hierarchy creation.
int max_level_index () const
int med_level_index () const
int min_level_index () const
std::size_t num_global_layers () const
std::size_t num_local_layers () const
virtual bool parse_args (SimpleArgParser &args)
Parses the partitioner options from an argument parser.
virtual bool parse_property_map (const PropertyMap &pmap)
Parses the partitioner options from a PropertyMap.
virtual void print () const
void push_layer (std::shared_ptr< LayerType > layer)
void push_level_back (int layer_index, std::shared_ptr< LevelType > level)
void push_level_front (int layer_index, std::shared_ptr< LevelType > level)
Geometry::CGALWrapper< CoordType > * release_cgal_wrapper ()
Releases the internal cgal wrapper.
std::vector< char > serialize_partitioning () const
Serializes the partitioning information into a binary buffer.
void set_adapt_mode (Geometry::AdaptMode adapt_mode)
Sets the adapt-mode for refinement.
MeshNodeType & set_base_mesh (std::unique_ptr< MeshNodeType > &&mesh_node)
Set another mesh as base mesh.
void set_cgal_wrapper (std::unique_ptr< Geometry::CGALWrapper< CoordType > > &&cgal_wrapper)
virtual void set_desired_levels (const std::deque< String > &slvls)
Sets the desired levels for the partitioned hierarchy.
void set_desired_levels (const String &slvls)
Sets the desired levels for the partitioned hierarchy.
virtual void set_desired_levels (int lvl_max, int lvl_med, int lvl_min)
Sets the desired refinement levels for a double-layered hierarchy.
virtual void set_desired_levels (int lvl_max, int lvl_min=-1)
Sets the desired refinement levels for a single-layered hierarchy.
std::size_t size_physical () const
std::size_t size_virtual () const
Static Public Member Functions
static String name ()
Static Public Attributes
static constexpr int shape_dim = MeshType::shape_dim
shape dimension
Protected Member Functions
virtual bool _apply_parti (Ancestor &ancestor, MeshNodeType &base_mesh_node)
Applies an a-posteriori partitioner.
bool _apply_parti_genetic (Ancestor &ancestor, MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the genetic partitioner onto the base-mesh.
bool _apply_parti_metis (Ancestor &ancestor, const MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the METIS partitioner onto the base-mesh.
bool _apply_parti_naive (Ancestor &ancestor, const MeshNodeType &mesh_node, const std::vector< WeightType > &weights)
Applies the naive partitioner onto the base-mesh.
bool _apply_parti_zoltan (Ancestor &ancestor, const MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the Zoltan partitioner onto the base-mesh.
virtual bool _check_parti (Ancestor &ancestor, const MeshNodeType &mesh_node, bool is_base_layer)
Checks for an appropriate partitioning strategy.
Adjacency::Coloring _compute_base_mesh_coloring (const MeshNodeType &slag_node) const
Computes the coloring for the unpartitioned base mesh.
Adjacency::Coloring _compute_base_mesh_layering (const MeshNodeType &slag_node) const
Computes the element layering for the unpartitioned base mesh.
Adjacency::Coloring _compute_refined_mesh_coloring (const MeshNodeType &slag_node) const
Computes the coloring for a refined mesh.
Adjacency::Coloring _compute_refined_mesh_layering (const MeshNodeType &slag_node, const Adjacency::Coloring &coarse_layering) const
Computes the layering for a refined mesh.
Adjacency::Coloring _compute_unstructered_coloring (const MeshNodeType &base_node) const
std::vector< WeightType > _compute_weights (Ancestor &ancestor, const MeshNodeType &base_mesh_node) override
Computes the element partitioning weights.
virtual void _create_ancestry_scattered ()
Creates the layers for a multi-layered domain control in a scattered fashion.
virtual void _create_ancestry_single ()
Creates the ancestry for a single layer (or a single process)
virtual void _create_multi_layered (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a multi-layered mesh hierarchy.
virtual void _create_multi_layers_scattered ()
Creates the layers for a multi-layered domain control in a scattered fashion.
virtual void _create_single_layered (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a single-layered mesh hierarchy.
virtual void _create_single_process (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a single-layered mesh hierarchy for a single process.
virtual std::unique_ptr< MeshNodeType > _deslag_mesh_node (MeshNodeType &mesh_node)
Deslags an unpartitioned mesh node including its mesh-parts.
virtual std::unique_ptr< MeshNodeType > _deslag_mesh_node (MeshNodeType &mesh_node, const Ancestor &ancestor, bool is_child)
Deslags a (potentially partitioned) mesh node including its mesh-parts and halos.
virtual void _deslag_patch_halos (MeshNodeType &patch_mesh_node, const MeshNodeType &base_mesh_node, const Ancestor &ancestor, bool is_child)
Deslags the halos of a patch mesh node.
Adjacency::Coloring _extract_patch_coloring (const MeshNodeType &slag_node, const Adjacency::Coloring &parent_coloring, int child_rank) const
Extracts a patch coloring from the parent mesh coloring.
Adjacency::Coloring _extract_patch_layering (const MeshNodeType &slag_node, const Adjacency::Coloring &parent_layering, int child_rank) const
Extracts a patch layering from the parent mesh layering.
std::vector< WeightType > _gather_element_weights (const MeshType &mesh) const
Gathers the element slag weights for a given mesh.
std::vector< Index > _gather_masked_elements (const MeshType &mesh) const
Gather a vector of element indices that intersect the masked domain.
std::vector< Index > _gather_masked_elements (const MeshType &mesh, const Dist::Comm &sibling_comm) const
Gather a vector of element indices that intersect the masked domain in a copperative manner.
virtual bool _parse_parti_type (const String &type)
Parses a partitioner type.
virtual void _reset_parti_types ()
Resets/disables all partitioner types.
virtual void _split_basemesh_halos (const Ancestor &ancestor, const MeshNodeType &base_mesh_node, MeshNodeType &patch_mesh_node, std::vector< int > &neighbor_ranks)
Splits the base-mesh halos and computes the inter-patch-mesh halos.
Protected Attributes
Geometry::AdaptMode _adapt_mode
the adapt mode for refinement
bool _allow_parti_genetic
allow genetic partitioner?
bool _allow_parti_metis
allow metis partitioner?
bool _allow_parti_naive
allow naive partitioner?
bool _allow_parti_zoltan
allow Zoltan partitioner?
std::deque< Ancestor > _ancestry
the partition ancestry deque
AtlasType _atlas
std::deque< std::shared_ptr< LevelType > > _base_levels
std::unique_ptr< MeshNodeType > _base_mesh_node
the input base-mesh node on level 0
std::array< Index, shape_dim > _base_slices
number of element slices on base mesh level 0
Tiny::Vector< CoordType, shape_dim > _bbox_max
Tiny::Vector< CoordType, shape_dim > _bbox_min
the bounding box of the structured domain
std::unique_ptr< Geometry::CGALWrapper< CoordType > > _cgal_wrapper
cgal wrapper
bool _cheap_weights = true
std::deque< std::pair< int, int > > _chosen_levels
chosen level deque
const Dist::Comm & _comm
int _create_stage
creation stage to keep track what has already been initialized
std::deque< std::pair< int, int > > _desired_levels
desired level deque
double _genetic_time_init
time for genetic partitioner initialization
double _genetic_time_mutate
time for genetic partitioner mutation
bool _keep_base_levels
keep base-mesh levels on root process?
bool _keep_cgal_wrapper
specifies whether to keep the voxel map after hierarchy creation
std::deque< std::deque< std::shared_ptr< LevelType > > > _layer_levels
std::deque< std::shared_ptr< LayerType > > _layers
std::size_t _num_global_layers
int _required_elems_per_rank
required number of elements per rank for a-posteriori partitioning
bool _support_multi_layered
support multi-layered hierarchy?
bool _unstructered_mesh = false
specifies whether we use a non voxel base mesh
std::deque< VirtLevelType > _virt_levels
std::size_t _virt_size
bool _was_created
specifies whether the domain control was already created
StopWatch _watch_calc_weights
StopWatch _watch_create_base_mesh
a bunch of stop-watches
StopWatch _watch_create_cgal_wrapper
StopWatch _watch_create_hierarchy
Detailed Description
template<typename DomainLevel_>
class FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >
Hierarchical partitioned Voxel Domain Control.
Author
Peter Zajac, Maximilian Esser
Definition at line 92 of file cgal_domain_control.hpp.
Member Typedef Documentation
AtlasType
typedef Geometry::MeshAtlas<MeshType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::AtlasType inherited
Definition at line 466 of file domain_control.hpp.
BaseClass
template<typename DomainLevel_ > typedef Control::Domain::PartiDomainControlBase< DomainLevel_ > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::BaseClass
our base class
Definition at line 97 of file cgal_domain_control.hpp.
CoordType
template<typename DomainLevel_ > typedef MeshType::CoordType FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::CoordType
coordinate type
Definition at line 120 of file cgal_domain_control.hpp.
LayerType
typedef DomainLayer FEAT::Control::Domain::DomainControl< DomainLevel_ >::LayerType inherited
Definition at line 460 of file domain_control.hpp.
LevelType
typedef DomainLevel_ FEAT::Control::Domain::DomainControl< DomainLevel_ >::LevelType inherited
Definition at line 459 of file domain_control.hpp.
MeshNodeType
template<typename DomainLevel_ > typedef Geometry::RootMeshNode<MeshType> FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::MeshNodeType
our root mesh node type
Definition at line 56 of file parti_domain_control_base.hpp.
MeshPartType
template<typename DomainLevel_ > typedef LevelType::PartType FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::MeshPartType
our mesh-part type
Definition at line 58 of file parti_domain_control_base.hpp.
MeshType
typedef LevelType::MeshType FEAT::Control::Domain::DomainControl< DomainLevel_ >::MeshType inherited
Definition at line 464 of file domain_control.hpp.
ShapeType
typedef LevelType::ShapeType FEAT::Control::Domain::DomainControl< DomainLevel_ >::ShapeType inherited
Definition at line 463 of file domain_control.hpp.
VirtLevelType
typedef VirtualLevel<LevelType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::VirtLevelType inherited
Definition at line 461 of file domain_control.hpp.
WeightType
template<typename DomainLevel_ > typedef Real FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::WeightType
weight type for partitioner element weights; always Real
Definition at line 61 of file parti_domain_control_base.hpp.
Constructor & Destructor Documentation
CGALDomainControl()
template<typename DomainLevel_ > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::CGALDomainControl (const Dist::Comm & comm_, bool support_multi_layered) inline explicit
Constructor.
Parameters
[in] comm_ A resident reference to the main communicator to be used.
[in] support_multi_layered Specifies whether the controller is allowed to create multi-layered hierarchies.
Definition at line 158 of file cgal_domain_control.hpp.
~CGALDomainControl()
template<typename DomainLevel_ > virtual FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::~CGALDomainControl () inline virtual
virtual destructor
Definition at line 168 of file cgal_domain_control.hpp.
Member Function Documentation
_apply_parti()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti (Ancestor & ancestor, MeshNodeType & base_mesh_node) inline protected virtual inherited
Applies an a-posteriori partitioner.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
Returns
true, if the base-mesh was partitioned, otherwise false.
Definition at line 1317 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_genetic(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_metis(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_naive(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_zoltan(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_compute_weights(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_apriori.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered().
_apply_parti_genetic()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_genetic (Ancestor & ancestor, MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected inherited
Applies the genetic partitioner onto the base-mesh.
Parameters
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true.
Definition at line 1466 of file parti_domain_control_base.hpp.
References FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_comm.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_metis()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_metis (Ancestor & ancestor, const MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected inherited
Applies the METIS partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if METIS was applied successfully, otherwise false.
Definition at line 1413 of file parti_domain_control_base.hpp.
References FEAT::Geometry::PartiParMETIS::build_elems_at_rank(), FEAT::Geometry::PartiParMETIS::execute(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_comm.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_naive()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_naive (Ancestor & ancestor, const MeshNodeType & mesh_node, const std::vector< WeightType > & weights) inline protected inherited
Applies the naive partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if a naive partition was created successfully, otherwise false.
Definition at line 1508 of file parti_domain_control_base.hpp.
References FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Math::max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info, and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_zoltan()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_zoltan (Ancestor & ancestor, const MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected inherited
Applies the Zoltan partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if Zoltan was applied successfully, otherwise false.
Definition at line 1361 of file parti_domain_control_base.hpp.
References FEAT::Geometry::PartiZoltan::build_elems_at_rank(), FEAT::Geometry::PartiZoltan::execute(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_comm.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_check_parti()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_check_parti (Ancestor & ancestor, const MeshNodeType & mesh_node, bool is_base_layer) inline protected virtual inherited
Checks for an appropriate partitioning strategy.
This function examines the given base mesh and checks whether one of the a-priori partitioning strategies (extern or 2-level) yields a valid partitioning for the given number of partitions. If so, the corresponding partitioning level and graph are stored in ancestor.parti_level and ancestor.parti_graph. If not, this function determines how often the base-mesh has to be refined until its has enough cells so that one of the a-posteriori partitioners can be applied.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] mesh_node The base-mesh node that is to be partitioned.
[in] is_base_layer Set to true, if #base_mesh_node is the mesh node that corresponds to the input file's mesh and therefore extern partitioning is a valid option, or set to false in any other case.
Returns
true, if an a-priori partitioning was found, otherwise false.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 1276 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Math::max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_level.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_compute_base_mesh_coloring()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_base_mesh_coloring (const MeshNodeType & slag_node) const inline protected
Computes the coloring for the unpartitioned base mesh.
Parameters
[in] slag_node The unpartitioned structured base-mesh node
Returns
The coloring for the unpartitioned deslagged base-mesh node
Definition at line 1021 of file cgal_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), and XASSERT.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process().
_compute_base_mesh_layering()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_base_mesh_layering (const MeshNodeType & slag_node) const inline protected
Computes the element layering for the unpartitioned base mesh.
Parameters
[in] slag_node The unpartitioned structured base-mesh node
Returns
The layering for the unpartitioned deslagged base-mesh node
Definition at line 1144 of file cgal_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::shape_dim, and XASSERT.
_compute_refined_mesh_coloring()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring (const MeshNodeType & slag_node) const inline protected
Computes the coloring for a refined mesh.
Parameters
[in] slag_node The refined mesh node
Returns
The coloring for the refined and deslagged mesh node
Definition at line 1076 of file cgal_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), and XASSERT.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process().
_compute_refined_mesh_layering()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_refined_mesh_layering (const MeshNodeType & slag_node, const Adjacency::Coloring & coarse_layering) const inline protected
Computes the layering for a refined mesh.
Parameters
[in] slag_node The refined mesh node
Returns
The layering for the refined and deslagged mesh node
Definition at line 1194 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_unstructered_mesh, FEAT::Adjacency::Coloring::get_coloring(), FEAT::Adjacency::Coloring::get_num_colors(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::shape_dim, and XASSERT.
_compute_unstructered_coloring()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_unstructered_coloring (const MeshNodeType & base_node) const inline protected
Definition at line 1004 of file cgal_domain_control.hpp.
_compute_weights()
template<typename DomainLevel_ > std::vector< WeightType > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_weights (Ancestor & ancestor, const MeshNodeType & base_mesh_node) inline override protected virtual
Computes the element partitioning weights.
Note
This base-class implementation always returns an empty vector, but a derived class may override this method and an actual non-trivial weight vector.
Returns
A vector containing the weights for the base mesh elements or an empty vector, if all elements are to be weighted equally.
Reimplemented from FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >.
Definition at line 743 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_gather_element_weights(), and FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh().
_create_ancestry_scattered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_scattered () inline protected virtual inherited
Creates the layers for a multi-layered domain control in a scattered fashion.
Definition at line 887 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Dist::Comm::comm_create_range_incl(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_procs, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_child, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_comm, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_count, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_first, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_group, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_create_ancestry_single()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_single () inline protected virtual inherited
Creates the ancestry for a single layer (or a single process)
Definition at line 781 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_procs, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_child, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_comm, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_count, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_first, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_group, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERTM.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process().
_create_multi_layered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected virtual
Creates a multi-layered mesh hierarchy.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Definition at line 1497 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_base_mesh_coloring(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_scattered(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_multi_layers_scattered(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_mesh_node(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_extract_patch_coloring(), FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_split_basemesh_halos(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_unstructered_mesh, FEAT::Dist::Comm::allreduce(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Math::max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Dist::op_max, FEAT::Dist::op_min, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_level, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_child, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_group, FEAT::Dist::Comm::size(), and XASSERTM.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_hierarchy().
_create_multi_layers_scattered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_multi_layers_scattered () inline protected virtual inherited
Creates the layers for a multi-layered domain control in a scattered fashion.
Definition at line 826 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::comm, FEAT::Dist::Comm::comm_create_range_incl(), FEAT::Dist::Comm::comm_dup(), FEAT::Dist::Comm::is_null(), FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_create_single_layered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected virtual
Creates a single-layered mesh hierarchy.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Definition at line 1383 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_single(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_mesh_node(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_extract_patch_coloring(), FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_unstructered_mesh, FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Adjacency::Coloring::empty(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_level, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERTM.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_hierarchy().
_create_single_process()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected virtual
Creates a single-layered mesh hierarchy for a single process.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Note
This function does not keep the base-mesh levels explicitly even if _keep_base_levels is set to true, because it is not required to use the base splitter on a single process.
Definition at line 1304 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_base_mesh_coloring(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_single(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_mesh_node(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_unstructered_mesh, FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_hierarchy().
_deslag_mesh_node() [1/2]
template<typename DomainLevel_ > virtual std::unique_ptr< MeshNodeType > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_mesh_node (MeshNodeType & mesh_node) inline protected virtual
Deslags an unpartitioned mesh node including its mesh-parts.
Attention
This function can only be used for unpartitioned mesh nodes. If the mesh node represents a patch, then the other overload that requires and Ancestor object has to be used, because the halos also need to be deslagged in this case!
This function adds a patch with rank -1 to the mesh_node, which represents the deslagged patch.
Parameters
[in,out] mesh_node A transient reference to the mesh node that is to be deslagged.
Returns
A new mesh node that contains the deslagged mesh as well as the deslagged mesh parts.
Definition at line 767 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_gather_masked_elements(), FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), and XASSERTM.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process().
_deslag_mesh_node() [2/2]
template<typename DomainLevel_ > virtual std::unique_ptr< MeshNodeType > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_mesh_node (MeshNodeType & mesh_node, const Ancestor & ancestor, bool is_child) inline protected virtual
Deslags a (potentially partitioned) mesh node including its mesh-parts and halos.
This function adds a patch with rank -1 to the mesh_node, which represents the deslagged patch.
Parameters
[in,out] mesh_node A transient reference to the mesh node that is to be deslagged.
[in] ancestor Depending on whether is_child is false or true, a transient reference to the ancestor object of either the layer that the mesh node belongs to or the child layer of the layer that the mesh node belongs to, resp.
[in] is_child Specifies whether the ancestor object is actually the child ancestor object; this is only true for the mesh nodes belonging to parent layers in the case of hierarchical partitioning.
Returns
A new mesh node that contains the deslagged mesh as well as the deslagged mesh parts and halos.
Definition at line 792 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_patch_halos(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_gather_masked_elements(), FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_comm.
_deslag_patch_halos()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_patch_halos (MeshNodeType & patch_mesh_node, const MeshNodeType & base_mesh_node, const Ancestor & ancestor, bool is_child) inline protected virtual
Deslags the halos of a patch mesh node.
Parameters
[in] patch_mesh_node A transient reference to the deslagged patch mesh node whose halos are to be deslagged.
[in] base_mesh_node A transient reference to the mesh node that the deslagged mesh node was created from.
[in] ancestor Depending on whether is_child is false or true, a transient reference to the ancestor object of either the layer that the mesh node belongs to or the child layer of the layer that the mesh node belongs to, resp.
[in] is_child Specifies whether the ancestor object is actually the child ancestor object; this is only true for the mesh nodes belonging to parent layers in the case of hierarchical partitioning.
Definition at line 818 of file cgal_domain_control.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_halo(), FEAT::Dist::Comm::bcast(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_comm, FEAT::Dist::Comm::rank(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::shape_dim, FEAT::stringify(), FEAT::Dist::RequestVector::wait_all(), and XABORTM.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_mesh_node().
_extract_patch_coloring()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_extract_patch_coloring (const MeshNodeType & slag_node, const Adjacency::Coloring & parent_coloring, int child_rank) const inline protected
Extracts a patch coloring from the parent mesh coloring.
Parameters
[in] parent_node The parent node that the patch was extracted from
[in] parent_coloring The coloring of the parent node
[in] child_rank The rank of the extracted patch
Returns
The coloring for the refined deslagged mesh node
Definition at line 1113 of file cgal_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Adjacency::Coloring::get_num_colors(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), and XASSERT.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered().
_extract_patch_layering()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_extract_patch_layering (const MeshNodeType & slag_node, const Adjacency::Coloring & parent_layering, int child_rank) const inline protected
Extracts a patch layering from the parent mesh layering.
Parameters
[in] parent_node The parent node that the patch was extracted from
[in] parent_layering The layering of the parent node
[in] child_rank The rank of the extracted patch
Returns
The layering for the refined deslagged mesh node
Definition at line 1255 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_unstructered_mesh, FEAT::Adjacency::Coloring::get_coloring(), FEAT::Adjacency::Coloring::get_num_colors(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), and XASSERT.
_gather_element_weights()
template<typename DomainLevel_ > std::vector< WeightType > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_gather_element_weights (const MeshType & mesh) const inline protected
Gathers the element slag weights for a given mesh.
The "slag weight" of an element is defined as the integral of the step function defined by the inside out test, divided by the cell volume.
Parameters
[in] mesh The mesh for which the element weights are to be gathered.
Returns
A vector of floats in range [0,1] representing the element slag weights on the desired level. The length of the vector corresponds to the number of elements on the patch on the desired domain level.
trafo evaluation data type
Definition at line 683 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_cgal_wrapper, ASSERTM, FEAT::dom_point, FEAT::img_point, FEAT::jac_det, FEAT::StopWatch::start(), and FEAT::StopWatch::stop().
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_weights(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::gather_element_weights().
_gather_masked_elements() [1/2]
template<typename DomainLevel_ > std::vector< Index > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_gather_masked_elements (const MeshType & mesh) const inline protected
Gather a vector of element indices that intersect the masked domain.
Attention
It is silently assumed that all elements in the mesh are axis-parallel rectangles/cuboids; this function may yield incorrect results if the mesh violates this assumption!
Parameters
[in] mesh A transient reference to the mesh whose elements are to be tested against the cgal mesh
Returns
A vector containing the indices of all mesh elements that intersect the domain that is represented by the voxel map.
Definition at line 576 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_mesh_node().
_gather_masked_elements() [2/2]
template<typename DomainLevel_ > std::vector< Index > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_gather_masked_elements (const MeshType & mesh, const Dist::Comm & sibling_comm) const inline protected
Gather a vector of element indices that intersect the masked domain in a copperative manner.
Attention
This has to be called by all processes in the sibling communicator
Parameters
[in] mesh A transient reference to the mesh whose elements are to be tested against the cgal mesh
[in] sibling_comm The communicator accross the workload is to be spread.
Returns
A vector containing the indices of all mesh elements that intersect the domain that is represented by the voxel map.
Definition at line 622 of file cgal_domain_control.hpp.
References FEAT::Dist::Comm::allgather(), FEAT::Dist::Comm::allgatherv(), FEAT::Math::min(), FEAT::Dist::Comm::rank(), and FEAT::Dist::Comm::size().
_parse_parti_type()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type (const String & type) inline protected virtual inherited
Parses a partitioner type.
Parameters
[in] type The name of the partitioner type that is to be enabled.
Returns
true, if type represents a supported partitioner type, otherwise false.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 749 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan, and FEAT::String::compare_no_case().
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_reset_parti_types()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types () inline protected virtual inherited
Resets/disables all partitioner types.
This function is called by the parse_args and parse_property_map function when the user has supplied a list of allowed partitioner types.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 735 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_split_basemesh_halos()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_split_basemesh_halos (const Ancestor & ancestor, const MeshNodeType & base_mesh_node, MeshNodeType & patch_mesh_node, std::vector< int > & neighbor_ranks) inline protected virtual inherited
Splits the base-mesh halos and computes the inter-patch-mesh halos.
This is where the magic happens in the case of the multi-layered hierarchy.
Parameters
[in] ancestor The ancestor object for the current layer.
[in] base_mesh_node The base-mesh node that has been partitioned and whose halos are to be split.
[in,out] patch_mesh_node The patch-mesh node that represents the partition whose halos are to be computed.
[in,out] neighbor_ranks The vector that receives the ranks of the new neighbors that derive from halo splitting.
Definition at line 963 of file parti_domain_control_base.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_halo(), FEAT::Dist::Comm::bcast(), FEAT::Dist::Comm::gather(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::is_null(), FEAT::Dist::Comm::isend(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_child, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::progeny_comm, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), FEAT::Dist::RequestVector::wait_all(), and XASSERT.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
add_trafo_mesh_part_charts()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::add_trafo_mesh_part_charts () inline inherited
Definition at line 771 of file domain_control.hpp.
at() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::at (std::size_t i) inline inherited
Definition at line 625 of file domain_control.hpp.
at() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::at (std::size_t i) const inline inherited
Definition at line 630 of file domain_control.hpp.
back() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back () inline inherited
Definition at line 645 of file domain_control.hpp.
back() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back () const inline inherited
Definition at line 650 of file domain_control.hpp.
back_layer() [1/2]
LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back_layer () inline inherited
Definition at line 565 of file domain_control.hpp.
back_layer() [2/2]
const LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back_layer () const inline inherited
Definition at line 570 of file domain_control.hpp.
bytes()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::bytes () const inline inherited
Definition at line 523 of file domain_control.hpp.
cgal_wrapper_empty()
template<typename DomainLevel_ > bool FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::cgal_wrapper_empty () const inline
Definition at line 451 of file cgal_domain_control.hpp.
cheap_weight_calculation()
template<typename DomainLevel_ > void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::cheap_weight_calculation (bool option) inline
set whether we use an expensive or cheap method to calculate the element weights
Definition at line 190 of file cgal_domain_control.hpp.
comm()
const Dist::Comm & FEAT::Control::Domain::DomainControl< DomainLevel_ >::comm () const inline inherited
Definition at line 518 of file domain_control.hpp.
compile_virtual_levels()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::compile_virtual_levels () inline inherited
Definition at line 683 of file domain_control.hpp.
create() [1/3]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create (const std::deque< String > & filenames, String dirpath = "") inline virtual
Creates a domain control from a list of filenames.
Parameters
[in] filenames A list of mesh filenames from which the domain control is to be created.
[in] dirpath The path in which the mesh files are located.
Definition at line 529 of file cgal_domain_control.hpp.
References ASSERTM.
create() [2/3]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create (Geometry::MeshFileReader &) inline virtual
Creates a domain control from a MeshFileReader.
Parameters
[in,out] mesh_reader A transient reference to the mesh reader from which the domain control is to be created.
Definition at line 543 of file cgal_domain_control.hpp.
References ASSERTM.
create() [3/3]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create (std::unique_ptr< MeshNodeType > &) inline virtual
Creates a domain control from a base-mesh node.
Parameters
[in] base_mesh_node The base-mesh node that the domain control is to be created from
Definition at line 555 of file cgal_domain_control.hpp.
References ASSERTM.
create_base_mesh_3d()
template<typename DomainLevel_ > MeshNodeType & FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_base_mesh_3d (Index num_x, Index num_y, Index num_z, CoordType x_min, CoordType x_max, CoordType y_min, CoordType y_max, CoordType z_min, CoordType z_max) inline
Creates a 3D structured cuboid base mesh and returns its base-mesh node.
This functions returns a reference to the base-mesh node that is created and managed internally by this class. This base-mesh node reference can be used to create mesh-parts at the base-mesh level, which will be refined and deslagged during the creation of the domain hierarchy.
Attention
The returned base-mesh node reference is only valid until the create() method is called and is orphaned after the create() method returns, because the base-mesh node is then processed internally to create the domain level hierarchy.
Parameters
[in] num_x,num_y,num_z The number of element slices in X-, Y- and Z-direction.
[in] x_min,x_max The X-range of the cuboid domain.
[in] y_min,y_max The X-range of the cuboid domain.
[in] z_min,z_max The X-range of the cuboid domain.
Returns
A reference to the internal base-mesh node containing the base-mesh.
Definition at line 230 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_base_mesh_node, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_base_slices, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_bbox_min, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_stage, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_watch_create_base_mesh, FEAT::Geometry::RootMeshNode< MeshType >::make_unique(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), XASSERT, and XASSERTM.
create_cgal_wrapper() [1/2]
template<typename DomainLevel_ > void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_cgal_wrapper (const FEAT::String & file, Geometry::CGALFileMode file_mode) inline
has to be called from each process part of the domain hirarchy
Definition at line 355 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_cgal_wrapper(), FEAT::DistFileIO::read_common(), FEAT::StopWatch::start(), and FEAT::StopWatch::stop().
create_cgal_wrapper() [2/2]
template<typename DomainLevel_ > void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_cgal_wrapper (std::istream & file, Geometry::CGALFileMode file_mode) inline
Creates a voxel map based on a VoxelMasker object.
This function can only be called after the base-mesh has been created by calling create_base_mesh_3d or set_base_mesh.
Attention
This function is a "collective" function in distributed parallel (i.e. MPI) simulations and each process must be given the same file content, else this will lead to incostinet inside out information
Parameters
[in] file A transient reference to the input stream
[in] file_mode The file mode of the cgal input, should be either off or obj
Compiler Hack:
avoid std::make_unique for clang
Definition at line 341 of file cgal_domain_control.hpp.
References FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and XASSERTM.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_cgal_wrapper().
create_hierarchy()
template<typename DomainLevel_ > void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_hierarchy () inline
Creates the domain level hierarchy.
This function can only be called after the base-mesh has been created by calling create_base_mesh_2d or create_base_mesh_3d and after the voxel map has been created by calling create_voxel_map().
Definition at line 371 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_support_multi_layered, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::StopWatch::elapsed(), FEAT::Dist::Comm::size(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), FEAT::Statistics::toe_partition, and XASSERTM.
dump_ancestry()
template<typename DomainLevel_ > String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::dump_ancestry () const inline inherited
Debugging function: Returns a string containing encoded ancestry information.
Definition at line 593 of file parti_domain_control_base.hpp.
References FEAT::String::pad_front(), and FEAT::stringify().
dump_layer_levels()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_layer_levels () const inline inherited
Definition at line 811 of file domain_control.hpp.
dump_layers()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_layers () const inline inherited
Definition at line 789 of file domain_control.hpp.
dump_slag_layer_levels()
template<typename DomainLevel_ > String FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::dump_slag_layer_levels () const inline
Debugging function: Returns a string containing encoded slag layer level information.
Definition at line 500 of file cgal_domain_control.hpp.
References FEAT::String::pad_front(), and FEAT::stringify().
dump_virt_levels()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_virt_levels () const inline inherited
Definition at line 824 of file domain_control.hpp.
format_chosen_levels()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_chosen_levels () const inline virtual inherited
Returns the chosen levels formatted as a parsable string.
The string returned by this function can be parsed by the set_desired_levels() function.
Returns
The chosen levels formatted as a parsable string.
Definition at line 523 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, and FEAT::stringify().
format_desired_levels()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_desired_levels () const inline virtual inherited
Returns the desired levels formatted as a parsable string.
The string returned by this function can be parsed by the set_desired_levels() function.
Returns
The desired levels formatted as a parsable string.
Definition at line 502 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, and FEAT::stringify().
front() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front () inline inherited
Definition at line 635 of file domain_control.hpp.
front() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front () const inline inherited
Definition at line 640 of file domain_control.hpp.
front_layer() [1/2]
LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front_layer () inline inherited
Definition at line 555 of file domain_control.hpp.
front_layer() [2/2]
const LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front_layer () const inline inherited
Definition at line 560 of file domain_control.hpp.
gather_element_weights()
template<typename DomainLevel_ > std::vector< WeightType > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::gather_element_weights (Index level) const inline
Gathers the element map weights on a given domain level.
The "slag weight" of an element is defined as the integral of the step function defined by the inside out test, divided by the cell volume.
Parameters
[in] level The physical domain level for which the element weights are to be gathered.
Returns
A vector of floats in range [0,1] representing the element slag weights on the desired level. The length of the vector corresponds to the number of elements on the patch on the desired domain level.
Definition at line 491 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_gather_element_weights(), and XASSERT.
get_adapt_mode()
template<typename DomainLevel_ > Geometry::AdaptMode FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_adapt_mode () const inline inherited
Gets the adapt-mode for refinement.
Returns
The adapt-mode that is used.
Definition at line 326 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode.
get_ancestry()
template<typename DomainLevel_ > const std::deque< Ancestor > & FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_ancestry () const inline inherited
Returns a const reference to the ancestry.
Definition at line 628 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry.
get_atlas() [1/2]
AtlasType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::get_atlas () inline inherited
Definition at line 655 of file domain_control.hpp.
get_atlas() [2/2]
const AtlasType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::get_atlas () const inline inherited
Definition at line 660 of file domain_control.hpp.
get_bounding_box_max()
template<typename DomainLevel_ > Tiny::Vector< CoordType, shape_dim > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_bounding_box_max () const inline
Definition at line 200 of file cgal_domain_control.hpp.
get_bounding_box_min()
template<typename DomainLevel_ > Tiny::Vector< CoordType, shape_dim > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_bounding_box_min () const inline
Definition at line 195 of file cgal_domain_control.hpp.
get_cgal_wrapper() [1/2]
template<typename DomainLevel_ > Geometry::CGALWrapper< CoordType > * FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_cgal_wrapper () inline
Returns
a const reference to the internal cgal wrapper
Definition at line 435 of file cgal_domain_control.hpp.
get_cgal_wrapper() [2/2]
template<typename DomainLevel_ > const Geometry::CGALWrapper< CoordType > * FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_cgal_wrapper () const inline
Returns
a const reference to the internal cgal wrapper
Definition at line 441 of file cgal_domain_control.hpp.
get_chosen_levels()
template<typename DomainLevel_ > const std::deque< std::pair< int, int > > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_levels () const inline inherited
Returns the deque of chosen refinement levels.
Returns
The deque of chosen refinement levels.
Definition at line 585 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels.
get_chosen_parti_info()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_parti_info () const inline virtual inherited
Returns an informative string about the chosen partitioning.
Note
This function only returns something useful after the create() function has been called.
In the case of a multi-layered recursive partitioning, the returned string is a multi-line string containing the partitioning info for each recursive layer in a separate line.
Definition at line 549 of file parti_domain_control_base.hpp.
References FEAT::stringify().
get_desired_level_max()
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_max () const inline inherited
Returns the desired maximum refinement level.
Returns
The desired maximum refinement level
Definition at line 480 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_precreate_voxel_map().
get_desired_level_min()
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_min () const inline inherited
Returns the desired minimum refinement level.
Returns
The desired minimum refinement level
Definition at line 490 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
get_desired_levels()
template<typename DomainLevel_ > const std::deque< std::pair< int, int > > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_levels () const inline inherited
Returns the deque of desired refinement levels.
Returns
The deque of desired refinement levels.
Definition at line 575 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
get_watch_base_mesh()
template<typename DomainLevel_ > const StopWatch & FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_watch_base_mesh () const inline
Returns a const reference to the StopWatch that measures the base-mesh creation phase.
Definition at line 457 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_watch_create_base_mesh.
get_watch_cgal_wrapper()
template<typename DomainLevel_ > const StopWatch & FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_watch_cgal_wrapper () const inline
Returns a const reference to the StopWatch that measures the voxel-map creation phase.
Definition at line 463 of file cgal_domain_control.hpp.
get_watch_hierarchy()
template<typename DomainLevel_ > const StopWatch & FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_watch_hierarchy () const inline
Returns a const reference to the StopWatch that measures the base-mesh creation phase.
Definition at line 469 of file cgal_domain_control.hpp.
get_watch_weights()
template<typename DomainLevel_ > const StopWatch & FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_watch_weights () const inline
Definition at line 474 of file cgal_domain_control.hpp.
has_ghost()
bool FEAT::Control::Domain::DomainControl< DomainLevel_ >::has_ghost () const inline inherited
Todo:
does this really work?
Definition at line 600 of file domain_control.hpp.
keep_base_levels()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::keep_base_levels () inline inherited
Instructs the domain controller to keep the base-mesh levels after partitioning.
Calling this function requests the domain controller to keep the base-mesh levels and refine them even after the partitioning process. This functionality is required to assemble a Global::Splitter object, which allows to serialize and deserialize vectors independent of the partitioning used to create the vector.
Attention
The functionality requested by this function is NOT scalable for large process counts, i.e. the root process WILL run out of memory in large-scale simulations. This functionality should only be used for moderate process counts.
Definition at line 678 of file domain_control.hpp.
keep_cgal_wrapper()
template<typename DomainLevel_ > void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::keep_cgal_wrapper () inline
Instructs the domain controller to keep the voxel map after hierarchy creation.
Unless this function is called prior to the call of the create_hierarchy() function, the voxel map will be released after the hierarchy creation is completed to free up the memory used by the voxel map.
It is recommended not to call this function unless it is really necessary; if you want to use the voxel map for anything after it has been created, e.g. to write it to a file or to print some statistics to cout, then you can use it before calling the create_hierarchy function.
Definition at line 184 of file cgal_domain_control.hpp.
max_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::max_level_index () const inline inherited
Definition at line 580 of file domain_control.hpp.
med_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::med_level_index () const inline inherited
Definition at line 585 of file domain_control.hpp.
min_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::min_level_index () const inline inherited
Definition at line 575 of file domain_control.hpp.
name()
static String FEAT::Control::Domain::DomainControl< DomainLevel_ >::name () inline static inherited
Definition at line 494 of file domain_control.hpp.
num_global_layers()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::num_global_layers () const inline inherited
Definition at line 539 of file domain_control.hpp.
num_local_layers()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::num_local_layers () const inline inherited
Definition at line 534 of file domain_control.hpp.
parse_args()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args (SimpleArgParser & args) inline virtual inherited
Parses the partitioner options from an argument parser.
See also
Control::Domain::add_supported_pdc_args()
Parameters
[in] args The parser that is to be used.
Returns
true, if the parsing was successful, or false, if at least one option was invalid.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 210 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::SimpleArgParser::parse(), FEAT::Dist::Comm::print(), FEAT::SimpleArgParser::query(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args().
parse_property_map()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map (const PropertyMap & pmap) inline virtual inherited
Parses the partitioner options from a PropertyMap.
Parameters
[in] pmap A transient reference to the property map that contains the configuration
Returns
true, if the parsing was successful, or false, if at least one option was invalid.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 254 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::print(), FEAT::PropertyMap::query(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
print()
virtual void FEAT::Control::Domain::DomainControl< DomainLevel_ >::print () const inline virtual inherited
Definition at line 499 of file domain_control.hpp.
push_layer()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_layer (std::shared_ptr< LayerType > layer) inline inherited
Definition at line 544 of file domain_control.hpp.
push_level_back()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_level_back (int layer_index, std::shared_ptr< LevelType > level) inline inherited
Definition at line 595 of file domain_control.hpp.
push_level_front()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_level_front (int layer_index, std::shared_ptr< LevelType > level) inline inherited
Definition at line 590 of file domain_control.hpp.
release_cgal_wrapper()
template<typename DomainLevel_ > Geometry::CGALWrapper< CoordType > * FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::release_cgal_wrapper () inline
Releases the internal cgal wrapper.
Returns
A pointer to the heap allocated cgal wrapper
Attention
After calling this function YOU are responsible to free the cgal wrapper afterwards
Definition at line 429 of file cgal_domain_control.hpp.
serialize_partitioning()
template<typename DomainLevel_ > std::vector< char > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::serialize_partitioning () const inline inherited
Serializes the partitioning information into a binary buffer.
Definition at line 636 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::allreduce(), FEAT::BinaryStream::container(), FEAT::Dist::Comm::gather(), FEAT::Dist::op_max, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
set_adapt_mode()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode (Geometry::AdaptMode adapt_mode) inline inherited
Sets the adapt-mode for refinement.
Parameters
[in] adapt_mode The adapt-mode that is to be used.
Definition at line 314 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, and XASSERTM.
set_base_mesh()
template<typename DomainLevel_ > MeshNodeType & FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::set_base_mesh (std::unique_ptr< MeshNodeType > && mesh_node) inline
Set another mesh as base mesh.
Parameters
[in] mesh_node Unique ptr to mesh node that is to be consumed by this domain
Definition at line 282 of file cgal_domain_control.hpp.
References FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_base_mesh_node, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_base_slices, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_bbox_min, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_stage, FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_watch_create_base_mesh, FEAT::Math::max(), FEAT::Math::min(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::shape_dim, FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and XASSERTM.
set_cgal_wrapper()
template<typename DomainLevel_ > void FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::set_cgal_wrapper (std::unique_ptr< Geometry::CGALWrapper< CoordType > > && cgal_wrapper) inline
Definition at line 446 of file cgal_domain_control.hpp.
set_desired_levels() [1/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (const std::deque< String > & slvls) inline virtual inherited
Sets the desired levels for the partitioned hierarchy.
Parameters
[in] slvls A transient reference to the deque of strings containing the desired levels.
Each entry of the deque is supposed to be in the format level:nprocs.
Definition at line 351 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), FEAT::stringify(), and XASSERTM.
set_desired_levels() [2/4]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (const String & slvls) inline inherited
Sets the desired levels for the partitioned hierarchy.
Parameters
[in] slvls A string containing the list of desired levels.
Definition at line 337 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels(), and FEAT::String::split_by_whitespaces().
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels().
set_desired_levels() [3/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (int lvl_max, int lvl_med, int lvl_min) inline virtual inherited
Sets the desired refinement levels for a double-layered hierarchy.
Parameters
[in] lvl_max The desired maximum refinement level. Must be >= 0.
[in] lvl_med The desired median refinement level. Must be < lvl_max If < 0, then (lvl_max+lvl_med+1) is used as the median level.
[in] lvl_min The desired minimum refinement level. Must be <= lvl_med. If < 0, then (lvl_med+lvl_min+1) is used as the minimum level.
Definition at line 451 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), and XASSERTM.
set_desired_levels() [4/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (int lvl_max, int lvl_min = -1) inline virtual inherited
Sets the desired refinement levels for a single-layered hierarchy.
Parameters
[in] lvl_max The desired maximum refinement level. Must be >= 0.
[in] lvl_min The desired minimum refinement level. Must be <= lvl_max. If < 0, then (lvl_max+lvl_min+1) is used as the minimum level.
Definition at line 421 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), and XASSERTM.
size_physical()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::size_physical () const inline inherited
Definition at line 615 of file domain_control.hpp.
size_virtual()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::size_virtual () const inline inherited
Definition at line 610 of file domain_control.hpp.
Member Data Documentation
_adapt_mode
template<typename DomainLevel_ > Geometry::AdaptMode FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode protected inherited
the adapt mode for refinement
Definition at line 136 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_adapt_mode(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode().
_allow_parti_genetic
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic protected inherited
allow genetic partitioner?
Definition at line 141 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_metis
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis protected inherited
allow metis partitioner?
Definition at line 139 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_naive
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive protected inherited
allow naive partitioner?
Definition at line 143 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_zoltan
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan protected inherited
allow Zoltan partitioner?
Definition at line 145 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_ancestry
template<typename DomainLevel_ > std::deque<Ancestor> FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry protected inherited
the partition ancestry deque
Definition at line 164 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_ancestry().
_atlas
AtlasType FEAT::Control::Domain::DomainControl< DomainLevel_ >::_atlas protected inherited
Definition at line 470 of file domain_control.hpp.
_base_levels
std::deque<std::shared_ptr<LevelType> > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_base_levels protected inherited
Definition at line 472 of file domain_control.hpp.
_base_mesh_node
template<typename DomainLevel_ > std::unique_ptr<MeshNodeType> FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_base_mesh_node protected
the input base-mesh node on level 0
Definition at line 135 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_base_mesh_3d(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::set_base_mesh().
_base_slices
template<typename DomainLevel_ > std::array<Index, shape_dim> FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_base_slices protected
number of element slices on base mesh level 0
Definition at line 129 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_base_mesh_3d(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::set_base_mesh().
_bbox_max
template<typename DomainLevel_ > Tiny::Vector<CoordType, shape_dim> FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_bbox_max protected
Definition at line 127 of file cgal_domain_control.hpp.
_bbox_min
template<typename DomainLevel_ > Tiny::Vector<CoordType, shape_dim> FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_bbox_min protected
the bounding box of the structured domain
Definition at line 127 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_base_mesh_3d(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::set_base_mesh().
_cgal_wrapper
template<typename DomainLevel_ > std::unique_ptr<Geometry::CGALWrapper<CoordType> > FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_cgal_wrapper protected
cgal wrapper
Definition at line 132 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_gather_element_weights().
_cheap_weights
template<typename DomainLevel_ > bool FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_cheap_weights = true protected
Definition at line 146 of file cgal_domain_control.hpp.
_chosen_levels
template<typename DomainLevel_ > std::deque<std::pair<int,int> > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels protected inherited
chosen level deque
Definition at line 154 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_chosen_levels(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_levels(), and FEAT::Control::Domain::AdaptivePartiDomainControl< DomainLevel_, TemplateSet_ >::refine_partially().
_comm
const Dist::Comm& FEAT::Control::Domain::DomainControl< DomainLevel_ >::_comm protected inherited
Definition at line 469 of file domain_control.hpp.
_create_stage
template<typename DomainLevel_ > int FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_stage protected
creation stage to keep track what has already been initialized
Definition at line 124 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_base_mesh_3d(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::set_base_mesh().
_desired_levels
template<typename DomainLevel_ > std::deque<std::pair<int,int> > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels protected inherited
desired level deque
Definition at line 151 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_scattered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_desired_levels(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_min(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_levels(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels().
_genetic_time_init
template<typename DomainLevel_ > double FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init protected inherited
time for genetic partitioner initialization
Definition at line 159 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_genetic_time_mutate
template<typename DomainLevel_ > double FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate protected inherited
time for genetic partitioner mutation
Definition at line 161 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_keep_base_levels
bool FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels protected inherited
keep base-mesh levels on root process?
Definition at line 479 of file domain_control.hpp.
_keep_cgal_wrapper
template<typename DomainLevel_ > bool FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_keep_cgal_wrapper protected
specifies whether to keep the voxel map after hierarchy creation
Definition at line 141 of file cgal_domain_control.hpp.
_layer_levels
std::deque<std::deque<std::shared_ptr<LevelType> > > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_layer_levels protected inherited
Definition at line 473 of file domain_control.hpp.
_layers
std::deque<std::shared_ptr<LayerType> > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_layers protected inherited
Definition at line 471 of file domain_control.hpp.
_num_global_layers
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::_num_global_layers protected inherited
Definition at line 475 of file domain_control.hpp.
_required_elems_per_rank
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank protected inherited
required number of elements per rank for a-posteriori partitioning
Definition at line 157 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_support_multi_layered
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_support_multi_layered protected inherited
support multi-layered hierarchy?
Definition at line 148 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_hierarchy(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy().
_unstructered_mesh
template<typename DomainLevel_ > bool FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_unstructered_mesh = false protected
specifies whether we use a non voxel base mesh
Definition at line 144 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_create_single_process(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_extract_patch_layering().
_virt_levels
std::deque<VirtLevelType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::_virt_levels protected inherited
Definition at line 474 of file domain_control.hpp.
_virt_size
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::_virt_size protected inherited
Definition at line 476 of file domain_control.hpp.
_was_created
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created protected inherited
specifies whether the domain control was already created
Definition at line 134 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_rectilinear(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_permutation_strategy().
_watch_calc_weights
template<typename DomainLevel_ > StopWatch FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_watch_calc_weights protected
Definition at line 138 of file cgal_domain_control.hpp.
_watch_create_base_mesh
template<typename DomainLevel_ > StopWatch FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_watch_create_base_mesh mutable protected
a bunch of stop-watches
Definition at line 138 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::create_base_mesh_3d(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::get_watch_base_mesh(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::set_base_mesh().
_watch_create_cgal_wrapper
template<typename DomainLevel_ > StopWatch FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_watch_create_cgal_wrapper protected
Definition at line 138 of file cgal_domain_control.hpp.
_watch_create_hierarchy
template<typename DomainLevel_ > StopWatch FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_watch_create_hierarchy protected
Definition at line 138 of file cgal_domain_control.hpp.
shape_dim
template<typename DomainLevel_ > constexpr int FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::shape_dim = MeshType::shape_dim static constexpr
shape dimension
Definition at line 116 of file cgal_domain_control.hpp.
Referenced by FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_base_mesh_layering(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::_deslag_patch_halos(), and FEAT::Control::Domain::CGALDomainControl< DomainLevel_ >::set_base_mesh().
The documentation for this class was generated from the following file:
control/domain/cgal_domain_control.hpp