FEAT: FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ > Class Template Reference
FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ > Class Template Reference
Implementation of ADPSolverBase interface for Global::Matrix instances.
#include <adp_solver_base.hpp>
Public Types
typedef LAFEM::SparseMatrixCSR< DataType, IndexType > ADPMatrixType
the ADP matrix type; this is always a (globally partitioned) CSR matrix
typedef LAFEM::DenseVector< DataType, IndexType > ADPVectorType
the ADP vector type; this is always a (globally partitioned) dense vector
typedef Global::AlgDofPartiSystem< LocalMatrixType, LocalFilterType, MirrorType > AlgDofPartiSystemType
the algebraic dof partitioning system instance for this class
typedef Global::AlgDofParti< LocalVectorType, MirrorType > AlgDofPartiType
the algebraic dof partitioning instance for this class
typedef SolverBase_ BaseClass
our base class
typedef AlgDofPartiType::DataType DataType
our internal data type
typedef GlobalFilterType FilterType
the system filter type; coincides with the global filter type
typedef Global::Filter< LocalFilterType, MirrorType > GlobalFilterType
the global filter type
typedef Global::Matrix< LocalMatrixType, MirrorType, MirrorType > GlobalMatrixType
the global matrix type
typedef Global::Vector< LocalVectorType, MirrorType > GlobalVectorType
the global vector type
typedef AlgDofPartiType::IndexType IndexType
our internal index type
typedef LocalFilter_ LocalFilterType
the local filter type
typedef LocalMatrix_ LocalMatrixType
the local matrix type
typedef LocalMatrixType::VectorTypeL LocalVectorType
the local vector type
typedef GlobalMatrixType MatrixType
the system matrix type; coincides with the global matrix type
typedef Mirror_ MirrorType
the mirror type
typedef GlobalVectorType VectorType
the system vector type; coincides with the global vector type
Public Member Functions
const Dist::Comm * _get_comm () const
virtual void done_symbolic () override
Symbolic finalization.
virtual void init_symbolic () override
Symbolic initialization.
Protected Member Functions
ADPSolverBase (const GlobalMatrixType &matrix, const GlobalFilterType &filter)
protected constructor
template<typename DTV_ >
void _download_vector (GlobalVectorType &vector, const DTV_ *val)
Downloads the ADP vector values from the given array.
template<typename DTV_ >
void _download_vector (LocalVectorType &vector, const DTV_ *val)
Downloads the ADP vector values from the given array.
Index _get_adp_matrix_num_cols () const
Index _get_adp_matrix_num_nzes () const
Index _get_adp_matrix_num_rows () const
Index _get_adp_vector_size () const
Index _get_global_dof_offset () const
Index _get_num_global_dofs () const
Index _get_num_global_nonzeros () const
Index _get_num_owned_dofs () const
template<typename DTV_ , typename RPT_ , typename CIT_ >
void _upload_numeric (DTV_ *val, const RPT_ *row_ptr, const CIT_ *col_idx)
Uploads the (filtered) ADP matrix values to the given array.
template<typename RPT_ , typename CIT_ >
void _upload_symbolic (RPT_ *row_ptr, CIT_ *col_idx)
Uploads the ADP matrix structure to the given arrays.
template<typename DTV_ >
void _upload_vector (DTV_ *val, const GlobalVectorType &vector)
Uploads the ADP vector values to the given array.
template<typename DTV_ >
void _upload_vector (DTV_ *val, const LocalVectorType &vector)
Uploads the ADP vector values to the given array.
Protected Attributes
std::shared_ptr< AlgDofPartiSystemType > _adp_system
the algebraic DOF partitioning
const GlobalFilterType & _system_filter
the global system filter
const GlobalMatrixType & _system_matrix
the global system matrix
Detailed Description
template<typename LocalMatrix_, typename Mirror_, typename LocalFilter_, typename SolverBase_>
class FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >
Implementation of ADPSolverBase interface for Global::Matrix instances.
This class implements the ADPSolverBase interface for Global::Matrix instances, which derive from standard finite element discretizations. Most of the dirty work is outsourced to the Global::AlgDofParti and Global::AlgDofPartiSystem classes.
Author
Peter Zajac
Definition at line 159 of file adp_solver_base.hpp.
Member Typedef Documentation
ADPMatrixType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef LAFEM::SparseMatrixCSR<DataType, IndexType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::ADPMatrixType
the ADP matrix type; this is always a (globally partitioned) CSR matrix
Definition at line 200 of file adp_solver_base.hpp.
ADPVectorType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::ADPVectorType
the ADP vector type; this is always a (globally partitioned) dense vector
Definition at line 202 of file adp_solver_base.hpp.
AlgDofPartiSystemType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef Global::AlgDofPartiSystem<LocalMatrixType, LocalFilterType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::AlgDofPartiSystemType
the algebraic dof partitioning system instance for this class
Definition at line 192 of file adp_solver_base.hpp.
AlgDofPartiType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef Global::AlgDofParti<LocalVectorType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::AlgDofPartiType
the algebraic dof partitioning instance for this class
Definition at line 190 of file adp_solver_base.hpp.
BaseClass
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef SolverBase_ FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::BaseClass
our base class
Definition at line 180 of file adp_solver_base.hpp.
DataType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef AlgDofPartiType::DataType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::DataType
our internal data type
Definition at line 195 of file adp_solver_base.hpp.
FilterType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef GlobalFilterType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::FilterType
the system filter type; coincides with the global filter type
Definition at line 187 of file adp_solver_base.hpp.
GlobalFilterType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef Global::Filter<LocalFilterType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::GlobalFilterType
the global filter type
Definition at line 177 of file adp_solver_base.hpp.
GlobalMatrixType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef Global::Matrix<LocalMatrixType, MirrorType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::GlobalMatrixType
the global matrix type
Definition at line 173 of file adp_solver_base.hpp.
GlobalVectorType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef Global::Vector<LocalVectorType, MirrorType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::GlobalVectorType
the global vector type
Definition at line 175 of file adp_solver_base.hpp.
IndexType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef AlgDofPartiType::IndexType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::IndexType
our internal index type
Definition at line 197 of file adp_solver_base.hpp.
LocalFilterType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef LocalFilter_ FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::LocalFilterType
the local filter type
Definition at line 168 of file adp_solver_base.hpp.
LocalMatrixType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef LocalMatrix_ FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::LocalMatrixType
the local matrix type
Definition at line 164 of file adp_solver_base.hpp.
LocalVectorType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef LocalMatrixType::VectorTypeL FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::LocalVectorType
the local vector type
Definition at line 166 of file adp_solver_base.hpp.
MatrixType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef GlobalMatrixType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::MatrixType
the system matrix type; coincides with the global matrix type
Definition at line 183 of file adp_solver_base.hpp.
MirrorType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef Mirror_ FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::MirrorType
the mirror type
Definition at line 170 of file adp_solver_base.hpp.
VectorType
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > typedef GlobalVectorType FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::VectorType
the system vector type; coincides with the global vector type
Definition at line 185 of file adp_solver_base.hpp.
Constructor & Destructor Documentation
ADPSolverBase()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::ADPSolverBase (const GlobalMatrixType & matrix, const GlobalFilterType & filter) inline explicit protected
protected constructor
Parameters
[in] matrix A resident reference to the system matrix
[in] filter A resident reference to the system filter
Definition at line 221 of file adp_solver_base.hpp.
Member Function Documentation
_download_vector() [1/2]
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_download_vector (GlobalVectorType & vector, const DTV_ * val) inline protected
Downloads the ADP vector values from the given array.
Parameters
[in,out] vector A transient reference to the global vector that receives the downloaded ADP value array. It is assumed to be allocated to the correct size, but its contents on entry are ignored.
[in] val A transient pointer to an array of length _get_adp_vector_size() that contains the ADP values that are to be downloaded to the output vector given by vector.
Definition at line 397 of file adp_solver_base.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::local().
_download_vector() [2/2]
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_download_vector (LocalVectorType & vector, const DTV_ * val) inline protected
Downloads the ADP vector values from the given array.
Parameters
[in,out] vector A transient reference to the local vector that receives the downloaded ADP value array. It is assumed to be allocated to the correct size, but its contents on entry are ignored.
[in] val A transient pointer to an array of length _get_adp_vector_size() that contains the ADP values that are to be downloaded to the output vector given by vector.
Definition at line 414 of file adp_solver_base.hpp.
_get_adp_matrix_num_cols()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_adp_matrix_num_cols () const inline protected
Returns
The number of columns of the local ADP matrix; equal to _get_num_global_dofs()
Definition at line 278 of file adp_solver_base.hpp.
_get_adp_matrix_num_nzes()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_adp_matrix_num_nzes () const inline protected
Returns
The number of nonzero entries of the local ADP matrix
Definition at line 284 of file adp_solver_base.hpp.
_get_adp_matrix_num_rows()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_adp_matrix_num_rows () const inline protected
Returns
The number of rows of the local ADP matrix; equal to _get_num_owned_dofs()
Definition at line 272 of file adp_solver_base.hpp.
_get_adp_vector_size()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_adp_vector_size () const inline protected
Returns
The size of the local ADP vector; equal to _get_num_owned_dofs()
Definition at line 266 of file adp_solver_base.hpp.
_get_comm()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > const Dist::Comm * FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_comm () const inline
Returns
A pointer to the underlying communicator
Definition at line 231 of file adp_solver_base.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_comm().
_get_global_dof_offset()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_global_dof_offset () const inline protected
Returns
The index of the first global DOF owned by this process
Definition at line 308 of file adp_solver_base.hpp.
_get_num_global_dofs()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_num_global_dofs () const inline protected
Returns
The total number of global DOFs on all processes
Definition at line 296 of file adp_solver_base.hpp.
_get_num_global_nonzeros()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_num_global_nonzeros () const inline protected
Returns
The total number of nonzero entries of the global ADP matrix
Definition at line 290 of file adp_solver_base.hpp.
_get_num_owned_dofs()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > Index FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_get_num_owned_dofs () const inline protected
Returns
The number of global DOFs owned by this process
Definition at line 302 of file adp_solver_base.hpp.
_upload_numeric()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > template<typename DTV_ , typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_upload_numeric (DTV_ * val, const RPT_ * row_ptr, const CIT_ * col_idx) inline protected
Uploads the (filtered) ADP matrix values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the filtered matrix values of the local ADP matrix.
[in] row_ptr A transient pointer to the row-pointer array of the ADP matrix as returned by the _upload_symbolic() function.
[in] col_idx A transient pointer to the column-index array of the ADP matrix as returned by the _upload_symbolic() function.
Definition at line 346 of file adp_solver_base.hpp.
_upload_symbolic()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > template<typename RPT_ , typename CIT_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_upload_symbolic (RPT_ * row_ptr, CIT_ * col_idx) inline protected
Uploads the ADP matrix structure to the given arrays.
Parameters
[out] row_ptr A transient pointer to an array of length _get_adp_matrix_num_rows()+1 that receives the the row-pointer array of the ADP matrix.
[out] col_idx A transient pointer to an array of length _get_adp_matrix_num_nzes() that receives the column index array of the ADP matrix.
Definition at line 325 of file adp_solver_base.hpp.
_upload_vector() [1/2]
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_upload_vector (DTV_ * val, const GlobalVectorType & vector) inline protected
Uploads the ADP vector values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_vector_size() that receives the local ADP values of the input vector given by vector.
[in] vector A transient reference to the global vector that is to be uploaded to the ADP value array.
Definition at line 364 of file adp_solver_base.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::local().
_upload_vector() [2/2]
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > template<typename DTV_ > void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_upload_vector (DTV_ * val, const LocalVectorType & vector) inline protected
Uploads the ADP vector values to the given array.
Parameters
[out] val A transient pointer to an array of length _get_adp_vector_size() that receives the local ADP values of the input vector given by vector.
[in] vector A transient reference to the local vector that is to be uploaded to the ADP value array.
Definition at line 380 of file adp_solver_base.hpp.
done_symbolic()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > virtual void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::done_symbolic () inline override virtual
Symbolic finalization.
This function releases all data allocated during the symbolic initialization phase.
Definition at line 257 of file adp_solver_base.hpp.
init_symbolic()
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > virtual void FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::init_symbolic () inline override virtual
Symbolic initialization.
This function performs the symbolic initialization of the algebraic DOF partitioning, which pre-computes the actual algebraic DOF partitioning. After this function call, the derived class has to call the corresponding upload functions to retrieve the ADP matrix arrays.
Definition at line 243 of file adp_solver_base.hpp.
Member Data Documentation
_adp_system
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > std::shared_ptr<AlgDofPartiSystemType> FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_adp_system protected
the algebraic DOF partitioning
Definition at line 210 of file adp_solver_base.hpp.
_system_filter
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > const GlobalFilterType& FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_system_filter protected
the global system filter
Definition at line 208 of file adp_solver_base.hpp.
_system_matrix
template<typename LocalMatrix_ , typename Mirror_ , typename LocalFilter_ , typename SolverBase_ > const GlobalMatrixType& FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ >, SolverBase_ >::_system_matrix protected
the global system matrix
Definition at line 206 of file adp_solver_base.hpp.
The documentation for this class was generated from the following file:
kernel/solver/adp_solver_base.hpp