FEAT: FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ > Class Template Reference
FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ > Class Template Reference
Burgers assembly job for block right-hand-side vector.
#include <burgers_assembly_job.hpp>
Classes
class Task
the actual assembly task
Public Types
typedef BurgersAssemblyJobBase< DataType, Space_, ConvVector_ > BaseClass
our base class
typedef ConvVector_ ConvVectorType
the convection vector type
typedef VectorType::DataType DataType
the data type
typedef Space_ SpaceType
the space type
typedef Vector_ VectorType
the vector type
Public Member Functions
BurgersBlockedVectorAssemblyJob (Vector_ &rhs_vector_, const Vector_ &sol_vector_, const ConvVector_ &conv_vector, const Space_ &space_, const String &cubature_name)
Constructor.
template<typename VectorType_ >
void set_sd_v_norm (const VectorType_ &convect)
Sets the convection field norm \(\|v\|_\Omega\) for the local streamline diffusion parameter delta_T.
Static Public Member Functions
template<typename LocalVector_ , typename Mirror_ >
static DataType calc_sd_v_norm (const Global::Vector< LocalVector_, Mirror_ > &convect)
Calculates the convection field norm \(\|v\|_\Omega\) for the streamline diffusion parameter delta_T.
template<typename IndexType_ , int conv_dim_>
static DataType calc_sd_v_norm (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, conv_dim_ > &convect)
Calculates the convection field norm \(\|v\|_\Omega\) for the local streamline diffusion parameter delta_T.
Public Attributes
DataType_ beta
scaling parameter for convective operator K
const ConvVector_ & convection_vector
the convection vector to be used
Cubature::DynamicFactory cubature_factory
the cubature factory to use
bool deformation
specifies whether to use the deformation tensor
DataType_ frechet_beta
scaling parameter for Frechet derivative of convective operator K'
DataType_ nu
scaling parameter for diffusive operator L (aka viscosity)
DataType_ sd_delta
scaling parameter for streamline diffusion stabilization operator S
DataType_ sd_nu
viscosity parameter nu_S for streamline diffusion (usually equal to nu)
DataType_ sd_v_norm
velocity norm for streamline diffusion
const Space_ & space
the test-/trial-space to be used
DataType_ theta
scaling parameter for reactive operator M
VectorType & vector_rhs
the RHS vector to be assembled
const VectorType & vector_sol
the solution vector
Static Public Attributes
static constexpr int block_size = Vector_::BlockSize
the block size
Detailed Description
template<typename Vector_, typename Space_, typename ConvVector_ = Vector_>
class FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >
Burgers assembly job for block right-hand-side vector.
This assembly job implements the blocked (i.e. vector-valued) Burgers operator assembly, which is assembled into a right-hand-side vector.
See the documentation of the BurgersAssemblyJobBase class template (which is a base class of this class) for details about the terms and coefficients offered by this assembly job.
Template Parameters
Vector_ The type of the blocked vector that is to be assembled.
Space_ The finite element space to be used for assembly
ConvVector_ The type of the convection (velocity) vector field; usually identical to Vector_
Author
Peter Zajac
Definition at line 856 of file burgers_assembly_job.hpp.
Member Typedef Documentation
BaseClass
template<typename Vector_ , typename Space_ , typename ConvVector_ = Vector_> typedef BurgersAssemblyJobBase<DataType, Space_, ConvVector_> FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >::BaseClass
our base class
Definition at line 866 of file burgers_assembly_job.hpp.
ConvVectorType
template<typename DataType_ , typename Space_ , typename ConvVector_ > typedef ConvVector_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::ConvVectorType inherited
the convection vector type
Definition at line 111 of file burgers_assembly_job.hpp.
DataType
template<typename Vector_ , typename Space_ , typename ConvVector_ = Vector_> typedef VectorType::DataType FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >::DataType
the data type
Definition at line 863 of file burgers_assembly_job.hpp.
SpaceType
template<typename DataType_ , typename Space_ , typename ConvVector_ > typedef Space_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::SpaceType inherited
the space type
Definition at line 108 of file burgers_assembly_job.hpp.
VectorType
template<typename Vector_ , typename Space_ , typename ConvVector_ = Vector_> typedef Vector_ FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >::VectorType
the vector type
Definition at line 861 of file burgers_assembly_job.hpp.
Constructor & Destructor Documentation
BurgersBlockedVectorAssemblyJob()
template<typename Vector_ , typename Space_ , typename ConvVector_ = Vector_> FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >::BurgersBlockedVectorAssemblyJob (Vector_ & rhs_vector_, const Vector_ & sol_vector_, const ConvVector_ & conv_vector, const Space_ & space_, const String & cubature_name) inline explicit
Constructor.
Parameters
[in,out] rhs_vector_ A resident reference to the RHS vector that is to be assembled.
[in] sol_vector_ A resident reference to the solution vector that the matrix is to be multiplied by. May be the same object as conv_vector, but must not be the same as rhs_vector_.
[in] conv_vector A resident reference to the convection field vector. May be the same object as sol_vector, but must not be the same as rhs_vector_.
[in] space_ A resident reference to the space that is be used for assembly.
[in] cubature_name The name of the cubature rule to be used for assembly.
Definition at line 898 of file burgers_assembly_job.hpp.
References XASSERTM.
Member Function Documentation
calc_sd_v_norm() [1/2]
template<typename DataType_ , typename Space_ , typename ConvVector_ > template<typename LocalVector_ , typename Mirror_ > static DataType FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm (const Global::Vector< LocalVector_, Mirror_ > & convect) inline static inherited
Calculates the convection field norm \(\|v\|_\Omega\) for the streamline diffusion parameter delta_T.
Note
This function automatically syncs the norm over all processes by using the vector's gate.
Parameters
[in] convect The transient (global) convection field vector.
Returns
The convection vector field norm.
Definition at line 206 of file burgers_assembly_job.hpp.
References FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm(), FEAT::Global::Vector< LocalVector_, Mirror_ >::get_gate(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::max().
calc_sd_v_norm() [2/2]
template<typename DataType_ , typename Space_ , typename ConvVector_ > template<typename IndexType_ , int conv_dim_> static DataType FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, conv_dim_ > & convect) inline static inherited
Calculates the convection field norm \(\|v\|_\Omega\) for the local streamline diffusion parameter delta_T.
Parameters
[in] convect The transient (local) convection field vector.
Returns
The convection vector field norm.
Definition at line 184 of file burgers_assembly_job.hpp.
References FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::Math::max(), and FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size().
Referenced by FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm(), and FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::set_sd_v_norm().
set_sd_v_norm()
template<typename DataType_ , typename Space_ , typename ConvVector_ > template<typename VectorType_ > void FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::set_sd_v_norm (const VectorType_ & convect) inline inherited
Sets the convection field norm \(\|v\|_\Omega\) for the local streamline diffusion parameter delta_T.
Parameters
[in] convect The transient (local) convection field vector.
Definition at line 222 of file burgers_assembly_job.hpp.
References FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm().
Member Data Documentation
beta
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::beta inherited
scaling parameter for convective operator K
Definition at line 123 of file burgers_assembly_job.hpp.
block_size
template<typename Vector_ , typename Space_ , typename ConvVector_ = Vector_> constexpr int FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >::block_size = Vector_::BlockSize static constexpr
the block size
Definition at line 869 of file burgers_assembly_job.hpp.
convection_vector
template<typename DataType_ , typename Space_ , typename ConvVector_ > const ConvVector_& FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::convection_vector inherited
the convection vector to be used
Definition at line 138 of file burgers_assembly_job.hpp.
cubature_factory
template<typename DataType_ , typename Space_ , typename ConvVector_ > Cubature::DynamicFactory FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::cubature_factory inherited
the cubature factory to use
Definition at line 144 of file burgers_assembly_job.hpp.
deformation
template<typename DataType_ , typename Space_ , typename ConvVector_ > bool FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::deformation inherited
specifies whether to use the deformation tensor
Definition at line 114 of file burgers_assembly_job.hpp.
frechet_beta
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::frechet_beta inherited
scaling parameter for Frechet derivative of convective operator K'
Definition at line 126 of file burgers_assembly_job.hpp.
nu
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::nu inherited
scaling parameter for diffusive operator L (aka viscosity)
Definition at line 117 of file burgers_assembly_job.hpp.
sd_delta
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::sd_delta inherited
scaling parameter for streamline diffusion stabilization operator S
Definition at line 129 of file burgers_assembly_job.hpp.
sd_nu
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::sd_nu inherited
viscosity parameter nu_S for streamline diffusion (usually equal to nu)
Definition at line 132 of file burgers_assembly_job.hpp.
sd_v_norm
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::sd_v_norm inherited
velocity norm for streamline diffusion
Definition at line 135 of file burgers_assembly_job.hpp.
space
template<typename DataType_ , typename Space_ , typename ConvVector_ > const Space_& FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::space inherited
the test-/trial-space to be used
Definition at line 141 of file burgers_assembly_job.hpp.
theta
template<typename DataType_ , typename Space_ , typename ConvVector_ > DataType_ FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::theta inherited
scaling parameter for reactive operator M
Definition at line 120 of file burgers_assembly_job.hpp.
vector_rhs
template<typename Vector_ , typename Space_ , typename ConvVector_ = Vector_> VectorType& FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >::vector_rhs
the RHS vector to be assembled
Definition at line 872 of file burgers_assembly_job.hpp.
vector_sol
template<typename Vector_ , typename Space_ , typename ConvVector_ = Vector_> const VectorType& FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >::vector_sol
the solution vector
Definition at line 875 of file burgers_assembly_job.hpp.
The documentation for this class was generated from the following file:
kernel/assembly/burgers_assembly_job.hpp