FEAT: FEAT::Meshopt::ConcentrationFunctionDefault< DT_ > Class Template Reference
FEAT::Meshopt::ConcentrationFunctionDefault< DT_ > Class Template Reference
Default elemental distance concentration function.
#include <mesh_concentration_function.hpp>
Public Types
typedef DT_ DataType
Floating point precision.
Public Member Functions
ConcentrationFunctionDefault ()
Default constructor.
ConcentrationFunctionDefault (const ConcentrationFunctionDefault &other)
Copy constructor.
virtual ~ConcentrationFunctionDefault ()
Empty destructor.
DataType conc_der (DT_ dist) const
Computes the derivative of the concentration according to a distance.
DataType conc_val (DT_ dist) const
Computes the concentration according to a distance.
virtual String info () const
Prints relevant information.
Static Public Member Functions
static String name ()
Returns a descriptive String.
Public Attributes
const bool use_derivative
Does this utilize the derivative of the input wrt. some other DoF?
Detailed Description
template<typename DT_>
class FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >
Default elemental distance concentration function.
Template Parameters
DT_ Floating point precision
This maps a signed distance to a concentration, leaving the derivative zero.
Definition at line 1627 of file mesh_concentration_function.hpp.
Member Typedef Documentation
DataType
template<typename DT_ > typedef DT_ FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::DataType
Floating point precision.
Definition at line 1631 of file mesh_concentration_function.hpp.
Constructor & Destructor Documentation
ConcentrationFunctionDefault() [1/2]
template<typename DT_ > FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::ConcentrationFunctionDefault () inline explicit
Default constructor.
This sets use_derivative to false.
Definition at line 1641 of file mesh_concentration_function.hpp.
ConcentrationFunctionDefault() [2/2]
template<typename DT_ > FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::ConcentrationFunctionDefault (const ConcentrationFunctionDefault< DT_ > & other) inline
Copy constructor.
Parameters
[in] other Object to be copied.
Definition at line 1653 of file mesh_concentration_function.hpp.
~ConcentrationFunctionDefault()
template<typename DT_ > virtual FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::~ConcentrationFunctionDefault () inline virtual
Empty destructor.
Definition at line 1661 of file mesh_concentration_function.hpp.
Member Function Documentation
conc_der()
template<typename DT_ > DataType FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::conc_der (DT_ dist) const inline
Computes the derivative of the concentration according to a distance.
Parameters
[in] dist The input parameter
Returns
0.
Definition at line 1711 of file mesh_concentration_function.hpp.
conc_val()
template<typename DT_ > DataType FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::conc_val (DT_ dist) const inline
Computes the concentration according to a distance.
Parameters
[in] dist The input parameter
Returns
Definition at line 1698 of file mesh_concentration_function.hpp.
References FEAT::Math::abs().
info()
template<typename DT_ > virtual String FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::info () const inline virtual
Prints relevant information.
Definition at line 1678 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::name(), FEAT::String::pad_back(), FEAT::stringify(), and FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::use_derivative.
name()
template<typename DT_ > static String FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::name () inline static
Returns a descriptive String.
Returns
The class name as String.
Definition at line 1670 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::info().
Member Data Documentation
use_derivative
template<typename DT_ > const bool FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::use_derivative
Does this utilize the derivative of the input wrt. some other DoF?
Definition at line 1634 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::info().
The documentation for this class was generated from the following file:
kernel/meshopt/mesh_concentration_function.hpp