FEAT: FEAT::Global::SynchVectorTicket< VT_, VMT_ > Class Template Reference
FEAT::Global::SynchVectorTicket< VT_, VMT_ > Class Template Reference
Ticket class for asynchronous global operations on vectors.
#include <synch_vec.hpp>
Public Types
using BufferType = LAFEM::DenseVector< typename VT_::DataType, typename VT_::IndexType >
the buffer vector type
Public Member Functions
SynchVectorTicket ()
default constructor
SynchVectorTicket (const SynchVectorTicket &)=delete
Unwanted copy constructor: Do not implement!
SynchVectorTicket (SynchVectorTicket &&other)
move constructor
SynchVectorTicket (VT_ &target, const Dist::Comm &comm, const std::vector< int > &ranks, const std::vector< VMT_ > &mirrors)
Constructor.
~SynchVectorTicket ()
Destructor.
SynchVectorTicket & operator= (const SynchVectorTicket &)=delete
Unwanted copy assignment operator: Do not implement!
SynchVectorTicket & operator= (SynchVectorTicket &&other)
move-assign operator
void wait ()
wait method
Protected Attributes
const Dist::Comm * _comm
our communicator
bool _finished
signals, whether wait was already called
const std::vector< VMT_ > * _mirrors
the vector mirrors
std::vector< BufferType > _recv_bufs
Dist::RequestVector _recv_reqs
std::vector< BufferType > _send_bufs
send and receive buffers
Dist::RequestVector _send_reqs
send and receive request vectors
VT_ * _target
the vector to be synchronized
Detailed Description
template<typename VT_, typename VMT_>
class FEAT::Global::SynchVectorTicket< VT_, VMT_ >
Ticket class for asynchronous global operations on vectors.
Todo:
statistics
Author
Dirk Ribbrock, Peter Zajac
Definition at line 28 of file synch_vec.hpp.
Member Typedef Documentation
BufferType
template<typename VT_ , typename VMT_ > using FEAT::Global::SynchVectorTicket< VT_, VMT_ >::BufferType = LAFEM::DenseVector<typename VT_::DataType, typename VT_::IndexType>
the buffer vector type
Definition at line 32 of file synch_vec.hpp.
Constructor & Destructor Documentation
SynchVectorTicket() [1/3]
template<typename VT_ , typename VMT_ > FEAT::Global::SynchVectorTicket< VT_, VMT_ >::SynchVectorTicket () inline
default constructor
Definition at line 53 of file synch_vec.hpp.
SynchVectorTicket() [2/3]
template<typename VT_ , typename VMT_ > FEAT::Global::SynchVectorTicket< VT_, VMT_ >::SynchVectorTicket (VT_ & target, const Dist::Comm & comm, const std::vector< int > & ranks, const std::vector< VMT_ > & mirrors) inline
Constructor.
Parameters
[in,out] target The type-0 vector to be synchronized
[in] comm The communicator
[in] ranks The neighbor ranks within the communicator
[in] mirrors The vector mirrors to be used for synchronization
Definition at line 85 of file synch_vec.hpp.
References FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_comm, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_mirrors, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_send_bufs, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_send_reqs, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_target, FEAT::TimeStamp::elapsed_now(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Dist::RequestVector::push_back(), FEAT::Dist::RequestVector::reserve(), and XASSERTM.
SynchVectorTicket() [3/3]
template<typename VT_ , typename VMT_ > FEAT::Global::SynchVectorTicket< VT_, VMT_ >::SynchVectorTicket (SynchVectorTicket< VT_, VMT_ > && other) inline
move constructor
Definition at line 138 of file synch_vec.hpp.
~SynchVectorTicket()
template<typename VT_ , typename VMT_ > FEAT::Global::SynchVectorTicket< VT_, VMT_ >::~SynchVectorTicket () inline
Destructor.
Definition at line 219 of file synch_vec.hpp.
References FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_finished, and XASSERTM.
Member Function Documentation
operator=()
template<typename VT_ , typename VMT_ > SynchVectorTicket & FEAT::Global::SynchVectorTicket< VT_, VMT_ >::operator= (SynchVectorTicket< VT_, VMT_ > && other) inline
move-assign operator
Definition at line 162 of file synch_vec.hpp.
References FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_comm, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_finished, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_mirrors, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_send_bufs, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_send_reqs, and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_target.
wait()
template<typename VT_ , typename VMT_ > void FEAT::Global::SynchVectorTicket< VT_, VMT_ >::wait () inline
wait method
wait for completion barrier on return, the target vector has been updated
Definition at line 195 of file synch_vec.hpp.
References FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_finished, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_mirrors, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_send_reqs, FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_target, FEAT::TimeStamp::elapsed_now(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERTM.
Referenced by FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1().
Member Data Documentation
_comm
template<typename VT_ , typename VMT_ > const Dist::Comm* FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_comm protected
our communicator
Definition at line 42 of file synch_vec.hpp.
Referenced by FEAT::Global::SynchVectorTicket< VT_, VMT_ >::SynchVectorTicket(), and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::operator=().
_finished
template<typename VT_ , typename VMT_ > bool FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_finished protected
signals, whether wait was already called
Definition at line 36 of file synch_vec.hpp.
Referenced by FEAT::Global::SynchVectorTicket< VT_, VMT_ >::~SynchVectorTicket(), FEAT::Global::SynchVectorTicket< VT_, VMT_ >::operator=(), and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::wait().
_mirrors
template<typename VT_ , typename VMT_ > const std::vector<VMT_>* FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_mirrors protected
the vector mirrors
Definition at line 44 of file synch_vec.hpp.
Referenced by FEAT::Global::SynchVectorTicket< VT_, VMT_ >::SynchVectorTicket(), FEAT::Global::SynchVectorTicket< VT_, VMT_ >::operator=(), and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::wait().
_recv_bufs
template<typename VT_ , typename VMT_ > std::vector<BufferType> FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_recv_bufs protected
Definition at line 48 of file synch_vec.hpp.
_recv_reqs
template<typename VT_ , typename VMT_ > Dist::RequestVector FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_recv_reqs protected
Definition at line 46 of file synch_vec.hpp.
_send_bufs
template<typename VT_ , typename VMT_ > std::vector<BufferType> FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_send_bufs protected
send and receive buffers
Definition at line 48 of file synch_vec.hpp.
Referenced by FEAT::Global::SynchVectorTicket< VT_, VMT_ >::SynchVectorTicket(), and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::operator=().
_send_reqs
template<typename VT_ , typename VMT_ > Dist::RequestVector FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_send_reqs protected
send and receive request vectors
Definition at line 46 of file synch_vec.hpp.
Referenced by FEAT::Global::SynchVectorTicket< VT_, VMT_ >::SynchVectorTicket(), FEAT::Global::SynchVectorTicket< VT_, VMT_ >::operator=(), and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::wait().
_target
template<typename VT_ , typename VMT_ > VT_* FEAT::Global::SynchVectorTicket< VT_, VMT_ >::_target protected
the vector to be synchronized
Definition at line 40 of file synch_vec.hpp.
Referenced by FEAT::Global::SynchVectorTicket< VT_, VMT_ >::SynchVectorTicket(), FEAT::Global::SynchVectorTicket< VT_, VMT_ >::operator=(), and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::wait().
The documentation for this class was generated from the following file:
kernel/global/synch_vec.hpp