FEAT: FEAT::LAFEM::DenseVector< DT_, IT_ > Class Template Reference
FEAT::LAFEM::DenseVector< DT_, IT_ > Class Template Reference
Dense data vector class template.
#include <dense_vector.hpp>
Classes
class GatherAxpy
Gather-Axpy operation for DenseVector.
class ScatterAxpy
Scatter-Axpy operation for DenseVector.
Public Types
template<typename DT2_ = DT_, typename IT2_ = IT_>
using ContainerType = DenseVector< DT2_, IT2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a vector container with new Datatape and Index types
typedef DT_ DataType
Our datatype.
typedef IT_ IndexType
Our indextype.
typedef DT_ ValueType
Our value type.
Public Member Functions
DenseVector ()
Constructor.
DenseVector (const DenseVector &dv_in, Index size_in, Index offset_in)
Constructor.
template<int BS_>
DenseVector (const DenseVectorBlocked< DT_, IT_, BS_ > &other)
Constructor.
DenseVector (DenseVector &&other)
Move Constructor.
DenseVector (FileMode mode, std::istream &file)
Constructor.
DenseVector (FileMode mode, String filename)
Constructor.
DenseVector (Index size_in)
Constructor.
DenseVector (Index size_in, DT_ *data)
Constructor.
DenseVector (Index size_in, DT_ value)
Constructor.
DenseVector (Random &rng, Index size_in, DataType min, DataType max)
Constructor.
template<typename DT2_ = DT_, typename IT2_ = IT_>
DenseVector (std::vector< char > input)
Constructor.
virtual ~DenseVector ()
Destructor.
std::size_t bytes () const
Returns the total amount of bytes allocated.
virtual void clear ()
Free all allocated arrays.
DenseVector clone (CloneMode clone_mode=CloneMode::Deep) const
Clone operation.
void clone (const Container &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const Container< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const DenseVector< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Deep)
Clone operation.
template<typename DT2_ , typename IT2_ >
void convert (const DenseVector< DT2_, IT2_ > &other)
Conversion method.
template<typename DT2_ , typename IT2_ , int BS2_>
void convert (const DenseVectorBlocked< DT2_, IT2_, BS2_ > &other)
Conversion method.
template<typename VT_ >
void convert (const VT_ &a)
Conversion method.
void copy (const DenseVector &x, bool full=false)
Performs \(this \leftarrow x\).
template<typename VT_ >
void copy (const VT_ &a)
Performs \(this \leftarrow x\).
template<typename VT_ >
void copy_inv (VT_ &a) const
Performs \(x \leftarrow this\).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void deserialize (std::vector< char > input)
Deserialization of complete container entity.
template<Perspective = Perspective::native>
DT_ * elements ()
Get a pointer to the data array.
template<Perspective = Perspective::native>
DT_ const * elements () const
bool empty () const
Checks whether the container is empty.
void format (DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DT_ min, DT_ max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (const LAFEM::SerialConfig &config)
Calculate size.
const std::vector< DT_ * > & get_elements () const
Returns a list of all data arrays.
const std::vector< Index > & get_elements_size () const
Returns a list of all data array sizes.
const std::vector< IT_ * > & get_indices () const
Returns a list of all Index arrays.
const std::vector< Index > & get_indices_size () const
Returns a list of all Index array sizes.
const std::vector< DT_ > & get_scalar_dt () const
Returns a list of all scalar values with datatype dt.
const std::vector< Index > & get_scalar_index () const
Returns a list of all scalar values with datatype index.
template<int BlockSize_>
DenseVectorBlocked< DT_, IT_, BlockSize_ > inflate_to_blocks ()
Expand DenseVector to DenseVectorBlocked.
void move (Container &&other)
Assignment move operation.
const DT_ operator() (Index index) const
Retrieve specific vector element.
void operator() (Index index, DT_ value)
Set specific vector element.
DenseVector & operator= (DenseVector &&other)
Assignment move operator.
void permute (Adjacency::Permutation &perm)
Permutate vector according to the given Permutation.
void read_from (FileMode mode, const String &filename)
Read in vector from file.
void read_from (FileMode mode, std::istream &file)
Read in vector from stream.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > serialize (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Serialization of complete container entity.
std::uint64_t set_checkpoint_data (std::vector< char > &data, const LAFEM::SerialConfig &config)
template<Perspective = Perspective::native>
Index size () const
Returns the containers size.
template<Perspective = Perspective::native>
Index used_elements () const
Returns the number of effective stored elements.
void write_out (FileMode mode, const String &filename) const
Write out vector to file.
void write_out (FileMode mode, std::ostream &file) const
Write out vector to file.
Linear algebra operations
void axpy (const DenseVector &x, const DenseVector &y, const DT_ alpha=DT_(1))
Calculate \(this \leftarrow \alpha~ x + y\).
void component_product (const DenseVector &x, const DenseVector &y)
Calculate \(this_i \leftarrow x_i \cdot y_i\).
void component_invert (const DenseVector &x, const DT_ alpha=DT_(1))
Performs \(this_i \leftarrow \alpha / x_i \).
void scale (const DenseVector &x, const DT_ alpha)
Calculate \(this \leftarrow \alpha~ x \).
DataType triple_dot (const DenseVector &x, const DenseVector &y) const
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
DataType dot (const DenseVector &x) const
Calculate \(result \leftarrow this \cdot x\).
DT_ norm2 () const
Calculates and returns the euclid norm of this vector.
DT_ norm2sqr () const
Calculates and returns the squared euclid norm of this vector.
DT_ max_abs_element () const
Retrieve the absolute maximum value of this vector.
DT_ min_abs_element () const
Retrieve the absolute minimum value of this vector.
DT_ max_element () const
Retrieve the maximum value of this vector.
DT_ min_element () const
Retrieve the minimum value of this vector.
Static Public Member Functions
static String name ()
Returns a descriptive string.
Protected Member Functions
void _copy_content (const Container &other, bool full)
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::istream &file)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::vector< char > &input)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > _serialize (FileMode mode, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _serialize (FileMode mode, std::ostream &file, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::uint64_t _serialized_size (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Calculation of the serialized size with optional compression of complete container entity.
template<typename DT2_ , typename IT2_ >
void assign (const Container< DT2_, IT2_ > &other)
Assignment operation.
Protected Attributes
std::vector< DT_ * > _elements
List of pointers to all datatype dependent arrays.
std::vector< Index > _elements_size
List of corresponding datatype array sizes.
bool _foreign_memory
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
std::vector< IT_ * > _indices
List of pointers to all IT_ dependent arrays.
std::vector< Index > _indices_size
List of corresponding IT_ array sizes.
std::vector< DT_ > _scalar_dt
List of scalars with datatype DT_.
std::vector< Index > _scalar_index
List of scalars with datatype index.
Friends
std::ostream & operator<< (std::ostream &lhs, const DenseVector &b)
DenseVector streaming operator.
bool operator== (const DenseVector &a, const DenseVector< DT_, IT_ > &b)
DenseVector comparison operator.
Detailed Description
template<typename DT_, typename IT_ = Index>
class FEAT::LAFEM::DenseVector< DT_, IT_ >
Dense data vector class template.
Template Parameters
DT_ The datatype to be used.
IT_ The indextype to be used.
This class represents a vector of continuous data in memory.
Data survey:
_elements[0]: raw number values
_scalar_index[0]: container size
Refer to LAFEM design description for general usage informations.
Author
Dirk Ribbrock
Definition at line 58 of file dense_vector.hpp.
Member Typedef Documentation
ContainerType
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::DenseVector< DT_, IT_ >::ContainerType = DenseVector<DT2_, IT2_>
Our 'base' class type.
Definition at line 148 of file dense_vector.hpp.
ContainerTypeByDI
template<typename DT_ , typename IT_ = Index> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::DenseVector< DT_, IT_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a vector container with new Datatape and Index types
Definition at line 152 of file dense_vector.hpp.
DataType
template<typename DT_ , typename IT_ = Index> typedef DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::DataType
Our datatype.
Definition at line 141 of file dense_vector.hpp.
IndexType
template<typename DT_ , typename IT_ = Index> typedef IT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::IndexType
Our indextype.
Definition at line 143 of file dense_vector.hpp.
ValueType
template<typename DT_ , typename IT_ = Index> typedef DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::ValueType
Our value type.
Definition at line 145 of file dense_vector.hpp.
Constructor & Destructor Documentation
DenseVector() [1/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector () inline explicit
Constructor.
Creates an empty non dimensional vector.
Definition at line 159 of file dense_vector.hpp.
DenseVector() [2/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (Index size_in) inline explicit
Constructor.
Parameters
[in] size_in The size of the created vector.
Creates a vector with a given size.
Definition at line 171 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, and FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
DenseVector() [3/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (Index size_in, DT_ value) inline explicit
Constructor.
Parameters
[in] size_in The size of the created vector.
[in] value The value, each element will be set to.
Creates a vector with given size and value.
Definition at line 190 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::MemoryPool::set_memory().
DenseVector() [4/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (Index size_in, DT_ * data) inline explicit
Constructor.
Parameters
[in] size_in The size of the created vector.
[in] data An array containing the value data.
Creates a vector with given size and given data.
Note
The array must be allocated by FEAT's own memory pool
Obviously, the pointer must point to data in the same memory.
Warning
If you use a data pointer from another container, both containers will be able to modify the array and will effect the other container, as they share one and the same array.
Definition at line 217 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::increase_memory().
DenseVector() [5/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (const DenseVector< DT_, IT_ > & dv_in, Index size_in, Index offset_in) inline explicit
Constructor.
Parameters
[in] dv_in The source DenseVector
[in] size_in The size of the created vector range.
[in] offset_in The starting element of the created vector range in relation to the source vector.
Creates a vector range from a given DenseVector
Note
The created DenseVector has no own memory management nor own allocated memory and should be used carefully!
Definition at line 243 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), XASSERT, and XASSERTM.
DenseVector() [6/11]
template<typename DT_ , typename IT_ = Index> template<int BS_> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (const DenseVectorBlocked< DT_, IT_, BS_ > & other) inline explicit
Constructor.
Parameters
[in] other The source blocked vector
Creates a vector from a given source blocked vector
Definition at line 264 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
DenseVector() [7/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (FileMode mode, String filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a vector from the given source file.
Definition at line 278 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from().
DenseVector() [8/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (FileMode mode, std::istream & file) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The stream that is to be read from.
Creates a vector from the given source file.
Definition at line 292 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from().
DenseVector() [9/11]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (std::vector< char > input) inline explicit
Constructor.
Parameters
[in] input A std::vector, containing the byte.
Creates a vector from the given byte array.
Definition at line 306 of file dense_vector.hpp.
DenseVector() [10/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (Random & rng, Index size_in, DataType min, DataType max) inline explicit
Constructor.
Parameters
[in] rng The random number generator.
[in] size_in The vector size.
[in] min Lower rng bound.
[in] max Upper rng bound.
Creates a vector from the given random number generator.
Definition at line 322 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::LAFEM::Container< DT_, IT_ >::format().
DenseVector() [11/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector (DenseVector< DT_, IT_ > && other) inline
Move Constructor.
Parameters
[in] other The source vector.
Moves another vector to this vector.
Definition at line 341 of file dense_vector.hpp.
~DenseVector()
template<typename DT_ , typename IT_ = Index> virtual FEAT::LAFEM::DenseVector< DT_, IT_ >::~DenseVector () inline virtual
Destructor.
Definition at line 349 of file dense_vector.hpp.
Member Function Documentation
_copy_content()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::_copy_content (const Container< DT_, IT_ > & other, bool full) inline protected inherited
Definition at line 242 of file container.hpp.
_deserialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::istream & file) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file std::istream, pointing to the input data.
Recreate a complete container entity by a single binary file.
Definition at line 782 of file container.hpp.
References XABORTM.
_deserialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::vector< char > & input) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] input A std::vector containing the byte array.
Recreate a complete container entity by a single binary array.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 628 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Pack::decode(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Type::Helper::extract_floatness(), FEAT::Type::Helper::extract_intness(), FEAT::Type::Helper::extract_signedness(), FEAT::Type::Helper::extract_type_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, XABORTM, XASSERT, and XASSERTM.
_serialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
Array data layout:
raw array size in bytes (std::uint64_t)
magic number (std::uint64_t)
DT_ 'hash' value (sizeof(DT_) and floating/integral distinction (packed std::uint64_t)
IT_ 'hash' value (sizeof(IT_) and floating/integral distinction (packed std::uint64_t)
_elements.size() (std::uint64_t)
_indices.size() (std::uint64_t)
_elements_size.size() (std::uint64_t)
_indices_size.size() (std::uint64_t)
_scalar_index.size() (std::uint64_t)
_scalar_dt.size() (std::uint64_t)
_compressed (std::uint64_t)
_elements_size array (std::uint64_t)
_elements arrays byte_size (std::uint64_t) just temporary to read in data
_indices_size array (std::uint64_t)
_indices arrays byte_size (std::uint64_t)
_scalar_index array (std::uint64_t)
_scalar_dt array (DT2_)
_elements arrays (DT2_)
_indices arrays (IT2_)
See FEAT::LAFEM::SerialConfig for details.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 446 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XASSERTM.
_serialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, std::ostream & file, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file The output stream to write data into.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary file with compression enabled. See FEAT::LAFEM::SerialConfig for details.
Definition at line 611 of file container.hpp.
References XABORTM.
_serialized_size()
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline protected inherited
Calculation of the serialized size with optional compression of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Returns
An unsigned int containing the size of serialized container.
Calculate the size of the serialized container entity.
Definition at line 363 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), and FEAT::LAFEM::indices_zlib.
assign()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::assign (const Container< DT2_, IT2_ > & other) inline protected inherited
Assignment operation.
Assigns contents of another container
Parameters
[in] other The source container.
Definition at line 282 of file container.hpp.
References FEAT::MemoryPool::convert(), FEAT::MemoryPool::increase_memory(), FEAT::MemoryPool::release_memory(), and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::convert(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute().
axpy()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy (const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1)) inline
Calculate \(this \leftarrow \alpha~ x + y\).
Parameters
[in] x The first summand vector to be scaled.
[in] y The second summand vector
[in] alpha A scalar to multiply x with.
Definition at line 814 of file dense_vector.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::LAFEM::Container< DT_, IT_ >::bytes () const inline inherited
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 1047 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes().
clear()
template<typename DT_ , typename IT_ > virtual void FEAT::LAFEM::Container< DT_, IT_ >::clear () inline virtual inherited
Free all allocated arrays.
Definition at line 880 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from().
clone() [1/4]
template<typename DT_ , typename IT_ = Index> DenseVector FEAT::LAFEM::DenseVector< DT_, IT_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Clone operation.
Create a clone of this container.
Parameters
[in] clone_mode The actual cloning procedure.
Returns
The created clone.
Definition at line 375 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::clone().
Referenced by FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clone(), and FEAT::Global::MeanFilter< DT_, IT_ >::clone().
clone() [2/4]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 907 of file container.hpp.
References FEAT::LAFEM::Allocate, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Deep, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Layout, FEAT::LAFEM::Shallow, FEAT::LAFEM::Weak, XABORTM, and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVector< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone().
clone() [3/4]
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 980 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), and FEAT::LAFEM::Container< DT_, IT_ >::clone().
clone() [4/4]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::DenseVector< DT_, IT_ >::clone (const DenseVector< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clone operation.
Create a clone of another container.
Parameters
[in] other The source container to create the clone from.
[in] clone_mode The actual cloning procedure.
Definition at line 391 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clone().
component_invert()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert (const DenseVector< DT_, IT_ > & x, const DT_ alpha = DT_(1)) inline
Performs \(this_i \leftarrow \alpha / x_i \).
Parameters
[in] x The vector whose components serve as denominators.
[in] alpha The nominator.
Definition at line 867 of file dense_vector.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
component_product()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product (const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y) inline
Calculate \(this_i \leftarrow x_i \cdot y_i\).
Parameters
[in] x The first factor.
[in] y The second factor.
Definition at line 844 of file dense_vector.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
convert() [1/3]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::DenseVector< DT_, IT_ >::convert (const DenseVector< DT2_, IT2_ > & other) inline
Conversion method.
Parameters
[in] other The source vector.
Use source vector content as content of current vector
Definition at line 404 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign().
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::Global::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join_send(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split_recv(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
convert() [2/3]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ , int BS2_> void FEAT::LAFEM::DenseVector< DT_, IT_ >::convert (const DenseVectorBlocked< DT2_, IT2_, BS2_ > & other) inline
Conversion method.
Parameters
[in] other The source vector.
Use source vector content as content of current vector
Definition at line 417 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::MemoryPool::increase_memory(), and FEAT::LAFEM::Container< DT_, IT_ >::size().
convert() [3/3]
template<typename DT_ , typename IT_ = Index> template<typename VT_ > void FEAT::LAFEM::DenseVector< DT_, IT_ >::convert (const VT_ & a) inline
Conversion method.
Parameters
[in] a The input vector.
Converts any vector to DenseVector-format
Definition at line 439 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and FEAT::LAFEM::Container< DT_, IT_ >::move().
copy() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::copy (const DenseVector< DT_, IT_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The vector to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 800 of file dense_vector.hpp.
copy() [2/2]
template<typename DT_ , typename IT_ = Index> template<typename VT_ > void FEAT::LAFEM::DenseVector< DT_, IT_ >::copy (const VT_ & a) inline
Performs \(this \leftarrow x\).
Parameters
[in] a The vector to be copied (could be of any format; must have same size).
Definition at line 504 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and XASSERTM.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_conc(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy().
copy_inv()
template<typename DT_ , typename IT_ = Index> template<typename VT_ > void FEAT::LAFEM::DenseVector< DT_, IT_ >::copy_inv (VT_ & a) const inline
Performs \(x \leftarrow this\).
Parameters
[in] a The target-vector to be copied to (could be of any format; must have same size).
Definition at line 517 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and XASSERTM.
deserialize()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::DenseVector< DT_, IT_ >::deserialize (std::vector< char > input) inline
Deserialization of complete container entity.
Parameters
[in] input A std::vector, containing the byte array.
Recreate a complete container entity by a single binary array.
Definition at line 454 of file dense_vector.hpp.
References FEAT::LAFEM::fm_dv.
dot()
template<typename DT_ , typename IT_ = Index> DataType FEAT::LAFEM::DenseVector< DT_, IT_ >::dot (const DenseVector< DT_, IT_ > & x) const inline
Calculate \(result \leftarrow this \cdot x\).
Parameters
[in] x The other vector.
Returns
The computed dot product.
Definition at line 931 of file dense_vector.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol().
elements() [1/2]
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> DT_ * FEAT::LAFEM::DenseVector< DT_, IT_ >::elements () inline
Get a pointer to the data array.
Returns
Pointer to the data array.
Definition at line 738 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_neighbor_schur_matrix(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_gather_b(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::add_to_vtk_exporter(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::add_to_vtk_exporter(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::apply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::copy_inv(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector(), FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::DenseVector< DT_, IT_ >::inflate_to_blocks(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join_send(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseVector< DT_, IT_ >::permute(), FEAT::Assembly::RewProjector::project(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split_recv(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose(), FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector(), FEAT::LAFEM::PointstarStructureFE::value(), FEAT::LAFEM::PointstarStructureFD::value(), FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble(), FEAT::LAFEM::PointstarFactoryFD2< DataType_, IndexType_ >::vector_q2_bubble(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
elements() [2/2]
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> DT_ const * FEAT::LAFEM::DenseVector< DT_, IT_ >::elements () const inline
Definition at line 747 of file dense_vector.hpp.
empty()
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::empty () const inline inherited
Checks whether the container is empty.
Returns
true if the container is empty, otherwise false.
Definition at line 1170 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic().
format() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (DT_ value = DT_(0)) inline inherited
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 853 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::MemoryPool::set_memory(), and FEAT::value.
Referenced by FEAT::Assembly::CellErrorFunctionIntegralJob< Function_, Vector_, Space_, max_der_ >::CellErrorFunctionIntegralJob(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), FEAT::Assembly::CellErrorFunctionIntegralJob< Function_, Vector_, Space_, max_der_ >::result(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
format() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (Random & rng, DT_ min, DT_ max) inline inherited
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 866 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::MemoryPool::set_memory().
get_checkpoint_size()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::get_checkpoint_size (const LAFEM::SerialConfig & config) inline inherited
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1023 of file container.hpp.
get_elements()
template<typename DT_ , typename IT_ > const std::vector< DT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements () const inline inherited
Returns a list of all data arrays.
Returns
A list of all data arrays.
Definition at line 1073 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
get_elements_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size () const inline inherited
Returns a list of all data array sizes.
Returns
A list of all data array sizes.
Definition at line 1093 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
get_indices()
template<typename DT_ , typename IT_ > const std::vector< IT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices () const inline inherited
Returns a list of all Index arrays.
Returns
A list of all Index arrays.
Definition at line 1083 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
get_indices_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size () const inline inherited
Returns a list of all Index array sizes.
Returns
A list of all Index array sizes.
Definition at line 1103 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices_size.
get_scalar_dt()
template<typename DT_ , typename IT_ > const std::vector< DT_ > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt () const inline inherited
Returns a list of all scalar values with datatype dt.
Returns
A list of all scalars with datatype dt.
Definition at line 1123 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt.
get_scalar_index()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index () const inline inherited
Returns a list of all scalar values with datatype index.
Returns
A list of all scalars with datatype index.
Definition at line 1113 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
inflate_to_blocks()
template<typename DT_ , typename IT_ = Index> template<int BlockSize_> DenseVectorBlocked< DT_, IT_, BlockSize_ > FEAT::LAFEM::DenseVector< DT_, IT_ >::inflate_to_blocks () inline
Expand DenseVector to DenseVectorBlocked.
Inflate the DenseVector to DenseVectorBlocked by filling each complete block with the input scalar vector entry.
Note
The resulting DenseVectorBlocked will have size == DenseVector.size() * BlockSize_.
Definition at line 485 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and FEAT::LAFEM::Container< DT_, IT_ >::size().
max_abs_element()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::max_abs_element () const inline
Retrieve the absolute maximum value of this vector.
Returns
The largest absolute value.
Definition at line 980 of file dense_vector.hpp.
References FEAT::Math::abs(), ASSERT, FEAT::MemoryPool::copy(), and FEAT::TimeStamp::elapsed().
max_element()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::max_element () const inline
Retrieve the maximum value of this vector.
Returns
The largest value.
Definition at line 1022 of file dense_vector.hpp.
References ASSERT, FEAT::MemoryPool::copy(), and FEAT::TimeStamp::elapsed().
min_abs_element()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::min_abs_element () const inline
Retrieve the absolute minimum value of this vector.
Returns
The smallest absolute value.
Definition at line 1001 of file dense_vector.hpp.
References FEAT::Math::abs(), ASSERT, FEAT::MemoryPool::copy(), and FEAT::TimeStamp::elapsed().
min_element()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::min_element () const inline
Retrieve the minimum value of this vector.
Returns
The smallest value.
Definition at line 1042 of file dense_vector.hpp.
References ASSERT, FEAT::MemoryPool::copy(), and FEAT::TimeStamp::elapsed().
move()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::move (Container< DT_, IT_ > && other) inline inherited
Assignment move operation.
Move another container to the current one.
Parameters
[in] other The source container.
Definition at line 994 of file container.hpp.
References FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
name()
template<typename DT_ , typename IT_ = Index> static String FEAT::LAFEM::DenseVector< DT_, IT_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 789 of file dense_vector.hpp.
norm2()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2 () const inline
Calculates and returns the euclid norm of this vector.
Definition at line 950 of file dense_vector.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2sqr().
norm2sqr()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2sqr () const inline
Calculates and returns the squared euclid norm of this vector.
Returns
The computed norm.
Definition at line 969 of file dense_vector.hpp.
References FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), and FEAT::Math::sqr().
operator()() [1/2]
template<typename DT_ , typename IT_ = Index> const DT_ FEAT::LAFEM::DenseVector< DT_, IT_ >::operator() (Index index) const inline
Retrieve specific vector element.
Parameters
[in] index The index of the vector element.
Returns
Specific vector element.
Definition at line 762 of file dense_vector.hpp.
References ASSERT, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and FEAT::LAFEM::Container< DT_, IT_ >::size().
operator()() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::operator() (Index index, DT_ value) inline
Set specific vector element.
Parameters
[in] index The index of the vector element.
[in] value The value to be set.
Definition at line 777 of file dense_vector.hpp.
References ASSERT, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::value.
operator=()
template<typename DT_ , typename IT_ = Index> DenseVector & FEAT::LAFEM::DenseVector< DT_, IT_ >::operator= (DenseVector< DT_, IT_ > && other) inline
Assignment move operator.
Parameters
[in] other The source vector.
Moves another vector to the target vector.
Definition at line 360 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::move().
permute()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::permute (Adjacency::Permutation & perm) inline
Permutate vector according to the given Permutation.
Definition at line 1060 of file dense_vector.hpp.
References FEAT::Adjacency::Permutation::apply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::Adjacency::Permutation::size(), and XASSERTM.
read_from() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from (FileMode mode, const String & filename) inline
Read in vector from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 531 of file dense_vector.hpp.
References FEAT::LAFEM::fm_mtx, FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from().
read_from() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from (FileMode mode, std::istream & file) inline
Read in vector from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Definition at line 549 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::MemoryPool::copy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_dv, FEAT::LAFEM::fm_exp, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::Container< DT_, IT_ >::move(), XABORTM, and XASSERTM.
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::restore_from_checkpoint_data (std::vector< char > & data) inline inherited
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1029 of file container.hpp.
References FEAT::LAFEM::fm_binary.
scale()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::scale (const DenseVector< DT_, IT_ > & x, const DT_ alpha) inline
Calculate \(this \leftarrow \alpha~ x \).
Parameters
[in] x The vector to be scaled.
[in] alpha A scalar to scale x with.
Definition at line 886 of file dense_vector.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_post_sync(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_post_sync().
serialize()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::DenseVector< DT_, IT_ >::serialize (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline
Serialization of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
See FEAT::LAFEM::Container::_serialize for details.
Definition at line 472 of file dense_vector.hpp.
References FEAT::LAFEM::fm_dv.
set_checkpoint_data()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::set_checkpoint_data (std::vector< char > & data, const LAFEM::SerialConfig & config) inline inherited
Definition at line 1035 of file container.hpp.
References FEAT::LAFEM::fm_binary.
size()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::size () const inline inherited
Returns the containers size.
Returns
The containers size.
The template parameter of type Perspective is used in blocked containers to switch between the raw size and the size, when every block is treated as one entry.
Most containers like SparseMatrixCSR ignore this template parameter.
Definition at line 1141 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseVector< DT_, IT_ >::compare_layout(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_local_dofs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::get_num_nodes_image(), FEAT::LAFEM::DenseVector< DT_, IT_ >::inflate_to_blocks(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::Assembly::FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >::interpolate(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::map_local_to_global_index(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::mask_scatter(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::write_out().
triple_dot()
template<typename DT_ , typename IT_ = Index> DataType FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot (const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y) const inline
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
Parameters
[in] x The first vector.
[in] y The second vector.
Returns
The computed triple dot product.
Definition at line 908 of file dense_vector.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
Referenced by FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), and FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol().
used_elements()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::used_elements () const inline inherited
Returns the number of effective stored elements.
Returns
The number of data values.
The template parameter of type Perspective is used in block containers to switch between the raw number of used elements and the number of used elements, when every block is counted as one entry.
Definition at line 1160 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::invert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::scale_rows(), and FEAT::LAFEM::DenseMatrix< DT_, IT_ >::write_out().
write_out() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out (FileMode mode, const String & filename) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] filename The file where the vector shall be stored.
Definition at line 665 of file dense_vector.hpp.
References FEAT::LAFEM::FileOutStreamBufferSize, FEAT::LAFEM::fm_exp, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
write_out() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out (FileMode mode, std::ostream & file) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
Definition at line 691 of file dense_vector.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::MemoryPool::copy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_dv, FEAT::LAFEM::fm_exp, FEAT::LAFEM::fm_mtx, FEAT::MemoryPool::release_memory(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::stringify_fp_sci(), and XABORTM.
Friends And Related Function Documentation
operator<<
template<typename DT_ , typename IT_ = Index> std::ostream & operator<< (std::ostream & lhs, const DenseVector< DT_, IT_ > & b) friend
DenseVector streaming operator.
Parameters
[in] lhs The target stream.
[in] b The vector to be streamed.
Definition at line 1122 of file dense_vector.hpp.
operator==
template<typename DT_ , typename IT_ = Index> bool operator== (const DenseVector< DT_, IT_ > & a, const DenseVector< DT_, IT_ > & b) friend
DenseVector comparison operator.
Parameters
[in] a A vector to compare with.
[in] b A vector to compare with.
Definition at line 1090 of file dense_vector.hpp.
Member Data Documentation
_elements
template<typename DT_ , typename IT_ > std::vector<DT_*> FEAT::LAFEM::Container< DT_, IT_ >::_elements protected inherited
List of pointers to all datatype dependent arrays.
Definition at line 228 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
_elements_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_elements_size protected inherited
List of corresponding datatype array sizes.
Definition at line 232 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_foreign_memory
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory protected inherited
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
Definition at line 240 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), and FEAT::LAFEM::Container< DT_, IT_ >::clear().
_indices
template<typename DT_ , typename IT_ > std::vector<IT_*> FEAT::LAFEM::Container< DT_, IT_ >::_indices protected inherited
List of pointers to all IT_ dependent arrays.
Definition at line 230 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseVector< DT_, IT_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
_indices_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_indices_size protected inherited
List of corresponding IT_ array sizes.
Definition at line 234 of file container.hpp.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_scalar_dt
template<typename DT_ , typename IT_ > std::vector<DT_> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt protected inherited
List of scalars with datatype DT_.
Definition at line 238 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), and FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt().
_scalar_index
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index protected inherited
List of scalars with datatype index.
Definition at line 236 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::Container(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVector< DT_, IT_ >::allocated_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::sorted(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size().
The documentation for this class was generated from the following file:
kernel/lafem/dense_vector.hpp