FEAT: FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ > Class Template Reference
FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ > Class Template Reference
Public Member Functions
BezierPointsParser (Bezier< Mesh_ > &bezier, Index size)
virtual bool attribs (std::map< String, bool > &) const override
Specifies the mandatory and optional attributes.
virtual void close (int iline, const String &sline) override
Closes this markup parser node.
virtual bool content (int iline, const String &sline) override
Called to process a content line.
virtual void create (int iline, const String &sline, const String &, const std::map< String, String > &, bool closed) override
Creates this markup parser node.
virtual std::shared_ptr< MarkupParser > markup (int, const String &, const String &) override
Called to process a child markup node.
Private Types
typedef Bezier< Mesh_ > ChartType
Private Attributes
Bezier< Mesh_ > & _bezier
Index _read
Index _size
Detailed Description
template<typename Mesh_>
class FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >
Definition at line 996 of file bezier.hpp.
Member Typedef Documentation
ChartType
template<typename Mesh_ > typedef Bezier<Mesh_> FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::ChartType private
Definition at line 999 of file bezier.hpp.
Constructor & Destructor Documentation
BezierPointsParser()
template<typename Mesh_ > FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::BezierPointsParser (Bezier< Mesh_ > & bezier, Index size) inline explicit
Definition at line 1006 of file bezier.hpp.
Member Function Documentation
attribs()
template<typename Mesh_ > virtual bool FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::attribs (std::map< String, bool > & attrs) const inline override virtual
Specifies the mandatory and optional attributes.
Parameters
[out] attrs A transient reference to a map of all supported attribute key names. The second component specifies whether the attribute is mandatory (true) or optional (false).
Returns
true, if the scanner should check for valid arguments, otherwise false.
Implements FEAT::Xml::MarkupParser.
Definition at line 1011 of file bezier.hpp.
close()
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::close (int iline, const String & sline) inline override virtual
Closes this markup parser node.
Parameters
[in] iline The line number of the markup terminator in the XML file.
[in] sline The line string of the markup in the XML file.
Implements FEAT::Xml::MarkupParser.
Definition at line 1022 of file bezier.hpp.
content()
template<typename Mesh_ > virtual bool FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::content (int iline, const String & sline) inline override virtual
Called to process a content line.
This function is called by the XML scanner when a content line inside this markup parser node is detected.
Parameters
[in] iline The line number of the content line in the XML file.
[in] sline The line string of the content line in the XML file.
Returns
true, if the content line was parsed successfully, otherwise false.
Note
Returning false will cause the scanner to throw a Xml::GammarError.
Implements FEAT::Xml::MarkupParser.
Definition at line 1035 of file bezier.hpp.
References FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_control(), FEAT::Geometry::Atlas::Bezier< Mesh_ >::push_vertex(), FEAT::String::split_by_whitespaces(), and FEAT::Geometry::Atlas::ChartCRTP< Bezier< Mesh_ >, Mesh_, BezierTraits >::world_dim.
create()
template<typename Mesh_ > virtual void FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::create (int iline, const String & sline, const String & name, const std::map< String, String > & attrs, bool closed) inline override virtual
Creates this markup parser node.
Parameters
[in] iline The line number of the markup in the XML file.
[in] sline The line string of the markup in the XML file.
[in] name The name of the markup.
[in] attrs A transient reference to a map of all attributes of the markup.
[in] closed Specifies whether the markup is closed.
Implements FEAT::Xml::MarkupParser.
Definition at line 1016 of file bezier.hpp.
markup()
template<typename Mesh_ > virtual std::shared_ptr< MarkupParser > FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::markup (int iline, const String & sline, const String & name) inline override virtual
Called to process a child markup node.
This function is called by the XML scanner when a child markup inside this markup parser node is detected.
Parameters
[in] iline The line number of the child markup in the XML file.
[in] sline The line string of the child markup in the XML file.
[in] name The markup name of the child markup.
Returns
A new MarkupParser object if the markup is a valid child or nullptr if a child markup with this name is not supported.
Note
Returning nullptr will cause the scanner to throw a Xml::GammarError.
Implements FEAT::Xml::MarkupParser.
Definition at line 1029 of file bezier.hpp.
Member Data Documentation
_bezier
template<typename Mesh_ > Bezier<Mesh_>& FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::_bezier private
Definition at line 1002 of file bezier.hpp.
_read
template<typename Mesh_ > Index FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::_read private
Definition at line 1003 of file bezier.hpp.
_size
template<typename Mesh_ > Index FEAT::Geometry::Atlas::BezierPointsParser< Mesh_ >::_size private
Definition at line 1003 of file bezier.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/atlas/bezier.hpp