FEAT: FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ > Class Template Reference
FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ > Class Template Reference
Class to compute a desired concentration for the mesh cell distribution base on distance to Charts.
#include <mesh_concentration_function.hpp>
Public Types
typedef MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ > BaseClass
Our base class.
typedef MeshType::CoordType CoordType
The precision of the mesh coordinates.
typedef MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ > DirectBaseClass
Our direct base class.
typedef ElementalFunction_ ElementalFunction
Type for the function mapping distance to concentration.
typedef LAFEM::DenseVectorBlocked< CoordType, Index, MeshType::world_dim *Shape::FaceTraits< ShapeType, 0 >::count > GradHType
Vector type for the gradient of h wrt. the DoF.
typedef Index IndexType
The index type.
typedef TrafoType::MeshType MeshType
The mesh the transformation is defined on.
typedef AlignmentPenalty< CoordType, ShapeType > PenaltyFunction
Surface alignment penalty function.
typedef LAFEM::DenseVector< CoordType, IndexType > ScalarVectorType
Vector type for element sizes etc.
typedef MeshType::ShapeType ShapeType
ShapeType of said mesh.
typedef Trafo_ TrafoType
Type for the transformation.
typedef LAFEM::DenseVectorBlocked< CoordType, IndexType, MeshType::world_dim > VectorType
Vector type for element scales etc.
typedef Tiny::Vector< CoordType, MeshType::world_dim > WorldPoint
Type for one mesh vertex.
Public Member Functions
ChartDistanceFunction ()=delete
Explicitly delete the empty default constructor.
ChartDistanceFunction (const ElementalFunction &func_, const std::deque< String > &chart_list_, const String &operation_)
Constructor setting the ElementalFunction_ and the list of charts.
virtual ~ChartDistanceFunction ()
virtual void add_constraint_grad (VectorType &grad, const CoordType constraint, const CoordType fac) const override
Adds the scaled gradient of the constraint wrt. the vertex coordinates.
virtual void add_sync_vecs (std::set< VectorType * > &sync_vecs) override
Adds pointers to vectors that need synchronising (type-0 to type-1 vectors)
virtual void compute_conc () override
Computes the mesh concentration function for each cell.
virtual CoordType compute_constraint () const override
Computes the surface alignment constraint.
virtual CoordType compute_constraint (CoordType *constraint_at_vtx) const override
Computes the surface alignment constraint at every vertex.
virtual void compute_dist () override
Computes the distance information.
void compute_dist_add ()
Computes the distance information.
void compute_dist_max ()
Computes the distance information.
void compute_dist_min ()
Computes the distance information.
virtual void compute_grad_conc () override
Computes the gradient of the sum of all mesh concentrations.
template<typename Tgrad_ , typename Tl_ , typename Tgradl_ >
void compute_grad_conc_local (Tgrad_ &grad_loc_, const Tl_ &dist_loc_, const Tgradl_ &grad_dist_loc_)
Computes the local gradient of the concentration function wrt. the vertices.
virtual void compute_grad_h (const CoordType &sum_det) override
Computes the local gradient of the optimal scales.
virtual void compute_grad_sum_det (const VectorType &coords) override
Computes the gradient of the sum of all determinants of the trafo.
virtual std::shared_ptr< BaseClass > create_empty_clone () const override
Creates an empty clone of itself.
virtual const ScalarVectorType & get_conc () const override
Returns a const reference to the concentration.
virtual const ScalarVectorType & get_dist () const override
Returns a const reference to the distance information.
virtual const VectorType & get_grad_dist () const override
Returns a const reference to the gradient of the distance function.
virtual const GradHType & get_grad_h () const override
Returns a reference to gradient of the optimal scales wrt. the vertex coordinates.
virtual GradHType & get_grad_h () override
Returns a reference to gradient of the optimal scales wrt. the vertex coordinates.
virtual CoordType & get_sum_conc () override
Returns the sum of the mesh concentration over all cells.
virtual String info () const override
Prints relevant information.
virtual void set_mesh_node (const Geometry::RootMeshNode< MeshType > *mesh_node_) override
Sets this object's mesh node.
virtual bool use_derivative () const override
Returns whether this function make use of the derivative of h wrt. the vertex coordinates.
Static Public Member Functions
static String name ()
Returns the class name as String.
Protected Attributes
std::deque< String > _chart_list
List of charts to compute the distance to.
ScalarVectorType _conc
Vector for saving the mesh concentration, one entry per cell.
ScalarVectorType _dist
For all vertices, this holds their scalar "distance" to whatever.
ScalarVectorType _edge_freqs
For each edge, this contains 1/(# halos it is present in)
ElementalFunction _func
The scalar function mapping distance to concentration.
VectorType _grad_conc
Gradient of the mesh concentration wrt. the world coordinates.
VectorType _grad_dist
For all vertices, this holds the gradient of the distance function.
GradHType _grad_h
Gradient of the local optimal scales h wrt. the vertex coordinates.
VectorType _grad_sum_det
Gradient of _sum_det wrt. the mesh vertices.
const Geometry::RootMeshNode< MeshType > * _mesh_node
The mesh node this function works with.
const String _operation
How to mangle more than one distance (add, max, min)
CoordType _sum_conc
The sum of all entries in _conc.
Detailed Description
template<typename ElementalFunction_, typename Trafo_, typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>>
class FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >
Class to compute a desired concentration for the mesh cell distribution base on distance to Charts.
Template Parameters
ElementalFunction_ The scalar function that computes the concentration.
Trafo_ Our transformation.
RefCellTrafo_ Mesh optimization reference cell transformation.
Note
To avoid virtual functions, this class explicitly knows which type of elemental function it has.
The Charts are identified by a deque of Strings passed to the constructor and need to be present in the Atlas of the object's MeshNode. At the moment, the sum of all distances is taken, which is to be revised in the future.
Definition at line 1282 of file mesh_concentration_function.hpp.
Member Typedef Documentation
BaseClass
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef MeshConcentrationFunctionBase<Trafo_, RefCellTrafo_> FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::BaseClass
Our base class.
Definition at line 1299 of file mesh_concentration_function.hpp.
CoordType
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef MeshType::CoordType FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::CoordType
The precision of the mesh coordinates.
Definition at line 1292 of file mesh_concentration_function.hpp.
DirectBaseClass
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef MeshConcentrationFunction<ElementalFunction_, Trafo_, RefCellTrafo_> FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::DirectBaseClass
Our direct base class.
Definition at line 1297 of file mesh_concentration_function.hpp.
ElementalFunction
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef ElementalFunction_ FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::ElementalFunction
Type for the function mapping distance to concentration.
Definition at line 1286 of file mesh_concentration_function.hpp.
GradHType
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef LAFEM::DenseVectorBlocked<CoordType, Index, MeshType::world_dim*Shape::FaceTraits<ShapeType,0>::count> FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::GradHType inherited
Vector type for the gradient of h wrt. the DoF.
Definition at line 853 of file mesh_concentration_function.hpp.
IndexType
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef Index FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::IndexType
The index type.
Definition at line 1301 of file mesh_concentration_function.hpp.
MeshType
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef TrafoType::MeshType FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::MeshType
The mesh the transformation is defined on.
Definition at line 1290 of file mesh_concentration_function.hpp.
PenaltyFunction
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef AlignmentPenalty<CoordType, ShapeType> FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::PenaltyFunction inherited
Surface alignment penalty function.
Definition at line 857 of file mesh_concentration_function.hpp.
ScalarVectorType
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef LAFEM::DenseVector<CoordType, IndexType> FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::ScalarVectorType
Vector type for element sizes etc.
Definition at line 1306 of file mesh_concentration_function.hpp.
ShapeType
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef MeshType::ShapeType FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::ShapeType
ShapeType of said mesh.
Definition at line 1304 of file mesh_concentration_function.hpp.
TrafoType
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef Trafo_ FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::TrafoType
Type for the transformation.
Definition at line 1288 of file mesh_concentration_function.hpp.
VectorType
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef LAFEM::DenseVectorBlocked<CoordType, IndexType, MeshType::world_dim> FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::VectorType
Vector type for element scales etc.
Definition at line 1308 of file mesh_concentration_function.hpp.
WorldPoint
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> typedef Tiny::Vector<CoordType, MeshType::world_dim> FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::WorldPoint
Type for one mesh vertex.
Definition at line 1294 of file mesh_concentration_function.hpp.
Constructor & Destructor Documentation
ChartDistanceFunction()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::ChartDistanceFunction (const ElementalFunction & func_, const std::deque< String > & chart_list_, const String & operation_) inline
Constructor setting the ElementalFunction_ and the list of charts.
Parameters
[in] func_ Elemental function.
[in] chart_list_ The list of charts to compute the distance from.
[in] operation_ How to handle the distances multiple charts (sum, min, max etc.)
Definition at line 1333 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_chart_list, and XASSERTM.
~ChartDistanceFunction()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::~ChartDistanceFunction () inline virtual
Definition at line 1351 of file mesh_concentration_function.hpp.
Member Function Documentation
add_constraint_grad()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual void FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::add_constraint_grad (VectorType & grad, const CoordType constraint, const CoordType fac) const inline override virtual inherited
Adds the scaled gradient of the constraint wrt. the vertex coordinates.
Parameters
[in,out] grad Vector to add the constraint gradient to.
[in] constraint The current constraint value.
[in] fac grad <- grad + fac * constraint_grad
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1248 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Meshopt::AlignmentPenalty< DT_, ShapeType_ >::add_constraint_grad(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), and FEAT::grad.
add_sync_vecs()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual void FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::add_sync_vecs (std::set< VectorType * > & sync_vecs) inline override virtual inherited
Adds pointers to vectors that need synchronising (type-0 to type-1 vectors)
Parameters
[in,out] sync_vecs deque holding pointers to all vectors that need synchronising.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 929 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_func, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_conc, and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_sum_det.
compute_conc()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual void FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc () inline override virtual inherited
Computes the mesh concentration function for each cell.
This means it computes
\[ \forall K \in \mathcal{T}_h: \underbrace{c(K)}_{ =: \mathtt{conc(cell)}} ~ \mathrm{and} ~ \underbrace{\sum_{K \in \mathcal{T}_h} c(K)}_{\mathtt{\_sum\_conc}} \]
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1027 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_conc, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_func, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_sum_conc, FEAT::LAFEM::Container< DT_, IT_ >::format(), and FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh().
compute_constraint() [1/2]
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual CoordType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_constraint () const inline override virtual inherited
Computes the surface alignment constraint.
Returns
The sum of all surface alignment constraints.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1225 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Meshopt::AlignmentPenalty< DT_, ShapeType_ >::compute_constraint(), and FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh().
compute_constraint() [2/2]
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual CoordType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_constraint (CoordType * constraint_at_vtx) const inline override virtual inherited
Computes the surface alignment constraint at every vertex.
Parameters
[out] constraint_at_vtx The vector of constraints at every vertex.
The is for post processing and debugging purposes.
Returns
The sum of all surface alignment constraints.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1241 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Meshopt::AlignmentPenalty< DT_, ShapeType_ >::compute_constraint(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), and XASSERT.
compute_dist()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual void FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist () inline override virtual
Computes the distance information.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1364 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_operation, FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min(), and XABORTM.
compute_dist_add()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> void FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add () inline
Computes the distance information.
Definition at line 1377 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_chart_list, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Math::abs(), FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_atlas(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid(), XABORTM, and XASSERT.
Referenced by FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist().
compute_dist_max()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> void FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max () inline
Computes the distance information.
Definition at line 1413 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_chart_list, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_atlas(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), XABORTM, and XASSERT.
Referenced by FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist().
compute_dist_min()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> void FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min () inline
Computes the distance information.
Definition at line 1447 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_chart_list, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Math::abs(), FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_atlas(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), XABORTM, and XASSERT.
Referenced by FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist().
compute_grad_conc()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual void FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc () inline override virtual inherited
Computes the gradient of the sum of all mesh concentrations.
\[ \mathrm{grad\_conc}(k,i) = \frac{\partial}{\partial x_j} \sum_{l=1}^N c(K_l), \]
where \(i \) is the global index of the local vertex \(j \).
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1178 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_conc, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc_local(), FEAT::LAFEM::Container< DT_, IT_ >::format(), and FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh().
compute_grad_conc_local()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> template<typename Tgrad_ , typename Tl_ , typename Tgradl_ > void FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc_local (Tgrad_ & grad_loc_, const Tl_ & dist_loc_, const Tgradl_ & grad_dist_loc_) inline inherited
Computes the local gradient of the concentration function wrt. the vertices.
Template Parameters
Tgrad_ Type of the local gradient, i.e. Tiny::Matrix
Tl_ Type for the vector of distance values, i.e. Tiny::vector
Tgradl_ Type for the local gradient of the distance wrt. the vertices, i.e. Tiny::Matrix
Parameters
[out] grad_loc_ The gradient of the concentration wrt. the vertices
[in] grad_dist_loc_ The levelset values at the vertices
[in] dist_loc_ The distances of the local vertices
Definition at line 1092 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_func.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h().
compute_grad_h()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual void FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h (const CoordType & sum_det) inline override virtual inherited
Computes the local gradient of the optimal scales.
Parameters
[out] sum_det The sum of all optimal reference cell's volumes, which is different from the domain's volume in general.
The optimal scales \(h \) depend on the concentration \(c \) by the relation
\[ \forall K_k \in \mathcal{T}_h: h_k = \left(\frac{c (K_k)}{\sum_{l=1}^N c(K_l) \sum_{l=1}^N \mathrm{det} \nabla R_{T,l}(\phi)} \right)^{\frac{1}{d}} \]
The concentration function in turn indirectly depends on the vertex locations \(\{ x_i : i=1, \dots, n \} \) via
\[ c(K_k) = (\alpha + \sum_{x_j \in K_k} \varphi(x_j))^\beta, \]
so that we have to take this dependency into account for the full gradient. Define
\[ s_d := \sum_{l=1}^N \mathrm{det} \nabla R_{T,l}(\Phi), s_c := \frac{c (K_k)}{\sum_{l=1}^N c(K_l)}. \]
So for each \(x_j \) we arrive at
\[ \frac{\partial h(K_k)}{\partial x_j} = \frac{1}{d} \left(\frac{c(K_k)}{s_d s_c} \right)^ {\frac{1}{d}-1} \left[ c(K_k) (\frac{\partial s_d}{\partial x_j} s_c + s_d \frac{\partial s_c}{\partial x_j}) + \frac{\partial c(K_k)}{\partial x_j} s_d s_c \right] (s_d s_c)^{-2} \]
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1112 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_conc, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_func, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_conc, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_h, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_sum_det, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_sum_conc, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc_local(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Math::pow(), FEAT::Math::sqr(), and XASSERT.
compute_grad_sum_det()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual void FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_sum_det (const VectorType & coords) inline override virtual inherited
Computes the gradient of the sum of all determinants of the trafo.
Parameters
[in] coords Set of coordinates to compute the gradient for
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1061 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_func, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_sum_det, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, and FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh().
create_empty_clone()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual std::shared_ptr< BaseClass > FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::create_empty_clone () const inline override virtual
Creates an empty clone of itself.
This function is handy for creating empty copies of objects of a derived class, which is used in the HyperelasticityFunctional class.
Returns
A shared_ptr to a new object of this (or rather the derived) class.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1356 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_func, and FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_operation.
get_conc()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual const ScalarVectorType & FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_conc () const inline override virtual inherited
Returns a const reference to the concentration.
Returns
A const reference to the concentration.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 939 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_conc.
get_dist()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual const ScalarVectorType & FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_dist () const inline override virtual inherited
Returns a const reference to the distance information.
Returns
A const reference to the distance information in each vertex.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 945 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist.
get_grad_dist()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual const VectorType & FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_grad_dist () const inline override virtual inherited
Returns a const reference to the gradient of the distance function.
Returns
A const reference to the gradient of the distance function in each vertex.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 951 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist.
get_grad_h() [1/2]
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual const GradHType & FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_grad_h () const inline override virtual inherited
Returns a reference to gradient of the optimal scales wrt. the vertex coordinates.
Returns
A reference to gradient of the optimal scales wrt. the vertex coordinates
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 963 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_h.
get_grad_h() [2/2]
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual GradHType & FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_grad_h () inline override virtual inherited
Returns a reference to gradient of the optimal scales wrt. the vertex coordinates.
Returns
A reference to gradient of the optimal scales wrt. the vertex coordinates
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 957 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_h.
get_sum_conc()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual CoordType & FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_sum_conc () inline override virtual inherited
Returns the sum of the mesh concentration over all cells.
Returns
_sum_conc
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 969 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_sum_conc.
info()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual String FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::info () const inline override virtual
Prints relevant information.
Reimplemented from FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >.
Definition at line 1492 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_chart_list, FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_operation, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::info(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::name(), and FEAT::String::pad_back().
name()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> static String FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::name () inline static
Returns the class name as String.
Returns
The class name as String.
Definition at line 1486 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::info().
set_mesh_node()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual void FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node (const Geometry::RootMeshNode< MeshType > * mesh_node_) inline override virtual inherited
Sets this object's mesh node.
Parameters
[in] mesh_node_ The mesh node this function is to use.
Note
The mesh node cannot be set at construction time because this class is used from the MeshConcentrationFuncionFactory, so this method is necessary.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 981 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_conc, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_edge_freqs, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_conc, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_h, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_sum_det, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node, FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_sum_conc, FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::find_mesh_part(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh_part_names(), and XASSERT.
use_derivative()
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> virtual bool FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::use_derivative () const inline override virtual inherited
Returns whether this function make use of the derivative of h wrt. the vertex coordinates.
Returns
True if the function makes use of the derivative of h wrt. the vertex coordinates.
Implements FEAT::Meshopt::MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ >.
Definition at line 1014 of file mesh_concentration_function.hpp.
References FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_func.
Member Data Documentation
_chart_list
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> std::deque<String> FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_chart_list protected
List of charts to compute the distance to.
Definition at line 1312 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::ChartDistanceFunction(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min(), and FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::info().
_conc
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> ScalarVectorType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_conc protected inherited
Vector for saving the mesh concentration, one entry per cell.
Definition at line 874 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_conc(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
_dist
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> ScalarVectorType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_dist protected inherited
For all vertices, this holds their scalar "distance" to whatever.
Definition at line 868 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::add_constraint_grad(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_dist(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
_edge_freqs
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> ScalarVectorType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_edge_freqs protected inherited
For each edge, this contains 1/(# halos it is present in)
Definition at line 866 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
_func
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> ElementalFunction FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_func protected inherited
The scalar function mapping distance to concentration.
Definition at line 863 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::add_sync_vecs(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc_local(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_sum_det(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::create_empty_clone(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::info(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::use_derivative().
_grad_conc
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> VectorType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_conc protected inherited
Gradient of the mesh concentration wrt. the world coordinates.
Definition at line 876 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::add_sync_vecs(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
_grad_dist
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> VectorType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_dist protected inherited
For all vertices, this holds the gradient of the distance function.
Definition at line 870 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::add_constraint_grad(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_grad_dist(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
_grad_h
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> GradHType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_h protected inherited
Gradient of the local optimal scales h wrt. the vertex coordinates.
Definition at line 883 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_grad_h(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
_grad_sum_det
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> VectorType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_grad_sum_det protected inherited
Gradient of _sum_det wrt. the mesh vertices.
Definition at line 878 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::add_sync_vecs(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_sum_det(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
_mesh_node
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> const Geometry::RootMeshNode<MeshType>* FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_mesh_node protected inherited
The mesh node this function works with.
Definition at line 861 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::add_constraint_grad(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_constraint(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_sum_det(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
_operation
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> const String FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_operation protected
How to mangle more than one distance (add, max, min)
Definition at line 1314 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::create_empty_clone(), and FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::info().
_sum_conc
template<typename ElementalFunction_ , typename Trafo_ , typename RefCellTrafo_ = RumpfTrafo<Trafo_, typename Trafo_::CoordType>> CoordType FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::_sum_conc protected inherited
The sum of all entries in _conc.
Definition at line 872 of file mesh_concentration_function.hpp.
Referenced by FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::get_sum_conc(), and FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::set_mesh_node().
The documentation for this class was generated from the following file:
kernel/meshopt/mesh_concentration_function.hpp