FEAT: FEAT::LAFEM::MeanFilter< DT_, IT_ > Class Template Reference
FEAT::LAFEM::MeanFilter< DT_, IT_ > Class Template Reference
Mean Filter class template.
#include <mean_filter.hpp>
Public Types
typedef VectorType::DataType DataType
data-type typedef
template<typename DT2_ = DT_, typename IT2_ = IT_>
using FilterType = MeanFilter< DT2_, IT2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using FilterTypeByDI = FilterType< DataType2_, IndexType2_ >
this typedef lets you create a filter with different Data and Index types
typedef VectorType::IndexType IndexType
index-type typedef
typedef DenseVector< DT_, IT_ > VectorType
vector-type typedef
Public Member Functions
MeanFilter (MeanFilter &&other)
move ctor
MeanFilter (VectorType &&vec_prim, VectorType &&vec_dual, DataType sol_mean, DataType volume)
Constructor.
MeanFilter (VectorType &&vec_prim, VectorType &&vec_dual, DataType sol_mean=DataType(0))
Constructor.
virtual ~MeanFilter ()
virtual destructor
void clear ()
Clears this filter.
MeanFilter clone (CloneMode clone_mode=CloneMode::Deep) const
Creates a clone of itself.
void clone (const MeanFilter &other, CloneMode clone_mode=CloneMode::Deep)
Clones data from another MeanFilter.
template<typename DT2_ , typename IT2_ >
void convert (const MeanFilter< DT2_, IT2_ > &other)
Conversion method.
void filter_cor (VectorType &vector) const
Applies the filter onto a correction vector.
void filter_def (VectorType &vector) const
Applies the filter onto a defect vector.
template<typename MT_ >
void filter_mat (MT_ &matrix) const
Applies the filter onto a system matrix.
void filter_rhs (VectorType &vector) const
Applies the filter onto the right-hand-side vector.
void filter_sol (VectorType &vector) const
Applies the filter onto the solution vector.
MeanFilter & operator= (MeanFilter &&other)
move-assign operator
Protected Attributes
DataType _sol_mean
desired solution vector mean
VectorType _vec_dual
dual weighting vector
VectorType _vec_prim
primal weighting vector
DataType _volume
weight volume
Detailed Description
template<typename DT_, typename IT_>
class FEAT::LAFEM::MeanFilter< DT_, IT_ >
Mean Filter class template.
Author
Peter Zajac
Definition at line 21 of file mean_filter.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ > typedef VectorType::DataType FEAT::LAFEM::MeanFilter< DT_, IT_ >::DataType
data-type typedef
Definition at line 27 of file mean_filter.hpp.
FilterType
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::MeanFilter< DT_, IT_ >::FilterType = MeanFilter<DT2_, IT2_>
Our 'base' class type.
Definition at line 33 of file mean_filter.hpp.
FilterTypeByDI
template<typename DT_ , typename IT_ > template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::MeanFilter< DT_, IT_ >::FilterTypeByDI = FilterType<DataType2_, IndexType2_>
this typedef lets you create a filter with different Data and Index types
Definition at line 37 of file mean_filter.hpp.
IndexType
template<typename DT_ , typename IT_ > typedef VectorType::IndexType FEAT::LAFEM::MeanFilter< DT_, IT_ >::IndexType
index-type typedef
Definition at line 29 of file mean_filter.hpp.
VectorType
template<typename DT_ , typename IT_ > typedef DenseVector<DT_, IT_> FEAT::LAFEM::MeanFilter< DT_, IT_ >::VectorType
vector-type typedef
Definition at line 25 of file mean_filter.hpp.
Constructor & Destructor Documentation
MeanFilter() [1/4]
template<typename DT_ , typename IT_ > FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter () inline
Definition at line 51 of file mean_filter.hpp.
MeanFilter() [2/4]
template<typename DT_ , typename IT_ > FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter (VectorType && vec_prim, VectorType && vec_dual, DataType sol_mean = DataType(0)) inline explicit
Constructor.
Parameters
[in] vec_prim,vec_dual The primal-dual weighting vector pair for the mean filter.
[in] sol_mean The desired integral mean of the solution vector. Defaults to 0.
Definition at line 68 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, FEAT::LAFEM::Container< DT_, IT_ >::empty(), and XASSERTM.
MeanFilter() [3/4]
template<typename DT_ , typename IT_ > FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter (VectorType && vec_prim, VectorType && vec_dual, DataType sol_mean, DataType volume) inline explicit
Constructor.
Parameters
[in] vec_prim,vec_dual The primal-dual weighting vector pair for the mean filter.
[in] sol_mean The desired integral mean of the solution vector.
[in] volume The domain volume. This is simply the dot-product of the two vectors.
Definition at line 92 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, FEAT::LAFEM::Container< DT_, IT_ >::empty(), and XASSERTM.
MeanFilter() [4/4]
template<typename DT_ , typename IT_ > FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter (MeanFilter< DT_, IT_ > && other) inline
move ctor
Definition at line 105 of file mean_filter.hpp.
~MeanFilter()
template<typename DT_ , typename IT_ > virtual FEAT::LAFEM::MeanFilter< DT_, IT_ >::~MeanFilter () inline virtual
virtual destructor
Definition at line 127 of file mean_filter.hpp.
Member Function Documentation
clear()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear () inline
Clears this filter.
Definition at line 167 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_sol_mean, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, and FEAT::LAFEM::Container< DT_, IT_ >::clear().
clone() [1/2]
template<typename DT_ , typename IT_ > MeanFilter FEAT::LAFEM::MeanFilter< DT_, IT_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Creates a clone of itself.
Warning
_volume and _sol_mean will always be a deep copy
Definition at line 135 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_sol_mean, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, and FEAT::LAFEM::DenseVector< DT_, IT_ >::clone().
clone() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::MeanFilter< DT_, IT_ >::clone (const MeanFilter< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clones data from another MeanFilter.
Warning
_volume and _sol_mean will always be a deep copy
Definition at line 144 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_sol_mean, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, and FEAT::LAFEM::DenseVector< DT_, IT_ >::clone().
convert()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert (const MeanFilter< DT2_, IT2_ > & other) inline
Conversion method.
Definition at line 154 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_sol_mean, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), and XASSERTM.
filter_cor()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor (VectorType & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 257 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), and FEAT::LAFEM::Container< DT_, IT_ >::empty().
filter_def()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_def (VectorType & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 245 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs().
filter_mat()
template<typename DT_ , typename IT_ > template<typename MT_ > void FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_mat (MT_ & matrix) const inline
Applies the filter onto a system matrix.
Parameters
[in,out] matrix A reference to the matrix to be filtered.
Definition at line 271 of file mean_filter.hpp.
filter_rhs()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs (VectorType & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 212 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), and FEAT::LAFEM::Container< DT_, IT_ >::empty().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_def().
filter_sol()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol (VectorType & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 225 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_sol_mean, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume, FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), and FEAT::LAFEM::Container< DT_, IT_ >::empty().
operator=()
template<typename DT_ , typename IT_ > MeanFilter & FEAT::LAFEM::MeanFilter< DT_, IT_ >::operator= (MeanFilter< DT_, IT_ > && other) inline
move-assign operator
Definition at line 114 of file mean_filter.hpp.
References FEAT::LAFEM::MeanFilter< DT_, IT_ >::_sol_mean, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual, FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim, and FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume.
Member Data Documentation
_sol_mean
template<typename DT_ , typename IT_ > DataType FEAT::LAFEM::MeanFilter< DT_, IT_ >::_sol_mean protected
desired solution vector mean
Definition at line 47 of file mean_filter.hpp.
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clone(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::LAFEM::MeanFilter< DT_, IT_ >::operator=().
_vec_dual
template<typename DT_ , typename IT_ > VectorType FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_dual protected
dual weighting vector
Definition at line 43 of file mean_filter.hpp.
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clone(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::LAFEM::MeanFilter< DT_, IT_ >::operator=().
_vec_prim
template<typename DT_ , typename IT_ > VectorType FEAT::LAFEM::MeanFilter< DT_, IT_ >::_vec_prim protected
primal weighting vector
Definition at line 41 of file mean_filter.hpp.
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clone(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::LAFEM::MeanFilter< DT_, IT_ >::operator=().
_volume
template<typename DT_ , typename IT_ > DataType FEAT::LAFEM::MeanFilter< DT_, IT_ >::_volume protected
weight volume
Definition at line 45 of file mean_filter.hpp.
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clone(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::LAFEM::MeanFilter< DT_, IT_ >::operator=().
The documentation for this class was generated from the following file:
kernel/lafem/mean_filter.hpp