FEAT: FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ > Class Template Reference
FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ > Class Template Reference
Cosine-Tensor Static function.
#include <common.hpp>
Static Public Member Functions
static DataType_ der_x (DataType_ x)
1D: X-derivative
static DataType_ der_x (DataType_ x, DataType_ y)
2D: X-derivative
static DataType_ der_x (DataType_ x, DataType_ y, DataType_ z)
3D: X-derivative
static DataType_ der_xx (DataType_ x)
1D: XX-derivative
static DataType_ der_xx (DataType_ x, DataType_ y)
2D: XX-derivative
static DataType_ der_xx (DataType_ x, DataType_ y, DataType_ z)
3D: XX-derivative
static DataType_ der_xy (DataType_ x, DataType_ y)
2D: XY-derivative
static DataType_ der_xy (DataType_ x, DataType_ y, DataType_ z)
3D: XY-derivative
static DataType_ der_xz (DataType_ x, DataType_ y, DataType_ z)
3D: XZ-derivative
static DataType_ der_y (DataType_ x, DataType_ y)
2D: Y-derivative
static DataType_ der_y (DataType_ x, DataType_ y, DataType_ z)
3D: Y-derivative
static DataType_ der_yx (DataType_ x, DataType_ y)
2D: YX-derivative
static DataType_ der_yx (DataType_ x, DataType_ y, DataType_ z)
3D: YX-derivative
static DataType_ der_yy (DataType_ x, DataType_ y)
2D: YY-derivative
static DataType_ der_yy (DataType_ x, DataType_ y, DataType_ z)
3D: YY-derivative
static DataType_ der_yz (DataType_ x, DataType_ y, DataType_ z)
3D: YZ-derivative
static DataType_ der_z (DataType_ x, DataType_ y, DataType_ z)
3D: Z-derivative
static DataType_ der_zx (DataType_ x, DataType_ y, DataType_ z)
3D: ZX-derivative
static DataType_ der_zy (DataType_ x, DataType_ y, DataType_ z)
3D: ZY-derivative
static DataType_ der_zz (DataType_ x, DataType_ y, DataType_ z)
3D: ZZ-derivative
static DataType_ eval (DataType_ x)
1D: function value
static DataType_ eval (DataType_ x, DataType_ y)
2D: function value
static DataType_ eval (DataType_ x, DataType_ y, DataType_ z)
3D: function value
static DataType_ kpi ()
Returns k times pi.
Detailed Description
template<typename DataType_, int k_ = 1>
class FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >
Cosine-Tensor Static function.
This class implements the StaticFunction interface representing the function
1D: u(x) = cos(k*pi*x)
2D: u(x,y) = cos(k*pi*x) * cos(k*pi*y)
3D: u(x,y,z) = cos(k*pi*x) * cos(k*pi*y) * cos(k*pi*z)
For any positive integral k, these functions are eigenfunctions of the Laplace operator. The corresponding eigenvalue is , where d is the dimension of the domain.
Moreover, on any rectangular/rectoid domain [x0,x1]x[y0,y1]x[z0,z1] with integral domain boundaries xi,yi,zi, this function fulfills homogeneous Neumann boundary conditions including the integral-mean condition .
Author
Peter Zajac
Definition at line 396 of file common.hpp.
Member Function Documentation
der_x() [1/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_x (DataType_ x) inline static
1D: X-derivative
Definition at line 426 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sin().
der_x() [2/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_x (DataType_ x, DataType_ y) inline static
2D: X-derivative
Definition at line 432 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sin().
der_x() [3/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_x (DataType_ x, DataType_ y, DataType_ z) inline static
3D: X-derivative
Definition at line 444 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sin().
der_xx() [1/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xx (DataType_ x) inline static
1D: XX-derivative
Definition at line 462 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sqr().
Referenced by FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yy(), and FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_zz().
der_xx() [2/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xx (DataType_ x, DataType_ y) inline static
2D: XX-derivative
Definition at line 468 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sqr().
der_xx() [3/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xx (DataType_ x, DataType_ y, DataType_ z) inline static
3D: XX-derivative
Definition at line 492 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sqr().
der_xy() [1/2]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xy (DataType_ x, DataType_ y) inline static
2D: XY-derivative
Definition at line 480 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), FEAT::Math::sin(), and FEAT::Math::sqr().
Referenced by FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yx().
der_xy() [2/2]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xy (DataType_ x, DataType_ y, DataType_ z) inline static
3D: XY-derivative
Definition at line 510 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), FEAT::Math::sin(), and FEAT::Math::sqr().
der_xz()
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xz (DataType_ x, DataType_ y, DataType_ z) inline static
3D: XZ-derivative
Definition at line 522 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), FEAT::Math::sin(), and FEAT::Math::sqr().
Referenced by FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_zx().
der_y() [1/2]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_y (DataType_ x, DataType_ y) inline static
2D: Y-derivative
Definition at line 438 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sin().
der_y() [2/2]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_y (DataType_ x, DataType_ y, DataType_ z) inline static
3D: Y-derivative
Definition at line 450 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sin().
der_yx() [1/2]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yx (DataType_ x, DataType_ y) inline static
2D: YX-derivative
Definition at line 486 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xy().
der_yx() [2/2]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yx (DataType_ x, DataType_ y, DataType_ z) inline static
3D: YX-derivative
Definition at line 516 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xy().
der_yy() [1/2]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yy (DataType_ x, DataType_ y) inline static
2D: YY-derivative
Definition at line 474 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xx().
der_yy() [2/2]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yy (DataType_ x, DataType_ y, DataType_ z) inline static
3D: YY-derivative
Definition at line 498 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xx().
der_yz()
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yz (DataType_ x, DataType_ y, DataType_ z) inline static
3D: YZ-derivative
Definition at line 534 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), FEAT::Math::sin(), and FEAT::Math::sqr().
Referenced by FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_zy().
der_z()
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_z (DataType_ x, DataType_ y, DataType_ z) inline static
3D: Z-derivative
Definition at line 456 of file common.hpp.
References FEAT::Math::cos(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi(), and FEAT::Math::sin().
der_zx()
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_zx (DataType_ x, DataType_ y, DataType_ z) inline static
3D: ZX-derivative
Definition at line 528 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xz().
der_zy()
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_zy (DataType_ x, DataType_ y, DataType_ z) inline static
3D: ZY-derivative
Definition at line 540 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yz().
der_zz()
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_zz (DataType_ x, DataType_ y, DataType_ z) inline static
3D: ZZ-derivative
Definition at line 504 of file common.hpp.
References FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xx().
eval() [1/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::eval (DataType_ x) inline static
1D: function value
Definition at line 408 of file common.hpp.
References FEAT::Math::cos(), and FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi().
eval() [2/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::eval (DataType_ x, DataType_ y) inline static
2D: function value
Definition at line 414 of file common.hpp.
References FEAT::Math::cos(), and FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi().
eval() [3/3]
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::eval (DataType_ x, DataType_ y, DataType_ z) inline static
3D: function value
Definition at line 420 of file common.hpp.
References FEAT::Math::cos(), and FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi().
kpi()
template<typename DataType_ , int k_ = 1> static DataType_ FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::kpi () inline static
Returns k times pi.
Definition at line 402 of file common.hpp.
Referenced by FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_x(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xx(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xy(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_xz(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_y(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_yz(), FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::der_z(), and FEAT::Analytic::Common::CosineTensorStatic< DataType_, k_ >::eval().
The documentation for this class was generated from the following file:
kernel/analytic/common.hpp