FEAT: FEAT::Assembly::VelocityAnalyser Class Reference
FEAT::Assembly::VelocityAnalyser Class Reference
Velocity field analyser class.
#include <velocity_analyser.hpp>
Static Public Member Functions
template<typename DataType_ , typename IndexType_ , int dim_, typename Space_ >
static VelocityInfo< DataType_, dim_ > compute (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > &vector, const Space_ &space, const Cubature::DynamicFactory &cubature_factory)
Performs the analysis of a velocity field.
template<typename DataType_ , typename IndexType_ , int dim_, typename Space_ >
static VelocityInfo< DataType_, dim_ > compute (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > &vector, const Space_ &space, const String &cubature_name)
Performs the analysis of a velocity field.
template<typename DataType_ , typename IndexType_ , int dim_, typename Space_ >
static VelocityInfo< DataType_, dim_ > compute (const LAFEM::PowerVector< LAFEM::DenseVector< DataType_, IndexType_ >, dim_ > &vector, const Space_ &space, const Cubature::DynamicFactory &cubature_factory)
Performs the analysis of a velocity field.
template<typename DataType_ , typename IndexType_ , int dim_, typename Space_ >
static VelocityInfo< DataType_, dim_ > compute (const LAFEM::PowerVector< LAFEM::DenseVector< DataType_, IndexType_ >, dim_ > &vector, const Space_ &space, const String &cubature_name)
Performs the analysis of a velocity field.
Detailed Description
Velocity field analyser class.
This class can be used for post-processing of a 2D or 3D velocity vector field. For more information about the computed quantities, see the VelocityInfo struct.
Author
Peter Zajac
Definition at line 197 of file velocity_analyser.hpp.
Member Function Documentation
compute() [1/4]
template<typename DataType_ , typename IndexType_ , int dim_, typename Space_ > static VelocityInfo< DataType_, dim_ > FEAT::Assembly::VelocityAnalyser::compute (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > & vector, const Space_ & space, const Cubature::DynamicFactory & cubature_factory) inline static
Performs the analysis of a velocity field.
Parameters
[in] vector The transient vector representing the velocity field to be analyzed.
[in] space The transient finite element space for the velocity.
[in] cubature_factory The cubature factory to be used for integration.
Returns
A VelocityInfo structure containing the computed information.
space type
assembly traits
data type
Definition at line 452 of file velocity_analyser.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_outer_product(), FEAT::Tiny::Vector< T_, n_, s_ >::axpy(), FEAT::Assembly::VelocityInfo< DataType_, dim_ >::divergence, FEAT::Tiny::dot(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::Assembly::VelocityInfo< DataType_, dim_ >::norm_h0, FEAT::Assembly::VelocityInfo< DataType_, dim_ >::norm_h0_comp, FEAT::Assembly::VelocityInfo< DataType_, dim_ >::norm_h1, FEAT::Assembly::VelocityInfo< DataType_, dim_ >::norm_h1_comp, FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::Math::sqr(), FEAT::Math::sqrt(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::trace(), FEAT::Assembly::VelocityInfo< DataType_, dim_ >::vorticity, and XASSERTM.
compute() [2/4]
template<typename DataType_ , typename IndexType_ , int dim_, typename Space_ > static VelocityInfo< DataType_, dim_ > FEAT::Assembly::VelocityAnalyser::compute (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > & vector, const Space_ & space, const String & cubature_name) inline static
Performs the analysis of a velocity field.
Parameters
[in] vector The transient vector representing the velocity field to be analyzed.
[in] space The transient finite element space for the velocity.
[in] cubature_name The name of the cubature rule to be used for integration.
Returns
A VelocityInfo structure containing the computed information.
Definition at line 428 of file velocity_analyser.hpp.
References compute().
compute() [3/4]
template<typename DataType_ , typename IndexType_ , int dim_, typename Space_ > static VelocityInfo< DataType_, dim_ > FEAT::Assembly::VelocityAnalyser::compute (const LAFEM::PowerVector< LAFEM::DenseVector< DataType_, IndexType_ >, dim_ > & vector, const Space_ & space, const Cubature::DynamicFactory & cubature_factory) inline static
Performs the analysis of a velocity field.
Parameters
[in] vector The transient vector representing the velocity field to be analyzed.
[in] space The transient finite element space for the velocity.
[in] cubature_factory The cubature factory to be used for integration.
Returns
A VelocityInfo structure containing the computed information.
space type
assembly traits
data type
Definition at line 261 of file velocity_analyser.hpp.
References FEAT::Assembly::VelocityInfo< DataType_, dim_ >::divergence, FEAT::Tiny::dot(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::Assembly::VelocityInfo< DataType_, dim_ >::norm_h0, FEAT::Assembly::VelocityInfo< DataType_, dim_ >::norm_h0_comp, FEAT::Assembly::VelocityInfo< DataType_, dim_ >::norm_h1, FEAT::Assembly::VelocityInfo< DataType_, dim_ >::norm_h1_comp, FEAT::Math::sqr(), FEAT::Math::sqrt(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::trace(), and FEAT::Assembly::VelocityInfo< DataType_, dim_ >::vorticity.
compute() [4/4]
template<typename DataType_ , typename IndexType_ , int dim_, typename Space_ > static VelocityInfo< DataType_, dim_ > FEAT::Assembly::VelocityAnalyser::compute (const LAFEM::PowerVector< LAFEM::DenseVector< DataType_, IndexType_ >, dim_ > & vector, const Space_ & space, const String & cubature_name) inline static
Performs the analysis of a velocity field.
Parameters
[in] vector The transient vector representing the velocity field to be analyzed.
[in] space The transient finite element space for the velocity.
[in] cubature_name The name of the cubature rule to be used for integration.
Returns
A VelocityInfo structure containing the computed information.
Definition at line 237 of file velocity_analyser.hpp.
References compute().
Referenced by compute().
The documentation for this class was generated from the following file:
kernel/assembly/velocity_analyser.hpp