FEAT: FEAT::Tiny::Vector< T_, n_, s_ > Class Template Reference
FEAT::Tiny::Vector< T_, n_, s_ > Class Template Reference
Tiny Vector class template.
#include <tiny_algebra.hpp>
Public Types
typedef Intern::DataTypeExtractor< ValueType >::MyDataType DataType
The basic data type buried in the lowest level of the vector.
typedef T_ ValueType
the value type of the vector
Public Member Functions
CUDA_HOST_DEVICE Vector ()
default constructor
template<typename Tx_ >
CUDA_HOST_DEVICE Vector (const std::initializer_list< Tx_ > &x)
Initializer list constructor.
template<int sx_>
CUDA_HOST_DEVICE Vector (const Vector< T_, n_, sx_ > &x)
copy constructor
CUDA_HOST_DEVICE Vector (DataType value)
value-assignment constructor
template<int m_, int sma_, int sna_, int sx_>
CUDA_HOST_DEVICE Vector & add_mat_vec_mult (const Matrix< T_, n_, m_, sma_, sna_ > &a, const Vector< T_, m_, sx_ > &x, DataType alpha=DataType(1))
Adds the result of a matrix-vector product onto this vector.
template<int m_, int sma_, int sna_, int sx_>
CUDA_HOST_DEVICE Vector & add_vec_mat_mult (const Vector< T_, m_, sx_ > &x, const Matrix< T_, m_, n_, sma_, sna_ > &a, DataType alpha=DataType(1))
Adds the result of a vector-matrix product onto this vector.
template<int snx_>
CUDA_HOST_DEVICE Vector & axpy (DataType alpha, const Vector< T_, n_, snx_ > &x)
Adds another scaled vector onto this vector.
CUDA_HOST_DEVICE void format (DataType alpha=DataType(0))
Format the vector.
CUDA_HOST_DEVICE Vector & negate ()
Negates the vector, i.e. effectively multiplies all components by -1.
CUDA_HOST_DEVICE DataType norm_euclid () const
Computes the euclid norm of the vector.
CUDA_HOST_DEVICE DataType norm_euclid_sqr () const
Computes the squared euclid norm of the vector.
CUDA_HOST_DEVICE DataType norm_l1 () const
Computes the l1-norm of the vector.
CUDA_HOST_DEVICE DataType norm_max () const
Computes the max-norm of the vector.
CUDA_HOST_DEVICE Vector & normalize ()
Normalizes this vector.
CUDA_HOST_DEVICE T_ & operator() (int i)
Access operator.
CUDA_HOST_DEVICE const T_ & operator() (int i) const
Access operator.
template<int sx_>
CUDA_HOST_DEVICE Vector & operator*= (const Vector< T_, n_, sx_ > &x)
element-wise-multiply operator
CUDA_HOST_DEVICE Vector & operator*= (DataType alpha)
scalar-multiply operator
template<int sx_>
CUDA_HOST_DEVICE Vector & operator+= (const Vector< T_, n_, sx_ > &x)
vector-add operator
template<int sx_>
CUDA_HOST_DEVICE Vector & operator-= (const Vector< T_, n_, sx_ > &x)
vector-subtract operator
template<typename Tx_ >
CUDA_HOST_DEVICE Vector & operator= (const std::initializer_list< Tx_ > &x)
Initializer list assignment operator.
template<int sx_>
CUDA_HOST_DEVICE Vector & operator= (const Vector< T_, n_, sx_ > &x)
copy-assignment operator
CUDA_HOST_DEVICE Vector & operator= (DataType value)
value-assignment operator
CUDA_HOST_DEVICE T_ & operator[] (int i)
Access operator.
CUDA_HOST_DEVICE const T_ & operator[] (int i) const
Access operator.
template<int sna_, int snb_>
CUDA_HOST_DEVICE Vector & set_convex (DataType alpha, const Vector< T_, n_, sna_ > &a, const Vector< T_, n_, snb_ > &b)
Sets this vector to the convex combination of two other vectors.
template<int m_, int sma_, int sna_, int sx_>
CUDA_HOST_DEVICE Vector & set_mat_vec_mult (const Matrix< T_, n_, m_, sma_, sna_ > &a, const Vector< T_, m_, sx_ > &x)
Sets this vector to the result of a matrix-vector product.
template<int m_, int sma_, int sna_, int sx_>
CUDA_HOST_DEVICE Vector & set_vec_mat_mult (const Vector< T_, m_, sx_ > &x, const Matrix< T_, m_, n_, sma_, sna_ > &a)
Sets this vector to the result of a vector-matrix product.
template<int nn_>
CUDA_HOST_DEVICE Vector< T_, nn_, s_ > & size_cast ()
Size-cast function.
template<int nn_>
CUDA_HOST_DEVICE const Vector< T_, nn_, s_ > & size_cast () const
Size-cast function.
Static Public Member Functions
static CUDA_HOST_DEVICE Vector null ()
Returns a null-vector.
Public Attributes
T_ v [s_]
actual vector data
Static Public Attributes
static constexpr int n = n_
the length of the vector
static constexpr int s = s_
the stride of the vector
Friends
CUDA_HOST friend std::ostream & operator<< (std::ostream &lhs, const Vector &b)
Tiny::Vector streaming operator.
Detailed Description
template<typename T_, int n_, int s_ = n_>
class FEAT::Tiny::Vector< T_, n_, s_ >
Tiny Vector class template.
This class template implements a vector whose value type and size is given at compile-time. The value type can be a primitive type, or some other object like (again) a Vector.
Template Parameters
T_ The value-type that the vector shall contain.
n_ The length of the vector. Must be > 0.
s_ The stride of the vector. Must be >= n_.
Author
Peter Zajac
Definition at line 52 of file tiny_algebra.hpp.
Member Typedef Documentation
DataType
template<typename T_ , int n_, int s_ = n_> typedef Intern::DataTypeExtractor<ValueType>::MyDataType FEAT::Tiny::Vector< T_, n_, s_ >::DataType
The basic data type buried in the lowest level of the vector.
Definition at line 217 of file tiny_algebra.hpp.
ValueType
template<typename T_ , int n_, int s_ = n_> typedef T_ FEAT::Tiny::Vector< T_, n_, s_ >::ValueType
the value type of the vector
Definition at line 215 of file tiny_algebra.hpp.
Constructor & Destructor Documentation
Vector() [1/4]
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE FEAT::Tiny::Vector< T_, n_, s_ >::Vector () inline
default constructor
Definition at line 223 of file tiny_algebra.hpp.
Referenced by FEAT::Tiny::Vector< T_, n_, s_ >::null().
Vector() [2/4]
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE FEAT::Tiny::Vector< T_, n_, s_ >::Vector (DataType value) inline explicit
value-assignment constructor
Definition at line 228 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::value.
Vector() [3/4]
template<typename T_ , int n_, int s_ = n_> template<int sx_> CUDA_HOST_DEVICE FEAT::Tiny::Vector< T_, n_, s_ >::Vector (const Vector< T_, n_, sx_ > & x) inline
copy constructor
Definition at line 238 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
Vector() [4/4]
template<typename T_ , int n_, int s_ = n_> template<typename Tx_ > CUDA_HOST_DEVICE FEAT::Tiny::Vector< T_, n_, s_ >::Vector (const std::initializer_list< Tx_ > & x) inline explicit
Initializer list constructor.
This operator allows to assign values to a new vector in a simple manner:
Tiny::Vector<double, 3> v1{0.1, 2.1, 7.3};
Tiny::Vector<double, 3> v2 = {0.1, 2.1, 7.3};
Parameters
[in] x The initializer list whose elements are to be assigned.
Definition at line 259 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v, and XASSERTM.
Member Function Documentation
add_mat_vec_mult()
template<typename T_ , int n_, int s_ = n_> template<int m_, int sma_, int sna_, int sx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::add_mat_vec_mult (const Matrix< T_, n_, m_, sma_, sna_ > & a, const Vector< T_, m_, sx_ > & x, DataType alpha = DataType(1)) inline
Adds the result of a matrix-vector product onto this vector.
Let y denote this vector, and let A denote the input matrix and x in the input vector, then this function computes:
\[ y \leftarrow y + \alpha\cdot A\cdot x \]
Parameters
[in] a The matrix for the product.
[in] x The (right) multiplicand vector for the product.
[in] alpha The scaling parameter for the product.
Returns
*this
Definition at line 587 of file tiny_algebra.hpp.
References ASSERTM, FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
add_vec_mat_mult()
template<typename T_ , int n_, int s_ = n_> template<int m_, int sma_, int sna_, int sx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::add_vec_mat_mult (const Vector< T_, m_, sx_ > & x, const Matrix< T_, m_, n_, sma_, sna_ > & a, DataType alpha = DataType(1)) inline
Adds the result of a vector-matrix product onto this vector.
Let y denote this vector, and let x in the input vector and A denote the input matrix, then this function computes:
\[ y^\top \leftarrow y^\top + \alpha\cdot x^\top \cdot A \Longleftrightarrow y \leftarrow y + \alpha\cdot A^\top\cdot x \]
Parameters
[in] x The (left) multiplicand vector for the product.
[in] a The matrix for the product.
[in] alpha The scaling parameter for the product.
Returns
*this
Definition at line 621 of file tiny_algebra.hpp.
References ASSERTM, FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
axpy()
template<typename T_ , int n_, int s_ = n_> template<int snx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::axpy (DataType alpha, const Vector< T_, n_, snx_ > & x) inline
Adds another scaled vector onto this vector.
Parameters
[in] x The vector to be added onto this vector.
[in] alpha The scaling parameter for the axpy.
Returns
*this
Definition at line 472 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::OldroydAssembler::assemble_matrix(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_scalar_matrix(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_vector(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_vector(), FEAT::Assembly::VelocityAnalyser::compute(), FEAT::Assembly::VectorErrorComputer< max_norm_ >::compute(), FEAT::Assembly::BurgersAssemblyTaskBase< Job_, DataType_ >::prepare(), and FEAT::Assembly::BurgersAssemblyTaskBase< Job_, DataType_ >::prepare_point().
format()
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE void FEAT::Tiny::Vector< T_, n_, s_ >::format (DataType alpha = DataType(0)) inline
Format the vector.
Parameters
[in] alpha The value that the vector is to be set to.
Definition at line 422 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
Referenced by FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_functional_vector(), FEAT::Assembly::GridTransfer::assemble_intermesh_transfer(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_operator_matrix(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_stabil_operator_matrix(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::OldroydAssembler::assemble_matrix(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2(), FEAT::Assembly::GridTransfer::assemble_prolongation(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_scalar_matrix(), FEAT::Assembly::GridTransfer::assemble_truncation(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_vector(), FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::assemble_vector(), FEAT::Assembly::VelocityAnalyser::compute(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min(), FEAT::Assembly::BurgersBlockedVectorAssemblyJob< Vector_, Space_, ConvVector_ >::Task::compute_local_vector(), FEAT::Assembly::BurgersScalarVectorAssemblyJob< Vector_, Space_, ConvVector_ >::Task::compute_local_vector(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::mean_value(), FEAT::Assembly::VectorDiscreteEvalData< DT_, dim_ >::mean_value_dist(), FEAT::Assembly::BurgersAssemblyTaskBase< Job_, DataType_ >::prepare(), FEAT::Assembly::BurgersAssemblyTaskBase< Job_, DataType_ >::prepare_point(), and FEAT::Assembly::GridTransfer::prolongate_vector().
negate()
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::negate () inline
Negates the vector, i.e. effectively multiplies all components by -1.
Returns
*this
Definition at line 453 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
norm_euclid()
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE DataType FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid () const inline
Computes the euclid norm of the vector.
Returns
The euclid norm of the vector.
Definition at line 660 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid_sqr(), and FEAT::Math::sqrt().
Referenced by FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_matrix(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::assemble_scalar_matrix(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Trafo::Standard::inverse_mapping(), FEAT::Tiny::Vector< T_, n_, s_ >::normalize(), FEAT::Assembly::BurgersAssemblyTaskBase< Job_, DataType_ >::prepare(), and FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::project_point().
norm_euclid_sqr()
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE DataType FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid_sqr () const inline
Computes the squared euclid norm of the vector.
Returns
The squared euclid norm of the vector.
Definition at line 642 of file tiny_algebra.hpp.
References FEAT::Math::sqr(), and FEAT::Tiny::Vector< T_, n_, s_ >::v.
Referenced by FEAT::Assembly::FunctionIntegralInfo< DataType_, ValueType_, GradientType_, HessianType_ >::add_grad(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid(), FEAT::Tiny::Vector< T_, n_, s_ >::normalize(), FEAT::Trafo::InverseMapping< Trafo_, DataType_ >::unmap_point_by_newton(), and FEAT::Geometry::Atlas::Extrude< Mesh_, SubChart_ >::write().
norm_l1()
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE DataType FEAT::Tiny::Vector< T_, n_, s_ >::norm_l1 () const inline
Computes the l1-norm of the vector.
Returns
The l1-norm of the vector.
Definition at line 675 of file tiny_algebra.hpp.
References FEAT::Math::abs(), and FEAT::Tiny::Vector< T_, n_, s_ >::v.
norm_max()
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE DataType FEAT::Tiny::Vector< T_, n_, s_ >::norm_max () const inline
Computes the max-norm of the vector.
Returns
The max-norm of the vector.
Definition at line 693 of file tiny_algebra.hpp.
References FEAT::Math::abs(), FEAT::Math::max(), and FEAT::Tiny::Vector< T_, n_, s_ >::v.
normalize()
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::normalize () inline
Normalizes this vector.
Returns
*this
Definition at line 435 of file tiny_algebra.hpp.
References ASSERTM, FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid(), and FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid_sqr().
Referenced by FEAT::Trafo::Standard::inverse_mapping(), and FEAT::Trafo::IsoSphere::Evaluator< Trafo_, EvalPolicy_, Shape::Vertex >::prepare().
null()
template<typename T_ , int n_, int s_ = n_> static CUDA_HOST_DEVICE Vector FEAT::Tiny::Vector< T_, n_, s_ >::null () inline static
Returns a null-vector.
Definition at line 708 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::Vector().
operator()() [1/2]
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE T_ & FEAT::Tiny::Vector< T_, n_, s_ >::operator() (int i) inline
Access operator.
Parameters
[in] i The index of the vector component to be returned.
Returns
A (const) reference to the i-th entry of the vector.
Definition at line 320 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator()() [2/2]
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE const T_ & FEAT::Tiny::Vector< T_, n_, s_ >::operator() (int i) const inline
Access operator.
Parameters
[in] i The index of the vector component to be returned.
Returns
A (const) reference to the i-th entry of the vector.
Definition at line 327 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator*=() [1/2]
template<typename T_ , int n_, int s_ = n_> template<int sx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::operator*= (const Vector< T_, n_, sx_ > & x) inline
element-wise-multiply operator
Definition at line 385 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator*=() [2/2]
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::operator*= (DataType alpha) inline
scalar-multiply operator
Definition at line 374 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator+=()
template<typename T_ , int n_, int s_ = n_> template<int sx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::operator+= (const Vector< T_, n_, sx_ > & x) inline
vector-add operator
Definition at line 396 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator-=()
template<typename T_ , int n_, int s_ = n_> template<int sx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::operator-= (const Vector< T_, n_, sx_ > & x) inline
vector-subtract operator
Definition at line 407 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator=() [1/3]
template<typename T_ , int n_, int s_ = n_> template<typename Tx_ > CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::operator= (const std::initializer_list< Tx_ > & x) inline
Initializer list assignment operator.
This operator allows to assign values to the vector in a simple manner:
Tiny::Vector<double, 3> v;
v = {0.1, 2.1, 7.3};
Parameters
[in] x The initializer list whose elements are to be assigned.
Returns
*this
Definition at line 303 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v, and XASSERTM.
operator=() [2/3]
template<typename T_ , int n_, int s_ = n_> template<int sx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::operator= (const Vector< T_, n_, sx_ > & x) inline
copy-assignment operator
Definition at line 279 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator=() [3/3]
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::operator= (DataType value) inline
value-assignment operator
Definition at line 268 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::value.
operator[]() [1/2]
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE T_ & FEAT::Tiny::Vector< T_, n_, s_ >::operator[] (int i) inline
Access operator.
Parameters
[in] i The index of the vector component to be returned.
Returns
A (const) reference to the i-th entry of the vector.
Definition at line 334 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Vector< T_, n_, s_ >::v.
operator[]() [2/2]
template<typename T_ , int n_, int s_ = n_> CUDA_HOST_DEVICE const T_ & FEAT::Tiny::Vector< T_, n_, s_ >::operator[] (int i) const inline
Access operator.
Parameters
[in] i The index of the vector component to be returned.
Returns
A (const) reference to the i-th entry of the vector.
Definition at line 341 of file tiny_algebra.hpp.
References ASSERTM, and FEAT::Tiny::Vector< T_, n_, s_ >::v.
set_convex()
template<typename T_ , int n_, int s_ = n_> template<int sna_, int snb_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::set_convex (DataType alpha, const Vector< T_, n_, sna_ > & a, const Vector< T_, n_, snb_ > & b) inline
Sets this vector to the convex combination of two other vectors.
Let y denote this vector, then this function computes:
\[ y \leftarrow (1-\alpha)\cdot a + \alpha\cdot b \]
Parameters
[in] alpha The interpolation parameter for the convex combination. Should be 0 <= alpha <= 1
[in] a The first vector for the convex combination.
[in] b The second vector for the convex combination.
Returns
*this
Definition at line 497 of file tiny_algebra.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::v.
Referenced by FEAT::Trafo::Isoparam::Evaluator< Trafo_, EvalPolicy_, degree_, Shape::Hypercube< 2 > >::prepare().
set_mat_vec_mult()
template<typename T_ , int n_, int s_ = n_> template<int m_, int sma_, int sna_, int sx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::set_mat_vec_mult (const Matrix< T_, n_, m_, sma_, sna_ > & a, const Vector< T_, m_, sx_ > & x) inline
Sets this vector to the result of a matrix-vector product.
Let y denote this vector, and let A denote the input matrix and x in the input vector, then this function computes:
\[ y \leftarrow A\cdot x \]
Parameters
[in] a The matrix for the product.
[in] x The (right) multiplicand vector for the product.
Returns
*this
Definition at line 520 of file tiny_algebra.hpp.
References ASSERTM, FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_vertex_set(), and FEAT::Tiny::operator*().
set_vec_mat_mult()
template<typename T_ , int n_, int s_ = n_> template<int m_, int sma_, int sna_, int sx_> CUDA_HOST_DEVICE Vector & FEAT::Tiny::Vector< T_, n_, s_ >::set_vec_mat_mult (const Vector< T_, m_, sx_ > & x, const Matrix< T_, m_, n_, sma_, sna_ > & a) inline
Sets this vector to the result of a vector-matrix product.
Let y denote this vector, and let x in the input vector and A denote the input matrix, then this function computes:
\[ y^\top \leftarrow x^\top \cdot A \Longleftrightarrow y \leftarrow A^\top\cdot x \]
Parameters
[in] x The (left) multiplicand vector for the product.
[in] a The matrix for the product.
Returns
*this
Definition at line 552 of file tiny_algebra.hpp.
References ASSERTM, FEAT::Tiny::Vector< T_, n_, s_ >::v, and FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::v.
Referenced by FEAT::Tiny::operator*().
size_cast() [1/2]
template<typename T_ , int n_, int s_ = n_> template<int nn_> CUDA_HOST_DEVICE Vector< T_, nn_, s_ > & FEAT::Tiny::Vector< T_, n_, s_ >::size_cast () inline
Size-cast function.
This function casts this vector's reference to another size.
Template Parameters
nn_ The length of the casted vector. Must be 0 < nn_ <= s_.
Returns
A casted (const) reference of *this.
Definition at line 359 of file tiny_algebra.hpp.
size_cast() [2/2]
template<typename T_ , int n_, int s_ = n_> template<int nn_> CUDA_HOST_DEVICE const Vector< T_, nn_, s_ > & FEAT::Tiny::Vector< T_, n_, s_ >::size_cast () const inline
Size-cast function.
This function casts this vector's reference to another size.
Template Parameters
nn_ The length of the casted vector. Must be 0 < nn_ <= s_.
Returns
A casted (const) reference of *this.
Definition at line 367 of file tiny_algebra.hpp.
Friends And Related Function Documentation
operator<<
template<typename T_ , int n_, int s_ = n_> CUDA_HOST friend std::ostream & operator<< (std::ostream & lhs, const Vector< T_, n_, s_ > & b) friend
Tiny::Vector streaming operator.
Parameters
[in] lhs The target stream.
[in] b The vector to be streamed.
Definition at line 719 of file tiny_algebra.hpp.
Member Data Documentation
n
template<typename T_ , int n_, int s_ = n_> constexpr int FEAT::Tiny::Vector< T_, n_, s_ >::n = n_ static constexpr
the length of the vector
Definition at line 210 of file tiny_algebra.hpp.
s
template<typename T_ , int n_, int s_ = n_> constexpr int FEAT::Tiny::Vector< T_, n_, s_ >::s = s_ static constexpr
the stride of the vector
Definition at line 212 of file tiny_algebra.hpp.
v
template<typename T_ , int n_, int s_ = n_> T_ FEAT::Tiny::Vector< T_, n_, s_ >::v[s_]
actual vector data
Definition at line 220 of file tiny_algebra.hpp.
Referenced by FEAT::Tiny::Vector< T_, n_, s_ >::Vector(), FEAT::Tiny::Vector< T_, n_, s_ >::add_mat_vec_mult(), FEAT::Tiny::Vector< T_, n_, s_ >::add_vec_mat_mult(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::axpy(), FEAT::Tiny::Vector< T_, n_, s_ >::axpy(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Vector< T_, n_, s_ >::negate(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_euclid_sqr(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_l1(), FEAT::Tiny::Vector< T_, n_, s_ >::norm_max(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::Tiny::Vector< T_, n_, s_ >::operator()(), FEAT::Tiny::Vector< T_, n_, s_ >::operator*=(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator+=(), FEAT::Tiny::Vector< T_, n_, s_ >::operator+=(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator-=(), FEAT::Tiny::Vector< T_, n_, s_ >::operator-=(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::operator=(), FEAT::Tiny::Vector< T_, n_, s_ >::operator=(), FEAT::Tiny::Vector< T_, n_, s_ >::operator[](), FEAT::Tiny::Vector< T_, n_, s_ >::set_convex(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_gram(), FEAT::Tiny::Vector< T_, n_, s_ >::set_mat_vec_mult(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::set_transpose(), and FEAT::Tiny::Vector< T_, n_, s_ >::set_vec_mat_mult().
The documentation for this class was generated from the following file:
kernel/util/tiny_algebra.hpp