FEAT: FEAT::LAFEM::PowerFilter< SubFilter_, count_ > Class Template Reference
FEAT::LAFEM::PowerFilter< SubFilter_, count_ > Class Template Reference
PowerVector meta-filter class template.
#include <power_filter.hpp>
Public Types
typedef SubFilter_::DataType DataType
sub-filter data-type
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using FilterType = PowerFilter< typename SubFilterType::template FilterType< DT2_, IT2_ >, count_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using FilterTypeByDI = FilterType< DataType2_, IndexType2_ >
this typedef lets you create a filter with different Data and Index types
typedef SubFilter_::IndexType IndexType
sub-filter index-type
typedef SubFilter_ SubFilterType
sub-filter type
typedef PowerVector< typename SubFilter_::VectorType, count_ > VectorType
vector type
Public Member Functions
PowerFilter ()
default ctor
PowerFilter (PowerFilter &&other)
move CTOR
template<int i_>
SubFilterType & at ()
template<int i_>
const SubFilterType & at () const
std::size_t bytes () const
Returns the total amount of bytes allocated.
PowerFilter clone (CloneMode clone_mode=CloneMode::Deep) const
Creates a clone of itself.
void clone (const PowerFilter &other, CloneMode clone_mode=CloneMode::Deep)
Clones data from another PowerFilter.
template<typename SubFilter2_ >
void convert (const PowerFilter< SubFilter2_, count_ > &other)
Conversion method.
void filter_cor (VectorType &vector) const
Applies the filter onto a correction vector.
void filter_def (VectorType &vector) const
Applies the filter onto a defect vector.
void filter_rhs (VectorType &vector) const
Applies the filter onto the right-hand-side vector.
void filter_sol (VectorType &vector) const
Applies the filter onto the solution vector.
SubFilterType & get (int i)
Returns a sub-filter block.
const SubFilterType & get (int i) const
Returns a sub-filter block.
PowerFilter & operator= (PowerFilter &&other)
move-assign operator
Static Public Attributes
static constexpr int num_blocks = count_
number of filter blocks
Protected Member Functions
PowerFilter (SubFilterType &&the_first, RestClass &&the_rest)
base-class ctor; for internal use only
Protected Attributes
SubFilterType _first
the first sub-filter
RestClass _rest
the remaining part
Private Types
typedef PowerFilter< SubFilter_, count_-1 > RestClass
base-class typedef
Detailed Description
template<typename SubFilter_, int count_>
class FEAT::LAFEM::PowerFilter< SubFilter_, count_ >
PowerVector meta-filter class template.
This class template implements a composition of n sub-filters of the same type, which can be applied onto PowerVector meta-container objects.
Note
For a composed meta-filter of different sub-filters, see the TupleFilter class template.
Template Parameters
SubFilter_ The type of the sub-filter.
count_ The number of sub-filter blocks.
Author
Peter Zajac
Definition at line 34 of file power_filter.hpp.
Member Typedef Documentation
DataType
template<typename SubFilter_ , int count_> typedef SubFilter_::DataType FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::DataType
sub-filter data-type
Definition at line 50 of file power_filter.hpp.
FilterType
template<typename SubFilter_ , int count_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::FilterType = PowerFilter<typename SubFilterType::template FilterType<DT2_, IT2_>, count_>
Our 'base' class type.
Definition at line 62 of file power_filter.hpp.
FilterTypeByDI
template<typename SubFilter_ , int count_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::FilterTypeByDI = FilterType<DataType2_, IndexType2_>
this typedef lets you create a filter with different Data and Index types
Definition at line 66 of file power_filter.hpp.
IndexType
template<typename SubFilter_ , int count_> typedef SubFilter_::IndexType FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::IndexType
sub-filter index-type
Definition at line 52 of file power_filter.hpp.
RestClass
template<typename SubFilter_ , int count_> typedef PowerFilter<SubFilter_, count_-1> FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::RestClass private
base-class typedef
Definition at line 44 of file power_filter.hpp.
SubFilterType
template<typename SubFilter_ , int count_> typedef SubFilter_ FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::SubFilterType
sub-filter type
Definition at line 48 of file power_filter.hpp.
VectorType
template<typename SubFilter_ , int count_> typedef PowerVector<typename SubFilter_::VectorType, count_> FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::VectorType
vector type
Definition at line 58 of file power_filter.hpp.
Constructor & Destructor Documentation
PowerFilter() [1/3]
template<typename SubFilter_ , int count_> FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::PowerFilter (SubFilterType && the_first, RestClass && the_rest) inline explicit protected
base-class ctor; for internal use only
Definition at line 75 of file power_filter.hpp.
PowerFilter() [2/3]
template<typename SubFilter_ , int count_> FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::PowerFilter () inline
default ctor
Definition at line 83 of file power_filter.hpp.
PowerFilter() [3/3]
template<typename SubFilter_ , int count_> FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::PowerFilter (PowerFilter< SubFilter_, count_ > && other) inline
move CTOR
Definition at line 88 of file power_filter.hpp.
Member Function Documentation
at() [1/2]
template<typename SubFilter_ , int count_> template<int i_> SubFilterType & FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::at () inline
Definition at line 155 of file power_filter.hpp.
at() [2/2]
template<typename SubFilter_ , int count_> template<int i_> const SubFilterType & FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::at () const inline
Definition at line 162 of file power_filter.hpp.
bytes()
template<typename SubFilter_ , int count_> std::size_t FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 127 of file power_filter.hpp.
References FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_first, FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_rest, and FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::bytes().
Referenced by FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::bytes().
clone() [1/2]
template<typename SubFilter_ , int count_> PowerFilter FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Creates a clone of itself.
Definition at line 106 of file power_filter.hpp.
References FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::clone().
Referenced by FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::clone().
clone() [2/2]
template<typename SubFilter_ , int count_> void FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::clone (const PowerFilter< SubFilter_, count_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clones data from another PowerFilter.
Definition at line 112 of file power_filter.hpp.
References FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_first, FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_rest, and FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::clone().
convert()
template<typename SubFilter_ , int count_> template<typename SubFilter2_ > void FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::convert (const PowerFilter< SubFilter2_, count_ > & other) inline
Conversion method.
Definition at line 120 of file power_filter.hpp.
References FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_first, FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_rest, and FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::convert().
Referenced by FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::convert().
filter_cor()
template<typename SubFilter_ , int count_> void FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::filter_cor (VectorType & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 212 of file power_filter.hpp.
filter_def()
template<typename SubFilter_ , int count_> void FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::filter_def (VectorType & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 205 of file power_filter.hpp.
filter_rhs()
template<typename SubFilter_ , int count_> void FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::filter_rhs (VectorType & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 191 of file power_filter.hpp.
filter_sol()
template<typename SubFilter_ , int count_> void FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::filter_sol (VectorType & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 198 of file power_filter.hpp.
get() [1/2]
template<typename SubFilter_ , int count_> SubFilterType & FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::get (int i) inline
Returns a sub-filter block.
Parameters
[in] i The index of the sub-filter block that is to be returned.
Returns
A (const) reference to the sub-filter at position i.
Definition at line 177 of file power_filter.hpp.
References FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_first, FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_rest, FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::get(), and XASSERTM.
Referenced by FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::get().
get() [2/2]
template<typename SubFilter_ , int count_> const SubFilterType & FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::get (int i) const inline
Returns a sub-filter block.
Parameters
[in] i The index of the sub-filter block that is to be returned.
Returns
A (const) reference to the sub-filter at position i.
Definition at line 184 of file power_filter.hpp.
References FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_first, FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_rest, FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::get(), and XASSERTM.
operator=()
template<typename SubFilter_ , int count_> PowerFilter & FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::operator= (PowerFilter< SubFilter_, count_ > && other) inline
move-assign operator
Definition at line 95 of file power_filter.hpp.
References FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_first, and FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_rest.
Friends And Related Function Documentation
PowerFilter
template<typename SubFilter_ , int count_> template<typename , int > friend class PowerFilter friend
Definition at line 41 of file power_filter.hpp.
Member Data Documentation
_first
template<typename SubFilter_ , int count_> SubFilterType FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_first protected
the first sub-filter
Definition at line 70 of file power_filter.hpp.
Referenced by FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::bytes(), FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::clone(), FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::convert(), FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::get(), and FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::operator=().
_rest
template<typename SubFilter_ , int count_> RestClass FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::_rest protected
the remaining part
Definition at line 72 of file power_filter.hpp.
Referenced by FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::bytes(), FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::clone(), FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::convert(), FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::get(), and FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::operator=().
num_blocks
template<typename SubFilter_ , int count_> constexpr int FEAT::LAFEM::PowerFilter< SubFilter_, count_ >::num_blocks = count_ static constexpr
number of filter blocks
Definition at line 55 of file power_filter.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/power_filter.hpp