FEAT: FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > > Class Template Reference
FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > > Class Template Reference abstract
Direct Stokes solver class for SaddlePointMatrix systems.
#include <direct_stokes_solver.hpp>
Public Types
typedef Solver::SolverBase< SystemVectorType > BaseClass
our base class
typedef Global::Filter< LocalFilter_, Mirror_ > SystemFilterType
our system filter type
typedef Global::Matrix< LocalMatrix_, Mirror_, Mirror_ > SystemMatrixType
our system matrix type
typedef Global::Vector< typename LocalMatrix_::VectorTypeR, Mirror_ > SystemVectorType
our system vector type
typedef Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > VectorType
The type of vector this solver can be applied to.
Public Member Functions
DirectStokesSolver (const SystemMatrixType &matrix_sys, const SystemFilterType &filter_sys)
virtual Status apply (Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > &vec_cor, const Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > &vec_def)=0
Solver application method.
virtual Solver::Status apply (SystemVectorType &vec_sol, const SystemVectorType &vec_rhs) override
Applies the direct Stokes solver.
virtual void done ()
Finalization method.
virtual void done_numeric () override
Releases all data allocated during numeric initialization.
virtual void done_symbolic () override
Releases all data allocated during symbolic initialization.
virtual void init ()
Initialization method.
virtual void init_numeric () override
Performs the numeric initialization.
virtual void init_symbolic () override
Performs the symbolic initialization.
virtual String name () const override
Returns the name of the solver.
Protected Attributes
const SystemFilterType & _filter_sys
the system filter
DirectStokesSolver< LocalMatrix_, LocalFilter_ > _local_solver
our local solver
const SystemMatrixType & _matrix_sys
the system matrix
Detailed Description
template<typename LocalMatrix_, typename LocalFilter_, typename Mirror_>
class FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >
Direct Stokes solver class for SaddlePointMatrix systems.
Attention
Currently, this solver class is merely a wrapper around a local direct solver, i.e. this class can only be used to solve systems on a single process, e.g. in the case of a single-process coarse grid solver. An "actual" parallel direct solver may or may not be implemented in future.
Currently, this solver class can only be used if FEAT is compiled and linked with support for the UMFPACK library.
Author
Peter Zajac
Definition at line 1148 of file direct_stokes_solver.hpp.
Member Typedef Documentation
BaseClass
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Solver::SolverBase<SystemVectorType> FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::BaseClass
our base class
Definition at line 1160 of file direct_stokes_solver.hpp.
SystemFilterType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Global::Filter<LocalFilter_, Mirror_> FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::SystemFilterType
our system filter type
Definition at line 1157 of file direct_stokes_solver.hpp.
SystemMatrixType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Global::Matrix<LocalMatrix_, Mirror_, Mirror_> FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::SystemMatrixType
our system matrix type
Definition at line 1153 of file direct_stokes_solver.hpp.
SystemVectorType
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > typedef Global::Vector<typename LocalMatrix_::VectorTypeR, Mirror_> FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::SystemVectorType
our system vector type
Definition at line 1155 of file direct_stokes_solver.hpp.
VectorType
typedef Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >::VectorType inherited
The type of vector this solver can be applied to.
Definition at line 188 of file base.hpp.
Constructor & Destructor Documentation
DirectStokesSolver()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::DirectStokesSolver (const SystemMatrixType & matrix_sys, const SystemFilterType & filter_sys) inline explicit
Definition at line 1172 of file direct_stokes_solver.hpp.
Member Function Documentation
apply() [1/2]
virtual Status FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >::apply (Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > & vec_cor, const Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
apply() [2/2]
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > virtual Solver::Status FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::apply (SystemVectorType & vec_sol, const SystemVectorType & vec_rhs) inline override virtual
Applies the direct Stokes solver.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Definition at line 1235 of file direct_stokes_solver.hpp.
References FEAT::Global::Vector< LocalVector_, Mirror_ >::local().
done()
virtual void FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 285 of file base.hpp.
done_numeric()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > virtual void FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::done_numeric () inline override virtual
Releases all data allocated during numeric initialization.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >.
Definition at line 1207 of file direct_stokes_solver.hpp.
done_symbolic()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > virtual void FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::done_symbolic () inline override virtual
Releases all data allocated during symbolic initialization.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >.
Definition at line 1214 of file direct_stokes_solver.hpp.
init()
virtual void FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 270 of file base.hpp.
init_numeric()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > virtual void FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::init_numeric () inline override virtual
Performs the numeric initialization.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >.
Definition at line 1200 of file direct_stokes_solver.hpp.
init_symbolic()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > virtual void FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::init_symbolic () inline override virtual
Performs the symbolic initialization.
Reimplemented from FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >.
Definition at line 1186 of file direct_stokes_solver.hpp.
References FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_comm(), FEAT::Dist::Comm::size(), and XASSERTM.
name()
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > virtual String FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::name () const inline override virtual
Returns the name of the solver.
Implements FEAT::Solver::SolverBase< Global::Vector< LocalMatrix_::VectorTypeR, Mirror_ > >.
Definition at line 1180 of file direct_stokes_solver.hpp.
Member Data Documentation
_filter_sys
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > const SystemFilterType& FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::_filter_sys protected
the system filter
Definition at line 1166 of file direct_stokes_solver.hpp.
_local_solver
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > DirectStokesSolver<LocalMatrix_, LocalFilter_> FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::_local_solver protected
our local solver
Definition at line 1169 of file direct_stokes_solver.hpp.
_matrix_sys
template<typename LocalMatrix_ , typename LocalFilter_ , typename Mirror_ > const SystemMatrixType& FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::_matrix_sys protected
the system matrix
Definition at line 1164 of file direct_stokes_solver.hpp.
The documentation for this class was generated from the following file:
kernel/solver/direct_stokes_solver.hpp