FEAT: FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ > Class Template Reference
FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ > Class Template Reference
Finite-Element pointstar matrix factory.
#include <pointstar_factory.hpp>
Public Member Functions
PointstarFactoryFE (Index m)
Creates the pointstar factory.
virtual DenseVector< DataType_, IndexType_ > eigenvector_min () const
Computes the eigenvector of the smallest eigenvalue.
virtual DataType_ lambda_max () const override
Computes the largest eigenvalue of the FE-style matrix.
virtual DataType_ lambda_min () const override
Computes the smallest eigenvalue of the FE-style matrix.
virtual SparseMatrixCSR< DataType_, IndexType_ > matrix_csr () const override
Generates a FE-style pointstar CSR matrix.
virtual SparseMatrixCSR< DataType_, IndexType_ > matrix_csr_neumann () const
Generates a FE-style pointstar CSR matrix with Neumann boundaries.
virtual DataType_ spectral_cond () const
Computes the spectral condition number of the pointstar matrix.
DenseVector< DataType_, IndexType_ > vector_q2_bubble () const
Computes a Q2-bubble vector.
Protected Attributes
Index _d
number of dimensions
Index _m
number of inner nodes per dimension
Detailed Description
template<typename DataType_, typename IndexType_>
class FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >
Finite-Element pointstar matrix factory.
This class generates a CSR poinstar matrices in Finite-Element style. Moreover, this class can compute the largest and smallest eigenvalue of the corresponding matrix as well as the eigenvector with respect to the smallest eigenvalue.
For now, this class can only compute 2D FE pointstars.
Author
Peter Zajac
Definition at line 426 of file pointstar_factory.hpp.
Constructor & Destructor Documentation
PointstarFactoryFE()
template<typename DataType_ , typename IndexType_ > FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::PointstarFactoryFE (Index m) inline
Creates the pointstar factory.
Parameters
[in] m The number of inner nodes per dimension. Must be >= 3.
Definition at line 436 of file pointstar_factory.hpp.
~PointstarFactoryFE()
template<typename DataType_ , typename IndexType_ > virtual FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::~PointstarFactoryFE () inline virtual
Definition at line 441 of file pointstar_factory.hpp.
Member Function Documentation
eigenvector_min()
template<typename DataType_ , typename IndexType_ > virtual DenseVector< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min () const inline virtual inherited
Computes the eigenvector of the smallest eigenvalue.
This function generates the eigenvector with respect to the smallest eigenvalue of the corresponding pointstar matrix.
Returns
The m^d x m^d eigenvector
Definition at line 90 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and FEAT::Math::sin().
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
lambda_max()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_max () const inline override virtual
Computes the largest eigenvalue of the FE-style matrix.
Implements FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >.
Definition at line 873 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m, FEAT::Math::cos(), and FEAT::Math::sqr().
lambda_min()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_min () const inline override virtual
Computes the smallest eigenvalue of the FE-style matrix.
Implements FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >.
Definition at line 847 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m, and FEAT::Math::cos().
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
matrix_csr()
template<typename DataType_ , typename IndexType_ > virtual SparseMatrixCSR< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr () const inline override virtual
Generates a FE-style pointstar CSR matrix.
This function generates pointstar matrices in Finite-Element style.
Returns
The m^d x m^d FE-stye pointstar matrix.
Implements FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >.
Definition at line 451 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m, and FEAT::LAFEM::DenseVector< DT_, IT_ >::elements().
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system(), and FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr_neumann().
matrix_csr_neumann()
template<typename DataType_ , typename IndexType_ > virtual SparseMatrixCSR< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr_neumann () const inline virtual
Generates a FE-style pointstar CSR matrix with Neumann boundaries.
This function generates pointstar matrices in Finite-Element style using Neumann boundaries.
Returns
The m^d x m^d FE-stye pointstar matrix with Neumann boundaries.
Definition at line 660 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
spectral_cond()
template<typename DataType_ , typename IndexType_ > virtual DataType_ FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::spectral_cond () const inline virtual inherited
Computes the spectral condition number of the pointstar matrix.
Returns
The spectral condition number of the matrix.
Definition at line 76 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::lambda_max(), and FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::lambda_min().
vector_q2_bubble()
template<typename DataType_ , typename IndexType_ > DenseVector< DataType_, IndexType_ > FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble () const inline inherited
Computes a Q2-bubble vector.
This function can be used to generate a useful solution vector for the pointstar matrix. The corresponding right hand side can be computed by multiplying this vector by the matrix.
Returns
The m^d x m^d Q2-bubble vector
Definition at line 125 of file pointstar_factory.hpp.
References FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_d, FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m, and FEAT::LAFEM::DenseVector< DT_, IT_ >::elements().
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
Member Data Documentation
_d
template<typename DataType_ , typename IndexType_ > Index FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_d protected inherited
number of dimensions
Definition at line 34 of file pointstar_factory.hpp.
Referenced by FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr(), and FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble().
_m
template<typename DataType_ , typename IndexType_ > Index FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::_m protected inherited
number of inner nodes per dimension
Definition at line 32 of file pointstar_factory.hpp.
Referenced by FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::eigenvector_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_max(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::lambda_min(), FEAT::LAFEM::PointstarFactoryFD< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr_neumann(), and FEAT::LAFEM::PointstarFactoryBase< DataType_, IndexType_ >::vector_q2_bubble().
The documentation for this class was generated from the following file:
kernel/lafem/pointstar_factory.hpp