FEAT: FEAT::Geometry::PartitionSet Class Reference
FEAT::Geometry::PartitionSet Class Reference
Partition set class.
#include <partition_set.hpp>
Public Member Functions
PartitionSet (PartitionSet &&other)
void add_partition (Partition &&part)
void clear ()
const Partition * find_partition (int size, const std::deque< String > &names, int prio=0) const
const Partition * find_partition (int size, const String &name="", int prio=0) const
Tries to find a suitable partition in the set.
std::deque< Partition > & get_partitions ()
const std::deque< Partition > & get_partitions () const
Protected Attributes
std::deque< Partition > _parts
the actual partitions in the set
Detailed Description
Partition set class.
This class acts as a container, which manages a set of partitions. This class is effectively just a wrapper around a deque of Partition objects.
Author
Peter Zajac
Definition at line 187 of file partition_set.hpp.
Constructor & Destructor Documentation
PartitionSet() [1/2]
FEAT::Geometry::PartitionSet::PartitionSet () inline
Definition at line 194 of file partition_set.hpp.
PartitionSet() [2/2]
FEAT::Geometry::PartitionSet::PartitionSet (PartitionSet && other) inline
Definition at line 198 of file partition_set.hpp.
~PartitionSet()
virtual FEAT::Geometry::PartitionSet::~PartitionSet () inline virtual
Definition at line 203 of file partition_set.hpp.
Member Function Documentation
add_partition()
void FEAT::Geometry::PartitionSet::add_partition (Partition && part) inline
Definition at line 222 of file partition_set.hpp.
clear()
void FEAT::Geometry::PartitionSet::clear () inline
Definition at line 207 of file partition_set.hpp.
find_partition() [1/2]
const Partition * FEAT::Geometry::PartitionSet::find_partition (int size, const std::deque< String > & names, int prio = 0) const inline
Definition at line 253 of file partition_set.hpp.
find_partition() [2/2]
const Partition * FEAT::Geometry::PartitionSet::find_partition (int size, const String & name = "", int prio = 0) const inline
Tries to find a suitable partition in the set.
Parameters
[in] size The required size (number of ranks) of the partition. Must be > 0.
[in] name The required name of the partition. If name is an empty string, the name of a partition is considered irrelevant.
[in] prio The required minimal priority of the partition. Only partitions with a priority greater or equal to prio are considered valid candidates.
Returns
A pointer to a Partition object that meets the requirements or nullptr, if no suitable partition was found in the set.
Definition at line 245 of file partition_set.hpp.
References find_partition().
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_extern(), and find_partition().
get_partitions() [1/2]
std::deque< Partition > & FEAT::Geometry::PartitionSet::get_partitions () inline
Definition at line 212 of file partition_set.hpp.
get_partitions() [2/2]
const std::deque< Partition > & FEAT::Geometry::PartitionSet::get_partitions () const inline
Definition at line 217 of file partition_set.hpp.
Member Data Documentation
_parts
std::deque<Partition> FEAT::Geometry::PartitionSet::_parts protected
the actual partitions in the set
Definition at line 191 of file partition_set.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/partition_set.hpp