FEAT: FEAT::Geometry::RedundantIndexSetBuilder< Shape_ > Class Template Reference
FEAT::Geometry::RedundantIndexSetBuilder< Shape_ > Class Template Reference
Builder for redundant index sets.
#include <index_calculator.hpp>
Static Public Member Functions
static void compute (IndexSetHolder< Shape_ > &index_set_holder)
Routine that does the actual work.
Detailed Description
template<typename Shape_>
class FEAT::Geometry::RedundantIndexSetBuilder< Shape_ >
Builder for redundant index sets.
This class builds all redundant index sets from the mandatory index sets.
Author
Peter Zajac
Definition at line 524 of file index_calculator.hpp.
Member Function Documentation
compute()
template<typename Shape_ > static void FEAT::Geometry::RedundantIndexSetBuilder< Shape_ >::compute (IndexSetHolder< Shape_ > & index_set_holder) inline static
Routine that does the actual work.
Definition at line 528 of file index_calculator.hpp.
Referenced by FEAT::Geometry::MeshPart< MeshType_ >::deduct_topology(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::deduct_topology_from_top(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_topology(), and FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::fill_index_sets().
The documentation for this class was generated from the following file:
kernel/geometry/index_calculator.hpp