FEAT: FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ > Class Template Reference
FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ > Class Template Reference
Q2Lagrange thread parallel assembly class for the burgers velo material operator.
#include <burgers_velo_material_assembler.hpp>
Public Types
typedef VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ > BaseClass
typedef BaseClass::DataHandler DataHandler
typedef SpaceHelp::DataType DataType
typedef SpaceHelp::DomainPointType DomainPointType
typedef SpaceHelp::ImagePointType ImagePointType
typedef SpaceHelp::IndexType IndexType
typedef SpaceHelp::JacobianMatrixType JacobianMatrixType
typedef SpaceHelp::ShapeType ShapeType
typedef BaseClass::SpaceHelp SpaceHelp
typedef BaseClass::SpaceType SpaceType
typedefs
typedef SpaceHelp::ValueType ValueType
Public Member Functions
template<typename ColoringType_ >
VoxelBurgersVeloMaterialAssembler (const SpaceType &space, const ColoringType_ &coloring, int hint=-1)
Constructor for burgers velo material assembler.
VoxelBurgersVeloMaterialAssembler (const VoxelBurgersVeloMaterialAssembler &)=delete
VoxelBurgersVeloMaterialAssembler (VoxelBurgersVeloMaterialAssembler &&)=default
template<typename CubatureFactory_ >
void assemble_matrix1 (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > &matrix, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect, const SpaceType &space, const CubatureFactory_ &cubature_factory, DataType alpha=DataType(1)) const
Assembles the burgers velo material operator for finitie element space with same test and trial space.
void assemble_matrix1_cuda (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > &matrix, const SpaceType &space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType *cub_pt, const DataType *cub_wg, int num_cubs, DataType alpha) const
void assemble_matrix1_generic (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > &matrix, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect, const SpaceType &space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType *cub_pt, const DataType *cub_wg, int num_cubs, DataType alpha) const
template<typename CubatureFactory_ >
void assemble_vector (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &vector, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &primal, const SpaceType &space, const CubatureFactory_ &cubature_factory, DataType alpha=DataType(1)) const
Assembles the application of the burgers operator to a given primal vector.
void assemble_vector_cuda (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &, const SpaceType &, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType *, const DataType *, int, DataType) const
void assemble_vector_generic (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &vector, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &primal, const SpaceType &space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType *cub_pt, const DataType *cub_wg, int num_cubs, DataType alpha) const
VoxelBurgersVeloMaterialAssembler & operator= (const VoxelBurgersVeloMaterialAssembler &)=delete
VoxelBurgersVeloMaterialAssembler & operator= (VoxelBurgersVeloMaterialAssembler &&)=default
void set_sd_v_norm (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > &convect)
Sets the internal maximum streamline diffusion velocity norm.
void set_sd_v_norm (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect)
Sets the internal maximum streamline diffusion velocity norm.
void set_sd_v_norm_cuda (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > &)
void set_sd_v_norm_cuda (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &)
void set_sd_v_norm_generic (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > &convect)
void set_sd_v_norm_generic (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &convect)
VoxelAssembly::AssemblyBurgersData< DataType > wrap_burgers_params () const
Wraps the set burgers parameter into convenient struct.
VoxelAssembly::AssemblyMaterialData< DataType > wrap_material_params () const
Wraps the set burgers parameter into convenient struct.
Public Attributes
DataType a_T
DataType beta
Convection scaling.
int blocksize
the block size to be used
bool deformation
Should we use full deformation formulation?
DataType exp
DataType frechet_beta
Scaling parameter for full jacobian convection part.
DataType frechet_material
Scaling factor full material jacobian.
int gridsize
the grid size to be used
DataType lambda
MaterialType material_type
material type
DataHandler mesh_data
The meshdata handler.
DataType mu_0
Material Parameter.
DataType mu_inf
DataType nu
The viscosity.
bool print_occupancy
print out occupancy
DataType reg_eps
regularity parameter
DataType sd_delta
Streamline diffusion parameter.
DataType sd_nu
Streamline diffosuion viscosity. Generally equal to nu.
DataType sd_v_norm
The current maximum velocity norm.
int shared_mem
how much shared memory should the kernel use
DataType theta
Reaction scaling.
DataType yasuda_a
Static Public Attributes
static constexpr int dim = SpaceHelp::dim
constexpr
Detailed Description
template<int dim_, typename DT_, typename IT_>
class FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >
Q2Lagrange thread parallel assembly class for the burgers velo material operator.
This class provides host and device variants for a thread parallel assembly of the extended burgers operator. For details on the burgers velocity material operator, see the burgers velocity material assembler in </kernel/assembly/>. The threading strategy is based on a cell based coloring of the mesh, so in principle this version for Q2 space works as long as a valid coloring is provided.
Template Parameters
dim_ Dimension of the hypercubes.
DT_ Datatype to be used.
IT_ Indextype to be used.
Definition at line 1193 of file burgers_velo_material_assembler.hpp.
Member Typedef Documentation
BaseClass
template<int dim_, typename DT_ , typename IT_ > typedef VoxelBurgersAssembler<Q2StandardHyperCube<dim_>, DT_, IT_> FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::BaseClass
Definition at line 1197 of file burgers_velo_material_assembler.hpp.
DataHandler
template<int dim_, typename DT_ , typename IT_ > typedef BaseClass::DataHandler FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::DataHandler
Definition at line 1200 of file burgers_velo_material_assembler.hpp.
DataType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::DataType
Definition at line 1203 of file burgers_velo_material_assembler.hpp.
DomainPointType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::DomainPointType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::DomainPointType
Definition at line 1209 of file burgers_velo_material_assembler.hpp.
ImagePointType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::ImagePointType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::ImagePointType
Definition at line 1210 of file burgers_velo_material_assembler.hpp.
IndexType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::IndexType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::IndexType
Definition at line 1204 of file burgers_velo_material_assembler.hpp.
JacobianMatrixType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::JacobianMatrixType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::JacobianMatrixType
Definition at line 1212 of file burgers_velo_material_assembler.hpp.
ShapeType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::ShapeType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::ShapeType
Definition at line 1202 of file burgers_velo_material_assembler.hpp.
SpaceHelp
template<int dim_, typename DT_ , typename IT_ > typedef BaseClass::SpaceHelp FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::SpaceHelp
Definition at line 1201 of file burgers_velo_material_assembler.hpp.
SpaceType
template<int dim_, typename DT_ , typename IT_ > typedef BaseClass::SpaceType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::SpaceType
typedefs
Definition at line 1199 of file burgers_velo_material_assembler.hpp.
ValueType
template<int dim_, typename DT_ , typename IT_ > typedef SpaceHelp::ValueType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::ValueType
Definition at line 1211 of file burgers_velo_material_assembler.hpp.
Constructor & Destructor Documentation
VoxelBurgersVeloMaterialAssembler()
template<int dim_, typename DT_ , typename IT_ > template<typename ColoringType_ > FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::VoxelBurgersVeloMaterialAssembler (const SpaceType & space, const ColoringType_ & coloring, int hint = -1) inline explicit
Constructor for burgers velo material assembler.
Template Parameters
ColoringType_ The type of the coloring indexset.
Parameters
[in] space The underlying finite element space.
[in] coloring The coloring index set. Has to map each cell to its color. Obviously requires no two adjecent cells to have the same color.
[in] hint Hint for the number of colors. If < 0 the mesh_data will determine this number itself. Undefined behavior if number is not correct.
//TODO: setting of base configuration does not fit completely, due to DataWrapperSize
Definition at line 1249 of file burgers_velo_material_assembler.hpp.
~VoxelBurgersVeloMaterialAssembler()
template<int dim_, typename DT_ , typename IT_ > FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::~VoxelBurgersVeloMaterialAssembler () inline
Definition at line 1264 of file burgers_velo_material_assembler.hpp.
Member Function Documentation
assemble_matrix1()
template<int dim_, typename DT_ , typename IT_ > template<typename CubatureFactory_ > void FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1 (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > & matrix, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect, const SpaceType & space, const CubatureFactory_ & cubature_factory, DataType alpha = DataType(1)) const inline
Assembles the burgers velo material operator for finitie element space with same test and trial space.
Template Parameters
CubatureFactory_ Factory type for cubature data.
Parameters
[in/out] matrix The matrix to be assembled. Adds onto residing data.
[in] convect The convection vector. Values are ignored if either beta or sd_delta is zero.
[in] space The underlying space.
[in] cubature_factory The cubature rule to be used.
[in] alpha Scaling parameter for assembly.
Definition at line 1288 of file burgers_velo_material_assembler.hpp.
References FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::Space::Lagrange2::Element< Trafo_ >::get_num_dofs(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
assemble_matrix1_cuda()
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1_cuda (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > & matrix, const SpaceType & space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType * cub_pt, const DataType * cub_wg, int num_cubs, DataType alpha) const inline
Definition at line 1430 of file burgers_velo_material_assembler.hpp.
assemble_matrix1_generic()
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_matrix1_generic (LAFEM::SparseMatrixBCSR< DataType, IndexType, dim, dim > & matrix, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect, const SpaceType & space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType * cub_pt, const DataType * cub_wg, int num_cubs, DataType alpha) const inline
Definition at line 1338 of file burgers_velo_material_assembler.hpp.
assemble_vector()
template<int dim_, typename DT_ , typename IT_ > template<typename CubatureFactory_ > void FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_vector (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & vector, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & primal, const SpaceType & space, const CubatureFactory_ & cubature_factory, DataType alpha = DataType(1)) const inline
Assembles the application of the burgers operator to a given primal vector.
Template Parameters
CubatureFactory_ Factory type for cubature data.
Parameters
[in/out] vector The vector to be assembled. Adds onto residing data.
[in] convect The convection vector. Values are ignored if either beta or sd_delta is zero.
[in] primal The primal vector the operator is applied on.
[in] space The underlying space.
[in] cubature_factory The cubature rule to be used.
[in] alpha Scaling parameter for assembly.
Definition at line 1320 of file burgers_velo_material_assembler.hpp.
References FEAT::Space::Lagrange2::Element< Trafo_ >::get_num_dofs(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
assemble_vector_cuda()
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_vector_cuda (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & , const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & , const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & , const SpaceType & , typename Cubature::Rule< ShapeType, DataType, DataType >::PointType * , const DataType * , int , DataType) const inline
Definition at line 1435 of file burgers_velo_material_assembler.hpp.
assemble_vector_generic()
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::assemble_vector_generic (LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & vector, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect, const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & primal, const SpaceType & space, typename Cubature::Rule< ShapeType, DataType, DataType >::PointType * cub_pt, const DataType * cub_wg, int num_cubs, DataType alpha) const inline
Definition at line 1355 of file burgers_velo_material_assembler.hpp.
set_sd_v_norm() [1/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > & convect) inline inherited
Sets the internal maximum streamline diffusion velocity norm.
Parameters
[in] convect The global convection vector which is evaluated regarding its maximum euclidean norm.
Definition at line 1611 of file burgers_assembler.hpp.
set_sd_v_norm() [2/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect) inline inherited
Sets the internal maximum streamline diffusion velocity norm.
Parameters
[in] convect The local convection vector which is evaluated regarding its maximum euclidean norm.
Definition at line 1601 of file burgers_assembler.hpp.
set_sd_v_norm_cuda() [1/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm_cuda (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > &) inline inherited
Definition at line 1771 of file burgers_assembler.hpp.
set_sd_v_norm_cuda() [2/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm_cuda (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > &) inline inherited
Definition at line 1765 of file burgers_assembler.hpp.
set_sd_v_norm_generic() [1/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm_generic (const Global::Vector< LAFEM::DenseVectorBlocked< DataType, IndexType, dim >, LAFEM::VectorMirror< DataType, IndexType > > & convect) inline inherited
Definition at line 1654 of file burgers_assembler.hpp.
set_sd_v_norm_generic() [2/2]
template<int dim_, typename DT_ , typename IT_ > void FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::set_sd_v_norm_generic (const LAFEM::DenseVectorBlocked< DataType, IndexType, dim > & convect) inline inherited
Definition at line 1648 of file burgers_assembler.hpp.
wrap_burgers_params()
template<int dim_, typename DT_ , typename IT_ > VoxelAssembly::AssemblyBurgersData< DataType > FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::wrap_burgers_params () const inline inherited
Wraps the set burgers parameter into convenient struct.
Returns
A wrapper for the burgers data.
Definition at line 1529 of file burgers_assembler.hpp.
wrap_material_params()
template<int dim_, typename DT_ , typename IT_ > VoxelAssembly::AssemblyMaterialData< DataType > FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::wrap_material_params () const inline
Wraps the set burgers parameter into convenient struct.
Returns
A wrapper for the burgers data.
Definition at line 1271 of file burgers_velo_material_assembler.hpp.
References FEAT::Math::pow().
Member Data Documentation
a_T
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::a_T
Definition at line 1224 of file burgers_velo_material_assembler.hpp.
beta
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::beta inherited
Convection scaling.
Definition at line 1448 of file burgers_assembler.hpp.
blocksize
template<int dim_, typename DT_ , typename IT_ > int FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::blocksize inherited
the block size to be used
Definition at line 1470 of file burgers_assembler.hpp.
deformation
template<int dim_, typename DT_ , typename IT_ > bool FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::deformation inherited
Should we use full deformation formulation?
Definition at line 1476 of file burgers_assembler.hpp.
dim
template<int dim_, typename DT_ , typename IT_ > constexpr int FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::dim = SpaceHelp::dim static constexpr
constexpr
Definition at line 1207 of file burgers_velo_material_assembler.hpp.
exp
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::exp
Definition at line 1222 of file burgers_velo_material_assembler.hpp.
frechet_beta
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::frechet_beta inherited
Scaling parameter for full jacobian convection part.
Definition at line 1451 of file burgers_assembler.hpp.
frechet_material
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::frechet_material
Scaling factor full material jacobian.
Definition at line 1215 of file burgers_velo_material_assembler.hpp.
gridsize
template<int dim_, typename DT_ , typename IT_ > int FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::gridsize inherited
the grid size to be used
Definition at line 1467 of file burgers_assembler.hpp.
lambda
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::lambda
Definition at line 1223 of file burgers_velo_material_assembler.hpp.
material_type
template<int dim_, typename DT_ , typename IT_ > MaterialType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::material_type
material type
Definition at line 1229 of file burgers_velo_material_assembler.hpp.
mesh_data
template<int dim_, typename DT_ , typename IT_ > DataHandler FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::mesh_data inherited
The meshdata handler.
Definition at line 1439 of file burgers_assembler.hpp.
mu_0
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::mu_0
Material Parameter.
Definition at line 1221 of file burgers_velo_material_assembler.hpp.
mu_inf
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::mu_inf
Definition at line 1226 of file burgers_velo_material_assembler.hpp.
nu
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::nu inherited
The viscosity.
Definition at line 1442 of file burgers_assembler.hpp.
print_occupancy
template<int dim_, typename DT_ , typename IT_ > bool FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::print_occupancy inherited
print out occupancy
Definition at line 1473 of file burgers_assembler.hpp.
reg_eps
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::reg_eps
regularity parameter
Definition at line 1218 of file burgers_velo_material_assembler.hpp.
sd_delta
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::sd_delta inherited
Streamline diffusion parameter.
Definition at line 1454 of file burgers_assembler.hpp.
sd_nu
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::sd_nu inherited
Streamline diffosuion viscosity. Generally equal to nu.
Definition at line 1457 of file burgers_assembler.hpp.
sd_v_norm
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::sd_v_norm inherited
The current maximum velocity norm.
Definition at line 1460 of file burgers_assembler.hpp.
shared_mem
template<int dim_, typename DT_ , typename IT_ > int FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::shared_mem inherited
how much shared memory should the kernel use
Definition at line 1464 of file burgers_assembler.hpp.
theta
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::theta inherited
Reaction scaling.
Definition at line 1445 of file burgers_assembler.hpp.
yasuda_a
template<int dim_, typename DT_ , typename IT_ > DataType FEAT::VoxelAssembly::VoxelBurgersVeloMaterialAssembler< Q2StandardHyperCube< dim_ >, DT_, IT_ >::yasuda_a
Definition at line 1225 of file burgers_velo_material_assembler.hpp.
The documentation for this class was generated from the following file:
kernel/voxel_assembly/burgers_velo_material_assembler.hpp