FEAT: FEAT::Trafo::Standard::Mapping< Mesh_ > Class Template Reference
FEAT::Trafo::Standard::Mapping< Mesh_ > Class Template Reference
Standard transformation mapping class template.
#include <mapping.hpp>
Classes
class Evaluator
Trafo evaluator class template.
Public Types
typedef MappingBase< Mesh_ > BaseClass
base-class typedef
typedef MeshType::VertexSetType::CoordType CoordType
data type
typedef Shape::FaceTraits< ShapeType, ShapeType::dimension-1 >::ShapeType FacetType
typedef Mesh_ MeshType
mesh type
typedef MeshType::ShapeType ShapeType
shape type
Public Member Functions
Mapping (MeshType &mesh)
Constructor.
void add_meshpart_chart (const Geometry::MeshPart< MeshType > &mesh_part, const Geometry::Atlas::ChartBase< MeshType > &chart)
Adds a mesh-part and its associated chart to the trafo.
CoordType compute_vol ()
Computes the volume of the whole mesh given by this trafo.
template<typename ShapeType_ = ShapeType, typename CoordType_ = CoordType>
CoordType_ compute_vol (const Index cell) const
Computes the volume of one cell.
MeshType & get_mesh ()
Returns a reference to the underlying mesh.
const MeshType & get_mesh () const
Returns a reference to the underlying mesh.
bool operator== (const MappingBase &other) const
Comparison operator.
Static Public Attributes
static constexpr int num_coeff = ...
static constexpr int num_coeff_facet = ...
Number of coefficients of the reference transformation for faces.
static constexpr int world_dim = Mesh_::world_dim
our image/world dimension
Protected Attributes
MeshType & _mesh
mesh reference
Detailed Description
template<typename Mesh_>
class FEAT::Trafo::Standard::Mapping< Mesh_ >
Standard transformation mapping class template.
This class implements the standard first-order transformation mapping for any sort of mesh.
Template Parameters
Mesh_ The mesh class that this transformation is to be defined on.
Author
Peter Zajac
Definition at line 37 of file mapping.hpp.
Member Typedef Documentation
BaseClass
template<typename Mesh_ > typedef MappingBase<Mesh_> FEAT::Trafo::Standard::Mapping< Mesh_ >::BaseClass
base-class typedef
Definition at line 42 of file mapping.hpp.
CoordType
template<typename Mesh_ > typedef MeshType::VertexSetType::CoordType FEAT::Trafo::Standard::Mapping< Mesh_ >::CoordType
data type
Definition at line 46 of file mapping.hpp.
FacetType
template<typename Mesh_ > typedef Shape::FaceTraits<ShapeType,ShapeType::dimension-1>::ShapeType FEAT::Trafo::Standard::Mapping< Mesh_ >::FacetType
Shape of the facets that make up the boundary we can i.e. compute the normals for, i.e. Simplex<2> faces for a Simplex<3> mesh
Definition at line 51 of file mapping.hpp.
MeshType
template<typename Mesh_ > typedef Mesh_ FEAT::Trafo::Standard::Mapping< Mesh_ >::MeshType
mesh type
Definition at line 44 of file mapping.hpp.
ShapeType
template<typename Mesh_ > typedef MeshType::ShapeType FEAT::Trafo::Standard::Mapping< Mesh_ >::ShapeType
shape type
Definition at line 48 of file mapping.hpp.
Constructor & Destructor Documentation
Mapping()
template<typename Mesh_ > FEAT::Trafo::Standard::Mapping< Mesh_ >::Mapping (MeshType & mesh) inline explicit
Constructor.
Parameters
[in] mesh A resident reference to the mesh that this trafo mapping is to be defined on.
Definition at line 76 of file mapping.hpp.
Member Function Documentation
add_meshpart_chart()
template<typename Mesh_ > void FEAT::Trafo::Standard::Mapping< Mesh_ >::add_meshpart_chart (const Geometry::MeshPart< MeshType > & mesh_part, const Geometry::Atlas::ChartBase< MeshType > & chart) inline
Adds a mesh-part and its associated chart to the trafo.
Parameters
[in] mesh_part The transient mesh-part that is to be added.
[in] chart The transient chart that the mesh part is associated with.
Definition at line 137 of file mapping.hpp.
compute_vol() [1/2]
template<typename Mesh_ > CoordType FEAT::Trafo::Standard::Mapping< Mesh_ >::compute_vol () inline
Computes the volume of the whole mesh given by this trafo.
Returns
The shape_dim dimensional volume
Definition at line 111 of file mapping.hpp.
References FEAT::Trafo::EvaluatorBase< Trafo_, Evaluator_, EvalPolicy_ >::finish(), FEAT::Trafo::MappingBase< Mesh_ >::get_mesh(), FEAT::Trafo::Standard::Evaluator< Trafo_, EvalPolicy_, Shape_ >::prepare(), and FEAT::Trafo::Standard::Evaluator< Trafo_, EvalPolicy_, Shape_ >::volume().
compute_vol() [2/2]
template<typename Mesh_ > template<typename ShapeType_ = ShapeType, typename CoordType_ = CoordType> CoordType_ FEAT::Trafo::Standard::Mapping< Mesh_ >::compute_vol (const Index cell) const inline
Computes the volume of one cell.
Template Parameters
ShapeType_ Shape type of the underlying mesh.
CoordType_ Precision, by default the same precision as for the coordinates.
Parameters
[in] cell Index for which the volume is computed.
Returns
The volume of cell.
Definition at line 96 of file mapping.hpp.
References FEAT::Trafo::EvaluatorBase< Trafo_, Evaluator_, EvalPolicy_ >::finish(), FEAT::Trafo::Standard::Evaluator< Trafo_, EvalPolicy_, Shape_ >::prepare(), and FEAT::Trafo::Standard::Evaluator< Trafo_, EvalPolicy_, Shape_ >::volume().
get_mesh() [1/2]
template<typename Mesh_ > MeshType & FEAT::Trafo::MappingBase< Mesh_ >::get_mesh () inline inherited
Returns a reference to the underlying mesh.
Returns
A (const) reference to the underlying mesh.
Definition at line 93 of file mapping_base.hpp.
References FEAT::Trafo::MappingBase< Mesh_ >::_mesh.
Referenced by FEAT::Trafo::Standard::Mapping< Mesh_ >::compute_vol().
get_mesh() [2/2]
template<typename Mesh_ > const MeshType & FEAT::Trafo::MappingBase< Mesh_ >::get_mesh () const inline inherited
Returns a reference to the underlying mesh.
Returns
A (const) reference to the underlying mesh.
Definition at line 99 of file mapping_base.hpp.
References FEAT::Trafo::MappingBase< Mesh_ >::_mesh.
operator==()
template<typename Mesh_ > bool FEAT::Trafo::MappingBase< Mesh_ >::operator== (const MappingBase< Mesh_ > & other) const inline inherited
Comparison operator.
This operator checks whether two trafo mapping objects are equal.
Parameters
[in] other The other mapping object
Returns
true, if this this and other name the same object, otherwise false.
Definition at line 115 of file mapping_base.hpp.
Member Data Documentation
_mesh
template<typename Mesh_ > MeshType& FEAT::Trafo::MappingBase< Mesh_ >::_mesh protected inherited
mesh reference
Definition at line 72 of file mapping_base.hpp.
Referenced by FEAT::Trafo::MappingBase< Mesh_ >::get_mesh().
num_coeff
template<typename Mesh_ > constexpr int FEAT::Trafo::MappingBase< Mesh_ >::num_coeff = ... static constexpr inherited
Number of coefficients of the reference transformation for cells Since all transformations are finite element functions, this is just the local number of DoFs of the corresponding FE space (P1/Q1, P2/Q2, ...)
Definition at line 59 of file mapping_base.hpp.
num_coeff_facet
template<typename Mesh_ > constexpr int FEAT::Trafo::MappingBase< Mesh_ >::num_coeff_facet = ... static constexpr inherited
Number of coefficients of the reference transformation for faces.
Definition at line 61 of file mapping_base.hpp.
world_dim
template<typename Mesh_ > constexpr int FEAT::Trafo::MappingBase< Mesh_ >::world_dim = Mesh_::world_dim static constexpr inherited
our image/world dimension
Definition at line 31 of file mapping_base.hpp.
The documentation for this class was generated from the following file:
kernel/trafo/standard/mapping.hpp