FEAT: FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ > Class Template Reference
FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ > Class Template Reference
VTK exporter class template.
#include <export_vtk.hpp>
Classes
struct CompressedHeader
Header for compressed binary data.
struct UncompressedHeader
Header for uncompressed binary data.
Public Types
using CellShapeType = typename Shape::FaceTraits< ShapeType, cell_dim_ >::ShapeType
shape type of exported cells
using MeshType = Mesh_
mesh type
using ShapeType = typename MeshType::ShapeType
our shape type
using VTKShapeType = Intern::VTKShape< CellShapeType >
our VTK shape type
Public Member Functions
ExportVTK (const ExportVTK &other)=default
Copy constructor.
template<typename DT_ >
ExportVTK (const Geometry::CGALWrapper< DT_ > &cw, int var_prec=0)
Constructor.
ExportVTK (const MeshType &mesh, const MeshPart< MeshType > &part, int var_prec=0)
Constructor.
ExportVTK (const MeshType &mesh, int var_prec=0)
Constructor.
ExportVTK (ExportVTK &&other) noexcept=default
Move constructor.
virtual ~ExportVTK ()=default
destructor
template<typename T_ >
void add_cell_scalar (const String &name, const T_ *data, double scaling_factor=1.0)
Adds a scalar cell variable to the exporter.
template<typename DT_ , int dim_>
void add_cell_vector (const String &name, const std::vector< Tiny::Vector< DT_, dim_ > > &v, double scaling_factor=1.0)
Adds a vector-field cell variable given by a std::vector of Tiny::Vector to the exporter.
template<typename T_ >
void add_cell_vector (const String &name, const T_ *x, const T_ *y=nullptr, const T_ *z=nullptr, double scaling_factor=1.0)
Adds a vector-field cell variable to the exporter.
template<typename VectorType_ >
void add_cell_vector (const String &name, const VectorType_ &v, double scaling_factor=1.0)
Adds a vector-field cell variable given by a LAFEM::***VectorBlocked to the exporter.
template<typename T_ >
void add_vertex_scalar (const String &name, const T_ *data, double scaling_factor=1.0)
Adds a scalar vertex variable to the exporter.
template<typename DT_ , int dim_>
void add_vertex_vector (const String &name, const std::vector< Tiny::Vector< DT_, dim_ > > &v, double scaling_factor=1.0)
Adds a vector-field vertex variable given by a std::vector of Tiny::Vector to the exporter.
template<typename T_ >
void add_vertex_vector (const String &name, const T_ *x, const T_ *y=nullptr, const T_ *z=nullptr, double scaling_factor=1.0)
Adds a vector-field vertex variable to the exporter.
template<typename VectorType_ >
void add_vertex_vector (const String &name, const VectorType_ &v, double scaling_factor=1.0)
Adds a vector-field vertex variable given by a LAFEM::***VectorBlocked to the exporter.
void clear ()
Clears all vertex and cell variables in the exporter.
void enable_ascii_output (bool flag)
Enable or disable binary output.
void enable_compression (bool flag)
Enable or disable compression.
ExportVTK & operator= (const ExportVTK &other)=default
Copy-assignment constructor.
ExportVTK & operator= (ExportVTK &&other)=default
Move-assignment constructor.
void write (const String &filename) const
Writes out the data to a serial XML-VTU file.
void write (const String &filename, const Dist::Comm &comm)
Writes out the data to a parallel XML-PVTU file.
void write (const String &filename, const int rank, const int nparts)
Writes out the data to a parallel XML-PVTU file.
void write_pvtu (std::ostream &os, const String &file_title, const int nparts) const
Writes out the partition data in parallel XML-PVTU format.
void write_vtu (std::ostream &os) const
Writes out the mesh and variable data in serial XML-VTU format.
Static Public Attributes
static constexpr bool can_compress = false
static constexpr int num_coords = 3
Coordinates per vertex. The VTK documentation states that this is always three.
static constexpr int verts_per_cell = Shape::FaceTraits<CellShapeType, 0>::count
Vertices per cell.
Protected Types
using VarDeque = std::deque< std::pair< String, std::vector< double > > >
our variable container
Protected Attributes
bool _ascii_output = false
ascii output flag
VarDeque _cell_scalars
cell variable list
VarDeque _cell_vectors
cell field list
std::function< void(Index, IndexTuple< verts_per_cell > &)> _cells
Accessor function for cells.
Index _num_cells
number of cells in mesh
Index _num_verts
number of vertices in mesh
bool _use_compression = can_compress
compressed output flag. Only applicable if _binary_output is true
int _var_prec
precision of variables
VarDeque _vertex_scalars
vertex variable list
VarDeque _vertex_vectors
vertex field list
std::function< void(Index, Tiny::Vector< float, num_coords > &)> _vertices
Accessor function for vertices.
Private Member Functions
bool _little_endian () const
template<typename T_ >
void _write_data_array (std::ostream &os, const std::pair< String, std::vector< T_ > > &data, Index number_of_components=0) const
Writes an DataArray XML-node to the give output stream.
Detailed Description
template<typename Mesh_, int cell_dim_ = Mesh_::ShapeType::dimension>
class FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >
VTK exporter class template.
This class templates implements an exporter for the XML-based VTK file formats. This exporter is capable of writing (stand-alone) serial VTU files representing unstructured grids as well as parallel PVTU files representing partitionings.
This class templates supports exporting in ascii, binary, and compressed binary formats. The default format is binary, if zlib is not available, and compressed binary, if zlib is available.
Note
This class template supports both the Geometry::ConformalMesh and Geometry::StructuredMesh classes as input, however, both types of meshes are exported as unstructured meshes in the sense of VTK.
Template Parameters
Mesh_ The type of the mesh to be exported.
cell_dim_ The dimension of the mesh entities to be exported.
Author
Peter Zajac
Definition at line 194 of file export_vtk.hpp.
Member Typedef Documentation
CellShapeType
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> using FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::CellShapeType = typename Shape::FaceTraits<ShapeType, cell_dim_>::ShapeType
shape type of exported cells
Definition at line 202 of file export_vtk.hpp.
MeshType
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> using FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::MeshType = Mesh_
mesh type
Definition at line 198 of file export_vtk.hpp.
ShapeType
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> using FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::ShapeType = typename MeshType::ShapeType
our shape type
Definition at line 200 of file export_vtk.hpp.
VarDeque
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> using FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::VarDeque = std::deque<std::pair<String, std::vector<double> >> protected
our variable container
Definition at line 220 of file export_vtk.hpp.
VTKShapeType
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> using FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::VTKShapeType = Intern::VTKShape<CellShapeType>
our VTK shape type
Definition at line 204 of file export_vtk.hpp.
Constructor & Destructor Documentation
ExportVTK() [1/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::ExportVTK (const MeshType & mesh, int var_prec = 0) inline explicit
Constructor.
Parameters
[in] mesh A resident reference to the mesh that is to be exported. Must remain unchanged for the lifetime of this exporter.
[in] var_prec Specifies the precision of the variable entries. If set to 0, the runtime's default precision is used. See the precision parameter of the stringify_fp_sci() function for details.
Definition at line 262 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cells, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertices, and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::verts_per_cell.
ExportVTK() [2/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::ExportVTK (const MeshType & mesh, const MeshPart< MeshType > & part, int var_prec = 0) inline explicit
Constructor.
Parameters
[in] mesh A resident reference to the mesh that part was created from. Must remain unchanged for the lifetime of this exporter.
[in] part A resident reference to the meshpart that is to be exported. Must remain unchanged for the lifetime of this exporter.
[in] var_prec Specifies the precision of the variable entries. If set to 0, the runtime's default precision is used. See the precision parameter of the stringify_fp_sci() function for details.
Definition at line 301 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cells, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertices, FEAT::Geometry::MeshPart< MeshType_ >::has_topology(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::verts_per_cell.
ExportVTK() [3/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename DT_ > FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::ExportVTK (const Geometry::CGALWrapper< DT_ > & cw, int var_prec = 0) inline explicit
Constructor.
Parameters
[in] cw A resident reference to the cgal surface mesh. Must remain unchanged for the lifetime of this exporter.
[in] var_prec Specifies the precision of the variable entries. If set to 0, the runtime's default precision is used. See the precision parameter of the stringify_fp_sci() function for details.
Definition at line 368 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cells, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertices, FEAT::Geometry::CGALWrapper< DT_ >::point(), FEAT::Geometry::CGALWrapper< DT_ >::vertices_around_face(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::verts_per_cell, and XASSERTM.
Member Function Documentation
_little_endian()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> bool FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_little_endian () const inline private
Definition at line 1336 of file export_vtk.hpp.
_write_data_array()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename T_ > void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_write_data_array (std::ostream & os, const std::pair< String, std::vector< T_ > > & data, Index number_of_components = 0) const inline private
Writes an DataArray XML-node to the give output stream.
Template Parameters
T_ Type of data to write, supported are std::uint{8,16,32,64}_t, std::int{8,16,32,64}_t, float, and double.
Parameters
[in] os Outputstream to write to
[in] data Pair of array name and data to write
[in] number_of_components Number of components per entry, i.e. 1 for scalar arrays, 3 for 3D vector arrays
If the name of the data array is empty, no Name attribute will be added to the emitted DataArray tag If number_of_components is zero, no NumberOfComponents attribute will be added to the emitted DataArray tag
data is automatically compressed and base64 encoded, depending on settings for binary output and compression.
Definition at line 1262 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_ascii_output, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_use_compression, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_var_prec, FEAT::Pack::base64_encode(), FEAT::Pack::encode(), FEAT::Pack::estimate_size(), and FEAT::stringify_fp_sci().
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
add_cell_scalar()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename T_ > void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_scalar (const String & name, const T_ * data, double scaling_factor = 1.0) inline
Adds a scalar cell variable to the exporter.
Parameters
[in] name The name of the variable to be exported.
[in] data An transient array of floating point values. Its length is assumed to correspond to the number of cells of the mesh. Must not be nullptr.
[in] scaling_factor A scaling factor applied to each datapoint.
Note
This function creates a (deep) copy of the data array, so the data array can be deleted or overwritten after the return of this function.
Definition at line 629 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_scalars, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_cells, and XASSERTM.
Referenced by FEAT::Meshopt::DuDvFunctional< DT_, IT_, TrafoType_, MatrixType_ >::add_to_vtk_exporter(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::add_to_vtk_exporter(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write().
add_cell_vector() [1/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename DT_ , int dim_> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_vector (const String & name, const std::vector< Tiny::Vector< DT_, dim_ > > & v, double scaling_factor = 1.0) inline
Adds a vector-field cell variable given by a std::vector of Tiny::Vector to the exporter.
This functions adds a 1D, 2D or 3D vector-field variable to the exporter.
Template Parameters
VectorType_ Type of the input. Only DenseVectorBlocked and SparseVectorBlocked have the right interface at the moment.
Parameters
[in] name The name of the variable to be exported.
[in] v A transient reference to the vector containing the field values in the mesh cell.
[in] scaling_factor A scaling factor applied to each datapoint.
Note
This function creates a (deep) copy of the vector data.
Definition at line 761 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_vectors, and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_cells.
add_cell_vector() [2/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename T_ > void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_vector (const String & name, const T_ * x, const T_ * y = nullptr, const T_ * z = nullptr, double scaling_factor = 1.0) inline
Adds a vector-field cell variable to the exporter.
This functions adds a 1D, 2D or 3D vector-field variable to the exporter.
Parameters
[in] name The name of the variable to be exported.
[in] x,y,z The three transient arrays of floating point values. Their lengths are assumed to correspond to the number of cells of the mesh. The first array x must not be nullptr.
[in] scaling_factor A scaling factor applied to each datapoint.
Note
This function creates a (deep) copy of the three data arrays, so the data arrays can be deleted or overwritten after the return of this function.
Definition at line 660 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_vectors, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_cells, and XASSERTM.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::add_to_vtk_exporter().
add_cell_vector() [3/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename VectorType_ > void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_vector (const String & name, const VectorType_ & v, double scaling_factor = 1.0) inline
Adds a vector-field cell variable given by a LAFEM::***VectorBlocked to the exporter.
This functions adds a 1D, 2D or 3D vector-field variable to the exporter.
Template Parameters
VectorType_ Type of the input. Only DenseVectorBlocked and SparseVectorBlocked have the right interface at the moment.
Parameters
[in] name The name of the variable to be exported.
[in] v A transient reference to the vector containing the field values in the mesh cell.
[in] scaling_factor A scaling factor applied to each datapoint.
Note
This function creates a (deep) copy of the vector data.
Definition at line 721 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_vectors, and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_cells.
add_vertex_scalar()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename T_ > void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_scalar (const String & name, const T_ * data, double scaling_factor = 1.0) inline
Adds a scalar vertex variable to the exporter.
Parameters
[in] name The name of the variable to be exported.
[in] data An transient array of floating point values. Its length is assumed to correspond to the number of vertices of the mesh. Must not be nullptr.
[in] scaling_factor A scaling factor applied to each datapoint.
Note
This function creates a (deep) copy of the data array, so the data array can be deleted or overwritten after the return of this function.
Definition at line 460 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_verts, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_scalars, and XASSERTM.
Referenced by FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::add_to_vtk_exporter().
add_vertex_vector() [1/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename DT_ , int dim_> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_vector (const String & name, const std::vector< Tiny::Vector< DT_, dim_ > > & v, double scaling_factor = 1.0) inline
Adds a vector-field vertex variable given by a std::vector of Tiny::Vector to the exporter.
This functions adds a 1D, 2D or 3D vector-field variable to the exporter.
Template Parameters
VectorType_ Type of the input. Only DenseVectorBlocked and SparseVectorBlocked have the right interface at the moment.
Parameters
[in] name The name of the variable to be exported.
[in] v A transient reference to the vector containing the field values in the mesh vertices.
[in] scaling_factor A scaling factor applied to each datapoint.
Note
This function creates a (deep) copy of the vector data.
Definition at line 592 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_verts, and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_vectors.
add_vertex_vector() [2/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename T_ > void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_vector (const String & name, const T_ * x, const T_ * y = nullptr, const T_ * z = nullptr, double scaling_factor = 1.0) inline
Adds a vector-field vertex variable to the exporter.
This functions adds a 1D, 2D or 3D vector-field variable to the exporter.
Parameters
[in] name The name of the variable to be exported.
[in] x,y,z The three transient arrays of floating point values. Their lengths are assumed to correspond to the number of vertices of the mesh. The first array x must not be nullptr.
[in] scaling_factor A scaling factor applied to each datapoint.
Note
This function creates a (deep) copy of the three data arrays, so the data arrays can be deleted or overwritten after the return of this function.
Definition at line 491 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_verts, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_vectors, and XASSERTM.
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::add_to_vtk_exporter(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::add_to_vtk_exporter(), and FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::add_to_vtk_exporter().
add_vertex_vector() [3/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> template<typename VectorType_ > void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_vector (const String & name, const VectorType_ & v, double scaling_factor = 1.0) inline
Adds a vector-field vertex variable given by a LAFEM::***VectorBlocked to the exporter.
This functions adds a 1D, 2D or 3D vector-field variable to the exporter.
Template Parameters
VectorType_ Type of the input. Only DenseVectorBlocked and SparseVectorBlocked have the right interface at the moment.
Parameters
[in] name The name of the variable to be exported.
[in] v A transient reference to the vector containing the field values in the mesh vertices.
[in] scaling_factor A scaling factor applied to each datapoint.
Note
This function creates a (deep) copy of the vector data.
Definition at line 552 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_verts, and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_vectors.
clear()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::clear () inline
Clears all vertex and cell variables in the exporter.
Definition at line 412 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_scalars, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_vectors, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_scalars, and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_vectors.
enable_ascii_output()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::enable_ascii_output (bool flag) inline
Enable or disable binary output.
Parameters
[in] flag Boolean flag indicating whether binary output should be enabled
Definition at line 425 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_ascii_output.
enable_compression()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::enable_compression (bool flag) inline
Enable or disable compression.
Parameters
[in] flag Boolean flag indicating whether compression should be enabled
Note
Compression is only supported for binary output and only used if FEAT3 has been built with zlib support.
Definition at line 437 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_use_compression.
write() [1/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write (const String & filename) const inline
Writes out the data to a serial XML-VTU file.
Parameters
[in] filename The filename to which to export to. The extension ".vtu" is automatically appended to the filename.
Definition at line 786 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write().
write() [2/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write (const String & filename, const Dist::Comm & comm) inline
Writes out the data to a parallel XML-PVTU file.
This function writes out the serial VTU file of the partition represented by this exporter object and, if the rank parameter is 0, also the corresponding parallel PVTU file.
Parameters
[in] filename The filename to which to export to. The extension is automatically appended to the filename.
[in] comm The communicator of this exporter.
Definition at line 881 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_cells, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_scalar(), FEAT::Math::ilog10(), FEAT::Math::max(), FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu(), FEAT::DistFileIO::write_sequence(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
write() [3/3]
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write (const String & filename, const int rank, const int nparts) inline
Writes out the data to a parallel XML-PVTU file.
This function writes out the serial VTU file of the partition represented by this exporter object and, if the rank parameter is 0, also the corresponding parallel PVTU file.
Parameters
[in] filename The filename to which to export to. The extension is automatically appended to the filename.
[in] rank The rank of this exporter. Must be 0 <= rank < nparts. This usually coincides with the MPI-rank of the current process.
[in] nparts The total number of partitions. This usually coincides with the number of MPI-processes.
Note
Specifying nparts < 1 is equivalent to calling write(filename).
Definition at line 822 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_cells, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_scalar(), FEAT::Math::ilog10(), FEAT::stringify(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu(), and XASSERTM.
write_pvtu()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu (std::ostream & os, const String & file_title, const int nparts) const inline
Writes out the partition data in parallel XML-PVTU format.
Parameters
[in] os The output stream to which to write to.
[in] file_title The file title of the serial VTU files.
[in] nparts The total number of partitions.
Definition at line 1133 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_ascii_output, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_scalars, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_vectors, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_use_compression, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_scalars, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_vectors, FEAT::Math::ilog10(), FEAT::String::pad_front(), FEAT::stringify(), FEAT::version_major, FEAT::version_minor, FEAT::version_patch, and XABORTM.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write().
write_vtu()
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> void FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu (std::ostream & os) const inline
Writes out the mesh and variable data in serial XML-VTU format.
Parameters
[in] os The output stream to which to write to.
Definition at line 931 of file export_vtk.hpp.
References FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_ascii_output, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_scalars, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_vectors, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cells, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_cells, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_verts, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_use_compression, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_scalars, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_vectors, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertices, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_write_data_array(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::num_coords, FEAT::version_major, FEAT::version_minor, FEAT::version_patch, FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::verts_per_cell, and XABORTM.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write().
Member Data Documentation
_ascii_output
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> bool FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_ascii_output = false protected
ascii output flag
Definition at line 246 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_write_data_array(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::enable_ascii_output(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_cell_scalars
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> VarDeque FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_scalars protected
cell variable list
Definition at line 240 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_scalar(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::clear(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_cell_vectors
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> VarDeque FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cell_vectors protected
cell field list
Definition at line 242 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_vector(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::clear(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_cells
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> std::function<void(Index, IndexTuple<verts_per_cell>&)> FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_cells protected
Accessor function for cells.
Definition at line 230 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::ExportVTK(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_num_cells
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> Index FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_cells protected
number of cells in mesh
Definition at line 234 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_scalar(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_cell_vector(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_num_verts
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> Index FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_num_verts protected
number of vertices in mesh
Definition at line 232 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_scalar(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_vector(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_use_compression
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> bool FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_use_compression = can_compress protected
compressed output flag. Only applicable if _binary_output is true
Definition at line 248 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_write_data_array(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::enable_compression(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_var_prec
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> int FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_var_prec protected
precision of variables
Definition at line 244 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_write_data_array().
_vertex_scalars
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> VarDeque FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_scalars protected
vertex variable list
Definition at line 236 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_scalar(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::clear(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_vertex_vectors
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> VarDeque FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertex_vectors protected
vertex field list
Definition at line 238 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::add_vertex_vector(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::clear(), FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
_vertices
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> std::function<void(Index, Tiny::Vector<float, num_coords>&)> FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::_vertices protected
Accessor function for vertices.
Definition at line 228 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::ExportVTK(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
can_compress
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> constexpr bool FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::can_compress = false static constexpr
Definition at line 215 of file export_vtk.hpp.
num_coords
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> constexpr int FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::num_coords = 3 static constexpr
Coordinates per vertex. The VTK documentation states that this is always three.
Definition at line 207 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
verts_per_cell
template<typename Mesh_ , int cell_dim_ = Mesh_::ShapeType::dimension> constexpr int FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::verts_per_cell = Shape::FaceTraits<CellShapeType, 0>::count static constexpr
Vertices per cell.
Definition at line 210 of file export_vtk.hpp.
Referenced by FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::ExportVTK(), and FEAT::Geometry::ExportVTK< Mesh_, cell_dim_ >::write_vtu().
The documentation for this class was generated from the following file:
kernel/geometry/export_vtk.hpp