FEAT: FEAT::Assembly::OuterNormalComputer< Trafo_ > Class Template Reference
FEAT::Assembly::OuterNormalComputer< Trafo_ > Class Template Reference
Helper class that computes a weighted outer unit normal field.
#include <slip_filter_assembler.hpp>
Public Types
typedef MeshType::CoordType CoordType
Floating point type.
typedef Shape::FaceTraits< ShapeType, ShapeType::dimension-1 >::ShapeType FacetType
Shape of the facets that make up the boundary we want to compute the normals for,.
typedef TrafoType::MeshType MeshType
The underlying mesh type.
typedef MeshType::ShapeType ShapeType
Shape of the mesh's cells.
typedef Trafo_ TrafoType
Type for the transformation.
Static Public Member Functions
static void compute_orientations (CoordType *orientation, const Index *facets, const MeshType &mesh)
Computes facet orientations.
template<typename TrafoType_ >
static Tiny::Matrix< CoordType, nvt_loc, MeshType::world_dim > compute_oriented_normals (const TrafoType_ &trafo, Index k)
Computes all oriented normals on one face.
template<typename VectorType_ , typename TrafoType_ >
static void compute_outer_unit_normal (VectorType_ &nu, const Index *facets, const CoordType *orientation, const TrafoType_ &trafo)
Computes an outer unit normal field.
Static Public Attributes
static constexpr int facet_dim = ShapeType::dimension-1
The shape dimension of the boundary faces.
static constexpr int nvt_loc = Shape::FaceTraits<FacetType, 0>::count
The number of vertices that make up a Facet, i.e. 4 for a Hypercube<2>
static constexpr int world_dim = MeshType::world_dim
The number of coordinates for each vertex.
Detailed Description
template<typename Trafo_>
class FEAT::Assembly::OuterNormalComputer< Trafo_ >
Helper class that computes a weighted outer unit normal field.
Template Parameters
Trafo_ Type of the transformation
The transformation is a Finite Element function itself. Globally, it does not have enough regularity, but in each cell (or rather, on each boundary facet), a local normal field can be computed. This can be interpolated or projected onto a global space with more regularity so it can be used in computations.
At the moment, only the standard P1/Q1 trafo is implemented, meaning the outer normal field is constant in each boundary facet and discontinuous across facet boundaries. One method of mapping this function onto P1/Q1 on the boundary is to define the outer unit normal field pointwise in each mesh vertex by calculating the mean of the normals of the surrounding facets, weighted by the facet's volume. The same can be done for P2/Q2 transformations, which are not implemented yet.
In some circumstances, this leads to error estimates of optimal order, see [BD99]
This weighted mean outer unit normal is used in the SlipFilter.
See also
LAFEM::SlipFilter, SlipFilterAssembler, TraceAssembler
Author
Jordi Paul
Definition at line 60 of file slip_filter_assembler.hpp.
Member Typedef Documentation
CoordType
template<typename Trafo_ > typedef MeshType::CoordType FEAT::Assembly::OuterNormalComputer< Trafo_ >::CoordType
Floating point type.
Definition at line 83 of file slip_filter_assembler.hpp.
FacetType
template<typename Trafo_ > typedef Shape::FaceTraits<ShapeType,ShapeType::dimension-1>::ShapeType FEAT::Assembly::OuterNormalComputer< Trafo_ >::FacetType
Shape of the facets that make up the boundary we want to compute the normals for,.
Definition at line 71 of file slip_filter_assembler.hpp.
MeshType
template<typename Trafo_ > typedef TrafoType::MeshType FEAT::Assembly::OuterNormalComputer< Trafo_ >::MeshType
The underlying mesh type.
Definition at line 66 of file slip_filter_assembler.hpp.
ShapeType
template<typename Trafo_ > typedef MeshType::ShapeType FEAT::Assembly::OuterNormalComputer< Trafo_ >::ShapeType
Shape of the mesh's cells.
Definition at line 68 of file slip_filter_assembler.hpp.
TrafoType
template<typename Trafo_ > typedef Trafo_ FEAT::Assembly::OuterNormalComputer< Trafo_ >::TrafoType
Type for the transformation.
Definition at line 64 of file slip_filter_assembler.hpp.
Member Function Documentation
compute_orientations()
template<typename Trafo_ > static void FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_orientations (CoordType * orientation, const Index * facets, const MeshType & mesh) inline static
Computes facet orientations.
We need to figure out how a cell is oriented wrt. the reference cell. With the orientation code that we get from the CongruencySampler, we know if the facets of the real cell are oriented like the corresponding facets of the reference cell. Their orientation is known, so we can compute the orientation of the real facets from all this.
Parameters
[in,out] orientation Orientations in floating point format, -1.0 and 1.0 resp. for negatively or positively oriented facets
[in] facets Marker if a facet of the mesh is part of the boundary considered
[in] mesh The mesh of which we consider a part of the boundary
orientation and facets are numbered like the facets in the original mesh (and not the corresponding MeshPart for the boundary) because they need to be accessed from there.
Definition at line 106 of file slip_filter_assembler.hpp.
References FEAT::Assembly::OuterNormalComputer< Trafo_ >::nvt_loc.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
compute_oriented_normals()
template<typename Trafo_ > template<typename TrafoType_ > static Tiny::Matrix< CoordType, nvt_loc, MeshType::world_dim > FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_oriented_normals (const TrafoType_ & trafo, Index k) inline static
Computes all oriented normals on one face.
Parameters
[in] k Number of the face to compute the normals at
Returns
A matrix containing the oriented normals in all Lagrange points row-wise
Definition at line 248 of file slip_filter_assembler.hpp.
References FEAT::jac_mat, FEAT::Assembly::OuterNormalComputer< Trafo_ >::nvt_loc, and FEAT::Tiny::orthogonal().
Referenced by FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_outer_unit_normal().
compute_outer_unit_normal()
template<typename Trafo_ > template<typename VectorType_ , typename TrafoType_ > static void FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_outer_unit_normal (VectorType_ & nu, const Index * facets, const CoordType * orientation, const TrafoType_ & trafo) inline static
Computes an outer unit normal field.
The outer unit normal is computed in all vertices of the mesh's facets that are identified by facets. Because the real outer unit normal is discontinuous across facets, this is a mean where each contribution is weighted by the corresponding facet's volume.
Template Parameters
VectorType_ Type for holding the value vector for a filter, so this will be a LAFEM::SparseVector.
TrafoType_ Transformation, at the moment there is just the standard trafo.
Parameters
[in] nu This will hold the weighted mean outer unit normal in the vertices
[in] facets All relevant facets are marked in this array
[in] orientation The orientation for all faces
[in] trafo The transformation
orientation and facets are numbered like the facets in the original mesh (and not the corresponding MeshPart for the boundary) because they need to be accessed from there.
Definition at line 186 of file slip_filter_assembler.hpp.
References FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_oriented_normals(), FEAT::Assembly::OuterNormalComputer< Trafo_ >::facet_dim, and FEAT::Assembly::OuterNormalComputer< Trafo_ >::nvt_loc.
Referenced by FEAT::Assembly::SlipFilterAssembler< Trafo_ >::assemble().
Member Data Documentation
facet_dim
template<typename Trafo_ > constexpr int FEAT::Assembly::OuterNormalComputer< Trafo_ >::facet_dim = ShapeType::dimension-1 static constexpr
The shape dimension of the boundary faces.
Definition at line 74 of file slip_filter_assembler.hpp.
Referenced by FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_outer_unit_normal().
nvt_loc
template<typename Trafo_ > constexpr int FEAT::Assembly::OuterNormalComputer< Trafo_ >::nvt_loc = Shape::FaceTraits<FacetType, 0>::count static constexpr
The number of vertices that make up a Facet, i.e. 4 for a Hypercube<2>
Definition at line 80 of file slip_filter_assembler.hpp.
Referenced by FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_orientations(), FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_oriented_normals(), and FEAT::Assembly::OuterNormalComputer< Trafo_ >::compute_outer_unit_normal().
world_dim
template<typename Trafo_ > constexpr int FEAT::Assembly::OuterNormalComputer< Trafo_ >::world_dim = MeshType::world_dim static constexpr
The number of coordinates for each vertex.
Definition at line 76 of file slip_filter_assembler.hpp.
The documentation for this class was generated from the following file:
kernel/assembly/slip_filter_assembler.hpp