FEAT: FEAT::Global::SynchMatrix< MT_, VMT_ > Class Template Reference
FEAT::Global::SynchMatrix< MT_, VMT_ > Class Template Reference
Ticket class for asynchronous global matrix conversion.
#include <synch_mat.hpp>
Public Types
typedef LAFEM::MatrixMirrorBuffer< typename MT_::DataType, typename MT_::IndexType > BufferMatrixType
the buffer matrix type
typedef LAFEM::MatrixMirror< typename MT_::DataType, typename MT_::IndexType > MatrixMirrorType
the matrix mirror type
Public Member Functions
SynchMatrix (const Dist::Comm &comm, const std::vector< int > &ranks, const std::vector< VMT_ > &mirrors_row, const std::vector< VMT_ > &mirrors_col)
Constructor.
SynchMatrix (const SynchMatrix &)=delete
deleted copy constructor
void exec (MT_ &matrix)
Converts a type-0 matrix to a type-1 matrix.
void init (const MT_ &matrix)
Initializes the internal buffers for synchronization.
SynchMatrix & operator= (const SynchMatrix &)=delete
deleted copy assignment operator
Protected Attributes
const Dist::Comm & _comm
our communicator
bool _initialized
std::vector< MatrixMirrorType > _mirrors
the matrix mirrors
std::vector< int > _ranks
the neighbor ranks
std::vector< BufferMatrixType > _recv_bufs
Dist::RequestVector _recv_reqs
std::vector< BufferMatrixType > _send_bufs
send and receive buffers
Dist::RequestVector _send_reqs
send and receive request vectors
Detailed Description
template<typename MT_, typename VMT_>
class FEAT::Global::SynchMatrix< MT_, VMT_ >
Ticket class for asynchronous global matrix conversion.
Todo:
statistics
Template Parameters
MT_ The matrix type
VMT_ The vector mirror type
Author
Peter Zajac
Definition at line 38 of file synch_mat.hpp.
Member Typedef Documentation
BufferMatrixType
template<typename MT_ , typename VMT_ > typedef LAFEM::MatrixMirrorBuffer<typename MT_::DataType, typename MT_::IndexType> FEAT::Global::SynchMatrix< MT_, VMT_ >::BufferMatrixType
the buffer matrix type
Definition at line 44 of file synch_mat.hpp.
MatrixMirrorType
template<typename MT_ , typename VMT_ > typedef LAFEM::MatrixMirror<typename MT_::DataType, typename MT_::IndexType> FEAT::Global::SynchMatrix< MT_, VMT_ >::MatrixMirrorType
the matrix mirror type
Definition at line 42 of file synch_mat.hpp.
Constructor & Destructor Documentation
SynchMatrix()
template<typename MT_ , typename VMT_ > FEAT::Global::SynchMatrix< MT_, VMT_ >::SynchMatrix (const Dist::Comm & comm, const std::vector< int > & ranks, const std::vector< VMT_ > & mirrors_row, const std::vector< VMT_ > & mirrors_col) inline
Constructor.
Parameters
[in] comm The communicator
[in] ranks The neighbor ranks within the communicator
[in] mirrors_row The row vector mirrors to be used for synchronization
[in] mirrors_col The column vector mirrors to be used for synchronization
Definition at line 78 of file synch_mat.hpp.
References FEAT::Global::SynchMatrix< MT_, VMT_ >::_mirrors, and XASSERTM.
Member Function Documentation
exec()
template<typename MT_ , typename VMT_ > void FEAT::Global::SynchMatrix< MT_, VMT_ >::exec (MT_ & matrix) inline
Converts a type-0 matrix to a type-1 matrix.
Parameters
[in,out] matrix The type-0 matrix that is to be converted to type-1.
Definition at line 228 of file synch_mat.hpp.
References FEAT::Global::SynchMatrix< MT_, VMT_ >::_comm, FEAT::Global::SynchMatrix< MT_, VMT_ >::_mirrors, FEAT::Global::SynchMatrix< MT_, VMT_ >::_ranks, FEAT::Global::SynchMatrix< MT_, VMT_ >::_send_bufs, FEAT::Global::SynchMatrix< MT_, VMT_ >::_send_reqs, FEAT::Dist::RequestVector::get_request(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size(), FEAT::Dist::RequestVector::wait_all(), FEAT::Dist::RequestVector::wait_any(), and XASSERTM.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1(), and FEAT::Global::synch_matrix().
init()
template<typename MT_ , typename VMT_ > void FEAT::Global::SynchMatrix< MT_, VMT_ >::init (const MT_ & matrix) inline
Initializes the internal buffers for synchronization.
Parameters
[in] matrix The matrix to be used as a template for the buffers. The structure must be initialized, but the numerical content of the matrix is ignored.
Definition at line 126 of file synch_mat.hpp.
References FEAT::Global::SynchMatrix< MT_, VMT_ >::_comm, FEAT::Global::SynchMatrix< MT_, VMT_ >::_mirrors, FEAT::Global::SynchMatrix< MT_, VMT_ >::_ranks, FEAT::Global::SynchMatrix< MT_, VMT_ >::_send_bufs, FEAT::Global::SynchMatrix< MT_, VMT_ >::_send_reqs, FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::Dist::RequestVector::wait_all(), and XASSERTM.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1(), and FEAT::Global::synch_matrix().
Member Data Documentation
_comm
template<typename MT_ , typename VMT_ > const Dist::Comm& FEAT::Global::SynchMatrix< MT_, VMT_ >::_comm protected
our communicator
Definition at line 50 of file synch_mat.hpp.
Referenced by FEAT::Global::SynchMatrix< MT_, VMT_ >::exec(), and FEAT::Global::SynchMatrix< MT_, VMT_ >::init().
_initialized
template<typename MT_ , typename VMT_ > bool FEAT::Global::SynchMatrix< MT_, VMT_ >::_initialized protected
Definition at line 47 of file synch_mat.hpp.
_mirrors
template<typename MT_ , typename VMT_ > std::vector<MatrixMirrorType> FEAT::Global::SynchMatrix< MT_, VMT_ >::_mirrors protected
the matrix mirrors
Definition at line 54 of file synch_mat.hpp.
Referenced by FEAT::Global::SynchMatrix< MT_, VMT_ >::SynchMatrix(), FEAT::Global::SynchMatrix< MT_, VMT_ >::exec(), and FEAT::Global::SynchMatrix< MT_, VMT_ >::init().
_ranks
template<typename MT_ , typename VMT_ > std::vector<int> FEAT::Global::SynchMatrix< MT_, VMT_ >::_ranks protected
the neighbor ranks
Definition at line 52 of file synch_mat.hpp.
Referenced by FEAT::Global::SynchMatrix< MT_, VMT_ >::exec(), and FEAT::Global::SynchMatrix< MT_, VMT_ >::init().
_recv_bufs
template<typename MT_ , typename VMT_ > std::vector<BufferMatrixType> FEAT::Global::SynchMatrix< MT_, VMT_ >::_recv_bufs protected
Definition at line 58 of file synch_mat.hpp.
_recv_reqs
template<typename MT_ , typename VMT_ > Dist::RequestVector FEAT::Global::SynchMatrix< MT_, VMT_ >::_recv_reqs protected
Definition at line 56 of file synch_mat.hpp.
_send_bufs
template<typename MT_ , typename VMT_ > std::vector<BufferMatrixType> FEAT::Global::SynchMatrix< MT_, VMT_ >::_send_bufs protected
send and receive buffers
Definition at line 58 of file synch_mat.hpp.
Referenced by FEAT::Global::SynchMatrix< MT_, VMT_ >::exec(), and FEAT::Global::SynchMatrix< MT_, VMT_ >::init().
_send_reqs
template<typename MT_ , typename VMT_ > Dist::RequestVector FEAT::Global::SynchMatrix< MT_, VMT_ >::_send_reqs protected
send and receive request vectors
Definition at line 56 of file synch_mat.hpp.
Referenced by FEAT::Global::SynchMatrix< MT_, VMT_ >::exec(), and FEAT::Global::SynchMatrix< MT_, VMT_ >::init().
The documentation for this class was generated from the following file:
kernel/global/synch_mat.hpp