FEAT: FEAT::Solver::SecantLinesearch< Functional_, Filter_ > Class Template Reference
FEAT::Solver::SecantLinesearch< Functional_, Filter_ > Class Template Reference abstract
Secant linesearch.
#include <secant_linesearch.hpp>
Public Types
typedef Linesearch< Functional_, Filter_ > BaseClass
Our base class.
typedef Functional_::DataType DataType
Underlying floating point type.
typedef Filter_ FilterType
Filter type to be applied to the gradient of the functional.
typedef Functional_::VectorTypeR VectorType
Input vector type for the functional's gradient.
Public Member Functions
SecantLinesearch (const String &section_name, const PropertyMap *section, Functional_ &functional, Filter_ &filter)
Constructor using a PropertyMap.
SecantLinesearch (Functional_ &functional, Filter_ &filter, const DataType secant_step=secant_step_default, const bool keep_iterates=false)
Standard constructor.
virtual ~SecantLinesearch ()
virtual Status apply (Vector_ &vec_cor, const Vector_ &vec_def)=0
Solver application method.
virtual Status apply (VectorType &vec_cor, const VectorType &vec_dir) override
Applies the solver, setting the initial guess to zero.
DataType calc_convergence_rate () const
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
DataType calc_defect_reduction () const
Computes the overall defect reduction factor: (defect_final / defect_inital)
virtual Status correct (VectorType &vec_sol, const VectorType &vec_dir) override
Applies the solver, making use of an initial guess.
virtual void done ()
Finalization method.
virtual void done_numeric ()
Numeric finalization method.
virtual void done_symbolic () override
Symbolic finalization method.
virtual void force_defect_norm_calc (bool force)
Forces the calculation of defect norms in every iteration.
DataType get_def_final () const
Returns the final defect.
DataType get_def_initial () const
Returns the initial defect.
void get_defect_from_grad (VectorType &vec_def) const
Sets the initial gradient from a defect vector.
DataType get_div_abs () const
Returns the absolute divergence.
DataType get_div_rel () const
Returns the relative divergence.
DataType get_final_fval () const
Gets the functional value of the last iteration.
const VectorType & get_initial_sol () const
Gets the initial solution the linesearch started with.
Index get_max_iter () const
Returns the maximum number of iterations.
Index get_min_iter () const
Returns the minimal number of iterations.
Index get_min_stag_iter () const
Returns the minimum stagnation iteration count.
Index get_num_iter () const
Returns number of performed iterations.
String get_plot_name () const
Returns the plot name of the solver.
virtual DataType get_rel_update () const
Get the relative update of the solver application.
DataType get_stag_rate () const
Returns the stagnation rate.
Status get_status () const
Returns the status.
virtual String get_summary () const override
Returns a summary string.
DataType get_tol_abs () const
Returns the absolute tolerance.
DataType get_tol_abs_low () const
Returns the lower absolute tolerance.
DataType get_tol_rel () const
Returns the relative tolerance.
virtual void init ()
Initialization method.
virtual void init_numeric ()
Numeric initialization method.
virtual void init_symbolic () override
Symbolic initialization method.
bool is_converged () const
checks for convergence
bool is_converged (const DataType def_cur) const
checks for convergence
bool is_diverged () const
checks for divergence
bool is_diverged (const DataType def_cur) const
checks for divergence
virtual String name () const override
Returns a descriptive string.
virtual void plot_summary () const
Plot a summary of the last solver run.
virtual void reset () override
Resets various member variables in case the solver is reused.
void set_dir_scaling (const bool b)
Determines if search direction scaling is to be used.
void set_div_abs (DataType div_abs)
Sets the absolute divergence for the solver.
void set_div_rel (DataType div_rel)
Sets the relative divergence for the solver.
void set_grad_from_defect (const VectorType &vec_def)
Gets a defect vector from the final gradient.
void set_initial_fval (DataType f0)
Sets the intitial functional value.
void set_max_iter (Index max_iter)
Sets the maximum iteration count for the solver.
void set_min_iter (Index min_iter)
Sets the minimum iteration count for the solver.
void set_min_stag_iter (Index min_iter)
Sets the minimum stagnate iteration count for the solver.
void set_plot_interval (const Index plot_interval)
Sets the interval between two plot outputs, if any.
void set_plot_mode (const PlotMode plot_mode)
Sets the plot mode of the solver.
void set_plot_name (const String &plot_name)
Sets the plot name of the solver.
void set_secant_step (DataType secant_step)
Sets the length of the first secant step.
void set_stag_rate (DataType rate)
Sets the stagnation rate for the solver.
void set_tol_abs (DataType tol_abs)
Sets the absolute tolerance for the solver.
void set_tol_abs_low (DataType tol_abs_low)
Sets the lower absolute tolerance for the solver.
void set_tol_curvature (DataType tol_curvature)
Sets the tolerance for the sufficient decrease in curvature.
void set_tol_decrease (DataType tol_decrease)
Sets the tolerance for the sufficient decrease in functional value.
void set_tol_rel (DataType tol_rel)
Sets the relative tolerance for the solver.
void set_tol_step (DataType tol_step)
Sets the step length tolerance.
virtual void trim_func_grad (DataType &func)
Trims the function value and gradient according to some threshold.
Public Attributes
std::deque< VectorType > * iterates
For debugging purposes, it is possible to save all iterates to this.
Static Public Attributes
static constexpr DataType secant_step_default = DataType(1e-2)
Default initial step length.
Protected Member Functions
virtual Status _analyze_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag)
Internal function: analyze the current defect.
virtual Status _apply_intern (VectorType &vec_sol, const VectorType &vec_dir)
Internal function: Applies the solver.
virtual DataType _calc_def_norm (const VectorType &vec_def, const VectorType &vec_sol)
Computes the defect norm.
virtual Status _check_convergence (const DataType fval, const DataType df, const DataType alpha)
Performs the line search convergence checks using the strong Wolfe conditions.
bool _plot_iter (Status st=Status::progress) const
Plot the current iteration?
virtual void _plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev)
Plots an iteration line.
bool _plot_summary () const
Plot summary?
void _print_line (const String &line) const
Prints a line.
bool _progress () const
Progress iteration?
void _set_comm (const Dist::Comm *comm)
Sets the communicator for the solver directly.
void _set_comm_by_matrix (const Matrix_ &matrix)
Sets the communicator for the solver from a matrix.
void _set_comm_by_vector (const Functional_::VectorTypeR &vector)
Sets the communicator for the solver from a vector.
virtual Status _set_initial_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the initial defect vector.
virtual Status _set_new_defect (const VectorType &vec_def, const VectorType &vec_sol)
Internal function: sets the new (next) defect vector.
virtual Status _startup (DataType &alpha, DataType &fval, DataType &delta, const VectorType &vec_sol, const VectorType &vec_dir)
Performs the startup of the iteration.
virtual Status _update_defect (const DataType def_cur_norm)
Internal function: sets the new (next) defect norm.
Protected Attributes
DataType _alpha_0
Initial line search parameter.
DataType _alpha_min
Line search parameter.
const Dist::Comm * _comm
Communicator of the solver.
DataType _def_cur
current defect
DataType _def_init
initial defect
DataType _def_prev
previous iteration defect
DataType _delta_0
Initial <vec_dir, vec_grad>
bool _dir_scaling
DataType _div_abs
absolute divergence parameter
DataType _div_rel
relative divergence parameter
Filter_ & _filter
The filter to be applied to the functional's gradient.
bool _force_def_norm_calc
whether skipping of defect computation is allowed or not
Functional_ & _functional
The (nonlinear) functional.
DataType _fval_0
Initial functional value.
DataType _fval_min
Functional functional value.
Index _iter_digits
iteration count digits for plotting
Index _max_iter
maximum number of iterations
Index _min_iter
minimum number of iterations
Index _min_stag_iter
minimum number of stagnation iterations
DataType _norm_dir
The 2-norm of the search direction.
DataType _norm_sol
The 2-norm of the iterate.
Index _num_iter
number of performed iterations
Index _num_stag_iter
number of consecutive stagnated iterations
Index _plot_interval
plot output interval
PlotMode _plot_mode
whether to plot something
String _plot_name
name of the solver in plots
DataType _secant_step
Default step for calculating the "other" secant point in the initial step. Crucial.
DataType _stag_rate
stagnation rate
Status _status
current status of the solver
DataType _tol_abs
absolute tolerance parameter
DataType _tol_abs_low
absolute low tolerance parameter
DataType _tol_curvature
Tolerance for sufficient decrease in the norm of the gradient (Wolfe conditions)
DataType _tol_decrease
Tolerance for sufficient decrease in the functional value (Wolfe conditions)
DataType _tol_rel
relative tolerance parameter
DataType _tol_step
Tolerance for the update step.
DataType _trim_threshold
Threshold for trimming function value and gradient.
VectorType _vec_grad
Gradient vector.
VectorType _vec_initial_sol
Initial solution.
VectorType _vec_pn
descend direction vector, normalized for better numerical stability
VectorType _vec_tmp
temporary vector
Detailed Description
template<typename Functional_, typename Filter_>
class FEAT::Solver::SecantLinesearch< Functional_, Filter_ >
Secant linesearch.
Template Parameters
Functional_ The (nonlinear) functional to be evaluated
Filter_ The filter to be applied to the functional's gradient
This class implements a linesearch which approximately finds
\[ \alpha^* = \mathrm{argmin} \nabla f(x + \alpha d) \cdot d \]
for a given search direction \(d \) by approximating the second order derivatives along \(d \) by a secant.
Definition at line 32 of file secant_linesearch.hpp.
Member Typedef Documentation
BaseClass
template<typename Functional_ , typename Filter_ > typedef Linesearch<Functional_, Filter_> FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::BaseClass
Our base class.
Definition at line 42 of file secant_linesearch.hpp.
DataType
template<typename Functional_ , typename Filter_ > typedef Functional_::DataType FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::DataType
Underlying floating point type.
Definition at line 40 of file secant_linesearch.hpp.
FilterType
template<typename Functional_ , typename Filter_ > typedef Filter_ FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::FilterType
Filter type to be applied to the gradient of the functional.
Definition at line 36 of file secant_linesearch.hpp.
VectorType
template<typename Functional_ , typename Filter_ > typedef Functional_::VectorTypeR FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::VectorType
Input vector type for the functional's gradient.
Definition at line 38 of file secant_linesearch.hpp.
Constructor & Destructor Documentation
SecantLinesearch() [1/2]
template<typename Functional_ , typename Filter_ > FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::SecantLinesearch (Functional_ & functional, Filter_ & filter, const DataType secant_step = secant_step_default, const bool keep_iterates = false) inline explicit
Standard constructor.
Parameters
[in,out] functional The (nonlinear) functional. Cannot be const because it saves its own state.
[in] filter Filter to apply to the functional's gradient.
[in] secant_step Step length for setting the "other" secant point in the first iteration. Crucial.
[in] keep_iterates Keep all iterates in a std::deque. Defaults to false.
Definition at line 67 of file secant_linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_alpha_0, and FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_secant_step.
SecantLinesearch() [2/2]
template<typename Functional_ , typename Filter_ > FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::SecantLinesearch (const String & section_name, const PropertyMap * section, Functional_ & functional, Filter_ & filter) inline explicit
Constructor using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] functional The functional.
[in] filter The system filter.
Definition at line 93 of file secant_linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_alpha_0, FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_secant_step, FEAT::PropertyMap::query(), and FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::set_secant_step().
~SecantLinesearch()
template<typename Functional_ , typename Filter_ > virtual FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::~SecantLinesearch () inline virtual
Definition at line 108 of file secant_linesearch.hpp.
Member Function Documentation
_analyze_defect()
virtual Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_analyze_defect (Index num_iter, DataType def_cur, DataType def_prev, bool check_stag) inline protected virtual inherited
Internal function: analyze the current defect.
Note
This function is called by _set_new_defect() and _update_defect().
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
[in] check_stag Specifies whether to check (and update) the stagnation criterion. This is typically set to false if one wants to check anything else than the 'true' next defect norm.
Returns
The updated status code.
Definition at line 866 of file iterative.hpp.
_apply_intern()
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern (VectorType & vec_sol, const VectorType & vec_dir) inline protected virtual
Internal function: Applies the solver.
Parameters
[in,out] vec_sol Initial guess, gets overwritten by solution
[in] vec_dir Search direction
Note
This assumes that the initial functional value _fval_0 and the gradient were already set from the calling solver!
Returns
The solver status (success, max_iter, stagnated)
<vec_pn, vec_grad>. We want to find the minimum of the functional value along vec_pn
Definition at line 195 of file secant_linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_alpha_min, FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_dir_scaling, FEAT::Solver::Linesearch< Functional_, Filter_ >::_filter, FEAT::Solver::Linesearch< Functional_, Filter_ >::_functional, FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_min, FEAT::Solver::Linesearch< Functional_, Filter_ >::_norm_dir, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_iter, FEAT::Solver::Linesearch< Functional_, Filter_ >::_startup(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_grad, FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_initial_sol, FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_pn, FEAT::Math::abs(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_num_iter(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::name(), FEAT::Solver::progress, FEAT::Math::sqrt(), FEAT::Solver::stagnated, FEAT::Solver::success, and FEAT::Solver::undefined.
Referenced by FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::apply(), and FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::correct().
_calc_def_norm()
virtual DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_calc_def_norm (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Computes the defect norm.
Parameters
[in] vec_def The current defect vector.
[in] vec_sol The current solution vector approximation.
Definition at line 706 of file iterative.hpp.
_check_convergence()
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence (const DataType fval, const DataType df, const DataType alpha) inline protected virtual inherited
Performs the line search convergence checks using the strong Wolfe conditions.
Parameters
[in] fval The current functional value
[in] df The current directional derivative value: \(df = \left< \nabla f(x_0), d \right>\).
[in] alpha The step size of the last update.
Also sets the current defect. The strong Wolfe conditions are
\[ f(x) < f(x_0) + \alpha c_1 \left< \nabla f(x_0), d \right> \wedge |\left< \nabla f(x), d \right>| < - c_2 \left< \nabla f(x_0), d \right>, \]
where \(c_1\) is known as tol_decrease and \(c_2 \) is known as tol_curvature.
Returns
Status::success if the strong Wolfe conditions hold.
Definition at line 543 of file linesearch.hpp.
References FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_cur, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_init, FEAT::Solver::Linesearch< Functional_, Filter_ >::_delta_0, FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_0, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_iter_digits, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_max_iter, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_iter, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_iter(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_name, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_print_line(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_tol_curvature, FEAT::Solver::Linesearch< Functional_, Filter_ >::_tol_decrease, FEAT::Solver::aborted, FEAT::Math::abs(), FEAT::Solver::diverged, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_num_iter(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_diverged(), FEAT::Math::isfinite(), FEAT::Solver::max_iter, FEAT::Solver::SolverBase< Vector_ >::name(), FEAT::String::pad_front(), FEAT::Solver::progress, FEAT::stringify(), FEAT::stringify_fp_sci(), and FEAT::Solver::success.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), and FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern().
_plot_iter()
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_iter (Status st = Status::progress) const inline protected inherited
Plot the current iteration?
Parameters
[in] st The status of the current iteration.
Returns
true if the plot mode is set to iter or all and the plot interval matches or the solver does not continue to the next iteration
Definition at line 720 of file iterative.hpp.
_plot_iter_line()
virtual void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_iter_line (Index num_iter, DataType def_cur, DataType def_prev) inline protected virtual inherited
Plots an iteration line.
Parameters
[in] num_iter Current number of iterations; usually = this->_num_iter.
[in] def_cur Current defect norm; usually = this->_def_cur.
[in] def_prev Previous defect norm; usually = this->_def_prev.
Definition at line 773 of file iterative.hpp.
_plot_summary()
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_summary () const inline protected inherited
Plot summary?
Returns
true if the plot mode is set to summary or all.
Definition at line 731 of file iterative.hpp.
_print_line()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_print_line (const String & line) const inline protected inherited
Prints a line.
Parameters
[in] line The line to be printed.
Definition at line 752 of file iterative.hpp.
_progress()
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_progress () const inline protected inherited
Progress iteration?
Returns
true if the solver should process, otherwise false.
Definition at line 741 of file iterative.hpp.
_set_comm()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_comm (const Dist::Comm * comm) inline protected inherited
Sets the communicator for the solver directly.
Parameters
[in] comm A pointer to the communicator that is to be used by the solver.
Definition at line 667 of file iterative.hpp.
_set_comm_by_matrix()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_comm_by_matrix (const Matrix_ & matrix) inline protected inherited
Sets the communicator for the solver from a matrix.
Parameters
[in] matrix A reference to a matrix. If 'Matrix_' is a 'Global::Matrix', then the communicator of the matrix gate is taken.
Definition at line 680 of file iterative.hpp.
_set_comm_by_vector()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_comm_by_vector (const Functional_::VectorTypeR & vector) inline protected inherited
Sets the communicator for the solver from a vector.
Parameters
[in] vector A reference to a vector. If 'Vector_' is a 'Global::Vector', then the communicator of the vector gate is taken.
Definition at line 692 of file iterative.hpp.
_set_initial_defect()
virtual Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_initial_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Internal function: sets the initial defect vector.
Parameters
[in] vec_def The initial defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Reimplemented in FEAT::Solver::QPenalty< Functional_ >.
Definition at line 802 of file iterative.hpp.
_set_new_defect()
virtual Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_set_new_defect (const VectorType & vec_def, const VectorType & vec_sol) inline protected virtual inherited
Internal function: sets the new (next) defect vector.
This function computes the defect vector's norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] vec_def The new defect vector.
[in] vec_sol The current solution vector approximation.
Returns
The updated Status code.
Definition at line 924 of file iterative.hpp.
_startup()
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::Linesearch< Functional_, Filter_ >::_startup (DataType & alpha, DataType & fval, DataType & delta, const VectorType & vec_sol, const VectorType & vec_dir) inline protected virtual inherited
Performs the startup of the iteration.
Parameters
[out] alpha The initial step size value.
[out] fval The initial functional value.
[out] delta The initial direction derivative value: \(\delta = \left< dir, grad \right>\).
[in] vec_sol The initial guess.
[in] vec_dir The search direction.
The routine sets the initial data from "iteration 0" (needed for checking the strong Wolfe conditions later) and does some error checking.
Returns
Status::progress if no error occurred.
Definition at line 464 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_alpha_0, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_init, FEAT::Solver::Linesearch< Functional_, Filter_ >::_delta_0, FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_0, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_iter_digits, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_iter, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_iter(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_name, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_print_line(), FEAT::Solver::aborted, FEAT::Math::abs(), FEAT::Math::isfinite(), FEAT::String::pad_front(), FEAT::Solver::progress, FEAT::stringify(), FEAT::stringify_fp_sci(), and XABORTM.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), and FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern().
_update_defect()
virtual Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_update_defect (const DataType def_cur_norm) inline protected virtual inherited
Internal function: sets the new (next) defect norm.
This function takes a pre-calculated defect vector norm, increments the iteration count, plots an output line to std::cout and checks whether any of the stopping criterions is fulfilled.
Parameters
[in] def_cur_norm The new defect norm.
Returns
The updated Status code.
Note
This function is preferred over _set_new_defect when using asynchronous mpi operations.
Definition at line 970 of file iterative.hpp.
apply() [1/2]
template<typename Vector_ > virtual Status FEAT::Solver::SolverBase< Vector_ >::apply (Vector_ & vec_cor, const Vector_ & vec_def) pure virtual inherited
Solver application method.
This method applies the solver represented by this object onto a given defect vector and returns the corresponding correction vector.
Note
Solvers which derive from the IterativeSolver base class also provide a correct() method which corrects an initial solution instead of starting with the null vector.
Parameters
[out] vec_cor The vector that shall receive the solution of the linear system. It is assumed to be allocated, but its numerical contents may be undefined upon calling this method.
[in] vec_def The vector that represents the right-hand-side of the linear system to be solved.
Attention
vec_cor and vec_def must not refer to the same vector object!
Returns
A Status code that represents the status of the solution step.
Implemented in FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::CuSolverLU, FEAT::Solver::CuSolverQR, FEAT::Solver::ScalePrecond< Vector_, Filter_ >, FEAT::Solver::DiagonalPrecond< Vector_, Filter_ >, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NLOptPrecond< VectorType_, FilterType_ >, FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, and FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >.
Referenced by FEAT::Solver::solve().
apply() [2/2]
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::apply (VectorType & vec_cor, const VectorType & vec_dir) inline override virtual
Applies the solver, setting the initial guess to zero.
Parameters
[out] vec_cor Solution, gets zeroed
[in] vec_dir Search direction
Returns
The solver status (success, max_iter, stagnated)
Definition at line 147 of file secant_linesearch.hpp.
References FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_filter, FEAT::Solver::Linesearch< Functional_, Filter_ >::_functional, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_status, and FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::plot_summary().
calc_convergence_rate()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::calc_convergence_rate () const inline inherited
Computes the overall convergence rate: (defect_final / defect_initial) ^ (1 / number of iterations)
Definition at line 582 of file iterative.hpp.
calc_defect_reduction()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::calc_defect_reduction () const inline inherited
Computes the overall defect reduction factor: (defect_final / defect_inital)
Definition at line 597 of file iterative.hpp.
correct()
template<typename Functional_ , typename Filter_ > virtual Status FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::correct (VectorType & vec_sol, const VectorType & vec_dir) inline override virtual
Applies the solver, making use of an initial guess.
Parameters
[out] vec_sol Initial guess, gets overwritten by the solution
[in] vec_dir Search direction
Returns
The solver status (success, max_iter, stagnated)
Implements FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >.
Definition at line 170 of file secant_linesearch.hpp.
References FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_filter, FEAT::Solver::Linesearch< Functional_, Filter_ >::_functional, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_status, and FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::plot_summary().
done()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done () inline virtual inherited
Finalization method.
This function performs both the symbolic and numeric finalization, i.e. it simply performs
this->done_numeric();
this->done_symbolic();
Definition at line 283 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::done_numeric(), and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
done_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::done_numeric () inline virtual inherited
Numeric finalization method.
This method is called to release any data allocated in the numeric initialization step.
Reimplemented in FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >.
Definition at line 246 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::done(), FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::done_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::done_numeric(), FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::done_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::done_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::done_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::done_numeric(), and FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::done_numeric().
done_symbolic()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::Linesearch< Functional_, Filter_ >::done_symbolic () inline override virtual inherited
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 286 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_grad, FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_initial_sol, FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_pn, FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_tmp, and FEAT::Solver::SolverBase< Vector_ >::done_symbolic().
force_defect_norm_calc()
virtual void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::force_defect_norm_calc (bool force) inline virtual inherited
Forces the calculation of defect norms in every iteration.
Note
Please note that allowing the skipping of defect norm calculations is merely a hint and a derived class may override this function therefore always forcing the calculation of defect norms. One possible reason is that the derived solver class may require defect norms as part of its solver algorithm and therefore skipping the computation of the defect norms may break the solver; two examples are the BiCGStab and GMRES solvers.
Parameters
[in] force Specifies whether defect norm computation is to be enforced in every iteration
Definition at line 490 of file iterative.hpp.
get_def_final()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_def_final () const inline inherited
Returns the final defect.
Definition at line 570 of file iterative.hpp.
get_def_initial()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_def_initial () const inline inherited
Returns the initial defect.
Definition at line 564 of file iterative.hpp.
get_defect_from_grad()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::Linesearch< Functional_, Filter_ >::get_defect_from_grad (VectorType & vec_def) const inline inherited
Sets the initial gradient from a defect vector.
Parameters
[in] vec_def The initial defect vector.
This is handy because the linesearch gets called from another solver that in general already evaluated the functional gradient.
Definition at line 378 of file linesearch.hpp.
get_div_abs()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_div_abs () const inline inherited
Returns the absolute divergence.
Definition at line 419 of file iterative.hpp.
get_div_rel()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_div_rel () const inline inherited
Returns the relative divergence.
Definition at line 413 of file iterative.hpp.
get_final_fval()
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::get_final_fval () const inline inherited
Gets the functional value of the last iteration.
Returns
The functional value of the last iteration
Definition at line 344 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_min.
get_initial_sol()
template<typename Functional_ , typename Filter_ > const VectorType & FEAT::Solver::Linesearch< Functional_, Filter_ >::get_initial_sol () const inline inherited
Gets the initial solution the linesearch started with.
Returns
A const reference to the initial solution vector.
This is useful for rejecting steps that are too small in the calling solver, like NLCG or NLSD.
Definition at line 404 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_initial_sol.
get_max_iter()
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_max_iter () const inline inherited
Returns the maximum number of iterations.
Definition at line 474 of file iterative.hpp.
get_min_iter()
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_min_iter () const inline inherited
Returns the minimal number of iterations.
Definition at line 468 of file iterative.hpp.
get_min_stag_iter()
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_min_stag_iter () const inline inherited
Returns the minimum stagnation iteration count.
Definition at line 443 of file iterative.hpp.
get_num_iter()
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_num_iter () const inline inherited
Returns number of performed iterations.
Definition at line 462 of file iterative.hpp.
get_plot_name()
String FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_plot_name () const inline inherited
Returns the plot name of the solver.
Definition at line 523 of file iterative.hpp.
get_rel_update()
template<typename Functional_ , typename Filter_ > virtual DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::get_rel_update () const inline virtual inherited
Get the relative update of the solver application.
The linesearch updates the solution according to
\[ x \mapsto x + \alpha d, \]
so the relative update is
\[ \hat{\alpha} = | \alpha | \frac{\| d \|_2}{ \| x \|_2}. \]
Used for determining if the linesearch stagnated without updating the solution in a significant way. As this base class normalizes \(d \) in _startup(), it just return \(\alpha \). Derived classes NOT performing this normalization must overwrite this.
Returns
The relative update.
Reimplemented in FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >.
Definition at line 334 of file linesearch.hpp.
References FEAT::Math::abs().
get_stag_rate()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_stag_rate () const inline inherited
Returns the stagnation rate.
Definition at line 431 of file iterative.hpp.
get_status()
Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_status () const inline inherited
Returns the status.
Definition at line 576 of file iterative.hpp.
get_summary()
template<typename Functional_ , typename Filter_ > virtual String FEAT::Solver::Linesearch< Functional_, Filter_ >::get_summary () const inline override virtual inherited
Returns a summary string.
Reimplemented from FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >.
Definition at line 213 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_alpha_min, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_cur, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_init, FEAT::Solver::Linesearch< Functional_, Filter_ >::_functional, FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_0, FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_min, FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_num_iter(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_plot_name(), FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_status(), FEAT::stringify(), and FEAT::stringify_fp_sci().
get_tol_abs()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_tol_abs () const inline inherited
Returns the absolute tolerance.
Definition at line 389 of file iterative.hpp.
get_tol_abs_low()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_tol_abs_low () const inline inherited
Returns the lower absolute tolerance.
Definition at line 395 of file iterative.hpp.
get_tol_rel()
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::get_tol_rel () const inline inherited
Returns the relative tolerance.
Definition at line 383 of file iterative.hpp.
init()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init () inline virtual inherited
Initialization method.
This function performs both the symbolic and numeric initialization, i.e. it simply performs
this->init_symbolic();
this->init_numeric();
Definition at line 268 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::init_numeric(), and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
init_numeric()
template<typename Vector_ > virtual void FEAT::Solver::SolverBase< Vector_ >::init_numeric () inline virtual inherited
Numeric initialization method.
This method is called to perform numeric initialization of the solver.
Before this function can be called, the symbolic initialization must be performed.
Reimplemented in FEAT::Solver::AmaVanka< Matrix_, Filter_ >, FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::Chebyshev< Matrix_, Filter_ >, FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >, FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >, FEAT::Solver::CUDSS, FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >, FEAT::Solver::DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >, FEAT::Solver::ParaSailsPrecond< Matrix_, Filter_ >, FEAT::Solver::EuclidPrecond< Matrix_, Filter_ >, FEAT::Solver::BoomerAMG< Matrix_, Filter_ >, FEAT::Solver::ILUPrecond< Matrix_, Filter_ >, FEAT::Solver::PreconditionedIterativeSolver< Vector_ >, FEAT::Solver::PreconditionedIterativeSolver< Matrix_::VectorTypeR >, FEAT::Solver::PreconditionedIterativeSolver< Functional_::VectorTypeR >, FEAT::Solver::JacobiPrecond< Matrix_, Filter_ >, FEAT::Solver::MatrixPrecond< Matrix_, Filter_ >, FEAT::Solver::MKLDSS, FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >, FEAT::Solver::NonlinearOperatorPrecondWrapper< NonlinearOperator_ >, FEAT::Solver::PCGNR< Matrix_, Filter_ >, FEAT::Solver::PCGNRILU< Matrix_, Filter_ >, FEAT::Solver::PolynomialPrecond< Matrix_, Filter_ >, FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >, FEAT::Solver::SuperLU< Matrix_, Filter_ >, FEAT::Solver::Umfpack, FEAT::Solver::UmfpackMean, FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >, FEAT::Solver::GenericUmfpack< Matrix_ >, FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >, FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >, FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >, and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >.
Definition at line 237 of file base.hpp.
Referenced by FEAT::Solver::SolverBase< Vector_ >::init(), FEAT::Solver::BFBT< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::init_numeric(), FEAT::Solver::BFBT< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_numeric(), FEAT::Solver::Chebyshev< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::init_numeric(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::init_numeric(), FEAT::Solver::HypreSolverBase< Matrix_, Filter_, SolverBase_ >::init_numeric(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::init_numeric(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::init_numeric(), FEAT::Solver::PCGNR< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::PCGNRILU< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::SuperLU< Matrix_, Filter_ >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ >::init_numeric(), FEAT::Solver::UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >::init_numeric(), and FEAT::Solver::VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ >::init_numeric().
init_symbolic()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::Linesearch< Functional_, Filter_ >::init_symbolic () inline override virtual inherited
Reimplemented from FEAT::Solver::SolverBase< Vector_ >.
Definition at line 275 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_grad, FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_initial_sol, FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_pn, FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_tmp, and FEAT::Solver::SolverBase< Vector_ >::init_symbolic().
is_converged() [1/2]
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_converged () const inline inherited
checks for convergence
Returns
true, if converged, else false
Definition at line 533 of file iterative.hpp.
is_converged() [2/2]
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_converged (const DataType def_cur) const inline inherited
checks for convergence
Parameters
[in] def_cur The defect norm that is to be analyzed
Returns
true, if converged, else false
Definition at line 546 of file iterative.hpp.
is_diverged() [1/2]
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_diverged () const inline inherited
checks for divergence
Definition at line 552 of file iterative.hpp.
is_diverged() [2/2]
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::is_diverged (const DataType def_cur) const inline inherited
checks for divergence
Definition at line 558 of file iterative.hpp.
name()
template<typename Functional_ , typename Filter_ > virtual String FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::name () const inline override virtual
Returns a descriptive string.
Returns
A string describing the solver.
Implements FEAT::Solver::SolverBase< Vector_ >.
Definition at line 113 of file secant_linesearch.hpp.
Referenced by FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern().
plot_summary()
virtual void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::plot_summary () const inline virtual inherited
Plot a summary of the last solver run.
Definition at line 627 of file iterative.hpp.
reset()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::reset () inline override virtual
Resets various member variables in case the solver is reused.
Reimplemented from FEAT::Solver::Linesearch< Functional_, Filter_ >.
Definition at line 119 of file secant_linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_alpha_0, FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_secant_step, and FEAT::Solver::Linesearch< Functional_, Filter_ >::reset().
set_dir_scaling()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::Linesearch< Functional_, Filter_ >::set_dir_scaling (const bool b) inline inherited
Determines if search direction scaling is to be used.
Internally, the search direction vector gets normalized (\(\| p \|_2 = 1 \)) for numerical stablility. Some line searches have a heuristic for choosing the initial step length \(\alpha_0 \), which can use \(\| p \|_2 \) if _dir_scaling is set to true. This is useful when using a preconditioner (e.g. Newton).
Definition at line 269 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_dir_scaling.
set_div_abs()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_div_abs (DataType div_abs) inline inherited
Sets the absolute divergence for the solver.
Definition at line 407 of file iterative.hpp.
set_div_rel()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_div_rel (DataType div_rel) inline inherited
Sets the relative divergence for the solver.
Definition at line 401 of file iterative.hpp.
set_grad_from_defect()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::Linesearch< Functional_, Filter_ >::set_grad_from_defect (const VectorType & vec_def) inline inherited
Gets a defect vector from the final gradient.
Parameters
[out] vec_def The final defect vector.
This is handy because the other solver can use the gradient of the new solution without re-calculating it.
Definition at line 392 of file linesearch.hpp.
set_initial_fval()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::Linesearch< Functional_, Filter_ >::set_initial_fval (DataType f0) inline inherited
Sets the intitial functional value.
Parameters
[in] f0 The initial functional value.
This is handy because the linesearch gets called from another solver that in general already evaluated the functional.
Definition at line 359 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_0, FEAT::Solver::Linesearch< Functional_, Filter_ >::_trim_threshold, and FEAT::Math::abs().
set_max_iter()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_max_iter (Index max_iter) inline inherited
Sets the maximum iteration count for the solver.
Definition at line 455 of file iterative.hpp.
set_min_iter()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_min_iter (Index min_iter) inline inherited
Sets the minimum iteration count for the solver.
Definition at line 449 of file iterative.hpp.
set_min_stag_iter()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_min_stag_iter (Index min_iter) inline inherited
Sets the minimum stagnate iteration count for the solver.
Definition at line 437 of file iterative.hpp.
set_plot_interval()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_plot_interval (const Index plot_interval) inline inherited
Sets the interval between two plot outputs, if any.
Parameters
[in] plot_interval The desired interval of iteration plots
Definition at line 511 of file iterative.hpp.
set_plot_mode()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_plot_mode (const PlotMode plot_mode) inline inherited
Sets the plot mode of the solver.
Parameters
[in] plot_mode The desired plot mode
Definition at line 501 of file iterative.hpp.
set_plot_name()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_plot_name (const String & plot_name) inline inherited
Sets the plot name of the solver.
Definition at line 517 of file iterative.hpp.
set_secant_step()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::set_secant_step (DataType secant_step) inline
Sets the length of the first secant step.
Definition at line 129 of file secant_linesearch.hpp.
References FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_secant_step, and XASSERT.
Referenced by FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::SecantLinesearch().
set_stag_rate()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_stag_rate (DataType rate) inline inherited
Sets the stagnation rate for the solver.
Definition at line 425 of file iterative.hpp.
set_tol_abs()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_tol_abs (DataType tol_abs) inline inherited
Sets the absolute tolerance for the solver.
Definition at line 371 of file iterative.hpp.
set_tol_abs_low()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_tol_abs_low (DataType tol_abs_low) inline inherited
Sets the lower absolute tolerance for the solver.
Definition at line 377 of file iterative.hpp.
set_tol_curvature()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::Linesearch< Functional_, Filter_ >::set_tol_curvature (DataType tol_curvature) inline inherited
Sets the tolerance for the sufficient decrease in curvature.
Definition at line 233 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_tol_curvature, and XASSERT.
Referenced by FEAT::Solver::Linesearch< Functional_, Filter_ >::Linesearch().
set_tol_decrease()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::Linesearch< Functional_, Filter_ >::set_tol_decrease (DataType tol_decrease) inline inherited
Sets the tolerance for the sufficient decrease in functional value.
Definition at line 243 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_tol_decrease, and XASSERT.
Referenced by FEAT::Solver::Linesearch< Functional_, Filter_ >::Linesearch().
set_tol_rel()
void FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::set_tol_rel (DataType tol_rel) inline inherited
Sets the relative tolerance for the solver.
Definition at line 365 of file iterative.hpp.
set_tol_step()
template<typename Functional_ , typename Filter_ > void FEAT::Solver::Linesearch< Functional_, Filter_ >::set_tol_step (DataType tol_step) inline inherited
Sets the step length tolerance.
Definition at line 254 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_tol_step, and XASSERT.
Referenced by FEAT::Solver::Linesearch< Functional_, Filter_ >::Linesearch().
trim_func_grad()
template<typename Functional_ , typename Filter_ > virtual void FEAT::Solver::Linesearch< Functional_, Filter_ >::trim_func_grad (DataType & func) inline virtual inherited
Trims the function value and gradient according to some threshold.
Parameters
[in,out] func Function value.
This sets
\[ trim(f, \nabla f) = \begin{cases} (f, \nabla f), & f \leq f_t \\ (f_t, 0), & f > f_t \end{cases}, \]
where \(f_t : = 10*(|f_0|+1) \).
This is useful and even mandatory when \(f \) has singularities, so that if the linesearch steps into a singularity the very high function and gradient values do not pollute the solution process, since they get rejected by the linesearch anyway but might be used in computations.
Definition at line 430 of file linesearch.hpp.
References FEAT::Solver::Linesearch< Functional_, Filter_ >::_trim_threshold.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), and FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern().
Member Data Documentation
_alpha_0
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_alpha_0 protected inherited
Initial line search parameter.
Definition at line 69 of file linesearch.hpp.
Referenced by FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::SecantLinesearch(), FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_startup(), FEAT::Solver::Linesearch< Functional_, Filter_ >::reset(), and FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::reset().
_alpha_min
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_alpha_min protected inherited
Line search parameter.
Definition at line 71 of file linesearch.hpp.
Referenced by FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::FixedStepLinesearch(), FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::get_summary(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::reset().
_comm
const Dist::Comm* FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_comm protected inherited
Communicator of the solver.
Definition at line 209 of file iterative.hpp.
_def_cur
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_cur protected inherited
current defect
Definition at line 239 of file iterative.hpp.
_def_init
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_init protected inherited
initial defect
Definition at line 237 of file iterative.hpp.
_def_prev
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_def_prev protected inherited
previous iteration defect
Definition at line 241 of file iterative.hpp.
_delta_0
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_delta_0 protected inherited
Initial <vec_dir, vec_grad>
Definition at line 73 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_startup(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::reset().
_dir_scaling
template<typename Functional_ , typename Filter_ > bool FEAT::Solver::Linesearch< Functional_, Filter_ >::_dir_scaling protected inherited
Use the search direction norm for step scaling? This can be important if the search direction was preconditioned (e.g. the Newton direction)
Definition at line 87 of file linesearch.hpp.
Referenced by FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::set_dir_scaling().
_div_abs
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_div_abs protected inherited
absolute divergence parameter
Definition at line 223 of file iterative.hpp.
_div_rel
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_div_rel protected inherited
relative divergence parameter
Definition at line 221 of file iterative.hpp.
_filter
template<typename Functional_ , typename Filter_ > Filter_& FEAT::Solver::Linesearch< Functional_, Filter_ >::_filter protected inherited
The filter to be applied to the functional's gradient.
Definition at line 50 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::correct(), FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::correct(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::correct(), and FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::correct().
_force_def_norm_calc
bool FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_force_def_norm_calc protected inherited
whether skipping of defect computation is allowed or not
Definition at line 249 of file iterative.hpp.
_functional
template<typename Functional_ , typename Filter_ > Functional_& FEAT::Solver::Linesearch< Functional_, Filter_ >::_functional protected inherited
The (nonlinear) functional.
Definition at line 48 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::correct(), FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::correct(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::correct(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::correct(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::get_summary().
_fval_0
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_0 protected inherited
Initial functional value.
Definition at line 64 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_startup(), FEAT::Solver::Linesearch< Functional_, Filter_ >::get_summary(), FEAT::Solver::Linesearch< Functional_, Filter_ >::reset(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::set_initial_fval().
_fval_min
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_fval_min protected inherited
Functional functional value.
Definition at line 62 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::correct(), FEAT::Solver::Linesearch< Functional_, Filter_ >::get_final_fval(), FEAT::Solver::Linesearch< Functional_, Filter_ >::get_summary(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::reset().
_iter_digits
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_iter_digits protected inherited
iteration count digits for plotting
Definition at line 243 of file iterative.hpp.
_max_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_max_iter protected inherited
maximum number of iterations
Definition at line 229 of file iterative.hpp.
_min_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_min_iter protected inherited
minimum number of iterations
Definition at line 227 of file iterative.hpp.
_min_stag_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_min_stag_iter protected inherited
minimum number of stagnation iterations
Definition at line 233 of file iterative.hpp.
_norm_dir
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_norm_dir protected inherited
The 2-norm of the search direction.
Definition at line 75 of file linesearch.hpp.
Referenced by FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::apply(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::correct(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::get_rel_update(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::reset().
_norm_sol
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_norm_sol protected inherited
The 2-norm of the iterate.
Definition at line 77 of file linesearch.hpp.
Referenced by FEAT::Solver::Linesearch< Functional_, Filter_ >::reset().
_num_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_iter protected inherited
number of performed iterations
Definition at line 231 of file iterative.hpp.
_num_stag_iter
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_num_stag_iter protected inherited
number of consecutive stagnated iterations
Definition at line 235 of file iterative.hpp.
_plot_interval
Index FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_interval protected inherited
plot output interval
Definition at line 247 of file iterative.hpp.
_plot_mode
PlotMode FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_mode protected inherited
whether to plot something
Definition at line 245 of file iterative.hpp.
_plot_name
String FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_plot_name protected inherited
name of the solver in plots
Definition at line 211 of file iterative.hpp.
_secant_step
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_secant_step protected
Default step for calculating the "other" secant point in the initial step. Crucial.
Definition at line 48 of file secant_linesearch.hpp.
Referenced by FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::SecantLinesearch(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::reset(), and FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::set_secant_step().
_stag_rate
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_stag_rate protected inherited
stagnation rate
Definition at line 225 of file iterative.hpp.
_status
Status FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_status protected inherited
current status of the solver
Definition at line 213 of file iterative.hpp.
_tol_abs
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_tol_abs protected inherited
absolute tolerance parameter
Definition at line 217 of file iterative.hpp.
_tol_abs_low
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_tol_abs_low protected inherited
absolute low tolerance parameter
Definition at line 219 of file iterative.hpp.
_tol_curvature
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_tol_curvature protected inherited
Tolerance for sufficient decrease in the norm of the gradient (Wolfe conditions)
Definition at line 80 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::set_tol_curvature().
_tol_decrease
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_tol_decrease protected inherited
Tolerance for sufficient decrease in the functional value (Wolfe conditions)
Definition at line 82 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::set_tol_decrease().
_tol_rel
DataType FEAT::Solver::IterativeSolver< Functional_::VectorTypeR >::_tol_rel protected inherited
relative tolerance parameter
Definition at line 215 of file iterative.hpp.
_tol_step
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_tol_step protected inherited
Tolerance for the update step.
Definition at line 84 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::set_tol_step().
_trim_threshold
template<typename Functional_ , typename Filter_ > DataType FEAT::Solver::Linesearch< Functional_, Filter_ >::_trim_threshold protected inherited
Threshold for trimming function value and gradient.
Definition at line 66 of file linesearch.hpp.
Referenced by FEAT::Solver::Linesearch< Functional_, Filter_ >::reset(), FEAT::Solver::Linesearch< Functional_, Filter_ >::set_initial_fval(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::trim_func_grad().
_vec_grad
template<typename Functional_ , typename Filter_ > VectorType FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_grad protected inherited
Gradient vector.
Definition at line 53 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::FixedStepLinesearch< Functional_, Filter_ >::correct(), FEAT::Solver::Linesearch< Functional_, Filter_ >::done_symbolic(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::init_symbolic().
_vec_initial_sol
template<typename Functional_ , typename Filter_ > VectorType FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_initial_sol protected inherited
Initial solution.
Definition at line 55 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::done_symbolic(), FEAT::Solver::Linesearch< Functional_, Filter_ >::get_initial_sol(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::init_symbolic().
_vec_pn
template<typename Functional_ , typename Filter_ > VectorType FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_pn protected inherited
descend direction vector, normalized for better numerical stability
Definition at line 59 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::done_symbolic(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::init_symbolic().
_vec_tmp
template<typename Functional_ , typename Filter_ > VectorType FEAT::Solver::Linesearch< Functional_, Filter_ >::_vec_tmp protected inherited
temporary vector
Definition at line 57 of file linesearch.hpp.
Referenced by FEAT::Solver::MQCLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::NewtonRaphsonLinesearch< Functional_, Filter_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::done_symbolic(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::init_symbolic().
iterates
template<typename Functional_ , typename Filter_ > std::deque<VectorType>* FEAT::Solver::Linesearch< Functional_, Filter_ >::iterates inherited
For debugging purposes, it is possible to save all iterates to this.
Definition at line 91 of file linesearch.hpp.
Referenced by FEAT::Solver::Linesearch< Functional_, Filter_ >::Linesearch(), FEAT::Solver::Linesearch< Functional_, Filter_ >::~Linesearch(), and FEAT::Solver::Linesearch< Functional_, Filter_ >::reset().
secant_step_default
template<typename Functional_ , typename Filter_ > constexpr DataType FEAT::Solver::SecantLinesearch< Functional_, Filter_ >::secant_step_default = DataType(1e-2) static constexpr
Default initial step length.
Definition at line 44 of file secant_linesearch.hpp.
The documentation for this class was generated from the following file:
kernel/solver/secant_linesearch.hpp