FEAT: FEAT::Assembly::TraceAssembler< Trafo_ > Class Template Reference
FEAT::Assembly::TraceAssembler< Trafo_ > Class Template Reference
Assembler for operators/functionals on boundaries and other sub-dimensional mesh parts.
#include <trace_assembler.hpp>
Public Types
typedef TrafoType::MeshType MeshType
typedef TrafoType::ShapeType ShapeType
typedef Trafo_ TrafoType
Public Member Functions
TraceAssembler (const TrafoType &trafo)
Constructor.
void add_facet (Index ifacet)
Adds a single facet to the assembler.
void add_mesh_part (const Geometry::MeshPart< MeshType > &mesh_part)
Adds all facets of a mesh part to the assembler.
template<typename DataType_ , typename IndexType_ , typename Space_ , typename CubatureFactory_ >
DataType_ assemble_discrete_integral (const LAFEM::DenseVector< DataType_, IndexType_ > &vector, const Space_ &space, const CubatureFactory_ &cubature_factory)
Assembles the surface integral of a discrete function.
template<typename DataType_ , typename IndexType_ , typename Space_ >
DataType_ assemble_discrete_integral (const LAFEM::DenseVector< DataType_, IndexType_ > &vector, const Space_ &space, const String &cubature_name)
Assembles the surface integral of a discrete function.
template<typename DataType_ , typename IndexType_ , typename Space_ , typename CubatureFactory_ , int dim_>
Tiny::Vector< DataType_, dim_ > assemble_discrete_integral (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > &vector, const Space_ &space, const CubatureFactory_ &cubature_factory)
Assembles the surface integral of a discrete function.
template<typename DataType_ , typename IndexType_ , typename Space_ , int dim_>
Tiny::Vector< DataType_, dim_ > assemble_discrete_integral (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > &vector, const Space_ &space, const String &cubature_name)
Assembles the surface integral of a discrete function.
template<typename Accum_ , typename DataType_ , typename IndexType_ , int dim_, typename SpaceV_ , typename SpaceP_ , typename CubatureFactory_ >
void assemble_flow_accum (Accum_ &accum, const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > &vector_v, const LAFEM::DenseVector< DataType_, IndexType_ > &vector_p, const SpaceV_ &space_v, const SpaceP_ &space_p, const CubatureFactory_ &cubature_factory)
Assembles a flow accumulator.
template<typename Accum_ , typename DataType_ , typename IndexType_ , int dim_, typename SpaceV_ , typename SpaceP_ >
void assemble_flow_accum (Accum_ &accum, const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > &vector_v, const LAFEM::DenseVector< DataType_, IndexType_ > &vector_p, const SpaceV_ &space_v, const SpaceP_ &space_p, const String &cubature_name)
Assembles a flow accumulator.
template<typename Vector_ , typename Functional_ , typename CubatureFactory_ , typename Space_ >
void assemble_functional_vector (Vector_ &vector, const Functional_ &functional, const Space_ &space, const CubatureFactory_ &cubature_factory, typename Vector_::DataType alpha=typename Vector_::DataType(1)) const
Assembles a linear functional into a vector.
template<typename Vector_ , typename Functional_ , typename Space_ >
void assemble_functional_vector (Vector_ &vector, const Functional_ &functional, const Space_ &space, const String &cubature_name, typename Vector_::DataType alpha=typename Vector_::DataType(1)) const
Assembles a linear functional into a vector.
template<typename Matrix_ , typename Space_ , typename CubatureFactory_ >
void assemble_jump_operator_matrix (Matrix_ &matrix, const Space_ &space, const CubatureFactory_ &cubature_factory, typename Matrix_::DataType alpha=typename Matrix_::DataType(1)) const
Assembles the jump operator onto a matrix.
template<typename Matrix_ , typename Space_ >
void assemble_jump_operator_matrix (Matrix_ &matrix, const Space_ &space, const String &cubature_name, typename Matrix_::DataType alpha=typename Matrix_::DataType(1)) const
Assembles the jump operator onto a matrix.
template<typename Matrix_ , typename Space_ , typename CubatureFactory_ >
void assemble_jump_stabil_operator_matrix (Matrix_ &matrix, const Space_ &space, const CubatureFactory_ &cubature_factory, typename Matrix_::DataType gamma=typename Matrix_::DataType(1), typename Matrix_::DataType jacdet_scal=typename Matrix_::DataType(2), typename Matrix_::DataType jacdet_expo=typename Matrix_::DataType(2)) const
Assembles the jump-stabilization operator onto a matrix.
template<typename Matrix_ , typename Space_ >
void assemble_jump_stabil_operator_matrix (Matrix_ &matrix, const Space_ &space, const String &cubature_name, typename Matrix_::DataType gamma=typename Matrix_::DataType(1), typename Matrix_::DataType jacdet_scal=typename Matrix_::DataType(2), typename Matrix_::DataType jacdet_expo=typename Matrix_::DataType(2)) const
Assembles the jump-stabilization operator onto a matrix.
template<typename Matrix_ , typename Operator_ , typename Space_ , typename CubatureFactory_ >
void assemble_operator_matrix1 (Matrix_ &matrix, Operator_ &operat, const Space_ &space, const CubatureFactory_ &cubature_factory, typename Matrix_::DataType alpha=typename Matrix_::DataType(1)) const
Assembles a bilinear operator into a matrix.
template<typename Matrix_ , typename Operator_ , typename Space_ >
void assemble_operator_matrix1 (Matrix_ &matrix, Operator_ &operat, const Space_ &space, const String &cubature_name, typename Matrix_::DataType alpha=typename Matrix_::DataType(1)) const
Assembles a bilinear operator into a matrix.
template<typename Matrix_ , typename Operator_ , typename TestSpace_ , typename TrialSpace_ , typename CubatureFactory_ >
void assemble_operator_matrix2 (Matrix_ &matrix, Operator_ &operat, const TestSpace_ &test_space, const TrialSpace_ &trial_space, const CubatureFactory_ &cubature_factory, typename Matrix_::DataType alpha=typename Matrix_::DataType(1)) const
Assembles a bilinear operator into a matrix.
template<typename Matrix_ , typename Operator_ , typename TestSpace_ , typename TrialSpace_ >
void assemble_operator_matrix2 (Matrix_ &matrix, Operator_ &operat, const TestSpace_ &test_space, const TrialSpace_ &trial_space, const String &cubature_name, typename Matrix_::DataType alpha=typename Matrix_::DataType(1)) const
Assembles a bilinear operator into a matrix.
void clear ()
Clears the assembler.
void compile ()
Compiles the assembler for all facets that have been added manually.
void compile_all_facets (bool inner, bool outer)
Compiles the assembler for all inner and/our outer facets of the underlying mesh.
Static Public Attributes
static constexpr int facet_dim = shape_dim-1
static constexpr int shape_dim = ShapeType::dimension
Protected Member Functions
bool _find_local_facet (Index face, Index cell, int &facet, int &ori)
Helper function: tries to find the local facet index for a given facet/cell pair.
Protected Attributes
std::vector< int > _cell_facet
std::vector< Index > _cells
the indices of all cells and facets to loop over during assembly
std::vector< int > _facet_mask
the facet masks, local cell facet indices and facet orientation codes
std::vector< int > _facet_ori
std::vector< Index > _facets
const TrafoType & _trafo
a reference to the trafo
Detailed Description
template<typename Trafo_>
class FEAT::Assembly::TraceAssembler< Trafo_ >
Assembler for operators/functionals on boundaries and other sub-dimensional mesh parts.
This class can be used to assemble operators, functionals and various other quantities on (a part of) the boundary of a mesh or any other set of mesh facets.
After you have constructed the trace assembler object, you still have to tell the assembler on which set of facets the assembly should take place before you can actually assemble anything. There are 2 ways to do this:
You can tell the assembler to assemble on all inner and/or outer facets of the mesh by calling the compile_all_facets() function.
You can add individual facets or whole mesh parts to the assembler by calling the add_facet() and add_mesh_part() functions. Afterwards, you need to compile the assembler by calling the compile() function.
Template Parameters
Trafo_ The transformation on whose underlying mesh the assembly should take place
Author
Peter Zajac
Definition at line 138 of file trace_assembler.hpp.
Member Typedef Documentation
MeshType
template<typename Trafo_ > typedef TrafoType::MeshType FEAT::Assembly::TraceAssembler< Trafo_ >::MeshType
Definition at line 142 of file trace_assembler.hpp.
ShapeType
template<typename Trafo_ > typedef TrafoType::ShapeType FEAT::Assembly::TraceAssembler< Trafo_ >::ShapeType
Definition at line 143 of file trace_assembler.hpp.
TrafoType
template<typename Trafo_ > typedef Trafo_ FEAT::Assembly::TraceAssembler< Trafo_ >::TrafoType
Definition at line 141 of file trace_assembler.hpp.
Constructor & Destructor Documentation
TraceAssembler()
template<typename Trafo_ > FEAT::Assembly::TraceAssembler< Trafo_ >::TraceAssembler (const TrafoType & trafo) inline explicit
Constructor.
Parameters
[in] trafo A resident reference to the trafo on which to assemble
Definition at line 163 of file trace_assembler.hpp.
Member Function Documentation
_find_local_facet()
template<typename Trafo_ > bool FEAT::Assembly::TraceAssembler< Trafo_ >::_find_local_facet (Index face, Index cell, int & facet, int & ori) inline protected
Helper function: tries to find the local facet index for a given facet/cell pair.
Parameters
[in] face The global index of the facet that is adjacent to cell
[in] cell The global index of the cell/element that is adjacent to face
[out] facet The local facet index of face with respect to cell
[out] ori The local facet orientation code of face with respect to the corresponding reference element facet of cell
Returns
true, if the local facet was identified, or false, if face does not seem to be a facet of cell
Definition at line 2137 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_trafo.
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::compile(), and FEAT::Assembly::TraceAssembler< Trafo_ >::compile_all_facets().
add_facet()
template<typename Trafo_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::add_facet (Index ifacet) inline
Adds a single facet to the assembler.
Parameters
[in] facet The index of the facet to be added to the assembler.
Definition at line 188 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_facet_mask, and ASSERTM.
add_mesh_part()
template<typename Trafo_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::add_mesh_part (const Geometry::MeshPart< MeshType > & mesh_part) inline
Adds all facets of a mesh part to the assembler.
Parameters
[in] mesh_part The mesh part whose facets are to be added.
Definition at line 200 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_facet_mask.
assemble_discrete_integral() [1/4]
template<typename Trafo_ > template<typename DataType_ , typename IndexType_ , typename Space_ , typename CubatureFactory_ > DataType_ FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral (const LAFEM::DenseVector< DataType_, IndexType_ > & vector, const Space_ & space, const CubatureFactory_ & cubature_factory) inline
Assembles the surface integral of a discrete function.
Parameters
[in] vector A transient reference to the vector that represents the function to be integrated
[in] space A transient reference to the finite element space
[in] cubature_factory The cubature factory
Returns
The surface integral of the discrete function
Definition at line 1236 of file trace_assembler.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
assemble_discrete_integral() [2/4]
template<typename Trafo_ > template<typename DataType_ , typename IndexType_ , typename Space_ > DataType_ FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral (const LAFEM::DenseVector< DataType_, IndexType_ > & vector, const Space_ & space, const String & cubature_name) inline
Assembles the surface integral of a discrete function.
Parameters
[in] vector A transient reference to the vector that represents the function to be integrated
[in] space A transient reference to the finite element space
[in] cubature_nane The name of the cubature rule to be used for integration
Returns
The surface integral of the discrete function
Definition at line 1212 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral().
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral().
assemble_discrete_integral() [3/4]
template<typename Trafo_ > template<typename DataType_ , typename IndexType_ , typename Space_ , typename CubatureFactory_ , int dim_> Tiny::Vector< DataType_, dim_ > FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > & vector, const Space_ & space, const CubatureFactory_ & cubature_factory) inline
Assembles the surface integral of a discrete function.
Parameters
[in] vector A transient reference to the vector that represents the function to be integrated
[in] space A transient reference to the finite element space
[in] cubature_factory The cubature factory
Returns
The surface integral of the discrete function
Definition at line 1422 of file trace_assembler.hpp.
References FEAT::Tiny::Vector< T_, n_, s_ >::axpy(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), and XASSERTM.
assemble_discrete_integral() [4/4]
template<typename Trafo_ > template<typename DataType_ , typename IndexType_ , typename Space_ , int dim_> Tiny::Vector< DataType_, dim_ > FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral (const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > & vector, const Space_ & space, const String & cubature_name) inline
Assembles the surface integral of a discrete function.
Parameters
[in] vector A transient reference to the vector that represents the function to be integrated
[in] space A transient reference to the finite element space
[in] cubature_nane The name of the cubature rule to be used for integration
Returns
The surface integral of the discrete function
Definition at line 1398 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_discrete_integral().
assemble_flow_accum() [1/2]
template<typename Trafo_ > template<typename Accum_ , typename DataType_ , typename IndexType_ , int dim_, typename SpaceV_ , typename SpaceP_ , typename CubatureFactory_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum (Accum_ & accum, const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > & vector_v, const LAFEM::DenseVector< DataType_, IndexType_ > & vector_p, const SpaceV_ & space_v, const SpaceP_ & space_p, const CubatureFactory_ & cubature_factory) inline
Assembles a flow accumulator.
This function assembles a so-called accumulator on a sub-dimensional mesh region, which can be used to assemble body forces on a boundary.
Attention
This assembly function is somewhat provisional - use at own risk!
The accumulator that is assembled by this function has to provide an overloaded "operator()" with the following function parameters:
cubature weight (scalar)
mapped image point (Tiny::Vector)
jacobi matrix (Tiny::Matrix)
velocity value (Tiny::Vector)
velocity gradient (Tiny::Matrix)
pressure value (scalar)
Parameters
[in,out] accum The accumulator to be assembled. The "operator()" of this object is called for each cubature point on each facet.
[in] vector_v The velocity vector.
[in] vector_p The pressure vector.
[in] space_v The velocity space.
[in] space_p The pressure space.
[in] cubature_factory The cubature factory that is to be used for integration.
Definition at line 1011 of file trace_assembler.hpp.
References FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::add_outer_product(), FEAT::Tiny::Vector< T_, n_, s_ >::axpy(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::grad, FEAT::img_point, FEAT::jac_det, FEAT::jac_mat, FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::value, and XASSERTM.
assemble_flow_accum() [2/2]
template<typename Trafo_ > template<typename Accum_ , typename DataType_ , typename IndexType_ , int dim_, typename SpaceV_ , typename SpaceP_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum (Accum_ & accum, const LAFEM::DenseVectorBlocked< DataType_, IndexType_, dim_ > & vector_v, const LAFEM::DenseVector< DataType_, IndexType_ > & vector_p, const SpaceV_ & space_v, const SpaceP_ & space_p, const String & cubature_name) inline
Assembles a flow accumulator.
This function assembles a so-called accumulator on a sub-dimensional mesh region, which can be used to assemble body forces on a boundary.
Attention
This assembly function is somewhat provisional - use at own risk!
The accumulator that is assembled by this function has to provide an overloaded "operator()" with the following function parameters:
cubature weight (scalar)
mapped image point (Tiny::Vector)
jacobi matrix (Tiny::Matrix)
velocity value (Tiny::Vector)
velocity gradient (Tiny::Matrix)
pressure value (scalar)
Parameters
[in,out] accum The accumulator to be assembled. The "operator()" of this object is called for each cubature point on each facet.
[in] vector_v The velocity vector.
[in] vector_p The pressure vector.
[in] space_v The velocity space.
[in] space_p The pressure space.
[in] cubature_name The name of the cubature rule that is to be used for integration.
Definition at line 954 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum().
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum().
assemble_functional_vector() [1/2]
template<typename Trafo_ > template<typename Vector_ , typename Functional_ , typename CubatureFactory_ , typename Space_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_functional_vector (Vector_ & vector, const Functional_ & functional, const Space_ & space, const CubatureFactory_ & cubature_factory, typename Vector_::DataType alpha = typename Vector_::DataType(1)) const inline
Assembles a linear functional into a vector.
Note
The assembler automatically computes the normal vectors in the cubature points of each facet (even if the functional did not ask for this), which can be queried by tau.normal during the set_point() function call of the operator's evaluator.
Parameters
[in,out] vector A transient reference to the vector that is to be assembled.
[in] functional A transient reference to the linear functional implementing the LinearFunctional interface to be assembled.
[in] space A transient reference to the finite-element (test) space to be used.
[in] cubature_factory A transient reference to the cubature factory to be used for integration.
[in] alpha The scaling factor for the linear functional.
Definition at line 737 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_cells, FEAT::Tiny::axpy(), FEAT::Shape::ReferenceCell< Shape_ >::facet_orientation(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::Tiny::orthogonal(), and XASSERTM.
assemble_functional_vector() [2/2]
template<typename Trafo_ > template<typename Vector_ , typename Functional_ , typename Space_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_functional_vector (Vector_ & vector, const Functional_ & functional, const Space_ & space, const String & cubature_name, typename Vector_::DataType alpha = typename Vector_::DataType(1)) const inline
Assembles a linear functional into a vector.
Note
The assembler automatically computes the normal vectors in the cubature points of each facet (even if the functional did not ask for this), which can be queried by tau.normal during the set_point() function call of the operator's evaluator.
Parameters
[in,out] vector A transient reference to the vector that is to be assembled.
[in] functional A transient reference to the linear functional implementing the LinearFunctional interface to be assembled.
[in] space A transient reference to the finite-element (test) space to be used.
[in] cubature_name The name of the cubature rule to be used for integration.
[in] alpha The scaling factor for the linear functional.
Definition at line 698 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_functional_vector().
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_functional_vector().
assemble_jump_operator_matrix() [1/2]
template<typename Trafo_ > template<typename Matrix_ , typename Space_ , typename CubatureFactory_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_operator_matrix (Matrix_ & matrix, const Space_ & space, const CubatureFactory_ & cubature_factory, typename Matrix_::DataType alpha = typename Matrix_::DataType(1)) const inline
Assembles the jump operator onto a matrix.
This function assembles the jump operator:
\[J(\varphi,\psi) = \alpha \sum_E \int_E [\varphi]\cdot[\psi]\]
Attention
The matrix must have an extended stencil, which must have been assembled by calling Assembly::SymbolicAssembler::assemble_matrix_ext_facet1() !
Parameters
[in,out] matrix The matrix that is to be assembled.
[in] space The finite element space to be used.
[in] cubature_factory The cubature rule for integration. Note that this is a cubature rule on the facets.
[in] alpha The scaling factor alpha for the jump operator.
Definition at line 1913 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_cells, FEAT::Tiny::add_id(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::value, and XASSERTM.
assemble_jump_operator_matrix() [2/2]
template<typename Trafo_ > template<typename Matrix_ , typename Space_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_operator_matrix (Matrix_ & matrix, const Space_ & space, const String & cubature_name, typename Matrix_::DataType alpha = typename Matrix_::DataType(1)) const inline
Assembles the jump operator onto a matrix.
This function assembles the jump operator:
\[J(\varphi,\psi) = \alpha \sum_E \int_E [\varphi]\cdot[\psi]\]
Attention
The matrix must have an extended stencil, which must have been assembled by calling Assembly::SymbolicAssembler::assemble_matrix_ext_facet1() !
Parameters
[in,out] matrix The matrix that is to be assembled.
[in] space The finite element space to be used.
[in] cubature_name The cubature rule for integration. Note that this is a cubature rule on the facets.
[in] alpha The scaling factor alpha for the jump operator.
Definition at line 1877 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_operator_matrix().
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_operator_matrix().
assemble_jump_stabil_operator_matrix() [1/2]
template<typename Trafo_ > template<typename Matrix_ , typename Space_ , typename CubatureFactory_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_stabil_operator_matrix (Matrix_ & matrix, const Space_ & space, const CubatureFactory_ & cubature_factory, typename Matrix_::DataType gamma = typename Matrix_::DataType(1), typename Matrix_::DataType jacdet_scal = typename Matrix_::DataType(2), typename Matrix_::DataType jacdet_expo = typename Matrix_::DataType(2)) const inline
Assembles the jump-stabilization operator onto a matrix.
This function assembles the jump stabilization operator:
\[J(\varphi,\psi) = \gamma \sum_E (s\cdot J_E)^{p} \int_E [\nabla \varphi]\cdot[\nabla\psi]\]
Attention
The matrix must have an extended stencil, which must have been assembled by calling Assembly::SymbolicAssembler::assemble_matrix_ext_facet1() !
Parameters
[in,out] matrix The matrix that is to be assembled.
[in] space The finite element space to be used.
[in] cubature_factory The cubature for integration. Note that this is a cubature rule on the facets.
[in] gamma The scaling factor gamma for the jump stabilization operator.
[in] jacdet_scal The scaling factor s for the Jacobian determinant factor.
[in] jacdet_expo The exponent p for the Jacobian determinant factor.
Definition at line 1645 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_cells, FEAT::Tiny::add_id(), FEAT::Tiny::dot(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::grad, FEAT::Math::pow(), XASSERT, and XASSERTM.
assemble_jump_stabil_operator_matrix() [2/2]
template<typename Trafo_ > template<typename Matrix_ , typename Space_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_stabil_operator_matrix (Matrix_ & matrix, const Space_ & space, const String & cubature_name, typename Matrix_::DataType gamma = typename Matrix_::DataType(1), typename Matrix_::DataType jacdet_scal = typename Matrix_::DataType(2), typename Matrix_::DataType jacdet_expo = typename Matrix_::DataType(2)) const inline
Assembles the jump-stabilization operator onto a matrix.
This function assembles the jump stabilization operator:
\[J(\varphi,\psi) = \gamma \sum_E (s\cdot J_E)^{p} \int_E [\nabla \varphi]\cdot[\nabla\psi]\]
Attention
The matrix must have an extended stencil, which must have been assembled by calling Assembly::SymbolicAssembler::assemble_matrix_ext_facet1() !
Parameters
[in,out] matrix The matrix that is to be assembled.
[in] space The finite element space to be used.
[in] cubature_name The cubature for integration. Note that this is a cubature rule on the facets.
[in] gamma The scaling factor gamma for the jump stabilization operator.
[in] jacdet_scal The scaling factor s for the Jacobian determinant factor.
[in] jacdet_expo The exponent p for the Jacobian determinant factor.
Definition at line 1601 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_stabil_operator_matrix().
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_stabil_operator_matrix().
assemble_operator_matrix1() [1/2]
template<typename Trafo_ > template<typename Matrix_ , typename Operator_ , typename Space_ , typename CubatureFactory_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix1 (Matrix_ & matrix, Operator_ & operat, const Space_ & space, const CubatureFactory_ & cubature_factory, typename Matrix_::DataType alpha = typename Matrix_::DataType(1)) const inline
Assembles a bilinear operator into a matrix.
This function is the version for identical test- and trial-spaces.
Note
The assembler automatically computes the normal vectors in the cubature points of each facet (even if the operator did not ask for this), which can be queried by tau.normal during the set_point() function call of the operator's evaluator.
Parameters
[in,out] matrix The transient matrix that is to be assembled.
[in] operat A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] space A transient reference to the finite-element test-/trial-space to be used.
[in] cubature_factory A transient reference to the cubature factory to be used for integration.
[in] alpha The scaling factor for the bilinear operator.
Definition at line 430 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2().
assemble_operator_matrix1() [2/2]
template<typename Trafo_ > template<typename Matrix_ , typename Operator_ , typename Space_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix1 (Matrix_ & matrix, Operator_ & operat, const Space_ & space, const String & cubature_name, typename Matrix_::DataType alpha = typename Matrix_::DataType(1)) const inline
Assembles a bilinear operator into a matrix.
This function is the version for identical test- and trial-spaces.
Note
The assembler automatically computes the normal vectors in the cubature points of each facet (even if the operator did not ask for this), which can be queried by tau.normal during the set_point() function call of the operator's evaluator.
Parameters
[in,out] matrix The transient matrix that is to be assembled.
[in] operat A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] space A transient reference to the finite-element test-/trial-space to be used.
[in] cubature_name The name of to the cubature rule to be used for integration.
[in] alpha The scaling factor for the bilinear operator.
Definition at line 343 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2().
assemble_operator_matrix2() [1/2]
template<typename Trafo_ > template<typename Matrix_ , typename Operator_ , typename TestSpace_ , typename TrialSpace_ , typename CubatureFactory_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2 (Matrix_ & matrix, Operator_ & operat, const TestSpace_ & test_space, const TrialSpace_ & trial_space, const CubatureFactory_ & cubature_factory, typename Matrix_::DataType alpha = typename Matrix_::DataType(1)) const inline
Assembles a bilinear operator into a matrix.
This function is the version for different test- and trial-spaces.
Note
The assembler automatically computes the normal vectors in the cubature points of each facet (even if the operator did not ask for this), which can be queried by tau.normal during the set_point() function call of the operator's evaluator.
Parameters
[in,out] matrix The transient matrix that is to be assembled.
[in] operat A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] test_space A transient reference to the finite-element test-space to be used.
[in] trial_space A transient reference to the finite-element trial-space to be used.
[in] cubature_factory A transient reference to the cubature factory to be used for integration.
[in] alpha The scaling factor for the bilinear operator.
Definition at line 475 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_cells, FEAT::Tiny::axpy(), FEAT::Shape::ReferenceCell< Shape_ >::facet_orientation(), FEAT::Tiny::Vector< T_, n_, s_ >::format(), FEAT::Tiny::Matrix< T_, m_, n_, sm_, sn_ >::format(), FEAT::jac_det, FEAT::jac_mat, FEAT::Tiny::orthogonal(), and XASSERTM.
assemble_operator_matrix2() [2/2]
template<typename Trafo_ > template<typename Matrix_ , typename Operator_ , typename TestSpace_ , typename TrialSpace_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2 (Matrix_ & matrix, Operator_ & operat, const TestSpace_ & test_space, const TrialSpace_ & trial_space, const String & cubature_name, typename Matrix_::DataType alpha = typename Matrix_::DataType(1)) const inline
Assembles a bilinear operator into a matrix.
This function is the version for different test- and trial-spaces.
Note
The assembler automatically computes the normal vectors in the cubature points of each facet (even if the operator did not ask for this), which can be queried by tau.normal during the set_point() function call of the operator's evaluator.
Parameters
[in,out] matrix The transient matrix that is to be assembled.
[in] operat A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] test_space A transient reference to the finite-element test-space to be used.
[in] trial_space A transient reference to the finite-element trial-space to be used.
[in] cubature_name The name of to the cubature rule to be used for integration.
[in] alpha The scaling factor for the bilinear operator.
Definition at line 388 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2().
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix1(), and FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2().
clear()
template<typename Trafo_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::clear () inline
Clears the assembler.
Definition at line 172 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_cells.
compile()
template<typename Trafo_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::compile () inline
Compiles the assembler for all facets that have been added manually.
This function compiles the assembler for all facets that have been added manually by previous calls of the add_facet or add_mesh_part functions.
Note
If you want to compile the assembler for all facets of the trafo's underlying mesh, consider using the compile_all_facets() function instead.
Definition at line 217 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_cells, FEAT::Assembly::TraceAssembler< Trafo_ >::_facet_mask, FEAT::Assembly::TraceAssembler< Trafo_ >::_find_local_facet(), FEAT::Assembly::TraceAssembler< Trafo_ >::_trafo, FEAT::Adjacency::Graph::image_begin(), FEAT::Adjacency::Graph::image_end(), FEAT::Adjacency::injectify_transpose, and XABORTM.
compile_all_facets()
template<typename Trafo_ > void FEAT::Assembly::TraceAssembler< Trafo_ >::compile_all_facets (bool inner, bool outer) inline
Compiles the assembler for all inner and/our outer facets of the underlying mesh.
Parameters
[in] inner Specifies whether the mesh's inner facets are to be added to the assembler or not.
[in] outer Specifies whether the mesh's outer (i.e. boundary) facets are to be added to the assembler or not.
Definition at line 268 of file trace_assembler.hpp.
References FEAT::Assembly::TraceAssembler< Trafo_ >::_cells, FEAT::Assembly::TraceAssembler< Trafo_ >::_facet_mask, FEAT::Assembly::TraceAssembler< Trafo_ >::_find_local_facet(), FEAT::Assembly::TraceAssembler< Trafo_ >::_trafo, FEAT::Adjacency::Graph::degree(), FEAT::Adjacency::Graph::image_begin(), FEAT::Adjacency::Graph::image_end(), FEAT::Adjacency::injectify_transpose, XABORTM, and XASSERT.
Member Data Documentation
_cell_facet
template<typename Trafo_ > std::vector<int> FEAT::Assembly::TraceAssembler< Trafo_ >::_cell_facet protected
Definition at line 152 of file trace_assembler.hpp.
_cells
template<typename Trafo_ > std::vector<Index> FEAT::Assembly::TraceAssembler< Trafo_ >::_cells protected
the indices of all cells and facets to loop over during assembly
Definition at line 154 of file trace_assembler.hpp.
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_functional_vector(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_operator_matrix(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_jump_stabil_operator_matrix(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_operator_matrix2(), FEAT::Assembly::TraceAssembler< Trafo_ >::clear(), FEAT::Assembly::TraceAssembler< Trafo_ >::compile(), and FEAT::Assembly::TraceAssembler< Trafo_ >::compile_all_facets().
_facet_mask
template<typename Trafo_ > std::vector<int> FEAT::Assembly::TraceAssembler< Trafo_ >::_facet_mask protected
the facet masks, local cell facet indices and facet orientation codes
Definition at line 152 of file trace_assembler.hpp.
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::add_facet(), FEAT::Assembly::TraceAssembler< Trafo_ >::add_mesh_part(), FEAT::Assembly::TraceAssembler< Trafo_ >::compile(), and FEAT::Assembly::TraceAssembler< Trafo_ >::compile_all_facets().
_facet_ori
template<typename Trafo_ > std::vector<int> FEAT::Assembly::TraceAssembler< Trafo_ >::_facet_ori protected
Definition at line 152 of file trace_assembler.hpp.
_facets
template<typename Trafo_ > std::vector<Index> FEAT::Assembly::TraceAssembler< Trafo_ >::_facets protected
Definition at line 154 of file trace_assembler.hpp.
_trafo
template<typename Trafo_ > const TrafoType& FEAT::Assembly::TraceAssembler< Trafo_ >::_trafo protected
a reference to the trafo
Definition at line 150 of file trace_assembler.hpp.
Referenced by FEAT::Assembly::TraceAssembler< Trafo_ >::_find_local_facet(), FEAT::Assembly::TraceAssembler< Trafo_ >::compile(), and FEAT::Assembly::TraceAssembler< Trafo_ >::compile_all_facets().
facet_dim
template<typename Trafo_ > constexpr int FEAT::Assembly::TraceAssembler< Trafo_ >::facet_dim = shape_dim-1 static constexpr
Definition at line 146 of file trace_assembler.hpp.
shape_dim
template<typename Trafo_ > constexpr int FEAT::Assembly::TraceAssembler< Trafo_ >::shape_dim = ShapeType::dimension static constexpr
Definition at line 145 of file trace_assembler.hpp.
The documentation for this class was generated from the following file:
kernel/assembly/trace_assembler.hpp