FEAT: FEAT::Global::Filter< LocalFilter_, Mirror_ > Class Template Reference
FEAT::Global::Filter< LocalFilter_, Mirror_ > Class Template Reference
Global Filter wrapper class template.
#include <filter.hpp>
Public Types
template<typename LocalFilter2_ , typename Mirror2_ = Mirror_>
using FilterType = Filter< LocalFilter2_, Mirror2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using FilterTypeByDI = Filter< typename LocalFilter_::template FilterType< DataType2_, IndexType2_ >, typename Mirror_::template MirrorType< DataType2_, IndexType2_ > >
this typedef lets you create a filter with new Datatape and Index types
typedef LocalFilter_ LocalFilterType
typedef Mirror_ MirrorType
typedef Global::Vector< typename LocalFilter_::VectorType, Mirror_ > VectorType
Public Member Functions
template<typename... Args_>
Filter (Args_ &&... args)
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clone (const Filter &other, LAFEM::CloneMode mode=LAFEM::CloneMode::Weak)
Filter clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
template<typename OtherGlobalFilter_ >
void convert (const OtherGlobalFilter_ &other)
void filter_cor (VectorType &vector) const
void filter_def (VectorType &vector) const
void filter_rhs (VectorType &vector) const
void filter_sol (VectorType &vector) const
LocalFilter_ & local ()
const LocalFilter_ & local () const
Static Public Attributes
static constexpr bool is_global = true
static constexpr bool is_local = false
Protected Attributes
LocalFilter_ _filter
Detailed Description
template<typename LocalFilter_, typename Mirror_>
class FEAT::Global::Filter< LocalFilter_, Mirror_ >
Global Filter wrapper class template.
Author
Peter Zajac
Definition at line 22 of file filter.hpp.
Member Typedef Documentation
FilterType
template<typename LocalFilter_ , typename Mirror_ > template<typename LocalFilter2_ , typename Mirror2_ = Mirror_> using FEAT::Global::Filter< LocalFilter_, Mirror_ >::FilterType = Filter<LocalFilter2_, Mirror2_>
Our 'base' class type.
Definition at line 31 of file filter.hpp.
FilterTypeByDI
template<typename LocalFilter_ , typename Mirror_ > template<typename DataType2_ , typename IndexType2_ > using FEAT::Global::Filter< LocalFilter_, Mirror_ >::FilterTypeByDI = Filter<typename LocalFilter_::template FilterType<DataType2_, IndexType2_>, typename Mirror_::template MirrorType<DataType2_, IndexType2_> >
this typedef lets you create a filter with new Datatape and Index types
Definition at line 35 of file filter.hpp.
LocalFilterType
template<typename LocalFilter_ , typename Mirror_ > typedef LocalFilter_ FEAT::Global::Filter< LocalFilter_, Mirror_ >::LocalFilterType
Definition at line 27 of file filter.hpp.
MirrorType
template<typename LocalFilter_ , typename Mirror_ > typedef Mirror_ FEAT::Global::Filter< LocalFilter_, Mirror_ >::MirrorType
Definition at line 26 of file filter.hpp.
VectorType
template<typename LocalFilter_ , typename Mirror_ > typedef Global::Vector<typename LocalFilter_::VectorType, Mirror_> FEAT::Global::Filter< LocalFilter_, Mirror_ >::VectorType
Definition at line 25 of file filter.hpp.
Constructor & Destructor Documentation
Filter()
template<typename LocalFilter_ , typename Mirror_ > template<typename... Args_> FEAT::Global::Filter< LocalFilter_, Mirror_ >::Filter (Args_ &&... args) inline explicit
Definition at line 45 of file filter.hpp.
Member Function Documentation
bytes()
template<typename LocalFilter_ , typename Mirror_ > std::size_t FEAT::Global::Filter< LocalFilter_, Mirror_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 79 of file filter.hpp.
Referenced by FEAT::Control::BlockedUnitFilterSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::bytes(), FEAT::Control::ScalarMixedSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), FEAT::Control::StokesBlockedUnitVeloNonePresSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), FEAT::Control::StokesBlockedSlipUnitVeloNonePresSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), FEAT::Control::StokesBlockedSlipUnitVeloMeanPresSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), and FEAT::Control::StokesBlockedCombinedSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes().
clone() [1/2]
template<typename LocalFilter_ , typename Mirror_ > void FEAT::Global::Filter< LocalFilter_, Mirror_ >::clone (const Filter< LocalFilter_, Mirror_ > & other, LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) inline
Definition at line 71 of file filter.hpp.
clone() [2/2]
template<typename LocalFilter_ , typename Mirror_ > Filter FEAT::Global::Filter< LocalFilter_, Mirror_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Definition at line 66 of file filter.hpp.
convert()
template<typename LocalFilter_ , typename Mirror_ > template<typename OtherGlobalFilter_ > void FEAT::Global::Filter< LocalFilter_, Mirror_ >::convert (const OtherGlobalFilter_ & other) inline
Definition at line 61 of file filter.hpp.
filter_cor()
template<typename LocalFilter_ , typename Mirror_ > void FEAT::Global::Filter< LocalFilter_, Mirror_ >::filter_cor (VectorType & vector) const inline
Definition at line 99 of file filter.hpp.
filter_def()
template<typename LocalFilter_ , typename Mirror_ > void FEAT::Global::Filter< LocalFilter_, Mirror_ >::filter_def (VectorType & vector) const inline
Definition at line 94 of file filter.hpp.
filter_rhs()
template<typename LocalFilter_ , typename Mirror_ > void FEAT::Global::Filter< LocalFilter_, Mirror_ >::filter_rhs (VectorType & vector) const inline
Definition at line 84 of file filter.hpp.
filter_sol()
template<typename LocalFilter_ , typename Mirror_ > void FEAT::Global::Filter< LocalFilter_, Mirror_ >::filter_sol (VectorType & vector) const inline
Definition at line 89 of file filter.hpp.
local() [1/2]
template<typename LocalFilter_ , typename Mirror_ > LocalFilter_ & FEAT::Global::Filter< LocalFilter_, Mirror_ >::local () inline
Definition at line 50 of file filter.hpp.
local() [2/2]
template<typename LocalFilter_ , typename Mirror_ > const LocalFilter_ & FEAT::Global::Filter< LocalFilter_, Mirror_ >::local () const inline
Definition at line 55 of file filter.hpp.
Member Data Documentation
_filter
template<typename LocalFilter_ , typename Mirror_ > LocalFilter_ FEAT::Global::Filter< LocalFilter_, Mirror_ >::_filter protected
Definition at line 41 of file filter.hpp.
is_global
template<typename LocalFilter_ , typename Mirror_ > constexpr bool FEAT::Global::Filter< LocalFilter_, Mirror_ >::is_global = true static constexpr
Definition at line 37 of file filter.hpp.
is_local
template<typename LocalFilter_ , typename Mirror_ > constexpr bool FEAT::Global::Filter< LocalFilter_, Mirror_ >::is_local = false static constexpr
Definition at line 38 of file filter.hpp.
The documentation for this class was generated from the following file:
kernel/global/filter.hpp