FEAT: FEAT::LAFEM::UnitFilter< DT_, IT_ > Class Template Reference
FEAT::LAFEM::UnitFilter< DT_, IT_ > Class Template Reference
Unit Filter class template.
#include <unit_filter.hpp>
Public Types
typedef DT_ DataType
data-type typedef
template<typename DT2_ = DT_, typename IT2_ = IT_>
using FilterType = UnitFilter< DT2_, IT2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using FilterTypeByDI = FilterType< DataType2_, IndexType2_ >
this typedef lets you create a filter with new Datatype and Index types
typedef IT_ IndexType
index-type typedef
typedef DenseVector< DataType, IndexType > VectorType
our supported vector type
Public Member Functions
UnitFilter ()
default constructor
UnitFilter (Index size_in)
Constructor.
UnitFilter (Index size_in, DenseVector< DT_, IT_ > &values, DenseVector< IT_, IT_ > &indices)
Constructor.
UnitFilter (UnitFilter &&other)
move-ctor
virtual ~UnitFilter ()
virtual destructor
void add (IndexType idx, DataType val)
Adds one element to the filter.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Clears the underlying data (namely the SparseVector)
UnitFilter clone (CloneMode clone_mode=CloneMode::Deep) const
Creates a clone of itself.
void clone (const UnitFilter &other, CloneMode clone_mode=CloneMode::Deep)
Clones data from another UnitFilter.
template<typename DT2_ , typename IT2_ >
void convert (const UnitFilter< DT2_, IT2_ > &other)
Converts data from another UnitFilter.
void filter_cor (DenseVector< DT_, IT_ > &vector) const
Applies the filter onto a correction vector.
void filter_def (DenseVector< DT_, IT_ > &vector) const
Applies the filter onto a defect vector.
void filter_mat (MatrixType &matrix) const
Applies the filter onto a system matrix.
void filter_offdiag_col_mat (MatrixType &matrix) const
Filter the non-diagonal entries, column wise.
void filter_offdiag_row_mat (MatrixType &matrix) const
Filter the non-diagonal entries, row wise.
void filter_rhs (DenseVector< DT_, IT_ > &vector) const
Applies the filter onto the right-hand-side vector.
void filter_sol (DenseVector< DT_, IT_ > &vector) const
Applies the filter onto the solution vector.
void filter_weak_matrix_rows (SparseMatrixCSR< DT_, IT_ > &matrix_a, const SparseMatrixCSR< DT_, IT_ > &matrix_m) const
Replaces the rows of the system matrix by scaled rows of another matrix.
IT_ * get_indices ()
const IT_ * get_indices () const
DT_ * get_values ()
const DT_ * get_values () const
UnitFilter & operator= (UnitFilter &&other)
move-assignment operator
void permute (Adjacency::Permutation &perm)
Permutate internal vector according to the given Permutation.
Index size () const
Index used_elements () const
Static Public Attributes
static constexpr bool is_global = false
static constexpr bool is_local = true
Private Attributes
SparseVector< DT_, IT_ > _sv
SparseVector, containing all entries of the unit filter.
Detailed Description
template<typename DT_, typename IT_ = Index>
class FEAT::LAFEM::UnitFilter< DT_, IT_ >
Unit Filter class template.
Author
Peter Zajac
Definition at line 30 of file unit_filter.hpp.
Member Typedef Documentation
DataType
template<typename DT_ , typename IT_ = Index> typedef DT_ FEAT::LAFEM::UnitFilter< DT_, IT_ >::DataType
data-type typedef
Definition at line 34 of file unit_filter.hpp.
FilterType
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::UnitFilter< DT_, IT_ >::FilterType = UnitFilter<DT2_, IT2_>
Our 'base' class type.
Definition at line 43 of file unit_filter.hpp.
FilterTypeByDI
template<typename DT_ , typename IT_ = Index> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::UnitFilter< DT_, IT_ >::FilterTypeByDI = FilterType<DataType2_, IndexType2_>
this typedef lets you create a filter with new Datatype and Index types
Definition at line 47 of file unit_filter.hpp.
IndexType
template<typename DT_ , typename IT_ = Index> typedef IT_ FEAT::LAFEM::UnitFilter< DT_, IT_ >::IndexType
index-type typedef
Definition at line 36 of file unit_filter.hpp.
VectorType
template<typename DT_ , typename IT_ = Index> typedef DenseVector<DataType, IndexType> FEAT::LAFEM::UnitFilter< DT_, IT_ >::VectorType
our supported vector type
Definition at line 39 of file unit_filter.hpp.
Constructor & Destructor Documentation
UnitFilter() [1/4]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter () inline
default constructor
Definition at line 58 of file unit_filter.hpp.
UnitFilter() [2/4]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter (Index size_in) inline explicit
Constructor.
Parameters
[in] size_in The total size of the unit filter.
Definition at line 69 of file unit_filter.hpp.
UnitFilter() [3/4]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter (Index size_in, DenseVector< DT_, IT_ > & values, DenseVector< IT_, IT_ > & indices) inline explicit
Constructor.
Parameters
[in] size_in The size of the created filter.
[in] values DenseVector containing element values
[in] indices DenseVector containing element indices
Definition at line 81 of file unit_filter.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
UnitFilter() [4/4]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter (UnitFilter< DT_, IT_ > && other) inline
move-ctor
Definition at line 88 of file unit_filter.hpp.
~UnitFilter()
template<typename DT_ , typename IT_ = Index> virtual FEAT::LAFEM::UnitFilter< DT_, IT_ >::~UnitFilter () inline virtual
virtual destructor
Definition at line 104 of file unit_filter.hpp.
Member Function Documentation
add()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::add (IndexType idx, DataType val) inline
Adds one element to the filter.
Parameters
[in] idx Index where to add
[in] val Value to add
Definition at line 160 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
Referenced by FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble().
bytes()
template<typename DT_ , typename IT_ = Index> std::size_t FEAT::LAFEM::UnitFilter< DT_, IT_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 136 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
Referenced by FEAT::Control::ScalarUnitFilterSystemLevel< DataType_, IndexType_, ScalarMatrix_ >::bytes().
clear()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::clear () inline
Clears the underlying data (namely the SparseVector)
Definition at line 130 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
clone() [1/2]
template<typename DT_ , typename IT_ = Index> UnitFilter FEAT::LAFEM::UnitFilter< DT_, IT_ >::clone (CloneMode clone_mode = CloneMode::Deep) const inline
Creates a clone of itself.
Definition at line 109 of file unit_filter.hpp.
Referenced by FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres().
clone() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::clone (const UnitFilter< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Deep) inline
Clones data from another UnitFilter.
Definition at line 117 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
convert()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::UnitFilter< DT_, IT_ >::convert (const UnitFilter< DT2_, IT2_ > & other) inline
Converts data from another UnitFilter.
Definition at line 124 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
filter_cor()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_cor (DenseVector< DT_, IT_ > & vector) const inline
Applies the filter onto a correction vector.
Parameters
[in,out] vector A reference to the correction vector to be filtered.
Definition at line 416 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def().
filter_def()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def (DenseVector< DT_, IT_ > & vector) const inline
Applies the filter onto a defect vector.
Parameters
[in,out] vector A reference to the defect vector to be filtered.
Definition at line 402 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
Referenced by FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_cor().
filter_mat()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_mat (MatrixType & matrix) const inline
Applies the filter onto a system matrix.
Parameters
[in,out] matrix A reference to the matrix to be filtered.
Definition at line 218 of file unit_filter.hpp.
filter_offdiag_col_mat()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_offdiag_col_mat (MatrixType & matrix) const inline
Filter the non-diagonal entries, column wise.
Parameters
[in,out] matrix A reference to the matrix to be filtered.
Definition at line 240 of file unit_filter.hpp.
filter_offdiag_row_mat()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_offdiag_row_mat (MatrixType & matrix) const inline
Filter the non-diagonal entries, row wise.
Parameters
[in,out] matrix A reference to the matrix to be filtered.
Definition at line 229 of file unit_filter.hpp.
filter_rhs()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs (DenseVector< DT_, IT_ > & vector) const inline
Applies the filter onto the right-hand-side vector.
Parameters
[in,out] vector A reference to the right-hand-side vector to be filtered.
Definition at line 376 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
Referenced by FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_sol().
filter_sol()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_sol (DenseVector< DT_, IT_ > & vector) const inline
Applies the filter onto the solution vector.
Parameters
[in,out] vector A reference to the solution vector to be filtered.
Definition at line 390 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs().
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector().
filter_weak_matrix_rows()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_weak_matrix_rows (SparseMatrixCSR< DT_, IT_ > & matrix_a, const SparseMatrixCSR< DT_, IT_ > & matrix_m) const inline
Replaces the rows of the system matrix by scaled rows of another matrix.
This function replaces all rows of the system matrix A, whose row index is included in this filter's indices, by the corresponding rows of a given donor matrix M, which is typically a mass matrix, scaled by the values which are stored in this filter. This functionality can be used to implement a weak form of Dirichlet boundary conditions, which is also used to employ mass-conserving fictitious boundary conditions in a Stokes system.
Parameters
[in,out] matrix_a The system matrix whose rows are to be replaced
[in] matrix_m The donor matrix whose rows are to be copied into the system matrix
Definition at line 338 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_values(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERTM.
get_indices() [1/2]
template<typename DT_ , typename IT_ = Index> IT_ * FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_indices () inline
Returns
The index array.
Definition at line 178 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix(), and FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_weak_matrix_rows().
get_indices() [2/2]
template<typename DT_ , typename IT_ = Index> const IT_ * FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_indices () const inline
Returns
The index array.
Definition at line 184 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
get_values() [1/2]
template<typename DT_ , typename IT_ = Index> DT_ * FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_values () inline
Returns
The value array.
Definition at line 190 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
Referenced by FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_weak_matrix_rows().
get_values() [2/2]
template<typename DT_ , typename IT_ = Index> const DT_ * FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_values () const inline
Returns
The value array.
Definition at line 196 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
operator=()
template<typename DT_ , typename IT_ = Index> UnitFilter & FEAT::LAFEM::UnitFilter< DT_, IT_ >::operator= (UnitFilter< DT_, IT_ > && other) inline
move-assignment operator
Definition at line 94 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
permute()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::UnitFilter< DT_, IT_ >::permute (Adjacency::Permutation & perm) inline
Permutate internal vector according to the given Permutation.
Definition at line 202 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
size()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::UnitFilter< DT_, IT_ >::size () const inline
Returns
The total size of the filter.
Definition at line 166 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
Referenced by FEAT::Assembly::UnitFilterAssembler< Mesh_ >::assemble().
used_elements()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::UnitFilter< DT_, IT_ >::used_elements () const inline
Returns
The number of entries in the filter.
Definition at line 172 of file unit_filter.hpp.
References FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix().
Member Data Documentation
_sv
template<typename DT_ , typename IT_ = Index> SparseVector<DT_, IT_> FEAT::LAFEM::UnitFilter< DT_, IT_ >::_sv private
SparseVector, containing all entries of the unit filter.
Definition at line 54 of file unit_filter.hpp.
Referenced by FEAT::LAFEM::UnitFilter< DT_, IT_ >::add(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::bytes(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::clear(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::clone(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::convert(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_weak_matrix_rows(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::get_values(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::operator=(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::permute(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::size(), and FEAT::LAFEM::UnitFilter< DT_, IT_ >::used_elements().
is_global
template<typename DT_ , typename IT_ = Index> constexpr bool FEAT::LAFEM::UnitFilter< DT_, IT_ >::is_global = false static constexpr
Definition at line 49 of file unit_filter.hpp.
is_local
template<typename DT_ , typename IT_ = Index> constexpr bool FEAT::LAFEM::UnitFilter< DT_, IT_ >::is_local = true static constexpr
Definition at line 50 of file unit_filter.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/unit_filter.hpp