FEAT: FEAT::Geometry::MeshDistortion< MeshType_ > Class Template Reference
FEAT::Geometry::MeshDistortion< MeshType_ > Class Template Reference
(Unpartitioned) mesh distortion class template
#include <mesh_distortion.hpp>
Public Types
typedef MeshType_::CoordType CoordType
Public Member Functions
MeshDistortion (MeshType_ &mesh)
Constructor.
MeshDistortion (MeshType_ &mesh, Random::SeedType seed)
Constructor.
void distort_shortest_edge_local (CoordType scale=CoordType(0.1))
Distorts the mesh according to the shortest local edge.
void distort_shortest_edge_uniform (CoordType scale=CoordType(0.1))
Distorts the mesh according to the shortest edge.
void distort_uniform (CoordType rad)
Distorts the mesh uniformly.
Static Public Attributes
static constexpr int shape_dim = MeshType_::shape_dim
static constexpr int world_dim = MeshType_::world_dim
Protected Member Functions
virtual void _calc_boundary_facets ()
determines for each facet whether it is a boundary facet or an inner facet
virtual void _calc_boundary_vertices ()
determines for each vertex whether it is a boundary vertex or an inner vertex
virtual void _calc_shortest_edge ()
determines for each vertex the length of the shortest adjacent edge
virtual void _synchronize ()
synchronizes the distortion over all processes; is overridden in DistributedMeshDistortion
Protected Attributes
std::vector< int > _boundary_facets
vector to story which facet is at the boundary
std::vector< int > _boundary_vertices
vector to store which vertex is at the boundary
MeshType_ & _mesh
the mesh we want to distort
const CoordType _pi_val = Math::pi<CoordType>()
have a guess...
Random _rand
random number generator for random distortion
std::vector< CoordType > _shortest_edge
vector to store the length of the shortest edge belonging to each vertex
Detailed Description
template<typename MeshType_>
class FEAT::Geometry::MeshDistortion< MeshType_ >
(Unpartitioned) mesh distortion class template
Template Parameters
MeshType_ The type of the mesh that is to be distorted, e.g. ConformalMesh
Attention
This class should only be used in serial applications, i.e. on unpartitioned meshes! If you need to distort a partitioned mesh, use the derived DistributedMeshDistortion class template instead!
Author
Chantal Jahner
Definition at line 41 of file mesh_distortion.hpp.
Member Typedef Documentation
CoordType
template<typename MeshType_ > typedef MeshType_::CoordType FEAT::Geometry::MeshDistortion< MeshType_ >::CoordType
Definition at line 44 of file mesh_distortion.hpp.
Constructor & Destructor Documentation
MeshDistortion() [1/2]
template<typename MeshType_ > FEAT::Geometry::MeshDistortion< MeshType_ >::MeshDistortion (MeshType_ & mesh) inline explicit
Constructor.
Parameters
[in] _mesh A reference to the mesh that is to be distorted
Definition at line 69 of file mesh_distortion.hpp.
MeshDistortion() [2/2]
template<typename MeshType_ > FEAT::Geometry::MeshDistortion< MeshType_ >::MeshDistortion (MeshType_ & mesh, Random::SeedType seed) inline explicit
Constructor.
Parameters
[in] _mesh A reference to the mesh that is to be distorted
[in] _seed The seed for the random number generator
Definition at line 87 of file mesh_distortion.hpp.
~MeshDistortion()
template<typename MeshType_ > virtual FEAT::Geometry::MeshDistortion< MeshType_ >::~MeshDistortion () inline virtual
Definition at line 96 of file mesh_distortion.hpp.
Member Function Documentation
_calc_boundary_facets()
template<typename MeshType_ > virtual void FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_facets () inline protected virtual
determines for each facet whether it is a boundary facet or an inner facet
Reimplemented in FEAT::Geometry::DistributedMeshDistortion< MeshType_ >.
Definition at line 237 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_facets, and FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh.
Referenced by FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_boundary_facets(), and FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices().
_calc_boundary_vertices()
template<typename MeshType_ > virtual void FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices () inline protected virtual
determines for each vertex whether it is a boundary vertex or an inner vertex
Definition at line 264 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_facets, FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_vertices, FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_facets(), and FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_calc_shortest_edge()
template<typename MeshType_ > virtual void FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge () inline protected virtual
determines for each vertex the length of the shortest adjacent edge
Reimplemented in FEAT::Geometry::DistributedMeshDistortion< MeshType_ >.
Definition at line 287 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh, FEAT::Geometry::MeshDistortion< MeshType_ >::_shortest_edge, and FEAT::Math::min().
Referenced by FEAT::Geometry::DistributedMeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform().
_synchronize()
template<typename MeshType_ > virtual void FEAT::Geometry::MeshDistortion< MeshType_ >::_synchronize () inline protected virtual
synchronizes the distortion over all processes; is overridden in DistributedMeshDistortion
Reimplemented in FEAT::Geometry::DistributedMeshDistortion< MeshType_ >.
Definition at line 307 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
distort_shortest_edge_local()
template<typename MeshType_ > void FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local (CoordType scale = CoordType(0.1)) inline
Distorts the mesh according to the shortest local edge.
Moves each inner vertex on an arbitrary point on a circle (2D) or sphere (3D) around the original vertex The radius of the circle/sphere is determined by the shortest edge adjacent to the vertex: radius = scale * length_shortest_edge
Parameters
[in] scale factor to scale the length of the shortest edge to determine the radius
Note
This function only moves inner vertices and leaves boundary vertices untouched.
Definition at line 188 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_vertices, FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh, FEAT::Geometry::MeshDistortion< MeshType_ >::_pi_val, FEAT::Geometry::MeshDistortion< MeshType_ >::_rand, FEAT::Geometry::MeshDistortion< MeshType_ >::_shortest_edge, FEAT::Geometry::MeshDistortion< MeshType_ >::_synchronize(), FEAT::Math::cos(), and FEAT::Math::sin().
distort_shortest_edge_uniform()
template<typename MeshType_ > void FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform (CoordType scale = CoordType(0.1)) inline
Distorts the mesh according to the shortest edge.
Moves each inner vertex on an arbitrary point on a circle (2D) or sphere (3D) around the original vertex The radius of the circle/sphere is determined by the shortest edge in the mesh:
radius = scale * shortest_edge
Parameters
[in] scale factor to scale the length of the shortest edge to determine the radius
Note
This function only moves inner vertices and leaves boundary vertices untouched.
Definition at line 167 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::_shortest_edge, and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
distort_uniform()
template<typename MeshType_ > void FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform (CoordType rad) inline
Distorts the mesh uniformly.
Moves each inner vertex on an arbitrary point on a circle (2D) or sphere (3D) around the original vertex
Parameters
[in] rad Radius of the circle or sphere
Note
This function only moves inner vertices and leaves boundary vertices untouched.
Definition at line 111 of file mesh_distortion.hpp.
References FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_vertices, FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh, FEAT::Geometry::MeshDistortion< MeshType_ >::_pi_val, FEAT::Geometry::MeshDistortion< MeshType_ >::_rand, FEAT::Geometry::MeshDistortion< MeshType_ >::_synchronize(), FEAT::Math::cos(), and FEAT::Math::sin().
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform().
Member Data Documentation
_boundary_facets
template<typename MeshType_ > std::vector<int> FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_facets protected
vector to story which facet is at the boundary
Definition at line 56 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_facets(), and FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices().
_boundary_vertices
template<typename MeshType_ > std::vector<int> FEAT::Geometry::MeshDistortion< MeshType_ >::_boundary_vertices protected
vector to store which vertex is at the boundary
Definition at line 54 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_mesh
template<typename MeshType_ > MeshType_& FEAT::Geometry::MeshDistortion< MeshType_ >::_mesh protected
the mesh we want to distort
Definition at line 50 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_facets(), FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_boundary_vertices(), FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_pi_val
template<typename MeshType_ > const CoordType FEAT::Geometry::MeshDistortion< MeshType_ >::_pi_val = Math::pi<CoordType>() protected
have a guess...
Definition at line 60 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_rand
template<typename MeshType_ > Random FEAT::Geometry::MeshDistortion< MeshType_ >::_rand protected
random number generator for random distortion
Definition at line 52 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_uniform().
_shortest_edge
template<typename MeshType_ > std::vector<CoordType> FEAT::Geometry::MeshDistortion< MeshType_ >::_shortest_edge protected
vector to store the length of the shortest edge belonging to each vertex
Definition at line 58 of file mesh_distortion.hpp.
Referenced by FEAT::Geometry::MeshDistortion< MeshType_ >::_calc_shortest_edge(), FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_local(), and FEAT::Geometry::MeshDistortion< MeshType_ >::distort_shortest_edge_uniform().
shape_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::MeshDistortion< MeshType_ >::shape_dim = MeshType_::shape_dim static constexpr
Definition at line 45 of file mesh_distortion.hpp.
world_dim
template<typename MeshType_ > constexpr int FEAT::Geometry::MeshDistortion< MeshType_ >::world_dim = MeshType_::world_dim static constexpr
Definition at line 46 of file mesh_distortion.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/mesh_distortion.hpp