FEAT: FEAT::LAFEM::TupleVector< First_, Rest_ > Class Template Reference
FEAT::LAFEM::TupleVector< First_, Rest_ > Class Template Reference
Variadic TupleVector class template.
#include <tuple_vector.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = TupleVector< typename First_::template ContainerType< DT2_, IT2_ >, typename Rest_::template ContainerType< DT2_, IT2_ >... >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a vector container with different Data and Index types
typedef First_::DataType DataType
sub-vector data-type
typedef First_::IndexType IndexType
sub-vector index-type
Public Member Functions
TupleVector ()
default CTOR
TupleVector (const TupleVector &)=delete
deleted copy-ctor
TupleVector (First_ &&the_first, Rest_ &&... the_rest)
Sub-Vector emplacement constructor.
TupleVector (First_ &&the_first, RestClass &&the_rest)
rest-class emplacement ctor; for internal use only
TupleVector (TupleVector &&other)
move ctor
template<int i_>
TupleElement< i_, First_, Rest_... >::Type & at ()
Returns a sub-vector block.
template<int i_>
TupleElement< i_, First_, Rest_... >::Type const & at () const
Returns a sub-vector block.
void axpy (const TupleVector &x, DataType alpha=DataType(1))
int blocks () const
Returns the number of blocks in this tuple-vector.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
void clone (const TupleVector &other)
Turns this vector into a clone of other.
void clone (const TupleVector &other, CloneMode clone_mode)
Turns this vector into a clone of other.
TupleVector clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a copy of this vector.
void component_invert (const TupleVector &x, DataType alpha=DataType(1))
void component_product (const TupleVector &x, const TupleVector &y)
template<typename First2_ , typename... Rest2_>
void convert (const TupleVector< First2_, Rest2_... > &other)
Conversion method.
void copy (const TupleVector &x, bool full=false)
Performs \(this \leftarrow x\).
DataType dot (const TupleVector &x) const
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DataType min, DataType max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
DataType max_abs_element () const
Retrieve the absolute maximum value of this vector.
DataType max_element () const
Retrieve the maximum value of this vector.
DataType min_abs_element () const
Retrieve the absolute minimum value of this vector.
DataType min_element () const
Retrieve the minimum value of this vector.
DataType norm2 () const
DataType norm2sqr () const
TupleVector & operator= (const TupleVector &)=delete
deleted copy-assign operator
TupleVector & operator= (TupleVector &&other)
move-assign operator
void read_from (FileMode mode, const String &filename)
Read in vector from file.
void read_from (FileMode mode, std::istream &file)
Read in vector from stream.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
void scale (const TupleVector &x, DataType alpha)
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
template<Perspective perspective_ = Perspective::native>
Index size () const
Returns the total size of this tuple-vector.
DataType triple_dot (const TupleVector &x, const TupleVector &y) const
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
void write_out (FileMode mode, const String &filename) const
Write out vector to file.
void write_out (FileMode mode, std::ostream &file) const
Write out vector to file.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr int num_blocks = TupleVector<Rest_...>::num_blocks + 1
number of vector blocks
Static Protected Member Functions
static String sub_name_list ()
Returns a list of all sub-vector type names.
Protected Attributes
First_ _first
the first sub-vector
RestClass _rest
all remaining sub-vectors
Private Types
typedef TupleVector< Rest_... > RestClass
Private Member Functions
void _read_from_binary (std::istream &file)
read binary data of _first and _rest to file.
void _write_out_binary (std::ostream &file) const
write binary data of _first and _rest to file.
Detailed Description
template<typename First_, typename... Rest_>
class FEAT::LAFEM::TupleVector< First_, Rest_ >
Variadic TupleVector class template.
This class template implements a composition of sub-vectors of arbitrary classes.
Template Parameters
First_,...Rest_ A sequence of (meta) vector classes which are to be composed.
Author
Peter Zajac
Definition at line 35 of file tuple_vector.hpp.
Member Typedef Documentation
ContainerType
template<typename First_ , typename... Rest_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::TupleVector< First_, Rest_ >::ContainerType = TupleVector< typename First_::template ContainerType<DT2_, IT2_>, typename Rest_::template ContainerType<DT2_, IT2_>...>
Our 'base' class type.
Definition at line 74 of file tuple_vector.hpp.
ContainerTypeByDI
template<typename First_ , typename... Rest_> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::TupleVector< First_, Rest_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a vector container with different Data and Index types
Definition at line 80 of file tuple_vector.hpp.
DataType
template<typename First_ , typename... Rest_> typedef First_::DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::DataType
sub-vector data-type
Definition at line 68 of file tuple_vector.hpp.
IndexType
template<typename First_ , typename... Rest_> typedef First_::IndexType FEAT::LAFEM::TupleVector< First_, Rest_ >::IndexType
sub-vector index-type
Definition at line 70 of file tuple_vector.hpp.
RestClass
template<typename First_ , typename... Rest_> typedef TupleVector<Rest_...> FEAT::LAFEM::TupleVector< First_, Rest_ >::RestClass private
Definition at line 41 of file tuple_vector.hpp.
Constructor & Destructor Documentation
TupleVector() [1/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleVector< First_, Rest_ >::TupleVector () inline
default CTOR
Definition at line 102 of file tuple_vector.hpp.
TupleVector() [2/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleVector< First_, Rest_ >::TupleVector (First_ && the_first, RestClass && the_rest) inline explicit
rest-class emplacement ctor; for internal use only
Definition at line 107 of file tuple_vector.hpp.
TupleVector() [3/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleVector< First_, Rest_ >::TupleVector (First_ && the_first, Rest_ &&... the_rest) inline explicit
Sub-Vector emplacement constructor.
Definition at line 114 of file tuple_vector.hpp.
TupleVector() [4/4]
template<typename First_ , typename... Rest_> FEAT::LAFEM::TupleVector< First_, Rest_ >::TupleVector (TupleVector< First_, Rest_ > && other) inline
move ctor
Definition at line 121 of file tuple_vector.hpp.
Member Function Documentation
_read_from_binary()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::_read_from_binary (std::istream & file) inline private
read binary data of _first and _rest to file.
Definition at line 44 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_read_from_binary(), FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, and FEAT::LAFEM::fm_binary.
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::_read_from_binary(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::read_from().
_write_out_binary()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::_write_out_binary (std::ostream & file) const inline private
write binary data of _first and _rest to file.
Definition at line 54 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, FEAT::LAFEM::TupleVector< First_, Rest_ >::_write_out_binary(), and FEAT::LAFEM::fm_binary.
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::_write_out_binary(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::write_out().
at() [1/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type & FEAT::LAFEM::TupleVector< First_, Rest_ >::at () inline
Returns a sub-vector block.
Template Parameters
i_ The index of the sub-vector block that is to be returned.
Returns
A (const) reference to the sub-vector at position i_.
Definition at line 246 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::num_blocks.
at() [2/2]
template<typename First_ , typename... Rest_> template<int i_> TupleElement< i_, First_, Rest_... >::Type const & FEAT::LAFEM::TupleVector< First_, Rest_ >::at () const inline
Returns a sub-vector block.
Template Parameters
i_ The index of the sub-vector block that is to be returned.
Returns
A (const) reference to the sub-vector at position i_.
Definition at line 254 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::num_blocks.
axpy()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::axpy (const TupleVector< First_, Rest_ > & x, DataType alpha = DataType(1)) inline
Definition at line 324 of file tuple_vector.hpp.
blocks()
template<typename First_ , typename... Rest_> int FEAT::LAFEM::TupleVector< First_, Rest_ >::blocks () const inline
Returns the number of blocks in this tuple-vector.
Definition at line 268 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::num_blocks.
bytes()
template<typename First_ , typename... Rest_> std::size_t FEAT::LAFEM::TupleVector< First_, Rest_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 443 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleVector< First_, Rest_ >::bytes().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::bytes().
clear()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::clear () inline
Free all allocated arrays.
Definition at line 305 of file tuple_vector.hpp.
Referenced by FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::done_symbolic().
clone() [1/3]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::clone (const TupleVector< First_, Rest_ > & other) inline
Turns this vector into a clone of other.
As the default CloneMode of the underlying containers is unknown, this has to be separate.
Definition at line 174 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleVector< First_, Rest_ >::clone().
clone() [2/3]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::clone (const TupleVector< First_, Rest_ > & other, CloneMode clone_mode) inline
Turns this vector into a clone of other.
Parameters
[in] clone_mode Determines the type of clone returned (shallow, weak, layout, deep)
Definition at line 162 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleVector< First_, Rest_ >::clone().
clone() [3/3]
template<typename First_ , typename... Rest_> TupleVector FEAT::LAFEM::TupleVector< First_, Rest_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a copy of this vector.
Parameters
[in] mode Determines the type of clone returned (shallow, weak, layout, deep)
Definition at line 150 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleVector< First_, Rest_ >::clone().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::clone().
component_invert()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::component_invert (const TupleVector< First_, Rest_ > & x, DataType alpha = DataType(1)) inline
Definition at line 336 of file tuple_vector.hpp.
component_product()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::component_product (const TupleVector< First_, Rest_ > & x, const TupleVector< First_, Rest_ > & y) inline
Definition at line 330 of file tuple_vector.hpp.
convert()
template<typename First_ , typename... Rest_> template<typename First2_ , typename... Rest2_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::convert (const TupleVector< First2_, Rest2_... > & other) inline
Conversion method.
Parameters
[in] other The source Vector.
Use source vector content as content of current vector
Definition at line 436 of file tuple_vector.hpp.
Referenced by FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
copy()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::copy (const TupleVector< First_, Rest_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The vector to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 318 of file tuple_vector.hpp.
Referenced by FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_diag(), and FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_full().
dot()
template<typename First_ , typename... Rest_> DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::dot (const TupleVector< First_, Rest_ > & x) const inline
Definition at line 348 of file tuple_vector.hpp.
format() [1/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the vector's entries are to be set to.
Definition at line 285 of file tuple_vector.hpp.
References FEAT::value.
Referenced by FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_diag(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_apply_full(), FEAT::Solver::Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >::_calc_scale(), and FEAT::LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >::extract_diag().
format() [2/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::format (Random & rng, DataType min, DataType max) inline
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 298 of file tuple_vector.hpp.
get_checkpoint_size()
template<typename First_ , typename... Rest_> std::uint64_t FEAT::LAFEM::TupleVector< First_, Rest_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 181 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleVector< First_, Rest_ >::get_checkpoint_size().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::get_checkpoint_size().
max_abs_element()
template<typename First_ , typename... Rest_> DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::max_abs_element () const inline
Retrieve the absolute maximum value of this vector.
Returns
The largest absolute value.
Definition at line 377 of file tuple_vector.hpp.
References FEAT::Math::max(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::max_abs_element().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::max_abs_element().
max_element()
template<typename First_ , typename... Rest_> DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::max_element () const inline
Retrieve the maximum value of this vector.
Returns
The largest value.
Definition at line 397 of file tuple_vector.hpp.
References FEAT::Math::max(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::max_element().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::max_element().
min_abs_element()
template<typename First_ , typename... Rest_> DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::min_abs_element () const inline
Retrieve the absolute minimum value of this vector.
Returns
The smallest absolute value.
Definition at line 387 of file tuple_vector.hpp.
References FEAT::Math::min(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::min_abs_element().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::min_abs_element().
min_element()
template<typename First_ , typename... Rest_> DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::min_element () const inline
Retrieve the minimum value of this vector.
Returns
The smallest value.
Definition at line 407 of file tuple_vector.hpp.
References FEAT::Math::min(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::min_element().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::min_element().
name()
template<typename First_ , typename... Rest_> static String FEAT::LAFEM::TupleVector< First_, Rest_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 274 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::sub_name_list().
norm2()
template<typename First_ , typename... Rest_> DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::norm2 () const inline
Definition at line 367 of file tuple_vector.hpp.
norm2sqr()
template<typename First_ , typename... Rest_> DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::norm2sqr () const inline
Definition at line 362 of file tuple_vector.hpp.
operator=()
template<typename First_ , typename... Rest_> TupleVector & FEAT::LAFEM::TupleVector< First_, Rest_ >::operator= (TupleVector< First_, Rest_ > && other) inline
move-assign operator
Definition at line 128 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, and FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest.
read_from() [1/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::read_from (FileMode mode, const String & filename) inline
Read in vector from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 454 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::read_from().
read_from() [2/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::read_from (FileMode mode, std::istream & file) inline
Read in vector from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Definition at line 469 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_read_from_binary(), FEAT::LAFEM::fm_binary, and XABORTM.
restore_from_checkpoint_data()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 187 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleVector< First_, Rest_ >::restore_from_checkpoint_data().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::restore_from_checkpoint_data().
scale()
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::scale (const TupleVector< First_, Rest_ > & x, DataType alpha) inline
Definition at line 342 of file tuple_vector.hpp.
set_checkpoint_data()
template<typename First_ , typename... Rest_> std::uint64_t FEAT::LAFEM::TupleVector< First_, Rest_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 200 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest, and FEAT::LAFEM::TupleVector< First_, Rest_ >::set_checkpoint_data().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::set_checkpoint_data().
size()
template<typename First_ , typename... Rest_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::TupleVector< First_, Rest_ >::size () const inline
Returns the total size of this tuple-vector.
Definition at line 262 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_first, and FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest.
Referenced by FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::apply().
sub_name_list()
template<typename First_ , typename... Rest_> static String FEAT::LAFEM::TupleVector< First_, Rest_ >::sub_name_list () inline static protected
Returns a list of all sub-vector type names.
Definition at line 95 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::sub_name_list().
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::name(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::sub_name_list().
triple_dot()
template<typename First_ , typename... Rest_> DataType FEAT::LAFEM::TupleVector< First_, Rest_ >::triple_dot (const TupleVector< First_, Rest_ > & x, const TupleVector< First_, Rest_ > & y) const inline
Calculate \(result \leftarrow x^T \mathrm{diag}(this) y \).
Parameters
[in] x The first vector.
[in] y The second vector.
Returns
The computed triple dot product.
Definition at line 356 of file tuple_vector.hpp.
write_out() [1/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::write_out (FileMode mode, const String & filename) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] filename The file where the vector shall be stored.
Definition at line 498 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::write_out().
write_out() [2/2]
template<typename First_ , typename... Rest_> void FEAT::LAFEM::TupleVector< First_, Rest_ >::write_out (FileMode mode, std::ostream & file) const inline
Write out vector to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
Todo:
globale liste anlegen
Definition at line 513 of file tuple_vector.hpp.
References FEAT::LAFEM::TupleVector< First_, Rest_ >::_write_out_binary(), FEAT::LAFEM::fm_binary, FEAT::LAFEM::TupleVector< First_, Rest_ >::num_blocks, and XABORTM.
Friends And Related Function Documentation
TupleVector
template<typename First_ , typename... Rest_> template<typename , typename... > friend class TupleVector friend
Definition at line 39 of file tuple_vector.hpp.
Member Data Documentation
_first
template<typename First_ , typename... Rest_> First_ FEAT::LAFEM::TupleVector< First_, Rest_ >::_first protected
the first sub-vector
Definition at line 90 of file tuple_vector.hpp.
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::_read_from_binary(), FEAT::LAFEM::TupleVector< First_, Rest_ >::_write_out_binary(), FEAT::LAFEM::TupleVector< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleVector< First_, Rest_ >::clone(), FEAT::LAFEM::TupleVector< First_, Rest_ >::get_checkpoint_size(), FEAT::LAFEM::TupleVector< First_, Rest_ >::operator=(), FEAT::LAFEM::TupleVector< First_, Rest_ >::restore_from_checkpoint_data(), FEAT::LAFEM::TupleVector< First_, Rest_ >::set_checkpoint_data(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::size().
_rest
template<typename First_ , typename... Rest_> RestClass FEAT::LAFEM::TupleVector< First_, Rest_ >::_rest protected
all remaining sub-vectors
Definition at line 92 of file tuple_vector.hpp.
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::_read_from_binary(), FEAT::LAFEM::TupleVector< First_, Rest_ >::_write_out_binary(), FEAT::LAFEM::TupleVector< First_, Rest_ >::bytes(), FEAT::LAFEM::TupleVector< First_, Rest_ >::clone(), FEAT::LAFEM::TupleVector< First_, Rest_ >::get_checkpoint_size(), FEAT::LAFEM::TupleVector< First_, Rest_ >::operator=(), FEAT::LAFEM::TupleVector< First_, Rest_ >::restore_from_checkpoint_data(), FEAT::LAFEM::TupleVector< First_, Rest_ >::set_checkpoint_data(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::size().
num_blocks
template<typename First_ , typename... Rest_> constexpr int FEAT::LAFEM::TupleVector< First_, Rest_ >::num_blocks = TupleVector<Rest_...>::num_blocks + 1 static constexpr
number of vector blocks
Definition at line 65 of file tuple_vector.hpp.
Referenced by FEAT::LAFEM::TupleVector< First_, Rest_ >::at(), FEAT::LAFEM::TupleVector< First_, Rest_ >::blocks(), and FEAT::LAFEM::TupleVector< First_, Rest_ >::write_out().
The documentation for this class was generated from the following file:
kernel/lafem/tuple_vector.hpp