FEAT: FEAT::TestSystem::TestList Class Reference
FEAT::TestSystem::TestList Class Reference
list of all instantiated tests
#include <test_system.hpp>
Classes
class DeleteOnDestruction
Public Types
typedef std::list< UnitTest * >::iterator Iterator
TestList forward iterator.
Public Member Functions
Iterator begin_tests ()
returns an iterator to the front of the TestList
Iterator end_tests ()
returns an iterator beyond the last element of the TestList
Iterator erase (Iterator i)
removes iterator target from the TestList
void register_test (UnitTest *const test)
adds a test to the TestList
size_t size ()
returns the size of the TestList
Static Public Member Functions
static TestList * instance ()
Returns the instance.
Private Member Functions
TestList ()
default CTOR
TestList (const TestList &)=delete
TestList & operator= (const TestList &)=delete
Static Private Member Functions
static void _delete (TestList *const ptr)
static TestList ** _instance_ptr ()
Returns a pointer to our instance pointer.
Private Attributes
std::list< UnitTest * > _tests
internal STL list representation of TestList
Detailed Description
list of all instantiated tests
Definition at line 92 of file test_system.hpp.
Member Typedef Documentation
Iterator
typedef std::list<UnitTest*>::iterator FEAT::TestSystem::TestList::Iterator
TestList forward iterator.
Definition at line 181 of file test_system.hpp.
Constructor & Destructor Documentation
TestList()
FEAT::TestSystem::TestList::TestList () inline private
default CTOR
Definition at line 146 of file test_system.hpp.
Referenced by instance().
Member Function Documentation
_delete()
static void FEAT::TestSystem::TestList::_delete (TestList *const ptr) inline static private
Definition at line 137 of file test_system.hpp.
_instance_ptr()
static TestList ** FEAT::TestSystem::TestList::_instance_ptr () inline static private
Returns a pointer to our instance pointer.
Definition at line 117 of file test_system.hpp.
References instance().
Referenced by instance().
begin_tests()
Iterator FEAT::TestSystem::TestList::begin_tests () inline
returns an iterator to the front of the TestList
Definition at line 195 of file test_system.hpp.
References _tests.
end_tests()
Iterator FEAT::TestSystem::TestList::end_tests () inline
returns an iterator beyond the last element of the TestList
Definition at line 201 of file test_system.hpp.
References _tests.
erase()
Iterator FEAT::TestSystem::TestList::erase (Iterator i) inline
removes iterator target from the TestList
Definition at line 213 of file test_system.hpp.
References _tests.
instance()
static TestList * FEAT::TestSystem::TestList::instance () inline static
Returns the instance.
Returns
A pointer to the singleton.
Todo:
Make thread safe
Definition at line 160 of file test_system.hpp.
References TestList(), and _instance_ptr().
Referenced by FEAT::TestSystem::UnitTest::UnitTest(), and _instance_ptr().
register_test()
void FEAT::TestSystem::TestList::register_test (UnitTest *const test) inline
adds a test to the TestList
Parameters
[in] test the test that will be added
Definition at line 189 of file test_system.hpp.
References _tests.
Referenced by FEAT::TestSystem::UnitTest::UnitTest().
size()
size_t FEAT::TestSystem::TestList::size () inline
returns the size of the TestList
Definition at line 207 of file test_system.hpp.
References _tests.
Member Data Documentation
_tests
std::list<UnitTest*> FEAT::TestSystem::TestList::_tests private
internal STL list representation of TestList
Definition at line 143 of file test_system.hpp.
Referenced by begin_tests(), end_tests(), erase(), register_test(), and size().
The documentation for this class was generated from the following file:
test_system/test_system.hpp