FEAT: FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ > Class Template Reference
FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ > Class Template Reference
CSR based sparse matrix.
#include <sparse_matrix_csr.hpp>
Classes
class GatherAxpy
Gather-Axpy operation for SparseMatrixCSR.
class ScatterAxpy
Scatter-Axpy operation for SparseMatrixCSR.
Public Types
template<typename DT2_ = DT_, typename IT2_ = IT_>
using ContainerType = SparseMatrixCSR< DT2_, IT2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using ContainerTypeByDI = ContainerType< DataType2_, IndexType2_ >
this typedef lets you create a matrix container with new Datatape and Index types
typedef DT_ DataType
Our datatype.
typedef const IT_ * ImageIterator
ImageIterator typedef for Adjactor interface implementation.
typedef IT_ IndexType
Our indextype.
typedef DT_ ValueType
Value type, meaning the type of each 'block'.
typedef DenseVector< DT_, IT_ > VectorTypeL
Compatible L-vector type.
typedef DenseVector< DT_, IT_ > VectorTypeR
Compatible R-vector type.
Public Member Functions
SparseMatrixCSR ()
Constructor.
SparseMatrixCSR (const Adjacency::Graph &graph)
Constructor.
SparseMatrixCSR (const Index rows_in, const Index columns_in, DenseVector< IT_, IT_ > &col_ind_in, DenseVector< DT_, IT_ > &val_in, DenseVector< IT_, IT_ > &row_ptr_in)
Constructor.
template<typename MT_ >
SparseMatrixCSR (const MT_ &other)
Constructor.
SparseMatrixCSR (const SparseLayout< IT_, layout_id > &layout_in)
Constructor.
SparseMatrixCSR (FileMode mode, std::istream &file)
Constructor.
SparseMatrixCSR (FileMode mode, String filename)
Constructor.
SparseMatrixCSR (Index rows_in, Index columns_in)
Constructor.
SparseMatrixCSR (Index rows_in, Index columns_in, Index used_elements_in)
Constructor.
SparseMatrixCSR (SparseMatrixCSR &&other)
Move Constructor.
template<typename DT2_ = DT_, typename IT2_ = IT_>
SparseMatrixCSR (std::vector< char > input)
Constructor.
void bandwidth_column (Index &bandw, Index &bandw_i) const
Retrieve maximum bandwidth among all columns.
void bandwidth_row (Index &bandw, Index &bandw_i) const
Retrieve maximum bandwidth among all rows.
std::size_t bytes () const
Returns the total amount of bytes allocated.
virtual void clear ()
Free all allocated arrays.
SparseMatrixCSR clone (CloneMode clone_mode=CloneMode::Weak) const
Clone operation.
void clone (const Container &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const Container< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
template<typename DT2_ , typename IT2_ >
void clone (const SparseMatrixCSR< DT2_, IT2_ > &other, CloneMode clone_mode=CloneMode::Weak)
Clone operation.
IT_ * col_ind ()
Retrieve column indices array.
IT_ const * col_ind () const
template<Perspective = Perspective::native>
Index columns () const
Retrieve matrix column count.
void convert (const Adjacency::Graph &graph)
Conversion method.
template<typename MT_ >
void convert (const MT_ &a)
Conversion method.
template<typename DT2_ , typename IT2_ >
void convert (const SparseMatrixBanded< DT2_, IT2_ > &other)
Conversion method.
template<typename DT2_ , typename IT2_ , int BlockHeight_, int BlockWidth_>
void convert (const SparseMatrixBCSR< DT2_, IT2_, BlockHeight_, BlockWidth_ > &other)
Conversion method.
template<typename DT2_ , typename IT2_ >
void convert (const SparseMatrixCSR< DT2_, IT2_ > &other)
Conversion method.
template<typename MT_ >
void convert_reverse (MT_ &a) const
Reverse Conversion method.
void copy (const SparseMatrixCSR &x, bool full=false)
Performs \(this \leftarrow x\).
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void deserialize (std::vector< char > input)
Deserialization of complete container entity.
bool empty () const
Checks whether the container is empty.
VectorTypeL extract_diag () const
extract main diagonal vector from matrix
void extract_diag (VectorTypeL &diag) const
extract main diagonal vector from matrix
void extract_diag (VectorTypeL &diag, DenseVector< IT_, IT_ > &diag_indices) const
extract main diagonal vector from matrix
DenseVector< IT_, IT_ > extract_diag_indices () const
extract main diagonal vector from matrix
void extract_diag_indices (DenseVector< IT_, IT_ > &diag_indices) const
extract main diagonal vector from matrix
void format (DT_ value=DT_(0))
Reset all elements of the container to a given value or zero if missing.
void format (Random &rng, DT_ min, DT_ max)
Reset all elements of the container to random values.
std::uint64_t get_checkpoint_size (const LAFEM::SerialConfig &config)
Calculate size.
const std::vector< DT_ * > & get_elements () const
Returns a list of all data arrays.
const std::vector< Index > & get_elements_size () const
Returns a list of all data array sizes.
const std::vector< IT_ * > & get_indices () const
Returns a list of all Index arrays.
const std::vector< Index > & get_indices_size () const
Returns a list of all Index array sizes.
Index get_length_of_line (const Index row) const
Returns the number of NNZ-elements of the selected row.
Index get_num_nodes_domain () const
Index get_num_nodes_image () const
const std::vector< DT_ > & get_scalar_dt () const
Returns a list of all scalar values with datatype dt.
const std::vector< Index > & get_scalar_index () const
Returns a list of all scalar values with datatype index.
ImageIterator image_begin (Index domain_node) const
ImageIterator image_end (Index domain_node) const
SparseLayout< IT_, layout_id > layout () const
Retrieve convenient sparse matrix layout object.
VectorTypeL lump_rows () const
Returns the lumped rows vector.
void lump_rows (VectorTypeL &lump) const
void move (Container &&other)
Assignment move operation.
DT_ operator() (Index row, Index col) const
Retrieve specific matrix element.
SparseMatrixCSR & operator= (const SparseLayout< IT_, layout_id > &layout_in)
Assignment operator.
SparseMatrixCSR & operator= (SparseMatrixCSR &&other)
Move operator.
void permute (Adjacency::Permutation &perm_row, Adjacency::Permutation &perm_col)
Permutate matrix rows and columns according to the given Permutations.
void radius_column (Index &radius, Index &radius_i) const
Retrieve maximum radius among all column.
void radius_row (Index &radius, Index &radius_i) const
Retrieve maximum radius among all rows.
void read_from (FileMode mode, std::istream &file)
Read in matrix from stream.
void read_from (FileMode mode, String filename)
Read in matrix from file.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
IT_ * row_ptr ()
Retrieve row start index array.
IT_ const * row_ptr () const
template<Perspective = Perspective::native>
Index rows () const
Retrieve matrix row count.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > serialize (const LAFEM::SerialConfig &config=SerialConfig()) const
Serialization of complete container entity.
std::uint64_t set_checkpoint_data (std::vector< char > &data, const LAFEM::SerialConfig &config)
void shrink (DT_ eps)
Shrink matrix and drop small values.
template<Perspective = Perspective::native>
Index size () const
Returns the containers size.
template<Perspective = Perspective::native>
Index used_elements () const
Retrieve non zero element count.
DT_ * val ()
Retrieve non zero element array.
DT_ const * val () const
void write_out (FileMode mode, std::ostream &file, bool symmetric=false) const
Write out matrix to file.
void write_out (FileMode mode, String filename, bool symmetric=false) const
Write out matrix to file.
Linear algebra operations
void axpy (const SparseMatrixCSR &x, const SparseMatrixCSR &y, const DT_ alpha=DT_(1))
Calculate \(this \leftarrow y + \alpha~ x\).
void scale (const SparseMatrixCSR &x, const DT_ alpha)
Calculate \(this \leftarrow \alpha~ x \).
DT_ norm_frobenius () const
Calculates the Frobenius norm of this matrix.
void row_norm2 (VectorTypeL &row_norms) const
Computes the 2-norm for every row.
void row_norm2sqr (VectorTypeL &row_norms) const
Computes the square of the 2-norm for every row.
void row_norm2sqr (VectorTypeL &row_norms, const VectorTypeR &scal) const
Computes the square of the 2-norm for every row, where every row is scaled by a vector.
DT_ max_abs_element () const
Retrieve the absolute maximum value of this matrix.
DT_ min_abs_element () const
Retrieve the absolute minimum value of this matrix.
DT_ max_element () const
Retrieve the maximum value of this matrix.
DT_ min_element () const
Retrieve the minimum value of this matrix.
SparseMatrixCSR transpose () const
Calculate \(this^\top \).
void transpose (const SparseMatrixCSR &x)
Calculate \(this \leftarrow x^\top \).
void scale_rows (const SparseMatrixCSR &x, const DenseVector< DT_, IT_ > &s)
Calculate \(this_{ij} \leftarrow x_{ij}\cdot s_i\).
void scale_cols (const SparseMatrixCSR &x, const DenseVector< DT_, IT_ > &s)
Calculate \(this_{ij} \leftarrow x_{ij}\cdot s_j\).
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x, bool transposed=false) const
Calculate \(r \leftarrow this\cdot x \).
template<int BlockSize_>
void apply (DenseVectorBlocked< DT_, IT_, BlockSize_ > &r, const DenseVectorBlocked< DT_, IT_, BlockSize_ > &x) const
Calculate \(r \leftarrow this\cdot x \).
void apply (DenseVector< DT_, IT_ > &r, const DenseVector< DT_, IT_ > &x, const DenseVector< DT_, IT_ > &y, const DT_ alpha=DT_(1), const bool transposed=false) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
template<int BlockSize_>
void apply (DenseVectorBlocked< DT_, IT_, BlockSize_ > &r, const DenseVectorBlocked< DT_, IT_, BlockSize_ > &x, const DenseVectorBlocked< DT_, IT_, BlockSize_ > &y, const DT_ alpha=DT_(1)) const
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
void add_double_mat_product (const LAFEM::SparseMatrixCSR< DT_, IT_ > &d, const LAFEM::SparseMatrixCSR< DT_, IT_ > &a, const LAFEM::SparseMatrixCSR< DT_, IT_ > &b, const DT_ alpha=DT_(1), const bool allow_incomplete=false)
Adds a double-matrix product onto this matrix.
void add_double_mat_product (const LAFEM::SparseMatrixCSR< DT_, IT_ > &d, const LAFEM::DenseVector< DT_, IT_ > &a, const LAFEM::SparseMatrixCSR< DT_, IT_ > &b, const DT_ alpha=DT_(1), const bool allow_incomplete=false)
Adds a double-matrix product onto this matrix.
void add_mat_mat_product (const LAFEM::SparseMatrixCSR< DT_, IT_ > &d, const LAFEM::SparseMatrixCSR< DT_, IT_ > &b, const DT_ alpha=DT_(1), const bool allow_incomplete=false)
Adds a matrix-matrix product onto this matrix.
Static Public Member Functions
static String name ()
Returns a descriptive string.
Static Public Attributes
static constexpr bool is_global = false
static constexpr bool is_local = true
static constexpr SparseLayoutId layout_id = SparseLayoutId::lt_csr
Our used layout type.
Protected Member Functions
void _copy_content (const Container &other, bool full)
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::istream &file)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _deserialize (FileMode mode, std::vector< char > &input)
Deserialization of complete container entity with possible decompression.
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::vector< char > _serialize (FileMode mode, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
void _serialize (FileMode mode, std::ostream &file, const SerialConfig &config=SerialConfig()) const
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
template<typename DT2_ = DT_, typename IT2_ = IT_>
std::uint64_t _serialized_size (const LAFEM::SerialConfig &config=LAFEM::SerialConfig()) const
Calculation of the serialized size with optional compression of complete container entity.
template<typename DT2_ , typename IT2_ >
void assign (const Container< DT2_, IT2_ > &other)
Assignment operation.
Protected Attributes
std::vector< DT_ * > _elements
List of pointers to all datatype dependent arrays.
std::vector< Index > _elements_size
List of corresponding datatype array sizes.
bool _foreign_memory
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
std::vector< IT_ * > _indices
List of pointers to all IT_ dependent arrays.
std::vector< Index > _indices_size
List of corresponding IT_ array sizes.
std::vector< DT_ > _scalar_dt
List of scalars with datatype DT_.
std::vector< Index > _scalar_index
List of scalars with datatype index.
Private Member Functions
Index & _columns ()
Index & _rows ()
Index & _size ()
Index & _used_elements ()
Friends
std::ostream & operator<< (std::ostream &lhs, const SparseMatrixCSR &b)
SparseMatrixCSR streaming operator.
bool operator== (const SparseMatrixCSR &a, const SparseMatrixCSR &b)
SparseMatrixCSR comparison operator.
Detailed Description
template<typename DT_, typename IT_ = Index>
class FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >
CSR based sparse matrix.
Template Parameters
DT_ The datatype to be used.
IT_ The indexing type to be used.
This class represents a sparse matrix, that stores its non zero elements in the compressed sparse row format.
Data survey:
_elements[0]: raw non zero number values
_indices[0]: column index per non zero element
_indices[1]: row start index (including matrix end index)
_scalar_index[0]: container size
_scalar_index[1]: row count
_scalar_index[2]: column count
_scalar_index[3]: non zero element count (used elements)
Refer to LAFEM design description for general usage informations.
Author
Dirk Ribbrock
Definition at line 61 of file sparse_matrix_csr.hpp.
Member Typedef Documentation
ContainerType
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> using FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::ContainerType = SparseMatrixCSR<DT2_, IT2_>
Our 'base' class type.
Definition at line 295 of file sparse_matrix_csr.hpp.
ContainerTypeByDI
template<typename DT_ , typename IT_ = Index> template<typename DataType2_ , typename IndexType2_ > using FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::ContainerTypeByDI = ContainerType<DataType2_, IndexType2_>
this typedef lets you create a matrix container with new Datatape and Index types
Definition at line 299 of file sparse_matrix_csr.hpp.
DataType
template<typename DT_ , typename IT_ = Index> typedef DT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::DataType
Our datatype.
Definition at line 280 of file sparse_matrix_csr.hpp.
ImageIterator
template<typename DT_ , typename IT_ = Index> typedef const IT_* FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::ImageIterator
ImageIterator typedef for Adjactor interface implementation.
Definition at line 292 of file sparse_matrix_csr.hpp.
IndexType
template<typename DT_ , typename IT_ = Index> typedef IT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::IndexType
Our indextype.
Definition at line 282 of file sparse_matrix_csr.hpp.
ValueType
template<typename DT_ , typename IT_ = Index> typedef DT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::ValueType
Value type, meaning the type of each 'block'.
Definition at line 284 of file sparse_matrix_csr.hpp.
VectorTypeL
template<typename DT_ , typename IT_ = Index> typedef DenseVector<DT_, IT_> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::VectorTypeL
Compatible L-vector type.
Definition at line 286 of file sparse_matrix_csr.hpp.
VectorTypeR
template<typename DT_ , typename IT_ = Index> typedef DenseVector<DT_, IT_> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::VectorTypeR
Compatible R-vector type.
Definition at line 288 of file sparse_matrix_csr.hpp.
Constructor & Destructor Documentation
SparseMatrixCSR() [1/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR () inline explicit
Constructor.
Creates an empty non dimensional matrix.
Definition at line 309 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR().
SparseMatrixCSR() [2/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (Index rows_in, Index columns_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
Creates an empty matrix. Because SparseMatrixCSR is a read-only container, it stays empty.
Note
This matrix does not allocate any memory
Definition at line 328 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
SparseMatrixCSR() [3/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (Index rows_in, Index columns_in, Index used_elements_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
[in] used_elements_in The amount of non zero elements of the created matrix.
Creates an empty (but allocated) matrix.
Note
The allocated memory will not be initialized.
Definition at line 347 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and XASSERT.
SparseMatrixCSR() [4/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (const SparseLayout< IT_, layout_id > & layout_in) inline explicit
Constructor.
Parameters
[in] layout_in The layout to be used.
Creates an empty matrix with given layout.
Definition at line 373 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and FEAT::MemoryPool::increase_memory().
SparseMatrixCSR() [5/11]
template<typename DT_ , typename IT_ = Index> template<typename MT_ > FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (const MT_ & other) inline explicit
Constructor.
Parameters
[in] other The source matrix.
Creates a CSR matrix based on the source matrix.
Definition at line 395 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert().
SparseMatrixCSR() [6/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (const Adjacency::Graph & graph) inline explicit
Constructor.
Parameters
[in] graph The graph to create the matrix from
Creates a CSR matrix based on a given adjacency graph, representing the sparsity pattern.
Definition at line 408 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), and FEAT::Adjacency::Graph::get_num_indices().
SparseMatrixCSR() [7/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (FileMode mode, String filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a CSR matrix based on the source file.
Definition at line 452 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
SparseMatrixCSR() [8/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (FileMode mode, std::istream & file) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Creates a CSR matrix based on the source filestream.
Definition at line 466 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
SparseMatrixCSR() [9/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (const Index rows_in, const Index columns_in, DenseVector< IT_, IT_ > & col_ind_in, DenseVector< DT_, IT_ > & val_in, DenseVector< IT_, IT_ > & row_ptr_in) inline explicit
Constructor.
Parameters
[in] rows_in The row count of the created matrix.
[in] columns_in The column count of the created matrix.
[in] col_ind_in Vector with column indices.
[in] val_in Vector with non zero elements.
[in] row_ptr_in Vector with start indices of all rows into the val/col_ind arrays. Note that this vector must also contain the end index of the last row and thus has a size of row_count + 1.
Creates a matrix with given dimensions and content.
Todo:
maybe create empty matrix if col_ind and val and row_ptr inputs are all three empty
Definition at line 484 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERT.
SparseMatrixCSR() [10/11]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (std::vector< char > input) inline explicit
Constructor.
Parameters
[in] input A std::vector, containing the byte array.
Creates a matrix from the given byte array.
Definition at line 518 of file sparse_matrix_csr.hpp.
SparseMatrixCSR() [11/11]
template<typename DT_ , typename IT_ = Index> FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR (SparseMatrixCSR< DT_, IT_ > && other) inline
Move Constructor.
Parameters
[in] other The source matrix.
Moves a given matrix to this matrix.
Definition at line 531 of file sparse_matrix_csr.hpp.
Member Function Documentation
_columns()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::_columns () inline private
Definition at line 268 of file sparse_matrix_csr.hpp.
_copy_content()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::_copy_content (const Container< DT_, IT_ > & other, bool full) inline protected inherited
Definition at line 242 of file container.hpp.
_deserialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::istream & file) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file std::istream, pointing to the input data.
Recreate a complete container entity by a single binary file.
Definition at line 776 of file container.hpp.
References XABORTM.
_deserialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_deserialize (FileMode mode, std::vector< char > & input) inline protected inherited
Deserialization of complete container entity with possible decompression.
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] input A std::vector containing the byte array.
Recreate a complete container entity by a single binary array.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 622 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::Pack::decode(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Type::Helper::extract_floatness(), FEAT::Type::Helper::extract_intness(), FEAT::Type::Helper::extract_signedness(), FEAT::Type::Helper::extract_type_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, XABORTM, XASSERT, and XASSERTM.
_rows()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::_rows () inline private
Definition at line 263 of file sparse_matrix_csr.hpp.
_serialize() [1/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Returns
A std::vector, containing the byte array.
Serialize a complete container entity into a single binary array.
Array data layout:
raw array size in bytes (std::uint64_t)
magic number (std::uint64_t)
DT_ 'hash' value (sizeof(DT_) and floating/integral distinction (packed std::uint64_t)
IT_ 'hash' value (sizeof(IT_) and floating/integral distinction (packed std::uint64_t)
_elements.size() (std::uint64_t)
_indices.size() (std::uint64_t)
_elements_size.size() (std::uint64_t)
_indices_size.size() (std::uint64_t)
_scalar_index.size() (std::uint64_t)
_scalar_dt.size() (std::uint64_t)
_compressed (std::uint64_t)
_elements_size array (std::uint64_t)
_elements arrays byte_size (std::uint64_t) just temporary to read in data
_indices_size array (std::uint64_t)
_indices arrays byte_size (std::uint64_t)
_scalar_index array (std::uint64_t)
_scalar_dt array (DT2_)
_elements arrays (DT2_)
_indices arrays (IT2_)
See FEAT::LAFEM::SerialConfig for details.
Compiler Hack:
clang seems to use older libc++ without std::underlying_type
Definition at line 440 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_off, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), FEAT::LAFEM::indices_off, FEAT::LAFEM::indices_zlib, and XASSERTM.
_serialize() [2/2]
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::Container< DT_, IT_ >::_serialize (FileMode mode, std::ostream & file, const SerialConfig & config = SerialConfig()) const inline protected inherited
Serialization of complete container entity(with options of lossless and lossy compression of data arrays).
Parameters
[in] mode FileMode enum, describing the actual container specialization.
[in] file The output stream to write data into.
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary file with compression enabled. See FEAT::LAFEM::SerialConfig for details.
Definition at line 605 of file container.hpp.
References XABORTM.
_serialized_size()
template<typename DT_ , typename IT_ > template<typename DT2_ = DT_, typename IT2_ = IT_> std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size (const LAFEM::SerialConfig & config = LAFEM::SerialConfig()) const inline protected inherited
Calculation of the serialized size with optional compression of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Returns
An unsigned int containing the size of serialized container.
Calculate the size of the serialized container entity.
Definition at line 357 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::elements_mask, FEAT::LAFEM::elements_zfp, FEAT::LAFEM::elements_zlib, FEAT::Pack::estimate_size(), and FEAT::LAFEM::indices_zlib.
_size()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::_size () inline private
Definition at line 258 of file sparse_matrix_csr.hpp.
_used_elements()
template<typename DT_ , typename IT_ = Index> Index & FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::_used_elements () inline private
Definition at line 273 of file sparse_matrix_csr.hpp.
add_double_mat_product() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product (const LAFEM::SparseMatrixCSR< DT_, IT_ > & d, const LAFEM::DenseVector< DT_, IT_ > & a, const LAFEM::SparseMatrixCSR< DT_, IT_ > & b, const DT_ alpha = DT_(1), const bool allow_incomplete = false) inline
Adds a double-matrix product onto this matrix.
This function performs the following computation:
\[ X \leftarrow X + \alpha D\cdot \textnormal{diag}(A)\cdot B\]
where
X denotes this m-by-n matrix
D denotes a m-by-l matrix
A denotes a vector representing a l-by-l diagonal matrix
B denotes a l-by-n matrix
Attention
This function assumes that the output matrix already contains the required sparsity pattern. This function will throw an exception if the sparsity pattern of the output matrix is incomplete unless allow_incomplete is set to true.
Note
This function currently only supports data in main memory.
Parameters
[in] a The vector representing the diagonal matrix A.
[in] d,b The left and right multiplicand matrices
[in] alpha The scaling factor for the product
[in] allow_incomplete Specifies whether the output matrix structure is allowed to be incomplete. If set to false, this function will throw an exception on incompleteness, otherwise the missing entries are ignored (dropped).
Definition at line 2049 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), XABORTM, and XASSERT.
add_double_mat_product() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product (const LAFEM::SparseMatrixCSR< DT_, IT_ > & d, const LAFEM::SparseMatrixCSR< DT_, IT_ > & a, const LAFEM::SparseMatrixCSR< DT_, IT_ > & b, const DT_ alpha = DT_(1), const bool allow_incomplete = false) inline
Adds a double-matrix product onto this matrix.
This function performs the following computation:
\[ X \leftarrow X + \alpha D\cdot A\cdot B\]
where
X denotes this m-by-n matrix
D denotes a m-by-k matrix
A denotes a k-by-l matrix
B denotes a l-by-n matrix
Attention
This function assumes that the output matrix already contains the required sparsity pattern. This function will throw an exception if the sparsity pattern of the output matrix is incomplete unless allow_incomplete is set to true.
Note
This function currently only supports data in main memory.
Parameters
[in] d,a,b The three matrices to be multiplied
[in] alpha The scaling factor for the product
[in] allow_incomplete Specifies whether the output matrix structure is allowed to be incomplete. If set to false, this function will throw an exception on incompleteness, otherwise the missing entries are ignored (dropped).
Definition at line 1922 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), XABORTM, and XASSERT.
add_mat_mat_product()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_mat_mat_product (const LAFEM::SparseMatrixCSR< DT_, IT_ > & d, const LAFEM::SparseMatrixCSR< DT_, IT_ > & b, const DT_ alpha = DT_(1), const bool allow_incomplete = false) inline
Adds a matrix-matrix product onto this matrix.
This function performs the following computation:
\[ X \leftarrow X + \alpha D\cdot B\]
where
X denotes this m-by-n matrix
D denotes a m-by-l matrix
B denotes a l-by-n matrix
Attention
This function assumes that the output matrix already contains the required sparsity pattern. This function will throw an exception if the sparsity pattern of the output matrix is incomplete unless allow_incomplete is set to true.
Note
This function currently only supports data in main memory.
Parameters
[in] d,b The left and right multiplicand matrices
[in] alpha The scaling factor for the product
[in] allow_incomplete Specifies whether the output matrix structure is allowed to be incomplete. If set to false, this function will throw an exception on incompleteness, otherwise the missing entries are ignored (dropped).
Definition at line 2163 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), XABORTM, and XASSERT.
apply() [1/4]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x, bool transposed = false) const inline
Calculate \(r \leftarrow this\cdot x \).
Attention
r and x must not refer to the same vector object!
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] transposed Should the product use the transposed matrix?
Definition at line 1728 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and XASSERTM.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_apply(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::apply(), and FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system().
apply() [2/4]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply (DenseVector< DT_, IT_ > & r, const DenseVector< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & y, const DT_ alpha = DT_(1), const bool transposed = false) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Attention
r and x must not refer to the same vector object!
Note
r and y are allowed to refer to the same vector object.
Parameters
[out] r The vector that receives the result.
[in] x The vector to be multiplied by this matrix.
[in] y The summand vector.
[in] alpha A scalar to scale the product with.
[in] transposed Should the product use the transposed matrix?
Definition at line 1807 of file sparse_matrix_csr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVector< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and XASSERTM.
apply() [3/4]
template<typename DT_ , typename IT_ = Index> template<int BlockSize_> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply (DenseVectorBlocked< DT_, IT_, BlockSize_ > & r, const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x) const inline
Calculate \(r \leftarrow this\cdot x \).
Attention
r and x must not refer to the same vector object!
Parameters
[out] r The block vector that receives the result.
[in] x The block vector to be multiplied by this matrix.
Note
Every element of each block in the vector x is multiplied with the corresponding single scalar entry in the matrix.
Definition at line 1770 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and XASSERTM.
apply() [4/4]
template<typename DT_ , typename IT_ = Index> template<int BlockSize_> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply (DenseVectorBlocked< DT_, IT_, BlockSize_ > & r, const DenseVectorBlocked< DT_, IT_, BlockSize_ > & x, const DenseVectorBlocked< DT_, IT_, BlockSize_ > & y, const DT_ alpha = DT_(1)) const inline
Calculate \(r \leftarrow y + \alpha~ this\cdot x \).
Attention
r and x must not refer to the same vector object!
Note
r and y are allowed to refer to the same vector object.
Parameters
[out] r The block vector that receives the result.
[in] x The block vector to be multiplied by this matrix.
[in] y The summand block vector.
[in] alpha A scalar to scale the product with.
Note
Every element of each block in the vector x is multiplied with the corresponding single scalar entry in the matrix.
Definition at line 1860 of file sparse_matrix_csr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::size(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and XASSERTM.
assign()
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::assign (const Container< DT2_, IT2_ > & other) inline protected inherited
Assignment operation.
Assigns contents of another container
Parameters
[in] other The source container.
Definition at line 282 of file container.hpp.
References FEAT::MemoryPool::convert(), FEAT::MemoryPool::increase_memory(), and FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::convert(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::permute(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::transpose(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
axpy()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::axpy (const SparseMatrixCSR< DT_, IT_ > & x, const SparseMatrixCSR< DT_, IT_ > & y, const DT_ alpha = DT_(1)) inline
Calculate \(this \leftarrow y + \alpha~ x\).
Parameters
[in] x The first summand matrix to be scaled.
[in] y The second summand matrix
[in] alpha A scalar to multiply x with.
Warning
All three matrices must have the same non zero layout. This operation assumes this silently and does not check this on its own!
Definition at line 1375 of file sparse_matrix_csr.hpp.
References FEAT::Math::abs(), FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERTM.
bandwidth_column()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::bandwidth_column (Index & bandw, Index & bandw_i) const inline
Retrieve maximum bandwidth among all columns.
Parameters
[out] bandw The maximum bandwidth.
[out] bandw_i The column, where the bandwidth is maximal.
Definition at line 1285 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::bandwidth_row(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
bandwidth_row()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::bandwidth_row (Index & bandw, Index & bandw_i) const inline
Retrieve maximum bandwidth among all rows.
Parameters
[out] bandw The maximum bandwidth.
[out] bandw_i The row, where the bandwidth is maximal.
Definition at line 1261 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows().
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::bandwidth_column().
bytes()
template<typename DT_ , typename IT_ > std::size_t FEAT::LAFEM::Container< DT_, IT_ >::bytes () const inline inherited
Returns the total amount of bytes allocated.
Returns
The amount of bytes allocated in all arrays
Definition at line 1033 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::bytes().
clear()
template<typename DT_ , typename IT_ > virtual void FEAT::LAFEM::Container< DT_, IT_ >::clear () inline virtual inherited
Free all allocated arrays.
Definition at line 874 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory, FEAT::LAFEM::Container< DT_, IT_ >::_indices, and FEAT::MemoryPool::release_memory().
Referenced by FEAT::Meshopt::MeshQualityFunctional< MeshType_ >::~MeshQualityFunctional(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::clear(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::clear(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::clear(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::clear(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::clear(), FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::done_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::done_symbolic(), FEAT::Solver::GenericUmfpack< Matrix_ >::done_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from().
clone() [1/4]
template<typename DT_ , typename IT_ = Index> SparseMatrixCSR FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone (CloneMode clone_mode = CloneMode::Weak) const inline
Clone operation.
Create a clone of this container.
Parameters
[in] clone_mode The actual cloning procedure.
Returns
The created clone.
Definition at line 558 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone().
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_column().
clone() [2/4]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT_, IT_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 901 of file container.hpp.
References FEAT::LAFEM::Allocate, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::Deep, FEAT::MemoryPool::increase_memory(), FEAT::LAFEM::Layout, FEAT::LAFEM::Shallow, FEAT::LAFEM::Weak, XABORTM, and XASSERTM.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::clone(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVector< DT_, IT_ >::clone(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::clone(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVector< DT_, IT_ >::clone(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::clone(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone().
clone() [3/4]
template<typename DT_ , typename IT_ > template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::Container< DT_, IT_ >::clone (const Container< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline inherited
Clone operation.
Become a copy of a given container.
Parameters
[in] other The source container.
[in] clone_mode The actual cloning procedure
Definition at line 974 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), and FEAT::LAFEM::Container< DT_, IT_ >::clone().
clone() [4/4]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone (const SparseMatrixCSR< DT2_, IT2_ > & other, CloneMode clone_mode = CloneMode::Weak) inline
Clone operation.
Create a clone of another container.
Parameters
[in] other The source container to create the clone from.
[in] clone_mode The actual cloning procedure.
Definition at line 574 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::clone().
col_ind() [1/2]
template<typename DT_ , typename IT_ = Index> IT_ * FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind () inline
Retrieve column indices array.
Returns
Column indices array.
Definition at line 1196 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_mat_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::bandwidth_row(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_weak_matrix_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::Solver::GenericUmfpack< Matrix_ >::init_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::make_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr_neumann(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_row(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out().
col_ind() [2/2]
template<typename DT_ , typename IT_ = Index> IT_ const * FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind () const inline
Definition at line 1204 of file sparse_matrix_csr.hpp.
columns()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns () const inline
Retrieve matrix column count.
Returns
Matrix column count.
Definition at line 1174 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::SORPrecondWithBackend(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::Solver::SSORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::SSORPrecondWithBackend(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_mat_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_r(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::get_num_nodes_image(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out().
convert() [1/5]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert (const Adjacency::Graph & graph) inline
Conversion method.
Parameters
[in] graph The graph to create the matrix from
Creates a CSR matrix based on a given adjacency graph, representing the sparsity pattern.
Definition at line 781 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign().
convert() [2/5]
template<typename DT_ , typename IT_ = Index> template<typename MT_ > void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert (const MT_ & a) inline
Conversion method.
Parameters
[in] a The input matrix.
Converts any matrix to SparseMatrixCSR-format
Definition at line 733 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), and XASSERT.
convert() [3/5]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert (const SparseMatrixBanded< DT2_, IT2_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 600 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::Math::max(), FEAT::Math::min(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements().
convert() [4/5]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ , int BlockHeight_, int BlockWidth_> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert (const SparseMatrixBCSR< DT2_, IT2_, BlockHeight_, BlockWidth_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 678 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, and FEAT::LAFEM::Container< DT_, IT_ >::clear().
convert() [5/5]
template<typename DT_ , typename IT_ = Index> template<typename DT2_ , typename IT2_ > void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert (const SparseMatrixCSR< DT2_, IT2_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 587 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign().
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), and FEAT::Solver::GenericUmfpack< Matrix_ >::init_symbolic().
convert_reverse()
template<typename DT_ , typename IT_ = Index> template<typename MT_ > void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert_reverse (MT_ & a) const inline
Reverse Conversion method.
Parameters
[out] a The target matrix.
Assigns own matrix values to target matrix
Warning
This method assumes, that ideally this csr matrix was created from the target matrix a earlier and thus, both (nonzero) layouts match perfectly.
Definition at line 798 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
copy()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::copy (const SparseMatrixCSR< DT_, IT_ > & x, bool full = false) inline
Performs \(this \leftarrow x\).
Parameters
[in] x The Matrix to be copied.
[in] full Shall we create a full copy, including scalars and index arrays?
Definition at line 1359 of file sparse_matrix_csr.hpp.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_numeric(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::axpy().
create_vector_l()
template<typename DT_ , typename IT_ = Index> VectorTypeL FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 2483 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows().
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_interface_filter(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::Solver::GenericUmfpack< Matrix_ >::init_symbolic(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows().
create_vector_r()
template<typename DT_ , typename IT_ = Index> VectorTypeR FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 2489 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns().
Referenced by FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::create_solver_vector(), and FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic().
deserialize()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::deserialize (std::vector< char > input) inline
Deserialization of complete container entity.
Parameters
[in] input A std::vector, containing the byte array.
Recreate a complete container entity by a single binary array.
Definition at line 853 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::fm_csr.
empty()
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::empty () const inline inherited
Checks whether the container is empty.
Returns
true if the container is empty, otherwise false.
Definition at line 1156 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::size().
Referenced by FEAT::LAFEM::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Global::MeanFilter< DT_, IT_ >::MeanFilter(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::_add_filter_pres(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::convert(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_cor(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_rhs(), FEAT::Global::MeanFilter< DT_, IT_ >::filter_sol(), FEAT::LAFEM::MeanFilter< DT_, IT_ >::filter_sol(), and FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic().
extract_diag() [1/3]
template<typename DT_ , typename IT_ = Index> VectorTypeL FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag () const inline
extract main diagonal vector from matrix
Returns
The vector containing the diagonal entry values
Definition at line 2310 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_l(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag().
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag().
extract_diag() [2/3]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag (VectorTypeL & diag) const inline
extract main diagonal vector from matrix
Parameters
[out] diag The vector containing the diagonal entry values
Definition at line 2299 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices().
extract_diag() [3/3]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag (VectorTypeL & diag, DenseVector< IT_, IT_ > & diag_indices) const inline
extract main diagonal vector from matrix
Parameters
[in] diag_indices A vector containing the indices of the diagonal entries
[out] diag The vector containing the diagonal entry values
Definition at line 2277 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERTM.
Referenced by FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_interface_filter(), and FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::extract_diag().
extract_diag_indices() [1/2]
template<typename DT_ , typename IT_ = Index> DenseVector< IT_, IT_ > FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices () const inline
extract main diagonal vector from matrix
Returns
A vector containing the indices of the diagonal entries
Definition at line 2336 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows().
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices().
extract_diag_indices() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices (DenseVector< IT_, IT_ > & diag_indices) const inline
extract main diagonal vector from matrix
Parameters
[out] diag_indices A vector containing the indices of the diagonal entries
Definition at line 2323 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and XASSERTM.
format() [1/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (DT_ value = DT_(0)) inline inherited
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to be set (defaults to 0)
Definition at line 847 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::MemoryPool::set_memory(), and FEAT::value.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Assembly::GradPresDivVeloAssembler::assemble(), FEAT::Assembly::GradOperatorAssembler::assemble(), FEAT::Assembly::StokesFBMAssembler< MeshType_ >::assemble_characteristic_vector(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_conc(), FEAT::Meshopt::MeshConcentrationFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_grad_h(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_numeric(), FEAT::Solver::ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >::init_symbolic(), and FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric().
format() [2/2]
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::format (Random & rng, DT_ min, DT_ max) inline inherited
Reset all elements of the container to random values.
Parameters
[in] rng The random number generator.
[in] min Lower rng bound.
[in] max Upper rng bound.
Definition at line 860 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, and FEAT::MemoryPool::set_memory().
get_checkpoint_size()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::get_checkpoint_size (const LAFEM::SerialConfig & config) inline inherited
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 1009 of file container.hpp.
get_elements()
template<typename DT_ , typename IT_ > const std::vector< DT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements () const inline inherited
Returns a list of all data arrays.
Returns
A list of all data arrays.
Definition at line 1059 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::convert().
get_elements_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size () const inline inherited
Returns a list of all data array sizes.
Returns
A list of all data array sizes.
Definition at line 1079 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements_size.
get_indices()
template<typename DT_ , typename IT_ > const std::vector< IT_ * > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices () const inline inherited
Returns a list of all Index arrays.
Returns
A list of all Index arrays.
Definition at line 1069 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
get_indices_size()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size () const inline inherited
Returns a list of all Index array sizes.
Returns
A list of all Index array sizes.
Definition at line 1089 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices_size.
get_length_of_line()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::get_length_of_line (const Index row) const inline
Returns the number of NNZ-elements of the selected row.
Definition at line 2495 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr().
get_num_nodes_domain()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::get_num_nodes_domain () const inline
Definition at line 2540 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows().
get_num_nodes_image()
template<typename DT_ , typename IT_ = Index> Index FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::get_num_nodes_image () const inline
Definition at line 2546 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns().
get_scalar_dt()
template<typename DT_ , typename IT_ > const std::vector< DT_ > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt () const inline inherited
Returns a list of all scalar values with datatype dt.
Returns
A list of all scalars with datatype dt.
Definition at line 1109 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt.
get_scalar_index()
template<typename DT_ , typename IT_ > const std::vector< Index > & FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index () const inline inherited
Returns a list of all scalar values with datatype index.
Returns
A list of all scalars with datatype index.
Definition at line 1099 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
image_begin()
template<typename DT_ , typename IT_ = Index> ImageIterator FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin (Index domain_node) const inline
Definition at line 2552 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and XASSERTM.
image_end()
template<typename DT_ , typename IT_ = Index> ImageIterator FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end (Index domain_node) const inline
Definition at line 2559 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and XASSERTM.
layout()
template<typename DT_ , typename IT_ = Index> SparseLayout< IT_, layout_id > FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout () const inline
Retrieve convenient sparse matrix layout object.
Returns
An object containing the sparse matrix layout.
Definition at line 1152 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, and FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
lump_rows() [1/2]
template<typename DT_ , typename IT_ = Index> VectorTypeL FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows () const inline
Returns the lumped rows vector.
Each entry in the returned lumped rows vector contains the the sum of all matrix elements in the corresponding row.
Returns
The lumped vector.
Definition at line 2261 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_l(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows().
lump_rows() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows (VectorTypeL & lump) const inline
Definition at line 2245 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERTM.
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows().
max_abs_element()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::max_abs_element () const inline
Retrieve the absolute maximum value of this matrix.
Returns
The largest absolute value.
Definition at line 1519 of file sparse_matrix_csr.hpp.
References FEAT::Math::abs(), ASSERT, FEAT::MemoryPool::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
max_element()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::max_element () const inline
Retrieve the maximum value of this matrix.
Returns
The largest value.
Definition at line 1561 of file sparse_matrix_csr.hpp.
References ASSERT, FEAT::MemoryPool::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
min_abs_element()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::min_abs_element () const inline
Retrieve the absolute minimum value of this matrix.
Returns
The smallest absolute value
Definition at line 1540 of file sparse_matrix_csr.hpp.
References FEAT::Math::abs(), ASSERT, FEAT::MemoryPool::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
min_element()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::min_element () const inline
Retrieve the minimum value of this matrix.
Returns
The smallest value.
Definition at line 1581 of file sparse_matrix_csr.hpp.
References ASSERT, FEAT::MemoryPool::copy(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
move()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::move (Container< DT_, IT_ > && other) inline inherited
Assignment move operation.
Move another container to the current one.
Parameters
[in] other The source container.
Definition at line 988 of file container.hpp.
References FEAT::MemoryPool::release_memory().
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator=(), and FEAT::LAFEM::VectorMirror< DT_, IT_ >::operator=().
name()
template<typename DT_ , typename IT_ = Index> static String FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::name () inline static
Returns a descriptive string.
Returns
A string describing the container.
Definition at line 1348 of file sparse_matrix_csr.hpp.
norm_frobenius()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::norm_frobenius () const inline
Calculates the Frobenius norm of this matrix.
Returns
The Frobenius norm of this matrix.
Definition at line 1429 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
operator()()
template<typename DT_ , typename IT_ = Index> DT_ FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator() (Index row, Index col) const inline
Retrieve specific matrix element.
Parameters
[in] row The row of the matrix element.
[in] col The column of the matrix element.
Returns
Specific matrix element.
Definition at line 1127 of file sparse_matrix_csr.hpp.
References ASSERT, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
operator=() [1/2]
template<typename DT_ , typename IT_ = Index> SparseMatrixCSR & FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator= (const SparseLayout< IT_, layout_id > & layout_in) inline
Assignment operator.
Parameters
[in] layout_in A sparse matrix layout.
Assigns a new matrix layout, discarding all old data
Definition at line 819 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::MemoryPool::increase_memory(), and FEAT::MemoryPool::release_memory().
operator=() [2/2]
template<typename DT_ , typename IT_ = Index> SparseMatrixCSR & FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator= (SparseMatrixCSR< DT_, IT_ > && other) inline
Move operator.
Parameters
[in] other The source matrix.
Moves another matrix to the target matrix.
Definition at line 543 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::move().
permute()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute (Adjacency::Permutation & perm_row, Adjacency::Permutation & perm_col) inline
Permutate matrix rows and columns according to the given Permutations.
Definition at line 2344 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::Adjacency::Permutation::get_perm_pos(), FEAT::Adjacency::Permutation::inverse(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::Adjacency::Permutation::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERTM.
radius_column()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_column (Index & radius, Index & radius_i) const inline
Retrieve maximum radius among all column.
The radius is defined as the maximal distance to the main diagonal
Parameters
[out] radius The maximum radius.
[out] radius_i The column, where the radius is maximal.
Definition at line 1336 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::clone(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_row(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
radius_row()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_row (Index & radius, Index & radius_i) const inline
Retrieve maximum radius among all rows.
The radius is defined as the maximal distance to the main diagonal
Parameters
[out] radius The maximum radius.
[out] radius_i The row, where the radius is maximal.
Definition at line 1300 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::Math::max(), FEAT::Math::min(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows().
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_column().
read_from() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from (FileMode mode, std::istream & file) inline
Read in matrix from stream.
Parameters
[in] mode The used file format.
[in] file The stream that shall be read in.
Definition at line 898 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements, FEAT::LAFEM::Container< DT_, IT_ >::_elements_size, FEAT::LAFEM::Container< DT_, IT_ >::_indices, FEAT::LAFEM::Container< DT_, IT_ >::_indices_size, FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index, FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_csr, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XABORTM.
read_from() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from (FileMode mode, String filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 880 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), and XABORTM.
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
restore_from_checkpoint_data()
template<typename DT_ , typename IT_ > void FEAT::LAFEM::Container< DT_, IT_ >::restore_from_checkpoint_data (std::vector< char > & data) inline inherited
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 1015 of file container.hpp.
References FEAT::LAFEM::fm_binary.
row_norm2()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2 (VectorTypeL & row_norms) const inline
Computes the 2-norm for every row.
Parameters
[in] row_norms For every row, this left-vector will contain its 2-norm
Definition at line 1448 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), ASSERTM, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements().
row_norm2sqr() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr (VectorTypeL & row_norms) const inline
Computes the square of the 2-norm for every row.
Parameters
[out] row_norms For every row, this left-vector will contain the square of its 2-norm
Definition at line 1467 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), ASSERTM, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements().
row_norm2sqr() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr (VectorTypeL & row_norms, const VectorTypeR & scal) const inline
Computes the square of the 2-norm for every row, where every row is scaled by a vector.
Parameters
[out] row_norms For every (scaled) row, this left-vector will contain the square of its 2-norm
[in] scal The scaling vector
This computes
\[ row\_norms_i = \sum_{j=0}^{n-1} scal_j (this_{ij})^2 \]
and is used to compute
\[ \mathrm{tr}(B^T \mathrm{diag}(A) B) \]
Definition at line 1499 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), ASSERTM, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements().
row_ptr() [1/2]
template<typename DT_ , typename IT_ = Index> IT_ * FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr () inline
Retrieve row start index array.
Returns
Row start index array.
Definition at line 1238 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_indices.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_mat_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_numeric(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::bandwidth_row(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert_reverse(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_weak_matrix_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::get_length_of_line(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::GenericUmfpack< Matrix_ >::init_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::make_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr_neumann(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_row(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out().
row_ptr() [2/2]
template<typename DT_ , typename IT_ = Index> IT_ const * FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr () const inline
Definition at line 1246 of file sparse_matrix_csr.hpp.
rows()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows () const inline
Retrieve matrix row count.
Returns
Matrix row count.
Definition at line 1163 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::Solver::SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::SORPrecondWithBackend(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::Solver::SSORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::SSORPrecondWithBackend(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_mat_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_numeric(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::bandwidth_row(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::create_vector_l(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_weak_matrix_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::get_num_nodes_domain(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::Solver::GenericUmfpack< Matrix_ >::init_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_row(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out().
scale()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale (const SparseMatrixCSR< DT_, IT_ > & x, const DT_ alpha) inline
Calculate \(this \leftarrow \alpha~ x \).
Parameters
[in] x The matrix to be scaled.
[in] alpha A scalar to scale x with.
Definition at line 1409 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERTM.
scale_cols()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols (const SparseMatrixCSR< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & s) inline
Calculate \(this_{ij} \leftarrow x_{ij}\cdot s_j\).
Parameters
[in] x The matrix whose columns are to be scaled.
[in] s The vector to the scale the columns by.
Definition at line 1702 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERTM.
scale_rows()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows (const SparseMatrixCSR< DT_, IT_ > & x, const DenseVector< DT_, IT_ > & s) inline
Calculate \(this_{ij} \leftarrow x_{ij}\cdot s_i\).
Parameters
[in] x The matrix whose rows are to be scaled.
[in] s The vector to the scale the rows by.
Definition at line 1679 of file sparse_matrix_csr.hpp.
References FEAT::Statistics::add_flops(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::TimeStamp::elapsed(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XASSERTM.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer().
serialize()
template<typename DT_ , typename IT_ = Index> template<typename DT2_ = DT_, typename IT2_ = IT_> std::vector< char > FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::serialize (const LAFEM::SerialConfig & config = SerialConfig()) const inline
Serialization of complete container entity.
Parameters
[in] config LAFEM::SerialConfig, a struct describing the serialize configuration.
Note
the corresponding configure flags 'zlib' and/or 'zfp' need to be added in the build-id at the configure call.
Serialize a complete container entity into a single binary array.
See FEAT::LAFEM::Container::_serialize for details.
Definition at line 869 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::fm_csr.
set_checkpoint_data()
template<typename DT_ , typename IT_ > std::uint64_t FEAT::LAFEM::Container< DT_, IT_ >::set_checkpoint_data (std::vector< char > & data, const LAFEM::SerialConfig & config) inline inherited
Definition at line 1021 of file container.hpp.
References FEAT::LAFEM::fm_binary.
shrink()
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink (DT_ eps) inline
Shrink matrix and drop small values.
Shrinks the matrix by dropping all values, that have a smaller absoute value than eps.
Parameters
[in] eps The dropping criterion
Definition at line 2426 of file sparse_matrix_csr.hpp.
References FEAT::Math::abs(), FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
size()
template<typename DT_ , typename IT_ > template<Perspective = Perspective::native> Index FEAT::LAFEM::Container< DT_, IT_ >::size () const inline inherited
Returns the containers size.
Returns
The containers size.
The template parameter of type Perspective is used in blocked containers to switch between the raw size and the size, when every block is treated as one entry.
Most containers like SparseMatrixCSR ignore this template parameter.
Definition at line 1127 of file container.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::HyperelasticityFunctional(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::UnitFilter(), FEAT::LAFEM::UnitFilterBlocked< DT_, IT_, BlockSize_ >::UnitFilterBlocked(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::_compute_lambda_uniform(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_gather_data(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_scatter_data(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_trace_double_mat_mult(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::allgather(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::apply(), FEAT::LAFEM::NullMatrix< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::apply(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::apply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Solver::ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >::apply(), FEAT::Assembly::TraceAssembler< Trafo_ >::assemble_flow_accum(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseVector< DT_, IT_ >::compare_layout(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_invert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::component_product(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::download(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::download_vector(), FEAT::LAFEM::Container< DT_, IT_ >::empty(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::extract_diag_indices(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag_indices(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_def(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_rhs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::gather(), FEAT::LAFEM::MetaMatrixTestBase< DataType_, IndexType_ >::gen_system(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::get_num_local_dofs(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::get_num_nodes_image(), FEAT::LAFEM::DenseVector< DT_, IT_ >::inflate_to_blocks(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_symbolic(), FEAT::Assembly::FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >::interpolate(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::map_local_to_global_index(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::mask_scatter(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::DenseVector< DT_, IT_ >::norm2(), FEAT::LAFEM::DenseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::scale(), FEAT::LAFEM::DenseVector< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::DenseVector< DT_, IT_ >::triple_dot(), FEAT::Global::AlgDofPartiVector< LocalVector_, Mirror_ >::upload(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::upload_numeric(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::upload_vector(), FEAT::LAFEM::Container< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), and FEAT::LAFEM::SparseVector< DT_, IT_ >::write_out().
transpose() [1/2]
template<typename DT_ , typename IT_ = Index> SparseMatrixCSR FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose () const inline
Calculate \(this^\top \).
Returns
The transposed matrix
Definition at line 1601 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::bandwidth_column(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::radius_column(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose().
transpose() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose (const SparseMatrixCSR< DT_, IT_ > & x) inline
Calculate \(this \leftarrow x^\top \).
Parameters
[in] x The matrix to be transposed.
Definition at line 1613 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::assign(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val().
used_elements()
template<typename DT_ , typename IT_ = Index> template<Perspective = Perspective::native> Index FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements () const inline
Retrieve non zero element count.
Returns
Non zero element count.
Definition at line 1185 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index.
Referenced by FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_assemble_data_mirrors(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::apply(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_symbolic(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::max_abs_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::max_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::min_abs_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::min_element(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_norm2sqr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out().
val() [1/2]
template<typename DT_ , typename IT_ = Index> DT_ * FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val () inline
Retrieve non zero element array.
Returns
Non zero element array.
Definition at line 1217 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::Container< DT_, IT_ >::_elements.
Referenced by FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_asm_local_schur_matrix(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::_upload_own(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_double_mat_product(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::add_mat_mat_product(), FEAT::Solver::CuSolverLU::apply(), FEAT::Solver::CuSolverQR::apply(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::asm_adp_numeric(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert_reverse(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::extract_diag(), FEAT::Global::AlgDofPartiMatrix< LocalMatrix_, Mirror_ >::filter_matrix(), FEAT::LAFEM::UnitFilter< DT_, IT_ >::filter_weak_matrix_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::gather(), FEAT::Solver::DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >::init_numeric(), FEAT::Solver::SaddleUmfpackMean< DT_, IT_, dim_ >::init_numeric(), FEAT::Solver::GenericUmfpack< Matrix_ >::init_numeric(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::lump_rows(), FEAT::LAFEM::SparseMatrixFactory< DT_, IT_ >::make_csr(), FEAT::LAFEM::PointstarFactoryFE< DataType_, IndexType_ >::matrix_csr_neumann(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::max_abs_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::max_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::min_abs_element(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::min_element(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::multiply(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::norm_frobenius(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::permute(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_cols(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::scale_rows(), FEAT::LAFEM::MatrixMirror< DT_, IT_ >::scatter_axpy(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::shrink(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::transpose(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out().
val() [2/2]
template<typename DT_ , typename IT_ = Index> DT_ const * FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val () const inline
Definition at line 1225 of file sparse_matrix_csr.hpp.
write_out() [1/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out (FileMode mode, std::ostream & file, bool symmetric = false) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] file The stream that shall be written to.
[in] symmetric Should we store only the lower half of the matrix in symmetric format?
Warning
This routine does no check on symmetric properties of the source matrix!
Only uses symmetric properties if mode is mtx!
Definition at line 1062 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::fm_binary, FEAT::LAFEM::fm_csr, FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), and XABORTM.
write_out() [2/2]
template<typename DT_ , typename IT_ = Index> void FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out (FileMode mode, String filename, bool symmetric = false) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
[in] symmetric Should we store only the lower half of the matrix in symmetric format?
Warning
This routine does no check on symmetric properties of the source matrix!
Only uses symmetric properties if mode is mtx!
Definition at line 1040 of file sparse_matrix_csr.hpp.
References FEAT::LAFEM::fm_mtx, FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out(), and XABORTM.
Referenced by FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out().
Friends And Related Function Documentation
operator<<
template<typename DT_ , typename IT_ = Index> std::ostream & operator<< (std::ostream & lhs, const SparseMatrixCSR< DT_, IT_ > & b) friend
SparseMatrixCSR streaming operator.
Parameters
[in] lhs The target stream.
[in] b The matrix to be streamed.
Definition at line 2634 of file sparse_matrix_csr.hpp.
operator==
template<typename DT_ , typename IT_ = Index> bool operator== (const SparseMatrixCSR< DT_, IT_ > & a, const SparseMatrixCSR< DT_, IT_ > & b) friend
SparseMatrixCSR comparison operator.
Parameters
[in] a A matrix to compare with.
[in] b A matrix to compare with.
Definition at line 2572 of file sparse_matrix_csr.hpp.
Member Data Documentation
_elements
template<typename DT_ , typename IT_ > std::vector<DT_*> FEAT::LAFEM::Container< DT_, IT_ >::_elements protected inherited
List of pointers to all datatype dependent arrays.
Definition at line 228 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVector< DT_, IT_ >::elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::elements(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::elements(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::val(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::val(), and FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out().
_elements_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_elements_size protected inherited
List of corresponding datatype array sizes.
Definition at line 232 of file container.hpp.
Referenced by FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::format(), FEAT::LAFEM::Container< DT_, IT_ >::get_elements_size(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_foreign_memory
template<typename DT_ , typename IT_ > bool FEAT::LAFEM::Container< DT_, IT_ >::_foreign_memory protected inherited
do we use memory that we did not allocate, nor are we allowed to free it - this mostly holds true, if the container is a ranged slice of another one
Definition at line 240 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), and FEAT::LAFEM::Container< DT_, IT_ >::clear().
_indices
template<typename DT_ , typename IT_ > std::vector<IT_*> FEAT::LAFEM::Container< DT_, IT_ >::_indices protected inherited
List of pointers to all IT_ dependent arrays.
Definition at line 230 of file container.hpp.
Referenced by FEAT::LAFEM::DenseVector< DT_, IT_ >::DenseVector(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::DenseVectorBlocked(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::~Container(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::clear(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::col_ind(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::col_ind(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_begin(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_begin(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_begin(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::image_end(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::image_end(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::image_end(), FEAT::LAFEM::SparseVector< DT_, IT_ >::indices(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::indices(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::offsets(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_numbers(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::row_ptr(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::row_ptr(), and FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sort().
_indices_size
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_indices_size protected inherited
List of corresponding IT_ array sizes.
Definition at line 234 of file container.hpp.
Referenced by FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::Container< DT_, IT_ >::get_indices_size(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), and FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from().
_scalar_dt
template<typename DT_ , typename IT_ > std::vector<DT_> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_dt protected inherited
List of scalars with datatype DT_.
Definition at line 238 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), and FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_dt().
_scalar_index
template<typename DT_ , typename IT_ > std::vector<Index> FEAT::LAFEM::Container< DT_, IT_ >::_scalar_index protected inherited
List of scalars with datatype index.
Definition at line 236 of file container.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::Container(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::DenseMatrix(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::MatrixMirrorBuffer(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::SparseMatrixBanded(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::SparseMatrixBCSR(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::SparseMatrixCSCR(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::SparseMatrixCSR(), FEAT::LAFEM::SparseVector< DT_, IT_ >::SparseVector(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::SparseVectorBlocked(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::VectorMirror(), FEAT::LAFEM::Container< DT_, IT_ >::_deserialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialize(), FEAT::LAFEM::Container< DT_, IT_ >::_serialized_size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::alloc_increment(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::alloc_increment(), FEAT::LAFEM::SparseVector< DT_, IT_ >::allocated_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::allocated_elements(), FEAT::LAFEM::Container< DT_, IT_ >::bytes(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::columns(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::columns(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::columns(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::columns(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::convert(), FEAT::LAFEM::DenseVector< DT_, IT_ >::convert(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::convert(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::entries_per_nonzero(), FEAT::LAFEM::Container< DT_, IT_ >::get_scalar_index(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::layout(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::layout(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::num_indices(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::num_of_offsets(), FEAT::LAFEM::SparseVector< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator()(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::operator=(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::operator=(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::operator=(), FEAT::LAFEM::DenseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::read_from(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::read_from(), FEAT::LAFEM::SparseVector< DT_, IT_ >::read_from(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::rows(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::rows(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::rows(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::rows(), FEAT::LAFEM::Container< DT_, IT_ >::size(), FEAT::LAFEM::SparseVector< DT_, IT_ >::sorted(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::sorted(), FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBanded< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVector< DT_, IT_ >::used_elements(), FEAT::LAFEM::SparseVectorBlocked< DT_, IT_, BlockSize_ >::used_elements(), FEAT::LAFEM::SparseMatrixCSCR< DT_, IT_ >::used_rows(), and FEAT::LAFEM::MatrixMirrorBuffer< DT_, IT_ >::val_size().
is_global
template<typename DT_ , typename IT_ = Index> constexpr bool FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::is_global = false static constexpr
Definition at line 301 of file sparse_matrix_csr.hpp.
is_local
template<typename DT_ , typename IT_ = Index> constexpr bool FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::is_local = true static constexpr
Definition at line 302 of file sparse_matrix_csr.hpp.
layout_id
template<typename DT_ , typename IT_ = Index> constexpr SparseLayoutId FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::layout_id = SparseLayoutId::lt_csr static constexpr
Our used layout type.
Definition at line 290 of file sparse_matrix_csr.hpp.
The documentation for this class was generated from the following files:
kernel/lafem/forward.hpp
kernel/lafem/sparse_matrix_csr.hpp