FEAT: FEAT::Space::ExtVtkWriter< Trafo_ > Class Template Reference
FEAT::Space::ExtVtkWriter< Trafo_ > Class Template Reference
Extended VTK writer class template.
#include <ext_vtk_writer.hpp>
Public Types
typedef TrafoType::MeshType MeshType
typedef Geometry::ConformalMesh< ShapeType > RefMeshType
typedef MeshType::ShapeType ShapeType
typedef Trafo_ TrafoType
Public Member Functions
ExtVtkWriter (const TrafoType &trafo, Index num_refines=1)
void close ()
Closes the VTK file.
bool open (String filename)
Opens a VTK files and writes basic information.
template<typename Space_ , typename T_ >
void write_gradients (String name, const Space_ &space, const T_ *data)
Writes a finite element function gradient field to the VTK file.
template<typename Space_ , typename T_ >
void write_hessians (String name, const Space_ &space, const T_ *data)
Writes a finite element function Hessian field to the VTK file.
template<typename Space_ , typename T_ >
void write_values (String name, const Space_ &space, const T_ *data)
Writes a finite element function to the VTK file.
template<typename Space_ , typename VectorType_ >
void write_values_blocked (String name, const Space_ &space, const VectorType_ &v)
Writes a finite element function to the VTK file.
Protected Types
typedef TrafoType::template Evaluator ::Type TrafoEval
Protected Member Functions
void get_dom_point (typename TrafoEval::DomainPointType &dom_point, Index i) const
void write_indices ()
void write_vertices ()
Protected Attributes
std::ofstream _ofs
RefMeshType * _ref_mesh
const TrafoType & _trafo
Friends
struct Intern::ExtVtkGradWriter< true >
struct Intern::ExtVtkHessWriter< true >
struct Intern::ExtVtkValueWriter< true >
Detailed Description
template<typename Trafo_>
class FEAT::Space::ExtVtkWriter< Trafo_ >
Extended VTK writer class template.
This class template implements a VTK writer which exports Finite Element functions evaluated on a locally refined mesh instead of a projection in the mesh's vertices or cells.
Author
Peter Zajac
Definition at line 89 of file ext_vtk_writer.hpp.
Member Typedef Documentation
MeshType
template<typename Trafo_ > typedef TrafoType::MeshType FEAT::Space::ExtVtkWriter< Trafo_ >::MeshType
Definition at line 97 of file ext_vtk_writer.hpp.
RefMeshType
template<typename Trafo_ > typedef Geometry::ConformalMesh<ShapeType> FEAT::Space::ExtVtkWriter< Trafo_ >::RefMeshType
Definition at line 99 of file ext_vtk_writer.hpp.
ShapeType
template<typename Trafo_ > typedef MeshType::ShapeType FEAT::Space::ExtVtkWriter< Trafo_ >::ShapeType
Definition at line 98 of file ext_vtk_writer.hpp.
TrafoEval
template<typename Trafo_ > typedef TrafoType::template Evaluator ::Type FEAT::Space::ExtVtkWriter< Trafo_ >::TrafoEval protected
Definition at line 102 of file ext_vtk_writer.hpp.
TrafoType
template<typename Trafo_ > typedef Trafo_ FEAT::Space::ExtVtkWriter< Trafo_ >::TrafoType
Definition at line 96 of file ext_vtk_writer.hpp.
Constructor & Destructor Documentation
ExtVtkWriter()
template<typename Trafo_ > FEAT::Space::ExtVtkWriter< Trafo_ >::ExtVtkWriter (const TrafoType & trafo, Index num_refines = 1) inline explicit
Definition at line 110 of file ext_vtk_writer.hpp.
~ExtVtkWriter()
template<typename Trafo_ > virtual FEAT::Space::ExtVtkWriter< Trafo_ >::~ExtVtkWriter () inline virtual
Definition at line 131 of file ext_vtk_writer.hpp.
Member Function Documentation
close()
template<typename Trafo_ > void FEAT::Space::ExtVtkWriter< Trafo_ >::close () inline
Closes the VTK file.
Definition at line 173 of file ext_vtk_writer.hpp.
get_dom_point()
template<typename Trafo_ > void FEAT::Space::ExtVtkWriter< Trafo_ >::get_dom_point (typename TrafoEval::DomainPointType & dom_point, Index i) const inline protected
Definition at line 610 of file ext_vtk_writer.hpp.
open()
template<typename Trafo_ > bool FEAT::Space::ExtVtkWriter< Trafo_ >::open (String filename) inline
Opens a VTK files and writes basic information.
Definition at line 142 of file ext_vtk_writer.hpp.
References FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::version_major, FEAT::version_minor, and FEAT::version_patch.
write_gradients()
template<typename Trafo_ > template<typename Space_ , typename T_ > void FEAT::Space::ExtVtkWriter< Trafo_ >::write_gradients (String name, const Space_ & space, const T_ * data) inline
Writes a finite element function gradient field to the VTK file.
Parameters
[in] name The name of the variable for the VTK file.
[in] space A transient reference to the finite element space.
[in] data An transient array representing the coefficient vector of the finite element function.
Definition at line 350 of file ext_vtk_writer.hpp.
References FEAT::dom_point, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::grad, and XASSERT.
write_hessians()
template<typename Trafo_ > template<typename Space_ , typename T_ > void FEAT::Space::ExtVtkWriter< Trafo_ >::write_hessians (String name, const Space_ & space, const T_ * data) inline
Writes a finite element function Hessian field to the VTK file.
Parameters
[in] name The name of the variable for the VTK file.
[in] space A transient reference to the finite element space.
[in] data An transient array representing the coefficient vector of the finite element function.
Definition at line 436 of file ext_vtk_writer.hpp.
References FEAT::dom_point, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::hess, and XASSERT.
write_indices()
template<typename Trafo_ > void FEAT::Space::ExtVtkWriter< Trafo_ >::write_indices () inline protected
Definition at line 566 of file ext_vtk_writer.hpp.
write_values()
template<typename Trafo_ > template<typename Space_ , typename T_ > void FEAT::Space::ExtVtkWriter< Trafo_ >::write_values (String name, const Space_ & space, const T_ * data) inline
Writes a finite element function to the VTK file.
Parameters
[in] name The name of the variable for the VTK file.
[in] space A transient reference to the finite element space.
[in] data An transient array representing the coefficient vector of the finite element function.
Definition at line 272 of file ext_vtk_writer.hpp.
References FEAT::dom_point, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), FEAT::value, and XASSERT.
write_values_blocked()
template<typename Trafo_ > template<typename Space_ , typename VectorType_ > void FEAT::Space::ExtVtkWriter< Trafo_ >::write_values_blocked (String name, const Space_ & space, const VectorType_ & v) inline
Writes a finite element function to the VTK file.
Parameters
[in] name The name of the variable for the VTK file.
[in] space A transient reference to the finite element space.
[in] v The transient blocked coefficient vector of the finite element function.
Definition at line 191 of file ext_vtk_writer.hpp.
References FEAT::dom_point, FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::get_num_entities(), and FEAT::value.
write_vertices()
template<typename Trafo_ > void FEAT::Space::ExtVtkWriter< Trafo_ >::write_vertices () inline protected
Definition at line 519 of file ext_vtk_writer.hpp.
Friends And Related Function Documentation
Intern::ExtVtkGradWriter< true >
template<typename Trafo_ > friend struct Intern::ExtVtkGradWriter< true > friend
Definition at line 1 of file ext_vtk_writer.hpp.
Intern::ExtVtkHessWriter< true >
template<typename Trafo_ > friend struct Intern::ExtVtkHessWriter< true > friend
Definition at line 1 of file ext_vtk_writer.hpp.
Intern::ExtVtkValueWriter< true >
template<typename Trafo_ > friend struct Intern::ExtVtkValueWriter< true > friend
Definition at line 1 of file ext_vtk_writer.hpp.
Member Data Documentation
_ofs
template<typename Trafo_ > std::ofstream FEAT::Space::ExtVtkWriter< Trafo_ >::_ofs protected
Definition at line 106 of file ext_vtk_writer.hpp.
_ref_mesh
template<typename Trafo_ > RefMeshType* FEAT::Space::ExtVtkWriter< Trafo_ >::_ref_mesh protected
Definition at line 107 of file ext_vtk_writer.hpp.
_trafo
template<typename Trafo_ > const TrafoType& FEAT::Space::ExtVtkWriter< Trafo_ >::_trafo protected
Definition at line 105 of file ext_vtk_writer.hpp.
The documentation for this class was generated from the following file:
kernel/space/ext_vtk_writer.hpp