FEAT: FEAT::Geometry::MeshAtlas< Mesh_ > Class Template Reference
FEAT::Geometry::MeshAtlas< Mesh_ > Class Template Reference
Mesh Atlas class template.
#include <mesh_atlas.hpp>
Public Types
typedef Atlas::ChartBase< MeshType > MeshChartType
our chart base-class type
typedef Mesh_ MeshType
our mesh type
typedef MeshType::VertexType VertexType
our vertex type (aka world point type)
Public Member Functions
MeshAtlas ()
default CTOR
MeshAtlas (const MeshAtlas &)=delete
deleted copy CTOR
MeshAtlas (MeshAtlas &&other)=default
move CTOR
virtual ~MeshAtlas ()
virtual DTOR
bool add_mesh_chart (const String &name, std::unique_ptr< MeshChartType > chart, bool replace=false)
Inserts a new chart into the map.
std::size_t bytes () const
MeshChartType * find_mesh_chart (const String &name)
Searches for a mesh chart.
const MeshChartType * find_mesh_chart (const String &name) const
Searches for a mesh chart.
std::deque< String > get_chart_names () const
Returns the names of all charts of this atlas.
const MeshChartMap & get_mesh_chart_map () const
Returns a const reference to the chart map.
MeshAtlas & operator= (const MeshAtlas &)=delete
deleted copy-assignment operator
MeshAtlas & operator= (MeshAtlas &&other)=default
move-assignment operator
void transform (const VertexType &origin, const VertexType &angles, const VertexType &offset)
Applies a "proper rigid" transformation onto the atlas.
Static Public Member Functions
static std::unique_ptr< MeshAtlas > make_unique ()
Creates a new MeshAtlas on the heap and returns a unique pointer to it.
Protected Types
typedef std::map< String, std::unique_ptr< MeshChartType > > MeshChartMap
our chart map type
Protected Attributes
MeshChartMap _chart_map
our chart map
Detailed Description
template<typename Mesh_>
class FEAT::Geometry::MeshAtlas< Mesh_ >
Mesh Atlas class template.
Template Parameters
Mesh_ The type of the mesh that is to be parameterized by this atlas, i.e. ConformalMesh
Author
Peter Zajac
Definition at line 33 of file mesh_atlas.hpp.
Member Typedef Documentation
MeshChartMap
template<typename Mesh_ > typedef std::map<String, std::unique_ptr<MeshChartType> > FEAT::Geometry::MeshAtlas< Mesh_ >::MeshChartMap protected
our chart map type
Definition at line 45 of file mesh_atlas.hpp.
MeshChartType
template<typename Mesh_ > typedef Atlas::ChartBase<MeshType> FEAT::Geometry::MeshAtlas< Mesh_ >::MeshChartType
our chart base-class type
Definition at line 39 of file mesh_atlas.hpp.
MeshType
template<typename Mesh_ > typedef Mesh_ FEAT::Geometry::MeshAtlas< Mesh_ >::MeshType
our mesh type
Definition at line 37 of file mesh_atlas.hpp.
VertexType
template<typename Mesh_ > typedef MeshType::VertexType FEAT::Geometry::MeshAtlas< Mesh_ >::VertexType
our vertex type (aka world point type)
Definition at line 41 of file mesh_atlas.hpp.
Constructor & Destructor Documentation
MeshAtlas()
template<typename Mesh_ > FEAT::Geometry::MeshAtlas< Mesh_ >::MeshAtlas () inline
default CTOR
Definition at line 52 of file mesh_atlas.hpp.
Referenced by FEAT::Geometry::MeshAtlas< Mesh_ >::make_unique().
~MeshAtlas()
template<typename Mesh_ > virtual FEAT::Geometry::MeshAtlas< Mesh_ >::~MeshAtlas () inline virtual
virtual DTOR
Definition at line 69 of file mesh_atlas.hpp.
Member Function Documentation
add_mesh_chart()
template<typename Mesh_ > bool FEAT::Geometry::MeshAtlas< Mesh_ >::add_mesh_chart (const String & name, std::unique_ptr< MeshChartType > chart, bool replace = false) inline
Inserts a new chart into the map.
Parameters
[in] name The name of the chart to be inserted.
[in] chart A unique pointer to the mesh chart to be inserted. The atlas takes ownership of the chart object and deletes it upon destruction.
[in] replace Specifies whether to replace an old chart with the same name if it already exists.
Returns
True if the MeshChart was successfully inserted, meaning a chart of that name was either not present yet, or it was present and replace was set to true.
Definition at line 111 of file mesh_atlas.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::_chart_map.
Referenced by FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_atlas().
bytes()
template<typename Mesh_ > std::size_t FEAT::Geometry::MeshAtlas< Mesh_ >::bytes () const inline
Returns
The size of dynamically allocated memory in bytes.
Definition at line 86 of file mesh_atlas.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::_chart_map.
find_mesh_chart() [1/2]
template<typename Mesh_ > MeshChartType * FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart (const String & name) inline
Searches for a mesh chart.
Parameters
[in] name The name of the mesh chart to the found.
Returns
A pointer to the mesh chart associated with name, or nullptr if no chart with that name was found. This returned pointer does not transfer ownership and must therefore not be deleted by the caller.
Definition at line 164 of file mesh_atlas.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::_chart_map.
Referenced by FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_add(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_max(), FEAT::Meshopt::ChartDistanceFunction< ElementalFunction_, Trafo_, RefCellTrafo_ >::compute_dist_min(), FEAT::Geometry::MeshNodeLinker< RootMesh_ >::execute(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_atlas(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_root_node(), and FEAT::Geometry::MeshFileWriter::write_atlas().
find_mesh_chart() [2/2]
template<typename Mesh_ > const MeshChartType * FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart (const String & name) const inline
Searches for a mesh chart.
Parameters
[in] name The name of the mesh chart to the found.
Returns
A pointer to the mesh chart associated with name, or nullptr if no chart with that name was found. This returned pointer does not transfer ownership and must therefore not be deleted by the caller.
Definition at line 173 of file mesh_atlas.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::_chart_map.
get_chart_names()
template<typename Mesh_ > std::deque< String > FEAT::Geometry::MeshAtlas< Mesh_ >::get_chart_names () const inline
Returns the names of all charts of this atlas.
Definition at line 133 of file mesh_atlas.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::_chart_map.
Referenced by FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_atlas(), and FEAT::Geometry::MeshFileWriter::write_atlas().
get_mesh_chart_map()
template<typename Mesh_ > const MeshChartMap & FEAT::Geometry::MeshAtlas< Mesh_ >::get_mesh_chart_map () const inline
Returns a const reference to the chart map.
Returns
A const reference to the chart map
Definition at line 148 of file mesh_atlas.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::_chart_map.
make_unique()
template<typename Mesh_ > static std::unique_ptr< MeshAtlas > FEAT::Geometry::MeshAtlas< Mesh_ >::make_unique () inline static
Creates a new MeshAtlas on the heap and returns a unique pointer to it.
Returns
A unique pointer to the new MeshAtlas object.
Definition at line 80 of file mesh_atlas.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::MeshAtlas().
transform()
template<typename Mesh_ > void FEAT::Geometry::MeshAtlas< Mesh_ >::transform (const VertexType & origin, const VertexType & angles, const VertexType & offset) inline
Applies a "proper rigid" transformation onto the atlas.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any chart point x of the atlas:
Parameters
[in] origin The origin of the transformation. This is subtracted from any vertex before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): ignored
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any vertex after applying the rotation.
Definition at line 207 of file mesh_atlas.hpp.
References FEAT::Geometry::MeshAtlas< Mesh_ >::_chart_map.
Member Data Documentation
_chart_map
template<typename Mesh_ > MeshChartMap FEAT::Geometry::MeshAtlas< Mesh_ >::_chart_map protected
our chart map
Definition at line 48 of file mesh_atlas.hpp.
Referenced by FEAT::Geometry::MeshAtlas< Mesh_ >::add_mesh_chart(), FEAT::Geometry::MeshAtlas< Mesh_ >::bytes(), FEAT::Geometry::MeshAtlas< Mesh_ >::find_mesh_chart(), FEAT::Geometry::MeshAtlas< Mesh_ >::get_chart_names(), FEAT::Geometry::MeshAtlas< Mesh_ >::get_mesh_chart_map(), and FEAT::Geometry::MeshAtlas< Mesh_ >::transform().
The documentation for this class was generated from the following file:
kernel/geometry/mesh_atlas.hpp