FEAT: FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > > Class Template Reference
FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > > Class Template Reference
Class for creating MeshParts referring to a patch BaseMesh, ConformalMesh specialization.
#include <patch_meshpart_splitter.hpp>
Public Types
typedef MeshType::VertexSetType::CoordType AttributeDataType
Data type for attributes.
typedef MeshPartType::AttributeSetContainer AttributeSetContainer
Mesh attribute holder type.
typedef MeshPartType::IndexSetHolderType IndexSetHolderType
Index set holder type.
typedef Geometry::MeshPart< MeshType > MeshPartType
The MeshPart type.
typedef Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > MeshType
The mesh type.
typedef Shape_ ShapeType
Our shape type.
typedef MeshPartType::TargetSetHolderType TargetSetHolderType
Target set holder type.
Public Member Functions
PatchMeshPartSplitter (const MeshType &base_mesh, const MeshPartType &patch_mesh_part)
Constructor.
virtual ~PatchMeshPartSplitter ()
Virtual destructor.
bool build (const MeshPartType &mesh_part)
Assembles information from a MeshPart referring to the BaseMesh.
virtual void fill_attribute_sets (AttributeSetContainer &attribute_container) override
Fills the attribute sets.
virtual void fill_index_sets (std::unique_ptr< IndexSetHolderType > &index_set_holder) override
Fills the index sets.
virtual void fill_target_sets (TargetSetHolderType &target_set_holder) override
Fills the target sets.
virtual Index get_num_entities (int dim) override
Returns the number of entities.
Static Public Attributes
static constexpr int shape_dim = ShapeType::dimension
The shape dimension.
Protected Attributes
const MeshType & _base_mesh
The BaseMesh we refer to.
const AttributeSetContainer * _cur_part_attribute_container
The mesh attributes of the current BaseMesh MeshPart.
const IndexSetHolder< ShapeType > * _cur_part_topology
The topology of the current BaseMesh MeshPart.
PatchPartMapHolder< ShapeType, ShapeType::dimension > _part_holder
The BaseMesh MeshPart to PatchMeshPart MeshPart mapping information.
const MeshPartType & _patch_mesh_part
The MeshPart identifying this patch.
Detailed Description
template<typename Shape_, int num_coords_, typename Coord_>
class FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >
Class for creating MeshParts referring to a patch BaseMesh, ConformalMesh specialization.
Template Parameters
Shape_ Shape type of the mesh cells
num_coords_ World dimension
Coord_ Floating point type for vertex coordinates
Like the PatchPartMap and PatchPartMapHolder, this assembles information about the BaseMesh and PatchMeshPart first and can later be used to create several MeshParts referring to the PatchMeshPart by calling build() and then the Factory interface, one at a time.
Author
Jordi Paul
Definition at line 56 of file patch_meshpart_splitter.hpp.
Member Typedef Documentation
AttributeDataType
template<typename Shape_ , int num_coords_, typename Coord_ > typedef MeshType::VertexSetType::CoordType FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::AttributeDataType
Data type for attributes.
Definition at line 69 of file patch_meshpart_splitter.hpp.
AttributeSetContainer
template<typename Shape_ , int num_coords_, typename Coord_ > typedef MeshPartType::AttributeSetContainer FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::AttributeSetContainer
Mesh attribute holder type.
Definition at line 71 of file patch_meshpart_splitter.hpp.
IndexSetHolderType
template<typename Shape_ , int num_coords_, typename Coord_ > typedef MeshPartType::IndexSetHolderType FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::IndexSetHolderType
Index set holder type.
Definition at line 73 of file patch_meshpart_splitter.hpp.
MeshPartType
template<typename Shape_ , int num_coords_, typename Coord_ > typedef Geometry::MeshPart<MeshType> FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::MeshPartType
The MeshPart type.
Definition at line 67 of file patch_meshpart_splitter.hpp.
MeshType
template<typename Shape_ , int num_coords_, typename Coord_ > typedef Geometry::ConformalMesh<Shape_, num_coords_, Coord_> FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::MeshType
The mesh type.
Definition at line 65 of file patch_meshpart_splitter.hpp.
ShapeType
template<typename Shape_ , int num_coords_, typename Coord_ > typedef Shape_ FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::ShapeType
Our shape type.
Definition at line 61 of file patch_meshpart_splitter.hpp.
TargetSetHolderType
template<typename Shape_ , int num_coords_, typename Coord_ > typedef MeshPartType::TargetSetHolderType FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::TargetSetHolderType
Target set holder type.
Definition at line 75 of file patch_meshpart_splitter.hpp.
Constructor & Destructor Documentation
PatchMeshPartSplitter()
template<typename Shape_ , int num_coords_, typename Coord_ > FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::PatchMeshPartSplitter (const MeshType & base_mesh, const MeshPartType & patch_mesh_part) inline explicit
Constructor.
Parameters
[in] base_mesh A resident reference to the (global) BaseMesh
[in] patch_mesh_part A resident reference to the MeshPart identifying the Patch
Definition at line 100 of file patch_meshpart_splitter.hpp.
~PatchMeshPartSplitter()
template<typename Shape_ , int num_coords_, typename Coord_ > virtual FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::~PatchMeshPartSplitter () inline virtual
Virtual destructor.
Definition at line 112 of file patch_meshpart_splitter.hpp.
Member Function Documentation
build()
template<typename Shape_ , int num_coords_, typename Coord_ > bool FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::build (const MeshPartType & mesh_part) inline
Assembles information from a MeshPart referring to the BaseMesh.
Parameters
[in] mesh_part A transient reference to the basemesh patch meshpart
Returns
true if there is a nonempty cut between mesh_part and the PatchMeshPart.
Definition at line 126 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::build(), and FEAT::Geometry::MeshPart< MeshType_ >::get_mesh_attributes().
fill_attribute_sets()
template<typename Shape_ , int num_coords_, typename Coord_ > virtual void FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::fill_attribute_sets (AttributeSetContainer & attribute_container) inline override virtual
Fills the attribute sets.
Parameters
[in,out] attribute_container A transient reference to the attribute set holder whose attribute sets are to be filled.
Definition at line 157 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_attribute_sets().
fill_index_sets()
template<typename Shape_ , int num_coords_, typename Coord_ > virtual void FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::fill_index_sets (std::unique_ptr< IndexSetHolderType > & index_set_holder) inline override virtual
Fills the index sets.
Parameters
[in,out] index_set_holder A transient reference to the index set holder whose index sets are to be filled.
Definition at line 168 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::RedundantIndexSetBuilder< Shape_ >::compute(), FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_index_sets(), FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::has_topology(), and XASSERT.
fill_target_sets()
template<typename Shape_ , int num_coords_, typename Coord_ > virtual void FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::fill_target_sets (TargetSetHolderType & target_set_holder) inline override virtual
Fills the target sets.
Parameters
[in,out] target_set_holder A transient reference to the target set holder whose target sets are to be filled.
Definition at line 195 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::fill_target_sets().
get_num_entities()
template<typename Shape_ , int num_coords_, typename Coord_ > virtual Index FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::get_num_entities (int dim) inline override virtual
Returns the number of entities.
Parameters
[in] dim The dimension of the entity whose count is to be returned. Must be 0 <= dim <= shape_dim.
Returns
The number of entities of dimension dim.
Definition at line 146 of file patch_meshpart_splitter.hpp.
References FEAT::Geometry::PatchPartMapHolder< Shape_, dim_ >::get_num_entities().
Member Data Documentation
_base_mesh
template<typename Shape_ , int num_coords_, typename Coord_ > const MeshType& FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::_base_mesh protected
The BaseMesh we refer to.
Definition at line 79 of file patch_meshpart_splitter.hpp.
_cur_part_attribute_container
template<typename Shape_ , int num_coords_, typename Coord_ > const AttributeSetContainer* FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::_cur_part_attribute_container protected
The mesh attributes of the current BaseMesh MeshPart.
Definition at line 84 of file patch_meshpart_splitter.hpp.
_cur_part_topology
template<typename Shape_ , int num_coords_, typename Coord_ > const IndexSetHolder<ShapeType>* FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::_cur_part_topology protected
The topology of the current BaseMesh MeshPart.
Definition at line 86 of file patch_meshpart_splitter.hpp.
_part_holder
template<typename Shape_ , int num_coords_, typename Coord_ > PatchPartMapHolder<ShapeType, ShapeType::dimension> FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::_part_holder protected
The BaseMesh MeshPart to PatchMeshPart MeshPart mapping information.
Definition at line 88 of file patch_meshpart_splitter.hpp.
_patch_mesh_part
template<typename Shape_ , int num_coords_, typename Coord_ > const MeshPartType& FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::_patch_mesh_part protected
The MeshPart identifying this patch.
Definition at line 81 of file patch_meshpart_splitter.hpp.
shape_dim
template<typename Shape_ , int num_coords_, typename Coord_ > constexpr int FEAT::Geometry::PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >::shape_dim = ShapeType::dimension static constexpr
The shape dimension.
Definition at line 63 of file patch_meshpart_splitter.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/patch_meshpart_splitter.hpp