FEAT: FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ > Class Template Reference
FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ > Class Template Reference
Power-Row-Matrix meta class template.
#include <power_row_matrix.hpp>
Public Types
template<typename DT2_ = DataType, typename IT2_ = IndexType>
using ContainerType = PowerRowMatrix< typename SubType_::template ContainerType< DT2_, IT2_ >, blocks_ >
Our 'base' class type.
typedef SubMatrixType::DataType DataType
sub-matrix data type
typedef SubMatrixType::IndexType IndexType
sub-matrix index type
typedef SubType_ SubMatrixType
sub-matrix type
typedef SubMatrixType::VectorTypeL VectorTypeL
Compatible L-vector type.
typedef PowerVector< typename SubMatrixType::VectorTypeR, blocks_ > VectorTypeR
Compatible R-vector type.
Public Member Functions
PowerRowMatrix ()
default ctor
PowerRowMatrix (const PowerRowMatrix &)=delete
deleted copy-ctor
PowerRowMatrix (const SparseLayout< IndexType, layout_id > &layout)
sub-matrix layout ctor
PowerRowMatrix (FileMode mode, std::istream &file, String directory="")
Constructor.
PowerRowMatrix (FileMode mode, String filename)
Constructor.
PowerRowMatrix (PowerRowMatrix &&other)
move ctor
virtual ~PowerRowMatrix ()
virtual destructor
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply (VectorTypeL &r, const VectorTypeR &x) const
Applies this matrix onto a vector.
void apply (VectorTypeL &r, const VectorTypeR &x, const VectorTypeL &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x) const
void apply_transposed (DenseVector< DataType, IndexType > &r, const DenseVector< DataType, IndexType > &x, const DenseVector< DataType, IndexType > &y, DataType alpha=DataType(1)) const
void apply_transposed (VectorTypeR &r, const VectorTypeL &x) const
Applies this matrix onto a vector.
void apply_transposed (VectorTypeR &r, const VectorTypeL &x, const VectorTypeR &y, DataType alpha=DataType(1)) const
Applies this matrix onto a vector.
template<int i_, int j_>
SubMatrixType & at ()
Returns a sub-matrix block.
template<int i_, int j_>
const SubMatrixType & at () const
Returns a sub-matrix block.
std::size_t bytes () const
Returns the total amount of bytes allocated.
void clear ()
Free all allocated arrays.
PowerRowMatrix clone (LAFEM::CloneMode mode=LAFEM::CloneMode::Weak) const
Creates and returns a deep copy of this matrix.
template<Perspective perspective_ = Perspective::native>
Index columns () const
Returns the total number of columns in this matrix.
template<typename SubType2_ >
void convert (const PowerRowMatrix< SubType2_, blocks_ > &other)
Conversion method.
template<typename SubType2_ >
void convert_reverse (PowerRowMatrix< SubType2_, blocks_ > &other) const
VectorTypeL create_vector_l () const
Returns a new compatible L-Vector.
VectorTypeR create_vector_r () const
Returns a new compatible R-Vector.
void format (DataType value=DataType(0))
Reset all elements of the container to a given value or zero if missing.
SubMatrixType & get (int i, int j)
Returns a sub-matrix block.
const SubMatrixType & get (int i, int j) const
Returns a sub-matrix block.
std::uint64_t get_checkpoint_size (SerialConfig &config)
Calculate size.
Index get_length_of_line (const Index row) const
Returns the number of NNZ-elements of the selected row.
PowerRowMatrix & operator= (const PowerRowMatrix &)=delete
deleted copy-assign operator
PowerRowMatrix & operator= (PowerRowMatrix &&other)
move-assign operator
void read_from (FileMode mode, String filename)
Read in matrix from file.
void restore_from_checkpoint_data (std::vector< char > &data)
Extract object from checkpoint.
template<Perspective perspective_ = Perspective::native>
Index rows () const
Returns the total number of rows in this matrix.
std::uint64_t set_checkpoint_data (std::vector< char > &data, SerialConfig &config)
template<Perspective perspective_ = Perspective::native>
Index size () const
template<Perspective perspective_ = Perspective::native>
Index used_elements () const
Returns the total number of non-zeros in this matrix.
void write_out (FileMode mode, String filename) const
Write out matrix to file.
void write_out_submatrices (FileMode mode, String directory, String prefix, String suffix, Index length=blocks_) const
Write out submatrices to file.
Static Public Member Functions
static String name ()
Returns a descriptive string for this container.
Static Public Attributes
static constexpr SparseLayoutId layout_id = SubMatrixType::layout_id
sub-matrix layout type
static constexpr int num_col_blocks = blocks_
number of column blocks (horizontal size)
static constexpr int num_row_blocks = 1
number of row blocks (vertical size)
Protected Member Functions
PowerRowMatrix (SubMatrixType &&the_first, RestClass &&the_rest)
base-class constructor; this one is protected for a reason
Protected Attributes
SubMatrixType _first
the first sub-matrix
RestClass _rest
the remaining part
Private Types
typedef PowerRowMatrix< SubType_, blocks_-1 > RestClass
rest-class typedef
Friends
bool operator== (const PowerRowMatrix &a, const PowerRowMatrix &b)
PowerRowMatrix comparison operator.
Detailed Description
template<typename SubType_, int blocks_>
class FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >
Power-Row-Matrix meta class template.
This class template implements a horizontal composition of n sub-matrices of the same class. This can be interpreted as a dense 1-by-m matrix of other matrices.
Template Parameters
SubType_ The type of the sub-matrix.
blocks_ The number of sub-matrix blocks.
Author
Peter Zajac
Definition at line 38 of file power_row_matrix.hpp.
Member Typedef Documentation
ContainerType
template<typename SubType_ , int blocks_> template<typename DT2_ = DataType, typename IT2_ = IndexType> using FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::ContainerType = PowerRowMatrix<typename SubType_::template ContainerType<DT2_, IT2_>, blocks_>
Our 'base' class type.
Definition at line 65 of file power_row_matrix.hpp.
DataType
template<typename SubType_ , int blocks_> typedef SubMatrixType::DataType FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::DataType
sub-matrix data type
Definition at line 54 of file power_row_matrix.hpp.
IndexType
template<typename SubType_ , int blocks_> typedef SubMatrixType::IndexType FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::IndexType
sub-matrix index type
Definition at line 56 of file power_row_matrix.hpp.
RestClass
template<typename SubType_ , int blocks_> typedef PowerRowMatrix<SubType_, blocks_-1> FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::RestClass private
rest-class typedef
Definition at line 48 of file power_row_matrix.hpp.
SubMatrixType
template<typename SubType_ , int blocks_> typedef SubType_ FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::SubMatrixType
sub-matrix type
Definition at line 52 of file power_row_matrix.hpp.
VectorTypeL
template<typename SubType_ , int blocks_> typedef SubMatrixType::VectorTypeL FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::VectorTypeL
Compatible L-vector type.
Definition at line 60 of file power_row_matrix.hpp.
VectorTypeR
template<typename SubType_ , int blocks_> typedef PowerVector<typename SubMatrixType::VectorTypeR, blocks_> FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::VectorTypeR
Compatible R-vector type.
Definition at line 62 of file power_row_matrix.hpp.
Constructor & Destructor Documentation
PowerRowMatrix() [1/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix (SubMatrixType && the_first, RestClass && the_rest) inline explicit protected
base-class constructor; this one is protected for a reason
Definition at line 79 of file power_row_matrix.hpp.
PowerRowMatrix() [2/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix () inline
default ctor
Definition at line 87 of file power_row_matrix.hpp.
PowerRowMatrix() [3/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix (const SparseLayout< IndexType, layout_id > & layout) inline explicit
sub-matrix layout ctor
Definition at line 92 of file power_row_matrix.hpp.
PowerRowMatrix() [4/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix (PowerRowMatrix< SubType_, blocks_ > && other) inline
move ctor
Definition at line 99 of file power_row_matrix.hpp.
PowerRowMatrix() [5/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix (FileMode mode, String filename) inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] filename The source file.
Creates a power-row-point-matrix based on the source file.
Definition at line 113 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::read_from().
PowerRowMatrix() [6/6]
template<typename SubType_ , int blocks_> FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix (FileMode mode, std::istream & file, String directory = "") inline explicit
Constructor.
Parameters
[in] mode The used file format.
[in] file The source filestream.
Note
This constructor is used internally when reading a file
Creates a power-row-matrix based on the source filestream.
Definition at line 128 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, FEAT::String::trim_me(), and XABORTM.
~PowerRowMatrix()
template<typename SubType_ , int blocks_> virtual FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::~PowerRowMatrix () inline virtual
virtual destructor
Definition at line 194 of file power_row_matrix.hpp.
Member Function Documentation
apply() [1/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 433 of file power_row_matrix.hpp.
apply() [2/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::apply (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 497 of file power_row_matrix.hpp.
apply() [3/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::apply (VectorTypeL & r, const VectorTypeR & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 427 of file power_row_matrix.hpp.
apply() [4/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::apply (VectorTypeL & r, const VectorTypeR & x, const VectorTypeL & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this\cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 491 of file power_row_matrix.hpp.
apply_transposed() [1/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x) const inline
Definition at line 463 of file power_row_matrix.hpp.
apply_transposed() [2/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::apply_transposed (DenseVector< DataType, IndexType > & r, const DenseVector< DataType, IndexType > & x, const DenseVector< DataType, IndexType > & y, DataType alpha = DataType(1)) const inline
Definition at line 533 of file power_row_matrix.hpp.
apply_transposed() [3/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow this^\top \cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
Definition at line 457 of file power_row_matrix.hpp.
apply_transposed() [4/4]
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::apply_transposed (VectorTypeR & r, const VectorTypeL & x, const VectorTypeR & y, DataType alpha = DataType(1)) const inline
Applies this matrix onto a vector.
This function performs
\[r \leftarrow y + \alpha\cdot this^\top \cdot x \]
Parameters
[out] r The vector the receives the result.
[in] x The multiplicant vector.
[in] y The summand vector
[in] alpha A scalar to scale the product with.
Definition at line 527 of file power_row_matrix.hpp.
at() [1/2]
template<typename SubType_ , int blocks_> template<int i_, int j_> SubMatrixType & FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::at () inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 276 of file power_row_matrix.hpp.
at() [2/2]
template<typename SubType_ , int blocks_> template<int i_, int j_> const SubMatrixType & FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::at () const inline
Returns a sub-matrix block.
Template Parameters
i_ The row index of the sub-matrix block that is to be returned.
j_ The column index of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i_,j_).
Definition at line 285 of file power_row_matrix.hpp.
bytes()
template<typename SubType_ , int blocks_> std::size_t FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 258 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::bytes().
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::bytes().
clear()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::clear () inline
Free all allocated arrays.
Definition at line 409 of file power_row_matrix.hpp.
clone()
template<typename SubType_ , int blocks_> PowerRowMatrix FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::clone (LAFEM::CloneMode mode = LAFEM::CloneMode::Weak) const inline
Creates and returns a deep copy of this matrix.
Definition at line 252 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::clone().
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::clone().
columns()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::columns () const inline
Returns the total number of columns in this matrix.
Returns
Matrix column count if raw = false.
Raw matrix column count if raw = true.
Definition at line 365 of file power_row_matrix.hpp.
convert()
template<typename SubType_ , int blocks_> template<typename SubType2_ > void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::convert (const PowerRowMatrix< SubType2_, blocks_ > & other) inline
Conversion method.
Parameters
[in] other The source Matrix.
Use source matrix content as content of current matrix
Definition at line 630 of file power_row_matrix.hpp.
convert_reverse()
template<typename SubType_ , int blocks_> template<typename SubType2_ > void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::convert_reverse (PowerRowMatrix< SubType2_, blocks_ > & other) const inline
Definition at line 637 of file power_row_matrix.hpp.
create_vector_l()
template<typename SubType_ , int blocks_> VectorTypeL FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::create_vector_l () const inline
Returns a new compatible L-Vector.
Definition at line 551 of file power_row_matrix.hpp.
create_vector_r()
template<typename SubType_ , int blocks_> VectorTypeR FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::create_vector_r () const inline
Returns a new compatible R-Vector.
Definition at line 557 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::create_vector_r().
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::create_vector_r().
format()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::format (DataType value = DataType(0)) inline
Reset all elements of the container to a given value or zero if missing.
Parameters
[in] value The value to which the matrix' entries are to be set to.
Definition at line 400 of file power_row_matrix.hpp.
References FEAT::value.
get() [1/2]
template<typename SubType_ , int blocks_> SubMatrixType & FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get (int i, int j) inline
Returns a sub-matrix block.
Parameters
[in] i,j The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i,j).
Definition at line 301 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get(), and XASSERTM.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_grad_div_matrices(), FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::get(), and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get().
get() [2/2]
template<typename SubType_ , int blocks_> const SubMatrixType & FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get (int i, int j) const inline
Returns a sub-matrix block.
Parameters
[in] i,j The indices of the sub-matrix block that is to be returned.
Returns
A (const) reference to the sub-matrix at position (i,j).
Definition at line 308 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get(), and XASSERTM.
get_checkpoint_size()
template<typename SubType_ , int blocks_> std::uint64_t FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get_checkpoint_size (SerialConfig & config) inline
Calculate size.
Calculate size of complete object as it is stored in the checkpoint
Returns
size of object
Definition at line 589 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get_checkpoint_size().
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get_checkpoint_size().
get_length_of_line()
template<typename SubType_ , int blocks_> Index FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get_length_of_line (const Index row) const inline
Returns the number of NNZ-elements of the selected row.
Definition at line 563 of file power_row_matrix.hpp.
name()
template<typename SubType_ , int blocks_> static String FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::name () inline static
Returns a descriptive string for this container.
Definition at line 383 of file power_row_matrix.hpp.
References FEAT::stringify().
operator=()
template<typename SubType_ , int blocks_> PowerRowMatrix & FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::operator= (PowerRowMatrix< SubType_, blocks_ > && other) inline
move-assign operator
Definition at line 178 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest.
read_from()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::read_from (FileMode mode, String filename) inline
Read in matrix from file.
Parameters
[in] mode The used file format.
[in] filename The file that shall be read in.
Definition at line 151 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, and XABORTM.
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix().
restore_from_checkpoint_data()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::restore_from_checkpoint_data (std::vector< char > & data) inline
Extract object from checkpoint.
Restores complete object with all its contents from checkpoint data
Parameters
[out] data object as bytestrem
Definition at line 595 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::restore_from_checkpoint_data().
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::restore_from_checkpoint_data().
rows()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::rows () const inline
Returns the total number of rows in this matrix.
Returns
Matrix row count if raw = false.
Raw matrix row count if raw = true.
Definition at line 353 of file power_row_matrix.hpp.
set_checkpoint_data()
template<typename SubType_ , int blocks_> std::uint64_t FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::set_checkpoint_data (std::vector< char > & data, SerialConfig & config) inline
Definition at line 608 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::set_checkpoint_data().
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::set_checkpoint_data().
size()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::size () const inline
Definition at line 389 of file power_row_matrix.hpp.
used_elements()
template<typename SubType_ , int blocks_> template<Perspective perspective_ = Perspective::native> Index FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::used_elements () const inline
Returns the total number of non-zeros in this matrix.
Returns
Matrix non zero element count if raw = false.
Raw matrix non zero element count if raw = true.
Definition at line 377 of file power_row_matrix.hpp.
write_out()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out (FileMode mode, String filename) const inline
Write out matrix to file.
Parameters
[in] mode The used file format.
[in] filename The file where the matrix shall be stored.
Definition at line 204 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out_submatrices(), and XABORTM.
write_out_submatrices()
template<typename SubType_ , int blocks_> void FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out_submatrices (FileMode mode, String directory, String prefix, String suffix, Index length = blocks_) const inline
Write out submatrices to file.
Parameters
[in] mode The used file format.
[in] directory The directory of the matrix-files.
[in] prefix The prefix of the matrix-files.
[in] suffix The suffix of the matrix-files.
Definition at line 243 of file power_row_matrix.hpp.
References FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first, FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest, FEAT::stringify(), and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out_submatrices().
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out(), and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out_submatrices().
Friends And Related Function Documentation
PowerRowMatrix
template<typename SubType_ , int blocks_> template<typename , int > friend class PowerRowMatrix friend
Definition at line 45 of file power_row_matrix.hpp.
operator==
template<typename SubType_ , int blocks_> bool operator== (const PowerRowMatrix< SubType_, blocks_ > & a, const PowerRowMatrix< SubType_, blocks_ > & b) friend
PowerRowMatrix comparison operator.
Parameters
[in] a A matrix to compare with.
[in] b A matrix to compare with.
Definition at line 649 of file power_row_matrix.hpp.
Member Data Documentation
_first
template<typename SubType_ , int blocks_> SubMatrixType FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_first protected
the first sub-matrix
Definition at line 74 of file power_row_matrix.hpp.
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::bytes(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::clone(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get_checkpoint_size(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::operator=(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::read_from(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::restore_from_checkpoint_data(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::set_checkpoint_data(), and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out_submatrices().
_rest
template<typename SubType_ , int blocks_> RestClass FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::_rest protected
the remaining part
Definition at line 76 of file power_row_matrix.hpp.
Referenced by FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::PowerRowMatrix(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::bytes(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::clone(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get_checkpoint_size(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::operator=(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::read_from(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::restore_from_checkpoint_data(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::set_checkpoint_data(), and FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out_submatrices().
layout_id
template<typename SubType_ , int blocks_> constexpr SparseLayoutId FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::layout_id = SubMatrixType::layout_id static constexpr
sub-matrix layout type
Definition at line 58 of file power_row_matrix.hpp.
num_col_blocks
template<typename SubType_ , int blocks_> constexpr int FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::num_col_blocks = blocks_ static constexpr
number of column blocks (horizontal size)
Definition at line 70 of file power_row_matrix.hpp.
num_row_blocks
template<typename SubType_ , int blocks_> constexpr int FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::num_row_blocks = 1 static constexpr
number of row blocks (vertical size)
Definition at line 68 of file power_row_matrix.hpp.
The documentation for this class was generated from the following file:
kernel/lafem/power_row_matrix.hpp