FEAT: FEAT::Intern::ParameterCore Class Reference
FEAT::Intern::ParameterCore Class Reference
Type-erased core of a Parameter.
#include <arg_parser.hpp>
Public Types
using Need = std::pair< std::weak_ptr< ParameterCore >, std::function< bool(const std::any &)> >
Type of "A needs B" declaration with condition.
using ParserType = std::function< void(std::any &, const String &)>
Type of type-erased parser function.
using PrinterType = std::function< void(std::ostream &, const std::any &)>
Type of type-erased printer function.
using ValidatorType = std::function< void(const std::any &)>
Type of type-erased validator function.
Public Member Functions
template<typename T_ >
ParameterCore (T_ def_value)
Constructor.
void add_argument (const String &s, int incoming_priority)
Add an argument to this parameter.
String name () const
Tries to create a user-readable name for this parameter.
void parse (std::deque< String > &errors)
Parse this parameter.
void reset ()
Reset this parameter to default.
void validate (std::deque< String > &errors) const
Validate this parameter.
Public Attributes
std::deque< String > arguments
String custom_name
std::any default_value
String environment_variable {""}
String help_string
String long_flag {""}
std::deque< Need > needs
ParserType parser
String placeholder
PrinterType printer
int priority = 0
String property_path {""}
bool required = false
bool set_by_user = false
String short_flag {""}
ParameterType type = ParameterType::flag
ValidatorType validator
std::any value
Detailed Description
Type-erased core of a Parameter.
This class enables the argument parser to treat all parameters as a homogenous collection. It stores
information for parsing (flags, environment variables, property paths)
information for generating help texts
metadata, like priority and whether the parameter is required to be set by the user
the actual parameter values
function pointers to type-erased function for type specific functionality.
The type erased function pointers allow the argument parser to automatically parse the parameters value, validate its correctness if needed, and print the parameter, without needing to know the parameters actual type.
Definition at line 226 of file arg_parser.hpp.
Member Typedef Documentation
Need
using FEAT::Intern::ParameterCore::Need = std::pair<std::weak_ptr<ParameterCore>, std::function<bool(const std::any&)> >
Type of "A needs B" declaration with condition.
Definition at line 237 of file arg_parser.hpp.
ParserType
using FEAT::Intern::ParameterCore::ParserType = std::function<void(std::any&, const String&)>
Type of type-erased parser function.
Definition at line 230 of file arg_parser.hpp.
PrinterType
using FEAT::Intern::ParameterCore::PrinterType = std::function<void(std::ostream&, const std::any&)>
Type of type-erased printer function.
Definition at line 234 of file arg_parser.hpp.
ValidatorType
using FEAT::Intern::ParameterCore::ValidatorType = std::function<void(const std::any&)>
Type of type-erased validator function.
Definition at line 232 of file arg_parser.hpp.
Constructor & Destructor Documentation
ParameterCore()
template<typename T_ > FEAT::Intern::ParameterCore::ParameterCore (T_ def_value) inline explicit
Constructor.
Definition at line 269 of file arg_parser.hpp.
References FEAT::value.
Member Function Documentation
add_argument()
void FEAT::Intern::ParameterCore::add_argument (const String & s, int incoming_priority)
Add an argument to this parameter.
Definition at line 48 of file arg_parser.cpp.
References FEAT::String::trim().
name()
String FEAT::Intern::ParameterCore::name () const
Tries to create a user-readable name for this parameter.
Tries to derive a name from the long flag, the short flag, the property path or the environment variable. If all four are empty the name is '<anonymous>'.
Tries to derive a name from the long flag, the short flag, the property path or the environment variable. If all four are empty the name is '<anonymous>'.
Definition at line 18 of file arg_parser.cpp.
Referenced by parse(), and validate().
parse()
void FEAT::Intern::ParameterCore::parse (std::deque< String > & errors)
Parse this parameter.
Convert the collected arguments into actual data types
Definition at line 111 of file arg_parser.cpp.
References name(), FEAT::String::trim(), and XABORTM.
reset()
void FEAT::Intern::ParameterCore::reset ()
Reset this parameter to default.
Definition at line 167 of file arg_parser.cpp.
validate()
void FEAT::Intern::ParameterCore::validate (std::deque< String > & errors) const
Validate this parameter.
Checks for requiredness, runs the validator if it is set, checks for dependencies between parameters
Definition at line 66 of file arg_parser.cpp.
References name(), and XABORTM.
Member Data Documentation
arguments
std::deque<String> FEAT::Intern::ParameterCore::arguments
Definition at line 258 of file arg_parser.hpp.
custom_name
String FEAT::Intern::ParameterCore::custom_name
Definition at line 247 of file arg_parser.hpp.
default_value
std::any FEAT::Intern::ParameterCore::default_value
Definition at line 259 of file arg_parser.hpp.
environment_variable
String FEAT::Intern::ParameterCore::environment_variable {""}
Definition at line 243 of file arg_parser.hpp.
help_string
String FEAT::Intern::ParameterCore::help_string
Definition at line 249 of file arg_parser.hpp.
long_flag
String FEAT::Intern::ParameterCore::long_flag {""}
Definition at line 242 of file arg_parser.hpp.
needs
std::deque<Need> FEAT::Intern::ParameterCore::needs
Definition at line 255 of file arg_parser.hpp.
parser
ParserType FEAT::Intern::ParameterCore::parser
Definition at line 263 of file arg_parser.hpp.
placeholder
String FEAT::Intern::ParameterCore::placeholder
Definition at line 248 of file arg_parser.hpp.
printer
PrinterType FEAT::Intern::ParameterCore::printer
Definition at line 265 of file arg_parser.hpp.
priority
int FEAT::Intern::ParameterCore::priority = 0
Definition at line 252 of file arg_parser.hpp.
property_path
String FEAT::Intern::ParameterCore::property_path {""}
Definition at line 244 of file arg_parser.hpp.
required
bool FEAT::Intern::ParameterCore::required = false
Definition at line 253 of file arg_parser.hpp.
set_by_user
bool FEAT::Intern::ParameterCore::set_by_user = false
Definition at line 254 of file arg_parser.hpp.
short_flag
String FEAT::Intern::ParameterCore::short_flag {""}
Definition at line 241 of file arg_parser.hpp.
type
ParameterType FEAT::Intern::ParameterCore::type = ParameterType::flag
Definition at line 240 of file arg_parser.hpp.
validator
ValidatorType FEAT::Intern::ParameterCore::validator
Definition at line 264 of file arg_parser.hpp.
value
std::any FEAT::Intern::ParameterCore::value
Definition at line 260 of file arg_parser.hpp.
The documentation for this class was generated from the following files:
kernel/util/arg_parser.hpp
kernel/util/arg_parser.cpp