FEAT: FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > > Class Template Reference
FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > > Class Template Reference
*‍/
#include <mesh_part.hpp>
Public Types
typedef MeshType::AttributeSetContainer AttributeSetContainer
index set holder type
typedef MeshType::AttributeSetType AttributeType
Attribute set type.
typedef MeshType::IndexSetHolderType IndexSetHolderType
index set holder type
typedef MeshPart< ParentMesh_ > MeshType
mesh type
typedef MeshType::ShapeType ShapeType
shape type
typedef MeshType::TargetSetHolderType TargetSetHolderType
target set holder type
Public Member Functions
StandardRefinery (const MeshType &coarse_meshpart, const MeshPart< ParentMesh_ > &parent_meshpart)
Constructor.
StandardRefinery (const MeshType &coarse_meshpart, const ParentMesh_ &parent_mesh)
Constructor.
virtual ~StandardRefinery ()
virtual destructor
virtual void fill_attribute_sets (AttributeSetContainer &attribute_container) override
Fills attribute sets where applicable.
virtual void fill_index_sets (std::unique_ptr< IndexSetHolderType > &index_set_holder) override
Fills the index sets.
virtual void fill_target_sets (TargetSetHolderType &target_set_holder) override
Fills the target sets.
virtual Index get_num_entities (int dim) override
Returns the number of entities of the refined mesh.
Static Public Attributes
static constexpr int shape_dim = ShapeType::dimension
shape dimension
Protected Attributes
const MeshType & _coarse_meshpart
coarse mesh reference
Index _num_entities_coarse [shape_dim+1]
number of entities for coarse mesh
Index _num_entities_fine [shape_dim+1]
number of entities for fine mesh
const ParentMesh_ * _parent_mesh
coarse parent mesh reference
const MeshType * _parent_meshpart
coarse parent mesh-part reference
Detailed Description
template<typename ParentMesh_>
class FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >
*‍/
StandardRefinery implementation for MeshPart
Author
Jordi Paul
Peter Zajac
Definition at line 661 of file mesh_part.hpp.
Member Typedef Documentation
AttributeSetContainer
template<typename ParentMesh_ > typedef MeshType::AttributeSetContainer FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::AttributeSetContainer
index set holder type
Definition at line 672 of file mesh_part.hpp.
AttributeType
template<typename ParentMesh_ > typedef MeshType::AttributeSetType FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::AttributeType
Attribute set type.
Definition at line 670 of file mesh_part.hpp.
IndexSetHolderType
template<typename ParentMesh_ > typedef MeshType::IndexSetHolderType FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::IndexSetHolderType
index set holder type
Definition at line 674 of file mesh_part.hpp.
MeshType
template<typename ParentMesh_ > typedef MeshPart<ParentMesh_> FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::MeshType
mesh type
Definition at line 666 of file mesh_part.hpp.
ShapeType
template<typename ParentMesh_ > typedef MeshType::ShapeType FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::ShapeType
shape type
Definition at line 668 of file mesh_part.hpp.
TargetSetHolderType
template<typename ParentMesh_ > typedef MeshType::TargetSetHolderType FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::TargetSetHolderType
target set holder type
Definition at line 676 of file mesh_part.hpp.
Constructor & Destructor Documentation
StandardRefinery() [1/2]
template<typename ParentMesh_ > FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::StandardRefinery (const MeshType & coarse_meshpart, const ParentMesh_ & parent_mesh) inline explicit
Constructor.
Use this constructor if the meshpart, which is to be refined, is defined on the root mesh (and not on another meshpart).
Parameters
[in] coarse_meshpart A resident reference to the coarse mesh that is to be refined.
[in] parent_mesh A resident reference to the coarse parent mesh.
Definition at line 706 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities().
StandardRefinery() [2/2]
template<typename ParentMesh_ > FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::StandardRefinery (const MeshType & coarse_meshpart, const MeshPart< ParentMesh_ > & parent_meshpart) inline explicit
Constructor.
Use this constructor if the meshpart, which is to be refined, is defined on another meshpart (and not on the root mesh).
Parameters
[in] coarse_meshpart A resident reference to the coarse mesh that is to be refined.
[in] parent_meshpart A resident reference to the coarse parent mesh part.
Definition at line 733 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::get_num_entities().
~StandardRefinery()
template<typename ParentMesh_ > virtual FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::~StandardRefinery () inline virtual
virtual destructor
Definition at line 749 of file mesh_part.hpp.
Member Function Documentation
fill_attribute_sets()
template<typename ParentMesh_ > virtual void FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::fill_attribute_sets (AttributeSetContainer & attribute_container) inline override virtual
Fills attribute sets where applicable.
Parameters
[in,out] attribute_container A transient reference to the container for the attribute sets being added to
Definition at line 773 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::get_mesh_attributes(), FEAT::Geometry::MeshPart< MeshType_ >::has_topology(), and XASSERTM.
fill_index_sets()
template<typename ParentMesh_ > virtual void FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::fill_index_sets (std::unique_ptr< IndexSetHolderType > & index_set_holder) inline override virtual
Fills the index sets.
Parameters
[in,out] index_set_holder A transient reference to the index set holder whose index sets are to be filled.
Definition at line 804 of file mesh_part.hpp.
References FEAT::Geometry::MeshPart< MeshType_ >::has_topology(), and XASSERT.
fill_target_sets()
template<typename ParentMesh_ > virtual void FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::fill_target_sets (TargetSetHolderType & target_set_holder) inline override virtual
Fills the target sets.
Parameters
[in,out] target_set_holder A transient reference to the target set holder whose target sets are to be filled.
Definition at line 825 of file mesh_part.hpp.
References XABORTM.
get_num_entities()
template<typename ParentMesh_ > virtual Index FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::get_num_entities (int dim) inline override virtual
Returns the number of entities of the refined mesh.
Parameters
[in] dim The dimension of the entity whose count is to be returned. Must be 0 <= dim <= shape_dim.
Returns
The number of entities of dimension dim.
Definition at line 762 of file mesh_part.hpp.
Member Data Documentation
_coarse_meshpart
template<typename ParentMesh_ > const MeshType& FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::_coarse_meshpart protected
coarse mesh reference
Definition at line 683 of file mesh_part.hpp.
_num_entities_coarse
template<typename ParentMesh_ > Index FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::_num_entities_coarse[shape_dim+1] protected
number of entities for coarse mesh
Definition at line 689 of file mesh_part.hpp.
_num_entities_fine
template<typename ParentMesh_ > Index FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::_num_entities_fine[shape_dim+1] protected
number of entities for fine mesh
Definition at line 691 of file mesh_part.hpp.
_parent_mesh
template<typename ParentMesh_ > const ParentMesh_* FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::_parent_mesh protected
coarse parent mesh reference
Definition at line 685 of file mesh_part.hpp.
_parent_meshpart
template<typename ParentMesh_ > const MeshType* FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::_parent_meshpart protected
coarse parent mesh-part reference
Definition at line 687 of file mesh_part.hpp.
shape_dim
template<typename ParentMesh_ > constexpr int FEAT::Geometry::StandardRefinery< MeshPart< ParentMesh_ > >::shape_dim = ShapeType::dimension static constexpr
shape dimension
Definition at line 679 of file mesh_part.hpp.
The documentation for this class was generated from the following file:
kernel/geometry/mesh_part.hpp