FEAT: FEAT::Adjacency::Coloring Class Reference
FEAT::Adjacency::Coloring Class Reference
Coloring object implementation.
#include <coloring.hpp>
Public Member Functions
Coloring ()
Default constructor.
Coloring (Coloring &&other) noexcept
move ctor
Coloring (const Graph &graph)
Creation out of a given Graph.
Coloring (const Graph &graph, const Index *order)
Creation out of a given Graph with a prescribed order.
Coloring (Index num_colors, const IndexVector &coloring)
Vector Constructor.
Coloring (Index num_nodes, Index *coloring)
Array Constructor.
Coloring (Index num_nodes, Index num_colors)
Allocation Constructor.
virtual ~Coloring ()
virtual destructor
Coloring clone () const
Clones this coloring.
Graph create_partition_graph () const
Creates a color partition graph.
bool empty () const
Checks whether the coloring is empty.
Index * get_coloring ()
Returns the coloring array.
const Index * get_coloring () const
Returns the coloring array.
Index get_max_color () const
Returns the maximum color index.
Index get_num_colors () const
Returns the number of colors.
Index get_num_nodes () const
Returns the total number of nodes.
Coloring & operator= (Coloring &&other) noexcept
move-assign operator
Index & operator[] (Index i)
Returns the color for a node i.
const Index & operator[] (Index i) const
Returns the color for a node i.
auto size () const -> decltype(_coloring.size())
Returns the total number of nodes.
Protected Types
using IndexVector = std::vector< Index >
Protected Attributes
IndexVector _coloring
coloring vector
Index _num_colors
total number of colors used
Detailed Description
Coloring object implementation.
Todo:
detailed description
Author
Constantin Christof
Definition at line 38 of file coloring.hpp.
Member Typedef Documentation
IndexVector
using FEAT::Adjacency::Coloring::IndexVector = std::vector < Index> protected
Definition at line 41 of file coloring.hpp.
Constructor & Destructor Documentation
Coloring() [1/7]
FEAT::Adjacency::Coloring::Coloring ()
Default constructor.
This constructor creates a new empty coloring object, but does not allocate any vectors.
Definition at line 21 of file coloring.cpp.
Referenced by clone().
Coloring() [2/7]
FEAT::Adjacency::Coloring::Coloring (Index num_nodes, Index num_colors)
Allocation Constructor.
This constructor creates a new coloring object and allocates a coloring vector of length num_nodes.
Note
This constructor does not initialize the allocated vector – it has to be initialized by the user after construction.
Parameters
[in] num_nodes The total number of nodes.
[in] num_colors The number of colors.
Definition at line 28 of file coloring.cpp.
References _coloring.
Coloring() [3/7]
FEAT::Adjacency::Coloring::Coloring (Index num_nodes, Index * coloring)
Array Constructor.
This constructor creates a new coloring object from a given array.
Parameters
[in] num_nodes The total number of nodes.
[in] coloring The transient coloring array
Definition at line 38 of file coloring.cpp.
References _coloring, and _num_colors.
Coloring() [4/7]
FEAT::Adjacency::Coloring::Coloring (Index num_colors, const IndexVector & coloring)
Vector Constructor.
This constructor creates a new coloring object from a given vector.
Parameters
[in] num_colors The total number of colors.
[in] coloring The transient coloring vector
Definition at line 60 of file coloring.cpp.
Coloring() [5/7]
FEAT::Adjacency::Coloring::Coloring (const Graph & graph) explicit
Creation out of a given Graph.
This constructor creates a coloring object out of a graph. The returned coloring satisfies the condition that adjacent nodes do not have the same color.
Parameters
[in] graph The transient graph to create the coloring from.
Definition at line 68 of file coloring.cpp.
References _coloring, _num_colors, FEAT::Adjacency::Graph::degree(), FEAT::Adjacency::Graph::get_domain_ptr(), and FEAT::Adjacency::Graph::get_image_idx().
Coloring() [6/7]
FEAT::Adjacency::Coloring::Coloring (const Graph & graph, const Index * order) explicit
Creation out of a given Graph with a prescribed order.
This constructor creates a coloring object out of a graph. The returned coloring satisfies the condition that adjacent nodes do not have the same color. The algorithm proceeds through the nodes as given by the parameter order.
Parameters
[in] graph The transient graph to create the coloring from.
[in] order Permutation array that describes how the algorithm is supposed to proceed through the nodes.
Definition at line 160 of file coloring.cpp.
References _coloring, _num_colors, FEAT::Adjacency::Graph::degree(), FEAT::Adjacency::Graph::get_domain_ptr(), and FEAT::Adjacency::Graph::get_image_idx().
Coloring() [7/7]
FEAT::Adjacency::Coloring::Coloring (Coloring && other) noexcept
move ctor
Definition at line 264 of file coloring.cpp.
~Coloring()
FEAT::Adjacency::Coloring::~Coloring () virtual
virtual destructor
Definition at line 289 of file coloring.cpp.
Member Function Documentation
clone()
Coloring FEAT::Adjacency::Coloring::clone () const inline
Clones this coloring.
Returns
A deep-copy of this coloring.
Definition at line 156 of file coloring.hpp.
References Coloring(), _coloring, and _num_colors.
create_partition_graph()
Graph FEAT::Adjacency::Coloring::create_partition_graph () const
Creates a color partition graph.
This function creates a graph out of this coloring object. The graph's image is the set of nodes, the domain is the set of colors.
Definition at line 292 of file coloring.cpp.
References _coloring, _num_colors, FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), get_max_color(), and get_num_nodes().
Referenced by FEAT::Assembly::DomainAssembler< Trafo_ >::_build_colors(), FEAT::Geometry::PartiParMETIS::build_elems_at_rank(), FEAT::Geometry::PartiZoltan::build_elems_at_rank(), and FEAT::Geometry::MeshPermutation< Shape_ >::create_colored().
empty()
bool FEAT::Adjacency::Coloring::empty () const inline
Checks whether the coloring is empty.
Definition at line 225 of file coloring.hpp.
References _coloring.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered().
get_coloring() [1/2]
Index * FEAT::Adjacency::Coloring::get_coloring () inline
Returns the coloring array.
Returns
The coloring array.
Definition at line 177 of file coloring.hpp.
References _coloring.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_coloring(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_layering().
get_coloring() [2/2]
const Index * FEAT::Adjacency::Coloring::get_coloring () const inline
Returns the coloring array.
Returns
The coloring array.
Definition at line 183 of file coloring.hpp.
References _coloring.
get_max_color()
Index FEAT::Adjacency::Coloring::get_max_color () const inline
Returns the maximum color index.
Returns
The maximum color index.
Definition at line 209 of file coloring.hpp.
References _num_colors.
Referenced by create_partition_graph().
get_num_colors()
Index FEAT::Adjacency::Coloring::get_num_colors () const inline
Returns the number of colors.
Returns
The number of colors.
Definition at line 219 of file coloring.hpp.
References _num_colors.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_layering(), and FEAT::Adjacency::ColoringDataHandler::fill_color().
get_num_nodes()
Index FEAT::Adjacency::Coloring::get_num_nodes () const inline
Returns the total number of nodes.
Returns
The total number of nodes.
Definition at line 193 of file coloring.hpp.
References _coloring.
Referenced by create_partition_graph().
operator=()
Coloring & FEAT::Adjacency::Coloring::operator= (Coloring && other) noexcept
move-assign operator
Definition at line 273 of file coloring.cpp.
operator[]() [1/2]
Index & FEAT::Adjacency::Coloring::operator[] (Index i) inline
Returns the color for a node i.
Definition at line 231 of file coloring.hpp.
References _coloring, and ASSERT.
operator[]() [2/2]
const Index & FEAT::Adjacency::Coloring::operator[] (Index i) const inline
Returns the color for a node i.
Definition at line 238 of file coloring.hpp.
References _coloring, and ASSERT.
size()
auto FEAT::Adjacency::Coloring::size () const -> decltype(_coloring.size()) inline
Returns the total number of nodes.
Returns
The total number of nodes.
Definition at line 199 of file coloring.hpp.
References _coloring.
Referenced by FEAT::Adjacency::ColoringDataHandler::fill_color().
Member Data Documentation
_coloring
IndexVector FEAT::Adjacency::Coloring::_coloring protected
coloring vector
Dimension: #_num_nodes The coloring vector is defined as the second row of the following chart: node number : 0 1 ... num_nodes-1 color number: color of node 0 color of node 1 ... color of node num_nodes-1
Definition at line 55 of file coloring.hpp.
Referenced by Coloring(), clone(), create_partition_graph(), empty(), get_coloring(), get_num_nodes(), operator[](), and size().
_num_colors
Index FEAT::Adjacency::Coloring::_num_colors protected
total number of colors used
Definition at line 44 of file coloring.hpp.
Referenced by Coloring(), clone(), create_partition_graph(), get_max_color(), and get_num_colors().
The documentation for this class was generated from the following files:
kernel/adjacency/coloring.hpp
kernel/adjacency/coloring.cpp