FEAT: FEAT::Global::Gate< LocalVector_, Mirror_ > Class Template Reference
FEAT::Global::Gate< LocalVector_, Mirror_ > Class Template Reference
Global gate implementation.
#include <gate.hpp>
Public Types
typedef LAFEM::DenseVector< DataType, IndexType > BufferVectorType
typedef LocalVector_::DataType DataType
template<typename LocalVector2_ , typename Mirror2_ >
using GateType = Gate< LocalVector2_, Mirror2_ >
Our 'base' class type.
template<typename DataType2_ , typename IndexType2_ >
using GateTypeByDI = Gate< typename LocalVector_::template ContainerType< DataType2_, IndexType2_ >, typename Mirror_::template MirrorType< DataType2_, IndexType2_ > >
this typedef lets you create a gate container with new Data and Index types
typedef LocalVector_::IndexType IndexType
typedef Mirror_ MirrorType
typedef SynchScalarTicket< DataType > ScalarTicketType
typedef SynchVectorTicket< LocalVector_, Mirror_ > VectorTicketType
Public Member Functions
Gate ()
standard constructor
Gate (const Dist::Comm &comm)
Constructor.
Gate (Gate &&other)
move constructor
virtual ~Gate ()
virtual destructor
std::size_t bytes () const
Returns the total amount of bytes allocated.
void compile (LocalVector_ &&vector)
Compiles the gate to finish its setup.
template<typename LVT2_ >
void convert (const Gate< LVT2_, Mirror_ > &other, LocalVector_ &&vector, LAFEM::CloneMode mode=LAFEM::CloneMode::Shallow)
Conversion function for different vector container type.
template<typename LVT2_ , typename MT2_ >
void convert (const Gate< LVT2_, MT2_ > &other)
Conversion function for same vector container type but with different MDI-Type.
DataType dot (const LocalVector_ &x, const LocalVector_ &y) const
Computes a synchronized dot-product of two type-1 vectors.
ScalarTicketType dot_async (const LocalVector_ &x, const LocalVector_ &y, bool sqrt=false) const
Computes a synchronized dot-product of two type-1 vectors.
void from_1_to_0 (LocalVector_ &vector) const
Converts a type-1 vector into a type-0 vector.
const Dist::Comm * get_comm () const
Returns a const pointer to the underlying communicator.
const LocalVector_ & get_freqs () const
Returns a const reference to the frequencies vector.
const std::vector< Mirror_ > & get_mirrors () const
Returns a const reference to the neighbor mirrors vector.
template<LAFEM::Perspective perspective_ = LAFEM::Perspective::native>
Index get_num_global_dofs () const
Returns the number of global DOFs.
template<LAFEM::Perspective perspective_ = LAFEM::Perspective::native>
Index get_num_local_dofs () const
Returns the number of local DOFs.
const std::vector< int > get_ranks () const
Returns a const reference to the neighbor ranks vector.
DataType max (DataType x) const
Computes the maximum of a scalar variable over all processes.
ScalarTicketType max_async (DataType x) const
Computes the maximum of a scalar variable over all processes.
DataType min (DataType x) const
Computes the minimum of a scalar variable over all processes.
ScalarTicketType min_async (DataType x) const
Computes the minimum of a scalar variable over all processes.
DataType norm2 (DataType x) const
Computes a reduced 2-norm over all processes.
ScalarTicketType norm2_async (DataType x) const
Computes a reduced 2-norm over all processes.
Gate & operator= (Gate &&other)
move-assign operator
void push (int rank, Mirror_ &&mirror)
Adds a mirror for a neighbor process.
void set_comm (const Dist::Comm *comm_)
Sets the communicator for this gate.
DataType sum (DataType x) const
Computes a reduced sum over all processes.
ScalarTicketType sum_async (DataType x, bool sqrt=false) const
Computes a reduced sum over all processes.
void sync_0 (LocalVector_ &vector) const
Synchronizes a type-0 vector, resulting in a type-1 vector.
VectorTicketType sync_0_async (LocalVector_ &vector) const
Synchronizes a type-0 vector, resulting in a type-1 vector.
void sync_1 (LocalVector_ &vector) const
Synchronizes a type-1 vector, resulting in a type-1 vector.
VectorTicketType sync_1_async (LocalVector_ &vector) const
Synchronizes a type-1 vector, resulting in a type-1 vector.
Public Attributes
const Dist::Comm * _comm
our communicator
LocalVector_ _freqs
frequency vector
std::vector< Mirror_ > _mirrors
vector mirrors
std::vector< int > _ranks
communication ranks
Detailed Description
template<typename LocalVector_, typename Mirror_>
class FEAT::Global::Gate< LocalVector_, Mirror_ >
Global gate implementation.
This class provides the functionality for the synchronization of data across interfaces between nearest neighbors (aka 'halos') in the overlapping domain decomposition approach and is used by most other Global classes. Note that a gate is tied to one finite element space (or a tuple thereof) and one vector type, i.e. if you need to synchronize different vector types belonging to possibly different finite element spaces, then you also need one gate object for each space-vector pair. In the case where you need two gate objects for the same finite element space object, but for different vector classes, you can make use of the convert functions to convert one gate into another one for the second vector type.
Template Parameters
LocalVector_ The type of the local vector container; may be any valid combination of LAFEM (meta-)vector types
Mirror_ The type of the vector mirror; must be compatible to the local vector type
To set up an object of this class, one has to perform three separate steps:
Set the Dist::Comm object for the gate by using the set_comm() function.
Add the mirror for each nearest neighbor by using the push() function.
Compile the gate by calling the compile() function and supplying it with a temporary local vector.
Author
Peter Zajac
Definition at line 52 of file gate.hpp.
Member Typedef Documentation
BufferVectorType
template<typename LocalVector_ , typename Mirror_ > typedef LAFEM::DenseVector<DataType, IndexType> FEAT::Global::Gate< LocalVector_, Mirror_ >::BufferVectorType
Definition at line 57 of file gate.hpp.
DataType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVector_::DataType FEAT::Global::Gate< LocalVector_, Mirror_ >::DataType
Definition at line 55 of file gate.hpp.
GateType
template<typename LocalVector_ , typename Mirror_ > template<typename LocalVector2_ , typename Mirror2_ > using FEAT::Global::Gate< LocalVector_, Mirror_ >::GateType = Gate<LocalVector2_, Mirror2_>
Our 'base' class type.
Definition at line 75 of file gate.hpp.
GateTypeByDI
template<typename LocalVector_ , typename Mirror_ > template<typename DataType2_ , typename IndexType2_ > using FEAT::Global::Gate< LocalVector_, Mirror_ >::GateTypeByDI = Gate<typename LocalVector_::template ContainerType<DataType2_, IndexType2_>, typename Mirror_::template MirrorType<DataType2_, IndexType2_> >
this typedef lets you create a gate container with new Data and Index types
Definition at line 79 of file gate.hpp.
IndexType
template<typename LocalVector_ , typename Mirror_ > typedef LocalVector_::IndexType FEAT::Global::Gate< LocalVector_, Mirror_ >::IndexType
Definition at line 56 of file gate.hpp.
MirrorType
template<typename LocalVector_ , typename Mirror_ > typedef Mirror_ FEAT::Global::Gate< LocalVector_, Mirror_ >::MirrorType
Definition at line 58 of file gate.hpp.
ScalarTicketType
template<typename LocalVector_ , typename Mirror_ > typedef SynchScalarTicket<DataType> FEAT::Global::Gate< LocalVector_, Mirror_ >::ScalarTicketType
Definition at line 60 of file gate.hpp.
VectorTicketType
template<typename LocalVector_ , typename Mirror_ > typedef SynchVectorTicket<LocalVector_, Mirror_> FEAT::Global::Gate< LocalVector_, Mirror_ >::VectorTicketType
Definition at line 61 of file gate.hpp.
Constructor & Destructor Documentation
Gate() [1/3]
template<typename LocalVector_ , typename Mirror_ > FEAT::Global::Gate< LocalVector_, Mirror_ >::Gate () inline explicit
standard constructor
Definition at line 83 of file gate.hpp.
Gate() [2/3]
template<typename LocalVector_ , typename Mirror_ > FEAT::Global::Gate< LocalVector_, Mirror_ >::Gate (const Dist::Comm & comm) inline explicit
Constructor.
Parameters
[in] comm A resident reference to the communicator to be used by the gate.
Definition at line 94 of file gate.hpp.
Gate() [3/3]
template<typename LocalVector_ , typename Mirror_ > FEAT::Global::Gate< LocalVector_, Mirror_ >::Gate (Gate< LocalVector_, Mirror_ > && other) inline
move constructor
Definition at line 100 of file gate.hpp.
~Gate()
template<typename LocalVector_ , typename Mirror_ > virtual FEAT::Global::Gate< LocalVector_, Mirror_ >::~Gate () inline virtual
virtual destructor
Definition at line 125 of file gate.hpp.
Member Function Documentation
bytes()
template<typename LocalVector_ , typename Mirror_ > std::size_t FEAT::Global::Gate< LocalVector_, Mirror_ >::bytes () const inline
Returns the total amount of bytes allocated.
Definition at line 252 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, and FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks.
Referenced by FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::bytes(), and FEAT::Control::ScalarBasicSystemLevel< DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::bytes().
compile()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Gate< LocalVector_, Mirror_ >::compile (LocalVector_ && vector) inline
Compiles the gate to finish its setup.
Parameters
[in] vector A temporary vector allocated to the correct size which is used for initialization of the internal frequencies vector. Its numerical contents are ignored.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 296 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs, and FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates(), FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_gates(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::convert().
convert() [1/2]
template<typename LocalVector_ , typename Mirror_ > template<typename LVT2_ > void FEAT::Global::Gate< LocalVector_, Mirror_ >::convert (const Gate< LVT2_, Mirror_ > & other, LocalVector_ && vector, LAFEM::CloneMode mode = LAFEM::CloneMode::Shallow) inline
Conversion function for different vector container type.
This function (re)creates this gate from another gate with a different vector type, but the same mirrors. This can be used to create a gate using DenseVectorBlocked from a gate using DenseVector or vice versa.
Parameters
[in] other A (transient) reference to the gate using the other vector type to create this gate from.
[in] vector A temporary vector allocated to the correct size that is to be used for internal initialization.
[in] mode The clone-mode to be used for cloning the mirrors. Defaults to shallow clone.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 228 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, and FEAT::Global::Gate< LocalVector_, Mirror_ >::compile().
convert() [2/2]
template<typename LocalVector_ , typename Mirror_ > template<typename LVT2_ , typename MT2_ > void FEAT::Global::Gate< LocalVector_, Mirror_ >::convert (const Gate< LVT2_, MT2_ > & other) inline
Conversion function for same vector container type but with different MDI-Type.
Parameters
[in] other A transient reference to the gate to convert from
Definition at line 187 of file gate.hpp.
dot()
template<typename LocalVector_ , typename Mirror_ > DataType FEAT::Global::Gate< LocalVector_, Mirror_ >::dot (const LocalVector_ & x, const LocalVector_ & y) const inline
Computes a synchronized dot-product of two type-1 vectors.
Parameters
[in] x,y The two type-1 vector whose dot-product is to be computed.
Returns
The dot-product of x and y.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 506 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, FEAT::Dist::Comm::size(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sum().
Referenced by FEAT::Global::Vector< LocalVector_, Mirror_ >::dot().
dot_async()
template<typename LocalVector_ , typename Mirror_ > ScalarTicketType FEAT::Global::Gate< LocalVector_, Mirror_ >::dot_async (const LocalVector_ & x, const LocalVector_ & y, bool sqrt = false) const inline
Computes a synchronized dot-product of two type-1 vectors.
Parameters
[in] x,y The two type-1 vector whose dot-product is to be computed.
Returns
A scalar ticket that has to be waited upon to complete the operation.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 536 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs, and FEAT::Global::Gate< LocalVector_, Mirror_ >::sum_async().
Referenced by FEAT::Global::Vector< LocalVector_, Mirror_ >::dot_async(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::norm2_async().
from_1_to_0()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Gate< LocalVector_, Mirror_ >::from_1_to_0 (LocalVector_ & vector) const inline
Converts a type-1 vector into a type-0 vector.
Parameters
[in,out] vector On entry, the type-1 vector to be converted. On exit, the converted type-0 vector.
Note
This function does not perform any synchronization.
Definition at line 387 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs, and FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks.
Referenced by FEAT::Global::Vector< LocalVector_, Mirror_ >::from_1_to_0(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1_async().
get_comm()
template<typename LocalVector_ , typename Mirror_ > const Dist::Comm * FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm () const inline
Returns a const pointer to the underlying communicator.
Returns
A const pointer to the underlying communicator
Definition at line 134 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::Matrix(), FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::assemble_by_gate(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::bytes(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::get_comm(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::get_comm(), FEAT::Global::Vector< LocalVector_, Mirror_ >::get_comm(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_symbolic(), and FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::used_elements().
get_freqs()
template<typename LocalVector_ , typename Mirror_ > const LocalVector_ & FEAT::Global::Gate< LocalVector_, Mirror_ >::get_freqs () const inline
Returns a const reference to the frequencies vector.
Returns
A const reference to the frequencies vector
Definition at line 175 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs.
get_mirrors()
template<typename LocalVector_ , typename Mirror_ > const std::vector< Mirror_ > & FEAT::Global::Gate< LocalVector_, Mirror_ >::get_mirrors () const inline
Returns a const reference to the neighbor mirrors vector.
Returns
A const reference to the neighbor mirrors vector
Definition at line 165 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors.
get_num_global_dofs()
template<typename LocalVector_ , typename Mirror_ > template<LAFEM::Perspective perspective_ = LAFEM::Perspective::native> Index FEAT::Global::Gate< LocalVector_, Mirror_ >::get_num_global_dofs () const inline
Returns the number of global DOFs.
Template Parameters
perspective_ Specifies whether to compute the native or POD DOF count
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Returns
The number of global DOFS; either in native or POD size
Definition at line 343 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, FEAT::Dist::Comm::allreduce(), FEAT::Dist::op_sum, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
get_num_local_dofs()
template<typename LocalVector_ , typename Mirror_ > template<LAFEM::Perspective perspective_ = LAFEM::Perspective::native> Index FEAT::Global::Gate< LocalVector_, Mirror_ >::get_num_local_dofs () const inline
Returns the number of local DOFs.
Template Parameters
perspective_ Specifies whether to compute the native or POD DOF count
Returns
The number of local DOFS; either in native or POD size
Definition at line 326 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs.
get_ranks()
template<typename LocalVector_ , typename Mirror_ > const std::vector< int > FEAT::Global::Gate< LocalVector_, Mirror_ >::get_ranks () const inline
Returns a const reference to the neighbor ranks vector.
Returns
A const reference to the neighbor ranks vector
Definition at line 155 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks.
max()
template<typename LocalVector_ , typename Mirror_ > DataType FEAT::Global::Gate< LocalVector_, Mirror_ >::max (DataType x) const inline
Computes the maximum of a scalar variable over all processes.
Parameters
[in] x What we want to compute the maximum over all processes of.
Returns
The maximum of all x.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 619 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::max_async(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
Referenced by FEAT::Assembly::BurgersAssemblyJobBase< DataType_, Space_, ConvVector_ >::calc_sd_v_norm(), FEAT::Global::Vector< LocalVector_, Mirror_ >::max_abs_element(), FEAT::Assembly::BurgersAssembler< DataType_, IndexType_, dim_ >::set_sd_v_norm(), and FEAT::Assembly::BurgersAssemblerCarreau< DataType_, IndexType_, dim_ >::set_sd_v_norm().
max_async()
template<typename LocalVector_ , typename Mirror_ > ScalarTicketType FEAT::Global::Gate< LocalVector_, Mirror_ >::max_async (DataType x) const inline
Computes the maximum of a scalar variable over all processes.
Parameters
[in] x What we want to compute the maximum over all processes of.
Returns
A scalar ticket that has to be waited upon to complete the operation.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 635 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, and FEAT::Dist::op_max.
Referenced by FEAT::Global::Gate< LocalVector_, Mirror_ >::max(), FEAT::Global::Vector< LocalVector_, Mirror_ >::max_abs_element_async(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::max_element_async().
min()
template<typename LocalVector_ , typename Mirror_ > DataType FEAT::Global::Gate< LocalVector_, Mirror_ >::min (DataType x) const inline
Computes the minimum of a scalar variable over all processes.
Parameters
[in] x What we want to compute the minimum over all processes of.
Returns
The minimum of all x.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 586 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::min_async(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
Referenced by FEAT::Global::Vector< LocalVector_, Mirror_ >::min_abs_element().
min_async()
template<typename LocalVector_ , typename Mirror_ > ScalarTicketType FEAT::Global::Gate< LocalVector_, Mirror_ >::min_async (DataType x) const inline
Computes the minimum of a scalar variable over all processes.
Parameters
[in] x What we want to compute the minimum over all processes of.
Returns
A scalar ticket that has to be waited upon to complete the operation.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 602 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, and FEAT::Dist::op_min.
Referenced by FEAT::Global::Gate< LocalVector_, Mirror_ >::min(), FEAT::Global::Vector< LocalVector_, Mirror_ >::min_abs_element_async(), and FEAT::Global::Vector< LocalVector_, Mirror_ >::min_element_async().
norm2()
template<typename LocalVector_ , typename Mirror_ > DataType FEAT::Global::Gate< LocalVector_, Mirror_ >::norm2 (DataType x) const inline
Computes a reduced 2-norm over all processes.
This function is equivalent to the call Math::sqrt(this->sum(x*x))
Parameters
[in] x The value that is to be summarized over all processes.
Returns
The reduced 2-norm of all x.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 655 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::norm2_async(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
norm2_async()
template<typename LocalVector_ , typename Mirror_ > ScalarTicketType FEAT::Global::Gate< LocalVector_, Mirror_ >::norm2_async (DataType x) const inline
Computes a reduced 2-norm over all processes.
This function is equivalent to the call Math::sqrt(this->sum(x*x))
Parameters
[in] x The value that is to be summarized over all processes.
Returns
A scalar ticket that has to be waited upon to complete the operation.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 674 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, and FEAT::Dist::op_sum.
Referenced by FEAT::Global::Gate< LocalVector_, Mirror_ >::norm2().
operator=()
template<typename LocalVector_ , typename Mirror_ > Gate & FEAT::Global::Gate< LocalVector_, Mirror_ >::operator= (Gate< LocalVector_, Mirror_ > && other) inline
move-assign operator
Definition at line 109 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, and FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks.
push()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Gate< LocalVector_, Mirror_ >::push (int rank, Mirror_ && mirror) inline
Adds a mirror for a neighbor process.
Parameters
[in] rank The rank of the neighbor with respect to our communicator
[in] mirror The mirror assembled for the halo of this neighbor process.
Definition at line 274 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates(), and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_gates().
set_comm()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Gate< LocalVector_, Mirror_ >::set_comm (const Dist::Comm * comm_) inline
Sets the communicator for this gate.
Parameters
[in] comm_ A resident pointer to the communicator object to use.
Definition at line 145 of file gate.hpp.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates(), and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_gates().
sum()
template<typename LocalVector_ , typename Mirror_ > DataType FEAT::Global::Gate< LocalVector_, Mirror_ >::sum (DataType x) const inline
Computes a reduced sum over all processes.
Parameters
[in] x The value that is to be summed over all processes.
Returns
The reduced sum of all x.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 553 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::sum_async(), and FEAT::Global::SynchScalarTicket< DT_ >::wait().
Referenced by FEAT::Global::Gate< LocalVector_, Mirror_ >::dot(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::eval_fval_grad(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::init(), and FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::prepare().
sum_async()
template<typename LocalVector_ , typename Mirror_ > ScalarTicketType FEAT::Global::Gate< LocalVector_, Mirror_ >::sum_async (DataType x, bool sqrt = false) const inline
Computes a reduced sum over all processes.
Parameters
[in] x The value that is to be summed over all processes.
Returns
A scalar ticket that has to be waited upon to complete the operation.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 569 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, and FEAT::Dist::op_sum.
Referenced by FEAT::Global::Gate< LocalVector_, Mirror_ >::dot_async(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sum().
sync_0()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0 (LocalVector_ & vector) const inline
Synchronizes a type-0 vector, resulting in a type-1 vector.
This function performs a type-0 synchronization, i.e. sums up all local DOF contributions for each DOF, by exchanging the DOF values of each shared DOF among all nearest neighbors.
Parameters
[in,out] vector On entry, the type-0 vector to be synchronized.
On exit, the synchronized type-1 vector.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 408 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::wait().
Referenced by FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::init(), FEAT::Global::NonlinearFunctional< LocalNonlinearFunctional_, RowMirrorType_, ColMirrorType_ >::prepare(), FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0(), and FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::sync_system_filter().
sync_0_async()
template<typename LocalVector_ , typename Mirror_ > VectorTicketType FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0_async (LocalVector_ & vector) const inline
Synchronizes a type-0 vector, resulting in a type-1 vector.
This function performs a type-0 synchronization, i.e. sums up all local DOF contributions for each DOF, by exchanging the DOF values of each shared DOF among all nearest neighbors.
Parameters
[in,out] vector On entry, the type-0 vector to be synchronized.
On exit, the synchronized type-1 vector.
Returns
A ticket that has to be waited upon to complete the sync operation.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 432 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, and FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks.
Referenced by FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0_async().
sync_1()
template<typename LocalVector_ , typename Mirror_ > void FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1 (LocalVector_ & vector) const inline
Synchronizes a type-1 vector, resulting in a type-1 vector.
This function performs a type-1 synchronization, i.e. averages all local DOF contributions for each DOF, by exchanging the DOF values of each shared DOF among all nearest neighbors.
Parameters
[in,out] vector On entry, the type-1 vector to be synchronized.
On exit, the synchronized type-1 vector.
Note
This function effectively applies the from_1_to_0() and sync_0() functions onto the input vector.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 457 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, FEAT::Global::Gate< LocalVector_, Mirror_ >::from_1_to_0(), and FEAT::Global::SynchVectorTicket< VT_, VMT_ >::wait().
Referenced by FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_1().
sync_1_async()
template<typename LocalVector_ , typename Mirror_ > VectorTicketType FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1_async (LocalVector_ & vector) const inline
Synchronizes a type-1 vector, resulting in a type-1 vector.
This function performs a type-1 synchronization, i.e. averages all local DOF contributions for each DOF, by exchanging the DOF values of each shared DOF among all nearest neighbors.
Parameters
[in,out] vector On entry, the type-1 vector to be synchronized.
On exit, the synchronized type-1 vector.
Returns
A ticket that has to be waited upon to complete the sync operation.
Note
This function effectively applies the from_1_to_0() and sync_0() functions onto the input vector.
Attention
This function is collective, i.e. it must be called by all processes participating in the gate's communicator, otherwise the application will deadlock.
Definition at line 485 of file gate.hpp.
References FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm, FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors, FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks, and FEAT::Global::Gate< LocalVector_, Mirror_ >::from_1_to_0().
Referenced by FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_1_async().
Member Data Documentation
_comm
template<typename LocalVector_ , typename Mirror_ > const Dist::Comm* FEAT::Global::Gate< LocalVector_, Mirror_ >::_comm
our communicator
Definition at line 65 of file gate.hpp.
Referenced by FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1(), FEAT::Global::Gate< LocalVector_, Mirror_ >::dot(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_comm(), FEAT::Global::Gate< LocalVector_, Mirror_ >::max_async(), FEAT::Global::Gate< LocalVector_, Mirror_ >::min_async(), FEAT::Global::Gate< LocalVector_, Mirror_ >::norm2_async(), FEAT::Global::Gate< LocalVector_, Mirror_ >::operator=(), FEAT::Global::Gate< LocalVector_, Mirror_ >::push(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sum_async(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0_async(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1_async().
_freqs
template<typename LocalVector_ , typename Mirror_ > LocalVector_ FEAT::Global::Gate< LocalVector_, Mirror_ >::_freqs
frequency vector
Definition at line 71 of file gate.hpp.
Referenced by FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::assemble_by_gate(), FEAT::Global::Gate< LocalVector_, Mirror_ >::bytes(), FEAT::Global::Gate< LocalVector_, Mirror_ >::compile(), FEAT::Global::Gate< LocalVector_, Mirror_ >::dot(), FEAT::Global::Gate< LocalVector_, Mirror_ >::dot_async(), FEAT::Global::Gate< LocalVector_, Mirror_ >::from_1_to_0(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_freqs(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_num_local_dofs(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::operator=().
_mirrors
template<typename LocalVector_ , typename Mirror_ > std::vector<Mirror_> FEAT::Global::Gate< LocalVector_, Mirror_ >::_mirrors
vector mirrors
Definition at line 69 of file gate.hpp.
Referenced by FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::assemble_by_gate(), FEAT::Global::Gate< LocalVector_, Mirror_ >::bytes(), FEAT::Global::Gate< LocalVector_, Mirror_ >::compile(), FEAT::Global::Gate< LocalVector_, Mirror_ >::convert(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_mirrors(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_num_global_dofs(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_symbolic(), FEAT::Global::Gate< LocalVector_, Mirror_ >::operator=(), FEAT::Global::Gate< LocalVector_, Mirror_ >::push(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0_async(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1_async().
_ranks
template<typename LocalVector_ , typename Mirror_ > std::vector<int> FEAT::Global::Gate< LocalVector_, Mirror_ >::_ranks
communication ranks
Definition at line 67 of file gate.hpp.
Referenced by FEAT::Global::AlgDofParti< LAFEM::DenseVector< DT_, IT_ >, LAFEM::VectorMirror< DT_, IT_ > >::assemble_by_gate(), FEAT::Global::Gate< LocalVector_, Mirror_ >::bytes(), FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::convert_to_1(), FEAT::Global::Gate< LocalVector_, Mirror_ >::dot(), FEAT::Global::Gate< LocalVector_, Mirror_ >::from_1_to_0(), FEAT::Global::Gate< LocalVector_, Mirror_ >::get_ranks(), FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::init_symbolic(), FEAT::Global::Gate< LocalVector_, Mirror_ >::operator=(), FEAT::Global::Gate< LocalVector_, Mirror_ >::push(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_0_async(), FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1(), and FEAT::Global::Gate< LocalVector_, Mirror_ >::sync_1_async().
The documentation for this class was generated from the following file:
kernel/global/gate.hpp