FEAT: FEAT::Control::Domain::PartiDomainControl< DomainLevel_ > Class Template Reference
FEAT::Control::Domain::PartiDomainControl< DomainLevel_ > Class Template Reference
Recursively Partitioned Domain Control.
#include <parti_domain_control.hpp>
Classes
class Ancestor
Ancestor info class.
Public Types
typedef BaseClass::AtlasType AtlasType
our atlas type
typedef Control::Domain::DomainControl< DomainLevel_ > BaseClass
Our base class.
typedef BaseClass::LayerType LayerType
our domain layer type
typedef BaseClass::LevelType LevelType
our domain level type
typedef Geometry::RootMeshNode< MeshType > MeshNodeType
our root mesh node type
typedef LevelType::PartType MeshPartType
our mesh-part type
typedef BaseClass::MeshType MeshType
our mesh type
typedef LevelType::ShapeType ShapeType
typedef VirtualLevel< LevelType > VirtLevelType
Public Member Functions
PartiDomainControl (const Dist::Comm &comm_, bool support_multi_layered)
Constructor.
virtual ~PartiDomainControl ()
virtual destructor
VirtLevelType & at (std::size_t i)
const VirtLevelType & at (std::size_t i) const
VirtLevelType & back ()
const VirtLevelType & back () const
LayerType & back_layer ()
const LayerType & back_layer () const
std::size_t bytes () const
const Dist::Comm & comm () const
void compile_virtual_levels ()
void create (const std::deque< String > &filenames, String dirpath="")
Creates a domain control from a list of filenames.
void create (Geometry::MeshFileReader &mesh_reader)
Creates a domain control from a MeshFileReader.
void create (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a domain control from a base-mesh node.
void create_mesh_permutations ()
Creates the mesh permutations based on the chosen permutation strategy.
void create_rectilinear (Index num_elems_x, Index num_elems_y=0u, Index num_elems_z=0u)
Creates a domain control from a structured rectilinear base mesh.
String dump_ancestry () const
Debugging function: Returns a string containing encoded ancestry information.
String dump_layer_levels () const
String dump_layers () const
String dump_virt_levels () const
String format_chosen_levels () const
Returns the chosen levels formatted as a parsable string.
String format_desired_levels () const
Returns the desired levels formatted as a parsable string.
VirtLevelType & front ()
const VirtLevelType & front () const
LayerType & front_layer ()
const LayerType & front_layer () const
Geometry::AdaptMode get_adapt_mode () const
Gets the adapt-mode for refinement.
const std::deque< Ancestor > & get_ancestry () const
Returns a const reference to the ancestry.
AtlasType & get_atlas ()
const AtlasType & get_atlas () const
const std::deque< std::pair< int, int > > get_chosen_levels () const
Returns the deque of chosen refinement levels.
String get_chosen_parti_info () const
Returns an informative string about the chosen partitioning.
int get_desired_level_max () const
Returns the desired maximum refinement level.
int get_desired_level_min () const
Returns the desired minimum refinement level.
const std::deque< std::pair< int, int > > get_desired_levels () const
Returns the deque of desired refinement levels.
Geometry::PermutationStrategy get_permutation_strategy () const
bool has_ghost () const
void keep_base_levels ()
Instructs the domain controller to keep the base-mesh levels after partitioning.
int max_level_index () const
int med_level_index () const
int min_level_index () const
std::size_t num_global_layers () const
std::size_t num_local_layers () const
bool parse_args (SimpleArgParser &args)
Parses the partitioner options from an argument parser.
bool parse_property_map (PropertyMap &pmap)
Parses the partitioner options from a PropertyMap.
virtual void print () const
void push_layer (std::shared_ptr< LayerType > layer)
void push_level_back (int layer_index, std::shared_ptr< LevelType > level)
void push_level_front (int layer_index, std::shared_ptr< LevelType > level)
std::vector< char > serialize_partitioning () const
Serializes the partitioning information into a binary buffer.
void set_adapt_mode (Geometry::AdaptMode adapt_mode)
Sets the adapt-mode for refinement.
void set_desired_levels (const std::deque< String > &slvls)
Sets the desired levels for the partitioned hierarchy.
void set_desired_levels (const String &slvls)
Sets the desired levels for the partitioned hierarchy.
void set_desired_levels (int lvl_max, int lvl_med, int lvl_min)
Sets the desired refinement levels for a double-layered hierarchy.
void set_desired_levels (int lvl_max, int lvl_min=-1)
Sets the desired refinement levels for a single-layered hierarchy.
void set_permutation_strategy (Geometry::PermutationStrategy strategy)
Sets the permutation strategy for mesh permutation.
std::size_t size_physical () const
std::size_t size_virtual () const
Static Public Member Functions
static String name ()
Protected Member Functions
bool _apply_parti (Ancestor &ancestor, MeshNodeType &base_mesh_node)
Applies an a-posteriori partitioner.
bool _apply_parti_genetic (Ancestor &ancestor, MeshNodeType &base_mesh_node)
Applies the genetic partitioner onto the base-mesh.
bool _apply_parti_metis (Ancestor &ancestor, const MeshNodeType &base_mesh_node)
Applies the METIS partitioner onto the base-mesh.
bool _apply_parti_naive (Ancestor &ancestor, const MeshNodeType &mesh_node)
Applies the naive partitioner onto the base-mesh.
bool _apply_parti_zoltan (Ancestor &ancestor, const MeshNodeType &base_mesh_node)
Applies the Zoltan partitioner onto the base-mesh.
bool _check_parti (Ancestor &ancestor, const MeshNodeType &mesh_node, bool check_extern)
Checks for an appropriate partitioning strategy.
bool _check_parti_2level (Ancestor &ancestor, const MeshNodeType &base_mesh_node)
Checks whether the 2-level partitioner can be applied.
bool _check_parti_extern (Ancestor &ancestor)
Checks whether an extern partition is given.
void _create_ancestry_scattered ()
Creates the layers for a multi-layered domain control in a scattered fashion.
void _create_ancestry_single ()
Creates the ancestry for a single layer (or a single process)
void _create_multi_layered (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a multi-layered mesh hierarchy.
void _create_multi_layers_scattered ()
Creates the layers for a multi-layered domain control in a scattered fashion.
void _create_single_layered (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a single-layered mesh hierarchy.
void _create_single_process (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a single-layered mesh hierarchy for a single process.
void _split_basemesh_halos (const Ancestor &ancestor, const MeshNodeType &base_mesh_node, MeshNodeType &patch_mesh_node, std::vector< int > &neighbor_ranks)
Splits the base-mesh halos and computes the inter-patch-mesh halos.
Protected Attributes
Geometry::AdaptMode _adapt_mode
the adapt mode for refinement
bool _allow_parti_2level
allow 2-level partitioner?
bool _allow_parti_extern
allow extern partitioner?
bool _allow_parti_genetic
allow genetic partitioner?
bool _allow_parti_metis
allow metis partitioner?
bool _allow_parti_naive
allow naive partitioner?
bool _allow_parti_zoltan
allow Zoltan partitioner?
std::deque< Ancestor > _ancestry
the partition ancestry deque
AtlasType _atlas
std::deque< std::shared_ptr< LevelType > > _base_levels
std::deque< std::pair< int, int > > _chosen_levels
chosen level deque
const Dist::Comm & _comm
std::deque< std::pair< int, int > > _desired_levels
desired level deque
std::deque< String > _extern_parti_names
required partition name for extern partitioning
double _genetic_time_init
time for genetic partitioner initialization
double _genetic_time_mutate
time for genetic partitioner mutation
bool _keep_base_levels
keep base-mesh levels on root process?
std::deque< std::deque< std::shared_ptr< LevelType > > > _layer_levels
std::deque< std::shared_ptr< LayerType > > _layers
std::size_t _num_global_layers
Geometry::PartitionSet _parti_set
the extern partition sets
Geometry::PermutationStrategy _permutation_strategy
the permutation strategy for the mesh permutation
int _required_elems_per_rank
required number of elements per rank for a-posteriori partitioning
bool _support_multi_layered
support multi-layered hierarchy?
std::deque< VirtLevelType > _virt_levels
std::size_t _virt_size
bool _was_created
specifies whether the domain control was already created
Detailed Description
template<typename DomainLevel_>
class FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >
Recursively Partitioned Domain Control.
Todo:
document this
For more details on meshes, see the related doxygen page FEAT Mesh File Format.
Author
Peter Zajac
Definition at line 73 of file parti_domain_control.hpp.
Member Typedef Documentation
AtlasType
template<typename DomainLevel_ > typedef BaseClass::AtlasType FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::AtlasType
our atlas type
Definition at line 86 of file parti_domain_control.hpp.
BaseClass
template<typename DomainLevel_ > typedef Control::Domain::DomainControl<DomainLevel_> FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::BaseClass
Our base class.
Definition at line 78 of file parti_domain_control.hpp.
LayerType
template<typename DomainLevel_ > typedef BaseClass::LayerType FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::LayerType
our domain layer type
Definition at line 82 of file parti_domain_control.hpp.
LevelType
template<typename DomainLevel_ > typedef BaseClass::LevelType FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::LevelType
our domain level type
Definition at line 80 of file parti_domain_control.hpp.
MeshNodeType
template<typename DomainLevel_ > typedef Geometry::RootMeshNode<MeshType> FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::MeshNodeType
our root mesh node type
Definition at line 88 of file parti_domain_control.hpp.
MeshPartType
template<typename DomainLevel_ > typedef LevelType::PartType FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::MeshPartType
our mesh-part type
Definition at line 90 of file parti_domain_control.hpp.
MeshType
template<typename DomainLevel_ > typedef BaseClass::MeshType FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::MeshType
our mesh type
Definition at line 84 of file parti_domain_control.hpp.
ShapeType
typedef LevelType::ShapeType FEAT::Control::Domain::DomainControl< DomainLevel_ >::ShapeType inherited
Definition at line 417 of file domain_control.hpp.
VirtLevelType
typedef VirtualLevel<LevelType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::VirtLevelType inherited
Definition at line 415 of file domain_control.hpp.
Constructor & Destructor Documentation
PartiDomainControl()
template<typename DomainLevel_ > FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::PartiDomainControl (const Dist::Comm & comm_, bool support_multi_layered) inline explicit
Constructor.
Parameters
[in] comm_ A resident reference to the main communicator to be used.
[in] support_multi_layered Specifies whether the controller is allowed to create multi-layered hierarchies.
Definition at line 190 of file parti_domain_control.hpp.
~PartiDomainControl()
template<typename DomainLevel_ > virtual FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::~PartiDomainControl () inline virtual
virtual destructor
Definition at line 212 of file parti_domain_control.hpp.
Member Function Documentation
_apply_parti()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti (Ancestor & ancestor, MeshNodeType & base_mesh_node) inline protected
Applies an a-posteriori partitioner.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
Returns
true, if the base-mesh was partitioned, otherwise false.
Definition at line 1900 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_genetic(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_metis(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_naive(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_zoltan(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_apriori, and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered().
_apply_parti_genetic()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_genetic (Ancestor & ancestor, MeshNodeType & base_mesh_node) inline protected
Applies the genetic partitioner onto the base-mesh.
Parameters
[in] base_mesh_node The base-mesh node that is to be partitioned.
Returns
true.
Definition at line 2088 of file parti_domain_control.hpp.
References FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti().
_apply_parti_metis()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_metis (Ancestor & ancestor, const MeshNodeType & base_mesh_node) inline protected
Applies the METIS partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
Returns
true, if METIS was applied successfully, otherwise false.
Definition at line 2042 of file parti_domain_control.hpp.
References FEAT::Geometry::PartiParMETIS::build_elems_at_rank(), FEAT::Geometry::PartiParMETIS::execute(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti().
_apply_parti_naive()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_naive (Ancestor & ancestor, const MeshNodeType & mesh_node) inline protected
Applies the naive partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] mesh_node The base-mesh node that is to be partitioned.
Returns
true, if a naive partition was created successfully, otherwise false.
Definition at line 2124 of file parti_domain_control.hpp.
References FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_info, and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti().
_apply_parti_zoltan()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti_zoltan (Ancestor & ancestor, const MeshNodeType & base_mesh_node) inline protected
Applies the Zoltan partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
Returns
true, if Zoltan was applied successfully, otherwise false.
Definition at line 1997 of file parti_domain_control.hpp.
References FEAT::Geometry::PartiZoltan::build_elems_at_rank(), FEAT::Geometry::PartiZoltan::execute(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti().
_check_parti()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti (Ancestor & ancestor, const MeshNodeType & mesh_node, bool check_extern) inline protected
Checks for an appropriate partitioning strategy.
This function examines the given base mesh and checks whether one of the a-priori partitioning strategies (extern or 2-level) yields a valid partitioning for the given number of partitions. If so, the corresponding partitioning level and graph are stored in ancestor.parti_level and ancestor.parti_graph. If not, this function determines how often the base-mesh has to be refined until its has enough cells so that one of the a-posteriori partitioners can be applied.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] mesh_node The base-mesh node that is to be partitioned.
[in] check_extern Set to true, if #base_mesh_node is the mesh node that corresponds to the input file's mesh and therefore extern partitioning is a valid option, or set to false in any other case.
Returns
true, if an a-priori partitioning was found, otherwise false.
Definition at line 1853 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_2level(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_extern(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_required_elems_per_rank, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Math::max(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_level.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered().
_check_parti_2level()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_2level (Ancestor & ancestor, const MeshNodeType & base_mesh_node) inline protected
Checks whether the 2-level partitioner can be applied.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
Returns
true, if the 2-level partitioner can be applied, otherwise false.
Definition at line 1964 of file parti_domain_control.hpp.
References FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_apriori, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_info, and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_level.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti().
_check_parti_extern()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_extern (Ancestor & ancestor) inline protected
Checks whether an extern partition is given.
Parameters
[in,out] ancestor The ancestor object for this layer.
Returns
true, if an extern partition is given, otherwise false.
Definition at line 1933 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_extern_parti_names, FEAT::Adjacency::Graph::clone(), FEAT::Geometry::PartitionSet::find_partition(), FEAT::Geometry::Partition::get_level(), FEAT::Geometry::Partition::get_name(), FEAT::Geometry::Partition::get_patches(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_apriori, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_info, and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_level.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti().
_create_ancestry_scattered()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_ancestry_scattered () inline protected
Creates the layers for a multi-layered domain control in a scattered fashion.
Definition at line 1223 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels, FEAT::Dist::Comm::comm_create_range_incl(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_procs, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered().
_create_ancestry_single()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_ancestry_single () inline protected
Creates the ancestry for a single layer (or a single process)
Definition at line 955 of file parti_domain_control.hpp.
References FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_procs, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process().
_create_multi_layered()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected
Creates a multi-layered mesh hierarchy.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Definition at line 1288 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_ancestry, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_ancestry_scattered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layers_scattered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_split_basemesh_halos(), FEAT::Dist::Comm::allreduce(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::layer_p, FEAT::Math::max(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Dist::op_max, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_level, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), XABORTM, XASSERT, and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create().
_create_multi_layers_scattered()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layers_scattered () inline protected
Creates the layers for a multi-layered domain control in a scattered fashion.
Definition at line 1162 of file parti_domain_control.hpp.
References FEAT::Dist::Comm::comm, FEAT::Dist::Comm::comm_create_range_incl(), FEAT::Dist::Comm::comm_dup(), FEAT::Dist::Comm::is_null(), FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered().
_create_single_layered()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected
Creates a single-layered mesh hierarchy.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Definition at line 1059 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_apply_parti(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_ancestry_single(), FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels, FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_level, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XABORTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create().
_create_single_process()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected
Creates a single-layered mesh hierarchy for a single process.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Note
This function does not keep the base-mesh levels explicitly even if _keep_base_levels is set to true, because it is not required to use the base splitter on a single process.
Definition at line 1003 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_ancestry_single(), FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::parti_info, and FEAT::String::push_front().
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create().
_split_basemesh_halos()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_split_basemesh_halos (const Ancestor & ancestor, const MeshNodeType & base_mesh_node, MeshNodeType & patch_mesh_node, std::vector< int > & neighbor_ranks) inline protected
Splits the base-mesh halos and computes the inter-patch-mesh halos.
This is where the magic happens in the case of the multi-layered hierarchy.
Parameters
[in] ancestor The ancestor object for the current layer.
[in] base_mesh_node The base-mesh node that has been partitioned and whose halos are to be split.
[in,out] patch_mesh_node The patch-mesh node that represents the partition whose halos are to be computed.
[in,out] neighbor_ranks The vector that receives the ranks of the new neighbors that derive from halo splitting.
Definition at line 1540 of file parti_domain_control.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_halo(), FEAT::Dist::Comm::bcast(), FEAT::Dist::Comm::gather(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::is_null(), FEAT::Dist::Comm::isend(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::Ancestor::layer_p, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), FEAT::Dist::RequestVector::wait_all(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered().
at() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::at (std::size_t i) inline inherited
Definition at line 579 of file domain_control.hpp.
at() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::at (std::size_t i) const inline inherited
Definition at line 584 of file domain_control.hpp.
back() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back () inline inherited
Definition at line 599 of file domain_control.hpp.
back() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back () const inline inherited
Definition at line 604 of file domain_control.hpp.
back_layer() [1/2]
LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back_layer () inline inherited
Definition at line 519 of file domain_control.hpp.
back_layer() [2/2]
const LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back_layer () const inline inherited
Definition at line 524 of file domain_control.hpp.
bytes()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::bytes () const inline inherited
Definition at line 477 of file domain_control.hpp.
comm()
const Dist::Comm & FEAT::Control::Domain::DomainControl< DomainLevel_ >::comm () const inline inherited
Definition at line 472 of file domain_control.hpp.
compile_virtual_levels()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::compile_virtual_levels () inline inherited
Definition at line 637 of file domain_control.hpp.
create() [1/3]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create (const std::deque< String > & filenames, String dirpath = "") inline
Creates a domain control from a list of filenames.
Parameters
[in] filenames A list of mesh filenames from which the domain control is to be created.
[in] dirpath The path in which the mesh files are located.
Definition at line 675 of file parti_domain_control.hpp.
References FEAT::Geometry::MeshFileReader::add_mesh_files(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create().
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_rectilinear().
create() [2/3]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create (Geometry::MeshFileReader & mesh_reader) inline
Creates a domain control from a MeshFileReader.
Parameters
[in,out] mesh_reader A transient reference to the mesh reader from which the domain control is to be created.
Definition at line 693 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_parti_set, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), FEAT::TimeStamp::elapsed_now(), FEAT::Geometry::MeshFileReader::parse(), FEAT::Statistics::toe_partition, XASSERT, and XASSERTM.
create() [3/3]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create (std::unique_ptr< MeshNodeType > base_mesh_node) inline
Creates a domain control from a base-mesh node.
Parameters
[in] base_mesh_node The base-mesh node that the domain control is to be created from
Definition at line 715 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_parti_set, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_support_multi_layered, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_mesh_permutations(), FEAT::TimeStamp::elapsed_now(), FEAT::Dist::Comm::size(), FEAT::Statistics::toe_partition, XASSERT, and XASSERTM.
create_mesh_permutations()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_mesh_permutations () inline
Creates the mesh permutations based on the chosen permutation strategy.
Definition at line 802 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_permutation_strategy, and FEAT::Geometry::none.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create().
create_rectilinear()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_rectilinear (Index num_elems_x, Index num_elems_y = 0u, Index num_elems_z = 0u) inline
Creates a domain control from a structured rectilinear base mesh.
Note
This function also creates a mesh-part named "bnd" that represents the entire domain boundary.
Parameters
[in] num_elems_x,num_elems_y,num_elems_z The number of elements in each dimension for the base-mesh
Definition at line 773 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), FEAT::TimeStamp::elapsed_now(), FEAT::Geometry::RootMeshNode< MeshType >::make_unique(), FEAT::Statistics::toe_partition, XASSERT, and XASSERTM.
dump_ancestry()
template<typename DomainLevel_ > String FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::dump_ancestry () const inline
Debugging function: Returns a string containing encoded ancestry information.
Definition at line 818 of file parti_domain_control.hpp.
References FEAT::String::pad_front(), and FEAT::stringify().
dump_layer_levels()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_layer_levels () const inline inherited
Definition at line 735 of file domain_control.hpp.
dump_layers()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_layers () const inline inherited
Definition at line 713 of file domain_control.hpp.
dump_virt_levels()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_virt_levels () const inline inherited
Definition at line 748 of file domain_control.hpp.
format_chosen_levels()
template<typename DomainLevel_ > String FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::format_chosen_levels () const inline
Returns the chosen levels formatted as a parsable string.
The string returned by this function can be parsed by the set_desired_levels() function.
Returns
The chosen levels formatted as a parsable string.
Definition at line 599 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_chosen_levels, and FEAT::stringify().
format_desired_levels()
template<typename DomainLevel_ > String FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::format_desired_levels () const inline
Returns the desired levels formatted as a parsable string.
The string returned by this function can be parsed by the set_desired_levels() function.
Returns
The desired levels formatted as a parsable string.
Definition at line 578 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels, and FEAT::stringify().
front() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front () inline inherited
Definition at line 589 of file domain_control.hpp.
front() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front () const inline inherited
Definition at line 594 of file domain_control.hpp.
front_layer() [1/2]
LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front_layer () inline inherited
Definition at line 509 of file domain_control.hpp.
front_layer() [2/2]
const LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front_layer () const inline inherited
Definition at line 514 of file domain_control.hpp.
get_adapt_mode()
template<typename DomainLevel_ > Geometry::AdaptMode FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_adapt_mode () const inline
Gets the adapt-mode for refinement.
Returns
The adapt-mode that is used.
Definition at line 384 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_adapt_mode.
get_ancestry()
template<typename DomainLevel_ > const std::deque< Ancestor > & FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_ancestry () const inline
Returns a const reference to the ancestry.
Definition at line 851 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_ancestry.
get_atlas() [1/2]
AtlasType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::get_atlas () inline inherited
Definition at line 609 of file domain_control.hpp.
get_atlas() [2/2]
const AtlasType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::get_atlas () const inline inherited
Definition at line 614 of file domain_control.hpp.
get_chosen_levels()
template<typename DomainLevel_ > const std::deque< std::pair< int, int > > FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_chosen_levels () const inline
Returns the deque of chosen refinement levels.
Returns
The deque of chosen refinement levels.
Definition at line 661 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_chosen_levels.
get_chosen_parti_info()
template<typename DomainLevel_ > String FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_chosen_parti_info () const inline
Returns an informative string about the chosen partitioning.
Note
This function only returns something useful after the create() function has been called.
In the case of a multi-layered recursive partitioning, the returned string is a multi-line string containing the partitioning info for each recursive layer in a separate line.
Definition at line 625 of file parti_domain_control.hpp.
References FEAT::stringify().
get_desired_level_max()
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_desired_level_max () const inline
Returns the desired maximum refinement level.
Returns
The desired maximum refinement level
Definition at line 556 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels.
get_desired_level_min()
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_desired_level_min () const inline
Returns the desired minimum refinement level.
Returns
The desired minimum refinement level
Definition at line 566 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels.
get_desired_levels()
template<typename DomainLevel_ > const std::deque< std::pair< int, int > > FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_desired_levels () const inline
Returns the deque of desired refinement levels.
Returns
The deque of desired refinement levels.
Definition at line 651 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels.
get_permutation_strategy()
template<typename DomainLevel_ > Geometry::PermutationStrategy FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_permutation_strategy () const inline
Returns
The permutation strategy used for mesh permutation.
Definition at line 402 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_permutation_strategy.
has_ghost()
bool FEAT::Control::Domain::DomainControl< DomainLevel_ >::has_ghost () const inline inherited
Todo:
does this really work?
Definition at line 554 of file domain_control.hpp.
keep_base_levels()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::keep_base_levels () inline inherited
Instructs the domain controller to keep the base-mesh levels after partitioning.
Calling this function requests the domain controller to keep the base-mesh levels and refine them even after the partitioning process. This functionality is required to assemble a Global::Splitter object, which allows to serialize and deserialize vectors independent of the partitioning used to create the vector.
Attention
The functionality requested by this function is NOT scalable for large process counts, i.e. the root process WILL run out of memory in large-scale simulations. This functionality should only be used for moderate process counts.
Definition at line 632 of file domain_control.hpp.
max_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::max_level_index () const inline inherited
Definition at line 534 of file domain_control.hpp.
med_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::med_level_index () const inline inherited
Definition at line 539 of file domain_control.hpp.
min_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::min_level_index () const inline inherited
Definition at line 529 of file domain_control.hpp.
name()
static String FEAT::Control::Domain::DomainControl< DomainLevel_ >::name () inline static inherited
Definition at line 448 of file domain_control.hpp.
num_global_layers()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::num_global_layers () const inline inherited
Definition at line 493 of file domain_control.hpp.
num_local_layers()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::num_local_layers () const inline inherited
Definition at line 488 of file domain_control.hpp.
parse_args()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args (SimpleArgParser & args) inline
Parses the partitioner options from an argument parser.
See also
Control::Domain::add_supported_pdc_args()
Parameters
[in] args The parser that is to be used.
Returns
true, if the parsing was successful, or false, if at least one option was invalid.
Definition at line 228 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_2level, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_extern, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_genetic, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_metis, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_naive, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_zoltan, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_extern_parti_names, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_genetic_time_init, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_genetic_time_mutate, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_required_elems_per_rank, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, FEAT::SimpleArgParser::parse(), FEAT::Dist::Comm::print(), FEAT::SimpleArgParser::query(), and XASSERTM.
parse_property_map()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map (PropertyMap & pmap) inline
Parses the partitioner options from a PropertyMap.
Parameters
[in] pmap A transient reference to the property map that contains the configuration
Returns
true, if the parsing was successful, or false, if at least one option was invalid.
Definition at line 292 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_2level, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_extern, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_genetic, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_metis, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_naive, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_zoltan, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_genetic_time_init, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_genetic_time_mutate, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_required_elems_per_rank, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, FEAT::Dist::Comm::print(), FEAT::PropertyMap::query(), and XASSERTM.
print()
virtual void FEAT::Control::Domain::DomainControl< DomainLevel_ >::print () const inline virtual inherited
Definition at line 453 of file domain_control.hpp.
push_layer()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_layer (std::shared_ptr< LayerType > layer) inline inherited
Definition at line 498 of file domain_control.hpp.
push_level_back()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_level_back (int layer_index, std::shared_ptr< LevelType > level) inline inherited
Definition at line 549 of file domain_control.hpp.
push_level_front()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_level_front (int layer_index, std::shared_ptr< LevelType > level) inline inherited
Definition at line 544 of file domain_control.hpp.
serialize_partitioning()
template<typename DomainLevel_ > std::vector< char > FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::serialize_partitioning () const inline
Serializes the partitioning information into a binary buffer.
Definition at line 859 of file parti_domain_control.hpp.
References FEAT::Dist::Comm::allreduce(), FEAT::BinaryStream::container(), FEAT::Dist::Comm::gather(), FEAT::Dist::op_max, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
set_adapt_mode()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_adapt_mode (Geometry::AdaptMode adapt_mode) inline
Sets the adapt-mode for refinement.
Parameters
[in] adapt_mode The adapt-mode that is to be used.
Definition at line 372 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, and XASSERTM.
set_desired_levels() [1/4]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_desired_levels (const std::deque< String > & slvls) inline
Sets the desired levels for the partitioned hierarchy.
Parameters
[in] slvls A transient reference to the deque of strings containing the desired levels.
Each entry of the deque is supposed to be in the format level:nprocs.
Definition at line 427 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), FEAT::stringify(), and XASSERTM.
set_desired_levels() [2/4]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_desired_levels (const String & slvls) inline
Sets the desired levels for the partitioned hierarchy.
Parameters
[in] slvls A string containing the list of desired levels.
Definition at line 413 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_desired_levels(), and FEAT::String::split_by_whitespaces().
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_desired_levels().
set_desired_levels() [3/4]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_desired_levels (int lvl_max, int lvl_med, int lvl_min) inline
Sets the desired refinement levels for a double-layered hierarchy.
Parameters
[in] lvl_max The desired maximum refinement level. Must be >= 0.
[in] lvl_med The desired median refinement level. Must be < lvl_max If < 0, then (lvl_max+lvl_med+1) is used as the median level.
[in] lvl_min The desired minimum refinement level. Must be <= lvl_med. If < 0, then (lvl_med+lvl_min+1) is used as the minimum level.
Definition at line 527 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), and XASSERTM.
set_desired_levels() [4/4]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_desired_levels (int lvl_max, int lvl_min = -1) inline
Sets the desired refinement levels for a single-layered hierarchy.
Parameters
[in] lvl_max The desired maximum refinement level. Must be >= 0.
[in] lvl_min The desired minimum refinement level. Must be <= lvl_max. If < 0, then (lvl_max+lvl_min+1) is used as the minimum level.
Definition at line 497 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), and XASSERTM.
set_permutation_strategy()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_permutation_strategy (Geometry::PermutationStrategy strategy) inline
Sets the permutation strategy for mesh permutation.
Parameters
[in] strategy The mesh permutation strategy to be used.
Definition at line 395 of file parti_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_permutation_strategy, FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created, and XASSERTM.
size_physical()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::size_physical () const inline inherited
Definition at line 569 of file domain_control.hpp.
size_virtual()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::size_virtual () const inline inherited
Definition at line 564 of file domain_control.hpp.
Member Data Documentation
_adapt_mode
template<typename DomainLevel_ > Geometry::AdaptMode FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_adapt_mode protected
the adapt mode for refinement
Definition at line 140 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_adapt_mode(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_adapt_mode().
_allow_parti_2level
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_2level protected
allow 2-level partitioner?
Definition at line 149 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_allow_parti_extern
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_extern protected
allow extern partitioner?
Definition at line 147 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_allow_parti_genetic
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_genetic protected
allow genetic partitioner?
Definition at line 153 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_allow_parti_metis
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_metis protected
allow metis partitioner?
Definition at line 151 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_allow_parti_naive
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_naive protected
allow naive partitioner?
Definition at line 155 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_allow_parti_zoltan
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_allow_parti_zoltan protected
allow Zoltan partitioner?
Definition at line 157 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_ancestry
template<typename DomainLevel_ > std::deque<Ancestor> FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_ancestry protected
the partition ancestry deque
Definition at line 178 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_ancestry().
_atlas
AtlasType FEAT::Control::Domain::DomainControl< DomainLevel_ >::_atlas protected inherited
Definition at line 424 of file domain_control.hpp.
_base_levels
std::deque<std::shared_ptr<LevelType> > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_base_levels protected inherited
Definition at line 426 of file domain_control.hpp.
_chosen_levels
template<typename DomainLevel_ > std::deque<std::pair<int,int> > FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_chosen_levels protected
chosen level deque
Definition at line 166 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::format_chosen_levels(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_chosen_levels().
_comm
const Dist::Comm& FEAT::Control::Domain::DomainControl< DomainLevel_ >::_comm protected inherited
Definition at line 423 of file domain_control.hpp.
_desired_levels
template<typename DomainLevel_ > std::deque<std::pair<int,int> > FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_desired_levels protected
desired level deque
Definition at line 163 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_ancestry_scattered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::format_desired_levels(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_desired_level_max(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_desired_level_min(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_desired_levels(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_desired_levels().
_extern_parti_names
template<typename DomainLevel_ > std::deque<String> FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_extern_parti_names protected
required partition name for extern partitioning
Definition at line 169 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti_extern(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args().
_genetic_time_init
template<typename DomainLevel_ > double FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_genetic_time_init protected
time for genetic partitioner initialization
Definition at line 173 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_genetic_time_mutate
template<typename DomainLevel_ > double FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_genetic_time_mutate protected
time for genetic partitioner mutation
Definition at line 175 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_keep_base_levels
bool FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels protected inherited
keep base-mesh levels on root process?
Definition at line 433 of file domain_control.hpp.
_layer_levels
std::deque<std::deque<std::shared_ptr<LevelType> > > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_layer_levels protected inherited
Definition at line 427 of file domain_control.hpp.
_layers
std::deque<std::shared_ptr<LayerType> > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_layers protected inherited
Definition at line 425 of file domain_control.hpp.
_num_global_layers
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::_num_global_layers protected inherited
Definition at line 429 of file domain_control.hpp.
_parti_set
template<typename DomainLevel_ > Geometry::PartitionSet FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_parti_set protected
the extern partition sets
Definition at line 144 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create().
_permutation_strategy
template<typename DomainLevel_ > Geometry::PermutationStrategy FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_permutation_strategy protected
the permutation strategy for the mesh permutation
Definition at line 142 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_mesh_permutations(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::get_permutation_strategy(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_permutation_strategy().
_required_elems_per_rank
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_required_elems_per_rank protected
required number of elements per rank for a-posteriori partitioning
Definition at line 171 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
_support_multi_layered
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_support_multi_layered protected
support multi-layered hierarchy?
Definition at line 160 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create().
_virt_levels
std::deque<VirtLevelType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::_virt_levels protected inherited
Definition at line 428 of file domain_control.hpp.
_virt_size
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::_virt_size protected inherited
Definition at line 430 of file domain_control.hpp.
_was_created
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_was_created protected
specifies whether the domain control was already created
Definition at line 138 of file parti_domain_control.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_rectilinear(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_adapt_mode(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_desired_levels(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_permutation_strategy().
The documentation for this class was generated from the following file:
control/domain/parti_domain_control.hpp