FEAT: FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ > Class Template Reference
FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ > Class Template Reference
Hierarchical partitioned Voxel Domain Control.
#include <voxel_domain_control.hpp>
Public Types
typedef Geometry::MeshAtlas< MeshType > AtlasType
typedef Control::Domain::PartiDomainControlBase< DomainLevel_ > BaseClass
our base class
typedef MeshType::CoordType CoordType
coordinate type
typedef DomainLayer LayerType
typedef DomainLevel_ LevelType
typedef Geometry::RootMeshNode< MeshType > MeshNodeType
our root mesh node type
typedef LevelType::PartType MeshPartType
our mesh-part type
typedef LevelType::MeshType MeshType
typedef LevelType::ShapeType ShapeType
typedef VirtualLevel< LevelType > VirtLevelType
typedef Real WeightType
weight type for partitioner element weights; always Real
Public Member Functions
VoxelDomainControl (const Dist::Comm &comm_, bool support_multi_layered)
Constructor.
virtual ~VoxelDomainControl ()
virtual destructor
VirtLevelType & at (std::size_t i)
const VirtLevelType & at (std::size_t i) const
VirtLevelType & back ()
const VirtLevelType & back () const
LayerType & back_layer ()
const LayerType & back_layer () const
std::size_t bytes () const
const Dist::Comm & comm () const
void compile_virtual_levels ()
MeshNodeType & create_base_mesh_2d (Index num_x, Index num_y, CoordType x_min, CoordType x_max, CoordType y_min, CoordType y_max)
Creates a 2D structured rectangle base mesh and returns its base-mesh node.
MeshNodeType & create_base_mesh_3d (Index num_x, Index num_y, Index num_z, CoordType x_min, CoordType x_max, CoordType y_min, CoordType y_max, CoordType z_min, CoordType z_max)
Creates a 3D structured cuboid base mesh and returns its base-mesh node.
void create_hierarchy ()
Creates the domain level hierarchy.
void create_voxel_map (Geometry::VoxelMasker< CoordType, shape_dim > &masker, Real resolution=Real(0))
Creates a voxel map based on a VoxelMasker object.
void create_voxel_map_from_chart (const Geometry::Atlas::ChartBase< MeshType > &chart, bool invert, Real resolution)
Creates a voxel map based on a chart.
template<typename Lambda_ >
void create_voxel_map_from_lambda (Lambda_ &&lambda, Real resolution)
Creates a voxel map based on a lambda expression.
void create_voxel_map_from_off (const String &filename, bool invert, Real resolution)
Creates a voxel map based on a surface triangulation stored in an OFF file.
void create_voxel_map_from_off (std::istream &is, bool invert, Real resolution)
Creates a voxel map based on a surface triangulation stored in an OFF file.
String dump_ancestry () const
Debugging function: Returns a string containing encoded ancestry information.
String dump_layer_levels () const
String dump_layers () const
String dump_slag_layer_levels () const
Debugging function: Returns a string containing encoded slag layer level information.
String dump_virt_levels () const
virtual String format_chosen_levels () const
Returns the chosen levels formatted as a parsable string.
virtual String format_desired_levels () const
Returns the desired levels formatted as a parsable string.
VirtLevelType & front ()
const VirtLevelType & front () const
LayerType & front_layer ()
const LayerType & front_layer () const
std::vector< WeightType > gather_element_voxel_weights (Index level) const
Gathers the element voxel map weights on a given domain level.
std::vector< int > gather_vertex_voxel_map (Index level) const
Gathers the vertex voxel map on a given domain level.
Geometry::AdaptMode get_adapt_mode () const
Gets the adapt-mode for refinement.
const std::deque< Ancestor > & get_ancestry () const
Returns a const reference to the ancestry.
AtlasType & get_atlas ()
const AtlasType & get_atlas () const
const std::deque< std::pair< int, int > > get_chosen_levels () const
Returns the deque of chosen refinement levels.
virtual String get_chosen_parti_info () const
Returns an informative string about the chosen partitioning.
int get_desired_level_max () const
Returns the desired maximum refinement level.
int get_desired_level_min () const
Returns the desired minimum refinement level.
const std::deque< std::pair< int, int > > get_desired_levels () const
Returns the deque of desired refinement levels.
const Geometry::VoxelMap & get_voxel_map () const
Returns a const reference to the internal voxel map.
const StopWatch & get_watch_base_mesh () const
Returns a const reference to the StopWatch that measures the base-mesh creation phase.
const StopWatch & get_watch_hierarchy () const
Returns a const reference to the StopWatch that measures the base-mesh creation phase.
const StopWatch & get_watch_voxel_map () const
Returns a const reference to the StopWatch that measures the voxel-map creation phase.
bool has_ghost () const
void keep_base_levels ()
Instructs the domain controller to keep the base-mesh levels after partitioning.
void keep_voxel_map ()
Instructs the domain controller to keep the voxel map after hierarchy creation.
int max_level_index () const
int med_level_index () const
int min_level_index () const
std::size_t num_global_layers () const
std::size_t num_local_layers () const
virtual bool parse_args (SimpleArgParser &args)
Parses the partitioner options from an argument parser.
virtual bool parse_property_map (PropertyMap &pmap)
Parses the partitioner options from a PropertyMap.
virtual void print () const
void push_layer (std::shared_ptr< LayerType > layer)
void push_level_back (int layer_index, std::shared_ptr< LevelType > level)
void push_level_front (int layer_index, std::shared_ptr< LevelType > level)
Geometry::VoxelMap::ReadResult read_voxel_map (const String &filename)
Reads the voxel map from a voxel map file.
std::vector< char > serialize_partitioning () const
Serializes the partitioning information into a binary buffer.
void set_adapt_mode (Geometry::AdaptMode adapt_mode)
Sets the adapt-mode for refinement.
virtual void set_desired_levels (const std::deque< String > &slvls)
Sets the desired levels for the partitioned hierarchy.
void set_desired_levels (const String &slvls)
Sets the desired levels for the partitioned hierarchy.
virtual void set_desired_levels (int lvl_max, int lvl_med, int lvl_min)
Sets the desired refinement levels for a double-layered hierarchy.
virtual void set_desired_levels (int lvl_max, int lvl_min=-1)
Sets the desired refinement levels for a single-layered hierarchy.
void set_voxel_map_out_of_bounds_balue (bool value)
Sets the out-of-bounds value for the voxel map.
std::size_t size_physical () const
std::size_t size_virtual () const
Geometry::VoxelMap::WriteResult write_voxel_map (const String &filename)
Writes the voxel map to a voxel map file.
Static Public Member Functions
static String name ()
Static Public Attributes
static constexpr int shape_dim = MeshType::shape_dim
shape dimension
Protected Member Functions
virtual bool _apply_parti (Ancestor &ancestor, MeshNodeType &base_mesh_node)
Applies an a-posteriori partitioner.
bool _apply_parti_genetic (Ancestor &ancestor, MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the genetic partitioner onto the base-mesh.
bool _apply_parti_metis (Ancestor &ancestor, const MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the METIS partitioner onto the base-mesh.
bool _apply_parti_naive (Ancestor &ancestor, const MeshNodeType &mesh_node, const std::vector< WeightType > &weights)
Applies the naive partitioner onto the base-mesh.
bool _apply_parti_zoltan (Ancestor &ancestor, const MeshNodeType &base_mesh_node, const std::vector< WeightType > &weights)
Applies the Zoltan partitioner onto the base-mesh.
virtual bool _check_parti (Ancestor &ancestor, const MeshNodeType &mesh_node, bool is_base_layer)
Checks for an appropriate partitioning strategy.
Adjacency::Coloring _compute_base_mesh_coloring (const MeshNodeType &slag_node) const
Computes the coloring for the unpartitioned base mesh.
Adjacency::Coloring _compute_base_mesh_layering (const MeshNodeType &slag_node) const
Computes the element layering for the unpartitioned base mesh.
Adjacency::Coloring _compute_refined_mesh_coloring (const MeshNodeType &slag_node) const
Computes the coloring for a refined mesh.
Adjacency::Coloring _compute_refined_mesh_layering (const MeshNodeType &slag_node, const Adjacency::Coloring &coarse_layering) const
Computes the layering for a refined mesh.
virtual std::vector< WeightType > _compute_weights (Ancestor &ancestor, const MeshNodeType &base_mesh_node)
Computes the element partitioning weights.
virtual void _create_ancestry_scattered ()
Creates the layers for a multi-layered domain control in a scattered fashion.
virtual void _create_ancestry_single ()
Creates the ancestry for a single layer (or a single process)
virtual void _create_multi_layered (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a multi-layered mesh hierarchy.
virtual void _create_multi_layers_scattered ()
Creates the layers for a multi-layered domain control in a scattered fashion.
virtual void _create_single_layered (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a single-layered mesh hierarchy.
virtual void _create_single_process (std::unique_ptr< MeshNodeType > base_mesh_node)
Creates a single-layered mesh hierarchy for a single process.
virtual std::unique_ptr< MeshNodeType > _deslag_mesh_node (MeshNodeType &mesh_node)
Deslags an unpartitioned mesh node including its mesh-parts.
virtual std::unique_ptr< MeshNodeType > _deslag_mesh_node (MeshNodeType &mesh_node, const Ancestor &ancestor, bool is_child)
Deslags a (potentially partitioned) mesh node including its mesh-parts and halos.
virtual void _deslag_patch_halos (MeshNodeType &patch_mesh_node, const MeshNodeType &base_mesh_node, const Ancestor &ancestor, bool is_child)
Deslags the halos of a patch mesh node.
Adjacency::Coloring _extract_patch_coloring (const MeshNodeType &slag_node, const Adjacency::Coloring &parent_coloring, int child_rank) const
Extracts a patch coloring from the parent mesh coloring.
Adjacency::Coloring _extract_patch_layering (const MeshNodeType &slag_node, const Adjacency::Coloring &parent_layering, int child_rank) const
Extracts a patch layering from the parent mesh layering.
std::vector< WeightType > _gather_element_weights (const MeshType &mesh) const
Gathers the element slag weights for a given mesh.
std::vector< Index > _gather_masked_elements (const MeshType &mesh) const
Gather a vector of element indices that intersect the masked domain.
virtual bool _parse_parti_type (const String &type)
Parses a partitioner type.
void _precreate_voxel_map (Real resolution)
Pre-creates the voxel map by setting the bounding box and resolution.
virtual void _reset_parti_types ()
Resets/disables all partitioner types.
virtual void _split_basemesh_halos (const Ancestor &ancestor, const MeshNodeType &base_mesh_node, MeshNodeType &patch_mesh_node, std::vector< int > &neighbor_ranks)
Splits the base-mesh halos and computes the inter-patch-mesh halos.
Protected Attributes
Geometry::AdaptMode _adapt_mode
the adapt mode for refinement
bool _allow_parti_genetic
allow genetic partitioner?
bool _allow_parti_metis
allow metis partitioner?
bool _allow_parti_naive
allow naive partitioner?
bool _allow_parti_zoltan
allow Zoltan partitioner?
std::deque< Ancestor > _ancestry
the partition ancestry deque
AtlasType _atlas
std::deque< std::shared_ptr< LevelType > > _base_levels
std::unique_ptr< MeshNodeType > _base_mesh_node
the input base-mesh node on level 0
std::array< Index, shape_dim > _base_slices
number of element slices on base mesh level 0
Tiny::Vector< CoordType, shape_dim > _bbox_max
Tiny::Vector< CoordType, shape_dim > _bbox_min
the bounding box of the structured domain
std::deque< std::pair< int, int > > _chosen_levels
chosen level deque
const Dist::Comm & _comm
int _create_stage
creation stage to keep track what has already been initialized
std::deque< std::pair< int, int > > _desired_levels
desired level deque
double _genetic_time_init
time for genetic partitioner initialization
double _genetic_time_mutate
time for genetic partitioner mutation
bool _keep_base_levels
keep base-mesh levels on root process?
bool _keep_voxel_map
specifies whether to keep the voxel map after hierarchy creation
std::deque< std::deque< std::shared_ptr< LevelType > > > _layer_levels
std::deque< std::shared_ptr< LayerType > > _layers
std::size_t _num_global_layers
int _required_elems_per_rank
required number of elements per rank for a-posteriori partitioning
bool _support_multi_layered
support multi-layered hierarchy?
std::deque< VirtLevelType > _virt_levels
std::size_t _virt_size
std::unique_ptr< Geometry::VoxelMap > _voxel_map
the voxel map
bool _was_created
specifies whether the domain control was already created
StopWatch _watch_create_base_mesh
a bunch of stop-watches
StopWatch _watch_create_hierarchy
StopWatch _watch_create_voxel_map
Detailed Description
template<typename DomainLevel_>
class FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >
Hierarchical partitioned Voxel Domain Control.
Author
Peter Zajac
Definition at line 95 of file voxel_domain_control.hpp.
Member Typedef Documentation
AtlasType
typedef Geometry::MeshAtlas<MeshType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::AtlasType inherited
Definition at line 420 of file domain_control.hpp.
BaseClass
template<typename DomainLevel_ > typedef Control::Domain::PartiDomainControlBase< DomainLevel_ > FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::BaseClass
our base class
Definition at line 100 of file voxel_domain_control.hpp.
CoordType
template<typename DomainLevel_ > typedef MeshType::CoordType FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::CoordType
coordinate type
Definition at line 122 of file voxel_domain_control.hpp.
LayerType
typedef DomainLayer FEAT::Control::Domain::DomainControl< DomainLevel_ >::LayerType inherited
Definition at line 414 of file domain_control.hpp.
LevelType
typedef DomainLevel_ FEAT::Control::Domain::DomainControl< DomainLevel_ >::LevelType inherited
Definition at line 413 of file domain_control.hpp.
MeshNodeType
template<typename DomainLevel_ > typedef Geometry::RootMeshNode<MeshType> FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::MeshNodeType
our root mesh node type
Definition at line 56 of file parti_domain_control_base.hpp.
MeshPartType
template<typename DomainLevel_ > typedef LevelType::PartType FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::MeshPartType
our mesh-part type
Definition at line 58 of file parti_domain_control_base.hpp.
MeshType
typedef LevelType::MeshType FEAT::Control::Domain::DomainControl< DomainLevel_ >::MeshType inherited
Definition at line 418 of file domain_control.hpp.
ShapeType
typedef LevelType::ShapeType FEAT::Control::Domain::DomainControl< DomainLevel_ >::ShapeType inherited
Definition at line 417 of file domain_control.hpp.
VirtLevelType
typedef VirtualLevel<LevelType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::VirtLevelType inherited
Definition at line 415 of file domain_control.hpp.
WeightType
template<typename DomainLevel_ > typedef Real FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::WeightType
weight type for partitioner element weights; always Real
Definition at line 61 of file parti_domain_control_base.hpp.
Constructor & Destructor Documentation
VoxelDomainControl()
template<typename DomainLevel_ > FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::VoxelDomainControl (const Dist::Comm & comm_, bool support_multi_layered) inline explicit
Constructor.
Parameters
[in] comm_ A resident reference to the main communicator to be used.
[in] support_multi_layered Specifies whether the controller is allowed to create multi-layered hierarchies.
Definition at line 155 of file voxel_domain_control.hpp.
~VoxelDomainControl()
template<typename DomainLevel_ > virtual FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::~VoxelDomainControl () inline virtual
virtual destructor
Definition at line 163 of file voxel_domain_control.hpp.
Member Function Documentation
_apply_parti()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti (Ancestor & ancestor, MeshNodeType & base_mesh_node) inline protected virtual inherited
Applies an a-posteriori partitioner.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
Returns
true, if the base-mesh was partitioned, otherwise false.
Definition at line 1295 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_genetic(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_metis(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_naive(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_zoltan(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_compute_weights(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_apriori.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered().
_apply_parti_genetic()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_genetic (Ancestor & ancestor, MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected inherited
Applies the genetic partitioner onto the base-mesh.
Parameters
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true.
Definition at line 1444 of file parti_domain_control_base.hpp.
References FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_metis()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_metis (Ancestor & ancestor, const MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected inherited
Applies the METIS partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if METIS was applied successfully, otherwise false.
Definition at line 1391 of file parti_domain_control_base.hpp.
References FEAT::Geometry::PartiParMETIS::build_elems_at_rank(), FEAT::Geometry::PartiParMETIS::execute(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_naive()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_naive (Ancestor & ancestor, const MeshNodeType & mesh_node, const std::vector< WeightType > & weights) inline protected inherited
Applies the naive partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if a naive partition was created successfully, otherwise false.
Definition at line 1486 of file parti_domain_control_base.hpp.
References FEAT::Adjacency::Graph::get_domain_ptr(), FEAT::Adjacency::Graph::get_image_idx(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info, and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_apply_parti_zoltan()
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti_zoltan (Ancestor & ancestor, const MeshNodeType & base_mesh_node, const std::vector< WeightType > & weights) inline protected inherited
Applies the Zoltan partitioner onto the base-mesh.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] base_mesh_node The base-mesh node that is to be partitioned.
[in] weights A vector containing the distribution weights for each element. May be empty if all elements are to be weighted equally.
Returns
true, if Zoltan was applied successfully, otherwise false.
Definition at line 1339 of file parti_domain_control_base.hpp.
References FEAT::Geometry::PartiZoltan::build_elems_at_rank(), FEAT::Geometry::PartiZoltan::execute(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_check_parti()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_check_parti (Ancestor & ancestor, const MeshNodeType & mesh_node, bool is_base_layer) inline protected virtual inherited
Checks for an appropriate partitioning strategy.
This function examines the given base mesh and checks whether one of the a-priori partitioning strategies (extern or 2-level) yields a valid partitioning for the given number of partitions. If so, the corresponding partitioning level and graph are stored in ancestor.parti_level and ancestor.parti_graph. If not, this function determines how often the base-mesh has to be refined until its has enough cells so that one of the a-posteriori partitioners can be applied.
Parameters
[in,out] ancestor The ancestor object for this layer.
[in] mesh_node The base-mesh node that is to be partitioned.
[in] is_base_layer Set to true, if #base_mesh_node is the mesh node that corresponds to the input file's mesh and therefore extern partitioning is a valid option, or set to false in any other case.
Returns
true, if an a-priori partitioning was found, otherwise false.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 1254 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Math::max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_level.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_check_parti(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_compute_base_mesh_coloring()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_coloring (const MeshNodeType & slag_node) const inline protected
Computes the coloring for the unpartitioned base mesh.
Parameters
[in] slag_node The unpartitioned structured base-mesh node
Returns
The coloring for the unpartitioned deslagged base-mesh node
Definition at line 1125 of file voxel_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), and XASSERT.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process().
_compute_base_mesh_layering()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_layering (const MeshNodeType & slag_node) const inline protected
Computes the element layering for the unpartitioned base mesh.
Parameters
[in] slag_node The unpartitioned structured base-mesh node
Returns
The layering for the unpartitioned deslagged base-mesh node
Definition at line 1248 of file voxel_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim, and XASSERT.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process().
_compute_refined_mesh_coloring()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring (const MeshNodeType & slag_node) const inline protected
Computes the coloring for a refined mesh.
Parameters
[in] slag_node The refined mesh node
Returns
The coloring for the refined and deslagged mesh node
Definition at line 1180 of file voxel_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), and XASSERT.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process().
_compute_refined_mesh_layering()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_layering (const MeshNodeType & slag_node, const Adjacency::Coloring & coarse_layering) const inline protected
Computes the layering for a refined mesh.
Parameters
[in] slag_node The refined mesh node
Returns
The layering for the refined and deslagged mesh node
Definition at line 1298 of file voxel_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Adjacency::Coloring::get_num_colors(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim, and XASSERT.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process().
_compute_weights()
template<typename DomainLevel_ > virtual std::vector< WeightType > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_compute_weights (Ancestor & ancestor, const MeshNodeType & base_mesh_node) inline protected virtual inherited
Computes the element partitioning weights.
Note
This base-class implementation always returns an empty vector, but a derived class may override this method and an actual non-trivial weight vector.
Returns
A vector containing the weights for the base mesh elements or an empty vector, if all elements are to be weighted equally.
Definition at line 751 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti().
_create_ancestry_scattered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_scattered () inline protected virtual inherited
Creates the layers for a multi-layered domain control in a scattered fashion.
Definition at line 865 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Dist::Comm::comm_create_range_incl(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_procs, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_create_ancestry_single()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_single () inline protected virtual inherited
Creates the ancestry for a single layer (or a single process)
Definition at line 759 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_procs, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process().
_create_multi_layered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected virtual
Creates a multi-layered mesh hierarchy.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Definition at line 1599 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_apply_parti(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_scattered(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_multi_layers_scattered(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_layering(), FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_split_basemesh_halos(), FEAT::Dist::Comm::allreduce(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Math::max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::num_parts, FEAT::Dist::op_max, FEAT::Dist::op_min, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_level, FEAT::Dist::Comm::size(), and XASSERTM.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy().
_create_multi_layers_scattered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_multi_layers_scattered () inline protected virtual inherited
Creates the layers for a multi-layered domain control in a scattered fashion.
Definition at line 804 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::comm, FEAT::Dist::Comm::comm_create_range_incl(), FEAT::Dist::Comm::comm_dup(), FEAT::Dist::Comm::is_null(), FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
_create_single_layered()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected virtual
Creates a single-layered mesh hierarchy.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Definition at line 1480 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_single(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_layering(), FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels, FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, FEAT::Adjacency::Coloring::empty(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_found, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_graph, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_level, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERTM.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy().
_create_single_process()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process (std::unique_ptr< MeshNodeType > base_mesh_node) inline protected virtual
Creates a single-layered mesh hierarchy for a single process.
Parameters
[in] base_mesh_node The base-mesh node from which the hierarchy is to be derived from.
Note
This function does not keep the base-mesh levels explicitly even if _keep_base_levels is set to true, because it is not required to use the base splitter on a single process.
Definition at line 1402 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_coloring(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_single(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node(), FEAT::Dist::Comm::comm_dup(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::desired_level_max, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::parti_info.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy().
_deslag_mesh_node() [1/2]
template<typename DomainLevel_ > virtual std::unique_ptr< MeshNodeType > FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node (MeshNodeType & mesh_node) inline protected virtual
Deslags an unpartitioned mesh node including its mesh-parts.
Attention
This function can only be used for unpartitioned mesh nodes. If the mesh node represents a patch, then the other overload that requires and Ancestor object has to be used, because the halos also need to be deslagged in this case!
This function adds a patch with rank -1 to the mesh_node, which represents the deslagged patch.
Parameters
[in,out] mesh_node A transient reference to the mesh node that is to be deslagged.
Returns
A new mesh node that contains the deslagged mesh as well as the deslagged mesh parts.
Definition at line 879 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_gather_masked_elements(), FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), and XASSERTM.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process().
_deslag_mesh_node() [2/2]
template<typename DomainLevel_ > virtual std::unique_ptr< MeshNodeType > FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node (MeshNodeType & mesh_node, const Ancestor & ancestor, bool is_child) inline protected virtual
Deslags a (potentially partitioned) mesh node including its mesh-parts and halos.
This function adds a patch with rank -1 to the mesh_node, which represents the deslagged patch.
Parameters
[in,out] mesh_node A transient reference to the mesh node that is to be deslagged.
[in] ancestor Depending on whether is_child is false or true, a transient reference to the ancestor object of either the layer that the mesh node belongs to or the child layer of the layer that the mesh node belongs to, resp.
[in] is_child Specifies whether the ancestor object is actually the child ancestor object; this is only true for the mesh nodes belonging to parent layers in the case of hierarchical partitioning.
Returns
A new mesh node that contains the deslagged mesh as well as the deslagged mesh parts and halos.
Definition at line 903 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_patch_halos(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_gather_masked_elements(), FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), and FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh().
_deslag_patch_halos()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_patch_halos (MeshNodeType & patch_mesh_node, const MeshNodeType & base_mesh_node, const Ancestor & ancestor, bool is_child) inline protected virtual
Deslags the halos of a patch mesh node.
Parameters
[in] patch_mesh_node A transient reference to the deslagged patch mesh node whose halos are to be deslagged.
[in] base_mesh_node A transient reference to the mesh node that the deslagged mesh node was created from.
[in] ancestor Depending on whether is_child is false or true, a transient reference to the ancestor object of either the layer that the mesh node belongs to or the child layer of the layer that the mesh node belongs to, resp.
[in] is_child Specifies whether the ancestor object is actually the child ancestor object; this is only true for the mesh nodes belonging to parent layers in the case of hierarchical partitioning.
Definition at line 927 of file voxel_domain_control.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_halo(), FEAT::Dist::Comm::bcast(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::isend(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Dist::Comm::rank(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim, FEAT::stringify(), FEAT::Dist::RequestVector::wait_all(), and XABORTM.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node().
_extract_patch_coloring()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_coloring (const MeshNodeType & slag_node, const Adjacency::Coloring & parent_coloring, int child_rank) const inline protected
Extracts a patch coloring from the parent mesh coloring.
Parameters
[in] parent_node The parent node that the patch was extracted from
[in] parent_coloring The coloring of the parent node
[in] child_rank The rank of the extracted patch
Returns
The coloring for the refined deslagged mesh node
Definition at line 1217 of file voxel_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), and XASSERT.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered().
_extract_patch_layering()
template<typename DomainLevel_ > Adjacency::Coloring FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_extract_patch_layering (const MeshNodeType & slag_node, const Adjacency::Coloring & parent_layering, int child_rank) const inline protected
Extracts a patch layering from the parent mesh layering.
Parameters
[in] parent_node The parent node that the patch was extracted from
[in] parent_layering The layering of the parent node
[in] child_rank The rank of the extracted patch
Returns
The layering for the refined deslagged mesh node
Definition at line 1355 of file voxel_domain_control.hpp.
References FEAT::Adjacency::Coloring::get_coloring(), FEAT::Adjacency::Coloring::get_num_colors(), FEAT::Geometry::TargetSet::get_num_entities(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), and XASSERT.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered().
_gather_element_weights()
template<typename DomainLevel_ > std::vector< WeightType > FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_gather_element_weights (const MeshType & mesh) const inline protected
Gathers the element slag weights for a given mesh.
The "slag weight" of an element is defined as the number of voxel map points with a value of 1, which lie inside the element cuboid, divided by the total number of voxel map points, which lie inside the element cuboid.
Parameters
[in] mesh The mesh for which the element weights are to be gathered.
Returns
A vector of floats in range [0,1] representing the element slag weights on the desired level. The length of the vector corresponds to the number of elements on the patch on the desired domain level.
Definition at line 823 of file voxel_domain_control.hpp.
References FEAT::Math::minimax(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::gather_element_voxel_weights().
_gather_masked_elements()
template<typename DomainLevel_ > std::vector< Index > FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_gather_masked_elements (const MeshType & mesh) const inline protected
Gather a vector of element indices that intersect the masked domain.
Attention
It is silently assumed that all elements in the mesh are axis-parallel rectangles/cuboids; this function may yield incorrect results if the mesh violates this assumption!
Parameters
[in] mesh A transient reference to the mesh whose elements are to be tested against the voxel map
Returns
A vector containing the indices of all mesh elements that intersect the domain that is represented by the voxel map.
Definition at line 767 of file voxel_domain_control.hpp.
References FEAT::Math::minimax(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_mesh_node().
_parse_parti_type()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type (const String & type) inline protected virtual inherited
Parses a partitioner type.
Parameters
[in] type The name of the partitioner type that is to be enabled.
Returns
true, if type represents a supported partitioner type, otherwise false.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 727 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan, and FEAT::String::compare_no_case().
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_precreate_voxel_map()
template<typename DomainLevel_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_precreate_voxel_map (Real resolution) inline protected
Pre-creates the voxel map by setting the bounding box and resolution.
Definition at line 728 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_max(), FEAT::Math::min(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_chart(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_lambda(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_off().
_reset_parti_types()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types () inline protected virtual inherited
Resets/disables all partitioner types.
This function is called by the parse_args and parse_property_map function when the user has supplied a list of allowed partitioner types.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 713 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive, and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_split_basemesh_halos()
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_split_basemesh_halos (const Ancestor & ancestor, const MeshNodeType & base_mesh_node, MeshNodeType & patch_mesh_node, std::vector< int > & neighbor_ranks) inline protected virtual inherited
Splits the base-mesh halos and computes the inter-patch-mesh halos.
This is where the magic happens in the case of the multi-layered hierarchy.
Parameters
[in] ancestor The ancestor object for the current layer.
[in] base_mesh_node The base-mesh node that has been partitioned and whose halos are to be split.
[in,out] patch_mesh_node The patch-mesh node that represents the partition whose halos are to be computed.
[in,out] neighbor_ranks The vector that receives the ranks of the new neighbors that derive from halo splitting.
Definition at line 941 of file parti_domain_control_base.hpp.
References FEAT::Geometry::RootMeshNode< RootMesh_ >::add_halo(), FEAT::Dist::Comm::bcast(), FEAT::Dist::Comm::gather(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_halo_map(), FEAT::Geometry::MeshNode< RootMesh_, ThisMesh_ >::get_mesh(), FEAT::Geometry::RootMeshNode< RootMesh_ >::get_patch(), FEAT::Dist::Comm::irecv(), FEAT::Dist::Comm::is_null(), FEAT::Dist::Comm::isend(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::Ancestor::layer_p, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), FEAT::Dist::RequestVector::wait_all(), and XASSERT.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered().
at() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::at (std::size_t i) inline inherited
Definition at line 579 of file domain_control.hpp.
at() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::at (std::size_t i) const inline inherited
Definition at line 584 of file domain_control.hpp.
back() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back () inline inherited
Definition at line 599 of file domain_control.hpp.
back() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back () const inline inherited
Definition at line 604 of file domain_control.hpp.
back_layer() [1/2]
LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back_layer () inline inherited
Definition at line 519 of file domain_control.hpp.
back_layer() [2/2]
const LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::back_layer () const inline inherited
Definition at line 524 of file domain_control.hpp.
bytes()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::bytes () const inline inherited
Definition at line 477 of file domain_control.hpp.
comm()
const Dist::Comm & FEAT::Control::Domain::DomainControl< DomainLevel_ >::comm () const inline inherited
Definition at line 472 of file domain_control.hpp.
compile_virtual_levels()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::compile_virtual_levels () inline inherited
Definition at line 637 of file domain_control.hpp.
create_base_mesh_2d()
template<typename DomainLevel_ > MeshNodeType & FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_2d (Index num_x, Index num_y, CoordType x_min, CoordType x_max, CoordType y_min, CoordType y_max) inline
Creates a 2D structured rectangle base mesh and returns its base-mesh node.
This functions returns a reference to the base-mesh node that is created and managed internally by this class. This base-mesh node reference can be used to create mesh-parts at the base-mesh level, which will be refined and deslagged during the creation of the domain hierarchy.
Attention
The returned base-mesh node reference is only valid until the create() method is called and is orphaned after the create() method returns, because the base-mesh node is then processed internally to create the domain level hierarchy.
Parameters
[in] num_x,num_y The number of element slices in X- and Y-direction.
[in] x_min,x_max The X-range of the cuboid domain.
[in] y_min,y_max The X-range of the cuboid domain.
Returns
A reference to the internal base-mesh node containing the base-mesh.
Definition at line 206 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_base_mesh_node, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_base_slices, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_bbox_min, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_stage, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_watch_create_base_mesh, FEAT::Geometry::RootMeshNode< MeshType >::make_unique(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim, FEAT::StopWatch::start(), FEAT::StopWatch::stop(), XASSERT, and XASSERTM.
create_base_mesh_3d()
template<typename DomainLevel_ > MeshNodeType & FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_3d (Index num_x, Index num_y, Index num_z, CoordType x_min, CoordType x_max, CoordType y_min, CoordType y_max, CoordType z_min, CoordType z_max) inline
Creates a 3D structured cuboid base mesh and returns its base-mesh node.
This functions returns a reference to the base-mesh node that is created and managed internally by this class. This base-mesh node reference can be used to create mesh-parts at the base-mesh level, which will be refined and deslagged during the creation of the domain hierarchy.
Attention
The returned base-mesh node reference is only valid until the create() method is called and is orphaned after the create() method returns, because the base-mesh node is then processed internally to create the domain level hierarchy.
Parameters
[in] num_x,num_y,num_z The number of element slices in X-, Y- and Z-direction.
[in] x_min,x_max The X-range of the cuboid domain.
[in] y_min,y_max The X-range of the cuboid domain.
[in] z_min,z_max The X-range of the cuboid domain.
Returns
A reference to the internal base-mesh node containing the base-mesh.
Definition at line 272 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_base_mesh_node, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_base_slices, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_bbox_min, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_stage, FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_watch_create_base_mesh, FEAT::Geometry::RootMeshNode< MeshType >::make_unique(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim, FEAT::StopWatch::start(), FEAT::StopWatch::stop(), XASSERT, and XASSERTM.
create_hierarchy()
template<typename DomainLevel_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy () inline
Creates the domain level hierarchy.
This function can only be called after the base-mesh has been created by calling create_base_mesh_2d or create_base_mesh_3d and after the voxel map has been created by calling create_voxel_map().
Definition at line 582 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_support_multi_layered, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::StopWatch::elapsed(), FEAT::Dist::Comm::size(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), FEAT::Statistics::toe_partition, and XASSERTM.
create_voxel_map()
template<typename DomainLevel_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map (Geometry::VoxelMasker< CoordType, shape_dim > & masker, Real resolution = Real(0)) inline
Creates a voxel map based on a VoxelMasker object.
This function can only be called after the base-mesh has been created by calling create_base_mesh_2d or create_base_mesh_3d.
Attention
This function is a "collective" function in distributed parallel (i.e. MPI) simulations and each process must be given the same masker, because this function distributes the actual work over all processes before gathering the computed voxel map on all processes afterwards!
Parameters
[in] masker A transient reference to the voxel map masker.
[in] resolution Specifies the desired resolution of the voxel map. If set to 0, the resolution will be computed automatically.
Compiler Hack:
avoid std::make_unique for clang
Definition at line 353 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_precreate_voxel_map(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and XASSERTM.
create_voxel_map_from_chart()
template<typename DomainLevel_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_chart (const Geometry::Atlas::ChartBase< MeshType > & chart, bool invert, Real resolution) inline
Creates a voxel map based on a chart.
This function can only be called after the base-mesh has been created by calling create_base_mesh_2d or create_base_mesh_3d.
Attention
This function is a "collective" function in distributed parallel (i.e. MPI) simulations and each process must be given the same chart, because this function distributes the actual work over all processes before gathering the computed voxel map on all processes afterwards!
Parameters
[in] chart A transient reference to the chart that is to be used for the inside outside test.
[in] invert Specifies, whether the definition of inside/outside is to be inverted.
[in] resolution Specifies the desired resolution of the voxel map. If set to 0, the resolution will be computed automatically.
Definition at line 436 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_precreate_voxel_map(), FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and XASSERTM.
create_voxel_map_from_lambda()
template<typename DomainLevel_ > template<typename Lambda_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_lambda (Lambda_ && lambda, Real resolution) inline
Creates a voxel map based on a lambda expression.
This function can only be called after the base-mesh has been created by calling create_base_mesh_2d or create_base_mesh_3d.
Attention
This function is a "collective" function in distributed parallel (i.e. MPI) simulations and each process must be given the same lambda expression, because this function distributes the actual work over all processes before gathering the computed voxel map on all processes afterwards!
Parameters
[in] lambda A lambda expression that takes a const reference (or a copy) of a Tiny::Vector<CoordType_, shape_dim> that represents the point to be tested and returns true, if the point is in the interior of the domain or false if it is outside the domain.
[in] resolution Specifies the desired resolution of the voxel map. If set to 0, the resolution will be computed automatically.
Compiler Hack:
avoid std::make_unique for clang
Definition at line 394 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_precreate_voxel_map(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim, FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and XASSERTM.
create_voxel_map_from_off() [1/2]
template<typename DomainLevel_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_off (const String & filename, bool invert, Real resolution) inline
Creates a voxel map based on a surface triangulation stored in an OFF file.
This function can only be called after the base-mesh has been created by calling create_base_mesh_3d.
Note
This function can only be used in 3D and if FEAT was compiled and linked against the CGAL library.
Attention
This function is a "collective" function in distributed parallel (i.e. MPI) simulations, which will read in the file on the root process and distribute the file's contents to all processes.
Parameters
[in] filename The filename of the OFF file that is to be read in.
[in] invert Specifies, whether the inside/outside is to be inverted.
[in] resolution Specifies the desired resolution of the voxel map. If set to 0, the resolution will be computed automatically.
Definition at line 476 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_off(), and FEAT::DistFileIO::read_common().
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_off().
create_voxel_map_from_off() [2/2]
template<typename DomainLevel_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_off (std::istream & is, bool invert, Real resolution) inline
Creates a voxel map based on a surface triangulation stored in an OFF file.
This function can only be called after the base-mesh has been created by calling create_base_mesh_3d.
Note
This function can only be used in 3D and if FEAT was compiled and linked against the CGAL library.
Attention
This function is a "collective" function in distributed parallel (i.e. MPI) simulations and each process must be given the same OFF file content stream, because this function distributes the actual work over all processes before gathering the computed voxel map on all processes afterwards!
Parameters
[in] is The input stream that contains the OFF data; this should ideally be a std::stringstream that was read in by using the DistFileIO::read_common function to avoid a DDoS attack on the file system.
[in] invert Specifies, whether the inside/outside is to be inverted.
[in] resolution Specifies the desired resolution of the voxel map. If set to 0, the resolution will be computed automatically.
Definition at line 506 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_precreate_voxel_map(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim, FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and XASSERTM.
dump_ancestry()
template<typename DomainLevel_ > String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::dump_ancestry () const inline inherited
Debugging function: Returns a string containing encoded ancestry information.
Definition at line 571 of file parti_domain_control_base.hpp.
References FEAT::String::pad_front(), and FEAT::stringify().
dump_layer_levels()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_layer_levels () const inline inherited
Definition at line 735 of file domain_control.hpp.
dump_layers()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_layers () const inline inherited
Definition at line 713 of file domain_control.hpp.
dump_slag_layer_levels()
template<typename DomainLevel_ > String FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::dump_slag_layer_levels () const inline
Debugging function: Returns a string containing encoded slag layer level information.
Definition at line 704 of file voxel_domain_control.hpp.
References FEAT::String::pad_front(), and FEAT::stringify().
dump_virt_levels()
String FEAT::Control::Domain::DomainControl< DomainLevel_ >::dump_virt_levels () const inline inherited
Definition at line 748 of file domain_control.hpp.
format_chosen_levels()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_chosen_levels () const inline virtual inherited
Returns the chosen levels formatted as a parsable string.
The string returned by this function can be parsed by the set_desired_levels() function.
Returns
The chosen levels formatted as a parsable string.
Definition at line 501 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels, and FEAT::stringify().
format_desired_levels()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_desired_levels () const inline virtual inherited
Returns the desired levels formatted as a parsable string.
The string returned by this function can be parsed by the set_desired_levels() function.
Returns
The desired levels formatted as a parsable string.
Definition at line 480 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, and FEAT::stringify().
front() [1/2]
VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front () inline inherited
Definition at line 589 of file domain_control.hpp.
front() [2/2]
const VirtLevelType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front () const inline inherited
Definition at line 594 of file domain_control.hpp.
front_layer() [1/2]
LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front_layer () inline inherited
Definition at line 509 of file domain_control.hpp.
front_layer() [2/2]
const LayerType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::front_layer () const inline inherited
Definition at line 514 of file domain_control.hpp.
gather_element_voxel_weights()
template<typename DomainLevel_ > std::vector< WeightType > FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::gather_element_voxel_weights (Index level) const inline
Gathers the element voxel map weights on a given domain level.
The "slag weight" of an element is defined as the number of voxel map points with a value of 1, which lie inside the element cuboid, divided by the total number of voxel map points, which lie inside the element cuboid.
Parameters
[in] level The physical domain level for which the element weights are to be gathered.
Returns
A vector of floats in range [0,1] representing the element slag weights on the desired level. The length of the vector corresponds to the number of elements on the patch on the desired domain level.
Definition at line 695 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_gather_element_weights(), and XASSERT.
gather_vertex_voxel_map()
template<typename DomainLevel_ > std::vector< int > FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::gather_vertex_voxel_map (Index level) const inline
Gathers the vertex voxel map on a given domain level.
Parameters
[in] level The physical domain level for which the vertex mask is to be computed.
Returns
A vector of ints representing the vertex voxel map on the desired level. The length of the vector corresponds to the number of vertices on the patch on the desired domain level.
Definition at line 667 of file voxel_domain_control.hpp.
References XASSERT, and XASSERTM.
get_adapt_mode()
template<typename DomainLevel_ > Geometry::AdaptMode FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_adapt_mode () const inline inherited
Gets the adapt-mode for refinement.
Returns
The adapt-mode that is used.
Definition at line 304 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode.
get_ancestry()
template<typename DomainLevel_ > const std::deque< Ancestor > & FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_ancestry () const inline inherited
Returns a const reference to the ancestry.
Definition at line 606 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry.
get_atlas() [1/2]
AtlasType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::get_atlas () inline inherited
Definition at line 609 of file domain_control.hpp.
get_atlas() [2/2]
const AtlasType & FEAT::Control::Domain::DomainControl< DomainLevel_ >::get_atlas () const inline inherited
Definition at line 614 of file domain_control.hpp.
get_chosen_levels()
template<typename DomainLevel_ > const std::deque< std::pair< int, int > > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_levels () const inline inherited
Returns the deque of chosen refinement levels.
Returns
The deque of chosen refinement levels.
Definition at line 563 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels.
get_chosen_parti_info()
template<typename DomainLevel_ > virtual String FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_parti_info () const inline virtual inherited
Returns an informative string about the chosen partitioning.
Note
This function only returns something useful after the #create() function has been called.
In the case of a multi-layered recursive partitioning, the returned string is a multi-line string containing the partitioning info for each recursive layer in a separate line.
Definition at line 527 of file parti_domain_control_base.hpp.
References FEAT::stringify().
get_desired_level_max()
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_max () const inline inherited
Returns the desired maximum refinement level.
Returns
The desired maximum refinement level
Definition at line 458 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_precreate_voxel_map().
get_desired_level_min()
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_min () const inline inherited
Returns the desired minimum refinement level.
Returns
The desired minimum refinement level
Definition at line 468 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
get_desired_levels()
template<typename DomainLevel_ > const std::deque< std::pair< int, int > > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_levels () const inline inherited
Returns the deque of desired refinement levels.
Returns
The deque of desired refinement levels.
Definition at line 553 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels.
get_voxel_map()
template<typename DomainLevel_ > const Geometry::VoxelMap & FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::get_voxel_map () const inline
Returns a const reference to the internal voxel map.
Definition at line 653 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_voxel_map.
get_watch_base_mesh()
template<typename DomainLevel_ > const StopWatch & FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::get_watch_base_mesh () const inline
Returns a const reference to the StopWatch that measures the base-mesh creation phase.
Definition at line 633 of file voxel_domain_control.hpp.
References FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_watch_create_base_mesh.
get_watch_hierarchy()
template<typename DomainLevel_ > const StopWatch & FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::get_watch_hierarchy () const inline
Returns a const reference to the StopWatch that measures the base-mesh creation phase.
Definition at line 645 of file voxel_domain_control.hpp.
get_watch_voxel_map()
template<typename DomainLevel_ > const StopWatch & FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::get_watch_voxel_map () const inline
Returns a const reference to the StopWatch that measures the voxel-map creation phase.
Definition at line 639 of file voxel_domain_control.hpp.
has_ghost()
bool FEAT::Control::Domain::DomainControl< DomainLevel_ >::has_ghost () const inline inherited
Todo:
does this really work?
Definition at line 554 of file domain_control.hpp.
keep_base_levels()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::keep_base_levels () inline inherited
Instructs the domain controller to keep the base-mesh levels after partitioning.
Calling this function requests the domain controller to keep the base-mesh levels and refine them even after the partitioning process. This functionality is required to assemble a Global::Splitter object, which allows to serialize and deserialize vectors independent of the partitioning used to create the vector.
Attention
The functionality requested by this function is NOT scalable for large process counts, i.e. the root process WILL run out of memory in large-scale simulations. This functionality should only be used for moderate process counts.
Definition at line 632 of file domain_control.hpp.
keep_voxel_map()
template<typename DomainLevel_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::keep_voxel_map () inline
Instructs the domain controller to keep the voxel map after hierarchy creation.
Unless this function is called prior to the call of the create_hierarchy() function, the voxel map will be released after the hierarchy creation is completed to free up the memory used by the voxel map.
It is recommended not to call this function unless it is really necessary; if you want to use the voxel map for anything after it has been created, e.g. to write it to a file or to print some statistics to cout, then you can use it before calling the create_hierarchy function.
Definition at line 179 of file voxel_domain_control.hpp.
max_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::max_level_index () const inline inherited
Definition at line 534 of file domain_control.hpp.
med_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::med_level_index () const inline inherited
Definition at line 539 of file domain_control.hpp.
min_level_index()
int FEAT::Control::Domain::DomainControl< DomainLevel_ >::min_level_index () const inline inherited
Definition at line 529 of file domain_control.hpp.
name()
static String FEAT::Control::Domain::DomainControl< DomainLevel_ >::name () inline static inherited
Definition at line 448 of file domain_control.hpp.
num_global_layers()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::num_global_layers () const inline inherited
Definition at line 493 of file domain_control.hpp.
num_local_layers()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::num_local_layers () const inline inherited
Definition at line 488 of file domain_control.hpp.
parse_args()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args (SimpleArgParser & args) inline virtual inherited
Parses the partitioner options from an argument parser.
See also
Control::Domain::add_supported_pdc_args()
Parameters
[in] args The parser that is to be used.
Returns
true, if the parsing was successful, or false, if at least one option was invalid.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 188 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::SimpleArgParser::parse(), FEAT::Dist::Comm::print(), FEAT::SimpleArgParser::query(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_args().
parse_property_map()
template<typename DomainLevel_ > virtual bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map (PropertyMap & pmap) inline virtual inherited
Parses the partitioner options from a PropertyMap.
Parameters
[in] pmap A transient reference to the property map that contains the configuration
Returns
true, if the parsing was successful, or false, if at least one option was invalid.
Reimplemented in FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >.
Definition at line 232 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::print(), FEAT::PropertyMap::query(), and XASSERTM.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::parse_property_map().
print()
virtual void FEAT::Control::Domain::DomainControl< DomainLevel_ >::print () const inline virtual inherited
Definition at line 453 of file domain_control.hpp.
push_layer()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_layer (std::shared_ptr< LayerType > layer) inline inherited
Definition at line 498 of file domain_control.hpp.
push_level_back()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_level_back (int layer_index, std::shared_ptr< LevelType > level) inline inherited
Definition at line 549 of file domain_control.hpp.
push_level_front()
void FEAT::Control::Domain::DomainControl< DomainLevel_ >::push_level_front (int layer_index, std::shared_ptr< LevelType > level) inline inherited
Definition at line 544 of file domain_control.hpp.
read_voxel_map()
template<typename DomainLevel_ > Geometry::VoxelMap::ReadResult FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::read_voxel_map (const String & filename) inline
Reads the voxel map from a voxel map file.
Parameters
[in] filename The filename of the voxel map file.
Returns
A Geometry::VoxelMap::ReadResult object that contains information about the read file.
Definition at line 539 of file voxel_domain_control.hpp.
References FEAT::StopWatch::start(), FEAT::StopWatch::stop(), and XASSERTM.
serialize_partitioning()
template<typename DomainLevel_ > std::vector< char > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::serialize_partitioning () const inline inherited
Serializes the partitioning information into a binary buffer.
Definition at line 614 of file parti_domain_control_base.hpp.
References FEAT::Dist::Comm::allreduce(), FEAT::BinaryStream::container(), FEAT::Dist::Comm::gather(), FEAT::Dist::op_max, FEAT::Dist::Comm::rank(), FEAT::Dist::Comm::size(), and XASSERT.
set_adapt_mode()
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode (Geometry::AdaptMode adapt_mode) inline inherited
Sets the adapt-mode for refinement.
Parameters
[in] adapt_mode The adapt-mode that is to be used.
Definition at line 292 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, and XASSERTM.
set_desired_levels() [1/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (const std::deque< String > & slvls) inline virtual inherited
Sets the desired levels for the partitioned hierarchy.
Parameters
[in] slvls A transient reference to the deque of strings containing the desired levels.
Each entry of the deque is supposed to be in the format level:nprocs.
Definition at line 329 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), FEAT::stringify(), and XASSERTM.
set_desired_levels() [2/4]
template<typename DomainLevel_ > void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (const String & slvls) inline inherited
Sets the desired levels for the partitioned hierarchy.
Parameters
[in] slvls A string containing the list of desired levels.
Definition at line 315 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels(), and FEAT::String::split_by_whitespaces().
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels().
set_desired_levels() [3/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (int lvl_max, int lvl_med, int lvl_min) inline virtual inherited
Sets the desired refinement levels for a double-layered hierarchy.
Parameters
[in] lvl_max The desired maximum refinement level. Must be >= 0.
[in] lvl_med The desired median refinement level. Must be < lvl_max If < 0, then (lvl_max+lvl_med+1) is used as the median level.
[in] lvl_min The desired minimum refinement level. Must be <= lvl_med. If < 0, then (lvl_med+lvl_min+1) is used as the minimum level.
Definition at line 429 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), and XASSERTM.
set_desired_levels() [4/4]
template<typename DomainLevel_ > virtual void FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels (int lvl_max, int lvl_min = -1) inline virtual inherited
Sets the desired refinement levels for a single-layered hierarchy.
Parameters
[in] lvl_max The desired maximum refinement level. Must be >= 0.
[in] lvl_min The desired minimum refinement level. Must be <= lvl_max. If < 0, then (lvl_max+lvl_min+1) is used as the minimum level.
Definition at line 399 of file parti_domain_control_base.hpp.
References FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels, FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created, FEAT::Dist::Comm::size(), and XASSERTM.
set_voxel_map_out_of_bounds_balue()
template<typename DomainLevel_ > void FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::set_voxel_map_out_of_bounds_balue (bool value) inline
Sets the out-of-bounds value for the voxel map.
The out-of-bounds-value specifies whether the outside of the voxel map bounding box is being treated as 'inside' (true) or 'outside' (false).
Parameters
[in] value The out-of-bounds-value for the voxel map
Definition at line 329 of file voxel_domain_control.hpp.
References FEAT::value.
size_physical()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::size_physical () const inline inherited
Definition at line 569 of file domain_control.hpp.
size_virtual()
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::size_virtual () const inline inherited
Definition at line 564 of file domain_control.hpp.
write_voxel_map()
template<typename DomainLevel_ > Geometry::VoxelMap::WriteResult FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::write_voxel_map (const String & filename) inline
Writes the voxel map to a voxel map file.
Parameters
[in] filename The filename of the voxel map file.
Returns
A Geometry::VoxelMap::WriteResult object that contains information about the written file.
Definition at line 570 of file voxel_domain_control.hpp.
References XASSERTM.
Member Data Documentation
_adapt_mode
template<typename DomainLevel_ > Geometry::AdaptMode FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_adapt_mode protected inherited
the adapt mode for refinement
Definition at line 114 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_adapt_mode(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode().
_allow_parti_genetic
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_genetic protected inherited
allow genetic partitioner?
Definition at line 119 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_metis
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_metis protected inherited
allow metis partitioner?
Definition at line 117 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_naive
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_naive protected inherited
allow naive partitioner?
Definition at line 121 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_allow_parti_zoltan
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_allow_parti_zoltan protected inherited
allow Zoltan partitioner?
Definition at line 123 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_parse_parti_type(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_reset_parti_types().
_ancestry
template<typename DomainLevel_ > std::deque<Ancestor> FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_ancestry protected inherited
the partition ancestry deque
Definition at line 142 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_ancestry().
_atlas
AtlasType FEAT::Control::Domain::DomainControl< DomainLevel_ >::_atlas protected inherited
Definition at line 424 of file domain_control.hpp.
_base_levels
std::deque<std::shared_ptr<LevelType> > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_base_levels protected inherited
Definition at line 426 of file domain_control.hpp.
_base_mesh_node
template<typename DomainLevel_ > std::unique_ptr<MeshNodeType> FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_base_mesh_node protected
the input base-mesh node on level 0
Definition at line 137 of file voxel_domain_control.hpp.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_2d(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_3d().
_base_slices
template<typename DomainLevel_ > std::array<Index, shape_dim> FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_base_slices protected
number of element slices on base mesh level 0
Definition at line 131 of file voxel_domain_control.hpp.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_2d(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_3d().
_bbox_max
template<typename DomainLevel_ > Tiny::Vector<CoordType, shape_dim> FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_bbox_max protected
Definition at line 129 of file voxel_domain_control.hpp.
_bbox_min
template<typename DomainLevel_ > Tiny::Vector<CoordType, shape_dim> FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_bbox_min protected
the bounding box of the structured domain
Definition at line 129 of file voxel_domain_control.hpp.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_2d(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_3d().
_chosen_levels
template<typename DomainLevel_ > std::deque<std::pair<int,int> > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_chosen_levels protected inherited
chosen level deque
Definition at line 132 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_layered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_single_process(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_chosen_levels(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_levels().
_comm
const Dist::Comm& FEAT::Control::Domain::DomainControl< DomainLevel_ >::_comm protected inherited
Definition at line 423 of file domain_control.hpp.
_create_stage
template<typename DomainLevel_ > int FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_stage protected
creation stage to keep track what has already been initialized
Definition at line 126 of file voxel_domain_control.hpp.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_2d(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_3d().
_desired_levels
template<typename DomainLevel_ > std::deque<std::pair<int,int> > FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_desired_levels protected inherited
desired level deque
Definition at line 129 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_create_ancestry_scattered(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_create_multi_layered(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_desired_levels(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_max(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_level_min(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_desired_levels(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels().
_genetic_time_init
template<typename DomainLevel_ > double FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_init protected inherited
time for genetic partitioner initialization
Definition at line 137 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_genetic_time_mutate
template<typename DomainLevel_ > double FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_genetic_time_mutate protected inherited
time for genetic partitioner mutation
Definition at line 139 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_keep_base_levels
bool FEAT::Control::Domain::DomainControl< DomainLevel_ >::_keep_base_levels protected inherited
keep base-mesh levels on root process?
Definition at line 433 of file domain_control.hpp.
_keep_voxel_map
template<typename DomainLevel_ > bool FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_keep_voxel_map protected
specifies whether to keep the voxel map after hierarchy creation
Definition at line 143 of file voxel_domain_control.hpp.
_layer_levels
std::deque<std::deque<std::shared_ptr<LevelType> > > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_layer_levels protected inherited
Definition at line 427 of file domain_control.hpp.
_layers
std::deque<std::shared_ptr<LayerType> > FEAT::Control::Domain::DomainControl< DomainLevel_ >::_layers protected inherited
Definition at line 425 of file domain_control.hpp.
_num_global_layers
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::_num_global_layers protected inherited
Definition at line 429 of file domain_control.hpp.
_required_elems_per_rank
template<typename DomainLevel_ > int FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_required_elems_per_rank protected inherited
required number of elements per rank for a-posteriori partitioning
Definition at line 135 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_check_parti(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), and FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map().
_support_multi_layered
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_support_multi_layered protected inherited
support multi-layered hierarchy?
Definition at line 126 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy().
_virt_levels
std::deque<VirtLevelType> FEAT::Control::Domain::DomainControl< DomainLevel_ >::_virt_levels protected inherited
Definition at line 428 of file domain_control.hpp.
_virt_size
std::size_t FEAT::Control::Domain::DomainControl< DomainLevel_ >::_virt_size protected inherited
Definition at line 430 of file domain_control.hpp.
_voxel_map
template<typename DomainLevel_ > std::unique_ptr<Geometry::VoxelMap> FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_voxel_map protected
the voxel map
Definition at line 134 of file voxel_domain_control.hpp.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::get_voxel_map().
_was_created
template<typename DomainLevel_ > bool FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::_was_created protected inherited
specifies whether the domain control was already created
Definition at line 112 of file parti_domain_control_base.hpp.
Referenced by FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::_create(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_hierarchy(), FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::create_rectilinear(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_args(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::parse_property_map(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_adapt_mode(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels(), and FEAT::Control::Domain::PartiDomainControl< DomainLevel_ >::set_permutation_strategy().
_watch_create_base_mesh
template<typename DomainLevel_ > StopWatch FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_watch_create_base_mesh protected
a bunch of stop-watches
Definition at line 140 of file voxel_domain_control.hpp.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_2d(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_3d(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::get_watch_base_mesh().
_watch_create_hierarchy
template<typename DomainLevel_ > StopWatch FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_watch_create_hierarchy protected
Definition at line 140 of file voxel_domain_control.hpp.
_watch_create_voxel_map
template<typename DomainLevel_ > StopWatch FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_watch_create_voxel_map protected
Definition at line 140 of file voxel_domain_control.hpp.
shape_dim
template<typename DomainLevel_ > constexpr int FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::shape_dim = MeshType::shape_dim static constexpr
shape dimension
Definition at line 119 of file voxel_domain_control.hpp.
Referenced by FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_base_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_compute_refined_mesh_layering(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_patch_halos(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_gather_element_weights(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_gather_masked_elements(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_precreate_voxel_map(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_2d(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_base_mesh_3d(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_lambda(), and FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::create_voxel_map_from_off().
The documentation for this class was generated from the following file:
control/domain/voxel_domain_control.hpp