FEAT: FEAT::Global::Transfer< LocalTransfer_, Mirror_ > Class Template Reference
FEAT::Global::Transfer< LocalTransfer_, Mirror_ > Class Template Reference
Global grid-transfer operator class template.
#include <transfer.hpp>
Public Types
typedef LocalTransfer_::MatrixType LocalMatrixType
our internal local matrix type
typedef LocalTransfer_ LocalTransferType
our local transfer
typedef LocalTransfer_::VectorType LocalVectorType
our internal local vector type
typedef Global::Muxer< LocalVectorType, Mirror_ > MuxerType
our coarse grid multiplexer type
template<typename DT2_ , typename IT2_ >
using TransferTypeByDI = Transfer< typename LocalTransfer_::template TransferTypeByDI< DT2_, IT2_ >, typename Mirror_::template MirrorType< DT2_, IT2_ > >
Our 'base' class type.
typedef Global::Vector< LocalVectorType, Mirror_ > VectorType
our global vector type
Public Member Functions
Transfer ()
standard constructor
template<typename... Args_>
Transfer (const MuxerType *coarse_muxer, Args_ &&... args)
Constructor.
Transfer (Transfer &&other)
move-constructor
virtual ~Transfer ()
virtual destructor
std::size_t bytes () const
Transfer clone (LAFEM::CloneMode clone_mode=LAFEM::CloneMode::Weak) const
Creates a clone of this object.
void compile ()
template<typename LocalTransfer2_ , typename Mirror2_ >
void convert (MuxerType *coarse_muxer, const Transfer< LocalTransfer2_, Mirror2_ > &other)
container conversion function
bool is_ghost () const
Checks whether this transfer is a ghost-operator.
LocalTransfer_ & local ()
const LocalTransfer_ & local () const
Transfer & operator= (Transfer &&other)
move-assign operator
bool prol (VectorType &vec_fine, const VectorType &vec_coarse) const
Applies the prolongation operator.
void prol_cancel () const
Cancels the prolongation.
bool prol_recv (VectorType &vec_fine) const
Receives the prolongation for a ghost operator.
bool rest (const VectorType &vec_fine, VectorType &vec_coarse) const
Applies the restriction operator.
bool rest_send (const VectorType &vec_fine) const
Sends the restriction for a ghost operator.
bool trunc (const VectorType &vec_fine, VectorType &vec_coarse) const
Applies the truncation operator.
bool trunc_send (const VectorType &vec_fine) const
Sends the truncation for a ghost operator.
Public Attributes
const MuxerType * _coarse_muxer
the coarse-level multiplexer
LocalTransfer_ _transfer
the local transfer operator
LocalVectorType _vec_tmp
a temporary local vector
Static Public Attributes
static constexpr bool is_global = true
static constexpr bool is_local = false
Detailed Description
template<typename LocalTransfer_, typename Mirror_>
class FEAT::Global::Transfer< LocalTransfer_, Mirror_ >
Global grid-transfer operator class template.
Author
Peter Zajac
Definition at line 22 of file transfer.hpp.
Member Typedef Documentation
LocalMatrixType
template<typename LocalTransfer_ , typename Mirror_ > typedef LocalTransfer_::MatrixType FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::LocalMatrixType
our internal local matrix type
Definition at line 28 of file transfer.hpp.
LocalTransferType
template<typename LocalTransfer_ , typename Mirror_ > typedef LocalTransfer_ FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::LocalTransferType
our local transfer
Definition at line 26 of file transfer.hpp.
LocalVectorType
template<typename LocalTransfer_ , typename Mirror_ > typedef LocalTransfer_::VectorType FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::LocalVectorType
our internal local vector type
Definition at line 30 of file transfer.hpp.
MuxerType
template<typename LocalTransfer_ , typename Mirror_ > typedef Global::Muxer<LocalVectorType, Mirror_> FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::MuxerType
our coarse grid multiplexer type
Definition at line 36 of file transfer.hpp.
TransferTypeByDI
template<typename LocalTransfer_ , typename Mirror_ > template<typename DT2_ , typename IT2_ > using FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::TransferTypeByDI = Transfer< typename LocalTransfer_::template TransferTypeByDI<DT2_, IT2_>, typename Mirror_::template MirrorType<DT2_, IT2_> >
Our 'base' class type.
Definition at line 40 of file transfer.hpp.
VectorType
template<typename LocalTransfer_ , typename Mirror_ > typedef Global::Vector<LocalVectorType, Mirror_> FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::VectorType
our global vector type
Definition at line 33 of file transfer.hpp.
Constructor & Destructor Documentation
Transfer() [1/3]
template<typename LocalTransfer_ , typename Mirror_ > FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::Transfer () inline
standard constructor
Definition at line 57 of file transfer.hpp.
Referenced by FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::clone().
Transfer() [2/3]
template<typename LocalTransfer_ , typename Mirror_ > FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::Transfer (Transfer< LocalTransfer_, Mirror_ > && other) inline
move-constructor
Definition at line 63 of file transfer.hpp.
Transfer() [3/3]
template<typename LocalTransfer_ , typename Mirror_ > template<typename... Args_> FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::Transfer (const MuxerType * coarse_muxer, Args_ &&... args) inline explicit
Constructor.
Parameters
[in] coarse_muxer The coarse-level muxer.
[in] args The arguments that are passed to the local transfer operator constructor.
Definition at line 80 of file transfer.hpp.
~Transfer()
template<typename LocalTransfer_ , typename Mirror_ > virtual FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::~Transfer () inline virtual
virtual destructor
Definition at line 88 of file transfer.hpp.
Member Function Documentation
bytes()
template<typename LocalTransfer_ , typename Mirror_ > std::size_t FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::bytes () const inline
Returns
the internal data size in bytes
Definition at line 143 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, and FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp.
Referenced by FEAT::Control::BlockedBasicSystemLevel< dim_, DataType_, IndexType_, BlockedMatrix_, TransferMatrix_ >::bytes(), FEAT::Control::ScalarBasicSystemLevel< DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::bytes(), FEAT::Control::ScalarMixedSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_ >::bytes(), FEAT::Control::Stokes3FieldSystemLevel< dim_, nsc_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, MatrixBlockM_, MatrixBlockK_, MatrixBlockL_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_, TransferMatrixS_ >::bytes(), and FEAT::Control::StokesBlockedSystemLevel< dim_, DataType_, IndexType_, MatrixBlockA_, MatrixBlockB_, MatrixBlockD_, ScalarMatrix_, TransferMatrixV_, TransferMatrixP_, TransferMatrixS_ >::bytes().
clone()
template<typename LocalTransfer_ , typename Mirror_ > Transfer FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::clone (LAFEM::CloneMode clone_mode = LAFEM::CloneMode::Weak) const inline
Creates a clone of this object.
Parameters
[in] clone_mode The desired clone mode
Returns
A clone of this object
Definition at line 125 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::Transfer(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, and FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer.
compile()
template<typename LocalTransfer_ , typename Mirror_ > void FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::compile () inline
Definition at line 148 of file transfer.hpp.
convert()
template<typename LocalTransfer_ , typename Mirror_ > template<typename LocalTransfer2_ , typename Mirror2_ > void FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::convert (MuxerType * coarse_muxer, const Transfer< LocalTransfer2_, Mirror2_ > & other) inline
container conversion function
Definition at line 107 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, and FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp.
is_ghost()
template<typename LocalTransfer_ , typename Mirror_ > bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::is_ghost () const inline
Checks whether this transfer is a ghost-operator.
Definition at line 194 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, and FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_ghost().
local() [1/2]
template<typename LocalTransfer_ , typename Mirror_ > LocalTransfer_ & FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::local () inline
Returns
the local transfer operator
Definition at line 131 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer.
Referenced by FEAT::Control::Meshopt::MeshoptSystemLevel< DT_, IT_, Functional_ >::assemble_system_transfer().
local() [2/2]
template<typename LocalTransfer_ , typename Mirror_ > const LocalTransfer_ & FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::local () const inline
Returns
the local transfer operator
Definition at line 137 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer.
operator=()
template<typename LocalTransfer_ , typename Mirror_ > Transfer & FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::operator= (Transfer< LocalTransfer_, Mirror_ > && other) inline
move-assign operator
Definition at line 93 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, and FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp.
prol()
template<typename LocalTransfer_ , typename Mirror_ > bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol (VectorType & vec_fine, const VectorType & vec_coarse) const inline
Applies the prolongation operator.
Parameters
[out] vec_fine The prolonged fine-mesh primal vector.
[in] vec_coarse The coarse-mesh primal vector to be prolonged.
Returns
true
Definition at line 294 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp, FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_child(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_parent(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split(), FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0(), and XASSERT.
prol_cancel()
template<typename LocalTransfer_ , typename Mirror_ > void FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol_cancel () const inline
Cancels the prolongation.
Definition at line 314 of file transfer.hpp.
References XASSERTM.
prol_recv()
template<typename LocalTransfer_ , typename Mirror_ > bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol_recv (VectorType & vec_fine) const inline
Receives the prolongation for a ghost operator.
Parameters
[out] vec_fine The prolonged fine-mesh primal vector.
Definition at line 325 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp, FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_ghost(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::split_recv(), FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0(), and XASSERT.
rest()
template<typename LocalTransfer_ , typename Mirror_ > bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::rest (const VectorType & vec_fine, VectorType & vec_coarse) const inline
Applies the restriction operator.
Parameters
[in] vec_fine The fine-mesh dual vector to be restricted.
[out] vec_coarse The restricted coarse-mesh dual vector.
Returns
true
Definition at line 252 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp, FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_child(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_parent(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0(), and XASSERT.
rest_send()
template<typename LocalTransfer_ , typename Mirror_ > bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::rest_send (const VectorType & vec_fine) const inline
Sends the restriction for a ghost operator.
Parameters
[in] vec_fine The fine-mesh dual vector to be restricted.
Definition at line 274 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp, FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_ghost(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join_send(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and XASSERT.
trunc()
template<typename LocalTransfer_ , typename Mirror_ > bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::trunc (const VectorType & vec_fine, VectorType & vec_coarse) const inline
Applies the truncation operator.
Parameters
[in] vec_fine The fine-mesh dual vector to be truncated.
[out] vec_coarse The truncated coarse-mesh dual vector.
Returns
true
Definition at line 210 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp, FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_child(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_parent(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), FEAT::Global::Vector< LocalVector_, Mirror_ >::sync_0(), and XASSERT.
trunc_send()
template<typename LocalTransfer_ , typename Mirror_ > bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::trunc_send (const VectorType & vec_fine) const inline
Sends the truncation for a ghost operator.
Parameters
[in] vec_fine The fine-mesh dual vector to be truncated.
Definition at line 232 of file transfer.hpp.
References FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer, FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp, FEAT::Global::Muxer< LocalVector_, Mirror_ >::is_ghost(), FEAT::Global::Muxer< LocalVector_, Mirror_ >::join_send(), FEAT::Global::Vector< LocalVector_, Mirror_ >::local(), and XASSERT.
Member Data Documentation
_coarse_muxer
template<typename LocalTransfer_ , typename Mirror_ > const MuxerType* FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_coarse_muxer
the coarse-level multiplexer
Definition at line 49 of file transfer.hpp.
Referenced by FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::clone(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::convert(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::is_ghost(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::operator=(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol_recv(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::rest(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::rest_send(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::trunc(), and FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::trunc_send().
_transfer
template<typename LocalTransfer_ , typename Mirror_ > LocalTransfer_ FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_transfer
the local transfer operator
Definition at line 51 of file transfer.hpp.
Referenced by FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::bytes(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::clone(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::convert(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::local(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::operator=(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol_recv(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::rest(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::rest_send(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::trunc(), and FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::trunc_send().
_vec_tmp
template<typename LocalTransfer_ , typename Mirror_ > LocalVectorType FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::_vec_tmp mutable
a temporary local vector
Definition at line 53 of file transfer.hpp.
Referenced by FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::bytes(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::convert(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::operator=(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::prol_recv(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::rest(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::rest_send(), FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::trunc(), and FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::trunc_send().
is_global
template<typename LocalTransfer_ , typename Mirror_ > constexpr bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::is_global = true static constexpr
Definition at line 44 of file transfer.hpp.
is_local
template<typename LocalTransfer_ , typename Mirror_ > constexpr bool FEAT::Global::Transfer< LocalTransfer_, Mirror_ >::is_local = false static constexpr
Definition at line 45 of file transfer.hpp.
The documentation for this class was generated from the following file:
kernel/global/transfer.hpp