FEAT: FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ > Class Template Reference
FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ > Class Template Reference
*‍/
#include <domain_assembler.hpp>
Public Member Functions
Worker (Job_ &job, std::size_t id, std::size_t num_workers, ThreadingStrategy strategy, ThreadStats &thread_stats, std::mutex &thread_mutex, std::vector< ThreadFence > &thread_fences, const std::vector< Index > &element_indices, const std::vector< Index > &color_elements, const std::vector< Index > &layer_elements, const std::vector< Index > &thread_layers)
Constructor.
virtual ~Worker ()
virtual destructor
void operator() ()
Evaluation operator.
Protected Member Functions
bool _work_colored (std::unique_ptr< TaskType > task)
Assembly worker implementation for colored strategy.
bool _work_layered (std::unique_ptr< TaskType > task)
Assembly worker implementation for layered (+sorted) strategy.
bool _work_no_scatter (std::unique_ptr< TaskType > task)
Assembly worker implementation for no-scatter assembly.
bool _work_single (std::unique_ptr< TaskType > task)
Assembly worker implementation for single-threaded strategy.
Private Types
typedef Job_::Task TaskType
a typedef for the task
Private Attributes
const std::vector< Index > & _color_elements
the color elements vector
const std::vector< Index > & _element_indices
the element indices vector
Job_ & _job
a reference to the assembly job
const std::vector< Index > & _layer_elements
the layer elements vector
const std::size_t _my_id
id of this worker thread and total number of worker threads
const std::size_t _num_workers
const ThreadingStrategy _strategy
the chosen threading strategy
std::vector< ThreadFence > & _thread_fences
the thread fences vector
const std::vector< Index > & _thread_layers
the thread layers vector
std::mutex & _thread_mutex
the free-to-use thread mutex
ThreadStats & _thread_stats
the thread statistics
Detailed Description
template<typename Trafo_>
template<typename Job_>
class FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >
*‍/
Worker thread data class
This class encapsulates all data that is required by a worker thread to execute an assembly job.
Definition at line 464 of file domain_assembler.hpp.
Member Typedef Documentation
TaskType
template<typename Trafo_ > template<typename Job_ > typedef Job_::Task FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::TaskType private
a typedef for the task
Definition at line 468 of file domain_assembler.hpp.
Constructor & Destructor Documentation
Worker()
template<typename Trafo_ > template<typename Job_ > FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::Worker (Job_ & job, std::size_t id, std::size_t num_workers, ThreadingStrategy strategy, ThreadStats & thread_stats, std::mutex & thread_mutex, std::vector< ThreadFence > & thread_fences, const std::vector< Index > & element_indices, const std::vector< Index > & color_elements, const std::vector< Index > & layer_elements, const std::vector< Index > & thread_layers) inline explicit
Constructor.
Parameters
[in] job A resident reference to the assembly job.
[in] id The id of this worker thread. Is 0 if the master thread is assembling, otherwise 1 <= id <= num_workers.
[in] num_workers The total number of worker threads. May be 0 if the master thread is assembling.
[in] strategy The chosen threading strategy
[in,out] thread_stats A resident reference to the thread's statistics object.
[in,out] thread_mutex A resident reference to the common thread mutex.
[in,out] thread_fences A resident reference to the thread fence vector.
[in] element_indices A resident reference to the element indices vector.
[in] color_elements A resident reference to the color elements vector.
[in] layer_elements A resident reference to the layer elements vector.
[in] thread_layers A resident reference to the thread layers vector.
Definition at line 529 of file domain_assembler.hpp.
~Worker()
template<typename Trafo_ > template<typename Job_ > virtual FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::~Worker () inline virtual
virtual destructor
Definition at line 553 of file domain_assembler.hpp.
Member Function Documentation
_work_colored()
template<typename Trafo_ > template<typename Job_ > bool FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_colored (std::unique_ptr< TaskType > task) inline protected
Assembly worker implementation for colored strategy.
This member function implements the actual assembly for the colored threading strategy.
Parameters
[in] task A unique pointer to the task that is to be executed.
Definition at line 856 of file domain_assembler.hpp.
References FEAT::TimeStamp::elapsed_micros(), FEAT::TimeStamp::elapsed_micros_now(), FEAT::Assembly::DomainAssembler< Trafo_ >::ThreadStats::micros_assemble, FEAT::Assembly::DomainAssembler< Trafo_ >::ThreadStats::micros_wait, and FEAT::TimeStamp::stamp().
Referenced by FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::operator()().
_work_layered()
template<typename Trafo_ > template<typename Job_ > bool FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_layered (std::unique_ptr< TaskType > task) inline protected
Assembly worker implementation for layered (+sorted) strategy.
This member function implements the actual assembly for the layered threading strategy.
Parameters
[in] task A unique pointer to the task that is to be executed.
Definition at line 731 of file domain_assembler.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_my_id, FEAT::TimeStamp::elapsed_micros(), FEAT::TimeStamp::elapsed_micros_now(), FEAT::Assembly::DomainAssembler< Trafo_ >::ThreadStats::micros_assemble, FEAT::Assembly::DomainAssembler< Trafo_ >::ThreadStats::micros_wait, FEAT::TimeStamp::stamp(), and XASSERTM.
Referenced by FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::operator()().
_work_no_scatter()
template<typename Trafo_ > template<typename Job_ > bool FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_no_scatter (std::unique_ptr< TaskType > task) inline protected
Assembly worker implementation for no-scatter assembly.
This member function implements the actual no-scatter assembly, which does not perform any synchronization to avoid race conditions except for the optional mutexed combine.
Parameters
[in] task A unique pointer to the task that is to be executed.
Definition at line 674 of file domain_assembler.hpp.
References FEAT::TimeStamp::elapsed_micros(), FEAT::TimeStamp::elapsed_micros_now(), FEAT::Assembly::DomainAssembler< Trafo_ >::ThreadStats::micros_assemble, FEAT::Assembly::DomainAssembler< Trafo_ >::ThreadStats::micros_wait, FEAT::TimeStamp::stamp(), and XASSERTM.
Referenced by FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::operator()().
_work_single()
template<typename Trafo_ > template<typename Job_ > bool FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_single (std::unique_ptr< TaskType > task) inline protected
Assembly worker implementation for single-threaded strategy.
This member function implements the actual assembly for the single-threaded strategy.
Parameters
[in] task A unique pointer to the task that is to be executed.
Definition at line 623 of file domain_assembler.hpp.
References FEAT::TimeStamp::elapsed_micros_now(), FEAT::Assembly::DomainAssembler< Trafo_ >::ThreadStats::micros_assemble, and XASSERTM.
Referenced by FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::operator()().
operator()()
template<typename Trafo_ > template<typename Job_ > void FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::operator() () inline
Evaluation operator.
This operator is called by each thread to execute the assembly.
Definition at line 562 of file domain_assembler.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_job, FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_colored(), FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_layered(), FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_no_scatter(), FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_single(), FEAT::Assembly::colored, FEAT::TimeStamp::elapsed_micros_now(), and FEAT::Assembly::DomainAssembler< Trafo_ >::ThreadStats::micros_total.
Member Data Documentation
_color_elements
template<typename Trafo_ > template<typename Job_ > const std::vector<Index>& FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_color_elements private
the color elements vector
Definition at line 484 of file domain_assembler.hpp.
_element_indices
template<typename Trafo_ > template<typename Job_ > const std::vector<Index>& FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_element_indices private
the element indices vector
Definition at line 482 of file domain_assembler.hpp.
_job
template<typename Trafo_ > template<typename Job_ > Job_& FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_job private
a reference to the assembly job
Definition at line 470 of file domain_assembler.hpp.
Referenced by FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::operator()().
_layer_elements
template<typename Trafo_ > template<typename Job_ > const std::vector<Index>& FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_layer_elements private
the layer elements vector
Definition at line 486 of file domain_assembler.hpp.
_my_id
template<typename Trafo_ > template<typename Job_ > const std::size_t FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_my_id private
id of this worker thread and total number of worker threads
Definition at line 472 of file domain_assembler.hpp.
Referenced by FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_work_layered().
_num_workers
template<typename Trafo_ > template<typename Job_ > const std::size_t FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_num_workers private
Definition at line 472 of file domain_assembler.hpp.
_strategy
template<typename Trafo_ > template<typename Job_ > const ThreadingStrategy FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_strategy private
the chosen threading strategy
Definition at line 474 of file domain_assembler.hpp.
_thread_fences
template<typename Trafo_ > template<typename Job_ > std::vector<ThreadFence>& FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_thread_fences private
the thread fences vector
Definition at line 480 of file domain_assembler.hpp.
_thread_layers
template<typename Trafo_ > template<typename Job_ > const std::vector<Index>& FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_thread_layers private
the thread layers vector
Definition at line 488 of file domain_assembler.hpp.
_thread_mutex
template<typename Trafo_ > template<typename Job_ > std::mutex& FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_thread_mutex private
the free-to-use thread mutex
Definition at line 476 of file domain_assembler.hpp.
_thread_stats
template<typename Trafo_ > template<typename Job_ > ThreadStats& FEAT::Assembly::DomainAssembler< Trafo_ >::Worker< Job_ >::_thread_stats private
the thread statistics
Definition at line 478 of file domain_assembler.hpp.
The documentation for this class was generated from the following file:
kernel/assembly/domain_assembler.hpp