var dir_2fc8e21c74047a85e942968bac7fe59f =
[
    [ "boundary_computer.hpp", "boundary__computer_8hpp_source.html", null ],
    [ "coarse_fine_cell_mapping.hpp", "coarse__fine__cell__mapping_8hpp_source.html", null ],
    [ "congruency_mapping.hpp", "congruency__mapping_8hpp_source.html", null ],
    [ "congruency_sampler.hpp", "congruency__sampler_8hpp_source.html", null ],
    [ "congruency_trafo.hpp", "congruency__trafo_8hpp_source.html", null ],
    [ "dual_adaptor.hpp", "dual__adaptor_8hpp_source.html", null ],
    [ "entity_counter.hpp", "entity__counter_8hpp_source.html", null ],
    [ "face_index_mapping.hpp", "face__index__mapping_8hpp_source.html", null ],
    [ "face_ref_trafo.hpp", "face__ref__trafo_8hpp_source.html", null ],
    [ "facet_neighbors.hpp", "facet__neighbors_8hpp_source.html", null ],
    [ "index_representative.hpp", "index__representative_8hpp_source.html", null ],
    [ "index_set_filler.hpp", "index__set__filler_8hpp_source.html", null ],
    [ "macro_index_mapping.hpp", "macro__index__mapping_8hpp_source.html", null ],
    [ "patch_index_mapping.hpp", "patch__index__mapping_8hpp_source.html", null ],
    [ "shape_convert_index.hpp", "shape__convert__index_8hpp_source.html", null ],
    [ "shape_convert_target.hpp", "shape__convert__target_8hpp_source.html", null ],
    [ "shape_convert_traits.hpp", "shape__convert__traits_8hpp_source.html", null ],
    [ "shape_convert_vertex.hpp", "shape__convert__vertex_8hpp_source.html", null ],
    [ "simple_target_refiner.hpp", "simple__target__refiner_8hpp_source.html", null ],
    [ "standard_attrib_refiner.hpp", "standard__attrib__refiner_8hpp_source.html", null ],
    [ "standard_index_refiner.hpp", "standard__index__refiner_8hpp_source.html", null ],
    [ "standard_refinement_traits.hpp", "standard__refinement__traits_8hpp_source.html", null ],
    [ "standard_target_refiner.hpp", "standard__target__refiner_8hpp_source.html", null ],
    [ "standard_vertex_refiner.hpp", "standard__vertex__refiner_8hpp_source.html", null ],
    [ "struct_index_coding.hpp", "struct__index__coding_8hpp_source.html", null ],
    [ "struct_index_mapping.hpp", "struct__index__mapping_8hpp_source.html", null ],
    [ "struct_num_entities.hpp", "struct__num__entities_8hpp_source.html", null ],
    [ "structured_target_refiner.hpp", "structured__target__refiner_8hpp_source.html", null ],
    [ "structured_vertex_refiner.hpp", "structured__vertex__refiner_8hpp_source.html", null ],
    [ "sub_index_mapping.hpp", "sub__index__mapping_8hpp_source.html", null ],
    [ "target_index_mapping.hpp", "target__index__mapping_8hpp_source.html", null ],
    [ "target_set_computer.hpp", "target__set__computer_8hpp_source.html", null ]
];