#!/usr/bin/env python
# vim: set filetype=python sw=2 sts=2 et nofoldenable :
# This is a python script.
# If you encounter problemes when executing it on its own, start it with a python interpreter
from __future__ import print_function
import sys
import os
import subprocess
import socket
import shutil
import time
import datetime
import peewee as pw
import smtplib

sys.dont_write_bytecode = True

def get_messages(r, stage, status):
  return Message.select().where(Message.runid == r.id, Message.stage == stage, Message.status == status)

myDB = pw.MySQLDatabase("feastdash", host="augias", port=3306, user="feastdash", passwd="feastdash")
myDB.connect()

class MySQLModel(pw.Model):
  """A base model that will use our MySQL database"""
  class Meta:
    database = myDB

class User(MySQLModel):
  username = pw.CharField()

class BranchQueue(MySQLModel):
  branch = pw.CharField()

class Run(MySQLModel):
  branch = pw.CharField()
  hostname = pw.CharField()
  build = pw.CharField()
  starttime = pw.IntegerField()
  endtime = pw.IntegerField()
  notes = pw.TextField()

class Message(MySQLModel):
  runid = pw.ForeignKeyField(Run, related_name="messages", db_column="runid")
  stage = pw.CharField()
  status = pw.CharField()
  timestamp = pw.IntegerField()
  title = pw.CharField()
  body = pw.TextField()

class Attachment(MySQLModel):
  messageid = pw.ForeignKeyField(Message, related_name="attachments", db_column="messageid")
  name = pw.CharField()
  mimetype = pw.CharField()
  data = pw.BlobField()

class Subscriber(MySQLModel):
  email = pw.CharField()

################## MAIN ######################

#TODO help, ? und guess nicht in sys.argv[0] suchen
# output help screen
if len(sys.argv) != 1 and ("help" in " ".join(sys.argv) or "?" in " ".join(sys.argv)):
  print ("This python scripts collects test results from the database and sends them via email")
  sys.exit()

dt = datetime.datetime.today()
#dt = datetime.datetime(2013, 12, 11)
starttime = datetime.datetime(dt.year, dt.month, dt.day)
endtime = datetime.datetime(dt.year, dt.month, dt.day, 23, 59)
runs = Run.select().where(Run.starttime.between(time.mktime(starttime.timetuple()), time.mktime(endtime.timetuple())))

detailed_report = ""
failed_report = ""
passed_report = ""
failed_runs = []
passed_runs = []

for run in runs:
  config_warning = get_messages(run, "configure", "warning")
  config_error = get_messages(run, "configure", "error")
  build_warning = get_messages(run, "build", "warning")
  build_error = get_messages(run, "build", "error")
  test_failed = get_messages(run, "test", "failed")

  if config_warning.count() + config_error.count() + build_warning.count() + build_error.count() + test_failed.count() > 0:
    failed_runs.append(run)
  else:
    passed_runs.append(run)

if len(failed_runs) == 0:
  failed_report = "No run failed\n\n"
else:
  failed_report = "Failed runs:\n"
  for run in failed_runs:
    config_warning = get_messages(run, "configure", "warning")
    config_error = get_messages(run, "configure", "error")
    build_warning = get_messages(run, "build", "warning")
    build_error = get_messages(run, "build", "error")
    test_failed = get_messages(run, "test", "failed")
    test_passed = get_messages(run, "test", "passed")

    failed_report += "  " + run.hostname + " " + run.branch + " "+ run.build + " C: " + str(config_warning.count()) + " " + str(config_error.count()) + " B: " + str(build_warning.count()) + " " + str(build_error.count()) + " T: " + str(test_failed.count()) + " " + str(test_passed.count()) + "\n"

if len(passed_runs) == 0:
  passed_report = "No run passed without failure\n\n"
else:
  passed_report = "Passed runs:\n"
  for run in passed_runs:
    config_warning = get_messages(run, "configure", "warning")
    config_error = get_messages(run, "configure", "error")
    build_warning = get_messages(run, "build", "warning")
    build_error = get_messages(run, "build", "error")
    test_failed = get_messages(run, "test", "failed")
    test_passed = get_messages(run, "test", "passed")

    passed_report += "  " + run.hostname + " " + run.branch + " "+ run.build + " C: " + str(config_warning.count()) + " " + str(config_error.count()) + " B: " + str(build_warning.count()) + " " + str(build_error.count()) + " T: " + str(test_failed.count()) + " " + str(test_passed.count()) + "\n"


if len(failed_runs) > 0:
  detailed_report = "Detailed report of failed runs:\n\n"
for run in failed_runs:
  config_warning = get_messages(run, "configure", "warning")
  config_error = get_messages(run, "configure", "error")
  build_warning = get_messages(run, "build", "warning")
  build_error = get_messages(run, "build", "error")
  test_failed = get_messages(run, "test", "failed")
  test_passed = get_messages(run, "test", "passed")

  detailed_report += "Host: " + run.hostname + " Branch: " + run.branch + " Buildid: "+ run.build + "\n"

  detailed_report += "=== CONFIGURE ===\n"
  config_warning = get_messages(run, "configure", "warning")
  detailed_report += "Warnings: " + str(config_warning.count()) + "\n"
  config_error = get_messages(run, "configure", "error")
  detailed_report += "Errors: " + str(config_error.count()) + "\n"

  detailed_report += "=== BUILD ===\n"
  build_warning = get_messages(run, "build", "warning")
  detailed_report += "Warnings: " + str(build_warning.count()) + "\n"
  for i in build_warning:
    detailed_report += "   " + i.title + "\n"
  build_error = get_messages(run, "build", "error")
  detailed_report += "Errors: " + str(build_error.count()) + "\n"
  for i in build_error:
    detailed_report += "   " + i.title + "\n"

  detailed_report += "=== TEST ===\n"
  test_failed = get_messages(run, "test", "failed")
  detailed_report += "Failed: " + str(test_failed.count()) + "\n"
  for i in test_failed:
    detailed_report += "   " + i.title + "\n"
  test_passed = get_messages(run, "test", "passed")
  detailed_report += "Passed: " + str(test_passed.count()) + "\n"

  detailed_report += "\n\n"


mail_body = "\n" + failed_report + "\n" + passed_report + "\n" + detailed_report

mail_subject = "Subject: [FEAST-DASH] Summary Mail - "
if len(failed_runs) == 0:
  mail_subject += "All runs passed"
else:
  mail_subject += str(len(failed_runs))+ " runs failed"
mail_from = "dirk.ribbrock@math.tu-dortmund.de"
mail_to = [i.email for i in Subscriber.select()]

s = smtplib.SMTP("localhost")
s.sendmail(mail_from, mail_to, os.linesep.join([mail_subject, "From: " + mail_from, "To: " + ", ".join(mail_to), mail_body]))
s.quit()
