FEAT: FEAT::Assembly Namespace Reference
FEAT::Assembly Namespace Reference
Assembly namespace.
Namespaces
namespace Common
Assembly Common namespace.
Classes
class AnalyticCellProjector
Analytic cell projector class.
struct AnalyticFunctionIntegral
Helper class to determine the FunctionIntegralInfo type for analytic functions.
class AnalyticFunctionIntegralJob
Assembly job for the integration of an analytic function.
class AnalyticVertexProjector
Analytic vertex projector class.
class AsmTraits1
Common single-space assembly traits class template.
class AsmTraits2
Common test-/trial-space assembly traits class template.
class AsmTraits3
Common test-/trial-/mult-space assembly traits class template.
class BasicMatrixAssemblyTaskCRTP1
Basic Matrix assembly task CRTP base-class for identical test-/trial-space.
class BasicMatrixAssemblyTaskCRTP2
Basic Matrix assembly task CRTP base-class for (possibly different) test-/trial-spaces.
class BasicVectorAssemblyTaskCRTP
Basic Vector assembly task CRTP base-class.
class BilinearOperator
Base class for Bilinear Operators.
class BilinearOperatorAssembler
Bilinear Operator Assembler class template.
class BilinearOperatorMatrixAssemblyJob1
Matrix assembly job for BilinearOperator and identical test-/trial-spaces.
class BilinearOperatorMatrixAssemblyJob2
Matrix assembly job for BilinearOperator and (possibly different) test-/trial-spaces.
class BurgersAssembler
Burgers operator assembly class.
class BurgersAssemblerCarreau
Burgers operator assembly class.
class BurgersAssemblyJobBase
Base class for Burgers assembly jobs.
class BurgersAssemblyTaskBase
Base class for Burgers assembly tasks.
class BurgersBlockedAssemblyTaskBase
Base class for blocked Burgers assembly tasks.
class BurgersBlockedMatrixAssemblyJob
Burgers assembly job for block matrix.
class BurgersBlockedVectorAssemblyJob
Burgers assembly job for block right-hand-side vector.
class BurgersScalarAssemblyTaskBase
Base class for scalar Burgers assembly tasks.
class BurgersScalarMatrixAssemblyJob
Burgers assembly job for scalar matrix.
class BurgersScalarVectorAssemblyJob
Burgers assembly job for scalar right-hand-side vector.
class DiscreteCellProjector
Discrete cell projector class.
class DiscreteEvaluator
Discrete function evaluator.
struct DiscreteFunctionIntegral
Helper class to determine the FunctionIntegralInfo type for discrete functions.
struct DiscreteFunctionIntegral< LAFEM::DenseVector< DT_, IT_ >, Space_ >
specialization for LAFEM::DenseVector coefficient vectors
struct DiscreteFunctionIntegral< LAFEM::DenseVectorBlocked< DT_, IT_, bs_ >, Space_ >
specialization for LAFEM::DenseVectorBlocked coefficient vectors
class DiscreteFunctionIntegralJob
Assembly job for the integration of a discrete finite element function.
class DiscreteVertexProjector
Discrete vertex projector class.
class DomainAssembler
Domain Integral Assembler class template.
class DomainAssemblyJob
Interface description of a domain assembly job.
class ErrorFunctionIntegralJob
Assembly job for the integration of a analytic vs discrete error function.
struct FEInterpolator
Interpolation operator between two finite element spaces.
struct FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >
Interpolator class from Lagrange2 to Lagrange1.
struct FEInterpolator< Space::Lagrange2::Element< Trafo_ >, Space::Lagrange1::Element< Trafo_ > >
Interpolator class from Lagrange1 to Lagrange2.
struct FEInterpolator< Space_, Space_ >
Interpolator class for trivial interpolator between same class.
class ForceFunctionalAssemblyJob
Vector assembly job for a force functional represented by an analytic function.
class FunctionIntegralInfo
Function integral info class.
class GradOperatorAssembler
Assembles the gradient operator.
class GradPresDivVeloAssembler
Grad(P)/Div(V) assembler class.
class GridTransfer
Grid-Transfer assembly class template.
class Interpolator
Interpolator class template.
struct Lagrange1To2DofAtEntity
Helper class that recurses through shape dimensions and evaluates Lagrange2 DoF based on Lagrange1 DoF.
struct Lagrange1To2DofAtEntity< Trafo_, 0 >
End of helper class template recursion.
class LinearFunctional
Base class for Linear Functionals.
class LinearFunctionalAssembler
Linear Functional Assembly class template.
class LinearFunctionalAssemblyJob
Vector assembly job for LinearFunctional implementations.
class MatrixDiscreteEvalData
Discrete evaluation data for matrix-valued functions.
class MeanFilterAssembler
Mean Filter assembler class.
class MirrorAssembler
Dof-Mirror assembler class template.
class OldroydAssembler
Oldroyd-B operator assembly class.
class OuterNormalComputer
*‍/
class RewProjector
Restricted Element-Wise Projection operator.
class ScalarDiscreteEvalData
Discrete evaluation data for scalar functions.
class ScalarErrorComputer
Scalar H0/H1/H2-error computer class template.
struct ScalarErrorInfo
Scalar Error information structure.
class SlipFilterAssembler
Contains routines to assemble slip filters.
class StokesFBMAssembler
Stokes Fictitious Boundary Method assembler class.
class SymbolicAssembler
Symbolic Matrix and Graph assembler class.
class TraceAssembler
Assembler for operators/functionals on boundaries and other sub-dimensional mesh parts.
class UnitFilterAssembler
Unit-Filter assembly class template.
class VectorDiscreteEvalData
Discrete evaluation data for vector-valued functions.
class VectorErrorComputer
Vector H0/H1/H2-error computer class template.
struct VectorErrorInfo
Vector Error information structure.
class VelocityAnalyser
Velocity field analyser class.
struct VelocityInfo
Velocity field information structure.
Enumerations
enum class ThreadingStrategy {
automatic = 0 , single , layered , layered_sorted ,
colored
}
Threading Strategy for multi-threaded assembler.
Functions
template<typename Trafo_ , typename Matrix_ , typename BilOp_ , typename Space_ >
void assemble_bilinear_operator_matrix_1 (DomainAssembler< Trafo_ > &dom_asm, Matrix_ &matrix, const BilOp_ &bilinear_operator, const Space_ &space, const String &cubature, const typename Matrix_::DataType alpha=typename Matrix_::DataType(1))
Assembles a bilinear operator into a matrix with identical test- and trial-spaces.
template<typename Trafo_ , typename Matrix_ , typename BilOp_ , typename TestSpace_ , typename TrialSpace_ >
void assemble_bilinear_operator_matrix_2 (DomainAssembler< Trafo_ > &dom_asm, Matrix_ &matrix, const BilOp_ &bilinear_operator, const TestSpace_ &test_space, const TrialSpace_ &trial_space, const String &cubature, const typename Matrix_::DataType alpha=typename Matrix_::DataType(1))
Assembles a bilinear operator into a matrix with different test- and trial-spaces.
template<typename Trafo_ , typename Vector_ , typename Function_ , typename Space_ >
void assemble_force_function_vector (DomainAssembler< Trafo_ > &dom_asm, Vector_ &vector, const Function_ &function, const Space_ &space, const String &cubature, const typename Vector_::DataType alpha=typename Vector_::DataType(1))
Assembles a force function into a vector.
template<typename Trafo_ , typename Vector_ , typename LinFunc_ , typename Space_ >
void assemble_linear_functional_vector (DomainAssembler< Trafo_ > &dom_asm, Vector_ &vector, const LinFunc_ &linear_functional, const Space_ &space, const String &cubature, const typename Vector_::DataType alpha=typename Vector_::DataType(1))
Assembles a linear functional into a vector.
template<int max_der_, typename DataType_ , typename Trafo_ , typename Function_ >
AnalyticFunctionIntegral< DataType_, Function_ >::Type integrate_analytic_function (DomainAssembler< Trafo_ > &dom_asm, const Function_ &function, const String &cubature)
Assembles the integral of an analytic function.
template<int max_der_, typename Vector_ , typename Trafo_ , typename Space_ >
DiscreteFunctionIntegral< Vector_, Space_ >::Type integrate_discrete_function (DomainAssembler< Trafo_ > &dom_asm, const Vector_ &vector, const Space_ &space, const String &cubature)
Assembles the integral of a discrete finite element function.
template<int max_der_, typename Function_ , typename Vector_ , typename Trafo_ , typename Space_ >
DiscreteFunctionIntegral< Vector_, Space_ >::Type integrate_error_function (DomainAssembler< Trafo_ > &dom_asm, const Function_ &function, const Vector_ &vector, const Space_ &space, const String &cubature)
Assembles the integral of an (analytic - discrete) error function.
Detailed Description
Assembly namespace.
Enumeration Type Documentation
ThreadingStrategy
enum class FEAT::Assembly::ThreadingStrategy strong
Threading Strategy for multi-threaded assembler.
This enumeration defines the various threading strategies supported by the DomainAssembler class template.
Enumerator
automatic
Automatic threading strategy.
This is the recommended default threading strategy.
This value specifies that the domain assembler should choose an appropriate threading strategy for the given number of maximum worker threads however it sees fit.
In its current implementation, the domain assembler will automatically choose the strategy based on the following criterions:
If only 1 thread is requested, ThreadingStrategy::single is chosen.
If the underlying mesh is permuted using the Geometry::PermutationStrategy::colored permutation strategy, then ThreadingStrategy::colored is chosen.
In any other case, ThreadingStrategy::layered is chosen.
single
Single-Threaded strategy.
This strategy corresponds to the single-threading approach, i.e. no multi-threading is performed.
layered
Layered threading strategy.
This strategy performs a (reverse) Cuthill-McKee ordering of the mesh elements to obtain a sequence of element layers which can be processed in parallel. By construction of the Cuthill-McKee layers, race conditions can only appear within two adjacent element layers, so it is sufficient to ensure that no two threads process two adjacent layers at the same time.
Example:
Consider the following 5x5 square mesh, then the Cuthill-McKee algorithm could produce the following 5 element layers A, B, C, D and E.
+---+---+---+---+---+
| E | E | E | E | E |
+---+---+---+---+---+
| D | D | D | D | E |
+---+---+---+---+---+
| C | C | C | D | E |
+---+---+---+---+---+
| B | B | C | D | E |
+---+---+---+---+---+
| A | B | C | D | E |
+---+---+---+---+---+
In a two-threaded assembly, the first thread may process the layers E and D, where as the second thread may process the layers C, B, and A. The only critical section are the two adjacent layers D and C, which may not be processed at the same time by the two threads. To avoid race conditions here, the second thread will notify the first thread once it has finished processing its first layer C, so that the first thread may proceed to process its last layer D.
In the general case, each thread is assigned 2 or more adjacent Cuthill-McKee layers, so that the only required interaction between threads takes place at the adjacent layers of two adjacent threads. Just as in the simple example above, each thread notifies its preceding thread once it has finished processing its first layer and each thread has to wait for notification from its succeeding thread before its starts processing its last layer to avoid race conditions on adjacent layers.
layered_sorted
Layered + sorted threading strategy.
This threading strategy is mostly identical to the (simple) layered strategy, where the only difference is that all entities in each layer are sorted by ascending degree, i.e. by the number of neighbor entities. This represents the 'classical' Cuthill-McKee ordering algorithms for simple graphs.
In practical experiments – especially when combined with mesh permutations – this layered+sorted strategy is often LESS efficient than the simple (unsorted) layered strategy, so therefore it is recommended to use the unsorted strategy. This sorted strategy is implemented primarily for benchmarking reasons.
colored
Colored threading strategy.
This strategy performs a coloring of the mesh elements, so that any two adjacent elements have different colors. By construction, no race conditions can appear when elements of a single color are processed in parallel. Therefore, the assembly processes all colors sequentially, where all elements of a single color are processed in parallel by multiple threads.
Example:
Consider the following 5x5 square mesh, then the elements could be partitioned into the four colors R, G, B and W.
+---+---+---+---+---+
| R | G | R | G | R |
+---+---+---+---+---+
| B | W | B | W | B |
+---+---+---+---+---+
| R | G | R | G | R |
+---+---+---+---+---+
| B | W | B | W | B |
+---+---+---+---+---+
| R | G | R | G | R |
+---+---+---+---+---+
Although this strategy is the more prominent one in the literature, it is usually less efficient than the layered strategy due to higher synchronization costs and less favorable memory access patterns.
Definition at line 31 of file domain_assembler.hpp.
Function Documentation
assemble_bilinear_operator_matrix_1()
template<typename Trafo_ , typename Matrix_ , typename BilOp_ , typename Space_ > void FEAT::Assembly::assemble_bilinear_operator_matrix_1 (DomainAssembler< Trafo_ > & dom_asm, Matrix_ & matrix, const BilOp_ & bilinear_operator, const Space_ & space, const String & cubature, const typename Matrix_::DataType alpha = typename Matrix_::DataType(1))
Assembles a bilinear operator into a matrix with identical test- and trial-spaces.
Parameters
[in,out] dom_asm A transient reference to the domain assembler that is to be used for the assembly.
[in,out] matrix The transient matrix that is to be assembled.
[in] bilinear_operator A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] space A transient reference to the finite-element to be used as the test- and trial-space.
[in] cubature The name of the cubature rule that is to be used for the assembly.
[in] alpha The scaling factor for the assembly.
Definition at line 41 of file domain_assembler_helpers.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::assemble(), FEAT::Assembly::DomainAssembler< Trafo_ >::get_trafo(), and XASSERTM.
assemble_bilinear_operator_matrix_2()
template<typename Trafo_ , typename Matrix_ , typename BilOp_ , typename TestSpace_ , typename TrialSpace_ > void FEAT::Assembly::assemble_bilinear_operator_matrix_2 (DomainAssembler< Trafo_ > & dom_asm, Matrix_ & matrix, const BilOp_ & bilinear_operator, const TestSpace_ & test_space, const TrialSpace_ & trial_space, const String & cubature, const typename Matrix_::DataType alpha = typename Matrix_::DataType(1))
Assembles a bilinear operator into a matrix with different test- and trial-spaces.
Parameters
[in,out] dom_asm A transient reference to the domain assembler that is to be used for the assembly.
[in,out] matrix The transient matrix that is to be assembled.
[in] bilinear_operator A transient reference to the operator implementing the BilinearOperator interface to be assembled.
[in] test_space A transient reference to the finite-element test-space to be used.
[in] trial_space A transient reference to the finite-element trial-space to be used.
[in] cubature The name of the cubature rule that is to be used for the assembly.
[in] alpha The scaling factor for the assembly.
Definition at line 79 of file domain_assembler_helpers.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::assemble(), FEAT::Assembly::DomainAssembler< Trafo_ >::get_trafo(), and XASSERTM.
Referenced by FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_grad_div_matrices().
assemble_force_function_vector()
template<typename Trafo_ , typename Vector_ , typename Function_ , typename Space_ > void FEAT::Assembly::assemble_force_function_vector (DomainAssembler< Trafo_ > & dom_asm, Vector_ & vector, const Function_ & function, const Space_ & space, const String & cubature, const typename Vector_::DataType alpha = typename Vector_::DataType(1))
Assembles a force function into a vector.
Parameters
[in,out] dom_asm A transient reference to the domain assembler that is to be used for the assembly.
[in,out] vector The transient vector that is to be assembled.
[in] function A transient reference to the force function implementing the Analytic::Function interface to be assembled.
[in] space A transient reference to the finite-element to be used as the test-space.
[in] cubature The name of the cubature rule that is to be used for the assembly.
[in] alpha The scaling factor for the assembly.
Definition at line 150 of file domain_assembler_helpers.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::assemble(), FEAT::Assembly::DomainAssembler< Trafo_ >::get_trafo(), and XASSERTM.
assemble_linear_functional_vector()
template<typename Trafo_ , typename Vector_ , typename LinFunc_ , typename Space_ > void FEAT::Assembly::assemble_linear_functional_vector (DomainAssembler< Trafo_ > & dom_asm, Vector_ & vector, const LinFunc_ & linear_functional, const Space_ & space, const String & cubature, const typename Vector_::DataType alpha = typename Vector_::DataType(1))
Assembles a linear functional into a vector.
Parameters
[in,out] dom_asm A transient reference to the domain assembler that is to be used for the assembly.
[in,out] vector The transient vector that is to be assembled.
[in] linear_functional A transient reference to the functional implementing the Assembly::LinearFunctional interface to be assembled.
[in] space A transient reference to the finite-element to be used as the test-space.
[in] cubature The name of the cubature rule that is to be used for the assembly.
[in] alpha The scaling factor for the assembly.
Definition at line 116 of file domain_assembler_helpers.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::assemble(), FEAT::Assembly::DomainAssembler< Trafo_ >::get_trafo(), and XASSERTM.
integrate_analytic_function()
template<int max_der_, typename DataType_ , typename Trafo_ , typename Function_ > AnalyticFunctionIntegral< DataType_, Function_ >::Type FEAT::Assembly::integrate_analytic_function (DomainAssembler< Trafo_ > & dom_asm, const Function_ & function, const String & cubature)
Assembles the integral of an analytic function.
Template Parameters
DataType_ The (scalar) datatype in which the assembly is to be performed. Must always be given.
Parameters
[in,out] dom_asm A transient reference to the domain assembler that is to be used for the assembly.
[in] function A transient reference to the analytic function that is to be integrated.
[in] cubature The name of the cubature rule that is to be used for the assembly.
Returns
The integrals of the input function stored in an Assembly::FunctionIntegralInfo instance, whose exact type is determined by the Assembly::AnalyticFunctionIntegral helper class.
Definition at line 182 of file domain_assembler_helpers.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::assemble(), FEAT::Assembly::DomainAssembler< Trafo_ >::get_trafo(), and FEAT::Assembly::AnalyticFunctionIntegralJob< DataType_, Function_, Trafo_, max_der_ >::result().
integrate_discrete_function()
template<int max_der_, typename Vector_ , typename Trafo_ , typename Space_ > DiscreteFunctionIntegral< Vector_, Space_ >::Type FEAT::Assembly::integrate_discrete_function (DomainAssembler< Trafo_ > & dom_asm, const Vector_ & vector, const Space_ & space, const String & cubature)
Assembles the integral of a discrete finite element function.
Parameters
[in,out] dom_asm A transient reference to the domain assembler that is to be used for the assembly.
[in] vector A transient reference to the coefficient vector of the finite element function that is to be integrated.
[in] space A transient reference to the finite element space that the coefficient vector belongs to.
[in] cubature The name of the cubature rule that is to be used for the assembly.
Returns
The integrals of the input function stored in an Assembly::FunctionIntegralInfo instance, whose exact type is determined by the Assembly::DiscreteFunctionIntegral helper class.
Definition at line 210 of file domain_assembler_helpers.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::assemble(), FEAT::Assembly::DomainAssembler< Trafo_ >::get_trafo(), and XASSERTM.
integrate_error_function()
template<int max_der_, typename Function_ , typename Vector_ , typename Trafo_ , typename Space_ > DiscreteFunctionIntegral< Vector_, Space_ >::Type FEAT::Assembly::integrate_error_function (DomainAssembler< Trafo_ > & dom_asm, const Function_ & function, const Vector_ & vector, const Space_ & space, const String & cubature)
Assembles the integral of an (analytic - discrete) error function.
Parameters
[in,out] dom_asm A transient reference to the domain assembler that is to be used for the assembly.
[in] function A transient reference to the analytic function that is to be integrated.
[in] vector A transient reference to the coefficient vector of the finite element function that is to be integrated.
[in] space A transient reference to the finite element space that the coefficient vector belongs to.
[in] cubature The name of the cubature rule that is to be used for the assembly.
Returns
The integrals of the error function stored in an Assembly::FunctionIntegralInfo instance, whose exact type is determined by the Assembly::DiscreteFunctionIntegral helper class.
Definition at line 243 of file domain_assembler_helpers.hpp.
References FEAT::Assembly::DomainAssembler< Trafo_ >::assemble(), FEAT::Assembly::DomainAssembler< Trafo_ >::get_trafo(), and XASSERTM.