var namespace_f_e_a_t_1_1_assembly =
[
    [ "Common", "namespace_f_e_a_t_1_1_assembly_1_1_common.html", "namespace_f_e_a_t_1_1_assembly_1_1_common" ],
    [ "AnalyticCellProjector", "class_f_e_a_t_1_1_assembly_1_1_analytic_cell_projector.html", "class_f_e_a_t_1_1_assembly_1_1_analytic_cell_projector" ],
    [ "AnalyticFunctionIntegral", "struct_f_e_a_t_1_1_assembly_1_1_analytic_function_integral.html", "struct_f_e_a_t_1_1_assembly_1_1_analytic_function_integral" ],
    [ "AnalyticFunctionIntegralJob", "class_f_e_a_t_1_1_assembly_1_1_analytic_function_integral_job.html", "class_f_e_a_t_1_1_assembly_1_1_analytic_function_integral_job" ],
    [ "AnalyticVertexProjector", "class_f_e_a_t_1_1_assembly_1_1_analytic_vertex_projector.html", "class_f_e_a_t_1_1_assembly_1_1_analytic_vertex_projector" ],
    [ "AsmTraits1", "class_f_e_a_t_1_1_assembly_1_1_asm_traits1.html", "class_f_e_a_t_1_1_assembly_1_1_asm_traits1" ],
    [ "AsmTraits2", "class_f_e_a_t_1_1_assembly_1_1_asm_traits2.html", "class_f_e_a_t_1_1_assembly_1_1_asm_traits2" ],
    [ "AsmTraits3", "class_f_e_a_t_1_1_assembly_1_1_asm_traits3.html", "class_f_e_a_t_1_1_assembly_1_1_asm_traits3" ],
    [ "BasicMatrixAssemblyTaskCRTP1", "class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p1.html", "class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p1" ],
    [ "BasicMatrixAssemblyTaskCRTP2", "class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p2.html", "class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p2" ],
    [ "BasicVectorAssemblyTaskCRTP", "class_f_e_a_t_1_1_assembly_1_1_basic_vector_assembly_task_c_r_t_p.html", "class_f_e_a_t_1_1_assembly_1_1_basic_vector_assembly_task_c_r_t_p" ],
    [ "BilinearOperator", "class_f_e_a_t_1_1_assembly_1_1_bilinear_operator.html", "class_f_e_a_t_1_1_assembly_1_1_bilinear_operator" ],
    [ "BilinearOperatorAssembler", "class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_assembler" ],
    [ "BilinearOperatorMatrixAssemblyJob1", "class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_matrix_assembly_job1.html", "class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_matrix_assembly_job1" ],
    [ "BilinearOperatorMatrixAssemblyJob2", "class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_matrix_assembly_job2.html", "class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_matrix_assembly_job2" ],
    [ "BurgersAssembler", "class_f_e_a_t_1_1_assembly_1_1_burgers_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_assembler" ],
    [ "BurgersAssemblerCarreau", "class_f_e_a_t_1_1_assembly_1_1_burgers_assembler_carreau.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_assembler_carreau" ],
    [ "BurgersAssemblyJobBase", "class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base" ],
    [ "BurgersAssemblyTaskBase", "class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base" ],
    [ "BurgersBlockedAssemblyTaskBase", "class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base" ],
    [ "BurgersBlockedMatrixAssemblyJob", "class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_matrix_assembly_job.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_matrix_assembly_job" ],
    [ "BurgersBlockedVectorAssemblyJob", "class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_vector_assembly_job.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_vector_assembly_job" ],
    [ "BurgersScalarAssemblyTaskBase", "class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base" ],
    [ "BurgersScalarMatrixAssemblyJob", "class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_matrix_assembly_job.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_matrix_assembly_job" ],
    [ "BurgersScalarVectorAssemblyJob", "class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_vector_assembly_job.html", "class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_vector_assembly_job" ],
    [ "CellErrorFunctionIntegralJob", "class_f_e_a_t_1_1_assembly_1_1_cell_error_function_integral_job.html", "class_f_e_a_t_1_1_assembly_1_1_cell_error_function_integral_job" ],
    [ "DiscreteCellProjector", "class_f_e_a_t_1_1_assembly_1_1_discrete_cell_projector.html", "class_f_e_a_t_1_1_assembly_1_1_discrete_cell_projector" ],
    [ "DiscreteEvaluator", "class_f_e_a_t_1_1_assembly_1_1_discrete_evaluator.html", "class_f_e_a_t_1_1_assembly_1_1_discrete_evaluator" ],
    [ "DiscreteFunctionIntegral", "struct_f_e_a_t_1_1_assembly_1_1_discrete_function_integral.html", null ],
    [ "DiscreteFunctionIntegral< LAFEM::DenseVector< DT_, IT_ >, Space_ >", "struct_f_e_a_t_1_1_assembly_1_1_discrete_function_integral_3_01_l_a_f_e_m_1_1_dense_vector_3_01_a768f17c1eda786ac85c0b6fa08eaeae.html", "struct_f_e_a_t_1_1_assembly_1_1_discrete_function_integral_3_01_l_a_f_e_m_1_1_dense_vector_3_01_a768f17c1eda786ac85c0b6fa08eaeae" ],
    [ "DiscreteFunctionIntegral< LAFEM::DenseVectorBlocked< DT_, IT_, bs_ >, Space_ >", "struct_f_e_a_t_1_1_assembly_1_1_discrete_function_integral_3_01_l_a_f_e_m_1_1_dense_vector_block282ab9ff04649d6c90f61fc974e9149f.html", "struct_f_e_a_t_1_1_assembly_1_1_discrete_function_integral_3_01_l_a_f_e_m_1_1_dense_vector_block282ab9ff04649d6c90f61fc974e9149f" ],
    [ "DiscreteFunctionIntegralJob", "class_f_e_a_t_1_1_assembly_1_1_discrete_function_integral_job.html", "class_f_e_a_t_1_1_assembly_1_1_discrete_function_integral_job" ],
    [ "DiscreteVertexProjector", "class_f_e_a_t_1_1_assembly_1_1_discrete_vertex_projector.html", "class_f_e_a_t_1_1_assembly_1_1_discrete_vertex_projector" ],
    [ "DomainAssembler", "class_f_e_a_t_1_1_assembly_1_1_domain_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_domain_assembler" ],
    [ "DomainAssemblyJob", "class_f_e_a_t_1_1_assembly_1_1_domain_assembly_job.html", "class_f_e_a_t_1_1_assembly_1_1_domain_assembly_job" ],
    [ "ErrorFunctionIntegralJob", "class_f_e_a_t_1_1_assembly_1_1_error_function_integral_job.html", "class_f_e_a_t_1_1_assembly_1_1_error_function_integral_job" ],
    [ "FEInterpolator", "struct_f_e_a_t_1_1_assembly_1_1_f_e_interpolator.html", null ],
    [ "FEInterpolator< Space::Lagrange1::Element< Trafo_ >, Space::Lagrange2::Element< Trafo_ > >", "struct_f_e_a_t_1_1_assembly_1_1_f_e_interpolator_3_01_space_1_1_lagrange1_1_1_element_3_01_trafo88bd382a0f92c8baea41863ea8ff4cff.html", "struct_f_e_a_t_1_1_assembly_1_1_f_e_interpolator_3_01_space_1_1_lagrange1_1_1_element_3_01_trafo88bd382a0f92c8baea41863ea8ff4cff" ],
    [ "FEInterpolator< Space::Lagrange2::Element< Trafo_ >, Space::Lagrange1::Element< Trafo_ > >", "struct_f_e_a_t_1_1_assembly_1_1_f_e_interpolator_3_01_space_1_1_lagrange2_1_1_element_3_01_trafoaad41beedc2a09129705ed54a155ebb0.html", "struct_f_e_a_t_1_1_assembly_1_1_f_e_interpolator_3_01_space_1_1_lagrange2_1_1_element_3_01_trafoaad41beedc2a09129705ed54a155ebb0" ],
    [ "FEInterpolator< Space_, Space_ >", "struct_f_e_a_t_1_1_assembly_1_1_f_e_interpolator_3_01_space___00_01_space___01_4.html", "struct_f_e_a_t_1_1_assembly_1_1_f_e_interpolator_3_01_space___00_01_space___01_4" ],
    [ "ForceFunctionalAssemblyJob", "class_f_e_a_t_1_1_assembly_1_1_force_functional_assembly_job.html", "class_f_e_a_t_1_1_assembly_1_1_force_functional_assembly_job" ],
    [ "FunctionCellIntegralInfo", "class_f_e_a_t_1_1_assembly_1_1_function_cell_integral_info.html", null ],
    [ "FunctionIntegralInfo", "class_f_e_a_t_1_1_assembly_1_1_function_integral_info.html", "class_f_e_a_t_1_1_assembly_1_1_function_integral_info" ],
    [ "GradOperatorAssembler", "class_f_e_a_t_1_1_assembly_1_1_grad_operator_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_grad_operator_assembler" ],
    [ "GradPresDivVeloAssembler", "class_f_e_a_t_1_1_assembly_1_1_grad_pres_div_velo_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_grad_pres_div_velo_assembler" ],
    [ "GridTransfer", "class_f_e_a_t_1_1_assembly_1_1_grid_transfer.html", "class_f_e_a_t_1_1_assembly_1_1_grid_transfer" ],
    [ "Interpolator", "class_f_e_a_t_1_1_assembly_1_1_interpolator.html", "class_f_e_a_t_1_1_assembly_1_1_interpolator" ],
    [ "Lagrange1To2DofAtEntity", "struct_f_e_a_t_1_1_assembly_1_1_lagrange1_to2_dof_at_entity.html", "struct_f_e_a_t_1_1_assembly_1_1_lagrange1_to2_dof_at_entity" ],
    [ "Lagrange1To2DofAtEntity< Trafo_, 0 >", "struct_f_e_a_t_1_1_assembly_1_1_lagrange1_to2_dof_at_entity_3_01_trafo___00_010_01_4.html", "struct_f_e_a_t_1_1_assembly_1_1_lagrange1_to2_dof_at_entity_3_01_trafo___00_010_01_4" ],
    [ "LinearFunctional", "class_f_e_a_t_1_1_assembly_1_1_linear_functional.html", "class_f_e_a_t_1_1_assembly_1_1_linear_functional" ],
    [ "LinearFunctionalAssembler", "class_f_e_a_t_1_1_assembly_1_1_linear_functional_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_linear_functional_assembler" ],
    [ "LinearFunctionalAssemblyJob", "class_f_e_a_t_1_1_assembly_1_1_linear_functional_assembly_job.html", "class_f_e_a_t_1_1_assembly_1_1_linear_functional_assembly_job" ],
    [ "MatrixDiscreteEvalData", "class_f_e_a_t_1_1_assembly_1_1_matrix_discrete_eval_data.html", "class_f_e_a_t_1_1_assembly_1_1_matrix_discrete_eval_data" ],
    [ "MeanFilterAssembler", "class_f_e_a_t_1_1_assembly_1_1_mean_filter_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_mean_filter_assembler" ],
    [ "MirrorAssembler", "class_f_e_a_t_1_1_assembly_1_1_mirror_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_mirror_assembler" ],
    [ "OldroydAssembler", "class_f_e_a_t_1_1_assembly_1_1_oldroyd_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_oldroyd_assembler" ],
    [ "OuterNormalComputer", "class_f_e_a_t_1_1_assembly_1_1_outer_normal_computer.html", "class_f_e_a_t_1_1_assembly_1_1_outer_normal_computer" ],
    [ "RewProjector", "class_f_e_a_t_1_1_assembly_1_1_rew_projector.html", "class_f_e_a_t_1_1_assembly_1_1_rew_projector" ],
    [ "ScalarDiscreteEvalData", "class_f_e_a_t_1_1_assembly_1_1_scalar_discrete_eval_data.html", "class_f_e_a_t_1_1_assembly_1_1_scalar_discrete_eval_data" ],
    [ "ScalarErrorComputer", "class_f_e_a_t_1_1_assembly_1_1_scalar_error_computer.html", "class_f_e_a_t_1_1_assembly_1_1_scalar_error_computer" ],
    [ "ScalarErrorInfo", "struct_f_e_a_t_1_1_assembly_1_1_scalar_error_info.html", "struct_f_e_a_t_1_1_assembly_1_1_scalar_error_info" ],
    [ "SlipFilterAssembler", "class_f_e_a_t_1_1_assembly_1_1_slip_filter_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_slip_filter_assembler" ],
    [ "SpaceTransfer", "class_f_e_a_t_1_1_assembly_1_1_space_transfer.html", "class_f_e_a_t_1_1_assembly_1_1_space_transfer" ],
    [ "StokesFBMAssembler", "class_f_e_a_t_1_1_assembly_1_1_stokes_f_b_m_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_stokes_f_b_m_assembler" ],
    [ "SymbolicAssembler", "class_f_e_a_t_1_1_assembly_1_1_symbolic_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_symbolic_assembler" ],
    [ "TraceAssembler", "class_f_e_a_t_1_1_assembly_1_1_trace_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_trace_assembler" ],
    [ "UnitFilterAssembler", "class_f_e_a_t_1_1_assembly_1_1_unit_filter_assembler.html", "class_f_e_a_t_1_1_assembly_1_1_unit_filter_assembler" ],
    [ "VectorDiscreteEvalData", "class_f_e_a_t_1_1_assembly_1_1_vector_discrete_eval_data.html", "class_f_e_a_t_1_1_assembly_1_1_vector_discrete_eval_data" ],
    [ "VectorErrorComputer", "class_f_e_a_t_1_1_assembly_1_1_vector_error_computer.html", "class_f_e_a_t_1_1_assembly_1_1_vector_error_computer" ],
    [ "VectorErrorInfo", "struct_f_e_a_t_1_1_assembly_1_1_vector_error_info.html", "struct_f_e_a_t_1_1_assembly_1_1_vector_error_info" ],
    [ "VelocityAnalyser", "class_f_e_a_t_1_1_assembly_1_1_velocity_analyser.html", "class_f_e_a_t_1_1_assembly_1_1_velocity_analyser" ],
    [ "VelocityInfo", "struct_f_e_a_t_1_1_assembly_1_1_velocity_info.html", "struct_f_e_a_t_1_1_assembly_1_1_velocity_info" ],
    [ "ThreadingStrategy", "namespace_f_e_a_t_1_1_assembly.html#a28186a335b7da11c0a4a2a3770462bf0", [
      [ "automatic", "namespace_f_e_a_t_1_1_assembly.html#a28186a335b7da11c0a4a2a3770462bf0a2bd9c0ed00116be1258e0cc66617d7c8", null ],
      [ "single", "namespace_f_e_a_t_1_1_assembly.html#a28186a335b7da11c0a4a2a3770462bf0add5c07036f2975ff4bce568b6511d3bc", null ],
      [ "layered", "namespace_f_e_a_t_1_1_assembly.html#a28186a335b7da11c0a4a2a3770462bf0a9442e6482c63def4c35bc13b704c52e2", null ],
      [ "layered_sorted", "namespace_f_e_a_t_1_1_assembly.html#a28186a335b7da11c0a4a2a3770462bf0a3c5097fb5c0edb92db17a1740f6ae4bf", null ],
      [ "colored", "namespace_f_e_a_t_1_1_assembly.html#a28186a335b7da11c0a4a2a3770462bf0a028f0749e1b6a005abdfb9a3975d8c32", null ]
    ] ],
    [ "assemble_bilinear_operator_matrix_1", "namespace_f_e_a_t_1_1_assembly.html#a5c8d5a032923d79c0ce5a9d944a0f6b5", null ],
    [ "assemble_bilinear_operator_matrix_2", "namespace_f_e_a_t_1_1_assembly.html#a2fb985922ac6e3fa04313f1abfd0bc20", null ],
    [ "assemble_force_function_vector", "namespace_f_e_a_t_1_1_assembly.html#a105b50bbb2cca05a2fadb234d099560a", null ],
    [ "assemble_linear_functional_vector", "namespace_f_e_a_t_1_1_assembly.html#a191b225af4bb871d1a4637527833a05e", null ],
    [ "integrate_analytic_function", "namespace_f_e_a_t_1_1_assembly.html#a4d6f3cbc2e767ac015f0e462d6767814", null ],
    [ "integrate_discrete_function", "namespace_f_e_a_t_1_1_assembly.html#aee74214fac60a1a3fd710118dcc03fd3", null ],
    [ "integrate_error_function", "namespace_f_e_a_t_1_1_assembly.html#a607bf7ab2c6e0a5e34522fc62f831709", null ]
];