FEAT: FEAT Namespace Reference
FEAT Namespace Reference
FEAT namespace.
Namespaces
namespace Adjacency
Adjacency namespace.
namespace Analytic
Analytic namespace.
namespace Assembly
Assembly namespace.
namespace Cubature
Cubature namespace.
namespace Dist
Distributed Communication namespace.
namespace Geometry
Geometry namespace.
namespace Global
Global linear algebra namespace.
namespace LAFEM
LAFEM namespace.
namespace Math
FEAT Math namespace.
namespace Meshopt
Namespace for everything mesh optimizer related.
namespace MetaMath
Template Meta-Program Math namespace.
namespace Pack
Data Array Pack namespace.
namespace Shape
Shape namespace.
namespace Solver
Solver namespace.
namespace Space
Finite Element Space namespace.
namespace TestSystem
TestSystem namespace.
namespace Tiny
Tiny namespace.
namespace Trafo
Transformation namespace.
namespace Type
Type namespace.
namespace VoxelAssembly
Namespace for different voxel based assembly methods.
namespace VoxelAssemblyPolicies
Provides different policies for the voxel assembly kernels.
namespace Windows
Windows OS utility namespace.
namespace Xml
Xml namespace.
Classes
class Backend
Backend support class.
class BinaryStream
Binary Stream class.
class DistFileIO
Distributed File Input/Output class.
class Exception
Base exception class.
class FileError
Base class for file related errors.
class FileNotCreated
File-Not-Created exception.
class FileNotFound
File-Not-Found exception.
class InternalError
exception that is thrown if something that is never supposed to happen happens
struct KahanAccumulation
class MemoryPool
Memory management.
class MemoryUsage
Memory usage info object.
class mutable_priority_queue
class ParseError
Class for parser related errors.
class PropertyMap
A class organizing a tree of key-value pairs.
class Random
Pseudo-Random Number Generator.
class Runtime
FEAT Runtime management class.
class SimpleArgParser
Simple argument parser implementation.
class Statistics
Statistics collection class.
class StopWatch
Stop-Watch class.
class String
String class implementation.
class StringMapped
String-Mapped class template.
class SyntaxError
Syntax Error exception class.
class ThreadFence
Thread fence synchronization utility class.
class TimeStamp
Time stamp class.
Typedefs
typedef __half Half
Half data type.
typedef std::uint64_t Index
Index data type.
typedef double Real
Real data type.
Enumerations
enum class PreferredBackend { generic = 0 , mkl , cuda }
The backend that shall be used in all compute heavy calculations.
enum class SpaceTags {
none = 0 , value = 0x0001 , grad = 0x0002 , hess = 0x0004 ,
ref_value = 0x0008 , ref_grad = 0x0010 , ref_hess = 0x0020
}
Space configuration tags enum.
enum class TimeFormat {
h_m_s_m , h_m_s , m_s_m , m_s ,
s_m
}
enum class TrafoTags {
none = 0 , dom_point = 0x0001 , img_point = 0x0002 , jac_mat = 0x0004 ,
jac_inv = 0x0008 , jac_det = 0x0010 , hess_ten = 0x0020 , hess_inv = 0x0040 ,
normal = 0x0080
}
Trafo configuration tags enum.
Functions
CUDA_HOST_DEVICE void abortion (const char *const func, const char *const file, const int line, const char *const msg)
Abortion function.
CUDA_HOST void abortion (const char *const func, const char *const file, const int line, const std::string &msg)
CUDA_HOST_DEVICE void assertion (bool expr, const char *const expr_str, const char *const func, const char *const file, const int line, const char *const msg=nullptr)
Assertion function.
CUDA_HOST void assertion (bool expr, const char *const expr_str, const char *const func, const char *const file, const int line, const std::string &msg)
KahanAccumulation KahanSum (KahanAccumulation accumulation, double value)
static constexpr SpaceTags operator& (SpaceTags a, SpaceTags b)
Binary AND operator for SpaceTags values.
static constexpr TrafoTags operator& (TrafoTags a, TrafoTags b)
Binary AND operator for TrafoTags values.
static constexpr bool operator* (SpaceTags a)
bool conversion operator
static constexpr bool operator* (TrafoTags a)
bool conversion operator
std::ostream & operator<< (std::ostream &left, PreferredBackend value)
static constexpr SpaceTags operator| (SpaceTags a, SpaceTags b)
Binary OR operator for SpaceTags values.
static constexpr TrafoTags operator| (TrafoTags a, TrafoTags b)
Binary OR operator for TrafoTags values.
template<typename ValueType_ >
StringMapped< ValueType_ > string_mapped (ValueType_ &value, const std::map< String, ValueType_ > &value_map)
Creates a StringMapped object.
template<typename ValueType_ >
bool string_mapped_lookup (ValueType_ &value, const std::map< String, ValueType_ > &value_map, const String &str)
Looks up a StringMapped value.
template<typename T_ >
String stringify (const T_ &item)
Converts an item into a String.
String stringify_bytes (std::uint64_t bytes, int precision=3, int width=7)
Prints a byte size to a string using the common units Bytes, KiB, MiB, Gib, TiB or PiB.
template<typename DataType_ >
String stringify_fp_fix (DataType_ value, int precision=0, int width=0, bool sign=false)
Prints a floating point value to a string in fixed-point notation.
template<typename DataType_ >
String stringify_fp_sci (DataType_ value, int precision=0, int width=0, bool sign=false)
Prints a floating point value to a string in scientific notation.
template<typename Container_ >
String stringify_join (const Container_ &container, const String &delimiter="")
Joins a sequence of strings.
template<typename Iterator_ >
String stringify_join (Iterator_ first, Iterator_ last, const String &delimiter="")
Joins a sequence of strings.
Variables
static constexpr int version_major = 3
FEAT major version number.
static constexpr int version_minor = 0
FEAT minor version number.
static constexpr int version_patch = 0
FEAT patch version number.
Detailed Description
FEAT namespace.
Typedef Documentation
Half
typedef __half FEAT::Half
Half data type.
Half data type derived from nvidias cuda __half data type.
Todo:
add overloads/specializations in math.hpp for this type
Author
Dirk Ribbrock
Definition at line 27 of file half.hpp.
Index
typedef std::uint64_t FEAT::Index
Index data type.
Definition at line 118 of file base_header.hpp.
Real
typedef double FEAT::Real
Real data type.
Definition at line 124 of file base_header.hpp.
Enumeration Type Documentation
PreferredBackend
enum class FEAT::PreferredBackend strong
The backend that shall be used in all compute heavy calculations.
Enumerator
generic
generic c++ code
mkl
intel mkl blas library
cuda
nvidia cuda gpgpu support
Definition at line 125 of file backend.hpp.
SpaceTags
enum class FEAT::SpaceTags strong
Space configuration tags enum.
This enumeration is used to specify the evaluation requirements for space evaluators. For this enumeration, the "binary" AND and OR operators are overloaded, so that the single enumeration values can be combined and masked using these operators.
Enumerator
value
specifies whether the space should supply basis function values
grad
specifies whether the space should supply basis function gradients
hess
specifies whether the space should supply basis function hessians
ref_value
specifies whether the space should supply reference basis function values
ref_grad
specifies whether the space should supply reference basis function gradients
ref_hess
specifies whether the space should supply reference basis function hessians
Definition at line 98 of file eval_tags.hpp.
TimeFormat
enum class FEAT::TimeFormat strong
Supported time string formatting.
Enumerator
h_m_s_m
h:mm:ss.mmm
h_m_s
h:mm:ss
m_s_m
m:ss.mmm
m_s
m:ss
s_m
s.mmm
Definition at line 32 of file time_stamp.hpp.
TrafoTags
enum class FEAT::TrafoTags strong
Trafo configuration tags enum.
This enumeration is used to specify the evaluation requirements for transformation evaluators. For this enumeration, the "binary" AND and OR operators are overloaded, so that the single enumeration values can be combined and masked using these operators.
Enumerator
dom_point
specifies whether the trafo should supply domain point coordinates
img_point
specifies whether the trafo should supply image point coordinates
jac_mat
specifies whether the trafo should supply jacobian matrices
jac_inv
specifies whether the trafo should supply inverse jacobian matrices
jac_det
specifies whether the trafo should supply jacobian determinants
hess_ten
specifies whether the trafo should supply hessian tensors
hess_inv
specifies whether the trafo should supply inverse hessian tensors
normal
specifies whether the trafo should supply outer normal vectors note: The normal vector is always automatically defined by the Assembly::TraceAssembler class and does not have to be specifies explicitly
Definition at line 23 of file eval_tags.hpp.
Function Documentation
abortion() [1/2]
CUDA_HOST_DEVICE void FEAT::abortion (const char *const func, const char *const file, const int line, const char *const msg) inline
Abortion function.
This function implements the actual abortion that is called by the XABORTM macro, which prints an informative error message to stderr and calls Runtime::abort to terminate the process.
Parameters
[in] func The name of the function that contains the abortion, usually func.
[in] file The name of the source/header file that contains the abortion, usually FILE.
[in] line The line number of the abortion in the source/header file, usually LINE.
[in] msg A custom error message to be displayed in addition to the standard information.
Definition at line 40 of file assertion.hpp.
References FEAT::Runtime::abort().
abortion() [2/2]
CUDA_HOST void FEAT::abortion (const char *const func, const char *const file, const int line, const std::string & msg) inline
Definition at line 81 of file assertion.hpp.
assertion() [1/2]
CUDA_HOST_DEVICE void FEAT::assertion (bool expr, const char *const expr_str, const char *const func, const char *const file, const int line, const char *const msg = nullptr) inline
Assertion function.
This function implements the actual assertion that is called by the ASSERT, ASSERTM, XASSERT and XASSERTM macros.
The behavior of this function is as follows:
If expr evaluates to true, then this function does nothing.
If expr evaluates to false, then this function prints an informative error message to stderr and calls Runtime::abort to terminate the process.
Parameters
[in] expr The expression that is asserted.
[in] expr_str The stringified expression, usually #expr.
[in] func The name of the function that contains the assertion, usually func.
[in] file The name of the source/header file that contains the assertion, usually FILE.
[in] line The line number of the assertion in the source/header file, usually LINE.
[in] msg A custom error message to be displayed in addition to the standard information. May be nullptr if no additional information is available for the assertion.
Definition at line 116 of file assertion.hpp.
References FEAT::Runtime::abort().
assertion() [2/2]
CUDA_HOST void FEAT::assertion (bool expr, const char *const expr_str, const char *const func, const char *const file, const int line, const std::string & msg) inline
Definition at line 165 of file assertion.hpp.
KahanSum()
KahanAccumulation FEAT::KahanSum (KahanAccumulation accumulation, double value)
This struct executes the actual Kahan Summation step. See https://en.wikipedia.org/wiki/Kahan_summation_algorithm and https://stackoverflow.com/questions/10330002/sum-of-small-double-numbers-c/10330857#10330857 for details.
Definition at line 10 of file kahan_summation.cpp.
References value.
Referenced by FEAT::Statistics::get_formatted_times().
operator&() [1/2]
static constexpr SpaceTags FEAT::operator& (SpaceTags a, SpaceTags b) inline static constexpr
Binary AND operator for SpaceTags values.
Parameters
[in] a,b The two SpaceTags values that are to be AND'ed.
Returns
The masked tags of a and b.
Definition at line 138 of file eval_tags.hpp.
operator&() [2/2]
static constexpr TrafoTags FEAT::operator& (TrafoTags a, TrafoTags b) inline static constexpr
Binary AND operator for TrafoTags values.
Parameters
[in] a,b The two TrafoTags values that are to be AND'ed.
Returns
The masked tags of a and b.
Definition at line 69 of file eval_tags.hpp.
operator*() [1/2]
static constexpr bool FEAT::operator* (SpaceTags a) inline static constexpr
bool conversion operator
Parameters
[in] a The SpaceTags value that is to be checked.
Returns
false, if a is SpaceTags::none, otherwise true.
Definition at line 152 of file eval_tags.hpp.
operator*() [2/2]
static constexpr bool FEAT::operator* (TrafoTags a) inline static constexpr
bool conversion operator
Parameters
[in] a The TrafoTags value that is to be checked.
Returns
false, if a is TrafoTags::none, otherwise true.
Definition at line 83 of file eval_tags.hpp.
operator<<()
std::ostream & FEAT::operator<< (std::ostream & left, PreferredBackend value)
Definition at line 32 of file backend.cpp.
operator|() [1/2]
static constexpr SpaceTags FEAT::operator| (SpaceTags a, SpaceTags b) inline static constexpr
Binary OR operator for SpaceTags values.
Parameters
[in] a,b The two SpaceTags values that are to be OR'ed.
Returns
The combined tags of a and b.
Definition at line 124 of file eval_tags.hpp.
operator|() [2/2]
static constexpr TrafoTags FEAT::operator| (TrafoTags a, TrafoTags b) inline static constexpr
Binary OR operator for TrafoTags values.
Parameters
[in] a,b The two TrafoTags values that are to be OR'ed.
Returns
The combined tags of a and b.
Definition at line 55 of file eval_tags.hpp.
string_mapped()
template<typename ValueType_ > StringMapped< ValueType_ > FEAT::string_mapped (ValueType_ & value, const std::map< String, ValueType_ > & value_map) inline
Creates a StringMapped object.
Parameters
[in] value A reference to the value to be looked up.
[in] value_map A const reference to the value map to be used for lookup.
Returns
A StringMapped<ValueType_> object.
Definition at line 164 of file string_mapped.hpp.
References value.
Referenced by string_mapped_lookup().
string_mapped_lookup()
template<typename ValueType_ > bool FEAT::string_mapped_lookup (ValueType_ & value, const std::map< String, ValueType_ > & value_map, const String & str) inline
Looks up a StringMapped value.
Parameters
[in] value A reference to the value to be looked up.
[in] value_map A const reference to the value map to be used for lookup.
[in] str The string to be looked up.
Returns
true, if str was found in the value map, otherwise false.
Definition at line 185 of file string_mapped.hpp.
References string_mapped(), and value.
stringify()
template<typename T_ > String FEAT::stringify (const T_ & item) inline
Converts an item into a String.
Template Parameters
T_ The type of the item to be converted.
Parameters
[in] item A transient reference to the item that is to be converted.
Returns
A String representation of the item.
Definition at line 946 of file string.hpp.
Referenced by FEAT::Solver::BiCGStabL< Matrix_, Filter_ >::BiCGStabL(), FEAT::Solver::QPenalty< Functional_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::_deslag_patch_halos(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::DistFileIO::_rankname(), FEAT::Solver::QPenalty< Functional_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_startup(), FEAT::Dist::Comm::allprint(), FEAT::Solver::NLCG< Functional_, Filter_ >::compute_beta(), FEAT::Control::Meshopt::MeshoptControlBase< DomainControl_ >::compute_mesh_quality(), FEAT::Cubature::DriverFactory< Driver_, Shape_, true >::create(), FEAT::Cubature::Scalar::DriverFactory< Driver_, true >::create(), FEAT::Assembly::DomainAssembler< Trafo_ >::dump(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::dump_ancestry(), FEAT::Control::Domain::VoxelDomainControl< DomainLevel_ >::dump_slag_layer_levels(), FEAT::Geometry::VoxelMap::export_to_bmp(), FEAT::Geometry::RootMeshNode< RootMesh_ >::extract_patch(), FEAT::Geometry::PatchPartMap::fill_index_set(), FEAT::Geometry::Atlas::SurfaceMesh< Mesh_ >::find_cell(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_chosen_levels(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::format_desired_levels(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::get_chosen_parti_info(), FEAT::Statistics::get_formatted_flops(), FEAT::MemoryUsage::get_formatted_memory_usage(), FEAT::Statistics::get_formatted_solver_internals(), FEAT::Statistics::get_formatted_times(), FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), FEAT::Solver::Linesearch< Functional_, Filter_ >::get_summary(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::info(), FEAT::Meshopt::ConcentrationFunctionDefault< DT_ >::info(), FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::info(), FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::info(), FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::info(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_pre_sync(), FEAT::Pack::lossy_decode(), FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::name(), FEAT::Geometry::IndexCalculator< Shape_, face_dim_ >::name(), FEAT::Geometry::IndexSet< num_indices_ >::name(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::name(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::name(), FEAT::LAFEM::PowerFullMatrix< SubType_, width_, height_ >::name(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::name(), FEAT::LAFEM::PowerVector< SubType_, count_ >::name(), FEAT::Shape::Simplex< dimension_ >::name(), FEAT::Shape::Hypercube< dimension_ >::name(), FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::name(), FEAT::Analytic::ParsedVectorFunction< dom_dim_, img_dim_ >::parse(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync(), FEAT::Statistics::print_solver_expressions(), FEAT::PropertyMap::read(), FEAT::Geometry::VoxelMap::read(), FEAT::DistFileIO::read_combined(), FEAT::LAFEM::PowerVector< SubType_, count_ >::read_from(), FEAT::Geometry::VoxelMap::render_to_bmp(), FEAT::Control::Time::NvsBdfQ< DT_ >::set_coeffs(), FEAT::Control::Domain::PartiDomainControlBase< DomainLevel_ >::set_desired_levels(), FEAT::Solver::ALGLIBMinCG< Functional_, Filter_ >::set_direction_update(), stringify_bytes(), stringify_join(), FEAT::Geometry::ExportVTK< Mesh_ >::write(), FEAT::LAFEM::TupleDiagMatrix< First_, Rest_ >::write_out_submatrices(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::write_out_submatrices(), FEAT::LAFEM::PowerDiagMatrix< SubType_, blocks_ >::write_out_submatrices(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::write_out_submatrices(), and FEAT::Geometry::ExportVTK< Mesh_ >::write_pvtu().
stringify_bytes()
String FEAT::stringify_bytes (std::uint64_t bytes, int precision = 3, int width = 7) inline
Prints a byte size to a string using the common units Bytes, KiB, MiB, Gib, TiB or PiB.
The output unit is chosen based in the input value bytes in a way, so that there are at most 3 leading digits and for any size >= 1000 bytes, and the output will contain as many digits as were specified by the precision parameter and it will be padded to the right to as many characters as specified by the width parameter excluding the unit postfix. For example, the well-known HD 3.5" floppy disk has a size of 1457664 bytes, which results in an output of " 1.390 MiB", and a standard CD-ROM has a size of 681574400 bytes, which results in an output of "650.000 MiB".
Parameters
[in] bytes The size in bytes that is to be printed
[in] precision The number of decimal places to be printed; defaults to 3.
If set to 0, the default (compiler-dependent) precision will be used.
[in] width The width that is to be used, i.e. the total number of characters to be printed for the number excluding the unit postfix. This defaults to 7, which ensures that output will be properly aligned independent of the number of digits and the selected unit.
If set to 0, the default (compiler-dependent) width will be used.
Returns
A String containing the size in the largest sensible unit for the given size.
Definition at line 1263 of file string.hpp.
References FEAT::String::pad_front(), stringify(), and stringify_fp_fix().
Referenced by FEAT::MemoryUsage::format_peak_physical_usage().
stringify_fp_fix()
template<typename DataType_ > String FEAT::stringify_fp_fix (DataType_ value, int precision = 0, int width = 0, bool sign = false) inline
Prints a floating point value to a string in fixed-point notation.
Template Parameters
DataType_ The data type of the value to be printed. Is silently assumed to be a standard floating-point datatype, i.e. either float, double or long double.
Note
There exists an overload of this function for the __float128 data type if FEAT is configured and build with support for the quadmath library.
Parameters
[in] value The floating-point value that is to be printed.
[in] precision The precision that is to be used, i.e. the number of mantissa digits to be printed.
If set to 0, the default (compiler-dependent) precision will be used.
[in] width The width that is to be used, i.e. the total number of characters to be printed.
If set to 0, the default (compiler-dependent) width will be used.
[in] sign Specifies whether non-negative numbers are to be prefixed by '+'.
Returns
A String containing the value of value in fixed-point notation.
Author
Peter Zajac
Definition at line 1144 of file string.hpp.
References value.
Referenced by FEAT::Global::PMDCDSCMatrix< Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, MirrorV_, MirrorP_ >, Global::Matrix< LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, MirrorV_, MirrorP_ > >::_fmt_time(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Assembly::DomainAssembler< Trafo_ >::dump(), FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), FEAT::StopWatch::percent_of(), and stringify_bytes().
stringify_fp_sci()
template<typename DataType_ > String FEAT::stringify_fp_sci (DataType_ value, int precision = 0, int width = 0, bool sign = false) inline
Prints a floating point value to a string in scientific notation.
Template Parameters
DataType_ The data type of the value to be printed. Is silently assumed to be a standard floating-point datatype, i.e. either float, double or long double.
Note
There exists an overload of this function for the __float128 data type if FEAT is configured and build with support for the quadmath library.
Parameters
[in] value The floating-point value that is to be printed.
[in] precision The precision that is to be used, i.e. the number of mantissa digits to be printed.
If set to 0, the default (compiler-dependent) precision will be used.
[in] width The width that is to be used, i.e. the total number of characters to be printed.
If set to 0, the default (compiler-dependent) width will be used.
[in] sign Specifies whether non-negative numbers are to be prefixed by '+'.
Returns
A String containing the value of value in scientific notation.
Author
Peter Zajac
Definition at line 1090 of file string.hpp.
References value.
Referenced by FEAT::Solver::QPenalty< Functional_ >::_apply_intern(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_check_convergence(), FEAT::Solver::IterativeSolver< Vector_ >::_plot_iter_line(), FEAT::Solver::QPenalty< Functional_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_initial_defect(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::_set_new_defect(), FEAT::Solver::Linesearch< Functional_, Filter_ >::_startup(), FEAT::Assembly::VelocityInfo< DataType_, dim_ >::format_string(), FEAT::Assembly::ScalarErrorInfo< DataType_ >::format_string(), FEAT::Assembly::VectorErrorInfo< DataType_, dim_ >::format_string(), FEAT::Solver::IterativeSolver< Vector_ >::get_summary(), FEAT::Solver::Linesearch< Functional_, Filter_ >::get_summary(), FEAT::Solver::NLOptLS< Functional_, Filter_ >::get_summary(), FEAT::Meshopt::ConcentrationFunctionPowOfDist< DT_ >::info(), FEAT::Meshopt::RumpfFunctionalBase< DataType_ >::info(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::init_pre_sync(), FEAT::Meshopt::HyperelasticityFunctional< DT_, IT_, Trafo_, CellFunctionalType_, RefCellTrafo_ >::prepare_pre_sync(), FEAT::LAFEM::DenseMatrix< DT_, IT_ >::write_out(), FEAT::LAFEM::DenseVector< DT_, IT_ >::write_out(), FEAT::LAFEM::DenseVectorBlocked< DT_, IT_, BlockSize_ >::write_out(), FEAT::LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >::write_out(), FEAT::LAFEM::SparseVector< DT_, IT_ >::write_out(), FEAT::LAFEM::SparseMatrixCSR< DT_, IT_ >::write_out(), and FEAT::Geometry::ExportVTK< Mesh_ >::write_vtu().
stringify_join() [1/2]
template<typename Container_ > String FEAT::stringify_join (const Container_ & container, const String & delimiter = "")
Joins a sequence of strings.
This method joins a sequence of items given by a container, e.g. std::list<double>, separating each item in the container by a delimiter string.
Parameters
[in] container A container representing the item sequence. Each item referenced of the container is converted via the stringify function.
[in] delimiter A string acting as a delimiter.
Returns
A String containing the stringified items.
Definition at line 1052 of file string.hpp.
References stringify_join().
stringify_join() [2/2]
template<typename Iterator_ > String FEAT::stringify_join (Iterator_ first, Iterator_ last, const String & delimiter = "")
Joins a sequence of strings.
This functions joins a sequence of items given by two input iterators, separating them by a delimiter string.
Parameters
[in] first,last Two forward iterators representing the item sequence. Each item referenced by the iterators is converted via the stringify function.
[in] delimiter A string acting as a delimiter.
Returns
A String containing the stringified items.
Definition at line 1019 of file string.hpp.
References FEAT::String::String(), and stringify().
Referenced by stringify_join().
Variable Documentation
version_major
constexpr int FEAT::version_major = 3 static constexpr
FEAT major version number.
Definition at line 106 of file base_header.hpp.
Referenced by FEAT::Runtime::initialize(), FEAT::Space::ExtVtkWriter< Trafo_ >::open(), FEAT::Geometry::ExportVTK< Mesh_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_ >::write_vtu().
version_minor
constexpr int FEAT::version_minor = 0 static constexpr
FEAT minor version number.
Definition at line 108 of file base_header.hpp.
Referenced by FEAT::Runtime::initialize(), FEAT::Space::ExtVtkWriter< Trafo_ >::open(), FEAT::Geometry::ExportVTK< Mesh_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_ >::write_vtu().
version_patch
constexpr int FEAT::version_patch = 0 static constexpr
FEAT patch version number.
Definition at line 110 of file base_header.hpp.
Referenced by FEAT::Runtime::initialize(), FEAT::Space::ExtVtkWriter< Trafo_ >::open(), FEAT::Geometry::ExportVTK< Mesh_ >::write_pvtu(), and FEAT::Geometry::ExportVTK< Mesh_ >::write_vtu().