FEAT: FEAT::Windows Namespace Reference
FEAT::Windows Namespace Reference
Windows OS utility namespace.
Functions
void disable_error_prompts ()
Disables Windows error dialog boxes.
void dump_call_stack (CONTEXT &ctx, FILE *stream)
void dump_call_stack_to_stderr ()
Dumps the call-stack to stderr.
LONG WINAPI FeatWinExceptionFilter (LPEXCEPTION_POINTERS p)
unsigned long get_current_process_id ()
Returns the Windows process ID for the current process.
void install_seh_filter ()
Installs custom Windows Structured-Exception-Handler filter.
void query_memory_usage (unsigned long long &work_set_size, unsigned long long &work_set_size_peak, unsigned long long &page_file_usage, unsigned long long &page_file_usage_peak)
Queries memory usage information.
long long query_performance_counter ()
Wraps around the QueryPerformanceCounter function.
long long query_performance_frequency ()
Wraps around the QueryPerformanceCounter function.
Detailed Description
Windows OS utility namespace.
This namespace encapsulates a set of functions which are wrapped from the Win32 API, and provides some additional functions for debugging and profiling.
Function Documentation
disable_error_prompts()
void FEAT::Windows::disable_error_prompts ()
Disables Windows error dialog boxes.
This functions disables the Popup-Dialog-Boxes when an application crashes.
Note
This function is called by the automated regression test system.
Author
Peter Zajac
Definition at line 212 of file os_windows.cpp.
Referenced by FEAT::Runtime::initialize().
dump_call_stack()
void FEAT::Windows::dump_call_stack (CONTEXT & ctx, FILE * stream)
Definition at line 61 of file os_windows.cpp.
dump_call_stack_to_stderr()
void FEAT::Windows::dump_call_stack_to_stderr ()
Dumps the call-stack to stderr.
Author
Peter Zajac
Definition at line 150 of file os_windows.cpp.
Referenced by FEAT::Runtime::abort().
FeatWinExceptionFilter()
LONG WINAPI FEAT::Windows::FeatWinExceptionFilter (LPEXCEPTION_POINTERS p)
Definition at line 160 of file os_windows.cpp.
get_current_process_id()
unsigned long FEAT::Windows::get_current_process_id ()
Returns the Windows process ID for the current process.
Author
Peter Zajac
Definition at line 220 of file os_windows.cpp.
Referenced by FEAT::Runtime::initialize().
install_seh_filter()
void FEAT::Windows::install_seh_filter ()
Installs custom Windows Structured-Exception-Handler filter.
This function installs a handler for the Windows SEH system, which prints an error message and a call-stack dump to stderr.
Note
This function is called by the automated regression test system.
Author
Peter Zajac
Definition at line 206 of file os_windows.cpp.
Referenced by FEAT::Runtime::initialize().
query_memory_usage()
void FEAT::Windows::query_memory_usage (unsigned long long & work_set_size, unsigned long long & work_set_size_peak, unsigned long long & page_file_usage, unsigned long long & page_file_usage_peak)
Queries memory usage information.
See also
https://msdn.microsoft.com/en-us/library/windows/desktop/aa965225.aspx
Note
This function is used by the MemoryUsage class.
Author
Peter Zajac
Definition at line 39 of file os_windows.cpp.
Referenced by FEAT::MemoryUsage::stamp().
query_performance_counter()
long long FEAT::Windows::query_performance_counter ()
Wraps around the QueryPerformanceCounter function.
See also
https://msdn.microsoft.com/en-us/library/windows/desktop/ms644904.aspx
Note
This function is used by the TimeStamp class.
Author
Peter Zajac
Definition at line 23 of file os_windows.cpp.
Referenced by FEAT::TimeStamp::stamp().
query_performance_frequency()
long long FEAT::Windows::query_performance_frequency ()
Wraps around the QueryPerformanceCounter function.
See also
https://msdn.microsoft.com/en-us/library/windows/desktop/ms644905.aspx
Note
This function is used by the TimeStamp class.
Author
Peter Zajac
Definition at line 31 of file os_windows.cpp.
Referenced by FEAT::TimeStamp::elapsed(), and FEAT::TimeStamp::elapsed_micros().