FEAT: FEAT::Solver Namespace Reference
FEAT::Solver Namespace Reference
Solver namespace.
Classes
class ADPSolverBase
Base-Class for Solvers based on Algebraic-DOF-Partitioning.
class ADPSolverBase< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, GlobalFilter_, SolverBase_ >
Implementation of ADPSolverBase interface for Global::Matrix instances.
class ADPSolverBase< Global::PMDCDSCMatrix< MatrixB_, MatrixD_ >, GlobalFilter_, SolverBase_ >
Implementation of ADPSolverBase interface for Global::PMDCDSCMatrix instances.
class ALGLIBMinCG
Wrapper around ALGLIB's mincg implementation for minimising an functional's gradient.
class ALGLIBMinLBFGS
Wrapper around ALGLIB's lBFGS implementation for minimising an functional's gradient.
class AmaVanka
Additive Macro-wise Matrix-based Vanka preconditioner/smoother.
class AnalyticFunctionOperator
Wrapper class defining an operator based on a scalar AnalyticFunction.
class ApproximateHessianPrecond
Wrapper class for applying an the inverse of an operator's approximate Hessian as a preconditioner.
class BiCGStab
(Preconditioned) Bi-Conjugate Gradient Stabilized solver implementation
class BiCGStabL
(Preconditioned) BiCGStab(l) solver implementation
class BoomerAMG
HYPRE BoomerAMGWrapper class template.
class Chebyshev
Chebyshev Polynomial implementation.
class ConvertPrecond
Solver conversion module.
class ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >
Convert preconditioner specialization for Global::Vector.
class CuSolverLU
CuSolverLU solver class.
class CuSolverQR
CuSolverQR solver class.
class DiagonalPrecond
Diagonal preconditioner implementation.
class DirectStokesCore
Core class for conversion of Stokes systems to CSR format for direct solvers.
class DirectStokesCore< SolverDT_, SolverIT_, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ >, LAFEM::SparseMatrixCSR< DT_, IT_ > >
Core class for conversion of BCSR Stokes systems to CSR format for direct solvers.
class DirectStokesSolver
Direct Stokes solver class template.
class DirectStokesSolver< Global::Matrix< LocalMatrix_, Mirror_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >
Direct Stokes solver class for SaddlePointMatrix systems.
class DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >
Direct Stokes solver class for SaddlePointMatrix systems.
class EuclidPrecond
HYPRE Euclid Preconditioner Wrapper class template.
class ExpressionBase
class ExpressionCallCoarseSolver
class ExpressionCallPrecond
class ExpressionCallPrecondL
class ExpressionCallPrecondR
class ExpressionCallSmoother
class ExpressionCallUzawaA
class ExpressionCallUzawaS
class ExpressionDefect
class ExpressionEndSolve
class ExpressionLevelTimings
class ExpressionProlongation
class ExpressionRestriction
class ExpressionStartSolve
class ExpressionTimings
class FGMRES
FGMRES(k) solver implementation.
class FixedStepLinesearch
Fixed step line search.
class GenericUmfpack
Generic UMFPACK solver class.
class GroppPCG
(Preconditioned) pipelined Conjugate-Gradient solver implementation from Bill Gropp
class HessianPrecond
Preconditioner that applies the inverse of an operator's Hessian.
class HypreSolverBase
Base-Class for solvers/preconditioners borrowed from HYPRE library.
class IDRS
IDR(s) solver implementation.
class ILUPrecond
ILU(0) and ILU(p) preconditioner implementation.
class ILUPrecondBase
Inheritances inside ilu_precond.hpp.
class ILUPrecondWithBackend
ILU(0) and ILU(p) preconditioner internal implementation.
class ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, Filter_ >
ILU(p) specialization for SparseMatrixBCSR<...>
class ILUPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >
ILU(p) specialization for SparseMatrixCSR.
class InvalidMatrixStructureException
Invalid Matrix structure exception.
class IterationStats
Helper class for iteration statistics collection.
class IterativeSolver
Abstract base-class for iterative solvers.
class JacobiPrecond
Jacobi preconditioner implementation.
class Linesearch
Linesearch base class.
class MatrixPrecond
Matrix preconditioner implementation.
class MQCLinesearch
Mixed quadratic-cubic line search.
class MultiGrid
Multigrid preconditioner implementation.
class MultiGridHierarchy
Multigrid hierarchy management class template.
class MultiGridLevelBase
Multigrid level base class.
class MultiGridLevelStd
Standard Multigrid level class implementation.
class NewtonRaphsonLinesearch
Newton Raphson linesearch.
class NLCG
Nonlinear Conjugate Gradient method for finding a minimum of an functional's gradient.
class NLOptLS
Base class for line search based nonlinear optimizers.
class NLOptPrecond
Abstract base class for preconditioners for nonlinear optimization.
class NLSD
Nonlinear Steepest Descent method for finding a minimum of an functional's gradient.
class NonlinearOperatorPrecondWrapper
Wrapper class around a (potentially nonlinear) operator.
struct OptimizationTestTraits
Class holding additional information about certain AnalyticFunction used for optimization tests.
class ParaSailsPrecond
HYPRE ParaSails Preconditioner Wrapper class template.
class PCG
(Preconditioned) Conjugate-Gradient solver implementation
class PCGNR
(Preconditioned) Conjugate-Gradient on Normal Equations solver implementation
class PCGNRILU
ILU(p)-preconditioned Conjugate-Gradient on Normal Equations solver implementation.
class PCR
(Preconditioned) Conjugate-Residual solver implementation
class PipePCG
(Preconditioned) pipelined Conjugate-Gradient solver implementation from Ghysels and Vnaroose
class PMR
(Preconditioned) Minimal-Residual-Iteration solver implementation
class PolynomialPrecond
Polynomial preconditioner implementation.
class PreconditionedIterativeSolver
Abstract base-class for preconditioned iterative solvers.
class PreconWrapper
Provisional Legacy Preconditioners Wrapper class template.
class PSD
(Preconditioned) Steepest-Descent solver implementation
class QPenalty
Quadratic penalty iteration.
class RBiCGStab
(Preconditioned) reordered BiCGStab solver implementation
class RGCR
(Preconditioned) Recycling Generalized Conjugate Residual solver implementation
class Richardson
(Preconditioned) Richardson solver implementation
class SaddleUmfpackMean
UMFPACK Saddle-Point Mean solver class.
class ScalePrecond
Scaling preconditioner class template.
class SchwarzPrecond
Schwarz preconditioner class template declaration.
class SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >
Schwarz preconditioner specialization for Global::Vector.
class SecantLinesearch
Secant linesearch.
class SingularMatrixException
Singular Matrix exception.
class SolverBase
Polymorphic solver interface.
class SolverException
Base-class for solver generated exceptions.
class SORPrecond
SOR preconditioner implementation.
class SORPrecondBase
Inheritances inside sor_precond.hpp.
class SORPrecondWithBackend
Dummy class for not implemented specializations.
class SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >
class SORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >
SOR preconditioner internal implementation.
class SSORPrecond
SSOR preconditioner implementation.
class SSORPrecondBase
Inheritances inside sor_precond.hpp.
class SSORPrecondWithBackend
Dummy class for not implemented specializations.
class SSORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixBCSR< DT_, IT_, BlockHeight_, BlockWidth_ >, Filter_ >
class SSORPrecondWithBackend< PreferredBackend::generic, LAFEM::SparseMatrixCSR< DT_, IT_ >, Filter_ >
SSOR preconditioner internal implementation.
class SuperLU
(distributed) SuperLU direct sparse solver
class Umfpack
UMFPACK solver class.
class UmfpackMean
UMFPACK Mean solver class.
class UzawaPrecond
Uzawa preconditioner.
class UzawaPrecond< Global::Matrix< MatrixA_, MirrorV_, MirrorV_ >, Global::Matrix< MatrixB_, MirrorV_, MirrorP_ >, Global::Matrix< MatrixD_, MirrorP_, MirrorV_ >, Global::Filter< FilterV_, MirrorV_ >, Global::Filter< FilterP_, MirrorP_ > >
UzawaPrecond specialization for Global matrices.
class Vanka
Vanka preconditioner/smoother class template.
class Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ >
Vanka preconditioner/smoother class template implementation.
class VankaFactorError
Vanka Factorization Error.
class VoxelAmaVanka
Additive Macro-wise Matrix-based Vanka preconditioner/smoother.
Enumerations
enum class BiCGStabLPreconVariant { left , right }
Enum for diffent preconditioning variants for BiCGStabL.
enum class BiCGStabPreconVariant { left , right }
Enum for different preconditioning variants for BiCGStab.
enum class ExpressionType {
start_solve = 0 , end_solve , call_precond , call_precond_l ,
call_precond_r , call_smoother , call_coarse_solver , defect ,
timings , level_timings , prol , rest ,
call_uzawa_s , call_uzawa_a
}
Expression Type enumeration.
enum class MultiGridAdaptCGC { Fixed , MinEnergy , MinDefect }
Multigrid adaptive Coarse-Grid-Correction enumeration.
enum class MultiGridCycle { V , F , W }
Multigrid Cycle enumeration.
enum class NLCGDirectionUpdate {
undefined = 0 , DaiYuan , DYHSHybrid , FletcherReeves ,
HagerZhang , HestenesStiefel , PolakRibiere
}
Enum for NLCG search direction updates.
enum class PlotMode { none = 0 , iter , summary , all }
Solver plot modes enumeration.
enum class Status {
undefined = 0 , progress , success , aborted ,
diverged , max_iter , stagnated
}
Solver status return codes enumeration.
enum class UzawaType { diagonal , lower , upper , full }
Uzawa preconditioner type.
enum class VankaType {
nodal_diag_mult = 0x000 , nodal_full_mult = 0x001 , block_diag_mult = 0x010 , block_full_mult = 0x011 ,
nodal_diag_add = 0x100 , nodal_full_add = 0x101 , block_diag_add = 0x110 , block_full_add = 0x111
}
Vanka type enumeration.
Functions
template<typename Functional_ , typename Filter_ >
std::shared_ptr< ALGLIBMinCG< Functional_, Filter_ > > new_alglib_mincg (const String &section_name, PropertyMap *section, Functional_ &functional_, Filter_ &filter_)
Creates a new ALGLIBMinCG solver object using a PropertyMap.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< ALGLIBMinCG< Functional_, Filter_ > > new_alglib_mincg (Functional_ &functional_, Filter_ &filter_, NLCGDirectionUpdate du_=ALGLIBMinCG< Functional_, Filter_ >::direction_update_default, bool keep_iterates_=false)
Creates a new ALGLIBMinCG solver object.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< ALGLIBMinLBFGS< Functional_, Filter_ > > new_alglib_minlbfgs (const String &section_name, PropertyMap *section, Functional_ &functional_, Filter_ &filter_)
Creates a new ALGLIBMinLBFGS solver object using a PropertyMap.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< ALGLIBMinLBFGS< Functional_, Filter_ > > new_alglib_minlbfgs (Functional_ &functional_, Filter_ &filter_, alglib::ae_int_t lbfgs_dim_=alglib::ae_int_t(0), bool keep_iterates=false)
Creates a new ALGLIBMinLBFGS solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< AmaVanka< Matrix_, Filter_ > > new_amavanka (const Matrix_ &matrix, const Filter_ &filter, typename Matrix_::DataType omega=typename Matrix_::DataType(1), Index num_steps=Index(1))
Creates a new AmaVanka smoother object.
template<typename Operator_ , typename Filter_ >
std::shared_ptr< ApproximateHessianPrecond< Operator_, Filter_ > > new_approximate_hessian_precond (Operator_ &op_, const Filter_ &filter_)
Creates a new ApproximateHessianPrecond.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< BiCGStab< Matrix_, Filter_ > > new_bicgstab (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr, BiCGStabPreconVariant precon_variant=BiCGStabPreconVariant::left)
Creates a new BiCGStab solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< BiCGStab< Matrix_, Filter_ > > new_bicgstab (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new BiCGStab solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< BiCGStabL< Matrix_, Filter_ > > new_bicgstabl (const Matrix_ &matrix, const Filter_ &filter, int l=2, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr, BiCGStabLPreconVariant precon_variant=BiCGStabLPreconVariant::left)
Creates a new BiCGStabL solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< BiCGStabL< Matrix_, Filter_ > > new_bicgstabl (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new BiCGStabL solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< BoomerAMG< Matrix_, Filter_ > > new_boomeramg (const Matrix_ &matrix, const Filter_ &filter)
Creates a new BoomerAMG solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< BoomerAMG< Matrix_, Filter_ > > new_boomeramg (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter)
Creates a new BoomerAMG solver object based on a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< Chebyshev< Matrix_, Filter_ > > new_chebyshev (const Matrix_ &matrix, const Filter_ &filter, const typename Matrix_::DataType fraction_min_ev=typename Matrix_::DataType(0.03), const typename Matrix_::DataType fraction_max_ev=typename Matrix_::DataType(1.1))
Creates a new Chebyshev solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< Chebyshev< Matrix_, Filter_ > > new_chebyshev (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter)
Creates a new Chebyshev solver object using a PropertyMap.
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ >
std::shared_ptr< ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > > > new_convert_precond (std::shared_ptr< SolverBase< Global::Vector< LocalVectorInner_, MirrorInner_ > > > inner_solver)
Creates a new ConvertPrecond solver object.
template<typename VectorOuter_ , typename VectorInner_ >
std::shared_ptr< ConvertPrecond< VectorOuter_, VectorInner_ > > new_convert_precond (std::shared_ptr< SolverBase< VectorInner_ > > inner_solver)
Creates a new ConvertPrecond solver object.
template<typename Vector_ , typename Filter_ >
std::shared_ptr< DiagonalPrecond< Vector_, Filter_ > > new_diagonal_precond (const Vector_ &diag, const Filter_ &filter)
Creates a new DiagonalPrecond solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< DirectStokesSolver< Matrix_, Filter_ > > new_direct_stokes_solver (const Matrix_ &matrix, const Filter_ &filter)
Creates a new DirectStokesSolver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< EuclidPrecond< Matrix_, Filter_ > > new_euclid_precond (const Matrix_ &matrix, const Filter_ &filter)
Creates a new EuclidPrecond solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< EuclidPrecond< Matrix_, Filter_ > > new_euclid_precond (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter)
Creates a new EuclidPrecond solver object based on a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< FGMRES< Matrix_, Filter_ > > new_fgmres (const Matrix_ &matrix, const Filter_ &filter, Index krylov_dim, typename Matrix_::DataType inner_res_scale=typename Matrix_::DataType(0), std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new FGMRES solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< FGMRES< Matrix_, Filter_ > > new_fgmres (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new FGMRES solver object using a PropertyMap.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< FixedStepLinesearch< Functional_, Filter_ > > new_fixed_step_linesearch (const String &section_name, PropertyMap *section, Functional_ &functional, Filter_ &filter)
Creates a new FixedStepLinesearch object using a PropertyMap.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< FixedStepLinesearch< Functional_, Filter_ > > new_fixed_step_linesearch (Functional_ &functional, Filter_ &filter, typename Functional_::DataType step_length, bool keep_iterates=false)
Creates a new FixedStepLinesearch object.
template<typename Matrix_ >
std::shared_ptr< GenericUmfpack< Matrix_ > > new_generic_umfpack (const Matrix_ &matrix)
Creates a new GenericUmfpack solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< GroppPCG< Matrix_, Filter_ > > new_gropppcg (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new GroppPCG solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< GroppPCG< Matrix_, Filter_ > > new_gropppcg (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new GroppPCG solver object using a PropertyMap.
template<typename Operator_ , typename Filter_ >
std::shared_ptr< HessianPrecond< Operator_, Filter_ > > new_hessian_precond (Operator_ &op_, const Filter_ &filter_)
Creates a new HessianPrecond.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< IDRS< Matrix_, Filter_ > > new_idrs (const Matrix_ &matrix, const Filter_ &filter, Index krylov_dim, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new IDR(s) solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< IDRS< Matrix_, Filter_ > > new_idrs (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new IDR(s) solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< ILUPrecond< Matrix_, Filter_ > > new_ilu_precond (const String &section_name, PropertyMap *section, PreferredBackend backend, const Matrix_ &matrix, const Filter_ &filter)
Creates a new ILUPrecond solver object based on a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< ILUPrecond< Matrix_, Filter_ > > new_ilu_precond (PreferredBackend backend, const Matrix_ &matrix, const Filter_ &filter, const int p=0)
Creates a new ILUPrecond solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< JacobiPrecond< Matrix_, Filter_ > > new_jacobi_precond (const Matrix_ &matrix, const Filter_ &filter, const typename Matrix_::DataType omega=typename Matrix_::DataType(1))
Creates a new JacobiPrecond solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< JacobiPrecond< Matrix_, Filter_ > > new_jacobi_precond (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter)
Creates a new JacobiPrecond solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< MatrixPrecond< Matrix_, Filter_ > > new_matrix_precond (const Matrix_ &matrix, const Filter_ &filter)
Creates a new MatrixPrecond solver object.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< MQCLinesearch< Functional_, Filter_ > > new_mqc_linesearch (const String &section_name, PropertyMap *section, Functional_ &functional, Filter_ &filter)
Creates a new MQCLinesearch object using a PropertyMap.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< MQCLinesearch< Functional_, Filter_ > > new_mqc_linesearch (Functional_ &functional, Filter_ &filter, bool keep_iterates=false)
Creates a new MQCLinesearch object.
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ >
std::shared_ptr< MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ > > new_multigrid (std::shared_ptr< MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ > > hierarchy, MultiGridCycle cycle=MultiGridCycle::V, int top_level=0, int crs_level=-1)
Creates a new Multigrid preconditioner object.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< NewtonRaphsonLinesearch< Functional_, Filter_ > > new_newton_raphson_linesearch (const String &section_name, PropertyMap *section, Functional_ &functional, Filter_ &filter)
Creates a new NewtonRaphsonLinesearch object using a PropertyMap.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< NewtonRaphsonLinesearch< Functional_, Filter_ > > new_newton_raphson_linesearch (Functional_ &functional, Filter_ &filter, bool keep_iterates=false)
Creates a new NewtonRaphsonLinesearch object.
template<typename Functional_ , typename Filter_ , typename Linesearch_ >
std::shared_ptr< NLCG< Functional_, Filter_ > > new_nlcg (const String &section_name, PropertyMap *section, Functional_ &functional, Filter_ &filter, Linesearch_ &linesearch, std::shared_ptr< NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > > precond=nullptr)
Creates a new NLCG solver object using a PropertyMap.
template<typename Functional_ , typename Filter_ , typename Linesearch_ >
std::shared_ptr< NLCG< Functional_, Filter_ > > new_nlcg (Functional_ &functional, Filter_ &filter, Linesearch_ &linesearch, NLCGDirectionUpdate direction_update=NLCG< Functional_, Filter_ >::direction_update_default, bool keep_iterates=false, std::shared_ptr< NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > > precond=nullptr)
Creates a new NLCG solver object.
template<typename Functional_ , typename Filter_ , typename Linesearch_ >
std::shared_ptr< NLSD< Functional_, Filter_ > > new_nlsd (const String &section_name, PropertyMap *section, Functional_ &functional, Filter_ &filter, Linesearch_ &linesearch, std::shared_ptr< NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > > precond=nullptr)
Creates a new NLSD solver object using a PropertyMap.
template<typename Functional_ , typename Filter_ , typename Linesearch_ >
std::shared_ptr< NLSD< Functional_, Filter_ > > new_nlsd (Functional_ &functional, Filter_ &filter, Linesearch_ &linesearch, bool keep_iterates=false, std::shared_ptr< NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > > precond=nullptr)
Creates a new NLSD solver object.
template<typename NonlinearOperator_ , typename... Args_>
std::shared_ptr< NonlinearOperatorPrecondWrapper< NonlinearOperator_ > > new_nonlinear_operator_precond_wrapper (Args_ &&... args)
Creates a new NonlinearOperatorPrecondWrapper.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< ParaSailsPrecond< Matrix_, Filter_ > > new_parasails_precond (const Matrix_ &matrix, const Filter_ &filter)
Creates a new ParaSailsPrecond solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< ParaSailsPrecond< Matrix_, Filter_ > > new_parasails_precond (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter)
Creates a new ParaSailsPrecond solver object based on a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PCG< Matrix_, Filter_ > > new_pcg (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PCG solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PCG< Matrix_, Filter_ > > new_pcg (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PCG solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PCGNR< Matrix_, Filter_ > > new_pcgnr (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond_l=nullptr, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond_r=nullptr)
Creates a new PCGNR solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PCGNR< Matrix_, Filter_ > > new_pcgnr (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond_l=nullptr, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond_r=nullptr)
Creates a new PCGNR solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PCGNRILU< Matrix_, Filter_ > > new_pcgnrilu (const Matrix_ &matrix, const Filter_ &filter, int ilu_p=-1)
Creates a new PCGNRILU solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PCGNRILU< Matrix_, Filter_ > > new_pcgnrilu (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter)
Creates a new PCGNRILU solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PCR< Matrix_, Filter_ > > new_pcr (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PCR solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PCR< Matrix_, Filter_ > > new_pcr (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PCR solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PipePCG< Matrix_, Filter_ > > new_pipepcg (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PipePCG solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PipePCG< Matrix_, Filter_ > > new_pipepcg (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PipePCG solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PMR< Matrix_, Filter_ > > new_pmr (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PMR solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PMR< Matrix_, Filter_ > > new_pmr (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PMR solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PolynomialPrecond< Matrix_, Filter_ > > new_polynomial_precond (const Matrix_ &matrix, const Filter_ &filter, const Index m, const typename Matrix_::DataType omega=typename Matrix_::DataType(1))
Creates a new PoynomialPrecond solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PolynomialPrecond< Matrix_, Filter_ > > new_polynomial_precond (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter)
Creates a new PolynomialPrecond solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PSD< Matrix_, Filter_ > > new_psd (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PSD solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< PSD< Matrix_, Filter_ > > new_psd (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new PSD solver object using a PropertyMap.
template<typename Functional_ >
std::shared_ptr< QPenalty< Functional_ > > new_qpenalty (const String &section_name, PropertyMap *section, Functional_ &functional, std::shared_ptr< IterativeSolver< typename Functional_::VectorTypeR > > inner_solver)
Creates a new QPenalty object using a PropertyMap.
template<typename Functional_ >
std::shared_ptr< QPenalty< Functional_ > > new_qpenalty (Functional_ &functional, std::shared_ptr< IterativeSolver< typename Functional_::VectorTypeR > > inner_solver, typename Functional_::VectorTypeR::DataType initial_penalty_param=typename Functional_::VectorTypeR::DataType(1))
Creates a new QPenalty object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< RBiCGStab< Matrix_, Filter_ > > new_rbicgstab (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new RBiCGStab solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< RBiCGStab< Matrix_, Filter_ > > new_rbicgstab (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new RBiCGStab solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< RGCR< Matrix_, Filter_ > > new_rgcr (const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new RGCR solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< RGCR< Matrix_, Filter_ > > new_rgcr (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new RGCR solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< Richardson< Matrix_, Filter_ > > new_richardson (const Matrix_ &matrix, const Filter_ &filter, typename Matrix_::DataType omega=typename Matrix_::DataType(1), std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new Richardson solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< Richardson< Matrix_, Filter_ > > new_richardson (const String &section_name, PropertyMap *section, const Matrix_ &matrix, const Filter_ &filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond=nullptr)
Creates a new Richardson solver object using a PropertyMap.
template<typename DT_ , typename IT_ , int dim_>
std::shared_ptr< SaddleUmfpackMean< DT_, IT_, dim_ > > new_saddle_umfpack_mean (const LAFEM::SaddlePointMatrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ > > &matrix, const LAFEM::DenseVector< DT_, IT_ > &weight_vector)
Creates a new UmfpackMean solver object.
template<typename DT_ , typename IT_ , int dim_>
std::shared_ptr< SaddleUmfpackMean< DT_, IT_, dim_ > > new_saddle_umfpack_mean (const LAFEM::SaddlePointMatrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ > > &matrix, const LAFEM::MeanFilter< DT_, IT_ > &filter)
Creates a new UmfpackMean solver object.
template<typename Filter_ , typename DataType_ >
std::shared_ptr< ScalePrecond< typename Filter_::VectorType, Filter_ > > new_scale_precond (const Filter_ &filter, DataType_ omega)
Creates a new ScalePrecond solver object.
template<typename Filter_ >
std::shared_ptr< ScalePrecond< typename Filter_::VectorType, Filter_ > > new_scale_precond (const String &section_name, PropertyMap *section, const Filter_ &filter)
Creates a new ScalePrecond solver object using a PropertyMap.
template<typename LocalFilter_ , typename Mirror_ >
std::shared_ptr< SchwarzPrecond< Global::Vector< typename LocalFilter_::VectorType, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > > > new_schwarz_precond (const String &section_name, PropertyMap *section, std::shared_ptr< SolverBase< typename LocalFilter_::VectorType > > local_solver, const Global::Filter< LocalFilter_, Mirror_ > &filter)
Creates a new SchwarzPrecond solver object using a PropertyMap.
template<typename LocalFilter_ , typename Mirror_ >
std::shared_ptr< SchwarzPrecond< Global::Vector< typename LocalFilter_::VectorType, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > > > new_schwarz_precond (std::shared_ptr< SolverBase< typename LocalFilter_::VectorType > > local_solver, const Global::Filter< LocalFilter_, Mirror_ > &filter)
Creates a new SchwarzPrecond solver object.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< SecantLinesearch< Functional_, Filter_ > > new_secant_linesearch (const String &section_name, PropertyMap *section, Functional_ &functional, Filter_ &filter)
Creates a new SecantLinesearch object using a PropertyMap.
template<typename Functional_ , typename Filter_ >
std::shared_ptr< SecantLinesearch< Functional_, Filter_ > > new_secant_linesearch (Functional_ &functional, Filter_ &filter, typename Functional_::DataType secant_step=SecantLinesearch< Functional_, Filter_ >::secant_step_default, bool keep_iterates=false)
Creates a new SecantLinesearch object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< SORPrecond< Matrix_, Filter_ > > new_sor_precond (const String &section_name, PropertyMap *section, PreferredBackend backend, const Matrix_ &matrix, const Filter_ &filter)
Creates a new SORPrecond solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< SORPrecond< Matrix_, Filter_ > > new_sor_precond (PreferredBackend backend, const Matrix_ &matrix, const Filter_ &filter, const typename Matrix_::DataType omega=typename Matrix_::DataType(1))
Creates a new SORPrecond solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< SSORPrecond< Matrix_, Filter_ > > new_ssor_precond (const PreferredBackend backend, const Matrix_ &matrix, const Filter_ &filter, const typename Matrix_::DataType omega=typename Matrix_::DataType(1))
Creates a new SSORPrecond solver object.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< SSORPrecond< Matrix_, Filter_ > > new_ssor_precond (const String &section_name, PropertyMap *section, PreferredBackend backend, const Matrix_ &matrix, const Filter_ &filter)
Creates a new SSORPrecond solver object using a PropertyMap.
template<typename Matrix_ , typename Filter_ >
std::shared_ptr< SuperLU< Matrix_, Filter_ > > new_superlu (const Matrix_ &matrix, const Filter_ &filter)
Creates a new SuperLU solver object.
std::shared_ptr< Umfpack > new_umfpack (const LAFEM::SparseMatrixCSR< double, Index > &matrix)
Creates a new Umfpack solver object.
std::shared_ptr< UmfpackMean > new_umfpack_mean (const LAFEM::SparseMatrixCSR< double, Index > &matrix, const LAFEM::DenseVector< double, Index > &weight_vector)
Creates a new UmfpackMean solver object.
std::shared_ptr< UmfpackMean > new_umfpack_mean (const LAFEM::SparseMatrixCSR< double, Index > &matrix, const LAFEM::MeanFilter< double, Index > &filter)
Creates a new UmfpackMean solver object.
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ >
std::shared_ptr< UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ > > new_uzawa_precond (const MatrixA_ &matrix_a, const MatrixB_ &matrix_b, const MatrixD_ &matrix_d, const FilterV_ &filter_v, const FilterP_ &filter_p, std::shared_ptr< SolverBase< typename MatrixB_::VectorTypeL > > solver_a, std::shared_ptr< SolverBase< typename MatrixD_::VectorTypeL > > solver_s, UzawaType type=UzawaType::diagonal, bool auto_init_s=true)
Creates a new UzawaPrecond solver object.
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ >
std::shared_ptr< Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ > > new_vanka (const LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > &matrix, const Filter_ &filter, VankaType type, typename MatrixA_::DataType omega=typename MatrixA_::DataType(1), Index num_iter=Index(1))
Creates a new Vanka solver object.
template<typename Matrix_ , typename Filter_ , typename ColoringType_ , FEAT::Intern::VankaAssemblyPolicy pol_threading_ = FEAT::Intern::VankaAssemblyPolicy::batchedAssembly, FEAT::Intern::VankaMacroPolicy macro_type_ = FEAT::Intern::VankaMacroPolicy::uniformMacros>
std::shared_ptr< VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ > > new_voxel_amavanka (const Matrix_ &matrix, const Filter_ &filter, const ColoringType_ &coloring, typename Matrix_::DataType omega=typename Matrix_::DataType(1), Index num_steps=Index(1))
Creates a new VoxelAmaVanka smoother object.
template<typename Vector_ , typename Matrix_ , typename Filter_ >
Status solve (IterativeSolver< Vector_ > &solver, Vector_ &vec_sol, const Vector_ &vec_rhs, const Matrix_ &matrix, const Filter_ &filter)
Override of solve() for IterativeSolver solvers.
template<typename Vector_ , typename Matrix_ , typename Filter_ >
Status solve (SolverBase< Vector_ > &solver, Vector_ &vec_sol, const Vector_ &vec_rhs, const Matrix_ &matrix, const Filter_ &filter)
Solve linear system with initial solution guess.
bool status_success (Status status)
Status success check function.
Detailed Description
Solver namespace.
Enumeration Type Documentation
BiCGStabLPreconVariant
enum class FEAT::Solver::BiCGStabLPreconVariant strong
Enum for diffent preconditioning variants for BiCGStabL.
Definition at line 22 of file bicgstabl.hpp.
BiCGStabPreconVariant
enum class FEAT::Solver::BiCGStabPreconVariant strong
Enum for different preconditioning variants for BiCGStab.
Definition at line 21 of file bicgstab.hpp.
ExpressionType
enum class FEAT::Solver::ExpressionType strong
Expression Type enumeration.
Enumerator
start_solve
start new solve process
end_solve
end last solve process
call_precond
call preconditioner
call_precond_l
call L preconditioner
call_precond_r
call R preconditioner
call_smoother
call smoother
call_coarse_solver
call coarse grid solver
defect
annotate iterations defect
timings
annotate iterations timings
level_timings
annotate level timings
prol
prolonation (multigrid)
rest
restriction (multigrid)
call_uzawa_s
call S matrix solver (uzawa complement)
call_uzawa_a
call A matrix solver (uzawa complement)
Definition at line 23 of file expression.hpp.
MultiGridAdaptCGC
enum class FEAT::Solver::MultiGridAdaptCGC strong
Multigrid adaptive Coarse-Grid-Correction enumeration.
Enumerator
Fixed
fixed coarse grid correction damping
MinEnergy
Energy-Minimization.
MinDefect
Defect-Minimization.
Definition at line 39 of file multigrid.hpp.
MultiGridCycle
enum class FEAT::Solver::MultiGridCycle strong
Multigrid Cycle enumeration.
This enumeration specifies the various cycles supported by the MultiGrid solver.
Enumerator
V
Multigrid V-Cycle.
F
Multigrid F-Cycle.
W
Multigrid W-Cycle.
Definition at line 26 of file multigrid.hpp.
NLCGDirectionUpdate
enum class FEAT::Solver::NLCGDirectionUpdate strong
Enum for NLCG search direction updates.
Definition at line 24 of file nlcg.hpp.
PlotMode
enum class FEAT::Solver::PlotMode strong
Solver plot modes enumeration.
Enumerator
none
No plotting whatsoever.
iter
Plot every iteration (if applicable)
summary
Plot a summary after each solver run.
all
Plot every iteration (if applicable) and a summary.
Definition at line 55 of file iterative.hpp.
Status
enum class FEAT::Solver::Status strong
Solver status return codes enumeration.
This enumeration defined the solver status return codes, which specify whether the solver application was successful or failed due to some reason.
Enumerator
undefined
undefined status
progress
continue iteration (internal use only)
success
solving successful (convergence criterion fulfilled)
aborted
premature abort (solver aborted due to internal errors or preconditioner failure)
diverged
solver diverged (divergence criterion fulfilled)
max_iter
solver reached maximum iterations
stagnated
solver stagnated (stagnation criterion fulfilled)
Definition at line 48 of file base.hpp.
UzawaType
enum class FEAT::Solver::UzawaType strong
Uzawa preconditioner type.
This enumeration specifies the various preconditioner types implemented in the UzawaPrecond class template.
Enumerator
diagonal
diagonal Uzawa preconditioner
lower
lower-diagonal Uzawa preconditioner
upper
upper-diagonal Uzawa preconditioner
full
full Uzawa preconditioner
Definition at line 30 of file uzawa_precond.hpp.
VankaType
enum class FEAT::Solver::VankaType strong
Vanka type enumeration.
This enumeration specifies the various types of supported Vanka variants. See the documentation of the Vanka solver class template for details.
Enumerator
nodal_diag_mult
Nodal diagonal Vanka type (multiplicative)
nodal_full_mult
Nodal full Vanka type (multiplicative)
block_diag_mult
Blocked diagonal Vanka type (multiplicative)
block_full_mult
Blocked full Vanka type (multiplicative)
nodal_diag_add
Nodal diagonal Vanka type (additive)
nodal_full_add
Nodal full Vanka type (additive)
block_diag_add
Blocked diagonal Vanka type (additive)
block_full_add
Blocked full Vanka type (additive)
Definition at line 893 of file vanka.hpp.
Function Documentation
new_alglib_mincg() [1/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< ALGLIBMinCG< Functional_, Filter_ > > FEAT::Solver::new_alglib_mincg (const String & section_name, PropertyMap * section, Functional_ & functional_, Filter_ & filter_) inline
Creates a new ALGLIBMinCG solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] functional_ The functional
[in] filter_ The system filter.
Returns
A shared pointer to a new ALGLIBMinCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 1093 of file alglib_wrapper.hpp.
new_alglib_mincg() [2/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< ALGLIBMinCG< Functional_, Filter_ > > FEAT::Solver::new_alglib_mincg (Functional_ & functional_, Filter_ & filter_, NLCGDirectionUpdate du_ = ALGLIBMinCG<Functional_, Filter_>::direction_update_default, bool keep_iterates_ = false) inline
Creates a new ALGLIBMinCG solver object.
Parameters
[in] functional_ The functional
[in] filter_ The system filter.
[in] keep_iterates_ Flag for keeping the iterates, defaults to false
Returns
A shared pointer to a new ALGLIBMinCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 1065 of file alglib_wrapper.hpp.
new_alglib_minlbfgs() [1/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< ALGLIBMinLBFGS< Functional_, Filter_ > > FEAT::Solver::new_alglib_minlbfgs (const String & section_name, PropertyMap * section, Functional_ & functional_, Filter_ & filter_) inline
Creates a new ALGLIBMinLBFGS solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] functional_ The functional
[in] filter_ The system filter.
Returns
A shared pointer to a new ALGLIBMinLBFGS object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 565 of file alglib_wrapper.hpp.
new_alglib_minlbfgs() [2/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< ALGLIBMinLBFGS< Functional_, Filter_ > > FEAT::Solver::new_alglib_minlbfgs (Functional_ & functional_, Filter_ & filter_, alglib::ae_int_t lbfgs_dim_ = alglib::ae_int_t(0), bool keep_iterates = false) inline
Creates a new ALGLIBMinLBFGS solver object.
Parameters
[in] functional_ The functional
[in] filter_ The system filter.
[in] lbfgs_dim_ How many vectors to keep for the lBFGS hessian update. Defaults to min(7, functional_.columns()).
[in] keep_iterates Keep all iterates in a std::deque. Defaults to false.
Returns
A shared pointer to a new ALGLIBMinLBFGS object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 538 of file alglib_wrapper.hpp.
new_amavanka()
template<typename Matrix_ , typename Filter_ > std::shared_ptr< AmaVanka< Matrix_, Filter_ > > FEAT::Solver::new_amavanka (const Matrix_ & matrix, const Filter_ & filter, typename Matrix_::DataType omega = typename Matrix_::DataType(1), Index num_steps = Index(1))
Creates a new AmaVanka smoother object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter
[in] omega The damping parameter.
[in] num_steps The number of Vanka iterations to be performed.
Returns
A shared pointer to a new AmaVanka object.
Definition at line 490 of file amavanka.hpp.
new_approximate_hessian_precond()
template<typename Operator_ , typename Filter_ > std::shared_ptr< ApproximateHessianPrecond< Operator_, Filter_ > > FEAT::Solver::new_approximate_hessian_precond (Operator_ & op_, const Filter_ & filter_) inline
Creates a new ApproximateHessianPrecond.
Template Parameters
Operator_ The operator's type.
Filter_ The type of the filte for the preconditioner.
Parameters
[in] op_ The (nonlinear) operator.
[in] filter_ The system filter.
Returns
A shared pointer to a new HessianPrecond object.
Definition at line 329 of file hessian_precond.hpp.
new_bicgstab() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< BiCGStab< Matrix_, Filter_ > > FEAT::Solver::new_bicgstab (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr, BiCGStabPreconVariant precon_variant = BiCGStabPreconVariant::left) inline
Creates a new BiCGStab solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
[in] precon_variant Which preconditioning variant to use, defaults to left
Returns
A shared pointer to a new BiCGStab object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 602 of file bicgstab.hpp.
new_bicgstab() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< BiCGStab< Matrix_, Filter_ > > FEAT::Solver::new_bicgstab (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new BiCGStab solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new BiCGStab object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 652 of file bicgstab.hpp.
new_bicgstabl() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< BiCGStabL< Matrix_, Filter_ > > FEAT::Solver::new_bicgstabl (const Matrix_ & matrix, const Filter_ & filter, int l = 2, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr, BiCGStabLPreconVariant precon_variant = BiCGStabLPreconVariant::left) inline
Creates a new BiCGStabL solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] l A parameter for the solver configuration
[in] precond The preconditioner. May be nullptr.
[in] precon_variant Which preconditioning variant to use, defaults to left
Returns
A shared pointer to a new BiCGStabL object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 558 of file bicgstabl.hpp.
new_bicgstabl() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< BiCGStabL< Matrix_, Filter_ > > FEAT::Solver::new_bicgstabl (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new BiCGStabL solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new BiCGStabL object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 610 of file bicgstabl.hpp.
new_boomeramg() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< BoomerAMG< Matrix_, Filter_ > > FEAT::Solver::new_boomeramg (const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new BoomerAMG solver object.
Parameters
[in] matrix The global system matrix.
[in] filter The global system filter.
Returns
A shared pointer to a new BoomerAMG object.
Definition at line 621 of file hypre.hpp.
new_boomeramg() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< BoomerAMG< Matrix_, Filter_ > > FEAT::Solver::new_boomeramg (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new BoomerAMG solver object based on a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new BoomerAMG object.
Definition at line 646 of file hypre.hpp.
new_chebyshev() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< Chebyshev< Matrix_, Filter_ > > FEAT::Solver::new_chebyshev (const Matrix_ & matrix, const Filter_ & filter, const typename Matrix_::DataType fraction_min_ev = typename Matrix_::DataType(0.03), const typename Matrix_::DataType fraction_max_ev = typename Matrix_::DataType(1.1)) inline
Creates a new Chebyshev solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new Chebyshev object.
Definition at line 301 of file chebyshev.hpp.
new_chebyshev() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< Chebyshev< Matrix_, Filter_ > > FEAT::Solver::new_chebyshev (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new Chebyshev solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new Chebyshev object.
Definition at line 328 of file chebyshev.hpp.
new_convert_precond() [1/2]
template<typename LocalVectorOuter_ , typename LocalVectorInner_ , typename MirrorOuter_ , typename MirrorInner_ > std::shared_ptr< ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > > > FEAT::Solver::new_convert_precond (std::shared_ptr< SolverBase< Global::Vector< LocalVectorInner_, MirrorInner_ > > > inner_solver) inline
Creates a new ConvertPrecond solver object.
Parameters
[in] inner_solver The actual solver, which shall be executed with converted rhs/sol vectors
Returns
A shared pointer to a new ConvertPrecond object.
Definition at line 237 of file convert_precond.hpp.
new_convert_precond() [2/2]
template<typename VectorOuter_ , typename VectorInner_ > std::shared_ptr< ConvertPrecond< VectorOuter_, VectorInner_ > > FEAT::Solver::new_convert_precond (std::shared_ptr< SolverBase< VectorInner_ > > inner_solver) inline
Creates a new ConvertPrecond solver object.
Parameters
[in] inner_solver The actual solver, which shall be executed with converted rhs/sol vectors
Returns
A shared pointer to a new ConvertPrecond object.
Definition at line 132 of file convert_precond.hpp.
new_diagonal_precond()
template<typename Vector_ , typename Filter_ > std::shared_ptr< DiagonalPrecond< Vector_, Filter_ > > FEAT::Solver::new_diagonal_precond (const Vector_ & diag, const Filter_ & filter) inline
Creates a new DiagonalPrecond solver object.
Parameters
[in] diag The vector representing the diagonal matrix.
[in] filter The system filter.
Returns
A shared pointer to a new DiagonalPrecond object.
Definition at line 88 of file diagonal_precond.hpp.
new_direct_stokes_solver()
template<typename Matrix_ , typename Filter_ > std::shared_ptr< DirectStokesSolver< Matrix_, Filter_ > > FEAT::Solver::new_direct_stokes_solver (const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new DirectStokesSolver object.
Parameters
[in] matrix A resident reference to the system matrix.
[in] filter A resident reference to the system filter.
Returns
A shared pointer to a new DirectStokesSolver object.
Definition at line 1254 of file direct_stokes_solver.hpp.
new_euclid_precond() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< EuclidPrecond< Matrix_, Filter_ > > FEAT::Solver::new_euclid_precond (const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new EuclidPrecond solver object.
Parameters
[in] matrix The global system matrix.
[in] filter The global system filter.
Returns
A shared pointer to a new EuclidPrecond object.
Definition at line 487 of file hypre.hpp.
new_euclid_precond() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< EuclidPrecond< Matrix_, Filter_ > > FEAT::Solver::new_euclid_precond (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new EuclidPrecond solver object based on a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new EuclidPrecond object.
Definition at line 512 of file hypre.hpp.
new_fgmres() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< FGMRES< Matrix_, Filter_ > > FEAT::Solver::new_fgmres (const Matrix_ & matrix, const Filter_ & filter, Index krylov_dim, typename Matrix_::DataType inner_res_scale = typename Matrix_::DataType(0), std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new FGMRES solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] krylov_dim The maximum Krylov subspace dimension. Must be > 0.
[in] inner_res_scale The scaling factor for the inner GMRES loop residual. Set this to zero unless you know what you are doing.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new FGMRES object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 427 of file fgmres.hpp.
new_fgmres() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< FGMRES< Matrix_, Filter_ > > FEAT::Solver::new_fgmres (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new FGMRES solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new FGMRES object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 476 of file fgmres.hpp.
new_fixed_step_linesearch() [1/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< FixedStepLinesearch< Functional_, Filter_ > > FEAT::Solver::new_fixed_step_linesearch (const String & section_name, PropertyMap * section, Functional_ & functional, Filter_ & filter) inline
Creates a new FixedStepLinesearch object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself.
[in] section A pointer to the PropertyMap section configuring this solver.
[in] functional The functional.
[in] filter The system filter.
Returns
A shared pointer to a new FixedStepLinesearch object.
Definition at line 223 of file fixed_step_linesearch.hpp.
new_fixed_step_linesearch() [2/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< FixedStepLinesearch< Functional_, Filter_ > > FEAT::Solver::new_fixed_step_linesearch (Functional_ & functional, Filter_ & filter, typename Functional_::DataType step_length, bool keep_iterates = false) inline
Creates a new FixedStepLinesearch object.
Parameters
[in] functional The functional.
[in] filter The system filter.
[in] step_length The step length the "line search" is to take.
[in] keep_iterates Flag for keeping the iterates, defaults to false.
Returns
A shared pointer to a new FixedStepLinesearch object.
Definition at line 197 of file fixed_step_linesearch.hpp.
new_generic_umfpack()
template<typename Matrix_ > std::shared_ptr< GenericUmfpack< Matrix_ > > FEAT::Solver::new_generic_umfpack (const Matrix_ & matrix) inline
Creates a new GenericUmfpack solver object.
Parameters
[in] matrix The system matrix.
Returns
A shared pointer to a new GenericUmfpack object.
Definition at line 781 of file umfpack.hpp.
new_gropppcg() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< GroppPCG< Matrix_, Filter_ > > FEAT::Solver::new_gropppcg (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new GroppPCG solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new GroppPCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 299 of file gropppcg.hpp.
new_gropppcg() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< GroppPCG< Matrix_, Filter_ > > FEAT::Solver::new_gropppcg (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new GroppPCG solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new GroppPCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 347 of file gropppcg.hpp.
new_hessian_precond()
template<typename Operator_ , typename Filter_ > std::shared_ptr< HessianPrecond< Operator_, Filter_ > > FEAT::Solver::new_hessian_precond (Operator_ & op_, const Filter_ & filter_) inline
Creates a new HessianPrecond.
Template Parameters
Operator_ The operator's type.
Filter_ The type of the filte for the preconditioner.
Parameters
[in] op_ The (nonlinear) operator.
[in] filter_ The system filter.
Returns
A shared pointer to a new HessianPrecond object.
Definition at line 159 of file hessian_precond.hpp.
new_idrs() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< IDRS< Matrix_, Filter_ > > FEAT::Solver::new_idrs (const Matrix_ & matrix, const Filter_ & filter, Index krylov_dim, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new IDR(s) solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] krylov_dim The maximum Krylov subspace dimension. Must be > 0.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new IDRS object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 470 of file idrs.hpp.
new_idrs() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< IDRS< Matrix_, Filter_ > > FEAT::Solver::new_idrs (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new IDR(s) solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new IDRS object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 518 of file idrs.hpp.
new_ilu_precond() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< ILUPrecond< Matrix_, Filter_ > > FEAT::Solver::new_ilu_precond (const String & section_name, PropertyMap * section, PreferredBackend backend, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new ILUPrecond solver object based on a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] backend The backend to be preferred. This implementation works with generic and cuda.
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new ILUPrecond object.
Definition at line 1847 of file ilu_precond.hpp.
new_ilu_precond() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< ILUPrecond< Matrix_, Filter_ > > FEAT::Solver::new_ilu_precond (PreferredBackend backend, const Matrix_ & matrix, const Filter_ & filter, const int p = 0) inline
Creates a new ILUPrecond solver object.
Parameters
[in] backend The backend to be preferred. This implementation works with generic and cuda.
[in] matrix The system matrix.
[in] filter The system filter.
[in] p Maximum level of fill-in.
Returns
A shared pointer to a new ILUPrecond object.
Definition at line 1819 of file ilu_precond.hpp.
new_jacobi_precond() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< JacobiPrecond< Matrix_, Filter_ > > FEAT::Solver::new_jacobi_precond (const Matrix_ & matrix, const Filter_ & filter, const typename Matrix_::DataType omega = typename Matrix_::DataType(1)) inline
Creates a new JacobiPrecond solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] omega The damping parameter for Jacobi.
Returns
A shared pointer to a new JacobiPrecond object.
Definition at line 183 of file jacobi_precond.hpp.
new_jacobi_precond() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< JacobiPrecond< Matrix_, Filter_ > > FEAT::Solver::new_jacobi_precond (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new JacobiPrecond solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
Returns
A shared pointer to a new JacobiPrecond object.
Definition at line 206 of file jacobi_precond.hpp.
new_matrix_precond()
template<typename Matrix_ , typename Filter_ > std::shared_ptr< MatrixPrecond< Matrix_, Filter_ > > FEAT::Solver::new_matrix_precond (const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new MatrixPrecond solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new JacobiPrecond object.
Definition at line 93 of file matrix_precond.hpp.
new_mqc_linesearch() [1/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< MQCLinesearch< Functional_, Filter_ > > FEAT::Solver::new_mqc_linesearch (const String & section_name, PropertyMap * section, Functional_ & functional, Filter_ & filter) inline
Creates a new MQCLinesearch object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself.
[in] section A pointer to the PropertyMap section configuring this solver.
[in] functional The functional.
[in] filter The system filter.
Returns
A shared pointer to a new MQCLinesearch object.
Definition at line 840 of file mqc_linesearch.hpp.
new_mqc_linesearch() [2/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< MQCLinesearch< Functional_, Filter_ > > FEAT::Solver::new_mqc_linesearch (Functional_ & functional, Filter_ & filter, bool keep_iterates = false) inline
Creates a new MQCLinesearch object.
Parameters
[in] functional The functional.
[in] filter The system filter.
[in] keep_iterates Flag for keeping the iterates, defaults to false.
Returns
A shared pointer to a new MQCLinesearch object.
Definition at line 815 of file mqc_linesearch.hpp.
new_multigrid()
template<typename SystemMatrix_ , typename SystemFilter_ , typename TransferOperator_ > std::shared_ptr< MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ > > FEAT::Solver::new_multigrid (std::shared_ptr< MultiGridHierarchy< SystemMatrix_, SystemFilter_, TransferOperator_ > > hierarchy, MultiGridCycle cycle = MultiGridCycle::V, int top_level = 0, int crs_level = -1)
Creates a new Multigrid preconditioner object.
Parameters
[in] hierarchy A pointer to the multigrid hierarchy object.
[in] cycle The desired multigrid cycle.
[in] top_level The desired top-level for this multigrid solver.
Set to 0 to use the finest level in the multigrid hierarchy.
[in] crs_level The desired coarse-level for this multigrid solver.
Set to -1 to use the coarsest level in the multigrid hierarchy.
Returns
A shared pointer to a new MultiGrid object.
Definition at line 2029 of file multigrid.hpp.
new_newton_raphson_linesearch() [1/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< NewtonRaphsonLinesearch< Functional_, Filter_ > > FEAT::Solver::new_newton_raphson_linesearch (const String & section_name, PropertyMap * section, Functional_ & functional, Filter_ & filter) inline
Creates a new NewtonRaphsonLinesearch object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] functional The functional
[in] filter The system filter.
Returns
A shared pointer to a new NewtonRaphsonLinesearch object.
Definition at line 282 of file newton_raphson_linesearch.hpp.
new_newton_raphson_linesearch() [2/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< NewtonRaphsonLinesearch< Functional_, Filter_ > > FEAT::Solver::new_newton_raphson_linesearch (Functional_ & functional, Filter_ & filter, bool keep_iterates = false) inline
Creates a new NewtonRaphsonLinesearch object.
Parameters
[in] functional The functional.
[in] filter The system filter.
[in] keep_iterates Flag for keeping the iterates, defaults to false
Returns
A shared pointer to a new NewtonRaphsonLinesearch object.
Definition at line 257 of file newton_raphson_linesearch.hpp.
new_nlcg() [1/2]
template<typename Functional_ , typename Filter_ , typename Linesearch_ > std::shared_ptr< NLCG< Functional_, Filter_ > > FEAT::Solver::new_nlcg (const String & section_name, PropertyMap * section, Functional_ & functional, Filter_ & filter, Linesearch_ & linesearch, std::shared_ptr< NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > > precond = nullptr) inline
Creates a new NLCG solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] functional The functional.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
[in] linesearch The linesearch to use.
Returns
A shared pointer to a new NLCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 988 of file nlcg.hpp.
new_nlcg() [2/2]
template<typename Functional_ , typename Filter_ , typename Linesearch_ > std::shared_ptr< NLCG< Functional_, Filter_ > > FEAT::Solver::new_nlcg (Functional_ & functional, Filter_ & filter, Linesearch_ & linesearch, NLCGDirectionUpdate direction_update = NLCG<Functional_, Filter_>::direction_update_default, bool keep_iterates = false, std::shared_ptr< NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > > precond = nullptr) inline
Creates a new NLCG solver object.
Parameters
[in] functional The functional.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
[in] linesearch The linesearch to use.
[in] direction_update The direction update to use, defaults to Polak-Ribiere.
[in] keep_iterates Flag for keeping the iterates, defaults to false
Returns
A shared pointer to a new NLCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 933 of file nlcg.hpp.
new_nlsd() [1/2]
template<typename Functional_ , typename Filter_ , typename Linesearch_ > std::shared_ptr< NLSD< Functional_, Filter_ > > FEAT::Solver::new_nlsd (const String & section_name, PropertyMap * section, Functional_ & functional, Filter_ & filter, Linesearch_ & linesearch, std::shared_ptr< NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > > precond = nullptr) inline
Creates a new NLSD solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself.
[in] section A pointer to the PropertyMap section configuring this solver.
[in] functional The nonlinear functional.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
[in] linesearch The linesearch to use.
Returns
A shared pointer to a new NLSD object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 470 of file nlsd.hpp.
new_nlsd() [2/2]
template<typename Functional_ , typename Filter_ , typename Linesearch_ > std::shared_ptr< NLSD< Functional_, Filter_ > > FEAT::Solver::new_nlsd (Functional_ & functional, Filter_ & filter, Linesearch_ & linesearch, bool keep_iterates = false, std::shared_ptr< NLOptPrecond< typename Functional_::VectorTypeL, Filter_ > > precond = nullptr) inline
Creates a new NLSD solver object.
Parameters
[in] functional The nonlinear functional.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
[in] linesearch The linesearch to use.
[in] keep_iterates Flag for keeping the iterates, defaults to false
Returns
A shared pointer to a new NLSD object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 415 of file nlsd.hpp.
new_nonlinear_operator_precond_wrapper()
template<typename NonlinearOperator_ , typename... Args_> std::shared_ptr< NonlinearOperatorPrecondWrapper< NonlinearOperator_ > > FEAT::Solver::new_nonlinear_operator_precond_wrapper (Args_ &&... args) inline
Creates a new NonlinearOperatorPrecondWrapper.
Template Parameters
NonlinearOperator_ The operator to be used.
Parameters
[in] args Arguments passed to the NonlinearOperator's constructor.
Returns
A shared_ptr to a new NonlinearOperatorPrecondWrapper object.
Definition at line 201 of file nlopt_precond.hpp.
new_parasails_precond() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< ParaSailsPrecond< Matrix_, Filter_ > > FEAT::Solver::new_parasails_precond (const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new ParaSailsPrecond solver object.
Parameters
[in] matrix The global system matrix.
[in] filter The global system filter.
Returns
A shared pointer to a new ParaSailsPrecond object.
Definition at line 347 of file hypre.hpp.
new_parasails_precond() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< ParaSailsPrecond< Matrix_, Filter_ > > FEAT::Solver::new_parasails_precond (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new ParaSailsPrecond solver object based on a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new ParaSailsPrecond object.
Definition at line 372 of file hypre.hpp.
new_pcg() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PCG< Matrix_, Filter_ > > FEAT::Solver::new_pcg (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PCG solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 323 of file pcg.hpp.
new_pcg() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PCG< Matrix_, Filter_ > > FEAT::Solver::new_pcg (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PCG solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 371 of file pcg.hpp.
new_pcgnr() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PCGNR< Matrix_, Filter_ > > FEAT::Solver::new_pcgnr (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond_l = nullptr, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond_r = nullptr) inline
Creates a new PCGNR solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond_l The left preconditioner. May be nullptr.
[in] precond_r The right preconditioner. May be nullptr.
Returns
A shared pointer to a new PCGNR object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 419 of file pcgnr.hpp.
new_pcgnr() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PCGNR< Matrix_, Filter_ > > FEAT::Solver::new_pcgnr (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond_l = nullptr, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond_r = nullptr) inline
Creates a new PCGNR solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond_l The left preconditioner. May be nullptr.
[in] precond_r The right preconditioner. May be nullptr.
Returns
A shared pointer to a new PCGNR object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 473 of file pcgnr.hpp.
new_pcgnrilu() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PCGNRILU< Matrix_, Filter_ > > FEAT::Solver::new_pcgnrilu (const Matrix_ & matrix, const Filter_ & filter, int ilu_p = -1) inline
Creates a new PCGNRILU solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] ilu_p Maximum allowed fill-in for ILU preconditioner. Set to -1 to disable preconditioning.
Returns
A shared pointer to a new PCGNRILU object.
Definition at line 374 of file pcgnrilu.hpp.
new_pcgnrilu() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PCGNRILU< Matrix_, Filter_ > > FEAT::Solver::new_pcgnrilu (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new PCGNRILU solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new PCGNRILU object.
Definition at line 399 of file pcgnrilu.hpp.
new_pcr() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PCR< Matrix_, Filter_ > > FEAT::Solver::new_pcr (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PCR solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PCR object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 317 of file pcr.hpp.
new_pcr() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PCR< Matrix_, Filter_ > > FEAT::Solver::new_pcr (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PCR solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PCR object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 366 of file pcr.hpp.
new_pipepcg() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PipePCG< Matrix_, Filter_ > > FEAT::Solver::new_pipepcg (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PipePCG solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PipePCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 335 of file pipepcg.hpp.
new_pipepcg() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PipePCG< Matrix_, Filter_ > > FEAT::Solver::new_pipepcg (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PipePCG solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PipePCG object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 383 of file pipepcg.hpp.
new_pmr() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PMR< Matrix_, Filter_ > > FEAT::Solver::new_pmr (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PMR solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PMR object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 286 of file pmr.hpp.
new_pmr() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PMR< Matrix_, Filter_ > > FEAT::Solver::new_pmr (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PMR solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PMR object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 335 of file pmr.hpp.
new_polynomial_precond() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PolynomialPrecond< Matrix_, Filter_ > > FEAT::Solver::new_polynomial_precond (const Matrix_ & matrix, const Filter_ & filter, const Index m, const typename Matrix_::DataType omega = typename Matrix_::DataType(1)) inline
Creates a new PoynomialPrecond solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] m The order of the polynom
[in] omega The damping parameter for the internal jacobi preconditioner.
Returns
A shared pointer to a new PolynomialPrecond object.
Definition at line 242 of file polynomial_precond.hpp.
new_polynomial_precond() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PolynomialPrecond< Matrix_, Filter_ > > FEAT::Solver::new_polynomial_precond (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new PolynomialPrecond solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new PolynomialPrecond object.
Definition at line 268 of file polynomial_precond.hpp.
new_psd() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PSD< Matrix_, Filter_ > > FEAT::Solver::new_psd (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PSD solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PSD object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 260 of file psd.hpp.
new_psd() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< PSD< Matrix_, Filter_ > > FEAT::Solver::new_psd (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new PSD solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new PSD object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 309 of file psd.hpp.
new_qpenalty() [1/2]
template<typename Functional_ > std::shared_ptr< QPenalty< Functional_ > > FEAT::Solver::new_qpenalty (const String & section_name, PropertyMap * section, Functional_ & functional, std::shared_ptr< IterativeSolver< typename Functional_::VectorTypeR > > inner_solver) inline
Creates a new QPenalty object using a PropertyMap.
Template Parameters
Functional_ The type of the quadratic penalty function \(Q \).
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] functional The quadratic penalty function \(Q \).
[in] inner_solver The inner solver for solving the penalized unconstrained optimization problem.
Returns
An std::shared_ptr to the new QPenalty solver object
Definition at line 423 of file qpenalty.hpp.
new_qpenalty() [2/2]
template<typename Functional_ > std::shared_ptr< QPenalty< Functional_ > > FEAT::Solver::new_qpenalty (Functional_ & functional, std::shared_ptr< IterativeSolver< typename Functional_::VectorTypeR > > inner_solver, typename Functional_::VectorTypeR::DataType initial_penalty_param = typename Functional_::VectorTypeR::DataType(1)) inline
Creates a new QPenalty object.
Template Parameters
Functional_ The type of the quadratic penalty function \(Q \).
Parameters
[in] functional The quadratic penalty function \(Q \).
[in] inner_solver The inner solver for solving the penalized unconstrained optimization problem.
Returns
An std::shared_ptr to the new QPenalty solver object
Definition at line 394 of file qpenalty.hpp.
new_rbicgstab() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< RBiCGStab< Matrix_, Filter_ > > FEAT::Solver::new_rbicgstab (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new RBiCGStab solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new RBiCGStab object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 401 of file rbicgstab.hpp.
new_rbicgstab() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< RBiCGStab< Matrix_, Filter_ > > FEAT::Solver::new_rbicgstab (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new RBiCGStab solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new RBiCGStab object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 449 of file rbicgstab.hpp.
new_rgcr() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< RGCR< Matrix_, Filter_ > > FEAT::Solver::new_rgcr (const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new RGCR solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new RGCR object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 277 of file rgcr.hpp.
new_rgcr() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< RGCR< Matrix_, Filter_ > > FEAT::Solver::new_rgcr (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new RGCR solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new RGCR object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 325 of file rgcr.hpp.
new_richardson() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< Richardson< Matrix_, Filter_ > > FEAT::Solver::new_richardson (const Matrix_ & matrix, const Filter_ & filter, typename Matrix_::DataType omega = typename Matrix_::DataType(1), std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new Richardson solver object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter.
[in] omega The damping parameter for the solver.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new Richardson object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 270 of file richardson.hpp.
new_richardson() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< Richardson< Matrix_, Filter_ > > FEAT::Solver::new_richardson (const String & section_name, PropertyMap * section, const Matrix_ & matrix, const Filter_ & filter, std::shared_ptr< SolverBase< typename Matrix_::VectorTypeL > > precond = nullptr) inline
Creates a new Richardson solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] matrix The system matrix.
[in] filter The system filter.
[in] precond The preconditioner. May be nullptr.
Returns
A shared pointer to a new Richardson object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 319 of file richardson.hpp.
new_saddle_umfpack_mean() [1/2]
template<typename DT_ , typename IT_ , int dim_> std::shared_ptr< SaddleUmfpackMean< DT_, IT_, dim_ > > FEAT::Solver::new_saddle_umfpack_mean (const LAFEM::SaddlePointMatrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ > > & matrix, const LAFEM::DenseVector< DT_, IT_ > & weight_vector) inline
Creates a new UmfpackMean solver object.
Parameters
[in] matrix The system matrix.
[in] weight_vector The weight vector to be used as a Lagrange multiplier.
Returns
A shared pointer to a new UmfpackMean object.
Definition at line 604 of file umfpack.hpp.
new_saddle_umfpack_mean() [2/2]
template<typename DT_ , typename IT_ , int dim_> std::shared_ptr< SaddleUmfpackMean< DT_, IT_, dim_ > > FEAT::Solver::new_saddle_umfpack_mean (const LAFEM::SaddlePointMatrix< LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, dim_ >, LAFEM::SparseMatrixBCSR< DT_, IT_, dim_, 1 >, LAFEM::SparseMatrixBCSR< DT_, IT_, 1, dim_ > > & matrix, const LAFEM::MeanFilter< DT_, IT_ > & filter) inline
Creates a new UmfpackMean solver object.
Parameters
[in] matrix The system matrix.
[in] filter A reference to the mean filter containing the weight vector.
Returns
A shared pointer to a new UmfpackMean object.
Definition at line 627 of file umfpack.hpp.
new_scale_precond() [1/2]
template<typename Filter_ , typename DataType_ > std::shared_ptr< ScalePrecond< typename Filter_::VectorType, Filter_ > > FEAT::Solver::new_scale_precond (const Filter_ & filter, DataType_ omega) inline
Creates a new ScalePrecond solver object.
Parameters
[in] filter The system filter.
[in] omega The scaling parameter for the preconditioner.
Returns
A shared pointer to a new ScalePrecond object.
Definition at line 124 of file scale_precond.hpp.
new_scale_precond() [2/2]
template<typename Filter_ > std::shared_ptr< ScalePrecond< typename Filter_::VectorType, Filter_ > > FEAT::Solver::new_scale_precond (const String & section_name, PropertyMap * section, const Filter_ & filter) inline
Creates a new ScalePrecond solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] filter The system filter.
Returns
A shared pointer to a new ScalePrecond object.
Definition at line 146 of file scale_precond.hpp.
new_schwarz_precond() [1/2]
template<typename LocalFilter_ , typename Mirror_ > std::shared_ptr< SchwarzPrecond< Global::Vector< typename LocalFilter_::VectorType, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > > > FEAT::Solver::new_schwarz_precond (const String & section_name, PropertyMap * section, std::shared_ptr< SolverBase< typename LocalFilter_::VectorType > > local_solver, const Global::Filter< LocalFilter_, Mirror_ > & filter) inline
Creates a new SchwarzPrecond solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] local_solver The local solver object.
[in] filter The global system filter.
Returns
A shared pointer to a new SchwarzPrecond object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 248 of file schwarz_precond.hpp.
new_schwarz_precond() [2/2]
template<typename LocalFilter_ , typename Mirror_ > std::shared_ptr< SchwarzPrecond< Global::Vector< typename LocalFilter_::VectorType, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > > > FEAT::Solver::new_schwarz_precond (std::shared_ptr< SolverBase< typename LocalFilter_::VectorType > > local_solver, const Global::Filter< LocalFilter_, Mirror_ > & filter) inline
Creates a new SchwarzPrecond solver object.
Parameters
[in] local_solver The local solver object.
[in] filter The global system filter.
Returns
A shared pointer to a new SchwarzPrecond object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 192 of file schwarz_precond.hpp.
new_secant_linesearch() [1/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< SecantLinesearch< Functional_, Filter_ > > FEAT::Solver::new_secant_linesearch (const String & section_name, PropertyMap * section, Functional_ & functional, Filter_ & filter) inline
Creates a new SecantLinesearch object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] functional The functional
[in] filter The system filter.
Returns
A shared pointer to a new SecantLinesearch object.
Definition at line 341 of file secant_linesearch.hpp.
new_secant_linesearch() [2/2]
template<typename Functional_ , typename Filter_ > std::shared_ptr< SecantLinesearch< Functional_, Filter_ > > FEAT::Solver::new_secant_linesearch (Functional_ & functional, Filter_ & filter, typename Functional_::DataType secant_step = SecantLinesearch<Functional_, Filter_>::secant_step_default, bool keep_iterates = false) inline
Creates a new SecantLinesearch object.
Parameters
[in] functional The functional.
[in] filter The system filter.
[in] secant_step Length for first secant step.
[in] keep_iterates Flag for keeping the iterates, defaults to false
Returns
A shared pointer to a new SecantLinesearch object.
Definition at line 313 of file secant_linesearch.hpp.
new_sor_precond() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< SORPrecond< Matrix_, Filter_ > > FEAT::Solver::new_sor_precond (const String & section_name, PropertyMap * section, PreferredBackend backend, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new SORPrecond solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] backend The backend to be preferred. This implementation works with generic and cuda.
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new SORPrecond object.
Definition at line 916 of file sor_precond.hpp.
new_sor_precond() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< SORPrecond< Matrix_, Filter_ > > FEAT::Solver::new_sor_precond (PreferredBackend backend, const Matrix_ & matrix, const Filter_ & filter, const typename Matrix_::DataType omega = typename Matrix_::DataType(1)) inline
Creates a new SORPrecond solver object.
Parameters
[in] backend The backend to be preferred. This implementation works with generic and cuda.
[in] matrix The system matrix.
[in] filter The system filter.
[in] omega The damping value.
Returns
A shared pointer to a new SORPrecond object.
Definition at line 887 of file sor_precond.hpp.
new_ssor_precond() [1/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< SSORPrecond< Matrix_, Filter_ > > FEAT::Solver::new_ssor_precond (const PreferredBackend backend, const Matrix_ & matrix, const Filter_ & filter, const typename Matrix_::DataType omega = typename Matrix_::DataType(1)) inline
Creates a new SSORPrecond solver object.
Parameters
[in] backend The backend to be preferred. This implementation works with generic and cuda.
[in] matrix The system matrix.
[in] filter The system filter.
[in] omega The damping value.
Returns
A shared pointer to a new SSORPrecond object.
Definition at line 859 of file ssor_precond.hpp.
new_ssor_precond() [2/2]
template<typename Matrix_ , typename Filter_ > std::shared_ptr< SSORPrecond< Matrix_, Filter_ > > FEAT::Solver::new_ssor_precond (const String & section_name, PropertyMap * section, PreferredBackend backend, const Matrix_ & matrix, const Filter_ & filter) inline
Creates a new SSORPrecond solver object using a PropertyMap.
Parameters
[in] section_name The name of the config section, which it does not know by itself
[in] section A pointer to the PropertyMap section configuring this solver
[in] backend The backend to be preferred. This implementation works with generic and cuda.
[in] matrix The system matrix.
[in] filter The system filter.
Returns
A shared pointer to a new SSORPrecond object.
Definition at line 889 of file ssor_precond.hpp.
new_superlu()
template<typename Matrix_ , typename Filter_ > std::shared_ptr< SuperLU< Matrix_, Filter_ > > FEAT::Solver::new_superlu (const Matrix_ & matrix, const Filter_ & filter)
Creates a new SuperLU solver object.
Parameters
[in] matrix The system matrix
[in] filter The system filter
Returns
A shared pointer to a new SuperLU object.
Definition at line 204 of file superlu.hpp.
new_umfpack()
std::shared_ptr< Umfpack > FEAT::Solver::new_umfpack (const LAFEM::SparseMatrixCSR< double, Index > & matrix) inline
Creates a new Umfpack solver object.
Parameters
[in] matrix The system matrix.
Returns
A shared pointer to a new Umfpack object.
Definition at line 118 of file umfpack.hpp.
Referenced by FEAT::Solver::DirectStokesSolver< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, LAFEM::TupleFilter< FilterV_, FilterP_ > >::DirectStokesSolver().
new_umfpack_mean() [1/2]
std::shared_ptr< UmfpackMean > FEAT::Solver::new_umfpack_mean (const LAFEM::SparseMatrixCSR< double, Index > & matrix, const LAFEM::DenseVector< double, Index > & weight_vector) inline
Creates a new UmfpackMean solver object.
Parameters
[in] matrix The system matrix.
[in] weight_vector The weight vector to be used as a Lagrange multiplier.
Returns
A shared pointer to a new UmfpackMean object.
Definition at line 230 of file umfpack.hpp.
new_umfpack_mean() [2/2]
std::shared_ptr< UmfpackMean > FEAT::Solver::new_umfpack_mean (const LAFEM::SparseMatrixCSR< double, Index > & matrix, const LAFEM::MeanFilter< double, Index > & filter) inline
Creates a new UmfpackMean solver object.
Parameters
[in] matrix The system matrix.
[in] filter A reference to the mean filter containing the weight vector.
Returns
A shared pointer to a new UmfpackMean object.
Definition at line 249 of file umfpack.hpp.
new_uzawa_precond()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename FilterV_ , typename FilterP_ > std::shared_ptr< UzawaPrecond< MatrixA_, MatrixB_, MatrixD_, FilterV_, FilterP_ > > FEAT::Solver::new_uzawa_precond (const MatrixA_ & matrix_a, const MatrixB_ & matrix_b, const MatrixD_ & matrix_d, const FilterV_ & filter_v, const FilterP_ & filter_p, std::shared_ptr< SolverBase< typename MatrixB_::VectorTypeL > > solver_a, std::shared_ptr< SolverBase< typename MatrixD_::VectorTypeL > > solver_s, UzawaType type = UzawaType::diagonal, bool auto_init_s = true) inline
Creates a new UzawaPrecond solver object.
Parameters
[in] matrix_a,matrix_b,matrix_d The three sub-matrices of the saddle-point system matrix.
[in] filter_v,filter_p The two sub-filters of the system.
[in] solver_a The solver object for the A-matrix block.
[in] solver_s The solver object for the S-matrix block.
[in] type Specifies the type of the preconditioner.
[in] auto_init_s Specifies whether to automatically initialize the S-matrix solver.
Returns
A shared pointer to a new UzawaPrecond object.
Compiler Hack:
GCC < 4.9 fails to deduct shared_ptr
Definition at line 703 of file uzawa_precond.hpp.
new_vanka()
template<typename MatrixA_ , typename MatrixB_ , typename MatrixD_ , typename Filter_ > std::shared_ptr< Vanka< LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ >, Filter_ > > FEAT::Solver::new_vanka (const LAFEM::SaddlePointMatrix< MatrixA_, MatrixB_, MatrixD_ > & matrix, const Filter_ & filter, VankaType type, typename MatrixA_::DataType omega = typename MatrixA_::DataType(1), Index num_iter = Index(1))
Creates a new Vanka solver object.
Parameters
[in] matrix The saddle-point system matrix.
[in] filter The system filter
[in] type Specifies the Vanka type.
[in] omega The relaxation parameter.
[in] num_iter The number of Vanka iterations to be performed.
Returns
A shared pointer to a new Vanka object.
Definition at line 1997 of file vanka.hpp.
new_voxel_amavanka()
template<typename Matrix_ , typename Filter_ , typename ColoringType_ , FEAT::Intern::VankaAssemblyPolicy pol_threading_ = FEAT::Intern::VankaAssemblyPolicy::batchedAssembly, FEAT::Intern::VankaMacroPolicy macro_type_ = FEAT::Intern::VankaMacroPolicy::uniformMacros> std::shared_ptr< VoxelAmaVanka< Matrix_, Filter_, pol_threading_, macro_type_ > > FEAT::Solver::new_voxel_amavanka (const Matrix_ & matrix, const Filter_ & filter, const ColoringType_ & coloring, typename Matrix_::DataType omega = typename Matrix_::DataType(1), Index num_steps = Index(1))
Creates a new VoxelAmaVanka smoother object.
Parameters
[in] matrix The system matrix.
[in] filter The system filter
[in] coloring The coloring of the voxel array.
[in] omega The damping parameter.
[in] num_steps The number of Vanka iterations to be performed.
Returns
A shared pointer to a new AmaVanka object.
Definition at line 639 of file voxel_amavanka.hpp.
solve() [1/2]
template<typename Vector_ , typename Matrix_ , typename Filter_ > Status FEAT::Solver::solve (IterativeSolver< Vector_ > & solver, Vector_ & vec_sol, const Vector_ & vec_rhs, const Matrix_ & matrix, const Filter_ & filter) inline
Override of solve() for IterativeSolver solvers.
Definition at line 934 of file iterative.hpp.
References FEAT::Solver::IterativeSolver< Vector_ >::correct().
solve() [2/2]
template<typename Vector_ , typename Matrix_ , typename Filter_ > Status FEAT::Solver::solve (SolverBase< Vector_ > & solver, Vector_ & vec_sol, const Vector_ & vec_rhs, const Matrix_ & matrix, const Filter_ & filter) inline
Solve linear system with initial solution guess.
Parameters
[in] solver The solver object that is to be used for solving the system.
[in,out] vec_sol The solution vector containing an initial guess.
[in] vec_rhs The right-hand-side vector of the linear system.
[in] matrix The matrix of the linear system.
[in] filter The filter of the linear system.
Attention
vec_sol and vec_rhs must not refer to the same vector object!
Returns
A status code representing the status of the solving step.
Definition at line 349 of file base.hpp.
References FEAT::Solver::SolverBase< Vector_ >::apply(), FEAT::LAFEM::Layout, and status_success().
Referenced by FEAT::Control::Meshopt::DuDvFunctionalControl< DT_, IT_, DomainControl_ >::apply().
status_success()
bool FEAT::Solver::status_success (Status status) inline
Status success check function.
This function takes a Status value as input and checks whether it represents a 'successful' run. A solving run is interpreted as successful, if one of the following status codes was returned:
Status::success
Status::max_iter
Status::stagnated
For any other status code, the solving run is interpreted as unsuccessful.
Parameters
[in] status A status code returned by a solver.
Returns
true, if the run was successful, otherwise false.
Definition at line 110 of file base.hpp.
References max_iter, stagnated, and success.
Referenced by FEAT::Solver::MultiGrid< SystemMatrix_, SystemFilter_, TransferOperator_ >::_apply_coarse(), FEAT::Solver::PreconditionedIterativeSolver< Vector_ >::_apply_precond(), FEAT::Solver::SchwarzPrecond< Global::Vector< LocalVector_, Mirror_ >, Global::Filter< LocalFilter_, Mirror_ > >::apply(), FEAT::Solver::ConvertPrecond< VectorOuter_, VectorInner_ >::apply(), FEAT::Solver::ConvertPrecond< Global::Vector< LocalVectorOuter_, MirrorOuter_ >, Global::Vector< LocalVectorInner_, MirrorInner_ > >::apply(), and solve().