FEAT: FEAT::Geometry Namespace Reference
FEAT::Geometry Namespace Reference
Geometry namespace.
Namespaces
namespace Atlas
Atlas namespace.
Classes
struct AdaptionStats
Statistics about entities added, removed, and kept during a mesh adaption.
class AdaptiveChildMapping
Adjactor for iterating over children of adaptive mesh elements.
class AdaptiveExportVTU
class AdaptiveExportVTU< Geometry::AdaptiveMesh< TemplateSet_, Shape_ > >
class AdaptiveIndexSet
IndexSet interface for adaptive meshes.
class AdaptiveIndexSetHolder
IndexSetHolder interface for adaptive meshes.
class AdaptiveIndexSetHolder< AdaptiveMeshType_, Shape::Vertex >
class AdaptiveIndexSetWrapper
class AdaptiveIndexSetWrapper< AdaptiveMeshType_, Shape_, 0 >
class AdaptiveIndexTuple
IndexTuple interface for adaptive meshes.
class AdaptiveMesh
Dynamic mesh data structure.
class AdaptiveMeshLayer
ConformalMesh interface for adaptive meshes.
class AdaptiveNeighbors
Gives access to neighbor information on a mesh layer.
class AdaptiveVertexSet
VertexSet interface for adaptive meshes.
class AttributeSet
Container for saving data related to mesh entities.
class BoundaryFactory
BoundaryFactory implementation.
class CGALWrapper
Wrapper for the CGAL Library.
class ChartHitTestFactory
Chart-based Hit-Test Factory class template.
class ConformalMesh
Conformal mesh class template.
struct DimensionalChartHelper
World dimension dependent helper class for parsing charts.
class DistributedMeshDistortion
Distributed mesh distortion class template.
struct EntityReference
Reference to another local mesh entity.
struct EntitySearchEntry
Tuple of raw entity and corresponding reference.
class ExportEPS
EPS exporter class.
class ExportSVG
SVG exporter class.
class ExportVTK
VTK exporter class template.
class FacetFlipper
Helper class for reorienting boundary facets to be positive.
class Factory
Mesh Factory class template.
class Factory< ConformalMesh< Shape_, num_coords_, CoordType_ > >
Factory specialization for ConformalMesh class template.
class Factory< MeshPart< MeshType_ > >
Factory specialization for MeshPart class template.
class Factory< StructuredMesh< shape_dim_, num_coords_, Coord_ > >
Factory specialization for StructuredMesh class template.
class GlobalMaskedBoundaryFactory
GlobalMaskedBoundaryFactory implementation.
class HitTestFactory
Hit-Test Factory class template.
class IndexCalculator
Calculates the missing index sets if the vertex-at-shape index sets are given.
class IndexSet
Conformal Index-Set class template.
class IndexTree
Stores the index representatives of an index set.
struct IndexTuple
Index Tuple class template.
class IsolatedPointRefinementType
class IsolatedPointTemplateSet
Schneiders template set for adaptive mesh refinement.
struct IsolatedPointVertexMarking
class LambdaHitTestFactory
Lambda Hit-Test Factory class template.
class MacroFactory
class MaskedBoundaryFactory
MaskedBoundaryFactory implementation.
class MeshAtlas
Mesh Atlas class template.
class MeshDistortion
(Unpartitioned) mesh distortion class template
class MeshExtruder
class MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >
Quadrilateral-to-Hexahedral mesh extruder.
class MeshExtruderFactory
class MeshExtruderFactory< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >
Mesh Extruder factory.
class MeshFileReader
Mesh file reader class.
class MeshFileWriter
Mesh file writer class.
class MeshNode
Mesh Node base class.
class MeshNodeLinker
MeshNode liner class template.
class MeshNodeLinkerError
MeshNodeLinker Error class.
class MeshPart
Class template for partial meshes.
class MeshPartExtruderFactory
class MeshPartExtruderFactory< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >
MeshPart Extruder factory.
class MeshPartNode
MeshPart mesh tree node class template.
class MeshPartSliceExtruderFactory
class MeshPartSliceExtruderFactory< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >
MeshPart Extruder factory.
class MeshPermutation
Mesh permutation class template.
struct MeshQualityHeuristic
Helper class for computing heuristic mesh quality.
class OrientationMapping
Mapping between different orientations of a refinement template.
struct OrientationMappingHolder
Dimension-recursive container for OrientationMappingWrappers.
struct OrientationMappingHolder< RawData_, Shape::Vertex >
Dimension-recursive container for OrientationMappingWrappers.
struct OrientationMappingWrapper
Dimension-recursive container for OrientationMappings.
struct OrientationMappingWrapper< RawData_, Shape_, 0 >
Dimension-recursive container for OrientationMappings.
class ParsedHitTestFactory
Parsed-Hit-Test Factory class template.
class Parti2Lvl
2-Level-Partitioner class template declaration
class Parti2Lvl< ConformalMesh< Shape_, num_coords_, Coord_ > >
2-Level-Partitioner class template specialization for ConformalMesh
class PartiIterative
Iterative-Partitioner class template declaration.
class PartiIterative< ConformalMesh< Shape_, num_coords_, Coord_ > >
Iterative-Partitioner class template specialization for ConformalMesh.
class PartiParMETIS
ParMETIS mesh/graph partitioner backend.
class Partition
Partition class.
class PartitionSet
Partition set class.
class PartiZoltan
Zoltan hypergraph partitioner backend.
class PatchHaloFactory
class PatchHaloFactory< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >
Factory for creating halo mesh-parts between neighbor patches on a base-mesh.
class PatchHaloSplitter
Base-Mesh Patch Halo splitter.
class PatchHaloSplitter< ConformalMesh< Shape_, num_coords_, Coord_ > >
Base-Mesh Patch Halo splitter implementation for ConformalMesh.
class PatchMeshFactory
class PatchMeshPartFactory
Factory for building a PatchBaseMesh from a given partitioning.
class PatchMeshPartSplitter
Class for creating MeshParts referring to a patch BaseMesh.
class PatchMeshPartSplitter< Geometry::ConformalMesh< Shape_, num_coords_, Coord_ > >
Class for creating MeshParts referring to a patch BaseMesh, ConformalMesh specialization.
class PatchPartMap
Mapping class for BaseMesh/PatchBaseMesh and MeshPart index conversions.
class PatchPartMapHolder
This is a container class for holding PatchPartMaps for all dimensions.
class PolylineFactory
Constructs a polyline mesh.
struct RawEntity
struct RawTemplate
class RedundantIndexSetBuilder
Builder for redundant index sets.
class ReferenceCellFactory
Reference Cell Mesh factory.
class RefineFactory
Refine mesh factory.
struct RefinementTemplate
Template for refining a mesh entity.
struct RefinementTemplate< Shape_, Shape::Vertex >
Template for refining a mesh entity.
class RootMeshNode
Root mesh node class template.
class SchneidersData
class ShapeConvertFactory
Shape-Conversion Mesh Factory class template.
class ShapeConvertFactory< ConformalMesh< Shape_, num_coords_, Coord_ > >
ShapeConvertFactory implementation for ConformalMesh.
class ShapeConvertFactory< MeshPart< ConformalMesh< Shape_, Shape_::dimension, Coord_ > > >
ShapeConvertFactory implementation for ConformalMesh.
class SphereHitTestFunction
Sphere hit-test function.
class StandardRefinementType
class StandardRefinery
Standard Refinery class template.
class StandardRefinery< ConformalMesh< Shape_, num_coords_, CoordType_ > >
StandardRefinery implementation for ConformalMesh.
class StandardRefinery< MeshPart< ParentMesh_ > >
*‍/
class StandardRefinery< StructuredMesh< shape_dim_, num_coords_, Coord_ > >
StandardRefinery implementation for StructuredMesh.
class StandardTemplateSet
Schneiders template set for adaptive mesh refinement.
class StructIndexSet
Structured Index-Set class template.
class StructUnitCubeFactory
Structured unit-cube mesh factory.
class StructuredMesh
Structured mesh class template.
class SubdivisionLevels
Subdivision level markings for meshes.
struct SubdivisionLevelTuple
Tuple-type for SubdivisionLevels.
class SunZhaoMaData
class SunZhaoMaExpansionData
class TargetSet
Target set class.
class TemplateBuilder
Constructs RefinementTemplates from RawTemplates.
class TemplateSearchSpace
Mapping between RawEntities and EntityReferences.
class TemplateSearchSpace< Shape::Vertex, num_coords_ >
Mapping between RawEntities and EntityReferences.
struct TopologyTemplate
Construction rule for a single entities topology.
struct TopologyTemplate< Shape_, 0 >
Construction rule for a single entities topology.
class TwoRefinementData
class UnitCubeFactory
Unit-Cube mesh factory.
class UnitCubePatchGenerator
class UnitSphereFactory
class UnitStarCubeFactory
Unit cube factory with star shaped mesh topology.
struct VertexMarking
struct VertexSet
Fixed-Sized Vertex Set class template.
class VoxelCGALMasker
Voxel masker implementation for CGAL wrapper.
class VoxelChartMasker
Voxel masker implementation for chart classes.
class VoxelFormulaMasker
Voxel masker implementation for function parser expression tests.
class VoxelLambdaMasker
Voxel masker implementation for lambda expression tests.
class VoxelMap
VoxelMap class.
class VoxelMapFileError
Error class for VoxelMap related file errors.
class VoxelMapFormulaParseError
Error class for VoxelMap related formula parsing errors.
class VoxelMasker
Interface for voxel masker for the VoxelMap class.
Typedefs
typedef std::int64_t i64
signed 64-bit integer type
using Layer = Intern::Layer
Re-export of layer type.
template<typename MeshType_ >
using RefinedUnitCubeFactory = RefineFactory< MeshType_, Geometry::UnitCubeFactory >
template<typename MeshType_ >
using RefinedUnitSphereFactory = RefineFactory< MeshType_, Geometry::UnitSphereFactory >
using SchneidersTemplates = StandardTemplateSet< SchneidersData >
using SunZhaoMaExpansionTemplates = IsolatedPointTemplateSet< SunZhaoMaExpansionData >
using SunZhaoMaTemplates = IsolatedPointTemplateSet< SunZhaoMaData >
using TwoRefinementTemplates = StandardTemplateSet< TwoRefinementData >
typedef std::uint64_t u64
unsigned 64-bit integer type
Enumerations
enum class AdaptMode { none = 0x0 , chart = 0x1 , dual = 0x2 }
Adapt mode enumeration.
enum class CGALFileMode { fm_off = 0 , fm_obj }
enum class EntitySource : std::uint8_t { ParentTopology , Sibling , BoundaryEdge , BoundaryFace }
Enumeration of possible entity sources.
enum class PermutationStrategy {
none = 0 , other , random , lexicographic ,
colored , cuthill_mckee , cuthill_mckee_reversed , geometric_cuthill_mckee ,
geometric_cuthill_mckee_reversed
}
Mesh permutation strategy enumeration.
Functions
template<typename TemplateMap , typename RefinementType_ >
int create_2dtemplate_rotations (TemplateMap &map, const RefinementType_ &base_type)
template<typename TemplateMap , typename RefinementType_ >
int create_3dtemplate_rotations (TemplateMap &map, const RefinementType_ &base_type)
template<typename Mesh_ >
MeshPart< Mesh_ > make_boundary_meshpart (const Mesh_ &mesh)
Creates a new boundary mesh-part for a given mesh.
template<typename Mesh_ , typename Chart_ >
MeshPart< Mesh_ > make_meshpart_by_chart_hit_test (const Mesh_ &mesh, const Chart_ &chart, bool invert=false)
Creates a new mesh-part from a chart hit-test function.
template<typename Mesh_ , typename HitFunc_ >
MeshPart< Mesh_ > make_meshpart_by_hit_test (const Mesh_ &mesh, const HitFunc_ &hit_func)
Creates a new mesh-part from a hit-test function.
template<typename Mesh_ , typename Lambda_ >
MeshPart< Mesh_ > make_meshpart_by_lambda_hit_test (const Mesh_ &mesh, Lambda_ &&lambda)
Creates a new mesh-part from a lambda hit-test function.
template<typename Mesh_ >
std::unique_ptr< MeshPart< Mesh_ > > make_unique_boundary_meshpart (const Mesh_ &mesh)
Creates a new boundary mesh-part for a given mesh.
template<typename Mesh_ , typename Chart_ >
std::unique_ptr< MeshPart< Mesh_ > > make_unique_meshpart_by_chart_hit_test (const Mesh_ &mesh, const Chart_ &chart, bool invert=false)
Creates a new mesh-part from a chart hit-test function.
template<typename Mesh_ , typename HitFunc_ >
std::unique_ptr< MeshPart< Mesh_ > > make_unique_meshpart_by_hit_test (const Mesh_ &mesh, const HitFunc_ &hit_func)
Creates a new mesh-part from a hit-test function.
template<typename Mesh_ , typename Lambda_ >
std::unique_ptr< MeshPart< Mesh_ > > make_unique_meshpart_by_lambda_hit_test (const Mesh_ &mesh, Lambda_ &&lambda)
Creates a new mesh-part from a lambda hit-test function.
template void MeshFileReader::parse< ConformalMesh< Shape::Hypercube< 2 >, 2, Real > > (MeshNodeLinker< ConformalMesh< Shape::Hypercube< 2 >, 2, Real > > &, RootMeshNode< ConformalMesh< Shape::Hypercube< 2 >, 2, Real > > &, MeshAtlas< ConformalMesh< Shape::Hypercube< 2 >, 2, Real > > &, PartitionSet *)
template void MeshFileReader::parse< ConformalMesh< Shape::Hypercube< 3 >, 3, Real > > (MeshNodeLinker< ConformalMesh< Shape::Hypercube< 3 >, 3, Real > > &, RootMeshNode< ConformalMesh< Shape::Hypercube< 3 >, 3, Real > > &, MeshAtlas< ConformalMesh< Shape::Hypercube< 3 >, 3, Real > > &, PartitionSet *)
template void MeshFileReader::parse< ConformalMesh< Shape::Simplex< 2 >, 2, Real > > (MeshNodeLinker< ConformalMesh< Shape::Simplex< 2 >, 2, Real > > &, RootMeshNode< ConformalMesh< Shape::Simplex< 2 >, 2, Real > > &, MeshAtlas< ConformalMesh< Shape::Simplex< 2 >, 2, Real > > &, PartitionSet *)
template void MeshFileReader::parse< ConformalMesh< Shape::Simplex< 3 >, 3, Real > > (MeshNodeLinker< ConformalMesh< Shape::Simplex< 3 >, 3, Real > > &, RootMeshNode< ConformalMesh< Shape::Simplex< 3 >, 3, Real > > &, MeshAtlas< ConformalMesh< Shape::Simplex< 3 >, 3, Real > > &, PartitionSet *)
bool operator!= (const EntityReference &lhs, const EntityReference &rhs)
Not-equals operator for EntityReferences.
template<typename Shape_ >
bool operator!= (const IsolatedPointRefinementType< Shape_ > &lhs, const IsolatedPointRefinementType< Shape_ > &rhs)
bool operator!= (const IsolatedPointVertexMarking &a, const IsolatedPointVertexMarking &b)
template<typename Shape_ >
bool operator!= (const StandardRefinementType< Shape_ > &lhs, const StandardRefinementType< Shape_ > &rhs)
template<typename Shape_ >
bool operator!= (const VertexMarking< Shape_ > &lhs, const VertexMarking< Shape_ > &rhs)
std::ostream & operator<< (std::ostream &os, const SubdivisionLevels &sdls)
Debug output operator for SubdivisionLevels.
std::ostream & operator<< (std::ostream &stream, const EntityReference &reference)
Output operator for EntityReferences.
template<typename Shape_ , int num_coords_>
std::ostream & operator<< (std::ostream &stream, const EntitySearchEntry< Shape_, num_coords_ > &entry)
Output-operator for EntitySearchEntry.
template<typename Shape_ >
std::ostream & operator<< (std::ostream &stream, const IsolatedPointRefinementType< Shape_ > &type)
std::ostream & operator<< (std::ostream &stream, const IsolatedPointVertexMarking &marking)
template<typename Shape_ , int num_coords_>
std::ostream & operator<< (std::ostream &stream, const RawEntity< Shape_, num_coords_ > &entity)
template<typename Shape_ >
std::ostream & operator<< (std::ostream &stream, const StandardRefinementType< Shape_ > &type)
template<typename Shape_ >
std::ostream & operator<< (std::ostream &stream, const VertexMarking< Shape_ > &type)
std::ostream & operator<< (std::ostream &stream, EntitySource source)
Output operator for EntitySource.
bool operator== (const EntityReference &lhs, const EntityReference &rhs)
Equals operator for EntityReferences.
template<typename Shape_ >
bool operator== (const IsolatedPointRefinementType< Shape_ > &lhs, const IsolatedPointRefinementType< Shape_ > &rhs)
bool operator== (const IsolatedPointVertexMarking &a, const IsolatedPointVertexMarking &b)
template<typename Shape_ >
bool operator== (const StandardRefinementType< Shape_ > &lhs, const StandardRefinementType< Shape_ > &rhs)
template<typename Shape_ >
bool operator== (const VertexMarking< Shape_ > &lhs, const VertexMarking< Shape_ > &rhs)
template<typename Shape_ >
static RawTemplate< Shape_ > rotate_template_2d (RawTemplate< Shape_ > &tmplt)
Rotates a raw template 90 degrees counterclockwise around (0.5, 0.5)
template<typename Shape_ >
static RawTemplate< Shape_ > rotate_template_xaxis (RawTemplate< Shape_ > &tmplt)
Rotates a raw template 90 degrees counterclockwise around the x-axis.
template<typename Shape_ >
static RawTemplate< Shape_ > rotate_template_yaxis (RawTemplate< Shape_ > &tmplt)
Rotates a raw template 90 degrees counterclockwise around the y-axis.
template<typename Shape_ >
static RawTemplate< Shape_ > rotate_template_zaxis (RawTemplate< Shape_ > &tmplt)
Rotates a raw template 90 degrees counterclockwise around the z-axis.
template<typename Shape_ , typename FnVert , typename FnEntity >
static RawTemplate< Shape_ > transform_template_vertices (FnVert vertex_transform, FnEntity entity_transform, RawTemplate< Shape_ > &tmplt)
Detailed Description
Geometry namespace.
Typedef Documentation
i64
typedef std::int64_t FEAT::Geometry::i64
signed 64-bit integer type
Definition at line 19 of file voxel_map.cpp.
Layer
using FEAT::Geometry::Layer = typedef Intern::Layer
Re-export of layer type.
Definition at line 39 of file adaptive_mesh.hpp.
RefinedUnitCubeFactory
template<typename MeshType_ > using FEAT::Geometry::RefinedUnitCubeFactory = typedef RefineFactory<MeshType_, Geometry::UnitCubeFactory >
Definition at line 562 of file common_factories.hpp.
RefinedUnitSphereFactory
template<typename MeshType_ > using FEAT::Geometry::RefinedUnitSphereFactory = typedef RefineFactory<MeshType_, Geometry::UnitSphereFactory>
Definition at line 1428 of file common_factories.hpp.
SchneidersTemplates
using FEAT::Geometry::SchneidersTemplates = typedef StandardTemplateSet<SchneidersData>
Definition at line 42 of file adaptive_mesh.hpp.
SunZhaoMaExpansionTemplates
using FEAT::Geometry::SunZhaoMaExpansionTemplates = typedef IsolatedPointTemplateSet<SunZhaoMaExpansionData>
Definition at line 44 of file adaptive_mesh.hpp.
SunZhaoMaTemplates
using FEAT::Geometry::SunZhaoMaTemplates = typedef IsolatedPointTemplateSet<SunZhaoMaData>
Definition at line 43 of file adaptive_mesh.hpp.
TwoRefinementTemplates
using FEAT::Geometry::TwoRefinementTemplates = typedef StandardTemplateSet<TwoRefinementData>
Definition at line 45 of file adaptive_mesh.hpp.
u64
typedef std::uint64_t FEAT::Geometry::u64
unsigned 64-bit integer type
Definition at line 21 of file voxel_map.cpp.
Enumeration Type Documentation
AdaptMode
enum class FEAT::Geometry::AdaptMode strong
Adapt mode enumeration.
Definition at line 50 of file mesh_node.hpp.
CGALFileMode
enum class FEAT::Geometry::CGALFileMode strong
Enumerator
fm_off
OFF
fm_obj
OBJ
Definition at line 20 of file cgal.hpp.
EntitySource
enum class FEAT::Geometry::EntitySource : std::uint8_t strong
Enumeration of possible entity sources.
During adaptive refinement, entity topologies have to be found. This enum indicates where an entity can be found.
Enumerator
ParentTopology
Entity is part of the parents topology.
Sibling
Entity is a sibling in the refinement tree.
BoundaryEdge
Entity is part of a boundary edge, i.e. a child of one of the parents edges.
BoundaryFace
Entity is part of a boundary face, i.e. a child of one of the parents faces.
Definition at line 449 of file template_builder.hpp.
PermutationStrategy
enum class FEAT::Geometry::PermutationStrategy strong
Mesh permutation strategy enumeration.
Enumerator
none
no permutation strategy
This value indicates that the mesh has not been permuted.
other
generic/other permutation strategy
This value indicates that the mesh has been permuted by some strategy other than any of the standard permutation strategies.
This value can be used by user-defined sorting strategies.
random
random permutation strategy
This value indicates that all mesh entities have been permuted by using a pseudo-random number generator.
This permutation strategy usually represents a worst-case scenario and is therefore primarily only of interest for benchmarking.
lexicographic
lexicographic permutation strategy
This value indicates that all mesh entities have been sorted in lexicographic order, i.e. the entities are sorted by the partial ordering based on their X (1D), Y-X (2D) or Z-Y-X (3D) coordinates of the entity barycenters.
Note
The lexicographic order in 2D/3D is defined as:
2D: (x1,y1) < (x2,y2) :<==> (y1 < y2) or ((y1 == y2) and (x1 < x2))
3D: (x1,y1,z1) < (x2,y2,z2) :<==> (z1 < z2) or ((z1 == z2) and ((y1 < y2) or ((y1 == y2) and (x1 < x2))))
colored
colored permutation strategy a.k.a. "red-black" strategy
This value indicates that the mesh elements have been sorted based on a coloring of the elements.
This permutation strategy will automatically create an element coloring; see the documentation of the MeshPermutation class for more information.
Note
This permutation strategy is only applied to the mesh elements (cells of highest dimension), i.e. all sub-dimensional entities are left unpermuted.
cuthill_mckee
(algebraic) Cuthill-McKee permutation strategy
This value indicates that the mesh elements have been sorted based on an algebraic Cuthill-McKee ordering of the elements-neighbors-via-common-vertex adjacency graph.
This permutation strategy will automatically create an element layering; see the documentation of the MeshPermutation class for more information.
Note
This permutation strategy is only applied to the mesh elements (cells of highest dimension), i.e. all sub-dimensional entities are left unpermuted.
cuthill_mckee_reversed
reversed (algebraic) Cuthill-McKee permutation strategy
This value indicates that the mesh elements have been sorted based on a reversed algebraic Cuthill-McKee ordering of the elements-neighbors-via-common-vertex adjacency graph.
This permutation strategy will automatically create an element layering; see the documentation of the MeshPermutation class for more information.
Note
This permutation strategy is only applied to the mesh elements (cells of highest dimension), i.e. all sub-dimensional entities are left unpermuted.
geometric_cuthill_mckee
geometric Cuthill-McKee permutation strategy
This value indicates that all mesh entities have been sorted based on a geometric Cuthill-McKee ordering.
This permutation strategy will automatically create an element layering; see the documentation of the MeshPermutation class for more information.
geometric_cuthill_mckee_reversed
reversed geometric Cuthill-McKee permutation strategy
This value indicates that all mesh entities have been sorted based on a reversed geometric Cuthill-McKee ordering.
This permutation strategy will automatically create an element layering; see the documentation of the MeshPermutation class for more information.
Definition at line 190 of file mesh_permutation.hpp.
Function Documentation
create_2dtemplate_rotations()
template<typename TemplateMap , typename RefinementType_ > int FEAT::Geometry::create_2dtemplate_rotations (TemplateMap & map, const RefinementType_ & base_type)
Definition at line 308 of file raw_refinement_templates.hpp.
create_3dtemplate_rotations()
template<typename TemplateMap , typename RefinementType_ > int FEAT::Geometry::create_3dtemplate_rotations (TemplateMap & map, const RefinementType_ & base_type)
Definition at line 332 of file raw_refinement_templates.hpp.
make_boundary_meshpart()
template<typename Mesh_ > MeshPart< Mesh_ > FEAT::Geometry::make_boundary_meshpart (const Mesh_ & mesh)
Creates a new boundary mesh-part for a given mesh.
Parameters
[in] mesh A transient reference to the mesh for which a boundary mesh-part is to be created.
Returns
A mesh-part containing all entities for which lie on the mesh boundary
Definition at line 104 of file boundary_factory.hpp.
make_meshpart_by_chart_hit_test()
template<typename Mesh_ , typename Chart_ > MeshPart< Mesh_ > FEAT::Geometry::make_meshpart_by_chart_hit_test (const Mesh_ & mesh, const Chart_ & chart, bool invert = false)
Creates a new mesh-part from a chart hit-test function.
Parameters
[in] mesh A transient reference to the mesh for which a mesh-part is to be created.
[in] chart A chart object whose signed-distance function is to be used for hit-testing.
Returns
A mesh-part containing all entities for which the chart signed distance is <= 0.
Definition at line 479 of file hit_test_factory.hpp.
make_meshpart_by_hit_test()
template<typename Mesh_ , typename HitFunc_ > MeshPart< Mesh_ > FEAT::Geometry::make_meshpart_by_hit_test (const Mesh_ & mesh, const HitFunc_ & hit_func)
Creates a new mesh-part from a hit-test function.
Parameters
[in] mesh A transient reference to the mesh for which a mesh-part is to be created.
[in] hit_func An object implementing the hit-test function interface.
Returns
A mesh-part containing all entities for which the hit-test function evaluated to true.
Definition at line 126 of file hit_test_factory.hpp.
make_meshpart_by_lambda_hit_test()
template<typename Mesh_ , typename Lambda_ > MeshPart< Mesh_ > FEAT::Geometry::make_meshpart_by_lambda_hit_test (const Mesh_ & mesh, Lambda_ && lambda)
Creates a new mesh-part from a lambda hit-test function.
Parameters
[in] mesh A transient reference to the mesh for which a mesh-part is to be created.
[in] lambda A lambda expression in X/Y/Z coordinates that returns true, if a point is inside, otherwise false.
Returns
A mesh-part containing all entities for which the lambda evaluated to true.
Definition at line 624 of file hit_test_factory.hpp.
make_unique_boundary_meshpart()
template<typename Mesh_ > std::unique_ptr< MeshPart< Mesh_ > > FEAT::Geometry::make_unique_boundary_meshpart (const Mesh_ & mesh)
Creates a new boundary mesh-part for a given mesh.
Parameters
[in] mesh A transient reference to the mesh for which a boundary mesh-part is to be created.
Returns
A mesh-part containing all entities for which lie on the mesh boundary
Definition at line 120 of file boundary_factory.hpp.
make_unique_meshpart_by_chart_hit_test()
template<typename Mesh_ , typename Chart_ > std::unique_ptr< MeshPart< Mesh_ > > FEAT::Geometry::make_unique_meshpart_by_chart_hit_test (const Mesh_ & mesh, const Chart_ & chart, bool invert = false)
Creates a new mesh-part from a chart hit-test function.
Parameters
[in] mesh A transient reference to the mesh for which a mesh-part is to be created.
[in] chart A chart object whose signed-distance function is to be used for hit-testing.
Returns
A unique-pointer to a mesh-part containing all entities for which the chart signed distance is <= 0.
Definition at line 498 of file hit_test_factory.hpp.
make_unique_meshpart_by_hit_test()
template<typename Mesh_ , typename HitFunc_ > std::unique_ptr< MeshPart< Mesh_ > > FEAT::Geometry::make_unique_meshpart_by_hit_test (const Mesh_ & mesh, const HitFunc_ & hit_func)
Creates a new mesh-part from a hit-test function.
Parameters
[in] mesh A transient reference to the mesh for which a mesh-part is to be created.
[in] hit_func An object implementing the hit-test function interface.
Returns
A unique-pointer to a mesh-part containing all entities for which the hit-test function evaluated to true.
Definition at line 145 of file hit_test_factory.hpp.
make_unique_meshpart_by_lambda_hit_test()
template<typename Mesh_ , typename Lambda_ > std::unique_ptr< MeshPart< Mesh_ > > FEAT::Geometry::make_unique_meshpart_by_lambda_hit_test (const Mesh_ & mesh, Lambda_ && lambda)
Creates a new mesh-part from a lambda hit-test function.
Parameters
[in] mesh A transient reference to the mesh for which a mesh-part is to be created.
[in] lambda A lambda expression in X/Y/Z coordinates that returns true, if a point is inside, otherwise false.
Returns
A unique-pointer to a mesh-part containing all entities for which the lambda evaluated to true.
Definition at line 643 of file hit_test_factory.hpp.
operator!=() [1/5]
bool FEAT::Geometry::operator!= (const EntityReference & lhs, const EntityReference & rhs)
Not-equals operator for EntityReferences.
Definition at line 501 of file template_builder.hpp.
operator!=() [2/5]
template<typename Shape_ > bool FEAT::Geometry::operator!= (const IsolatedPointRefinementType< Shape_ > & lhs, const IsolatedPointRefinementType< Shape_ > & rhs)
Definition at line 382 of file refinement_types.hpp.
operator!=() [3/5]
bool FEAT::Geometry::operator!= (const IsolatedPointVertexMarking & a, const IsolatedPointVertexMarking & b) inline
Definition at line 252 of file refinement_types.hpp.
operator!=() [4/5]
template<typename Shape_ > bool FEAT::Geometry::operator!= (const StandardRefinementType< Shape_ > & lhs, const StandardRefinementType< Shape_ > & rhs)
Definition at line 223 of file refinement_types.hpp.
operator!=() [5/5]
template<typename Shape_ > bool FEAT::Geometry::operator!= (const VertexMarking< Shape_ > & lhs, const VertexMarking< Shape_ > & rhs)
Definition at line 101 of file refinement_types.hpp.
operator<<() [1/9]
std::ostream & FEAT::Geometry::operator<< (std::ostream & os, const SubdivisionLevels & sdls) inline
Debug output operator for SubdivisionLevels.
Debug output operator.
Definition at line 247 of file subdivision_levels.hpp.
operator<<() [2/9]
std::ostream & FEAT::Geometry::operator<< (std::ostream & stream, const EntityReference & reference)
Output operator for EntityReferences.
Definition at line 507 of file template_builder.hpp.
References FEAT::Geometry::EntityReference::entity, FEAT::Geometry::EntityReference::index, FEAT::Geometry::EntityReference::orientation, FEAT::Geometry::EntityReference::source, and FEAT::stringify().
operator<<() [3/9]
template<typename Shape_ , int num_coords_> std::ostream & FEAT::Geometry::operator<< (std::ostream & stream, const EntitySearchEntry< Shape_, num_coords_ > & entry)
Output-operator for EntitySearchEntry.
Definition at line 959 of file template_builder.hpp.
References FEAT::Geometry::EntitySearchEntry< Shape_, num_coords_ >::raw_entity, and FEAT::Geometry::EntitySearchEntry< Shape_, num_coords_ >::reference.
operator<<() [4/9]
template<typename Shape_ > std::ostream & FEAT::Geometry::operator<< (std::ostream & stream, const IsolatedPointRefinementType< Shape_ > & type)
Definition at line 388 of file refinement_types.hpp.
operator<<() [5/9]
std::ostream & FEAT::Geometry::operator<< (std::ostream & stream, const IsolatedPointVertexMarking & marking) inline
Definition at line 257 of file refinement_types.hpp.
operator<<() [6/9]
template<typename Shape_ , int num_coords_> std::ostream & FEAT::Geometry::operator<< (std::ostream & stream, const RawEntity< Shape_, num_coords_ > & entity)
Definition at line 53 of file raw_refinement_templates.hpp.
operator<<() [7/9]
template<typename Shape_ > std::ostream & FEAT::Geometry::operator<< (std::ostream & stream, const StandardRefinementType< Shape_ > & type)
Definition at line 229 of file refinement_types.hpp.
operator<<() [8/9]
template<typename Shape_ > std::ostream & FEAT::Geometry::operator<< (std::ostream & stream, const VertexMarking< Shape_ > & type)
Definition at line 107 of file refinement_types.hpp.
operator<<() [9/9]
std::ostream & FEAT::Geometry::operator<< (std::ostream & stream, EntitySource source) inline
Output operator for EntitySource.
Definition at line 458 of file template_builder.hpp.
References BoundaryEdge, BoundaryFace, ParentTopology, and Sibling.
operator==() [1/5]
bool FEAT::Geometry::operator== (const EntityReference & lhs, const EntityReference & rhs)
Equals operator for EntityReferences.
Definition at line 494 of file template_builder.hpp.
References FEAT::Geometry::EntityReference::entity, FEAT::Geometry::EntityReference::index, FEAT::Geometry::EntityReference::orientation, and FEAT::Geometry::EntityReference::source.
operator==() [2/5]
template<typename Shape_ > bool FEAT::Geometry::operator== (const IsolatedPointRefinementType< Shape_ > & lhs, const IsolatedPointRefinementType< Shape_ > & rhs)
Definition at line 376 of file refinement_types.hpp.
operator==() [3/5]
bool FEAT::Geometry::operator== (const IsolatedPointVertexMarking & a, const IsolatedPointVertexMarking & b) inline
Definition at line 247 of file refinement_types.hpp.
operator==() [4/5]
template<typename Shape_ > bool FEAT::Geometry::operator== (const StandardRefinementType< Shape_ > & lhs, const StandardRefinementType< Shape_ > & rhs)
Definition at line 217 of file refinement_types.hpp.
operator==() [5/5]
template<typename Shape_ > bool FEAT::Geometry::operator== (const VertexMarking< Shape_ > & lhs, const VertexMarking< Shape_ > & rhs)
Definition at line 95 of file refinement_types.hpp.
rotate_template_2d()
template<typename Shape_ > static RawTemplate< Shape_ > FEAT::Geometry::rotate_template_2d (RawTemplate< Shape_ > & tmplt) static
Rotates a raw template 90 degrees counterclockwise around (0.5, 0.5)
Definition at line 213 of file raw_refinement_templates.hpp.
Referenced by FEAT::Geometry::SchneidersData::raw_faces().
rotate_template_xaxis()
template<typename Shape_ > static RawTemplate< Shape_ > FEAT::Geometry::rotate_template_xaxis (RawTemplate< Shape_ > & tmplt) static
Rotates a raw template 90 degrees counterclockwise around the x-axis.
Vertices are transformed such that the template is centered around the origin, then the rotation is applied, then the vertices are transformed back.
Definition at line 239 of file raw_refinement_templates.hpp.
Referenced by FEAT::Geometry::SchneidersData::raw_cells().
rotate_template_yaxis()
template<typename Shape_ > static RawTemplate< Shape_ > FEAT::Geometry::rotate_template_yaxis (RawTemplate< Shape_ > & tmplt) static
Rotates a raw template 90 degrees counterclockwise around the y-axis.
Vertices are transformed such that the template is centered around the origin, then the rotation is applied, then the vertices are transformed back.
Definition at line 264 of file raw_refinement_templates.hpp.
Referenced by FEAT::Geometry::SchneidersData::raw_cells().
rotate_template_zaxis()
template<typename Shape_ > static RawTemplate< Shape_ > FEAT::Geometry::rotate_template_zaxis (RawTemplate< Shape_ > & tmplt) static
Rotates a raw template 90 degrees counterclockwise around the z-axis.
Vertices are transformed such that the template is centered around the origin, then the rotation is applied, then the vertices are transformed back.
Definition at line 289 of file raw_refinement_templates.hpp.
Referenced by FEAT::Geometry::SchneidersData::raw_cells().
transform_template_vertices()
template<typename Shape_ , typename FnVert , typename FnEntity > static RawTemplate< Shape_ > FEAT::Geometry::transform_template_vertices (FnVert vertex_transform, FnEntity entity_transform, RawTemplate< Shape_ > & tmplt) static
Definition at line 190 of file raw_refinement_templates.hpp.