FEAT: FEAT::Meshopt::MeshConcentrationFunctionFactory< Trafo_, RefCellTrafo_ > Struct Template Reference
FEAT::Meshopt::MeshConcentrationFunctionFactory< Trafo_, RefCellTrafo_ > Struct Template Reference
Factory for MeshConcentrationFunctions.
#include <mesh_concentration_function.hpp>
Public Types
typedef MeshType::CoordType CoordType
Floating point precision of the mesh vertex coordinates.
typedef Trafo_::MeshType MeshType
The Meshtype.
Static Public Member Functions
static std::shared_ptr< MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ > > create (const String &section_key, PropertyMap *config)
Creates a MeshConcentrationFunction according to a PropertyMap.
Detailed Description
template<typename Trafo_, typename RefCellTrafo_>
struct FEAT::Meshopt::MeshConcentrationFunctionFactory< Trafo_, RefCellTrafo_ >
Factory for MeshConcentrationFunctions.
Template Parameters
Trafo_ Our transformation.
RefCellTrafo_ Mesh optimization reference cell transformation.
Definition at line 1524 of file mesh_concentration_function.hpp.
Member Typedef Documentation
CoordType
template<typename Trafo_ , typename RefCellTrafo_ > typedef MeshType::CoordType FEAT::Meshopt::MeshConcentrationFunctionFactory< Trafo_, RefCellTrafo_ >::CoordType
Floating point precision of the mesh vertex coordinates.
Definition at line 1529 of file mesh_concentration_function.hpp.
MeshType
template<typename Trafo_ , typename RefCellTrafo_ > typedef Trafo_::MeshType FEAT::Meshopt::MeshConcentrationFunctionFactory< Trafo_, RefCellTrafo_ >::MeshType
The Meshtype.
Definition at line 1527 of file mesh_concentration_function.hpp.
Member Function Documentation
create()
template<typename Trafo_ , typename RefCellTrafo_ > static std::shared_ptr< MeshConcentrationFunctionBase< Trafo_, RefCellTrafo_ > > FEAT::Meshopt::MeshConcentrationFunctionFactory< Trafo_, RefCellTrafo_ >::create (const String & section_key, PropertyMap * config) inline static
Creates a MeshConcentrationFunction according to a PropertyMap.
Parameters
[in] section_key Name of our section in config.
[in] config The PropertyMap holding our configuration
Returns
A shared_ptr to an object derived from MeshConcencentrationFunctionBase.
Definition at line 1543 of file mesh_concentration_function.hpp.
References FEAT::PropertyMap::query_section(), FEAT::String::split_by_whitespaces(), XASSERT, and XASSERTM.
Referenced by FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_hyperelasticity_control_with_cell_functional().
The documentation for this struct was generated from the following file:
kernel/meshopt/mesh_concentration_function.hpp