FEAT: FEAT::Control::Meshopt::MeshoptPrecondFactory Struct Reference
FEAT::Control::Meshopt::MeshoptPrecondFactory Struct Reference
Factory class for specialized preconditioners.
#include <meshopt_precond_factory.hpp>
Static Public Member Functions
template<typename MeshoptCtrl_ , typename DomCtrl_ = typename MeshoptCtrl_::DomainControlType, typename SolverVectorType_ = typename MeshoptCtrl_::SystemLevelType::GlobalSystemVectorL, typename FilterType_ = typename MeshoptCtrl_::SystemLevelType::GlobalSystemFilter>
static std::shared_ptr< Solver::NLOptPrecond< SolverVectorType_, FilterType_ > > create_nlopt_precond (MeshoptCtrl_ &my_ctrl, DomCtrl_ &dom_ctrl, PropertyMap *current_section)
Creates a preconditioner for nonlinear mesh optimization problems.
Detailed Description
Factory class for specialized preconditioners.
Definition at line 25 of file meshopt_precond_factory.hpp.
Member Function Documentation
create_nlopt_precond()
template<typename MeshoptCtrl_ , typename DomCtrl_ = typename MeshoptCtrl_::DomainControlType, typename SolverVectorType_ = typename MeshoptCtrl_::SystemLevelType::GlobalSystemVectorL, typename FilterType_ = typename MeshoptCtrl_::SystemLevelType::GlobalSystemFilter> static std::shared_ptr< Solver::NLOptPrecond< SolverVectorType_, FilterType_ > > FEAT::Control::Meshopt::MeshoptPrecondFactory::create_nlopt_precond (MeshoptCtrl_ & my_ctrl, DomCtrl_ & dom_ctrl, PropertyMap * current_section) inline static
Creates a preconditioner for nonlinear mesh optimization problems.
Template Parameters
MeshoptCtrl_ The type of the control object for mesh optimization
DomCtrl_ The type of the control object for the domain.
SolverVectorType_ The input vector type for the preconditioner.
FilterType_ The filter type for the preconditioner.
Parameters
[in] my_ctrl The mesh optimization control object.
[in] dom_ctrl The domain control object.
[in] current_section The configuration section of the solver this preconditioner is built for.
Returns
An std::shared_ptr to the new NLOptPrecond object.
Definition at line 61 of file meshopt_precond_factory.hpp.
References create_nlopt_precond(), FEAT::PropertyMap::query(), and XABORTM.
Referenced by FEAT::Control::Meshopt::HyperelasticityFunctionalControl< DT_, IT_, DomainControl_, Hyperelasticity_ >::HyperelasticityFunctionalControl(), and create_nlopt_precond().
The documentation for this struct was generated from the following file:
control/meshopt/meshopt_precond_factory.hpp