FEAT: FEAT::Geometry::VertexSet< num_coords_, Coord_ > Struct Template Reference
FEAT::Geometry::VertexSet< num_coords_, Coord_ > Struct Template Reference
Fixed-Sized Vertex Set class template.
#include <vertex_set.hpp>
Public Types
typedef Coord_ CoordType
vertex coordinate type
typedef Tiny::Vector< CoordType, num_coords > VertexType
vertex type
Public Member Functions
VertexSet ()
standard constructor
VertexSet (Index num_vertices)
Constructor.
VertexSet (VertexSet &&other)
move constructor
virtual ~VertexSet ()
virtual destructor
std::size_t bytes () const
VertexSet clone () const
int get_num_coords () const
Returns the number of coordinates per vertex.
Index get_num_vertices () const
Returns the number of vertices in the vertex set.
VertexSet & operator= (VertexSet &&other)
move-assignment operator
VertexType & operator[] (Index i)
Returns a reference to a vertex.
const VertexType & operator[] (Index i) const
Returns a reference to a vertex.
void permute (const Adjacency::Permutation &perm, bool invert=false)
Applies a permutation onto this vertex set.
void transform (const VertexType &origin, const VertexType &angles, const VertexType &offset)
Applies a "proper rigid" transformation onto the vertex set.
Static Public Member Functions
static String name ()
Returns the name of the class.
Static Public Attributes
static constexpr int num_coords = num_coords_
number of coordinates per vertex
Protected Member Functions
VertexSet (const std::vector< VertexType > &vtx)
internal clone constructor
Protected Attributes
std::vector< VertexType > _vertices
vertex vector
Detailed Description
template<int num_coords_, typename Coord_ = Real>
struct FEAT::Geometry::VertexSet< num_coords_, Coord_ >
Fixed-Sized Vertex Set class template.
This class implements a vertex set whose number of coordinates is specified at compile-time.
Template Parameters
num_coords_ The number of coordinates per vertex. Must be > 0.
Coord_ The data type for a vertex coordinate.
Author
Peter Zajac
Definition at line 38 of file vertex_set.hpp.
Member Typedef Documentation
CoordType
template<int num_coords_, typename Coord_ = Real> typedef Coord_ FEAT::Geometry::VertexSet< num_coords_, Coord_ >::CoordType
vertex coordinate type
Definition at line 47 of file vertex_set.hpp.
VertexType
template<int num_coords_, typename Coord_ = Real> typedef Tiny::Vector<CoordType, num_coords> FEAT::Geometry::VertexSet< num_coords_, Coord_ >::VertexType
vertex type
Definition at line 50 of file vertex_set.hpp.
Constructor & Destructor Documentation
VertexSet() [1/4]
template<int num_coords_, typename Coord_ = Real> FEAT::Geometry::VertexSet< num_coords_, Coord_ >::VertexSet (const std::vector< VertexType > & vtx) inline explicit protected
internal clone constructor
Definition at line 84 of file vertex_set.hpp.
VertexSet() [2/4]
template<int num_coords_, typename Coord_ = Real> FEAT::Geometry::VertexSet< num_coords_, Coord_ >::VertexSet () inline
standard constructor
Definition at line 91 of file vertex_set.hpp.
Referenced by FEAT::Geometry::VertexSet< num_coords_, Coord_ >::clone().
VertexSet() [3/4]
template<int num_coords_, typename Coord_ = Real> FEAT::Geometry::VertexSet< num_coords_, Coord_ >::VertexSet (Index num_vertices) inline explicit
Constructor.
Parameters
[in] num_vertices The number of vertices to be allocated in the vertex set.
Definition at line 102 of file vertex_set.hpp.
VertexSet() [4/4]
template<int num_coords_, typename Coord_ = Real> FEAT::Geometry::VertexSet< num_coords_, Coord_ >::VertexSet (VertexSet< num_coords_, Coord_ > && other) inline
move constructor
Definition at line 108 of file vertex_set.hpp.
~VertexSet()
template<int num_coords_, typename Coord_ = Real> virtual FEAT::Geometry::VertexSet< num_coords_, Coord_ >::~VertexSet () inline virtual
virtual destructor
Definition at line 124 of file vertex_set.hpp.
Member Function Documentation
bytes()
template<int num_coords_, typename Coord_ = Real> std::size_t FEAT::Geometry::VertexSet< num_coords_, Coord_ >::bytes () const inline
Returns
The size of dynamically allocated memory in bytes.
Definition at line 135 of file vertex_set.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::_vertices.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::bytes(), and FEAT::Geometry::StructuredMesh< shape_dim_, num_coords_, Coord_ >::bytes().
clone()
template<int num_coords_, typename Coord_ = Real> VertexSet FEAT::Geometry::VertexSet< num_coords_, Coord_ >::clone () const inline
Returns
An independent clone of this vertex set object.
Definition at line 129 of file vertex_set.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::VertexSet().
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::clone().
get_num_coords()
template<int num_coords_, typename Coord_ = Real> int FEAT::Geometry::VertexSet< num_coords_, Coord_ >::get_num_coords () const inline
Returns the number of coordinates per vertex.
Definition at line 141 of file vertex_set.hpp.
get_num_vertices()
template<int num_coords_, typename Coord_ = Real> Index FEAT::Geometry::VertexSet< num_coords_, Coord_ >::get_num_vertices () const inline
Returns the number of vertices in the vertex set.
Definition at line 147 of file vertex_set.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::_vertices.
Referenced by FEAT::Geometry::MeshFileWriter::_write_vertex_set(), FEAT::Geometry::MeshExtruder< ConformalMesh< Shape::Hypercube< 2 >, 2, Coord_ > >::extrude_vertex_set(), and FEAT::Geometry::VertexSet< num_coords_, Coord_ >::operator[]().
name()
template<int num_coords_, typename Coord_ = Real> static String FEAT::Geometry::VertexSet< num_coords_, Coord_ >::name () inline static
Returns the name of the class.
Definition at line 232 of file vertex_set.hpp.
operator=()
template<int num_coords_, typename Coord_ = Real> VertexSet & FEAT::Geometry::VertexSet< num_coords_, Coord_ >::operator= (VertexSet< num_coords_, Coord_ > && other) inline
move-assignment operator
Definition at line 114 of file vertex_set.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::_vertices, and FEAT::Geometry::other.
operator[]() [1/2]
template<int num_coords_, typename Coord_ = Real> VertexType & FEAT::Geometry::VertexSet< num_coords_, Coord_ >::operator[] (Index i) inline
Returns a reference to a vertex.
Parameters
[in] i The index of the vertex to be returned.
Returns
A reference to the vertex.
Definition at line 161 of file vertex_set.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::_vertices, ASSERT, and FEAT::Geometry::VertexSet< num_coords_, Coord_ >::get_num_vertices().
operator[]() [2/2]
template<int num_coords_, typename Coord_ = Real> const VertexType & FEAT::Geometry::VertexSet< num_coords_, Coord_ >::operator[] (Index i) const inline
Returns a reference to a vertex.
Parameters
[in] i The index of the vertex to be returned.
Returns
A reference to the vertex.
Definition at line 168 of file vertex_set.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::_vertices, ASSERT, and FEAT::Geometry::VertexSet< num_coords_, Coord_ >::get_num_vertices().
permute()
template<int num_coords_, typename Coord_ = Real> void FEAT::Geometry::VertexSet< num_coords_, Coord_ >::permute (const Adjacency::Permutation & perm, bool invert = false) inline
Applies a permutation onto this vertex set.
Parameters
[in] perm The permutation that is to be applied.
[in] invert Specifies whether to apply the inverse permutation instead of the forward one.
Definition at line 222 of file vertex_set.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::_vertices, FEAT::Adjacency::Permutation::apply(), FEAT::Adjacency::Permutation::empty(), FEAT::Adjacency::Permutation::size(), and XASSERT.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::create_permutation(), and FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::set_permutation().
transform()
template<int num_coords_, typename Coord_ = Real> void FEAT::Geometry::VertexSet< num_coords_, Coord_ >::transform (const VertexType & origin, const VertexType & angles, const VertexType & offset) inline
Applies a "proper rigid" transformation onto the vertex set.
Let v denote the origin world point, w the offset world point and R the rotation matrix corresponding to the angles, then this function applies the following transformation for any vertex x of the vertex set:
\[ x \mapsto w + R\cdot (x - v) \]
Parameters
[in] origin The origin of the transformation. This is subtracted from any vertex before applying the rotation.
[in] angles The angles of the rotation matrix.
2D: the rotation angle in radians is stored as:
angles(0): rotation angle
angles(1): ignored
3D: the rotation angles in radians stored as:
angles(0): yaw angle
angles(1): pitch angle
angles(2): roll angle
[in] offset The offset of the transformation. This is added to any vertex after applying the rotation.
Definition at line 200 of file vertex_set.hpp.
References FEAT::Geometry::VertexSet< num_coords_, Coord_ >::_vertices.
Referenced by FEAT::Geometry::ConformalMesh< Shape_, num_coords_, Coord_ >::transform().
Member Data Documentation
_vertices
template<int num_coords_, typename Coord_ = Real> std::vector<VertexType> FEAT::Geometry::VertexSet< num_coords_, Coord_ >::_vertices protected
vertex vector
Definition at line 54 of file vertex_set.hpp.
Referenced by FEAT::Geometry::VertexSet< num_coords_, Coord_ >::bytes(), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::get_num_vertices(), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::operator=(), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::operator[](), FEAT::Geometry::VertexSet< num_coords_, Coord_ >::permute(), and FEAT::Geometry::VertexSet< num_coords_, Coord_ >::transform().
num_coords
template<int num_coords_, typename Coord_ = Real> constexpr int FEAT::Geometry::VertexSet< num_coords_, Coord_ >::num_coords = num_coords_ static constexpr
number of coordinates per vertex
Definition at line 44 of file vertex_set.hpp.
The documentation for this struct was generated from the following file:
kernel/geometry/vertex_set.hpp