FEAT: FEAT::Type::Helper Struct Reference
FEAT::Type::Helper Struct Reference
Static Public Member Functions
static bool extract_floatness (uint64_t feature_hash)
extracts floating point feature from a given types feature hash
static bool extract_intness (uint64_t feature_hash)
extracts integral feature from a given types feature hash
static bool extract_signedness (uint64_t feature_hash)
extracts sign feature from a given types feature hash
static size_t extract_type_size (uint64_t feature_hash)
extracts sizeof datatype from a given types feature hash
Detailed Description
Definition at line 32 of file type_traits.hpp.
Member Function Documentation
extract_floatness()
static bool FEAT::Type::Helper::extract_floatness (uint64_t feature_hash) inline static
extracts floating point feature from a given types feature hash
Definition at line 47 of file type_traits.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize().
extract_intness()
static bool FEAT::Type::Helper::extract_intness (uint64_t feature_hash) inline static
extracts integral feature from a given types feature hash
Definition at line 41 of file type_traits.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize().
extract_signedness()
static bool FEAT::Type::Helper::extract_signedness (uint64_t feature_hash) inline static
extracts sign feature from a given types feature hash
Definition at line 53 of file type_traits.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize().
extract_type_size()
static size_t FEAT::Type::Helper::extract_type_size (uint64_t feature_hash) inline static
extracts sizeof datatype from a given types feature hash
Definition at line 35 of file type_traits.hpp.
Referenced by FEAT::LAFEM::Container< DT_, IT_ >::_deserialize().
The documentation for this struct was generated from the following file:
kernel/util/type_traits.hpp