FEAT: FEAT::Geometry::AdaptionStats Struct Reference
FEAT::Geometry::AdaptionStats Struct Reference
Statistics about entities added, removed, and kept during a mesh adaption.
#include <adaptive_mesh.hpp>
Public Member Functions
template<int dim_>
void added_element (Index count=1)
Indicate a entity was added.
template<int dim_>
void kept_element (Index count=1)
Indicate a entity was kept.
template<int dim_>
void removed_element (Index count=1)
Indicate a entity was removed.
void removed_elements (const std::array< Index, 4 > &counts)
Indicate entities were removed.
void reset ()
Reset statistics to zero.
Public Attributes
std::array< Index, 4 > added
Statistics about added entities.
std::array< Index, 4 > kept
Statistics about kept entities.
std::array< Index, 4 > removed
Statistics about removed entities.
Detailed Description
Statistics about entities added, removed, and kept during a mesh adaption.
Author
Markus Muegge
Definition at line 101 of file adaptive_mesh.hpp.
Member Function Documentation
added_element()
template<int dim_> void FEAT::Geometry::AdaptionStats::added_element (Index count = 1) inline
Indicate a entity was added.
Template Parameters
dim_ Dimension of added entities
Parameters
[in] count Number of entities added
Definition at line 141 of file adaptive_mesh.hpp.
References added.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_build().
kept_element()
template<int dim_> void FEAT::Geometry::AdaptionStats::kept_element (Index count = 1) inline
Indicate a entity was kept.
Template Parameters
dim_ Dimension of kep entities
Parameters
[in] count Number of entities kept
Definition at line 178 of file adaptive_mesh.hpp.
References kept.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_adapt_children().
removed_element()
template<int dim_> void FEAT::Geometry::AdaptionStats::removed_element (Index count = 1) inline
Indicate a entity was removed.
Template Parameters
dim_ Dimension of removed entities
Parameters
[in] count Number of entities removed
Definition at line 153 of file adaptive_mesh.hpp.
References removed.
removed_elements()
void FEAT::Geometry::AdaptionStats::removed_elements (const std::array< Index, 4 > & counts) inline
Indicate entities were removed.
Parameters
[in] counts Number of entities of each dimension removed
Definition at line 163 of file adaptive_mesh.hpp.
References removed.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::_erase().
reset()
void FEAT::Geometry::AdaptionStats::reset () inline
Reset statistics to zero.
Definition at line 127 of file adaptive_mesh.hpp.
References added, kept, and removed.
Referenced by FEAT::Geometry::AdaptiveMesh< TemplateSet_, Shape_, num_coords_, Coord_ >::adapt().
Member Data Documentation
added
std::array<Index, 4> FEAT::Geometry::AdaptionStats::added
Statistics about added entities.
added[dim] contains the number of entities of dimension dim added to the mesh during adaption.
Definition at line 108 of file adaptive_mesh.hpp.
Referenced by added_element(), and reset().
kept
std::array<Index, 4> FEAT::Geometry::AdaptionStats::kept
Statistics about kept entities.
added[dim] contains the number of entities of dimension dim reused from the mesh during adaption.
Definition at line 122 of file adaptive_mesh.hpp.
Referenced by kept_element(), and reset().
removed
std::array<Index, 4> FEAT::Geometry::AdaptionStats::removed
Statistics about removed entities.
added[dim] contains the number of entities of dimension dim removed from the mesh during adaption.
Definition at line 115 of file adaptive_mesh.hpp.
Referenced by removed_element(), removed_elements(), and reset().
The documentation for this struct was generated from the following file:
kernel/geometry/adaptive_mesh.hpp