FEAT: FEAT::Control::Meshopt::ControlFactory< DT_, IT_ > Struct Template Reference
FEAT::Control::Meshopt::ControlFactory< DT_, IT_ > Struct Template Reference
Factory for MeshoptControl objects.
#include <meshopt_control_factory.hpp>
Static Public Member Functions
template<typename DomCtrl_ >
static std::shared_ptr< Control::Meshopt::MeshoptControlBase< DomCtrl_ > > create_dudv_control (DomCtrl_ &dom_ctrl, const String &section_key, PropertyMap *meshopt_config, PropertyMap *solver_config)
Creates a DuDvFunctionalControl object.
template<typename DomCtrl_ >
static std::shared_ptr< Control::Meshopt::MeshoptControlBase< DomCtrl_ > > create_hyperelasticity_control (DomCtrl_ &dom_ctrl, const String &section_key, PropertyMap *meshopt_config, PropertyMap *solver_config)
Creates a HyperelasticityFunctionalControl object.
template<typename DomCtrl_ , typename CellFunctional_ >
static std::shared_ptr< Control::Meshopt::MeshoptControlBase< DomCtrl_ > > create_hyperelasticity_control_with_cell_functional (DomCtrl_ &dom_ctrl, const int meshopt_lvl, PropertyMap *hyperelasticity_config_section, PropertyMap *meshopt_config, PropertyMap *solver_config, std::shared_ptr< CellFunctional_ > my_functional, const std::deque< String > &dirichlet_list, const std::deque< String > &slip_list)
Creates a HyperelasticityFunctionalControl object.
template<typename DomCtrl_ >
static std::shared_ptr< Control::Meshopt::MeshoptControlBase< DomCtrl_ > > create_meshopt_control (DomCtrl_ &dom_ctrl, const String &section_key, PropertyMap *meshopt_config, PropertyMap *solver_config)
Creates a MeshoptControlBase object according to a PropertyMap.
Detailed Description
template<typename DT_, typename IT_>
struct FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >
Factory for MeshoptControl objects.
Template Parameters
DT_ Floating point type for the solver.
IT_ Index type for the solver.
This class can construct MeshoptControl objects of different types at runtime based on PropertyMaps and returns them through base class std::shared_ptrs.
Note
At this time, the only transformation available is Trafo::Standard.
Definition at line 65 of file meshopt_control_factory.hpp.
Member Function Documentation
create_dudv_control()
template<typename DT_ , typename IT_ > template<typename DomCtrl_ > static std::shared_ptr< Control::Meshopt::MeshoptControlBase< DomCtrl_ > > FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_dudv_control (DomCtrl_ & dom_ctrl, const String & section_key, PropertyMap * meshopt_config, PropertyMap * solver_config) inline static
Creates a DuDvFunctionalControl object.
Template Parameters
DomCtrl_ The domain control type.
Parameters
[in] dom_ctrl The DomainControl containing meshes on all levels, the atlas etc.
[in] section_key The name of the parameter section which configures this object.
[in] meshopt_config Meshopt configuration.
[in] solver_config Solver configuration.
Returns
A BaseClass std::shared_ptr to the new object
Definition at line 90 of file meshopt_control_factory.hpp.
References FEAT::PropertyMap::query_section(), XABORTM, and XASSERTM.
Referenced by FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_meshopt_control().
create_hyperelasticity_control()
template<typename DT_ , typename IT_ > template<typename DomCtrl_ > static std::shared_ptr< Control::Meshopt::MeshoptControlBase< DomCtrl_ > > FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_hyperelasticity_control (DomCtrl_ & dom_ctrl, const String & section_key, PropertyMap * meshopt_config, PropertyMap * solver_config) inline static
Creates a HyperelasticityFunctionalControl object.
Template Parameters
DomCtrl_ The domain control type.
Parameters
[in] dom_ctrl The DomainControl containing meshes on all levels, the atlas etc.
[in] section_key The name of the parameter section which configures this object.
[in] meshopt_config Meshopt configuration.
[in] solver_config Solver configuration.
Returns
A BaseClass std::shared_ptr to the new object
This is the first stage, where the (cell-)local functional is determined, configured, created and then passed to the next stage.
Definition at line 174 of file meshopt_control_factory.hpp.
References FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_hyperelasticity_control_with_cell_functional(), FEAT::PropertyMap::query(), FEAT::PropertyMap::query_section(), XABORTM, and XASSERTM.
Referenced by FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_meshopt_control().
create_hyperelasticity_control_with_cell_functional()
template<typename DT_ , typename IT_ > template<typename DomCtrl_ , typename CellFunctional_ > static std::shared_ptr< Control::Meshopt::MeshoptControlBase< DomCtrl_ > > FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_hyperelasticity_control_with_cell_functional (DomCtrl_ & dom_ctrl, const int meshopt_lvl, PropertyMap * hyperelasticity_config_section, PropertyMap * meshopt_config, PropertyMap * solver_config, std::shared_ptr< CellFunctional_ > my_functional, const std::deque< String > & dirichlet_list, const std::deque< String > & slip_list) inline static
Creates a HyperelasticityFunctionalControl object.
Template Parameters
DomCtrl_ The domain control type.
CellFunctional_ The cell-local functional's type
Parameters
[in] dom_ctrl The DomainControl containing meshes on all levels, the atlas etc.
[in] meshopt_lvl The level (as in domain level) to optimize the mesh on. For all other levels, this solution gets prolongated/restricted.
[in] hyperelasticity_config_section The PropertyMap(section) containing the configuration for the new object.
[in] meshopt_config Meshopt configuration PropertyMap.
[in] solver_config Solver configuration PropertyMap.
[in] my_functional The cell-local functional that was created at the first stage.
[in] dirichlet_list List of meshpart identifiers for Dirichlet boundary conditions
[in] slip_list List of meshpart identifiers for slip boundary conditions
Returns
A BaseClass std::shared_ptr to the new object
This is the second stage, where the (cell-) local functional is already finished and gets passed to the HyperelasticityFunctional object's constructor.
Definition at line 344 of file meshopt_control_factory.hpp.
References FEAT::Meshopt::MeshConcentrationFunctionFactory< Trafo_, RefCellTrafo_ >::create(), FEAT::PropertyMap::query(), XABORTM, and XASSERTM.
Referenced by FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_hyperelasticity_control().
create_meshopt_control()
template<typename DT_ , typename IT_ > template<typename DomCtrl_ > static std::shared_ptr< Control::Meshopt::MeshoptControlBase< DomCtrl_ > > FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_meshopt_control (DomCtrl_ & dom_ctrl, const String & section_key, PropertyMap * meshopt_config, PropertyMap * solver_config) inline static
Creates a MeshoptControlBase object according to a PropertyMap.
Template Parameters
DomCtrl_ The type of domain control
Parameters
[in] dom_ctrl The domain control containing the meshes etc. for the mesh optimization
[in] section_key The name of the configuration section for this object
[in] meshopt_config The PropertyMap containing the configuration referenced by section_key
[in] solver_config The PropertyMap containing the solver configuration
Returns
An std::shared_ptr<MeshoptControlBase> to the new object
Definition at line 440 of file meshopt_control_factory.hpp.
References FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_dudv_control(), FEAT::Control::Meshopt::ControlFactory< DT_, IT_ >::create_hyperelasticity_control(), FEAT::PropertyMap::query_section(), and XABORTM.
The documentation for this struct was generated from the following file:
control/meshopt/meshopt_control_factory.hpp