FEAT: FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ > Struct Template Reference
FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ > Struct Template Reference
Helper class that recurses through shape dimensions and evaluates Lagrange2 DoF based on Lagrange1 DoF.
#include <fe_interpolator.hpp>
Public Types
typedef Space::Lagrange1::Element< Trafo_ > FromSpace
We map from Lagrange1.
typedef Space::Lagrange2::Element< Trafo_ > ToSpace
We map to Lagrange2.
Static Public Member Functions
template<typename Vector_ >
static void recurse (Vector_ &to_coeffs, const Vector_ &from_coeffs, const ToSpace &to_space)
Evaluates the node functionals from shape_dim_ on down to shape dimension 0.
Detailed Description
template<typename Trafo_, int shape_dim_ = Trafo_::MeshType::shape_dim>
struct FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ >
Helper class that recurses through shape dimensions and evaluates Lagrange2 DoF based on Lagrange1 DoF.
Template Parameters
Trafo_ The type of the transformation
shape_dim_ Shape dim for mapping Lagrange2 DoF, e.g. 1 for edges
This is needed for the template recursion and applies the Lagrange2 node functionals for DoF associated with entities of shape_dim_ to a Lagrange1 function. (This means it does linear interpolation at the edge, face and cell midpoints if required by the shape type used).
Author
Jordi Paul
Definition at line 58 of file fe_interpolator.hpp.
Member Typedef Documentation
FromSpace
template<typename Trafo_ , int shape_dim_ = Trafo_::MeshType::shape_dim> typedef Space::Lagrange1::Element<Trafo_> FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ >::FromSpace
We map from Lagrange1.
Definition at line 63 of file fe_interpolator.hpp.
ToSpace
template<typename Trafo_ , int shape_dim_ = Trafo_::MeshType::shape_dim> typedef Space::Lagrange2::Element<Trafo_> FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ >::ToSpace
We map to Lagrange2.
Definition at line 61 of file fe_interpolator.hpp.
Member Function Documentation
recurse()
template<typename Trafo_ , int shape_dim_ = Trafo_::MeshType::shape_dim> template<typename Vector_ > static void FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ >::recurse (Vector_ & to_coeffs, const Vector_ & from_coeffs, const ToSpace & to_space) inline static
Evaluates the node functionals from shape_dim_ on down to shape dimension 0.
Template Parameters
Vector_ The DoF vector type
Parameters
[in,out] to_coeffs The transient Lagrange2 DoF vector to be filled
[in] from_coeffs The transient Lagrange1 DoF vector representing the FE function we interpolate
[in] to_space The transient Lagrange2 space, needed for DoF mappings
Note
This explicitly uses that the DoF for shape dim 0 are numbered like the mesh's vertices. Without this, it is not possible to find out which DoF of shape dim 0 lie at an edge for the interpolation.
Definition at line 85 of file fe_interpolator.hpp.
References FEAT::Space::ElementBase< Trafo_ >::get_trafo(), and FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ >::recurse().
Referenced by FEAT::Assembly::FEInterpolator< Space::Lagrange2::Element< Trafo_ >, Space::Lagrange1::Element< Trafo_ > >::interpolate(), and FEAT::Assembly::Lagrange1To2DofAtEntity< Trafo_, shape_dim_ >::recurse().
The documentation for this struct was generated from the following file:
kernel/assembly/fe_interpolator.hpp