FEAT: FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ > Struct Template Reference
FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ > Struct Template Reference
Public Types
typedef DataType_ DataType
typedef Global::Matrix< LocalMatrixBlockA, VeloMirror, VeloMirror > GlobalMatrixBlockA
typedef Global::Matrix< LocalMatrixBlockB, VeloMirror, PresMirror > GlobalMatrixBlockB
typedef Global::Matrix< LocalMatrixBlockD, PresMirror, VeloMirror > GlobalMatrixBlockD
typedef Global::Transfer< LocalPresTransfer, PresMirror > GlobalPresTransfer
typedef Global::Vector< LocalPresVector, PresMirror > GlobalPresVector
typedef Global::Matrix< LocalScalarMatrix, PresMirror, PresMirror > GlobalSchurMatrix
typedef Global::Matrix< LocalSystemMatrix, SystemMirror, SystemMirror > GlobalSystemMatrix
typedef Global::Transfer< LocalSystemTransfer, SystemMirror > GlobalSystemTransfer
typedef Global::Vector< LocalSystemVector, SystemMirror > GlobalSystemVector
typedef Global::Transfer< LocalVeloTransfer, VeloMirror > GlobalVeloTransfer
typedef Global::Vector< LocalVeloVector, VeloMirror > GlobalVeloVector
typedef IndexType_ IndexType
typedef LAFEM::PowerDiagMatrix< LocalScalarMatrix, dim > LocalMatrixBlockA
typedef LAFEM::PowerColMatrix< LocalScalarMatrix, dim > LocalMatrixBlockB
typedef LAFEM::PowerRowMatrix< LocalScalarMatrix, dim > LocalMatrixBlockD
typedef LAFEM::Transfer< LocalPresTransferMatrix > LocalPresTransfer
typedef TransferMatrix_ LocalPresTransferMatrix
typedef LocalScalarVector LocalPresVector
typedef ScalarMatrix_ LocalScalarMatrix
typedef TransferMatrix_ LocalScalarTransferMatrix
typedef LocalScalarMatrix::VectorTypeR LocalScalarVector
typedef LAFEM::SaddlePointMatrix< LocalMatrixBlockA, LocalMatrixBlockB, LocalMatrixBlockD > LocalSystemMatrix
typedef LAFEM::Transfer< LocalSystemTransferMatrix > LocalSystemTransfer
typedef LAFEM::TupleDiagMatrix< LocalVeloTransferMatrix, LocalPresTransferMatrix > LocalSystemTransferMatrix
typedef LAFEM::TupleVector< LocalVeloVector, LocalPresVector > LocalSystemVector
typedef LAFEM::Transfer< LocalVeloTransferMatrix > LocalVeloTransfer
typedef LAFEM::PowerDiagMatrix< TransferMatrix_, dim_ > LocalVeloTransferMatrix
typedef LAFEM::PowerVector< LocalScalarVector, dim > LocalVeloVector
typedef Global::Gate< LocalPresVector, PresMirror > PresGate
typedef ScalarMirror PresMirror
typedef Global::Muxer< LocalPresVector, PresMirror > PresMuxer
typedef LAFEM::VectorMirror< DataType, IndexType > ScalarMirror
typedef Global::Gate< LocalSystemVector, SystemMirror > SystemGate
typedef LAFEM::TupleMirror< VeloMirror, PresMirror > SystemMirror
typedef Global::Muxer< LocalSystemVector, SystemMirror > SystemMuxer
typedef Global::Gate< LocalVeloVector, VeloMirror > VeloGate
typedef LAFEM::PowerMirror< ScalarMirror, dim > VeloMirror
typedef Global::Muxer< LocalVeloVector, VeloMirror > VeloMuxer
Public Member Functions
template<typename DomainLevel_ >
void assemble_coarse_muxers (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse)
template<typename DomainLevel_ >
void assemble_gates (const Domain::VirtualLevel< DomainLevel_ > &virt_dom_lvl)
template<typename Trafo_ , typename SpaceVelo_ , typename SpacePres_ , typename Cubature_ >
void assemble_grad_div_matrices (Assembly::DomainAssembler< Trafo_ > &dom_asm, const SpaceVelo_ &space_velo, const SpacePres_ &space_pres, const Cubature_ &cubature)
template<typename DomainLevel_ , typename Cubature_ >
void assemble_pressure_transfer (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse, const Cubature_ &cubature)
template<typename DomainLevel_ , typename Cubature_ >
void assemble_pressure_truncation (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse, const Cubature_ &cubature, const StokesPowerSystemLevel *sys_lvl_coarse=nullptr)
template<typename DomainLevel_ , typename Cubature_ >
void assemble_transfers (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse, const Cubature_ &cubature)
template<typename DomainLevel_ , typename Cubature_ >
void assemble_truncations (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse, const Cubature_ &cubature, const StokesPowerSystemLevel *sys_lvl_coarse=nullptr)
template<typename Trafo_ , typename SpaceVelo_ , typename Cubature_ >
void assemble_velocity_laplace_matrix (Assembly::DomainAssembler< Trafo_ > &dom_asm, const SpaceVelo_ &space_velo, const Cubature_ &cubature, const DataType nu=DataType(1))
template<typename DomainLevel_ , typename Cubature_ >
void assemble_velocity_transfer (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse, const Cubature_ &cubature)
template<typename DomainLevel_ , typename Cubature_ >
void assemble_velocity_truncation (const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > &virt_lvl_coarse, const Cubature_ &cubature, const StokesPowerSystemLevel *sys_lvl_coarse=nullptr)
void compile_system_matrix ()
void compile_system_transfer ()
template<typename D_ , typename I_ , typename SM_ , typename TM_ >
void convert (const StokesPowerSystemLevel< dim_, D_, I_, SM_, TM_ > &other)
Public Attributes
PresMuxer coarse_muxer_pres
SystemMuxer coarse_muxer_sys
VeloMuxer coarse_muxer_velo
our coarse-level system muxer
PresGate gate_pres
SystemGate gate_sys
VeloGate gate_velo
GlobalMatrixBlockA matrix_a
GlobalMatrixBlockB matrix_b
GlobalMatrixBlockD matrix_d
GlobalSchurMatrix matrix_s
GlobalSystemMatrix matrix_sys
GlobalPresTransfer transfer_pres
GlobalSystemTransfer transfer_sys
GlobalVeloTransfer transfer_velo
our global transfer operator
Static Public Attributes
static constexpr int dim = dim_
Detailed Description
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>>
struct FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >
Definition at line 63 of file stokes_power.hpp.
Member Typedef Documentation
DataType
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef DataType_ FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::DataType
Definition at line 70 of file stokes_power.hpp.
GlobalMatrixBlockA
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Matrix<LocalMatrixBlockA, VeloMirror, VeloMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalMatrixBlockA
Definition at line 119 of file stokes_power.hpp.
GlobalMatrixBlockB
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Matrix<LocalMatrixBlockB, VeloMirror, PresMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalMatrixBlockB
Definition at line 120 of file stokes_power.hpp.
GlobalMatrixBlockD
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Matrix<LocalMatrixBlockD, PresMirror, VeloMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalMatrixBlockD
Definition at line 121 of file stokes_power.hpp.
GlobalPresTransfer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Transfer<LocalPresTransfer, PresMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalPresTransfer
Definition at line 127 of file stokes_power.hpp.
GlobalPresVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Vector<LocalPresVector, PresMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalPresVector
Definition at line 115 of file stokes_power.hpp.
GlobalSchurMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Matrix<LocalScalarMatrix, PresMirror, PresMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalSchurMatrix
Definition at line 122 of file stokes_power.hpp.
GlobalSystemMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Matrix<LocalSystemMatrix, SystemMirror, SystemMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalSystemMatrix
Definition at line 123 of file stokes_power.hpp.
GlobalSystemTransfer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Transfer<LocalSystemTransfer, SystemMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalSystemTransfer
Definition at line 128 of file stokes_power.hpp.
GlobalSystemVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Vector<LocalSystemVector, SystemMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalSystemVector
Definition at line 116 of file stokes_power.hpp.
GlobalVeloTransfer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Transfer<LocalVeloTransfer, VeloMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalVeloTransfer
Definition at line 126 of file stokes_power.hpp.
GlobalVeloVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Vector<LocalVeloVector, VeloMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::GlobalVeloVector
Definition at line 114 of file stokes_power.hpp.
IndexType
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef IndexType_ FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::IndexType
Definition at line 71 of file stokes_power.hpp.
LocalMatrixBlockA
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::PowerDiagMatrix<LocalScalarMatrix, dim> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalMatrixBlockA
Definition at line 75 of file stokes_power.hpp.
LocalMatrixBlockB
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::PowerColMatrix<LocalScalarMatrix, dim> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalMatrixBlockB
Definition at line 76 of file stokes_power.hpp.
LocalMatrixBlockD
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::PowerRowMatrix<LocalScalarMatrix, dim> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalMatrixBlockD
Definition at line 77 of file stokes_power.hpp.
LocalPresTransfer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::Transfer<LocalPresTransferMatrix> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalPresTransfer
Definition at line 94 of file stokes_power.hpp.
LocalPresTransferMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef TransferMatrix_ FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalPresTransferMatrix
Definition at line 89 of file stokes_power.hpp.
LocalPresVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LocalScalarVector FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalPresVector
Definition at line 83 of file stokes_power.hpp.
LocalScalarMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef ScalarMatrix_ FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalScalarMatrix
Definition at line 74 of file stokes_power.hpp.
LocalScalarTransferMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef TransferMatrix_ FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalScalarTransferMatrix
Definition at line 87 of file stokes_power.hpp.
LocalScalarVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LocalScalarMatrix::VectorTypeR FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalScalarVector
Definition at line 81 of file stokes_power.hpp.
LocalSystemMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::SaddlePointMatrix<LocalMatrixBlockA, LocalMatrixBlockB, LocalMatrixBlockD> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalSystemMatrix
Definition at line 78 of file stokes_power.hpp.
LocalSystemTransfer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::Transfer<LocalSystemTransferMatrix> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalSystemTransfer
Definition at line 95 of file stokes_power.hpp.
LocalSystemTransferMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::TupleDiagMatrix<LocalVeloTransferMatrix, LocalPresTransferMatrix> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalSystemTransferMatrix
Definition at line 90 of file stokes_power.hpp.
LocalSystemVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::TupleVector<LocalVeloVector, LocalPresVector> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalSystemVector
Definition at line 84 of file stokes_power.hpp.
LocalVeloTransfer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::Transfer<LocalVeloTransferMatrix> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalVeloTransfer
Definition at line 93 of file stokes_power.hpp.
LocalVeloTransferMatrix
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::PowerDiagMatrix<TransferMatrix_, dim_> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalVeloTransferMatrix
Definition at line 88 of file stokes_power.hpp.
LocalVeloVector
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::PowerVector<LocalScalarVector, dim> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::LocalVeloVector
Definition at line 82 of file stokes_power.hpp.
PresGate
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Gate<LocalPresVector, PresMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::PresGate
Definition at line 105 of file stokes_power.hpp.
PresMirror
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef ScalarMirror FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::PresMirror
Definition at line 100 of file stokes_power.hpp.
PresMuxer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Muxer<LocalPresVector, PresMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::PresMuxer
Definition at line 110 of file stokes_power.hpp.
ScalarMirror
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::VectorMirror<DataType, IndexType> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::ScalarMirror
Definition at line 98 of file stokes_power.hpp.
SystemGate
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Gate<LocalSystemVector, SystemMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::SystemGate
Definition at line 106 of file stokes_power.hpp.
SystemMirror
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::TupleMirror<VeloMirror, PresMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::SystemMirror
Definition at line 101 of file stokes_power.hpp.
SystemMuxer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Muxer<LocalSystemVector, SystemMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::SystemMuxer
Definition at line 111 of file stokes_power.hpp.
VeloGate
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Gate<LocalVeloVector, VeloMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::VeloGate
Definition at line 104 of file stokes_power.hpp.
VeloMirror
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef LAFEM::PowerMirror<ScalarMirror, dim> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::VeloMirror
Definition at line 99 of file stokes_power.hpp.
VeloMuxer
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> typedef Global::Muxer<LocalVeloVector, VeloMirror> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::VeloMuxer
Definition at line 109 of file stokes_power.hpp.
Constructor & Destructor Documentation
StokesPowerSystemLevel()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::StokesPowerSystemLevel () inline
Definition at line 154 of file stokes_power.hpp.
~StokesPowerSystemLevel()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> virtual FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::~StokesPowerSystemLevel () inline virtual
Definition at line 166 of file stokes_power.hpp.
Member Function Documentation
assemble_coarse_muxers()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename DomainLevel_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_coarse_muxers (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse) inline
Definition at line 268 of file stokes_power.hpp.
assemble_gates()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename DomainLevel_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_gates (const Domain::VirtualLevel< DomainLevel_ > & virt_dom_lvl) inline
Todo:
find out what to do for disc/cont pressure spaces here...
Definition at line 212 of file stokes_power.hpp.
References FEAT::Assembly::MirrorAssembler::assemble_mirror(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::clone(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::clone(), FEAT::LAFEM::PowerVector< SubType_, count_ >::clone(), FEAT::Global::Gate< LocalVector_, Mirror_ >::compile(), FEAT::LAFEM::PowerMirror< SubMirror_, count_ >::empty(), FEAT::LAFEM::TupleMirror< First_, Rest_ >::empty(), FEAT::LAFEM::VectorMirror< DT_, IT_ >::empty(), FEAT::Global::Gate< LocalVector_, Mirror_ >::push(), FEAT::Global::Gate< LocalVector_, Mirror_ >::set_comm(), and XASSERT.
assemble_grad_div_matrices()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename Trafo_ , typename SpaceVelo_ , typename SpacePres_ , typename Cubature_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_grad_div_matrices (Assembly::DomainAssembler< Trafo_ > & dom_asm, const SpaceVelo_ & space_velo, const SpacePres_ & space_pres, const Cubature_ & cubature) inline
Todo:
share matrix structures of D_i
Definition at line 728 of file stokes_power.hpp.
References FEAT::Assembly::assemble_bilinear_operator_matrix_2(), FEAT::Assembly::SymbolicAssembler::assemble_matrix_std2(), FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::PowerRowMatrix< SubType_, blocks_ >::get(), FEAT::LAFEM::Layout, FEAT::Global::Matrix< LocalMatrix_, RowMirror_, ColMirror_ >::local(), and FEAT::LAFEM::PowerColMatrix< SubType_, blocks_ >::num_row_blocks.
assemble_pressure_transfer()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename DomainLevel_ , typename Cubature_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_pressure_transfer (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse, const Cubature_ & cubature) inline
Definition at line 420 of file stokes_power.hpp.
assemble_pressure_truncation()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename DomainLevel_ , typename Cubature_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_pressure_truncation (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse, const Cubature_ & cubature, const StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ > * sys_lvl_coarse = nullptr) inline
Definition at line 591 of file stokes_power.hpp.
assemble_transfers()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename DomainLevel_ , typename Cubature_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_transfers (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse, const Cubature_ & cubature) inline
Definition at line 473 of file stokes_power.hpp.
assemble_truncations()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename DomainLevel_ , typename Cubature_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_truncations (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse, const Cubature_ & cubature, const StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ > * sys_lvl_coarse = nullptr) inline
Definition at line 683 of file stokes_power.hpp.
assemble_velocity_laplace_matrix()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename Trafo_ , typename SpaceVelo_ , typename Cubature_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_velocity_laplace_matrix (Assembly::DomainAssembler< Trafo_ > & dom_asm, const SpaceVelo_ & space_velo, const Cubature_ & cubature, const DataType nu = DataType(1)) inline
Definition at line 695 of file stokes_power.hpp.
assemble_velocity_transfer()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename DomainLevel_ , typename Cubature_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_velocity_transfer (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse, const Cubature_ & cubature) inline
Definition at line 348 of file stokes_power.hpp.
assemble_velocity_truncation()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename DomainLevel_ , typename Cubature_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::assemble_velocity_truncation (const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_fine, const Domain::VirtualLevel< DomainLevel_ > & virt_lvl_coarse, const Cubature_ & cubature, const StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ > * sys_lvl_coarse = nullptr) inline
Definition at line 484 of file stokes_power.hpp.
compile_system_matrix()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::compile_system_matrix () inline
Definition at line 182 of file stokes_power.hpp.
compile_system_transfer()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::compile_system_transfer () inline
Definition at line 170 of file stokes_power.hpp.
convert()
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> template<typename D_ , typename I_ , typename SM_ , typename TM_ > void FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::convert (const StokesPowerSystemLevel< dim_, D_, I_, SM_, TM_ > & other) inline
Definition at line 190 of file stokes_power.hpp.
Member Data Documentation
coarse_muxer_pres
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> PresMuxer FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::coarse_muxer_pres
Definition at line 139 of file stokes_power.hpp.
coarse_muxer_sys
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> SystemMuxer FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::coarse_muxer_sys
Definition at line 140 of file stokes_power.hpp.
coarse_muxer_velo
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> VeloMuxer FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::coarse_muxer_velo
our coarse-level system muxer
Definition at line 138 of file stokes_power.hpp.
dim
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> constexpr int FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::dim = dim_ static constexpr
Definition at line 69 of file stokes_power.hpp.
gate_pres
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> PresGate FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::gate_pres
Definition at line 134 of file stokes_power.hpp.
gate_sys
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> SystemGate FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::gate_sys
Definition at line 135 of file stokes_power.hpp.
gate_velo
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> VeloGate FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::gate_velo
Definition at line 133 of file stokes_power.hpp.
matrix_a
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> GlobalMatrixBlockA FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::matrix_a
Definition at line 144 of file stokes_power.hpp.
matrix_b
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> GlobalMatrixBlockB FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::matrix_b
Definition at line 145 of file stokes_power.hpp.
matrix_d
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> GlobalMatrixBlockD FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::matrix_d
Definition at line 146 of file stokes_power.hpp.
matrix_s
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> GlobalSchurMatrix FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::matrix_s
Definition at line 147 of file stokes_power.hpp.
matrix_sys
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> GlobalSystemMatrix FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::matrix_sys
Definition at line 143 of file stokes_power.hpp.
transfer_pres
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> GlobalPresTransfer FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::transfer_pres
Definition at line 151 of file stokes_power.hpp.
transfer_sys
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> GlobalSystemTransfer FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::transfer_sys
Definition at line 152 of file stokes_power.hpp.
transfer_velo
template<int dim_, typename DataType_ = Real, typename IndexType_ = Index, typename ScalarMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>, typename TransferMatrix_ = LAFEM::SparseMatrixCSR<DataType_, IndexType_>> GlobalVeloTransfer FEAT::Control::StokesPowerSystemLevel< dim_, DataType_, IndexType_, ScalarMatrix_, TransferMatrix_ >::transfer_velo
our global transfer operator
Definition at line 150 of file stokes_power.hpp.
The documentation for this struct was generated from the following file:
control/stokes_power.hpp