var searchData=
[
  ['random_0',['Random',['../class_f_e_a_t_1_1_random.html',1,'FEAT']]],
  ['rangeexception_1',['RangeException',['../class_f_e_a_t_1_1_memory_1_1_range_exception.html',1,'FEAT::Memory']]],
  ['rawentity_2',['RawEntity',['../struct_f_e_a_t_1_1_geometry_1_1_raw_entity.html',1,'FEAT::Geometry']]],
  ['rawentity_3c_20shape_5f_2c_20num_5fcoords_5f_20_3e_3',['RawEntity&lt; Shape_, num_coords_ &gt;',['../struct_f_e_a_t_1_1_geometry_1_1_raw_entity.html',1,'FEAT::Geometry']]],
  ['rawtemplate_4',['RawTemplate',['../struct_f_e_a_t_1_1_geometry_1_1_raw_template.html',1,'FEAT::Geometry']]],
  ['ray_5',['Ray',['../struct_f_e_a_t_1_1_geometry_1_1_ray.html',1,'FEAT::Geometry']]],
  ['rayintersectionprimitives_6',['RayIntersectionPrimitives',['../class_f_e_a_t_1_1_geometry_1_1_ray_intersection_primitives.html',1,'FEAT::Geometry']]],
  ['rbicgstab_7',['RBiCGStab',['../class_f_e_a_t_1_1_solver_1_1_r_bi_c_g_stab.html',1,'FEAT::Solver']]],
  ['readresult_8',['ReadResult',['../class_f_e_a_t_1_1_geometry_1_1_voxel_map_1_1_read_result.html',1,'FEAT::Geometry::VoxelMap']]],
  ['redundantindexsetbuilder_9',['RedundantIndexSetBuilder',['../class_f_e_a_t_1_1_geometry_1_1_redundant_index_set_builder.html',1,'FEAT::Geometry']]],
  ['referencecell_10',['ReferenceCell',['../struct_f_e_a_t_1_1_shape_1_1_reference_cell.html',1,'FEAT::Shape']]],
  ['referencecellfactory_11',['ReferenceCellFactory',['../class_f_e_a_t_1_1_geometry_1_1_reference_cell_factory.html',1,'FEAT::Geometry']]],
  ['refinefactory_12',['RefineFactory',['../class_f_e_a_t_1_1_cubature_1_1_refine_factory.html',1,'FEAT::Cubature::RefineFactory&lt; Factory_, variadic_ &gt;'],['../class_f_e_a_t_1_1_geometry_1_1_refine_factory.html',1,'FEAT::Geometry::RefineFactory&lt; Mesh_, Factory_ &gt;']]],
  ['refinefactory_3c_20factory_5f_2c_20false_20_3e_13',['RefineFactory&lt; Factory_, false &gt;',['../class_f_e_a_t_1_1_cubature_1_1_refine_factory_3_01_factory___00_01false_01_4.html',1,'FEAT::Cubature']]],
  ['refinefactory_3c_20factory_5f_2c_20true_20_3e_14',['RefineFactory&lt; Factory_, true &gt;',['../class_f_e_a_t_1_1_cubature_1_1_refine_factory_3_01_factory___00_01true_01_4.html',1,'FEAT::Cubature']]],
  ['refinefactorybase_15',['RefineFactoryBase',['../class_f_e_a_t_1_1_cubature_1_1_refine_factory_base.html',1,'FEAT::Cubature']]],
  ['refinefactorycore_16',['RefineFactoryCore',['../class_f_e_a_t_1_1_cubature_1_1_refine_factory_core.html',1,'FEAT::Cubature']]],
  ['refinementfield_17',['RefinementField',['../class_f_e_a_t_1_1_geometry_1_1_intern_1_1_refinement_field.html',1,'FEAT::Geometry::Intern']]],
  ['refinementfieldtuple_18',['RefinementFieldTuple',['../class_f_e_a_t_1_1_geometry_1_1_intern_1_1_refinement_field_tuple.html',1,'FEAT::Geometry::Intern']]],
  ['refinementtemplate_19',['RefinementTemplate',['../struct_f_e_a_t_1_1_geometry_1_1_refinement_template.html',1,'FEAT::Geometry']]],
  ['refinementtemplate_3c_20shape_5f_2c_20shape_3a_3avertex_20_3e_20',['RefinementTemplate&lt; Shape_, Shape::Vertex &gt;',['../struct_f_e_a_t_1_1_geometry_1_1_refinement_template_3_01_shape___00_01_shape_1_1_vertex_01_4.html',1,'FEAT::Geometry']]],
  ['request_21',['Request',['../class_f_e_a_t_1_1_dist_1_1_request.html',1,'FEAT::Dist']]],
  ['requestvector_22',['RequestVector',['../class_f_e_a_t_1_1_dist_1_1_request_vector.html',1,'FEAT::Dist']]],
  ['rewprojector_23',['RewProjector',['../class_f_e_a_t_1_1_assembly_1_1_rew_projector.html',1,'FEAT::Assembly']]],
  ['rgcr_24',['RGCR',['../class_f_e_a_t_1_1_solver_1_1_r_g_c_r.html',1,'FEAT::Solver']]],
  ['richardson_25',['Richardson',['../class_f_e_a_t_1_1_solver_1_1_richardson.html',1,'FEAT::Solver']]],
  ['rigidbodyvortexpres2d_26',['RigidBodyVortexPres2D',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_rigid_body_vortex_pres2_d.html',1,'FEAT::Analytic::Common']]],
  ['rigidbodyvortexvelo2d_27',['RigidBodyVortexVelo2D',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_rigid_body_vortex_velo2_d.html',1,'FEAT::Analytic::Common']]],
  ['rootmeshnode_28',['RootMeshNode',['../class_f_e_a_t_1_1_geometry_1_1_root_mesh_node.html',1,'FEAT::Geometry']]],
  ['rootmeshnode_3c_20meshtype_20_3e_29',['RootMeshNode&lt; MeshType &gt;',['../class_f_e_a_t_1_1_geometry_1_1_root_mesh_node.html',1,'FEAT::Geometry']]],
  ['rownorm2bcsr_30',['RowNorm2BCSR',['../struct_f_e_a_t_1_1_l_a_f_e_m_1_1_arch_1_1_row_norm2_b_c_s_r.html',1,'FEAT::LAFEM::Arch']]],
  ['rownorm2csr_31',['RowNorm2CSR',['../struct_f_e_a_t_1_1_l_a_f_e_m_1_1_arch_1_1_row_norm2_c_s_r.html',1,'FEAT::LAFEM::Arch']]],
  ['rule_32',['Rule',['../class_f_e_a_t_1_1_cubature_1_1_rule.html',1,'FEAT::Cubature::Rule&lt; Shape_, Weight_, Coord_, Point_ &gt;'],['../class_f_e_a_t_1_1_cubature_1_1_scalar_1_1_rule.html',1,'FEAT::Cubature::Scalar::Rule&lt; Weight_, Coord_ &gt;']]],
  ['rule_3c_20facettype_2c_20datatype_5f_2c_20datatype_5f_2c_20domainpointtype_20_3e_33',['Rule&lt; FacetType, DataType_, DataType_, DomainPointType &gt;',['../class_f_e_a_t_1_1_cubature_1_1_rule.html',1,'FEAT::Cubature']]],
  ['rule_3c_20shapetype_2c_20datatype_5f_2c_20datatype_5f_2c_20domainpointtype_20_3e_34',['Rule&lt; ShapeType, DataType_, DataType_, DomainPointType &gt;',['../class_f_e_a_t_1_1_cubature_1_1_rule.html',1,'FEAT::Cubature']]],
  ['rule_3c_20surfaceshapetype_2c_20datatype_2c_20datatype_2c_20refcoordvectype_20_3e_35',['Rule&lt; SurfaceShapeType, DataType, DataType, RefCoordVecType &gt;',['../class_f_e_a_t_1_1_cubature_1_1_rule.html',1,'FEAT::Cubature']]],
  ['rumpffunctional_36',['RumpfFunctional',['../class_f_e_a_t_1_1_meshopt_1_1_rumpf_functional.html',1,'FEAT::Meshopt']]],
  ['rumpffunctionalbase_37',['RumpfFunctionalBase',['../class_f_e_a_t_1_1_meshopt_1_1_rumpf_functional_base.html',1,'FEAT::Meshopt']]],
  ['rumpftrafo_38',['RumpfTrafo',['../struct_f_e_a_t_1_1_meshopt_1_1_rumpf_trafo.html',1,'FEAT::Meshopt']]],
  ['runtime_39',['Runtime',['../class_f_e_a_t_1_1_runtime.html',1,'FEAT']]]
];
