var searchData=
[
  ['gap_0',['Gap',['../struct_f_e_a_t_1_1_geometry_1_1_gap.html',1,'FEAT::Geometry']]],
  ['gate_1',['Gate',['../class_f_e_a_t_1_1_global_1_1_gate.html',1,'FEAT::Global']]],
  ['gate_3c_20localpresvector_2c_20presmirror_20_3e_2',['Gate&lt; LocalPresVector, PresMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_gate.html',1,'FEAT::Global']]],
  ['gate_3c_20localscalarvector_2c_20scalarmirror_20_3e_3',['Gate&lt; LocalScalarVector, ScalarMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_gate.html',1,'FEAT::Global']]],
  ['gate_3c_20localstressvector_2c_20stressmirror_20_3e_4',['Gate&lt; LocalStressVector, StressMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_gate.html',1,'FEAT::Global']]],
  ['gate_3c_20localsystemvector_2c_20systemmirror_20_3e_5',['Gate&lt; LocalSystemVector, SystemMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_gate.html',1,'FEAT::Global']]],
  ['gate_3c_20localsystemvectorr_2c_20systemmirror_20_3e_6',['Gate&lt; LocalSystemVectorR, SystemMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_gate.html',1,'FEAT::Global']]],
  ['gate_3c_20localvelovector_2c_20velomirror_20_3e_7',['Gate&lt; LocalVeloVector, VeloMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_gate.html',1,'FEAT::Global']]],
  ['gatheraxpy_8',['GatherAxpy',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_dense_vector_1_1_gather_axpy.html',1,'FEAT::LAFEM::DenseVector&lt; DT_, IT_ &gt;::GatherAxpy'],['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_dense_vector_blocked_1_1_gather_axpy.html',1,'FEAT::LAFEM::DenseVectorBlocked&lt; DT_, IT_, BlockSize_ &gt;::GatherAxpy'],['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_banded_1_1_gather_axpy.html',1,'FEAT::LAFEM::SparseMatrixBanded&lt; DT_, IT_ &gt;::GatherAxpy'],['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_r_1_1_gather_axpy.html',1,'FEAT::LAFEM::SparseMatrixCSR&lt; DT_, IT_ &gt;::GatherAxpy']]],
  ['gausslegendredriver_9',['GaussLegendreDriver',['../class_f_e_a_t_1_1_cubature_1_1_scalar_1_1_gauss_legendre_driver.html',1,'FEAT::Cubature::Scalar']]],
  ['gausslobattodriver_10',['GaussLobattoDriver',['../class_f_e_a_t_1_1_cubature_1_1_scalar_1_1_gauss_lobatto_driver.html',1,'FEAT::Cubature::Scalar']]],
  ['genericumfpack_11',['GenericUmfpack',['../class_f_e_a_t_1_1_solver_1_1_generic_umfpack.html',1,'FEAT::Solver']]],
  ['globalmaskedboundaryfactory_12',['GlobalMaskedBoundaryFactory',['../class_f_e_a_t_1_1_geometry_1_1_global_masked_boundary_factory.html',1,'FEAT::Geometry']]],
  ['gmres_13',['GMRES',['../class_f_e_a_t_1_1_solver_1_1_g_m_r_e_s.html',1,'FEAT::Solver']]],
  ['gradient_14',['Gradient',['../class_f_e_a_t_1_1_analytic_1_1_gradient.html',1,'FEAT::Analytic']]],
  ['gradienttestoperatorblocked_15',['GradientTestOperatorBlocked',['../class_f_e_a_t_1_1_assembly_1_1_common_1_1_gradient_test_operator_blocked.html',1,'FEAT::Assembly::Common']]],
  ['gradienttrialoperatorblocked_16',['GradientTrialOperatorBlocked',['../class_f_e_a_t_1_1_assembly_1_1_common_1_1_gradient_trial_operator_blocked.html',1,'FEAT::Assembly::Common']]],
  ['gradoperatorassembler_17',['GradOperatorAssembler',['../class_f_e_a_t_1_1_assembly_1_1_grad_operator_assembler.html',1,'FEAT::Assembly']]],
  ['gradpresdivveloassembler_18',['GradPresDivVeloAssembler',['../class_f_e_a_t_1_1_assembly_1_1_grad_pres_div_velo_assembler.html',1,'FEAT::Assembly']]],
  ['grammarerror_19',['GrammarError',['../class_f_e_a_t_1_1_xml_1_1_grammar_error.html',1,'FEAT::Xml']]],
  ['graph_20',['Graph',['../class_f_e_a_t_1_1_adjacency_1_1_graph.html',1,'FEAT::Adjacency']]],
  ['gridtransfer_21',['GridTransfer',['../class_f_e_a_t_1_1_assembly_1_1_grid_transfer.html',1,'FEAT::Assembly']]],
  ['gropppcg_22',['GroppPCG',['../class_f_e_a_t_1_1_solver_1_1_gropp_p_c_g.html',1,'FEAT::Solver']]],
  ['guermondstokessol_23',['GuermondStokesSol',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_guermond_stokes_sol.html',1,'FEAT::Analytic::Common']]],
  ['guermondstokessolpressure_24',['GuermondStokesSolPressure',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_guermond_stokes_sol_pressure.html',1,'FEAT::Analytic::Common']]],
  ['guermondstokessolrhs_25',['GuermondStokesSolRhs',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_guermond_stokes_sol_rhs.html',1,'FEAT::Analytic::Common']]]
];
