var searchData=
[
  ['backend_0',['Backend',['../class_f_e_a_t_1_1_backend.html',1,'FEAT']]],
  ['barycentredriver_1',['BarycentreDriver',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver.html',1,'FEAT::Cubature']]],
  ['barycentredriver_3c_20shape_3a_3ahypercube_3c_20dim_5f_20_3e_20_3e_2',['BarycentreDriver&lt; Shape::Hypercube&lt; dim_ &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver_3_01_shape_1_1_hypercube_3_01dim___01_4_01_4.html',1,'FEAT::Cubature']]],
  ['barycentredriver_3c_20shape_3a_3asimplex_3c_20dim_5f_20_3e_20_3e_3',['BarycentreDriver&lt; Shape::Simplex&lt; dim_ &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver_3_01_shape_1_1_simplex_3_01dim___01_4_01_4.html',1,'FEAT::Cubature']]],
  ['basisdata_4',['BasisData',['../class_f_e_a_t_1_1_space_1_1_basis_data.html',1,'FEAT::Space']]],
  ['basisdatareduced_5',['BasisDataReduced',['../class_f_e_a_t_1_1_space_1_1_basis_data_reduced.html',1,'FEAT::Space']]],
  ['bezier_6',['Bezier',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierchartparser_7',['BezierChartParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_chart_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierparamsparser_8',['BezierParamsParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_params_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierpointsparser_9',['BezierPointsParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_points_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['beziertraits_10',['BezierTraits',['../struct_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_traits.html',1,'FEAT::Geometry::Atlas']]],
  ['bfbt_11',['BFBT',['../class_f_e_a_t_1_1_solver_1_1_b_f_b_t.html',1,'FEAT::Solver']]],
  ['bfbt_3c_20global_3a_3amatrix_3c_20matrixa_5f_2c_20mirrorv_5f_2c_20mirrorv_5f_20_3e_2c_20global_3a_3amatrix_3c_20matrixb_5f_2c_20mirrorv_5f_2c_20mirrorp_5f_20_3e_2c_20global_3a_3amatrix_3c_20matrixd_5f_2c_20mirrorp_5f_2c_20mirrorv_5f_20_3e_2c_20global_3a_3afilter_3c_20filterv_5f_2c_20mirrorv_5f_20_3e_2c_20global_3a_3afilter_3c_20filterp_5f_2c_20mirrorp_5f_20_3e_20_3e_12',['BFBT&lt; Global::Matrix&lt; MatrixA_, MirrorV_, MirrorV_ &gt;, Global::Matrix&lt; MatrixB_, MirrorV_, MirrorP_ &gt;, Global::Matrix&lt; MatrixD_, MirrorP_, MirrorV_ &gt;, Global::Filter&lt; FilterV_, MirrorV_ &gt;, Global::Filter&lt; FilterP_, MirrorP_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_b_f_b_t_3_01_global_1_1_matrix_3_01_matrix_a___00_01_mirror_v___00_b78d0c70abd3b3b8f4e08d78d44fb7d6.html',1,'FEAT::Solver']]],
  ['bicgstab_13',['BiCGStab',['../class_f_e_a_t_1_1_solver_1_1_bi_c_g_stab.html',1,'FEAT::Solver']]],
  ['bicgstabl_14',['BiCGStabL',['../class_f_e_a_t_1_1_solver_1_1_bi_c_g_stab_l.html',1,'FEAT::Solver']]],
  ['bilinearoperator_15',['BilinearOperator',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator.html',1,'FEAT::Assembly']]],
  ['bilinearoperatorassembler_16',['BilinearOperatorAssembler',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_assembler.html',1,'FEAT::Assembly']]],
  ['binarystream_17',['BinaryStream',['../class_f_e_a_t_1_1_binary_stream.html',1,'FEAT']]],
  ['binomial_18',['Binomial',['../struct_f_e_a_t_1_1_meta_math_1_1_binomial.html',1,'FEAT::MetaMath']]],
  ['blockedbasicsystemlevel_19',['BlockedBasicSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_basic_system_level.html',1,'FEAT::Control']]],
  ['blockedbasicsystemlevel_3c_20dim_5f_2c_20real_2c_20index_2c_20lafem_3a_3asparsematrixbcsr_3c_20real_2c_20index_2c_20dim_5f_2c_20dim_5f_20_3e_2c_20lafem_3a_3asparsematrixbwrappedcsr_3c_20real_2c_20index_2c_20dim_5f_20_3e_20_3e_20',['BlockedBasicSystemLevel&lt; dim_, Real, Index, LAFEM::SparseMatrixBCSR&lt; Real, Index, dim_, dim_ &gt;, LAFEM::SparseMatrixBWrappedCSR&lt; Real, Index, dim_ &gt; &gt;',['../class_f_e_a_t_1_1_control_1_1_blocked_basic_system_level.html',1,'FEAT::Control']]],
  ['blockedcombinedsystemlevel_21',['BlockedCombinedSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_combined_system_level.html',1,'FEAT::Control']]],
  ['blockedunitfiltersystemlevel_22',['BlockedUnitFilterSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_unit_filter_system_level.html',1,'FEAT::Control']]],
  ['booleanclass_23',['BooleanClass',['../class_f_e_a_t_1_1_type_1_1_boolean_class.html',1,'FEAT::Type']]],
  ['boomeramg_24',['BoomerAMG',['../class_f_e_a_t_1_1_solver_1_1_boomer_a_m_g.html',1,'FEAT::Solver']]],
  ['boundaryfactory_25',['BoundaryFactory',['../class_f_e_a_t_1_1_geometry_1_1_boundary_factory.html',1,'FEAT::Geometry']]],
  ['burgersassembler_26',['BurgersAssembler',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembler.html',1,'FEAT::Assembly']]],
  ['burgersassemblercarreau_27',['BurgersAssemblerCarreau',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembler_carreau.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_28',['BurgersAssemblyJobBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20matrix_5f_3a_3adatatype_2c_20space_5f_2c_20convvector_5f_20_3e_29',['BurgersAssemblyJobBase&lt; Matrix_::DataType, Space_, ConvVector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20matrix_5f_3a_3adatatype_2c_20space_5f_2c_20typename_20matrix_5f_3a_3avectortyper_20_3e_30',['BurgersAssemblyJobBase&lt; Matrix_::DataType, Space_, typename Matrix_::VectorTypeR &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20vector_5f_3a_3adatatype_2c_20space_5f_2c_20convvector_5f_20_3e_31',['BurgersAssemblyJobBase&lt; Vector_::DataType, Space_, ConvVector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20vector_5f_3a_3adatatype_2c_20space_5f_2c_20vector_5f_20_3e_32',['BurgersAssemblyJobBase&lt; Vector_::DataType, Space_, Vector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_33',['BurgersAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersblockedmatrixassemblyjob_2c_20datatype_20_3e_34',['BurgersAssemblyTaskBase&lt; BurgersBlockedMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersblockedvectorassemblyjob_2c_20datatype_20_3e_35',['BurgersAssemblyTaskBase&lt; BurgersBlockedVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersscalarmatrixassemblyjob_2c_20datatype_20_3e_36',['BurgersAssemblyTaskBase&lt; BurgersScalarMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersscalarvectorassemblyjob_2c_20datatype_20_3e_37',['BurgersAssemblyTaskBase&lt; BurgersScalarVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_38',['BurgersBlockedAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_3c_20burgersblockedmatrixassemblyjob_2c_20datatype_2c_20block_5fsize_20_3e_39',['BurgersBlockedAssemblyTaskBase&lt; BurgersBlockedMatrixAssemblyJob, DataType, block_size &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_3c_20burgersblockedvectorassemblyjob_2c_20datatype_2c_20block_5fsize_20_3e_40',['BurgersBlockedAssemblyTaskBase&lt; BurgersBlockedVectorAssemblyJob, DataType, block_size &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedmatrixassemblyjob_41',['BurgersBlockedMatrixAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_matrix_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersblockedvectorassemblyjob_42',['BurgersBlockedVectorAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_vector_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersdefectshareddataglobalwrapper_43',['BurgersDefectSharedDataGlobalWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_defect_shared_data_global_wrapper.html',1,'FEAT::VoxelAssembly']]],
  ['burgersscalarassemblytaskbase_44',['BurgersScalarAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarassemblytaskbase_3c_20burgersscalarmatrixassemblyjob_2c_20datatype_20_3e_45',['BurgersScalarAssemblyTaskBase&lt; BurgersScalarMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarassemblytaskbase_3c_20burgersscalarvectorassemblyjob_2c_20datatype_20_3e_46',['BurgersScalarAssemblyTaskBase&lt; BurgersScalarVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarmatrixassemblyjob_47',['BurgersScalarMatrixAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_matrix_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersscalarvectorassemblyjob_48',['BurgersScalarVectorAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_vector_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersshareddataglobalwrapper_49',['BurgersSharedDataGlobalWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_shared_data_global_wrapper.html',1,'FEAT::VoxelAssembly']]],
  ['burgersshareddatakernelwrapper_50',['BurgersSharedDataKernelWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_shared_data_kernel_wrapper.html',1,'FEAT::VoxelAssembly']]]
];
