var searchData=
[
  ['backend_0',['Backend',['../class_f_e_a_t_1_1_backend.html',1,'FEAT']]],
  ['barycentredriver_1',['BarycentreDriver',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver.html',1,'FEAT::Cubature']]],
  ['barycentredriver_3c_20shape_3a_3ahypercube_3c_20dim_5f_20_3e_20_3e_2',['BarycentreDriver&lt; Shape::Hypercube&lt; dim_ &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver_3_01_shape_1_1_hypercube_3_01dim___01_4_01_4.html',1,'FEAT::Cubature']]],
  ['barycentredriver_3c_20shape_3a_3asimplex_3c_20dim_5f_20_3e_20_3e_3',['BarycentreDriver&lt; Shape::Simplex&lt; dim_ &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver_3_01_shape_1_1_simplex_3_01dim___01_4_01_4.html',1,'FEAT::Cubature']]],
  ['basicmatrixassemblytaskcrtp1_4',['BasicMatrixAssemblyTaskCRTP1',['../class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p1.html',1,'FEAT::Assembly']]],
  ['basicmatrixassemblytaskcrtp1_3c_20task_2c_20matrix_5f_2c_20space_5f_2c_20trafo_5fconfig_2c_20space_5fconfig_20_3e_5',['BasicMatrixAssemblyTaskCRTP1&lt; Task, Matrix_, Space_, trafo_config, space_config &gt;',['../class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p1.html',1,'FEAT::Assembly']]],
  ['basicmatrixassemblytaskcrtp2_6',['BasicMatrixAssemblyTaskCRTP2',['../class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p2.html',1,'FEAT::Assembly']]],
  ['basicmatrixassemblytaskcrtp2_3c_20task_2c_20matrix_5f_2c_20testspace_5f_2c_20trialspace_5f_2c_20trafo_5fconfig_2c_20test_5fconfig_2c_20trial_5fconfig_20_3e_7',['BasicMatrixAssemblyTaskCRTP2&lt; Task, Matrix_, TestSpace_, TrialSpace_, trafo_config, test_config, trial_config &gt;',['../class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p2.html',1,'FEAT::Assembly']]],
  ['basicvectorassemblytaskcrtp_8',['BasicVectorAssemblyTaskCRTP',['../class_f_e_a_t_1_1_assembly_1_1_basic_vector_assembly_task_c_r_t_p.html',1,'FEAT::Assembly']]],
  ['basicvectorassemblytaskcrtp_3c_20task_2c_20vector_5f_2c_20space_5f_2c_20trafo_5fconfig_2c_20test_5fconfig_20_3e_9',['BasicVectorAssemblyTaskCRTP&lt; Task, Vector_, Space_, trafo_config, test_config &gt;',['../class_f_e_a_t_1_1_assembly_1_1_basic_vector_assembly_task_c_r_t_p.html',1,'FEAT::Assembly']]],
  ['basisdata_10',['BasisData',['../class_f_e_a_t_1_1_space_1_1_basis_data.html',1,'FEAT::Space']]],
  ['basisdatareduced_11',['BasisDataReduced',['../class_f_e_a_t_1_1_space_1_1_basis_data_reduced.html',1,'FEAT::Space']]],
  ['bezier_12',['Bezier',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierchartparser_13',['BezierChartParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_chart_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierparamsparser_14',['BezierParamsParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_params_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierpointsparser_15',['BezierPointsParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_points_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['beziertraits_16',['BezierTraits',['../struct_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_traits.html',1,'FEAT::Geometry::Atlas']]],
  ['bfbt_17',['BFBT',['../class_f_e_a_t_1_1_solver_1_1_b_f_b_t.html',1,'FEAT::Solver']]],
  ['bfbt_3c_20global_3a_3amatrix_3c_20matrixa_5f_2c_20mirrorv_5f_2c_20mirrorv_5f_20_3e_2c_20global_3a_3amatrix_3c_20matrixb_5f_2c_20mirrorv_5f_2c_20mirrorp_5f_20_3e_2c_20global_3a_3amatrix_3c_20matrixd_5f_2c_20mirrorp_5f_2c_20mirrorv_5f_20_3e_2c_20global_3a_3afilter_3c_20filterv_5f_2c_20mirrorv_5f_20_3e_2c_20global_3a_3afilter_3c_20filterp_5f_2c_20mirrorp_5f_20_3e_20_3e_18',['BFBT&lt; Global::Matrix&lt; MatrixA_, MirrorV_, MirrorV_ &gt;, Global::Matrix&lt; MatrixB_, MirrorV_, MirrorP_ &gt;, Global::Matrix&lt; MatrixD_, MirrorP_, MirrorV_ &gt;, Global::Filter&lt; FilterV_, MirrorV_ &gt;, Global::Filter&lt; FilterP_, MirrorP_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_b_f_b_t_3_01_global_1_1_matrix_3_01_matrix_a___00_01_mirror_v___00_b78d0c70abd3b3b8f4e08d78d44fb7d6.html',1,'FEAT::Solver']]],
  ['bicgstab_19',['BiCGStab',['../class_f_e_a_t_1_1_solver_1_1_bi_c_g_stab.html',1,'FEAT::Solver']]],
  ['bicgstabl_20',['BiCGStabL',['../class_f_e_a_t_1_1_solver_1_1_bi_c_g_stab_l.html',1,'FEAT::Solver']]],
  ['bilinearoperator_21',['BilinearOperator',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator.html',1,'FEAT::Assembly']]],
  ['bilinearoperatorassembler_22',['BilinearOperatorAssembler',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_assembler.html',1,'FEAT::Assembly']]],
  ['bilinearoperatormatrixassemblyjob1_23',['BilinearOperatorMatrixAssemblyJob1',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_matrix_assembly_job1.html',1,'FEAT::Assembly']]],
  ['bilinearoperatormatrixassemblyjob2_24',['BilinearOperatorMatrixAssemblyJob2',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_matrix_assembly_job2.html',1,'FEAT::Assembly']]],
  ['binarystream_25',['BinaryStream',['../class_f_e_a_t_1_1_binary_stream.html',1,'FEAT']]],
  ['binomial_26',['Binomial',['../struct_f_e_a_t_1_1_meta_math_1_1_binomial.html',1,'FEAT::MetaMath']]],
  ['blockedbasicsystemlevel_27',['BlockedBasicSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_basic_system_level.html',1,'FEAT::Control']]],
  ['blockedbasicsystemlevel_3c_20dim_5f_2c_20real_2c_20index_2c_20lafem_3a_3asparsematrixbcsr_3c_20real_2c_20index_2c_20dim_5f_2c_20dim_5f_20_3e_2c_20lafem_3a_3asparsematrixbwrappedcsr_3c_20real_2c_20index_2c_20dim_5f_20_3e_20_3e_28',['BlockedBasicSystemLevel&lt; dim_, Real, Index, LAFEM::SparseMatrixBCSR&lt; Real, Index, dim_, dim_ &gt;, LAFEM::SparseMatrixBWrappedCSR&lt; Real, Index, dim_ &gt; &gt;',['../class_f_e_a_t_1_1_control_1_1_blocked_basic_system_level.html',1,'FEAT::Control']]],
  ['blockedcombinedsystemlevel_29',['BlockedCombinedSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_combined_system_level.html',1,'FEAT::Control']]],
  ['blockedunitfiltersystemlevel_30',['BlockedUnitFilterSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_unit_filter_system_level.html',1,'FEAT::Control']]],
  ['booleanclass_31',['BooleanClass',['../class_f_e_a_t_1_1_type_1_1_boolean_class.html',1,'FEAT::Type']]],
  ['boomeramg_32',['BoomerAMG',['../class_f_e_a_t_1_1_solver_1_1_boomer_a_m_g.html',1,'FEAT::Solver']]],
  ['boundaryfactory_33',['BoundaryFactory',['../class_f_e_a_t_1_1_geometry_1_1_boundary_factory.html',1,'FEAT::Geometry']]],
  ['burgersassembler_34',['BurgersAssembler',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembler.html',1,'FEAT::Assembly']]],
  ['burgersassemblercarreau_35',['BurgersAssemblerCarreau',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembler_carreau.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_36',['BurgersAssemblyJobBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20matrix_5f_3a_3adatatype_2c_20space_5f_2c_20convvector_5f_20_3e_37',['BurgersAssemblyJobBase&lt; Matrix_::DataType, Space_, ConvVector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20matrix_5f_3a_3adatatype_2c_20space_5f_2c_20typename_20matrix_5f_3a_3avectortyper_20_3e_38',['BurgersAssemblyJobBase&lt; Matrix_::DataType, Space_, typename Matrix_::VectorTypeR &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20vector_5f_3a_3adatatype_2c_20space_5f_2c_20convvector_5f_20_3e_39',['BurgersAssemblyJobBase&lt; Vector_::DataType, Space_, ConvVector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20vector_5f_3a_3adatatype_2c_20space_5f_2c_20vector_5f_20_3e_40',['BurgersAssemblyJobBase&lt; Vector_::DataType, Space_, Vector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_41',['BurgersAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersblockedmatrixassemblyjob_2c_20datatype_20_3e_42',['BurgersAssemblyTaskBase&lt; BurgersBlockedMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersblockedvectorassemblyjob_2c_20datatype_20_3e_43',['BurgersAssemblyTaskBase&lt; BurgersBlockedVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersscalarmatrixassemblyjob_2c_20datatype_20_3e_44',['BurgersAssemblyTaskBase&lt; BurgersScalarMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersscalarvectorassemblyjob_2c_20datatype_20_3e_45',['BurgersAssemblyTaskBase&lt; BurgersScalarVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_46',['BurgersBlockedAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_3c_20burgersblockedmatrixassemblyjob_2c_20datatype_2c_20block_5fsize_20_3e_47',['BurgersBlockedAssemblyTaskBase&lt; BurgersBlockedMatrixAssemblyJob, DataType, block_size &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_3c_20burgersblockedvectorassemblyjob_2c_20datatype_2c_20block_5fsize_20_3e_48',['BurgersBlockedAssemblyTaskBase&lt; BurgersBlockedVectorAssemblyJob, DataType, block_size &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedmatrixassemblyjob_49',['BurgersBlockedMatrixAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_matrix_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersblockedvectorassemblyjob_50',['BurgersBlockedVectorAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_vector_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersdefectshareddataglobalwrapper_51',['BurgersDefectSharedDataGlobalWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_defect_shared_data_global_wrapper.html',1,'FEAT::VoxelAssembly']]],
  ['burgersscalarassemblytaskbase_52',['BurgersScalarAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarassemblytaskbase_3c_20burgersscalarmatrixassemblyjob_2c_20datatype_20_3e_53',['BurgersScalarAssemblyTaskBase&lt; BurgersScalarMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarassemblytaskbase_3c_20burgersscalarvectorassemblyjob_2c_20datatype_20_3e_54',['BurgersScalarAssemblyTaskBase&lt; BurgersScalarVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarmatrixassemblyjob_55',['BurgersScalarMatrixAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_matrix_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersscalarvectorassemblyjob_56',['BurgersScalarVectorAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_vector_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersshareddataglobalwrapper_57',['BurgersSharedDataGlobalWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_shared_data_global_wrapper.html',1,'FEAT::VoxelAssembly']]],
  ['burgersshareddatakernelwrapper_58',['BurgersSharedDataKernelWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_shared_data_kernel_wrapper.html',1,'FEAT::VoxelAssembly']]]
];
