var searchData=
[
  ['backend_0',['Backend',['../class_f_e_a_t_1_1_backend.html',1,'FEAT']]],
  ['barycentredriver_1',['BarycentreDriver',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver.html',1,'FEAT::Cubature']]],
  ['barycentredriver_3c_20shape_3a_3ahypercube_3c_20dim_5f_20_3e_20_3e_2',['BarycentreDriver&lt; Shape::Hypercube&lt; dim_ &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver_3_01_shape_1_1_hypercube_3_01dim___01_4_01_4.html',1,'FEAT::Cubature']]],
  ['barycentredriver_3c_20shape_3a_3asimplex_3c_20dim_5f_20_3e_20_3e_3',['BarycentreDriver&lt; Shape::Simplex&lt; dim_ &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_barycentre_driver_3_01_shape_1_1_simplex_3_01dim___01_4_01_4.html',1,'FEAT::Cubature']]],
  ['basicmatrixassemblytaskcrtp1_4',['BasicMatrixAssemblyTaskCRTP1',['../class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p1.html',1,'FEAT::Assembly']]],
  ['basicmatrixassemblytaskcrtp1_3c_20task_2c_20matrix_5f_2c_20space_5f_2c_20trafo_5fconfig_2c_20space_5fconfig_20_3e_5',['BasicMatrixAssemblyTaskCRTP1&lt; Task, Matrix_, Space_, trafo_config, space_config &gt;',['../class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p1.html',1,'FEAT::Assembly']]],
  ['basicmatrixassemblytaskcrtp2_6',['BasicMatrixAssemblyTaskCRTP2',['../class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p2.html',1,'FEAT::Assembly']]],
  ['basicmatrixassemblytaskcrtp2_3c_20task_2c_20matrix_5f_2c_20testspace_5f_2c_20trialspace_5f_2c_20trafo_5fconfig_2c_20test_5fconfig_2c_20trial_5fconfig_20_3e_7',['BasicMatrixAssemblyTaskCRTP2&lt; Task, Matrix_, TestSpace_, TrialSpace_, trafo_config, test_config, trial_config &gt;',['../class_f_e_a_t_1_1_assembly_1_1_basic_matrix_assembly_task_c_r_t_p2.html',1,'FEAT::Assembly']]],
  ['basicvectorassemblytaskcrtp_8',['BasicVectorAssemblyTaskCRTP',['../class_f_e_a_t_1_1_assembly_1_1_basic_vector_assembly_task_c_r_t_p.html',1,'FEAT::Assembly']]],
  ['basicvectorassemblytaskcrtp_3c_20task_2c_20vector_5f_2c_20space_5f_2c_20trafo_5fconfig_2c_20test_5fconfig_20_3e_9',['BasicVectorAssemblyTaskCRTP&lt; Task, Vector_, Space_, trafo_config, test_config &gt;',['../class_f_e_a_t_1_1_assembly_1_1_basic_vector_assembly_task_c_r_t_p.html',1,'FEAT::Assembly']]],
  ['basisdata_10',['BasisData',['../class_f_e_a_t_1_1_space_1_1_basis_data.html',1,'FEAT::Space']]],
  ['basisdatareduced_11',['BasisDataReduced',['../class_f_e_a_t_1_1_space_1_1_basis_data_reduced.html',1,'FEAT::Space']]],
  ['bezier_12',['Bezier',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierchartparser_13',['BezierChartParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_chart_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierparamsparser_14',['BezierParamsParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_params_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['bezierpointsparser_15',['BezierPointsParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_points_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['beziertraits_16',['BezierTraits',['../struct_f_e_a_t_1_1_geometry_1_1_atlas_1_1_bezier_traits.html',1,'FEAT::Geometry::Atlas']]],
  ['bicgstab_17',['BiCGStab',['../class_f_e_a_t_1_1_solver_1_1_bi_c_g_stab.html',1,'FEAT::Solver']]],
  ['bicgstabl_18',['BiCGStabL',['../class_f_e_a_t_1_1_solver_1_1_bi_c_g_stab_l.html',1,'FEAT::Solver']]],
  ['bilinearoperator_19',['BilinearOperator',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator.html',1,'FEAT::Assembly']]],
  ['bilinearoperatorassembler_20',['BilinearOperatorAssembler',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_assembler.html',1,'FEAT::Assembly']]],
  ['bilinearoperatormatrixassemblyjob1_21',['BilinearOperatorMatrixAssemblyJob1',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_matrix_assembly_job1.html',1,'FEAT::Assembly']]],
  ['bilinearoperatormatrixassemblyjob2_22',['BilinearOperatorMatrixAssemblyJob2',['../class_f_e_a_t_1_1_assembly_1_1_bilinear_operator_matrix_assembly_job2.html',1,'FEAT::Assembly']]],
  ['binarystream_23',['BinaryStream',['../class_f_e_a_t_1_1_binary_stream.html',1,'FEAT']]],
  ['binomial_24',['Binomial',['../struct_f_e_a_t_1_1_meta_math_1_1_binomial.html',1,'FEAT::MetaMath']]],
  ['blockedbasicsystemlevel_25',['BlockedBasicSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_basic_system_level.html',1,'FEAT::Control']]],
  ['blockedbasicsystemlevel_3c_20dim_5f_2c_20real_2c_20index_2c_20lafem_3a_3asparsematrixbcsr_3c_20real_2c_20index_2c_20dim_5f_2c_20dim_5f_20_3e_2c_20lafem_3a_3asparsematrixbwrappedcsr_3c_20real_2c_20index_2c_20dim_5f_20_3e_20_3e_26',['BlockedBasicSystemLevel&lt; dim_, Real, Index, LAFEM::SparseMatrixBCSR&lt; Real, Index, dim_, dim_ &gt;, LAFEM::SparseMatrixBWrappedCSR&lt; Real, Index, dim_ &gt; &gt;',['../class_f_e_a_t_1_1_control_1_1_blocked_basic_system_level.html',1,'FEAT::Control']]],
  ['blockedcombinedsystemlevel_27',['BlockedCombinedSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_combined_system_level.html',1,'FEAT::Control']]],
  ['blockedunitfiltersystemlevel_28',['BlockedUnitFilterSystemLevel',['../class_f_e_a_t_1_1_control_1_1_blocked_unit_filter_system_level.html',1,'FEAT::Control']]],
  ['booleanclass_29',['BooleanClass',['../class_f_e_a_t_1_1_type_1_1_boolean_class.html',1,'FEAT::Type']]],
  ['boomeramg_30',['BoomerAMG',['../class_f_e_a_t_1_1_solver_1_1_boomer_a_m_g.html',1,'FEAT::Solver']]],
  ['boundaryfactory_31',['BoundaryFactory',['../class_f_e_a_t_1_1_geometry_1_1_boundary_factory.html',1,'FEAT::Geometry']]],
  ['burgersassembler_32',['BurgersAssembler',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembler.html',1,'FEAT::Assembly']]],
  ['burgersassemblercarreau_33',['BurgersAssemblerCarreau',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembler_carreau.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_34',['BurgersAssemblyJobBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20matrix_5f_3a_3adatatype_2c_20space_5f_2c_20convvector_5f_20_3e_35',['BurgersAssemblyJobBase&lt; Matrix_::DataType, Space_, ConvVector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20matrix_5f_3a_3adatatype_2c_20space_5f_2c_20typename_20matrix_5f_3a_3avectortyper_20_3e_36',['BurgersAssemblyJobBase&lt; Matrix_::DataType, Space_, typename Matrix_::VectorTypeR &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20vector_5f_3a_3adatatype_2c_20space_5f_2c_20convvector_5f_20_3e_37',['BurgersAssemblyJobBase&lt; Vector_::DataType, Space_, ConvVector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblyjobbase_3c_20vector_5f_3a_3adatatype_2c_20space_5f_2c_20vector_5f_20_3e_38',['BurgersAssemblyJobBase&lt; Vector_::DataType, Space_, Vector_ &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_job_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_39',['BurgersAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersblockedmatrixassemblyjob_2c_20datatype_20_3e_40',['BurgersAssemblyTaskBase&lt; BurgersBlockedMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersblockedvectorassemblyjob_2c_20datatype_20_3e_41',['BurgersAssemblyTaskBase&lt; BurgersBlockedVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersscalarmatrixassemblyjob_2c_20datatype_20_3e_42',['BurgersAssemblyTaskBase&lt; BurgersScalarMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersassemblytaskbase_3c_20burgersscalarvectorassemblyjob_2c_20datatype_20_3e_43',['BurgersAssemblyTaskBase&lt; BurgersScalarVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_44',['BurgersBlockedAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_3c_20burgersblockedmatrixassemblyjob_2c_20datatype_2c_20block_5fsize_20_3e_45',['BurgersBlockedAssemblyTaskBase&lt; BurgersBlockedMatrixAssemblyJob, DataType, block_size &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedassemblytaskbase_3c_20burgersblockedvectorassemblyjob_2c_20datatype_2c_20block_5fsize_20_3e_46',['BurgersBlockedAssemblyTaskBase&lt; BurgersBlockedVectorAssemblyJob, DataType, block_size &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersblockedmatrixassemblyjob_47',['BurgersBlockedMatrixAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_matrix_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersblockedvectorassemblyjob_48',['BurgersBlockedVectorAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_blocked_vector_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersdefectshareddataglobalwrapper_49',['BurgersDefectSharedDataGlobalWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_defect_shared_data_global_wrapper.html',1,'FEAT::VoxelAssembly']]],
  ['burgersscalarassemblytaskbase_50',['BurgersScalarAssemblyTaskBase',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarassemblytaskbase_3c_20burgersscalarmatrixassemblyjob_2c_20datatype_20_3e_51',['BurgersScalarAssemblyTaskBase&lt; BurgersScalarMatrixAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarassemblytaskbase_3c_20burgersscalarvectorassemblyjob_2c_20datatype_20_3e_52',['BurgersScalarAssemblyTaskBase&lt; BurgersScalarVectorAssemblyJob, DataType &gt;',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_assembly_task_base.html',1,'FEAT::Assembly']]],
  ['burgersscalarmatrixassemblyjob_53',['BurgersScalarMatrixAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_matrix_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersscalarvectorassemblyjob_54',['BurgersScalarVectorAssemblyJob',['../class_f_e_a_t_1_1_assembly_1_1_burgers_scalar_vector_assembly_job.html',1,'FEAT::Assembly']]],
  ['burgersshareddataglobalwrapper_55',['BurgersSharedDataGlobalWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_shared_data_global_wrapper.html',1,'FEAT::VoxelAssembly']]],
  ['burgersshareddatakernelwrapper_56',['BurgersSharedDataKernelWrapper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_burgers_shared_data_kernel_wrapper.html',1,'FEAT::VoxelAssembly']]]
];
