var searchData=
[
  ['saddlepointmatrix_0',['SaddlePointMatrix',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_saddle_point_matrix.html',1,'FEAT::LAFEM']]],
  ['saddlepointmatrix_3c_20localmatrixblocka_2c_20localmatrixblockb_2c_20localmatrixblockd_20_3e_1',['SaddlePointMatrix&lt; LocalMatrixBlockA, LocalMatrixBlockB, LocalMatrixBlockD &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_saddle_point_matrix.html',1,'FEAT::LAFEM']]],
  ['saddlepointmatrixelement_2',['SaddlePointMatrixElement',['../struct_f_e_a_t_1_1_l_a_f_e_m_1_1_saddle_point_matrix_element.html',1,'FEAT::LAFEM']]],
  ['saddleumfpackmean_3',['SaddleUmfpackMean',['../class_f_e_a_t_1_1_solver_1_1_saddle_umfpack_mean.html',1,'FEAT::Solver']]],
  ['scalar_4',['Scalar',['../struct_f_e_a_t_1_1_analytic_1_1_image_1_1_scalar.html',1,'FEAT::Analytic::Image']]],
  ['scalarbasicsystemlevel_5',['ScalarBasicSystemLevel',['../class_f_e_a_t_1_1_control_1_1_scalar_basic_system_level.html',1,'FEAT::Control']]],
  ['scalarbasicsystemlevel_3c_20real_2c_20index_2c_20lafem_3a_3asparsematrixcsr_3c_20real_2c_20index_20_3e_20_3e_6',['ScalarBasicSystemLevel&lt; Real, Index, LAFEM::SparseMatrixCSR&lt; Real, Index &gt; &gt;',['../class_f_e_a_t_1_1_control_1_1_scalar_basic_system_level.html',1,'FEAT::Control']]],
  ['scalarcombinedsystemlevel_7',['ScalarCombinedSystemLevel',['../class_f_e_a_t_1_1_control_1_1_scalar_combined_system_level.html',1,'FEAT::Control']]],
  ['scalarcurl_8',['ScalarCurl',['../class_f_e_a_t_1_1_analytic_1_1_scalar_curl.html',1,'FEAT::Analytic']]],
  ['scalardiscreteevaldata_9',['ScalarDiscreteEvalData',['../class_f_e_a_t_1_1_assembly_1_1_scalar_discrete_eval_data.html',1,'FEAT::Assembly']]],
  ['scalarerrorcomputer_10',['ScalarErrorComputer',['../class_f_e_a_t_1_1_assembly_1_1_scalar_error_computer.html',1,'FEAT::Assembly']]],
  ['scalarerrorinfo_11',['ScalarErrorInfo',['../struct_f_e_a_t_1_1_assembly_1_1_scalar_error_info.html',1,'FEAT::Assembly']]],
  ['scalarmeanfiltersystemlevel_12',['ScalarMeanFilterSystemLevel',['../class_f_e_a_t_1_1_control_1_1_scalar_mean_filter_system_level.html',1,'FEAT::Control']]],
  ['scalarmixedsystemlevel_13',['ScalarMixedSystemLevel',['../class_f_e_a_t_1_1_control_1_1_scalar_mixed_system_level.html',1,'FEAT::Control']]],
  ['scalarunitfiltersystemlevel_14',['ScalarUnitFilterSystemLevel',['../class_f_e_a_t_1_1_control_1_1_scalar_unit_filter_system_level.html',1,'FEAT::Control']]],
  ['scale_15',['Scale',['../struct_f_e_a_t_1_1_l_a_f_e_m_1_1_arch_1_1_scale.html',1,'FEAT::LAFEM::Arch']]],
  ['scalecols_16',['ScaleCols',['../struct_f_e_a_t_1_1_l_a_f_e_m_1_1_arch_1_1_scale_cols.html',1,'FEAT::LAFEM::Arch']]],
  ['scaleprecond_17',['ScalePrecond',['../class_f_e_a_t_1_1_solver_1_1_scale_precond.html',1,'FEAT::Solver']]],
  ['scalerows_18',['ScaleRows',['../struct_f_e_a_t_1_1_l_a_f_e_m_1_1_arch_1_1_scale_rows.html',1,'FEAT::LAFEM::Arch']]],
  ['scanner_19',['Scanner',['../class_f_e_a_t_1_1_xml_1_1_scanner.html',1,'FEAT::Xml']]],
  ['scatteraxpy_20',['ScatterAxpy',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_dense_vector_1_1_scatter_axpy.html',1,'FEAT::LAFEM::DenseVector&lt; DT_, IT_ &gt;::ScatterAxpy'],['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_dense_vector_blocked_1_1_scatter_axpy.html',1,'FEAT::LAFEM::DenseVectorBlocked&lt; DT_, IT_, BlockSize_ &gt;::ScatterAxpy'],['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_banded_1_1_scatter_axpy.html',1,'FEAT::LAFEM::SparseMatrixBanded&lt; DT_, IT_ &gt;::ScatterAxpy'],['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_b_c_s_r_1_1_scatter_axpy.html',1,'FEAT::LAFEM::SparseMatrixBCSR&lt; DT_, IT_, BlockHeight_, BlockWidth_ &gt;::ScatterAxpy'],['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_r_1_1_scatter_axpy.html',1,'FEAT::LAFEM::SparseMatrixCSR&lt; DT_, IT_ &gt;::ScatterAxpy']]],
  ['schwarzprecond_21',['SchwarzPrecond',['../class_f_e_a_t_1_1_solver_1_1_schwarz_precond.html',1,'FEAT::Solver']]],
  ['schwarzprecond_3c_20global_3a_3avector_3c_20localvector_5f_2c_20mirror_5f_20_3e_2c_20global_3a_3afilter_3c_20localfilter_5f_2c_20mirror_5f_20_3e_20_3e_22',['SchwarzPrecond&lt; Global::Vector&lt; LocalVector_, Mirror_ &gt;, Global::Filter&lt; LocalFilter_, Mirror_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_schwarz_precond_3_01_global_1_1_vector_3_01_local_vector___00_01_mic9e5dece21cb7735a0bc194fb3569eb4.html',1,'FEAT::Solver']]],
  ['scopeguard_23',['ScopeGuard',['../class_f_e_a_t_1_1_runtime_1_1_scope_guard.html',1,'FEAT::Runtime']]],
  ['secantlinesearch_24',['SecantLinesearch',['../class_f_e_a_t_1_1_solver_1_1_secant_linesearch.html',1,'FEAT::Solver']]],
  ['serialconfig_25',['SerialConfig',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_serial_config.html',1,'FEAT::LAFEM']]],
  ['shapeconvertfactory_26',['ShapeConvertFactory',['../class_f_e_a_t_1_1_geometry_1_1_shape_convert_factory.html',1,'FEAT::Geometry']]],
  ['shapeconvertfactory_3c_20conformalmesh_3c_20shape_5f_2c_20num_5fcoords_5f_2c_20coord_5f_20_3e_20_3e_27',['ShapeConvertFactory&lt; ConformalMesh&lt; Shape_, num_coords_, Coord_ &gt; &gt;',['../class_f_e_a_t_1_1_geometry_1_1_shape_convert_factory_3_01_conformal_mesh_3_01_shape___00_01num__ddbfcb9c037d180b3bd81aab02e7610b.html',1,'FEAT::Geometry']]],
  ['shapeconvertfactory_3c_20meshpart_3c_20conformalmesh_3c_20shape_5f_2c_20shape_5f_3a_3adimension_2c_20coord_5f_20_3e_20_3e_20_3e_28',['ShapeConvertFactory&lt; MeshPart&lt; ConformalMesh&lt; Shape_, Shape_::dimension, Coord_ &gt; &gt; &gt;',['../class_f_e_a_t_1_1_geometry_1_1_shape_convert_factory_3_01_mesh_part_3_01_conformal_mesh_3_01_shaef7d1b90fe5d8f8564ae577ae496f5bd.html',1,'FEAT::Geometry']]],
  ['shunnhamdriver_29',['ShunnHamDriver',['../class_f_e_a_t_1_1_cubature_1_1_shunn_ham_driver.html',1,'FEAT::Cubature']]],
  ['shunnhamdriver_3c_20shape_3a_3asimplex_3c_203_20_3e_20_3e_30',['ShunnHamDriver&lt; Shape::Simplex&lt; 3 &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_shunn_ham_driver_3_01_shape_1_1_simplex_3_013_01_4_01_4.html',1,'FEAT::Cubature']]],
  ['silvesteropendriver_31',['SilvesterOpenDriver',['../class_f_e_a_t_1_1_cubature_1_1_silvester_open_driver.html',1,'FEAT::Cubature']]],
  ['silvesteropendriver_3c_20shape_3a_3asimplex_3c_202_20_3e_20_3e_32',['SilvesterOpenDriver&lt; Shape::Simplex&lt; 2 &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_silvester_open_driver_3_01_shape_1_1_simplex_3_012_01_4_01_4.html',1,'FEAT::Cubature']]],
  ['simpleargparser_33',['SimpleArgParser',['../class_f_e_a_t_1_1_simple_arg_parser.html',1,'FEAT']]],
  ['simpledomainlevel_34',['SimpleDomainLevel',['../class_f_e_a_t_1_1_control_1_1_domain_1_1_simple_domain_level.html',1,'FEAT::Control::Domain']]],
  ['simplex_35',['Simplex',['../struct_f_e_a_t_1_1_shape_1_1_simplex.html',1,'FEAT::Shape']]],
  ['simplexscalarfactory_36',['SimplexScalarFactory',['../class_f_e_a_t_1_1_cubature_1_1_simplex_scalar_factory.html',1,'FEAT::Cubature']]],
  ['simplexscalarfactory_3c_20scalardriver_5f_2c_20false_20_3e_37',['SimplexScalarFactory&lt; ScalarDriver_, false &gt;',['../class_f_e_a_t_1_1_cubature_1_1_simplex_scalar_factory_3_01_scalar_driver___00_01false_01_4.html',1,'FEAT::Cubature']]],
  ['simplexscalarfactory_3c_20scalardriver_5f_2c_20true_20_3e_38',['SimplexScalarFactory&lt; ScalarDriver_, true &gt;',['../class_f_e_a_t_1_1_cubature_1_1_simplex_scalar_factory_3_01_scalar_driver___00_01true_01_4.html',1,'FEAT::Cubature']]],
  ['simplexscalarfactorybase_39',['SimplexScalarFactoryBase',['../class_f_e_a_t_1_1_cubature_1_1_simplex_scalar_factory_base.html',1,'FEAT::Cubature']]],
  ['sineringvortexpres2d_40',['SineRingVortexPres2D',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_sine_ring_vortex_pres2_d.html',1,'FEAT::Analytic::Common']]],
  ['sineringvortexrhs2d_41',['SineRingVortexRHS2D',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_sine_ring_vortex_r_h_s2_d.html',1,'FEAT::Analytic::Common']]],
  ['sineringvortexvelo2d_42',['SineRingVortexVelo2D',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_sine_ring_vortex_velo2_d.html',1,'FEAT::Analytic::Common']]],
  ['sinetensorstatic_43',['SineTensorStatic',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_sine_tensor_static.html',1,'FEAT::Analytic::Common']]],
  ['singularmatrixexception_44',['SingularMatrixException',['../class_f_e_a_t_1_1_solver_1_1_singular_matrix_exception.html',1,'FEAT::Solver']]],
  ['sinyt0_45',['SinYT0',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_sin_y_t0.html',1,'FEAT::Analytic::Common']]],
  ['sinyt0stokesrhs_46',['SinYT0StokesRhs',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_sin_y_t0_stokes_rhs.html',1,'FEAT::Analytic::Common']]],
  ['slipfilter_47',['SlipFilter',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_slip_filter.html',1,'FEAT::LAFEM']]],
  ['slipfilterassembler_48',['SlipFilterAssembler',['../class_f_e_a_t_1_1_assembly_1_1_slip_filter_assembler.html',1,'FEAT::Assembly']]],
  ['solverbase_49',['SolverBase',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20functional_5f_3a_3avectortyper_20_3e_50',['SolverBase&lt; Functional_::VectorTypeR &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20global_3a_3avector_3c_20lafem_3a_3atuplevector_3c_20matrixb_5f_3a_3avectortypel_2c_20matrixd_5f_3a_3avectortypel_20_3e_2c_20lafem_3a_3atuplemirror_3c_20mirrorv_5f_2c_20mirrorp_5f_20_3e_20_3e_20_3e_51',['SolverBase&lt; Global::Vector&lt; LAFEM::TupleVector&lt; MatrixB_::VectorTypeL, MatrixD_::VectorTypeL &gt;, LAFEM::TupleMirror&lt; MirrorV_, MirrorP_ &gt; &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20global_3a_3avector_3c_20localmatrix_5f_3a_3avectortyper_2c_20mirror_5f_20_3e_20_3e_52',['SolverBase&lt; Global::Vector&lt; LocalMatrix_::VectorTypeR, Mirror_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20global_3a_3avector_3c_20localvector_5f_2c_20mirror_5f_20_3e_20_3e_53',['SolverBase&lt; Global::Vector&lt; LocalVector_, Mirror_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20global_3a_3avector_3c_20localvectorouter_5f_2c_20mirrorouter_5f_20_3e_20_3e_54',['SolverBase&lt; Global::Vector&lt; LocalVectorOuter_, MirrorOuter_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20lafem_3a_3adensevector_3c_20double_2c_20index_20_3e_20_3e_55',['SolverBase&lt; LAFEM::DenseVector&lt; double, Index &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20lafem_3a_3adensevector_3c_20double_2c_20unsigned_20int_20_3e_20_3e_56',['SolverBase&lt; LAFEM::DenseVector&lt; double, unsigned int &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20lafem_3a_3atuplevector_3c_20lafem_3a_3adensevectorblocked_3c_20dt_5f_2c_20it_5f_2c_20dim_5f_20_3e_2c_20lafem_3a_3adensevector_3c_20dt_5f_2c_20it_5f_20_3e_20_3e_20_3e_57',['SolverBase&lt; LAFEM::TupleVector&lt; LAFEM::DenseVectorBlocked&lt; DT_, IT_, dim_ &gt;, LAFEM::DenseVector&lt; DT_, IT_ &gt; &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20lafem_3a_3atuplevector_3c_20matrixb_5f_3a_3avectortypel_2c_20matrixd_5f_3a_3avectortypel_20_3e_20_3e_58',['SolverBase&lt; LAFEM::TupleVector&lt; MatrixB_::VectorTypeL, MatrixD_::VectorTypeL &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20matrix_5f_3a_3avectortypel_20_3e_59',['SolverBase&lt; Matrix_::VectorTypeL &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20matrix_5f_3a_3avectortyper_20_3e_60',['SolverBase&lt; Matrix_::VectorTypeR &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20nonlinearoperator_5f_3a_3asystemleveltype_3a_3aglobalsystemvectorr_20_3e_61',['SolverBase&lt; NonlinearOperator_::SystemLevelType::GlobalSystemVectorR &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20operator_5f_3a_3avectortype_20_3e_62',['SolverBase&lt; Operator_::VectorType &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20operatortype_5f_3a_3avectortype_20_3e_63',['SolverBase&lt; OperatorType_::VectorType &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20systemmatrix_5f_3a_3avectortyper_20_3e_64',['SolverBase&lt; SystemMatrix_::VectorTypeR &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20typename_20matrix_5f_3a_3avectortypel_20_3e_65',['SolverBase&lt; typename Matrix_::VectorTypeL &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20vectorouter_5f_20_3e_66',['SolverBase&lt; VectorOuter_ &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverbase_3c_20vectortype_5f_20_3e_67',['SolverBase&lt; VectorType_ &gt;',['../class_f_e_a_t_1_1_solver_1_1_solver_base.html',1,'FEAT::Solver']]],
  ['solverexception_68',['SolverException',['../class_f_e_a_t_1_1_solver_1_1_solver_exception.html',1,'FEAT::Solver']]],
  ['sorprecond_69',['SORPrecond',['../class_f_e_a_t_1_1_solver_1_1_s_o_r_precond.html',1,'FEAT::Solver']]],
  ['sorprecondbase_70',['SORPrecondBase',['../class_f_e_a_t_1_1_solver_1_1_s_o_r_precond_base.html',1,'FEAT::Solver']]],
  ['sorprecondbase_3c_20lafem_3a_3asparsematrixbcsr_3c_20dt_5f_2c_20it_5f_2c_20blockheight_5f_2c_20blockwidth_5f_20_3e_20_3e_71',['SORPrecondBase&lt; LAFEM::SparseMatrixBCSR&lt; DT_, IT_, BlockHeight_, BlockWidth_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_s_o_r_precond_base.html',1,'FEAT::Solver']]],
  ['sorprecondbase_3c_20lafem_3a_3asparsematrixcsr_3c_20dt_5f_2c_20it_5f_20_3e_20_3e_72',['SORPrecondBase&lt; LAFEM::SparseMatrixCSR&lt; DT_, IT_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_s_o_r_precond_base.html',1,'FEAT::Solver']]],
  ['sorprecondwithbackend_73',['SORPrecondWithBackend',['../class_f_e_a_t_1_1_solver_1_1_s_o_r_precond_with_backend.html',1,'FEAT::Solver']]],
  ['sorprecondwithbackend_3c_20preferredbackend_3a_3ageneric_2c_20lafem_3a_3asparsematrixbcsr_3c_20dt_5f_2c_20it_5f_2c_20blockheight_5f_2c_20blockwidth_5f_20_3e_2c_20filter_5f_20_3e_74',['SORPrecondWithBackend&lt; PreferredBackend::generic, LAFEM::SparseMatrixBCSR&lt; DT_, IT_, BlockHeight_, BlockWidth_ &gt;, Filter_ &gt;',['../class_f_e_a_t_1_1_solver_1_1_s_o_r_precond_with_backend_3_01_preferred_backend_1_1generic_00_01_b057fb2a8d1f4c64f3e3aed2663fd10f.html',1,'FEAT::Solver']]],
  ['sorprecondwithbackend_3c_20preferredbackend_3a_3ageneric_2c_20lafem_3a_3asparsematrixcsr_3c_20dt_5f_2c_20it_5f_20_3e_2c_20filter_5f_20_3e_75',['SORPrecondWithBackend&lt; PreferredBackend::generic, LAFEM::SparseMatrixCSR&lt; DT_, IT_ &gt;, Filter_ &gt;',['../class_f_e_a_t_1_1_solver_1_1_s_o_r_precond_with_backend_3_01_preferred_backend_1_1generic_00_01_b01c4c6795db9d1026723694e15647be.html',1,'FEAT::Solver']]],
  ['spacehelper_76',['SpaceHelper',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_space_helper.html',1,'FEAT::VoxelAssembly']]],
  ['spacehelper_3c_20q2standardfe_3c_20shape_5f_20_3e_2c_20dt_5f_2c_20it_5f_20_3e_77',['SpaceHelper&lt; Q2StandardFE&lt; Shape_ &gt;, DT_, IT_ &gt;',['../struct_f_e_a_t_1_1_voxel_assembly_1_1_space_helper_3_01_q2_standard_f_e_3_01_shape___01_4_00_01_d_t___00_01_i_t___01_4.html',1,'FEAT::VoxelAssembly']]],
  ['sparselayout_78',['SparseLayout',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_layout.html',1,'FEAT::LAFEM']]],
  ['sparsematrixbanded_79',['SparseMatrixBanded',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_banded.html',1,'FEAT::LAFEM']]],
  ['sparsematrixbcsr_80',['SparseMatrixBCSR',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_b_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixbcsr_3c_20datatype_2c_20indextype_2c_20dim_2c_201_20_3e_81',['SparseMatrixBCSR&lt; DataType, IndexType, dim, 1 &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_b_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixbcsr_3c_20dt_5f_2c_20it_5f_2c_20meshtype_3a_3aworld_5fdim_2c_20meshtype_3a_3aworld_5fdim_20_3e_82',['SparseMatrixBCSR&lt; DT_, IT_, MeshType::world_dim, MeshType::world_dim &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_b_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixbwrappedcsr_83',['SparseMatrixBWrappedCSR',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_b_wrapped_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixcscr_84',['SparseMatrixCSCR',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_c_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixcsr_85',['SparseMatrixCSR',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixcsr_3c_20datatype_2c_20indextype_20_3e_86',['SparseMatrixCSR&lt; DataType, IndexType &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixcsr_3c_20double_2c_20index_20_3e_87',['SparseMatrixCSR&lt; double, Index &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixcsr_3c_20double_2c_20unsigned_20int_20_3e_88',['SparseMatrixCSR&lt; double, unsigned int &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixcsr_3c_20dt_5f_2c_20it_5f_20_3e_89',['SparseMatrixCSR&lt; DT_, IT_ &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixcsr_3c_20solverdatatype_2c_20solverindextype_20_3e_90',['SparseMatrixCSR&lt; SolverDataType, SolverIndexType &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_c_s_r.html',1,'FEAT::LAFEM']]],
  ['sparsematrixfactory_91',['SparseMatrixFactory',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_matrix_factory.html',1,'FEAT::LAFEM']]],
  ['sparsevector_92',['SparseVector',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_vector.html',1,'FEAT::LAFEM']]],
  ['sparsevector_3c_20dt_5f_2c_20index_20_3e_93',['SparseVector&lt; DT_, Index &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_vector.html',1,'FEAT::LAFEM']]],
  ['sparsevectorblocked_94',['SparseVectorBlocked',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_vector_blocked.html',1,'FEAT::LAFEM']]],
  ['sparsevectorblocked_3c_20datatype_2c_20indextype_2c_20blocksize_20_3e_95',['SparseVectorBlocked&lt; DataType, IndexType, BlockSize &gt;',['../class_f_e_a_t_1_1_l_a_f_e_m_1_1_sparse_vector_blocked.html',1,'FEAT::LAFEM']]],
  ['sphere_96',['Sphere',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_sphere.html',1,'FEAT::Geometry::Atlas']]],
  ['spherechartparser_97',['SphereChartParser',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_sphere_chart_parser.html',1,'FEAT::Geometry::Atlas']]],
  ['spherehittestfunction_98',['SphereHitTestFunction',['../class_f_e_a_t_1_1_geometry_1_1_sphere_hit_test_function.html',1,'FEAT::Geometry']]],
  ['spheresinbubblefunction_99',['SphereSinBubbleFunction',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_sphere_sin_bubble_function.html',1,'FEAT::Analytic::Common']]],
  ['spheretraits_100',['SphereTraits',['../struct_f_e_a_t_1_1_geometry_1_1_atlas_1_1_sphere_traits.html',1,'FEAT::Geometry::Atlas']]],
  ['splitter_101',['Splitter',['../class_f_e_a_t_1_1_global_1_1_splitter.html',1,'FEAT::Global']]],
  ['splitter_3c_20localpresvector_2c_20presmirror_20_3e_102',['Splitter&lt; LocalPresVector, PresMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_splitter.html',1,'FEAT::Global']]],
  ['splitter_3c_20localscalarvector_2c_20scalarmirror_20_3e_103',['Splitter&lt; LocalScalarVector, ScalarMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_splitter.html',1,'FEAT::Global']]],
  ['splitter_3c_20localsystemvector_2c_20systemmirror_20_3e_104',['Splitter&lt; LocalSystemVector, SystemMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_splitter.html',1,'FEAT::Global']]],
  ['splitter_3c_20localvelovector_2c_20velomirror_20_3e_105',['Splitter&lt; LocalVeloVector, VeloMirror &gt;',['../class_f_e_a_t_1_1_global_1_1_splitter.html',1,'FEAT::Global']]],
  ['ssorprecond_106',['SSORPrecond',['../class_f_e_a_t_1_1_solver_1_1_s_s_o_r_precond.html',1,'FEAT::Solver']]],
  ['ssorprecondbase_107',['SSORPrecondBase',['../class_f_e_a_t_1_1_solver_1_1_s_s_o_r_precond_base.html',1,'FEAT::Solver']]],
  ['ssorprecondbase_3c_20lafem_3a_3asparsematrixbcsr_3c_20dt_5f_2c_20it_5f_2c_20blockheight_5f_2c_20blockwidth_5f_20_3e_20_3e_108',['SSORPrecondBase&lt; LAFEM::SparseMatrixBCSR&lt; DT_, IT_, BlockHeight_, BlockWidth_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_s_s_o_r_precond_base.html',1,'FEAT::Solver']]],
  ['ssorprecondbase_3c_20lafem_3a_3asparsematrixcsr_3c_20dt_5f_2c_20it_5f_20_3e_20_3e_109',['SSORPrecondBase&lt; LAFEM::SparseMatrixCSR&lt; DT_, IT_ &gt; &gt;',['../class_f_e_a_t_1_1_solver_1_1_s_s_o_r_precond_base.html',1,'FEAT::Solver']]],
  ['ssorprecondwithbackend_110',['SSORPrecondWithBackend',['../class_f_e_a_t_1_1_solver_1_1_s_s_o_r_precond_with_backend.html',1,'FEAT::Solver']]],
  ['ssorprecondwithbackend_3c_20preferredbackend_3a_3ageneric_2c_20lafem_3a_3asparsematrixbcsr_3c_20dt_5f_2c_20it_5f_2c_20blockheight_5f_2c_20blockwidth_5f_20_3e_2c_20filter_5f_20_3e_111',['SSORPrecondWithBackend&lt; PreferredBackend::generic, LAFEM::SparseMatrixBCSR&lt; DT_, IT_, BlockHeight_, BlockWidth_ &gt;, Filter_ &gt;',['../class_f_e_a_t_1_1_solver_1_1_s_s_o_r_precond_with_backend_3_01_preferred_backend_1_1generic_00_03cc9221468c00ec17113383d091b5dfc.html',1,'FEAT::Solver']]],
  ['ssorprecondwithbackend_3c_20preferredbackend_3a_3ageneric_2c_20lafem_3a_3asparsematrixcsr_3c_20dt_5f_2c_20it_5f_20_3e_2c_20filter_5f_20_3e_112',['SSORPrecondWithBackend&lt; PreferredBackend::generic, LAFEM::SparseMatrixCSR&lt; DT_, IT_ &gt;, Filter_ &gt;',['../class_f_e_a_t_1_1_solver_1_1_s_s_o_r_precond_with_backend_3_01_preferred_backend_1_1generic_00_09cdd27baeeaa7c4869529b76c2c5d109.html',1,'FEAT::Solver']]],
  ['standardevalpolicy_113',['StandardEvalPolicy',['../struct_f_e_a_t_1_1_trafo_1_1_standard_eval_policy.html',1,'FEAT::Trafo']]],
  ['standardrefinery_114',['StandardRefinery',['../class_f_e_a_t_1_1_geometry_1_1_standard_refinery.html',1,'FEAT::Geometry']]],
  ['standardrefinery_3c_20conformalmesh_3c_20shape_5f_2c_20num_5fcoords_5f_2c_20coordtype_5f_20_3e_20_3e_115',['StandardRefinery&lt; ConformalMesh&lt; Shape_, num_coords_, CoordType_ &gt; &gt;',['../class_f_e_a_t_1_1_geometry_1_1_standard_refinery_3_01_conformal_mesh_3_01_shape___00_01num__coor2b7a1f41c741938e6ddb9e7bf2c48774.html',1,'FEAT::Geometry']]],
  ['standardrefinery_3c_20meshpart_3c_20parentmesh_5f_20_3e_20_3e_116',['StandardRefinery&lt; MeshPart&lt; ParentMesh_ &gt; &gt;',['../class_f_e_a_t_1_1_geometry_1_1_standard_refinery_3_01_mesh_part_3_01_parent_mesh___01_4_01_4.html',1,'FEAT::Geometry']]],
  ['standardrefinery_3c_20structuredmesh_3c_20shape_5fdim_5f_2c_20num_5fcoords_5f_2c_20coord_5f_20_3e_20_3e_117',['StandardRefinery&lt; StructuredMesh&lt; shape_dim_, num_coords_, Coord_ &gt; &gt;',['../class_f_e_a_t_1_1_geometry_1_1_standard_refinery_3_01_structured_mesh_3_01shape__dim___00_01num_b4b6d554135f436a9680aeb85e74df96.html',1,'FEAT::Geometry']]],
  ['standardscalarevaltraits_118',['StandardScalarEvalTraits',['../class_f_e_a_t_1_1_space_1_1_standard_scalar_eval_traits.html',1,'FEAT::Space']]],
  ['standardvectorevaltraits_119',['StandardVectorEvalTraits',['../class_f_e_a_t_1_1_space_1_1_standard_vector_eval_traits.html',1,'FEAT::Space']]],
  ['standingvortexfunction2d_120',['StandingVortexFunction2D',['../class_f_e_a_t_1_1_analytic_1_1_common_1_1_standing_vortex_function2_d.html',1,'FEAT::Analytic::Common']]],
  ['staticfunction_121',['StaticFunction',['../class_f_e_a_t_1_1_analytic_1_1_static_function.html',1,'FEAT::Analytic']]],
  ['staticwrapperfunction_122',['StaticWrapperFunction',['../class_f_e_a_t_1_1_analytic_1_1_static_wrapper_function.html',1,'FEAT::Analytic']]],
  ['statistics_123',['Statistics',['../class_f_e_a_t_1_1_control_1_1_statistics.html',1,'FEAT::Control::Statistics'],['../class_f_e_a_t_1_1_statistics.html',1,'FEAT::Statistics']]],
  ['status_124',['Status',['../class_f_e_a_t_1_1_dist_1_1_status.html',1,'FEAT::Dist']]],
  ['stdpolyp_125',['StdPolyP',['../struct_f_e_a_t_1_1_space_1_1_discontinuous_1_1_variant_1_1_std_poly_p.html',1,'FEAT::Space::Discontinuous::Variant']]],
  ['stokes3fielddomainlevel_126',['Stokes3FieldDomainLevel',['../class_f_e_a_t_1_1_control_1_1_domain_1_1_stokes3_field_domain_level.html',1,'FEAT::Control::Domain']]],
  ['stokes3fieldsystemlevel_127',['Stokes3FieldSystemLevel',['../class_f_e_a_t_1_1_control_1_1_stokes3_field_system_level.html',1,'FEAT::Control']]],
  ['stokesblockedcombinedsystemlevel_128',['StokesBlockedCombinedSystemLevel',['../class_f_e_a_t_1_1_control_1_1_stokes_blocked_combined_system_level.html',1,'FEAT::Control']]],
  ['stokesblockedslipunitvelomeanpressystemlevel_129',['StokesBlockedSlipUnitVeloMeanPresSystemLevel',['../class_f_e_a_t_1_1_control_1_1_stokes_blocked_slip_unit_velo_mean_pres_system_level.html',1,'FEAT::Control']]],
  ['stokesblockedslipunitvelononepressystemlevel_130',['StokesBlockedSlipUnitVeloNonePresSystemLevel',['../class_f_e_a_t_1_1_control_1_1_stokes_blocked_slip_unit_velo_none_pres_system_level.html',1,'FEAT::Control']]],
  ['stokesblockedsystemlevel_131',['StokesBlockedSystemLevel',['../class_f_e_a_t_1_1_control_1_1_stokes_blocked_system_level.html',1,'FEAT::Control']]],
  ['stokesblockedsystemlevel_3c_20dim_5f_2c_20real_2c_20index_2c_20lafem_3a_3asparsematrixbcsr_3c_20real_2c_20index_2c_20dim_5f_2c_20dim_5f_20_3e_2c_20lafem_3a_3asparsematrixbcsr_3c_20real_2c_20index_2c_20dim_5f_2c_201_20_3e_2c_20lafem_3a_3asparsematrixbcsr_3c_20real_2c_20index_2c_201_2c_20dim_5f_20_3e_2c_20lafem_3a_3asparsematrixcsr_3c_20real_2c_20index_20_3e_2c_20lafem_3a_3asparsematrixbwrappedcsr_3c_20real_2c_20index_2c_20dim_5f_20_3e_2c_20lafem_3a_3asparsematrixcsr_3c_20real_2c_20index_20_3e_20_3e_132',['StokesBlockedSystemLevel&lt; dim_, Real, Index, LAFEM::SparseMatrixBCSR&lt; Real, Index, dim_, dim_ &gt;, LAFEM::SparseMatrixBCSR&lt; Real, Index, dim_, 1 &gt;, LAFEM::SparseMatrixBCSR&lt; Real, Index, 1, dim_ &gt;, LAFEM::SparseMatrixCSR&lt; Real, Index &gt;, LAFEM::SparseMatrixBWrappedCSR&lt; Real, Index, dim_ &gt;, LAFEM::SparseMatrixCSR&lt; Real, Index &gt; &gt;',['../class_f_e_a_t_1_1_control_1_1_stokes_blocked_system_level.html',1,'FEAT::Control']]],
  ['stokesblockedunitvelomeanpressystemlevel_133',['StokesBlockedUnitVeloMeanPresSystemLevel',['../struct_f_e_a_t_1_1_control_1_1_stokes_blocked_unit_velo_mean_pres_system_level.html',1,'FEAT::Control']]],
  ['stokesblockedunitvelononepressystemlevel_134',['StokesBlockedUnitVeloNonePresSystemLevel',['../class_f_e_a_t_1_1_control_1_1_stokes_blocked_unit_velo_none_pres_system_level.html',1,'FEAT::Control']]],
  ['stokesdomainlevel_135',['StokesDomainLevel',['../class_f_e_a_t_1_1_control_1_1_domain_1_1_stokes_domain_level.html',1,'FEAT::Control::Domain']]],
  ['stokesfbmassembler_136',['StokesFBMAssembler',['../class_f_e_a_t_1_1_assembly_1_1_stokes_f_b_m_assembler.html',1,'FEAT::Assembly']]],
  ['stokespowersystemlevel_137',['StokesPowerSystemLevel',['../struct_f_e_a_t_1_1_control_1_1_stokes_power_system_level.html',1,'FEAT::Control']]],
  ['stokespowersystemlevel_3c_20dim_5f_2c_20real_2c_20index_2c_20lafem_3a_3asparsematrixcsr_3c_20real_2c_20index_20_3e_20_3e_138',['StokesPowerSystemLevel&lt; dim_, Real, Index, LAFEM::SparseMatrixCSR&lt; Real, Index &gt; &gt;',['../struct_f_e_a_t_1_1_control_1_1_stokes_power_system_level.html',1,'FEAT::Control']]],
  ['stokespowerunitvelomeanpressystemlevel_139',['StokesPowerUnitVeloMeanPresSystemLevel',['../struct_f_e_a_t_1_1_control_1_1_stokes_power_unit_velo_mean_pres_system_level.html',1,'FEAT::Control']]],
  ['stokespowerunitvelononepressystemlevel_140',['StokesPowerUnitVeloNonePresSystemLevel',['../struct_f_e_a_t_1_1_control_1_1_stokes_power_unit_velo_none_pres_system_level.html',1,'FEAT::Control']]],
  ['stopwatch_141',['StopWatch',['../class_f_e_a_t_1_1_stop_watch.html',1,'FEAT']]],
  ['strainratetensoroperator_142',['StrainRateTensorOperator',['../class_f_e_a_t_1_1_assembly_1_1_common_1_1_strain_rate_tensor_operator.html',1,'FEAT::Assembly::Common']]],
  ['stressdivergenceoperator_143',['StressDivergenceOperator',['../class_f_e_a_t_1_1_assembly_1_1_common_1_1_stress_divergence_operator.html',1,'FEAT::Assembly::Common']]],
  ['string_144',['String',['../class_f_e_a_t_1_1_string.html',1,'FEAT']]],
  ['stringmapped_145',['StringMapped',['../class_f_e_a_t_1_1_string_mapped.html',1,'FEAT']]],
  ['structindexset_146',['StructIndexSet',['../class_f_e_a_t_1_1_geometry_1_1_struct_index_set.html',1,'FEAT::Geometry']]],
  ['structuredmesh_147',['StructuredMesh',['../class_f_e_a_t_1_1_geometry_1_1_structured_mesh.html',1,'FEAT::Geometry']]],
  ['superlu_148',['SuperLU',['../class_f_e_a_t_1_1_solver_1_1_super_l_u.html',1,'FEAT::Solver']]],
  ['surfacemesh_149',['SurfaceMesh',['../class_f_e_a_t_1_1_geometry_1_1_atlas_1_1_surface_mesh.html',1,'FEAT::Geometry::Atlas']]],
  ['surfacemeshtraits_150',['SurfaceMeshTraits',['../struct_f_e_a_t_1_1_geometry_1_1_atlas_1_1_surface_mesh_traits.html',1,'FEAT::Geometry::Atlas']]],
  ['symbolicassembler_151',['SymbolicAssembler',['../class_f_e_a_t_1_1_assembly_1_1_symbolic_assembler.html',1,'FEAT::Assembly']]],
  ['symmetriclumpedschurmatrix_152',['SymmetricLumpedSchurMatrix',['../class_f_e_a_t_1_1_global_1_1_symmetric_lumped_schur_matrix.html',1,'FEAT::Global']]],
  ['symmetricsimplexdriver_153',['SymmetricSimplexDriver',['../class_f_e_a_t_1_1_cubature_1_1_symmetric_simplex_driver.html',1,'FEAT::Cubature']]],
  ['symmetricsimplexdriver_3c_20shape_3a_3asimplex_3c_202_20_3e_20_3e_154',['SymmetricSimplexDriver&lt; Shape::Simplex&lt; 2 &gt; &gt;',['../class_f_e_a_t_1_1_cubature_1_1_symmetric_simplex_driver_3_01_shape_1_1_simplex_3_012_01_4_01_4.html',1,'FEAT::Cubature']]],
  ['synchmatrix_155',['SynchMatrix',['../class_f_e_a_t_1_1_global_1_1_synch_matrix.html',1,'FEAT::Global']]],
  ['synchmatrix_3c_20lafem_3a_3apowerdiagmatrix_3c_20mt_5f_2c_20blocks_5f_20_3e_2c_20svmt_5f_20_3e_156',['SynchMatrix&lt; LAFEM::PowerDiagMatrix&lt; MT_, blocks_ &gt;, SVMT_ &gt;',['../class_f_e_a_t_1_1_global_1_1_synch_matrix_3_01_l_a_f_e_m_1_1_power_diag_matrix_3_01_m_t___00_01bfad49e83e7d7ff93a7e81608c975bb0d.html',1,'FEAT::Global']]],
  ['synchscalarticket_157',['SynchScalarTicket',['../class_f_e_a_t_1_1_global_1_1_synch_scalar_ticket.html',1,'FEAT::Global']]],
  ['synchvectorticket_158',['SynchVectorTicket',['../class_f_e_a_t_1_1_global_1_1_synch_vector_ticket.html',1,'FEAT::Global']]],
  ['syntaxerror_159',['SyntaxError',['../class_f_e_a_t_1_1_syntax_error.html',1,'FEAT::SyntaxError'],['../class_f_e_a_t_1_1_xml_1_1_syntax_error.html',1,'FEAT::Xml::SyntaxError']]]
];
