// FEAT3: Finite Element Analysis Toolbox, Version 3
// Copyright (C) 2010 by Stefan Turek & the FEAT group
// FEAT3 is released under the GNU General Public License version 3,
// see the file 'copyright.txt' in the top level directory for details.

// includes, FEAT
#include <kernel/base_header.hpp>
#include <kernel/lafem/arch/matvecmult_bcsr_dense.hpp>

namespace FEAT::LAFEM::Arch
{
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 1, 1>(Tiny::Vector<float, 1>*, const float, const Tiny::Vector<float, 1> * const, const Tiny::Vector<float, 1> * const, const Tiny::Matrix<float, 1, 1>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 1, 1>(Tiny::Vector<float, 1>*, const float, const Tiny::Vector<float, 1> * const, const Tiny::Vector<float, 1> * const, const Tiny::Matrix<float, 1, 1>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 2, 1>(Tiny::Vector<float, 2>*, const float, const Tiny::Vector<float, 1> * const, const Tiny::Vector<float, 2> * const, const Tiny::Matrix<float, 2, 1>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 2, 1>(Tiny::Vector<float, 2>*, const float, const Tiny::Vector<float, 1> * const, const Tiny::Vector<float, 2> * const, const Tiny::Matrix<float, 2, 1>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 3, 1>(Tiny::Vector<float, 3>*, const float, const Tiny::Vector<float, 1> * const, const Tiny::Vector<float, 3> * const, const Tiny::Matrix<float, 3, 1>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 3, 1>(Tiny::Vector<float, 3>*, const float, const Tiny::Vector<float, 1> * const, const Tiny::Vector<float, 3> * const, const Tiny::Matrix<float, 3, 1>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 4, 1>(Tiny::Vector<float, 4>*, const float, const Tiny::Vector<float, 1> * const, const Tiny::Vector<float, 4> * const, const Tiny::Matrix<float, 4, 1>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 4, 1>(Tiny::Vector<float, 4>*, const float, const Tiny::Vector<float, 1> * const, const Tiny::Vector<float, 4> * const, const Tiny::Matrix<float, 4, 1>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 1, 2>(Tiny::Vector<float, 1>*, const float, const Tiny::Vector<float, 2> * const, const Tiny::Vector<float, 1> * const, const Tiny::Matrix<float, 1, 2>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 1, 2>(Tiny::Vector<float, 1>*, const float, const Tiny::Vector<float, 2> * const, const Tiny::Vector<float, 1> * const, const Tiny::Matrix<float, 1, 2>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 2, 2>(Tiny::Vector<float, 2>*, const float, const Tiny::Vector<float, 2> * const, const Tiny::Vector<float, 2> * const, const Tiny::Matrix<float, 2, 2>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 2, 2>(Tiny::Vector<float, 2>*, const float, const Tiny::Vector<float, 2> * const, const Tiny::Vector<float, 2> * const, const Tiny::Matrix<float, 2, 2>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 3, 2>(Tiny::Vector<float, 3>*, const float, const Tiny::Vector<float, 2> * const, const Tiny::Vector<float, 3> * const, const Tiny::Matrix<float, 3, 2>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 3, 2>(Tiny::Vector<float, 3>*, const float, const Tiny::Vector<float, 2> * const, const Tiny::Vector<float, 3> * const, const Tiny::Matrix<float, 3, 2>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 4, 2>(Tiny::Vector<float, 4>*, const float, const Tiny::Vector<float, 2> * const, const Tiny::Vector<float, 4> * const, const Tiny::Matrix<float, 4, 2>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 4, 2>(Tiny::Vector<float, 4>*, const float, const Tiny::Vector<float, 2> * const, const Tiny::Vector<float, 4> * const, const Tiny::Matrix<float, 4, 2>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 1, 3>(Tiny::Vector<float, 1>*, const float, const Tiny::Vector<float, 3> * const, const Tiny::Vector<float, 1> * const, const Tiny::Matrix<float, 1, 3>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 1, 3>(Tiny::Vector<float, 1>*, const float, const Tiny::Vector<float, 3> * const, const Tiny::Vector<float, 1> * const, const Tiny::Matrix<float, 1, 3>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 2, 3>(Tiny::Vector<float, 2>*, const float, const Tiny::Vector<float, 3> * const, const Tiny::Vector<float, 2> * const, const Tiny::Matrix<float, 2, 3>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 2, 3>(Tiny::Vector<float, 2>*, const float, const Tiny::Vector<float, 3> * const, const Tiny::Vector<float, 2> * const, const Tiny::Matrix<float, 2, 3>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 3, 3>(Tiny::Vector<float, 3>*, const float, const Tiny::Vector<float, 3> * const, const Tiny::Vector<float, 3> * const, const Tiny::Matrix<float, 3, 3>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 3, 3>(Tiny::Vector<float, 3>*, const float, const Tiny::Vector<float, 3> * const, const Tiny::Vector<float, 3> * const, const Tiny::Matrix<float, 3, 3>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 4, 3>(Tiny::Vector<float, 4>*, const float, const Tiny::Vector<float, 3> * const, const Tiny::Vector<float, 4> * const, const Tiny::Matrix<float, 4, 3>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 4, 3>(Tiny::Vector<float, 4>*, const float, const Tiny::Vector<float, 3> * const, const Tiny::Vector<float, 4> * const, const Tiny::Matrix<float, 4, 3>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 1, 4>(Tiny::Vector<float, 1>*, const float, const Tiny::Vector<float, 4> * const, const Tiny::Vector<float, 1> * const, const Tiny::Matrix<float, 1, 4>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 1, 4>(Tiny::Vector<float, 1>*, const float, const Tiny::Vector<float, 4> * const, const Tiny::Vector<float, 1> * const, const Tiny::Matrix<float, 1, 4>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 2, 4>(Tiny::Vector<float, 2>*, const float, const Tiny::Vector<float, 4> * const, const Tiny::Vector<float, 2> * const, const Tiny::Matrix<float, 2, 4>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 2, 4>(Tiny::Vector<float, 2>*, const float, const Tiny::Vector<float, 4> * const, const Tiny::Vector<float, 2> * const, const Tiny::Matrix<float, 2, 4>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 3, 4>(Tiny::Vector<float, 3>*, const float, const Tiny::Vector<float, 4> * const, const Tiny::Vector<float, 3> * const, const Tiny::Matrix<float, 3, 4>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 3, 4>(Tiny::Vector<float, 3>*, const float, const Tiny::Vector<float, 4> * const, const Tiny::Vector<float, 3> * const, const Tiny::Matrix<float, 3, 4>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint32_t, 4, 4>(Tiny::Vector<float, 4>*, const float, const Tiny::Vector<float, 4> * const, const Tiny::Vector<float, 4> * const, const Tiny::Matrix<float, 4, 4>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<float, std::uint64_t, 4, 4>(Tiny::Vector<float, 4>*, const float, const Tiny::Vector<float, 4> * const, const Tiny::Vector<float, 4> * const, const Tiny::Matrix<float, 4, 4>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 1, 1>(Tiny::Vector<double, 1>*, const double, const Tiny::Vector<double, 1> * const, const Tiny::Vector<double, 1> * const, const Tiny::Matrix<double, 1, 1>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 1, 1>(Tiny::Vector<double, 1>*, const double, const Tiny::Vector<double, 1> * const, const Tiny::Vector<double, 1> * const, const Tiny::Matrix<double, 1, 1>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 2, 1>(Tiny::Vector<double, 2>*, const double, const Tiny::Vector<double, 1> * const, const Tiny::Vector<double, 2> * const, const Tiny::Matrix<double, 2, 1>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 2, 1>(Tiny::Vector<double, 2>*, const double, const Tiny::Vector<double, 1> * const, const Tiny::Vector<double, 2> * const, const Tiny::Matrix<double, 2, 1>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 3, 1>(Tiny::Vector<double, 3>*, const double, const Tiny::Vector<double, 1> * const, const Tiny::Vector<double, 3> * const, const Tiny::Matrix<double, 3, 1>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 3, 1>(Tiny::Vector<double, 3>*, const double, const Tiny::Vector<double, 1> * const, const Tiny::Vector<double, 3> * const, const Tiny::Matrix<double, 3, 1>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 4, 1>(Tiny::Vector<double, 4>*, const double, const Tiny::Vector<double, 1> * const, const Tiny::Vector<double, 4> * const, const Tiny::Matrix<double, 4, 1>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 4, 1>(Tiny::Vector<double, 4>*, const double, const Tiny::Vector<double, 1> * const, const Tiny::Vector<double, 4> * const, const Tiny::Matrix<double, 4, 1>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 1, 2>(Tiny::Vector<double, 1>*, const double, const Tiny::Vector<double, 2> * const, const Tiny::Vector<double, 1> * const, const Tiny::Matrix<double, 1, 2>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 1, 2>(Tiny::Vector<double, 1>*, const double, const Tiny::Vector<double, 2> * const, const Tiny::Vector<double, 1> * const, const Tiny::Matrix<double, 1, 2>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 2, 2>(Tiny::Vector<double, 2>*, const double, const Tiny::Vector<double, 2> * const, const Tiny::Vector<double, 2> * const, const Tiny::Matrix<double, 2, 2>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 2, 2>(Tiny::Vector<double, 2>*, const double, const Tiny::Vector<double, 2> * const, const Tiny::Vector<double, 2> * const, const Tiny::Matrix<double, 2, 2>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 3, 2>(Tiny::Vector<double, 3>*, const double, const Tiny::Vector<double, 2> * const, const Tiny::Vector<double, 3> * const, const Tiny::Matrix<double, 3, 2>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 3, 2>(Tiny::Vector<double, 3>*, const double, const Tiny::Vector<double, 2> * const, const Tiny::Vector<double, 3> * const, const Tiny::Matrix<double, 3, 2>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 4, 2>(Tiny::Vector<double, 4>*, const double, const Tiny::Vector<double, 2> * const, const Tiny::Vector<double, 4> * const, const Tiny::Matrix<double, 4, 2>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 4, 2>(Tiny::Vector<double, 4>*, const double, const Tiny::Vector<double, 2> * const, const Tiny::Vector<double, 4> * const, const Tiny::Matrix<double, 4, 2>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 1, 3>(Tiny::Vector<double, 1>*, const double, const Tiny::Vector<double, 3> * const, const Tiny::Vector<double, 1> * const, const Tiny::Matrix<double, 1, 3>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 1, 3>(Tiny::Vector<double, 1>*, const double, const Tiny::Vector<double, 3> * const, const Tiny::Vector<double, 1> * const, const Tiny::Matrix<double, 1, 3>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 2, 3>(Tiny::Vector<double, 2>*, const double, const Tiny::Vector<double, 3> * const, const Tiny::Vector<double, 2> * const, const Tiny::Matrix<double, 2, 3>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 2, 3>(Tiny::Vector<double, 2>*, const double, const Tiny::Vector<double, 3> * const, const Tiny::Vector<double, 2> * const, const Tiny::Matrix<double, 2, 3>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 3, 3>(Tiny::Vector<double, 3>*, const double, const Tiny::Vector<double, 3> * const, const Tiny::Vector<double, 3> * const, const Tiny::Matrix<double, 3, 3>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 3, 3>(Tiny::Vector<double, 3>*, const double, const Tiny::Vector<double, 3> * const, const Tiny::Vector<double, 3> * const, const Tiny::Matrix<double, 3, 3>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 4, 3>(Tiny::Vector<double, 4>*, const double, const Tiny::Vector<double, 3> * const, const Tiny::Vector<double, 4> * const, const Tiny::Matrix<double, 4, 3>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 4, 3>(Tiny::Vector<double, 4>*, const double, const Tiny::Vector<double, 3> * const, const Tiny::Vector<double, 4> * const, const Tiny::Matrix<double, 4, 3>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 1, 4>(Tiny::Vector<double, 1>*, const double, const Tiny::Vector<double, 4> * const, const Tiny::Vector<double, 1> * const, const Tiny::Matrix<double, 1, 4>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 1, 4>(Tiny::Vector<double, 1>*, const double, const Tiny::Vector<double, 4> * const, const Tiny::Vector<double, 1> * const, const Tiny::Matrix<double, 1, 4>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 2, 4>(Tiny::Vector<double, 2>*, const double, const Tiny::Vector<double, 4> * const, const Tiny::Vector<double, 2> * const, const Tiny::Matrix<double, 2, 4>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 2, 4>(Tiny::Vector<double, 2>*, const double, const Tiny::Vector<double, 4> * const, const Tiny::Vector<double, 2> * const, const Tiny::Matrix<double, 2, 4>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 3, 4>(Tiny::Vector<double, 3>*, const double, const Tiny::Vector<double, 4> * const, const Tiny::Vector<double, 3> * const, const Tiny::Matrix<double, 3, 4>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 3, 4>(Tiny::Vector<double, 3>*, const double, const Tiny::Vector<double, 4> * const, const Tiny::Vector<double, 3> * const, const Tiny::Matrix<double, 3, 4>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint32_t, 4, 4>(Tiny::Vector<double, 4>*, const double, const Tiny::Vector<double, 4> * const, const Tiny::Vector<double, 4> * const, const Tiny::Matrix<double, 4, 4>* const, const std::uint32_t * const, const std::uint32_t * const, const Index, const Index, const Index);
  template void MatVecMultBCSRDense::exec_generic_impl<double, std::uint64_t, 4, 4>(Tiny::Vector<double, 4>*, const double, const Tiny::Vector<double, 4> * const, const Tiny::Vector<double, 4> * const, const Tiny::Matrix<double, 4, 4>* const, const std::uint64_t * const, const std::uint64_t * const, const Index, const Index, const Index);
} // namespace FEAT::LAFEM::Arch
