include(FetchContent)

# function(print_package_info package_name module_name)

#   FetchContent_GetProperties(Boost)
#   message(STATUS "PackageInfo ${package_name}:")
#   message(STATUS Found ${module_name} ${${module_name}_FOUND})
#   message(STATUS Populated ${module_name} ${Boost_POPULATED})
# #   if(NOT TARGET ${module_name}::${module_name})
#   if("${${package_name}_POPULATED}")
#     message(STATUS "    FetchContent with --")
#     message(STATUS "        Populated: ${${package_name}_POPULATED}")
#     message(STATUS "        Source Dir: ${${package_name}_SOURCE_DIR}")
#     message(STATUS "        Binary Dir: ${${package_name}_BINARY_DIR}")
#   else()
#     message(STATUS "    FindPackage with --")
#     message(STATUS "        Version: ${${module_name}_VERSION}")
#     message(STATUS "        Root Dir: ${${module_name}_ROOT_DIR}")
#     message(STATUS "        Include Dir: ${${module_name}_INCLUDE_DIRS}")
#     message(STATUS "        Libraries: ${${module_name}_LIBRARIES}")
#     message(STATUS "        Definitions: ${${module_name}_DEFINITIONS}")
#   endif()

#   message(STATUS ${output_string})

# endfunction()

function(print_package_info module_name)

  message(STATUS "FindPackageInfo ${module_name}:")
  if(${module_name}_VERSION)
    message(STATUS "        -- Version: ${${module_name}_VERSION}")
  endif()
  if(${module_name}_DIR)
    message(STATUS "        -- Dir: ${${module_name}_DIR}")
  endif()
  if(${module_name}_ROOT_DIR)
    message(STATUS "        -- Root Dir: ${${module_name}_ROOT_DIR}")
  endif()
  if(${module_name}_INCLUDE_DIR)
    message(STATUS "        -- Include Dirs: ${${module_name}_INCLUDE_DIR}")
  endif()
  if(${module_name}_INCLUDE_DIRS)
    message(STATUS "        -- Include Dirs: ${${module_name}_INCLUDE_DIRS}")
  endif()
  if(${module_name}_LIBRARY)
    message(STATUS "        -- Library: ${${module_name}_LIBRARY}")
  endif()
  if(${module_name}_LIBRARIES)
    message(STATUS "        -- Libraries: ${${module_name}_LIBRARIES}")
  endif()
  if(${module_name}_DEFINITION)
    message(STATUS "        -- Definition: ${${module_name}_DEFINITION}")
  endif()
  if(${module_name}_DEFINITIONS)
    message(STATUS "        -- Definitions: ${${module_name}_DEFINITIONS}")
  endif()
endfunction()