#!/bin/sh

# Usage: checkfiles file [files...]
#        if "file" is a directory, will check all *.[hc] files recursively



# check usage

usage() {

    echo "Usage: run_tests file [files...]"
    echo "(if \"file\" is a directory, run recursively all tests)"
    exit 1

}

if test -z "$1" ; then
  usage
fi

all=0;
failed=0;
rv=0
tests=$(find "$1" -type f -name '*-test')

for tst in $tests; do
  path=`echo "$tst" | sed s!/[^/]*-test!!g`;
  tst_bin=`echo "$tst" | sed s!.*/!!g`;
  grep -q -s "$tst_bin" $path/CMakeLists.txt
  rv=$?
  if [ "$rv" -eq 0 ]; then
    echo $tst:
    $tst
    rv=$?
    all=$(( $all + 1 ));
    if [ "$rv" -ne 0 ]; then
      failed=$(( $failed + 1 ));
      fnames="$fnames $tst"
    fi
fi
done

if [ "$failed" -eq 0 ]; then
  banner="All $all tests passed";
else
  banner="$failed of $all tests failed";
fi;
dashes=`echo "$banner" | sed s/./=/g`;
echo $dashes
echo $banner;
echo $dashes
if [ "$failed" -eq 0 ]; then
  exit 0
else
  echo "List of failed tests:"
  for tst in $fnames; do
    echo $tst
  done
    exit 1
fi;
