#!/bin/sh

#Usage: run_mpi binary proc_count



# check usage

usage() {

    echo "Usage: run_mpi binary"
    exit 1

}

if test -z "$1" ; then
  usage
fi
./$1 mpiproccount
procs=$?
mpiexec -n ${procs} $1 $2 $3 $4 $5 $6 $7 $8 $9
